### ISSUE TITLE
[FEATURE] invoiceDeliveryPeriod

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#1]
Vannak szolgáltatások (pl. kiterjesztett garancia), amit egy időszakban folyamatosan teljesít az eladó. Ennek megadása az xsd-ben a számlafejben van. Ez rendben is van, ha végfelhasználónak számlázunk. De mi mint disztributor, egy számlázási periódusban akár 100 ilyet is eladunk egy dealernek. Természetesen mindegyik más-más autóra vonatkozik, így más a kezdő és végdátum is. Ezért a gyűjtőszámlán a számlasorokban adjuk meg ezeket az adatokat. Ezek továbbítása az online rendszerbe additionalData-ként történik jelenleg.

Ha a NAV-nak lényeges ezen adatok ismerete és feldolgozása, akkor lehetővé kellene tenni line szinten is a megadást. Nekünk megfelel a jelenlegi megoldás is, de az nyilván nem dolgozható fel a NAV oldalán. 3 adatot adunk meg plusszban: mire vonatkozik (alvázszám), mikortól, meddig.

**Comment by NTCA-developer** [comment]
Köszönjük a felvetést! Átbeszéljük a társterületekkel, hogy megéri-e az adatot kiemelni az additionalData köréből, mert nyilván vannak pro és kontra érvek is, amiket mérlegelni kell.

**Comment by Amn3s1a2018** [comment]
Igazából kérdés, hogy mire használod a számlafeladást. Nálunk egyetlen szempont a jogszabályi megfelelőség, így ezek a mezők (invoiceDeliveryPeriodStart, invoiceDeliveryPeriodEnd) kezdetben nem is lettek implementálva. Az egyik ok – amellett, hogy nem kötelező – pont az volt, hogy tételszinten lenne értelme.

Egy ötlet erre ha szabad: a batchInvoice kiterjesztésével minden ilyen eset kezelhető. Hasonlóan ahhoz, ahogy egy számlán szerepelhet vele több invoiceReference, ha megengedjük a használatát CREATE operációnál is, az szépen le tudná írni az ilyen „egy számlán több időszak” esetet.

Annyit tennék még hozzá, hogy a batchInvoice esetén a contained invoice elemekből kivenném a productFeeSummary-t és az invoiceSummary-t – nem csak CREATE esetben, a módosítónál is lenne értelme – és a batchInvoice tagekben a felső szinten adnám meg az összesítéseket a teljes számlára.

**Comment by NTCA-developer** [comment]
Sziasztok!

Átbeszéltük a kérdést, és arra jutottunk, hogy nem szeretnénk ezért módosítani a sémán. Ez egy nagyon példás használata az additionalData használatának, ezért is hoztuk létre, de külön dedikált csomópontot nem szeretnénk a garancia adatoknak, mert úgy látjuk, hogy a séma terjengőssé tétele nincs arányban a hasznosságával.

A felvetést minden esetre köszönjük szépen. Az issue-t lezárom.
