### ISSUE TITLE
[FEATURE] TimestampType ezredmásodperc

### ISSUE THREAD

**Issue by bakter80** [nav-gov-hu/Online-Invoice#10]
**Az igény összefoglalása / Summary of the request**
.NET környezetben az "xs:dateTime" típusnál nem lehet garantálni a megadott 3 jegyű ezredmásodperc formátumot. Emiatt mindig át kell írni az XSD-ben "xs:string" a típust.

**Az általam javasolt megoldás / The solution I propose**
Elfogadhatná a 0-3 jegyű ezredmásodperc értékek bármelyikét.

**Comment by NTCA-developer** [comment]
Szia!

Ebben sajnos nem tudunk engedni. Ha nincs séma szintű megkötés, akkor a világ összes elképzelhető formátuma fog bejönni. Ha visszaemlékszel, az első verzióban nem is volt ez benne, meg is őrült tőle mindenki amikor requestSignature hiba volt, hogy akkor hány helyiértékig számol a szerver és meddig kellene a kliensnek.

A .NET-etet nem ismerem, sajnálom ha szerializációs gond van a formátummal, de a szervernek ilyen kérdésekben szilárdnak kell lennie.

Lezárhatjuk vagy folytassuk?

**Comment by bakter80** [comment]
Ha semmi másra nem lesz használva a timestamp, akkor ez se olyan vészes, de akkor is kézzel bele kell piszkálni az XSD-be.
A .NET alatt egyébként annyi történik, hogy nem írja hozzá a felesleges 0-kat, ha arra végződik. Nem tudom milyen gondot okozhat ez. Nem lehetne a vége \d{0,3} ?

**Comment by NTCA-developer** [comment]
Szia!

Ha megnézed, most is így van: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z

Nem tudom akkor, hogy ezek alapján mi a gond, segíts kérlek vagy zárjuk le az issue-t.

**Comment by geisztdavid** [comment]
bakter80 helyett válaszolnék.
A \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z helyett kérné ő a : \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{0,3}Z
Hiszen így az ezredmásodperc beküldése nem lenne kötelező. 
Mivel a .NET alatt pl. ebből: "2019-05-09T:08:54:11.200Z" ez lesz alapértelmezés szerint: "2019-05-09T:08:54:11.2Z"

**Comment by NTCA-developer** [comment]
Köszönöm @geisztdavid!

Nem figyeltem a {0,3}-at a végén. Megnézem, mit lehet tenni.

**Comment by NTCA-developer** [comment]
Sziasztok!

Átírjuk a timestamp pattern végét d{0,3}Z-re.
