### ISSUE TITLE
Adatszolgáltatás több számlát módosító okiratról típusú számlára kapott hibaüzenet

### ISSUE THREAD

**Issue by frenki649** [nav-gov-hu/Online-Invoice#1002]
Sziasztok,

ügyfelünk kiállított egy olyan számlát, mellyel több korábbi számla került módosításra. A számla a 'batchInvoice' csomópontos adatszolgáltatást használta. A számla elutasításra került, egy olyan hibaüzenettel, mely alapján egy adott tag az xml-ben nincs kitöltve. Ellenőrzéskor viszont látszódik, hogy meg van adva a kívánt érték, úgyhogy valószínűleg valamilyen más validációs probléma okozza a hibát. Ezt a transaction ID-t kaptuk vissza: 3UO3QDO248PYWJ2Y
Próbáltuk a NAV oldalán (onlineszamla.nav.gov.hu) transaction ID alapján megtalálni a beküldést, hogy hátha kiderül a probléma oka, viszont nem találja ezt a tranzakciót.

Van rá lehetőség, hogy ránézzenek erre a tranzakcióra?

Előre is köszönöm

**Comment by renced42** [comment]
Kedves @frenki649 Éles rendszert itt nem támogatunk. Ha XSD validációs hiba van, akkor biztosan hibás a beküldött XML. 
A tranzakciót azért nem találod, mert nem jut el odáig, hogy letároljon belőle a rendszer bármilyen adatot. 
Próbáljátok, meg teszt rendszeren előidézni a hibát, akkor meg tudjuk nézni.

**Comment by frenki649** [comment]
koszi, akkor megprobáljuk reprodukálni, csak nem egyszeru megszerezni az adatokat az élesrol, de akkor marad ez. Ksozonom, lezárom a ticketet.

**Comment by frenki649** [comment]
koszi, akkor megprobáljuk reprodukálni, csak nem egyszeru megszerezni az adatokat az élesrol, de akkor marad ez. Ksozonom, lezárom a ticketet.
