### ISSUE TITLE
ABORTED számla lejelentés

### ISSUE THREAD

**Issue by frenki649** [nav-gov-hu/Online-Invoice#1003]
Hello,

ügyfelünk egy számlát nem tud lejelenteni, folyamatosan az alábbi hibaüzenettel utasítja vissza a NAV.
XML contains on line: [4,825] and column: [39] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerName}'. One of '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerVatStatus}

A customerVATStatus ki van töltve, illetve vannak további számlák, amik sikeresen lejelentődnek.

Az érintett számla annyiban eltér a többitől, hogy közel 100 számla sora van. Maga az xml 3000 soros, ez alapján a 4825-ös sorjelzést a hibaüzenetben nem tudom értelmezni.

Köszi a választ előre is.

**Comment by szecsenyizoltan** [comment]
Vevő neve első karaktere micsoda?

**Comment by frenki649** [comment]
a customerName:   E ...
vatstatus: DOMESTIC

**Comment by szecsenyizoltan** [comment]
Erre a vevőre sikerült már beküldeni számlát?

**Comment by frenki649** [comment]
igen, tobb 100-at

**Comment by frenki649** [comment]
kuldjek egy transaction id-t?

**Comment by szecsenyizoltan** [comment]
Nekem ne. Én nem tudok segíteni. Ugyanolyan felhasználó vagyok, mint te.   Amire következtetni lehetett a hibaüzenetből arra rákérdeztem. 
Ilyenekre tudok gondolni még, hogy hamarabb megszakad a feltöltés, minthogy végezne vele. Nem tudom mivel tolod fel a számlákat. Én curl-t használok. Ott van erre opció (timeout).

**Comment by NTCA-supporter** [comment]
Szia @frenki649 !

Kérlek küldj egy transactionId-t a tesztrendszerből és akkor meg tudjuk nézni a konkrét beküldött XML-t.
A hibaüzenet egyébként arra utal, hogy a customerName tag előtt nem szerepel a customerVatStatus (DOMESTIC/OTHER/PRIVATE_PERSON), ami kötelező.

Üdv

**Comment by renced42** [comment]
Kedves @frenki649 Nem lehet, hogy a mezők, nem jó sorrendben vannak?
Először a customerVatData node van utána a customerName, mező itt a hiba alapján pont fordítva szerepelhetnek.

**Comment by frenki649** [comment]
jonak tunik a sorrend:
<customerInfo>
                    <customerVatStatus>DOMESTIC</customerVatStatus>
                    <customerVatData>
                        <customerTaxNumber>
                            <ns2:taxpayerId>-</ns2:taxpayerId>
                            <ns2:vatCode>-</ns2:vatCode>
                            <ns2:countyCode>-</ns2:countyCode>
                        </customerTaxNumber>
                    </customerVatData>
                    <customerName>-</customerName>
                    <customerAddress>
                        <ns2:simpleAddress>
                            <ns2:countryCode>-</ns2:countryCode>
                            <ns2:postalCode>-</ns2:postalCode>
                            <ns2:city>-</ns2:city>
                            <ns2:additionalAddressDetail>-</ns2:additionalAddressDetail>
                        </ns2:simpleAddress>
                    </customerAddress>
                </customerInfo>

a teszt rendszerbe valo áttoltésen még dolgozunk, sajnos nem egyszerű megoldani

**Comment by frenki649** [comment]
Hello,

sikerult a teszt kornyezetbe bekuldeni egy számlát, aminél hasonlo hibát kapunk:
XML contains on line: [3,127] and column: [39] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerName}'. One of '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerVatStatus}'


ez a transaction id:  3VM1JWOSBDHEEB8K 

ratudnátok nézni, hogy mi a gond vele?

Köszi

**Comment by NTCA-supporter** [comment]
Szia!
A 27-es batchIndex-ű számlánál nincs kitöltve a customerVatStatus, a többinél igén.
Ez a gond.

Üdv

**Comment by frenki649** [comment]
köszönöm a segítséget, ez volt a hiba

**Comment by frenki649** [comment]
Hello,

sikerült továbblépni a a korábbi megoldással, viszont még mindig ABORTED-ot kapok.
Nem látok hibaüzenetet. Kérhetnék további segítséget? A teszt környezetbe küldtem be.

A transactionID: 3VS25X0O5ELOFY9X

Előre is köszönöm

**Comment by NTCA-supporter** [comment]
Szia!
A 42-es batchIndexen lévő számla INVALID_INVOICE_REFERENCE hibát kapott.
BatchInvoice esetén ha egy bukik akkor minden bukik.
Üdv

**Comment by frenki649** [comment]
Szia,

nagyon köszönöm. Az élesre amikor beküldtük, akkor az ügyfél nem találta meg a számlát transaction id alapján sem. Hogyan kellett volna keresnie, hogy lássuk a számlát és a hozzá tartozó hibaüzenetet? Van ilyenkor bármi nyoma a felületen?

Üdv

**Comment by NTCA-supporter** [comment]
Szia!

Megnéztem most felületen és itt kellene látni, transactionId alapján és még batchIndex szerint is külön vannak:
![image](https://user-images.githubusercontent.com/58814216/186363576-dc7f27b2-e84c-4fcd-91c0-b8e2f70dbb06.png)

Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ezt zárom mert nincs már nyitott kérdés. Ha szükséges, nyissatok újat kérlek.
Üdv
