### ISSUE TITLE
Vevő és szállítószámlák letöltése

### ISSUE THREAD

**Issue by vivacomp** [nav-gov-hu/Online-Invoice#1004]
Eddig gond nélkül le tudtuk tölteni a NAV-hoz beküldött vevő- és szállító számlákat. Néhány napja nem megy. Történt változtatás? Segítséget kérek!

**Comment by NTCA-supporter** [comment]
Szia @vivacomp !
Ilyen jellegű változás nem történt, arról mindenképp lenne tájékoztatás.
Ha küldesz valami hibakódot vagy requestId-t teszt rendszerből akkor megnézzük szívesen.

Üdv

**Comment by vivacomp** [comment]
Köszönöm a gyors választ! Elkerülte figyelmünket a 35 napos korlát. Most már jó.

**Comment by EnokhSys** [comment]
@vivacomp ebbe a problémába már én is belefutottam kb. két hete. :-)

**Comment by NTCA-supporter** [comment]
Sziasztok! Volt egy javítás az #1005 kapcsán, lehet az megoldotta ezt is?! Kérlek nézzetek rá.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet, ha van még kérdés nyissatok újat kérlek.
Üdv
