### ISSUE TITLE
QueryInvoiceData + SCHEMA_VIOLATION

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#1005]
A request és response xml az xsd helyes, mégis schema violation van. Csak ezzel az egy számla letöltéssel van gond, a többi megy.

Éles rendszer request + response minta

request:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:QueryInvoiceDataRequest xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base">
    <header>
        <requestId>2022081516215326MA6659LBR</requestId>
        <timestamp>2022-08-15T14:24:33.803Z</timestamp>
        <requestVersion>3.0</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
    <user>
...
    </user>
    <ns2:software>
...
    </ns2:software>
    <ns2:invoiceNumberQuery>
        <ns2:invoiceNumber>5120220011249459</ns2:invoiceNumber>
        <ns2:invoiceDirection>INBOUND</ns2:invoiceDirection>
        <ns2:supplierTaxNumber>10773381</ns2:supplierTaxNumber>
    </ns2:invoiceNumberQuery>
</ns2:QueryInvoiceDataRequest>`

NAV response
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:GeneralErrorResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">
    <header>
        <requestId>2022081516215326MA6659LBR</requestId>
        <timestamp>2022-08-15T14:24:33.803Z</timestamp>
        <requestVersion>3.0</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
    <result>
        <funcCode>ERROR</funcCode>
        <errorCode>INVALID_REQUEST</errorCode>
        <message>Helytelen kérés!</message>
    </result>
    <ns2:software>
...
    </ns2:software>
    <ns2:technicalValidationMessages>
        <validationResultCode>ERROR</validationResultCode>
        <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
        <message>Request body contains on line: [-1] and column: [-1] error: [cvc-complex-type.2.4.b: The content of element 'invoice' is not complete. One of '{"http://schemas.nav.gov.hu/OSA/3.0/data":invoiceLines, "http://schemas.nav.gov.hu/OSA/3.0/data":productFeeSummary, "http://schemas.nav.gov.hu/OSA/3.0/data":invoiceSummary}' is expected.]</message>
    </ns2:technicalValidationMessages>
</ns2:GeneralErrorResponse>`

Köszönöm.

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !

Éles rendszert nem támogatunk itt, erre kérlek használd ezt:
https://nav.gov.hu/ugyfeliranytu/keressen_minket/levelkuldes/e-ugyfsz

Ha teszt környezetben tudod ezt reprodukálni, akkor nézzük.

Köszi

**Comment by EPluribusUnum** [comment]
Nem tudjuk reprodukálni, mert nem mi küldtük be a számlát, mi csak letöltenénk, nem tudjuk hogy néz ki az xml.
Az éles környezet support használhatatlan, 30 napos válaszidővel dolgoznak (szándékosan a maximális ideig kitolják a válaszidőt), és akkor sem a feltett kérdésre válaszolnak.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Mások is jelezték, sajnos nálnuk van a hiba, de nem minden számla esetén, csak egy edge case-nél.
Javítani fogjuk és jelzem majd ha teszt/éles rendszeren ott lesz.

Köszi a jelzést.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

Javítva lett a hiba, élesen is tesztelhető.

Köszi a jelzést, üdv!

**Comment by EPluribusUnum** [comment]
Teszteltem, rendben van.
