### ISSUE TITLE
HIBA: "INCORRECT_LINE_CALCULATION_LINE_UNIT_PRICE_HUF" üzenet téves jelzése.

### ISSUE THREAD

**Issue by EnokhSys** [nav-gov-hu/Online-Invoice#1006]
Kedves @NTCA-developer és @NTCA-supporter!

Rengeteg számlánál tapasztalom a tévesen küldött "**_Eltérés a számla tétel eredeti pénznemben és forintban megadott egységára között._**" hibaüzenetet, ami megnehezíti a valós figyelmeztető üzenetek megtalálását.

Ezt a figyelmeztetést azért kapjuk, mert vannak olyan számla tételek, amelyeket az eladó nem tudott kiszállítani valamilyen oknál fogva, de a tételnek szerepelnie kell a számlán, hogy a vevő lássa ezt. Ilyenkor ez a tétel a rendeléskori (vagy a hatósági) egységárral együtt szerepel a számlán, de 0 mennyiséggel, 0 nettó-, ÁFA- és bruttó értékkel. Értelemszerűen a 0 db x 112 Ft-al = 0 Ft nettó érték, tehát a tétel értékei helyesek és konzisztensek egymással.

A megoldás az lenne, ha figyelembe vennétek a mennyiséget is, tehát csak akkor küldjetek ilyen figyelmeztető üzenetet, ha a mennyiség x egységár <> nettó értékkel.

Köszönöm!

**Comment by NTCA-supporter** [comment]
Szia @EnokhSys !

Amit leírtál eset és az említett hibaüzenet eltér egymástól.
Te a darabszám * egységár = nettó feltételt írod le, de a hibaüzenet arra vonatkozik, hogy egységár * árfolyam = egységárHUF.
Tehát itt a unitPrice és unitPriceHUF nem konzisztens, ami független a mennyiségtől.

Üdv

**Comment by EnokhSys** [comment]
Szia @NTCA-supporter,

oké, megnéztem, igazad van! 
Sajnos, én is így kapom az adatokat a vállalatirányítási rendszerből, úgyhogy most beleteszek egy módosítást a feladóprogramba. 

Köszi, zártam az issuet.
