### ISSUE TITLE
[Q&A] Teszt rendszer adatszolgáltatás nem történik meg.

### ISSUE THREAD

**Issue by landigabi** [nav-gov-hu/Online-Invoice#1008]
Kiállítottam egy teszt számlát a webes felületen és az androidos alkalmazásban.
A számla elkészült, ám az adatszolgáltatás státusza: "Beküldés előtt".
Hiába frissítek, hiába várok napokat, nem történik meg az adatszolgáltatás.

Érdeklődnék, hogy ez ismert hiba vagy történt valamilyen változtatás, ami elkerülte a figyelmemet?

Köszönöm a válaszokat!

**Comment by NTCA-supporter** [comment]
Szia @landigabi !
Kérlek küldj egy adószámot és számla sorszámokat, amiknek nem történik meg az adatszolgáltatása, és így meg tudjuk nézni.
Üdv

**Comment by NTCA-supporter** [comment]
Szia!

Köszi a jelzést, az egyik kompons nem lett elindítva véletlenül a legutóbbi release-kor.
Most az első számlára ránéztem, az be lett küldve, feltehetőleg a többi is :)

Üdv

**Comment by landigabi** [comment]
Szia!

Köszönöm, igen, mindegyik számlánál megtörtént az adatszolgáltatás!
