### ISSUE TITLE
[Q&A] Magyar adószámmal rendelkező EU-s cég adatszolgáltatás

### ISSUE THREAD

**Issue by surex89** [nav-gov-hu/Online-Invoice#1010]
Sziasztok!

Egy magyar adószámmal rendelkező EU-s cégnek (jelen esetben egy romániai cég) szeretnének kiállítani egy számlát úgy, hogy a számlán a magyar adószám szerepeljen. A cég megtalálható a NAV rendszerében.

![Screenshot 2022-09-15 at 7 50 51](https://user-images.githubusercontent.com/5535637/190324868-e6d0c289-a7ee-4894-9d5e-9ff07580cf30.png)

A kérdés az lenne, hogy ilyen esetben miként kell eljárni az adatszolgáltatáskor, a cégadatokat és az adószámot tekintve? Az EU-s cég esetében a customerTaxNumber / communityVatNumber-be kerül az adószám, magyar cég esetében pedig a customerTaxNumber / taxpayerId-be.

Válaszotokat köszönöm!

**Comment by Macskafarka** [comment]
Meglátásom szerint tévút abban gondolkodni, hogy van-e EU adószáma. Van, és van még számos más azonosítója is, meg telefonszáma is.  De a számlánál csak az számít, hogy milyen gazdasági eseményt képez le a számla, Ha ez belföldi értékesítés, és van a vevőnek magyar  adószáma, akkor a vevő oldalon az ügylet adószámaként a magyar adószámot kell szerepeltetni, És irreleváns hogy egyébként van-e bármilyen más adószáma (irreleváns, hogy van-e EU adószáma, mert az csak akkor lenne használható, ha közösségi értékesítés történne). Szóval a gazdasági esemény dönti el.

**Comment by NTCA-tax** [comment]
Az esetedben a román társaságnak van egy magyar áfa regisztrációja. Amennyiben egy belföldi társaság állít ki számlát egy magyar áfa regisztrált külföldi társaságnak, akkor az belföldi ügylet lesz (hiszen ezért van az az áfa regisztráció). Tehát nem kell azzal foglalkoznod, hogy egyébként a társaság román, attól még a magyar áfa regisztráció miatt belföldi adóalany. Itt ketté kell bontani a cégjogi és adójogi megítélést, egy román társaságnak lehet számos európai tagországban adóalanyisága. Adóalanyiság szempontjából különböző országokban keletkezhet neki adott ország tekintetében belföldi ügylete.

Fontos, hogy ebben az esetben a magyar adószámával jár el, belföldi adóalanynak minősül. Közösségi adószám belföldi ügylet esetén nem releváns, hiszen belföldi ügyletről beszélünk. Ne zavarjon az, hogy van olyan belföldi adóalany, amelynek egyébként a székhelye Magyarországon kívül van...
