### ISSUE TITLE
[Q&A] A lineDiscountData az Áfa törvény melyik cikke szerint lehet releváns adat

### ISSUE THREAD

**Issue by szkomaromi-contactplus** [nav-gov-hu/Online-Invoice#1011]
A specifikáció III.2 Kötelezőségek fejezete a lineDiscountData elemet "ha releváns"-ként jelöli meg az "Áfa törvény szerint kötelező" oszlopban. Az Áfa törvény melyik cikke szerint lesz a lineDiscountData kötelező eleme az adatszolgáltatásnak?

**Comment by NTCA-tax** [comment]
Az adatszolgáltatásnak tartalmaznia kell minden olyan adatot, amely az áfa törvény szerint kötelező eleme a számlának. Az áfa törvény 169. § i) pontját ha elolvasod, akkor teljesen visszaköszön a lineDiscountData annotációja is. Amennyiben az egységár nem tartalmazza az árengedményt, akkor az alkalmazott árengedmény kötelező eleme a számlának.

**Comment by szkomaromi-contactplus** [comment]
Köszönöm, így már érthető.
