### ISSUE TITLE
[Q&A] Miért kell nullának lennie az egyenlegnek, ha egyébként jó a számlázás? INCONSISTENT_MODIFICATION_DATA_NETAMOUNT_NOT_ZERO_NORMAL

### ISSUE THREAD

**Issue by GabiSzamla77** [nav-gov-hu/Online-Invoice#1012]
Sziasztok!
INCONSISTENT_MODIFICATION_DATA_NETAMOUNT_NOT_ZERO_NORMAL üzenetet kapunk, pedig az üzleti szándék nem látszik rossznak: miért kell 0-nak lennie az egyenlegnek?
Azt kipróbáltuk, hogy a NAV-os Online Számlázóban a módosító számlát nem lehet sztornózni, hanem csak az eredetit vele együtt.

Az eset: kiállítom a számlát, majd kiderül, hogy javítani kell, ezért kiállítom a módosító számlát (régi szóval helyesbítem). Ezután rájövünk, hogy mégiscsak az első számla volt a helyes, ezért sztornózzuk (érvénytelenítjük) az első módosító számlát. Így az eredeti számla "érvényben marad"; pontosabban fogalmazva a három számla együtt képez egy egységet, számlaláncot. Tehát, az egyenlegének nem kell nullának lennie.
A módosítás a mi rendszerünkben úgy működik, hogy az eredeti számla tételsorait automatikusan mínuszolja, és fel kell vinni a jó tételeket.
Pl. 100 eFt-os számla, majd módosítása 200 eFt-osra, utána a módosítás érvénytelenítése, mert mégiscsak a 100 eFt volt a jó.

eredeti alapszámla tételsora: 100.000 Ft nettó + áfa és bruttó

első módosító számla:
1. tételsora: -100.000 Ft nettó + áfa és bruttó
2. tételsora: +200.000 Ft nettó + áfa és bruttó
Összesítve: +100.000 Ft nettó + áfa és bruttó

a módosító számla érvénytelenítése:
1. tételsora: +100.000 Ft nettó + áfa és bruttó
2. tételsora: - 200.000 Ft nettó + áfa és bruttó
Összesítve: -100.000 Ft nettó + áfa és bruttó

Mindkét számla az első alapszámlára hivatkozik, így hárman alkotnak egy számlaláncot, és így együtt érvényesek.
Az érvénytelenítő számlának pedig kapjuk a fenti WARN üzenetet.
Mi mond ellent annak, hogy a módosító számlát sztornózni lehessen?
Azt azért korlátoztuk, hogy a végtelenségig ne lehessen módosítani-sztornózni-módosítani-sztornózni...., de ezt a fenti esetet, ahol csak egy módosító, majd annak a sztornózása történik, "még bírni kellene".

A hibakezelés nem jó, vagy a gyakorlatunk szabálytalan?
Köszönöm a segítséget.

**Comment by EPluribusUnum** [comment]
@GabiSzamla77 , a NAV értelmezésében a sztornó a számla láncra vontakozik, nem önállóan a számlára. Sztornóval nem lehet egy számlát "kiütni", ahhoz helyesbíteni kell.

**Comment by Macskafarka** [comment]
@GabiSzamla77 Amit bizonylatszinten létrehozol azt meg lehet csinálni, csak rosszul adod át a NAV felé. Ugyanis amit te "sztornónak" nevezel az nem más, mint a módosító okirat hatásának módosítása 0-ra. Vagyis "Modify".  Az Áfa törvény 2008 óta szintet lépett, és elhagyta a korábbi "helyesbítő számla" fogamat, és bevezette a módosító okirat fogalmat, és ezzel együtt a számlaláncolat fogalmát. Definiálta az "érvénytelenítés"-t, amely a számlaláncolat egészére vonatkozó végeges megsemmisítés.  Ha egy módosító okirat hatását szeretnéd kiküszöbölni, és az előtte lévő bizonylatlánc állapotra visszaállni akkor  az általad sajátos szóhasználattal "módosító számla érvénytelenítése"-nek említett második 2. módosítót "Modify" jelzéssel add át a NAV fel.

**Comment by Macskafarka** [comment]
A gyakorlat a 2008 óta eltelt 14 évben nem tudta átvenni az áfa tv. logikáját, mert annyira idegen a mindennapi gyakorlattól. Van benne logika, csak évtizedeken keresztül egyedi (diszkrét) bizonylatokban gondolkodtunk.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Úgy látom itt meg lett válaszolva a kérdés (helyesen), így zárom az issuet.
Ha van még kérdés, nyissatok újat kérlek.
Üdv
