### ISSUE TITLE
[Q&A] /QueryInvoiceData request supplierInfo, customerInfo-val kapcsolatos kérdés

### ISSUE THREAD

**Issue by krisztian2** [nav-gov-hu/Online-Invoice#1013]
Üdv mindenkinek!
Azt szeretném kérdezni, hogy a QueryInvoiceData responseban a supplierInfo, customerInfo  csomóponton belül a supplierAddress, illetve a customerAddress adatok nem jönnek meg. 
Vajon mitől lehetséges?

**Comment by NTCA-supporter** [comment]
Szia @krisztian2 !

Ha a tesztrendszeren tudod reprodukálni, akkor kérlek küldj egy requestId-t vagy valamilyen azonosítót, ami alapján meg tudjuk nézni.

Üdv

**Comment by NTCA-supporter** [comment]
Szia!

Ezt a requestId-t nem találom a tesztkörnyezeten, biztosan oda küldted be?
Egyébként kipróbáltam saját tesztadatokkal és visszaadjuk rendben. Ami gondot okozhat nálad tippre, hogy a címtípus külön sémában helyezkedik el (invoiceBase) és emiatt a válaszban más namespace-t kapnak ezen adatok.
Példa response részlet:
`                    <supplierAddress>
                        <ns2:detailedAddress>
                            <ns2:countryCode>HU</ns2:countryCode>
                            <ns2:postalCode>1234</ns2:postalCode>
                            <ns2:city>VÁROS</ns2:city>
                            <ns2:streetName>Kossuth</ns2:streetName>
                            <ns2:publicPlaceCategory>út</ns2:publicPlaceCategory>
                            <ns2:number>44</ns2:number>
                        </ns2:detailedAddress>
                    </supplierAddress>`

Üdv

**Comment by krisztian2** [comment]
Elnézést, nem teszt környezetben küldtem.
Igen, gondoltam arra is. De nem ez áll fenn.

**Comment by NTCA-supporter** [comment]
Szia!

Itt csak a tesztrendszert támogatjuk, kérlek ott próbáld meg és akkor tudom nézni.

Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet, mert nem érkezett válasz. Ha van még kérdés, nyisd újra kérlek.

Üdv

**Comment by GonZOO82** [comment]
@NTCA-supporter a kérdés nálam is aktuális.

Teszt környezetben küldött számla requestId értéke: 4COGE15ZQBEFE42T

```
array:4 [▼
  "invoiceNumber" => "AC4B5DBF-0042"
  "invoiceIssueDate" => "2023-10-23"
  "completenessIndicator" => "true"
  "invoiceMain" => array:1 [▼
    "invoice" => array:3 [▼
      "invoiceHead" => array:3 [▼
        "supplierInfo" => array:4 [▶]
        "customerInfo" => array:4 [▼
          "customerVatStatus" => "DOMESTIC"
          "customerVatData" => array:1 [▼
            "customerTaxNumber" => []
          ]
          "customerName" => "adsdassdasdadsasd"
          "customerAddress" => []
        ]
        "invoiceDetail" => array:7 [▶]
      ]
      "invoiceLines" => array:2 [▶]
      "invoiceSummary" => array:2 [▶]
    ]
  ]
]
```

A supplierAddress, customerTaxNumber, customerAddress értékek üresek.
