### ISSUE TITLE
[Q&A] Hibás vevő adószám kérdés

### ISSUE THREAD

**Issue by tnagymelinda** [nav-gov-hu/Online-Invoice#1014]
Sziasztok!

Az alábbi problémával kapcsolatban szeretném megkérdezni, hogy mi a helyes eljárásrend:

Kiállítottak egy számlát, téves vevő adószámmal - jó vevő névvel és címmel, de véletlenül más adózó adószámával. Készítettek egy helyesbítő számlát hozzá, amin a vevő adószámát javították - ezt sajnos engedte a rendszer. Majd az egész számlaláncra készült egy sztornó számla a javított adószámmal. Minden adatszolgáltatást elfogatott a rendszer, a módosító számlákra csak információs üzenet jött vissza, hogy az eredeti számla vevő adószáma és a helyesbítés vevő adószáma eltér.
A probléma az, hogy így az eredeti, téves adószámon megjelenik az eredeti számla, és nincs sztornója, mivel nem az eredeti adószámra készült a sztornó számla, a NAV pedig adószámon követi nyomon az ÁFA befizetéseket és visszaigényléseket. Ilyen esetben mi a teendő?

**Comment by NTCA-tax** [comment]
Ebben a konkrét esetben túl sokat már nem lehet tenni, mivel sztornót követően befejeződött a számlalánc életútja. Ténylegesen látja a hibás adószámon szereplő vevő a számlaadat-szolgáltatást, de ezzel nem lehet mit tenni. Itt maximum annyi lehet a tanulság, hogy a hibás de létező adószámnál a számlát érvényteleníteni szükséges és nem módosítani.

Az áfa rendelkezések alapján egyébként helyes megoldás adószám hiba esetén a számla módosítás (amennyiben a vevő neve megfelelő, tehát nem téves vevőre történt a számla kiállítása). Ugyanakkor a gyakorlatban inkább több problémát okoz az ilyen jellegű számlamódosítás, és sokkal logikusabb a számlát érvényteleníteni.

Az adóhivatali ellenőrzéseknél ez nem feltétlenül jelent problémát, maximum fennakad valamilyen elemzésen, de megmagyarázható az oka.
