### ISSUE TITLE
[Q&A] helyesbítő sztornoja

### ISSUE THREAD

**Issue by kristofbela** [nav-gov-hu/Online-Invoice#1015]
Mi a helyes eljárás
1) keszítettek a egy számlát    (DONE)
2) helyesbítették  vég összeg miatt (DONE)
3) a helyesbítő számlát le stornozták  ABORTED
   A módosítás vagy érvénytelenítés olyan okiratra hivatkozik, amire vonatkozóan nem történt adatszolgáltatás.
      <originalInvoiceNumber>2022/2867</originalInvoiceNumber>  HELYESBÍTŐ számla sorszáma van mival azt stornoztam

**Comment by NTCA-supporter** [comment]
Szia @kristofbela !
Ahogy @betasofthu leírta megfelel az elvárt működésnek.
Üdv

**Comment by kristofbela** [comment]
köszönöm
