### ISSUE TITLE
[Q&A] Végleges adattörlő kód adatszolgáltatás

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#1022]
Kedves NAV-os fejlesztők, a végleges adattörlő kód adatszolgáltatása kapcsán szeretnék kérdezni.

A számlázó programban kötelező-e adatot szolgáltatni a végleges adattörlő kódról?
(Én úgy gondolom, hogy nem, mivel nincs se dedikált, se opcionális mező, az XML struktúra nem változott, csupán a termékkód és cikkszámhoz hasonlóan additionalLineData-ként lehet beküldeni, de az additionalLineData-k használata semmi esetben sem kötelező!)

Ezen az oldalon (https://nav.gov.hu/ugyfeliranytu/nezzen-utana/tudjon_rola/AATKOD_adatszolgaltatas_az_adattorlo_kodokrol) azonban ez szerepel: "Gépi számlakiállítás esetén az adatszolgáltatást a számlázó programmal **KELL** teljesíteni." Itt a KELL szót kérem alátámasztani, hogy ennek mi a jogi háttere, melyik jogszabály, rendelet írja elő, hogy "KELL"! Az adatszolgáltatás XML struktúrájában ugyanis külön mezők vannak a kötelező tartalmi elemeknek, ez pedig egyértelműen nem az és nem is biztosítható, hogy ezt az adatot a program felismerje, ha valaki egy szabadon megadható számlamegjegyzésbe csak úgy minden nélkül beilleszt egy ilyen végleges adattörlő kódot.

Ha mégis vagyok olyan rendes és foglalkozok ezzel a szerintem nem kötelező dologgal, akkor az a kérdésem, hogy mi a helyzet több mennyiség esetén? Mivel az XML példa mindenhol csak 1 db eszközre vonatkozott. Ha 3 darab ilyen eszközt adnak el a vevőnek 3 adattörlő kóddal, akkor 3 soros lesz a számla vagy lehet 1 soros 3 db mennyiséggel, és ha igen, akkor az additionalLineData-ban lehet-e több kódot is felsorolni? Pl. A10000_VEGLEGES_ADATTORLO_KOD , A10001_VEGLEGES_ADATTORLO_KOD, A10002_VEGLEGES_ADATTORLO_KOD.

Tekintettel, hogy 2023. január elsejével életbe lép a dolog, elég sürgősen várnánk a választ! Szerintem hozzám hasonlóan sokan még csak nem is hallottak erről az újabb őrültségről, mivel se a nyitott, se a lezárt témák között nem találtam.

Kellemes Ünnepeket!

**Comment by Macskafarka** [comment]
@nbeeps2 Jó hogy megtaláltad ezt! Megdöbbentő praktikákkal találkozunk. Szerintem sem kell ezzel foglalkozni, mivel az adatszolgáltatást az ÁFA tv. 10.sz melléklete és a 23/2014.sz NGM rendelet szabályozza adatmező szinten. Ezen a jogszabályok vonatkozó részei nem változtak. A többi az csak erőlködés a NAV részéről.

**Comment by nbeeps2** [comment]
@Macskafarka Közben megkerestem a végleges adattörlő kódra vonatkozó 726/2020. (XII. 31.) Korm. rendeletet: https://net.jogtar.hu/jogszabaly?docid=a2000726.kor&timeshift=20230101

9. paragrafus, 4a pontja: "a) a számlán történő rögzítéssel került sor, úgy az az általános forgalmi adóról szóló 2007. évi CXXVII. törvény (a továbbiakban: Áfa tv.) 257/G. §-a és 10. melléklete szerinti adatszolgáltatás útján,"

Viszont jó hír, hogy semmi nem kötelez arra, hogy én ezt a számlán feltüntessem, mivel a végleges adattörlő kódot bármilyen más formában is átadhatom a vevőnek.

**Comment by Macskafarka** [comment]
Ok,, hogy megtaláltad, de ez egy Korm rendelet arról, hogy a rendelet kibocsátója szerint az ÁFA tv. 257.G.§ és a 10.sz. melléklete alapján kellene beletenni a számlaadat szolgáltatásba,  Azonban ez nem az ÁFA tv előírásai szerinti kötelező adata a számlának, ezért erre NEM vonatkozik az adatszolgáltatási kötelezettség. Itt is leírta többször egyértelműen @NTCA-tax  is, hogy sokféle jogszabály ír elő a számlán kötelezően megjelenítendő adatot, az adatszolgáltatásnak azonban kizárólag csak az ÁFA tv. által előírt adattartalom a kötelező eleme. Az ÁFA tv. ezen adatot nem tartja a számla k9telező elemének.

**Comment by Macskafarka** [comment]
Az pedig elfogadhatatlan dolog, hogy az állítólagosan 2023.01.01-től életbe lépő adatszolgáltatás előtt nem hagynak kellő időt a felkészülésre sem a fejlesztőknek, sem az adóalanyoknak.  erről kellene leszokni.

**Comment by nbeeps2** [comment]
_"Azonban ez nem az ÁFA tv előírásai szerinti kötelező adata a számlának, ezért erre NEM vonatkozik az adatszolgáltatási kötelezettség"_

Igen, pontosan ezért kifogásolom , hogy a NAV az oldalán ezt így kommunikálja: ""Gépi számlakiállítás esetén az adatszolgáltatást a számlázó programmal KELL teljesíteni." Ezzel adja a lovat a felhasználó alá, aki itt veri a tam-tam-ot , hogy ezt a programnak tudnia kell...

**Comment by Macskafarka** [comment]
Egyetértek veled. A NAV visszaél azzal, hogy vannak, akik kritika nélkül veszik az ilyeneket.  Aztán lehet módosító okiratot készíteni, ha csak ezt az egyetlen adatot akarják javítani. A módosító okirat pedig, ha másik áfa időszakba esik, akkor mehet a 2365M-02-K lapra. Agyrém az egész.

**Comment by Macskafarka** [comment]
A számla befogadó pedig mihez kezd egy olyan módosító okirattal, amelyen csak ez az adat változik? Be kell rögzítenie az ERP rendszerébe, miközben egyetlen olyan adata sem módosul, ami számítana akár a folyószámla nyilvántartásban, akár a könyvelésben?

**Comment by renced42** [comment]
Kedves @nbeeps2, a "KELL" szó az adott bekezdések elején szereplő mondatra vonatkozóan szerepel vagyis:

-Ha az adattörlő kódot a pénztárgéppel kiállított nyugtán vagy egyszerűsített számlán adják át a fogyasztónak
- Ha az adattörlő kódot számlázóprogrammal kiállított számlán adják át a fogyasztónak

Azaz ha szerepel a számlán, nyugtán, egyszerűsített számlán ez az adat, akkor érdemes az adatszolgáltatásban is szerepeltetni, ezzel egyrészt teljesíti az eladó az adatszolgáltatást, másrészt nem kell más módon átadni a vevőnek a kódot.

Ha valaki nem így akarja csinálni arra is van lehetőség. Az adatszolgáltatást nyomtatványon kell akkor megoldani. 

A  A10000_VEGLEGES_ADATTORLO_KOD szöveg az fix tehát nem kell számozni mert a dataValue érték fog csak változni. 
pl:
dataName -> A10000_VEGLEGES_ADATTORLO_KOD dataValue ->1000-0000-0000-0001
dataName -> A10000_VEGLEGES_ADATTORLO_KOD dataValue ->1000-0000-0000-0002
dataName -> A10000_VEGLEGES_ADATTORLO_KOD dataValue ->1000-0000-0000-0003

Az additionalLineData bármennyiszer felvehető. 
Tehát ha 1 termékből 5 db került eladásra egy soron akkor 5x veszed fel, ha 5 soron jeleníted meg az 5 terméket akkor soronként 1 additionalLineData-t veszel fel.

**Comment by nbeeps2** [comment]
Köszönöm a választ. Azt értem, hogy nem kötelező a számlán az adattörlő kódot szerepelteteni, mert át lehet adni e-mailben is, viszont ha a felhasználó mégis ezt a számlán teszi meg, akkor "KELL" szó az én értelmezésemben azt jelenti, hogy ebben az esetben a számlázó programnak kötelezően fel kell adnia a NAV-nak. Viszont ez ellentmondásban van a 23/2014-es rendelettel. mivel abban ilyen tartalmi elem nincs előírva. 

Én úgy gondolnám, hogy ez úgy szerencsére, hogy a számlázó program vagy támogatja ezt vagy nem, ez egy opcionális dolog. Vagyis a számlázó programnak ezt az adatott NEM KELL feladni a NAV-nak, viszont ha tudja ezt a funkciót és feladja, akkor boldog lehet a felhasználó mert nem kell kézzel adatot szolgáltatni. 

Ebben kérnék tehát egy megerősítést: 

FEL KELL ADNIA A SZÁMLÁZÓ PROGRAMNAK KÖTELEZŐEN AZ ADATTÖRLŐ KÓDOT, ha az a számlán szerepel?

**Comment by renced42** [comment]
Kedves @nbeeps2 a 726/2020. (XII. 31.) Korm. rendelet alapján fel kellene adni.

**Comment by Macskafarka** [comment]
@renced A kormányrendelet nulla, mert azt übereli a számlaadatszolgáltatásnál főszabályként alkalmazandó ÁFA törvény, amely csak és kizárólag a számlának **az ÁFA törvény által előírt kötelező elemeit rendeli kötelezóen átadni.**  Illene a NAV-nak is jögkövető magatartást tanúsítania, és  erre a jogszabályra mindenkinek felhívni a figyelmét. Hogy ő ugyan szeretné, de a törvény mást ír elő. Ez lenne a feladata, a korrekt tájékoztatás.  Ide másolom az ÁFA tv. 10.sz. mellékletének 4. pontját okulásként: 
"4. A számlázási funkcióval rendelkező programmal kiállított számla, számlával egy tekintet alá eső okirat esetében az adóalany külön jogszabályban meghatározott elektronikus módon teljesít adatszolgáltatást a számla, számlával egy tekintet alá eső okirat **e törvény szerinti adattartalmáról**..."

**Comment by renced42** [comment]
Kedves @nbeeps2, ha nincs több kérdés akkor kérlek zárd az issue-t!

Köszi szépen!

**Comment by szkomaromi-contactplus** [comment]
@NTCA-tax ugyanezt az álláspontot képviselte a termékdíj lejelentésével kapcsolatban: https://github.com/nav-gov-hu/Online-Invoice/issues/998#issuecomment-1240265709. Jó lenne úgy lezárni ezt az esetet, hogy a NAV részéről valaki megerősíti, hogy valóban csak opcionális adat a végleges adattörlő kód. Ha most egy végfelhasználó ránéz erre a kérdésre, azt fogja levonni, hogy a programozók "meg akarják ezt úszni".

> @renced42 A kormányrendelet nulla, mert azt übereli a számlaadatszolgáltatásnál főszabályként alkalmazandó ÁFA törvény, amely csak és kizárólag a számlának **az ÁFA törvény által előírt kötelező elemeit rendeli kötelezóen átadni.** Illene a NAV-nak is jögkövető magatartást tanúsítania, és erre a jogszabályra mindenkinek felhívni a figyelmét. Hogy ő ugyan szeretné, de a törvény mást ír elő. Ez lenne a feladata, a korrekt tájékoztatás. Ide másolom az ÁFA tv. 10.sz. mellékletének 4. pontját okulásként: "4. A számlázási funkcióval rendelkező programmal kiállított számla, számlával egy tekintet alá eső okirat esetében az adóalany külön jogszabályban meghatározott elektronikus módon teljesít adatszolgáltatást a számla, számlával egy tekintet alá eső okirat **e törvény szerinti adattartalmáról**..."

**Comment by betasofthu** [comment]
A tájékoztató szerint:
_Az adattörlő kód utolsó karaktere mindig számjegy, ellenőrzőkód, ami lehetőséget nyújt CDV-ellenőrzésre_
Hogyan kell számolni ezt az ellenőrző kódot? Valaki meg tudná adni?
B.Ú.É.K.

**Comment by nbeeps2** [comment]
> Kedves @nbeeps2, ha nincs több kérdés akkor kérlek zárd az issue-t!

Nincs dedikált mezője az XML-ben az adatörlő kódnak, már pedig a NAV hivatalos álláspontja szerint az XML struktúra úgy van kialaktítva, hogy a kötelező adatokat kötelező kitölteni az XML-ben, a feltételesen kötelező adatoknak pedig szintén külön fenntartott mezőjük van. Ezzel szemben a végleges adattörlő kódnak nincs ilyen mezője. Az általad említet 726/2020. (XII. 31.) Korm. rendelet a 23/2014 NGM rendelet 10. számú mellékletére hivatkozik, amiben szintén nem szerepel a végleges adatörlő kód, így jogilag semmi nem támasztja alá, hogy ezt a mezőt kötelezően fel kéne adni és semmilyen jogszabály nem is írja elő, hogy a számlán ezt az adatot kötelező lenne feltüntetni a számlán.

**Comment by Macskafarka** [comment]
Arról van szó, hogy a 726/2020 Korm. rendeletben kapott a NAV egy új feladatot. Erre azt gondolta, hogy beletuszkolja a már működő  számlaadat-szolgáltatásba. Azért kell ezen ötlet ellen fellépni, mert különben máskor is lennének ilyen vad elképzelései.

**Comment by nbeeps2** [comment]
Igen, de ez így ebben a formában megvalósítva nem szabad, hogy többet jelentsen, mint mint egy KÉNYELMI FUNKCIÓ. Vagyis a számla kiállítója átadhatja ezt a végleges adattörlő kódot bárhogy a vevőnek, majd adatot szolgáltat róla a kézzel a nyomtatványon. Esetleg, ha ezt rá is írja ezt a számlára a kiállító és a számlázó program esetleg ezt kezeli, akkor ezt a számlázó program az adatszolgáltatással megteszi helyezett és megússza a nyomtatvány kézi kitöltését, de ennyi. Ha tudja, tudja, ha nem , nem. Kb. ennyi. De semmiképpen nem a KELL és KÖTELEZŐ kategória.

**Comment by Macskafarka** [comment]
Biztos vagyok benne, hogy nem az ezen a fórumon jelen lévő NAV kollégák találták ezt ki, de jószerivel ez az egyetlen valóban működő közvetlen kommunikációs csatorna, amely nem 30 nap alatt küld semmitmondó választ.

**Comment by nbeeps2** [comment]
Igen, @renced42 válaszolt technikailag, hogy a A10000_VEGLEGES_ADATTORLO_KOD -ot nem kell sorszámozni és korlátlanszor fel lehet adni, bár ez megint csak generálja a problémákat. Pl. a mennyiség 5 db, de csak 4 vagy éppenséggel 6 kódot tüntetnek fel a számlán, stb. Betasoft által feltett CDV kérdésre a válasz is még érdekelne.

Mindezek felett nctatax válaszát is szívesen venném, mert most ez a termékkód, cikkszám opcionális mező töltéssel van nálam egy súlyban, mivel ez a technikai megvalósítása is.

**Comment by renced42** [comment]
Kedves @nbeeps2 
Szerintem itt nincs probléma. 
Egyrészt adathordozóból, nem tudsz tört számot feladni, tehát 2/3 pendriveot, vagy 4/5 merevlemezt nem tudnak értékesíteni. 
Az additionalLineData felvétele nem kötelező, tehát az az eladó döntése, hogy a számla tételhez mit vesz fel vagy mit nem vesz fel és azt milyen számossággal teszi.
A lényeg az, hogy a kiadott kódokról adatot kell szolgáltatnia az eladónak. Erre pedig több lehetőség van a rendelet szerint.
Ha a számlázó program vagy a pénztárgép képes az adott információ rögzítésére és beküldésére, akkor mindenki örül. Ha nem képes rá akkor, meg nem képes rá, vagy azzá teszik, vagy az adatszolgáltatást megoldja máshogyan az eladó. Ezzel kapcsolatosan sem én sem @NTCA-tax sem fog tudni többet mondani. A lehetőségek adottak, csak alkalmazni kell őket. A CDV képzésnek utána nézek, mert az nem Online számla téma, ha meg van akkor közzé teszem.

**Comment by nbeeps2** [comment]
"Ha a számlázó program vagy a pénztárgép képes az adott információ rögzítésére és beküldésére, akkor mindenki örül. Ha nem képes rá akkor, meg nem képes rá, vagy azzá teszik, vagy az adatszolgáltatást megoldja máshogyan az eladó"

Ez így rendben van, ez azt jelentené, hogy az adatszolgáltatás opcionális. Vagy tudja a számlázó program vagy nem. Abban az esetben viszont, ha kötelező az adat feladása, mert az első post-ban említett szerint a KELL szó szerepel, onnantól kezdve nincs olyan, hogy a program ezt tudja vagy sem, hanem kötelezően tudnia kell. 

Az egész issue-nak tehát ez az alapján, hogy kell-e vagy sem. A legutóbbi válaszod alapján akkor nincs gond, ha a számlázó program nem adja fel ezt az adatot a NAV-nak, annak ellenére, hogy ezt a számla kiállítója a számlán szerepeltette. Cserébe a felhasználónak ezt az adatot a nyomtatványon keresztül kell majd elküldenie a NAV-nak.

**Comment by nbeeps2** [comment]
"Egyrészt adathordozóból, nem tudsz tört számot feladni, tehát 2/3 pendriveot, vagy 4/5 merevlemezt nem tudnak értékesíteni."
Alulbecsülöd a felhasználókat :D

**Comment by Macskafarka** [comment]
Kedves @renced42 Korrekt válasz, ami abszolut elfogadható elvárást tartalmaz. Most már csak ez lenne a kérés, hogy a NAV honlapjáról le kellene venni azt, hogy a számlázó programnak adatot KELL szolgáltatnia. Helyette olyasmit lehetne oda kiírni, amit most írtál.

**Comment by renced42** [comment]
Kedves @nbeeps2 
Az én értelmezésemben és valószínűleg a jogalkotó értelmezésében KELL, hogy tudja, de ahogy írod ha nem tudja most éppen az nem gond, majd megoldja az adatlapon az eladó az adatszolgáltatást, egyéb iránt javasolt  a programját felkészíteni rá :), ami más szempontból is, hasznos lehet később.

**Comment by renced42** [comment]
> Kedves @renced42 Korrekt válasz, ami abszolut elfogadható elvárást tartalmaz. Most már csak ez lenne a kérés, hogy a NAV honlapjáról le kellene venni azt, hogy a számlázó programnak adatot KELL szolgáltatnia. Helyette olyasmit lehetne oda kiírni, amit most írtál.

Kedves @Macskafarka 
Erre nincs ráhatásom, de jelzem az illetékesek felé.

**Comment by renced42** [comment]
> 

Kedves  @betasofthu 

Itt a számítás leírása, példával.

https://nav.gov.hu/ado/onlinepenztargepek_1417761437385/a-tartos-adathordozon-tarolt-adatok-vegleges-hozzaferhetetlenne-tetelehez-szukseges-adattorlo-kod-cdv-ellenorzese

**Comment by betasofthu** [comment]
Köszönöm!
