### ISSUE TITLE
[Q&A] QueryInvoiceDigest érvénytelen kérés

### ISSUE THREAD

**Issue by kisadizs** [nav-gov-hu/Online-Invoice#1023]
Sziasztok!

QueryInvoiceDigest kérésben, ha ékezet van, akkor a response xml-ben azt kapjuk vissza, hogy "Érvénytelen kérés!".
Amennyiben nincs ékezet, úgy a kommunikáció helyesen megtörténik.
Az ékezeten kívül, minden más ugyanolyan, helyesnek tűnik az xml.
Karakterkódolásra gyanakszunk, de a mi oldalunkon nem látszik hiba az xml-ben.

Tudtok segíteni, hogy mi lehet a baj?

Pár request header, ahol ebbe a hibaüzenetbe futottunk:
   <common:header>
      <common:requestId>20230102112550271_15025</common:requestId>
      <common:timestamp>2023-01-02T11:25:50.430Z</common:timestamp>
      <common:requestVersion>3.0</common:requestVersion>
      <common:headerVersion>1.0</common:headerVersion>
   </common:header>
   <common:header>
      <common:requestId>20230102112549602_15024</common:requestId>
      <common:timestamp>2023-01-02T11:25:49.730Z</common:timestamp>
      <common:requestVersion>3.0</common:requestVersion>
      <common:headerVersion>1.0</common:headerVersion>
   </common:header>
   <common:header>
      <common:requestId>20230102112127635_15021</common:requestId>
      <common:timestamp>2023-01-02T11:21:27.770Z</common:timestamp>
      <common:requestVersion>3.0</common:requestVersion>
      <common:headerVersion>1.0</common:headerVersion>
   </common:header>

Előre is köszi!

**Comment by renced42** [comment]
Kedves @kisadizs Ezek teszt rendszeri requestek?
Érdemes megnézni, hogy a request objektum amibe az XML-t beteszitek UTF-8 kódolásban van (tehát nem maga az XML, hanem a http request)

**Comment by kisadizs** [comment]
Kedves @renced42!

Köszönöm a tippet, a request objektum kódolásával volt a gond, sikerült megoldani.
Köszi!
