### ISSUE TITLE
Invoice Category :Aggregate a számla beküldése vagy nem 

### ISSUE THREAD

**Issue by kurucza** [nav-gov-hu/Online-Invoice#1024]
Sziasztok @NTCA-tax @NTCA-supporter  és a többi Githubos Társunk,

Először is B.Ú.É.K.
Aggregált számlával kapcsolatban lenne egy gyors kérdésem.
Egyik ügyfelünknél ellenőrzés volt és azt a jelzést kapták vissza, hogy az aggregáltként beküldött számlát, Normálként kellene küldeni. Segítsetek kérlek ebben, hogy miért nem jó az AGGREGATE Invoice Category a következő esetben: 
-	Rendelés:1
Kiszállítás:1, ahol delivery date:20220818
-	Rendelés:1
Kiszállítás:2, ahol delivery date:20220818
Van egy rendelés, amelyhez 2 kiszállítás tartozik, ugyanaz a delivery date mindkét esetben. (a delivery date, sok esetben eltérő)
  
![image](https://user-images.githubusercontent.com/60350496/210227342-752433c9-05ec-4555-b928-16e8d064f77f.png)

A lineban, a kötelezően meghatározott exchange rate és delivery date is meg van adva tételenként.
 
![image](https://user-images.githubusercontent.com/60350496/210227393-87695677-f1d7-47db-b7a7-96a50421a33f.png)

Egy több kiszállítással készült számla nem minősül aggregált számlának, függetlenül attól, hogy ugyanaz a delivery date? 
Most igaz ugyanaz a rendelés, delivery date, de több kiszállíás van akkor is. 

A példaszámláknál hasonló esetre is aggregált XML-t látok a 3.0 speckóban.

Köszönettel,
Andi

**Comment by Macskafarka** [comment]
@kurucza Lehet gyűjtőszámlát készíteni akkor is, ha ugyanaz a delivery date. Ezt az ÁFA tv. kifejezetten nevesíti is a  164.§(1) a) pontjában.  Azonban van még egy feltétel a 164.§ (1) b) pontjában: több ügyletről kell szólnia. Ráadásul a a gyűjtőszámlán ugyanaz a teljesítési dátuma minden ügyletnek, akkor mentesül a felek között a gyűjtőszámlára vonatkozó előzetes megállapodási kötelezettség alól a 164.§ (3) bekezdése alapján. Persze kérdés mi számít ügyletnek. Ha ez nyilvánvaló lenne, akkor nem élnének meg a jogászok., mert szerintem direkt hagynak nyitva ilyen dolgokat.

**Comment by kurucza** [comment]
@Macskafarka , Köszönöm a gyors válaszod. 
Abban az esetben, ha több kiszállítás tartozik egy rendeléshez, 'ügylethez', akkor NORMALként küldjük a számlát? Az én példám a 164.§ (1) b) pontot nem teljesíti, ezért nem küldhetem aggregáltként? Ráadásul még a164.§ (3) bekezdést is sértem az azonos dátumokkal?

**Comment by Macskafarka** [comment]
@kurucza Én azért nem vagyok jogforrás, de szvsz a gyűjtőszámlának teljesítenie kell a 164.§ (1) b) pontját is, de hogy teljesíti-e a konkrét eset, azt nem a számlázó programnak kell eldöntenie, hanem az ügyfélnek.  A 164.§ (3) csak azt tartalmazza, mikor kell előzetes megállapodás. Ennek szerintem kifejezettnek kell lennie, nem hallgatólagosnak. A jogalkotó azért tehette ezt bele, mert  nem tudható, hogy a számlabefogadó fel tudja-e, akarja-e dolgozni a gyűjtőszámlát, annak minden egyéb járulékos dolgaival (tételsoronkénti árfolyam, előleg betudás, árfolyam-különbözet elvezetés,  módosító okirat stb..)

**Comment by betasofthu** [comment]
Szerintem ha különböző napon teljesített számla kiállításra alapot jelentő ügyletek esetén gyűjtőszámlát kell kiállítani (már pedig ez így van), akkor az egy napon belül teljesített több ügyletről is azt kell mert az is több "számla kiállításra alapot jelentő ügylet".  A különbség csak abban van, hogy az egy napon belül teljesített ügyletekről kiállított gyűjtő számlához nem szükséges előzetes megállapodás. Én ezt olvasom ki az áfa törvényből.

**Comment by kurucza** [comment]
@betasofthu , és itt jön  képbe, amit @Macskafarka írt, hogy mi számít ügyletnek. Az én példámban egy rendelés van, különböző szállítással, de ugyanazon szállítási dátummal.

**Comment by Macskafarka** [comment]
@betasoft.hu Csak annyit tennék hozzá, hogy gyűjtőszámlát nem KELL kiállítani soha senkinek, ez csak egy lehetőség, ha a törvényi feltételek azt megengedik. Ezen belül, ha a számla tételsorainak ugyanaz a teljesítési dátuma, akkor valóban nem kell a másik fél hozzájárulása, ami egyéb esetben szükséges.  A "törvényi feltételek megengedik" kitétel között pedig bizony ott van @kurucza által is említett külön ügylet, ami nem egy egzakt megfogalmazás.

**Comment by betasofthu** [comment]
@Macskafarka, "gyűjtő számlát nem kell kiállítani" a másik lehetőség, hogy minden kiszállítást 8 napon belül külön külön számlára kell tenni. Lényeg, hogy a törvény szövegéből az látszik, hogy az ellenőrnek nem volt igaza, az egy napon belül teljesített kiszállításokról nem összevont normál számlát KELL kiállítani, hanem pont ellenkezőleg gyűjtő számlát kell kiállítani.

**Comment by kurucza** [comment]
Kedves @NTCA-tax , ezzel a kérdésemmel tudunk esetleg foglalkozni? 
Nagyon köszönöm, Andi

**Comment by NTCA-tax** [comment]
Egészen jól körbejártátok a kérdést :)

Gyűjtőszámlát ki LEHET állítani az egy napon teljesített ügyletek esetében, és ekkor nincs szükség előzetes megállapodásra. Amennyiben naptári hónapon belüli teljesítésekről történik gyűjtőszámla kiállítása, akkor már szükséges az előzetes megállapodás.

Az ügylet értelmezése már teljesen a vállalkozásnál van, nem a szoftverfejlesztőnél. Egy megrendeléshez tartozó két kiszállítás is lehet két ügylet, de tekinthető akár egy ügyletnek is. Ehhez már a konkrét megállapodást és az ügyletet kell ismerni. Technikai oldalról ugyanakkor helyes, hogy egy számlázó szoftver támogatja az egy teljesítési napon belüli gyűjtőszámla kiállítást, tehát ettől még a szoftvered jól működik. 

A lehet/kell kérdését is érdemes látni. A gyűjtőszámla kiállítása lehetőség, nem kötelezettség. A gyűjtőszámlával az értékesítő az adminisztrációs költségeit csökkentheti, ezért került bevezetésre. Ez azonban nem mindig igaz, és az elektronikus számlázással ez a hatás már nem érvényesül, de ez már nagyon messzire vezet.... Lényeg az, hogy gyűjtőszámlázni nem kötelezettség, számlát kiállítani viszont igen. Az értékesítő döntése, hogy napon belüli teljesítésekről gyűjtőszámlát állít ki, és a vevővel kötött megállapodás kérdése, hogy naptári hónapon belüli teljesítésekről gyűjtőszámla kerül-e kiállításra vagy teljesítésenként számla.

**Comment by kurucza** [comment]
@NTCA-tax , Köszönöm szépen a válaszod ! 
A lényeg, hogy jól gondolkoztunk!

@Macskafarka , @betasofthu : Nektek is köszönöm a segítséget.
