### ISSUE TITLE
[Q&A] Adószám lekérdezés

### ISSUE THREAD

**Issue by Szildiko** [nav-gov-hu/Online-Invoice#1025]
Sziasztok!

A következő technikai problémával fordulok hozzátok:
A könyvelő programunkba beépítettük, hogy a rögzítéskor használt partner adószámát ellenőrizze le a programunk a NAV online számla rendszerrel, hogy érvényes-e, jó-e az utolsó három karakter. Viszont, amikor fennakadások vannak a NAV rendszerében, akkor a meglévő hibakezelésünk nem, vagy nem jól kezeli le, ezért nem várt módon záródik be. 

Egyértelmű, hogy nekünk kell javítani, de a NAV rendszerében annyira változó, hogy mikor milyen hiba, van, hogy hiába próbálunk mesterségesen előidézni hibákat, azok nem ugyanazok, amit az éles kommunikáció során tapasztalunk. Előfordul, hogy mire érzékeljük, hogy fennáll a jelenség, mire odajutunk, hogy elkezdjük nyomozni, addigra helyre is áll a kommunikáció.

Lehet valami információt szerezni arról, hogy a NAV rendszerében lassulások, hiba jelenségek esetén milyen kommunikációt végez a rendszer? Vagy esetleg az elmúlt időszakból van-e valami hiba log, amit át lehetne tanulmányozni, hogy mikor melyiket hogyan kezeljük le?
Van-e valami javaslat, bevált módszer arra, hogyan modellezzük a nem üzemszerű leállások, hibák eseteit, illetve lehetséges/van-e valamilyen tervezhető teszt időszak a teszt környezetben, ahol ezek a hibák megvizsgálhatók lennének?

Előre is köszönök minden észrevételt!

**Comment by renced42** [comment]
Kedves @Szildiko 

A hibákról lassulásokról, üzemszünetekről az online számla portálon a hírekben tesszük ki az eseményeket, másrészt a https://nav.gov.hu/fooldal-elemei/fooldali-csempek/uzemszunet oldalon is megtalálható.

A teszt rendszeresetében ezek az információk a teszt online számla portálon jelennek meg.

"Egyértelmű, hogy nekünk kell javítani, de a NAV rendszerében annyira változó, hogy mikor milyen hiba, van, hogy hiába próbálunk mesterségesen előidézni hibákat, azok nem ugyanazok, amit az éles kommunikáció során tapasztalunk"

Mi az a hiba amit nem tudtok előidézni? Timeout, notfound, Server error stb, mind mock szerverrel előidézhető és szimulálható.

**Comment by Macskafarka** [comment]
Kedves @Szildiko! Bár a kérdésed technikai volt, de én nem technikai oldalról közelítem meg a dolgot.  A számlakiállítónak -a fordított áfás belföldi értékesítések kivételével - lényegében mindegy, hogy a vevő adószáma helyes-e, vagy létezik-e, vagy fel van-e függesztve. Ha nem jó adószám kerül rá a számlára, az csak a vevő adólevonási jogát hiúsítja meg, és majd ő fog jelentkezni, ha akar. Pl. szünetelő egyéni vállalkozás is kérhet, és kaphat számlát, és van olyan eset, hogy a szünetelés után ezt a számlát elszámolhatja.  Amúgy pedig a magyar adószám 1-8 karakterei offline is ellenőrizhetők, a benne lévő CDV szám alapján.  Szóval az adószám érvényesség lekérdezése inkább kényelmi, vagy figyelemfelhívő  funkciónak tűnik a számomra.  A számlát a vevő kérésére MINDENKÉPPEN ki kell bocsátani, az ő által bemondott adószámra, függetlenül attól, hogy a NAV érvényesnek mondja-e az adószámot (kivéve a FAD eseteket, mert ott a számlakibocsátó kockáztat ilyenkor)

**Comment by Szildiko** [comment]
Nagyon szépen köszönöm a visszajelzéseket! Programozóink megnézik a javasolt módszert. 
Kényelmi funkció, de felhasználók által szeretett kényelmi funkció, így mindenképpen szeretnénk megtartani. Számla kiállítását nem akadályozza.
