### ISSUE TITLE
[Q&A] Csoportos áfaalany infó a /queryTaxpayer operációval

### ISSUE THREAD

**Issue by JamborTimea** [nav-gov-hu/Online-Invoice#1032]
Sziasztok,

Teszteltük a  /queryTaxpayer operációt csoportos áfaalanyok esetén.

Példa adószám, amire próbáltuk: 12869996

Az eredmény:

Az adószám valid.
Az adószámhoz tartozó név: AUTONET IMPORT MAGYARORSZÁG KERESKEDELMI ÉS SZOLGÁLTATÓ KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG
További lehetséges információk az adózóról:
SimpleXMLElement Object
(
    [taxpayerName] => AUTONET IMPORT MAGYARORSZÁG KERESKEDELMI ÉS SZOLGÁLTATÓ KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG
    [taxpayerShortName] => AUTONET IMPORT MAGYARORSZÁG KF
    [taxNumberDetail] => SimpleXMLElement Object
        (
            [taxpayerId] => 12869996
            [vatCode] => 2
            [countyCode] => 44
        )

    [incorporation] => ORGANIZATION
    [vatGroupMembership] => 17783491
)

Az eredmény kapcsán két kérdésünk merült fel:

1. A [vatCode] => 2, pedig csoportos áfaalany esetén ez 4-es kéné legyen, nem?
2. A [vatGroupMembership] => 17783491 és a [vatCode], de a [countyCode] nincs megadva külön, így hogyan tudjuk, hogy mi az értéke? [vatGroupMembership] esetén a [vatCode] mindig 5? és a [countyCode]? 

Lekértem a https://nav.gov.hu/ oldalról az adatokat erre az adószámra: 12869996:
<img width="1440" alt="Screenshot 2023-01-18 at 07 43 45" src="https://user-images.githubusercontent.com/42967821/213094290-734eb4b5-e555-4617-bb32-8f3c17a1d023.png">

és a következőképpen vannak:
17783491-5-44 - 12869996-4-44
17783491-5-44 - 12869996-4-44
17783491-5-44 - 27562107-4-13

Szeretnénk beépíteni a számlakiállítás folyamatában ezt a belföldi adószám validáló operációt, viszont itt a csoportos áfaalanyok esetében nem látjuk, hogyan lehetne, mivel nem adja a megfelelő értékeket vagy én érték félre valamit a használatában.

Segítségeteket előre is nagyon szépen köszönöm!

Köszönettel,
Tímea

**Comment by burnyo** [comment]
Üdv!

Csak egy tipp: szerintem eléggé eltér a teszt és az éles NAV rendszer
adatbázisa, ez is okozhatja ezt a jelenséget. Mi is csoporttagok
vagyunk/voltunk, ott is voltak a tesztrendszerben anomáliák.


JamborTimea ***@***.***> ezt írta (időpont: 2023. jan. 18.,
Sze, 6:57):

**Comment by burnyo** [comment]
Úgy tűnik, hogy ráhibáztam: a teszt és az éles adatbázis eltér:

- Tesztrendszerből lekérdezve:

-<taxpayerData>
<taxpayerName>AUTONET IMPORT MAGYARORSZÁG KERESKEDELMI ÉS SZOLGÁLTATÓ
KORLÁTOLT FELELŐSSÉGű TÁRSASÁG</taxpayerName>
<taxpayerShortName>AUTONET IMPORT MAGYARORSZÁG KF</taxpayerShortName>
-<taxNumberDetail>
<taxpayerId>12869996</taxpayerId>
*<vatCode>2</vatCode>*
<countyCode>44</countyCode>
</taxNumberDetail>
<incorporation>ORGANIZATION</incorporation>
<vatGroupMembership>17783491</vatGroupMembership>

- Az éles NAV rendszerben pedig:

-<taxpayerData>
<taxpayerName>AUTONET IMPORT MAGYARORSZÁG KERESKEDELMI ÉS SZOLGÁLTATÓ
KORLÁTOLT FELELŐSSÉGű TÁRSASÁG</taxpayerName>
<taxpayerShortName>AUTONET IMPORT MAGYARORSZÁG KF</taxpayerShortName>
-<taxNumberDetail>
<taxpayerId>12869996</taxpayerId>
*<vatCode>4</vatCode>*
<countyCode>44</countyCode>
</taxNumberDetail>
<incorporation>ORGANIZATION</incorporation>
<vatGroupMembership>17783491</vatGroupMembership>

Imre Burnyóczki ***@***.***> ezt írta (időpont: 2023. jan.
18., Sze, 7:47):

**Comment by JamborTimea** [comment]
Kedves @burnyo köszi a gyors választ! 

Valóban az 1-es kérdésem, akkor már nem kérdés:)
A 2-es viszont továbbra is, ahogy látom, nálad élesben is csak a <vatGroupMembership> értéke van meg. Elég, ha csak ennyit tüntetünk fel a számla Csoportazonosító szám esetén, a <vatCode>, <countyCode> nem szükséges?

**Comment by burnyo** [comment]
A  online séma nem tartalmazza azokat a mezőket. Ehhez írtunk egy külön lekérdezőt, ami innen kérdezi le az értékeket:

https://nav.gov.hu/adatbazisok/adatbleker/afaalanyok/afaalanyok_egyszeru

**Comment by JamborTimea** [comment]
@burnyo értem! Köszi szépen az infókat!

**Comment by JamborTimea** [comment]
Kedves @burnyo!

Meg tudod kérlek adni az API végpontot amivel dolgoztatok, ebben az esetben: 

"Ehhez írtunk egy külön lekérdezőt, ami innen kérdezi le az értékeket:
https://nav.gov.hu/adatbazisok/adatbleker/afaalanyok/afaalanyok_egyszeru"

vagy esetleg van valahol egy leírás róla?

**Comment by burnyo** [comment]
Kedves Tímea!
Sajnos rosszul emlékeztem: korábban azt terveztük (és azt hittem, hogy elkészült), hogy ezen keresztül kérdezzük le az adatokat, de ez meghiúsult, a captcha-kkal nehezített használat miatt.
Azonban nincs is rá szükség: a /queryTaxpayer használatával le lehet kérdezni a csoportos adószámot, és visszaadja a teljes adószámot az api:
<infoDate>2022-04-01T00:00:00.000Z</infoDate>
<taxpayerValidity>true</taxpayerValidity>
-[<taxpayerData>](file:///C:/Users/iburnyoczki/AppData/Local/Temp/81fc330_2720HTML000002.xml#)
<taxpayerName>AUTONET IMPORT MAGYARORSZÁG KERESKEDELMI ÉS SZOLGÁLTATÓ KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG ÁLTAL KÉPVISELT CSOPORTOS ÁFA</taxpayerName>
-[<taxNumberDetail>](file:///C:/Users/iburnyoczki/AppData/Local/Temp/81fc330_2720HTML000002.xml#)
<taxpayerId>17783491</taxpayerId>
<vatCode>5</vatCode>
<countyCode>44</countyCode>
</taxNumberDetail>
<incorporation>ORGANIZATION</incorporation>

**Comment by JamborTimea** [comment]
Kedves @burnyo! 

Nagyon szépen köszönöm!
