### ISSUE TITLE
[DOC] AuditData/insDate

### ISSUE THREAD

**Issue by connorhu** [nav-gov-hu/Online-Invoice#1035]
**A hibás dokumentum neve / Document name containing the error**
Online_Szamla_interfesz%20specifikacio_HU_v3.0.pdf

**Oldalszám / Page number**
38. oldal

**A dokumentációs hiba leírása / Description of the documentation error**
Az uml képen jó az insdate csomópont neve, de a tag leírásnál auditData/insDate szerepel. Helyesen: auditData/insdate

**Comment by renced42** [comment]
Kedves @connorhu 
Köszönjük a jelzést javítjuk.
