### ISSUE TITLE
Webhook API

### ISSUE THREAD

**Issue by Mocsa1974** [nav-gov-hu/Online-Invoice#1039]
Tisztelt fejlesztők!

Az lenne a kérdésem, hogy a közeljövőben lesz-e lehetőség egy technikai felhasználónak beállítani egy webhook API végpontot az onlne számla rendszerben, amit a rendszer meghívna -- egy olyan payload-al ami az queryInvoiceDigest operáció válaszában is szerepel -- abban az esetben ha az adózó számára egy új számla kerül be az online számla rendszerbe?

Köszönettel,
Mocsári Péter

**Comment by renced42** [comment]
Kedves @Mocsa1974 

Jelenleg nem tervezünk ilyen funkcionalitás kialakítását.

**Comment by Mocsa1974** [comment]
Köszönöm. Akkor zárom is az Issue-t

Mocsári Péter
