### ISSUE TITLE
[Q&A] Tesztrendszer láthatóság

### ISSUE THREAD

**Issue by csandazoltan** [nav-gov-hu/Online-Invoice#1057]
Kérdésem az lenne, hogy a tesztrendszer az egy teljes értékű rendszer tesztelésre?
---

Gondolok arra, hogy ha tesztrendszerbe számlázok, az a címzett cég teszt rendszeri kapcsolatán látható lesz?

Tudok e teljes értékű küldés fogadást tesztelni, elejétől a végéig?

> Ugyancsak itt tesztelhetik a számlázó programok fejlesztői az általuk rendszer-rendszer kapcsolattal, elektronikus szabványüzenetben küldött számlaadatok fogadására szolgáló informatikai rendszert.

Én ezt a kiírást úgy értelmeztem, de gondoltam megkérdezem!

**Comment by zonehun** [comment]
Igen, mi több cégünknél is használjuk és a számlák "átmennek" egyik cégtől a másikig a teszt rendszerben is. Tehát ha kiállítok egy számlát és a teszt rendszerbe küldöm, akkor a címzett cég azt a teszt rendszerben meg is kapja - képes letölteni.
