### ISSUE TITLE
[Q&A] Pénztárgépen kiállított nyugta helyesbítése

### ISSUE THREAD

**Issue by janosnad** [nav-gov-hu/Online-Invoice#1061]
Nem technikai kérdés,inkább ÁFA törvény értelmezés, viszont annyi jó ötletet tudott már adni a közösség, hogy felvetem a problémát, hátha találkozott már ezzel valaki. 

Alapszituáció: 
- pénztárgépen történő nyugtás vásárlás történik.
- pár nap múlva a vevő bármilyen panasz alapján visszahozza az árut, és kéri vissza a pénzt.
- az eladó jóváírószámlát állít ki a számlázó rendszerből.

Könyvelő egyik része szerint a visszavételt is csak a pénztárgépen és ezáltal nyugtán lehetne  intézni, másik része szerint azonban megfelelő a jóváírószámla kiállítása. 
A felküldéssel nincs is probléma, hiszen készül egy jóváírószámla, ahol a hivatkozásban a nyugta sorszámát adják meg, és modifyWithoutMaster= TRUE-ra állítva kerül felküldésre.

Részemről egy NAV állásfoglalás kéréssel fog záródni a történet, azonban addig is szeretném körbejárni a lehetőségeket.

**Comment by Macskafarka** [comment]
Meglátásom szerint a visszavétet is nyugtán kellene elvégezni. Az áfa törvény logikája alapján nincs olyan, hogy "független jóváíró számla", maga a "jóváíró számla" szóhasználat is kicsit avíttas. Számlát módosító okirat van, és annak a minimális adattartalma van törvényileg szabályozva. Az Áfa tv. 168.§ (2) bek: szerint a módosító okirat kiállítás feltétele : "...és kétséget kizáróan az adott számlára hivatkozva, annak adattartalmát módosítja."   - Jelen esetben nem számlát módosít. Az pedig, hogy bele lehet paszírozni  egy modifyWithoutMaster= TRUE trükkel, az nem felel meg az áfa törvénynek. A kérdés az, hogy a NAV rá fog-e erre a problémára izgulni. Valószínűleg nem, mivel a termékértékesítés nyugtája miatt a vevő nem tudott élni az áfa levonási jogával (mivel ahhoz számla kellett volna). Így a kötségvetésben nem keletkezett adóhiány.

**Comment by janosnad** [comment]
Köszönöm az iránymutatást. Nagyon erős érv.  A számlával egy tekintet alá eső okirat minimális adattartalmára a  170. § (1) c) is úgy fogalmaz , hogy  "hivatkozás arra a számlára, amelynek adattartalmát az okirat módosítja;"
A gyakorlatiasságot nem keverném ide, pl: 
- pár napos bevizsgálási idő alkalmazása, 
- a vevő 300 km-ről szállítócéggel visszaküldi a hibás terméket. Majd az eladó a vételár visszautalásakor a jóváírószámlát elpostázza (a jelenlegi szokás alapján).
- stb
Természetesen a patner könyvelőjét nem fogom tudni meggyőzni (valószínűleg még egy NAV állásfoglalással sem), de legalább számomra legyen világosabb.

Kicsit nyitva hagyom a kérdést, hátha valaki tud/szeretne még hozzászólni.
