### ISSUE TITLE
[Q&A] Rendszeres API timeout

### ISSUE THREAD

**Issue by neszt** [nav-gov-hu/Online-Invoice#1063]
NAV API kommunikáció során rendszeresen timeout-ot kapunk, ami egyre több problémát okoz.

A tömeges számlázási folyamat az, hogy a számlázási tranzakcióban minden céges ügyfélnek ellenőrizzük az adószámát, hogy érvényes-e, majd kiállítjuk a számlát, a tranzakció végén pedig beküldjük a számlákat, majd rendszeresen ellenőrizzük, hogy elfogadásra kerültek-e.

Nézzünk egy 10k ügyfélbázist, 10% céges ügyféllel, kb. 1 óra alatt lemegy a számlázás, tehát 1 óra alatt 1k adószám ellenőrzést csinálunk, majd a végén 10k számlabeküldést. Jelenleg 30 percenként ütemezetten ellenőrizzük a pending számlákat, amelyeket befogadott az API, de még nem tudjuk, hogy sikeres-e az adatszolgáltatás. Ideális esetben 30 perc után az összes számla sikeresen beküldött állapotban lesz, összesen 1k+10k+10k db API kommunikációval, nagyjából 90 perc alatt.

A timeout alatt azt értem, hogy 5 mp-en belül nem kapunk választ az API-n, ez alapján:
```
1.6.6 Válaszidő, timeout
A szerver jellemzően 200ms alatti válaszidőkkel szolgál ki. A szinkronhívások blokkoló timeout értéke 5000 ms.
Kérjük, hogy kliens oldalon a fenti értéket meghaladó válaszidőt kezeljék csak időtúllépésként!
```

A számlakészítés során, ha egy céges ügyfélnek nem tudjuk ellenőrizni, hogy érvényes-e az adószáma, akkor nem engedjük a számlát kiállítani, a problémánk tehát az, hogy így a számlakiállítás során is történik ügyfélirritáció, nem csak számlabeküldés során. A számlabeküldés késlekedése se jó, de ott nyilván nem akkora baj, ha 1-2 órát késik a beküldés vagy a beküldés után elfogadás megerősítése a timeout miatt.

Az a sejtésünk, hogy a NAV az API kommunikációban egyre szigorúbb szűrést alkalmaz és bizonyos időre blokkolja az API kliens IP címet, mert túl sok kérést küldünk.

A kérdésem az, hogy jól csináljuk? Lehet ennél optimálisabban, kevesebb API kommunikációval elvégezni ezt a feladatot?

**Comment by EPluribusUnum** [comment]
"A számlakészítés során, ha egy céges ügyfélnek nem tudjuk ellenőrizni, hogy érvényes-e az adószáma, akkor nem engedjük a számlát kiállítani"

@neszt , törvény szerint TILOS számla kiállítást blokkolni azért, mert a NAV API-ja nem él/lassú. A komplett számlabeküldés folyamat az aszinkron KELL legyen.

**Comment by renced42** [comment]
Kedves @neszt 

Ha jól értelmezem az adószám ellenőrzésre nem kapsz választ időben?

**Comment by neszt** [comment]
> Kedves @neszt
> 
> Ha jól értelmezem az adószám ellenőrzésre nem kapsz választ időben?

Általánosan, bármilyen API kommunikáció során előfordul timeout, de igen, a fő probléma, ahogy írtam is, hogy ha az adószám ellenőrzés nem sikerül.

**Comment by neszt** [comment]
> "A számlakészítés során, ha egy céges ügyfélnek nem tudjuk ellenőrizni, hogy érvényes-e az adószáma, akkor nem engedjük a számlát kiállítani"
> 
> @neszt , törvény szerint TILOS számla kiállítást blokkolni azért, mert a NAV API-ja nem él/lassú. A komplett számlabeküldés folyamat az aszinkron KELL legyen.

A issue szempontjából ezt nem tartottam lényegesnek részletezni, de akkor íme:

A nyilvántartási rendszerben konfigurálható / jogosultság függő, hogy adószám érvényességének ellenőrzésének hiányában engedi-e a rendszer kiállítani számlát.

**Comment by Macskafarka** [comment]
Sosem értettem ezt a vevő adószámának ellenőrzése miatti blokkolást. Azt az adószámot kell a számlán szerepelteti, amit a vevő kér. Neki kell tudnia, hogy a számlája alkalmas-e adólevonási jogra, vagy sem. Ennyi erővel vajon a címeket miért nem ellenőrzik a számlázó programok az országos címregiszterben?  Mit tenne egy számlázó program, ha azt kapná vissza, hogy az adott településen nincs is Tulipán utca 184. ?

**Comment by EPluribusUnum** [comment]
@neszt , az adószámnak is van CDV ellenőrzése.
https://ceginformaciosszolgalat.kormany.hu/download/4/27/02000/adoszam_adoazonosito_ellenorzes_2018.pdf

**Comment by zonehun** [comment]
Mi is alkalmazzuk az adószám ellenőrzés funkciót. Már csak azért is, mert a NAV önmaga is megjeleníti ezt ajánlásaiban. Mi úgy kezeljük ezt, hogy ha érkezik értelmes válasz az adószám lekérdezésre a NAV-tól, akkor azt feldolgozzuk és hiba esetén jelzünk a felhasználónak. Ha API timeout vagy egyéb üzemzavar folytán nem érkezik NAV válasz, akkor a futás tovább megy. Azaz nem akasztjuk meg a folyamatot.

TL/DR;

Egyébként a probléma teljesen élő. Mi már nem tudjuk hová emelni a timeout limitet (cloud rendszer), hiszen a kiállítás során szinkron módon, emberi beavatkozás nélkül valós időben, azonnal kell tovább küldeni a számlákat. Az "azonnal" és "valós időben" jelenti a szinkron módot. A válaszokat természetesen már asszinkron módon várjuk.

A szinkron küldés nálunk például olyan problémát okoz, hogy beküldjük a számlát, majd a NAV API-tól timeouttal tér vissza a rendszer. Ekkor a felhasználónak lehetősége van ismételt beküldésre. Meg is teszik. Igen ám, de közben kiderül, hogy bár az első küldésnél timeout volt, a NAV mégis befogadta a számlát és már rendelt is hozzá NAV tranzakciós azonosítót. Mi történik a második küldéssel? Természetesen egy szép nagy hibát kap az ügyfél, hogy már történt adatszolgáltatás ilyen számla sorszámmal. Ekkor az ügyfélnek be kell lépnie a NAV felületére és megnéznie, hogy mi volt az eredeti küldéskor kapott NAV tranzakció azonosító, majd azt mi kijavítjuk neki a rendszerünkben. Újra lekérdezzük az adatszolgáltatás eredményét és már jön is szépen a státusz.

Ez egyébként 1-2 hónappal ezelőttig nem volt probléma. Azóta valami eltört a NAV rendszerében és naponta többször is van timeout, annak ellenére, hogy mi a dupláját alkalmazzuk a NAV sepcifikációban leírtaknak.

Szóval a probléma élő. A "valós idejű" és "azonnal" törvényi elvárások nem teszik lehetővé az asszinkron küldést, de a jelenlegi fogadó rendszer kapacitásai miatt ez időről-időre problémát fog okozni. A leginkább érintett időszak a hónap első napjai, amikor mindenki önti befelé a számlákat ;)

**Comment by szecsenyizoltan** [comment]
Adószámra az lenne a legjobb, ha napi egy dumpot felrakna akár ide a github-ra a NAV. Így lehetne lokálban használni.

Sajnos az ilyen utólagos küldésnél, jobb ötlet híján én lekérdezéssel kezdem, hogy létezik-e a számla. Utólagos küldést nem tud nálam felhasználó indítani. Azt egy fix job csinálja, ami keresi a beküldetlen vagy ellenőrizetlen számlákat. (Minden számlát lekérdezek.)
 
Nagyon sokan aszinkron küldik be  számláikat, ezt a bankkártya használat és a NAV-nál szereplő adatokból látom.

**Comment by renced42** [comment]
@szecsenyizoltan , @neszt 

Kérlek küldjetek be néhány tranzakció azonosítót és megnézzük a konkrét eseteket, akár számla, akár adószám lekérdező interfacen

**Comment by neszt** [comment]
> Kérlek küldjetek be néhány tranzakció azonosítót és megnézzük a konkrét eseteket, akár számla, akár adószám lekérdező interfacen

Request id is jó lehet? Request id minden kéréshez van, Tranzakció azonosító nincs.

**Comment by renced42** [comment]
Igen jó lesz

**Comment by neszt** [comment]
> Igen jó lesz

3 típusból az utolsó 2 db TIMEOUT-os request_id-k:
```sql
            kelt            |           operation           |           request_id
----------------------------+-------------------------------+--------------------------------
 2023-09-25 10:33:12.993+02 | QueryTaxpayerRequest          | lOS74mUG2MmDSngnEM8zSNVGDbj1A1
 2023-09-25 10:32:40.536+02 | QueryTaxpayerRequest          | 8hjJK8ZK3VuTKwFUIFPByLQvjhZafx
 2023-09-13 12:35:43.627+02 | TokenExchangeRequest          | WkS9U7Xduu7POjIbXeK30R9WOje9Cp
 2023-09-04 09:37:32.949+02 | TokenExchangeRequest          | 7G9Ojznc3ylAW0G3aU2TfhplYfLHB0
 2023-09-25 12:00:07.738+02 | QueryTransactionStatusRequest | SkEiO2qLOtjf9sJDBfJ91MY9AuE4Hx
 2023-09-25 11:30:29.885+02 | QueryTransactionStatusRequest | I0tZyI6uLsy84DiCB0AbcJ7QaIqFcU
```

**Comment by renced42** [comment]
Kedves @neszt 

Kivételesen megnézték a kollégák az éles rendszert, amit itt nem szoktunk támogatni. 
A vizsgálat alapján az alkalmazásszerverek a választ a 1 esetben is 3,5 mp alatt adták vissza, egyébként 0,5-1 mp volt a válasz idő a többi esetben. Tehát igazából nem kellene, hogy timeoutot kapjál, tehát itt valami más lesz a ludas.

**Comment by neszt** [comment]
Kedves @renced42 ,

Az összes rendszerünkön megnöveltük a timeout értékét 30 mp-re. A teljes januári hónapot vizsgáltuk, mindenhol 1 tízezrelék alá esett be a TIMEOUT-ok száma, ez így már teljesen elfogadható, zárom az issue-t.

**Comment by renced42** [comment]
Kedves @neszt 

Köszi a visszajelzést
