### ISSUE TITLE
HTTP/1.1 426 Upgrade required[DEV support]

### ISSUE THREAD

**Issue by laladisc** [nav-gov-hu/Online-Invoice#1064]
Sziasztok!

Nem tudom, hogy a tegnapi karbantartás során változott e valami a teszt rendszeren, de minden kérésre ezt a választ kapom vissza: "HTTP/1.1 426 Upgrade required". Az éles rendszeren minden megfelelően működik, a program beállításai változatlanok.

Üdv: Lajos

**Comment by renced42** [comment]
Kedves @laladisc, most próbáld kérlek.

**Comment by laladisc** [comment]
Kedves @renced42!

Ugyanazt kapom vissza, viszont valószínűleg megtaláltam a próblémát. Egy régebbi szoftverem még HTTP/1.0 protokollt használt, ami elkerülte a figyelmemet. Tudom hogy korábban volt róla szó, hogy kivezetésre kerül, és csak a HTTP/1.1 verzió lesz támogatva. Ezek szerint a teszt rendszeren, most érkezett el az ideje?

**Comment by laladisc** [comment]
Köszönöm a választ. Pedig meg voltam róla győződve, hogy a protokoll verzióval volt a probléma.
