### ISSUE TITLE
Teszt rendszer HTTP/1.1 426 Upgrade required

### ISSUE THREAD

**Issue by uicodework** [nav-gov-hu/Online-Invoice#1065]
Sziasztok!

Tegnap óta a teszt rendszeren minden kérésre "HTTP/1.1 426 Upgrade required" válasz érkezik.
Az éles rendszeren minden megfelelően működik.
Nem láttam semmi infót róla, hogy a HTTP/1.0 már nem lesz támogatva.
Van erről valahol információ, esetleg az éles rendszeren is várható ez az átállítás?

köszönöm

**Comment by laladisc** [comment]
Szia!

Tegnap én is jeleztem. Ezek szerint akkor csak nem egyedi esetről van szó.
#1064

**Comment by uicodework** [comment]
Igen láttam.
De valaki a prog.hu-n is kérdezte már.
https://prog.hu/tarsalgo/188874/adohatosagi-ellenorzesi-adatszolgaltatas-online-szamla

**Comment by renced42** [comment]
Sziasztok! Megnézzük és visszajelzek.
Csak mellékesen mi indokolja, hogy 1.0-t használtok? Javaslom az 1.1 vagy a 2.0-ra történő áttérést.

**Comment by renced42** [comment]
Kedves @uicodework  Nézd meg most kérlek.

**Comment by uicodework** [comment]
különösebb indok nincs rá, így készült el anno, és eddig működött a teszt és az éles rendszeren is
csak nem láttunk róla infót és fél napig nyomoztuk, hogy hol lehet a probléma, hogy miért nem működik a teszt

**Comment by uicodework** [comment]
Kedves @renced42 , köszönöm működik.
