### ISSUE TITLE
ManageInvoice - customerBankAccount

### ISSUE THREAD

**Issue by lifblljxri2bspm** [nav-gov-hu/Online-Invoice#1066]
Hi,
 
I am getting the below error

<message>XML contains on line: [1] and column: [1,224] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerVatData}'. One of '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerAddress, "http://schemas.nav.gov.hu/OSA/3.0/data":customerBankAccountNumber}' is expected.]</message>

I am tried to include CustomerAddress or customerBankAccountNumber. 
I have tried to include both, and I still receive the same error.

The upload is done through a test account.

The InvoiceOperation xml is attached.

Does anyone know what to do with this error?

Kind regards
Anders Hemmingsen
Procon Solution

[manageInvoice_invoice_data (2).zip](https://github.com/nav-gov-hu/Online-Invoice/files/12303401/manageInvoice_invoice_data.2.zip)

**Comment by renced42** [comment]
Dear @lifblljxri2bspm 

There is a customerName tag after customerVatStatus. The customerName tag must  follow the customerVatData tag.
