### ISSUE TITLE
[Q&A] CDV hibás létező adószám

### ISSUE THREAD

**Issue by pitfla** [nav-gov-hu/Online-Invoice#1068]
Kedves Fejlesztők!

Ma találkoztunk egy olyan adószámmal, ami CDV hibás, de létező, működő szervezeté.
Az Opten és a nav.gov.hu ÁFA alany nyilvántartója is kihozza, de az e-cégjegyzék nem és a QueryTaxpayerRequest sem találja.
15445940-2-15 NYÍRBÁTORI KEREKERDŐ ÓVODA
Mi lehet ennek az oka?
Hogyan tudunk beküldeni helyesen egy ilyen adószámra kiállított számlát?

**Comment by renced42** [comment]
Kedves @pitfla 

Szerintem ez az adószám nem CDV hibás.

**Comment by pitfla** [comment]
Úgy néz ki, hogy a mai rendszerhibák miatt volt a probléma, most már le tudja kérni a query az adószámmal a szervezetet.
Ezzel le is lehet zárni a témát vagy akár törölni is lehet.
Köszönöm!
