### ISSUE TITLE
[Q&A] töneges számla annulálás

### ISSUE THREAD

**Issue by janisoft** [nav-gov-hu/Online-Invoice#1069]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Egy új ügyfelem adatszolgáltatását szeretném a múltra vonatkozóan rendberakni. Kb. 55e számla ment be hibásan, mert a számlaszámot hibásan egy extra előtaggal küldték be eddig, ami a számlán nem szerepel. 
Az a kérdésem, hogy az egyesével történő kézi annulálás helyett van-e bármilyen akár egyedi lehetőség arra, hogy ilyen mennyiségű számla adatszolgáltatása törlésre kerüljön, és be tudjam küldeni a helyes számlaszámmal az adatszolgáltatást?

Köszönettel:
János

**Comment by NTCA-BA** [comment]
Ha a kiállított számla helyes, csak az arról beküldött adatszolgáltatás nem megfelelő, akkor az Online Számla rendszer technikai érvénytelenítés funkciójával tudják az adatszolgáltatásokat törölni. Ezt követően küldhetők be a helyes adatszolgáltatások.
A technikai érvénytelenítés kezdeményezhető interfészen keresztül, ha az Önök számlázóprogramjában van erre lehetőség. Egy tranzakcióval 100 db számlaadat-szolgáltatás technikai érvénytelenítését lehet beküldeni, majd a Szolgáltatások menüpontban az Adatszolgáltatások érvénytelenítése alpontban a tranzakciókat kijelölve egyben jóvá lehet hagyni.
Ha a számlázóprogramjukban nincsen ilyen funkció, akkor az Online Számla rendszer Kimenő számlák menüpontjában lehet egyesével elindítani a technikai érvénytelenítéseket. Az Adatszolgáltatások érvénytelenítése menüpontban viszont egyszerre több adatszolgáltatást is kijelölhetnek és jóváhagyhatnak.
A jóváhagyást követően lehet újra beküldeni a helyes számlaadat-szolgáltatásokat.

**Comment by bmatyi94** [comment]
@janisoft https://www.rsm.hu/termek/tomeges-online-szamla-xml-korrekcio

**Comment by janisoft** [comment]
Köszönöm a válaszokat! 
Időközben elkészítettük a 100db-os csomagban annulálás funkciót, és mivel a NAV felületen 50 tételt egyben ki lehet jelölni és jóváhagyni, így kimaxolva 5000db számla egy jóváhagyással annulálható. Ezzel már lehet haladni nagyobb mennyiségnél is.
