### ISSUE TITLE
[Q&A] 0%-os ÁFA kulcs 2024-től?

### ISSUE THREAD

**Issue by Szildiko** [nav-gov-hu/Online-Invoice#1071]
Sziasztok!

Szeretném kérdezni, hogy mikorra várható esetleg akár teszt rendszerben a 0%-os áfakulccsal kapcsolatos változtatások bevezetése? Van-e esély arra, hogy még törvényt módosítanak, hogy mégse áfakulcs legyen, hanem inkább adómentesség, ami az informatikai rendszerekben már járható út?

A 2023. július 14., péntek 105. számú Magyar Közlönyben jelent meg a 2023. évi LIX. törvény
a légitársaságok hozzájárulásáról és egyes adó törvények módosítása, ennek az 54. §-ban található a következő:
„(4) A 3/B. számú mellékletben felsorolt termékek eseteben az adó mértéke az adó alapjának 0 százaléka.”
_(Napilap (hetenként legalább négyszer megjelenő kiadvány))_

Az Online Számla rendszer dokumentáció 176. oldalán egyértelműen le van írva, hogy milyen kulcsok szerepelhetnek, és nincs köztük a nulla, így gondolom ennek a rendszernek is változnia kell, ha így marad a törvény.

Csak kitekintés, mert nem ennek a csoportnak a része, de az ÁFA bevallásra és az eVAT-ra is lehet kihatása, ha az ezzel kapcsolatos adóalapokat is szerepeltetni kell majd a bevallásokban.

Előre is köszönöm az információkat!

**Comment by EPluribusUnum** [comment]
xsd szinten szerencsére nincsenek definiálva a használható kulcsok, így API változás/verziószám növelés nem szükséges, a business validation-be kell csak módosítaniuk.

**Comment by Szildiko** [comment]
Érdeklődnék, hogy mikorra várható, hogy a teszt rendszerben engedélyezésre kerül a 0%-os kulcs validálása? Valamint az is kérdés, hogy tényleg 0%-os kulcs lesz-e? A pénztárgépeknél nem várnak el módosítást, ott csak az adómentes gyűjtővel kell majd beküldeni.
https://nav.gov.hu/ado/onlinepenztargepek_1417761437385/Januartol_valtozik_a_napilapok_forgalmanak_rogzitese_az_online_penztargepeken

**Comment by Macskafarka** [comment]
Szerintem az nem kérdés, hogy 0% lesz, mivel azt a már elfogadott ÁFA törvény 82.§ (4) pontja 2024.01.01-től előírja. Ezt a pontot a 2023.évi LIX. tv 54.§-a iktatta be.

**Comment by Macskafarka** [comment]
Régebben volt egy olyan szabály, hogy az ÁNYK  NAV bevallási nyomtatványokat 60 nappal korábban közzé kell tenni, hogy az adóalanyok felkészülhessenek. A 2465 ÁFA bevallás már január elején esedékes lehet azoknak, akik pl. megszűnnek. Lassan már addig nem lesz 60 nap. Szerintem a NAV a 2024.02.20-i dátumot tekinti első lehetséges bevallási határidőnek, pedig vannak, akiknél korábban kellhet.

**Comment by LeisztnerJanos** [comment]
Sziasztok!

Részünkre, mint napilap disztríbutor egyre égetőbb a kérdés, hogy miképp tudunk 2024-ben napilapot értékesíteni úgy, hogy
- a 0%-os ÁFA-t tartalmazó számlákat hiba nélkül be tudjuk jelenteni a NAV online számla rendszerébe
- a 0%-os ÁFA-t tartalmazó árbevételünk adóbevallását el tudjuk készíteni, és be tudjuk azt küldeni

További kérdésünk az, hogy a pénztárgépeken adómentesként jelentett 0%-os ÁFA-s tételek miképp lesznek a NAV oldalán kezelve az ezekhez készült adóbevallásban 0%-os ÁFA tartalmú árbevétel jelentésekkel.

2024.01.09-én több ezer számlát kell már kiállítanunk 0%-os ÁFA tartalommal. Ha addig nem lehetséges a 0%-os ÁFA tartalmú számla beküldése a NAV online számla adatbázisába, és nem szeretnénk hibára futtatni ezeket a számlákat, akkor használhatunk adómentességi oknak 'Napilap 0% ÁFA' szöveget? Ha igen, mi történik az adóbevallással, ha az már használható lesz 0 %-os ÁFA-val?

A válaszokat előre is köszönöm.

**Comment by Macskafarka** [comment]
Ha olvassa ezt valaki a jogszabályokat előkészítő csapatból, akkor az adóalanyok jogkövető magatartásának biztosítás érdekében törvényben szabályozni kellene az ilyen helyzetet. Azt, hogy hány nappal korábban kell az adóalanyoknak és a szoftverfejlesztőknek megkapniuk a szükséges információkat, interfész leírásokat stb. A törvénynek ki kell térnie arra is, hogy mi a teendő akkor, ha ez nem teljesül időben. Akkor vajon nem kell adatot szolgáltatni, mert nem tud gépi számlaadat szolgáltatásba bekerülnie a számla kiálításakor, vagy nem léphet életbe a 0%-os áfa, vagy valaki kézzel berögzíti, és ki fizeti meg ennek a költségét kinek a részére,

**Comment by SimplifiedSzamla** [comment]
Valaki kérem segítsen megérteni:

Kell-e emiatt változtatnom a NAV online számla feladáson?
Vagy az a korábbi dolog miszerint 0% áfa nem létezik, helyette (ha jól emlékszem) adómentességi indokok vannak, megmarad?

**Comment by Szildiko** [comment]
Tudom, hogy a következő nem a NAV Online rendszer problémája, csak azt nem tudom, hova fordulhatok vele.
23/2014. (VI. 30.) NGM rendelet
a számla és a nyugta adóigazgatási azonosításáról, valamint az elektronikus formában megőrzött számlák adóhatósági ellenőrzéséről
https://net.jogtar.hu/jogszabaly?docid=a1400023.ngm

Ebben szigorúan leszabályozták, hogy egyszerűsített számla esetén milyen százalékokat lehet használni. Nem találom, hogy ezt hozzáigazították-e a 2024-es áfa törvényhez. Valamint számomra az is kérdés, hogy 0% esetén az Adómentességi hivatkozás részt kell-e használni, mert én úgy gondolom, hogy nem kéne, mert nem az a kategória. Ő egy 0%-os adómérték, adótartalom.

**Comment by Macskafarka** [comment]
@LeisztnerJanos  Igen, valami olyasmi történik. Azonban ezzel számos gond van.  Az idő rövidsége nem igaz. 6 hónapja kihirdették, hogy 2024.01.01-től van 0%-os áfa. Ha erre az állami adóhatóság nincs felkészülve, akkor kezdeményezni kell a jogalkotásnál a moratóriumot, de ilyen kezdeményezésről nem hallani. Másrészt a "súvasztással" óvatosan kell bánni, mert eredményeképpen egy állami adatbázis lesz meghamisítva, ennek lehetnek jogkövetkezményei.  Annak is, aki ösztönzi (előírja, javasolja), annak is, aki megcsinálja a valótlan adatok berögzítését.  Pontosan olyan, mintha a 27%-os áfába "súvasztaná" valaki be a 18%-os áfás tételeket.  Harmadrészt hogyan fogja a NAV az OPG-ből érkezett összesúvasztott áfa kulcsokból előállítani az OSZ-ből letölthető 0% és adómentes pénztárgéppel kiállított egyszerűsített számlákat? Negyedrészt ha eÁFA bevallást készít a számlabefogadó, aki 0%-osnak jelöli, de a NAV adómentesnek jelöli, akkor  WARN -t fog kapni. Tehát az kap figyelmeztetést, aki megfelel a törvénynek. Ötödrészt a Számlaadat szolgáltatásban sem lehet jelenleg 0%-os kulccsal beküldeni számlákat, mert ERROR miatt a befogadás meghíúsul. Miközben törvényi kötelezettség a gépi adatszolgáltatás, mulaszt az, aki betartja a törvényeket.  Szóval elég nagy a probléma.

**Comment by LeisztnerJanos** [comment]
Nem értek egyet a tapasztalt eljárással, egyetértek a felsorolt hibáival. Mindössze leírtam, hogy miképp döntöttek pénztárgép ügyben.

**Comment by Macskafarka** [comment]
Jogilag mindegy, hogy az 5%-bam vagy a 18%-bam vagy az adómentesbe teszik.  Hamis magánokirat készül tudottan.

**Comment by Macskafarka** [comment]
Lezárhatjuk, csak jelezni akartam, hogy nagyobb a baj, mint elsőre gondolnánk. Ha pl. a hipermarketben vásárol valaki 51 tételt, amelyből 50 tétel 27%-os áfa kulcsú, és 1 tétel 0%-os, de ez az 51. sor adómentesként jelenik meg a számlán, akkor a szála tudottan hamis magánokirat volta miatt semmilyen áfa levonási jog nem gyakorolható (a 27%-os tételekre sem), sőt még költségként sem számolható el ez a bizonylat egyetlen sora sem.

**Comment by renced42** [comment]
> Lezárhatjuk, csak jelezni akartam, hogy nagyobb a baj, mint elsőre gondolnánk. Ha pl. a hipermarketben vásárol valaki 51 tételt, amelyből 50 tétel 27%-os áfa kulcsú, és 1 tétel 0%-os, de ez az 51. sor adómentesként jelenik meg a számlán, akkor a számla tudottan hamis magánokirat volta miatt semmilyen áfa levonási jog nem gyakorolható (a 27%-os tételekre sem), sőt még költségként sem számolható el ez a bizonylat egyetlen sora sem.

Kedves @Macskafarka  csak szeretném jelezni halkan, hogy a 0%- os áfa és az adómentesség nem egy fogalom.

**Comment by LeisztnerJanos** [comment]
> > Lezárhatjuk, csak jelezni akartam, hogy nagyobb a baj, mint elsőre gondolnánk. Ha pl. a hipermarketben vásárol valaki 51 tételt, amelyből 50 tétel 27%-os áfa kulcsú, és 1 tétel 0%-os, de ez az 51. sor adómentesként jelenik meg a számlán, akkor a számla tudottan hamis magánokirat volta miatt semmilyen áfa levonási jog nem gyakorolható (a 27%-os tételekre sem), sőt még költségként sem számolható el ez a bizonylat egyetlen sora sem.
> 
> Kedves @Macskafarka csak szeretném jelezni halkan, hogy a 0%- os áfa és az adómentesség nem egy fogalom.

Pontosan, bár szerintem ezt az itt felszólalók mind értik is. Az, hogy a pénztárgépeken mentesként lett kezelve, @Macskafarka által és @omachtandras felvetett problémákat vonzza magával.

**Comment by SimplifiedSzamla** [comment]
Akkor ez csak pénztárgép változás, számlázó programból történő számla feladás ugyanúgy működik tovább?

**Comment by Macskafarka** [comment]
Kedves @SimplifiedSzamla , a  számlázó programoknak lehetővé kell tenni a 0%-os áfa kulcs alkalmazhatóságát. És ezt a számlát is fel kell küldeni a NAV-nak haladéktalanul. Erre a NAV ERROR-t fog küldeni, és a számla befogadást megtagadja, Így a számlalkibocsátó nem teljesítette a törvényben leírt adatszolgáltatási kötelezettségét, ami miatt számlánként akár több százezer Ft-ra is megbírságolható.  Ha megbírságolják, akkor vagy kifizeti a bírságot, vagy jogorvoslattal él a bíróságon. Ekkor azonban neki azt kell bizonyítania, hogy ő megtett mindent, amit a törvények előírnak. A bíróság arról fog dönteni, hogy elég-e a törvények betartása ahhoz, hogy valaki mentesüljön a bírság alól, vagy ekkor is megbírságolható, mivel a törvény nem szabályozza azt az esetet, amikor a hatóság hibájából nem teljesíthet a számlaadat-szolgáltatás.

**Comment by Macskafarka** [comment]
Jelenleg a NAV által szolgáltatásként nyújtott Online Számlázó program jais képtelen a 0%-os áfa kulcs kezelésére.

**Comment by Macskafarka** [comment]
A birságolási példát akár adózónként és számlánként is el lehet játszani, a hatóság döntésétől függően.

**Comment by SimplifiedSzamla** [comment]
Kedves @Macskafarka, köszönöm! Nem sírok, csak esik az eső.

Kérhetnék megerősítést ezzel kapcsolatban NAV-tól is?

Jó lenne mielőbb tudni, hogy év végéig milyen változtatásokat kell végrehajtani és kitelepíteni az ügyfelekhez.

**Comment by topybear** [comment]
A NAV mindkét problémát meg tudja oldani egy verzióváltással január első napjának hajnalán.

**Comment by LeisztnerJanos** [comment]
Nem ártana tudni, hogy a NAV megoldása igényel-e fejlesztést a számlakibocsájtóknál. Illetve mi gondos üzemeltetőként tesztelni is szoktunk, még ha nincs is ismert változás, akkor is.

**Comment by Szildiko** [comment]
Köszi szépen, hogy kihoztátok a doksiban, hogy 0 értéket kell írni a vatpercentage-be és a vatcontentbe. Nem szeretnék telhetetlennek tűnni, de van arról információ, hogy a teszt rendszerbe mikor engedélyezitek a beküldést? :)
Szeretném teljeskörűen letesztelni a programunk működését, mielőtt átadom az ügyfeleknek.
![kép](https://github.com/nav-gov-hu/Online-Invoice/assets/110169214/c61ba909-cbb1-494a-b814-f9e9336ee7ca)

**Comment by renced42** [comment]
> Nem szeretnék telhetetlennek tűnni, de van arról információ, hogy a teszt rendszerbe mikor engedélyezitek a beküldést? :)

Kedves @Szildiko várhatóan 2023.12.11-i héten.

**Comment by Szildiko** [comment]
A teszt rendszer már fogadja a 0%-os számlákat.
