### ISSUE TITLE
[Q&A] Adószám lekérdezés folyamatosan problémás

### ISSUE THREAD

**Issue by Szildiko** [nav-gov-hu/Online-Invoice#1075]
Sziasztok!

Szeretnék érdeklődni, hogy nem lehetne a NAV oldaláról megtámogatni erőforrásokkal az adószám lekérdezés funkciót? Akár hó eleje van (számlázás), akár hóközepe van (áfa bevallás) az éles rendszer küszködik, olyan mintha nem bírná el az adószámok ellenőrzését. Az ügyfelek szeretnék helyes adatokkal teljesíteni az adatszolgáltatást, ezért használnák ellenőrzésre, hogy érvényesek-e a partner adatok, de kénytelenek vagyunk azt mondani, hogy kapcsolják ki az ellenőrzést, mert lassítja például az áfa beküldés folyamatát.

Ez jó és hasznos funkció lehetne, de ilyen minőségben senki nem fogja használni hosszú távon.

![kép](https://github.com/nav-gov-hu/Online-Invoice/assets/110169214/4da4c42c-b431-46f8-9fa7-8a0877b43db5)

**Comment by renced42** [comment]
Kedves @Szildiko 

Dolgozunk a problémán remélhetőleg hamarosan kimegy az a módosítás ami ezt a problémát megoldja.

Köszönjük  a türelmet.

**Comment by mnbk** [comment]
hát nem sikerült

**Comment by connorhu** [comment]
Nem azt mondták, hogy működni fog, csak azt, hogy megy ki módosítás.

**Comment by nbeeps2** [comment]
Sajnos már három napja nem működik megfelelően a számla állapotok lekérdezése. Folyamatos időtúllépés van. Ma is egész nap ez van. Mikor lesz vége a karbantartásnak?

**Comment by vivacomp** [comment]
Örülnék, ha a NAV-os rendszergazda/fejlesztő mondana valamit a fentiekre, pl. .... nem tudjuk megcsinálni, kapcsoljátok ki az adószám validálást......   vagy valami ilyesmit.

**Comment by nbeeps2** [comment]
Az adószám lekédezésnél még sokkal-sokkal nagyobb probléma, hogy a beküldött számlák státuszát nem lehet lekérdezni, így nem lehet tudni, hogy sikeres vagy sikertelen az adatfeldolgozás.

**Comment by nbeeps2** [comment]
A queryTransactionStatus  ma sem működik! S.O.S megoldásra lenne már szükség, napok óta nem működik a funkció!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Olvassa ezt valaki illetékes????????????????????????

**Comment by EPluribusUnum** [comment]
@nbeeps2 , **nem kötelező** a NAV adószám lekérdezés használat, miért nem veszitek egyszerűen ki a programból? 3 évvel ezelőttig mindenki megvolt nélküle.
Most el vannak foglalva eVAT-tal. Lehet pont az áll a szolgáltatáskiesés mögött hogy beröffentették a teszt rendszert abból.

**Comment by nbeeps2** [comment]
Felháborító, hogy a NAV Online számla oldalon 12.12-i az utolsó hír ennek kapcsán (kapcsolódási problémák és lassulás tapasztalható). A 1819-et nem lehet felhívni, mert ha az Online számla menüpontot hívja valaki visszadob a főmenübe. Egy vicc az egész! A számlázó program fejlesztőkön csattan az egész, mindenki minket hívogat!

**Comment by nbeeps2** [comment]
> @nbeeps2 , **nem kötelező** a NAV adószám lekérdezés használat, miért nem veszitek egyszerűen ki a programból? 3 évvel ezelőttig mindenki megvolt nélküle. Most el vannak foglalva eVAT-tal. Lehet pont az áll a szolgáltatáskiesés mögött hogy beröffentették a teszt rendszert abból.

Rohadtul nem érdekel az adószám lekérdezés ;) Nem működik a beküldött számlák státuszának lekédezése egyáltalán napok óta!!!! Ez a gondom!

**Comment by EPluribusUnum** [comment]
@nbeeps2 , akkor rossz helyre szóltál hozzá. "[Q&A] Adószám lekérdezés folyamatosan problémás" ez a topic.

Amúgy mért érdekel hogy problémás bármilyen szinten a NAV szolgáltatás? A számlabeküldés/lekérdezés folyamat teljesen automatizált és aszinkron kell hogy legyen, user nem kell hogy lásson belőle semmit. Majd az automata beküldi/feldolgozza amikor tudja.

**Comment by szecsenyizoltan** [comment]
@nbeeps2 Érdemes lenne újragondolni a logikát, ha ez gondot okoz. Ugyanis, ha ez gondot okoz, akkor a rendszered is gondot okozhat a NAV szervereinek.

**Comment by renced42** [comment]
Kedves Fejlesztő Kollégák!

A problémát mi is érzékeljük és látjuk, folyamatosan dolgozunk a probléma megoldásán. Sajnos ti csak azt látjátok, hogy a NAV rendszer milyen hulladék, meg nem működik, de mi meg belülről látjuk, hogy van kiszolgálás.
A mai napon kiteszünk egy release-t, ami nem leállásos lesz. 

Köszönjük a türelmet, higgyétek el mi sem vagyunk könnyű helyzetben. Egy ekkora rendszerben nem lehet egyszerűen bármilyen módosítást csak úgy elvégezni.

**Comment by nbeeps2** [comment]
Kedves renced42, én nem gondolom, hogy a rendszeretek egy hulladék. Maximális együttérzésem, ha megy, akkor jól megy. Az elmúlt hónapokban kicsit több volt a leállás a szokásosnál az tény. A probléma a kommunikációval van. A NAV Online Számla oldalon minden nap kommunikálni kellett volna, hogy igen lassulás van, és még mindig dolgozunk rajta, ehelyett 3 nappal ezelőtti az utolsó post. Az ügyfeleket meg nekünk kell győzködni, hogy higyjék már el, hogy nem a program a rossz, hanem a NAV nem igazolja vissza a számlák beküldését.

**Comment by omachtandras** [comment]
> A probléma nem oldódik meg!

Éjszaka sem? Ránéztem most gyorsan egy olyan adatbázisra, ahol nagy mennyiségű számlát állítanak ki napközben. Tegnap este 22 után az utolsó számlára is le tudtuk kérni az állapotot.

(A legrosszabb eset egy 11:46kor kiállított számla volt, ez a 20. kérésre kapott választ. Nálunk elsőre 15 perccel a beküldés után kérdezünk vissza, majd egyre ritkábban, hogy ne terheljük a NAV oldalát, ha baj van. A 20. bekérdezés 10 óra 19 perccel a beküldés után történt, ekkor kapott választ.)

**Comment by nbeeps2** [comment]
Este nem próbáltam, reggel még nem működött. Renced42 postja után 1-2 perccel rá kezdett működni, most mindenre jött válasz a belső számlázási rendszerünkben és a vanenav oldalon is minden ok most, az adószám lekédezés funkció is.

**Comment by omachtandras** [comment]
> A probléma a kommunikációval van.

Igen, ez a probléma. Én pl. tegnap hallgattam végig egy könyvelőt, aki a számlatömbös számlákat szerette volna felrögzíteni. Akárhányszor próbálta, eljutott odaáig, hogy a logikai ellenőrzést kérte, de ott olyan szinten kiakadt a rögzítő felület, hogy a gombok elérhetetlenné váltak. Kuka minden bevitt adat, újrakezdés. De sehol nem volt kint egy figyelmeztetés, hogy ha lehet, akkor ne most akarja rögzíteni, mert vélhetően nem fog sikerülni, próbálja később, kitoljuk a határidőt egy nappal, stb.
Állítása szerint 2 órát szúrt el rá, mire feladta.

Lehet mondani, hogy rájöhetett volna előbb is, hogy nem megy, de másrészről ott a kötelezettség, hogy rögzíteni kell, ha nincs egyértelmű jelzés, hogy a probléma lehet a NAV oldalán is, akkor az, aki meg akar felelni a törvényeknek nem fogja elfogadni ezt a lehetőséget az utolsó pillanatig...

**Comment by Macskafarka** [comment]
Az egész onnantól el van rontva, hogy csak a sikeres beküldés számít teljesített adatszolgáltatásnak, miközben a NAV feldolgozásra (annak sebességére, eredményére) nulla ráhatása van a számlakiállítónak. Ráadásul a NAV van megbízva a büntik kiszabásával is. Egyszerre hatóság és szolgáltató. Hatóságként ellenőriz és büntet, szolgáltatóként közreműködik az adóalany jogszabályi tejesítésében.  Skrizofrén helyzet. Ha nem teljesült SIKERESEN  az adatszolgáltatás, kötelessége lenne megbüntetni a számla kiállítókat (az összeset) , akik aztán perelhetik a NAV-ot az időben nem teljesített feldolgozásért, és igazolhatják, hogy olyan szoftvert használnak, amelyik megfelelt minden jogszabályi elvárásnak, és megtett mindent a sikeres adatbeküldés érdekében. Ez agyrém.

**Comment by renced42** [comment]
Kedves Fejlesztő Kollégák!

Most jeleztek vissza, hogy kiment a release, de úgy látom, hogy @nbeeps2 már látja is a változást....köszi

**Comment by nbeeps2** [comment]
> Kedves Fejlesztő Kollégák!
> 
> Most jeleztek vissza, hogy kiment a release, de úgy látom, hogy @nbeeps2 már látja is a változást....köszi

Igen, köszönjük, szuper lett!

**Comment by renced42** [comment]
> Igen, köszönjük, szuper lett!

Remélem így is marad :)

**Comment by renced42** [comment]
@EPluribusUnum, @Macskafarka, @omachtandras @vivacomp, @connorhu, @Szildiko, @mnbk 
Majd nézzétek meg ti is, hogy nálatok is rendben lett-e.

Köszi!

**Comment by vivacomp** [comment]
Nálunk most rendben működik, ez lenne a természetes.

**Comment by omachtandras** [comment]
Én is ellenőriztem a korábban említett db-t, jelenleg nincs olyan számla, amire már bekérdeztünk és nem kaptunk volna választ.
Viszont a szolgáltatás log szerint van még timeout queryInvoiceDigest és queryTransactionList esetén

[WARN] 2023.12.15 10:02:33,273 - "DownloadThread (database: xxxxx; taxNumber: xxxxxxxxx)" - Supplier invoice list request failed, reduce insDate interval to: 21 sec. (java.net.SocketTimeoutException: SocketTimeoutException invoking https://api.onlineszamla.nav.gov.hu/invoiceService/v3/queryInvoiceDigest: Read timed out
(ProcessingException))
[EXT_ERROR] 2023.12.15 10:02:33,612 - "UploadThread (database: yyyyy; taxNumber: yyyyyyyy)" - java.net.SocketTimeoutException: SocketTimeoutException invoking https://api.onlineszamla.nav.gov.hu/invoiceService/v3/queryTransactionList: Read timed out
(ProcessingException)

**Comment by sinick2** [comment]
Timeout queryInvoiceData-ra is van. 

(Egyszerűsített számlák esetén queryInvoiceDigest mellé queryInvoiceData is kell, mert a digestben csak nettó és áfa érték jön vissza, ami egyszerűsített számlák esetén mindig nulla.)

**Comment by Szildiko** [comment]
Megvárom a 20-ai hajtást, ha azt is túléli az új rendszer, akkor majd zárom a topicot. Köszönjünk az erőfeszítéseteket!

**Comment by omachtandras** [comment]
Nálunk ritkulnak a timeoutok. Valószínű a két szolgáltatás ahogy szép lassan kiszolgálja az elmaradásokat csökken a többi terheltsége is...

**Comment by Szildiko** [comment]
Gondoltam, hogy lezárom a topicot, de nem tudom, hogy most tényleg megoldódtak-e a dolgok, mert ma reggel az egész rendszer nem működik.

**Comment by vivacomp** [comment]
Szerintem a lekérdezési problémák továbbra is fennmaradnak (az eddigi gyakorlat szerint), ezért még ne zárd le légyszíves.

**Comment by vivacomp** [comment]
Nem kellett sokat várni a problémára......

**Comment by neszt** [comment]
@renced42 @EPluribusUnum másik issue-ban @szecsenyizoltan nak volt egy jó ötlete, amit legalább elvi szinten vitassunk már meg:

Mi lenne, ha a NAV napi szinten felrakna egy adószám dumpot, akár csv-ben, json-ban, tökmindegy. A lényeg, hogy éjfél után 1 db fájl letöltéssel és feldolgozással az egész napi adószámlekérdezéseket házon belül meg tudnánk csinálni magunknak, nem kellene az NAV rendszerét terhelni.

Működhetne ez? Én azzal sem vagyok tisztában, hogy az adószámtörzs mennyi időnként változik. Igaz az, hogy ha egy adószám reggel érvényes, akkor aznap már végig érvényes? Pl. be tud csődölni egy cég délben, úgy, hogy este már nem érvényes az adószáma?

**Comment by EPluribusUnum** [comment]
@neszt , tudtommal technikailag a Cégbíróság az adószám törzs tulaj/gazda/kezelő és nem a NAV. A NAV is csúszásban van a Cégbírósághoz képest, NAVhoz sem instant kerülnek a friss adatok. A törzs tulajnak kellene publikus API-t biztosítania. Az hogy az milyen formában az mindegy, csak géppel feldolgozhatónak és autmatizálhatónak kell lennie.

**Comment by neszt** [comment]
> @neszt , tudtommal technikailag a Cégbíróság az adószám törzs tulaj/gazda/kezelő és nem a NAV. A NAV is csúszásban van a Cégbírósághoz képest, NAVhoz sem instant kerülnek a friss adatok. A törzs tulajnak kellene publikus API-t biztosítania. Az hogy az milyen formában az mindegy, csak géppel feldolgozhatónak és autmatizálhatónak kell lennie.

@EPluribusUnum nem értem, miért küldesz el borért? :)

A NAV rendszere fogja rámondani, hogy valid az adószám vagy sem, ha én egy harmadik féltől beszerzek bármilyen adószámtörzset, akkor kezdődhet a nyavaja, hogy ott valid volt, nálatok nem, stb.

Ez az én értelmezésemben csak úgy működhet, hogy ha nektek küldjük be a számlákat, akkor ti adjátok hozzá a valid adószám törzset. Az irreleváns, hogy ti is csúszásban vagytok a cégbírósághoz képest, hiszen akkor ez most is ugyanúgy probléma az API keresztüli adószám lekérdezésnél.

**Comment by EPluribusUnum** [comment]
A NAV rendszere a **SZÁMLÁRÓL** mondja hogy valid vagy nem valid. Az adószám érvényességről semmit nem állít. Ha az OSZ rendszer visszadobja hogy nem valid az adószám a számlán, az nem feltétlenül jelenti azt hogy a NAVnak van igaza.

Továbbá a törvénybe le van írva hogy számla kiállítást nem lehet blokkolni az OSZ-be feladás miatt. Ha a vevő bemond egy adószámot, akkor márpedig arra kell kiállítani a számlát, nem számít hogy arról az adószámról mit állít az OSZ rendszere.
Azt kell lejelenteni ami a számlára nyomtatva/írva lett, és így hibás/nem létező/stb... adószám is kerülhet a számlára és azt KELL beküldeni. Ha ERROR-ra fut a beküldés és nem lehet sehogyan sem sikeres ágra terelni, akkor jön a jegyzőkönyvezés hogy miért nem lehetséges a számláról sikeres beküldést készíteni.

(nem NAV oldali szereplő vagyok, @renced42 az egyedüli NAV oldalról aki itt írni szokott)

**Comment by neszt** [comment]
> A NAV rendszere a **SZÁMLÁRÓL** mondja hogy valid vagy nem valid. Az adószám érvényességről semmit nem állít.

No, de mi ennek az issue-nak a neve? "Adószám lekérdezés". Akkor ez minek van? Miről beszélünk? :)

> Továbbá a törvénybe le van írva hogy számla kiállítást nem lehet blokkolni az OSZ-be feladás miatt.

Ezt már fullosan átbeszéltük másik issue-ban, nem erről van szó, hogy blokkoljuk-e vagy sem. Nem blokkolunk semmit, mert törvény tiltja. Rendben van. Arról van szó, hogy nem akarjuk terhelni a NAV API-t adószámlekérdezéssel.

> (nem NAV oldali szereplő vagyok, @renced42 az egyedüli NAV oldalról aki itt írni szokott)

Bocs, ezt nem tudtam. akkor @renced42 majd ha lesz időd, várom a reakciókat.

**Comment by neszt** [comment]
> A NAV rendszere a **SZÁMLÁRÓL** mondja hogy valid vagy nem valid. Az adószám érvényességről semmit nem állít.

@EPluribusUnum a NAV API doksiból:
```
A /queryTaxpayer belföldi adószám validáló operáció, mely a számlakiállítás folyamatába építve képes a megadott adószám valódiságáról és érvényességéről a NAV adatbázisa alapján adatot szolgáltatni.
```

**Comment by renced42** [comment]
Sziasztok!

Az adószám lekérdezés performanciája esetenként hagyott kívánnivalót maga után valóban, de azt gondolom illetve látom, hogy a legutolsó optimalizációt követően nincs vele probléma.
Egyébként dolgozunk egy nagyobb átalakítás előkészítésén, ami után végkép nem lesz vele probléma. Az ötletet, hogy le lehessen egyben tölteni megvizsgáljuk, de nem ígérek semmit.

**Comment by renced42** [comment]
Zárom az issuet.
