### ISSUE TITLE
[Q&A] Pénztárgépes számlák elakadása

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#1077]
Tudom, hogy itt az éles rendszerrel nem nagyon foglalkoznak, de pénztárgépes számlákat nem lehet tesztben kiállítani, ezért kérdezek itt. 2023.12.14-i és 2023.12.15-i pénztárgépes számlákat nem lehet letölteni, de mégcsak az Online Számla Webes felületén sem láthatók, és nem exportálhatók sem XLSX-be, sem CSV-be. Más is tapasztalt ilyent?  Semmi hírt nem találok üzemszünetről sem.

**Comment by renced42** [comment]
Kedves @Macskafarka 

Köszi a jelzést 
Konkrét eseteket nem vizsgálunk, de természetesen megnézzük, hogy nem-e más a probléma.

**Comment by Macskafarka** [comment]
Köszönöm a segítséget, megérkeztek az OPG számlák.
