### ISSUE TITLE
[DEV support]

### ISSUE THREAD

**Issue by Istvan6691** [nav-gov-hu/Online-Invoice#1078]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[] 3.0

**A requestId értéke / requestId value**
```

```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Módosító számlát küld a rendszerünk alapszámlával kapcsolatban, a rendszer az alábbi hibaüzenettel megszakítja az adatszolgáltatást:

Blokkoló hiba
--
- Eredeti számlára történő hivatkozás alapszámla esetén nem adható meg. –  Tag: InvoiceData/invoiceMain/invoice/invoiceReference
- Alapszámla esetén nem adható meg tételsor módosítás jelleg. –  Tag: InvoiceData/invoiceMain/invoice/invoiceLines/line/lineModificationReference –  Érték: 1 –  Számla sor: 1
- Alapszámla esetén nem adható meg tételsor módosítás jelleg. –  Tag: InvoiceData/invoiceMain/invoice/invoiceLines/line/lineModificationReference –  Érték: 2 –  Számla sor: 2

A TESZT rendszerben a tranzakció azonosító: 4EZDVIMNP2MIEVTE. Az eredeti számla a TESZT rendszerbe a 4EZDROITUK56DWG3 tranzakció azonosítóval került feltöltésre.

Kérem segítségüket a hiba elhárításához!

*Egyéb tartalom / Additional content*

**Comment by topybear** [comment]
A módosító számlánál az invoiceOperation értékét nézd meg, gyanús, hogy MODIFY helyett CREATE szerepel.

**Comment by Istvan6691** [comment]
Köszönöm a javaslatot, szólok a fejlesztőknek, hogy ellenőrizzék.

**Comment by renced42** [comment]
Kedves @Istvan6691 

És ellenőrizzétek az InvoiceOperationt-is, mert éhet, hogy alapszámlaként akartok beküldeni egy módosítót.

**Comment by renced42** [comment]
Kedves @Istvan6691 

Sikerült megoldani a kérdéses problémát ha igen kérlek zárd az issuet.

**Comment by Istvan6691** [comment]
Igen, sikerült megoldani a problémát, köszönöm a segitséget!
