### ISSUE TITLE
[DEV support] Query Invoice Check Request 503-as hibakód

### ISSUE THREAD

**Issue by lakatoskevin** [nav-gov-hu/Online-Invoice#108]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fill out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[x] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[x] 2.0

**A requestId értéke / requestId value**
```
JHSARYFNGF2020116143332
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Query invoice check request nálam 503-as hibakódot ad vissza. A dokumentációnak megfelelően nálam a password hash SHA 512-vel történik, a request signature pedig SHA3 512-vel aminek a bemenete a RequestID + Timestamp + XMLKEY.

*Egyéb tartalom / Additional content*
Kijött egy segédprogram most kilencedikén, ezt is próbáltam már segítségre használni, de nálam ez a program el se indul, és olyan nem lekezelt kivételeket dob olyan egyszerű dolgoknál is mint pl egy mappa kiválasztása.

**Comment by NTCA-developer** [comment]
Szia @lakatoskevin 

Ez a request ezzel a requestId-vel nem ért el a szerverig. Megadnád az URL-t amire postoltál?

**Comment by lakatoskevin** [comment]
Szia! Erre küldtem:
https://api-test.onlineszamla.nav.gov.hu/invoiceService/v2/queryInvoiceCheck

**Comment by lakatoskevin** [comment]
Amúgy változtattam a programon kicsit, és ezzel a requestID-vel küldtem egy query-t, de ezzel meg 500-as hibád kaptam vissza: MCAL6RZVZ620201178426

**Comment by lakatoskevin** [comment]
Amúgy változtattam a programon kicsit, és ezzel a requestID-vel küldtem egy query-t, de ezzel meg 500-as hibát kaptam vissza: MCAL6RZVZ620201178426

**Comment by NTCA-developer** [comment]
Szia!

Az 500 már jobban hangzik. Itt requestSignature probléma van, de ez biztos te is láttad a válaszból. Az én számításom szerint a requestSignature vége helyesen CC10 lenne.

Biztosan nem a hash algoritmussal van a baj, mert a bemenetet SHA2-512-ként kiszámolva is más eredmény jön ki mint amit küldtél. Szóval valószínűleg az input string környékén lesz valami hiba.

**Comment by NTCA-developer** [comment]
Szia!

Gondoltam ránézek, hogy lezárható-e, de látom hogy még nem. Azt észrevetted, hogy azok a 2.0-ás token kéréseid amik sikeresek, ott a timestamp értéke egy órával korábbiak mint a helyi idő? Mivel a /queryInvoiceCheck operációban ugyan úgy kell authentikálni, mint a 2.0-ás token kérés esetén szerintem meg is van hol van a probléma. Olyan mintha a check-nél más időponttal számolnál.

**Comment by lakatoskevin** [comment]
Szia!

A beosztásaim miatt a mai napon tudok jobban foglalkozni ezzel a problémával, úgyhogy a nap végére szerintem zárható lesz. Akkor majd külön meg fogok ejteni egy kommentet.

**Comment by lakatoskevin** [comment]
Lezárhatod, már megvan a hiba, kijavítottam és működik! Köszönöm szépen a segítséget!
