### ISSUE TITLE
QueryInvoiceChainDigestRequest kitöltés hiba? [Q&A]

### ISSUE THREAD

**Issue by OszkarOlah** [nav-gov-hu/Online-Invoice#1080]
Mit nem töltök ki helyesen?
Íme a kérés:
`<QueryInvoiceChainDigestRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

    xmlns:xsd="http://www.w3.org/2001/XMLSchema"

    xmlns="http://schemas.nav.gov.hu/OSA/3.0/api">

    <header xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common">

        <requestId>20240104173634_234076367725480</requestId>

        <timestamp>2024-01-04T16:36:34.718Z</timestamp>

        <requestVersion>3.0</requestVersion>

    </header>

    <user xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common">

        <login>u***</login>

        <passwordHash cryptoType="SHA-512">8***</passwordHash>

        <taxNumber>1***</taxNumber>

        <requestSignature cryptoType="SHA3-512">D***</requestSignature>

    </user>

    <software>

        <softwareId>H***</softwareId>

        <softwareName>T***</softwareName>

        <softwareOperation>LOCAL_SOFTWARE</softwareOperation>

        <softwareMainVersion>4</softwareMainVersion>

        <softwareDevName>O***</softwareDevName>

        <softwareDevContact>o***</softwareDevContact>

        <softwareDevCountryCode>HU</softwareDevCountryCode>

        <softwareDevTaxNumber>5***</softwareDevTaxNumber>

    </software>

    <page>1</page>

    <invoiceChainQuery>

        <invoiceNumber>23SA400600</invoiceNumber>

        <invoiceDirection>OUTBOUND</invoiceDirection>

    </invoiceChainQuery>

</QueryInvoiceChainDigestRequest>`

Ezt a választ kapom:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<GeneralExceptionResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common"

    xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api"

    xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base"

    xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">

    <funcCode>ERROR</funcCode>

    <errorCode>INVALID_REQUEST</errorCode>

    <message>Érvénytelen kérés!</message>

</GeneralExceptionResponse>`

**Comment by renced42** [comment]
Kedves @OszkarOlah 
Az XML nem jó.  A root element záró tag nem maradt el véletlenül?

**Comment by renced42** [comment]
De a névterek sem stimmelnek a root elementben.

`<?xml version="1.0" encoding="UTF-8"?>
<QueryInvoiceChainDigestRequest xmlns="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common">
  <common:header>
    <common:requestId>RIDJf1Wp7Da6Em3Am5U7Oq9Kg0Sp6</common:requestId>
    <common:timestamp>2024-01-04T17:42:49.346Z</common:timestamp>
    <common:requestVersion>3.0</common:requestVersion>
    <common:headerVersion>1.0</common:headerVersion>
  </common:header>
  <common:user>
    <common:login>xxx</common:login>
    <common:passwordHash cryptoType="SHA-512">47C4A1D2A88A55D7F68A4F390117C7571880195C22B1C3392CC7AB6F213E56F345FD4416FAB8995EECB5729ACDA5212F5C4A8F179197BB11FC6B2A41C486BF1D</common:passwordHash>
    <common:taxNumber>12345678</common:taxNumber>
    <common:requestSignature cryptoType="SHA3-512">A8968848FAFA15B97C71786587DA943BB0DE75CFE363CE6B98DA112DE36E817A394C046FCAF59E33C633B4BFA9A3ACCD3AEF4F657CC8A722E81A1BFCA86C75F0</common:requestSignature>
  </common:user>
  <software>
    <softwareId>HU1004444400000001</softwareId>
    <softwareName>NAV Online Invoice Test tool</softwareName>
    <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
    <softwareMainVersion>1.0</softwareMainVersion>
    <softwareDevName>dennis</softwareDevName>
    <softwareDevContact>renced42@foo.bar</softwareDevContact>
    <softwareDevCountryCode>HU</softwareDevCountryCode>
    <softwareDevTaxNumber>12345678</softwareDevTaxNumber>
  </software>
  <page>1</page>
  <invoiceChainQuery>
    <invoiceNumber>EREDETI-1</invoiceNumber>
    <invoiceDirection>INBOUND</invoiceDirection>
    <taxNumber>87654321</taxNumber>
  </invoiceChainQuery>
</QueryInvoiceChainDigestRequest>`

**Comment by OszkarOlah** [comment]
Köszönöm a segítséget, valószínű a namespace lehet a gond.
