### ISSUE TITLE
[Q&A] Vevő és szállító adószáma megegyezik

### ISSUE THREAD

**Issue by janisoft** [nav-gov-hu/Online-Invoice#1081]
Sziasztok!

Egyik ügyfelemnél találkoztam egy olyan feldolgozott számlával, ahol a vevő adószáma megegyezik a szállító adószámával, azaz saját magára állított ki számlát, ráadásul ÁFA tartalommal. Ezek szerint ez valid? Nem jártam utána, de ez ilyenkor a bejövő oldalon is megjelenik?
Tanulmányaimból rémlik, hogy a saját termelésű készlet belső felhasználásánál ÁFA fizetési kötelezettség keletkezhet, más nem jut eszembe, ami ezt indokolhatná.

Szép napot!
János

**Comment by renced42** [comment]
Kedves @janisoft 
Ezzel kapcsolatosan #326 és a #931 témában van információ.
