### ISSUE TITLE
Tanúsítvány 2024

### ISSUE THREAD

**Issue by TNMarton** [nav-gov-hu/Online-Invoice#1082]
Kedves @NTCA-supporter!

A mai napon elérhetővé vált az új tanúsítvány 2024-re, de úgy tűnik, hogy a  onlineszamla.nav.go.hu még a korábbi tanúsítványt használja:
![image](https://github.com/nav-gov-hu/Online-Invoice/assets/68106468/00a182a6-f3d9-4982-b9d1-f1179f47afa0)

Mivel az ügyfeleink túlnyomó többségének már ki lett küldve a friss tanúsítvány, ezért kérhetjük, hogy a honlapon is mielőbb frissítésre kerüljön a tanúsítvány? 

Köszönöm!

**Comment by AndreaEINV** [comment]
Kedves @NTCA-supporter 

Ez a kérdés nekem is érdekes.
Tudnál abban segíteni, hogy az új tanúsítvány mikortól érvényes? Holnap 17:00 után?
 
Köszönettel,
Andrea

**Comment by renced42** [comment]
OSA Portálon kint van:

Tanúsítványcsere az Online Számla rendszerben
2024-01-10 15:30
2024. január 12-én 17 órakor megújul az Online Számla éles és tesztrendszerében használt gép-gép interfészkapcsolat titkosító SSL-tanúsítványa.
Az új tanúsítvány a [Technikai információk/Dokumentáció](https://onlineszamla-test.nav.gov.hu/dokumentaciok) menüpontban érhető el és tölthető le tömörített formában.

**Comment by TNMarton** [comment]
Köszönöm a visszajelzést!

A jelenleg használt (2023-as) tanúsítvány január 22-ig használható, vagy holnap 17:00 után már csak az új cert használható adatszolgáltatásra?

**Comment by tkelemen73** [comment]
Annyi észrevétel, hogy az "OSA Portálon kint van" részhez, hogy a megadott link az a tesztrendszerre mutat, ahol nincs ott a 2024-s új tanusítvány... ;) A produktív rendszeren a menüben viszont tényleg megtalálható...

**Comment by renced42** [comment]
Kedves @tkelemen73 

Köszi, javítjuk.

**Comment by renced42** [comment]
Zárom ezt az issuet.
Ha van valami akkor nyissátok újra.

Köszi!
