### ISSUE TITLE
[DEV support] Minusz számla sorainak sorszámozása

### ISSUE THREAD

**Issue by OszkarOlah** [nav-gov-hu/Online-Invoice#1083]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[x] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
20240116183218_0c93f613b9884c8

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
- A 4G29WUSYO3X4KBT1 tranzakciós id-vel elküld a program egy számlát (számlaszám: 23SA400600) ami 5 tételsort tartlmaz
- Ez után a felhasználó készít egy mínuszos számlát, ami ua mint az előző, csak a mennyiségek mínusz értékűek és a hivatkozásban benne van az eredeti számla sorszáma. Ezt egyeztettem a NAV jogi értelmezési csoporttal és azt az információt kaptam, hogy ez így megfelelő.
- A módosító számla sorainak sorszámozása 6-tól kezdődik, folytatva az eredeti számla sorainak sorszámozását
- A visszakapott hibaüzenetben az első soron LINE_NUMBER_NOT_SEQUENTIAL hibát kapok, a többi soron INVOICE_LINE_ALREADY_EXISTS hibát.

**Abban szeretnék segítséget kérni, hogy mi a hiba a módosító számla küldésben, illetve hogyan kell helyesen elküldeni a módosító számlát?**

*Egyéb tartalom / Additional content*
A tömörített fájl az XML küldéseket és válaszokat tartalmazza:
[2024-01-16_XML-ek.zip](https://github.com/nav-gov-hu/Online-Invoice/files/13954333/2024-01-16_XML-ek.zip)

- "2024-01-16a Cipo eredeti szamla INVOICE (szamlaszam 23SA400600) (transactionId 4G29WUSYO3X4KBT1).xml" 
Eredeti számla tartalma
- "2024-01-16b Cipo eredeti szamla REQUEST (szamlaszam 23SA400600).xml" 
A teljes számla küldés REQUEST
- "2024-01-16c Cipo eredeti szamla RESPONSE (szamlaszam 23SA400600).xml" 
A visszakapott válasz

- "2024-01-16d Cipo MINUSZ szamla sorok 6-tol kezdve INVOICE (szamlaszam 23SA400714) (transactionId 4G2CZX2L1ZX665PV).xml" 
A módosító számla tartalma
- "2024-01-16e Cipo MINUSZ szamla sorok 6-tol kezdve REQUEST (szamlaszam 23SA400714).xml" 
A módosító számla teljes küldés REQUEST
- "2024-01-16f Cipo MINUSZ szamla sorok 6-tol kezdve RESPONSE (szamlaszam 23SA400714).xml" 
A modosító számla küldésre kapott válasz
- "2024-01-16g Cipo MINUSZ szamla eredmeny REQUEST (transactionId 4G2CZX2L1ZX665PV).xml" 
A modosító számla lekérdezés REQUEST
- "2024-01-16h Cipo MINUSZ szamla eredmeny RESPONSE (transactionId 4G2CZX2L1ZX665PV).xml" 
A módosító számlára kapott válasz a hibaüzenetekkel

**Comment by renced42** [comment]
Kedves @OszkarOlah 

probáld meg linenumber 1,2,3...linenumberreference 7,8,9....

**Comment by OszkarOlah** [comment]
Tehát a módosító számlán a linenumber sorszámozása 1-től induljon, és a linenumberreference folytatódik onnan ahol az eredeti számla sorainak sorszámozása véget ért? Jól értem?

Én úgy értelmeztem, hogy a linenumberreference arra a sorra mutat, amelyik sort módosítom a mínuszos mennyiséggel.

**Comment by OszkarOlah** [comment]
@tsamu Nagyon köszönöm a segítséget! Valami miatt a **lineNumberReference** mező neve nekem arra utalt, hogy ez a módosítandó sor sorszámára kell mutasson.
Ez volt számomra a megoldást jelentő válasz:
"a lineNumberReference elem az eredeti számla és az összes korábbi módosítás eredményeként előálló sorszámozás folytatása."
