### ISSUE TITLE
[Q&A] Where to find out what the individual values of vatCode actually mean?

### ISSUE THREAD

**Issue by belfortf** [nav-gov-hu/Online-Invoice#1085]
Sziasztok, I have regarding the vatCode attribute which can be a number between 1 and 5. Where exactly do I find out what 1,2,3,4 or 5 actually mean? I have searched the documentation but found no explanation of the numbers. Any help is appreciated. Thank you.

**Comment by connorhu** [comment]
You can translate this page: https://hu.m.wikipedia.org/wiki/Ad%C3%B3sz%C3%A1m
