### ISSUE TITLE
[Q&A]

### ISSUE THREAD

**Issue by N-Andrea** [nav-gov-hu/Online-Invoice#1087]
Kedves @NTCA-developer , kedves @NTCA-supporter !

Egy kis segítséget szeretnék kérni. 
Mi, mint egy szoftverfejlesztő cég, megvásároltuk egy működő számlázó szoftver forráskódját, mi fejlesztjük tovább. Tehát a SoftwareType-ban nagyjából minden módosul.
A kérdésem csak annyi, egyszerűen képzünk egy új softwareId-t, módosítjuk a SoftwareType adatait, és ezentúl így küldjük be a számlákat, automatikusan működni fog? Vagy van egyéb teendőnk, regisztrációs-, bejelentési-, egyéb kötelezettségünk is?

Nagyon köszönöm előre is!

**Comment by renced42** [comment]
Kedves @N-Andrea 

Amit leírtál annyit kell csinálni nincs más teendő.

**Comment by N-Andrea** [comment]
Kedves @renced42 !

Tökéletes! Nagyon köszönöm a gyors segítséged !
