### ISSUE TITLE
[BUG] INCORRECT_DATE_AGGREGATE_INVOICE_ISSUE_DATE hibaüzenet

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#109]
Ma feladtam egy gyűjtőszámlát a teszt rendszerbe, amelyben a következő dátumok voltak:

  [invoiceIssueDate]2020-01-20[/invoiceIssueDate]
          [invoiceDeliveryDate]2020-01-15[/invoiceDeliveryDate]
            [lineDeliveryDate]2020-01-13[/lineDeliveryDate]
            [lineDeliveryDate]2020-01-14[/lineDeliveryDate]
            [lineDeliveryDate]2020-01-14[/lineDeliveryDate]
            [lineDeliveryDate]2020-01-15[/lineDeliveryDate]

Erre a következő WARN jött vissza:

[businessvalidationmessages]                                                                                        
  [validationresultcode]WARN[/validationresultcode]                                                                 
  [validationerrorcode]INCORRECT_DATE_AGGREGATE_INVOICE_ISSUE_DATE[/validationerrorcode]                            
  [message]Gyűjtőszámla kelte korábbi, mint az egyes tételsorok teljesítési dátuma közül a legnagyobb.[/message]    
  [pointer]                                                                                                         
    [tag]InvoiceData/invoiceIssueDate[/tag]                                                                         
    [value]2020-01-20[/value]                                                                                       
  [/pointer]                                                                                                        
[/businessvalidationmessages]                                                                                       

A számla dátuma 01.20, ami NEM korábbi, mint az utolsó számlázott szállító dátuma (01.15), vagyis a hibaüzenet nem értelmezhető.
A hibát más is jelezte a prog.hu-n és adatokkal együtt elküldtem a supportnak is. Javítani kellene még febr. 1. előtt.

Ugyan ezt a hibaüzenetet kaptuk akkor is, amikor egy hiba miatt kimaradt tételt számláztunk le, jóval túl a 15 napon. Ekkor a magyar hibaüzenet teljesen rossz (pont fordítva van), míg az 'INVALID' az persze jó mindenre :)

**Comment by NTCA-developer** [comment]
Szia!

Egy requestId-t vagy transactionId-t kérhetek a tesztes beküldéshez?

**Comment by kabelnet2** [comment]
Szia,
Transaction id 2U8LU9M8QHNMIM4F
A számla és response xml-t is elküldtem a init.onlineszamla_teszt_support@nav.gov.hu-ra (mivel valódi adatokkal dolgozok, gondoltam ide azért nem töltöm fel). Remélem azt is eléritek.

**Comment by kabelnet2** [comment]
Szia, írtam azt is, hogy más esetekben jogos a warn, de nem ezzel a szöveggel. Erre is csináltam egy példát, amiben szándékosan elrontottam az egyik szállító dátumát úgy, hogy az már kívül van a 15 napon. Ennek a transaction id-je 2U9B0QQOUH0Z61G8

**Comment by NTCA-developer** [comment]
Köszi szépen, látom az adatokat. (amit a supportnak írsz, azt viszont fő szabály szerint nem, ezért egyszerűbb és gyorsabb elkérni az azonosítót) Délután fogom csak tudni megnézni, visszajelzek.

**Comment by NTCA-supporter** [comment]
Szia!

Köszi a jelzést. Megnéztük, valóban hibás a működés.
A 15 nap "türelmi idő" a 2.5/2.6 verzióban ki lett vezetve, így már csak akkor kellene jönnie a hibaüzenetnek, ha invoiceIssueDate < max(lineDeliveryDate). (A hibaüzenet szövege ezt a számolást feltételezve egyébként helyes.)
Ennek megfelelően egyik példa beküldésednél sem fog jönni ez a hiba a javítás után.
Igyekszünk minél hamarabb beütemezni, jelzek majd ha megvan a konkrét verzió, amiben javítjuk.

**Comment by kabelnet2** [comment]
Köszönöm/köszönjük a gyors reakciót.

**Comment by NTCA-developer** [comment]
Az Online Számla 2.8 verziójában javítva.
