### ISSUE TITLE
Informatikai karbantartás 05.03

### ISSUE THREAD

**Issue by Szildiko** [nav-gov-hu/Online-Invoice#1096]
Sziasztok!
A tervezett karbantartás említi az elsődleges és másodlagos felhasználókat. Érdeklődnék, hogy a technikai felhasználók hozzáférése működni fog? Vagy a rendszer a szokásos karbantartós stílusában akadozni fog? Ha igen, akkor inkább mi is küldenénk ki tájékoztatót az ügyfeleknek, hogy kevesebb telefonunk legyen.
Köszi az információt!

**Comment by renced42** [comment]
Kedves @Szildiko 

A 2024. május 03-i karbantartás nem rendszer funkcionalitását érinti, azonban teljes leállás lesz, így nem csak a felhasználók, hanem gépi adatszolgáltatásra sem lesz lehetőség a karbantartás alatt. Mivel a hír ezt nem teljesen tükrözi, korrigálni fogjuk.
