### ISSUE TITLE
[FEATURE] TimeStampType időzóna

### ISSUE THREAD

**Issue by bakter80** [nav-gov-hu/Online-Invoice#11]
**Az igény összefoglalása / Summary of the request**
Nem igazán volt jó ötlet UTC-ben megadni az időbélyegzőket.
Például így összeférhetetlenség van a TimeStampType és a DateType között.
Időzónától függően napváltás körül, a módosító számla kelte és a módosítás időpontja nem ugyanarra a napra fog esni.

**Az általam javasolt megoldás / The solution I propose**
Helyi idő + időzóna használatának lehetősége TimeStampType esetén. Így nem veszik el az az információ, hogy melyik időzónából történt a feladás, és az UTC idő is könnyedén kinyerhető lenne, és még az időbélyeg és a dátum se veszne össze.

**Elfogadható alternatívák / Acceptable alternatives**
Időzóna jelölése valahol a HEADER környékén, és WARN mentesítés az ilyen esetekre.

**Comment by NTCA-developer** [comment]
Szia!

Köszönjük az észrevételed. 

Az általad említett WARN a 2.0-ban a modificationTimestamp törlése miatt ki fog esni a rendszerből, hiszen az összehasonlítás egyik része már nem lesz meg. Az egyetlen hely, ahol timestamp marad az XML-ben, az a requestSignature generáláshoz szükséges időbélyeg, amire viszont kell az UTC, de cserébe nincs rá egy szem WARN sem.

Szerintem nyitott kapukat döngetsz. :) Lezárhatjuk, vagy szeretnéd folytatni?

**Comment by bakter80** [comment]
Így rendben, csak véletlen vissza be kerüljön valahova a timestamp :D
