### ISSUE TITLE
[Q&A] Konzolos segédprogram onlineInvoiceTool

### ISSUE THREAD

**Issue by nemethi64** [nav-gov-hu/Online-Invoice#110]
Sziasztok!
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**

Várható konzolos segédprogram (onlineInvoiceTool) az SHA3-512-es titkosítás funkcióval bővítve?
Itt konkrétan az onlineInvoiceTool_v1.0.jar 2.0-s változatára gondolok.

Köszönöm.
Üdv.: István

**Comment by NTCA-supporter** [comment]
Szia!

Jelenleg a grafikus segédprogramban van lehetőség ellenőrizni, kiszámolni az SHA3-512 HASH eredményét, de természetesen nem a konzolos program mintájára, mert az eredményt felületen adja vissza. Ennek dokumentációját és magát a programot is megtalálod teszt és éles környezeteken.
Kérlek nézz majd rá, hátha ez megoldja a kérdésed.

Köszi

**Comment by nemethi64** [comment]
Szia!

A jelenlegi felállásban az érintett alkalmazások esetében a konzolos invoicetool által képzett eredmény került felhasználásra - nem csak ellenőrzés céllal - a kódolási műveleteknél, nyilván a grafikus segédprogram erre nem alkalmas. 

Köszönöm.

**Comment by NTCA-supporter** [comment]
Szia!

Értem a problémád. Alapvetően ez a program tesztelésre/önellenőrzésre készült, nem pedig beépítésre. Mivel ez a cél nem fog változni, így nem is tudunk vállalni garanciát, hogy ez folyamatosan karban lesz tartva. Ezáltal mindenképp érdemes lenne elgondolkozni a kiváltásán.
Megpróbáljuk beütemezni, viszont mivel a grafikus program ezt tudja, és az már publikálva van, így nem tudok semmi konkrétumot ígérni. Jelzek, ha van bármilyen irányú fejlemény, addig maradhat nyitva az issue.

Köszi

**Comment by nemethi64** [comment]
Szia!

Rendben, köszönöm a válaszokat.

Üdv. I

**Comment by NTCA-developer** [comment]
Szia @nemethi64 

Most kaptam a hírt, hogy elkészült a konzolos segédprogram új változata a v2-höz, hamarosan elérhető lesz a felületen. Jelezzük majd itt ha kikerült, csak addig is gondoltam szólok.

**Comment by nemethi64** [comment]
Szia!

Rendben, köszönöm! :)

Üdv. I

**Comment by NTCA-supporter** [comment]
Szia @nemethi64 !

Sorry a kicsit késői reakcióért, de:
kikerült teszt és prod környezetre a Grafikus segédprogram: OnlineInvoiceTool GUI v2.0.7356 és Felhasználói dokumentáció (2020.03.06.).
Ha ezt feltelepíted, akkor a telepített mappában ott lesz a kért file onlineInvoiceTool_v1.2.jar néven.

Zárom az issuet, ha van kérdés/észrevétel, várjuk továbbra is.

Üdv
