### ISSUE TITLE
Árfolyam és valuta összegek hibásan jelennek meg a webes felületen.

### ISSUE THREAD

**Issue by migpeti** [nav-gov-hu/Online-Invoice#1108]
Webes felületen, valutás számla esetén, Számla adatok lapon, az Alkalmazott árfolyam 38964. Pedig a számlám 389,64 az árfolyam.
A Számlatételeknél a Nettó összeg (számla pénznemében) és az ÁFA összeg (a számla pénznemében) is rossz értéket mutat. Ott is hiányzik a tizedesvessző.
Nettó összeg (számla pénznemében) 7874 pedig a számlán 78,74
ÁFA összeg (a számla pénznemében) 2126 pedig a számlán 21,26
A Bruttó összeg jó.
A fenti hiba a Számlaösszesítőben is megjelenik.

**Comment by NTCA-KZJ** [comment]
Köszönöm a jelzést
Kértük a javítását

**Comment by migpeti** [comment]
Csak pontosításként: Ezt a hibajelenséget a teszt felületen észleltük. Értesüléseim szerint az éles rendszerben korrektül jelenik meg.

**Comment by Mocsa1974** [comment]
az éles rendszeren is ez van. és nem csak a devizás számláknál

**Comment by migpeti** [comment]
Úgy látom már "megjavult".
Köszönjük!

**Comment by NTCA-KZJ** [comment]
Kedves "migpeti"
Köszönöm a visszajelzést.
