### ISSUE TITLE
[Q&A] QueryInvoiceData mennyiségi limit

### ISSUE THREAD

**Issue by ballonyi** [nav-gov-hu/Online-Invoice#1112]
Az OUTBOUND számlákat szeretnék lekérdezni QueryInvoiceData hívásokkal, nagyobb mennyiségben. Az alábbi kérésekre szeretnék választ kérni:
1. Van-e limit, hogy milyen gyakorisággal kérdezhetek le?
2. Ha a QueryInvoiceDataResponse nem tartalmaz InvoiceDataResult elemet az azt jelenti, hogy az adott számláról nem lett beküldve adatszolgáltatás?
3. A tömeges QueryInvoiceData hívásoknál egy idő után felaszaporodnak az általános "500 - Internal Server Error" válaszüzenetek. Ez jelzi a mennyiségi korlába ütközést?

Előre is köszönöm a válaszokat.

**Comment by balazshornacsek** [comment]
1. kérdésedre: dokumentáció 1.6.11 Forgalomkorlátozás
1 ip cimről 1 request / sec a korlát a QueryInvoiceData endpointnál, ha ezt túlléped akkor késleltetés, majd timeoutolnak

**Comment by szako** [comment]
> 1. kérdésedre: dokumentáció 1.6.11 Forgalomkorlátozás
>    1 ip cimről 1 request / sec a korlát a QueryInvoiceData endpointnál, ha ezt túlléped akkor késleltetés, majd timeoutolnak

Igen, **v1-es** végpont esetén.

**Comment by ballonyi** [comment]
Köszönöm
