### ISSUE TITLE
[FEATURE] Számlák lekérdezési lehetősége inkrementálisan

### ISSUE THREAD

**Issue by ballonyi** [nav-gov-hu/Online-Invoice#112]
**Az igény összefoglalása / Summary of the request**
QueryInvoiceDigest: bejövő számlák lekérdezési lehetősége inkrementálisan.

**Az általam javasolt megoldás / The solution I propose**
Legyen lehetőség bejövő számláknál feldolgozottságot bejelölni, illetve szűrőfeltételt megadni a feldolgozatlan számlák lekérdezésére. 

**Elfogadható alternatívák / Acceptable alternatives**
setProcessed(boolean) operáció egy megadott számlaszámra, illetve invoiceQueryParams szűrőfeltételek bővítése processed (boolean) opcionális szűrőfeltétellel.

**Egyéb tartalom / Additional content**
"nice to have", hiszen ez hívó oldalon is megvalósítható, de aki bejövő számlák feldolgozására készül annak hasznos lenne.

**Comment by NTCA-developer** [comment]
Szia!

Köszönjük a felvetést. Segítesz megérteni első körben, hogy a te általad javasolt lekérdezés miben tér el mondjuk egy időalapú, timestamp intervallumos lekérdezéstől? Mert számomra egyenértékű a kettő, ha mondjuk óránként végignézed a bejövő számláid akkor pont azt a bontást kapod amit te is szeretnél.

**Comment by ballonyi** [comment]
Szia!

A kettő szerintem nem egyenértékű, illetve csak abban az esetben, ha mindig feldogozok minden számlát amit a QueryDigest hoz. De ha a lekérdezett a bejövő számlákból a user ad-hoc bepipálhat néhányat amit feldolgoz, akkor a jó lenne ha a legközelebbi digest lekérdezés ezeket már nem hozná. 

Ha csak timestamp alapú lekérdezés van, akkor kell készítenem egy hívú oldali bejövő számla nyilvántartást, amibe timestamp alapján mindig letöltök mindent, onnan mazsolázhat a user hogy melyiket dolgozza fel, és ebben jelölgetem magamnak a feldolgozottságot. Ezt tudná megspórolni a szerver oldali feldolgozottság jelölés.

**Comment by NTCA-developer** [comment]
Tehát ez úgy nézne ki folyamatában, hogy először lekérdezed a digestet, visszakapsz egy teljes listát, majd utána ismét lekérdezed és a requestben megmondod, hogy miket ne adjunk vissza? Érdekes felvetés.

Amit te számla feldolgozottságnak nevezel az egy kliens oldali fogalom és nagyon öngól ezt szerver oldalra áttenni. (ld: több típusú számlázóprogram, több telephelyes számlázás problématér) Ehhez az infóhoz nekünk ad-1 semmi közünk ad-2 ebből az okból menteni sem akarjuk. Ha pedig nem mentjük így viszont továbbra sem látom ez mivel ad többet mint a v2-es digest, ahol nem csak timeStamp alapú lekérdezés van, hanem csomó más szűrési lehetőség is.

Másik, hogy te feldolgozz egy bejövő számlát ahhoz felteszem a teljes számla adattartalomra szükség van, tehát mindenképp egyesével kell lekérned őket. Ehhez képest nincs jelentősége annak, hogy a digest-es listában mi jön vissza. (szerintem)

**Comment by NTCA-developer** [comment]
@ballonyi ezt folytatjuk? Kicsit elhanyagoltuk. :)

**Comment by NTCA-developer** [comment]
Ezt most lezárom, ha merül fel új gondolat akkor nyisd újra nyugodtan.

**Comment by ballonyi** [comment]
Azért nem válaszoltam, mert elutasításként értelmeztem a választ. :)

_"Tehát ez úgy nézne ki folyamatában, hogy először lekérdezed a digestet, visszakapsz egy teljes listát, majd utána ismét lekérdezed és a requestben megmondod, hogy miket ne adjunk vissza? Érdekes felvetés."_

Pontosítanék: 

- Bővíteném queryInvoiceData hívást egy setProcessed lehetőséggel, ami egy szerver oldali flag beállítását eredményez.
- Bővíteném digest query szűrőfeltételeket unprocessed/processed szűréssel.

Ha a egy digest által visszaadott találati listából valamely számla feldolgozása mellett döntök, akkor queryInvoiceData-t setProcessed opcióval hívom meg. A legközelebbi query digest hívásnál pedig megadom szűrőnek hogy "unprocessed", azaz csak a maradékot kérem  le.

A sok szűrőfeltétel nagyon hasznos amikor célzottan keresek megadott számlá(ka)t összegek v. dátumok alapján. A másik cél a folyamatos feldolgozás, amikor az újonnan beérkezett, feldolgozatlan számlákkal akarunk foglalkozni. A feldolgozhatóság függhet adattól (pl. additionalInvoiceData megléte), vagy egyéb adminisztratív októl. Lehet hogy hetekig várni kell a feldolgozással. Mikortól kérjem le digest-et? Persze szerver oldali processed kezelés híján implementálom majd ezt kliens oldalon. Nem azért tettem erre javaslatot, mert nagy dolog lenne lefejleszteni, csak kb. minden fejlesztő ugyanazt fogja lekódolni.

(Egyébként nem saját ötlet, egy e-számla szolgáltató webszerviznél találkoztam hasonló megoldással. Kényelmes volt.)

**Comment by NTCA-developer** [comment]
Abban igazad van, hogy alapvetően nem lelkesedem az ötletért, de ettől még szerettem volna biztosnak lenni abban, hogy a lelkesedés hiánya arra vonatkozik amit javasolsz. :)

Ha ilyet szeretnénk csinálni, akkor:
- a setProcessed flag beállítását nem engednénk a listázó végpont részévé tenni (több okból sem), új végpont kellene rá
- ki kellene alakítani a státuszváltás workflowját (nyilván ha bebillenteni lehet a flaget akkor kibillenteni is tudni kell hiba meg egyéb eset miatt)
- nem csak a flaget kellene menteni, hanem az audit értékeit is (ki, mikor billentett) és akkor már 3 értéket mentek, amihez semmi közöm, ráadásul ezeket historikusan is tudnom kell vezetni

Ez így túl nagy bruttónak tűnik.
