### ISSUE TITLE
[Q&A] /queryInvoiceData lekérdezés -  invoiceOperation (CREATE, MODIFY, STORNO)?

### ISSUE THREAD

**Issue by pigator** [nav-gov-hu/Online-Invoice#1121]
A `/queryInvoiceData` lekérdezéssel a `QueryInvoiceDataResponse`-ból tényleg nem lehet megállapítani egy konkrét számláról az `invoiceOperation `(`CREATE`, `MODIFY`, `STORNO`) értékét? Ez tényleg csak `/queryInvoiceDigest `eredményében szerepel az `invoiceDigest`-ben?

**Comment by NTCA-KM** [comment]
Kedves @pigator !

Köszönjük az észrevételt! Valóban nem adja vissza az operáció a számla típusát.  
A továbbfejlesztési ötletek közé felvesszük. 

Jelenleg csak közvetetten lehet a számla típusára következtetni.
Az invoiceData részen visszaadott számla base64 dekódolása után ha szerepel benne, az invoiceReference csomópont, akkor az biztosan MODIFY vagy STORNO számla, ha nem szerepel, akkor biztosan CREATE. 

Üdvözlettel, 
IT Helpdesk

**Comment by NTCA-KM** [comment]
Kedves @pigator !

Egyrészt a transactionId nem jelöl ki egyértelműen egy számlát, mivel egy ManageInvoiceRequestben 100 InvoiceOperation csomópont is megadható.  
Másrészt a saját számlákat (kimenő oldali) transactionId alapján való keresésre a QueryTransactionStatus operáció használható, ahol a returnOriginalRequest = true kapcsolóval visszakapja a válaszban az adott adatszolgáltatásban beküldött InvoiceData.xsd szerinti XML-eket.
Ennek az alábbi a helye: QueryTransactionStatusResponse/processingResults/processingResult/originalRequest

Bejövő oldalon ilyenre nincs lehetőség. 

Sajnos a fejlesztéssel kapcsolatban még nincs információnk, nem tudjuk mikor kerül sorra. Az OSA oldalára kihelyezett release információkból érdemes tájékozódni, milyen javításokat, fejlesztéseket tartalmaz egy újabb verzió. Ezt a fejlesztést is itt fogjuk majd publikálni az élesítést követően. [https://onlineszamla.nav.gov.hu/informatikai_valtozasok]

Üdv,
IT Helpdesk
