### ISSUE TITLE
[Q&A] Kötegelt számla esetén /queryInvoiceDigest és /queryInvoiceData lekérdezés

### ISSUE THREAD

**Issue by pigator** [nav-gov-hu/Online-Invoice#1122]
Eddig szerencsére még nem akadtam kötegelt számlába (remélem), de elbizonytalanodtam, hogy pontosan mi is történik a  `/queryInvoiceDigest` és `/queryInvoiceData` lekérdezések esetén.
Az alábbiakban leírtakhoz kérnék segítséget:
Tegyük fel, hogy az adatszolgáltatás a következő (remélem, így jó). Tehát kettő kötegelt `batchInvoice` ugyanazon számlaszámon:
```xml
<InvoiceData>
    <invoiceNumber>123</invoiceNumber>
	<...>...</...>
	<invoiceMain>
	
	<batchInvoice>
		<batchIndex>1</batchIndex>
		<invoice>... számlaadatok 1 ...</invoice>
	</batchInvoice>
	<batchInvoice>
		<batchIndex>2</batchIndex>
		<invoice>... számlaadatok 2 ...</invoice>
	</batchInvoice>
	
	</invoiceMain>
</InvoiceData>
```

Ebben az esetben `/queryInvoiceDigest` operáció `QueryInvoiceDigestResponse`-ban ez így jelenne meg?

```xml
<invoiceDigestResult>

<invoiceDigest>
	<invoiceNumber>123</invoiceNumber>
	<batchIndex>1</batchIndex>
	<...>...</...>
</invoiceDigest>

<invoiceDigest>
	<invoiceNumber>123</invoiceNumber>
	<batchIndex>2</batchIndex>
	<...>...</...>
</invoiceDigest>

</invoiceDigestResult>
```

Tehát kettő külön `invoiceDigest`, de ugyanaz az `invoiceNumber`, csak eltérő `batchIndex`?

Ugyanaz a kötegelt számla `/queryInvoiceData` operáció a következő keresésre (leegyszerűsítve!): invoiceNumber 123, **batchIndex 1**

```xml
<InvoiceData>
	<invoiceNumber>123</invoiceNumber>
	<invoiceMain>
	
	<batchInvoice>
		<batchIndex>1</batchIndex>
		<invoice>... számlaadatok 1 ...</invoice>
	</batchInvoice>
	
	</invoiceMain>
</InvoiceData>
```

a következő keresésre (leegyszerűsítve!): invoiceNumber 123, **batchIndex 2**
```xml
<InvoiceData>
	<invoiceNumber>123</invoiceNumber>
	<invoiceMain>
	
	<batchInvoice>
		<batchIndex>2</batchIndex>
		<invoice>... számlaadatok 2 ...</invoice>
	</batchInvoice>
	
	</invoiceMain>
</InvoiceData>
```

Tehát, ha a keresőfeltételben szerepel a `batchIndex`, akkor csak azt az egy `batchIndex`-szel rendelkező számlát eredményezi, és csak egyetlen `batchInvoice` lesz a `invoiceMain`-en belül függetlenül attól, hogy az adatszolgáltatás során mennyi volt belőle?
Mi történik, ha kötegelt számla, de nem szerepel a keresőfeltételben a `batchIndex`?

Előre is köszönök minden segítséget.

**Comment by NTCA-KM** [comment]
Kedves @pigator!

Kérdés: Ha a keresőfeltételben szerepel a batchIndex, akkor csak azt az egy batchIndex-szel rendelkező számlát eredményezi, és csak egyetlen batchInvoice lesz a invoiceMain-en belül függetlenül attól, hogy az adatszolgáltatás során mennyi volt belőle? Válasz: igen

Kérdés: Mi történik, ha kötegelt számla, de nem szerepel a keresőfeltételben a batchIndex? 
Válasz: Ilyenkor a teljes batch számla szerepel a válaszban, illetve digest esetén annyiszor, amennyi batchIndex megfelel az egyéb keresési feltételeknek.

IT Helpdesk
