### ISSUE TITLE
[Q&A] InvoiceDigest/insDate - ezredmásodperc

### ISSUE THREAD

**Issue by pigator** [nav-gov-hu/Online-Invoice#1125]
A dokumentáció szerint a `InvoiceDigest/insDate` `InvoiceTimestampType`, azaz - szintén a dokumentáció szerint: '... a másodperc 5 karakteren ezred másodperc értékig'.
Eddigi `queryInvoiceDigest` lekérdezéseim során szúrópróba-szerűen megnéztem az `insDate`-t, de csak másodpercre pontos értéket láttam ezredmásodperc értékek nélkül.
Kérdésem: valóban ezredmásodpercre pontosan kérdezhető le az `insDate` `queryInvoiceDigest` operációval és csak pont olyanokba futottam bele, ahol egész másodpercek vannak?

**Comment by NTCA-KM** [comment]
Jelenleg az ilyen típusú dátumok másodperc pontossággal kerülnek visszaadásra.
Maga az InvoiceTimestampType típusban opcionálisan szerepelnek a másodperc tört részei, így ez a sémának megfelelő. 

<xs:pattern value="\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(.\d{1,3})?Z"/>
