### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ballonyi** [nav-gov-hu/Online-Invoice#113]
**Az igény összefoglalása / Summary of the request**
Amikor egy beküldőnél frissítik a számlázó rendszer tesztkörnyezetét, akkor az inkonzisztenssé válik a NAV teszt nyilvántartással, ez "nincs meg a hivatkozott számla" vagy "számla már beküldésre került" jellegű hibákat eredményez. 

**Az általam javasolt megoldás / The solution I propose**
Hasznos lenne egy olyan funkció, mely segítségével a tesztkörnyezet felülírható legyen az éles rendszer adataival. Vagy a tesztrendszer legyen alaphelyzetbe állítható.

**Comment by NTCA-developer** [comment]
Szia!

Sosem jó érzés azzal kezdeni egy igényre válaszolást hogy ilyen egészen biztosan nem lesz, de most mégis ezt kell tennem. A teszt környezetünk adatai még droppolhatók is, nem garantálunk sem konzisztenciát sem megőrzési időket ezen a síkon. Ez csak egy fejlesztőknek szóló szolgáltatás.

Ha a saját teszt környezetedet integráltad a mi tesztünkhöz - felteszem regresszió teszt céllal - akkor a tesztjeidet kell úgy átalakítani, hogy az adatfüggőségeket előbb magának állítsa elő, majd utána asszertáljon a végeredménye. (ez egyébként tesztelési alapelv is)

Ez volt a kérésed lényege és arra válaszoltam vagy félreértettem?

**Comment by szako** [comment]
@ballonyi: ez már korábban is előjött és a NAV oldal nemleges választ adott. Csak regy hint, mi ezt a kérdést tömeges technikai érvénytelenítéssel oldjuk meg és az új számlákra (értsd: a másolás után) rendben lesz a nyilvántartás.

**Comment by ballonyi** [comment]
@NTCA-developer: Sejtettem hogy az élesből történő frissítésre ez lesz a válasz :) bár a teszt környezet alaphelyzetbe állító funkció kívülállóként nem tűnik sem kivitelezhetetlennek, sem túl nagy fejlesztésnek, és a fejlesztők szerintem örülnének neki. Pl. a webes felületről indítható módon... 
De megértettem a választ, köszönöm!

**Comment by NTCA-developer** [comment]
Ok, köszi a felvetést és a megértést!
