### ISSUE TITLE
[Q&A] Linenumberreference

### ISSUE THREAD

**Issue by KKARACSONY** [nav-gov-hu/Online-Invoice#114]
Sziasztok, 

Szeretnék érdeklődni, hogy mi lenne a helyes XML tartalom, amit küldeni kellene a következő esetben. 

MODIFY (G2) STORNO-ja WARN üzenettel jön vissza.
CREATE (eredeti számla sztornója) -- DONE--> itt nincs probléma, az XML ugyanúgy néz ki, mint a sima storno számlánál.
[Linenumberref_WARN.docx](https://github.com/nav-gov-hu/Online-Invoice/files/4116656/Linenumberref_WARN.docx)

Így néz ki a számlalánc: 
Original invoice: 0090044600
Credit memo: 0090044601
Credit memo storno: 0090044602
Original invoice storno: 0090044603 

Minden számla probléma nélkül bemegy, kivétel a Credit memo storno számla, a WARN üzenettel jön vissza. 

Csatolom az XML-ekből a releváns részeket. 

Köszönöm szépen a segítséget!

**Comment by NTCA-developer** [comment]
Szia @KKARACSONY 

Elkezdtem nézni, csak adószám nélkül többértékű a dolog. Kis türelmet.

**Comment by KKARACSONY** [comment]
Szia, 

Köszi, egy teszt adószámot használtunk a beküldéshez. 

<taxpayerId>66073550</taxpayerId>
<vatCode>2</vatCode>
<countyCode>33</countyCode>

**Comment by NTCA-developer** [comment]
Szia!

Két hibát is látok. Az első és legfontosabb, hogy amit te számlaláncnak nevezel ('0090044600', '0090044601', '0090044602', '0090044603') azt az API XML-ben mindet CREATE operation értékkel küldted be. Ezáltal nem hivatkozhatsz az eredeti számlára (nem is tetted, vagy a B verzió az lett volna ha beküldöd előzmény nélküli módosításként, de ott megint kialakul az eredeti probléma, miszerint) így nem alakul ki a számlalánc. Itt MODIFY vagy STORNO lett volna a helyes érték.

A második probléma, hogy - és ez egyben válasz is arra a kérdésedre, hogy mi lenne a helyes érték - hogy lineNumberReference tagban csak 2 halmaz értékeire hivatkozhatsz:
 - az alapszámla (API-ban CREATE) minden lineNumber eleme
 - módosító okirat (API-ban MODIFY/STORNO) csak azokra a lineNumberReference értékekre, amelyek mellett a lineOperatation értéke CREATE

Ekkor nem fog jönni a WARN. Próbáld ki!

**Comment by KKARACSONY** [comment]
Szia! 

Nem teljesen értem, hogy hol látod ezt, hogy "mindet CREATE operation értékkel küldtem be". Most a fileba beraktam a Manage invoice operation request tartalmat, ami '0090044600' =CREATE, '0090044601'=MODIFY, '0090044602'=STORNO, '0090044603' =STORNO). Ez helyes így ugye? 

A hivatkozások szerintem jól szerepelnek az xml-ekben ez alapján: 
Eredeti számla: 0090044600
Eredeti módosítója: 0090044601 --> original invoice number tag : 0090044600
Módosító sztornoja: 0090044602 --> original invoice number tag : 0090044601
Eredeti számla sztornoja: 0090044603--> original invoice number tag : 0090044600

Nézd meg légyszi mégegyszer, mert nem értjük még, hogy hogy lenne helyes a beküldés. 
[Linenumberref_WARN.docx](https://github.com/nav-gov-hu/Online-Invoice/files/4116957/Linenumberref_WARN.docx)

**Comment by NTCA-developer** [comment]
Szia!

Ez elviekben helyes volna a leírásod alapján, de a teszten nem ez van.

0090044600	12501474	CREATE	2019-11-24 23:37:51
0090044601	12501474	CREATE	2019-11-24 23:37:53
0090044602	12501474	CREATE	2019-11-24 23:37:54
0090044603	12501474	CREATE	2019-11-24 23:37:56

Közben látom hogy ez másik adószám mint amit később leírtál. Ezek akkor irrelevánsak?

**Comment by KKARACSONY** [comment]
A saját adószámunk 66073550233 és a vevő adószáma 24307521233. Mindkét adat csak tesztadat. 
A beküldések ideje 24.01.2020 15:59:22 körül van. 

Köszi szépen!

**Comment by NTCA-developer** [comment]
Kérlek add meg a transactionId-ket, amikben beküldted ezeket!

**Comment by KKARACSONY** [comment]
90044603 | 2UE241N88DL6P46F
90044602 | 2UE10FN55BINVJ4M
90044601 | 2UE0VJELQS3N98MD
90044600 | 2UE0QIY69KWR9QZ9

**Comment by NTCA-developer** [comment]
Jól bevittél az erdőbe. A számlaszámokat hozzánk a vezető 00 nélkül küldtétek be. Na akkor nézem megint. :)

**Comment by NTCA-developer** [comment]
Nagyon meg kell köszönnöm ezt a ticketet neked, mert óriási hibát vettél észre.  A probléma a számla hivatkozások kezelésével (invoiceReference) van nálunk. Ha megnézed, minden MODIFY/STORNO számlában helyesen az alapszámlára hivatkozol, kivéve a 602-es végűben, ahol az első módosításra.

90044600  	CREATE	(null)
90044601  	MODIFY	90044600  
90044602  	STORNO	90044601  
90044603  	STORNO	90044600  

A 602-est be sem lett volna szabad engednünk, mert nem alapszámlára hivatkozik, ennek ABORTED státuszba kellett volna kerülni. A WARN pedig az miatt jön amit először a második pontban írtam, az első módosító számlának nincs lineOperation = CREATE-es sora. (a többiben pedig pont azért jó és nincs WARN, mert a számla hivatkozás helyes)

A hibát a 2.3.0-as verzióban követtük el, amikor az INVALID_INVOICE_REFERENCE validátort szétválasztottuk a v2-ben. Még az élesítés előtt javítani fogjuk, szerencsére ez még nem aktív verzió az élesen.

Hint: nézzétek meg a számlaszám formátum konverterét nálatok, mert tele van trailing whitespace-szel. (pl: a nálad lévő '90044600' számlaszám nálunk '90044600  ', és így a nálad nyilvántartott számlaszámmal nem fogod tudni a későbbiekben keresni)

**Comment by KKARACSONY** [comment]
Köszi szépen, hogy megnéztétek!

A 602-es számla üzletileg egy valós eset (amikor egy módosító számlát (601) kell sztornózni, mert pl. nem helyes. Módosító számlát módosítani nem szokták, hanem csak sztornózzák ezt egy az egyben). Így szerintünk helyes az, hogy ez a számla nem az eredeti (600-as) számlára hivatkozik, hanem a módosító számlára (601).  

A 601-es számlánál nem értjük, hogy miért kellene CREATE lineoperation-nek szerepelnie, mivel ott nem adtunk hozzá új számlatételt, hanem csak a meglévőt módosítottuk.

A specifikáció ezen részéből indultunk ki: " A lineOperation elem értéke az alábbiak egyike lehet:
• CREATE: a módosítás újabb tételsorral egészíti ki az eredeti számla és az esetleges korábbi
módosítás(ok) által leírt állapotot. Ilyenkor a lineModificationReference elem az eredeti
számla (lineNumber) és a korábbi módosítások (lineNumberReference) által létrehozott
sorszámozást folytatja.
• MODIFY: a módosítás az adott tételsor tekintetében változó adatokat tartalmaz. Ilyenkor a
lineNumberReference elem azon eredeti számlán szereplő tétel sorszámát (lineNumber), vagy
korábbi módosító okiraton létrehozott új tétel sorszámát (a korábbi módosító okiraton
lineNumberReference) tartalmazza, amire a módosítás vonatkozik."

Légyszi még ezekben a nyitott kérdésekben segíts nekünk.

Köszi a hintet, megnézzük :)

**Comment by NTCA-developer** [comment]
> A 602-es számla üzletileg egy valós eset (amikor egy módosító számlát (601) kell sztornózni, mert pl. nem helyes.

Logikailag talán igen, de így akkor sem lehet adatot szolgáltatni róla. A NAV kezdetek óta rigorózusan mondja, hogy módosító okirat (MODIFY/STORNO) nem hivatkozhat másra, csakis alapszámlára (CREATE). Ez egy tizen x éves hibás piaci gyakorlat, hogy módosító okirat hivatkozik módosító okiratra. Az ÁFA törvény ilyen esetet nem ismer.

> A 601-es számlánál nem értjük, hogy miért kellene CREATE lineoperation-nek szerepelnie, mivel ott nem adtunk hozzá új számlatételt, hanem csak a meglévőt módosítottuk.

Ilyet nem is mondtam hogy másnak kellene szerepelnie, a MODIFY a jó érték ebben az esetben. Csak azt próbáltam magyarázni, hogy miért jön most a WARN. De ha a validáció megjavul a WARN sem fog jönni, ahogy azoknál a számláidnál sem jött (601, 603), ahol a hivatkozás helyesen az alapszámlára történt.

**Comment by NTCA-developer** [comment]
Szia @KKARACSONY 

Mivel eltelt már pár nap a ticketet lezárom. Ha merül fel új kérdés akkor nyisd újra nyugodtan vagy csinálj egy újat.
