### ISSUE TITLE
[DEV support] - Versions of queryInvoiceDataRequest and qInvoiceDataRespons different

### ISSUE THREAD

**Issue by hamvasgy** [nav-gov-hu/Online-Invoice#115]
> **Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /queryInvoiceData

**A kérés verziója / version of the request**
[] 2.0

**A requestId értéke / requestId value**
<requestId>58a3bca8d1534ae080e532d5219e2a

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
If we call /QueryInvoiceData to get data of an invoice, which was processed (via MIR ) with web service version 1.0 than we get in the response a web service version 1.0 struture even if we call the webservice 2.0 function. From our point of view this is an error since the structural names of 1.0 and 2.0 version are only partly identical. Can you confirm and fix this issue?
Thank You
György Hamvas and Matthias Becker

**Comment by NTCA-supporter** [comment]
Hi @hamvasgy ,
just to be clear, do you mean the base-64 decoded content of the /QueryInvoiceDataResponse/invoiceDataResult/invoiceData tag? 
As I can see, the QueryInvoiceDataResponse is schema valid (validated by the v2 invoiceApi xsd).

**Comment by hamvasgy** [comment]
Hi,

Yes we have problem with the base-64 decoded content.

Best regards
György

**Comment by NTCA-supporter** [comment]
Okey, I thought that.
Well, the data you receive will always be the same as the original invoice. We will never convert data from one version to another, as in many cases it's not even possible, and the purpose of this query service is to return the original content.
You can use the /QueryInvoiceDataResponse/invoiceDataResult/auditData/originalRequestVersion tag to identify the original version of the invoice, so you'll know the exact version of the decoded invoice data.
I hope this could help you.

**Comment by hamvasgy** [comment]
OK, we will use that tag then.
Thank you
