### ISSUE TITLE
V2 Működik?

### ISSUE THREAD

**Issue by hosszuful** [nav-gov-hu/Online-Invoice#116]
Üdv!

A kérdésem az lenne, hogy a v2-es teszt végpont üzemel-e, vagy milyen formában lehet próbálni az átállást a v2-re? 

Köszi

**Comment by NTCA-supporter** [comment]
Szia!

Teszt környezetben már a beküldés és a lekérdezések is működnek, próbálhatod.

**Comment by hosszuful** [comment]
INVALID_REQUEST-et kapok tokenkérésre.
Leírás alapján a tokenkérésben csak a végpont url (/v2) és requestSignature kódolása változott (SHA3-512), a tartalma nem? 
A régi felhasználó / jelszóval kellene működni.

**Comment by NTCA-supporter** [comment]
Tudsz küldeni egy request_id-t? Ránézek a konkrét kérésre, úgy egyszerűbb.

**Comment by hosszuful** [comment]
1006646

**Comment by NTCA-supporter** [comment]
Első körben a software csomópont elemeit kellene tölteni, ezek kötelezősége változott XSD szinten:
![image](https://user-images.githubusercontent.com/58814216/73244730-ecb8c800-41aa-11ea-967b-624536079262.png)

**Comment by hosszuful** [comment]
Köszi ránézek...

**Comment by hosszuful** [comment]
Köszi sikeres lett a tokekkérés.
