### ISSUE TITLE
Teljes adószám lekérdezési lehetőség

### ISSUE THREAD

**Issue by era910413** [nav-gov-hu/Online-Invoice#117]
Érdeklődni szeretnénk, hogy a 8 karakteres adószám (törzsszám) lekérdezésre adott választ ki lehetne-e bővíteni, hogy a teljes 12 karakter hosszú adószámot is adja vissza a rendszer?
Ezen kívül szeretnénk, hogy az érvényesség, név és cím adatok mellett a telephelyek listáját is megkapjuk.

A bejövő számláknál a nevet és a címet mindenképpen ellenőrizni akarjuk, hogy elkerüljük a fiktív számlák befogadását - emiatt szükséges a telephely.
A kimenő számláknál pedig ha a partner nem teljesítése miatt jogi eljárás indul, és a partner a számlán szereplő címen nem lelhető fel, akkor hivatkozhat arra, hogy az általunk kiállított számla nem is rá vonatkozik.

**Comment by NTCA-supporter** [comment]
Szia!
Ha jól értem, a #63 és #41 ticketek pontosan lefedik az igényed. Kérlek erősíts meg ebben.
Mindkét ticket be lett fogadva, már dolgozunk rajta, illetve a boardon is megtalálhatod őket: #101 #102 
Ha lefedik a kérésed, kérlek zárd az issuet.

Köszi

**Comment by era910413** [comment]
Szia!

Elnézést, valóban nem néztem át az összes ticketet. A kettő lefedi a kérésemet, így természetesen lezárom.
Ja és szuper lesz mindkettő, köszönjük :)
