### ISSUE TITLE
[Q&A] Teszt adatbázis törlése

### ISSUE THREAD

**Issue by LeisztnerJanos** [nav-gov-hu/Online-Invoice#118]
Lehetséges valahogy, hogy a NAV-nál tárolt teszt adatbázisba beküldött számlákat töröljük?

**Comment by NTCA-supporter** [comment]
Szia!

Nem volt még erre példa, és nem is tervezünk ilyet.
A technikai érvénytelenítés nem segít a problémádon?

Köszönöm

**Comment by LeisztnerJanos** [comment]
Szia!

Vártam egy ilyen választ, mert alapvetően logikus megoldás lenne, de a számosság miatt nem járható.

A problémánk az, hogy nagy teszteket éles másolati teszt rendszeren végzünk és a keveset használt számla számköreink a teszt NAV adatbázisban emiatt rendszeresen duplikáltak lesznek, ha nem tologatjuk őket. Azt meg nem tartjuk nyilván, hogy milyen tologatások voltak eddig. Tudunk ezzel együtt élni, de amikor feszes határidővel kell mindenféle számlát előállítani és ellenőrizni, akkor feszültséget okozhat, ha ismételni kell emiatt.

Köszönöm.

**Comment by NTCA-supporter** [comment]
Értem a problémád, de a technikai érvénytelenítésen kívül sajnos nem tudok jobb alternatívát ugyanazon számlaszámok felhasználásra.
Zárhatom az issuet?

**Comment by LeisztnerJanos** [comment]
Reménykedek, hogy eljön az idő, amikor saját lehetőségünk is lesz erre, mondjuk egy a csak teszt rendszerben működő webservice meghívásával.

Ez az issue zárható természetesen.
