### ISSUE TITLE
[Q&A] - modificationIndex - nem kerül ellenörzésre

### ISSUE THREAD

**Issue by WittmannWien** [nav-gov-hu/Online-Invoice#119]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Kedves Olvasó.

Amennyiben egy módosító számlák generálok, és ott nem megfelelő modificationIndex értéket küldök be, látszólag ez az érték nem kerül ellenőrzésre. Ahogy tapasztalom, kb bármilyen értékkel fel tudom tölteni a módosítószámlát. Nyilván nem a hibás adatfeltöltés a célom, viszont az esetleg programozási hibákat egy logikai vizsgálattal le lehetne szükíteni.

Várható ide egy logikai vizsgálat a közeljövőben? 

Előre is köszönöm a választ.

Üdvözlettel:
Kovács Péter

**Comment by NTCA-supporter** [comment]
Kedves Péter!

Kérlek pontosíts azon, hogy nem megfelelő modificationIndex értéket küldesz be.
ERROR result_code-ot kellene kapnod (MODIFICATION_INDEX_NOT_UNIQUE), ha nem egyedi lenne a sorszám.

Köszönöm

**Comment by WittmannWien** [comment]
Rendben. Igyekszem jobban kifejteni.
Egy XML 1.1-es számlára (adatszolgáltatási tranzakció száma: 2OGQK2XLZHYWCKMI)
hivatkozva készítettem egy jóváíró számlát. tranzakció száma: 2UMFOZQJ5UQXKB3R (tranzakció rendben elfogadva, status: DONE, WARN nélkül)
A módosító transakcióban szereplö XML reference részében a modificationIndexben egy 2-es értéket tartalmaz, holott ez az elsö módosítás az eredeti számlán. A helyes érték egy lenne, mivel nem volt eddig semmilyen érvényes módosítás. 

Amit én hiányoltam, hogy egy rutin vizsgálja hogy ez az index helyes lehet-e. Ha nem létezik elsö érvényes módosítás, akkor nem fogadja el az indexet egy másik, helytelen számmal.

Remélem most már kicsit érthetöbb a kérdésem.

Ha részletesebb info kell, kérlek írj,

Köszönöm szépen.

**Comment by NTCA-supporter** [comment]
Szia!

Értem az esetet. Mivel aszinkron feldolgozás van, így nem elvárható, hogy sorrendiséget is vizsgáljunk az egyes módosítások között.
Egyedül az egyediséget tudjuk megkövetelni, ezt vizsgáljuk is, és hiba esetén visszadobjuk a módosítást MODIFICATION_INDEX_NOT_UNIQUE hibaüzenettel.
Ez az interfész specifikációban is így szerepel.
Remélem így már érthető, miért nem válaszolunk erre az esetre hibát.

Kérlek zárd az issuet, ha nincs több kérdés.

Köszönöm!

**Comment by WittmannWien** [comment]
Köszönöm a választ.
