### ISSUE TITLE
Lineoperation tag értéke CREATE/MODIFY

### ISSUE THREAD

**Issue by KKARACSONY** [nav-gov-hu/Online-Invoice#121]
Sziasztok, 

Felmerült egy kérdésünk, amiben segítséget szeretnénk még kérni. 

Ugyanazt a számlát beküldtük kétféleképpen, így  2 példánk lett, ami mindkettő DONE státusszal jött vissza. A kérdésünk az lenne, hogy melyik beküldés a helyes? 

1.	Eset: Egy egy tételes kimenő számlára módosítószámlát állítunk ki. 
Az első tétel nem változott az eredeti számlához képest, de a módosító számla tartalmazott egy plusz tételt is. 

Ebben az esetben hogy kell kinéznie a lineOperation tag értékének az első illetve a második tételnél? MODIFY /CREATE

Ha minden create:
Eredeti: 0090044675: 2UNYRMSB125L2797
Módosító: 0090044676: 2UNYT944MQD2OWVO

Modify: 
Eredeti: 0090044642: 2UMBWRQA19HIEXSG
Módosító: 0090044644: 2UMC2AE033P4TACG

2.	Eset: Illetve hogy kell kinéznie a lineOperation tag értékének, hogyha az első tételben is módosul pl. a termék az ár/mennyiség és hozzáadunk itt is még egy új tételt? MODIFY /CREATE

Köszi szépen!

K

**Comment by NTCA-supporter** [comment]
Szia!

Megnéztem a beküldéseket.
Ha az eredeti számlához képest egy tétel nem változott, akkor azt nem kell feltüntetni a módosító számlán. Mindkét eset azért lett DONE, mert számszakilag helyes adatokat közöltél, viszont:

- az első esetben hozzáadtad mégegyszer az első tételt, tehát összességében ez azt eredményezi, mintha az 2x szerepelne a számlán
- a második esetben változtattál az első tételen is, ami azért probléma, mert ha egy tételed módosul, akkor a módosító adatszolgáltatásban a számszerű adatokat (árak, mennyiségek) KÜLÖNBSÉGKÉNT kell jelölni a módosítandó tételsor aktuális értékéhez képest. Tehát esetedben ez a beküldés alapján azt eredményezi, hogy minden mennyiségét megdupláztad az első tételednek.

A 2. esetedre gyakorlatilag válaszoltam, tehát ha valóban változik egy tételed, akkor azt lineOperation = MODIFY értékkel kell feltüntetni, és az összegeket különbségként kell feltüntetni.
Javaslom, hogy fusd át az interface doksi 2.5 (azon belül is tételekre vonatkozóan a 2.5.3) fejezetet. Nem hosszú, és szépen leírja azt, amit most én itt.

Ha utána is van még kérdés, természetesen állunk rendelkezésre.

Köszi

**Comment by KKARACSONY** [comment]
Szia!

Köszi a választ. 
Még egy kérdés felmerült ezzel kapcsolatban. 
A második esetet nézzük, tehát az első tétel is változik (abban különbséget küldünk) MODIFY értékkel, és hozzájön egy plusz tétel CREATE-tel. Ezt követően rájövünk, hogy ez a módosító számla hibásan lett kiállítva, így stornozzuk. A stornoban MODIFY mindkét tételnél a lineoperation érték még akkor is, ha a sztornónak az eredeti számlára kell hivatkoznia (amiben ugye a 2. tétel nem is szerepelt)? 

Köszi szépen!

K

**Comment by NTCA-supporter** [comment]
Szia!

Pontosan, így kell eljárni. Mindig a teljes számlaláncot kell figyelembe venni, és ebben az esetben a számlaláncban már szerepel az egyes és kettes tétel, azokat módosítod.

**Comment by KKARACSONY** [comment]
Köszi szépen a válaszokat!

**Comment by NTCA-developer** [comment]
@KKARACSONY jól gondolom hogy ez lezárható? Ha igen akkor kérlek tedd meg!

**Comment by KKARACSONY** [comment]
Szia! Igen, köszi a segítséget!
