### ISSUE TITLE
[Q&A] 2.0 éles üzem kezdete

### ISSUE THREAD

**Issue by geisztdavid** [nav-gov-hu/Online-Invoice#122]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Sziasztok!
Mikorra várható éles üzemben a 2.0? (Esetleg a 04.01-es határidő változik-e?)
**Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.**
Az ügyfeleknél található szoftver frissítésének ütemezése miatt szükséges az éles rendszer indításának időpontja.

**Comment by NTCA-developer** [comment]
Szia @geisztdavid 

Már vártuk ezt a kérdést, sokan feltették már máshol de itt te vagy az első. Mi is köszönjük neked hogy reagálhatunk a kérdésre.

A teljes 2.0-ás funkcionalitás a 2.8-as Online Számla verzióval élesedhet. Mivel most a teszt környezeten a 2.6 van kint, ez azt jelenti hogy még két verzióval végezni kell előtte. A 2.7 telepítése elvileg hajszálon függ, bármikor megtörténhet. A 2.8 fejlesztése kész, ennek az UAT tesztelése még hátravan.

Az átfutási időket nézve ha becsülnöm kell akkor a 2.8 február második felében várható. De a februári határidőben még bőven benne vagyunk, nem látunk problémát. Szóval az első kérdésedre azt tudom válaszolni hogy legkorábban két hét múlva lehet az élesben is használni a 2.0-át.

Hogy az áprilisi határidő mennyire fix arról mi nem tudunk nyilatkozni, ez felsővezetői döntés. De javasoljuk hogy ellenkező értesítésig mindenki vegye komolyan az átállás tervezésénél és úgy számoljon, hogy 04.01-től nincs 1.x-es beküldés.

Hamarosan fog kijönni a témában DEV diary is a honlapon, érdemes lesz követni mert lesznek benne jó hírek a 2.8 tartalmával kapcsolatosan.

**Comment by geisztdavid** [comment]
Szia!

Köszönöm a választ!

**Comment by NTCA-developer** [comment]
Köszönjük hogy közzétetted Prog.hu-n is!

**Comment by kabelnet2** [comment]
Miért nem lehet egyszerre kitenni a 2.7 és 2.8-at, ahogy volt a 2.5 + 2.6?
Most már nincs sok idő, egyszerűbb lenne még egyszer módosítani/tesztelni ezen az oldalon, mint kétszer nekiugrani. Illetve lehet külön is kitenni, de akkor gondolom sokunknak hosonló lesz a reakciója: a 2.8-ig nem foglalkozunk a dologgal (csináljuk inkább az EKÁER 2.0-t, ha már a szervezés csúcsaként annak a bevezetése is márc. 1.)

**Comment by NTCA-developer** [comment]
@kabelnet2 melyik környezetre gondolsz? Azért kérdezem mert az élesre egyben fognak kimenni.

**Comment by kabelnet2** [comment]
Igen, pontatlan voltam: a tesztre gondoltam

**Comment by NTCA-developer** [comment]
Megnyugtatlak, a 2.7-ben egy deka XML API-t érintő funkcionalitás nincs. Viszont olyan NISZ-es integrációt tartalmaz, amit jó volna az élesítés előtt működni látni pár éles üzemi napot. Ha csak a regresszió a cél akkor ez miatt a 2.7-hez nem éri meg hozzányúlni a ti oldalatokon. A végeredmény szempontjából úgyis az lesz amit te mondasz: a 2.8-ig nem fogja senki felvenni a fonalat.
