### ISSUE TITLE
[DEV support] - test system is unavilable

### ISSUE THREAD

**Issue by hamvasgy** [nav-gov-hu/Online-Invoice#123]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageInvoice
[] /tokenExchange

**A kérés verziója / version of the request**
[] 2.0

**A requestId értéke / requestId value**
```
**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Our developer partner faced connection problem to test system v2.0:
<html>
<body>
<h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body>
</html>
Can you confirm that currently it is in maintenance mode, and can you estimate when they can continue the testing?
(2020.02.04 11:04)

**Comment by NTCA-developer** [comment]
Hi @hamvasgy ,

I can not confirm the downtime, the test system is up. Here is the XML API statistics from the past hour for v2 requests:

`queryTransactionStatus	190
queryInvoiceDigest	76
manageInvoice	131
queryInvoiceData	2
queryTaxpayer	32
manageAnnulment	2
queryInvoiceCheck	7
tokenExchange	1470`

I recently pushed 100 v2 tokenExchange messages and all of it were successful. Can you post the full HTTP message you sent? (HTTP header+body)

**Comment by NTCA-developer** [comment]
Just to make sure, I searched for a period between '2020-02-04 11:00:00' and '2020-02-04 12:00:00' and I don't see any drop in the traffic or in the numbers. 

This is for v2 between 11-12 hrs.

`queryTransactionStatus	152
queryInvoiceDigest	72
manageInvoice	103
queryInvoiceData	26
queryTaxpayer	36
manageAnnulment	2
queryInvoiceCheck	3
tokenExchange	1433`

**Comment by hamvasgy** [comment]
Here is the request:

<?xml version="1.0" encoding="UTF-8"?>


<TokenExchangeRequest xmlns="http://schemas.nav.gov.hu/OSA/2.0/api">


<header>


<requestId>d342a9a081d149fd8f556ccac3a451</requestId>


<timestamp>2020-02-04T12:04:07.168Z</timestamp>


<requestVersion>2.0</requestVersion>


<headerVersion>1.0</headerVersion>


</header>


<user>


<login>3ZjKL5tQR1ttcGL</login>


<passwordHash>removed</passwordHash>


<taxNumber>10773381</taxNumber>


<requestSignature>ED0E740D09241006392BD975B1A52B256E8DD1487CD637D44A5EBFE8F4C812ED4912CF8101C18D3B1F121177899543099614DCCFB7A005B3E11AC9A1719540E6</requestSignature>


</user>


<software>


<softwareId>DE123475223-SD--A1</softwareId>


<softwareName>OFISD_DMS_NAV_online_reporter</softwareName>


<softwareOperation>LOCAL_SOFTWARE</softwareOperation>


<softwareMainVersion>7.0.02-SNAPSHOT</softwareMainVersion>


<softwareDevName>DT IT GmbH</softwareDevName>


<softwareDevContact>info@telekom.de</softwareDevContact<mailto:info@telekom.de%3c/softwareDevContact>>


</software>


</TokenExchangeRequest>

**Comment by NTCA-developer** [comment]
Thanks but this is the HTTP body only. I would really need the HTTP header to investigate what went wrong.

**Comment by hamvasgy** [comment]
Sorry, I missed some Information:
This is the response (13:04:17.57 CET):
<?xml version="1.0" encoding="UTF-8"?><html><body><h1>503 Service Unavailable</h1>No server is available to handle this request.</body></html>

The headers are the following:
                        conn.setRequestMethod("POST");
                        conn.setRequestProperty("Content-Type", "text/xml");
                        conn.setRequestProperty("Content-Length", Integer.toString(contentLength));

To be honest, I’m not totally sure if the error is really from your endpoint.

Best regards,
Christoph

From: Hamvas, György <hamvas.gyorgy@telekom.hu>
Sent: Dienstag, 4. Februar 2020 13:10
To: 'nav-gov-hu/Online-Invoice' <reply@reply.github.com>; nav-gov-hu/Online-Invoice <Online-Invoice@noreply.github.com>
Cc: Hamvas, György <hamvas.gyorgy@t-systems.hu>; Mention <mention@noreply.github.com>; Schachtschabel, Christoph (ext) <C.Schachtschabel@external.telekom.de>
Subject: RE: [nav-gov-hu/Online-Invoice] [DEV support] - test system is unavilable (#123)

Here is the request:
<?xml version="1.0" encoding="UTF-8"?>
<TokenExchangeRequest xmlns="http://schemas.nav.gov.hu/OSA/2.0/api">
<header>
<requestId>d342a9a081d149fd8f556ccac3a451</requestId>
<timestamp>2020-02-04T12:04:07.168Z</timestamp>
<requestVersion>2.0</requestVersion>
<headerVersion>1.0</headerVersion>
</header>
<user>
<login>3ZjKL5tQR1ttcGL</login>
<passwordHash>removed</passwordHash>
<taxNumber>10773381</taxNumber>
<requestSignature>ED0E740D09241006392BD975B1A52B256E8DD1487CD637D44A5EBFE8F4C812ED4912CF8101C18D3B1F121177899543099614DCCFB7A005B3E11AC9A1719540E6</requestSignature>
</user>
<software>
<softwareId>DE123475223-SD--A1</softwareId>
<softwareName>OFISD_DMS_NAV_online_reporter</softwareName>
<softwareOperation>LOCAL_SOFTWARE</softwareOperation>
<softwareMainVersion>7.0.02-SNAPSHOT</softwareMainVersion>
<softwareDevName>DT IT GmbH</softwareDevName>
<softwareDevContact>info@telekom.de</softwareDevContact<mailto:info@telekom.de%3c/softwareDevContact>>
</software>
</TokenExchangeRequest>

**Comment by hamvasgy** [comment]
Sorry, I missed some Information:
This is the response (13:04:17.57 CET):

<?xml version="1.0" encoding="UTF-8"?><html><body><h1>503 Service Unavailable</h1>No server is available to handle this request.</body></html>


The headers are the following:
                        conn.setRequestMethod("POST");
                        conn.setRequestProperty("Content-Type", "text/xml");
                        conn.setRequestProperty("Content-Length", Integer.toString(contentLength));

**Comment by NTCA-developer** [comment]
> To be honest, I’m not totally sure if the error is really from your endpoint.

This could be the case, because since then I see valid messages from '3ZjKL5tQR1ttcGL' user on 2020-02-04 12:03:34 and 2020-02-04 12:03:35. The first was a successful tokenExchange and the second a successful manageInvoice call.

The generic HTTP 503 response is from an intermediary proxy. This usually happens when the called endpoint URL is not valid.

**Comment by hamvasgy** [comment]
sorry for the inconvenience. We found the problem on our SOA-BP, the endpoint to B2B-Gateway

**Comment by NTCA-developer** [comment]
No harm done, happy to help.
