### ISSUE TITLE
[DEV support]

### ISSUE THREAD

**Issue by szecsenyizoltan** [nav-gov-hu/Online-Invoice#124]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[x] /queryInvoiceData

**A kérés verziója / version of the request**
[x] 2.0

**A requestId értéke / requestId value**
RID050091600158099176751534

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Nem kapom a vissza a invoiceDataResult-t

A kódom az éles rendszeren megy szépen, a teszten nem.

**Comment by NTCA-developer** [comment]
Szia @szecsenyizoltan 

Az a baj hogy a lekérdező paraméterek közé betetted a batchIndexet. Az általad keresett számlaszám alapszámlaként van meg a rendszerben (CREATE) eleve nem is lehetne batchIndex értéke. A keresési eredmény a batchIndex(1) != batchIndex(null) miatt nem ad eredményt.

Próbáld meg a batchIndex elhagyásával.

**Comment by szecsenyizoltan** [comment]
Ezer köszönet! Működik.

**Comment by NTCA-developer** [comment]
Nagyon szívesen, akkor ezt lezárom. Ha merül fel új kérdés nyiss újat nyugodtan!
