### ISSUE TITLE
[FEATURE] queryTaxpayer operáció válaszának bővítése

### ISSUE THREAD

**Issue by szecsenyizoltan** [nav-gov-hu/Online-Invoice#125]
**Az igény összefoglalása / Summary of the request**
A queryTaxpayer operáció válaszban hasznos lenne, ha visszaadná az adózó rajta van-e az alábbi listák valamelyikén:
- https://www.nav.gov.hu/nav/adatbazisok/adoslista
- https://nav.gov.hu/nav/adatbazisok/koztartozasmentes/egyszeru_lekerdezes
 Köszi!

**Comment by NTCA-developer** [comment]
Szia @szecsenyizoltan 

Köszönjük a felvetésed. Más is fogalmazott már meg hasonló igényt, pl itt: https://github.com/nav-gov-hu/Online-Invoice/issues/63

Sajnos azt tudom mondani amit akkor is: ez már IT stratégiai kérdés, hogy melyik adózó lekérdező szolgáltatását erősíti a NAV. Amíg ez nincs eldöntve, nem tudunk a kérdésben mozdulni. Tudom ez nesze semmi típusú válasz, én is szeretném ha mást mondhatnék. Egyelőre lebeg a kérdés, ami azért különösen nem jó mert az igény szerintem is jogos, de legalább megfontolandó.

Kicsit még nyitva hagyom a ticketet, ha gondolod reagálj vagy zárd le.

**Comment by szecsenyizoltan** [comment]
#63-at azzal kiegészíteném, hogy jó lenne, ha a pontoznátok a NAV felé történő fizetési fegyelmet, ami igazából súlyozná az összegek nagyságával a késett napokat. Ezáltal publikusan csak egy fuzzy érték menne ki, de adótitok nem. Így minden döntéshozó e pontszám alapján dönthetné el, hogy mondjuk ad-e átutalásra árut vagy sem. A jelenlegi adatforrásokkal a legnagyobb gond, hogy sokat késik, így a problémás ügyfeleket későn szűri ki a piac és a NAV is. Azt gondolom, hogy egy ilyen rendszer erősen javítaná a fizetési fegyelmet. Vélelmezem, hogy NAV nem sokára nem csak azt fogja látni, hogy nekik mennyire pontosan fizetnek, hanem azt is, hogy a számla kibocsátója mikor kapja meg az ellenértéket. Meggyőződésem, hogy egy ilyen szintű monitorozás kölcsönösen hatalmas segítség lenne mindannyiunknak.

(Lezárható a tikket.)

**Comment by NTCA-developer** [comment]
Én úgy tudom, erre a pontozásra van is pilot jellegű project, talán egységes adózói profil, vagy valami hasonló névvel. Nyilván a kezdeti pontozási koncepció nem foglalhatja még magában, hogy ki milyen gyorsasággal teljesít, ezekre jelenleg nincs adatforrás. Legfeljebb a NAV felé történő fizetési hajlandóság lenne mérhető, ami viszont erősen torzít.

De abban teljesen egyetértek veled hogy a világ ebbe az irányba halad: előbb legyen adat, utána pedig jönnek az ötletek, hogy mit lehet vele kezdeni.
