### ISSUE TITLE
eredeti számla módosítása, majd módosító érvénytelenítése

### ISSUE THREAD

**Issue by moferi** [nav-gov-hu/Online-Invoice#126]
Kedves Fejlesztők!

Kérném a segítségeteket, mert nem vagyok biztos az api leírás és példák átnézése után sem, pont ilyen szituációra nem volt példa:

Alábbi számlákat állítom ki:

A normál, eredeti számlánk: SZÁMLA-1.
A SZÁMLA-1-et módosító számla a SZÁMLA-2 lett.
A SZÁMLA-2-t érvénytelenítő számla a SZÁMLA-3 lett.

Az világos, hogy a SZÁMLA-2 adatközlésben az originalInvoiceNumber='SZÁMLA-1' lesz.
Ami viszont kétséges számomra, hogy a SZÁMLA-3 adatközlésében mi lesz az originalInvoiceNumber. SZÁMLA-1 vagy SZÁMLA-2?

Köszönöm! Feri

**Comment by NTCA-developer** [comment]
Szia @moferi!

A SZÁMLA-3 adatközlésében az originalInvoiceNumber is 'SZÁMLA-1'. A NAV értelmezésében minden módosító okirat (MODIFY és STORNO) csak és kizárólag az alapszámlára (CREATE) hivatkozhat.

Azt sajnálattal kell mondanom, hogy ez az ellenőrzés jelenleg a 2.0-ban nem jól működik, és közvetlenül az élesítés előtt lesz csak kijavítva. De az 1.1-ben kipróbálhatod: az az előzményes módosítás vagy érvénytelenítés, ami nem alapszámlára hivatkozik ERROR-t ér és az adatszolgáltatás ABORTED státuszt kap.

**Comment by moferi** [comment]
Köszönöm. Fenti esetre nézve volna további kérdésem. Technikai érvénytelenítést küldtem fel a SZÁMLA-1-re. Ezzel együtt automatikusan technikai érvénytelenítés történt a SZÁMLA-2 és SZÁMLA-3-ra is. EZ teljesen világos, logikus.
Viszont ha a SZÁMLA-2-re küldök föl technikai érvénytelenítést, akkor nem történik meg a SZÁMLA-3 automata technikai érvénytelenítése, holott a 3-as számla a 2-es számlából következik. Ezzel ne foglalkozzak?
Köszönöm!

**Comment by NTCA-developer** [comment]
Ez ne zavarjon. Szerver oldalról nézve a számlalánc sorrendje mindig csak fikció lesz, mivel más határidővel kell a kézi és más határidővel a gépi számlákat jelenteni. Ezért ha a technikai érvénytelenítés nem alapszámlára hanem módosító okiratra vonatkozik, akkor mindig csak az adott módosító okirat lesz technikailag érvénytelenítve, az utána következők nem. Ez azt az esetet is kezeli ha SZÁMLA-2 valójában nem is létezik, hanem csak SZÁMLA-1 és SZÁMLA-3.

**Comment by moferi** [comment]
Köszönöm!
