### ISSUE TITLE
Data példa XML - 12_Többszörös módosítás_B.xml

### ISSUE THREAD

**Issue by moferi** [nav-gov-hu/Online-Invoice#127]
Kedves Fejlesztők!
A weboldalon a Technikai információk/Dokumentációk menüpont alatt elérhető Data példa XML csomagban található 12_Többszörös módosítás_B.xml fájl tartalma kapcsán lenne két kérdésem.
1. summaryGrossData miért nem 0 értéket tartalmaz?
2. Ha a számla nem tartalmaz tételt, akkor hogy kerül a summaryByVatRate blokkba egy 27%-os áfabontás. A számla tekintetében ennek üresnek kellene maradnia. Ennyi erővel 5%-os áfát is beírhattunk volna. Vagy az eredeti számla áfáit itt fel kell sorolni?
Köszönöm!
Feri

**Comment by NTCA-supporter** [comment]
Kedves Feri!

A kérdéseidre a válaszok:
1. Itt segíts egy kicsit megértenem a kérdést. A summaryGrossData egy nem kötelező tag, így nincs is megadva.
2. Az adatszolgáltatásban az invoiceSummary kötelező tag. A példába a 27%-os áfabontás azért került be, mert az eredeti számlán is ez szerepelt, de ez nem számít ennél a módosító számlánál, akár 5%-os is lehetne, ahogy írod is.

**Comment by moferi** [comment]
![image](https://user-images.githubusercontent.com/584501/74225732-8dcf7480-4cbb-11ea-9156-30da809dccdd.png)

Az említett példa xml tartalmát mutatom itt. Ez a számla teljesen nullás, nem tartalmaz tételeket. Mégis ez a mező 4572000.

**Comment by moferi** [comment]
Írásodból az következik számomra, hogy az eredeti számla áfa tartalmát jelezni kell a módosító számla áfabontásában. Ezt tovább gondolva:
van egy további kérdésem. Ha az eredeti számla 27%-os áfát tartalmaz, és mondjuk számla módosítással hozzáadunk egy 5%-os tételt, akkor a módosító számlának az eredeti számla 27%-os áfáját is szerepeltetni kell a módosító számla áfabontásában?
Köszönöm!
Feri

**Comment by NTCA-supporter** [comment]
Kedves Feri!

Utána kérdezek és jelentkezem.

**Comment by NTCA-supporter** [comment]
Szia!

Utánanéztünk, a következő a helyzet:
- a minta XML-ben valóban helytelen a summaryGrossData. Ezt hamarosan javítjuk 0 értékre. (Egyébként nem is lenne kötelező feltüntetni magát a csomópontot.)

- a példádnál maradva, ha az eredeti számla tartalmaz egy 27%-os tételt, majd a módosításban hozzáadsz egy 5%-osat, akkor a módosító számlán elegendő csak az 5%-osra vonatkozó summary-t feltüntetni. (Ha semmilyen tétel nem szerepel a módosításodban, XSD megszorítás miatt akkor is kell egy summaryByVatRate értéket szerepeltetni, 0 értékkel, ahogy fentebb beszéltük.)

Remélem ez így megválaszol mindent.

Üdv!

**Comment by moferi** [comment]
Szia,
nagyon köszönöm, minden világos!
Üdv!

**Comment by NTCA-supporter** [comment]
Rendben, szívesen! Zárom a ticketet.

**Comment by NTCA-developer** [comment]
Szia @moferi 

Megkaptuk a javított sample XML-t, pusholtam is már. A felületen letölthető zip-ben pedig már kint van 02.13 óta. Köszönjük még egyszer a jelzést.
