### ISSUE TITLE
[DEV support] INVALID_REQUEST_SIGNATURE hiba minden egyes kérésnél

### ISSUE THREAD

**Issue by bvica** [nav-gov-hu/Online-Invoice#128]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[x] /manageInvoice

**A kérés verziója / version of the request**
[x] 2.0

**A requestId értéke / requestId value**
Zafir02_1581268480388

```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Amikor a számlát próbálom beküldeni, mindig INVALID_REQUEST_SIGNARURE hibát kapok vissza. Korábban próbáltam a példa xml-ekben adott adatokat használni, a függvényeim ugyanazokat a titkosított adatokat adták vissza, mint az xml-ben. Ezért arra tippelnék, hogy az request előállítása jó.
Észrevettem azonban ma, hogy a timestamp-ek egy órával korábbiak, mint az aktuális idő, úgyhogy azt javítottam. Javítás közben volt, hogy a token kérés is rossz timestamppel ment, akkor arra is ezt a hibaüzenetet kaptam. Most viszont már mindenhol jó az óra-perc, és a tokent megkapom rendben, viszont a számla beküldésénél még mindig hibaüzenet a válasz.

*Egyéb tartalom / Additional content*
első uppercase hash: 6490A1A0BAE0C956E6646C4A3AF85103745991275941D8D07264C9ABAE900430CBAA75F9130AAD1E3FBC15227AABA4F5BE1567D5C1ACF3E4B6CBB4FD8B3BBA57
parciális hitelesítés értéke: Zafir02_158126848038820200209171440f2-952a-5f9ec8acdbfa26QD9SQD9D5F
ekkor az invoiceData: 6490A1A0BAE0C956E6646C4A3AF85103745991275941D8D07264C9ABAE900430CBAA75F9130AAD1E3FBC15227AABA4F5BE1567D5C1ACF3E4B6CBB4FD8B3BBA57
teljes requestsignature alapja: Zafir02_158126848038820200209171440f2-952a-5f9ec8acdbfa26QD9SQD9D5F6490A1A0BAE0C956E6646C4A3AF85103745991275941D8D07264C9ABAE900430CBAA75F9130AAD1E3FBC15227AABA4F5BE1567D5C1ACF3E4B6CBB4FD8B3BBA57
requestSignature: FFBEB0F34F46FB40D1C2C4757101C04FAC20186A5E31D4FC4E018B0040258B49DEEA5BDD61A335DAD81704D4FD681E5360980811F1F7BA6DFC7169BF9248E6E8

**Comment by NTCA-developer** [comment]
Szia @bvica 

Bocsánat a késői reagálásért, tele volt a kezünk a mai 2.0-ás commit publikálásának feladataival és az interfész dokumentációval. Elkezdtem nézni, visszajelzek.

**Comment by NTCA-developer** [comment]
Felteszem hogy a parciális hitelesítés rész rendben van, különben nem kaptál volna tokent sem. A beküldött adatból nekem az első index hash értéke

`9A2C55E49BF29F3EAF40528856C1D850ED33A74305EDA11382AADDB4E5D172BDFD6F11AD1CD42B5428E080B73A1D7CF4F30CE61FFAB8962D355FB499AB1EEA02`

Hozzáfűzted a BASE64 tartalom elé a 'CREATE' értéket?

**Comment by bvica** [comment]
Igen, beleraktam.

**Comment by NTCA-developer** [comment]
Akkor logikailag már csak az az eset lehetséges, hogy mégis a parciális hitelesítésben van a hiba. Objektum szinten ugyan azt használod mint a token kérésnél? Ha a válasz erre is igen akkor valahol sajnos hibás a feltételezés és vagy az index hash vagy a parciális hash nem jó.

**Comment by bvica** [comment]
Az index hash képzése:
        String invoiceData = "";
	SHA3.DigestSHA3 digestSHA3 = new SHA3.Digest512();
	for (EncodedInvoice ei : invoices) {
	  String operationAndBase64Invoice = ei.getOperation().name() + ei.getInvoice();
	  byte[] digest = digestSHA3.digest(operationAndBase64Invoice.getBytes());
	  invoiceData += Hex.toHexString(digest).toUpperCase();
	}

Token request:
        Calendar calendar = NavDataSupplyUtil.getCurrentTime();
	String requestId = NavDataSupplyUtil.getRequestId(softwareID, calendar);

	TokenExchangeRequest request = new TokenExchangeRequest(calendar, requestId);
	//set signature
	request.getUser().setRequestSignature(NavDataSupplyUtil.generateSignature(xmlSignKey, requestId, calendar));

ManageInvoice request:
        Calendar calendar =NavDataSupplyUtil.getCurrentTime();
	String requestId = NavDataSupplyUtil.getRequestId(softwareID, calendar);

	ManageInvoiceRequest request = new ManageInvoiceRequest(token, invoices, calendar, requestId);
	//set signature
	request.getUser().setRequestSignature(NavDataSupplyUtil.generateInvoiceSignature(xmlSignKey, requestId, calendar, invoiceData));

**Comment by bvica** [comment]
public static String generateSignature(String xmlSignKey, String requestId, Calendar timestamp) {
	String input = requestId + getTimestampString(timestamp) + xmlSignKey;
	System.out.println("parciális hitelesítés értéke: " + input);
	SHA3.DigestSHA3 digestSHA3 = new SHA3.Digest512();
    byte[] digest = digestSHA3.digest(input.getBytes());
    return Hex.toHexString(digest).toUpperCase();
  }

public static String generateInvoiceSignature(String xmlSignKey, String requestId, Calendar timestamp, String invoiceData) {
	String input = requestId + getTimestampString(timestamp) + xmlSignKey;
	System.out.println("parciális hitelesítés értéke: " + input);
	System.out.println("ekkor az invoiceData: " + invoiceData);
	input += invoiceData;
	System.out.println("teljes requestsignature alapja: " + input);
	SHA3.DigestSHA3 digestSHA3 = new SHA3.Digest512();
    byte[] digest = digestSHA3.digest(input.getBytes());

    String signature = Hex.toHexString(digest).toUpperCase();
    System.out.println("requestSignature: " + signature);
    return signature;
  }

Én nem látok köztük különbséget.

**Comment by NTCA-developer** [comment]
Kérlek használd az interfész dokumentációban lévő önellenőrzési lehetőséget. Mint korábban írtam, az index hash nálam nem jó értékre jött ki.

**Comment by bvica** [comment]
Igazad volt, tényleg elrontottam az index hash generálását, ez hiányzott belőle:
String operationAndBase64Invoice = ei.getOperation().name() + **new String(**ei.getInvoice()**)**;

Köszönöm a segítséget!

**Comment by NTCA-developer** [comment]
Ez remek hír, örülök hogy sikerült. Szívesen máskor is!
