### ISSUE TITLE
[DEV support]

### ISSUE THREAD

**Issue by AmrutaK1** [nav-gov-hu/Online-Invoice#129]
I am from the development team of A & F Invoicing application. In order to incorporate  Online Invoicing System 2.0 interface , we are implementing the SHA3-512 algorithm for hashing operation.
Can you please help us with the dependency details(groupId, artifactId, version) for the library to be used for this implementation?

**Comment by NTCA-developer** [comment]
Hi @AmrutaK1 

If you have no native support for SHA3 then I recommend to take a look at the BouncyCastle implementation for C# or Java at:https://www.bouncycastle.org/

**Comment by NTCA-developer** [comment]
As this ticket seem abandoned I'm closing it. Feel free to reopen it or create a new one if you have any further questions.
