### ISSUE TITLE
[FEATURE] /queryTaxgroup bővítés

### ISSUE THREAD

**Issue by connorhu** [nav-gov-hu/Online-Invoice#13]
Van-e mód arra, hogy lekérdezhetővé válljon a csoportazonosító, illetve a /queryTaxpayer válaszban esetleg megkapjuk a csoportazonosítót is?

**Comment by NTCA-developer** [comment]
Szia!

Alapvetően igen, csak kérlek segíts tisztázni az igényt. Melyik oldalról közelítenéd meg a kérdést, mire szeretnéd használni az eredményt? Ugye az ÁFA csoport saját adószámon szerepel az adóalanyok között. Az ÁFA csoportnak vannak tagjai és van 1 képviselője, akik szintén szerepelnek a saját adószámukon az adóalanyok között.

Azt szeretnéd tudni, hogy a lekérdezett adószám:
- melyik ÁFA csoportnak a tagja
- vagy amennyiben a lekérdezett adószám ÁFA csoport, akkor annak kik a tagjai

Ezen felül mindkét esetben kérdés, hogy szükség van-e a válaszban arra, hogy az ÁFA csoportnak ki a képviselője.

**Comment by connorhu** [comment]
Szia!

Az adószám szerinti adóalany keresést most arra használom, hogy kvázi validálom az adószámot új partner rögzítésekor, vagy adószámának változtatásakor.

Nem lenne rossz, ha le tudnám kérdezni, hogy az adószám mely csoporthoz tartozik. Ez azért hasznos, mert van amikor az új partner regisztrációjakor a partner adatok bekérésekor az ügyintéző nem kéri be a csoportazonosítót, az ügyfél meg nem tud róla/elfelejti, hogy neki azt is meg kell adnia. Ekkor az adószám megadásával rögtön javaslatként fel tudom dobni, hogy mi a csoportazonosító.
Ha csoportazonosítót kérek le akkor meg a tagokat lenne jó látni. Ha ez megvan akkor minden eshetőséget lefedtem.

A képviselőt nem látom feltétlen szükségesnek, mint inkább a csoport-tagok relációt.

**Comment by pvmon** [comment]
Szia!
Ebben a lekérésben a cégek hosszú neve mellett nem jöhetne le a cég rövidített neve is?
Pl: XYZ Kereskedemi és Szolgáltató Korlátolt Felelősségű Társaság helyet általában mindig van a cégjegyzékben is egy rövidített név a példánál maradva XYZ Kft.
(Ahogy a számlakérésnél lediktáljuk a rövidített cég nevét a félóráig gépelendő hosszú név helyett.)
Ezt csak nem kapjuk meg vagy a NAV-nál nincs is a rövidített név tárolva?

**Comment by NTCA-developer** [comment]
Szia!

De jó hogy mondod! Az adat természetesen megvan, mi már lassan egy éve behúztuk ezt az igényt magunkhoz (ha sorba állítjuk, kik örülnének neki nagyon, akkor az Online Számlázó biztosan a sor elején lenne) de más függőség miatt még nem tudjuk az adatot biztosítani kifelé. (a master data management minősített esete áll fenn)

Ami miatt örülök hogy felvetetted, hogy opcionálisként behúzom a 2.0-ás sémába, hogy amikor elkészül, már meglegyen a helye. Ugyan ez szerintem nem mostanában lesz kész, de ettől függetlenül mi tegyük meg, amit meg lehet.

**Comment by NTCA-developer** [comment]
> Nem lenne rossz, ha le tudnám kérdezni, hogy az adószám mely csoporthoz tartozik.

Ennek nincs különösebb akadálya, felveszem boardra.

> Ha csoportazonosítót kérek le akkor meg a tagokat lenne jó látni. Ha ez megvan akkor minden eshetőséget lefedtem.

Hát erre aludnom kell egyet, kicsit overkillnek érzem mint funkció. Jól gondolom, hogy ha a kettőből kellene egyet választanod, akkor az elsőt választanád? (ezért is kérdeztem, hogy mire használnád)

**Comment by connorhu** [comment]
> Hát erre aludnom kell egyet, kicsit overkillnek érzem mint funkció. Jól gondolom, hogy ha a kettőből kellene egyet választanod, akkor az elsőt választanád? (ezért is kérdeztem, hogy mire használnád)

Ez csak a teljesség igényével került be. Ha csak a validálási igényt nézem, akkor elég az adószám -> csoport reláció mutatása. Csoport -> adószám(ok) irány UX-t segítene csak.

**Comment by NTCA-developer** [comment]
Rendben, akkor egyelőre maradjunk ebben. Ha egyszer hangos tömeg fogja követelni a másik ágat is, akkor külön operációban majd felvesszük az aktuálisan támogatott API funkciói közé.
