### ISSUE TITLE
[Q&A] Devizás számla, HUF értékek

### ISSUE THREAD

**Issue by szako** [nav-gov-hu/Online-Invoice#130]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**

Két kérdésem lenne a devizás számlák ÁFA tartalmával kapcsolatban:

Devizás számlánál sem tétel szinten, sem ÁFA összesítő szinten, sem szumma szinten nincsenek nyilvántartva a HUF értékek a rendszerben. Ami nem kalkulatív az az összes ÁFA tartalom, ami ismert számla szinten. A 2.0-ban a számolás során az árfolyam segítségével számoljuk a HUF értékeket. A kérdésem az lenne, hogy elfogadott-e tört HUF értékekeket megadni vagy törekedni kell a kerekítésre (pl. tétel bruttó szintjén?, szumma bruttó szintjén?).

Küldtem már be ilyen számlát, figyelmeztető üzenetek nélkül, de valószínű kerekítési határon belül voltak az értékek. Viszont a beküldésnél a tételes HUF ÁFA tartalmak összege nem egyezett a számla HUF ÁFA tartalmával (347 Ft <> 346,9368 Ft) Mi az ajánlás (ha van ajánlás), milyen egyezőségre kell törekedni?

A példa XML nem válaszolta meg a kérdéseimet, mert minden egész számra jött ki.

**Comment by NTCA-developer** [comment]
Szia @szako 

Továbbítom a kérdésed a szakmai területnek, a türelmedet kérem.

**Comment by NTCA-developer** [comment]
Szia!

Ezt a választ kaptam vissza. 

> Devizás számláknál a számla kötelező adattartalma az ÁFA összege forintban, ebből az értékből számolható az árfolyam, majd az összes többi forintban kifejezett érték (mint ahogy a kérdésben is szerepel). A számított forint összeg feltüntethető egészre kerekítve vagy két tizedesjegy pontossággal is, a MonetaryType típusra vonatkozó megszorítások szerint. Az erre vonatkozó figyelmeztetés az 1070-es számú, pontos működése a specifikációban olvasható. Éppen a kerekítésekre figyelemmel tolerál 1%-nyi (de legalább 1 egységnyi) eltérést.

Ez maradéktalanul megválaszolja a kérdésed?

**Comment by szako** [comment]
Köszönöm a választ. Ha további kérdésem van, akkor jelentkezem.
