### ISSUE TITLE
[Q&A] Adómentes jelölés WARN üzenet

### ISSUE THREAD

**Issue by medve1400** [nav-gov-hu/Online-Invoice#131]
Szép jó napot!
Az olyan számlák, amik tartalmaznak ÁFA mentes tételt, azokra kapok egy INCORRECT_SUMMARY_DATA_VAT_EXEMPTION üzenetet. Ezt az esetet hogyan lehet orvosolni? Vagy én mit rontok el? Mert a vatExemption tag az rendben van hogy azzal kell jelölni, csak akkor a másik mondjuk 27%-os összesítésben is kell használni ezt a tag-et? A #83 issue-ban olvastam, hogy már kértek példa XML-t gondolom még nem készült el.
Hasonló eset a fordított ÁFA-s, illetve az Áfa törvény hatályán kívüli tételeknél is.

Köszönöm
Tamás

**Comment by NTCA-developer** [comment]
Szia @medve1400 

Tudsz nekem olyan adószám+számlaszám értéket mondani, amire kaptad a fent nevezett warningot? Küldtél már be a tesztre ilyet? Először megnézném a számlát mielőtt válaszolok.

**Comment by medve1400** [comment]
Igen azt elfelejtettem írni, hogy teszt környezetben próbáltam.
Adószám: 23446197
Számla sorszáma: NFC-2020-2110
Tranzakciós id: 2V54HV75868YLVC2

**Comment by NTCA-developer** [comment]
Szia!

Köszönöm a példát, így már egyértelmű az eset. Szerintem alapvetően jól csinálod az adómentességi jelölést, csak egy dologban nem jó az XML.

Van a sémában egy nagyon jellegzetes típus, ezt mi egymás között is csak "6-os choice"-nak hívjuk. Ennek a becsületes neve VatRateType, és ennek az egyik lehetséges ága a vatExemption, ahol jelölöd az ÁFA mentesség jogcímét. A WARN amit kapsz azt ellenőrzi, hogy számlasor szinten amit beírtál ebbe a tagba, az disztinct értéken előfordul-e a számla összesítőben. A számlában amit írtál ezek az értékek vannak:

line: `<vatExemption>AAM</vatExemption>`
summary: `<vatExemption>true</vatExemption>`

A WARN nem csak logikailag vizsgálja, hogy ha sorszinten ki van választva vatExemption akkor a summary-ban is legyen ilyen, hanem az értékeiket is vizsgálja. Mivel AAM != true, jön a WARN.

Próbáld meg így és kérlek jelezz vissza hogy tényleg így van-e, mert nem néztem kódot csak az emlékeimre támaszkodom.

**Comment by medve1400** [comment]
Szervusz!

Köszönöm szépen jól emlékeztél :) én rontottam el az XML-t a summary résznél.
Le is zárom akkor az issue-t.
