### ISSUE TITLE
[Q&A] QueryInvoiceDigestResponse

### ISSUE THREAD

**Issue by BeczeT** [nav-gov-hu/Online-Invoice#132]
**A kérdés, amire választ szeretnék kapni**
A QueryInvoiceDigestRequest kérést a következő fejléccel küldöm:
<?xml version="1.0" encoding="ISO-8859-1"?>
<QueryInvoiceDigestRequest xmlns="http://schemas.nav.gov.hu/OSA/2.0/api">
A választ az alábbiak szerint kapom:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<QueryInvoiceDigestResponse xmlns="http://schemas.nav.gov.hu/OSA/2.0/api" xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/data">

A problémám az lenne, hogy nincs utalás a válaszban arra, hogy a beküldött számlák eredeti karakterkódolása milyen! Ha a válasz fejlécében látható UTF-8-ra hagyatkozom, akkor konverziót fogok elvégezni aminek az eredménye a magyar ékezetes karakterek esetén problémás. Azt pedig a szállítói számlák lekérésekor nem tudhatom, hogy a másik program hogy milyen kódolással küldte fel a számlát. A magam által beküldött számlák esetén tudom kezelni a problémát., Bejövő számlák esetén elemeznem kellene karakterről-karakterre a választ?

Becze Tibor

**Comment by BeczeT** [comment]
Bocs!

Elnyelte az első néhány sorom a fórum!

A QueryInvoiceDigestRequest kérést a következő fejléccel küldöm:
`<?xml version="1.0" encoding="ISO-8859-1"?>
<QueryInvoiceDigestRequest xmlns="http://schemas.nav.gov.hu/OSA/2.0/api">
`
A választ az alábbiak szerint kapom:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<QueryInvoiceDigestResponse xmlns="http://schemas.nav.gov.hu/OSA/2.0/api" xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/data">
`

**Comment by NTCA-developer** [comment]
Szia @BeczeT 

A REST API a rendszerben UTF-8 exkluzív, minden bejövő számlát automatikusan erre konvertálunk is így is mentünk. Ezért a kiolvasáskor is arra kell számítanod, hogy az encoding UTF-8 lesz, ezért nincs erre külön információ feltüntetve.

Az interfész dokumentáció 1.7.3 része tartalmazza ezt, lehet hogy nem elég hangsúlyosan, ha a kérdés felmerült.

**Comment by NTCA-developer** [comment]
És kihagytam, hogy a többi számlázóprogramnak is ezt az encodinget kellene használni.

**Comment by BeczeT** [comment]
Köszi!
Lehet, hogy én bénáztam. Szerintem kétszer konvertáltam.
Becze Tibor
