### ISSUE TITLE
[Q&A]Vevő adószáma nem létezik WARN üzenet

### ISSUE THREAD

**Issue by adoszam** [nav-gov-hu/Online-Invoice#133]
Szép jó napot!
Sikeres és helyes adatszolgáltatás teljesítéséhez lenne szükségem megoldásra.
Probléma a következő:
Adatszolgáltatás Vevő adószáma nem létezik WARN üzenettel jön vissza. 
Az esetek előfordulása: minden esetben a vevő önkormányzati gazdálkodó szervezet, ami az Államkincsár törzskönyvi nyilvántartó rendszerében nyilvántartott, létező adóalany. Ebben a nyilvántartásban ott van a gazdálkodó szervezet adószáma. A NAV áfa alanyok lekérdezésben "Nincs ilyen", az adószám lekérdezésben pedig "A megadott adószám nem található az aktuális adatbázisban" válasz érkezik. Call center adóalany nyilvántartás informatikáról kapott és továbbított válasza alapján a szervezetek állapotkódja okozza a problémát. Sem mint szállító adóalany, sem mint vevő adóalany nem tudjuk mit jelent az állapotkód és mit kellene tennünk a helyes adatszolgáltatás megoldása érdekében.
Válaszukat előre is köszönöm!

**Comment by NTCA-developer** [comment]
Szia @adoszam 

A teszt vagy az éles rendszeren tapasztalod ezt a jelenséget? Illetve, ha tudsz egy konkrét requestId-t mondani, amire ezt a WARN-t adtuk vissza az még segítség a szakmai terület részére.

**Comment by adoszam** [comment]
Szia NTCA-developer!

Az éles rendszeren tapasztaljuk ezt. A következő requestId-k esetében:
20200214T071825189Z
20200214T071946940Z
20200214T072039596Z
20200214T072116440Z
20200214T072154258Z
Köszönöm!

**Comment by NTCA-developer** [comment]
Szia! 

Köszönöm a tranzakció azonosítókat. Mondjuk én a beküldés azonosítójára gondoltam nem a státusz lekérdezésére, de így is megvan. :)

Ezt el kell küldenem az illetékes szakterületre, egyedül nem tudok rá mit mondani, a türelmedet kérem.

**Comment by adoszam** [comment]
Szia!
Rendben, várok türelmesen. Nagyon szépen köszönöm!

**Comment by NTCA-developer** [comment]
Szia!

Egyeztettem a szakmai területtel. Az volt a kérésük, hogy keresd meg őket közvetlenül a https://nav.gov.hu/nav/e-ugyfsz/levelkuldes címen és segítenek.

A ticketet majd zárd le kérlek.

**Comment by adoszam** [comment]
Szia!

Köszönöm, a lehetőséget! Ezt már megtettem és nem érkezett válasz :(  . De azért köszönöm, hogy foglalkoztál vele.
