### ISSUE TITLE
[Q&A] Verzió váltás 

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#135]
Nem felejtettetek el valamit? Erre gondolok: "A karbantartás végeztével frissítést teszünk közzé."
Fogalmunk sincs, hogy most mi van a teszt rendszeren, azon kívül, hogy 2.7. De mi van ebben? 
Kellene a doku, az az xsd, ami most fenn van a teszten és a changelog, ami lehet, hogy azonos a github-ossal, na de hol van abban kimondva, hogy az a 2.7?
Ez most akkor az élesre áttérés előtti utolsó verzió, vagy lesz még 2.8? 

Kérlek tegyétek fel az információkat minél előbb. Köszi.

**Comment by NTCA-developer** [comment]
Szia!

Bárcsak ez lenne a helyzet hogy elfelejtettük. Akkor most megcsinálnám és kimenne. De nem ez a helyzet, a publikálási folyamat tart még a verzióváltás híréről. Ugyan ez a helyzet az interfész dokumentációval is.

Ahogy korábban beszéltük, a 2.7 nem tartalmaz XML API-t érintő módosítást. És továbbra is lesz 2.8, amiben a Githubos XSD funkcionalitása van, kivéve a metrika lekérdezéseket, amik csak később fognak működni.

Igyekszünk!

**Comment by NTCA-developer** [comment]
Szia @kabelnet2 

Kikerült tesztre és élesre az új interfész dokumentáció, ami a Githubos commithoz tartozik. Az API sample fájlokat, a sémákat és a WADL-t is frissítettük a felületen, ezzel szinkronba került a két állapot egymással. A verzióváltásról szóló hír is bent van már a csőben.

Kérlek legyél proxy. Köszönöm szépen!

**Comment by NTCA-developer** [comment]
Szia @kabelnet2 

Elérhető a teszten a 2.8, benne az új API funkcionalitással. Használjátok bátran!

**Comment by NTCA-developer** [comment]
A doksi még le van maradva, de ki fog kerülni az is remélem hamarosan.

**Comment by zonehun** [comment]
A 2.0-ás API élesítésének idejéről van esetleg információtok? 02.04-es napló üzenetben február közepére jósoltátok. Köszönöm, ha tudtok pontosabb dátumot küldeni.

**Comment by NTCA-developer** [comment]
Szia @zonehun 

Én per pillanat annyit tudok, hogy valamikor jövő héten lesz, mivel a telepítéshez kell egy nagy leállás. Amit megvan a hivatalos hír ki fog kerülni a holnapra, de persze én is beírom ide is majd szívesen.

**Comment by zonehun** [comment]
Köszönöm szépen!

**Comment by kabelnet2** [comment]
Kellene egy update az 'Informatikai változásokra' is, mert sokakat nem érdekel a github :)

**Comment by NTCA-developer** [comment]
Tudom, most kaptam meg a jóváhagyott szöveget. Csinálom.

**Comment by NTCA-developer** [comment]
Kész, kint van a release notes a felületen.

**Comment by kabelnet2** [comment]
Köszi!

**Comment by NTCA-developer** [comment]
Sziasztok!

Most héten csütörtökön, azaz 02.27-én 18 órától tervezzük az éles környezet leállítását. A tervezett állásidő 5 óra, a 2.0-ás XML API a visszaindítást követően lesz használható az éles környezetben.

**Comment by zonehun** [comment]
Köszönöm az átállás időpontját! Akkor a következő hét hétfőtől már az új séma szerint küldünk ;)
