### ISSUE TITLE
[DEV support] Felületen kezdeményezett technikai érvénytelenítés tranzakció azonosítójának lekérdezése

### ISSUE THREAD

**Issue by HWKF** [nav-gov-hu/Online-Invoice#136]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[x] /manageAnnulment
[x] /manageInvoice
[x] /queryInvoiceCheck
[x] /queryInvoiceData
[] /queryInvoiceDigest
[x] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[x] 2.0

**A requestId értéke / requestId value**
```

```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Az Online Számla tesztkörnyezetben indított technikai érvénytelenítés indítási állapota nem kérdezhető le az API keresztül. Az ANNULMENT_IN_PROGRESS hibakódot csak akkor kapjuk meg, ha az API keresztül indítunk ugyanarra a számlaszámra egy újabb technikai érvénytelenítést. És emiatt a saját program felhasználói felületén nem lehet jelezni, hogy tech. érv. van folyamatban, és így nem tudjuk figyelni az állapotát sem.
Jó volna ha az ANNULMENT_IN_PROGRESS hibakódot a queryTransactionStatus, a manageInvoice, a queryInvoiceData/Check operációk is visszaadnák a OSZ felületről indított tech. érv. transactionId-jával együtt, amely így lehetővé tenni a tech. érv. állapot státuszainak a lekérdezését.

*Egyéb tartalom / Additional content*

**Comment by NTCA-developer** [comment]
Szia @HWKF 

Működni fog, a /queryTransactionStatus operációban olyan transactionId értéket kérdezz le, amit a /manageAnnulment válaszában kaptál! Ekkor lesz megképezve az a csomópont ami a technikai érvénytelenítés státuszait tartalmazza. Ugyan itt fogod látni a változást akkor, amikor a felületen döntesz a technikai érvénytelenítés elfogadásáról vagy elutasításáról.

**Comment by HWKF** [comment]
Szia.
Ezt értem.
Ez így van, ha én indítok az API keresztül egy manageAnnulment operációt. Azzal nincs is gondom.
De ha az OSZ webes felületéről indítanak egy technikai érvénytelenítést, akkor annak elindításáról nem kapok információt az API keresztül és nem is tudom lekérdezni az APIval.

**Comment by HWKF** [comment]
Próbálok kigyűjteni requestID-kat a pénteki próbálkozásokból

**Comment by NTCA-developer** [comment]
Párhuzamosan használja valaki a te számlázódat meg az OSZ-t? Mert az OSZ-ben csak a saját OSZ-ben kiállított számlákra lehet technikai érvénytelenítést kezdeményezni. Ekkor viszont miért akarna a te számlázóprogramod értesülni erről? (mert ekkor nyilván az OSZ-ben kell az újrabeküldést is megcsinálni)

**Comment by HWKF** [comment]
Nekem sikerült, hogy az én számlázómból az APIn keresztül beküldött adatszolgáltatást a webes OSZ felületről is tudom érvényteleníteni a másodlagos felhasználómmal.
Nem használja senki, fejlesztem az OSZ v2-t és kipróbáltam, hogy tudom-e érvényteleníteni a webes OSZből és hogy erről kapok-e vissza információt.

**Comment by HWKF** [comment]
RequestIDk: 2VC1STXARWPVXG75, 2VC1WET2U6FEOKVX, 2VC1YOL6PU0N9U6G, 2VC20VILGSWUZT3Z, 2VC22G0VHHWJWWA0, 2VC25S3IHTRZRQ0R
Ez egy folyamat több eleme. A kapcsolódó technikai felhasználó és másodlagos user, illetve a számlaszám alapján láthatjátok az indított műveleteket.

**Comment by HWKF** [comment]
Ez egy folyamat több eleme. A kapcsolódó technikai felhasználó és másodlagos user, illetve a számlaszám alapján láthatjátok az indított műveleteket.
RequestIDk: 42941E7CA604D3A0D41A6B509104D7, 42942E9C700EFB41A494DBB67851FC

**Comment by HWKF** [comment]
Egy mai folyamat tranzakciós listája: a kapcsolódó technikai felhasználó és másodlagos user, illetve a számlaszám alapján végigkövethető a folyamat.
Tranzakciós id-k: 2VC1STXARWPVXG75, 2VC1WET2U6FEOKVX, 2VC1YOL6PU0N9U6G, 2VC22G0VHHWJWWA0, 2VC25S3IHTRZRQ0R
Az első, utolsó request id: 42941E7CA604D3A0D41A6B509104D7, 429701DEB3D0F9DBF414CAC7D7C5D4

**Comment by NTCA-developer** [comment]
Értem. Azt hiszem szótár eltérésünk van, én az OSZ alatt a NAV Online Számlázót értem, te pedig csak simán az Online Számla rendszer frontendjét. Így valóban lehetséges a technikai érvénytelenítés.

Ebben az esetben 2 dolgot tehetsz. Az egyik hogy a számlázóprogramban engedsz kézi bevitelt a tranzakció azonosítóra és úgy kérdezed le az adatokat. A felhasználó számára a felületről indított technikai érvénytelenítéshez tartozó transactionId hozzáférhető, az Adatszolgáltatások listaképernyőn, csak ezt kell átmásolnia a számlázóprogramba.

A másik segítséged a /queryTransactionList operáció lesz. Ennek az XSD-je Githubon már fent van, és nagyon-nagyon remélem hogy a hozzá tartozó dokumentáció is kijön ma. Ezzel tudod a transactionId-ket listásan lekérni API-ból is. Annak a ténye sajnos nincs benne, hogy az adott tétel technikai érvénytelenítést tartalmaz-e vagy sem, de idő alapú szűréssel talán megoldható a dolog, ha már a felhasználó "kétfelé" dolgozik.

**Comment by HWKF** [comment]
Próbáltam fentebb javasolni, hogy pl. a queryTransactionStatus operáció esetén, ha érvénytelenítés van folyamatban, akkor minden státusz mellett legyen benne az annulmentData node. Így minden esetben tudnánk róla. Ezt még DONE esetén is le lehessen megkapni. Javasolt kiegészítés még a annulmentData node kibővítése a transactionID-val, amely az érvénytelenítés tranzakció IDját adná vissza. Így könnyen össze lehetne kapcsolni.
Illetve javaslat még a QueryInvoiceCheck/Data operációk esetén a ANNULMENT_IN_PROGRESS hibakód visszaadása.
Eddig a státuszok tiszta folyamat változást mutattak. Úgy gondoltam, hogy az érvénytelenítés státuszai végstátuszok lesznek. Viszont elég zavaró a PROCESSING, a SAVED mellett visszakapni az érvénytelenítés státuszát.

**Comment by NTCA-developer** [comment]
> Eddig a státuszok tiszta folyamat változást mutattak. Úgy gondoltam, hogy az érvénytelenítés státuszai végstátuszok lesznek. Viszont elég zavaró a PROCESSING, a SAVED mellett visszakapni az érvénytelenítés státuszát.

A technikai érvénytelenítés státuszai közül a VERIFICATION_DONE és a VERIFICATION_REJECTED értékek végállapotok. Ellenben a technikai érvénytelenítés maga is egy autonóm aszinkron tranzakció, amit fel kell dolgozzunk. Ezért kaphat ugyan úgy PROCESSING és egyéb státuszokat, ez kvázi előfeltétele annak, hogy a technikai érvénytelenítés VERIFICATION_PENDING állapotba kerülhessen. Én nem találom ezt zavarónak, bár nyilván én ismerem a backended jobban, szóval lehet nem én vagyok a legjobb példa. 

Noha nem tetszik az ötlet, de lehet azon gondolkozni, hogyan kössünk össze még mit-mivel, de azt tegyük hozzá hogy az maga egy edge-case, amikor a user számlázóprogramból számlázik de a felületen kezdeményezi a technikai érvénytelenítést és nem pedig ugyan onnan, ahonnan a számlát is beküldte korábban.

Kicsit szeretnék meditálni rajta ha nem baj, most túl nagy a háttérzaj a fejemben.

**Comment by HWKF** [comment]
Rendben. 

Csak néhány gondolat ami felmerült bennem:
Nem kézenfekvő szerintem, hogy mindenki implementálja a technikai érvénytelenítést a saját programjában. Mondván, hogy az OSZ frontend felületén elvégezhető minden lépése. Mint a dokumentációban is írtátok: "_A technikai érvénytelenítésének képességét, mint funkciót nem kötelező implementálni a számlázó programokban, tekintettel a kézi javítás lehetőségére_."
Nálunk azért indult el a fejlesztése, mert anno az OSZ frontendben nem lehetett végrehajtani. Ha az elején elérhető lett volna a funkció, akkor valószínűleg teljesen kimarad.

Viszont az probléma szerintem, hogy az OSZ frontendben kiadott érvénytelenítést nem igazán lehet összekapcsolni a számlával az API oldalán. Igazából miből tudom meg az API oldalon, hogy egy számla érvénytelenítve lett? 
Egy adatszolgáltatás beküldésének státuszát addig csekkoljuk, amíg DONE vagy ABORTED státuszban nem kerül, de utána nem csekkolhatok a végtelenségig, hogy történt-e érvénytelenítés.
Végül is talán ezért jó, hogy anno az implementálásnál maradtunk, mert így legalább az API keresztül indított érvénytelenítések összekapcsolása nem jelent gondot.

Javaslat a QueryTransactionList lekérdezés paraméreihez: 
- számlaszám megadása: ez esetben a számlaszámhoz tartozó tranzakciókat adja vissza
- esetleg ez az eredeti alap számlával, amely esetben a számlalánc tranzakcióit képes visszaadni (erre a ChainDigest nem képes)
- valamint az OSZ frontend felületén az Adatszolgáltatások menüpontban lévő opciók megadásának lehetősége a lekérdezés paramétereként: 
-- státusz
-- technikai érvénytelenítés (igen/nem)
-- forrás
-- más felhasználók által indított tranzakciók, vagyis kizárva a lekérdező technikai felhasználó adatai
Így talán könnyebb volna csekkolni, hogy történt-e valami, ami máshonnan kezdeményeztek.
Valamint a Response-ban jó lenne megkapni, hogy Technikai érvénytelenítéshez tartozik-e a tranzakció. Bár ha a szűrésben meg lehet adni, akkor nem biztos, hogy ez szükséges.

Valamint felmerül a kérdés, hogy az érvénytelenítés tranzakciójáról hogyan tudom meg, hogy melyik számlához tartozott?

**Comment by HWKF** [comment]
"_Valamint felmerül a kérdés, hogy az érvénytelenítés tranzakciójáról hogyan tudom meg, hogy melyik számlához tartozott?_" Közben rájöttem, hogy a tranzakció állapot válasza tartalmazza a kapcsolodó számlákat.

**Comment by HWKF** [comment]
Mikortól lesz elérhető a QueryTransactionList operáció?

**Comment by NTCA-developer** [comment]
A teszten ma délutántól, élesen jövő hét valamikortól.

**Comment by NTCA-developer** [comment]
Szia @HWKF !

Akkor megpróbálom összefoglalni. Felületről kezdeményezett annulment tranzakció azonosítóját és annak feldolgozási státuszát szeretnéd API-ból lekérdezni. Szerintem a /queryTransactionList segít magukról a transactionId-kről tudomást szerezned, a többi információ pedig elérhető a /queryTransactionStatus operáción belül. Ez megoldja a problémád, nézted már hogy működik?

**Comment by HWKF** [comment]
Szia!

Köszönöm a segítséget. Úgy tűnik, hogy elegendő lesz az operáció a jelenlegi állapotában. Viszont átgondolva, így nem csak a felületről kezdeményezett érvénytelenítésekről kapunk infót. Így általánosabb fejlesztést igényel a megvalósítása. Igen eredetileg csak annyit szerettem volna.

A queryTransactionList fejlesztése folyamatban. Jelenleg a lekérdezés megy, a feldolgozás folyamata tervezés alatt.

Gond az (ha jól emlékszem), hogy egyes partnereinknél a technikai felhasználót nem csak nekünk adták meg, hanem más programokkal közösen használjuk. Így sajnos a kérésem, hogy e szerint lehessen szűrni, elvethető.

Jelenleg nem tűnik problémásnak az összes tranzakció lekérése adott időszakonként.

Jelen tervezett szerint azonosítási lépések:
1) létezik-e nálunk a transactionID, és arról van-e újabb info
2) ha nem, akkor queryTransactionStatus: Ebből meg tudom, hogy érvénytelenítés-e. Ha igen, akkor benne van minden info.
3) ha viszont nem, akkor kell egy queryInvoiceDigest lekérés transactionID alapján, hogy megtudjam, hogy melyik számlához kapcsolódik a tranzakció. Ez akkor lehet hasznos, ha számla elkészült, viszont az adatszolgáltatás valamilyen oknál fogva nem tudott elkészülni, és kézzel rögzítették a számlát. Itt viszont mint írtam a tech. felhasználó nem valószínű, hogy minden esetben egyértelműsíti a mi programunkat, így a számla adatokból kell visszaellenőrizni, amihez a Digest elegendő lesz.

Kérdés, hogy ha egy adott időszakra lekérdezett listába egy tranzakció bekerül, akkor azzal ott valamilyen művelet történt. Valamint az InsDate mindig a tranzakció keletkezési időpontját jelenti. Azaz ha egy tranzakció pl. PROCESSING státuszig jutott, akkor az adott időszakban erről kapok infót. Ha a következő időszakban lekérdezem a tranzakció listát, akkor abban az esetben meg kaphatom újra ezt a tranzakciót, ha közben eljuott pl a DONE státuszig. Jól értem a folyamatot?

Megjegyzés: A "Source" elemnek az APIban négy lehetséges értéke van, viszont a felületen 5 lehetőség van a szűrésnél.

**Comment by HWKF** [comment]
Viszont egy számla vagy az alapszámlához tartozó számlalánc tranzakcióinak lekérdezése egy ellenőrzési folyamathoz hasznos lenne. Mert ez másképpen nem valósítható meg. A queryInvoiceData és a queryInvoice(Chain)Digest operációk csak a számlák utolsó, beküldő tranzakcióit adják vissza.

**Comment by NTCA-developer** [comment]
Szia!

> Kérdés, hogy ha egy adott időszakra lekérdezett listába egy tranzakció bekerül, akkor azzal ott valamilyen művelet történt. Valamint az InsDate mindig a tranzakció keletkezési időpontját jelenti. Azaz ha egy tranzakció pl. PROCESSING státuszig jutott, akkor az adott időszakban erről kapok infót. Ha a következő időszakban lekérdezem a tranzakció listát, akkor abban az esetben meg kaphatom újra ezt a tranzakciót, ha közben eljuott pl a DONE státuszig. Jól értem a folyamatot?

Igen. Az insDate a beszúrás időpontja, és ha a kérdéses időpillanat már eltelt, akkor a listázás az adott intervallumra mindig konzisztensen ugyan azokat a tételeket adja vissza, az egyes tételek nem fognak elvándorolni a listáról ha a feldolgozottságuk meg is változik.

> Viszont egy számla vagy az alapszámlához tartozó számlalánc tranzakcióinak lekérdezése egy ellenőrzési folyamathoz hasznos lenne.

Nézd meg kérlek a /queryInvoiceDigest operációban a mandatoryQueryParams/originalInvoiceNumber lekérdezés működését, ez pont ezt csinálja: visszaadja azon számlák kivonatos elemeit, amelyek a számlaláncot felépítik. A response egyik eleme a transactionId.

**Comment by HWKF** [comment]
Szia!

1) Az említett tranzakciós lista lekérdezéseknél a két időszak, egymás utáni időszakra vonatkozik és nem ugyanarra az időszakra vonatkozó ismételt lekérdezésre.
2) A Digest operációk minden számla esetében egy tranzakciót adnak vissza, a legutolsót.

Azaz adott 3 tranzakció ugyanarra a számlára: 1) manageInvoice, 2) manageAnnulment, 3) manageInvoice. Vagy lehet, hogy a 3. hiányzik (vagy van egy negyedik manageAnnulment is). A javaslat arra vonatkozott, hogy ezeket szeretném visszakapni, mintegy ellenőrzésként. Mert lehet, hogy az első a mi számlázónkban történt, a többi meg a felületen. Ezt elég nehéz összevadászni. Ebből én annyit látok, hogy beküldtem, de ha lekérdezem, akkor érvénytelen. A queryTransactionList csak akkor használható igazából, ha beindítom és onnantól fogva folyamatosan kérdezek le. De akkor is csak akkor lesz meg a fenti információ, ha én megőrzöm a korábbi tranzakciók adatait.

**Comment by NTCA-developer** [comment]
Nem állítom hogy értem az utolsó hozzászólást, már az első pontnál elveszek. De a megértésem a ticket egészét érintve az, hogy hallgatólagosan maradunk a mostani állapotban. Ha mégsem így van akkor kérlek nyisd újra és beszéljünk.
