### ISSUE TITLE
[Q&A] Negatív elszámoló számla

### ISSUE THREAD

**Issue by gzsolnay** [nav-gov-hu/Online-Invoice#137]
A 2.0 újabb verziójában (kezdetekben nem tapasztaltuk) új WARN jelent meg: „INCORRECT_SUMMARY_DATA_INVOICE_NET_AMOUNT : Eredeti (CREATE) számla nettó összege nem lehet negatív.”
Elszámoló számlák esetén ez az üzemszerű működés, közmű cégeknél tömegesen lehetnek ilyen számlák. Mit lehet ebben az esetben tenni?

**Comment by szako** [comment]
Nagy +1, én is akartam ezzel kapcsolatban írni egy issue-t, csak megerősíteni tudom @gzsolnay-t.

**Comment by NTCA-developer** [comment]
Sziasztok!

A kevésbé IT jellegű kérdésekre mostantól van egy kijelölt Github user (@NTCA-tax ), aki közvetlenül tud nekünk segíteni, így sokkal hatékonyabb lesz a folyamat. Átettem rá a feladatot, majd válaszol ahogy az ideje (nem) engedi, mert ő is csak 100 különböző feladattal foglalkozik egyszerre.

**Comment by NTCA-tax** [comment]
A warningnak az az oka, hogy elvileg nem nagyon fordulhatna elő negatív összegű alapszámla. A jogszabály nem ismeri az elszámolószámla fogalmát, alapvetően az elszámolószámla egy korábbi időszakot korrigáló számla. A helyes jogszabályi eljárás az lenne, hogy a korábbi hónap(ok) számlája/számlái kerülnek korrigálásra. Amennyiben az adózó nem így jár el, hanem normál számlaként negatív összeget riportál, akkor a kérdésben említett warning üzenet kerül visszaadásra.

**Comment by KMGY100** [comment]
"" A jogszabály nem ismeri az elszámolószámla fogalmát""
Úgy gondolom , hogy nem az   "" elszámolószámla ""   mint  kifejezés a mértékadó jelen esetben,  (de köznyelvben használatos fogalom)   hanem az, hogy a jogszabály nem tiltja
a negatív előjelű számla kiállítását.   Ha igen akkor fel kellene tüntetni a jogszabályi hivatkozást a dokumentációban ( mint több más esetben ez meg is történik)
Szerintem sok-sok WARN-os számla keletkezik ezen oknál fogva .

**Comment by gzsolnay** [comment]
Konkrét példaként említettem a közmű cégek elszámolását, de akkor ne  elszámoló számlának hívjuk, hanem előlegek elszámolásnak, ahol szintén előfordulhat negatív előjelű számla

**Comment by betasofthu** [comment]
Csak egy példa a negatív összegű alapszámlára: egy hipermarketeket üzemeltető multi cégnek milliós értékben állítanak ki negatív összegű számlát az általa visszaküldött göngyölegekről. Több kiszállítás után az összegyűjtött,  visszaküldött göngyölegekről állítják ki ezt a számlát.  Az eredeti számla számla nem ismert, a göngyöleg nem beazonosítható,  tehát nem lehet korrekciós számlát kiállítani. Ez is WARN-os lesz.

**Comment by zonehun** [comment]
Fontos lenne ebben a kérdésben tisztán látni. Bizományos értékesítést folytató cégeink vannak, akiknél teljesen természetes és napi folyamat, hogy a korábban kiadott és kiszámlázott árut, ha nem sikerült értékesíteni, akkor csökkentett áron visszaveszik. Ilyen esetben szintén mínuszos számlákat készítenek.

**Comment by NTCA-tax** [comment]
Sejtettem, hogy ez egy nagyon érzékeny téma, számos társaságnak az "úgy szoktuk" elvébe ütközik. A felmerült kérdéseket adóhivatal oldaláról nem a gyakorlat (értsd így szoktuk) megközelítéséből validáljuk, hanem a jogszabály oldaláról.

Az áfa törvény a számlát, mint termék- vagy szolgáltatás értékesítés alapbizonylataként kezeli. Amennyiben egyszeri értékesítésről beszélünk, akkor nagyon nehéz értelmezni azt, hogy egy gazdasági tevékenységet végző entitás valamilyen terméket vagy szolgáltatást úgy értékesít, hogy még fizet is érte (persze a jogszabály nem zárja ki az logikátlan adózói tevékenységet). A negatív számlák ezért szinte minden esetben valaminek a következménye, és nem önállóan álló dokumentumok.

Amennyiben a fentieket elfogadjátok, akkor levezethető, hogy negatív előjelű számlának inkább számlával egy tekintet alá eső dokumentumnak kellene lennie.

Persze mondhattok nagyon sok olyan esetet, amikor a gyakorlatban (itt megint az így szoktuk elv jön be) negatív összegű számla kerül kiállításra, ugyanakkor az áfa törvény szempontjából ezt nehezen lehet logikusan levezetni. Azt, hogy mikor milyen adattartalommal kell a számlát kiállítani, nem szeretném a GitHub-on keresztül megvitatni, mivel ez már messze túlmutat a GitHub fórumunknak a céljain. A jogszabály magyarázatát az adott adatszolgáltatási kérdés erejéig próbálom korlátozni.

Fontos ugyanakkor látni, hogy számlázó program fejlesztőként nem lehet felelősséget vállalni az ügyfél hibás számla kiállítási gyakorlatának következményeiért. A számlázó programnak alapvetően a jogszerű számla kiállítási szabályokat kell támogatnia, ugyanakkor a felhasználó ezt a keretet átlépheti. Erre szoftver fejlesztőként nem mindig lehetséges felelősséget vállalni. A felvetett példák között is találok ilyen kérdést.

A fentiektől függetlenül az előleg-végszámla kérdését teljesen validnak látom. Itt van számomra egy zavaró kérdés, melyet a válaszom előtt mindenképp tisztáznom kell a kollégákkal. Addig ezzel türelmet kérek.

**Comment by tkelemen73** [comment]
Sajnos az előleg/végszámla körben ugyanez a helyzet adódik, itt is ugyanaz a figyelmeztető üzenet jön. Pl. bekértem a vevőtől 100 Ft előleget, arról kapott is előleg számlát, amiről meg is történt az adatszolgáltatás. Majd a a végszámla készítésekor kiderül, hogy csak 80 Ft-ba került a termék/szolgáltatás, amire a 100 Ft előleget szedtem be. Elkészül a végszámla, felhasználás 80 Ft, elszámolt előleg -100 (jelölve, hogy előleg típusú a tétel), számla végösszege így -20 Ft lesz. Kapom is rá a WARM üzenetet, nem lehet negatív.

**Comment by NTCA-tax** [comment]
Az előleg-végszámla kezelésével kapcsolatban a következő az adóhivatali álláspont: a vevő túlfizetését az előleg számla helyesbítésével kell korrigálni.

Tkelemen73 példáján keresztül tehát úgy kell eljárni, hogy a végszámlában 80 Ft-os terméket számlázunk ki, melybe beleszámít 80 Ft az előlegszámlából. Az előlegszámlára pedig egy számlával egy tekintet alá eső okiratot kell kibocsátani -20 Ft-tal.

**Comment by lvitya586** [comment]
Tehát jól értem, az adóhivatalnak az az álláspontja, hogy 1db végszámla helyett ki kell bocsátani egyszerre 2db bizonylatot? Ez milyen logikátlanság? Akkor ez alapján kéne a programokat is átalakítani, hogy ilyen esetben két bizonylat készüljön vagy bízzuk a tisztelt felhasználókra, hogy majd jól kezelik a helyzetet és megcsinálják egymás után a két bizonylatot?

**Comment by szecsenyizoltan** [comment]
Azt gondolom, hogy itt a jogszabályalkotóknak kellene segíteni a gazdaságot azzal, hogy életszerűbbre és a felhasználók számára könnyebbé tennék ezt a dolgot. Tényleg nagyon nehéz a valóságban lekezelni a jelenlegi szabályokat. Nagyon sok többlet terhet okoz.

**Comment by KMGY100** [comment]
@szecsenyizoltan 
@NTCA-tax 
""Azt gondolom, hogy itt a jogszabályalkotóknak kellene segíteni""
Nem..   jogszabály nem írja elő amit az NTCA-tax kifejtett. 
 Hogy őt idézzem:  ""adóhivatali álláspont"" ,   ez pedig nem
kötelezettség.
@tkelemen73 ékes példát vázolt fel  és sokaknak az az álláspontja.

**Comment by NTCA-tax** [comment]
Látom itt már kezdünk elvi kérdésekre áttérni, és néhány napja nem látok új kérdésfelvetést a negatív összegű számla adatszolgáltatásával kapcsolatban.

Adóhivatali oldalról a hatályos jogszabályokat tudjuk magyarázni, a jogszabályoknak megfelelő utat mutatni. Amennyiben valaki nem ért egyet ezzel az útmutatással, vagy más utat keres, az teljesen a saját felelősségébe tartozik. Az "adóhivatali álláspont" több személlyel egyeztetett álláspont, ezért így is érdemes erre tekinteni. 

Ezt az issue-t jelenleg lezárom, amennyiben van még a negatív összegű számla warning-val kérdés, akkor egy új issue-ban tovább folytathatjuk.

**Comment by MTYS87** [comment]
Sziasztok,
Sajnos nem találtunk megoldást erre a problémára, ezért szeretném kérni segítségeteket. Kereskedelmi cégnél is gyakori az úgynevezett jóváíró számla, mely esetben a végösszeg illetve minden elem a számlán negatív. Pl. tévedésből kétszer számlázunk ki szállítási költséget és 3 nap múlva derül ki, utólag már nem sztornózhatjuk.
Jelenleg a V1.1 verzióban is így használjuk jóváíró számláknál és nem kapjuk ezt a figyelmeztetést:

„INCORRECT_SUMMARY_DATA_INVOICE_NET_AMOUNT : Eredeti (CREATE) számla nettó összege nem lehet negatív.”

Előre is köszönöm!

**Comment by ghsyolko** [comment]
16 éve, 1-2 évenként, NAV ellenőrzés, a programot használó partnereknél (70-80) nem volt gond az "Eredeti (CREATE) számla nettó összege nem lehet negatív." Vajon mi lehet az eltérés az emberi ellenőrzés (nevezzük törvénynek) és a mostani gépi ellenőrzés között (nevezzük törvénynek)?

Köszönöm a választ.
