### ISSUE TITLE
[Q&A] unitPrice  és unitPriceHUF tagek opcionálisak vagy kötelezőek

### ISSUE THREAD

**Issue by KKARACSONY** [nav-gov-hu/Online-Invoice#138]
Sziasztok, 

Az lenne a kérdésem, hogy a unitPriceHUF mező opcionálisként van jelölve a specifikációban. 
Helyes az, hogyha a lineexpressionindicator= true és a unitPrice információt küldjük az XML struktúrában de a unitPriceHUF értéket nem küldjük? 

WARN és ERROR üzenetet nem kapunk rá. 

Köszönöm a választ!

**Comment by KKARACSONY** [comment]
Sziasztok, 
A példa XML-ben sem látom ezt a unitPriceHUF taget feltüntetve. 
Meg tudjátok légyszi ezt válaszolni? 

Köszi szépen!

**Comment by NTCA-developer** [comment]
Szia!

Köszönjük a kérdést! Utánakérdezünk és visszajelzek.

**Comment by connorhu** [comment]
Sziasztok,

Az adott taggal kapcsolatban halkan megjegyezném a következetlen elnevezést. :)
unitPriceHuf kéne legyen.

**Comment by NTCA-developer** [comment]
Szia @connorhu 

Attól függ hogyan nézed. A sémában használt camelCase szintaktikát sérti, viszont a forint megjelölés következetesen mindenhol HUF. Az üzleti területnek ez jobban tetszett, mert jobban hangsúlyozza a pénznem jelleget.

**Comment by NTCA-tax** [comment]
Elnézést, hogy ezt a kérdést ilyen sokáig nem tudtam megválaszolni.

A unitPriceHUF nem az Áfa törvény szerint a számla kötelező eleme, ugyanakkor ha természetes mértékegységben kifejezhető az adott tételsor, akkor kötelezően meg kell adni. Függetlenül attól, hogy hibajelzés nem történik, attól még a specifikációnak nem felel meg, hogy a unitPriceHUF nem kitöltött.

A példa XML-el kapcsolatban köszönjük a jelzést. Sajnos tényleg hibás a példa, a javításán dolgozunk.

**Comment by szako** [comment]
Ha "kötelező" a mező töltése ebben az esetben, akkor nem kéne figyelmeztetést kapni?
