### ISSUE TITLE
[FEATURE] /queryInvoiceData vevőoldali számlalekérdezés/letöltés

### ISSUE THREAD

**Issue by csaszko** [nav-gov-hu/Online-Invoice#14]
Szia, 

Vevő oldali számlalekérdés esetén, terveztetek-e bármi értesítést küldeni egy új számla feltöltéséről, ha igen akkor hogyan?

Javasolt lenne egy kliens oldalról állítható változó létrehozása, valamint erre API-n keresztűl szűrési lehetőség is, az új beérkezett számlákkal kapcsolatban. pl isDownloaded true/false

**Comment by NTCA-developer** [comment]
Szia!

Arra gondolsz, hogy valami feliratkozás szerűségen keresztül küldjünk értesítést a számlán szereplő vevőnek, hogy feldolgoztunk egy rá kiállított adatszolgáltatást? 

A kérdésedre válaszolva egyébként nem gondolkodtunk ezen, ez egy elég komoly bróker szolgáltatás volna, amit nem biztos, hogy nekünk kell nyújtani.

**Comment by csaszko** [comment]
Szia, 

Igen, ilyesmire. Ha jól értelmeztem a dolgokat akkor le lehet tölteni majd a vevő oldali számlákat úgy, hogy az időszak lekérdezésével megkapod a számlaszámot és számlaszám alapján tudod egy külön operációban letölteni az adatokat? Gondolom ezt sokan fogják használni automata feldolgozásra és ezért jó sok kérés fog beesni a szerverre feleslegesen, mert csak intervallumra lehet igazából szűrni és abból megkapni a számlaszámot. Ha ezekre a kérésekre pluszban fel van készülve a rendszer akkor végülis mindegy, hogy mennyiszer futunk neki a lekérdezésnek.

**Comment by csaszko** [comment]
#9  igazából itt is erről van szó.

**Comment by NTCA-developer** [comment]
Értem, akkor ezt lezárom duplikáltság miatt ha nem haragszol érte.

**Comment by csaszko** [comment]
Oké, köszi.
