### ISSUE TITLE
[DEV support] /queryInvoiceChainDigest nem elérhető

### ISSUE THREAD

**Issue by balintdozsa** [nav-gov-hu/Online-Invoice#140]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionStatus
[] /tokenExchange
[x] /queryInvoiceChainDigest

**A kérés verziója / version of the request**
[] 1.1
[x] 2.0

**A requestId értéke / requestId value**
```
RID014426900158211293280483
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
A queryInvoiceChainDigest végpont nem elérhető, 503 Service Unavailable hibát ad.

*Egyéb tartalom / Additional content*

**Comment by NTCA-supporter** [comment]
Szia!

A dokumentáció megelőzte a funkciót :) Várhatóan a holnapi nap folyamán kerül ki teszt környezetre az említett szolgáltatás. 2.8 verzióban fog szerepelni.

Zárhatom az issuet?

Köszi

**Comment by balintdozsa** [comment]
Szia!

igen, köszi!
