### ISSUE TITLE
[DEV support] /queryInvoiceDigest - originalInvoiceNumber probléma

### ISSUE THREAD

**Issue by balintdozsa** [nav-gov-hu/Online-Invoice#141]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceCheck
[] /queryInvoiceData
[x] /queryInvoiceDigest
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[x] 2.0

**A requestId értéke / requestId value**
```
RID012837600158211351558463
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Az új invoiceApi.xsd-ben az originalInvoiceNumber típusa "data:SimpleText50NotBlankType", de ezt a queryInvoiceDigest végpont nem fogadja el a teszt rendszerben. Helytelen kérés! (INVALID_REQUEST) hibaüzenetet ad.

*Egyéb tartalom / Additional content*
```
<invoiceQueryParams><mandatoryQueryParams><originalInvoiceNumber>ZZZ900001</originalInvoiceNumber></mandatoryQueryParams></invoiceQueryParams>
```

**Comment by NTCA-supporter** [comment]
Szia!

Itt is a dokumentáció megelőzte a funkciót :) Várhatóan a holnapi nap folyamán kerül ki teszt környezetre az említett szolgáltatás változtatása. 2.8 verzióban fog szerepelni.

Zárhatom az issuet? Ha a verzió kitelepítese után is tapasztalsz problémát, akkor nyisd újra nyugodtan.

Köszi

**Comment by balintdozsa** [comment]
Szia!

Igen :-)
