### ISSUE TITLE
[DEV support] /queryInvoiceData - curl error 56

### ISSUE THREAD

**Issue by balintdozsa** [nav-gov-hu/Online-Invoice#142]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceCheck
[x] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[x] 1.1
[] 2.0

**A requestId értéke / requestId value**
```
RID099129100158204404285869
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
A queryInvoiceData végpontra a curl 56-os hibát ad. Érdekes módon a többi végponttal nincs semmi gondunk, és ez a végpont is működik más szerverekről. Utána tudtok nézni, hogy a ti részetekről rendben volt-e ez a kérés?

*Egyéb tartalom / Additional content*

**Comment by NTCA-developer** [comment]
Szia @balintdozsa

Ezen a ponton nem tudok még segíteni. Ugyanis ha a beküldés nem sikerült nálad, akkor a request nem jutott el a szerverig, tovább egyenlő alkalmazás log sincs róla. Azt pedig kérlek ne kérd, hogy tűzfal logból találjam meg a TCP handshake logjait, nem áll arányban a ráfordítás a nyereséggel.

Abban egyetértek veled, hogy ez biztosan nem általános, hanem egyedi probléma, valami valahol el van írva. Nálam ez a curl hiba általában akkor történik, amikor a port számot rontom el a kérésben.

**Comment by balintdozsa** [comment]
Szia @NTCA-developer !

A mai napon ismételten belefutottunk több helyen is ebbe a problémába, és csak a queryInvoiceData végponttal van probléma (1.1 és 2.0 alatt is!). Mivel minden hívást ugyanazok a függvények állítanak elő, így felettébb érdekes, hogy csak a queryInvoiceData végpontnál, és csak bizonyos számlák esetében jutunk erre a hibára (de a problémás számláknál konzisztensen). Az esetek több mint felében viszont működik, ugyanakkor több, teljesen különböző környezetnél is jelentkezik a probléma.

A fenti requestId-ra nálatok nincs semmi olyan információ, ami segíthetne?

**Comment by NTCA-supporter** [comment]
Szia @balintdozsa

Utána néztem a fenti requestId-nak és semelyik szerver oldali logban sem találtam meg, így még mindig áll az mondásunk, hogy nem jutott le a kérés a szerverig.

**Comment by NTCA-supporter** [comment]
Szia @balintdozsa !
Itt történt valami előrelépés?
Zárhatom az issuet, vagy kell még tőlünk info?
Köszi

**Comment by balintdozsa** [comment]
Szia!
Köszi, zárhatjuk.
