### ISSUE TITLE
[Q&A] /queryInvoiceChainDigest 1.1-es információt is visszaad?

### ISSUE THREAD

**Issue by balintdozsa** [nav-gov-hu/Online-Invoice#143]
Egy gyors kérdésünk még lenne a queryInvoiceChainDigest végponttal kapcsolatban: 1.1-en beküldött módosító számlákat is beleveszi a modificationIndex-be?

**Comment by NTCA-supporter** [comment]
Szia!

Ha megnézed a response-t az XSD-ben, akkor láthatod, hogy az invoiceReferenceData-n belül van egy choice, vagy a modificationTimestamp (1.x számlák esetén töltött) vagy a modificationIndex (2.0 számlák esetén töltött) tag lesz töltve. 
Ezzel megválaszoltam a kérdést?

Köszi

**Comment by balintdozsa** [comment]
Igen, köszi!
