### ISSUE TITLE
[Q&A] szállítói számlák lekérdezésének lehetősége

### ISSUE THREAD

**Issue by connorhu** [nav-gov-hu/Online-Invoice#144]
Sziasztok!

Mivel most már kötelező lesz minden számlát beküldeni a navnak, tervben van-e olyan lekérdező funkció ami az adatszolgáltatónak kiállított számlák lekérdezésére ad lehetőséget?
Nagy segítséget jelentene a beérkező számlák feldolgozásában.

Elnézést ha elkerülte a figyelmemet és erre már most is van lehetőség.

**Comment by NTCA-developer** [comment]
Szia @connorhu 

Semmi gond, nincs rossz kérdés csak amit nem tesznek fel. Az Online Számla rendszer éles környezetben 2019.07.31 óta támogatja a 2.0-ás XML API égisze alatt a vevő oldali számla lekérdezéseket.

Lehetőség van listás és teljes adattartamos lekérdezésre is, ezeket a /queryInvoiceDigest és a /queryInvoiceData operációk valósítják meg. A lekérdezés akkor minősül vevőként elvégzettnek, ha a keresésben az invoiceDirection tag értéke INBOUND. Az operációk leírását megtalálod az interfész dokumentációban, illetve találsz ilyen példa requestet az API sample fájlok között itt: https://github.com/nav-gov-hu/Online-Invoice/blob/master/sample/API%20sample/queryInvoiceDigest_inbound_invoice_chain.xml

Arra felhívom viszont a figyelmet, hogy a 2.8-as verzióban változott a /queryInvoiceDigest, ami még nincs kint az élesen, tehát a jelenleg a teszten van a hatályos állapot.

Próbáld ki és jelezz vissza, hogy sikerült-e!

**Comment by connorhu** [comment]
Köszi! Akkor még csak nem vizsgáltam meg elég alaposan a 2.0-s változásokat.
