### ISSUE TITLE
[Invalid] Érvénytelen fejezetszám

### ISSUE THREAD

**Issue by NAGYPZS** [nav-gov-hu/Online-Invoice#145]
*Egyéb tartalom / Additional content*
A Online Szamla_interfesz specifikáció_HU_v2.0 dokumentáció olyan pontra hivatkozik, ami nincs a dokumentációban. 159 oldal.
"3) A dokumentáció kiegészítésre került az eltérő verziók közötti általános összefüggésekkel. A
részletekről ld: 1.7.9 fejezet. "

**Comment by NTCA-developer** [comment]
Szia @NAGYPZS 

Igazad van, köszönjük szépen hogy jelezted. A hivatkozott fejezet száma helyesen 1.6.9. Javítani fogjuk, addig nyitva hagyom a ticketet.

**Comment by bcdel** [comment]
oops #175 -ön részben duplikáltam...

**Comment by NTCA-supporter** [comment]
Szia!

Amiket jeleztél, javítottuk, kitettük teszt/éles környezetre.
Most sajnos nincs kapacitás az összes hivatkozás átnézésére, ha esetleg még találtok, megköszönjük a jelzést továbbra is.
Ezt az issuet most zárom.

Köszi
