### ISSUE TITLE
[Q&A] QueryTaxpayerResponse nincs megyekód, infoDate nem az utolsó változás dátuma

### ISSUE THREAD

**Issue by laladisc** [nav-gov-hu/Online-Invoice#146]
Sziasztok!

A 2.8-as verzióban közzétett QueryTaxpayerResponse nem ad vissza megyekódot. Az infoDate-nek az utolsó változást kellene visszaadni ha jól értelmezem (pl ha címadatokban bekövetkezett változás történik), de ha minden igaz, akkor az adószám kiállításának a dátumát kapjuk vissza.

Üdv: Lajos

**Comment by connorhu** [comment]
Szia!

Jelezték, hogy még nem kapnak adatokat ezekhez a mezőkhöz. Külön fognak arról szólni ha ez is megtörténik. Addig is a sémában már benne van a mező.

**Comment by laladisc** [comment]
Rendben, csak gondoltam szólok, hátha nem tudnak róla.

**Comment by NTCA-developer** [comment]
Szia @laladisc 

Így van ahogy @connorhu is mondja. Ennek még csak a helyét csináltuk meg a 2.0-ás sémában. Ugyan ez vonatkozik arra, hogy a címadat lista jelenleg mindig egy elemű, ehhez is további fejlesztés kell majd, hogy minden címet vissza tudjunk adni. De köszönjük hogy jelezted.

Lezárható a ticket?

**Comment by laladisc** [comment]
Szia!

Köszi az infót. Lezárhatod nyugodtan.

**Comment by NTCA-developer** [comment]
Illetve most látom csak hogy van a kérdésnek egy másik része amire még nem válaszoltam. Ha az infoDate tagban egy olyan dátum kerül visszaadásra, amikor az adószám keletkezett az azt jelenti, hogy azóta nincs a törzsadatban változás. Ergó az időbeli hatálya a lekérdezett adatoknak a létrehozáskori állapot.
