### ISSUE TITLE
[Q&A] Több számlát módosító okirat- batchinvoice

### ISSUE THREAD

**Issue by KKARACSONY** [nav-gov-hu/Online-Invoice#148]
Sziasztok, 

Ha a specifikáció 2.5.6-os fejezetét illetve a példa xmleket nézzük nem találunk választ ezekre a kérdésekre: 

Egy módosítószámla beküldésnél, hogyha több előzetesen kiállított számlát módosítunk akkor a tételek közé csak az éppen módosított tételek kerülnek bele vagy az összes? 

pl. 1-es számlában az első tételben volt 100 db termék, 2. tételben 50 db termék  és 2-es számlában volt 5 darab termék. A 3-as számlával módosítjuk az 1-es  számlát, de csak az első tételt illetve a 2-es számlát. 
Jól gondoljuk, hogy a 3-as (módosító számlámba) csak a 1es számla 1es tételét illetve a 2es számlatételt kell feltüntetni. 

(példa xml-ek nem tartalmaznak lineadatokat sajnos ennél az esetnél!)

Köszi szépen!

**Comment by NTCA-developer** [comment]
Szia @KKARACSONY

> Egy módosítószámla beküldésnél, hogyha több előzetesen kiállított számlát módosítunk akkor a tételek közé csak az éppen módosított tételek kerülnek bele vagy az összes?

Amennyiben a télelre itt mint számlasor adat (invoiceLine) gondolsz, akkor igen, jól értelmezed. Ugyan az a szabály mint a "sima" módosító okiratok adatszolgáltatásánál: csak a változást kell közölni.

**Comment by NTCA-developer** [comment]
Lezárhatom a ticketet?

**Comment by KKARACSONY** [comment]
Szia! Igen, köszi szépen a választ!
