### ISSUE TITLE
[FEATURE] IvoiceDigest - PaymentDate

### ISSUE THREAD

**Issue by samoly** [nav-gov-hu/Online-Invoice#15]
Üdv!
Megnéztem az új (várható) XSD-t, és reménykedtem, hogy a digest-re felkerül a fizetési határidő mint információ.

Nagyon sok olyan eset van, amikor ez az információ fontos, sőt, a mi szoftverünkben szinte mindig. És ha a digest-en meglenne, 100-ból 95 alkalommal el sem kellene mennünk egy újabb lekérdezéssel a részletes számla adatokért, mert minden meglenne. Most az esetek nagy részében csak amiatt intézünk újabb request-et a részletes számla adatok lekérdezésére, mert ez az infó kell. 
Ha a 2 másik fontos dátum rajta van, akkor harmadikként ezt a dátumot nem lehetne még odaszorítani? 
:)

Azt már csak úgy félve kérdezem-javaslom, hogy a query paraméterekbe is szerintem hasznos lenne (digest-ek lekérdezésénél), valószínűleg nem mi lennénk az egyetlenek, akik szeretnének úgy szűrni, hogy a fizetési határidőt (intervallumot) megadják.

Tényleg fontos dátum, azt is meg merem kockáztatni hogy fontosabb mint az invoiceDelivery dátum.

**Comment by kabelnet2** [comment]
Egyetértek azzal, amit írtál, de a teljesítés dátumát ne bántsuk, mert az ÁFA bevalláshoz meg az kell.

**Comment by samoly** [comment]
Persze, világos, én is szeretném ha maradna a Delivery dátum is, csak azt akartam érzékeltetni hogy van akinek a határidő is NAGYON fontos dátum :)

**Comment by NTCA-developer** [comment]
Szia!

Sajnálom, hogy előzetesen hiába reménykedtél, de ha most megcsináljuk, akkor az remélem kárpótolni fog. :)

Jó hogy ha egységben gondolkozunk, tehát result és queryParam is lesz az új tag. Viszont szeretnék előzetesen egy pontosítási kérdést feltenni. Ugye egy tagről, az invoiceDeliveryDate-ről beszélünk, nem pedig a periodos tagekről? Mert szerencsés volna, ha az nvl() kifejezéseket tudnánk kerülni a lekérdezésekben.

Tehát megfelel-e úgy, hogy az invoiceDeliveryDate benne lesz a digestben és keresni is lehet majd rá, de ha az invoiceDeliveryPeriodStart vagy invoiceDeliveryPeriodEnd meg van adva, akkor a paraméterrel nem fogunk keresni rajta.

**Comment by samoly** [comment]
Szia!

Egy tagról, de nem az invoiceDeliveryDate-ről, hanem a fizetési határidőről (PaymentDate) :)

Ez lenne fontos infó, hogy lehessen látni a diest-en is, hogy mikor esedékes a kifizetés. Köszönöm a konstruktív hozzáállást :)

**Comment by NTCA-developer** [comment]
Csak megnéztem hogy figyelsz-e, mivel invoiceDelivery már van a digestben. :)))

Akkor nem kérdés az nvl, felveszem a bővítést boardra. Lezárható az issue?

**Comment by samoly** [comment]
Igen, köszönöm!

**Comment by NTCA-developer** [comment]
Szia @samoly 

Egy gyors kérdés miatt visszanyitom az issue-t. A fizetési határidő lekérdezéséről lenne szó. 

A digest-es keresés úgy működik, hogy vannak kötelező lekérdezési paraméterek, amik meghatároznak egy számla halmazt. Jelenleg vagylagosan az ilyen kötelező paraméterek:
- a számla kiállítási dátuma, max 35 napos tartományban
- ez kiegészült egy itteni kérésre az adatszolgáltatás befogadásának napjával, szintén 35 napos tartományban
- illetve egy alapszámla számával lehetséges a rá vonatkozó számlalánc halmazát lekérdezni.

**Minden más opcionális kereső paraméter a fenti halmazt szűkíti.**

A kérdésem a fizetési határidőnél, hogy te ott melyik opcióra gondoltál? Csak szűkítő feltételként vagy magát a halmazt is ez alapján akarnád meghatározni? Jelenleg a fent lévő XSD szűkítő feltételként tartalmazza a paymentDate-et.

**Comment by samoly** [comment]
Szia!

Én szűkítő feltételként gondoltam rá, ahogy egy "általános" filter működik. Tehát a többi filter paraméterként megadott értékek alapján leszűkített halmazt szűkítené tovább, amennyiben olyan intervallum van megadva. (Tehát tudjak lekérdezni úgy, hogy pl csak azokat a digesteket szeretném listázni-menteni, amelyeknek a fizetési határideje lejár 5 napon belül, vagy éppen ma, vagy éppen júli 20 és 25 között).
Sikerült érthetően leírnom? :)
Ha nem, akkor szívesen nekifutok még egyszer :)

**Comment by NTCA-developer** [comment]
Teljesen érthető. Oké, akkor jól értettem az igényt mert a séma így készült. Köszi!
