### ISSUE TITLE
Original invoice number [Q&A]

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#150]
queryInvoiceDigestParam:
Az utolsó xsd-ben megváltozott az originalInvoiceNumber típusa: most simple string, míg korábban originalInvoiceNumberType volt.
Ez önmagában helyes változtatás, de nem olvastam róla sehol (ez lehet az én hibám), de még a példákban sem így van - ami viszont már nem az én hibám. 
queryInvoiceDigest_outbound_query_params.xml:
			[originalInvoiceNumber]
				[originalInvoiceNumber]string[/originalInvoiceNumber]
			[/originalInvoiceNumber]
A példában ki van kommentezve, mert nincs rá szükségetek, de azért ott van.
Egy ilyenre most jön a hibaüzenet:
 [validationerrorcode]SCHEMA_VIOLATION[/validationerrorcode]                                                                    
[message]Request body contains error: [cvc-type.3.1.2: Element 'originalInvoiceNumber' is a simple type, so it must have no element information item [children].][/message]
Ha az xsd az igazi, kérlek javítsátok a példát és esetleg érdemes lenne jelezni a changelog-ban/Informatikai változásokban is a változást.

**Comment by veerede** [comment]
Szia!
((Mivel ebbe én is beleléptem.))
Változott a 2.0-ás séma, az originalInvoiceNumber egyszerű elem lett, az adószám szűrő pedig átkerült az additionalQueryParams alá a taxNumber elembe.

Üdv
Ede

**Comment by NTCA-developer** [comment]
Szia @kabelnet2 !

A Changelog és az interfész dokumentáció 5.3-as fejezetében az API módosítások alfejezet 11-es pontjában is van szó erről a változásról.

Az API sample-ben én csak a supplierTaxNumber tag feltüntetését néztem meg, arra nem figyeltem hogy a csomópontot is törölni kell. Most javítottam, köszönöm a jelzést!
