### ISSUE TITLE
[DEV support] queryTaxpayer request névtér eltérés

### ISSUE THREAD

**Issue by HWKF** [nav-gov-hu/Online-Invoice#152]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[x] /queryTaxpayer
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[x] 2.0

**A requestId értéke / requestId value**
```
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
A queryTaxpayer operáció válaszban az egyes elemek "ns2" névtérben vannak. Ez direkt készül így? Mert eddig a többi operáció esetén eddig nem volt ilyen megkülönböztetés.
pl. <ns2:taxpayerId> <ns2:countryCode> 
viszont a <taxpayerName> nem, bár ez is "data:" az xsd-ben.

*Egyéb tartalom / Additional content*

**Comment by NTCA-developer** [comment]
Szia!

Igen, a célja pont az (ahogy a taxNumberDetail esetében is) a data névtérből jöjjenek az adatok. Ezzel megspóroljuk a típus duplikációt az API-s sémaleíróban, másrészt a visszakapott adatok típuskonverzió nélkül átemelhetők a számlabeküldés megfelelő adataihoz.

Itt (bár más volt a felvetés) is tárgyaltuk már ezt: https://github.com/nav-gov-hu/Online-Invoice/issues/75

**Comment by HWKF** [comment]
Sajnos a kérdés egyik részét elnyelte a html.
De nem egységes még válaszon belül sem. A taxpayerData/taxpayerName elem típusa is "data" még sincs a válaszban névtér. Ez látszik az említett (75-ös) issue-ban is.

**Comment by NTCA-developer** [comment]
Csak ismételni tudom magam. :)

Az említett 75-ös issue-ban pont azt magyarázzuk, hogy a névtér nem így működik. A namespace nem abból az XSD-ből származik, ahol az element típusa lakik, hanem onnan, ahol az element deklarálva van. Tehát mivel a taxpayerName az API-ban van deklarálva, ezért a default ns részét képezni, még akkor is, ha a típusa type="data:SimpleText512NotBlankType".

Ellenpélda a taxpayerAddressItem/taxpayerAddress. Mivel a taxpayerAddress típusa type="data:DetailedAddressType", ezért az azon belül lévő elementek névtere már a data lesz. De figyeld meg, hogy már a szülőelem, a taxpayerAddress sem kapja meg a data ns-t.

Szóval amit mondasz, az implicit módon igaz a complexType-ok esetén, de a simpleType-ok esetén nem. Ennek pont az az oka, hogy a complexType további elementeket fog tartalmazni magán belül, míg a simpleType sosem.

**Comment by NTCA-developer** [comment]
Ezt lezárom, ha merül fel új kérdés akkor nyisd újra nyugodtan.
