### ISSUE TITLE
Few fields missing for while requesting the /invoiceService/v2/queryTaxpayer service

### ISSUE THREAD

**Issue by AmrutaK1** [nav-gov-hu/Online-Invoice#153]
Hi Team,

I am trying to call the queryTaxpayer rest service 636D4737D95A40839D7DF400F is the request ID, but I am not receiving the taxpayerAddress details in response.Can you please check?

Thanks,
Amruta K

**Comment by NTCA-developer** [comment]
Hi @AmrutaK1 

Your request with the requestId 636D4737D95A40839D7DF400F was rejected with a faultcode REQUEST_ID_NOT_UNIQUE. Requests rejected by the server never contain any kind of business response.

**Comment by NTCA-developer** [comment]
I'm closing this one too. Please reopen it if it is not solved yet.
