### ISSUE TITLE
[DEV support]

### ISSUE THREAD

**Issue by GeetikaB-Ban** [nav-gov-hu/Online-Invoice#154]
Hi Team,

I am facing an issue related to an API-  https://api-test.onlineszamla.nav.gov.hu/invoiceService/v2/queryInvoiceDigest,

The request passed as,

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<QueryInvoiceDigestRequest xmlns="http://schemas.nav.gov.hu/OSA/2.0/api">
    <header>
        <requestId>D0C3E63ECE8A4865A8F601C84</requestId>
        <timestamp>2020-02-26T11:38:47.870Z</timestamp>
        <requestVersion>2.0</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
    <user>
        <login>sl8uampp21aj4eu</login>
        <passwordHash>1542EF96DF5226C1A3441E8C82399A5D51997C6B08E8CFAE23E766547E20F8514217D9CDA2E9EA3300F366CF6753F32DEF979B6D367FADF1A66708658C1E5140</passwordHash>
        <taxNumber>26952938</taxNumber>
        <requestSignature>0E24C766C8729C4EB28142C09BEC3291412A6D581EE30ECD138337866E3F7F54DF41739EDCF2B79240B2EC9C7523467BD1DE429F0D293A4A3A744D3E563575C5</requestSignature>
    </user>
    <software>
        <softwareId>PBVTGW0JV6QVGJZXL0</softwareId>
        <softwareName>string</softwareName>
        <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
        <softwareMainVersion>string</softwareMainVersion>
        <softwareDevName>string</softwareDevName>
        <softwareDevContact>string</softwareDevContact>
        <softwareDevCountryCode>HU</softwareDevCountryCode>
        <softwareDevTaxNumber>string</softwareDevTaxNumber>
    </software>
    <page>1</page>
    <invoiceDirection>INBOUND</invoiceDirection>
    <invoiceQueryParams>
        <mandatoryQueryParams>
            <originalInvoiceNumber>
                <originalInvoiceNumber>P35508003727</originalInvoiceNumber>
            </originalInvoiceNumber>
        </mandatoryQueryParams>
    </invoiceQueryParams>
</QueryInvoiceDigestRequest>

The response as,

<GeneralErrorResponse xmlns="http://schemas.nav.gov.hu/OSA/2.0/api" xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/data">
   <result>
      <funcCode>ERROR</funcCode>
      <errorCode>INVALID_REQUEST</errorCode>
      <message>Helytelen kérés!</message>
   </result>
   <technicalValidationMessages>
      <validationResultCode>ERROR</validationResultCode>
      <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
      <message>Request body contains error: [cvc-type.3.1.2: Element 'originalInvoiceNumber' is a simple type, so it must have no element information item [children].]</message>
   </technicalValidationMessages>
   <technicalValidationMessages>
      <validationResultCode>ERROR</validationResultCode>
      <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
      <message>Request body contains error: [cvc-pattern-valid: Value '' is not facet-valid with respect to pattern '.*[^\s].*' for type 'SimpleText50NotBlankType'.]</message>
   </technicalValidationMessages>
   <technicalValidationMessages>
      <validationResultCode>ERROR</validationResultCode>
      <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
      <message>Field [originalInvoiceNumber] contains error: [cvc-type.3.1.3: The value '' of element 'originalInvoiceNumber' is not valid.]</message>
   </technicalValidationMessages>
</GeneralErrorResponse>

Please help us to get the actual cause for an errors.

Thanks,
Geetika Banwari
geetika.banwari@infosys.com
7566290198

**Comment by NTCA-supporter** [comment]
Hi!

The invoiceApi.xsd has changed, please check our changelog for furter details.
The solution for your issue:
	<invoiceQueryParams>
		<mandatoryQueryParams>
			<originalInvoiceNumber>your_invoice_number</originalInvoiceNumber>
		</mandatoryQueryParams>
	</invoiceQueryParams>

from the changelog:
OriginalInvoiceNumberQueryType in the request of /queryInvoiceDigest is deleted, the mandatoryQueryParams/originalInvoiceNumber path is now an element, not a complex type.

I hope I could help!

**Comment by NTCA-supporter** [comment]
Hi @GeetikaB-Ban !
Do you need any more help related to this issue? Can I close this ticket?
BR

**Comment by NTCA-supporter** [comment]
I'm closing the ticket due to inactivity. If the problem persists or you have new questions feel free to reopen it or create a new one, we will help if we can.
