### ISSUE TITLE
Bejelentések megfogalmazása [Q&A]

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#155]
Elnézést, de most már kikivánkozik belőlem nagyon.
Bejelentitek a 2.0-t az éles rendszer honlapján. Ezt szerintem nem csak fejlesztők (sőt főleg nem) olvassák, hanem könyvelők, ügyfelek.
Minek kell itt XSD-ről beszélni? Kell tudni egy könyvelőnek, hogy mi az az XSD?
S a csúcs: mindenhol próbáltátok az 1.1-ből 2.0-ba átmenetet leírni, de az utolsó előtti mondatban nem tudtátok megállni hogy 2.8! Na az meg mi, mondja mindenki (nem fejlesztő), aki olvassa.
És miért írjátok, hogy a 2.0-hoz 03.31-ig használható. Utána is használható lesz az...
Nem lehetne egy ilyen fontos közleményt emberi nyelven megfogalmazni?

**Comment by NTCA-developer** [comment]
Szia @kabelnet2 

Köszönjük a jelzést, átadom az üzeneted.
