### ISSUE TITLE
[DEV support] schema violation

### ISSUE THREAD

**Issue by GeetikaB-Ban** [nav-gov-hu/Online-Invoice#156]
Hi Team,

I am facing as issue for API- https://api-test.onlineszamla.nav.gov.hu/invoiceService/v2/queryTransactionStatus,

Following is the request,
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<QueryTransactionStatusRequest xmlns="http://schemas.nav.gov.hu/OSA/2.0/api">
    <header>
        <requestId>C697CF53291A45569CDF1D0AE</requestId>
        <timestamp>2020-02-26T14:08:23.079Z</timestamp>
        <requestVersion>2.0</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
    <user>
        <login>sl8uampp21aj4eu</login>
        <passwordHash>1542EF96DF5226C1A3441E8C82399A5D51997C6B08E8CFAE23E766547E20F8514217D9CDA2E9EA3300F366CF6753F32DEF979B6D367FADF1A66708658C1E5140</passwordHash>
        <taxNumber>26952938</taxNumber>
        <requestSignature>17FB80D521EB3ACEC4122F6356C37EC0D551B2EA0C75E6AC297693642429DFE7C7192107089E868012AC8CD863CB9D5EE66361C50BA627DD98E299890CF5E9EA</requestSignature>
    </user>
    <software>
        <softwareId>NX9COHDHPF70NDE3IA</softwareId>
        <softwareName>string</softwareName>
        <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
        <softwareMainVersion>string</softwareMainVersion>
        <softwareDevName>string</softwareDevName>
        <softwareDevContact>string</softwareDevContact>
        <softwareDevCountryCode>HU</softwareDevCountryCode>
        <softwareDevTaxNumber>string</softwareDevTaxNumber>
    </software>
    <transactionId>2VOWEWNPO5FYL0WR</transactionId>
    <returnOriginalRequest>false</returnOriginalRequest>
</QueryTransactionStatusRequest>

Following is the response,

<QueryTransactionStatusResponse xmlns="http://schemas.nav.gov.hu/OSA/2.0/api" xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/data">
   <header>
      <requestId>FAF3719A607440A382CD680A2</requestId>
      <timestamp>2020-02-26T14:16:01.545Z</timestamp>
      <requestVersion>2.0</requestVersion>
      <headerVersion>1.0</headerVersion>
   </header>
   <result>
      <funcCode>OK</funcCode>
   </result>
   <software>
      <softwareId>B5J6J4RF9T16VL5UJT</softwareId>
      <softwareName>string</softwareName>
      <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
      <softwareMainVersion>string</softwareMainVersion>
      <softwareDevName>string</softwareDevName>
      <softwareDevContact>string</softwareDevContact>
      <softwareDevCountryCode>HU</softwareDevCountryCode>
      <softwareDevTaxNumber>string</softwareDevTaxNumber>
   </software>
   <processingResults>
      <processingResult>
         <index>1</index>
         <invoiceStatus>ABORTED</invoiceStatus>
         <technicalValidationMessages>
            <validationResultCode>ERROR</validationResultCode>
            <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
            <message>Field [null] contains error: [cvc-elt.1.a: Cannot find the declaration of element 'InvoiceType'.]</message>
         </technicalValidationMessages>
         <technicalValidationMessages>
            <validationResultCode>ERROR</validationResultCode>
            <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
            <message>Field [null] contains error: [unexpected element (uri:"http://schemas.nav.gov.hu/OSA/2.0/data", local:"InvoiceType"). Expected elements are &lt;{http://schemas.nav.gov.hu/OSA/2.0/data}InvoiceData>]</message>
         </technicalValidationMessages>
         <technicalValidationMessages>
            <validationResultCode>ERROR</validationResultCode>
            <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
            <message>Field [null] contains error: [unexpected element (uri:"http://schemas.nav.gov.hu/OSA/2.0/data", local:"InvoiceType"). Expected elements are &lt;{http://schemas.nav.gov.hu/OSA/2.0/data}InvoiceData>]</message>
         </technicalValidationMessages>
         <technicalValidationMessages>
            <validationResultCode>ERROR</validationResultCode>
            <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
            <message>Cannot construct valid object</message>
         </technicalValidationMessages>
         <compressedContentIndicator>false</compressedContentIndicator>
      </processingResult>
      <originalRequestVersion>2.0</originalRequestVersion>
   </processingResults>
</QueryTransactionStatusResponse>

Although getting <funcCode>OK</funcCode>, still there is error in the response.

Please help us to resolve the issue.

Thanks,
Geetika Banwari
geetika.banwari@infosys.com
7566290198

**Comment by NTCA-supporter** [comment]
Hi!

I think these two are not request-response pair, can you check it again?
There's about 8 minutes difference between the 2 requests.

Thanks

**Comment by NTCA-supporter** [comment]
Hi @GeetikaB-Ban !
Do you need any more help related to this issue? Can I close this ticket?
BR

**Comment by NTCA-supporter** [comment]
I'm closing the ticket due to inactivity. If the problem persists or you have new questions feel free to reopen it or create a new one, we will help if we can.
