### ISSUE TITLE
[DEV support] QueryInvoiceDataResponse structure

### ISSUE THREAD

**Issue by GeetikaB-Ban** [nav-gov-hu/Online-Invoice#157]
Hi Team,
For an API- https://api-test.onlineszamla.nav.gov.hu/invoiceService/v2/queryInvoiceData,

Following is the request,
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<QueryInvoiceDataRequest xmlns="http://schemas.nav.gov.hu/OSA/2.0/api">
    <header>
        <requestId>1F1C8DF544FF484BA5B135170</requestId>
        <timestamp>2020-02-26T13:59:28.770Z</timestamp>
        <requestVersion>2.0</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
    <user>
        <login>sl8uampp21aj4eu</login>
        <passwordHash>1542EF96DF5226C1A3441E8C82399A5D51997C6B08E8CFAE23E766547E20F8514217D9CDA2E9EA3300F366CF6753F32DEF979B6D367FADF1A66708658C1E5140</passwordHash>
        <taxNumber>26952938</taxNumber>
        <requestSignature>F479E5122E267B2FC34608E7F826C13096AC20C1CB3061E389B8FC0577A5D5FC1CE2A1CB96E5AA3C3F80BFC9D753A0E737104574110B4A3450ECB2205D98D6E4</requestSignature>
    </user>
    <software>
        <softwareId>HY83I48BID41C9K37W</softwareId>
        <softwareName>string</softwareName>
        <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
        <softwareMainVersion>string</softwareMainVersion>
        <softwareDevName>string</softwareDevName>
        <softwareDevContact>string</softwareDevContact>
        <softwareDevCountryCode>HU</softwareDevCountryCode>
        <softwareDevTaxNumber>string</softwareDevTaxNumber>
    </software>
    <invoiceNumberQuery>
        <invoiceNumber>P35508003884</invoiceNumber>
        <invoiceDirection>INBOUND</invoiceDirection>
    </invoiceNumberQuery>
</QueryInvoiceDataRequest>

Following is the response,

<QueryInvoiceDataResponse xmlns="http://schemas.nav.gov.hu/OSA/2.0/api" xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/data">
   <header>
      <requestId>1F1C8DF544FF484BA5B135170</requestId>
      <timestamp>2020-02-26T13:59:28.770Z</timestamp>
      <requestVersion>2.0</requestVersion>
      <headerVersion>1.0</headerVersion>
   </header>
   <result>
      <funcCode>OK</funcCode>
   </result>
   <software>
      <softwareId>HY83I48BID41C9K37W</softwareId>
      <softwareName>string</softwareName>
      <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
      <softwareMainVersion>string</softwareMainVersion>
      <softwareDevName>string</softwareDevName>
      <softwareDevContact>string</softwareDevContact>
      <softwareDevCountryCode>HU</softwareDevCountryCode>
      <softwareDevTaxNumber>string</softwareDevTaxNumber>
   </software>
</QueryInvoiceDataResponse>

We are not getting mandatory fields in the response as per mentioned in the API documentation: Online Invoicing System 2.0 Interface Specification for the same API.

Please provide the update on this.

Thanks,
Geetika Banwari
geetika.banwari@infosys.com
7566290198

**Comment by NTCA-supporter** [comment]
Hi!

Which mandatory fields are you expecting?
Are you sure that the reqested invoiceNumber exists? 

Thanks

**Comment by GeetikaB-Ban** [comment]
Hi,
Yes Invoice number exists, and in case of mandatory fields we are expecting in response the below fields,

currentPage, availablePage, invoiceData  , auditData, insdate, insCusUser, source, originalRequestVersion, compressedContentIndicator.

Thanks,
Geetika Banwari

**Comment by NTCA-supporter** [comment]
Hi @GeetikaB-Ban !

I checked the requested invoice_number and it doesn't exist at any customer (test environnment), so that's why you cannot receive the invoice's data.

If you chech the QeryInvoiceDataResponse you can see the following things:
- the invoiceDataResult is an optional node, so if the requested invoiceNumber doesn't exist, this node won't be in the response
- in case of queryInvoiceData you can query exactly 1 invoice's data, so (even if the invoice exists), you can get maximum 1 invoiceDataResult. This means there aren't currentPage, availablePage tags in this query service. (You can check either the XSD file or the documentation.)

I hope I could help.

BR

**Comment by NTCA-supporter** [comment]
Hi @GeetikaB-Ban !
Do you need any more help related to this issue? Can I close this ticket?
BR

**Comment by NTCA-supporter** [comment]
I'm closing the ticket due to inactivity. If the problem persists or you have new questions feel free to reopen it or create a new one, we will help if we can.
