### ISSUE TITLE
[Q&A] Több Számlát Módosító Okirat Sztornója 

### ISSUE THREAD

**Issue by kurucza** [nav-gov-hu/Online-Invoice#158]
Sziasztok,

Kérlek segítsetek nekem a több számlát módosító okirat sztornójának megértésében, mert elakadtunk a fejlesztésben emiatt.
Adott egy számla: visszáru jóváírás (RE) . A jóváírás 2 számlára ( A és B)  hivatkozott kiszállítással készült.
A jóváírás e-invoice op.ja Modify, 2 batchInvoice Tag-gel.  
Itt még semmi problémám nincs, mert a 2 hivatkozott számla ( alapszámla-CREATE)
A kérdésem itt jön: Ha szeretném sztornózni a visszáru jóváírást, amely eleve már módosító számla, akkor batchInvoice sturktúrában kell ezt megtennem?  Eredeti számlára kell hivatkoznom (A és B)?
'Sima' Stornot erre a számlára nem tudok létrehozni a módosító mivolta miatt.

Tranzakciós ID:  2VP3YG55GBMBQSMG, ő a visszáru jóváírás, amelyet szeretnénk Stornóként beküldeni.

Előre is köszönöm a segítségeteket!

Andi

**Comment by kabelnet2** [comment]
Miért nem egy újabb módosítóval 'lövöd ki' a nem szükséges vagy hibás módosítót vagy módosítókat? Ha az alapszámla különben jó, akkor miért kellene sztornózni mindent? Akárhány módosítót kiállíthatsz.

**Comment by NTCA-developer** [comment]
Szia @kurucza !

Előzetesen is bocsánat a lassú válaszért, a 2.0 élesítés eléggé leterhelt bennünket. Remélem még nincs késő. 

Nem néztem még meg a számlákat amiket írtál, mert azt hiszem hogy értem a problémát azok nélkül is. (Ha pedig a választ elolvasva mégis sikerült félreértenem akkor kérlek szólj.)

Szóval, technikai akadálya biztosan nincs annak, hogy egy alapszámlára úgy épüljön fel számlalánc, hogy a lánc tagjait batchInvoice és nem batchInvoice-os számlák alkotják, legyenek azok MODIFY vagy STORNO tartalmúak. Üzleti oldalról nézve azt ki lehet mondani, hogy ha a batchInvoice egyáltalán felmerült, akkor biztosan több alapszámla is van, hiszen a batchInvoice azokat módosítja egyben. Mivel több alapszámla van, innentől kezdve az is biztos hogy azok sztornírozását is tudni kell egymástól elkülönülten kezelni. Így véleményem szerint nincs akadálya annak - sőt, ez a generikusan helyes megoldás, ahogy @kabelnet2  is írja - hogy az egyes alapszámlákat egyedileg, nem batchInvoice-ként sztornírozod, figyelve arra hogy a hivatkozás mindig az alapszámlára történjen. Persze ha a már az első adatszolgáltatásnál tudod, hogy többet fogsz egyszerre stornírozni, akkor lehet egyben batch-ként, meg lehet külön-külön is. 

A fő szabály, hogy úgy csináld, ahogy a stornó számla kinéz! Ha egyben többet stornóz akkor batchInvoice, ha külön-külön bocsátasz ki akkor pedig nem batchInvoice a struktúra.

Ez válasz a kérdésedre?

**Comment by kurucza** [comment]
Köszönöm a válaszod. Időközben megoldottuk a 'problémát' és a visszajelzésed alapján is jók vagyunk!
