### ISSUE TITLE
[Q&A] TaxpayerAddressListType

### ISSUE THREAD

**Issue by hosszuful** [nav-gov-hu/Online-Invoice#159]
Helló!

Egyszerű kérdéseim vannak így séma frissítés után. A régi szerinti TaxpayerDataType.getTaxpayerAddress()-nek az új data.getTaxpayerAddressList().getTaxpayerAddressItem() elem közül a HQ típusú felel meg?
A HQ típusú adatból csak és kizárólag egy lehet?
A HQ mindig van?

**Comment by NTCA-developer** [comment]
Szia @hosszuful !

Amit te korábbi getternek nevezel `TaxpayerDataType.getTaxpayerAddress()` azok most a listát felépítő taxpayerAddressItem-ek. A HQ csak egy minősítő jelző, hogy az a cím székhely. (ahogy az enum annotáció mondja) 

Általában nincs garancia arra sem hogy minden időpillanatban címadat van-e az adózóhoz, ezen belül a HQ-ra sem lehet mindig mérget venni. Logikailag igaznak tűnik, hogy székhely csak egy lehet egy adózóhoz, de azért én erre sem vennék mérget, a valóság és a DB nem mindig 100%-ban fedik egymást.

Van még kérdésed vagy lezárható a ticket?

**Comment by hosszuful** [comment]
Akkor máshogy kérdezem. Ami eddig a lista nélküli TaxpayerDataType.getTaxpayerAddress()-ben jött az most a kapott listában szereplő HQ típusú adat?

**Comment by NTCA-developer** [comment]
Bocsánat ha nem erre válaszoltam rögtön, én így értettem ez volt a kérdés. Én is megpróbálom máshogy megfogalmazni a választ.

Amit korábban visszaadtunk címadatot (1.0, 1.1) sem minden esetben voltak székhely adatok.

A törzs tőlünk független erőknek is ki van téve, ezért technikailag nem tudjuk garantálni, hogy amelyik adózónál van cím annak mindegyike székhely adat. (HQ) De azt ki lehet jelenteni, hogy az esetek 99%-ban HQ lesz a cím jellege. Így oké?

**Comment by hosszuful** [comment]
Igen, Köszi!
