### ISSUE TITLE
[FEATURE] invoiceData.xsd ExchangeRateType minExclusive

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#16]
**Az igény összefoglalása / Summary of the request**
A krasa-jaxb-tools-t használom objektum generálásra, és nem szereti a "0.00"-t, viszont a "0"-val működik.

**Az általam javasolt megoldás / The solution I propose**
Az invoiceData.xsd-ben az ExchangeRateType.restriction.minExclusive jelenleg "0.00". Helyette lehetne "0"?

**Elfogadható alternatívák / Acceptable alternatives**
A probléma nem kritikus, könnyű az xsd-t javítani, de ha nem jelent lényegi változást a "0", akkor jó lenen ha gyári xsd-ből tudnánk generálni és nem kellene kézzel szerkeszteni.

**Comment by NTCA-developer** [comment]
Szia!

Kipróbáltam magamnál, hogy a típus alsó korlátját átírom 0-ra. A parser szerint jónak tűnik, invalid maradt a 0, 0.0, 0.00 stb. Most nem tudom teljes körűen kipróbálni, de nem látok vele előre látható problémát.

Maradjunk abba, hogy bevesszük a módosítást a 2.0-ba, és ha valami nem várt baj volna vele, akkor szólok.

Lezárhatjuk?

**Comment by EPluribusUnum** [comment]
Köszönöm, jó lesz így.
