### ISSUE TITLE
[DEV support] Érvénytelen request

### ISSUE THREAD

**Issue by era910413** [nav-gov-hu/Online-Invoice#160]
Az alábbi requestID-val beküldött ManageInvoiceRequest-re kapott response az invalid_request_signature hibával elutasításra kerül:
GAE831202002274613375

Ez jelenleg egy számlánál jelentkezik csak, az összes többi beküldésem sikeres... Meg tudnátok nézni, hogy mi a gond?
Igazából egy majdnem 7000 soros xml-t próbálok beküldeni, nem tudom, hogy esetleg az okozza-e a problémát.. másra már nem tudok gondolni.

**Comment by NTCA-developer** [comment]
Szia @era910413 !

Bocsánat a késői válaszért. Elkezdtem nézni, visszajelzek. (bár előzetesen azt el kell mondjam hogy ha tényleg requestSignature hibád van, akkor maximum a helyes értéket tudom megmondani, azt hogy te hol hibáztál már nem)

**Comment by NTCA-developer** [comment]
Valóban ez a hiba, a helyes érték a 6255B61610F27749326D006EE55062D98A90EB755F99A0C2F9EC47440A2B1E04F53AD5E5E87D6EEDA764DC527AFEB8EA205E150DF9B98E5C7C2789693F01455B lett volna, szemben a beküdött 1948A5E547A25AD4C07D1F257B5F7CC002983AA8D2551ED2B7398C2C798B4CF7757F43965873494BD89FC9A7334852F56A39E42A30ECF9317F360EAB532442BC értékkel.

Az a javaslatom, hogy csinálj erre az inputra kézzel egy önellenőrzést, az interfész dokumentáció 7.1 pontja alapján. Ha minden más számlánál jó csak konkrétan egynél rossz, akkor a parciális hash biztosan helyes, csak az index hashnél lehet valami probléma.

**Comment by era910413** [comment]
Amit helyes értékként írsz az konkrétan az index hash értéke, tehát az operation és a base64 tartalom összefűzését követő nagybetűs SHA3-512 hash értéke:
- invoiceOperation: MODIFY + invoiceData base64-ben

Viszont ha az elején a parciális hash-t is hozzárakom, akkor nyilván nem ez lesz az érték...
Próbálom keresni a bajt, és köszi hogy nézed, de biztosan a helyes értéket adtad meg?

**Comment by NTCA-developer** [comment]
Szia!

Nem, ez a teljes elvárt érték, nem rész eredmény.
