### ISSUE TITLE
[Q&A] <header>/<timestamp> érték relevancia

### ISSUE THREAD

**Issue by szako** [nav-gov-hu/Online-Invoice#161]
SAP ERP-ben nincs natív SHA3-512 támogatás, ezért vannak olyan ügyfelek, ahol ABAP stacken lett megírva a hash képzés. Nagyon nagy számláknál ez a hash (még tömörítés esetén is) percben mérhető. Jelenleg az aktuális timestamp "beszerzése" a számlák hash képzése előtt történik így a küldött timestamp értéke és a tényleges beküldés időpontja között akár egy perc is eltelhet.

Logikus lépés lenne későbbre helyezni a timestamp leképzését? Számít ez valamit a NAV oldalán amúgy? Az 1.1-ben ez nem jött elő, mert ms-ekben volt mérhető a timestamp és a tényleges küldés között eltelt idő.

Köszönöm!

**Comment by NTCA-developer** [comment]
Szia @szako !

Számunkra nincs lényegi különbség hogy a timestampet mikor állítod elő addig, amíg a requestSignature értékénél a helyes értéket vetted figyelembe. Általában szebb megoldás ha a küldés előtt közvetlenül van a timestamp megállapítva.

Lezárod majd?

**Comment by szako** [comment]
Köszönöm a választ!
