### ISSUE TITLE
[Q&A] Tömörítetlen számla XML méretkorlát emelése

### ISSUE THREAD

**Issue by szako** [nav-gov-hu/Online-Invoice#162]
Jelenleg 15mb a tömörítetlen számla XML méretkorlátja. Tervezett ennek az emelése? Az új kötelező tétel tagek miatt amúgy is megnőtt az XML-ek általános mérete.

Például most elakadt egy 23e tételes számla 15.2mb mérettel:

```
requestId: 200225204hTKNhAl2H7X00002kLcvW
transactionId: 2VNZS0G97498AIL8 / 4.
```

Még tudunk optimalizálni egy kicsit (kb 3%-ot), ami miatt épphogy bemegy 15mb alá, de ez nem megoldás mert vannak nagyobb tételszámú számlák is.

Köszönöm!

**Comment by NTCA-developer** [comment]
Szia @szako 

Nem, sőt nagyon vehemensen is tiltakoznánk minden méretkorlát növelés ellen. Gondolj bele, Shakespeare összes drámája 5-6 MB XML formátumban. Azon túl hogy a 15 MB korlát így is irreálisan sok, minden megemelt méretkorlátnál lesz olyan adózó, akinek az aktuális éppen kevés és még több kell. Ennek sosem volna vége, arról nem is beszélve hogy ha a méretkorlát növelés elszabadul, akkor megnézném mit csinál a kliens oldalon egy számlázóprogram ami kap egy számla lekérdezéskor mondjuk 100 MB méretű base64-et. (Szerintem a többség ebbe belehal)

Végső soron a szabályozási területre vár ennek a problémának a megoldása, hogy mi a teendő a méretkorlát túllépésekor. Ha belefuttok ebbe a hibába akkor javasolom írjatok hivatalosan a NAV-nak hogy mit kell tenni ekkor.

**Comment by szako** [comment]
Szia @NTCA-developer!

Köszönöm a választ, tudomásul veszem, bár nem értek egyet az érvelésed bizonyos részeivel. A kérdéses ügyfél felveszi a kapcsolatot a NAV-val, mert így az adatszolgáltatás nem elvégezhető.
