### ISSUE TITLE
[DEV support] requestSignature képzése

### ISSUE THREAD

**Issue by NAGYPZS** [nav-gov-hu/Online-Invoice#163]
Tisztelt Cím!
Egy kis segítséget szeretnék kérni. A leírás 11 oldalán lévő invoiceData tartalma az hona származik, a példában : invoiceData = QWJjZDEyMzQ=
A választ előre is köszönöm.
Papp Zsolt

**Comment by NTCA-supporter** [comment]
Kedves @NAGYPZS 

Az invoiceData  a /manageInvoice REST operáció kérésének ManageInvoiceRequest elementjének az  invoiceData tagban lévő értéke, ami a számla adatok BASE64-ben kódolt tartalma. A ManageInvoiceRequest-ről az interfész leírás 1.9.2.1 fejezetében tud bővebben olvasni.

**Comment by NTCA-supporter** [comment]
Illetve ha konkrétan a QWJjZDEyMzQ= értékre vagy kíváncsi, az csak egy fiktív példa, az előbb említett invoiceData base64 értékkel behelyettesítendő.

**Comment by NTCA-supporter** [comment]
Szia @NAGYPZS !

Van még kérdés ezzel kapcsolatban? Ha nincs, kérlek zárd az issuet.

Köszönöm!
