### ISSUE TITLE
[DEV support]/queryInvoiceChainDigest

### ISSUE THREAD

**Issue by tkelemen73** [nav-gov-hu/Online-Invoice#165]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[X] /queryInvoiceChainDigest

**A kérés verziója / version of the request**
[X] 2.0

**A requestId értéke / requestId value**
ABIFNPZ7O4POVFWGK64BDMJYAY

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
A specifikációnak illetve a minta hívásnak megfelelően van az queryInvoiceChainDigestRequest.XML  összeállítva, mégis minden hívásra OPERATION_FAILED error érkezik vissza a response-ban. Függetlenül attól, hogy INBOUND vagy OUTBUND, mindig ugyanez az üzenet érkezik vissza.
Valami nem csinálunk jól, vagy a nem működik a szolgáltatás?

*Egyéb tartalom / Additional content*

**Comment by NTCA-supporter** [comment]
Szia @tkelemen73 
Jó URL-t hívsz?
api-test.onlineszamla.nav.gov.hu/invoiceService/v2/queryInvoiceChainDigest

Ahogy látom te a /queryInvoiceData végpontot hívod.

**Comment by tkelemen73** [comment]
Szia, köszönöm, valóban. Köszönöm!

**Comment by NTCA-supporter** [comment]
Szívesen :) Zárom.
