### ISSUE TITLE
[DEV support]Bejövő számla xml állománya

### ISSUE THREAD

**Issue by KMGY100** [nav-gov-hu/Online-Invoice#166]

**Comment by KMGY100** [comment]
2UWBCK0EWCIA7SQO                        
2UUQSJKVQX2KWHDT                        
2V38L4AUGHYPVPDH                        

A fenti 3 TrId  ugyanahhoz a kibocsájtóhoz tartozik.
Általa kibocsájtott számlák közül egyetlen egynél sem 
értékelhető az XML állomány
QueryInvoiceDataRequest kérés és Base64 dekódolása után.                        

Minden más kibocsájtó bejövő számlája rendben van.

**Comment by NTCA-supporter** [comment]
Kedves @KMGY100 

Légyszi segíts, hogy ezek a tranzakciós Id-k melyik környezethez kapcsolódnak.

Köszi.

**Comment by KMGY100** [comment]
1.0   (természetesen éles) és
és nem a NAV oldalon keresztül adta fel.

**Comment by NTCA-supporter** [comment]
Az éles környezettel kapcsolatos kérdéseket kérlek közvetlenül a https://nav.gov.hu/nav/e-ugyfsz/levelkuldes címre küldd el és ott fognak segíteni. Mi csak a teszt környezettel kapcsolatban tudunk segíteni.

A ticketet majd zárd le kérlek, ha ez így rendben van.
