### ISSUE TITLE
[Q&A] technika érvénytelenítés státusza

### ISSUE THREAD

**Issue by csgerdan** [nav-gov-hu/Online-Invoice#167]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**

Sziasztok!

Azt szeretném kérdezni, hogy egy technikai érvénytelenítés státusza átlagosan kb. mennyi idő alatt vált VERIFICATION
_PENDING-ről valami másra.

Köszönöm,
Csongor

**Comment by NTCA-supporter** [comment]
Szia!

Ennek nincs átlagos ideje, mivel ez nem feldolgozás.
Ez akkor vált státuszt, amikor az Online Számla felületre bejelentkezve a felhasználó jóváhagyja/elutasítja a technikai érvénytelenítést. Ilyenkor vált végállapotba (VERIFICATION_DONE vagy VERIFICATION_REJECTED).
Így oké?

**Comment by csgerdan** [comment]
Szia!

Ez így oké. Köszönöm szépen a gyors választ!
(Sajnos az Online Számla felülethez nincs hozzáférésem.
Hát ezért nem voltam tisztában a lehetőségekkel.)

Zárom is az issue-t.
Üdv.
