### ISSUE TITLE
[Q&A] Betöltési hiba a weboldalon

### ISSUE THREAD

**Issue by connorhu** [nav-gov-hu/Online-Invoice#168]
Nem igazán illik egyik kategóriába sem.
Előfordul néha, hogy chrome böngésző alatt (máson nem teszteltem) az onlineszamla.nav.gov.hu nem tölt be, fehér marad a főképernyő. Megnéztem a konzolt és 3 js-ben syntax errort ír:
- main.[hash].js
- polyfills.[hash].js
- runtime.[hash].js

A tartalma pedig rendes html, mégpedig a scripteket betöltő html tartalmával azonos.
Egyedül a scripts.[hash].js file tartalma valid javascript. Újratöltve az oldalt a fenti 3 javascript már jól töltődik be. Első látogatások alkalmával tapasztalható, ha már egyszer betöltött jól az oldal többet nem jelentkezik. Azt nem tudnám megmondani, hogy mennyi idő után jön elő újra. Teszten is tapasztalható (gondolom azért mert azonos a szoftver stack).

**Comment by Rossi73** [comment]
Én Firefoxon (73.0.1, 64 bites verzió) dolgozom, ott is ugyanezt tapasztalom. A konzolon az alábbi 4 hibaüzenet jelenik meg:

1. A(z) https://onlineszamla.nav.gov.hu/styles.7cb7515f256f875837ed.css stíluslap nem töltődött be, mert a MIME-típusa „text/html” a „text/css” helyett. - onlineszamla.nav.gov.hu
2. SyntaxError: expected expression, got '<' - runtime.b038............de43.js:1
3. SyntaxError: expected expression, got '<' - polyfills.ce3f............e586.js:1
4. SyntaxError: expected expression, got '<' - main.ff4e............4eda.js:1

Frissítés (F5) vagy erőltetett frissítés (Ctrl+F5) megnyomása után általában megjavul, és rendben betöltődik az oldal. Teszten és élesen egyaránt.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Utána nézünk és jelentkezünk.

**Comment by connorhu** [comment]
Köszi!
Annyi plusz infóm van még, hogy mindez a /home -ra való redirection előtt történik amikor a path ennyi: /

**Comment by szecsenyizoltan** [comment]
Nekem:
Failed to load resource: the server responded with a status of 504 (Gateway Timeout)

**Comment by szecsenyizoltan** [comment]
refresh után:
GET https://www.googletagmanager.com/gtag/js net::ERR_ABORTED 504 (Gateway Timeout)
main.277d960d2cb9c7008510.js:1 angular-gtag: pageview none {page_path: "/home", page_title: "E-Invoice", page_location: "https://onlineszamla.nav.gov.hu/home"}
www-embed-player.js:389 GET https://googleads.g.doubleclick.net/pagead/id net::ERR_BLOCKED_BY_CLIENT
Je @ www-embed-player.js:389
Ie @ www-embed-player.js:375
(anonymous) @ www-embed-player.js:668
M @ www-embed-player.js:264
Ti @ www-embed-player.js:665
ee @ www-embed-player.js:678
ej @ www-embed-player.js:683
fj @ www-embed-player.js:684
(anonymous) @ www-embed-player.js:701
(anonymous) @ bGw_wbrA7gE:12
www-embed-player.js:424 GET https://static.doubleclick.net/instream/ad_status.js net::ERR_BLOCKED_BY_CLIENT
xf @ www-embed-player.js:424
uf @ www-embed-player.js:421
tf @ www-embed-player.js:420
Gf @ www-embed-player.js:435
(anonymous) @ www-embed-player.js:703
(anonymous) @ bGw_wbrA7gE:12


Van microblock telepítve nálam.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Köszi a türelmet és a jelzést! Megnéztük és adunk ki rá javítást. A következő fő verzióba már sajnos nem tudtuk beletenni, de az azt következő fő verzióba bele fog kerülni. 

A ticketet lezárom, de ha van még kérdés akkor nyissatok újat nyugodtan.

**Comment by connorhu** [comment]
Nálam ez a hiba most az éles weboldalon előjött. Majd jelezzétek itt ha kikerült élesbe. a javítás, hogy tudjam mikortól nem kéne látnom.
