### ISSUE TITLE
[Q&A]

### ISSUE THREAD

**Issue by veerede** [nav-gov-hu/Online-Invoice#169]
Sziasztok!

Két gondot találtam: 
1. Az adószám ellenőrzés a tavaly még EVÁ-s cégeknél, még mindig a vatCode 3-as értéket ad.
2. A QueryInvoiceDigestResponse  SIMPLIFIED számla esetén nem ad összeg információt
(invoiceNetAmount,invoiceVatAmount,invoiceVatAmountHUF)

Üdv
Ede

**Comment by NTCA-supporter** [comment]
Szia @veerede!

1. Ha az adószám ellenőrzés alatt a /gueryTaxpayer operációt érted, akkor abban a NAV-tól kapott adatokat adjuk vissza változtatás nélkül.
2. Ez így helyes is, hiszen a SIMPLIFIED számla esetén ezeket nem kell megadni. Ha megnézed a invoiceData.xsd-t akkor az invoiceSummary tag-nél egy choice található, ahol külön van választva, hogy  NORMAL és AGGREGATE számláknál miket kell megadni és miket SIMPLIFIED számláknál. Az említett 3 összeget pedig nem lehet megadni SIMPLIFIED esetén, ezért nem is tudjuk visszaadni.

Ha van még ezzel kapcsolatban kérdésed akkor tedd fel nyugodtan, ha nincs akkor kérlek zárd le.

**Comment by veerede** [comment]
Nézd felénk a TI vagytok NAV. 
1. A neten már a legtöbb forrás jól adja vissza az adószámomat. Csak jelezni akartam, hogy a törzs elég régi, hiszem január 1. től nincs EVA.
2. Ismerem a sémát. Csak a számla listázó funkcióban nem biztos, hogy megbocsátható, hogy azért nem jön semmilyen összeg információ (néhány számla kapcsán), mert egyszerűsített számlaként látta meg a napvilágot.

Nekem egyik sem életbevágó, inkább csak jelezni akartam felétek. 
(szóval lezárhatod)
Üdv
Ede
