### ISSUE TITLE
[FEATURE] Hibaüzenetek listája

### ISSUE THREAD

**Issue by vectorkovacspeter** [nav-gov-hu/Online-Invoice#170]
Üdv!

Kérdésem, hogy valamilyen emészthető formában elérhetők-e a rendszer által adott hibakódok és hibaüzenetek, vagy csak a PDF-ből lehet ezt megszerezni?

A cél ezekkel az üzenetekkel, hogy adott hibakód alapján automatikusan segítünk a szoftverünk felhasználójának, hogy értelmezze/elhárítsa az adott hibát, vagy pontosabb hibajegyet küldjön felénk.

**Comment by NTCA-developer** [comment]
Szia @vectorkovacspeter !

Mi a probléma a PDF-es forrással? Felteszem nem az abból történő kimásolás okozza a problémát, hanem valami más. Mire volna szükségetek a validationErrorCode listán kívül? A lokalizált, 3 nyelvű message értékek kellenének, vagy valami másra kell gondoljak?

**Comment by vectorkovacspeter** [comment]
Valójában a kimásolás a probléma, mivel ezek táblázatnak tűnnek a pdf-ben is, sokkal jobban lehetne felhasználni, és nyomon követni őket, ha lenne hozzájuk egy xml/csv/xlsx vagy bármilyen formátumú adathalmaz, amiben benne vannak a kódok, kategóriák, és üzenetek.
ennek segítségével gyakorlatilag készíthetnénk egy NAVtoHuman szótárat, ami segít a felhasználóknak és helpdeskeseknek értelmezni a sikertelen felküldés vagy a figyelmeztetést okát.

A ValidationMessage -ek amik jönnek nagyon klasszak, de szeretnénk kiegészíteni őket esetleges szoftver specifikus segítséggel, pusztán UX szempontból.

pl.:
BVCode: INCORRECT_HEAD_DATA_CUSTOMER_TAX_NUMBER
BVMsg: Vevő adószáma nem létezik.

ez persze oké, és érthető is, ez esetben mondjuk beleírnám, hogy "Kérem látogasson el az ügyfél törzsbe, és az adószám rovatban ellenőrizze/javítsa a vevő adószámát" vagy efféle

**Comment by kabelnet2** [comment]
Csatlakozok a kéréshez, tényleg segítség lenne egy ilyen teljes lista. Jelenleg a PDF-ből vadászom össze, ami persze megy, de nem is egyszerű. Nekem csak a kódok kellenének (pl. INCORRECT_XXXX...) vagy bármi amiből ezek egyszerűen kinyerhetők.

**Comment by NTCA-developer** [comment]
Kitalálok valamit, csak az a gond hogy biztosan engedélyeztetni kell majd. Adjatok egy kis időt, elindítom és visszajelzek.

**Comment by hamvasgy** [comment]
Szeretnék érdeklődni, történt-e előre haladás ez ügyben, várható-e, s ha igen akkor mikorra várható xml/csv/xlsx formátumú error/warning lista?

**Comment by NTCA-developer** [comment]
Szia!

Volt egy jó kezdeti koncepció ami megrekedt. Nem tudom mikor tudjuk felmelegíteni, de azt megígérem hogy elfelejtve nem lesz.

**Comment by NTCA-developer** [comment]
Sziasztok!

Köszönöm a türelmeteket. Itt találjátok a lokalizált értékeket (szinkron és aszinkron hibák is): https://github.com/nav-gov-hu/Online-Invoice/tree/master/src/i18n

Majd zárjátok le a ticketet pls!

**Comment by vectorkovacspeter** [comment]
Szuper, köszönjük!
