### ISSUE TITLE
[Q&A] Változások követése

### ISSUE THREAD

**Issue by zsom** [nav-gov-hu/Online-Invoice#171]
Tisztelt Fejlesztők!

Az aktuális dokumentció, ha jól látom itt érhető el: https://onlineszamla-test.nav.gov.hu/api/files/container/download/Online%20Szamla_interfesz%20specifik%C3%A1ci%C3%B3_HU_v2.0.pdf

1, Honnan lehet tudni, hogy ez mikori dokumentum? Ugyan ilyen néven volt korábban is közzétéve.

2, Hasonlóan, az xsd-k innen érhetőek el: https://onlineszamla-test.nav.gov.hu/api/files/container/download/OSA%20Schemas_v2.zip de itt is mindig ugyanazzal a névvel és verzióval (2.0)

Nem lehetne a file nevekben, vagy valami leírókban jelezni, hogy ez ugyan a 2.0-ás főverzióhoz tartozik, de vannak benne kisebb javítások, módosítások? Pl a fenti állományok verziója lehetne 2.0.X 
Így fejlesztésnél könnyebb lenne ellenőrizni, hogy az aktuális verziót használja-e a program.

3, Van valami levelező lista, vagy olyan csatorna, ami értesítene engem, ha változás van az xsd-kben?

Köszönettel:
Varga Zsombor

**Comment by NTCA-developer** [comment]
Szia @zsom !

Amikor dokumentációt publikálunk, akkor az a teszt és az éles frontendre is azonnal felkerül, így mindegy melyik környezetben nézed, ugyan azt kell látnod. Hogy mikori a doksi két dologból is látszik:
- a frontenden a fájlnév mögött pirossal írva van egy dátum, ami jelzi hogy mikor frissítettük utoljára
- magán a dokumentumon belül a 9-ik oldalon kezdődik egy dokumentum történet, ahol az egyes változások lényegi része és a közzététel dátuma is látható

Az XSD-k esetében fontos hogy ne a fájlnévben verziózzunk, különben path eltérések lesznek és nem szigorúan nézve nem is azt publikálnánk ki, mint ami nálunk belül van. Hogy mikori a séma, azt is két helyről láthatod, egyrészt a frontenden az utoljára frissítve dátumból, illetve az XML deklarációs részéből:

`<?xml version="1.0" encoding="UTF-8"?>`
`<!--`
`# Projekt: Magyar Online Számla Rendszer invoiceApi XML XSD séma`
`# Author: NAV Informatikai Intézet`

`# Version: v2.0 2020/02/06`
`-->`

Ha változik az XSD, akkor azt a Githubon (és jellemzően mindig sokkal előbb, mint ahogy az új sémát használni lehetne) publikáljuk. Ezekről a frissítésekről kapsz automatikus értesítést, ha watch-olod a projectet. Ezt a jobb felső sarokban lehet beállítani.

**Comment by zsom** [comment]
Szia @NTCA-developer !

Köszönöm a válaszokat.
Véleményem szerint így kicsit nehezebb követni/észrevenni a változásokat, de elfogadom az érveidet.

Az értesítésekhez elegendő a "release watch", vagy mindent kéne? 

Üdv:
Zsombor

**Comment by NTCA-developer** [comment]
Mindent kellene, mert release csak akkor megy ki amikor egy API verzió élesedik. Eddig 2 volt (1.0, 1.1), az is utólag lett kiadva, mivel Github később lett. Most áprilisban jön a 2.0, év végén a 3.0 és utána nem látunk mást.

Amikor a séma változik akkor az erről szóló commit message kell neked, és ahhoz sajnos nem elég a release-t nézni. Majd zárd le kérlek ha nincs több kérdésed!

**Comment by zsom** [comment]
Rendben, köszönöm.
