### ISSUE TITLE
[Q&A] Mit kell lekérdezni ahhoz, hogy egy számla adatszolgáltatás teljesítettnek legyen tekintve?

### ISSUE THREAD

**Issue by lakatoskevin** [nav-gov-hu/Online-Invoice#172]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Jelenleg az általam fejlesztett szoftver lekérdezi mind a számla, és a tranzakcióra vonatkozó státuszt (queryInvoiceCheck, queryTransactionStatus), így rendre azt a választ kapom, hogy "true" és "DONE". Viszont elég lenne az is ha egyenként lekérdezné a számlák státuszát is? (Csak a QueryInvoice Check vagy pedig csak queryTransaction Status?)

**Comment by NTCA-developer** [comment]
Szia @lakatoskevin !

Elbizonytalanítottál, hogy a számla státusza alatt te mit értesz. A queryInvoiceStatus és a queryTransactionStatus ugyan annak az API operációnak a v1-es illetve a v2-es neve, ezek logikailag egyenértékűek és mindketten a tranzakció feldolgozási státuszát adják vissza.

Segítesz megértenem a különbséget? Utána biztosan fogok tudni válaszolni.

**Comment by lakatoskevin** [comment]
Rosszul fogalmaztam. Nem queryInvoiceStatus-ra gondoltam, hanem "queryInvoiceCheck"-re. A "queryInvoiceCheck" true értéket ad vissza ha rendben volt a tranzakció, a "queryTransactionStatus" pedig DONE-t. Erre a kettőre vonatkozna az eredeti kérdésem is, ennek megfelelően javítottam is a kérdés kifejtését.

**Comment by NTCA-developer** [comment]
Értem már, köszönöm a pontosítást.

Nagyon fontos, hogy a queryTransactionStatus-t használd erre a célra. A számlát akkor tekintjük lekérdezettnek, ha bizonyítottan a queryTransactionStatus DONE státuszt adott vissza rá. A queryInvoiceCheck másra való, és ha csak azt használod akkor befejezetlennek minősül az adatszolgáltatás.

Így a kérdésedre a válasz az, hogy az adatszolgáltatás befejezéséhez a queryTransactionStatus elég, de fontos hogy ezt használd, ne pedig másik operációból vonj le a sikerességre következtetéseket.

**Comment by lakatoskevin** [comment]
Köszönöm a választ! Részemről akkor le is lehet zárni ezt az issue-t.
