### ISSUE TITLE
[Q&A]/metricService nem aktív

### ISSUE THREAD

**Issue by tkelemen73** [nav-gov-hu/Online-Invoice#173]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Csak nekem nem működik, vagy még nem aktív? A dokumentációban már megjelent a 8-as fejezetben, WADL-ben nincs benne, illetve HTTP/1.0 404 Not Found választ ad csak.
Lehet, hogy még nem működik, de az is, hogy valamit nem jól csinálunk?

**Comment by NTCA-supporter** [comment]
Szia!

A dokumentáció kicsit megelőzte a fejlesztés élesítését, ezt nézd el nekünk. A 2.9-es verzióban lesz elérhető, az Informatikai változások menüpontban és a híreknél biztosan jelezni fogjuk.
Zárhatom?
Köszi

**Comment by tkelemen73** [comment]
Szia, köszönöm, számomra ez megnyugtató válasz! ;) Persze, zárható!
