### ISSUE TITLE
Modification Index probléma

### ISSUE THREAD

**Issue by kurucza** [nav-gov-hu/Online-Invoice#174]
Sziasztok,

Szeretnék segítséget kérni Modifaction Index problémával kapcsolatban:
- Készült egy számla (eredeti-CREATE):''A számla''

-Hivatkozással készül egy visszáru jóváírás ''B számla'', ami batchInvoice.  
Ebben 2 BatchIndex van : ''C számla'' és ''A számla''
''C számla'' modificationIndexe: 1 ''A számla'' modificationIndex: 2

-Ismételten készül egy visszáru jóváírás, ami ugyancsak batchInvoice.  
Ebben 2 BatchIndex van: ''C számla'' és ''A számla''
''C számla'' modificationIndexe: 2 A számla modificationIndex: 3

-''A'' számlára hivatkozva készül egy Terhelés: ''D számla''. Ez a számla nem BatchInvoice
A ''D számla'' Modification Indexe:3

Erre az 3as Indexre kapunk egy Aborted státuszt, miszerint:MODIFICATION_INDEX_NOT_UNIQUE

Ha végignézzük a láncot, az ''A számlának' a ''D számla'' a harmadik módosítása.

A dokumentációbana  következő kitétel szerepel:
''Kötegelt módosításról történő adatszolgáltatás során nem lehet ugyanannak a számlának
ugyanazon módosítását többször szerepeltetni a kérésben. Másként fogalmazva, a teljes XMLben a módosítások által hivatkozott számla számának (invoiceReference) és a módosítás
sorrendiségét leíró elemnek (modificationIndex) egyedinek kell lennie''

''Az egyediség vizsgálat azt is jelenti, hogy a korábbi verziójú (1.0, 1.1) és módosító vagy stornó
adatszolgáltatások (ahol a modificationIndex még nem szerepelt) kiesnek az egyediség vizsgálatból. A rendszer nem vélelmez a korábbi módosító vagy stornó számlák között és az új 2.0-ás módosító és stornó számlák között sorrendiséget, azonban a logikailag inkonszisztens módosítások''

Segítsetek kérlek abban, mi a teendő, hogyan tudjuk helyesen megadni a Modification Indexet? Minden egyes esetben rá kellene vizsgálni az összes Batchre, az összes számlára? Az összes hivatkozásra, ahol szerepel az ''A számlám''?

ELőre is köszönöm a választ!

**Comment by NTCA-supporter** [comment]
Szia @kurucza !
"Ebben 2 BatchIndex van : ''C számla'' és ''A számla''": ezt úgy érted hogy az egyes hivatkozások a batchIndex-ek alatt az A és C számlára hivatkoznak?

Ha igen:
- az első batchInvoice-ban úgy kellett volna, hogy mindkét batchIndex alatt 1-es modificationIndex-el kezdesz, ha azok az első módosítások a számlaláncban. (A modificationIndex-nek az adott CREATE-es számlára hivatkozó számlák között kell, hogy egyedi legyen. Ha egy batchInvoice-on belül különböző CREATE-es szálákra hivatkozol, akkor nyugodtan lehet ugyanaz a modificationIndex mindkét hivatkozásnál.)
- ha csak az A számla számlaláncát nézzük, akkor az utolsó módosításban a 4-es indexet tudod használni, hiszen: 2-es volt az első batchInvoice-ban, 3-as a másodikban.

Ha nem, akkor esetleg valamilyen ID-val tudsz segíteni, ránézünk ha szükséges.

Köszi!

**Comment by kurucza** [comment]
Köszi szépen a választ, a probléma meg is oldódott!
