### ISSUE TITLE
Apró doksi elírások

### ISSUE THREAD

**Issue by bcdel** [nav-gov-hu/Online-Invoice#175]
Apró, elírásnak tűnő dolgok következnek. Nem kritikusak.

**A hibás dokumentum neve / Document name containing the error**
Fájlnév vagy hostolt URL / File name or hosted URL.

Online Szamla_interfesz specifikáció_HU_v2.0.pdf

**Oldalszám / Page number**
A hibát tartalmazó oldal száma / Page number containing the error.
**A dokumentációs hiba leírása / Description of the documentation error**
Rövid és tömör összefoglalása a hibának. / A clear and concise description of the summary of the error.

pdf page 23 (13. oldal)

1.6.1 ... Context root /invoiceService
1.6.2. Erőforrások
/mana....

A kettő között valahol nem hiányzik egy /v2/  ?

--------

pdf page 169 (159. oldal)

5.3 ... 2.0-ás verzió
Általános módosítások ...
API XSD általános ...
3) ... ld. 1.7.9 fejezet. ...  <<<<----
API XSD operációk ...
1) 1.9.1  ... <<<<----
3) 1.9.3 1.9.4 1.9.5 <<<<----

Szerintem 1.6.9 , 1.8.2   1.8.4 1.8.5 1.8.6 a renumber óta.

---------

Egyéb vélemény:

A dokumentáció pontjainak ilyen módú átsorszámozása az ilyen hibák mellett kényelmetlenné teszi azon implementációk kezelését, ahol az implementáció hivatkozik (commentben)
a specifikáció valamely pontjára. 

Pedig semmi nem szól az ellen, hogy pl:

1.9.3 A /queryIncoiceStatus operáció

Az operáció a V1.1 verzióban volt utoljára támogatva a V2.0-tól kivezetésre került, helyette a 
/queryTransactionStatus operáció használandó lásd 1.9.($n+1) stb...

**Comment by NTCA-supporter** [comment]
Szia @bcdel !

Köszi az észrevételeket, igyekszünk minél hamarabb javítani.
Jelzek ha kikerült a felületre a frissített doksi, addig nyitva hagyom az issuet.

Üdv

**Comment by NTCA-supporter** [comment]
Szia!

Amiket jeleztél, javítottuk, kitettük teszt/éles környezetre.
Most sajnos nincs kapacitás az összes hivatkozás átnézésére, ha esetleg még találtok, megköszönjük a jelzést továbbra is.
Ezt az issuet most zárom.

Köszi
