### ISSUE TITLE
[Q&A] queryServiceMetrics 404

### ISSUE THREAD

**Issue by vectorkovacspeter** [nav-gov-hu/Online-Invoice#176]
Üdv,

A https://api-test.onlineszamla.nav.gov.hu/metricService/v2/metric/queryServiceMetrics és https://api.onlineszamla.nav.gov.hu/metricService/v2/metric/queryServiceMetrics végpont és minden kapcsolódó végpontja nekem mindig 404 -es választ ad, én néztem el valamit, vagy nem működik még a metrics?

**Comment by NTCA-supporter** [comment]
Szia!

Lásd #173 
2.9 verzióval lesz elérhető.

Zárom az issuet, köszi!
