### ISSUE TITLE
[Q&A] ProductCodeValueType nem megengedett karaktert tartalmaz

### ISSUE THREAD

**Issue by ogiwogi** [nav-gov-hu/Online-Invoice#177]
mi a teendő, ha a vállalat által használt cikkódok a ProductCodeValueType szerint nem megengedett karaktereket - például pontot - tartalmaznak?

**Comment by kabelnet2** [comment]
A vállalat által használt cikkszámok csak OWN-ként adhatók meg, akkor viszont produczCodeOwnValue-ba kerük az érték, ami egy max 255 karakteres karaktersorozat, lehet benne akármi.

**Comment by ogiwogi** [comment]
és mi van akkor, ha az SZJ számot használja a cég cikkszámnak, mégpedig úgy, hogy a pontokat is megadja közben? például:
<ext_data:productCode>										<ext_data:productCodeCategory>SZJ</ext_data:productCodeCategory>							<ext_data:productCodeValue>10.10.13.0</ext_data:productCodeValue>
</ext_data:productCode>

**Comment by NTCA-developer** [comment]
Sziasztok!

Ezt a kérdést az interfész dokumentáció rendezi. Azért emlékszem rá mert ez a kérdés az 1.0 óta velünk van és én is feltettem még az elején.

> 2.2.3.1.3 productCodes
> 
>...
> Az egyes kódokat (a saját termékkód kivételével) – a sémának megfelelően – kizárólag nagybetűk és számok használatával kell feltüntetni akkor is, ha a kód egyéb karaktereket (pl. pont, kötőjel, szóköz stb.) is tartalmaz.

**Comment by kabelnet2** [comment]
Én meg azt válaszoltam volna, hogy SZJ számok azok, amik a dokumentációban megadott SZJ törzsben vannak és azokban nincs pont. Tehát ha ponttal szeparált SZJ számot akarsz megadni, az megint csak OWN...

**Comment by NTCA-developer** [comment]
Én az eredeti kérdésre fókuszáltam, az SZJ csak egy későbbi példában jött fel. Nem mondunk mást, csak én a generikus szabályt írtam.

**Comment by kabelnet2** [comment]
Persze, természetesen.
