### ISSUE TITLE
[Q&A] THK áfakód vatExemption vagy vatOutOfScope ?

### ISSUE THREAD

**Issue by floreagyorgy** [nav-gov-hu/Online-Invoice#179]
Sziasztok!

A THK azaz a területi hatályon kívüli áfakódot VatExemption-ként vagy vatOutOfScope-ként kell feladni?

Volt már régebben egy kérés egy sorvezetőre az áfamentes számlák feladásával kapcsolatban [https://github.com/nav-gov-hu/Online-Invoice/issues/83](url), de nem találok sehol ilyet azóta sem.

**Comment by NTCA-tax** [comment]
Az áfa hatályán kívüli értékesítés és az adómentes értékesítés az áfa törvény szempontjából két eltérő fogalom. Ezért is került bele a sémába a VatExemption és a vatOutOfScope. Amennyiben áfa hatályán kívüli értékesítés történik, akkor a vatOutOfScope elem true lesz.

**Comment by floreagyorgy** [comment]
Ezek szerint a THK áfakód (az Áfa területi hatályon kívül) esetében a vatOutOfScope=true.

Én is így gondoltam, csak elbizonytalanodtam, mert a NAV Online Számlázó programja vatExemption="THK" beállítással adja fel a THK (Területi hatályon kívül) áfakódú számlatételt – legalábbis a teszt oldalon –, ezek szerint hibásan.

**Comment by NTCA-tax** [comment]
Köszönöm a jelzést, most már értem a kérdés okát. Sajnos itt a NAV Online Számlázó nem a megfelelő helyen jelöli a területi hatályon kívüli értékesítést, ezt mindenképpen javítanunk kell. Köszönöm még egyszer, hogy jelezted ezt a problémát!
