### ISSUE TITLE
[DOC] Hibás érték a számlamintákban (14. példa)

### ISSUE THREAD

**Issue by Rossi73** [nav-gov-hu/Online-Invoice#181]
**A hibás dokumentum neve / Document name containing the error**
Fájlnév vagy hostolt URL / File name or hosted URL.
https://onlineszamla-test.nav.gov.hu/api/files/container/download/Sz%C3%A1mlamint%C3%A1k.zip

**A dokumentációs hiba leírása / Description of the documentation error**
Rövid és tömör összefoglalása a hibának. / A clear and concise description of the summary of the error.
A 14_Tételadatok módosítása.xml fájl 83. sorában ez szerepel:
`					<unitOfMeasure>TON</unitOfMeasure>
`

Az XML-hez tartozó leírás (!Számlaminták_v2.0_20200115.pdf) 20. oldalán a termék mennyisége 1 m2. A "TON" értéke nincs szinkronban a négyzetméterrel.

**Comment by NTCA-supporter** [comment]
Szia @Rossi73 !
Valóban hibásnak tűnik. Köszi a jelzést, igyekszünk hamar javítani.

Addig nyitva hagyom az issuet, jelzek ha kikerült a javítás.

Üdv

**Comment by NTCA-supporter** [comment]
Szia @Rossi73 !
Javítottam teszt és éles környezeten is.
Köszi mégegyszer, zárom az issuet.
