### ISSUE TITLE
[Q&A] QueryTaxPayer v2.0

### ISSUE THREAD

**Issue by kovadam69** [nav-gov-hu/Online-Invoice#182]
Sziasztok!

Csinálom a 2.0-s API séma támogatást, és azt vettem észre, hogy a v2.0 APIra küldött QueryTaxPayer nem ad vissza semmilyen más adatot, csak a cég nevét. A v1.1 ugyanarra az adózóra rendesen kitölti a címadatokat is, míg a 2.0 csak a cégnevet.
Bevezetésre került egy shortname (cég rövid neve) mező is, de az is üres minden adózónknál.
Lehetséges, hogy a 2.0-s API még nem adja vissza ezeket az adatokat, vagy én rontok el valamit a lekérés feldolgozásánál?
Ezt az éles rendszeren próbáltam!

**Comment by connorhu** [comment]
Szia!

Volt már ilyesmi kérdés: #146

**Comment by kovadam69** [comment]
Köszi, elolvastam, de ez nem igazán válaszolja meg a kérdésem, hogy miért csak és kizárólag a cég teljes nevét kapom meg, és egyáltalán nem kapok semmilyen címadatot.

**Comment by kovadam69** [comment]
Közben rájöttem, hogy még a február 17-i séma frissítés előtti változatot használom, ezért volt rossz a lekérdezés! Ebben valóban segített a belinkelt kérdés, mert abban említett olyan mezőt, ami nekem nem volt a sémában :)
Zárom!
