### ISSUE TITLE
[Q&A]Devizás előleg-végszámla beküldés

### ISSUE THREAD

**Issue by burnyo** [nav-gov-hu/Online-Invoice#183]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Elnézést, látom, hogy született korábban ebben a témában egy issue, de sajnos nem találtam megnyugtató és alkalmazható választ azzal kapcsolatban.
Nálunk is megjelentek az új WARNING-ok az árfolyamokkal kapcsolatban és a vállalati szakemberek nem tartják elfogadhatónak, hogy mindent a végszámla árfolyamán küldjünk be. Sajnos én csak technikailag látom a problémát, de az alábbi felvetések jutottak el hozzám, miszerint a jelenlegitől eltérő kezelés alkalmazandó, kérem nézzék meg ezeket a szempontokat is. A választ előre is köszönöm!

"Az Áfa törvény előírásai szerint az előleg átvételének, jóváírásának időpontjában adófizetési kötelezettséget keletkeztet. Az előleg forintra történő átszámításához a fizetendő adó megállapításának időpontjában érvényes árfolyamot kell alkalmazni. Az előleg fizetése esetén a fizetendő adó megállapításakor (előleg esetén ez az áfatörvény 59. §-a értelmében az előleg átvételének, jóváírásának időpontjában) érvényes árfolyam alkalmazandó a külföldi fizetőeszközben kifejezett előlegszámla adóalapjának forintban történő meghatározásakor. Természetesen az előlegszámlában a fizetendő adó összegének forintban történő feltüntetéséhez szükséges számítást is ezen az árfolyamon kell elvégezni. A teljesítéskor az ügyletre vonatkozó számlában – mivel az előleg és a fennmaradó összeg eltérő időpontban, külön-külön képez adóalapot – az adóalapot meg kell bontani, tekintettel arra, hogy az adó alapjának forintra történő átszámításakor az előlegre és a fennmaradó összegre különböző időpontban érvényes árfolyam alkalmazandó.

A vonatkozó paragrafusok az ÁFA törvény szerint:

    59. § (1) Termék értékesítése, szolgáltatás nyújtása esetében, ha a teljesítést megelőzően ellenértékbe beszámítható vagyoni előnyt juttatnak (a továbbiakban: előleg), a fizetendő adót pénz vagy készpénz-helyettesítő fizetési eszköz formájában juttatott előleg esetében annak jóváírásakor, kézhezvételekor, egyéb esetben annak megszerzésekor kell megállapítani.
    80. § (1) Termék értékesítése, szolgáltatás nyújtása, valamint termék Közösségen belüli beszerzése esetében, ha az adó alapja külföldi pénznemben kifejezett, a forintra történő átszámításhoz azt a (2) bekezdésben meghatározott árfolyamot kell alkalmazni, amely
    a) termék Közösségen belüli beszerzése, illetőleg előleg fizetése esetében, valamint a 60. §-ban említett esetekben a fizetendő adó megállapításakor,
    érvényes.
    172. § A számlán az áthárított adót [169. § k) pontja] - a 80. § szerint meghatározott árfolyam alkalmazásával - forintban kifejezve abban az esetben is fel kell tüntetni, ha az egyéb adatok külföldi pénznemben kifejezettek."

**Comment by NTCA-tax** [comment]
Az előleg és a végszámla két önálló számla, melyet ebben az esetben külföldi pénznemben állítanak ki. Amennyiben eurós számláról van szó, akkor az euró pénznemet kell elsődlegesnek tekinteni mind az előlegnél, mind pedig a végszámlánál. A forint összegnek kizárólag az áfa összegnél van jelentősége.

Ha van például egy euróban kiállított előleg számla, amiben az adó összegét 300 forintos árfolyamon határozták meg. A végszámla kiállításánál a forint árfolyama 330. Ekkor úgy kell eljárni a végszámlánál, hogy euróban szépen levezeti a társaság a különbözetet, és az előleg beszámítását követően a még fizetendő összeg adóját számítja 330 forintos árfolyamon. Tehát a végszámla kiállításánál nincs jelentősége annak, hogy az előleg számla kiállításakor mi volt az árfolyam.

**Comment by RvPSc** [comment]
Üdv!
Ez a válasz sajnos számomra sem elfogadható. Akkor az előleg tételnél a forintban kifejezett soron valótlan adatot küldjünk? Hiszen az előleg beszámító sornál a unitPriceHUF a fenti példa szerint 300 lesz. Ha 330-at adok meg, valótlan a bejelentésem. Ha 300-at, akkor meg visszadobják. Szívesen küldök egy XML-t, illetve szívesen fogadok egy olyan XML-t amiben a fentiek szerint minden adat helyes. Illetve ez a rész is teljesen világos: "_euróban szépen levezeti a társaság a különbözetet, és az előleg beszámítását követően a még fizetendő összeg adóját számítja 330 forintos árfolyamon_"
De ebből a számla fizetendő áfája lesz meg, az előleget levonva. Az előleg tételre vonatkozó unitpriceHUF elemet hogyan használjuk? Sajnos egyre több ügyfelünk fut bele a problémába. Vagy maradjon az a megoldásunk, hogy mivel az adatszolgáltatás megtörténik, elnyeljük a "hibát"? Viszont ebben az esetben meg az önök kérésének nem tudunk eleget tenni, miszerint törekedni kell a hibátlan adatszolgáltatásra.

**Comment by KMGY100** [comment]
A beküldés  hibamentes volt.

[Előlegszámla.txt](https://github.com/nav-gov-hu/Online-Invoice/files/4763196/Elolegszamla.txt)
[Végszámla.txt](https://github.com/nav-gov-hu/Online-Invoice/files/4763197/Vegszamla.txt)

Nem tudom előkeresni azt az Adóújságot melyben pontosan kifejtik , hogy így a megfelelő)

**Comment by clapygeza** [comment]
Szia!
Mi így csináljuk:
Előlegszámla: 500 EUR + áfa, 300 Ft-os árfolyamon: adóalap 500EUR/150000 HUF, áfa: 135 EUR/40 500 HUF. 300 Ft/EUR árfolyammal jelented az xml-ben.  Ezt a számlát mindkét cég, a kibocsátó és a befogadó is beteszi az áfa bevallásba. A kibocsátó (135*300) 40 500 Ft áfát fizet, a befogadó ugyanennyit igényel vissza, tehát ez ok.
A végszámla 1000 EUR + áfa, 330-as árfolyamon. Az adóalap 1000-500 EUR (előlegszámla levonva), az áfa 270-135 EUR. 330 EUR/HUF árfolyammal forintosítva jelented. Az áfa (135 * 330 ) 44 500 Ft amit a kibocsácsó szintén befizet, a befogadó visszaigényel, tehát is minden ok. 
Így hibamentes (remélem jól számoltam az értékeket :) )

**Comment by RvPSc** [comment]
KMGY, köszönöm a választ. Tehát "kamu" értékkel kell beküldeni és akkor befogadják.
Clapygeza, a Te válaszod is köszönöm, de ez nem a kérdésre irányult. Tudom, hogy hogyan kell számlázni, illetve bevallani. Azt nem tudtam, hogy az előleg beszámító soron hogyan forintosítsam. Lényeg ami lényeg, ha volt egy eredeti sorom, például (350 vs 330) <lineVatAmount>135</lineVatAmount><lineVatAmountHUF>47250</lineVatAmountHUF>, akkor ha ez a tétel felhasználásra kerül, ott már <lineVatAmount>-135</lineVatAmount><lineVatAmountHUF>-44550</lineVatAmountHUF> lesz belőle. Nem tartom túl szép megoldásnak, mert így oda az elv, miszerint az adatszolgáltatásnak a számla adattartamáról kell szólnia. Nem beszélve arról, hogy ez könyvelési feladat lenne -> korrektebb megoldás lett volna, ha bekérnek ilyenkor egy eredeti árfolyamot, ami alapján könyvelhető az árfolyamkülönbözet.

**Comment by NTCA-tax** [comment]
Lehet, hogy ismételni fogom magamat, de még egyszer fontos kiemelni, hogy a számla pénzneme euró, a forintra történő átszámítás egyrészt az áfa bevallás miatt szükséges (az áthárított adó összegét át kell váltani forintra), valamint az adatszolgáltatásban, hogy legyen minden külföldi pénznemben kiállított számla összegszerű adatánál forint összeg (ez technikai információ, nem jelenik meg a számlán). De attól még az előleg számla és a végszámla euróban került kiállításra.

Árfolyamkülönbözet pedig nem minden esetben jelenik meg. Amennyiben a könyveit euróban tartja nyilván és euróban történik a számla kibocsátása, akkor nem beszélhetünk árfolyam különbözetről sem. Azt is szem előtt érdemes tartani, hogy a számviteli elszámolási elvek és az áfa törvény elszámolási elvei nem mindig egyezőek. Az adatszolgáltatás pedig az áfa elveit követi le.

**Comment by RvPSc** [comment]
Köszönöm! A kollégák módszerével fogom beküldeni. Remélem a későbbiekben sem kell majd a metódust vissza alakítanom és valós adattal, a valójában forintálisan "befizetett" áfa összeg szerint küldeni az adatszolgáltatást (például, ha össze lesz kapcsolva a rendszerben az előleg számla és a végszámla). Lássuk be, itt a korrekt működés az lett volna, hogy előleg tétel esetén beküldésre kerül az eredeti árfolyam is, ez kerül be a XY(HUF) mezőkbe és advancedinditactor true esetén ezt kalkulálva végzik el az ellenőrzést. Így a könyvelő programok is teljes információt kaptak volna a műveletről.

**Comment by MikorMi** [comment]
Üdv. Én csak most kapcsolódok be ebbe a témába, mert eddig nem kellett devizás áfás számlát feladnunk, de most előjött igényként... A mi könyvelőink szerint is a Ft összeget kell levonni, vagyis a végszámla teljes értékét kell figyelembe venni a saját árfolyamán és ebből le kell vonni az eddig megfizetett áfát Forintban.

Ami érdekes számomra, az az, hogy a 100.000-es értékhatárnál egyértelműen leírták, hogy a végszámlát az előlegek figyelembe vétele nélkül kell tekinteni, vagyis a teljes (előleglevonás nélküli) érték az áfafizetési kötelezettségünk! Most pedig - ha jól értem - azt írják, hogy a végszámla az előlegek levonása után tekintendő, azaz csak a különbözet az, ami az áfafizetési kötelezettségünk.

Ha a 100.000-es határt nézzük, akkor ezt a példát le kellett volna jelenteni?:

Teljes értékű előleg! 
Előleg áfája: 330 EUR,  árfolyam 300, áfa HUF: 99000 - nem kellett felküldeni.
Végszámla végösszege 0 EUR. áfája előleg nélkül 330 EUR, árfolyam 310, áfa HUF: 102300 - fel kellett küldeni???

A most - fentebb - vázolt elmélet szerint:
előleg áfa huf: 99000 - nem kell küldeni
végszámla 0 EUR - áfa 0 huf - nem kell küldeni

Viszont az induláskori instrukciók alapján ez egy felküldendő számla volt, mivel a végszámla áfatartalma az előlegek figyelembevétele nélkül meghaldja a 100000 Ft-ot!
