### ISSUE TITLE
TokenExchangeRequest probléme

### ISSUE THREAD

**Issue by hsnrdu** [nav-gov-hu/Online-Invoice#184]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu/invoiceService/v2

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[X] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[X] 2.0

**A requestId értéke / requestId value**
```
6CF8A6D264CA31261D680ECF688600
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Saját ellenőrzésem alapján minden legyártott HASH érvényes, ennek ellenére a 401 Unauthorized üzenetet kapunk vissza.
Ugyanez a teszt felhasználó az 1.1 verzióval gond nélkül kommunikál.

Köszönettel
Szabó Gábor
K&H

[GITHUB_log.txt](https://github.com/nav-gov-hu/Online-Invoice/files/4311405/GITHUB_log.txt)

*Egyéb tartalom / Additional content*

**Comment by NTCA-developer** [comment]
Szia!

Jól gondolom, hogy a jelszhash-t is átforgattad SHA3-ra? Mert azt nem kellene, csak a requestSignature-t.

**Comment by hsnrdu** [comment]
Attól tartok jól gondolod. javítjuk. Köszi!

**Comment by kharonx** [comment]
Sziasztok!

Az 1.2-ben jól működő tokenrequestet futtatva (a megfelelő módosításokkal), ezzel a requestel (kitöröltem/átírtam az egyedi részeket):

<?xml version="1.0" encoding="utf-8" ?>
<TokenExchangeRequest xmlns="http://schemas.nav.gov.hu/OSA/2.0/api">
    <header>
        <requestId>DFVjyJlQqcHjwow</requestId>
        <timestamp>2020-05-04T16:37:24.000Z</timestamp>
        <requestVersion>2.0</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
    <user>
        <login>technikailogin</login>
        <passwordHash>2ECA................F173</passwordHash>
        <taxNumber>..............</taxNumber>
        <requestSignature>..............</requestSignature>
    </user>
    <software>
        <softwareId>HUAPPNEVE10317</softwareId>
        <softwareName>Appneve</softwareName>
        <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
        <softwareMainVersion>10.0.354</softwareMainVersion>
        <softwareDevName>Mivagyunk</softwareDevName>
        <softwareDevContact>support@email.hu</softwareDevContact>
        <softwareDevCountryCode>HU</softwareDevCountryCode>
    </software>
</TokenExchangeRequest>

Ezt a response -t kapjuk:

<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<GeneralExceptionResponse xmlns="http://schemas.nav.gov.hu/OSA/2.0/api" xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/data">
    <funcCode>ERROR</funcCode>
    <errorCode>OPERATION_FAILED</errorCode>
    <message>Érvénytelen kérés!</message>
</GeneralExceptionResponse>

Tudnátok segíteni? 
Köszönöm előre is!
