### ISSUE TITLE
[FEATURE] Devizás előlegszámla számlaminta

### ISSUE THREAD

**Issue by Rossi73** [nav-gov-hu/Online-Invoice#185]
**Az igény összefoglalása / Summary of the request**
Kérjük a számlaminták kiegészítését egy devizás előleg-végszámla párossal.

**Az általam javasolt megoldás / The solution I propose**
A 6., 6/a és 7. példákat kérjük pl. EUR devizában elkészíteni (mind dokumentáció, mind xml formában), az előleg számlánál legyen 320 Ft-os euró árfolyam, a végszámlánál legyen 330 Ft-os euró árfolyam. A nettó összegek legyenek azonosak a 6., 6/a és 7. példában szereplő összegekkel.

**Egyéb tartalom / Additional content**
A számlaminták mindenki számára világos és egyértelmű eseteket tartalmaznak, nagyon jó a pdf-es számlakép és az xml együttes vizsgálatának lehetősége (a pdf-hez készített kísérő, magyarázó szövegeket külön köszönjük!). Változó árfolyam esetén fontos tudni, hogy az előleg és a végszámla esetében pontosan milyen árfolyammal, forint számítással kell dolgozni, hogy a forintban számított áfa mezőt (is) pontosan töltsük ki.

**Comment by NTCA-supporter** [comment]
Szia @Rossi73!

Továbbítom a megfelelő személyeknek és jelentkezem, ha kapok választ.

**Comment by NTCA-tax** [comment]
A számlaminta igényt felvettük a feladatlistánkba. Jelenleg időpontot nem tudunk mondani a megjelentetéséről, ahogy tudjuk, kirakjuk.
