### ISSUE TITLE
[FEATURE] Purchase Order / PO szám / Megrendelés azonosítós feltüntetése bejövő számlában

### ISSUE THREAD

**Issue by xcom169** [nav-gov-hu/Online-Invoice#186]
**Az igény összefoglalása / Summary of the request**
Rövid és tömör leírása a problémának, amiből az igény származik. / A clear and concise description of what the problem is, from which the request arises.

A könnyebb összekapcsolás végett hihetetlenül hasznos lenne, ha a bejövő számlák XML-jében megjelenne egy konkrét, standard helyen a Megrendelés azonosítója, amire a számla hivatkozik. 

**Az általam javasolt megoldás / The solution I propose**
Rövid és tömör leírása a javasolt megoldásnak. / A clear and concise description of the proposed solution.

A sémában javaslok felvenni egy új (akár nem kötelező)  mezőt, ami kimondottan ezt a célt szolgálná. 

**Elfogadható alternatívák / Acceptable alternatives**
Rövid és tömör leírása az elfogadható alternatíváknak, ha az igény nem valósítható meg az eredeti formájában. / A clear and concise description of the acceptable alternative solutions, in case the request is not doable in it's original scope.

**Egyéb tartalom / Additional content**
Szabad szöveges rész. / Own remarks.

Egy ilyen mező segítésével gond nélkül össze lehetne kötni a bejövő számlákat a PO-kkal, ami lehetővé tenné a bejövő számlák automatikus könyvelését.

**Comment by NTCA-tax** [comment]
Köszönjük a felvetést! A PO szám mellett nálunk még a szállítólevél szám van hasonlóan a listában. Jelenleg ez AdditionalData elemként adható meg, melynek a hátránya az lehet, hogy minden fejlesztő más tag nevet adhat neki. Megfontoljuk a következő séma változásnál a megoldási lehetőségét.

**Comment by omachtandras** [comment]
Szép napot mindenkinek!

Továbbgondolásra javaslom a dolgot. Napon belüli több szállítás, illetve gyűjtőszámla esetén előfordulhat, hogy a számla tételsorai összevont mennyiséget tartalmaznak, így jobb lenne egy olyan struktúra, ami biztosítja mind az egyszerű (számlánként egy rendelés vagy szállítólevél szám), mind a bonyolultabb (tételsoronként mennyiségi bontással történő rendelés vagy szállítólevél szám megadás) lehetőséget is.

Köszönöm!
