### ISSUE TITLE
[Q&A] INVALID_REQUEST_SIGNATURE

### ISSUE THREAD

**Issue by ocsike** [nav-gov-hu/Online-Invoice#187]
Üdv!
Az onlineszámla V2-ben van-e korlátozva a sorok száma? Van egy 38 soros számlám az bemegy hiba nélkül, de a 39 sorosra már hibát kapok: INVALID_REQUEST_SIGNATURE

**Comment by NTCA-supporter** [comment]
Szia @ocsike !

A sorok számára nincs, csak méretkorlátunk van, de a 39 sorral nem kellene, hogy gond legyen.
Így valószínűleg nálad lehet a gond, a request_signature számítás környékén. Volt hasonló issue, a #180 például. Ha küldesz valamilyen azonosítót, akkor rá tudok nézni, hogy mi lenne az elvárt request_signature a beküldésednél.

Köszi

**Comment by ocsike** [comment]
ITALMAGYARO2020031212545464320200312125454f5-8bc1-bf8837de4f7022STYURR4ZFXD194E0DE3A6BFAEDFA2DEE210058F18F8154CBE57F5C5E4F8FFD5F4F9B2FB028DE78C9FF1B6994107B7B479E00AB99678F5A85AB3AA17B2B2F278E94C4B67F44

Erre a request_sign: 30180193558BDCB13D5493C627B6CE50ABB9EC3F350ED47455579276E58D52C724BAB937930F35695F60858DD2D919E8DD8B4E9C250F05DB529D4C0EBC39A55F

**Comment by laladisc** [comment]
Szia!
Milyen programnyelvben fejlesztessz? Én is pont így jártam Delphiben, és a hash képző algoritmus amit használtam sok tételes (50+) számlánál nem jó értéket képzett, de sikerült megtalálni a megoldást.

**Comment by ocsike** [comment]
Szia!
Szintén Delphi, jó régi.  Mi volt a megoldás?

**Comment by laladisc** [comment]
Szerintem te is a Wolfgang Ehrhardt hash library-jét használod, mint ahogy én is. Ha így van, akkor nagyon egyszerű a megoldás, az SHA3_512FULL procedure helyett, a SHA3_512FULLXL procedure-t használd, mert az SHA3_512FULL-ban limitálva van a hossz érték és így kb 40 tételes számla fölött helytelen lesz a hash érték.

**Comment by ocsike** [comment]
Köszi szépen. Ez volt a megoldás, be is ment a számla :) 
Közben próbáltam tömörítve is küldeni a soktételes számlát az bement az eddig használt procedure-ral.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Köszi a segítséget @laladisc .
Zárom az issuet, ha van még kérdés, jelezzétek.
