### ISSUE TITLE
[DEV support]TokenRequest Hiba

### ISSUE THREAD

**Issue by hosszuful** [nav-gov-hu/Online-Invoice#188]
Üdv!
Segítséget kérnék a hiba megoldásához.

Két rendszerből is küldünk token kéréseket. Azt egyikkel nincs probléma a másikkal viszont nem tudunk jó kérést beküldeni. Mindig Bad Request hibát ad vissza.

A tokenekhez a felhasználó, jelszó, cserekulcs, aláírókulcs ugyanaz, tehát azzal nem lehet probléma. A beküldő program is ugyanaz tehát a RequestSignature előállítása is ugyanaz.

Nem tudom, hogy láttok-e valami különbséget a két kérés között.
A jó kérés azonosítója: 1007667
A rossz kérés azonosítója: 10004073

Köszönöm.

**Comment by NTCA-developer** [comment]
Szia!

Igen, látok különbséget. A rossz kérésben a softwareMainVersion tag tartalma sérti a sémát. A válaszban vissza is mutatja ezt, 5 karakterrel túlléped a megengedett hosszt:

`XSD validation error: [cvc-maxLength-valid: Value 'ORGANE_SZAMLA_2.18.2' with length = '20' is not facet-valid with respect to maxLength '15' for type 'SimpleText15NotBlankType'`

**Comment by hosszuful** [comment]
Köszi szépen! Kereshettem volna egy darabig :-)
