### ISSUE TITLE
[Q&A] KORONAVÍRUS issue

### ISSUE THREAD

**Issue by Kivancsikonyvelo** [nav-gov-hu/Online-Invoice#189]
Kedves Fejlesztők, NAV Döntéshozók

Fejlesztő cégként fordulunk Önökhöz: Tekintettel a jelenlegi vészhelyzetre, van-e arra  mód, hogy az Online számla Adaszlgáltatás 2.0-ás verziójának 2020. áprilisi 1-vel való indulásának dátumát későbbre lehessen halasztani?
Az iskolák bezárása miatt sok dolgozónk csak csökkent óraszámban tud dolgozni, ami így erőforrás hiányt von maga után, illetve az ügyfelekhez való telepítések egy részét - ami személyes jelenlétet igényelne -, sem tudjuk biztonságosan végrehajtani.

Megértő, pozitív válaszukat és segítségüket előre is köszönjük szépen.

**Comment by NTCA-developer** [comment]
Szia @Kivancsikonyvelo! 

Jelenleg is egyeztetések zajlanak a témában. Mindenképpen kommunikáljuk a döntést, türelmet kérünk.

**Comment by szako** [comment]
@NTCA-supporter: Nem csak fejlesztői, hanem az ügyfelek oldalán is problémák adódtak. Kérlek vegyétek ezt is figyelembe a döntéskor.

Köszönöm!

**Comment by alaplap** [comment]
Nem feltétlenül csak az április 1-vel ütemezett kötelező 2.0 bevezetését kellene mérlegelni - egyébként talán annak az időpontját lenne a legegyszerűbb elhalasztani, hiszen a jelenlegi mindkét XSD verzió elfogadását kellene megtartani március 31 után is.
A július 1-vel tervezett 0 Ft-os ÁFA értékhatár bevezetése - vagy a számlázóprogramok frissítése/beszerzése miatt, vagy pedig a megnövekedő adminisztratív terhek miatt - jelentős plusz költséget fog jelenteni leginkább a kkv-kra, ami azokra a szektorokra is igaz, amikre a jelenlegi helyzet elhúzódása komoly gazdasági károkat mérhet. 
_(Off topic: egyébként sem értettem, hogy miért kell két ütemben bevezetni a változásokat, hiszen így idén kétszer kell frissíteni minden ügyfélnél, ami a fejlesztőknek többlet munkával, a többi cégnek pedig plusz költségekkel jár .. nem valami gazdaság élénkítő megoldás. A 0 Ft-os ÁFA határ bevezetése önmagában nem indokolta a jelenlegi változásokat, hiszen a jogszabály eddig is megengedő volt és van, aki az elejétől fogva minden belföldi adóalanynak kiállított számláját jelentette.)_

**Comment by NTCA-supporter** [comment]
Sziasztok!

Még egy kis türelmet kérünk, mert ahogy ti is írjátok, nem csak a 2.0-at érinti a téma. Így a mindenki számára megfelelő döntéshez még egy kis idő szükséges. A hét végére/ jövő hét elejére ígértek választ.

**Comment by betasofthu** [comment]
Köszönöm!
Én is regisztráltam itt. Olvasom.
Írhatsz, ha megtudsz valamit.

Pogonyi László
Béta Software Bt. Eger
www.betasoft.hu
Tel.:20/9241-760
U..i:Az üzenetet kizárólag a címzett, illetve az általa meghatalmazottak
használhatják fel. Ha Ön nem az üzenet címzettje, úgy kérem,
hogy telefonon vagy e-mail-ben értesítsen erről, és törölje az üzenetet,
valamint annak összes csatolt mellékletét a rendszeréből.
Ha Ön nem az üzenet címzettje, tilos az üzenetet vagy
annak bármely csatolt mellékletét lemásolnia, elmentenie,
az üzenet tartalmát bárkivel közölnie vagy azzal visszaélnie.

**Comment by Robaj85** [comment]
Sajnos nálunk is borult az ütemterv, múlt héten telefonon jeleztük az ügyfélszolgálatnak hogy az egy szem programozónk le van terhelve, mert más szuper SOS feladatot kellett adni neki, hogy a kollegák rendben tudjanak dolgozni az új home office rendszerben. Azt mondták, jelzik az illetékesek felé, azóta el is tűnt a hírek közül az XML 2.0 április 1-jei bevezetése szöveg, de még nem került ki, hogy akkor ténylegesen el lesz halasztva - akár csak 1 hónappal is. (még ott van a 2019-hez hír, hogy április 1-től lesz xml 2.0)
Jó lenne ha ma-holnap kikerülne a végleges döntés, hogy mire számítsunk, mit kommunikáljunk az ügyfelek felé.

**Comment by NTCA-developer** [comment]
Sziasztok!

Mi a fejlesztési kapacitások kiesését kevésbé tekintjük valid érvnek mert a tesztrendszeren hónapok óta elérhető a 2.0, minden fejlesztés saját felelőssége hogy beárazza és kezelje a felmerülő saját kockázatait. De a helyszíni telepítésekkel kapcsolatos aggodalmak és nehézségek szerintünk is megalapozottak.

A NAV partner abban, hogy a rendkívüli jogrend okán az 1.1-es XML API tovább működjön mint 2020.04.01, annak érdekében hogy a gazdaság szereplői változtatás nélkül meg tudjanak felelni az adatszolgáltatási kötelezettségnek. Erről meg fog jelenni az Online Számla oldalon is hír. Ez mellett az éles környezetben továbbra is menni fog a 2.0, és ezzel kapcsolatban az a kérés, hogy ne álljatok le az átállással! Aki képes megugrani a jelenlegi körülmények között is a váltást 2.0-ra, az tegye meg amint lehetséges! A lehető legkésőbbi időpont, amire a 2.0-ás átállási haladékot tudjuk nyújtani az 2020.07.01. Kérünk minden szereplőt hogy a munkát úgy tervezze meg, hogy a jelen keretek között ez a végső határidő.

Műszakilag mi már készen állunk, azaz a frontenden rögzített kézi számlák már 2.0-ás verzióval mennek be, és nagyon hamar az Online Számlázó is át fog állni. Ez azt is jelenti, hogy ti minél később álltok át, egyre nagyobb eséllyel fogtok belefutni a napi munkavégzés alatt olyan főverziók közötti problémákba, amit az interfész dokumentáció 1.6.9-es fejezete taglal. (pl: 2.0-ás alapszámlát nem lehet 1.x-es számlával módosítani, sem az 1.x alatt technikailag érvényteleníteni) Arról nem is beszélve, hogy számos kényelmi szolgáltatás és a metrikák lekérdezése is a 2.0 része, ezeket átállás nélkül nem tudjátok igénybe venni.

ps: Április és július között fokozatosan arra kell készüljetek, hogy a teszt rendszer alkalmanként nem lesz elérhető. Az értékhatár eltörlés miatt beterveztünk egy sorozat performancia tesztet amiket nem halaszthatunk el. Ez miatt lesznek órák amikor a teszt rendszer irreszponzívvá válhat, esetenként szándékosan be is fogjuk dönteni hogy a DR tesztek is futhassanak. Megpróbáljuk ezeket a teszteket az éjszakai órákra ütemezni, de mivel rengeteg műszaki szakterület együttműködése szükséges a hatékony vizsgálathoz ezért nem tudunk garanciát vállalni arra, hogy munkaidőben soha nem fogunk tesztelni. Ez miatt is fontos lenne, hogy az átállás fejlesztéses részével ne várjatok sokat.

**Comment by Robaj85** [comment]
Köszönjük a megértést és az 1.0 API hosszabbítását! Nálunk nem kell sokra gondolni, kb. 2 hét elég, hogy készen legyünk,  ez a koronavírus sajnos beborította az ütemtervet. (a NAV adatszolgáltatás leprogramozása természetesen SOS, de az élet közbeszólt, közbejött egy nem kalkulált kockázat: ami szuper SOS lett, 15 ember munkájának megőrzését és a munkafolyamatok programozott úton történő optimalizálását fontosabbnak ítéltük és inkább kértük a halasztást)

**Comment by spedinform** [comment]
Csatlakozom az előttem szólókhoz, jelenleg sok mindenkit egyéb dolgok is terhelnek, mint egy ilyen volumenű átállás. 
Ezért a köszönet részemről is indokolt.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Kikerült teszt/éles környezetre a hivatalos hír, új infot nem tartalmaz :)

Üdv

**Comment by Kivancsikonyvelo** [comment]
Köszönjük szépen!

**Comment by NTCA-supporter** [comment]
Lezárom a ticketet. Ha van még kérdésetek akkor nyissatok újat nyugodtan.
