### ISSUE TITLE
[Q&A] SUPPLIER_CUSTOMER_MATCH_TAXPAYER üzenet Csoportos ÁFA alanyok közti számlázásnál

### ISSUE THREAD

**Issue by tkelemen73** [nav-gov-hu/Online-Invoice#190]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Csoportos ÁFA alanyok számláznak egymás között, taxpayerId és groupMemberTaxNumber a specifikációnak megfelelően van töltve vevőnél is és a szállítónál is. A számla adatszolgáltatás DONE státusszal érkezik vissza, viszont kap egy SUPPLIER_CUSTOMER_MATCH_TAXPAYER  figyelmeztető üzenetet.
A dokumentáció szerint csak a supplierTaxNumber/taxpayerId és customerTaxNumber/taxpayerId kerül összehasonításra, de ÁFA Csoport tagok egymás közti számlázásánál a két mező tartalma azonos mindig, figyelembe kellene venni az üzenetnél a supplierTaxNumber/groupMemberTaxNumber és customerTaxNumber/groupMemberTaxNumber különbözőséget is.
Hogy kellene beküldni, hogy ne érkezzen Figyelmeztető üzenet sem, ha már el kellene kerülni azt? Vagy egy olyan belső hiba, amit javítani kellene odaát, és már fent van a listán?
RequestId: d2J7ZHhydXVqbDZ1MjAxR0xmT3RBVw

**Comment by NTCA-tax** [comment]
A kérdésed alapján csak arra tudok következtetni, hogy a vevő és az eladó ugyanaz az áfa csoport. Az Áfa törvény alapján kizárólag adóalanyok közötti számla kibocsátás értelmezhető, egy adóalanyon belül nincs számla kiállítás. Mivel áfa csoport esetében maga az áfa csoport minősül adóalanynak, ezért a csoporton belül nem kellene számlát kiállítani, hanem számviteli bizonylatot. Így nincs adatszolgáltatás a csoporton belüli tranzakciókról.

**Comment by tkelemen73** [comment]
Köszönöm a választ, továbbítom a partnereknek. Zárható a bejelentés.
