### ISSUE TITLE
[Q&A] BatchInvoice-ban lehetséges-e új számlát beküldeni a módosítások mellett?

### ISSUE THREAD

**Issue by fenisteel** [nav-gov-hu/Online-Invoice#191]
Sziasztok!

A következő szituáció kezeléséhez kérnék segítséget:

Adott a Számla-1 (rajta A tétel) és Számla-2 (rajta B tétel).

Bejön az ügyfél, hogy visszahozta az A és B tételt, de vinne egy C-t (nem az előzőek folytatásaként, hanem csak úgy, amúgy is vett volna).

Ilyenkor csinálunk egy módosító számlát (Számla-3) amire felkerül 2 visszáru (A és B tétel negatív mennyiségben), továbbá rá kellene kerüljön a C tétel (pozitív mennyiségben). Kérdés, hogy ilyenkor hogyan lehet ezt lejelenteni, mert a batchInvoice-ban 3 számlát kellene szerepeltetni, de ebből csak kettő módosítás, a harmadik számla egy új okirat (ami tulajdonképpen a C tétel). 

Vagy ilyenkor a C tétel valamely (kb. szabadon választott) előző számla folytatása lesz és hozzá kell csapni mondjuk a Számla-2 módosításához?

Köszi!

**Comment by NTCA-supporter** [comment]
Szia @fenisteel !

Ha röviden akarok az issue címére válaszolni, akkor nem :)

Bővebben:
batchInvoice esetén csak 1 index-ed lehet a /manageInvoice requestben, ami ugye vagy MODIFY vagy STORNO operáció lehet.

A fenti problémára több megoldás is lehetséges szerintem:
1. Beküldöd batchInvoice-ban a 2 számla sztornózását, és egy külön requestben beküldöd az új számlát CREATE operációval
2. nem batchInvoice-ként küldöd be a módosításokat, hanem külön külön, és akkor egy requestben lehet 2 módosítás, és 1 létrehozás, tehát 3db új számla sorszámmal.
3. Ha nem akarsz új számlát kiállítani, akkor technikailag lehetséges az is, amit te írtál.

A technikai válasz tehát, hogy batchInvoice-ban nem tudsz beküldeni új számlát.
Számlázási módszertanról esetleg még @NTCA-tax tud pontosabb információval szolgálni.

Köszi

**Comment by NTCA-tax** [comment]
Ha már @NTCA-supporter megszólított, akkor a jogszabályi oldalt is érdemes figyelembe venni. 

Számlát mindig egy gazdasági eseményről, egy tranzakcióról, egy teljesítésről állítunk ki. Amennyiben Számla-1 egy tranzakció volt, Számla-2 pedig egy másik tranzakció, akkor a kettőből nem csinálhatunk utólag sem egy tranzakciót (nem lehet véletlen a két számla sem). Arra van jogszabályi lehetőség, hogy a két számlát egy bizonylattal érvénytelenítsük, de a példában szereplő C termék értékesítése mindenképpen önálló bizonylat, önálló gazdasági esemény lesz, mely nem kapcsolódhat A és B termék értékesítéséhez. Hiszen éppen ezt írtad a példában is, hogy ez független vásárlás.

Általánosan igaz, hogy módosítani mindig egy gazdasági eseményt módosítunk, ahogy az a valóságban megtörtént. Amennyiben egy gazdasági esemény új teljesítést jelent, akkor arról új számlát kell kiállítani.

**Comment by fenisteel** [comment]
Köszönöm a válaszokat!
