### ISSUE TITLE
[Q&A] Csoportos módosító számlák kezelése

### ISSUE THREAD

**Issue by agardym** [nav-gov-hu/Online-Invoice#192]
Kedves Fejlesztők, NAV Döntéshozók

Érdeklődni szeretnék, hogy a 2.0-ás séma élesítését követően, elfogadott marad-e a kalapkázásos (^) módszer a csoportos módosító számlák küldése során, vagy az új sémában elérhetővé vált csoportos (batch) módszerrel kötelező továbbítani az adatot.

Köszönettel,
Máté

**Comment by szako** [comment]
Válasz:
https://github.com/nav-gov-hu/Online-Invoice/issues/66#issuecomment-531748788

**Comment by NTCA-developer** [comment]
Szia @agardym !

@szako már behivatkozta a lényeget. TL,DR: nem tiltjuk explicit, de magatokkal és a vevőitekkel babráltok ki, ha maradtok a régi gyakorlatnál és nem álltok át a batch-es szerkezetre.

**Comment by NTCA-developer** [comment]
@agardym lezárható?

**Comment by NTCA-supporter** [comment]
Lezárom a ticketet. Ha maradt még nyitott kérdés akkor nyiss újat nyugodtan.
