### ISSUE TITLE
[Q&A] taxpayerData/ShortName

### ISSUE THREAD

**Issue by connorhu** [nav-gov-hu/Online-Invoice#193]
A QueryTaxpayerResponse ShortName mezője milyen megfontolásból kezdődik nagybetűvel? Nevezéktan szerint kicsivel kéne kezdődnie.

**Comment by NTCA-supporter** [comment]
Szia @connorhu !
Köszi a jelzést.
Az interfész dokumentációban szerepel rosszul. Helyesen a tag neve taxpayerShortName.
Hamarosan javítjuk a leírást.
(Az issuet nyitva hagyom, ha kikerült a javítás, zárom.)
Üdv

**Comment by connorhu** [comment]
Köszi!

**Comment by NTCA-supporter** [comment]
Javítottam, zárom az issuet. Köszi mégegyszer!
