### ISSUE TITLE
/A 

### ISSUE THREAD

**Issue by Kalooz69** [nav-gov-hu/Online-Invoice#194]
Katás egyéni vállalkozó, nem Áfa körös, mert 12M alatti a bevételezés, és nem egyszerüsített számlát ad ki, a jelenlegi séma szerint 0% áfás feladás ebben az esetben nem lehetséges, hogyan adjam fel az adott ügyfél számláit?

**Comment by clapygeza** [comment]
Sztem a vatPercentage helyett <vatExemption>Adómentes</vatExemption>

**Comment by clapygeza** [comment]
Mármint vatExemption elemben

**Comment by NTCA-tax** [comment]
Az adatszolgáltatásban a supplierInfo alatt található egy individualExemption elem, melyet true-ra kellene állítani. A tételsornál pedig a vatExemption elemben kell jelölni a mentesség okát.
