### ISSUE TITLE
Vevő adószám lekérdezés[Q&A]

### ISSUE THREAD

**Issue by vivacomp** [nav-gov-hu/Online-Invoice#195]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Nálam a megyekódot (countyCode) nem adja vissza a QueryTaxpayerResponse.
Az alábbi válaszrészt itt közlöm:
<taxNumberDetail>
   <ns2:taxpayerId>11351063</ns2:taxpayerId>
   <ns2:vatCode>2</ns2:vatCode>
</taxNumberDetail>
A megyekódra azért lenne szükségünk, mert a számlázóba szeretnénk a kapott adószámot is beépíteni, hogy a vevő minden adata korrekt legyen.
Üdv.: Viva

**Comment by NTCA-supporter** [comment]
Szia!
A #146 issueban volt már ez a téma. Még nem áll rendelkezésre ez az adat, séma és operáció szinten felkészültünk a visszaadására.
Zárhatom?

**Comment by vivacomp** [comment]
Szia!
Köszönöm, lezárhatod.
Üdv.: Viva
