### ISSUE TITLE
[Q&A] Online számlázóban visszanézve hiányzik az áfa és a bruttó a tételsoroknál

### ISSUE THREAD

**Issue by Csomb** [nav-gov-hu/Online-Invoice#196]
Sziasztok!

Próbálunk ellenőrizni mindent a 2.0-ra átállás előtt és azt tapasztaltuk (lehet, hogy nem verziófüggő), hogy a beküldött és visszaigazolt számlákat az webes felületen visszanézve (Számlák/Adatszolgáltatások) és ellenőrizve a tételsoroknál üres az áfa és a bruttó oszlop. (Az adómérték fel van tüntetve helyesen).

Illetve a végén a számlaösszesítő is jól jelenik meg.

Mit ronthattunk el, mert mivel nincsen hiba, nem tudjuk, hogy mit keressünk.

Példa tranzakcióazonosító: 2WVPIKXOOOIM4PG8
![miss](https://user-images.githubusercontent.com/9965575/77762132-55041880-7039-11ea-9afe-35d5040db3d1.png)

Köszi a választ előre is!

ui: nem tudnátok megoldani, hogy az online számlázó LastPass kompatibilis legyen?

**Comment by NTCA-supporter** [comment]
Szia @Csomb !

Megnéztem az adatszolgáltatás XML-jét.
Azért nem látod a felületen a bruttó és ÁFA összegeket a soroknál, mert azokat nem küldted be.
Ha megnézed az XSD-t, akkor ezek a csomópontok lennének, amiket nem küldtél:
InvoiceData/invoiceMain/invoice/invoiceLines/line/lineAmountsNormal/lineVatData
InvoiceData/invoiceMain/invoice/invoiceLines/line/lineAmountsNormal/lineGrossAmountData

Hibát azért nem kapsz, mert ezek optional csomópontok.
A LastPassnak utánanézek, erre most hirtelen nem tudok semmi konkrétumot ígérni.

Üdv

**Comment by Csomb** [comment]
Szia!

Köszönöm az infót, javítom ennek megfelelően. Viszont akkor nem kellett volna hibát jeleznie, hogy a tételsorok áfája nem egyezik az összesítővel, vagy hogy meg van adva áfa mértéke, de nincsen hozzá összeg?

Mindenesetre lezárom, mert a problémámat megoldottátok, köszönöm!

**Comment by Csomb** [comment]
Nagyon köszönöm, hogy megcsináltátok a LastPassos bejelentkezést!!
