### ISSUE TITLE
[Q&A]queryServiceMetrics továbbra sem aktív

### ISSUE THREAD

**Issue by tkelemen73** [nav-gov-hu/Online-Invoice#197]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Sziasztok,
a #173-es ticketben már beszéltünk erről, hogy a /metricService operáció hívás a megadott végponton HTTP/1.0 404 Not Found választ ad vissza. Akkor azt írtátok, hogy a 2.9-es verzióban lesz benne. Tegnap ugye megtörtént az átállás a 2.9-re, és a változásokban benne is volt, hogy a "Elindult a queryServiceMetrics operáció". Nos, vagy nálam van a hiba, vagy még sem indult el.
Tehát a kérdés újfent, hogy még nem működik, vagy az, hogy valamit nem jól csinálunk?
Az alábbi végpontokat hívtam meg, mindegyiknél HTTP/1.0 404 Not Found a válasz:
https://api-test.onlineszamla.nav.gov.hu/metricService/v2/metric/queryServiceMetrics
https://api-test.onlineszamla.nav.gov.hu/metricService/v2/metric/queryServiceMetrics/list

**Comment by NTCA-supporter** [comment]
Szia!

https://api-test.onlineszamla.nav.gov.hu/metricService/v2/queryServiceMetrics/metric
https://api-test.onlineszamla.nav.gov.hu/metricService/v2/queryServiceMetrics/list
és ha csak 1 metrika lekérdezés:
https://api-test.onlineszamla.nav.gov.hu/metricService/v2/queryServiceMetrics/metric/responseTimeAverageMsManageInvoice
Így próbáld.
Köszi

**Comment by NTCA-supporter** [comment]
Most látom, hogy az interfész doksiban rosszul szerepel, ezt javítom gyorsan.
Köszi a jelzést :)

**Comment by tkelemen73** [comment]
Köszönöm, így már működik, viszont továbbra sem kerek.
Ha úgy hívom meg, ahogy a dokumentációban van, akkor ezt az üzenetet kapom:

<?xml version="1.0" encoding="UTF-8" standalone="true"?>
-<TechnicalFault xmlns:ns21="http://common.dto.icon.icellmobilsoft.hu/jms" xmlns:ns20="http://invoice.dto.icon.icellmobilsoft.hu/invoiceExport" xmlns:ns19="http://schemas.nav.gov.hu/OSA/2.0/api" xmlns:ns18="http://schemas.nav.gov.hu/OSA/2.0/annul" xmlns:ns17="http://common.dto.icon.icellmobilsoft.hu/commonservice" xmlns:ns16="http://common.dto.icon.icellmobilsoft.hu/commonsecurity" xmlns:ns15="http://user.dto.icon.icellmobilsoft.hu/user" xmlns:ns14="http://user.dto.icon.icellmobilsoft.hu/device" xmlns:ns13="http://navdata.dto.icon.icellmobilsoft.hu/navdata" xmlns:ns12="http://invoice.dto.icon.icellmobilsoft.hu/invoice" xmlns:ns11="http://invoice.dto.icon.icellmobilsoft.hu/invoice/history/v1" xmlns:ns10="http://config.dto.icon.icellmobilsoft.hu/config" xmlns:ns9="http://artemis.dto.icon.icellmobilsoft.hu/artemis" xmlns:ns8="http://document.dto.icon.icellmobilsoft.hu/document" xmlns:ns7="http://common.dto.fw.icell.hu/common" xmlns:ns6="http://invoice.dto.icon.icellmobilsoft.hu/invoiceitem" xmlns:ns5="http://schemas.nav.gov.hu/OSA/2.0/data" xmlns:ns4="http://test.dto.icon.icellmobilsoft.hu/invoicetest" xmlns:ns3="http://schemas.nav.gov.hu/OSA/1.0/data" xmlns:ns2="http://invoice.dto.icon.icellmobilsoft.hu/invoiceStatistics" xmlns="http://common.dto.fw.icell.hu/commonservice">
<funcCode>ERROR</funcCode>
<message>???hu.icellmobilsoft.icon.common.rest.exception.GeneralExceptionMapper.NOT_ACCEPTABLE_EXCEPTION???</message>
<faultType>OPERATION_FAILED</faultType>
</TechnicalFault>

Ha nem adom meg a HTTP fejlécben az content-type=application/xml és accept=application/xml értéket, akkor működik, de csak JSON jön válaszban. XML-ként nem működik.

**Comment by NTCA-supporter** [comment]
Szia!

Sajnos jól látod a helyzetet. 
Már kész a javítás, úton van a javító 2.9.1 verzió.
Addig mindenképp nyitva hagyom az issuet, a további hasonló jellegű kérdések elkerülésére.

Köszi a türelmet addig is!

**Comment by NTCA-supporter** [comment]
Szia @tkelemen73 !

Kikerült a javítás, már xmlben is elérhető a válasz.
Ha rendben találod, kérlek zárd az issuet.
Köszi

**Comment by tkelemen73** [comment]
Szia, így már ok, működik, annyi lenne még, hogy a dokumentációban van pár hivatkozás még a régi, hibás elérésre, azt javítsátok kérlek, és részemről zárható. 8.3.1.1 fejezetben láttam 3-t. Köszönöm!

**Comment by NTCA-supporter** [comment]
Szia!

Közben még nyitva hagyom, mert találtunk hibát az értékekkel kapcsolatban. Ugye mindenhol Ms van megadva mértékegységnek, de másodpercben kerülnek visszaadásra az értékek. Ezeket is javítjuk, illetve a doksit is.
Köszi

**Comment by tkelemen73** [comment]
Szia, a processingTimeAverageMsInvoice -ra gondoltok? Meglepő értékeket mutat...

**Comment by NTCA-supporter** [comment]
Igen, és az összes responseTime is. Ezek túl szép számok, úgyhogy a javító verzióban felszorozzuk ezerrel :)

**Comment by NTCA-supporter** [comment]
Szia @tkelemen73 !
Közben kikerült a javítás a teszt környezetre, más millisec-ben adjuk vissza helyesen az értékeket.
Zárom az issuet, köszi a türelmet.
