### ISSUE TITLE
[Q&A] A beküldött és a lekérhető xml-ek nem ugyanazok?

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#198]
Tisztelt Fejlesztők!

Tapasztaltunk szerint nem egyezik meg adattartalmilag egy számla beküldött xml és a lekérdezett xml.
Jelen pillanatban úgy tűnik, hogy karakter transformáció (upper) történik de csak az adatok egy részén, azonban ez felveti azt a kérdést, hogy mennyire lehet üzleti folyamatokat alapozni a lekért xml adatokra? Hiszen, ha nem azt kapjuk meg, amit a partner feltöltött, akkor bármikor előfordulhat az, hogy NEM PONTOSAN UGYANAZT az adatot kapjuk, amit a partner közölt a NAV felé, és ami (a kiállító szerint) a számlán szerepel.

Várom válaszukat.

**Comment by NTCA-supporter** [comment]
Szia @omachtandras !
Kérlek küldj valamilyen azonosítót(transactionID,requestID..) amivel rá tudunk nézni az általad problémásnak vélt számlára és a lekérdezésre, illetve hogy teszt vagy éles környezetről származik az ID. Esetleg ha megírod, mely adatokkal van problémád, azt is megköszönöm.

Üdv

**Comment by omachtandras** [comment]
Teszt környezet:  2X4A3345F12A0WHD
Azt látjuk, hogy a fejben a nevek, cím adatok, tételsoron a cikk nevek nagybetűsítésen esnek át.
A probléma azonban nem konkrétan ez, mert ez kezelhető lenne, a felvetés inkább arra vonatkozott, hogy mi komoly kockázatot látunk abban, hogy nem PONTOSAN azt az xml-t kapjuk meg, amit a partner beküldött.
Így gyakorlatilag nem lehet teljesen automatizált feldolgozást végezni, mert ki vállalja a felelősséget, ha véletlenül tartalmilag nem ugyanaz áll elő újra a NAV oldalán, ami beküldéskor volt az xml-ben?
Ha azonban nem történik XML újra előállítás, hanem a NAV oldalán letárolásra kerül, csak előtte kap egy upper transformációt néhány mező, az kicsit megnyugtatóbb lenne, de véleményem szerint ilyen esetben is jobb lenne, ha az eredeti xml kerülne tárolásra és átadásra a lekérdezés során.
Köszönöm!

**Comment by NTCA-developer** [comment]
Sziasztok!

Bocsánat hogy beleszólok, de kimásolnék egy részt az interfész dokumentációból. (1.8.6 fejezet, ez a )

> 2)	A beküldött számlák mentése során egyes tagekben szereplő adatokon a rendszer uppercase konverziót végez, melyek a következők:
o	supplierName, customerName, fiscalRepresentativeName, obligatedName
o	minden AddressType típus által leírt cím minden eleme
o	minden productCodeOwnValue tag értéke
o	lineDescription
o	unitOfMeasure
o	discountDescription
o	minden vatExemption tag értéke
o	brand, serialNum, engineNum
o	minden EkaerIdsType típus által leírt EKÁER szám
A válaszban a fenti mezők a beküldött értéktől függetlenül mindig uppercase formátumban kerülnek visszaadásra.

A konverzió szükségességéről itt volt már szó, azon nem szeretnénk változtatni: https://github.com/nav-gov-hu/Online-Invoice/issues/149#issuecomment-590245217

De ezen kívül minden más érintetlen, garantáljuk az egyező tartalmat.

**Comment by omachtandras** [comment]
Köszönöm a választ.

Nagyon sajnálom, ha ezen nem lehet változtatni, mert ügyfél oldalon ez oda fog vezetni, hogy vagy továbbra is megpróbálják az ügyfelek egymás közt eljuttatni az xml-eket (kényelmetlen és költséges az automata letöltéshez képest), vagy pedig megtanulnak együtt élni azzal, hogy a gépi úton befogadott számlák következménye az lesz, hogy a (legfőbb - partner, cikk-) törzsadataik és (szállító oldali) számlaadataik kiabálás módjára csupa nagybetűs értékekkel lesznek tele.
Mert hiába van egy emberi adatbevitel a feladó oldalon vélhetőleg olvasható, a magyar szemnek megszokott adatbevitellel, a gép által létrehozott rekordok már nem ilyenek lesznek.

A dokumentáció kérdéses része valóban elkerülte a figyelmemet. Megnyugtató lenne, ha kiegészítésre kerülne a fentebb található egy mondattal: "De ezen kívül minden más érintetlen, garantáljuk az egyező tartalmat.", hogy ha az ügyfelek a számlaképpel nem egyezőséget hánytorgatják fel a fejlesztőik felé, akkor meg lehessen őket nyugtatni, hogy tényleg minden egyezik, csak a fent leírtak nem, ahogy a NAV dokumentációban is szerepel.

Köszönöm, a jegy részemről zárható.
