### ISSUE TITLE
[Q&A] Kézi számla rögzítése, értékek ellenőrzése

### ISSUE THREAD

**Issue by csaszko** [nav-gov-hu/Online-Invoice#199]
Szia!

Szeretném kérdezni, hogy van-e különösebb oka annak, hogy kézi számla webes felületen történő rögzítésekor csak azt ellenőrzi a rendszer, hogy ki van-e töltve a mező vagy sem? A beírt esetleges hibás értékekkel egyáltalán nem foglalkozik. 
Tudom, hogy az adózó felelőssége a kitöltés, de egy alap ellenőrzés szerintem nagyon hasznos lenne. 
Számomra a queryInvoiceData bejövő számlák miatt érdekes, mert így pl bruttó összesen mezőben az áfa értéke volt... 
gondolom nem lesz újdonság ez sem számotokra, de találkoztam `<lineDescription>.</lineDescription>` "adattal" is. 
Köszi

Edit: 
Egyszerűsített számláról van szó egyébként (többit nem néztem). Még egy amit jó lenne egyértelműsíteni a felviteli felületen. (Benne a számla interfész dokumentációban ez is, de ezt egy sima felhasználó aki még mindig kézi számlát ír... soha nem fogja elolvasni.. ahogy jó eséllyel a warn-t sem. ) 
A unitPrice-nál nem egyértelmű, hogy nettó vagy bruttó formában kell megadni. 

Ahogy fent is írtam, ezt nagyon jó lenne pótolni, hogy lehessen támaszkodni az adatokra amit a felhasználók kézzel bevisznek, főleg kézi számla esetében.  Sajnos azt látjuk, hogy sokszor problémát okoz egy sima összeadás vagy szorzás is... itt ez is kiszűrhető lenne. 

Köszönöm ha foglalkoztok a témával.

**Comment by NTCA-supporter** [comment]
Szia!

Már kezdetektől az volt az alap koncepció, hogy a kézi számla webes felületre nem vezetünk be mélyebb ellenőrzéseket, csak a kötelezőségre. Ennek az az oka, hogy azokat az adatokat is lehessen rögzíteni, ahol az eredeti számlán is rosszul szerepelnek. Egyelőre ezen nem tervezünk változtatni.

Viszont az egységárra tett javaslatodat megfontoljuk és megnézzük mit tudunk tenni.

**Comment by csaszko** [comment]
Köszönöm, a válaszod és azt is ha megfontoljátok. 

Nem kötekedni szeretnék, de egy részről értem a koncepciót, hogy az legyen az adatszolgáltatásban is ami a számlán, csak az a része nem világos, hogy kinek jó ha hibás értékek szerepelnek egy számlán, és miért nem jobb megoldás ha jelez a usernek.. hogy tanuljon meg összeadni, vagy olvasni mert valami nem stimmel!? 
A konkrét esetben pl a számla jó volt viszont az adatszolgáltatás nem, szerintem ez a NAV-nak sem jó. (persze ha az ellenőrzéskori büntetésen van a hangsúly akkor nincs több kérdésem)  

Részemről azért volt csak ez az egész kérdés, mert a bejövő számlákat dolgoznám fel , hogy ne kelljen pont a kézi számlákon kihámozni, hogy mi is van ráírva, de így akkor kb. semmi értelme nincs, hogy le lehet kérni ezek esetében a bejövő számlákat, mert alapozni egyáltalán nem lehet az adatokra. 

Köszönöm.

**Comment by NTCA-developer** [comment]
Szia @csaszko 

Pár gondolattal szeretnék beszállni a beszélgetésbe. Alapvetően senki nem tudja neked garantálni hogy az adatszolgáltatást nem egy trehány implementáció csinálta, így ilyen különbség a kézi számlák és a gépi számlák között egyáltalán nincs, ez miatt ne állj el a vevő oldali feldolgozástól, nem ez fogja megoldani a problémát.

Az igaz, hogy a rögzítő felület enged logikátlanságokat, de itt jönnek a jogászok: ha a számla rossz mert 1+1 = 3 ÉS igaz az, hogy adatot a számláról kell szolgáltatni, akkor a felületen nem tilthatod az 1+1 = 3 rögzítését, mert ezzel meggátolod az adatszolgáltatási kötelezettség teljesítését, aminek nem kicsi szankciója van. Nyilván a megoldás a számla javítása lenne és ebben a vevőnek is van felelőssége hogy emlékeztesse a kiállítót a matematikai összefüggések betartására, nem csak a NAV-nak. 

Amit mi hozzátettünk az adatminőséghez eddig az volt hogy a kézi számlák is ugyan olyan warning vizsgálaton esnek át mint a gépi számlák. Ugyan azt a visszajelzést nyújtjuk az egyik bemenetnek is mint a másiknak.

A 2.0-val megnyílik egy új világ a rendszer életében, és közös a felelősség hogy ezek az adatok jók legyenek mert egyre többen akarják majd használni őket. Szóval kérlek húzd be te is magadhoz a vevő oldali feldolgozást és tegyünk együtt érte hogy mindenki helyes adatokat küldjön be azért, mert ez a saját jól megfontolt érdeke.

**Comment by csaszko** [comment]
Szia @NTCA-developer 

Teljesen igazad van, nem akarok elállni a vevő oldali számlák ellenőrzésétől, már régóta vártam ezt a lehetőséget! ( eddig is aki hajlandó volt a számlája mellé biztosítani xml-t azt feldolgoztuk és bevételeztük az alapján) 2.0-val valóban egy olyan lehetőség nyílik(na) meg mindenki számlára, hogy a felesleges kézi sokszori adatrögzítést elfelejthessük már... 

>  de itt jönnek a jogászok: ha a számla rossz mert 1+1 = 3  ÉS igaz az, hogy adatot a számláról kell szolgáltatni, akkor a felületen nem tilthatod az 1+1 = 3 rögzítését,

Ez az ami számomra felfoghatatlan... mindenki hibázhat, de ha a számlán rossz bármi számszaki adat, akkor miért cél az, hogy legyen az ügyfélnek egy hibás számlája, amiről csinál egy rossz, használhatatlan adatszolgáltatást, és eljuttatja a vevőnek aki szintén elkezdi feldolgozni és jó eséllyel kiszúrja (vagy nem... ), miután észlelte a hibát, visszaküldi javításra. 
Személy szerint örülnék, ha mindenki elfelejtené a kézzel írt számlákat és bármilyen gépi rendszerre állna át.. 

A warn üzenetet tesztél én is láttam, de mivel itt nem kötelező lekérdezni az adatszolgáltatást, ezért gyanítom senki nem fogja megnézni. 

Oké, hogy ne raboljam az Ti időtöket, - biztos van akin egyáltalán nem lehet segíteni- köztes megoldási javaslatom: 

A felület engedjen felvinni bármi hülyeséget amit csak szeretne a felhasználó, de hibát dobjon neki már a felvitelkor, hogy nézze meg még egyszer és biztos ezt szeretné.. és/vagy a warn üzenetet amit az adatszolgáltatásnál le lehet kérni, azt jelenítse meg itt a felvitel után egyből neki. (talán így lesz aki elolvassa) 

Erre jóval nagyobb a rálátásotok, de feltételezem sokkal több ilyen adatszolgáltatás lesz július 1 után mint most, annak ellenére, hogy biztosan sokan áttérnek gépi számlázásra. 

>  tegyünk együtt érte hogy mindenki helyes adatokat küldjön be azért
Ezért is kezdtem ezt a topicot, mert szeretnék én is megbízható adatokkal dolgozni. Fejlesztés közben belenyúltam egy éles rendszerben történt rossz adatszolgáltatásba, hogy a bruttó unitPrice helyén nettó érték volt, és lineGrossAmountSimplified bruttó összesen helyett csak az áfa szerepelt, elment némi időm vele, mire rájöttem, hogy nem én kevertem össze a mezőket..

**Comment by NTCA-developer** [comment]
Szia @csaszko 

Az igény befogadva a linkelt ticket alatt.

**Comment by csaszko** [comment]
Szia!
Köszi!
