### ISSUE TITLE
Adószám lekérdezés [DEV support]

### ISSUE THREAD

**Issue by era910413** [nav-gov-hu/Online-Invoice#200]
Az utóbbi hetekben rengeteg számlát küldtünk be sikeresen a teszt rendszerbe, viszont most olyan hibába ütköztünk, miszerint 3 számla esetében az adószám ellenőrzés az alábbi hibakódot adja vissza:
<funcCode>ERROR</funcCode>
<errorCode>OPERATION_FAILED</errorCode>
<message>Feldolgozás sikertelen!</message>

RequestId-k:
GAEA04202004062976219
GAEA04202004062982589
GAEA04202004062984596

A dokumentációban az szerepel, hogy ilyenkor meg kell ismételni az operációt, melyet meg is tettünk, viszont a fenti 3 kérést továbbra sem fogadja el a NAV teszt rendszere.

Ilyenkor mi a teendő?

**Comment by NTCA-developer** [comment]
Szia @era910413 

Ez jelenleg egy elszállás a kódban, ez sosem lesz sikeres lekérdezés. A hiba csak a v2-ben van jelen és specifikusan a lekérezett adószám belső szerkezete okozza a problémát. Az OPERATION_FAILED hibakódot egy általános - és sajnos - nem kezelt hiba miatt kapod. Általánosságban ez a hiba fog jönni a javításig ahol olyan egyéni vállalkozókat kérdezel le akinek nincs címadata.

Javítjuk és elnézést!

**Comment by era910413** [comment]
Rendben, köszönöm a visszajelzést.

Hagyjam még nyitva az issue-t, vissza fogtok jelezni ha megtörtént a javítás?

**Comment by NTCA-developer** [comment]
Igen maradjon, mindenképp visszajelzünk!

**Comment by NTCA-supporter** [comment]
Szia @era910413 

Nemrég kikerült a teszt környezetre az általad jelzett hiba javítása. Egyelőre még az éles környezeten nincs kint a javítást tartalmazó hiba, de a teszt környezeten már nézheted. Ha még mindig van hiba akkor szólj, de ha elhárult akkor légyszi zárd le a ticketet.

**Comment by era910413** [comment]
Szia!
Rendben van, köszi!
