### ISSUE TITLE
 [Q&A] Tételsor összegek kötelezősége

### ISSUE THREAD

**Issue by Amn3s1a2018** [nav-gov-hu/Online-Invoice#201]
A tételsorok `lineAmountsNormal/lineVatData` és `lineAmountsNormal/lineGrossAmountData` mezői az xsd és a doksi szerint nem kötelezően töltendők. Az 1.1-ben volt rá utalás, hogy csak azért opcionális, mert a módosító számlán esetleg nem releválns adat. Ilyent a 2.0-ban nem találok. A példák közt is változó, hogy szerepelnek-e ezek a mezők vagy sem.

Egyrészt érthető ha nem kell őket adni, némelyik nyomtatott számlán sem szerepelnek, másrészt jó lenne világosan látni, hogy pl. reklamáljunk-e a partnernek ha nem kapjuk ezeket az adatokat.

A #196 -ban találtam erre utalást, de sajnos az sem válaszolta meg a kérdésemet.

**Comment by NTCA-tax** [comment]
A lineVatData azért nem lehet kötelező, mivel nem minden számlán szerepelhet. Például fordított adózás esetén vagy különbözeti adózás esetén nem lehet a számlán adóérték. Így közvetve az adatszolgáltatásban sem szerepelhet itt összeg.
A lineGrossAmountData szintén van úgy, hogy nem értelmezhető az adott számlán, vagy nincs ilyen érték a számlán. A bruttó érték feltüntetése normál számla esetén jogszabályilag nem kötelező, egyszerűsített számla esetén viszont kötelező. Az Áfa tartalmú különbözet szerinti adózásnál viszont figyelni kell erre, mivel normál számlán kötelező mező lesz azzal, hogy itt kell feltüntetni az ellenértéket.

**Comment by betasofthu** [comment]
Bocsánat, hogy beleszólok  a témába. Teljesen jó és jogos is, hogy nem kötelező. Én már 25 éve készítek számlázó programokat és még emlékszem arra, amikor a tételsoroknál nem volt csak nettó érték, áfa érték és a kettő összege nem szerepelt. Az áfát a a számla végén számoltuk rá, ha egy áfa kulcs volt. Ha több, akkor szakaszonként számoltuk rá az áfát. Ez az számla (szinte) nem tartalmazott kerekítési eltérést. Ez megfelelt az akkori áfa törvénynek és megfelelne a mostaninak is.
K.b. 10 éve bevezették az áfa törvénybe a "tételenként" szót, akkor alakultak ki ezek a most szokásos  tételenkénti áfát tartalmazó számlák, amik eleve csak kerekítési eltéréssel összesíthetők. (Nem mennék bele, hogy miért, de így van.) Utána pár év múlva kikerült a "tételenként", de annyira berögzült a köztudatba a tételes áfás számla, hogy ma szinte minden számla ilyen. Ettől függetlenül a húsz évvel ezelőtti nem tételes áfát tartalmazó számla ma is szabályos. És ez nagyon helyes is így.
Én magam sem csináltam vissza a tételes számlámat, de ha egyszer ráérek biz'Isten megcsinálom.
**Na ezért nem kötelező tételenként az áfa összege**.

**Comment by Amn3s1a2018** [comment]
Köszönöm a választ és a kiegészítést is, külön köszönöm azt, hogy az egyszerűsített számlára is kitértél, ez segít egy kicsit pontosítani a kérdést...
Szeretném külön választani az adatszolgáltatás és a számla (legyen bár papír alapú avagy elektronikus számla) adattartalmára vonatkozó elvárásokat. Az amiről eddig beszéltünk nekem úgy jött le, hogy a számlára vonatkozik, de nem ez volt a szándékom a kérdéssel. Pont az a problémám, hogy a partner számláján rajta vannak a hivatkozott összegek, csak éppen webes felületen és/vagy az adatszolgáltatást lekérdezve látom azt, hogy a `lineAmountsNormal/lineVatData` és a `lineAmountsNormal/lineGrossAmountData` bizony üres. Az lenne a kérdés, hogy felelős adózóként vitatkozzak-e tovább a partnerrel, hogy ugyan töltse már ki ezeket a mezőket hamár a számláján ottvannak? Szerencsére az említett kerekítési téma eddig nem jött elő, de ha lesz is, adózási kérdést az sem érint, mivel a `vatRateVatData` és `vatRateGrossData` viszont szerepelnek a számlán és az adatszolgáltatásban is.
Egyébként @betasofthu #209 kérdése is ezt a témát érinti. Általánosságban értem, hogy a papíros és a feladott számla nem mindig teljesen azonos adattartalmában (mint a #209 esetén), de ha valamit feltüntetek a számlán akkor az keletkeztet(het) olyan kötelezettséget, hogy az onlineszamlába is azzal egyezően töltsem fel az adatot – nyilván nem más értéket, de az xsd kötelezőség megengedő volta miatt lehetséges olyan hiba, hogy elmulaszják pl a közvetített szolgáltatás jelölését. Szóval akkor a tételes áfa vajon melyik csoportba tartozik? Mostmár énis hajlok rá, hogy nincs rá szükség.

**Comment by NTCA-tax** [comment]
Az adatszolgáltatási kötelezettség az áfa törvény szerinti kötelező adattartalomra vonatkozik az NGM rendelet alapján. A számlán ezen felül megjelenhet olyan adattartalom, melyet más jogszabály ír elő kötelező adattartalomként, vagy a két partner megegyezése alapján kerül rávezetésre, vagy pedig a számlakiállító általában rá szokta vezetni. Tehát kizárólag jogszabályi kötelezettség oldaláról nem lehet helytelennek minősíteni az olyan adatszolgáltatásokat, melyek kizárólag az áfa törvény szerinti kötelező adattartalmat tartalmazzák, a többi adattartalmat nem (még akkor is, ha rajta vannak a számlán).

Az adatszolgáltatás XSD-je nem csupán az adatszolgáltatási célt szolgálja, hanem az NGM rendelet lehetőséget ad arra is, hogy a számla adatexport is ezen séma alapján készüljön. Ott viszont a számla teljes adattartalmát kell az adatexportba elhelyezni. Ezért is szélesebb a séma adatstruktúrája az áfa törvény szerinti minimumnál.
