### ISSUE TITLE
[Q&A] Negatív végösszeg jóváírás esetén

### ISSUE THREAD

**Issue by MTYS87** [nav-gov-hu/Online-Invoice#202]
Sziasztok,
Sajnos nem találtunk megoldást erre a problémára, ezért szeretném kérni segítségeteket. Kereskedelmi cégnél is gyakori az úgynevezett jóváíró számla, mely esetben a végösszeg illetve minden elem a számlán negatív. Pl. tévedésből kétszer számlázunk ki szállítási költséget és 3 nap múlva derül ki, utólag már nem sztornózhatjuk.
Jelenleg a V1.1 verzióban is így használjuk jóváíró számláknál és nem kapjuk ezt a figyelmeztetést:

„INCORRECT_SUMMARY_DATA_INVOICE_NET_AMOUNT : Eredeti (CREATE) számla nettó összege nem lehet negatív.”

Előre is köszönöm!

**Comment by NTCA-tax** [comment]
Szia @MTYS87!
Ennek elvileg számlával egy tekintet alá eső okiratnak kellene lennie. Nem lehet az a probléma, hogy alapszámlaként kerül adatszolgáltatásra?

**Comment by MTYS87** [comment]
Igen, NORMAL a head mezőben.

**Comment by NTCA-tax** [comment]
Akkor alapvetően ez a probléma, ez nem normál számla, hanem számlával egy tekintet alá eső okirat. Ennek alapján lezárható az issue?

**Comment by MTYS87** [comment]
Köszönöm a segítséget, így már érthető.
