### ISSUE TITLE
[Q&A]queryServiceMetrics/metric Feldolgozás sikertelen illetve 503 Service Unavailable

### ISSUE THREAD

**Issue by tkelemen73** [nav-gov-hu/Online-Invoice#203]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Sziasztok,
biztos tudtok róla, hogy a tesztrendszeren tegnap este 19:15:50 óta semmi válasz nem jön sem a queryServiceMetrics/metric-ről, sem a queryServiceMetrics/list-ről. Pontosabban jön egy 503 Service Unavailable No server is available to handle this request. üzenet.
https://api-test.onlineszamla.nav.gov.hu/metricService/v2/queryServiceMetrics/metric
https://api-test.onlineszamla.nav.gov.hu/metricService/v2/queryServiceMetrics/list

A produktív rendszeren a tegnapi upgrade óta működik a queryServiceMetrics/list, viszont a queryServiceMetrics/metric
<TechnicalFault>
<funcCode>ERROR</funcCode>
<message>Feldolgozás sikertelen!</message>
<faultType>OPERATION_FAILED</faultType>
</TechnicalFault>
üzenetet ad.
https://api.onlineszamla.nav.gov.hu/metricService/v2/queryServiceMetrics/metric
https://api.onlineszamla.nav.gov.hu/metricService/v2/queryServiceMetrics/list

Üdv
T.

**Comment by NTCA-supporter** [comment]
Szia @tkelemen73!

Köszi a jelzést! Az EDU-t már javítottuk is azt már nézheted. A PROD pedig már nézzük. Szólok, ha az is elhárult.

**Comment by NTCA-supporter** [comment]
A PROD is megjavult, köszi a jelzést mégegyszer, zárom az issuet.
