### ISSUE TITLE
[Q&A] - queryInvoiceData hívásra MULTIPLE_QUERY_RESULT_FOUND hiba válasz

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#204]
queryInvoiceData hívásra "MULTIPLE_QUERY_RESULT_FOUND : A lekérdezett számla többször is szerepel érvényesként a rendszerben." hiba választ kapok az egyik számlára.

Több ezer számlát letöltöttem már, eggyel van probléma. NAV oldali adatbázis hiba lesz ez, mert API-ba mind a 3 paraméter töltve van, nem tudok semmit másképp paraméterezni hogy a hibát elkerüljem.

Kinek lehet privátba elküldeni a számla adatait.

A hiba az éles rendszeren jelentkezik.

**Comment by NTCA-supporter** [comment]
Kedves @EPluribusUnum 

Ilyen esetben a következőt lehet tenni, ami az interfész dokumentációban is benne van: "A hibaüzenet a /queryInvoiceData és /queryInvoiceCheck operációkban adható vissza akkor, ha a lekérdezett számlaszám többször érvényesként szerepel a rendszerben. Ebben az esetben a számlaszámot technikailag érvényteleníteni kell, majd a jóváhagyást követően az adatszolgáltatást meg kell ismételni a helyes adatokkal."

Tehát saját magad rendbe tudod tenni a duplikációt.

**Comment by EPluribusUnum** [comment]
Nem tudom ezt a választ elfogadni. A rendszerbe nem szabad hogy egynél több érvényes számla legyen. Van is erre ellenőrzés és hibaüzenet a NAV APIban. Mivel ez átcsúszott azon az ellenőrzen ezért ez egyértelmű NAV feldolgozási hiba. Az adatábzis is a NAVé, rendbe tenni a NAV dolga.

Nem áll módomban érvényteleníteni a számlát, mi a számla befogadói vagyunk és nem kiállítói, INBOUND módban töltjük le a számlát.

Amúgy a technikai érvénytelenítés esetén egyáltalán melyik számla kerül érvénytelenítésre ilyen esetben? Egy számlaszám hívásra mindkettő érvénytelenítésre kerülne?

**Comment by NTCA-developer** [comment]
@EPluribusUnum 

Mielőtt véglegesen pálcát törnél a kérdés felett, kérlek olvasd el a 2019/14 számú dev diary bejegyzést. Mert hogy amit látsz az a genezis szempontjából pont hogy kliens oldali hanyagság eredménye.

**Comment by EPluribusUnum** [comment]
@NTCA-developer , A hivatalos "Online Szamla_Interfesz specifikáció_HU_v2.0.pdf" dokumentációban semmi ilyesmi nincs, csak írnak a hibakód létezéséről.
A performance érvelést megértem és elfogadom.
DE, miért nem része a dokumentációnak a dev diary? Miért kell több helytől összevadászni az információkat? A pdf-be bele kellene tenni akkor dev diary-t és az itteni issue részeket is, ne legyenek szétszórva az információk.

**Comment by omachtandras** [comment]
Elnézést, hogy egy kicsit kötekedő leszek, de az ilyen eseteknél azért felmerül az emberben, hogy mi az a rendszer méret, amit nagy rendszernek hívunk, és a performanciára hivatkozva vajon egy adóellenőrzéskor hivatkozhatok-e arra, hogy a NAV-os rendszer is enged számla duplázódást, és nálunk 2.5 millió számla esetén csak 3-4 ilyen van, nem 200?
Mert gondolom nem... És teljesen jogosan, a törvény tiltja.
A probléma ezekkel a megoldásokkal (mint például a néhány adatok módosítunk, és úgy tároljuk le / adjuk vissza performancia okok miatt) az, hogy ügyfél oldalon kell kerülő megoldásokat találni, foglalkoztatni vagy fejlesztőt, vagy ügyintézőt. És ahelyett, hogy egy helyen központilag lenne úgy megoldva a probléma, ahogy kívánatos az üzleti oldal próbál ezekre kerülő megoldásokat találni, ami hatványozottan több idő és energia.

**Comment by NTCA-developer** [comment]
Szia @omachtandras 

Nem haragszunk, csak azt nem értjük hogy ezt miért nem annál kifogásolod aki termeli ezeket? Mi kiszűrjük a párhuzamos dupla beküldések 99,99992 százalékát, míg a requesten belüli duplák 100 %-át. Kiszűrhetnénk a párhuzamosok 100%-át is, cserében minden befogadási folyamatunk töbszörösen lassabb volna. (és itt 10-20x lassabbra gondolunk) Úgy gondoltuk hogy a 0,00002 % miatt nem lassítunk mindenkit.

Kutatni kellene az ennél jobb hatásfokú és még mindig performens lehetőségeket. Ez a probléma annyira szűk kört érint, hogy kizárt hogy jelen évben foglalkozni tudjunk vele. (Pedig még szívesen is csinálnánk, csak hát van jóval nagyobb fajsúlyú, más teendő a rendszerrel.)

Lesz még ennél nagyobb csodálkozás is ha a vevői oldal lekérdezései elindulnak. A hanyag implementációkat sajnos presszionálni kell a jó működésre. Ezt megteszi a NAV is, de tegyék meg a vevők is a saját oldalukról!

**Comment by NTCA-developer** [comment]
Szia @EPluribusUnum 

Igazad van, ez valóban IF doksiba illik. A következő kiadáskor beleálmodjuk valahová. Köszi az észrevételt, jogos!

**Comment by omachtandras** [comment]
Kedves NTCA-developer!

Ha lehet egy javaslatom -, túllépve azon, hogy nekem még megérne visszaigazolás oldalon akár tízszeres lassulást is az, hogy ellenőrizve legyen az egyediség - : nem lehet megoldani azt, hogy aki duplán küldött be számla adatokat onnantól, hogy ez kiderül (akár egy napi job árán) MINDEN beküldött adatára warningot kap vissza, hogy van neki egy duplikált beküldése, oldja meg, hogy ne legyen ilyen.
Tegye helyre, mindannyiunk érdeke ez. Még az ővé is. Főleg, ha a NAV készíti majd a bevallását és duplán befizetteti vele az ilyen számlák ÁFA tartalmát. ;)
Mert ok, hogy hanyag az implementációja, lehet, hogy nem is tud róla, hogy ilyen logikai hiba van a programjában...
Amivel én találkoztam, az nem kis cég, és az IThez is van bőven köze... Elkeserítő, hogy ilyen az implementációja, de ezzel nem tudok mit kezdeni, az viszont fogadói oldalon drága megoldás lesz, hogy az automatizmusokat kézi ágra kell irányítani és a fogadó oldalnak - nem informatikus vénájú ügyintéző - kell intézkednie és megértetnie a kiállító oldal - szintén nem informatikus vénájú - ügyintézőjével, hogy itt annulálni kell és adatot újra átadni.

Tessék belegondolni, hogy ez milyen overheadet eredményez... Össze nem mérhető a tízszeres visszaigazolás lassulással...

**Comment by NTCA-developer** [comment]
Szia @omachtandras 

Ezeket az opciókat mi is végigvettük már korábban, de sajnos nem találtuk egyiket sem kielégítőnek. A probléma ezekkel hogy mind humán interakciót igényelnek, amihez elsőként meg kell érteni, hogy egyáltalán mi a probléma. Sztorizzak arról, hogy a használati statisztikát hányan nézik meg? (Vagy egyáltalán hányan tudják hogy van ilyen?) Esetleg említsem meg, hogy pár hónapja még havi 10 milliós nagyságrendben kaptunk pár adózótól 1.0-ás API hívásokat? Vagy hogy néhányan most jönnek rá, hogy a feldolgozás eredményét le is kellene kérdezni, nem elég behányni a számla adatokat a NAV-nak? Nyilván ezek extrém példák és csak néhány adóznál, sporadikusan fordulnak elő, de még így is, egy ilyen edge-case problémával hogy keresed meg őket úgy hogy annak legyen is foganatja?

Talán az egyedüli jó megoldás - a végleges módozat megtalálásán kívül - az lenne ha a NAV bizonyos időközönként összefésülné ezeket a duplákat és az összeset technikai érvénytelenítené erőből. Erről viszont a törvény sem pedig az NGM rendelet egyáltalán nem beszél, ezért nem választhatjuk mint opciót.

Nem akarunk senkinek sem nehézséget sem overheadet okozni, a lassítás viszont nekünk nem járható út. És ezzel visszatértünk a start mezőre. :(
