### ISSUE TITLE
[Q&A]Tétel nélküli számla adatszolgáltatása

### ISSUE THREAD

**Issue by harmatilaszlo** [nav-gov-hu/Online-Invoice#205]
Sziasztok!  Adott egy vállalkozás, mely úgy döntött, hogy áfa értékhatár nélkül már most beküldi az összes számláját. Kiállít egy 20/2020-as számlát, de tételt nem visz még fel. Majd utána kiállítja a 21/2020-as számlát, nyomtatja illetve sikeresen beküldi a NAV-hoz. Észreveszi, hogy ott a 20/2020-as számla tétel nélkül, úgy dönt, hogy rontott számlaként kezeli és kinyomtatja (könyvelő is keresni fogja). Az adatszolgáltatás itt is elindul, de a következő hiba jön: "A számla nem tartalmaz tételt.". Ez rendben is van, de akkor mi lesz ezzel a számlával adatszolgáltatás szempontjából? Ez július 1. után még inkább érvényes lesz, hiányozni fog az adatszolgáltatásból.

**Comment by NTCA-tax** [comment]
Az adatszolgáltatás ahhoz kötött, hogy a számla kiállításra kerül, tehát a számlázó program a számla adatait lezárja. Amennyiben a program a rontott bizonylatot is kiállításként kezeli, akkor az adatszolgáltatás automatizmusa miatt az adatszolgáltatásnak meg kell történnie, és ennek a hibaüzenetnek kell születnie és az adatszolgáltatás nem kerül feldolgozásra.

Ugyanakkor az is egy számlázó program logika lehet, hogy a tételsor nélküli számlákat nem engedi kiállítani, így ez a hibajelenség nem tud előállni.

A számlázó program adatszolgáltatásának kapcsán mindegyik megoldás megfelelő, hiszen egy állapot beállta az adatszolgáltatás kezdőidőpontja. Amennyiben a számla kiállítás, mint állapot beáll, akkor azt követően nem szabad az adatszolgáltató funkciónak semmit sem mérlegelnie, hanem az adatszolgáltatást be kell küldeni. Még akkor is be kell küldeni, amennyiben előre tudható, hogy az nem lesz feldolgozva.

**Comment by harmatilaszlo** [comment]
A tétel nélküli számla sajnos elkerülhetetlen, így az az opció, hogy ne engedjük meg, nem játszik. (1. számlafej elkészül, vevő nem vásárol mégsem, sarkon fordul és elmegy, 2. Kézi számlát elrontom, áthúzom, rontott, ez is tétel nélküli lesz, stb.)

A másik esetben:
"Amennyiben a program a rontott bizonylatot is kiállításként kezeli, akkor az adatszolgáltatás automatizmusa miatt az adatszolgáltatásnak meg kell történnie, és ennek a hibaüzenetnek kell születnie és az adatszolgáltatás nem kerül feldolgozásra."
Ez érthető, de:
A hibaüzenet a dokumentáció szerint a blokkoló validációs hibakódok közé tartozik, amelyek:
"A blokkoló validációs hibák olyan tartalmi hibát jeleznek, melyek az adatszolgáltatás sikerességét megakadályozzák. Ilyen hiba megjelenésekor a számlaadat-szolgáltatást nem lehet sikeresnek tekinteni, a beküldött adatokat minden esetben javítani kell!"
Ebből szerintem az következik, hogy a számla adatszolgáltatása NEM történik meg, és a számlán sem tudunk javítani semmit.
Úgy gondolom, hogy a tétel nélküli számláknak a lejelentését biztosítani kellene, ráadásul lehetőség van a számlák lekérésére, de az ilyen számla nem fog szerepelni ebben, például egy könyvelő programba történő beépítés után hiányozni fog onnan.

**Comment by NTCA-tax** [comment]
Egy tételsor nélküli bizonylat nem értelmezhető számlaként, az nem kerül lekönyvelésre, nincs összege, nem kerül bele az adóbevallásba sem. Ez egy rontott bizonylat, melyet a számlázó program nyilvántart. Erről a bizonylatról nem is kellene adatszolgáltatást adni, mivel nem funkcionál számlaként. 

Amennyiben mégis történik adatszolgáltatás, akkor az adóhivatal nem dolgozza fel azt. Itt ebben az esetben nincs mit javítani, és nem is lehet javítani. Amennyiben a felhasználó tudja, hogy ez a számlázó program működésének logikájából származik, akkor hátradőlhet. Amennyiben viszont hibás az adatszolgáltatás (pl. tényleg kihagyta a program a tételsorokat), akkor mindenképpen van vele teendője.
