### ISSUE TITLE
[Q&A] 2020.07.01 utáni végszámla KÜLÖNBÖZETRŐL való adatszolgáltatás  

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#206]
Az ÁFA tv. 2020.07.01-től hatályos szövege szerint a 10.sz. melléklet 5. pontja alapján  
végszámla esetén csak a termékértékesítés és a végszámlába betudott előleg KÜLÖNBÖZETÉRŐL kell adatot szolgáltatni elektronikus úton a NAVOnline adatszolgáltatás keretében. 
[http://njt.hu/cgi_bin/njt_doc.cgi?docid=111467.376077](url)
Idézet: 
„5. Amennyiben az adóalany az általa teljesített termékértékesítéshez, szolgáltatáshoz 59. § szerinti előleget kapott, a teljesítésről kibocsátott, kiállított számla, számlával egy tekintet alá eső okirat vonatkozásában az előleg figyelembevételével adódó különbözetről szolgáltat adatot.” 
 
Ez véleményem szerint beleütközik a számla adatszolgáltatás elvárásaiba, miszerint a számlán szereplő tételsorokat bele kell tenni az adatszolgáltatásba, és az adatszolgáltatásba kerülő adat-sor alkalmatlan lesz arra, amire hirdetik: hogy a számlát befogadó letölthesse a NAVOnline adatszolgáltatásból, és azt a saját ERP rendszerébe befogadva feldolgozza. 
 
Amennyiben a számlázó program nekiáll különbözetet számolni, akkor annak több módja is van, és számos további kérdést felvet: 
**Ha az előlegszámla így néz ki:** 
1 sor: nincs mennyiség, nincs mértékegység, nettó 1.010.000 Ft + 272.700 Ft Áfa = 1.282.700 Ft  
 
**A végszámla így néz ki:** 
1. sor: 6 db "A" termék értékesítése 100.000 Ft + 27.000 Ft áfa =127.000 Ft 
2. sor: 8 db "B" termék értékesítése 1.000.000 Ft + 270.000 Ft Áfa = 1.270.000 Ft 
3. sor: előleg betudás: -1.010.000 Ft -272.700 = -1.282.700 Ft 
Fizetendő adóalap: 90.000 Ft + áfa 24.300 = 114.300 Ft bruttó  
 
Eddig egy végszámláról úgy szolgáltattunk adatot, hogy mind a 3 db tételsort beküldtük. 
2020.07.01-től az eddigi módszer jogszabályba ütköző lesz, helyette KÜLÖNBÖZET-ről kell csak adatot szolgáltatni. Ekkor helyes lesz az alábbiak mindegyike?  
1. eset: Az 1. sor nem kerül bele az adatszolgáltatásba (mert ez előlegből betudtam rá 100.000 Ft-ot), a 2. sornál marad a 8 db mennyiség és az egységár is, de az adóalap 90.000 Ft lesz (1.000.000 Ft - 910.000 Ft betudott előleg), az adó 24.300 Ft lesz. 
A 3. sort is kihagyjuk az adatszolgáltatásból. 
 
2. eset: Az 1. sorról 6 db mennyiség és 90.000 Ft adóalap + 24.300 Ft adó kerül az adatszolgál-tatásba, és a 2. sorról semmi (mivel a különbözet 0.00 Ft)  
A 3. sort is kihagyjuk az adatszolgáltatásból. 
 
Több terméksoros és abba betudott több előlegszámla esetén a különbözet számításra a lehet-séges variációk száma sokkal több lesz.  
	1. Az egyik kérdésem az, hogy mikor jár el helyesen az adóalany, ha a törvényt tartja be, vagy ha annak ellenére minden számla tételsorról adatot szolgáltat?   
	2. A másik kérdésem az, hogy a számla program készítője helyesen jár-e el abban az esetben, ha a törvényt tartja szem előtt, és 2020.06.30 után különbözetet képez a végszámlából, és tényleg csak a különbözetről szolgáltat adatot?  

	3. A harmadik kérdésem az, hogy a mennyiségnél hogyan kell számítani a törvény szerint előírt különbözetet abban az esetben, ha a termékértékesítés természetes mértékegységben kifejezett, de az előlegnek nincs mértékegysége? A tételsor adóalapjába betudott előleg után maradó adóalaphoz arányosítani kell-e az eredeti mennyiséget ilyenkor, vagy az egységárat kell, arányosan átszámolni? 

Ha az előlegnek nincs mértékegysége és nincs mennyisége, akkor hogyan lehet a mennyiségnél ekkor „különbözetet” számolni?   
Ha az előlegnél valaki DB mértékegységet használ, a terméket viszont tonnában értékesíti, akkor hogyan kell számolni a tonna-db mennyiség „különbözetét”? 
 
**Ezek szerint a végszámláról történő adatszolgáltatás sarkított esetben teljesen kikerülhető az alábbi módon 2020.07.01 után:** 
Ha a termék értékesítés teljesítése előtti napon 100% előleg érkezik, amiről kiállítom az előleg-számlát, és ez be is kerül az adatszolgáltatásba, sőt a vevő le is töltheti API-n keresztül. 
A végszámlán a termékesítés lesz az első sor pozitív számokkal, a második sora az előleg be-tudása lesz, ami a 100% miatt 0 Ft fizetendő adóalapot 0 Ft fizetendő adót jelent számla szinten. 
És mivel a különbözetről kell adatot szolgáltatni, így erről a végszámláról NEM kell adatot szolgáltatni.  
Ha nincs adatszolgáltatás, akkor a vevő sem tudja a végszámlát letölteni a saját ERP rendszerébe, nem tudja mit vett, hiszen ő csak az előlegszámlát kaphatja meg a NAV-tól történő lekérdezéssel. 
 
**További súlyos probléma az,** hogy az ÁFA tv. 169.§ nem tartalmazza azt, hogy a végszámlán szerepeltetni kellene az előleg betudást, a végszámlán a 169.§ f) pontja szerint csak a termék-értékesítést, annak mennyiségét s egységárát kell kötelezően szerepeltetni, ugyanakkor az adat-szolgáltatásban meg az előleghez képesti KÜLÖNBÖZETET.   
Tehát az adatszolgáltatás ellentmond a számla adattartalmának, ezért ellentmond a 23/2014 NGM rendeletnek. 
**Mielőbb tisztázni kellene ezeket a kérdéseket, hogy 2020.07.01 után is meg tudjunk felelni az adatszolgáltatási kötelezettségnek, és közben a törvénynek is.**

**Comment by Rossi73** [comment]
_"erről a végszámláról NEM kell adatot szolgáltatni"_

Ebben egészen biztos vagy? Én úgy tudom, július 1-től minden számláról adatot kell szolgáltatni, összegtől/áfa értéktől függetlenül, amit **adóalanyok** részére állítunk ki (pl. KATA-s vállalkozók, nem áfás számla kiállítása esetén is), most még nem kell, július 1-től kell. Január 1-től pedig "jönnek" a magánszemélyek is.

Ettől függetlenül egyetértek Veled, mert ez csak káoszt fog eredményezni. A legjobb az lenne, ha minden maradna a régiben az előleg/végszámla tekintetében (ezzel megszívatnak X fejlesztőt, ahelyett, hogy a NAV programozói 1x megcsinálnák a lekérdezésüket úgy, ahogy nekik jó)...

**Comment by Macskafarka** [comment]
A probléma lényege az, hogy az ÁFA törvény által frissen beemelt "különbözet" hogyan értelmezhető tételsor szinten. A törvény szerint tehát végszámla esetén nem a számla tételsorairól kell adatot szolgáltatni (amelyben külön sorban szerpel az előleg betudás is), hanem a valamiféle különbözetről.
Ha nem "tételsorbeli különbözet" lenne a cél, akkor nyilván azt írták volna elő a törvényben, hogy az előleg betudásnak külön tételsorban kell szerepelnie,  és a számla minden tételsorának be kell kerülnie az adatszolgáltatásba. De nem ez van előírva.

**Comment by Rossi73** [comment]
Annál is inkább igazad van, mert szerintem ez az egész alapelvvel megy szembe. Mert eddig az volt, hogy amit kiállítottunk, a számlán tételt rögzítettünk, az egy az egyben menjen be, aztán a NAV úgy elemzi, ahogy akarja. Ha most a beküldő oldalon hozzá kell nyúlni ehhez, és **bármilyen számítási mód** alkalmazásával **nem azt kell beküldeni, ami a számlán szerepel,** az csak problémát okozhat. Mert senki sem tévedhetetlen, és bármikor hibázhat akár vétlenül is. Ha pedig ez az igény megmarad, akkor ez alapján bármikor megszabhatnák, hogy ugyan A adat van egy számlán, de menjen be mellette **vagy helyette** B adat.

Sokkal inkább az lenne a célszerű, ha a fogadó oldalon (NAV) alakítanák úgy a lekérdezéseket, hogy a "nyers" adatokból (azaz az **összes** adatból) megkapják azt, ami számukra megfelelő, és ne tőlünk kérjék azt, hogy az adatok módosításával, vagy bármilyen számítás elvégzésével küldjünk be más adatokat.

Ez megint egy olyan módosítás, aminek az egész számlázási, ÁFA bevallási történethez vajmi kevés köze van, azon nem gyorsít, "csak" ad a fejlesztőknek megint egy olyan plusz munkát, amit valószínűleg a hátuk közepére sem kívánnak.

**Comment by betasofthu** [comment]
Csatlakozom az előttem szólókhoz. A jelenlegi XSD fájlba ezt nem lehet belegyömöszölni. Jóformán már csak két hónap van e bevezetésig, és nem értjük mit kell csinálni.  Szeretnénk egy magyarázatot és számlamintát is.

**Comment by Macskafarka** [comment]
Én azt gondolom, hogy ez jogalkotói kérdés, és nem oldható meg az adatszolgáltatásban jelenleg.
Ellentmondás van a törvény és az adatszolgáltatás között, amit az adatszolgáltatásban a NAV sem tud feloldani, mert a törvény módosított szövege ellentmond a tételsorokból való adatszolgáltatás elvének.
Olyan, mintha a jogalkotó még az adatszolgáltatás előtti korszak fogalmaival operálna.
Valahol talán ott siklott félre a dolog, amikor az áfa bevallás xx65M lapjaival akarták összehangolni.
Mindenesetre ezt a kérdést már közvetlenül többször is beküldtem a NAV-nak, és nagy hallgatás van róla immár 60 napja.
Minden más kérdésre válaszoltak akkor is, azóta is. Tudom, hogy nehéz a válasz, de valamit kezdeni kell ezzel a helyzettel július 01-ig. Ezért tettem bele példával a lehetséges káoszt.
Megtehetjük, hogy úgy adunk fel adatot, mint eddig, mert tesztelni nem tudjuk. A NAVOnline teszt felülete nem alkalmas a különböző törvényi novellák miatti helyzetek tesztelésére. Nem tudható, hogy ha a törvény szövege változik, akkor azt hogyan képezik le. Ez csak élesben derül ki 2020.07.01-jén.
El kell dönteni, hogy a törvénynek akarunk megfelelni, vagy az XSD-nek.

**Comment by Rossi73** [comment]
... és ha készülne számlaminta (jogos felvetés, előre is köszönjük!), akkor a számlamintában eltérő mennyiségi egységekkel rendelkező tételeket kérünk szerepeltetni. Legyen pl. egy olyan gépjármű értékesítésről szóló számla, amikor két gépjárművet (4M + 5M Ft értékben, összesen 9M Ft) értékesítenek. Erről kap a vevő egy előlegszámlát (kezdőrészlet) egy összegről, majd egy másik előleg számlát az egyik gépjárműről árának 50%-áról, majd a végszámlát a két gépjárműről. A teljes tranzakció összege 9M Ft, az előleg két tételben 3M Ft, a végszámlával együtt fizetendő 6M Ft.

**1. számla (előleg):**
ELŐLEG (mennyiségi egység nélkül) +1.000.000 Ft + áfa
Végösszege: 1.000.000 Ft + áfa

**2. számla (előleg):**
„A” típusú autó előlege, 1 db, 50% kedvezmény, +2.000.000 Ft + áfa
Végösszege: 2.000.000 Ft + áfa

Jelenleg ez így néz ki a végszámla:

**3. számla (végszámla):**
ELŐLEG (mennyiségi egység nélkül) -1.000.000 Ft + áfa
„A” típusú autó, -1 db, 50% kedvezmény, -2.000.000 Ft + áfa
„A” típusú autó, 1 db, +4.000.000 Ft + áfa
„B” típusú autó, 1 db, +5.000.000 Ft + áfa
Végösszege: 6.000.000 Ft + áfa

Július 1-től hogy nézne ki ez a végszámla?

(Az sem baj, ha esetleg itt kapjuk meg a konkrét választ, tehát hogy a végszámla tételei pontosan milyen **nevet** kapjanak, milyen **mennyiségi egység nélkül/mennyiségi egységgel,** és **összeggel**, de nyilván a dokumentáció lenne a legjobb megoldás.)

**Comment by Macskafarka** [comment]
Az ilyen minta sokat segítene.

**Comment by NTCA-tax** [comment]
Sziasztok!

Jó látjátok a problémát, hogy a jogszabály eléggé szűkszavúan elintézte a végszámlát úgy, hogy a különbözetről kell adatot szolgáltatni. A különbözeti adatszolgáltatásnak jelenleg két módját látom (egészítsetek ki, ha ennél többet is el tudtok képzelni):

1. Az adatszolgáltatásban levezetitek a különbözetet. Tehát ebben az esetben nem néz ki másként az adatszolgáltatás, mint maga a számla (vagy ahogy az áfa törvény alapján a számlának ki kellene néznie). Tehát megjelenik a teljesítés teljes összege, külön sorban az előleg összege vagy előlegek összegei (advanceIndicator=true), az összesítésben pedig a különbözet. A különbözet a végösszegben megjelenik, az adatszolgáltatás könnyen értelmezhető adóhivatali oldalon is, valamint ügyféli oldalon is. Amennyiben a vevő megnézi az adatszolgáltatást, számára is egyértelmű lesz.

2. Az adatszolgáltatásban csak a különbözet jelenik meg egy tételsorban. Ezzel kapcsolatban én is hosszasan konzultáltam, mivel ahogy Ti is látjátok elég sok kérdést vet fel. Az áfa törvény nem nagyon magyarázza tovább a különbözetről történő adatszolgáltatást, ezért a jogszabályi keretekbe ez is belefér. Ennek a megoldásnak ugyanakkor vannak jelentős kihívásai. Ilyen lehet az adókulcs különbözőségének kérdése, tételsor megnevezése, de akár az általatok felvetett mértékegység kérdése is. Ebben az esetben eltér a számlakép az adatszolgáltatástól (amennyiben persze a jogszabályoknak megfelelően készült a számla). Amennyiben a vevő (de akár az értékesítő) megnézi az adatszolgáltatást, számára nem lesz könnyen értelmezhető az adatszolgáltatás tartalma. Amennyiben a vevő a számlafeldolgozásához használja az adatszolgáltatást, akkor nehézségekbe ütközhet. Ugyanakkor mivel a végszámla adatszolgáltatására speciális szabályt alkotott az áfa törvény, ezért nem ütközik jogszabályba, ha a számla adattartalma és az adatszolgáltatás adattartalma némileg eltér egymástól.

Amennyiben egy kicsit rendszerben akarunk gondolkozni, akkor azért van szükség a különbözetről történő adatszolgáltatásra, mivel az esetek többségében a végszámlánál az előleg beszámításakor a nettó előleggel csökkentett adóalap után keletkezik adófizetési kötelezettség. A végszámla adatszolgáltatása kapcsán jelenleg számos egyéb más megoldásokat is találunk (pl. a gazdasági esemény teljes összege jelenik meg csak a végszámlában, az előleg nem; az előleg bár megjelenik, de összesítésre a gazdasági esemény teljes összege kerül stb.). A jogszabály egyértelműsíti, hogy a végszámla adatszolgáltatásában az előleg beszámításából adódó különbözetet kell beküldeni.

**Comment by betasofthu** [comment]
O.K. Marad az 1. verzió. Nálam eddig is ez volt. A "számos egyéb megoldás pl. a gazdasági esemény teljes összege jelenik meg csak a végszámlában" az áthárított adó értelmezése miatt készülhetett. A végszámla áthárított adójának értelmezése meglehetősen elbonyolította eddig a 100 ezer forintos értékhatár figyelését és ez vezetett a "számos egyéb megoldáshoz".  Én magam is két egymásnak ellentmondó adóhivatali választ kaptam  a végszámla áthárított adójának értelmezéséről. Ennek most vége. Feltételezem, hogy a jogalkotó ezt a "számos egyéb megoldást" akarta kizárni KÜLÖNBÖZET szóhasználattal. Tehát marad az 1. megoldás, különben soha nem lesz vége a végszámla körüli bonyodalmaknak.

**Comment by Macskafarka** [comment]
Igen, az 1 megoldás szimpatikus, mert megmarad a számlaképpel való kapcsolata, és az értelmezhetősége. Itt legalább mi dönthetjük el.
Csak ugyebár már befogadó oldalon is gondolkodunk a NAV-tól való letöltésen, és ha ott kapunk olyan számlát, amelyből nem tudjuk "visszaálmodni" az eredeti számla sorait, akkor értelme sem lesz a letöltésnek.
Talán a jogalkotónak kellene kimondani pár egyértelműsítő dolgot, ilyenek pl.:
A számla tételsora az adatszolgáltatási egység, mindennek ebből kell levezethetőnek lennie. 
Ezt az adatszolgáltatási egységet lehet aztán módosítani, törölni stb. De azt nem kéne megengedni, hogy az adatszolgáltatás előtt adatvesztéshez számolni a kelljen a számlázó programnak. A "különbözet" az adatvesztéssel jár, mert belőle nem építhetó vissza a művelet két tényezője.

**Comment by Macskafarka** [comment]
ÁFA törvényi szinten kellene azt figyelembe vennie, hogy a számlából legalább 3 dolognak kell felépülnie. 1. NAV Online adatszolgáltatás (pl adómegállapításhoz), 2. vevő be tudja fogadni (legyen értelme számára is a NAV-tól letöltött adatoknak), 3. Ki lehessen elégíteni a saját könyvelési igényt.
Csak megjegyzem, hogy 4. lehet az, hogy a támogassa a  vevői készletre vételt is, vagyis cikk mélységű információkat is hordozzon (mennyiségi egység, mennyiség, cikkszám, termékjegyzék kód stb) .

**Comment by Rossi73** [comment]
> Az adatszolgáltatásban levezetitek a különbözetet. Tehát ebben az esetben nem néz ki másként az adatszolgáltatás, mint maga a számla (vagy ahogy az áfa törvény alapján a számlának ki kellene néznie). Tehát megjelenik a teljesítés teljes összege, külön sorban az előleg összege vagy előlegek összegei (advanceIndicator=true), az összesítésben pedig a különbözet. A különbözet a végösszegben megjelenik, az adatszolgáltatás könnyen értelmezhető adóhivatali oldalon is, valamint ügyféli oldalon is. Amennyiben a vevő megnézi az adatszolgáltatást, számára is egyértelmű lesz.

Jól értem ez alapján - ha az általam fent írt példánál maradunk -, hogy a végszámlában maradhat a példában írt számlakép, és ugyanezt küldhetem be adatszolgáltatásként (persze az advanceIndicator megfelelő használatával)? Tehát nem szükséges változtatnom, ha jelenleg is így csinálom?

**Comment by NTCA-tax** [comment]
Igen, jól érted @Rossi73 nem szükséges változtatnod, amennyiben az 1. pontban leírtnak megfelelően működik jelenleg a programod. A 2. pont bár jogszabályilag lehetséges megoldás, ugyanakkor gyakorlati alkalmazásával kapcsolatban erősen kérdőjeles.

**Comment by NTCA-supporter** [comment]
Lezárom a ticktetet. De ha még van kérdés akkor nyissatok újat nyugodtan.
