### ISSUE TITLE
[DEV support] queryInvoiceData nem válaszol

### ISSUE THREAD

**Issue by balintdozsa** [nav-gov-hu/Online-Invoice#207]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[x] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[x] 1.1
[] 2.0

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Nagy mennyiségű számla beküldésekor (8-10 ezer) azt vettük észre, hogy a queryInvoiceData végpont hibát adhat egy idő után a módosítószámlák eredetijének keresésekor. Ilyenkor jellemzően Curl Error 52-őt kapunk (Empty response), de előfordul Curl Error 35 is.
Van valamiféle korlátozás beépítve, hogy mennyi kérés intézhető rövid időn belül a végpont irányába?

**Comment by NTCA-supporter** [comment]
Kedves @balintdozsa 

Nincs olyan korlátozás a teszt környezeten, ami az intézett kérések számára vonatkozna. Amiért tapasztalhatsz ilyen eseteket az azért lehet, mert mi is futtatunk performancia teszteket ezen a környezeten és ilyenkor elképzelhető, hogy csak később(time out időn kívül) érkezik válasz.
A hamarosan kiadandó verzióban (2.10) kerülnek a rendszer performanciáját növelő módosítások is. A híreknél fog megjelenni az új verzió telepítéséről információ. Azt majd érdemes figyelni.

**Comment by NTCA-developer** [comment]
Ezt lezárom. Ha szükség van még segítségre akkor írj nyugodtan!
