### ISSUE TITLE
[Q&A] Onlineszamla oldalon export

### ISSUE THREAD

**Issue by karasu-code** [nav-gov-hu/Online-Invoice#208]
Kedves @NTCA-developer!

Kérdésként merült fel ügyfél részről, hogy tervezitek-e az onlineszámla webes felületen a jelenlegi export megoldás átalakítását, hogy a számlák (akár kiadott, akár beérkezett) adott feltételek szerint szűrt csoportja egyben, valamennyi adatukkal (tételsoronként, mellette a fejlécadatokkal) exportálhatóak legyenek, ne csak egyesével?

**Comment by NTCA-developer** [comment]
Szia @karasu-code 

Igen, az átalakítást a szakmai terület is megfogalmazta már részünkre igényként. Az új export egy fájlt fog tartalmazni, és nem csak az egy oldalon megjelenő számlák, hanem az összes - keresési feltételnek megfelelő - számla belekerül az exportált adatok közé. A fájlban listaszerűen jelennek majd meg a számlák főbb adatai az első sheeten, míg a lekérdezett számlákhoz tartozó tételek adatai egy másik sheeten, ugyanazon fájlon belül. Ez lényegében az az export formátum, amit Online Számlázó jelenleg is csinál. A számlák exportja a jelenleg használt és fenti új formátum szerint is kérhető lesz.

A funkció az Online Számla rendszer soron következő verziójában (2.10) fog települni. Figyeljétek az Informatikai változások menüpontot, ott fog megjelenni a funkció leírása verzióváltást követően.

Ha nincs több kérdésed akkor kérlek zárd majd le!

**Comment by karasu-code** [comment]
Köszönöm a választ

**Comment by NTCA-developer** [comment]
Szia @karasu-code 

Csak visszajelzek, ez a funkció tegnap este települt az élesre, már használható.
