### ISSUE TITLE
[Q&A] Lehet-e a számlán kevesebb áfa "mentes" alap összesítés mint a VatRateType-ban? 

### ISSUE THREAD

**Issue by betasofthu** [nav-gov-hu/Online-Invoice#209]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Lehet-e a papíron megjelenő számlán kevesebb áfa "mentes" alap összesítés mint az arról leadott adatszolgáltatásban a VatRateType-ban? Kérdezem ezt annál is inkább, mivel az áfa törvény egyáltalán nem ír elő semmilyen áfa alaponkénti összesítést sem.

A VatRateType-ban  un. "6-os choice"-ban a  nulla áfás tételeket külön összesíteni kell 5 kategóriában: 
mentes (vatExemtion), 
vatOutofScope(áfa hatályán kívüli), 
vatDomesticReverseCharge(fordított adózás),
marginSchameVat (különbözet sz. adózás1)
marginSchameNoVat (különbözet sz. adózás2)

Egy számlán belül előfordulhat egyszerre több olyan tétel, amit eszerint elkülönülten kell összesíteni. Amint azt a #131-es kérdésre adott válaszból tudjuk, több mentes tételt több külön áfa összesítésben kell összegezni. Szélsőséges esetben akár 5-8 féle áfa összesítésre is szükség lehet. 
Szándékom szerint a több "nulla áfás" áfa összesítést összevonom és egyben jelentetem meg a számlán. Az adatszolgáltatásban ettől függetlenül ezek külön összesítésben jelennek meg. 

Úgy gondolom, hogy a részletesebb adatszolgáltatási előírásnak nem kell visszahatnia a bizonylatolásra. Elfogadható ez a megoldás?

**Comment by NTCA-tax** [comment]
Erre a kérdésedre nem lehet egyértelmű igennel vagy nemmel válaszolni. A kérdésben van olyan elem, ami megfelelhet a jogszabálynak, de olyanok is vannak, amelyek nem. Ezeket érdemes átgondolnod, hogy a megfelelő megoldást megtaláljad.

A számla adattartalma és az adatszolgáltatás között lehetnek különbségek. Erre jó példa a gyűjtőszámla adatszolgáltatása, ahol az adatszolgáltatásban elvárunk egy számla teljesítési dátumot, miközben a gyűjtőszámlánál ez csak tételsoronként értelmezhető. Tehát elviekben helyes az a meglátás, hogy nem szükségszerűen egyezik meg a számlakép adattartalma és az adatszolgáltatás tartalma. Az adatszolgáltatás a számlának egy informatikai kivonatát jelenti, nem pedig magát a számlát.

A "hatos choice" többféle adózási módot takar, melyek közül csak egy az adómentes értékesítés. Ennél a jogszabály azt várja el, hogy a mentesség okát fel kell tüntetni a számlán, mely alapvetően az adott termékértékesítéshez, szolgáltatás nyújtáshoz kapcsolódik. A többi elem nem adómentességet takar, hanem különös adózási módokat (pl. fordított adózás, különbözet szerinti adózás). Ezeket akkor sem lehet adómentesnek tekinteni, ha a számlán nincs és nem is lehet feltüntetni áfa összeget.

A jogszabály nem ismer nulla százalékos adókulcsot. Ahogy láttuk az adatszolgáltatásoknál, hogy mennyi program küld be nekünk nulla százalékos értékesítést (a mentesség okának feltüntetése helyett), bevezettük az 1.1-es verzióban az adókulcsra az értéklistát. Így maga az a fogalom, hogy "nullás áfa" adójogilag biztosan nem helyes.

Az áthárított adót nem tartalmazó tételsorok összesítésére vonatkozóan az Áfa törvény nem ír elő taxatív szabályt, így ténylegesen enged mozgásteret a jogszabály. Az, hogy ki milyen széles mozgásteret enged meg a programjában, az egyedi döntés kérdése. Amennyiben a számlázás teljes folyamatát és a számla adattartalom feldolgozását is figyelembe vesszük, akkor ténylegesen lehet szerepe az áthárított adót nem tartalmazó tételsorok típusonkénti összegzésének. Nem feltétlenül szükséges az áfa hatályán kívüli értékesítéseket okonként összegezni, de érdemes lehet megkülönböztetni például a fordított adózású vagy különbözet szerinti adózású tételek összegzésétől.

**Comment by betasofthu** [comment]
Köszönöm a választ! Úgy látom, hogy valójában igen a válasz, mivel nem tudtál olyan elemet mondani ami nem felel meg a jogszabálynak.  A "nulla áfa"-ról tudjuk, hogy nincs a jogszabályban. Ez rendben van. Csupán így (illetve "mentes"-nek) neveztem az áthárított adót nem tartalmazó tételsorokat. Szerintem nemcsak ezen "tételsorok összesítésére vonatkozóan az Áfa törvény nem ír elő taxatív szabályt", hanem egyáltalán nem ír elő áfa alap összesítést. 
Egy bátor "igen" válasz jobb lett volna.  Végül is ha nincs ilyen előírás, akkor nem lehet kötelező. Tulajdonképpen ez az összesítés csak a könyvelők munkáját segíti.
