### ISSUE TITLE
[DEV Support] Vevő adószám nem létezik

### ISSUE THREAD

**Issue by MTYS87** [nav-gov-hu/Online-Invoice#210]
Sziasztok,
szeretnék segítséget kérni, miért nem fogadja be a rendszer a vásárló adószámát a teszt környezetben?
WARN üzenetet kapunk minden esetben.
Tranzakció azonosító: 2Y5E27KF9QPYAN48

Előre is köszönöm!

**Comment by NTCA-developer** [comment]
Szia @MTYS87 

Ez az adószám CDV hibás, baj lenne ha létezne. Ha itt ellenőrzöd láthatod hogy az élesen sincs: https://nav.gov.hu/nav/adatbazisok/adatbleker/afaalanyok/afaalanyok_egyszeru

**Comment by MTYS87** [comment]
Teszteltük létező adószámmal és működik. Köszönöm!

**Comment by zsfoto** [comment]
Hasonló problémával vagyok én is. például: https://www.ceginformacio.hu/cr9311611724 az adószáma nem létezik a teszt szerveren. Éleset nem tudom. Az adószám: 26670380-2-02

**Comment by baracsi** [comment]
> 
> 
> Hasonló problémával vagyok én is. például: https://www.ceginformacio.hu/cr9311611724 az adószáma nem létezik a teszt szerveren. Éleset nem tudom. Az adószám: 26670380-2-02

élesben jó 2.0-val de tesztben valóban azt mondja, hogy nem érvényes

**Comment by RvPSc** [comment]
Elvileg ez azért van, mert nem tartják karban a rendszert. Korábban néztem, akkor valami olyasmit figyeltem meg, hogy a 2018.X.X óta módosult / rögzített cégek adatai nem látszódnak (pl. mi is rossz cégnévvel vagyunk fent). Emellett csak reménykedni tudok, hogy pl. a beígért rövid cégnév le fog jönni (bár 1-2 hete már elengedtem, nem is nézem, hogy jó-e már) Inkább megcsináltam, hogy mivel nem adnak vissza rövid cégnevet, ezért oda az általam string műveletekkel hackeltet írom...  Én most éppen azt keresem, hogy van-e már olyan, hogy cégnév alapján adószám lekérés. Mintha olvastam volna valahol, de lehet, hogy csak igény. Csak hát ezen a github-on keresést indítani...
