### ISSUE TITLE
[Q&A] electronicInvoiceHash

### ISSUE THREAD

**Issue by laladisc** [nav-gov-hu/Online-Invoice#211]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Elektronikus számla sha256 lenyomatának beküldése
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Az Online számla adatszolgáltatásban lehetőség van az elektronikus számla SHA256 lenyomatát beküldeni (electronicInvoiceHash), és így a 1/2018. (VI. 29.) ITM rendelet szerint megvalósítható a számla eredet hitelességének és az adattartalom sértetlenségének megőrzése, így ha jól értelmezem nincs szükség elektronikus aláírás és időbélyegző használatára elektronikus számla készítéséhez. A kérdésem az lenne, hogy ha az alábbi módon járok el, akkor az a NAV álláspontja szerint megfelelő e az elektronikus számlázás bevezetéséhez?
-Elkészül egy pdf fájl mint elektronikus számla. 
-A fájl mentése után az egész fájlara vonatkozóan elkészítem a fájl SHA256 (UPPERCASE) lenyomatát, amely a következő online ellenörző szerinti eredményt adja: https://emn178.github.io/online-tools/sha256_checksum.html
-Ezt követően beküldöm a NAV online számlán keresztül a számlát, amelynek SHA256 lenyomatát mellékelem az electronicInvoiceHash-ben.
-Ha az adatszolgáltatás státusza DONE, akkor e-mailben továbbítom a vevő részére a pdf fájlt és a fájl hash értékét.

Üdvözlettel: Lajos

**Comment by NTCA-tax** [comment]
Alapvetően megfelelő a felvázolt megoldás. Annyiban pontosítanám, hogy a PDF állomány generálásnak a számla kiállítását követően azonnal meg kell történnie, és ezt követően pedig indulnia kell az adatszolgáltatásnak. Mind az értékesítőnek és mind a vevőnek van elektronikus iratmegőrzési kötelezettsége. Tehát mindkét félnek (amennyiben az ITM rendelet szerinti hash kódos megőrzés mellett döntenek) a PDF alapú elektronikus számlát és a hash kódot is meg kell őriznie.

Visszatérve az alapkérdésedre, amennyiben a hash kód beküldése mellett döntesz, akkor nincs szükség sem elektronikus aláírásra, sem pedig időbélyegzőre. Egyébként időbélyegzési kötelezettség más esetben sincs.

**Comment by laladisc** [comment]
Köszönöm szépen a választ. Még annyi kérdésem lenne ezzel kapcsolatban, hogy a hash kódot célszerű e egy külön fájlba tenni mint a számla melléklete, vagy esetleg az is elegendő lehet, ha email-ben a számlával együtt megküldjük szövegesen a vevő részére?

**Comment by NTCA-tax** [comment]
Ez a vevővel történt megállapodás kérdése. Talán azért célszerű külön fájlba tenni, mivel a jogszabály alapján az elektronikus számlát és a hash kódot együtt kell megőrizni. Amennyiben a vevő két állományt kap, akkor egyszerűbben tudja megőrizni a két állományt, mint összekötni az elektronikus számlát az email-el.

**Comment by laladisc** [comment]
Köszönöm szépen a választ.

**Comment by nbeeps2** [comment]
Mi a helyzet a következő esetben: elkészítem a PDF számlát, megcsinálom a hash lenyomatot, beküldöm a NAV-nak, DONE lesz, megy a vevőnek, MAJD tönkremegy a számítógép és a gépen tárolt PDF-ek elvesznek. A programból van adatbázismentés, tehát a számlák minden adata meg van (visszaállítható), ami alapján újra lehet generálni a PDF-et, számlaképet, viszont annak hash lenyomata nem fog megegyezni az eredetileg előállított PDF-el. Az általam említett eset nem szélsőséges eset, minden héten van ilyen ügyfelünk, akinek ilyen adatvesztése van...

**Comment by laladisc** [comment]
Én amikor elkészült a számla, akkor a PDF fájlt mentem az adatbázisba egy blob fieldbe a hash-el együtt. Így a fájlt nem kell újragenerálni, csak "elővenni" a blob field-böl, így a hash kód nem változik.

**Comment by NTCA-tax** [comment]
A PDF állományt a hash kóddal együtt kell az adózónak megőriznie. A megőrzés körülményeit az 1/2018 ITM rendelet alapján kell biztosítani. Ez feltételezi, hogy az elektronikus számlákat olyan helyen tárolja az adózó, ahonnan nem lehet törölni, módosítani az adatállományokat. Az ITM rendelet alapján ez alapkövetelményt jelent, független az elektronikus számla megőrzésének technikájától. Amennyiben ez nem teljesül, akkor az adózó nem teljesíti az archiválási rendeletben előírt szabályokat.

Az iratok elvesztésének körülményeit az adóhivatalnak ennek alapján kell mérlegelnie. Amennyiben azt állapítja meg az adóhivatal, hogy az adózónak felróható okok miatt történt az elektronikus iratok elvesztése, akkor azt szankcionálhatja. 

@laladisc kérdése csupán a mentés, megőrzés módját jelenti. Az ITM rendelet csupán azt írja elő, hogy az elektronikus számlát a hash kóddal együtt kell megőrizni. Ezt úgy is el lehet végezni, hogy adatbázisba kerül lementésre a PDF állomány és a hash kód.

**Comment by clapygeza** [comment]
Sziasztok!
Ez mind nagyon szép lenne, ha lenne olyan megoldás ami megfelelne az ITM rendeletnek:
_3. § (1) A megőrzésre kötelezett a megőrzési kötelezettség lejártáig folyamatosan köteles biztosítani, hogy az elektronikus dokumentum megőrzése olyan módon történjen, **amely védi az elektronikus dokumentumot a törlés, a megsemmisítés, a véletlen megsemmisülés, az utólagos módosítás és sérülés, valamint a jogosulatlan hozzáférés ellen.**

(2) A megőrzésre kötelezett köteles biztosítani, hogy az őrzött elektronikus dokumentum értelmezhetősége, olvashatósága - például a dokumentum megjeleníthetőségét lehetővé tevő szoftver- és hardverkörnyezet biztosításával - a megőrzési kötelezettség időtartama alatt megmaradjon._

Lehet, hogy szegényes a fantáziám, de elképzelni sem tudok olyan megoldást ami egyszerre megfelel ezeknek a feltételeknek. Ráadásul ugye a legkisebb EV-től a legnagyobb multi-ig mindenki fogadhat(na) be, vagy bocsáthat(na) ki ilyen egyszerű módon elektronikus számlát, tehát elfogadható költségszintű megoldás kellene. Van ilyen?

**Comment by nbeeps2** [comment]
> Én amikor elkészült a számla, akkor a PDF fájlt mentem az adatbázisba egy blob fieldbe a hash-el együtt. Így a fájlt nem kell újragenerálni, csak "elővenni" a blob field-böl, így a hash kód nem változik.

Adatbázisban PDF fájlt tárolni szerintem nem optimális, pláne évi több tízezer számla esetén.

**Comment by nbeeps2** [comment]
"> A PDF állományt a hash kóddal együtt kell az adózónak megőriznie"
Ezt értem, és kérem szépen, hogy most hagyjuk ezt a rendelet szöveget, hanem a gyakorlatból induljunk ki. A felhasználó használ egy offline számlázó programot, ami szépen a NAV Online számla adatszolgáltatáson keresztül gyártja az e-számlákat hash lenyomattal, meg minden. Ezeknek az embereknek nincs szervere, nincs több gépe, 1 gépük van, egyáltalán nem értenek a számítástechnikához, fel sem tudják mérni, hogy mi fán terem egy fájl és egy mappa, csak használnak egy programot, valószínűleg azzal sincsenek tisztában, hogy mi az az e-számla. Nincs is ezzel baj, ezeknek az embereknek saját szakmájuk van, nem programozók, nem adószakértők és nem navellenőrök. Csak végzik a munkájukat, számláznak, szépen meg is őrzik a gépükön a PDF-et és a hash kódot, aztán "PUKK": valami történik, elveszik minden. A papír alapú számlázásnál ez nem volt gond, ugyanúgy elveszett minden, de meg voltak a számlák papíron így nem volt gond. Az elektronikus számlánál hogy van ez? És ne feledkezzünk meg arról, hogy van DONE adatszolgáltatás, tehát elvileg a NAV-nál meg van a számla. Sőt, a példámban a programból volt mentés, tehát a számla előkép is legenerálható, csak éppen a hash nem valószínű, hogy megegyezne a beküldött hash-el. Erre kérnék szépen választ, mert az előző válaszban jóformán csak az volt leírva, hogy ez nem lehetséges, mert az adózónak ez meg az a kötelessége, de ez nem egy gyakorlati megközelítés.

**Comment by nbeeps2** [comment]
Amúgy arra is jó lenne a válasz, hogy minek egyáltalán PDF, minek egyáltalán HASH kód, onnantól kezdve, hogy a számla bemegy a NAV-hoz és érvényes adatszolgáltatás van rá, úgy már eleve biztosított az adat módosíthatlansága és sértetlensége. Ha a NAV-nál felmerül, hogy a vevő valami manipulált a számlával, nincs más dolga, mint a beküldött adatszolgáltatást ellenőrizni, ilyen formán az e-számlázás már önmagában szerintem azzal megvalósul, hogy megtörténik a NAV-nak való adatszolgáltatás és ehhez sem PDF, sen HASH kód nem (lenne) szükséges.

**Comment by szabogab** [comment]
nbeeps2 comment-jét tovább gondolva:
ha már bent van xml, akkor már csak az olvashatóságról kellene gondoskodni és szerveroldalon csak a számlaképet előállítani.
Ezt egy újabb webservice funkcióval bővítve le lehetne kérni vevőnek - eladónak egyaránt.
NAV Szerver oldalon Java-ban megfogalmazva: jaxb binding+ xsd segítségével elemeznék a beküldött xml-t és itext-vel megformázva lekérhető lenne a számlakép.
Request paraméter a számlaszám, Response pedig egy pdf lenne.
Nem is kellene tárolni a pdf-t a szerveren, hisz a beküldött xml-ből kérésre bármikor a szerver újra generálhatná.
