### ISSUE TITLE
Számlakép továbbítás sztenderdizálása / támogatása

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#212]
Tisztelt Kollégák!

Az elektronikus számla sha256 lenyomatának beküldése nagy előrelépést jelent a papírmentes számlázás elterjedése szempontjából.

A megoldás terjedéséhez jelentősen hozzájárulna, ha nem csak a lenyomat lenne beküldhető a NAVhoz, hanem maga a számlakép is. Még az év elején beszéltem erről NAVos kollégákkal és akkor azt a választ kaptam, hogy nincs a NAVnak kapacitása arra, hogy ilyen mennyiségű adatot tároljon.

Az akkor a kollégáknak felvázolt elképzelésem szeretném itt most írásban rögzíteni, hátha elfogadható a javaslat és megvalósításra kerülhet a közeljövőben.

A küldési utak egységesítése / egyszerűsítése / egyértelműsítése szempontjából már az is nagy segítség lenne, ha a számlaképet a NAV befogadná és csak limitált ideig (5-10-15 nap tárolná), mert aki automatizmust épít a számlaadatok letöltésére az a hozzá beérkező számla adatokat úgyis ütemezetten kéri le és ekkor egyből a számlaképet is lekérhetné, segítve ezzel az iratmegőrzési és adatrögzítési teendőket.

Amennyiben preformancia problémákat okozna a számlakép beküldése a normál API-n keresztül, úgy akár az is tökéletes megoldás lenne, ha a DONE/WARNING üzenet után a számlaszámra hivatkozva lehetne egy másik API-n keresztül küldeni a számlaképeket.

Fogadó oldalon így lehetőség nyílna a számlakép befogadására és a hash automatikus ellenőrzésére is teljesen automatikusan.

Köszönöm!

**Comment by NTCA-tax** [comment]
Köszönjük a javaslatot!

Jelenleg az elektronikus számlázás támogatásaként abban gondolkodunk, hogy magát az adatszolgáltatást hogyan lehetne elektronikus számlának tekinteni. Ehhez látunk megoldási lehetőségeket a következő verzióban. A jelenlegi szakmai elgondolásoknál mi nem a számlakép, hanem egy XML alapú elektronikus számla irányába indultunk el. Az XML dokumentumot emberi szem számára is olvasható módon meg lehet jelenteni megfelelő szoftverrel, de maga az elektronikus számla a teljes számla adattartalmú XML állomány lenne.

**Comment by Macskafarka** [comment]
Nagy kérés lenne, hogy számlabefogadó oldalon **mindazokat a mezőket le lehetne kérdezni, amelyeket be lehet küldeni?** 
Ezzel segíthetnénk a könyvelőket a számla befogadásában, értelmezésében. Több ilyen mező is kellene, pl. ilyen az additionalLineData mező is.

**Comment by omachtandras** [comment]
> 
> 
> Köszönjük a javaslatot!
> 
> Jelenleg az elektronikus számlázás támogatásaként abban gondolkodunk, hogy magát az adatszolgáltatást hogyan lehetne elektronikus számlának tekinteni. Ehhez látunk megoldási lehetőségeket a következő verzióban. A jelenlegi szakmai elgondolásoknál mi nem a számlakép, hanem egy XML alapú elektronikus számla irányába indultunk el. Az XML dokumentumot emberi szem számára is olvasható módon meg lehet jelenteni megfelelő szoftverrel, de maga az elektronikus számla a teljes számla adattartalmú XML állomány lenne.

Kedves NTCA-tax!

Köszönöm a választ. Részleteket nem ismerve a tervezett koncepcióra nem tudok reagálni, hosszabb távon mindenképp üdvözítő lenne, ha elfelejthetnénk akár a pdf számlaképet is, de jelen pillanatban - és azt gondolom közép távon is - a könyvelő szakma még biztosan nincs felkészülve ilyen mértékű változásra, így szerintem egy közbenső lépésként a pdf-ek "transzferjének" megoldása óriási segítség lenne abban, hogy a gondolkodásmódot az elektronikus számla felé tereljük, és elfogadottságát/használatát növeljük.

**Comment by NTCA-tax** [comment]
@Macskafarka kérdésére a teljes XML-t (additional elemekkel együtt) a QueryInvoiceDataResponse invoiceDataResult/invoiceData eleme tartalmazza.

@omachtandras javaslatát köszönjük, a következő verzióban megfontoljuk ezt a felvetést.

**Comment by omachtandras** [comment]
Kedves NTCA-tax!

Felvetnék még egy átgondolandó problémakört a következő gondolattal kapcsolatban:
"Az XML dokumentumot emberi szem számára is olvasható módon meg lehet jelenteni megfelelő szoftverrel, de maga az elektronikus számla a teljes számla adattartalmú XML állomány lenne."
A számlaképek nagy részére igaz, hogy az xml-ből megjeleníthető (ha eltekintünk olyan apróságoktól, hogy valaki szeretné a logóját megjeleníteni rajta, esetleg az akciós termékeit is reklámozza a végén, vagy bármi más információt szeretne közölni az ügyfelével), van azonban legalább egy speciális terület ma Magyarországon, ahol a számlakép tartalmára vonatkozóan rengeteg egyedi előírás van, amit átadni az xml-ben nem lehetséges, ez pedig a közüzemi szolgáltatók részére előírt egyedi "rezsicsökkentéses" számlakép.
Az érintett szektorok mind számla mennyiségében, mind ügyfélkörében igen jelentős tényezői a magyar gazdaságnak, az általuk előállított számlák szinte minden gazdálkodó szervezethez eljutnak, így ha abban gondolkodunk, hogy esetleg támogatni szeretnénk a papírmentes számlázást, akkor arra is gondolni kell, hogy ha nem az általuk előállított pdf-et csatornázzuk tovább, akkor képesek leszünk-e megjeleníteni a kapott adatokból a törvény által elvárt számlaképet.
