### ISSUE TITLE
[FEATURE] Több fizetési határidő és hozzájuk fizetendő összeg megadása

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#213]
Tisztelt Kollégák!

Érdeklődnék, hogy tervben van-e bővített fizetési határidő megadhatóság. A jelenlegi fizetési határidő megmaradhatna, ezt nem lenne érdemes módosítani, a legtöbb esetben egy fizetési határidő van.
Vannak azonban olyan iparágak (pl. építőipar - jóteljesítési garancia), amelyeknél 2-3-4 részletben történik a fizetés az előre megállapodottak szerint.
Ennek ábrázolására egy 0..n elemű fizetendő összeg + fizetési határidő (+ esetleg egy szöveges mező, ami leírja az esedékesség okát) struktúra megfelelő lenne.

Köszönöm!

**Comment by NTCA-tax** [comment]
Eddig ilyen igény nem merült fel. A fizetési határidő nem áfa törvény szerinti kötelező adattartalom, de adatszolgáltatásban helyet biztosítottunk erre. Jelenleg a több fizetési határidőt additionalData-ként lehet az adatszolgáltatásban feltüntetni.

Ugyanakkor a javaslatot köszönjük, átgondoljuk a következő verzió tervezésénél.
