### ISSUE TITLE
[Q&A]/queryTransactionStatus hiba?

### ISSUE THREAD

**Issue by tkelemen73** [nav-gov-hu/Online-Invoice#214]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Sziasztok,
egy érdekes dologgal találkoztam, aminek úgy gondolom, hogy nem szabadna működnie, vagyis hibára kellett volna futnia.
Indítottam egy tranzakció státusz lekérdezést a 2SS157EO9DL4TR6X tranzakció azonosítóra, RequestID száma: ABIFNPZ7O4POVI432X7VWDEYBA, amire a invoiceStatus ugyan nem jött vissza, de a RESULT-ban egy OK szerepel, üzenet semmi. A probléma ezzel csak az, hogy olyan technikai userrel/adószámmal indítottam a lekérdezést, akinek semmi köze nincs a 2SS157EO9DL4TR6X tranzakció azonosítóhoz, sem vevőként, sem szállítóként nem szerepelt a számlában, mégsem adott hibaüzenetet, hogy nem megfelelő adószámmal akarok lekérdezni. Nem adja vissza a tényleges státuszt, így adatbiztonságilag ok, de úgy gondolom, hogy ez egy nem lekezelt ág lehet a szolgáltatásban, a hibakezelés ágban.
Üdv
T.

**Comment by NTCA-developer** [comment]
Szia @tkelemen73 

Köszönjük a jelzést, de ez by-design az indulás óta így van. Ennek az oka, hogy bár szerver oldalon objektíven megkülönböztethető a 2 eset (az objektum nem létezik || az objektum létezik, de a hívó nem férhet hozzá) ezeket a külvilág felé nem fedjük fel. Tehát nem áruljuk el az ilyen próbálkozóknak azt sem, hogy sikerült eltalálnia egy olyan transactionId-t a kérésben, ami egyébként létezik csak neki semmi köze hozzá. (ahogy te is írod) Ezek belül szépen ki vannak logolva, de kifelé nincs látható különbség, ezért gondolhattad hogy ez egy nem kezelt ág, pedig pont az ellenkezője az igaz. Az interfész dokumentáció alábbi része ki is tér erre a jelenségre: 

> 1)	Ha az adózónak nincs a lekérdezési feltételeknek megfelelő adatszolgáltatási tranzakciója, a szolgáltatás csak egy <funcCode>OK</funcCode> üzenetet ad vissza.

Ugyan ezt a működést láthatod akkor is, amikor a /queryInvoiceData-ban számla adatot kérdezel le. Ez egy fontos safe REST API alapelv hogy így működjünk.

Majd zárd le kérlek a ticketet ha nincs több kérdésed!

**Comment by tkelemen73** [comment]
Köszönöm, zárom.
