### ISSUE TITLE
ABORTED számla [DEV support]

### ISSUE THREAD

**Issue by era910413** [nav-gov-hu/Online-Invoice#215]
A mai napon a teszt rendszerben elutasításra került egy számlánk, az INVOICE_NUMBER_NOT_UNIQUE error code-al, tehát mintha már beküldtük volna az adott számlát.
A saját rendszerünk logjaiban egyértelműen látszik, hogy mikor visszakaptuk ezt a hibaüzenetet, akkor nem volt még beküldve a számla (utána valóban megpróbáltuk újra):
RequestID: BGS97A202005044073838
Tranzakció azonosító: 2YE01TC8VHHQ00IR

Mivel szerintünk nem lett duplán beküldve, így a webes felületen rákerestünk a számlaszámra, és ott az alábbi tranzakció azonosítóval található meg a számla:
2YDZURZTXOQ0TZOX

Viszont ilyen azonosítót mi nem kaptunk vissza.. a rendszerünkben ennek nyoma sincs.

Esetleg megnéznék, hogy mi lehet ennek az oka?

**Comment by NTCA-developer** [comment]
Szia @era910413 

A teszt rendszeren ma 10-16 óra között ismét performancia teszt volt. A kérdéses számlabeküldés egybeesett a mi egyik olyan ablakunkkal, ahol a épp a világmindenség összes számláját küldtük be a rendszernek. A teszteseteink egy részének pont az volt a lényege hogy verjük be a fejünket a plafonba, ezért a mai napra nézve a külvilág kb 3,5 millió tranzakcióból 600 REST választ timeout miatt elvesztett. Szerintem a tiéd az egyik. Esetleg nézd meg, hogy nálad mi látszik a logból, mert ha rákeresek az általad említett transactionId értékekre, akkor azt látom, hogy:

transactionId: '2YDZURZTXOQ0TZOX', beérkezett: '2020-05-04 11:13:30', requestId: 'BGS97A202005044040973'
transactionId: '2YE01TC8VHHQ00IR', beérkezett: '2020-05-04 11:18:58', requestId: 'BGS97A202005044073838'

Erre az 5 perccel korábbi **BGS97A202005044040973** requestId-re te mit látsz? Azt nem néztem meg hogy ezekben a tranzakciókban milyen számla érkezett, de elvileg ez volt az a beküldés amire te nem kaptál választ, de mégis bement. (Kvázi előidéztük ugyan azt, ami az élesen is előfordult már párszor, ez is a cél)

**Comment by era910413** [comment]
Szia!

Igen, közben megtaláltuk. Tehát a BGS97A202005044040973 requestId-val próbáltuk küldeni először, viszont akkor 504 Gateway Time-out üzenet jött vissza.
Tehát a rendszerünk automatikusan beküldte újra a számlát, az pedig ahogy láttad elutasításra került.

Akkor ez azt jelenti, hogy a timeout esetében is feldolgozásra került a számla.. 
Igaz ilyen nem lesz a jövőben? :) 

Köszi hogy utánanéztél!

**Comment by NTCA-developer** [comment]
Szia!

Ezt nem lehet 100%-ra kijelenteni. Volt erről a témáról egy beszélgetés már itt, aminek az lett a kimenetele hogy elérhetővé tettük a tranzakció listázást az API alatt is. Ily módon ha elveszik egy válasz, akkor időalapon szűrve a listát meg lehet állapítani, hogy van-e számodra ismeretlen transactionId, és ha igen akkor az alatt milyen számla van. Ezt itt találod:

https://github.com/nav-gov-hu/Online-Invoice/issues/78

A 2.0-ban ebben az esetben - referencia implementáció szerint - már nem automatikusan újra kellene küldeni a számlát, hanem előbb listázni a tranzakcikóat és az összevezetés után dönteni arról, hogy a számla sikeresen bement-e és csak a válasz veszett el, vagy pedig meg kell ismételni magát a beküldést is. Ha megbízhatóan megőrzöd a requestId-ket, akkor a saját véleményem szerint mindkét esetben teljesül az adatszolgáltatás az azonnalisági feltétele, még akkor is, ha a számla a megismételt adatszolgáltatásban kerül csak be a rendszerbe.

**Comment by szako** [comment]
Ehhez kapcsolódna egy kérdésem: a webes felület _Interfész napló lekérdezése_ funkciójának kiajánlása interfészbe nincs tervben? Sajnos csak most jött szembe velem ez a funkció, mert a webes résszel ritkán találkozom, nem használom gyakran. "Elveszett" tranzakció megszerzésére ideális lenne. Tisztában vagyok azzal, hogy fejlesztésre került az időalapú lekérdezés, azt köszönjük!

**Comment by NTCA-developer** [comment]
Szia @szako 

Két dolgot tudj az interfész naplóról: a mentés benne nem tranzakcionális és nem is perzisztens. Ez azt jelenti, hogy amikor bejön a kérés akkor abban a feldolgozás részeként külön szálon elindítjuk az interfész naplóba mentést, de ha az egyébként sikertelen (pl nem érhető el a DB, vagy betelt a disk, ugyanis kvóta van), akkor annak semmilyen hatása nincs az eredeti beküldéses tranzakcióra. Számodra ez azt jelenti, hogy a valóságban történtekhez  képest vagy megtalálod a keresett tranzakciót az interfész naplóban vagy nem, de ha nincs benne akkor az nem biztos hogy azért van, mert nem is történt meg. Ez az egyik oka, ami miatt nem gondolkodtunk azon hogy ez a funkció API-ból is elérhető legyen.

A másik ok, hogy az API-s használhatósághoz olyan robosztusságot kellene a funkció mögé tenni, amit nem vállaltunk infra oldalon. Ugye minden requrest-response párt logolni kell a teljes payloaddal, ami azért naponta alaphangon több GB. Ezért az interfész napló rotálva is van, alapesetben 5 napig őrzünk egy tranzakciót, de ha jobban pörög akkor lehet hogy már 3 nap múlva sincs meg az adat.

Ezt a funkciót nem API-ra terveztük, sokkal inkább arra, hogy a fejlesztők - ha az ügyfél odaengedi őket - akkor az éles környezetből debugolhassanak, mi romlott el. Ez jó nekünk, jó az ügyfélnek és könnyebbség a fejlesztőnek, hiszen az éles adat szabályozottan elérhető, ráadásul online, nem kell kimenni adathordozóért helyszínre, felhőbe feltölteni éles üzleti adatot stb.

**Comment by szako** [comment]
@NTCA-developer Köszi a részletes választ, megválaszoltál mindent.

**Comment by era910413** [comment]
Köszönöm én is a visszajelzéseket!

**Comment by szako** [comment]
@NTCA-developer: Csak egy kérdés még: a queryTransactionList operáció vissza tudná adni a hívás requestId-jét? Így rögtön egyértelműen meg lehetne határozni, hogy melyik híváshoz kapcsolódott, nem kellene "találgatni". A találgatás alatt azt értem, hogy ahol nagyon nagy számlamennyiség megy be rövid időn belül, ott azért nem teljesen egyértelmű a beszúrási időpont alapján, hogy melyik manageInvoice híváshoz tartozott. Köszi!

**Comment by era910413** [comment]
Igaz nem hozzám irányult a kérdés, de nálunk pl. ez nem probléma, mivel a naplózásból egyértelműen látszik, hogy melyik híváshoz kapcsolódott. Direkt logolunk mindent, hogy utólag egyszerű legyen visszakeresni a hibákat...
Nem tudom, hogy nálatok ez mennyire megoldott, de egyértelműen biztosabb így az adatszolgáltatás.

**Comment by szako** [comment]
@era910413 Teljes naplózás van, ezzel nincs gond. Az ilyen jellegű hibák javítása jelenleg csak kézi beavatkozással lehetséges, miszerint a felhasználó (/adminisztrátor/kezelő/stb.) eldönti, hogy adott hiányzó tranzakció megvan-e a NAV rendszerében vagy nincs. Ehhez vannak API alapú segítségek, ami félig-meddig automatizálják a javítást. Szeretnénk a teljes automatizációt, erre keresünk most megoldási terveket. Az újraküldéses-teszteléses technikát elvetettük korábban a másik oldal aszinkron feldolgozási módja miatt.
