### ISSUE TITLE
[DEV support] - Token exchnage kérés hiba

### ISSUE THREAD

**Issue by kharonx** [nav-gov-hu/Online-Invoice#216]
Sziasztok!

Az 1.2-ben jól működő tokenrequestet futtatva (a megfelelő módosításokkal), ezzel a requestel (kitöröltem/átírtam az egyedi részeket):

<?xml version="1.0" encoding="utf-8" ?>
<TokenExchangeRequest xmlns="http://schemas.nav.gov.hu/OSA/2.0/api">
    <header>
        <requestId>DFVjyJlQqcHjwow</requestId>
        <timestamp>2020-05-04T16:37:24.000Z</timestamp>
        <requestVersion>2.0</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
    <user>
        <login>technikailogin</login>
        <passwordHash>2ECA................F173</passwordHash>
        <taxNumber>..............</taxNumber>
        <requestSignature>..............</requestSignature>
    </user>
    <software>
        <softwareId>HUAPPNEVE10317</softwareId>
        <softwareName>Appneve</softwareName>
        <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
        <softwareMainVersion>10.0.354</softwareMainVersion>
        <softwareDevName>Mivagyunk</softwareDevName>
        <softwareDevContact>support@email.hu</softwareDevContact>
        <softwareDevCountryCode>HU</softwareDevCountryCode>
    </software>
</TokenExchangeRequest>

Ezt a response -t kapjuk:

<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<GeneralExceptionResponse xmlns="http://schemas.nav.gov.hu/OSA/2.0/api" xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/data">
    <funcCode>ERROR</funcCode>
    <errorCode>OPERATION_FAILED</errorCode>
    <message>Érvénytelen kérés!</message>
</GeneralExceptionResponse>

(.net 4.6, vb.net, win10)

Tudnátok segíteni? 
Köszönöm előre is!

**Comment by NTCA-developer** [comment]
Szia @kharonx !

Nekem határozottan úgy tűnik, hogy magával a requesttel szintaktikailag semmi baj sincs, az egyetlen probléma hogy rossz végpontra küldöd. Ez a requestId amit írtál a /manageInvoice végpontra érkezett, próbáld a /tokenExchange-re küldeni.

**Comment by kharonx** [comment]
Köszönöm, ez hol mászhatott el ... :)

**Comment by NTCA-developer** [comment]
Akkor hallgatólagos engedelmeddel ezt most lezárom. Ha a probléma még mindig fennáll akkor nyisd újra vagy vegyél fel újat nyugodtan.
