### ISSUE TITLE
[Q&A] Tételes áfakerekítés

### ISSUE THREAD

**Issue by kaptast** [nav-gov-hu/Online-Invoice#217]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Sziasztok,

A következő problémával találkoztam:
Adva van egy számlám, 10 tétel, tételenként 1 db. mennyiséggel,  egységár 6,45 Ft. Kerekítéssel tételenként a következő adatok számolódnak:
Nettó : 6 Ft
Áfa: 2 Ft
Bruttó: 8 Ft

Szummázva a 10 tétel:
Nettó : 60 Ft
Áfa: 20 Ft
Bruttó: 80 Ft

Edit:
**Ez több online számlázóban is így számolódik!**

Beküldés után a következő Warning üzenetet kapjuk:
"WARN - Az áfa-mértékhez tartozó nettó összegből és az alkalmazott adó mértékből számított áfaösszeg forintban eltér a forintban feltüntetett áfaösszegtől.  - INCORRECT_SUMMARY_CALCULATION_VAT_RATE_VAT_AMOUNT_HUF_SUMMARY"

A kérdés: **Van-e teendő ezzel kapcsolatban?**

Amennyiben egy előleg számlát állítottam ki a rendelésemhez (Ugyanez a 10 tétel). Az előleg mértéke 90 %, ami egyetlen előleg sorban jelenik meg az előleg számlán. A 90 % a rendelés összértékéből számolódik: 
Nettó: 0,9 * 60 Ft
Áfa: 0,9 * 20 Ft
Bruttó: 0,9 * 80 Ft
**Ezek az értékek lesznek megadva az előleg számla egyetlen tétel sorában. Természetesen ez rögtön warning üzenettel tér vissza. Milyen megoldást javasolnak erre a problémára?**

Köszönettel

**Comment by Rossi73** [comment]
Egy kérdés: Ha egy termék nettó egységára tört szám, akkor az helyes eljárás, ha minden tételt kerekítünk? Nem elegendő az, ha a számla végösszegét kerekítjük? Így ugyanis akár több forintnyi eltérés lehet mind a nettó, mind az áfa, mind a bruttó árakban. Vagy mindkét eljárás helyes?

**Comment by betasofthu** [comment]
Szerintem a tételeknél nem szabad kerekíteni sem az áfa sem a bruttó összeget. Két tizedest érdemes használni. Ha euróban számlázol, akkor szükség lehet 3 tizedesre is a kerekítési eltérés minimalizálására. A fenti példán nem ellenőriztem le az online számlázót, de az már az első pillanatban feltűnt, hogy mindenhol két tizedest használ, a számla nettó, áfa, bruttó összesenjénél is.   Neki van igaza! Az egészre (forintra) kerekítés nincs előírva. A köztudatban az van, hogy a számla áfa értékét forintra kell kerekíteni. Erre nincs jogszabály, én kerestem, nincs.

**Comment by Macskafarka** [comment]
A feltett kérdés valós, engem is érdekel a válasz.
"betasofthu" által leírtakra: pontosan fogalmaztál, a 3 tizedes csak "minimalizálja" a probléma **előfordulását**, de a probléma elvileg akkor is fennáll.
Megerősítem: nincs jogszabályi előírás a kerekítésre.
A tételsor kerekítés kérdésköréhez  annyit tennék hozzá, hogy a tételsornak önállóan meg kell állnia a helyét, mert később a tételsort önállóan lehet módosítani a rá történő hivatkozással.

**Comment by nbeeps2** [comment]
Amit "kaptast" írt az teljesen való és HELYES, mint számlázás és az sem kell hozzá, hogy az egységár tört legyen. Legyen csak simán 6 Ft a nettó. Teljesen értelmes, hogy nem akar tizedesekkel bajlódni, minek is, hiszen a fillér megszűnt és nem kötelező fillérrel számolni. Tehát A 6 Ft-nak kerekítve 2 Ft lesz az ÁFA-ja és a bruttó 8 Ft lesz. Ezt a NAV-nak le kell tudni kezelnie! A WARN téves! A számla tételeinél hárítjuk/számoljuk fel az ÁFA-t, több tétel esetén a felszámított összegeket kell összeadni, tehát 10x6= nettó 60 Ft, 10x2= áfa 20 Ft, nettó+áfa=bruttó vagyis 80 Ft. Vagyis az ÁFA-t nem a végén számoljuk úgy, hogy a 60 Ft-ból számolunk 27%-ot (16 Ft), mivel az nem felelnek meg a tételesen felszámolt/áthárított számlán látható ÁFA összegeknek 16 Ft<>20 Ft.

**Comment by NTCA-tax** [comment]
A forint-fillér, a tizedesjegyek száma kérdés nagyon hosszúra vezetne, de nem is ezekben a részletekben szeretnék elveszni. A lényeg az, hogy bármely megoldás megfelelő, amennyiben matematikailag megfelelő módszert alkalmaz a számlázó program. Amennyiben a kerekítés megfelelő, akkor nagyjából ugyan akkora arányban kell a programnak felfelé és lefelé kerekítenie. Tehát a kerekítés nem tendenciózus, nem merül fel adóeltitkolás gyanúja.

A @kaptast által idézett warning üzenetnél van egy olyan algoritmus, mely a kerekítés hatását PRÓBÁLJA kiszűrni. Ezt az algoritmust mindig próbáljuk finomítani, ugyanakkor előállhat olyan szélsőséges helyzet, hogy akkor is jelez, amikor nem kellene. Amennyiben ténylegesen kerekítésből származik az eltérés, akkor nem szükséges ezzel a warninggal foglalkozni.
