### ISSUE TITLE
[Q&A] Korábbi számlák törlése teszkörnyezetből

### ISSUE THREAD

**Issue by KunSz** [nav-gov-hu/Online-Invoice#218]
Lehetséges-e az összes számla törlése a tesztkörnyezetben: https://onlineszamla-test.nav.gov.hu/login.
Júniusban szeretnénk elkezdeni a tesztkörnyezetben a számlák beküldését, de ehhez a korábbi számlákat ki akarjuk törölni, mert egyedi számlaszámra van szükség.

**Comment by NTCA-developer** [comment]
Szia @KunSz 

Ez már több ízben felmerült és mindig azt válaszoltuk, hogy nem biztosítunk ilyen lehetőséget. Ha egyediségre van szükségetek, akkor a régi számláitok tömeges technikai érvénytelenítése biztosítja ezt számotokra a teszt környezetben. De mi központilag ilyet nem csinálunk.

Majd kérlek zárd le ha nincs több kérdésed!
