### ISSUE TITLE
[FEATURE]Számla exportálás .xml formátumban

### ISSUE THREAD

**Issue by pezso75** [nav-gov-hu/Online-Invoice#219]
Sziasztok,

Jelenleg az Online számla felületen csak formázott Excel fájlba lehet a számla adatokat exportálni (bejövő-kimenő egyaránt). Nagy szüksége volna pl. a könyvelőirodáknak arra, hogy a számlákat .xml formátumban is le tudják tölteni. Ez nagyban megkönnyítené a könyvelői munkát, mert számos könyvelőprogram már tudja fogadni, importálni ezeket az .xml állományokat.

Köszönettel.

**Comment by NTCA-developer** [comment]
Szia @pezso75 

A 2.0-ás API-ban a kimenő és a bejövő számlák is lekérdezhetők, ezeknek a formátuma mindig XML. Azt kérlek fejtsd ki hogy erre a funkcióra miért van okvetlenül a felületen szükség, miért nem jó ha a használt számlázóprogramból lehet ezeket kinyerni? Szerintem egyszerűbb mint egyesével kézzel betallózni a könyvelőprogramba a fájlokat.

**Comment by pezso75** [comment]
Szia,

A számlázóprogramok bármelyikéből a könyvelők a cégek vevő (kimenő) bizonylatait valóban tömegesen ki tudják nyerni xml formátumban. Ezzel már most sincs probléma.
A könyvelt cégek szállító (bejövő) bizonylatai azonban különféle számlázó programokban, vagy kézi számlatömbben készülnek jelenleg. Nem jellemző az az eset, hogy az adott cég ugyanabból a számlázó programból állítja ki a vevő (kimenő) számláit, mint amiben a partner cégeinek mindegyike is kiállítja a saját bizonylatát (pl. számlázz.hu).
A könyvelőirodák ügyfelei a különböző számlázóprogramokkal dolgozó partnereiktől a szállító (bejövő) bizonylatokat nem kapják meg elektronikus formában. Éppen ezért van szükség arra, hogy az Online számla felületen a különböző számlázó programok által generált szállító (bejövő) bizonylatok xml-ben is letölthetők legyenek a könyvelők számára.  Jelenleg is lehetőség van tömeges exportálásra a felületen, de nem xml-ben.
Igazából kérésemnek a sokféle számlázóprogramban előállított szállító (bejövő) bizonylatok tekintetében van komoly jelentősége, mert ha le lehetne ezeket a szállító (bejövő) bizonylatokat xml-ben tölteni, a könyvelőknek nem kellene kézzel rögzíteniük, vagy egyéb drága megoldással beolvasniuk a szállító (bejövő) számlák adattartalmát.

**Comment by pezso75** [comment]
Előző kommentemet kiegészítem még azzal, hogy a könyvelőknek igazán két dologra van szükségük az Online számla felületről:
1. a számlázóprogramok által beküldött adatok szabványos .xml állományaira,
2. a számlák (kimenő és bejövő) számlaképeire.

A jelenleg a felületről elérhető formázott Excel állománnyal nem tudnak mit kezdeni.

**Comment by omachtandras** [comment]
Kedves pezso75!

1. Ahogy NTCA-developer jelezte, a szállító oldali (bejövő) számlák xml adatai is lekérhetőek az API-n keresztül, amennyiben a partner által beküldött xml-ben az adószámunk (mint vevői adószám) szerepel.
Ez a része pipa a 2.0-s interfacetől.

2. Erre vonatkozóan volt egy javaslatom és érkezett is rá válasz: https://github.com/nav-gov-hu/Online-Invoice/issues/212

**Comment by pezso75** [comment]
Sziasztok,

Köszönöm szépen válaszaitokat. Bocs, hogy tovább kérdezek, de könyvelőirodaként kevés információnk van a technikai, funkcionális részleteket illetően.

Ezek szerint az interfész kapcsolat most már lehetővé teszi a lekérdezést, és ha az adatok tartalmazzák a felek adószámait, akkor hozzá lehet jutni a bejövő számlákhoz is xml formátumban.
Vajon a számlázóprogramok mindegyike képes lesz (kötelezően képessé kell tenni?) arra, hogy a felhasználója által is elérhető lekérdező funkcióval visszakérje pl. az adott adószámot tartalmazó számlák (akár bejövő vagy kimenő) adatait függetlenül attól, hogy a számla milyen számlázó szoftverrel került kiállításra? A visszakért adatokat exportálni is lehet majd minden programból .xml formátumban?
Amennyiben igen, akkor rendben van, mert a könyvelők el tudják majd kérni az ügyfeleiktől az általuk használt számlázóprogramból lekérdezett bejövő/kimenő számlák .xml állományait.
Amennyiben nem fogja minden számlázóprogram tudni ezt a paraméterezhető lekérdezési, exportálási funkciót, akkor viszont a könyvelőknek máshonnan kell hozzájutni az adatokhoz, pl. kézenfekvő, hogy az Online számlázó felületről.

**Comment by fenyvessy** [comment]
Kedves pezso75,

Szerintem nézd egy picit más szemszögből és távolabbról: ha a könyvelőprogram fog tudni csatlakozni a saját technikai felhasználójával az API-n keresztül, azaz magában a könyvelőprogramban van megvalósítva az a funkcionalitás, hogy közvetlenül lekérje akár az adott cég nevében kiállított, akár az adott cég részére kiállított számlák adatait XML formátumban, akkor talán még arra sincs feltétlenül szükség, hogy a számlázóprogram exportálja az adatokat és az ügyfél küldözgesse át ezeket a könyvelőnek   :)

**Comment by pezso75** [comment]
Kedves Bela FENYVESSY,

Valóban az általad felvetett megoldás az optimális, ez minden korszerű könyvelő iroda "álma". Talán a könyvelőprogramok fejlesztői is gyorsan reagálnak majd erre az igényre.

**Comment by pezso75** [comment]
Sziasztok,

Saját fejlesztésben próbálunk meg interfészt készíteni a könyvelőprogramunkhoz annak érdekében, hogy az ügyfelek számláit a 2.0 API segítségével vissza tudjuk kérdezni. A tesztek eredménye alapján arra következtetek, hogy a fejlesztett programot nyilvántartásba kell vetetni ahhoz, hogy az API-val kapcsolatot tudjon létesíteni (softwareId stb.). Tudja valaki, hogy mi ennek a regisztrációnak a módja (pl SZAMLAZO nyomtatvány elég hozzá, vagy valami más úton kell kérvényezni)?

**Comment by clapygeza** [comment]
Szia! Nem kell a programot regisztráltatni (annak adatait a request tartalmazza ), viszont minden egyes könyvelt ügyfélnek technikai felhasználót kell regisztrálni az onlineszamla.nav.gov.hu oldalon. Ha ezeket az adatokat megadja Nektek, akkor azzal tudod az adott ügyfél számláit lekérni. (Tehát lekérdezés előtt adószám alapján valami táblából beolvasod a technikai felhasználó kódját, a jelszó hash-t, aláírókulcsot, xml cserekulcsot és ezekkel állítod össze a request-et ) Úgy nem működik, hogy a könyvelői iroda meghatalmazottként kérje az összeset.

**Comment by pezso75** [comment]
Kedves clapygeza!

Nagyon köszönöm a gyors választ!

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezzel az issue-val kapcsolatban van még kérdés?

Köszi

**Comment by pezso75** [comment]
Szia,

Köszönöm, nincs kérdés.

Üdv
