### ISSUE TITLE
INVALID_REQUEST_SIGNATURE

### ISSUE THREAD

**Issue by kharonx** [nav-gov-hu/Online-Invoice#220]
Sziasztok,

2.0, ManageInvoiceRequest, CREATE, RequestSignature számításával akadtam el (VB.NET).
A token megvan, azon túljutottam.
A dokumentáció alapján úgy értettem, hogy a partiális hitelesitéshez van fűzve a CREATE majd az invoiceData BASE64-re kodolt része (1.2nél crc volt). Ezek után az egész sha3-512 -vel kódolva.
Kérlek mondjátok meg mit csinálhatok rosszul mert érvénytelen az aláírás.
Előre is köszönöm!

**Comment by NTCA-developer** [comment]
Szia @kharonx 

Azt javasolom, hogy az általad használt metodikát hasonlítsd össze ezzel, itt kommentekben szerepelnek a részeredmények is: https://github.com/nav-gov-hu/Online-Invoice/blob/master/sample/API%20sample/manageInvoice.xml

Ha ugyan ezzel a módszerrel csinálod a hash számítást, akkor javasolom hogy az interfész dokumentáció önellenőrzés részében kezd el számolni a részeredményeket kézzel, valahol ki fog jönni a hiba.

Most sajnos behatóan nem tudom megnézni amit küldtél, de gondoltam gyorsan válaszolok hogy addig is tudj haladni. Ha a probléma továbbra is fennáll akkor írj és megnézünk egy kérést közösen.

**Comment by NTCA-developer** [comment]
Szia @kharonx 

Sikerült megoldani vagy kell fennáll még a probléma? Lezárható a ticket?

**Comment by kharonx** [comment]
Szia, sajnos még fennáll. Igaz kevés időm volt erre, de most belevetem magam.
Jól értem-e:
A manageinvoicerequest -nél a requestsignature = hash3-512(requestid + timestamp + alairokulcs + CREATE+invoicedata) ?

**Comment by NTCA-developer** [comment]
Ez nem jó így.

hash(requestid + timestamp + alairokulcs + "CREATE"+ hash(base64(invoicedata)))

**Comment by kharonx** [comment]
dupla hash ? :) köszi, próbálom

**Comment by kharonx** [comment]
sikerült! pontosítom az erdetit:

hash3-512(requestid + timestamp + alairokulcs + (hash3-512("CREATE"+ hash(base64(invoicedata)))).toupper()).toupper()

**Comment by kharonx** [comment]
Akinek gondja lenne a c# -os sha3-512 -vel, annak segítségképpen:

Public Function hash_sha3_512(s As String) As String

        Dim hashAlgorithm = New Org.BouncyCastle.Crypto.Digests.Sha3Digest(512)
        Dim input As Byte() = Encoding.ASCII.GetBytes(s)
        hashAlgorithm.BlockUpdate(input, 0, input.Length)
        Dim result As Byte() = New Byte(hashAlgorithm.GetDigestSize - 1) {}
        hashAlgorithm.DoFinal(result, 0)
        Dim hashString As String = BitConverter.ToString(result)
        hashString = hashString.Replace("-", "")
        Return hashString

    End Function

BouncyCastle.Crypto -t használva

**Comment by NTCA-developer** [comment]
Igen, bocsánat elkapkodtam a választ, köszi a pontosítást. Majd azért a rend kedvéért - feltéve hogy támogatod a technikai érvénytelenítés indítását is a programodból - akkor próbálj rá a /manageAnnulment kérésre is, mert ott is hasonló a szisztéma, csak nyilván az index hashbe más csomópontot kell belefűzni.
