### ISSUE TITLE
Számlasorokban megjegyzés sorok küldése

### ISSUE THREAD

**Issue by DevRTR** [nav-gov-hu/Online-Invoice#221]
Sziasztok, 

partnerünk számlázó szoftveréhez fejlesztjük az online adatküldést.
A rendszerben egyes számlasorok (természetesen mennyiség és egységár) nélkül u.n. megjegyzés sorokat tartalmaznak, és ezek a sorok sorszámozásában benne szerepelnek., 
A kérdés az, hogy ezeket a megjegyzés jellegű számlasorokat be kell-e küldeni, vagy sem, ha nem, a sorok számozása hogyan szabályos az XML állományban, különös tekintettel az esetleges későbbi módosító tételekről történő sor visszahivatkozásra?
Összefügg-e ez a probléma az eredeti, (papír alapú ) számlaképpel való egyezőség előírásával?

Köszönöm a választ előre is.

**Comment by NTCA-tax** [comment]
Az adatszolgáltatás az áfa törvény szerinti kötelező adattartalomra vonatkozik. A megjegyzés sorok nem tudom pontosan milyen adatokat tartalmazhat. Amennyiben például az értékesített termék/szolgáltatás leírását, akkor a lineDescription mezőnek kellene ezt tartalmaznia.

A lineNumber az adatszolgáltatáshoz kapcsolódik, nem feltétlenül a számla tételsorszámozásához. A lineNumber esetén alapvető elvárás, hogy 1-től folyamatos legyen a sorszámozás. Amennyiben számla módosításnál lineNumber-re hivatkozol, akkor az adatszolgáltatás lineNumber-re kell hivatkozni.

**Comment by DevRTR** [comment]
Köszönöm, a válaszod hivatkozás része világos.

A megjegyzés sorokról pontosítanék:
Ezek a "megjegyzés" sorok (számlánként lehet akár több is, mint a terméket/szolgáltatást) tartalmazó sor, arra van használva, hogy az utána következő tényleges számlasort "magyarázza"
De az adatállományban számla sorként szerepelnek, mennyiség és érték nélkül.

Pl:
Sor: 1  
A következő szolgáltatás teljesítése megtörtént:
Sor: 2 
(tényleges számlasor):
szolg1, Szolgáltatás 1  2 óra
...
...

A lineDescription-ba a számlasor tételének,  -itt: Szolgáltatás 1- megnevezés tartalma kerül.
Én a magam feje után nem küldeném ezeket a megjegyzés sorokat, de megköszönnék egy ajánlást erre a kérdésre.
