### ISSUE TITLE
[Q&A] idézőjel és aposztróf használata az XML-ben

### ISSUE THREAD

**Issue by szamszara** [nav-gov-hu/Online-Invoice#222]
Sziasztok!

Azt szeretném megtudni, hogy az idézőjelet és/vagy az aposztrófot HTML kódra (& quot; & apos;) kell-e cserélni az XML-ben? (Az &<> karaktereket, gondolom igen.)

Köszönöm,
Zoli

**Comment by NTCA-developer** [comment]
Szia @szamszara 

Melyik XML-re vonatkozik a kérdésed, melyik séma írja le? (api/data/annul)? Mert gondolom a szerver oldali mentés miatt kérdezed.

**Comment by szamszara** [comment]
A v2/manageInvoice -ra küldött Data részben, pl. <customerName> tagben.

**Comment by NTCA-developer** [comment]
Szia @szamszara 

Igen, ha azt szeretnéd hogy lekérdezéskor jól jelenjen meg.
`"&" => "&amp;"
"<" => "&lt;"
">" => "&gt;"
"'" =>  "&apos;"
"\"" => "&quot;"`

**Comment by szamszara** [comment]
Köszönöm
