### ISSUE TITLE
[Q&A] Devizás tételek kerekítési eljárása

### ISSUE THREAD

**Issue by Zoller79** [nav-gov-hu/Online-Invoice#223]
NAV hibaüzenet: 
Eltérés a számla tétel eredeti pénznemben és forintban megadott nettó értéke között. (INCORRECT_LINE_CALCULATION_LINE_NET_AMOUNT_HUF) 

A dokumentáció szerint a 741. azonosítóval ellátott ellenőrzés adja a hibát, amely szerint:
„Figyelmeztet, ha a tétel nettó összege és a tétel forintban feltüntetett nettó összege eltér egymástól, figyelembe véve az alkalmazott árfolyamot.
lineNetAmount x exchangeRate <> lineNetAmountHUF
Tolerált eltérés: lineNetAmountHUF 1%-a, de legalább 1 egység”

Kerekítési gondok:
A programban a devizás számlák esetén az EUR összegek 2 tizedessel összeggel kerülnek feltüntetésre, míg a forintos összegek egész számra kerekítve szerepelnek a számlaképen. 
A fenti tizedes jegy mennyiséggel kerülnek beküldésre is. 

A számlánál alkalmazott árfolyam: 355,31 
A számlán 2 tételsor szerepel, de az alábbi sor miatt jön az üzenet:
mennyiség: 3 
egységár:          0,13 EUR                
nettó érték:       0,39 EUR              
áfa érték:           0,11 EUR             
bruttó érték:      0,50 EUR              

Ha a NAV ellenőrzésnél megfogalmazott feltételek szerint történne a Ft összeg számítás:
Nettó: 0,39 x 355,31=138,5709 kerekítve 139 Ft
Áfa: 0,11 x 355,31=39,0841 kerekítve 39 Ft

Ha most megnézzük az áfa és nettó arányát: 39/139=0,28057… 
Ez alapján 28% áfa került felszámításra forintban!

Ha másik oldalról nézzük: (nettó x áfa) 
139 x 27% = 37,53 
ez kerekítve is csak 38 Ft lenne. 

A kerekítési problémák miatt programunkban úgy lett ez megoldva, hogy első lépésként az áfa összege kerül megállapításra forintban, majd ebből számoljuk vissza a nettó összeget. Így kisebb eséllyel lesz gond a nettó összeg, áfa százalék, áfa összeg összefüggéssel. 
A példánál maradva: 
Áfa: 0,11 x 355,31=39,0841 kerekítve 39 Ft
Nettó 39/27 x 100=144,4444… kerekítve 144 Ft

Kérdések: 
- A fentiek alapján várható-e valami módosítás az ellenőrzésekben? 
- Ha nem történik módosítás, akkor milyen adatokat szolgáltassunk? Eltérhetnek-e az adatok a számlaképen látható adatoktól, ahol csak 2 tizedes jegy szerepel a devizás tételeknél és egész számok a Ft-os összegeknél (mivel a háttérben le van tárolva 4 tizedesjegyig minden adat)?
- Ha módosítjuk a programban a HUF összeg számítást, akkor a fenti példánál maradva 28% áfa esetén nem lesz gond az ellenőrzéseknél?  

Válaszukat előre is köszönöm!

**Comment by NTCA-tax** [comment]
Alacsony összegű számlák adatszolgáltatásánál ténylegesen előállhat olyan helyzet, amikor az algoritmusunk akkor is jelez, amikor csak kerekítésből származik az eltérés. A 100 ezer forintos értékhatárnál ez inkább szélsőséges helyzet volt, ugyanakkor éppen @Zoller79 példája is mutatja, hogy kis összegek esetében könnyebben előfordulhat a téves jelzés. Mindenképpen megfontoljuk az algoritmus változtatását.

Az adatszolgáltatásnak mindig a számlán szereplő értékek alapján kell történnie. Nem szabad az adatszolgáltatásban a számlán szereplő összegeket módosítani! Még akkor sem, ha akár előre látható, hogy warningot vagy errort fog eredményezni az adott adatszolgáltatás. Így adatszolgáltatásban nem lehet 28%-os áfa kulcs, mivel a számlán nagy eséllyel 27%-os adókulcs szerepel (egyébként 28%-os adókulcsot be sem fogadunk).

**Comment by betasofthu** [comment]
Mindenképpen javaslom neked, hogy a forintban kifejezett tételhez tartozó áfa értéket 2 tizedesre számold és küldd be. Javasolt a tétel nettó és bruttó értékénél is. Egyébként szerintem ez nem csak a valutás számláknál, hanem a forintos számláknál is így érdemes csinálni a kerekítési eltérés minimalizálása miatt. Egyébként a tételenkénti áfát tartalmazó számlák, eleve csak kerekítési eltéréssel összesíthetők.  
Nem számoltam utána a példádnak, de szerintem így átmenne az ellenőrzésen. Az eurós számlán valószínűleg nem szerepel tételenként  forintban az áfa összege, ezért a számlától történő eltérés szóba sem jön.

**Comment by Zoller79** [comment]
> 
> 
> Alacsony összegű számlák adatszolgáltatásánál ténylegesen előállhat olyan helyzet, amikor az algoritmusunk akkor is jelez, amikor csak kerekítésből származik az eltérés. A 100 ezer forintos értékhatárnál ez inkább szélsőséges helyzet volt, ugyanakkor éppen @Zoller79 példája is mutatja, hogy kis összegek esetében könnyebben előfordulhat a téves jelzés. Mindenképpen megfontoljuk az algoritmus változtatását.
> 
> Az adatszolgáltatásnak mindig a számlán szereplő értékek alapján kell történnie. Nem szabad az adatszolgáltatásban a számlán szereplő összegeket módosítani! Még akkor sem, ha akár előre látható, hogy warningot vagy errort fog eredményezni az adott adatszolgáltatás. Így adatszolgáltatásban nem lehet 28%-os áfa kulcs, mivel a számlán nagy eséllyel 27%-os adókulcs szerepel (egyébként 28%-os adókulcsot be sem fogadunk).

**Comment by Zoller79** [comment]
@NTCA-tax 
Köszönöm a válaszokat! 
Annyit megjegyeznék, hogy a számla maga nem volt értékhatár alatti, mert több tétel is szerepelt rajta. Az ellenőrzést a konkrét tételsoron hajtotta végre a NAV online számla rendszer. 
A válasz alapján, akkor a felhasználónak nincs további dolga az így beküldött számlával. 

@betasofthu 
A programban lehetőség van tételsoronként is szerepeltetni a forintosított összegeket. A fent nevezett ellenőrzés is tételsoronként fut le. Az összesítő adatra külön ellenőrzés van (dokumentáció 1071. és 1074. azonosító). 
Jó megoldás lehetne a tizedesjegy kiírás is, csak ez felhasználó által beállítható adat. A felhasználók pedig jellemzően egész összegeket állítanak be a tételsorban megjelenő forint értékhez. Túl széles mezők lennének a számlaképen és esetleg nem is férne el egy sorban az összes adat, ha egy számlán van egységár, kedvezményes egységár, nettó, áfa, bruttó.
