### ISSUE TITLE
Furcsa response[DEV support]

### ISSUE THREAD

**Issue by kharonx** [nav-gov-hu/Online-Invoice#224]
Tisztelt Csapat,

ma a segítségetekkel sok számlát sikerült sikeresen beküldeni. Egy esetében furcsa státusz response -t kapok:

ez a transactionid -je : 2YRI6G2PBIO90ULD
result: OK viszont nincs message

Meg tudjuk nézni mi lehet más, mint a többinél?

Köszönöm előre is!

**Comment by NTCA-developer** [comment]
Szia @kharonx 

Nem kerestem ki logból, de biztos ez a helyzet amiről itt is beszéltünk: https://github.com/nav-gov-hu/Online-Invoice/issues/214

TL, DR: a keresett tranzakció vagy nem létezik vagy nem a tiéd.

**Comment by kharonx** [comment]
Hmm értem. Ebben az esetben mi végül is a státusz? Befogadott ?

**Comment by NTCA-developer** [comment]
Ez a konkrét tranzakció fel van dolgozva, de az adatszolgáltatás még nincs kész, mivel egy státusz lekérdezés sem érkezett még rá. (arra jogosulttól)

**Comment by kharonx** [comment]
Rendben. Köszönöm a választ! Zárom az issuet.
