### ISSUE TITLE
[Q&A] El lesz-e halasztva a 2020.07.01. 100 ezer Ft-os ÁFA érték határ eltörlése?

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#225]
A NAV 2.0 XSD/XML bevezetés végső határideje 2020.07.01. Ez rendben.
A kérdés arra vonatkozik, hogy az eredetileg 2020.07.01-re tervezett, ÁFA értéktől függetlenül minden belföldi adóalanynak kiállított számla kötelező NAV adatszolgáltatása be lesz-e vezetve végül vagy a koronavírus miatt kialakult helyzetre való tekintettel fél év csúszás lesz? Most már nagyon közelít a határidő és jó lenne 100% **BIZTOSAN TUDNI** a határidőt, hogy lehessen kommunikálni az ügyfeleknek, illetve kiadni az ehhez szükséges új programverziókat.

**Comment by NTCA-developer** [comment]
Szia @nbeeps2 

Szerintem sokan köszönik a kérdés feltevését. :) Továbbítjuk az illetékeseknek és proxyzzuk a választ, amit megszületik.

**Comment by NTCA-tax** [comment]
Az Áfa törvény 10. számú melléklete alapján az értékhatár eltörlése 2020. július 1-jén lép hatályba. Nincs olyan jogszabályi rendelkezés, mely ezen határidőt módosította volna. Ezért mindenképp úgy kell készülniük a szoftverfejlesztőknek és az adózóknak, hogy minden belföldi adóalanynak lesz adatszolgáltatási kötelezettsége, amennyiben másik belföldi adóalanynak állít ki számlát. A fejlesztéseiteknél ezért arra kell készülnötök, hogy július 1-től az ügyfeleknek rendelkezésre kell állnia nem csupán a 2.0-ás adatszolgáltatási funkció, hanem annak automatikusan az összes belföldi adóalanynak kiállított számlát is be kell küldenie.

Érdemes figyelembe venni a számlázással kapcsolatban 2020. július 1-jén hatályba lépő Áfa törvényi rendelkezéseket is. Így július 1-től minden adatszolgáltatásra kötelezett számlán fel kell tüntetni a vevő adószámát. A végszámláról történő adatszolgáltatás szabályai pontosodnak és néhány szolgáltatásnál pedig számlakiállítási kötelezettség keletkezik. Így a július 1-jével nem csupán az értékhatár kerül eltörlésre, hanem más kötelezettség változások is hatályba lépnek. A fejlesztéseknél ezeket a jogszabályi változásokat is figyelembe kell vennetek.

**Comment by Macskafarka** [comment]
Úgy lép életbe az ÁFA tv. módosítás, hogy nem lehet betartani.
Az xx65M áfa bevalláson a végszámlák esetén csak a különbözetet kell/lehet bevallani. 
Tudom, futottunk itt már egy kört a számla kiállítójának adatszolgáltatásbeli hasonló problémájáról, és abban maradtunk jobb híján, hogy minden tételsorról szolgáltatunk adatokat.
Azonban a számla befogadónak egyértelmű a törvényi elvárás, hogy a végszámla esetén csak a KÜLÖNBÖZET-et kell az xx65M-02 és 02K lapjain szerepeltetni. Ha az előlegezés 100% volt, akkor a végszámla esetén a különbözet 0.00 Ft.  Azonban a nyomtatvány nem fogad el 0 Ft-os tételsort, tehát a végszámlát ki kell hagyni a bevallásból. Kétlem, hogy ez lenne a cél, másrészt ez törvényellenes. Azonban a törvényt nem lehet betartani. Itt tehát nincs olyan lehetőség, hogy mi itt megállapodjunk abban, hogy úgy járunk el, mint eddig.

**Comment by betasofthu** [comment]
"A végszámláról történő adatszolgáltatás szabályai pontosodnak"
Itt arra gondolsz,  amit a #206 problémánál tisztáztunk? Tehát a 10.sz. melléklet 5. pontjában szereplő és nehezen értelmezhető szövegre gondolsz: "a teljesítésről kibocsátott, kiállított számla, számlával egy tekintet alá eső okirat vonatkozásában az előleg figyelembevételével adódó KÜLÖNBÖZETRŐL szolgáltat adatot."   A #206 ban megbeszéltek szerint az 1. megoldás megfelel ?

**Comment by Macskafarka** [comment]
Nem, nem felel meg a megbeszélt megoldás. Ott tételsorokról volt szó, de itt számla adattartalmáról. Tételsornál nem tudtuk értelmezni a különbözetet, de számla adattartalmában a különbözet már értelmezhető.   Ott abban maradtunk, hogy bővebb adatot szolgáltatunk, ami még belefér a jogértelmezésbe. De itt az ügyfelek ragaszkodnak a törvény szövegéhez, és elvárják azt, hogy csak a KÜLÖNBÖZET kerüljön a  2065M-02 lapjára, egy petákkal sem több. Ez technikailag lehetséges akkor, ha a különbözet nem 0, bár szerintem nem ez volt a jogalkotó célja. De 0.00 Ft esetén ez technikailag sem lehetséges. Csak nekem okoz ez problémát, és mindenki más érti, hogy mit kell beletenni 2020.07.01 után a 2065M-02 lapjára végszámla esetén? És az a módszer használható-e 100% előlegezés esetén is?

**Comment by NTCA-tax** [comment]
Az M lapon kizárólag azon számlákról kell adatot szolgáltatni, amelyre az adózó levonási jogot alapoz. Amennyiben a végszámlában az előleg beszámításával képzett különbözet nulla forint, akkor nincs olyan összeg, amely az adólevonást érintené. Így a nulla forint végösszegű számlát nem kell feltüntetni az M lapon.

**Comment by Macskafarka** [comment]
NTCA-tax válasza érthető és megvalósítható.
Feltéve, ha a 2065M-02 áfa bevallási lap F1 helpjéből is ki fog kerülni a termékértékesítés és a szolgáltatásnyújtás sor. Mert ameddig az szerepek ott, addig nem lehet az említett módon eljárni, mivel az előleg betudó sor NEM termékértékesítő sor.

Idézet a 2065M-02 lap kitöltési útmutatójból:
"A termékbeszerzés / szolgáltatás igénybevétel adót nem tartalmazó ellenértékét az adóalap elnevezésű (c) oszlopban kell feltüntetni. Az adatokat ezer forintra kerekített összegben kell megadni! Az adóalap (c) oszlop összegeit a lap 37. sorában, több kitöltött lap esetén az utolsó lap 37. sorában kell összesíteni."

**Comment by nbeeps2** [comment]
> Nincs olyan jogszabályi rendelkezés, mely ezen határidőt módosította volna

Igen, azt én is tudom, hogy jelenleg nincs olyan jogszabályi rendelkezés, mely ezen határidőt módosította volna, mert ha lenne, akkor nem tettem volna fel a kérdést... Vagyis köszönöm a választ, de ezzel nem lettem előrébb, mivel azt kaptam, amit eddig is tudtam. A kérdés inkább arra vonatkozott, hogy nincs-e a háttérben valami olyan mozgolódás/szakmai egyeztetés (amit mi fejlesztünk nem látunk), ami arra utalna, hogy jó eséllyel elhalasztásra kerülhet ez a határidő, a kialakult "apokalipszis..." miatt? Én úgy tudom, hogy több nagyobb szervezet (pl. MKOE) és kezdeményezte ennek a határidőnek az eltolását. E kapcsán biztosan vannak a tárgyalások a háttérben...

**Comment by NTCA-tax** [comment]
Az a tény, hogy nincs olyan jogszabályi rendelkezés, mely a határidőt módosította volna, következik, hogy július 1-jén hatályba fog lépni az értékhatár eltörlése és a többi olyan jogszabályi változás, melyről fent írtam. Adóhivatali oldalról is úgy készülünk, hogy július 1-től az új jogszabályi követelményeknek megfelelően fognak érkezni az adatszolgáltatások.

**Comment by kabelnet2** [comment]
Adótanácsadók egyesületének javaslata a kormánynak:
"Valamint azt is javasolják, hogy a július 1-től hatályba lépő online számlázás bejelentését halasszák el, mert annak alkalmazására a jelen helyzetben a vállalkozók jelentős része nem tudott felkészülni; különösen áll ez a mikro vállalkozásokra, és kiemelten igaz az eddig kézi számlát kiállítókra; ez utóbbiaknál jellemzően nincs meg a szükséges technikai (eszköz, szoftver) háttér, és ennek hiányában nincs meg a kellő felkészültség sem."

**Comment by nbeeps2** [comment]
Köszönöm kabelnet2-nek, az idézetet, én is ezekre gondoltam. A július 1-el mint határidővel, ha nincs ez a vírus dolog nem lett volna baj, de szerintem most nagyon sok embernek van ettől sokkal nagyobb baja és indokolatlan lenne ezt a terhet ebben az időszakban ráereszteni a vállalkozókra. Én mint fejlesztő készen állok, tehát ez nem egy olyan jellegű "rinyálás", hogy "jajj, nem lehet megcsinálni addig", mert a szoftver kész. Itt emberségről, empátiáról beszélünk, hogy nem csesztetjük az embereket vaskalaposan csak azért, mert valaki kitalálta a határidőt mikor még fogalma nem volt, hogy az elmúlt 100 év legnagyobb egészségügyi apokalipszise csap le. Néha érdemes újratervezni. Tudom, hogy ez nem a NAV hatásköre, a jogszabályi rendelkezést kellene megváltoztatni, ahogy azt az adótanácsadók egyesület is javasolta.

**Comment by kabelnet2** [comment]
Amit leírtál, az az egyik oldal. De ezt az egészet nyilván nem a vállalkozások szivatása miatt találták ki. Feltehetőleg a számlázási morál javítása is cél volt, ami meg többletbevételt jelent az államnak. És az általad leírt okok miatt az államnak jócskán megnőttek a kiadásai.
Ezt nem azért írtam, mert a bevezetés ellen/mellett szeretnék érvelni, csak jelezni, hogy valószínüleg sok szempontot kell mérlegelni a döntésnél. Fejlesztőként nekem ugyan olyan közömbös a dolog, mint neked: egy limitet kell átírnom. Vagy nem.

**Comment by NTCA-tax** [comment]
Szerintem ehhez a témához nagyon újat már nem tudunk hozzátenni. @nbeeps2 és @kabelnet2 hozzászólása is jól illusztrálja, hogy a halasztás és a hatályba lépés mellett is szólhatnak érvek. Az is jogalkotói döntés, hogy nem módosítja a hatályba lépés dátumát. Jelenleg mindenkinek erre kell készülnie, mint ahogy az adóhivatal is ezt teszi.

Az issue-t így lezárom
