### ISSUE TITLE
[Q&A] Számviteli bizonylatot be kell-e küldeni

### ISSUE THREAD

**Issue by Csomb** [nav-gov-hu/Online-Invoice#226]
Sziasztok!

Érdeklődnék, hogy azokra a cégekre, akik speciális okokból mentesülnek a SZÁMLA kibocsátás alól ( ÁFA törvény 165. § (1):  termék értékesítése, szolgáltatás nyújtása a 85. § (1) bekezdése és 86. § (1) bekezdése szerint mentes az adó alól) és csak számviteli bizonylatot állítanak elő vonatkozik-e a számlabeküldési kötelezettség?

Köszönöm a választ előre is!

**Comment by NTCA-tax** [comment]
Mivel az adatszolgáltatási kötelezettség kizárólag az áfa törvény szerinti számlára vonatkozik, ezért a számviteli bizonylatokra nem terjed ki az számlaadat-szolgáltatás. Tehát számviteli bizonylatok adatait nem szabad beküldeni számlaadat-szolgáltatásként.

**Comment by Csomb** [comment]
Köszönöm!
