### ISSUE TITLE
[FEATURE] online számlázó interfész

### ISSUE THREAD

**Issue by janisoft** [nav-gov-hu/Online-Invoice#227]
Kedves Fejlesztők!

Szívesen fogadnék egy interfészt az online számlázóhoz.

Az adatkapcsolat lehetne a már jól megszokott számla XML formátum csak számlaszám nélkül, amire a NAV Online számlázó visszaadná a legnerált számla számát, és esetleg a képet PDF-ben (aminek a hash kódját természetesen beküldi a másik rendszerébe :)

János

**Comment by NTCA-supporter** [comment]
Kedves @janisoft!

Először is bocsánat a késői válaszért! Nem tervezünk interfészt az Online Számlázóhoz mert annak teljesen más alap koncepciója az Online Számlához képest. Az Online Számlázó automatikusan beküldi az adatokat és /queryInvoiceDigest szolgáltatással kivonatosan ezeket is le tudod kérdezni, köztük a számlaszámot. Ha pedig megvan a számlaszám akkor /queryInvoiceData szolgáltatással a teljes adatokat.

**Comment by NTCA-developer** [comment]
Ezt inaktivitás miatt lezárom, kérlek nyissátok újra ha szükséges!
