### ISSUE TITLE
[FEATURE] Problémák az online számla felülettel

### ISSUE THREAD

**Issue by pvmon** [nav-gov-hu/Online-Invoice#23]
Szia!
Tudom nem a V2-höz kapcsolódik, de az online-szamla felület nagyon idegesítő hibáit is jó lenne ha kijavítaná valaki, mert nálunk csapódik le és nagyon fárasztó ezzel foglalkozni sok ügyfélnél. Remélem eljut az illetékesekhez:

1. A felület a technikai felhasználónál elfogad közepes, vagy gyenge jelszót. DE utána a feltöltés nem megy, mert csak Erős jelszóval működik az adatfogadás. **Jó lenne, ha már az API nem fogad csak erős jelszót, akkor a felület sem engedne nem erős jelszót megadni.**  Elég fárasztó ilyenkor átvergődni ezen az ügyféllel, amikor sokszor a könyvelője csinálta a regisztrációt is és az ügyfél be sem tud lépni a online számla felületére. (Rengetegszer ez volt - van!)

2. A technikai felhasználó jogosultságainál van egy "Összerendelések" gomb, ami nem egyértelműen látható, hogy mire való lenne. Kiderítettük, ha ide ír valaki valamilyen adószámot, akkor csak azokat fogadja el az API. Na ennek nem sok értelme van mert a számlázóban veszik fel a vevőt és utána senki nem jön ide is még beírni az adószámát a vevőnek.  **Viszont ha van itt valami, akkor onnantól más adószámokat nem fogad az API rendszerük. Az egyik ügyfelünk tévedésből ide beírta a saját adószámát és utána egy darab számlája sem ment fel a rendszerbe, mert visszautasította a szerver.**

3. Nem értjük azt sem, hogy **a technikai felhasználónak miért nincs alapban kikapcsolhatatlan "Számlák kezelése", "Számlák lekérdezése" vagy legalább a sajátoké.** Ez is állandó probléma forrás, hogy nem adnak semmi jogot, vagy a lekérdezést nem adják meg a technikai felhasználónak. Mivel a rendszerük asszinkron feldolgozású ezért feltöltés után tudnunk kell, hogy felment-e a számla, mielőtt pl. egy sztornót, módosítót küldünk rá. Mert ha még nem dolgozták fel és nincs DONE státuszban, akkor jön a hiba, hogy nincs előzmény bizonylat.
Ha valaki kiállít egy számlát és rögtön sztornózza is, mert elrontotta, akkor nem küldhetjük fel (talonban tartjuk), amíg az eredeti számla a rendszerükben történt befogadásáról lekérdezéssel nem győződtünk meg. Tehát a két jog szétválasztása csak problémákat szül a gyakorlatban és amúgy sem látszik értelme technikai felhasználó esetén. Az első előadásukon azt is mondták, hogy figyelik majd, hogy a szoftverek visszakérdezik-e a feltöltés eredményét -> Egy ilyen beállítással nem igazán megy az sem.

4. A kimenő számlák listájában megjelenik a nettó, bruttó összeg normál számlák esetén. Viszont ha **egyszerűsített számláról** van szó, akkor a nettó és bruttó oszlopban sincs adat.

5. A XML 1.1-ben bevezetett egységeknél sokszor kell használni az OWN jelzést és utána megadni, hogy mi az. PL négyzetméternél. A felületükön ha valaki megnéz egy ilyen számlát azt látja, az egységeknél, hogy Saját, viszont ide kiírhatnák mögé, hogy mi az, ha már mi megadjuk. Mert azért elég furcsán néz ki például az, hogy: mennyiségi egység meghatározható-e: **Igen** és után ez jön Burkolólap **5 Saját** 5000 27% 25000

**Comment by Amn3s1a2018** [comment]
>     Mert azért elég furcsán néz ki például az, hogy: mennyiségi egység meghatározható-e: **Igen** és után ez jön Burkolólap **5 Saját** 5000 27% 25000
Ez már én is észrevettem, kivéve, hogy a „**Mennyiségi egység meghatározható-e**:” az ilyen soroknál „Nem”. Amúgy ha belemész egy tételbe, ott már látszik a saját egység is, gondolom a korlátozott hely miatt nem került a tétellistába.
A lineExpressionIndicator az xsd szerint: „**Értéke true, ha a tétel mennyiségi egysége természetes mértékegységben kifejezhető**”. A kiemeltek alapján én úgy értem, hogy unitOfMeasure: OWN esetén ez nem kéne true legyen és vice versa.
A dokumentáció szerint viszont: „A  számlasorba  bevezetésre  került  egy  logikai  jelölő  tag  (lineExpressionIndicator),  amelynek megadása  minden  számlasorban  kötelező.  Ha  a  tag  értéke  true,  akkor  adott  számlasorban kötelező megadni” Ez a fentinél már egy sokkal megengedőbb kijelentés, az 1.1-ben meglévő keresztellenőrzések is ezt támasztják alá, csak éppen nem értem mire jó. A 2.0-ig érdemes lenne ezt is tisztázni.

**Comment by pvmon** [comment]
Szia!
„Értéke true, ha a tétel mennyiségi egysége természetes mértékegységben kifejezhető”
Szerintem ez arra vonatkozik, hogy van-e egyáltalán mennyiségi egysége. Nagyon sok természetes mennyiségi egység van a NAV által preferáltakon kívül is, cviszont nem lehet mindent mennyiségi egységben mérni.
Eddig figyelmeztetést adtak, ha nem adtál meg mennyiségi egységet, de például egy előlegnek nincs mennyiségi egysége, se mennyisége csak értéke.
Eddig, ha ilyet felküldtünk, akkor figyelmeztetés érkezett, hogy a tételnek nincs mennyiségi egysége, ha írtunk mennyiséget, ha mennyiséget se írtunk akkor arra érkezett figyelmeztetés.
Ezért, hogy ne érkezzen figyelmeztetés küldtünk valamit neki pl. 1 xx. Ezt szerette :)
Most már az 1.1-ben gondolom elég lenne ezt az értéket falsra rakni, hogy ne figyelmeztessen, ha nincs mennyiségi egység, de nem próbáltuk ki mert nem piszkáljuk amit már másképp megoldottunk és működik.

**Comment by Amn3s1a2018** [comment]
Köszi, így már világos. Mi nem találkoztunk ezzel a problémával, mert történelmileg mindennek van mennyisége ill. mikor felmerült, hogy valaminek nincs, eddig mindig elég volt egy „nembaj, akkor 1 darab”. Azért mielőtt pusholom a lineExpressionIndicator ezen értelmezését, örülnék egy megerősítésnek esetleg egy ígéretnek, hogy ez belekerül az xsdbe is.

**Comment by Amn3s1a2018** [comment]
A tétellistában ahol saját egység van, én úgy oldanám meg, hogy a „saját” helyett kiírnám a unitOfMeasureOwn tartalmát, és ha valakinek fáj, hogy ezek összetéveszthetőek a többivel, akkor formázással (font, szín, háttérkép) meg lehet különböztetni.

**Comment by csabecon** [comment]
Számlamásolatot miért nem lehet készíteni? Most már az ÁFA törvény sem tiltatkozik ellene (megfelelve az európai normáknak). Nem biztonságos megoldás, hogy a számla kiállítója "úgyis eltárol egy példányt magának".

**Comment by kabelnet2** [comment]
"Számlamásolatot miért nem lehet készíteni?"
Szerintem mert a NAV-nak kellene garantálni, hogy az hiteles, ezt viszont nem tudja megtenni, mert fogalma sincs arról, hogy azok az adatok, amiket feltöltöttek azok valóvan az eredeti számla adatai és annak valamennyi adata fel lett töltve.
A számlamásolatot ezen túl is az eladótól kell kérni, ő felel a számláért.
A V2-ben meglesz a letöltési lehetőség a bejövő számlákra is, azután ha akarod, kinyomtathatod.

**Comment by Amn3s1a2018** [comment]
> Számlamásolatot miért nem lehet készíteni
Igazából nem is biztos, hogy jól érjük a kérdést. Mármint miért és hogyan szeretnél számlamásolatot? Szimpatikus lenne egy olyan verzió, hogy „úgyis elküldöm a számlát a NAV-nak, a vevő meg le tudja kérdezni”. Vagyis akár ki sem nyomtatom, el sem küldöm a számlát (vagy elküldöm, de nem baj ha valaki elveszíti). Az első probléma ami kapásból eszembe jut, hogy az xml nem feltétlenül tartalmaz minden adatot, csak a kötelezőeket. Az elektronikus számlázásra átállást szerintem az gyorsítaná fel, ha az onlineszámla apiból elérhetővé tennék a https://niszavdh.gov.hu szolgáltatást, ami (úgytudom) jelenleg csak manuálisan használható.

**Comment by csabecon** [comment]
Pontosítom a kérdést.
Kiállítok egy számlát a NAV online felületén és kinyomtatom (újmagyarul: NAV-os online számlázóval gépi számlát készítek, de nem elektronikusat). Vevő elveszíti, kér másolatot. Hogyan tudom megtenni? Jelen rendszerben nem találom az újranyomtatási funkciót.

A hiteles másolat csak kézzel kiállított számla esetén érdekes kérdés, gépi vagy elektronikus számla esetén a hitelességet maga a rendszer garantálja, ti. kiállítás után már nem lehet rajta módosítani.

**Comment by Rossi73** [comment]
Ha megnyitod az online számlázót, a Számláim lista jobb szélén, az Adatszolgáltatás státusza oszlop és a 3 pötty (további műveletek) között van egy PDF ikon, amire kattintva le tudod tölteni a kiállított számla PDF változatát, így tehát bármennyi "másolatot" ki tudsz nyomtatni (csak teszt környezetben ellenőriztem, mivel élesben nem használjuk).

**Comment by pvmon** [comment]
Kicsit félre megy a topic. Nem az Online-**Számlázó**hoz kapcsolatosan nyitottam, hanem az Online-**Számla** felülettel kapcsolatban. (Ez is megérne egy misét minek kellett ennyire hasonló nevet adni nekik.)
Továbbra is várnám azzal kapcsolatban a hozzászólást, amit a nyitó kérdéseben leírtam.

A felsorolt 5 pontból lesznek-e kijavítva, vagy továbbra is ránk maradnak ezeknek az idegesítő hibáknak a kezelései.
Például: 1 pont: Már vagy 40 felhasználónak adtam már meg ugyanazt a technikai felhasználó **erős** jelszót, mert nincs kedvem mindenkinek újat kitalálni :) Pedig ez a felület hibája és könnyen javítható lenne és már a felhasználó rá lenne kényszerítve, hogy ne adjon meg rosszat. Ha ez sikerülne, nem hívna fel minket és nem kapná meg a sablon erős jelszavunkat.

**Comment by NTCA-developer** [comment]
Sziasztok!

Köszönjük a felvetéseket. Hamarosan visszajelzek, biztosan lesznek kérdéseim.

**Comment by NTCA-developer** [comment]
Sziasztok!

Jól elúsztam, de most pótolom, köszönöm a türelmeteket.

> A felület a technikai felhasználónál elfogad közepes, vagy gyenge jelszót. DE utána a feltöltés nem megy, mert csak Erős jelszóval működik az adatfogadás.

Ez ebben a formában nem igaz, vagy nem ugyan arról beszélünk. Ami jelszót elfogad a felület, az használható az API-nál is. Most egy meglévő technikai usernél átírtam a korábbi jelszót '111111aB'-re, ez egy elég gyenge jelszó, és az ebből generált '56CE072456976E3C8B1B0D579F6F99BBE139F3E859909FE4EBCDE210EC4D39810CEE3867CFE0EE5A29D352DA3A2BF12C30E157ED802250BC15EFD67A4BD7BBD5' jelszóhash-el simán kaptam tokent. Kérlek pontosítsd, hogy mi a probléma.

> A technikai felhasználó jogosultságainál van egy "Összerendelések" gomb, ami nem egyértelműen látható, hogy mire való lenne. Kiderítettük, ha ide ír valaki valamilyen adószámot, akkor csak azokat fogadja el az API. Na ennek nem sok értelme van mert a számlázóban veszik fel a vevőt és utána senki nem jön ide is még beírni az adószámát a vevőnek. Viszont ha van itt valami, akkor onnantól más adószámokat nem fogad az API rendszerük. Az egyik ügyfelünk tévedésből ide beírta a saját adószámát és utána egy darab számlája sem ment fel a rendszerbe, mert visszautasította a szerver.

Ez pontosan így van. Azért remélem nem kellett nagyon messze menni a kiderítéssel, mert az 1.0-ás release notesban és az interfész dokumentációban is benne van, hogy így működik. Van olyan, hogy valaki önmagának számláz, nem tilthatjuk meg, hogy egy technikai felhasználóhoz azt az adószámot rendeljék, akihez az tartozik. De a felvetésre visszatérve, ebből még nem értem, mi volna a javaslat lényege. Mit javasolsz, hogyan lenne egyértelműbb? Annó az adminisztrációs képernyőkre azért nem került magyarázó szöveg, mert az oldalon lévő regisztrációs tájékoztató ezeket az infókat elvben tartalmazza. (noha ezzel az érveléssel én sem értek egyet maradéktalanul) 

> Nem értjük azt sem, hogy a technikai felhasználónak miért nincs alapban kikapcsolhatatlan "Számlák kezelése", "Számlák lekérdezése" vagy legalább a sajátoké.

Mert valid igény, hogy egy technikai user ne tudjon adatot szolgáltatni csak lekérdezni, vagy éppen fordítva, mert valaki egy helyre akarja csoportosítani az adatszolgáltatás ellenőrzésének jogát. Megértem hogy fejlesztőként frusztráló fogni mások kezét, de azért, mert a könyvelők/cégvezetők akkor sem olvasnak el semmit, ha a képernyő közepére 100px-es betűmérettel ki van írva valami, azért szerintem nem a felületet kell hibáztatni.

> A kimenő számlák listájában megjelenik a nettó, bruttó összeg normál számlák esetén. Viszont ha egyszerűsített számláról van szó, akkor a nettó és bruttó oszlopban sincs adat.

Pontosítsunk. A felületen a listában nettó és ÁFA összeg (HUF) van, nem nettó és bruttó. Egyszerűsített számlában fogalmilag nincs nettó, még ÁFA összeg helyett ÁFA tartalom van. Mivel a felületnek reszponzívnak kell lennie (mobil nézet, tablet stb) a lista oszlopai nem bővíthetők a végtelenségig, igazából már most is túlságosan zsúfolt. Ezért azt nem tudjuk megtenni, hogy minden ilyen "egyik helyen nincs, a másikon van" oszlopot felveszünk a felületre. A másik megoldás az lenne, ha számla típusonként változna a lista oszlopszerkezete, akkor meg nem lehetne vegyesen, egyben látni a számlák listáját, ami sokkal nagyobb baj lenne. Mivel a kaméleon jellegű oszlopokat szeretnénk elkerülni (olyat nem szeretnénk, hogy adott oszlopba egy sornál van X érték, míg a másik sornál már Y érték) szerintem ez a legkevésbé rossz megoldás. Szívesen vesszük, ha van alternatív javaslatod a megoldásra és ezt megosztod velünk.

> A XML 1.1-ben bevezetett egységeknél sokszor kell használni az OWN jelzést és utána megadni, hogy mi az. PL négyzetméternél. A felületükön ha valaki megnéz egy ilyen számlát azt látja, az egységeknél, hogy Saját, viszont ide kiírhatnák mögé, hogy mi az, ha már mi megadjuk.

Megint csak a reszponzivitással tudok érvelni, miért nincs benne a listában és a kaméleon oszlopokkal, hogy OWN esetén miért nem a megadott érték szerepel benne. Az adatmodell nem barátja a felületnek, azt kell mondjam. Szerintem itt is a kisebbik rossz van megvalósítva, de nyitottak vagyunk a javaslatokra.

**Comment by pvmon** [comment]
Egyszerűsített számla:
Formailag lehet, hogy nincs ÁFA összeg és ÁFA tartalom van, de teljesen mindegy. ÁFA és nettó így is úgyis van és az ÁFA-t is be kell fizetni :) Az hogy magán a számlán minek nevezve jelenik meg ebben az esetben szerintem teljesen mindegy. A megjelenő táblázatnak nem magának a számla formátumát kell követnie, hanem az adatokat megjeleníteni, legalábbis szerintem. (A típusnál úgyis ki van írva, hogy egyszerűsített.)
Mivel az egyszerűsített számlából is meghatározható (kiszámolható) a nettó és az áfa összeg, így itt megjeleníthető lenne az üres adat helyett, ami nem valami jól néz ki.
Alternatíva lenne, ha a bruttó összeg lenne az egyik oszlop (pl. a nettó helyett) és az már az egyszerűsítettnek is van és számolás nélkül megjeleníthető.
De nekem mindegy maradhat így, ha másokat nem zavar ez az adat hiány a táblázatban.
![nav_egysz](https://user-images.githubusercontent.com/50443612/59662036-6667ec80-91ac-11e9-905b-62e1c4b9edb1.jpg)

**Comment by pvmon** [comment]
OWN egység problémára javaslat:
Ha megadják az XML-ben, hogy mi az OWN értéke (pl: m2) akkor legyen az kiírva, ha nem adja meg az XML akkor legyen OWN.
De ez sem engem zavar, hanem a felhasználókat, mert nem tudják mi az az OWN. (Nem fejlesztők, nem olvasnak doksit, és meg sokan azt sem, amit mi leírunk nekik, utána meg tőlünk kérdezgetik telefonon és  sajnos nem a NAV ügyfélszolgálatától)

**Comment by pvmon** [comment]
Technikai felhasználó:
Ha van valakinek ilyen igénye, akkor tudja mit csinál és minek, de amikor az egyszerű vállalkozó regisztrál és 25 perc múlva leizzadva elér ide, akkor nem figyel arra, hogy az alapban nem bekapcsolt jogokat bekapcsolja.
Tehát az lenne a jó megoldás szerintem, hogy **új technikai regisztrálásnál alapban legyen bekapcsolva a két jog**, és kapcsolja ki az aki paranoiás. Így az általánosabb felhasználóknak kedvezne ez a megoldás. Nekünk is kevesebb gondunk lenne :)
![nav_tech](https://user-images.githubusercontent.com/50443612/59664420-530b5000-91b1-11e9-9d8b-0f85032499bf.jpg)

**Comment by xcom169** [comment]
Ezt Én is abszolút csak támogatni tudnám!

**Comment by NTCA-developer** [comment]
Oké, köszi a javaslatot, rákérdezek mi lenne, ha kiosztott jogokkal jönne létre technikai felhasználó. De nem ígérek semmit, ez egy elég keményvonalas kérdés.

**Comment by xcom169** [comment]
> Oké, köszi a javaslatot, rákérdezek mi lenne, ha kiosztott jogokkal jönne létre technikai felhasználó. De nem ígérek semmit, ez egy elég keményvonalas kérdés.

És ha lenne rá lehetőség, hogy könnyen CTRL+C , CTRL+V-vel tudjanak másolni mindent a weblapról az is nagyszerű lenne!! Képként nagyon nehéz visszafejteni a betűket.

**Comment by NTCA-developer** [comment]
> És ha lenne rá lehetőség, hogy könnyen CTRL+C , CTRL+V-vel tudjanak másolni mindent a weblapról az is nagyszerű lenne!! Képként nagyon nehéz visszafejteni a betűket.

Ezt most is lehet, tegnap amikor írtam, hogy próbaként beállítottam gyenge jelszót én is a felületről másoltam ki a kulcsokat, login nevet. Csak naprakész böngésző kell hozzá, a régi verzióknál szokott ez probléma lenni.

**Comment by pvmon** [comment]
> Oké, köszi a javaslatot, rákérdezek mi lenne, ha kiosztott jogokkal jönne létre technikai felhasználó. De nem ígérek semmit, ez egy elég keményvonalas kérdés.

Nem kell, hogy azzal jöjjön létre mindenképpen, csak az lenne a jó ha ide érkezik a folyamatban **legyen bekapcsolva ez a kettő jog alapban a képernyőn**. Ha akarja kapcsolja ki, de az már egyértelműen a felhasználó szándéka legyen és ne a tudatlanság hiánya miatt vegye fel így.

**Comment by pvmon** [comment]
Jelszó probléma:
Ma én is újra próbáltam a jelszavas tesztet. Úgy néz ki ez megjavult valamikor, mert már nem sikerült nekem sem előhozni.
Köszönöm!

**Comment by pvmon** [comment]
Adószám összerendelés:
**A saját adószámát ne tudja ide beírni** a felhasználó. Az már jó lenne.

**Comment by pvmon** [comment]
> > És ha lenne rá lehetőség, hogy könnyen CTRL+C , CTRL+V-vel tudjanak másolni mindent a weblapról az is nagyszerű lenne!! Képként nagyon nehéz visszafejteni a betűket.
> 
> Ezt most is lehet, tegnap amikor írtam, hogy próbaként beállítottam gyenge jelszót én is a felületről másoltam ki a kulcsokat, login nevet. Csak naprakész böngésző kell hozzá, a régi verzióknál szokott ez probléma lenni.

Chromban: ha egérrel jelölöd ki a szöveget nem megy CTRL+C csak a jobb klikk másolás menüpont.
Ha billentyűvel jelölöd ki a szöveget (SHIFT+kurzor billentyűk), akkor megy a CTRL+C, majd CTRL+V is.

**Comment by NTCA-developer** [comment]
> Jelszó probléma:
Ma én is újra próbáltam a jelszavas tesztet. Úgy néz ki ez megjavult valamikor, mert már nem sikerült nekem sem előhozni.
Köszönöm!

Nm, örülök hogy már nem okoz gondot.

> Adószám összerendelés:
A saját adószámát ne tudja ide beírni a felhasználó. Az már jó lenne.

Mint mondtam ez egy valid használati eset, hogy a user önmagára van korlátozva. Azt viszont lehet, hogy amikor önmagát rögzíti, akkor promptoltatjuk a felületen, hogy biztos komolyan gondolta-e az összerendelést. Ezt elfogadnád?

> Chromban: ha egérrel jelölöd ki a szöveget nem megy CTRL+C csak a jobb klikk másolás menüpont.
Ha billentyűvel jelölöd ki a szöveget (SHIFT+kurzor billentyűk), akkor megy a CTRL+C, majd CTRL+V is.

Akkor ez egy Chrome bug. Van ilyen, éppen most a 42-es Edge és a 67-es Firefox szereti az Angulart (nálam ezzekkel simán megy a kijelölés, kimásolás), a Chrome meg nem. Majd megjavítják meg eltörik megint, ahogy mindenki a világon.

**Comment by pvmon** [comment]
> Mint mondtam ez egy valid használati eset, hogy a user önmagára van korlátozva. Azt viszont lehet, hogy amikor önmagát rögzíti, akkor promptoltatjuk a felületen, hogy biztos komolyan gondolta-e az összerendelést. Ezt elfogadnád?
> 
Igen ez egy jó megoldás, talán elolvassák :)

**Comment by NTCA-developer** [comment]
Oké, ezt felveszem feladatnak akkor. Maradt még nyitott kérdés, vagy lezárhatjuk ezt a szálat?

**Comment by Amn3s1a2018** [comment]
Hasonló megerősítés lehetne akkor is, ha vmi jogosultság nincs pipálva.

**Comment by pvmon** [comment]
**Zárható**
De még egyszer kérem, hogy a jognál nagyon jó lenne az alapnak legalább a számlák kezelése és a saját számlák lekérdezése bekapcsolt állapotban jöjjön új fel technikai felhasználó felvételekor.
Ez mindenképpen kellene alapban egy számlázó programnak, ahhoz hogy számlát tudjon feltölteni és az eredményt visszakérdezni az alapvető működéséhez. Aztán, ha valaki mégis kikapcsolja az már egyértelműen felhasználói hiba vagy szándékos döntése.
**Köszönöm a figyelmet és a segítséget!**

**Comment by NTCA-developer** [comment]
> De még egyszer kérem, hogy a jognál nagyon jó lenne az alapnak legalább a számlák kezelése és a saját számlák lekérdezése bekapcsolt állapotban jöjjön új fel technikai felhasználó felvételekor.

Ugyan így értettem én is, hogy a rögzítő felületen legyen már default kiválasztva ez a 2 jog.

**Comment by Amn3s1a2018** [comment]
Lol, ezt egyszerre írtuk. Nem gondolom, hogy a defaultban adott minden jog átmegy, de egy megerősítést kérni arra az esetre amikor nem jelöl be mindent (ami nyilván egy expert felhasználás), mindenkinek elfogadható sztem.

**Comment by csabecon** [comment]
> 
> 
> Ha megnyitod az online számlázót, a Számláim lista jobb szélén, az Adatszolgáltatás státusza oszlop és a 3 pötty (további műveletek) között van egy PDF ikon, amire kattintva le tudod tölteni a kiállított számla PDF változatát, így tehát bármennyi "másolatot" ki tudsz nyomtatni (csak teszt környezetben ellenőriztem, mivel élesben nem használjuk).

Az élesben sajnos még nem működik

**Comment by csabecon** [comment]
> 
> 
> Ha megnyitod az online számlázót, a Számláim lista jobb szélén, az Adatszolgáltatás státusza oszlop és a 3 pötty (további műveletek) között van egy PDF ikon, amire kattintva le tudod tölteni a kiállított számla PDF változatát, így tehát bármennyi "másolatot" ki tudsz nyomtatni (csak teszt környezetben ellenőriztem, mivel élesben nem használjuk).

Élesben nem működik

**Comment by NTCA-developer** [comment]
Szia!

> Az élesben sajnos még nem működik

De működik, csak lehet hogy scrolloznod kell jobbra a lista alján. Vagy vegyél ki egy oszlopot a listából, és meg fogod látni. :)

**Comment by NTCA-developer** [comment]
Sziasztok!

Két gyorshír.

1) Zöld lámpát kapott a technikai felhasználós felvetés. A fejlesztést követően új technikai felhasználó létrehozásakor a rögzítő felület úgy fog betölteni, hogy a számla beküldés és a lekérdezés joga ki lesz választva, és ha így rögzítik a felhasználót, akkor teljes funkcionalitással fog a user létrejönni. Remélhetőleg ez csökkenteni fogja a supportra elégetett óráitok számát.

2) Azokból a fejlesztési felvetésekből amit írtatok nekem az körvonalazódik, hogy kellene egy olyan funkciócsoport, ami vezeti az elsődleges felhasználók kezét addig a pontig, amíg a regisztráció adatszolgáltatásra alkalmas állapotba nem kerül, értsd legalább 1 olyan technikai felhasználó van, aki teljes körűen alkalmas adatot szolgáltatni az adózóra nézve. A következőképpen tudnám ezt elképzelni.

- Felveszünk egy új attribútumot a regisztrációs adatokhoz, amivel ez a segítség ki/be kapcsolható, hogy a profikat ne nyaggassuk feleslegesen. A telepítéskor ezt minden korábbi regisztrációnál default bekapcsoltra állítjuk és az új regisztrációk is így fognak létrejönni. Akit zavar vagy nem igényli hogy fogjuk a kezét, majd kikapcsolja.
- Ha fenti paraméter be van kapcsolva, akkor figyelmeztetünk a felületen ha nincs egyetlen aktív technikai felhasználó sem, vagy létezik technikai felhasználó a céghez, de
-- nincs meg nála mindkét API kulcs
-- nincs meg nála együttesen a számla beküldési és lekérdezési jog
-- ide jöhetne az az ellenőrzés is, ha az összerendeléseknél csak az adózó saját adószáma szerepel

Felveszem board-ra fejlesztési igényként.

**Comment by pvmon** [comment]
Ez nagyon jó és mindenkinek sokat segítene! Részemről köszönöm!

**Comment by NTCA-developer** [comment]
Sziasztok!

Csak egy visszajelzést, a tegnap esti release-ben kikerültek azok a fejlesztések az élesre, amiket itt vállaltunk. Használjátok egészséggel!
