### ISSUE TITLE
STORNO sample

### ISSUE THREAD

**Issue by Mailmedve** [nav-gov-hu/Online-Invoice#230]
Kedves Fejlesztők!

Kérlek tegyetek fel a Online-Invoice/sample/Data sample/ szekcióba egy mintát egy egyszerű néhány tételes számla STORNO -jának bemutatásához.

Csak simán érvényteleníteni szeretném a számlát nem módosítani, de a hibakezelő megköveteli tételek módosításának jelzését is ha jól értem:
 - Tételsort tartalmazó módosító okirat esetén a tételsor módosítás jellegének megadása kötelező. 
Tag: InvoiceData/invoiceMain//invoice/invoiceLines/line/lineModificationReference

Köszönöm a segítséget.

**Comment by NTCA-tax** [comment]
A [https://onlineszamla.nav.gov.hu/dokumentaciok](url) lapon találsz Data példa XML-ket. A 13/B példa XML tartalmaz egy mintát erre.

**Comment by Mailmedve** [comment]
Köszönöm
