### ISSUE TITLE
[Q&A]Papír alapon előállított, de elektronikus formában továbbított számla.

### ISSUE THREAD

**Issue by betasofthu** [nav-gov-hu/Online-Invoice#231]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Az adóhivatal szerint lehet-e elektronikusan továbbítani papír alapon előállított számlát?
Ezzel kapcsolatban miért változott az adóhatóság álláspontja?

Itt a PDF fájlként továbbított papíros számlára gondolok. A 2016-ban az adóhatósági ellenőrzési adatszolgáltatás sémájában a 23_2014_szamlasema.xsd-ben még ez szerepelt az "szla_forma" megadási lehetőségei között, de a 2020.04.16-án kiadott "Az elektronikus számlákkal kapcsolatos legfontosabb tudnivalók" című  anyagában már ezt elektronikus számlának minősíti. 

A séma ide vonatkozó része:
<xs:annotation>
<xs:documentation>Számla megjelenési formája: e-számla / EDI számla / papír alapon továbbított számla / papír alapon előállított, de elektronikus formában továbbított számla.</xs:documentation>
</xs:annotation>
A hivatkozott adóhivatali anyag linkje:
https://nav.gov.hu/nav/ado/afa/Az_elektronikus_szaml20200416.html?query=%22elektronikus+sz%C3%A1mla%22

**Comment by zsfoto** [comment]
Itt az is jó kérdés, hogy ha azonnal be kell küldeni a számla tartalmát, akkor minek kell digitálisan aláírni, minek kell hash kód stb? Hiszen a tartalma bent van már a rendszerükben. Bőven elég lenne egy egyszerűbb id, talán a tranzakció id is a lekérdezéshez. Vagy rosszul gondolom?

**Comment by NTCA-tax** [comment]
Itt több kérdés keveredik, megpróbálok mindegyikre választ adni.

Az elektronikus számla számlakibocsátási formátum, tehát számlakibocsátás időpontjában áll elő maga az elektronikus számla. Lehetséges papíralapú dokumentumból is elektronikus számlát készíteni, mellyel kapcsolatban speciális szabályokat tartalmaz a 23/2014 NGM rendelet. Tehát a papíralapú dokumentumból képzett elektronikus számla lehet akár önálló kategória is. Ebben az esetben a papíralapú bizonylat nem kerül kibocsátásra, hanem kizárólag elektronikus számla. 

Azzal, hogy a számla áfa törvény szerinti kötelező adattartalma bekerül az adóhivatalhoz, nem jelenti azt, hogy az adóhivatal rendelkezne a számlával. Az iratmegőrzés az iratmegőrzésre kötelezett adózó feladata, az adóhivatal mivel nem is rendelkezik az adott irattal, ezért azt nem is tudja megtenni helyette.

**Comment by zsfoto** [comment]
Ha az iratmegőrzésre kötelezett adózónál ellenőrzésre kerül az adott számla, akkor összevethető az abból a számlából beküldött tartalommal. Így a tételek, a végösszeg sem térhet el tőle. Ergo a megőrzött számla utólagos módosítása lehetetlen, azaz ellenőrzéskor kibukna.
Így a generált hash is egy ID lenne, amivel beazonosítható, hogy melyik számláról van szó. Ennek a hashnek keresném az értelémét, hogy más azonosítóval nem azonosítható be a számla, pl a tranzakció id-vel?
Ha pedig be van küldve a kötelező adattartalom, akkor akár már egy sajtpapírra is írhatnám a számlát, mert bent vannak az adatok, amik mindenhonnan lekérdezhetők.

**Comment by NTCA-tax** [comment]
Ne csak a számlakiállítóban gondolkodjál @zsfoto. A hash kódos megőrzés az iratmegőrzésre kötelezett vevőnek is egy választható módszer. Így a kiállított számlát mind az értékesítő, mind pedig a vevő ugyan azzal a technikával tudja védeni.

**Comment by betasofthu** [comment]
Már épp le akartam zárni a kérdést, de mégiscsak engedjetek meg egy megjegyzést.

Az általam feltett kérdés papíros számla PDF fájlban történő továbbítására vonatkozott és nem elektronikus számlára és nem a távnyomtatásos számlára és nem a beszkennelt papíros számlára. Újból ide írnám az adóhatósági ellenőrzési adatszolgáltatás sémájának ide vonatkozó részét:

xs:annotation
xs:documentationSzámla megjelenési formája: e-számla / EDI számla / papír alapon továbbított számla / papír alapon előállított, de elektronikus formában továbbított számla.</xs:documentation>
</xs:annotation>

Itt az elektronikus számla külön kategória az "e-számla", tehát a jogalkotó a "papír alapon előállított, de elektronikus formában továbbított számlát" nem elektronikus számlának tekinti, hanem egy külön kategóriának. Ez a kategória az online adatszolgáltatásban már elsikkadt, pedig ezt a körülményes távnyomtatás helyett lehetne alkalmazni.  **Miért jobb a papíron továbbított számla a PDF ben továbbított számlánál? Ha a jogalkotó létrehozta ezt a lehetőséget, akkor miért nem lehet használni?** Értem én az eredetiség követelményét, de a papíros számla sem eredetibb mint a PDF-ben továbbított papíros számla. Mint tudjuk, a papíros számlát sem kell aláírni, az nem lehet kifogás.
Nagyban segítené a gazdasági folyamatokat, ha ezt a lehetőséget használhatnánk, főleg a jelenlegi veszélyhelyzet idején. 

Elnézést a probléma további feszegetése miatt, de ezt még le kellett írnom.

**Comment by NTCA-tax** [comment]
A papíralapon készített, de elektronikus számlaként továbbított számla a jogszabályi rendelkezések miatt sikkadt el. @betasofthu amennyiben megnézed az NGM rendelet 17. § (2) b) pontját, akkor ott azt találod, hogy a papíralapú számláról a 451/2016. (XII. 19.) Kormányrendelet alapján kell hiteles elektronikus másolatot készíteni, majd ezt követően előállt elektronikus dokumentumot lehet megküldeni. Ezzel lényegében ugyan azokat a szabályokat kell alkalmazni, mintha egy papíralapú dokumentumból elektronikus másolatot készítenénk. Mivel ez nem túl valószínű nagy tömegű számlázásnál, ezért nem is tud ilyen megoldás elterjedni.

**Comment by nbeeps2** [comment]
@betasofthu: a simán PDF-ben elküldött számla gyakorlatilag a távnyomtatásnak felel meg. Ha megnézed a magyar számlázó szoftverek megoldásait (pl. Kulcs-Soft), akkor láthatod, hogy ez úgy néz ki, hogy egy linken keresztül letölti a vevő a PDF-et. Nos, ugyanez történik akkor is, ha simán e-mailben küldöd el a PDF-et, nincs közte semmi különbség. Mind a két esetben egy PDF töltődik le a vevő gépére, csak az egyik esetben egy böngészőn keresztül, a másik esetben pedig egy levelezőrendszeren keresztül, illetve ha valaki webmailt használ, akkor gyakorlatilag mindkét megoldásban a böngészőn keresztül jut el a PDF a vevő gépére. Az általad beidézett NAV állásfoglalás hibás, amiben több szakmai portál is foglalkozott, köztük az Önadózó is. Egyrészt nem is létezik sehol leírva olyan, hogy távnyomtatás... Másrészről egy számla van papír alapú lehet (NAV XML: PAPER) vagy e-számla (ELECTRONIC). Egy papír alapon kibocsájtott számla nem lehet elektronikus. Vagyis, kibocsájtod papír alapon a számlát, kinyomtatod, PAPER-ként jelented be, akkor az a büdös életben nem lesz már e-számla, küldheted akárhogy a vevőnek, hiszen az sincs sehol megszabva, hogy a vevő példányáért ő jön be személyesen, postán vagy futárral küldöd el, kiírod CD-re, pendrivere, elviszed neki személyesen, vagy e-mailben küldöd neki. Ez rajtad áll! A lényeg, hogy a vevő nyomtassa ki a saját példányát és papír alapon tegye el a könyvelésébe. A végeredmény egy A4-es lap lesz, amiről utólag lehetetlen is megállapítani, hogy postán jött vagy sem... Törvényi hivatkozás: az az elektronikus számla, amit elektronikusan bocsájtottak ki és fogadtak be. Mivel a Te esetetben, ha rögtön a kibocsájtás papír alapon történik (adatszolgáltatás is PAPER és ki is nyomtatod a számlát), akkor a törvényi feltétel első állítása nem teljesül, tehát nem beszélhetünk a továbbiakban elektronikus számláról. Minden más csak bullshit és nincs szakmai alapja!

**Comment by nbeeps2** [comment]
@betasofthu: ha szó szerint a (hibás) NAV állásfoglalás alapján akarsz eljárni, akkor pedig a PDF-ben elküldött számla e-számlának minősül. Ha nincs digitális aláírással ellátva, akkor üzleti eljárással kell hitelesíteni és a számlát a kiállítónak és a vevőnek is digitálisan kell megőriznie, de nem tiltott kinyomtatnia, sőt kinyomtatva is beteheti a könyvelésbe... Vagyis így is- úgy is küldheted PDF-ben a számlát a vevőnek. Én a nyomtatás mellett vagyok, mert egy kinyomtatott lap nehezebben veszik el, mint egy digitális adat, és utólag úgysem lehet bizonyítani egy A4-es lap "eredetét"...

**Comment by betasofthu** [comment]
@nbeeps2 : erről van szó. Tulajdonképpen ezt szerettem volna hallani NTCA-tax -tól.
