### ISSUE TITLE
[Q&A]Adószám nélkül, de 100eFt ÁFA tartalom fölött a magánszemélyek számláját is be kell küldeni 07.01-től?

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#232]
**Adószám nélkül, de 100eFt ÁFA tartalom fölött a magánszemélyek számláját is be kell küldeni 07.01-től?**
Tesztelem a programunkat, amennyire lehet minden variációban. Ha jól tudom a 100eFt áfa tartalom 7. hótól lemegy 0 Ft-ra, de idén csak azoknak akik adószámmal rendelkeznek. Aki nem rendelkezik adószámmal, magánszemélyek, azok számláival mi legyen? Mi legyen, ha 100eFt-nál nagyobb az áfa tartalma?
Egyelőre csak a TESZT-en dolgozom.
Csináltam egy beküldést és WARNING-gal hiányzó adószámra panaszkodott.

**Comment by NTCA-tax** [comment]
Egészen pontosan az adatszolgáltatási értékhatár eltörlésre kerül a jogszabályban 2020. július 1-től. Tehát adatszolgáltatásra kötelezett lesz az alanyi adómentes adózó által kiállított számla, vagy a belföldi fordított adózású számla is.

Az a szabály nem változik, hogy kizárólag belföldi adóalany által belföldi adóalanynak kiállított számláról kell adatot szolgáltatni. Amennyiben a magánszemély nem rendelkezik adószámmal, akkor ezen számlákat nem szabad beküldeni július 1-től. Az áfa törvény 2021. január 1-jén hatályba lépő változása teszi ezt majd kötelezővé. Tehát az adószám nélküli magánszemélyek esetében nem szabad a programodnak adatot szolgáltatni, függetlenül attól, mekkora összeg szerepel a számlán.

2020. július 1-től ugyanakkor a vevő adószámát a számlán fel kell tüntetni, amennyiben belföldi adóalany a vevő. Erre jelenleg 100 ezer forint áthárított adó esetében van kötelezettség. Tehát erre a változásra is érdemes a programodat felkészíteni.

A fentiek alapján működik a Warning funkció. A rendszer feltételezi a jogkövető magatartást, és azt, hogy ténylegesen csak belföldi adóalanynak kiállított számlákról történik meg adatszolgáltatás. Amennyiben az adatszolgáltatásban az áthárított adó összege meghaladja a 100 ezer forintot, akkor teljesen érthető a figyelmeztetés.

**Comment by zsfoto** [comment]
Köszönöm!
Így akkor a programunk a következő képpen működik:
Ha van adószáma vagy a dátum >= 2021-01-01, akkor felküldi.
Ha cég vagy intézmény a típusa, de nincs adószáma, nem készülhet neki számla csak adószám beírása után.

**Comment by NTCA-tax** [comment]
Egy kicsit azért árnyalnám ezt az optimista feltételrendszert.

2021. január 1-től hatályba lépő áfa törvény alapján a magánszemély neve, címe nem lehet része az adatszolgáltatásnak. Ez nem csak számlázó szoftver oldalán, hanem séma oldalán is jár változással.

A másik feltételrendszerrel kapcsolatban fontos megjegyezni, hogy vannak olyan intézmények, melyeknek nincs feltétlenül adószámuk. Erre jó példa a gazdasági tevékenységet nem folytató társasház, mely nem rendelkezik adószámmal, de nem is magánszemély. De például egy külföldi cég rendelkezik adószámmal, azonban a külföldi cég vevőnek kiállított számláról nem szabad adatot szolgáltatni.

**Comment by Macskafarka** [comment]
Érthetetlen ez az egész.
NTCA-tax írta: "Tehát adatszolgáltatásra kötelezett lesz az alanyi adómentes adózó által kiállított számla, vagy a belföldi fordított adózású számla is."
Azt nem értem, hogy ennek mi az értelme, különösen annak a fényében, hogy a NAV folyamatosan azt kommunikálja az ügyfeleink felé írásban ún."szakmai vélemény"-ként, hogy a befogadó oldalon NEM kell és nem is szabad az xx65M lapokra bekerülnie annak a számlára, amelynek az adótartalma 0.00 Ft.
Kibocsátó oldalon meg mennie kell annak is, aminek az adótartalma 0.00 Ft.
Mintha nem ugyanazt kellene tartalmaznia a két adatszolgáltatásnak. Fel nem tudom fogni azt, hogy miközben a SUP oldalon egyre bővítik az adatszolgáltatásba tartozó számlák körét, a befogadó oldalon meg az xx65M-nél szűkítik.
Meg tudná ezt nekem valaki magyarázni?

**Comment by NTCA-tax** [comment]
Jól látod @Macskafarka nem ugyan az a két adatszolgáltatás, de ez már 2018. július 1. óta így van. Az értékesítőnek a kiállított számláról kell adatot szolgáltatni, a 65M lapon pedig az adott időszakban levonásba helyezett számlák adatairól. Tartalmában és időben is eltér egymástól a két adatszolgáltatás.

**Comment by Macskafarka** [comment]
Akkor miért hangzik el a NAV részéről, hogy ellenőrzésképpen összefuttatják a két adathalmazt?
Mert nem ugyanazt tartalmazza.

**Comment by NTCA-tax** [comment]
A kettőnek van metszete, nem egymástól független adathalmazról beszélünk.

**Comment by zsfoto** [comment]
Mi van, ha a magánszemélyként nyilvántartott, de adószámmal rendelkezőről van szó (így felküldjük a számlát), de időközben megszűnt a vállalkozása és nekünk nem szólt. Így mi továbbra is toljuk fel a számlát a NAV rendszerébe, mert nálunk még van adószáma tárolva.

Kérdés: Ha pl megszűnt az ügyfél vállakozása, akkor milyen választ ad az adószám lekérdezés? Ha nem ad vissza, illetve üres választ ad vissza, akkor nem készítünk neki számlát és ennek utána kell járni.
Mivel csoportosan sok számla készül egyszerre így az adószám lekérdezéssel ezeket egyesével el lehet különíteni és utána kézzel megcsinálni nekik a számlát.

**Comment by Macskafarka** [comment]
Nemcsak az egyéni vállalkozóknak van adószámuk. Létezik olyan is, aki nem vállalkozó, de kért adószámot, ők az ún. adószámos magánszemélyek Pl. lakás bérbeadók)

**Comment by NTCA-tax** [comment]
Általános alapelv, hogy az értékesítőnek kellő körültekintéssel kell eljárnia, és a számla kiállításkor rendelkezésre álló információk alapján állítja ki a számlát. Amennyiben megszűnt vállalkozás nevére kéri a számlát a vevő, akkor úgy fogja kiállítani (nem kötelessége ellenőriznie a vevő által megadott adatok helyességét, persze azért a nyilvánvalóan valótlan adatokat kerülnie kell).

A fentiek alapján tehát ha egy magánszemély a megszűnt egyéni vállalkozói adószámára kér számlát, akkor az eladó arra a vevői adószámra fogja kiállítani és az adatszolgáltatás is megtörténik. Épp a napokban derült ki, hogy ha a nyilvántartásunkban szereplő, de már megszűnt adószámra kerül kiállításra számla (és így adatszolgáltatásra is), akkor jelenleg nem adunk erre warningot. Ezen még azért változtathatunk. Ugyanakkor az adószám lekérdezésnél a rendszer jelzi, hogy megszűnt az adószám.

**Comment by Macskafarka** [comment]
GDPR szempontból az ev. adatai nem védettek, a magánszemélyé védettek. Az adószámos magánszemély GDPR szempontból magánszemély.

**Comment by NTCA-tax** [comment]
Ne feledjük el, hogy az áfa törvény a belföldi adóalany vevő adószámának feltüntetését várja el, és ezzel tudja jelezni az adószámos magánszemély, hogy az adott ügyletben belföldi adóalanyként jár el. A törvény a belföldi adóalanynak kiállított számlák adataira vonatkozóan ír elő adatszolgáltatást, így nem a magánszemély személyes vásárlásai kerülnek át az adóhivatalhoz.

**Comment by NTCA-tax** [comment]
Már egy jó ideje erre az issue-ra nem jött új bejegyzés, így lezárom.
