### ISSUE TITLE
[Q&A]Nem felküldött számla jóváírása, ha nem volt adószáma mert ÁFA < 100eFt volt.

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#233]
**Nem felküldött számla jóváírása, ha nem volt adószáma és ÁFA < 100eFt volt.**
Mi van abban az esetben, ha a címben szereplő eset előfordult? Azaz, ha valamikor a múltban nem volt adószám rögzítve a cégnek kiállított számlához és az áfa tartalma sem volt 100eFt feletti. Tehát nem lett beküldve. Most viszont jóváíróval lerontanánk. megjelölésre kerül, hogy nem felküldött számlát rontanánk le, de azon nem volt adószám és azóta pótlásra került az ügyféltörzsben. A jóváíró számla és a számla eredője 0. Lényegében egy klónozó függvény mennyiség negálással és kereszt hivatkozás a számlaszámok között, keltezés, stb...
Így akkor nem lesz felküldve adószámmal a jóváíró számla? Na nem írok további bonyolító kérdéseket.
**Mi a helyes eljárás ebben az esetben?**

**Comment by NTCA-tax** [comment]
Számlával egy tekintet alá eső okirat esetén az Áfa törvény 170. §-a sorolja fel a kötelező adatokat. Itt nem találod meg a vevő adatait, ennek következtében a customerInfo sem kötelező elem. Amennyiben a vevő adatait nem érinti a változtatás, akkor az adatszolgáltatás befogadható vevőadat nélkül is. 

Az érvénytelenítő számlánál a vevőadatnak nem feltétlenül kell megegyeznie az eredeti számla vevőadataival. Például a vevő azóta átalakulhatott, megváltozhatott a neve stb. Az érvénytelenítő számla önálló számlatípus, nem feltétlenül az eredeti számlának az ellenkező előjelű másolata.
