### ISSUE TITLE
[Q&A]Hibás vagy nem létező adószámra WARNING. Mekkora probléma ez?

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#234]
**Hibás vagy nem létező adószámra WARNING. mekkora probléma ez?**
Eddig csak a tesztre küldtem be számlákat. Volt olyan eset, amikor az adószám valami miatt nem volt jó. Például nem létezett, vagy egy számjeggyel több volt benne vagy kevesebb...
WARNING jött ezekben az esetekben. Ez mekkora probléma?
Volt olyan is, amikor létező adószámról van szó, de a teszt adatbázisában nincs benne, nem tuzdom lekérdezni sem.

Így a számla kiállítás előtt inkább lefuttatok egy lekérdezés és ha nem ad eredményt, akkor nem lehet számlát készíteni az ügyfélnek.

**Comment by NTCA-tax** [comment]
Az értékesítőnek a rendelkezésre álló információk, adatok alapján kell a számláját kiállítania. Tehát ha a vevője hibás adószámot ad meg, akkor azzal a hibás adószámmal megtörténik az adatszolgáltatás. Az értékesítő a warning alapján értesül erről, és a tőle elvárható módon kell korrigálnia. Amennyiben egyszeri vevőről volt szó, akkor ezt nem nagyon tudja, viszont állandó partner esetén elvárható.

A számla kiállítását megelőző lekérdezés futtatása egy jó módszer lehet a hibák elkerülésének. Ugyanakkor ha éppen nincs internet és készpénzben fizet a vevő, akkor késedelem nélkül szükséges a számlát kibocsátani. Üzemzavar esetén az adatszolgáltatás lehet későbbi is, de a számla kibocsátása nem. Amennyiben ilyen eset előállhat, akkor óvatos lennék az ilyen feltételek beégetésével.
