### ISSUE TITLE
[Q&A]Számla technikai érvénytelenítése! Nem tudom újból felküldeni az adott számlaszámú számlát

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#235]
**Számla technikai érvénytelenítése! Nem tudom újból felküldeni az adott számlaszámú számlát.**
Kérdezni szeretném, hogy miért nem megy a számla újbóli felküldése. Számlaszám: 1000008989, a tranzakció id: **2Z806U241A4KK66P**. A technikai érvénytelenítésről megjelent egy rekord a webes felületen, ami az adott számlaszámra hivatkozik. Ennek a tr. id-je: **2Z85XCFEKUN5IORU**.
Megpróbáltam ismét felküldeni ugyanavval a számlaszámmal és hibával jött vissza, hogy már fel lett küldve. **Hogyan tovább?**
Köszönöm

**Comment by topybear** [comment]
A technikai érvénytelenítést jóváhagytátok a webes felületen?

**Comment by NTCA-supporter** [comment]
Szia @zsfoto!

Igen, az lesz a probléma, hogy még nem lett jóváhagyva a technikai érvénytelenítés.
Nem elég csak beküldeni interfészen, azt a felületen jóvá is kell hagyni, hogy az adott számla/számlák valóban technikai érvénytelenítve legyenek. Ezt a Nyilatkozatok/Technikai érvénytelenítések menüpontban tudod megtenni.
Ezután lehetséges a számlaszám újbóli felhasználása.

Üdv

**Comment by zsfoto** [comment]
Köszönöm.
Nézném.
Lehetséges, hogy most nem elérhető/áll a teszt?

**Comment by NTCA-supporter** [comment]
Igen, most volt egy karbantartás, indul az alkalmazás.

**Comment by zsfoto** [comment]
Azt olvastam a dokumentációban, hogy nem feltétlenül kell tudnia a számlázó programnak a technikai érvénytelenítést. De javasolt, hogy ha egyszerre sok számlát kellene érvényteleníteni. Ha ezt a webes felületen jóvá kell hagyni, akkor ott ugyanúgy egy lassú megoldásról beszélünk. Vagy van ennek egy gyorsabb megoldása is nagy mennyiségű számla esetén?

**Comment by NTCA-supporter** [comment]
Szia!

Az interfész dokumentáció 2.4.1 fejezetét ajánlom figyelmedbe.
Abból is ami fontos számodra:
"Technikai érvénytelenítés a /manageAnnulment operáción keresztül történik úgy, hogy a legfeljebb
100 darab annulmentOperation elem mindegyike technikai érvénytelenítést tartalmaz. A belső base64
tartalomnak az invoiceAnnulment sémaleíróban definált elemeket kell taratalmaznia, A séma nem
enged meg egy műveleten belül technikai érvénytelenítést és „eredeti” adatszolgáltatást vegyesen
benyújtani."

Tehát egy beküldésben 100 annulmentOperation csomópontot tudsz beküldeni, ezzel lehetséges a tömeges technikai érvénytelenítés.
A felületen magát a beküldést bírálod el (hagyod jóvá/utasítod el), tehát a max. 100 technikai érvénytelenítést csak egyszer kell jóváhagynod, nem pedig számlánként.

Remélem tudtam segíteni.

Üdv

**Comment by zsfoto** [comment]
Igen, köszönöm

**Comment by NTCA-supporter** [comment]
Szia @zsfoto!
Itt van még kérdés, vagy zárható az issue?
Köszi!

**Comment by zsfoto** [comment]
Igen, lezárható.
Hálás köszönetem.
Zs.

**Comment by robozb** [comment]
Köszönöm az infót én is!
