### ISSUE TITLE
[Q&A]Érvénytelen áfakód. Vevő áfakódja nem lehet 4-es.

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#236]
**Érvénytelen áfakód. Vevő áfakódja nem lehet 4-es.**
Tesztelem a rendszerünk és erre a cím béli hibát adta vissza.

Mi lehet az oka?

A [Cég](https://www.ceginformacio.hu/cr9310001564)

**Comment by betasofthu** [comment]
Nem helyes a csoportos áfa  alanyok részére 4-es áfa kóddal számlát kiállítani.

Csoportos adóalanyiság esetén a 4-es áfa kód az adószámban
(pl.:12345678-4-12) figyelmeztető üzenetet kap ("Érvénytelen ÁFA kód."), de
befogadják.
Azért kap figyelmeztetést, mert a vevő adószámában az 5-ös áfa kódot kellet volna szerepeltetni, a hozzá tartozó első 8 számjeggyel. Ugyanis ez a csoport adószáma, a számlát erre kell kiállítani. A csoport tagjának adószáma 4-es áfa kódot tartalmaz. Ezt szerintem nem kötelező feltüntetni a számlán, és nem is kell leadni az online számla-adatszolgáltatásban.

Az 5-ős áfa kódú csoport azonosító számot kell az adószám helyére írni. Ez nem egyezik meg a tag adószámával. 

Az áfa törvény 169. § d) dc) alapján a csoportos áfa alanyok esetén nem a
vevő adószámát, hanem a csoport azonosító számát kell feltüntetni
(pontosabban annak első nyolc számjegyét, ha 100 ezer forint felett van a
számla áfa tartalma)
https://net.jogtar.hu/jogszabaly?docid=A0700127.TV
169. § *  A számla kötelező adattartalma a következő:

dc) *  adószámának vagy csoportos általános forgalmiadó-alanyiság esetén
csoportazonosító számának első nyolc számjegye

Az adóhivatal honlapján ellenőrizhető a csoportos áfa alanyok adószáma:
http://www.nav.gov.hu/nav/adatbazisok/adatbleker/csoportos_afaalanyok

Az adóhivatal honlapján nem, de itt találtam információt erről:
http://konyveloleszek.hu/?q=content/ami-az-ad%C3%B3sz%C3%A1mb%C3%B3l-kiolvashat%C3%B3-i


Általános tapasztalat, hogy a vevők mind a csoportos adóalanyi tag
adószámát, mind a csoport azonosító számát is kérik feltüntetni a számlán.
Csak a csoport azonosító feltüntetése kötelező. A két szám első nyolc
számjegye is eltérő, tehát a csoportos adóalannyá váláskor nem elegendő az
áfa kód átírása.

**Comment by Macskafarka** [comment]
Osztom betasofthu jogértelmezését. Az ügyfelek többsége nem gondolja át ennyire szofisztikáltan.

**Comment by zsfoto** [comment]
Köszönöm a részletes infót

**Comment by NTCA-supporter** [comment]
Szia @zsfoto!
Előttem elég jól összefoglalták.
Kiegészítésként és megerősítésként interfész doksi 75. oldal alja pont ez az eset.
"A szállító (eladó) adatai között a számlán kötelező feltüntetni azt az adószámot, ami alatt a gazdasági
esemény történt (supplierTaxNumber elem, típusa: TaxNumberType). Amennyiben az eladó csoportos
áfa-alany, akkor – az Áfa törvény előírásainak megfelelően – az eladó a csoport. A csoporttag
adószámát pedig a groupMemberTaxNumber elemben (típusa: TaxNumberType) kell feltüntetni,
amennyiben ez szerepel a számlán. A szállító közösségi (uniós) adószáma pedig a
communityVatNumber elemben (típusa: CommunityVatNumberType) szerepeltethető, ha az szerepel
a számlán. "

Zárhatom az issuet?
Köszi!

**Comment by zsfoto** [comment]
Igen zárható.
Nagyon köszönöm a segítséget.
