### ISSUE TITLE
Kerekítési probléma

### ISSUE THREAD

**Issue by Kivancsikonyvelo** [nav-gov-hu/Online-Invoice#237]
Egy módosító számla beküldésekor kaptunk validálási figyelmeztetést, annak ellenére, hogy mi úgy látjuk, hogy a beküldött fájl megfelel a specifikációban lévő szabályoknak. 
A figyelmeztetést egy olyan módosító számla esetén kaptuk amely több eredeti számlára is hivatkozik. A figyelmeztetés csak az egyik hivatkozás esetén jelent meg.  (4. Batchindex)
![image](https://user-images.githubusercontent.com/51188923/83523586-b1286480-a4e2-11ea-9852-8ff40f90ed44.png)
A figyelmeztetés a specifikáció alapján az alábbiakat jelenti:  
![image](https://user-images.githubusercontent.com/51188923/83523648-c604f800-a4e2-11ea-859e-81febb6d9789.png)
A figyelmeztetés specifikációja alapján úgy értelmezzük, hogy a kerekítésből adódó tolerált eltérés a vatRateNetAmountHUF mező 1 %-a. Az alábbi képen illetve a csatolt xml fájlból látható, hogy ebben az esetben a vatRateNetAmountHUF = -292. Ennek az 1 %-a: -2,92

A vállalatirányítási rendszer amelyből a számla kiállításra került, a kerekítési beállítása alapján a vatRateVatAmountHUF mező értékét -80-ra kalkulálta ki.   Ha a beküldött vatRateNetAmountHUF alapján kalkuláljuk az áfát, akkor az -78,84. A beküldött  vatRateVatAmountHUF és a kalkulált érték között a különbség: -1,16, ez szerepel a figyelmeztetésben is, viszont a specifikáció alapján ennek az értéknek az abszolutértéke a tolerált eltérésnél kisebb. 
A hibaüzenet okára két lehetséges megoldást látunk: 
-	A negatív előjel miatt ez nem kisebb, hanem nagyobb matematikailag ez az érték -> ez a validáció hibájára utal számunkra. 
-	Vagy nem arra mezőre történik a validáció ami a specifikációban szerepel. (vatRateNetAmountHUF) Mert ha például a vatRateVATAmountHUF-ra történik a validáció akkor ez az érték valóban nagyobb abszolútértékben is a vatRateVATAmountHUF 1%-ánál. 
![image](https://user-images.githubusercontent.com/51188923/83523703-dcab4f00-a4e2-11ea-8dff-9a9438763f5d.png)
A kérdésünk az lenne, hogy jól látjuk-e a probléma okát? Milyen megoldást javasolnak bármely eset fennállása esetén?  
Köszönöm

**Comment by NTCA-supporter** [comment]
Szia @Kivancsikonyvelo !
Utánanézünk a problémának, hogy melyik oldalon van a turpisság.
Tudsz küldeni egy request_id-t/transaction_id-t, és azt, hogy melyik környezeten tapasztaltad?
Köszi!

**Comment by KMGY100** [comment]
Csak egy gondolat:
Az 1%  illetve az 1 egység tolerál,t eltérés az eredményértékre vonatkozik, 
vagyis a -292,00  27%-os áfája -78,84    és   erre vetített 1 % lehet az eltérés
vagyis a max eltérés -0,7884  lehet .
-78,84
-00,7884
----------
-79,6284      vagyis   a   -80   áfaösszeg  kilóg az 1% engedélyezett eltérésből.
(egyébként hogyan lehetett 80 az áfa ha kerekítve is csak 79 )

**Comment by Kivancsikonyvelo** [comment]
A bejelentés az éles környezetben történt. 
A tranzakció azonosító: 2Z0R9M4U2MFO6E70
A requestid: 2be5c6a2ca48b0bd2afcb956224dec. 

Köszönöm

**Comment by NTCA-supporter** [comment]
Szia @Kivancsikonyvelo!
Utánanéztem pontosan.
Így számolunk:
|(vatRateNetAmountHUF * vatRate) - vatRateVatAmountHUF| / |vatRateVatAmountHUF|

Tehát valóban nem a vatRateNetAmountHUF érték 1%-a a megengedett, hanem a vatRateVatAmountHUF abszolútértékének 1%-a.
Ezt javítjuk majd az interfész dokunmentációban, köszönjük a jelzést.
Ha nincs több kérdés, kérlek zárd az issuet.
Üdv

**Comment by NTCA-supporter** [comment]
Szia @Kivancsikonyvelo !
Van még kérdés?
Köszi
