### ISSUE TITLE
[Q&A]Módosító okirat 1.1 verzióban található számlára

### ISSUE THREAD

**Issue by MTYS87** [nav-gov-hu/Online-Invoice#238]
Sziasztok,

egy kérdés merült fel, mi lesz azokkal a módosító számlákkal melyek 100.000 HUF-ot meg nem haladó áfatartalmú számlára hivatkoznak? Jelenleg ezekre nem vonatkozik az adatszolgáltatás, azonban július 1.-től ha módosítás szükséges, csak a módosító számláról tudunk adatot szolgáltatni és hiányolni fogja az eredeti számlát.

**Comment by topybear** [comment]
A modifyWithoutMaster flag itt is játszik.

**Comment by NTCA-tax** [comment]
A kérdést alapvetően @topybear megválaszolta. A modifyWithoutMaster=true esetében lehet adatot szolgáltatni olyan számlával egy tekintet alá eső okiratról, melynek az alapszámlája nincs az adatszolgáltatási rendszerben jogszabályi kötelezettség hiányában.

**Comment by MTYS87** [comment]
Köszönöm a választ!
