### ISSUE TITLE
[Q&A] Bolti vásáráláskor ÁFÁ-s számla kérése és pénztárgép viszonylata

### ISSUE THREAD

**Issue by zonehun** [nav-gov-hu/Online-Invoice#239]
Talán ez a kérdés itt még nem merült fel, de tőlünk több, kiskereskedelmi egységgel rendelkező ügyfelünknél is előjött. 

A beküldési limit 0-ra csökken július 1-től, így minden kisker értékesítést is be fogunk küldeni az Online Számla rendszerbe, ahol ÁFÁs számlát kér a vásárló (pl. egy pár cipő). Mivel kiskerről beszélünk, így ők a számlát kiállítják, de beütik a pénztárgépbe is, hiszen pl. a kasszának ki kell nyílnia, hogy visszajárót adhassanak.

Okoz az bármiféle gondot, hogy az ilyen eladások:
- egyszer bemennek az Online Számla rendszerbe,
- plusz még egyszer bemennek a pénztárgépek adatait fogadó rendszerbe is?

A válaszokat előre is köszönöm!

**Comment by nbeeps2** [comment]
Már "ezer éve" nem szabad így csinálni, ez egy nagyon régi gyakorlat! A vevő vagy számlát vagy nyugtát kell kapjon. Ha számlát kér, NEM SZABAD (TILOS!!!) beütni a pénztárgépbe!!!

**Comment by NTCA-tax** [comment]
Az Áfa törvény alapján az áfa hatálya alá tartozó termékértékesítésről, szolgáltatás nyújtásról számlát VAGY nyugtát kell kiállítani. Amennyiben az adózó pénztárgép használatára kötelezett, akkor a nyugtaadási kötelezettségének pénztárgép használatával tehet eleget.

A fentiek alapján hibás az a gyakorlat, hogy értékesítésnél mind számla, mind pedig pénztárgépi nyugta kiállításra kerül. Ez az adóhivatali elemzéseket is félreviszi, mivel egy tranzakcióról bejön hozzánk pénztárgépi és számla adat is. Így előfordulhat, hogy hibás következtetéseket vonunk le az adatszolgáltatások alapján.

Amennyiben adózó ragaszkodik minden bevételének pénztárgépi rögzítéséhez, akkor ehhez használhatja a "nem adóügyi bizonylat"-ot is, vagy olyan gyűjtőt, melyben az egyéb pénzmozgásokat  tartja az adózó nyilván.

**Comment by zonehun** [comment]
Köszönöm a válaszaitokat!
