### ISSUE TITLE
[FEATURE] Automatikus fókusz - nagyon apróság

### ISSUE THREAD

**Issue by Csomb** [nav-gov-hu/Online-Invoice#240]
Meg tudnátok csinálni, hogy az Online Számlázóban sablon betöltés gombra kattintva sablon megnevezés mező (ahova gépelni kell) automatikusan megkapja a fókuszt.

Köszi előre is!

**Comment by NTCA-supporter** [comment]
Szia @Csomb !
Köszi a jelzést, valóban lehetne rajta finomítani. Igyekszünk beütemezni, ahogy a címben is előre jelezted, alacsony prioritással :)
Üdv

**Comment by NTCA-developer** [comment]
Szia @Csomb 

Az igény befogadva a linkelt ticket alatt.
