### ISSUE TITLE
[FEATURE]Elektronikus számlák támogatása

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#241]
A számlák hash-ének támogatása segítheti az elektronikus számlázást (főleg ha egy másik issue-ban leírt probléma, a módosító számlák hash-ének kezelése is megvalósul).
De szerintem kellene egy kis segítség a használhatósághoz.
Az kellene, hogy ha a vevő kap egy számlát elektronikusan, akkor ellenőrizni tudja, hogy az sértetlen, megegyezik az eredeti számlával. Ehhez kellene egy olyan lehetőség, hogy az online számla oldalon megadva a számlát (pl. pdf) az kiszámolja a hash értékét és összehasonlítsa azt a tárolt hash értékkel. Az eredmény (OK - not OK) jelezné a vevőnek, hogy valódi számlát kapott.

**Comment by fenyvessy** [comment]
Elméletileg az ellenőrzést automatikusan meg tudod csinálni már most is, hiszen befogadói oldalon le tudod kérni a számodra kiállított számla adatait, amiben elméletileg szerepelhet az electronicInvoiceHash is. Sokkal jobb megoldásnak (és főleg könnyebben automatizálhatónak) tartom az ilyen eredetiség ellenőrzést, mint a PDF-be ágyazott elektronikus aláírást (főleg nem-windows környezetben). 
PDF fájlokat feltöltögetni meglehetősen előforráspazarló lenne, de pl. a https://www.w3.org/TR/WebCryptoAPI/ -val böngészőben is megcsinálható platformfüggetlenül, mint pl. ahogy ez is működik: https://md5file.com/calculator
Most már csak az kellene, hogy minél többen kezdjék el használni az ITM rendelet 7. ṗaragrafus szerinti megőrzést, hogy általánosan elfogadott és elterjedt legyen, mert most még elég furcsán néznek rám, ha megemlítem....

**Comment by kabelnet2** [comment]
Egyetértek és nem értek egyet. Természetesen meg lehet csinálni. De itt a túloldalon könyvelők vannak, ők kapják a számlákat, nekik kell ellenőrizni. Ennek egyszerűnek kellene lenni, számítástechnikai ismeret nélkül is elvégezhetőnek. Azután ott van a bizalmi kérdés is. Ha én adok egy programot, akkor felmerül, hogy az csak kiírja, hogy OK. Ha a NAV ad ki egy megoldást, azt sokan elfogadják. És jobb lenne egy ellenőrző lehetőséget használni, minthogy mindenki fejleszget saját megoldást.

**Comment by omachtandras** [comment]
> 
> 
> Egyetértek és nem értek egyet. Természetesen meg lehet csinálni. De itt a túloldalon könyvelők vannak, ők kapják a számlákat, nekik kell ellenőrizni. Ennek egyszerűnek kellene lenni, számítástechnikai ismeret nélkül is elvégezhetőnek. Azután ott van a bizalmi kérdés is. Ha én adok egy programot, akkor felmerül, hogy az csak kiírja, hogy OK. Ha a NAV ad ki egy megoldást, azt sokan elfogadják. És jobb lenne egy ellenőrző lehetőséget használni, minthogy mindenki fejleszget saját megoldást.

Ezért vetettem fel egy issue-ban, hogy a NAV részt vehetne a folyamatban, mintegy közvetítőként tárolhatná x ideig a pdf-et. amit akár egy szoftver, akár a felületen az ügyfél letölthetne.
Ekkor a NAV oda tehetné mellé a pipát, hogy ok, a beküldött hash és a beküldött pdf hash-e egyezik.
Mindenki jól járna. Aki automatizálni akar, az könnyen megtehetné egy standard interface-en, aki meg csak annak hisz, ha látja a NAV oldalán a zöld pipát, az nézegethetné és megnyugodhatna.

Nyilván nem várható el a végtelen tároló kapacitás a NAVtól, de egy rövidebb idejű tárolás nagyon sokat segítene.

**Comment by fenyvessy** [comment]
A NAV-os tárolással szerintem adatvédelmi problémák is előjönnének. Konkrétan arra gondolok, hogy ha majd már a magánszemélyeknek kiállított számlákról is megy az anonimizált adatszolgáltatás, akkor a feltöltött számlaképen rajta lesznek a személyes adatok.
De ettől függetlenül arra is kellene megoldást találni, hogy az adatszolgáltatásra nem kötelezett számlák esetén hogyan lehetne ezt a fajta megoldást használni a hitelesség biztosítására.

**Comment by omachtandras** [comment]
Az adatvédelmi problémákat meg lehet oldani, NAV oldalon (is) vannak jogászok.
Első körben szerintem rengeteg kisebb cégnek, amelyeknek a teljes kiállított és befogadott számláinak körét lefedni a beküldési kötelezettség alá tartozó számlák halmaza nagy előrelépés lenne ez a megoldás.
És jó eséllyel ők azok, akik ma papír alapon küldözgetik a számlát, mert a digitális archiválási megoldások drágák nekik, a számlák darabszáma pedig nem túl magas, így professzionális megoldások felé sem tudnak elmozdulni, viszont van legalább egy számlázó + könyvelő programjuk (vagy a könyvelőjük programmal könyvel), amelybe azért elfogadható ráfordítással beépíthető lenne egy ilyen megoldás támogatása.

Középtávon pedig várhatóan úgyis jelentős változások lesznek (ahogy a korábbi jegyemben a navos kolléga jelezte is, hogy ők is gondolkodnak különböző megoldásokon a számlakép elfelejtésére), amelyek akár ki is szoríthatják teljesen a papír alapú, de akár a pdf számlaképpel megvalósuló számlázást.

**Comment by nbeeps2** [comment]
Sajnos a PDF-et muszáj lenne "pluszban" valahol eltárolni, mert nem lehet rábízni, hogy majd a kiállító vagy a vevő megőrzi. Ilyen szempontból verhetetlen a papíros megoldás előnye, mert sokkal kisebb eséllyel veszik egy papír alapú számla (ha mégis, újra lehet nyomtatni), mint egy e-számla, ami viszont már utólag nem reprodukálható, mert a hash megváltozna... Erre is lehetne megoldást keresni, hogy nem a PDF-re kéne hash-t generálni, hogy egy elveszett PDF-t bármikor újra elő lehessen állítani kiállítói oldalon. Szerintem még egyszer át kéne gondolni mélyen ezt az e-számla dolgot, a kulcs valahol ott van elásva, hogy a számla be megy a NAV-hoz, ilyen téren a fontos adatok sérthetetlensége biztosított és nem a PDF-el kéne foglalkozni, amit ha újra előállítok, mert elveszett, akkor eltérne a hash-e...

**Comment by nbeeps2** [comment]
Egy kis magyarázat ehhez: "nem lehet rábízni, hogy majd a kiállító vagy a vevő is megőrzi". Itt nem a rosszhiszeműségre gondolok, épp ellentétesen. Mit fog csinálni egy átlag user (főleg kiállító oldalon)? Kiállítja az e-számlát, a letárolt PDF meg ott lesz a merevlemezén, őrzi azt ő becsülettel... Csak hogy vírusos lesz a gépe vagy tönkremegy a vinyó vagy ellopják a gépet, stb. Utána pedig ott lesz meglőve, hogy nincsenek meg sehol a számlák. Papír alapú számlázásnál ilyenkor nem volt gond. Újratelepíti a programot, beállít egy kezdősorszámot és folytatja a számlázást. E-számlánál ilyen esetben mit tud tenni? Pl. Most Június 4-van, kiállítottam már 50 db e-számlát, a könyvelőnek majd csak júliusban fogom leadni, addig a gépemen tárolom, de beüt a krach. Mit tudok csinálni? Ezért kéne ehhez másképp hozzáállni és újra gondolni, ha júliustól úgyis bemennek ezek a számlák a NAV-hoz, az miért nem elég?

**Comment by kabelnet2** [comment]
Azért a mentést már feltalálták :)

**Comment by attilagyurman** [comment]
Szerintem egy vállalkozásnak eleve van csomó olyan adata (legyen bármennyire kicsi) amit őriznie kell digitálisan.
Ha valóban van ilyen vállalkozó ahogy leírod, az felelőtlenség.
Ha elveszti a számlázó program adatbázisát, akkor hogy fog a törvényben előírt nav XML-t generálni ellenőrzés esetén?

Mini vállalkozó: tárolja gépén + felhőszolgáltató tárhelyén, máris nem veszik el. Vagy használjon online számlázót, és nincs gond a tárolással.
Kisvállalkozó: vegyen egy NAS-t, ne a gépén tároljon a cég működéséhez szükséges adatokat.

**Comment by topybear** [comment]
Azért e-számlát a megfelelő informatikai háttér nélkül kiállítani finoman szólva is felelőtlenség, tekintettel a szabályozás által a megőrzési kötelezettséggel kapcsolatosan rögzített alapelvekre: a kiállító a megőrzési kötelezettség lejártáig folyamatosan köteles biztosítani az elektronikus dokumentumok megőrzését oly módon, hogy
–    kizárja az utólagos módosítás lehetőségét
–    védi az elektronikus dokumentumokat a törlés, a megsemmisítés, a véletlen megsemmisülés és sérülés, illetve a jogosulatlan hozzáférés ellen
–    biztosítja a teljes megőrzési idő alatt az értelmezhetőséget (olvashatóságot)
Úgyhogy aki erre akar átállni, annak szerintem igen alaposan át kell gondolnia, hogy ezt meg tudja-e ugrani saját infrastruktúrával, vagy inkább fizet egy erre szakosodott cégnek, aki a fentebb leírtakat a megfelelő garanicákkal vállalni tudja. Vagy marad a papír alapú megoldásnál.

**Comment by Rossi73** [comment]
... korábban már felvetettem én is hasonló kérdést a NAV-nál, miszerint mi van akkor, ha egy helyi gépen tárolt adatbázis tönkremegy? Mit tegyen az adózó? Töltse vissza az előző napi mentést, és vigye be újra ugyanazokat a számlákat? Vagy töltse vissza az előző napi mentést, de hagyja ki őket, és kezdjen új tartományt? A válasz az volt, hogy folyamatosan legyen archiválva az adatbázis, mert csak úgy felel meg a jogszabálynak. Ha tehát helyi adatbázisban tárolja a számlákat egy offline számlázó programmal, csak akkor jár el helyesen az adódó, ha **minden** egyes számla kiállítása után archiválja a teljes adatbázist. Az sem számít, ha abban az adatbázisban van egy csomó, a számlázástól független adat, és mondjuk 3 GB a mérete. Akkor is archiválni kell minden számla kiállítása után. Mert a krach beüthet csütörtök délután 3-kor is, és akkor máris nincs meg a csütörtökön 8:00-15:00-ig tömegesen kiállított mondjuk 300 db számla. De ha előrelátóan, és a jogszabályt szem előtt tartva, **minden számla kiállítása** után archiválta a 3 GB-nyi adatbázist (mert bármi okból nem tudja szétválasztani, vagy nem akarja csak táblánként, mert összefüggések vannak bizonyos táblák között, ezért a teljes adatbázist kell archiválnia ahhoz, hogy sérülés esetén mindent vissza tudjon állítani megfelelően), akkor nincs probléma... Ezt a választ kaptam... _(igaz, ez a számítógéppel kiállított, de papír alapú számlákra vonatkozott, de logikailag talán ide is tartozik)_

**Comment by nbeeps2** [comment]
@rossi73: papír alapú számlánál a számlát papír alapon kell megőrizni. A mi ügyfelkörünkben heti rendszerességgel fordul elő, hogy az ügyfél gépét ellopják, tönkremegy, vírusos lesz, hasonlók. Újratelepíti a programot, beállítja a kezdősorszámot és számláz tovább, minden számla meg lesz papíron. Az, hogy nincs meg a gépben az nem akkora probléma. Az AEA XML ilyenkor nem küldhető, de a NAV ha akarja a számlát papíron tudja ellenőrizni. Ez így megy amióta világ a világ, szóval ez nem gond, semmi változás nem történt e téren.

**Comment by nbeeps2** [comment]
@kabelnet2, @attilagyurman  @topybear: Egy átlagos felhasználó nem olyat, amit Te leírtok. Igen, úgy kéne eljárni, ahogy Ti leírtátok, de a gyakorlatban ez NEM FOG megtörténni. Kiss Pista e.v. rohadtul nem ért a számlázáshoz, az e-számlázához pláne nem, de nem akar a postára járni, szóval e-számlázni fog, amint teheti. Nem fog NAS-t használni (az se tudja mi az, de a NAS is tönkre tud menni...), nem fog felhőbe menteni (szintén nem vágja hogy is van), a legjobb esetben max. pendrivera másolgatna, de ahhoz meg link, nem jut eszébe, vagy nem napi szinten az is tuti. Ez nem fikció, én ezzel foglalkozom, látom, köztük élek. Igen, a törvény és a szabályok nem ismerete nem mentesít az alól, ez is ok.  Viszont ettől még az lesz, amit írok. Kiállítja a kis e-számláját, ott lesz a gépén a PDF, majd egyszer valamikor kakukk lesz a gépének és tömegek fognak így járni, ahogy most is heti rendszerességgel több alkalommal járnak így ügyfeleink, csak a papír alapú számlázásnál ez nem (akkora) gond. Erre lehetne megoldás, ha a NAV-nak beküldött számla, XML, PDF, bármi, megfelelne már mindennek és ha a kiállítói vagy befogadó oldalon adatvesztés van, akkor az már önmagában elég legyen, hogy ott a NAV-nál minden fontos infó. A PDF-et nem erőltetném, mert feleslegesen nagy a mérete és senkit nem érdekel, hogyan nézett ki a számla, milyen volt rajta a logó, mekkora volt a margó, milyen volt a betűtípus. A számla adattartalma a lényeg, ahhoz meg nem kell PDF...

**Comment by nbeeps2** [comment]
@attilagyurman: sokkal több nem online számlázó létezik, mint online, nekik is kell megoldás... ;) Nagyon sokan utálják az online számlázót, ráadásul sok esetben buták, lassúk és nehézkes a kezelésük, mert böngészőben futnak, és messze elmarad egy desktop rendszer tulajdonságaitól, de ebbe most ne menjünk bele, adatmegőrzés tekintetében igazad van, hogy az megoldás erre.

**Comment by kabelnet2** [comment]
@nbeeps2: részemről nem kívánom a világ összes számlázási problémáját megoldani ezzel a hash lehetőséggel, sőt még az online számlázással sem. A hozzászólók szerintem nagyon elszaladtak - de hát ez mindenkinek joga. Én csak annyit szeretnék, ha a VEVŐ-k tudnák használni ezt a lehetőséget (a nem számítástechnikusok is) és így lehetővé vállna elektronikus számlák küldése ezzel a lehetőséggel (vagyis a vevő ellenőrizni tudja, hogy a kapott számla hiteles). A számlák tárolása más dolog,azt szerintem nem az online számla keretében kell megoldani. Ennyi és nem több miatt indítottam ezt az issue-t.

**Comment by topybear** [comment]
@nbeeps2 Szerintem annyira azért nem lehet egységsugarú az a user, aki e-számlát akar csinálni, hisz szerződnie kell hitelesítés szolgáltatóval, ahol szerintem/reményeim szerint kellően "ráijesztenek" a megőrzéssel kapcsolatban. (Ha másért nem, marketing okokból: hátha megőrzésre is szerződnek velük). Szerintem egyébként ha meglátja ennek a költségeit, technikai feltételeit, hát lehet, hogy inkább marad papír alapon, vagy mégis inkább online számlázót választ - most úgy látom, inkább azoknak éri meg e-számlára váltani saját hatáskörben, akik nagy tömegben számláznak.
Ha a NAV-os fiúknak sikerülne a beküldött xml-t elektronikus számlaként elismertetni (ami egyébként baromi jó lenne), sajnos az sem oldaná meg az alapproblémát, azaz hogy az eredeti példány megőrzéséért a kiállító felel. Szerintem ahhoz, hogy a NAV adatszolgáltatás ezt - akár csak vis major esetén - kiváltsa, jogilag elég sok mindent kellene alátenni.

**Comment by nbeeps2** [comment]
@topybear: " aki e-számlát akar csinálni, hisz szerződnie kell hitelesítés szolgáltatóval": ez egy téves információ, egyáltalán nem kell szerződnie. Ma már az is elektronikus számlának számít a NAV állásfoglalása alapján, ha simán csak úgy (aláírás, időbélyegző) nélkül átküldök egy PDF számlát a vevőnek e-mailben.

**Comment by attilagyurman** [comment]
Ez értem, egy közepes KKV-nál már ez érv. De ott már kell is lennie backup-aak. De egy naponta max 1-2 számlát kiállító EV-nek nem hinném hogy körülményesebb egy böngésző, mint a vastag kliens telepítése. Főleg ha kockáztatja az adatvesztést.

**Comment by attilagyurman** [comment]
Ahogy írod is, nem mentesíti. Majd az első adatvesztés után (és esetleges NAV büntetés után) vesz NAS-t…. Egy google drive használata sem hinném hogy túl nehéz annak aki ki tud állítani egy számlát.

Nem akarom védeni a NAV oldali fejlesztőket, de ha egy funkciót fejlesztenek, az ne a link vállalkozók miatt legyen. Ez Kb. az a kategória, mint aki nem utalja a járulékokat meg az áfát, mert “a nav majd úgyis levonja” :D:D

**Comment by topybear** [comment]
@nbeeps2 azt hiszem itt most van némi keveredés, ezért megyünk el egymás mellett! :)
ami nincs digitálisan aláírva, az valójában papír alapú számla - megőrzéséről is így kell gondoskodni, mert az a hiteles formája - csak nem papír alapon kerül tovöbbításra; a ""valódi" e-számla pedig digitálisan aláírt, elektronikus formában létező és ebben a formájában hiteles, megőrizni is így kell
szerencsétlen mód nincs egyértelműen elfogadott szóhasználat, tapasztalatom szerint elektronikus számlának inkább a papír alapú, elektronikusan továbbított számlát szokták nevezni, e-számlának pedig a csak elektronikus formában létező, azláírt számlát

**Comment by kabelnet2** [comment]
@topybear nem egészen. Régen az volt, amit írtál, de az online számlával módosult az elektronikus számla definíciója is - éppen ezért indult ez az issue. Ma már elektronikus számla egy e-mail-ben küldött pdf is, ha a hash fel van töltve a NAV-hoz. [https://nav.gov.hu/nav/ado/afa/Az_elektronikus_szaml20200416.html](https://nav.gov.hu/nav/ado/afa/Az_elektronikus_szaml20200416.html)

**Comment by topybear** [comment]
@kabelnet2 köszi az infót, úgy tűnik lemaradtam egy brossúrával! :O :(

**Comment by hnwfs** [comment]
nem hinném hogy körülményesebb egy böngésző, mint a **vastag kliens** telepítése.

Miért lenne vastag?

**Comment by nbeeps2** [comment]
@attilagyurman : nem arról van szó, hogy a vállalkozó link, hanem ezek az emberek nem informatikusok, nem IT-s emberek. Kicsit sokat képzelsz róluk ezen a téren ;) A felhasználók nagy többsége nem tudja, hogy mi az a NAS, nem tudja mi az a Google Drive, sőt azt se tudja, hogy a számlázó programja online vagy nem online, lévén a NAV számlázó programjának névválasztása sem volt szerencsés és csak még jobban bekavart e téren, mert sok felhasználó fogalmazásában az az online számlázó, ami be van kötve a NAV-hoz... Az e-számlázás terén még ennyivel sincsenek tisztában. Ők vállalkozók, van saját szakmájuk, amiről kiállítanak egy számlát. Nem akar postára járni, e-mailben elküldi a vevőnek. A gépén ott lesz a PDF, amíg el nem veszik ennyi. Ez nem linkség, csak nem tájékozattak, nem értenek hozzá, számlázniuk viszont kell. Ez ugyanolyan, hogy rengeteg olyan felhasználóval is beszélünk, aki úgy használ számítógépet, hogy nincs hozzá jogosítványa, értsd nem érti, ha azt mondod neki, hogy fájl vagy könyvtár...

**Comment by kabelnet2** [comment]
@nbeeps2: erre csak azeretném mondani, hogy 2020-at írunk és a számítástechnika nem csak a számítástechnikusok szórakozása.
Élőben láttam a példát: a vírus miatt az oktatás áttért távoktatásra. A pedagógusok, akik korábban nem (sokat) foglalkoztak számítógéppel gyakorlatilag egy hosszú hétvége alatt felkészültek az oktatásra és lényegében megoldották azt. Nem történik semmi baj, ha a vállalkozók is megerőltetik magukat egy kicsit. Természetesen azt a legkönnyebb mondani, hogy mi nem értünk ehhez. Aki ezt mondja az járjon a postára.

**Comment by NTCA-developer** [comment]
Sziasztok!

Mivel az elektronikus számlázás a 3.0 egyik fő témája, ezt a ticketet most lezárom. Ha van új észrevétel kérlek nyissatok újat!
