### ISSUE TITLE
[Q&A] HASH érték felhasználása papír számla esetélben.

### ISSUE THREAD

**Issue by salesdb** [nav-gov-hu/Online-Invoice#242]
Beküldtem egy PAPER számlát is ahol szintén megadtam a hash-t. Kicsit meglepett, hogy  nem dobott hibát,  befogadta DONE lett.
Ez szándékos, hogy a PAPER számla esetében is gond nélkül megadható ez, vagy valami hibára utal? A teszt rendszerben ment, az élesben is így van?
Nagyon jó lenne ha így maradna, mert ezt fel lehetne használni az összes számla elektronikus másodpéldányainál. Azaz a számla kiállítója az összes számláját, beleértve a papír számlákat is tárolhatná elektronikusan, mindenféle utólagos aláírás és plusz hitelesítés nélkül.
Jól látom, hogy ez így használva alkalmas lehet erre?

Nagyon előremutatónak látjuk ezt a hash értékkel való operálást. Ha volt már ez issue akkor elnézést.

**Comment by NTCA-developer** [comment]
Szia @salesdb 

Csak amíg megkapod az üzleti választ addig megerősítem, hogy nincs validáció az alkalmazásban a számla formátuma és a között, hogy adtál-e a hashnek értéket az XML-ben. Ez szándékosan így van a kezdetek óta.

**Comment by NTCA-tax** [comment]
Az invoiceAppearance elemnél azt kell jelölni, hogy mi a számla megjelenési formája. Amennyiben papíralapú számla kerül kibocsátásra, akkor PAPER lesz az értéke. De ha nem ismert a számla kiállításakor, akkor UNKNOWN.

Az elektronikus másodpéldány egy megőrzési módszer és nem számla kiállítási. A számla ettől papíron kerül kiállításra, nem elektronikusan. Tehát ebben az esetben a mező értékének PAPER-nek kell lennie.

**Comment by salesdb** [comment]
Kedves NTCA-tax, 
Köszönöm a válaszod.
Mi is így látjuk, az elektronikus másodpéldány egy megőrzési módszer, amiben szeretnénk bevonni az Online Számla adatszolgáltatás HASH értékét, mivel minden számlához beküldhető a HASH.

Felteszem máshogy a kérdésemet, lehet, hogy rosszul fogalmaztam.
Tehát:
Kommunikálhatom-e az ügyfeleim felé, akik a számlázónkat használják, hogy a kiállított és beküldött számlák esetében az eredeti PDF és a hozzájuk tartozó HASH kódok elmentésével eleget tehetnek az elektronikus másodpéldányok megőrzési feltételeinek? (természetesen az egyéb, nem a hitelességet érintő szabályok betartása mellett)
Azért gondolom, hogy ez nem csak megőrzési, hanem Online Számla adatszolgáltatási kérdés is, mert a későbbiekben a megőrzött számlák hitelessége az Online Számla felületen található SHA256 lenyomat alapján ellenőrizhető.
