### ISSUE TITLE
[Q&A] Bejövő számlák lekérése API-val

### ISSUE THREAD

**Issue by attilaszoke** [nav-gov-hu/Online-Invoice#243]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Kedves Fejlesztők,  
Az iránt érdeklődöm, hogy adott cégnél a bejövő számlák lekérdezése API-val megoldható-e?
Ha igen, mi szükséges hozzá? Elég e hozzá a saját technikai felhasználó a szükséges kódokkal vagy szükséges a számlát kiállító cégtől is kérni valamit?

Köszönettel,

Attila

**Comment by NTCA-supporter** [comment]
Szia @attilaszoke !
Igen, a 2.0-ás verzióval lehetőség van erre, minden lekérdező operációban szerepel invoiceDirection tag. Ennek értékkészlete INBOUND, OUTBOUND.
OUTBOUND: kimenő számlák között keresel,
INBOUND: bejövő számlák között keresel (ez kell most neked).

Interfész doksiból idézve:
A keresés irányát az invoiceDirection tagban kell kötelezően jelölni. A keresés iránya lehet
kiállító oldali (OUTBOUND) vagy vevő oldali (INBOUND). Kiállítóként történő keresés esetén a
lekérdezést végző technikai felhasználóhoz tartozó adószámnak kell szerepelnie a számlán a
kiállítói oldalon. Hasonlóképpen, vevőként történő keresés esetén a lekérdezést végző
technikai felhasználóhoz tartozó adószámnak kell szerepelnie a számlán a vevői oldalon. Azon
számlák, amelyek nem tartalmazzák a vevő adószámát, vevői oldalról nem kereshetők, csak a
saját kiállítói oldalukról.

Üdv

**Comment by NTCA-supporter** [comment]
Szia @attilaszoke !
Sikerült ezzel haladni? Van még kérdés a lekérdezésekkel kapcsolatban.
Kérlek zárd majd az issue-t, ha minden adott az implementációhoz.
Üdv

**Comment by attilaszoke** [comment]
Köszönöm szépen, ennyire volt szükségem jelenleg.
Lezárom.

**Comment by lvitya586** [comment]
Szia @NTCA-supporter !

Nem akartam új issue-t nyitni, mert a kérdésem a bejövő számlák lekérdezésével kapcsolatban lenne, de nem égetően fontos.

Az interfész doksi 1.6.5-ös pontjában ez van: "A tömörítve  beküldött  számlákat  a  /queryInvoiceData  operációban  a  szerver  is  mindig  tömörítetten adja vissza (a nem tömörítetteket pedig hasonlóképp mindig tömörítetlenül). Ily módon, a tömörítés implementálása opcionális."

Feltételezem, hogy ez az idézett mondat még akkor született, amikor nem volt lehetőség a bejövő számlák lekérdezésére is, mivel ha bejövő számlát kérdezek le, akkor implementálnom kell a tömörítést, hiszen ha a másik oldal tömörítve küldte be, akkor a szerver úgy is adja vissza, tehát már nem lesz opcionális az implementáció.

Van-e arra lehetőség, hogy megmaradjon ez az opcionális állapot?
Pl. járható út lehetne valamelyik az alábbiak közül:
 - a bejövő számla mindig tömörítetlenül kerüljön visszaadásra
 - a kérésben meg lehetne adni, hogy a bejövő számla milyen formában kerüljön visszaadásra (tömörített vagy tömörítetlen)

Üdv
