### ISSUE TITLE
[Q&A] Szabad-e külföldi vevőnek kiállított számláról adatot szolgáltatni 2021 előtt?

### ISSUE THREAD

**Issue by emefem** [nav-gov-hu/Online-Invoice#244]
Kedves fejlesztők!

Egy olyan kérdésem lenne, hogy ha egy külföldi vevőnek kiállított számla kerül feltöltésre nem valid magyar adószámmal (hiszen ez nincs neki - csupa 1-es), akkor az kritikus hiba, vagy meg kell akadályozni az ilyen eseteket vállalva a kockázatot, hogy egy esetleges számla az erre kialakított szabályrendszer miatt nem kerül feltöltésre.
Leginkább a 2020.07.01.-i szabályozás miatt kérdezem, ami szerint a külföldi számlákról az alábbit írja:
"2020. július 1-jétől továbbra sem teljesítendő/teljesíthető számlaadat-szolgáltatás a nem adóalany és a külföldi adóalany részére teljesített ügylet számlájáról." Viszont sok rendszerben nem lehet egyértelműen eldönteni, hogy az adott vevő magyar-e vagy sem.

Tehát összegezve a kérdés az az, hogy egy esetleges külföldi számla feltöltését bünteti-e a NAV, vagy szemet huny felette?

**Comment by NTCA-tax** [comment]
A jogszabály egyértelműen belföldi ügyletekre, belföldi partnerre vonatkozóan írja elő az adatszolgáltatást. Nem szabad külföldi partnernek kiállított számláról adatot szolgáltatni, ez a kötelezettség 2021. január 1-től lép hatályba.

A jogszabály alapján az adóhivatal szankcionálhatja a nem megfelelő adatszolgáltatást is (persze az eset összes körülményének mérlegelése alapján).

**Comment by NTCA-supporter** [comment]
Kedves @emefem!

Ha nincs több kérdésed akkor kérlek zárd le a ticketet. Köszi

**Comment by bandras73** [comment]
Üdv! 

Akinek van magyarországi adószáma, de külföldi annak kell. Jól gondolom?
