### ISSUE TITLE
[DEV support] Egy számlaszám többszöri befogadása

### ISSUE THREAD

**Issue by mlnrdns** [nav-gov-hu/Online-Invoice#247]
Sziasztok,

a tesztjein során sikerült néhány alkalommal előidéznünk olyan helyzetet, amikor többször befogadásra került az oldalatokon egy adott számlaszám. Az egyik ilyen eset transactionId értékei: 2ZLI35UQ7327GER8  és 2ZLI4D8JGOWZKBVR.

**Comment by NTCA-developer** [comment]
Szia @mlnrdns 

Köszi a jelzést! Kicsit hosszú lesz, de kérlek ezt olvasd végig, ebben meg fogod találni a választ: https://github.com/nav-gov-hu/Online-Invoice/issues/204
