### ISSUE TITLE
[Q&A] invoiceDigest response adattartalom

### ISSUE THREAD

**Issue by clapygeza** [nav-gov-hu/Online-Invoice#248]
Sziasztok!
Az éles rendszerbe küldött olyan számláknál ahol a vevő egyéni vállalkozó (KATA-s) az invoiceDigest az adólapra (invoiceNetAmount) nullát ad vissza, az áfa érték viszont rendben. A számla jó, az xml jó, a status: DONE. Megnéznétek, hogy mi ennek az oka?
Az egyik: 2ZMOPVASU5BHBK7X, RID202006041751386
Köszi előre is.

**Comment by NTCA-supporter** [comment]
Szia @clapygeza !
Az invoiceDigest lekérdezéshez tartozó reqestId-t el tudod küldeni (amelyiknél 0 értéket kaptál a számlához)?
Láttam többször is lekérdezted, viszont az említett számlához tartozóan én ezeket láttam több válaszban is:
<invoiceNetAmount>3937.01</invoiceNetAmount>
<invoiceNetAmountHUF>3937.01</invoiceNetAmountHUF>

Tehát nekem úgy tűnik, hogy ezek töltve vannak.

Üdv

**Comment by clapygeza** [comment]
A lekérdezés RID: RID202006050839452
Azt vettem észre, hogy csak ezeknél a számláknál tartalmaz fillért az adóalap. Lehet, hogy a konvertálásnál lesz a baj? (Mármint nálam? nézem közben )
Köszi

**Comment by clapygeza** [comment]
Bocsi, nálam van a baj. A filléres adatokat rosszul konvertáltam. Le is zárom.
