### ISSUE TITLE
[Q&A] Számla módosítás és javítás

### ISSUE THREAD

**Issue by lakatoskevin** [nav-gov-hu/Online-Invoice#249]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Sziasztok!

Az az alaphelyzet, hogy van egy eredeti számla, egy jóváíró számla (amiben negatív előjelüek az összegek), és végül pedig egy javító számla.

Namost, szeretném beküldeni a teszt interfészre az eredeti számlát, de ugye azt nem lehet, mert az ugye jóval régebbi (idősebb mind 24 órás), és azt ugye a teszt interfész sem fogadja el. Így viszont a módosítást sem tudom tesztelni, hogy vajon miért nem sikerült az éles interfészre való beküldés.

Mit lehet tenni az én helyemben? Legszívesebben segítséget kérnék az éles interfésszel kapcsolatosan, csak ugye azt itt szigorúan tilos. Hibaüzenetnek csak ugye annyit kaptunk, hogy "Számlára vonatkozó módosító okirat egyedi sorszáma ugyanarra a számlára hivatkozva többször szerepel a kérésben."

**Comment by NTCA-supporter** [comment]
Szia @lakatoskevin!
Annyira nem értem még a problémád, kezdjük lépésenként:
- szeretném beküldeni a teszt interfészre az eredeti számlát, de ugye azt nem lehet, mert az ugye jóval régebbi (idősebb mind 24 órás), és azt ugye a teszt interfész sem fogadja el: itt arra gondolsz, hogy a beküldésnél kapsz WARN üzenetet? Teszt rendszerben szerintem ez nem gond neked sem.

- Hibaüzenetnek csak ugye annyit kaptunk, hogy "Számlára vonatkozó módosító okirat egyedi sorszáma ugyanarra a számlára hivatkozva többször szerepel a kérésben.": ezt ha jól értem élesen kapod. Ez akkor lehet, ha egy requestben belül van 2 vagy több módosítószámla, ami ugyanarra az eredeti számlára hivatkozik, és ezeknél a számláknál ugyanaz a modificationIndex, aminek ugye egy futó sorszámnak kellene lennie.

Ha küldesz requestId-kat, megjelölve a környezetet is, akkor rá tudok nézni a problémás beküldésekre.

Üdv

**Comment by lakatoskevin** [comment]
Köszi a gyors választ!

Itt a tranzakció azonosító (ha nem baj, hogy az élesbe ment): 2ZNOEGY0RMUHSA4K

**Comment by NTCA-supporter** [comment]
Első körben próbáljuk meg reprodukálni teszt környezetben kérlek, abban segítek szívesen, ha pedig nem tudjuk megfejteni az okot, akkor marad az éles hiba bejelentése a hivatalos csatornán keresztül (https://www.nav.gov.hu/nav/e-ugyfsz/e-ugyfsz.html).
Köszi

**Comment by lakatoskevin** [comment]
Rendben, akkor majd ideírom a teszt interfészt használó tranzakció azonosítóját, addig előkészítem a tesztet. Nem tudom, hogy hogyan vagytok "ügyeletben", de szerintem ne várd meg. Nem mostanában lesz...

**Comment by lakatoskevin** [comment]
Szia! Van végre fejlemény, Számla adatszolgáltatás megy, módosítás megy, egyedül a javító számla benyújtásánál van hiba. A v2.0, teszt tranzakció azonosítója: 2ZO8A429L5PDWH3M

**Comment by NTCA-supporter** [comment]
Szia @lakatoskevin !

Megnéztem a beküldést, alapvetően két hiba is van:
- 0000154523 ezzel a számlaszámmal már küldtél be számlát, így ezt nem használhatod fel mégegyszer, generálj újat
- <modificationIndex>1</modificationIndex>: a 0000154411 számlára már küldtél be módosítószámlát (invoiceNumber = 0000154522), ahol már a modificationIndex 1 volt, tehát ezt mégegyszer nem adhatod meg modificationIndex-ként, mivel ez egy futó index, tehát célszerűen a 2-es érték következne. 

Kérlek nézz utána, és próbáld meg újra.
Köszi

**Comment by lakatoskevin** [comment]
Köszönöm a segítséget!
Azóta már javítottam ezeket a hibákat. Le lehet zárni ezt az issue-t.
