### ISSUE TITLE
[DOC] unitOfMeasureOwn használatára több/jobb példa

### ISSUE THREAD

**Issue by Amn3s1a2018** [nav-gov-hu/Online-Invoice#25]
**A hibás dokumentum neve / Document name containing the error**
https://onlineszamla.nav.gov.hu/api/files/container/download/Data%20sample%20XML.zip

**A dokumentációs hiba leírása / Description of the documentation error**
Nem kifejezetten hiba, de az 1.1-hez megjelent dokumentációk és a példák eléggé homályban hagytak, hogyan is kéne ezt használni.
Az egy szem példában amit találtam, a következő szerepel:
```
<unitOfMeasure>PACK</unitOfMeasure>
<unitOfMeasureOwn>doboz</unitOfMeasureOwn>
```
Az sem világos, hogy miért tér el pont ez a sor a többitől, ahol darab és kilogramm van? Ez alapján nem kéne oda is <unitOfMeasureOwn>kg</unitOfMeasureOwn>?

Ezzel a „sorok közt” azt javasoljátok, hogy az összes _hasonló_ esetet (mint dózis, üveg, adag) mint PACK adjuk fel, a saját kiírt egységgel kiegészítve?

Mi a helyzet azokkal ahol nincs ilyen megfeleltethetőség, mint a gramm a tonna? Ezeknél lehetne használni a unitOfMeasure OWN-t, de erre egy példa sincs.

**Comment by NTCA-developer** [comment]
Köszönjük a felvetetést, továbbítom a készítőknek.

**Comment by NTCA-developer** [comment]
Szia @Amn3s1a2018 

Elvittem a javaslatod a Jedi Tanácshoz, az interfész doksi következő publikálásakor készülni fog pontosítás az általad kifogásolt részhez, ami remélhetőleg egyértelműsíti a kérdést.

Majd kérlek zárd le a ticketet!

**Comment by Amn3s1a2018** [comment]
Köszönöm, várom.

**Comment by NTCA-developer** [comment]
Oké, nyugodtan nyisd majd újra, ha a publikálás után a doksi nem úgy sikerült, mint ahogy szeretted volna.
