### ISSUE TITLE
periodicalsettlement vs. smallBusinessIndicator

### ISSUE THREAD

**Issue by KKARACSONY** [nav-gov-hu/Online-Invoice#251]
Sziasztok, 

Töltjük a következő tageket, és mégis ABORTED üzenetet kapunk vissza. 
- periodicalsettlement 
-  invoiceDeliveryPeriodStart
- invoiceDeliveryPeriodEnd
- Currencycode

Error: 

<validationErrorCode>SCHEMA_VIOLATION</validationErrorCode><message>XML contains on line: [1] and column: [1,353] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/2.0/data":invoiceDeliveryPeriodStart}'. One of '{"http://schemas.nav.gov.hu/OSA/2.0/data":smallBusinessIndicator, "http://schemas.nav.gov.hu/OSA/2.0/data":currencyCode}' is expected.]</message>

A smallBusinessIndicator = False érték is kötelező lenne? A specifikációban nincs erre utaló jel. 
Vagy hogy kell ezt az adatot szolgáltatni?

Köszi szépen!

**Comment by NTCA-supporter** [comment]
Szia @KKARACSONY!
Ha ezt élesen kapod, akkor kérlek küld be teszt környezeten is, hogy ránézhessek pontosabban.
A teszt környezetről pedig majd küldj requestId-t vagy transactionId-t, hogy könnyen megtaláljam.
A smallBusinessIndicator egyébként optional, tehát nem az a gond, valószínűleg az invoiceData xml-ed nem sémavalid.

Köszi

**Comment by KKARACSONY** [comment]
Szia!

Teszt környezetben kapom az üzenetet: 
TR ID:  2ZURX8M99HR3SCP4
Manage invoice request ID: 000000000000267

Köszi!

**Comment by NTCA-supporter** [comment]
Szia @KKARACSONY!
Nem követed a sémában lévő tagek sorrendjét.
Helyesen:
				<invoiceDetail>
					<invoiceCategory>NORMAL</invoiceCategory>
					<invoiceDeliveryDate>2020-06-30</invoiceDeliveryDate>
					<invoiceDeliveryPeriodStart>2020-06-01</invoiceDeliveryPeriodStart>
					<invoiceDeliveryPeriodEnd>2020-06-30</invoiceDeliveryPeriodEnd>
					<periodicalSettlement>true</periodicalSettlement>
					<currencyCode>HUF</currencyCode>
					<exchangeRate>1 </exchangeRate>
					<paymentMethod>TRANSFER</paymentMethod>
					<paymentDate>2020-07-10</paymentDate>
					<invoiceAppearance>UNKNOWN</invoiceAppearance>
				</invoiceDetail>

Így már nincs sémasértés.
Kérlek zárd az issuet, ha nincs több kérdés.
Üdv

**Comment by KKARACSONY** [comment]
Köszi a gyors segítséget! Megpróbáljuk így beküldeni.
