### ISSUE TITLE
[Q&A] Önszámlás

### ISSUE THREAD

**Issue by rednifegnar** [nav-gov-hu/Online-Invoice#252]
T.Fejlesztôk!
Kérnék egy kis segítséget önszámlás beküldéssel kapcsolatban. Igazából kicsit homály nekem a dolog. 
Mire van szükség a "szállítótól" ahhoz, hogy a nevében beküldhesse a vevõ saját magának kiállított számlát (a saját szoftverével)? 
Értem ez alatt hogy be kell kérnie a "szállító" technikai userének adatait (pwd,kulcsok)? Ezután a beküldést ezekkel kell kezdeményezni?

Jelenleg a szoftver használójának a tech user adataival müködik a "normál" számlaküldés, de az önszámlákra SUPPLIER_TAX_NUMBER_MISMATCH hibát dob (nyilván itt a szállítónak más az adószáma mint a beküldõ useré). A selfBillingIndicator be van állítva. 

Sajnos elég sok önszámlás ügyfelük van és ezen most megakadtam, mert akkor tömegével kellene ilyen számlákat beküldeni. Eddig ez azért nem merült fel mert alacsony vagy 0 áfa tartalmúak voltak.

Köszönet.

**Comment by baracsi** [comment]
prog.hu-n nem tudom te kérdezted-e, de ott megválaszoltam, belinkelem: [https://prog.hu/tarsalgo/188874/adohatosagi-ellenorzesi-adatszolgaltatas-2016?no=15084#e15084](url)

**Comment by NTCA-supporter** [comment]
Sziasztok!
Köszi a prog.hu-s választ, bemásolom lentre, igazából tartalmazza a teljes megoldást :)
Az összerendelésre különösen célszerű figyelni, mindkét fél érdekében.

"mindenképpen az eladónak kell adnia a saját technikai felhasználóját, mert egyébként televághatná mindenki egy tetszőleges adózó bejelentéseit fiktív számlákkal

1. eladó készít egy technikai felhasználót (XML-kulcsokat legenerálja), beállítja, hogy "Saját számlák lekérdezése" és "Számlák kezelése"
2. jogosultság részt karbantartva összerendeli ezt a technikai felhasználót a vevő adószámával (és csak azzal)
3. elküldi ennek a technikai felhasználónak az adatait a vevő részére

ezzel a megoldással a vevő tud készíteni eladó nevében saját magának számlát és nem fér hozzá az eladó egyéb számláihoz"

Ha nincs több kérdés, kérlek majd zárd az issuet.
Üdv

**Comment by rednifegnar** [comment]
koszonom, igen en kerdeztem ott is, sajnos most elegge meg vannak love mert a jelenlegi bekuldo modul csak egy elore kezzel beallitott technikai userrel tud bekuldeni. ez eddig igazabol nem volt gond (marmint nem is merult fel mint gond) mivel nagyon alacsony afa osszegekkel (vagy 0-val) dolgoznak, a sajat szamlaikat meg bekuldi az nem gond. most, hogy mindent be kell kuldeni es elkezdtem nezni ezt a csodat mikent kell beallitani, ekkor esett le hogy ehhez kell ennyi technikai user, de hiaba ha nem kepes a modul fogadni. most kellene keresni iziben egy masik modult. a szamlak egyszeruek es nincs modositas/eloleg meg hasonlok, nagy neha ervenytelenites.

**Comment by NTCA-supporter** [comment]
Szia @rednifegnar !
Ezzel kapcsolatban van még kérdés? Sikerült megoldani a több technikai user berögzítését?
Ha nincs kérdés, kérlek zárd az issuet.
Köszönöm
