### ISSUE TITLE
[FEATURE] Technikai felhasználó adatainak másolhatósága

### ISSUE THREAD

**Issue by Zoller79** [nav-gov-hu/Online-Invoice#253]
Tisztelt Fejlesztők! 

A technikai felhasználói adatokat a regisztrációt követően át kell emelni a saját számlázó rendszerbe. 
A kézi átmásolás sok hibalehetőséget rejt a 0 O, valamint a I l betűk nehéz megkülönböztetése miatt. 

Sajnos sok felhasználónak a kijelölés és másolás eléggé nehezen megy, ezért az lenne a javaslat, hogy a generált felhasználónév, XML aláírókulcs és az XML cserekulcs mellé egy másol gombot helyezzenek ki, amely a mező értéket vágólapra helyezi. Akár plusz infó panel lehet a végén, hogy a ..... érték vágólapra helyezve, az adatok beilleszthető a használt számlázóprogram megfelelő mezőjébe a Ctrl+v gombokkal. (OK) 

Egy lehetséges elképzelés 
![kép](https://user-images.githubusercontent.com/65278057/84481121-e75da500-ac95-11ea-897c-20df4d1a75de.png)

Segítségüket előre is megköszönve, Tisztelettel
Kispál Zoltán

**Comment by NTCA-supporter** [comment]
Szia @Zoller79!
Köszönjük a jelzést és ötletet, már szerepel nálunk is a backlogban.
Igyekszünk előre helyezni prioritásban, de most vannak sokkal fajsúlyosabb feladatok.
Ha gondolod, hagyd nyitva az issuet.
Üdv

**Comment by nbeeps2** [comment]
Alternatív megoldás még, hogy az újonnan generált technikai felhasználónévben nem szabadna használni nullát, kis- és nagy o betűt, kis L betűt, nagy i betűt, kis Q betűt.

Ez csak a felhasználónévnél probléma, mert ha az aláíró kulcsok nem jók, arról külön kap üzenetet a felhasználó.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Megkaptuk a jóváhagyást a Másolás gomb igényre, az Online Számla 2.11 verziójába fog kerülni.
Zárom az issuet, ha van még kérdés, nyissátok újra nyugodtan.
Köszi
