### ISSUE TITLE
[Q&A] Térítés nélküli tranzakciók jelentése

### ISSUE THREAD

**Issue by The2ndbest** [nav-gov-hu/Online-Invoice#254]
Sziasztok,

Nem biztos, hogy jó helyen teszem fel a kérdést, de nem találtam erre vonatkozó információt sehol, így remélem tudtok nekem ebben segíteni.

Ha minden igaz, akkor július 1-étől minden belföldi számlát jelentenünk kell. Vannak olyan tranzakcióink, amikor pénzügyi teljesítést nem igénylő számlát (0-ás számla) állítunk ki, melynek viszont - a beszerzési ár alapján - van áfa tartalma, és az áfa fizetésére az átadó kötelezett. Gyakorlatilag ez egy olyan eset, amikor a számla nettó és bruttó értéke 0, viszont az áfa érték nem 0. Ezzel az a baj, hogy így nem teljesül a Nettó + Áfa = Bruttó feltétel, sem a sorokon, sem az összesítőnél, mely miatt jelenleg hibát (figyelmeztetést) kapunk vissza.

Tudnátok tanácsot adni abban, hogy ezeket az eseteket, miképpen kellene jelenteni és megjeleníteni a jelenlegi schemában?

Előre is köszi.

**Comment by NTCA-tax** [comment]
Ez egy általunk ismert probléma ezzel a warninggal. Van olyan eset, amikor a nettó érték nulla, ugyanakkor van áfa összeg (nem teljesen az általad leírt eset, vagy lehet, hogy én értem félre). 
Amennyiben ingyenes eszközátadás történik, de az adó összege felszámításra kerül, akkor fordul ilyen elő. Ekkor az általad is említett warning feltétel hibát jelez. Ettől még persze az adatszolgáltatást feldolgozzuk. A warning módosítások listáján ez az eset is fent van.

**Comment by The2ndbest** [comment]
Arra gondoltam igen, csak cifrábban fogalmaztam.

Rendben, akkor ezt úgy értelmezem, hogy amíg nincs módosítva ez az eset, addig jelenthetjük warninggal.

Köszönöm szépen a választ.
