### ISSUE TITLE
[Q&A] Cégek rövid neve

### ISSUE THREAD

**Issue by tamassky** [nav-gov-hu/Online-Invoice#256]
A QueryTaxpayerResponse típusú válaszokban várható a közeljövőben, hogy a taxpayerShortName - vagyis az adózók rövid neve - is visszaadásra kerül? Vagy ez most nem prioritás?

**Comment by pvmon** [comment]
Ezt én is kértem régebben Fel is vették a Board-ra, de eddig sajnos nem látom, hogy megtörtént volna.

**Comment by NTCA-supporter** [comment]
Szia @tamassky 

Ahogy @pvmon  is írja fel van véve a boardra és nincs is elfelejtve, dolgozunk rajta. Még egy kis türelmet kérünk.
