### ISSUE TITLE
[Q&A] Adószám - megyekód

### ISSUE THREAD

**Issue by vivacomp** [nav-gov-hu/Online-Invoice#257]

**Comment by vivacomp** [comment]
Kedves Fejlesztők!
Érdeklődöm, hogy az adószám-megyekód mikor lesz elérhető? Esetleg elkerülte a figyelmemet?
Üdv.

**Comment by NTCA-supporter** [comment]
Kedves @vivacomp!

Nincs elfelejtve, de egyelőre mi is azt várjuk, hogy áttöltésre kerüljön hozzánk. Amint ez megtörténik akkor már elérhető lesz ez az adat is. (/queryTaxpayer válasza már tartalmazza) Addig nyitva hagyjuk a ticketet és jelzünk majd.

**Comment by vivacomp** [comment]
Köszönöm.


NTCA-supporter <notifications@github.com> ezt írta (időpont: 2020. jún.
26., P, 11:22):

**Comment by LaySoft** [comment]
> Kedves @vivacomp!
> 
> Nincs elfelejtve, de egyelőre mi is azt várjuk, hogy áttöltésre kerüljön hozzánk. Amint ez megtörténik akkor már elérhető lesz ez az adat is. (/queryTaxpayer válasza már tartalmazza) Addig nyitva hagyjuk a ticketet és jelzünk majd.

Én nem látom a válaszban továbbra sem, <ns2:countryCode> van, de countyCode nincs.

**Comment by renced42** [comment]
Kedves @vivacomp 
Kérlek ellenőrizd a lekérdezést. Most már a megyekód is benne van.

**Comment by vivacomp** [comment]
@renced42 Most már a teljes adószám rendben van, köszönöm. A rövid cégnév is jön, de a teljes cégnév még mindig csak NAGYBETŰS. Nekem nem gond, mert átalakítom, de szó volt arról, hogy a teljes cégnevet is "normál" betűkkel kapjuk meg. Ez nem akkora gond, csak ha már nem lesz más probléma, akkor érdemes kitérni rá.
Üdv.

**Comment by renced42** [comment]
> de a teljes cégnév még mindig csak NAGYBETŰS.

Kedves @vivacomp Ezt az adatot mi is így kapjuk így ezzel nem tudunk mit tenni.
Ha nincs több kérdés kérlek zárd az issue-t.

Köszönöm szépen!

**Comment by vivacomp** [comment]
Köszönöm, zárom.
