### ISSUE TITLE
[DOC] Gyártó terminológia nincs használva

### ISSUE THREAD

**Issue by connorhu** [nav-gov-hu/Online-Invoice#258]
**A hibás dokumentum neve / Document name containing the error**
Online Szamla_interfesz specifikáció_HU_v2.0.pdf

**Oldalszám / Page number**
-3 (első sorszámozott oldal előtt, ami egyébként szintén hibás az 1. oldal a címlap)

**A dokumentációs hiba leírása / Description of the documentation error**
Magyarázzátok a "Gyártó" terminológiát, viszont maga a szó nem szerepel a dokumentációban sehol máshol.

**Comment by NTCA-supporter** [comment]
Szia @connorhu !
Köszi a jelzést, valóban nem túl releváns. Gondolom anno a softwareDevName csomópont miatt került bele. Kiszedjük majd, vagy kezdünk vele valamit.
Üdv
