### ISSUE TITLE
[Q&A] Tömörített bejövő számlák

### ISSUE THREAD

**Issue by lvitya586** [nav-gov-hu/Online-Invoice#259]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

A kérdésem a bejövő számlák lekérdezésével kapcsolatban lenne, de nem égetően fontos.

Az interfész doksi 1.6.5-ös pontjában ez van: "A tömörítve beküldött számlákat a /queryInvoiceData operációban a szerver is mindig tömörítetten adja vissza (a nem tömörítetteket pedig hasonlóképp mindig tömörítetlenül). Ily módon, a tömörítés implementálása opcionális."

Feltételezem, hogy ez az idézett mondat még akkor született, amikor nem volt lehetőség a bejövő számlák lekérdezésére is, mivel ha bejövő számlát kérdezek le, akkor implementálnom kell a tömörítést, hiszen ha a másik oldal tömörítve küldte be, akkor a szerver úgy is adja vissza, tehát már nem lesz opcionális az implementáció.

Van-e arra lehetőség, hogy megmaradjon ez az opcionális állapot?
Pl. járható út lehetne valamelyik az alábbiak közül:

 - a bejövő számla mindig tömörítetlenül kerüljön visszaadásra
 - a kérésben meg lehetne adni, hogy a bejövő számla milyen formában kerüljön visszaadásra (tömörített vagy tömörítetlen)

Üdv

**Comment by NTCA-supporter** [comment]
Kedves @lvitya586 
Köszönjük a kérdésed/felvetésed. A következő XSD változtatás előtt átgondoljuk mélyebben, de első ránézésre megoldható lehet, hogy kérésben meg lehessen adni. Visszajelzünk majd.

**Comment by KMGY100** [comment]
"""Köszönjük a kérdésed/felvetésed. A következő XSD változtatás előtt átgondoljuk mélyebben"""
De a 2.0 XSD ne változzon.
Bármit változtattok az csak a 3.0 verzióban legyen, hogy ne okozzon zavart a már működő 
2.0-ban (ami már teljesíti az áfa értékhatás nélküli küldést is)

**Comment by NTCA-supporter** [comment]
A 2.0 már nem fog változni ez biztos! A 3.0-ra gondoltam, csak nem pontosan fogalmaztam.

**Comment by kabelnet2** [comment]
Azért két megjegyzés:
1. Nem ördöngősség decompress-álni a file-okat
2. A nem tömörített file-ok mérete a többszöröse a tömörített file-okénak. Talán nem kellene növelni a hálózati forgalmat, amikor van más lehetőség is.

**Comment by lvitya586** [comment]
> 
> 
> Azért két megjegyzés:
> 
>     1. Nem ördöngősség decompress-álni a file-okat
> 
>     2. A nem tömörített file-ok mérete a többszöröse a tömörített file-okénak. Talán nem kellene növelni a hálózati forgalmat, amikor van más lehetőség is.

Már vártam mikor jön valaki ezzel a megjegyzéssel. :)
Erre nekem is van válaszom:
 - Nyilván nem nagy ördöngösség, de mivel eleve úgy írtam a kérdést, hogy nem égetően fontos akkor mi a gond?
 - A fejlesztői doksi és a valóság között jelenleg ellentmondás van, ugyanis már nem feltétlen opcionális a tömörítés implementálása. Legalábbis abban az esetben nem opcionális, ha a bejövő számlákat is le akarjuk kérni. Persze lehet azt mondani, hogy a bejövő számlákat sem muszáj implementálni. Felőlem az is jó, ha pontosításra kerül a doksi.
 - A tömörítetlen méretre is van korlát, ami jelen esetben 15MB. Nem gondolnám, hogy akkora nagy forgalmat okozna ekkora adat letöltése. Amúgy meg a javaslatomban opcionálisan is megadtam a letöltési lehetőséget, tehát ha valaki spórolna a forgalmon, akkor továbbra is letölthetné tömörítetten.

**Comment by wirthandras** [comment]
> 2\. A nem tömörített file-ok mérete a többszöröse a tömörített file-okénak. Talán nem kellene növelni a hálózati forgalmat, amikor van más lehetőség is.

Ha a hálózati forgalom nagyon fontos lenne akkor xml helyett a json egy fokkal jobb lenne de még tömörebb lenne a google által fejlesztett protocol buffers használata vagy egyéb hasonló kommunikációs sémák.

Ha már ez felmerült esetleg a 3.0-ban meg lehetne vizsgálni más adatátviteli protokolok használatát? Esetleg egy swagger-t ki lehetne rakni a teszt környezet fölé?

**Comment by NTCA-developer** [comment]
Szia @lvitya586 

A dokumentáción fogunk pontosítani, ha akarsz bejövő számlákat kezelni akkor muszáj vagy felkészülni a tömörített válaszokra vagy olyan folyamatot tervezni, ami kihagyja a tömörített számlákat. Eddig nagyon szigorúan ügyeltünk a lekérdezett adatok integritására, nem akarunk olyan funkciót ami a mi oldalunkon változtatgatja a lekérdezett adatokat.

**Comment by lvitya586** [comment]
Rendben, előre is köszönöm a pontosítást.
