### ISSUE TITLE
[FEATURE] Simplify the modification of an invoice

### ISSUE THREAD

**Issue by sebastian-walz** [nav-gov-hu/Online-Invoice#26]
**Az igény összefoglalása / Summary of the request**
When modifying an invoice, we have to transmit the line number in sequence added to the original invoice lines. Example: Invoice with 3 line items has the lines 1,2 and 3. The update would have the lines 4 (reference item 1), 5 (reference item 2) and 6 (reference item 3). This is a huge challenge for most of the ERP systems to provide

**Az általam javasolt megoldás / The solution I propose**
My proposal would be, to transmit the modify document with the reference to the original document (what is already implemented) and an own sequence. Example: Invoice with 3 line items 1, 2 and 3. The modify document would have the line items 1 (reference item 1), 2 (reference item 2), and 3 (reference item 3). This would make it much easier to modify a document.

**Elfogadható alternatívák / Acceptable alternatives**
The alternative would be to cancel the initial invoice and submit a new one.

**Egyéb tartalom / Additional content**
This has been a pain point in most of the projects in the past. It would be a pleasure to have a new technique in future releases.

**Comment by Amn3s1a2018** [comment]
I think there is two misunderstanding here. At first, it is allowed to cancel the original invoice, and create a new one. Anyway, this two are the modifiers of the original one, so you need to reference it in them (with some exceptions). To upload the data of the cancel, you stil have to submit lines, so this does not solve your problem.
And second: If the first invoice you have lineNumber: 1-3, in the cancel (or modify) the line numbers start again from one, eg. the cancel will have again the lineNumbers 1-3.
If you want to use the lineOperation: MODIFY, you can reference the original lines, but you can neglect the connections if you keep using the CREATE operation in the cancel and countinue counting in the lineNumberReference tag.
Please inquire into the published examples:
https://onlineszamla.nav.gov.hu/api/files/container/download/Data%20sample%20XML.zip

**Comment by sebastian-walz** [comment]
Thank you for your fast response. I got the points mixed up. The line number always starts with one, but the line reference in case of create-operation has to continue the original line counter.

**Comment by NTCA-developer** [comment]
It is always a pleasure to see a proactive, self-organizing community. @Amn3s1a2018 took the lead before me, and incidentally he is all round correct, I have nothing to add.

@sebastian-walz 
If this issue is complete, please be so kind to close it. If you would like to continue here or to post a new one, we are looking forward to it.
