### ISSUE TITLE
[Q&A] Csoportos ANNUL sorszámozása angolul (?)

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#261]
**Csoportos ANNUL sorszámozása angolul (?)**
A https://github.com/nav-gov-hu/Online-Invoice/blob/master/sample/API%20sample/manageAnnulment.xml oldalon a **firstIndexHash**, mint első.
Oké, hogy a második **second...** és így tovább. Van erre valahol pontos lista, hogy pontosan, hogyan kell megadni 100-ig?
Kötőjelekkel, (ha van,) kis és nagy betűk, stb?
Köszönöm

**Comment by NTCA-developer** [comment]
Szia @zsfoto 

Az csak komment ha megnézed jól, nem az XML feldolgozandó része. A példa XML-ekben azért vannak ezek felírva, hogy a részeredményeket is validálni lehessen a fejlesztés közben. Ha csak a helyes requestSignature érték lenne benne, akkor kevésbé volna informatív.

**Comment by zsfoto** [comment]
Köszönöm
(Még elemzem, hogy megoldjam.)

**Comment by NTCA-supporter** [comment]
Szia @zsfoto !
Ezzel az issueval kapcsolatban van még kérdés?
Üdv!

**Comment by zsfoto** [comment]
Köszönöm.
Zárható
