### ISSUE TITLE
Hiányos  <invoiceDigest> SIMPLIFIED számla esetén

### ISSUE THREAD

**Issue by KMGY100** [nav-gov-hu/Online-Invoice#262]
Egyszerűsített SIMPLIFIED számla esetén miért nem tartamazza az -invoiceDigest-
legalább a   -vatContent-    áfa tartalom
és a         -invoiceGrossAmount-  
és a         -invoiceGrossAmountHUF-  értékeket ?

Hasonlóan a NORMAL  számlákhoz ahol minden 
összeg érték szerepel
Egyszerűbb lenne a vegyes (NORMAL  és SIMPLIFIED) bejövő
és kimenő számlákat feldolgozni.

**Comment by NTCA-supporter** [comment]
Szia @KMGY100 !
Normál számla esetén is csak nettó és ÁFA értékeket adunk vissza. Normál számláknál ugye ezeket összegezve kötelező beküldeni. Egyszerűsített számlánál ilyen adat nincs, ott adótartalmanként kell beküldeni. Aggregációt pedig direkt nem csinálunk ebben  alekérdezésben.
Köszi

**Comment by KMGY100** [comment]
Talán nem volt pontos a kérdésem/kérésem
QueryInvoiceDigestResponse   invoiceDigest   
 NORMAL számla esetén tartalmaz összeg értékeket melyekből pontosan meghatározható a NETTÓ,ÁFA,BRUTTÓ  hármas.
SIMPLIFIED számla esetén csak akkor lenne meghatározható a NETTÓ,ÁFA,BRUTTÓ  hármas
ha a QueryInvoiceDigestResponse   invoiceDigest-ben visszaadnátok a
-vatContent-  és a  -invoiceGrossAmount-   értékeket.

**Comment by NTCA-supporter** [comment]
Szia @KMGY100 !
Értem a célodat, de ezt simplified számláknál nem tudjuk megcsinálni.
A NORMAL számlák esetén ugye ott a van a számlaösszesítőben áfamérték szerint és a teljes számlára vonatkozóan is, a teljes számlára vonatkozó adatokból adjuk vissza a digest responseban a nettó és áfa értékeket.
Egyszerűsített számlánál nincs ilyen adatunk, ott csak áfamértékenként szerepel az összegzés, teljes számlára vonatkozóan nem.
Remélem érted a problémám. Ha máshogy gondoltad, akkor kérlek magyarázd el, hogy egy egyszerűsített számla esetén aggregálás nélkül hogyan képzelted el ezt a digest response-t.
Köszönöm

**Comment by KMGY100** [comment]
Szerintem egyszerűsített számlát jellemzően kézitömbből állít ki egy vállalkozás.
Egyszerűsített Kézitömbben csak egyféle áfatartalom érték szerepelhet.
Ekkor visszaadható lenne (és feldolgozható lenne)  -vatContent- és a -invoiceGrossAmount- értékek
amiből már számolható a nettó-áfa-bruttó érték hármas.

De megértem a válaszod, hiszen a WEBoldalon a -Számla adat rögzítés -Egyszerűsített számla- menüpontban
többféle áfatartalom érték adható meg.(több tételt tartalmazó számlában)

Vagyis:  nincs szinkronban a kézitömb (mint nyomtatvány)  a  WEB-es -Számla adat rögzítés -sel
mert a kézitömbben egyetlen áfatartalom érték adható meg. A WEB oldalon viszont többféle egyetlen
számlán belül.

Akkor lenne szinkronban  a kézitömb (mint nyomtatvány) a WEB-es -Számla adat rögzítés -sel ha
a WEB oldalon is csak egyetlen áfatartalom értéket lehetne megadni. 
Természetesen több tétel esetén  mindig ugyanaz az áfatartalom értéket szerepeljen.

És ebben az esetben már sínen vagyunk a nettó-áfa-bruttó  érték hármassal

**Comment by KMGY100** [comment]
OK. Rendben van.
SIMPLIFIED számla esetén számlaszám alapján  a   QueryInvoiceDigestResponse  -ban
ciklusban  kiszámolható a   -vatConten- és a -vatContentGrossAmount-  értékek
alapján   az  egyes   -vatConten- hoz   tartozó   nettó-áfa-bruttó
és ezek összegzése adja a számlára vonatkoztatott nettó-áfa-bruttó  értékhármast.

**Comment by NTCA-supporter** [comment]
Ok. Ha nincs több kérdésed akkor légyszi zárd le a ticketet. Köszi
