### ISSUE TITLE
[Q&A] Helyes a beküldés lineVatData és lineGrossAmountData nélkül

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#263]
Üdvözletem!

A kérdésem elsősorban TAX-nak szól, és elnézést érte, hogy itt teszem fel, de látva az itteni gyors reakcióidőt reménykedem a kérés gyors tisztázásában.

Egyik ügyfelünk jelezte, hogy a számla adatok beolvasása és automatikus feldolgozása közben találkozott egy olyan adatbeküldéssel, ahol a partner **_sem a lineVatData sem a lineGrossAmountData adatot nem küldte el az adatszolgáltatás során, pedig a papír alapú (normál) számlán van adó összeg és bruttó összeg is feltüntetve minden soron_**.
A line beküldve így néz ki:
```
                <line>
                    <lineNumber>1</lineNumber>
                    <lineExpressionIndicator>true</lineExpressionIndicator>
                    <lineDescription>Szöveg</lineDescription>
                    <quantity>275</quantity>
                    <unitOfMeasure>PIECE</unitOfMeasure>
                    <unitPrice>1400</unitPrice>
                    <unitPriceHUF>1400</unitPriceHUF>
                    <lineAmountsNormal>
                        <lineNetAmountData>
                            <lineNetAmount>385000</lineNetAmount>
                            <lineNetAmountHUF>385000</lineNetAmountHUF>
                        </lineNetAmountData>
                        <lineVatRate>
                            <vatPercentage>0.27</vatPercentage>
                        </lineVatRate>
                    </lineAmountsNormal>
                </line>

```

Helyes ez így? A kiállító egy olyan szoftvert használ, amelyről vélelmezzük, hogy már eddig is nagy mennyiségben küldött be adatot a NAV felé, és fura, hogy így teszi, viszont felénk most jelezték először ezt és nem tudjuk, hogy általános megoldás ez náluk vagy eseti, de ami fontosabb helyes-e vagy sem...

Köszönöm!

**Comment by NTCA-tax** [comment]
Az áfa törvény alapján a normál számla összegeinél az adóalapot és az adókulcsot kell megadni, az adó összegét és a bruttó összeget nem. Ezért a sémában a lineVatData és a lineGrossAmountData nem kötelező elem.
Egyszerűsített adattartalmú számla esetén más a szabályozás, ott a bruttó értéket szükséges megadni a számlán. 
Visszatérve a kérdésedre, összeg szempontjából helyes az XML, mivel a lineAmountsNormal került kitöltésre.

**Comment by omachtandras** [comment]
Köszönöm a választ!
