### ISSUE TITLE
[Q&A] Fordított ÁFA-s számla adószám kérdés

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#264]
Egy NAV által kiadott alábbi anyag: "A számlaadat-szolgáltatás 2020. július 1-jétől alkalmazandó szabályai kibocsátói oldalon" utolsó oldalán ez olvasható:

"E változás kapcsán hangsúlyozandó, hogy a belföldi fordított adózás hatálya alá tartozó ügylet
esetén az adószám 11 számjegyét kell szerepeltetni a számlán, az első 8 számjegy feltüntetése
nem elégséges"

A mondatot el is látták törvényi hivatkozással, amit ide mutat:
"Áfa tv. 169. § d) pont da) alpontja."

Az egyetlen "bibi" a történetben, hogy az ÁFA törvény említett pontja NEM VÁLTOZOTT, tehát nincs semmilyen változás e kapcsán júliustól és mivel az ÁFA törvény pontosan így szó...l:

"da) adószáma, amely alatt mint adófizetésre kötelezettnek a termék értékesítését, szolgáltatás nyújtását teljesítették, **VAGY(!!!)**
db) adószáma, amely alatt a 89. §-ban meghatározott termékértékesítést részére teljesítették, **VAGY(!!!)**
dc) *  adószámának vagy csoportos általános forgalmiadó-alanyiság esetén csoportazonosító számának első nyolc számjegye, amely alatt, mint belföldön nyilvántartásba vett adóalany részére a termékértékesítést, szolgáltatásnyújtást teljesítették, feltéve, hogy a termék értékesítője, szolgáltatás nyújtója gazdasági céllal belföldön telepedett le, gazdasági célú letelepedés hiányában pedig lakóhelye vagy szokásos tartózkodási helye van belföldön;"

...így ebből két dolog következik:
- egyrészt nem változott semmi, mert eddig is így volt, tehát nem érthető, hogy a NAV miért gondolja, hogy változott valami
- a VAGY szónak az a jelentése, hogy megengedett a másik alternatíva is, ebben az esetben a dc pont alkalmazása, vagyis elegendő fordított adózás esetén is az adószám első 8 számjegyét küldeni

Szeretném, ha ezt tisztáznánk.,,, hogy akkor most hogy is van ez. Nem NAV állásfoglalásra vagyok kíváncsi, mert az sokszor nem egyezik a jogszabályi háttérrel (pl. e-számlázás tipikus esete...)

**Comment by Macskafarka** [comment]
nbeeps2 igazad van. A tv. 169.§ dc) pontja abban nem változik 2020.07.01.-től, hogy a számlán csak az adószám vagy CSASZ 1-8 karaktereinek feltüntetése elégséges. Azonban rádöbbentek arra a NAV-nál, hogy ha ezt valaki komolyan veszi, akkor a számla kiállító nem tudja kitölteni az xx65A-07 lapot és a befogadó nem tudja kitölteni az xx65A-08 lapot, mert ezekre az adószám,. vagy CSASZ 1-11 karakterei kellenek.
Ahelyett, hogy módosították volna a törvény szöveget, vagy a 07 és 08 bevallási lapokat, elkezdték azt terjeszteni, hogy fordított áfa esetén a számlára 1-11 karakter kell. 
Pedig nem.
Amióta vannak ÁNYK nyomtatványok, azóta komoly dilemma az, hogy vajon a törvénynek kell-e megfelelni, vagy a nyomtatványnak.

**Comment by nbeeps2** [comment]
@Macskafarka Köszi :) Nekem mindig igazam van :D Nem igazán érdekel, hogy a NAV-nál mire döbbennek rá és ez nekik hol probléma. Ha az ÁFA törvény nem kötelezi erre a számla kiállítóját (már pedig nem kötelezi), akkor ne terjesszenek fals információkat! A kérdés azért fontos, mert a NAV-os XML-ben is elegendő csak az első 8 számot feladni, én is ezt teszem... A felhasználót se akarom feleslegesen csesztetni, hogy töltse ki a teljes adószámot, ha csak a 8 karaktert adta meg, amikor a törvény erre nem kötelezi. A törvény pedig a NAV felett áll. A NAV nem kérheti fordított adózásnál a 11 karaktert, ha ennek nincs meg a törvényi háttere. A legelső számlázós fejlesztői konferencián is elhangzott, hogy a NAV XML-ben csak azokat az adatokat kell kitölteni kötelezően, ami törvényileg kötelező, vagyis nem tekinthető hibás/hiányos adatszolgáltatásnak, ha egy fordított adózású számlát én úgy adok fel, hogy az adatszolgáltatásban fixen csak az első 8 karaktert küldöm...

**Comment by Macskafarka** [comment]
Részben.
A befogadó a számla alapján kell kitöltse az xx65-08 lapot. Ha a számlán az eladó adószámának 1-8 karaktere szerepelt, és ez törvényes, akkor nem kell sehol sem keresni a hiányzó 9-11 karaktereket, be kell adni így a bevallást. Csak így nem tud bemenni a bevallás.

**Comment by NTCA-tax** [comment]
Nos, az Áfa törvény 169. § da) pontja tényleg nem változott, de a tájékoztató sem erről szól... Amennyiben nem csak kiragadjátok a szövegkörnyezetéből ezt az egy mondatot, akkor a következőt látjátok magatok előtt. A tájékoztató ezen része arról ír, hogy a belföldi adóalany vevőnek az adószámának első 8 karakterét kötelező szerepeltetni a számlán. Ezt követően láttok egy olyan bekezdést, hogy ezzel a változással kapcsolatban felhívja a figyelmet arra, hogy belföldi fordított adózás esetén viszont a teljes adószámot kell szerepeltetni, tehát itt nem elégséges a 8 karakter.

Amennyiben a sémát is megnézitek, akkor szintén ezt látjátok visszaköszönni. Amennyiben egyenes adózás van, akkor az első 8 számjegy kerül a számlára, amennyiben belföldi fordított, akkor pedig a 11 számjegy (ezért opcionális az áfakód és megyekód).

**Comment by nbeeps2** [comment]
@NTCA-tax : elbeszélünk egymás mellett: "Ezt követően láttok egy olyan bekezdést, hogy ezzel a változással kapcsolatban felhívja a figyelmet arra, hogy belföldi fordított adózás esetén viszont a teljes adószámot kell szerepeltetni, tehát itt nem elégséges a 8 karakter" Én arról beszélek, hogy nem volt semmilyen változás! Mi változott? Hol? Hova van leírva, hogy a teljes adószámot kell szerepeltetni? Honnan vette ezt az illető, aki azt az anyagot írta? Erre keressük a választ, mert mi nem tudunk semmilyen változásról. Szóval tökéletesen értettük a mondatot, csak nem tudjuk, hogy mi az eredete ennek az agyszüleménynek, mert az ÁFA törvény ezen a ponton NEM VÁLTOZOTT! A sémában sem egyértelmű az, amit leírsz. Azért opcionális a sémában az áfakód és megyekód, mert lehet, hogy tudom (megadták) és lehet, hogy nem tudom (nem adták meg) és nem a fordított adózás miatt.

Kérlek idézd be az ÁFA törvény azon pontját, ami 2020. július 1-től lép életbe és előírja az adószám összes karakterének feltüntetését a számlán!

**Comment by nbeeps2** [comment]
"2020. július 1-jétől módosul a számla kötelező adattartalmára vonatkozó előírás is. Ennek
értelmében a számlán – függetlenül attól, hogy a bizonylat tartalmaz-e áthárított áfát illetve
milyen összegben – fel kell tüntetni a belföldi beszerző adóalany adószámának első 8
számjegyét.
....
E változás kapcsán hangsúlyozandó, hogy a belföldi fordított adózás* hatálya alá tartozó ügylet
esetén az adószám 11 számjegyét kell szerepeltetni a számlán, az első 8 számjegy feltüntetése
nem elégséges*. "
*Áfa tv. 169. § d) pont da) alpontja

@NTCA-tax : szóval a válaszod alapján szerinted sem volt változás, a változás ebben a kontextusban azt jelenti, hogy most már minden számlán fel kell tüntetni adószámot. Így is tudom értelmezni ezt a mondatot, ok. Viszont, amit utána ír a "költő" ráadásul ÁFA törvény hivatkozással az nem állja meg a helyét, mivel nem vagyok köteles a da) alpont szerint feltüntetni a vevő teljes adószámát a "VAGY" szó lehetőséget biztosít nekem a dc) pont alkalmazására és csak az első 8 karakter feltüntetésére. 

Szóval, kérlek idézd be a MEGLÉVŐ, AKTUÁLIS ÁFA törvény azon pontját, ami előírja az adószám összes karakterének feltüntetését a számlán fordított adózás esetén...!

**Comment by fzoli15** [comment]
A tájékoztató kérdéses mondatával fel akarták hívni a figyelmet arra, hogy a belföldi fordított adózású számlák esetén nincs változás, ugyanúgy a vevő teljes adószámát kell feltüntetni, ahogy eddig. Ha ezt a mondatot nem tették volna bele a tájékoztatóba, és valaki nem olvassa a törvény szövegét (vagy nem képes azt megfelelően értelmezni), akkor a tájékoztató alapján azt hihetné, hogy a belföldi fordított adózású számlák esetén is elegendő az adószám első 8 karaktere. Véleményem szerint ezért került ez bele a tájékoztatóba.

Az ÁFA tv. 169. § d) bekezdését nem jól értelmezitek, ugyanis nem veszitek figyelembe az "amely alatt..." kezdetű tagmondatokat. Ezek pontosan meghatározzák, hogy melyik pont melyik esetben alkalmazandó, nem a számlakiállító (vagy a számlázó program) döntésére van bízva, hogy melyiket alkalmazza. Épp ez a célja az ilyen tájékoztatóknak és információs füzeteknek, hogy segítsék a törvény értelmezését azok számára, akik nem szakavatottak a témában.

**Comment by nbeeps2** [comment]
@fzoli15 : nem értek egyet, de akkor segítsd nekem értelmezni. Se a da, se a db, se a dc pont nem említ fordított adózást. Az "amely alatt..." minden pontnál szerepel...
Nézzük, hogy szól például a da pont: 
"-  (a termék beszerzőjének, szolgáltatás igénybevevőjének) adószáma, amely alatt mint adófizetésre kötelezettnek a termék értékesítését, szolgáltatás nyújtását teljesítették, vagy"

Nos, itt nem beszél fordított adózásról és mivel ez a mondat MINDEN számlára igaz, így ez alapján ennyi erővel MINDEN számlán az adószámot kéne feltüntetni és nem az adószám első 8 karakterét. Viszont továbbra is ott a VAGY szó, ami lehetőséget ad a dc pont alkalmazására. 

A NAV-ra jellemző, hogy belemagyaráz nem létező dolgokat az ÁFA törvénybe, itt is ez történt és az e-számlázás során is ez a túlkapás jellemző...

Szóval kedves Zoli, akkor kérlek szépen írd meg nekem légy szíves hol látod az ÁFA törvényben, hogy a fordított adózásnál melyik pontot kell kötelezően alkalmazni, köszi!

**Comment by fzoli15** [comment]
@nbeeps2 Pont az általad is idézett, da) pont írja le, amit keresel.
"- (a termék beszerzőjének, szolgáltatás igénybevevőjének) adószáma, amely alatt **mint adófizetésre kötelezettnek** a termék értékesítését, szolgáltatás nyújtását teljesítették, vagy"
A vevő akkor lesz adófizetésre kötelezett, ha fordított adózás hatálya alá tartozik az ügylet.

**Comment by nbeeps2** [comment]
@fzoli15 : ha ez így van, akkor viszont ez a pont már ezer éve így van... nem most került be az ÁFA törvénybe... Miért most van hypeolva? ;)

**Comment by fzoli15** [comment]
@nbeeps2 Ezzel kapcsolatban is leírtam a véleményemet korábban:
"Ha ezt a mondatot nem tették volna bele a tájékoztatóba, és valaki nem olvassa a törvény szövegét (vagy nem képes azt megfelelően értelmezni), akkor a tájékoztató alapján azt hihetné, hogy a belföldi fordított adózású számlák esetén is elegendő az adószám első 8 karaktere."

Tehát ez a mondat a 2020.07.01-től hatályos szabályokat egyértelműsíti, és azt akarja kifejezni, hogy a fordított adózású számlák esetén nincs változás.

**Comment by Macskafarka** [comment]
Nekem már a **"fordított adózású számla"** fogalmának az értelmezése is problémás. Ugyanis a fordított adózás nem a számla egészéhez kapcsolódik, hanem a számla tételsorához! Láttam olyan számlát, amelyben volt egyenes áfás tételsor is, és fordított áfás tételsor is, ekkor néztem utána annak, hogy vajon tiltja ezt valami jogszabály? Én nem találtam tiltást. 
Szintén nem találtam arra sem tiltást, hogy a kapott előleget mindenképpen önálló bizonylaton kellene-e megjeleníteni, vagy mehet együtt más tételekkel?
Egy életszerű példa: Itt van a vevőm, aki vesz most tőlem egyenes áfás terméket (permetező szer) is, és fordított áfás terméket (vetőmag) is, de hagy még itt előleget műtrágyára. Ki és mi tiltja azt, hogy ezt egyetlen bizonylaton szerepeltessem?
Kényelmes dolog volt eddig a saját számlázó programunk korlátait úgy bemutatni, mintha ez lenne a jogszabályi előírás, de azzal, hogy letölthetők a NAV-tól a szállítói számlák, bizony más jogértelmezéssel készült számlákat is fel kell tudnunk dolgozni.
És ha szállítói számláknál lát az ügyfelünk olyan példákat, amely megtetszik neki, akkor ő is szeretne olyan számlákat kiállítani.
Nem véletlenül van úgy az OSD2.0 struktúrában a fordított áfásság és az előleg az nem a számlafejhez tartozik, hanem a tételsorhoz.

**Comment by Macskafarka** [comment]
Abszurd az, hogy mindez csak ezért, mert az xx65A-07 és 08 lap megköveteli. SEMMIN más oka nincs. Ha a partnerünk hó közben más megyébe költözik, akkor változik az adószámának a 10-11. karaktere. Ezért a xx65A-07 és 08 lapokon másképp kell szerepeltetni. De a NAVOnline adatszolgáltatásban 1-8 karakter és a xx65M-02 és 02K lapon ő egyetlen partnernek számít. Ez szerintem elég kuszaság.

**Comment by NTCA-tax** [comment]
Próbálok reagálni mindegyik felvetésre. Amikor az "adószám" fogalmat látjátok az Áfa törvényben, akkor a 11 jegyű adószámra vonatkozik a kötelezettség, hiszen az az adószám. Amennyiben ettől a fogalomtól a jogszabály eltérést enged, akkor az egyértelműen látszik a jogszabályban.
Ha megnézitek a július 1-jén hatályba lépő szöveget, akkor a következőt látjátok:
A 169. § da) és db) pontjai az adófizetésre kötelezett vevő adószámának a feltüntetését írja elő kötelezettségként. A dc) pont pedig leegyszerűsítve minden más belföldi adóalany vevő adószámának első 8 számjegyét írja elő kötelezettségként. Nem néztem utána, de ez tényleg nagyon régóta így van a jogszabályban. A hype-ot én sem értem, mivel az adóhivatali tájékoztató a dc) pont magyarázatával kapcsolatban csak felhívja a figyelmet, hogy a belföldi fordított adózásnál a vevő teljes adószámának a számlán meg kell jelennie.

**Comment by NTCA-developer** [comment]
Szerintem túlbeszéltétek a témát a Github kereteihez képest. Engedelmetekkel lezárom.
