### ISSUE TITLE
[Q&A] Eredeti tranzakció ID Annuálás és újraküldés esetén

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#267]
Ha annuálok egy számlát, akkor az annuálással kapok egy tranzakció ID-t. Tárolásra került a számla felküldésekor egy tranzakció ID és annuáláskor is az tranzakció ID. (Eddig két tranzakció ID.)
Hiba elhárítása után, amikor felküldöm újból a számlát, kapok egy új tranzakció ID-t. Ezzel felülírhatom az eredetit? Kellhet az még valamire? Elég ha csak a LOG-ban van benne? Vagy célszerű ennek egy helyet kialakítani az adatbázisban, hogy valamikor lekérdezhető legyen?
Köszönöm

**Comment by NTCA-supporter** [comment]
Szia @zsfoto !
Én hirtelen nem tudok róla, hogy ilyen esetben az eredeti transactionId-t tárolnod kellene.
Üdv

**Comment by NTCA-supporter** [comment]
Ha nincs több kérdésed @zsfoto, akkor légyszi zárd le a ticketet. Köszi
