### ISSUE TITLE
[Q&A] 0% ÁFA beküldése (gyűjtőszámlán lévő tétel)

### ISSUE THREAD

**Issue by szecsenyizoltan** [nav-gov-hu/Online-Invoice#268]
Éles rendszerből kaptam vissza hibát, erre a tranzakcióra: 30G4WK5WO0XQPMY6
(A programunkban a kollégák rögzítettek egy tételt ami 0% ÁFA (TAM) és kiszámlázták az ügyfélnek egy gyűjtőszámlán).
Erre a témára nem találtam sem a doksiban sem a példafájlokban egy olyan példát ami alapján valid lehetne a beküldés.
Segítséget kérek, mit rontok el. Köszönöm.

**Comment by NTCA-supporter** [comment]
Szia @szecsenyizoltan !
Pontosan milyen hibát kaptál?
Esetleg be tudnád küldeni teszt környezeten is ugyanazt a számlát?
Hivatalosan a github-os supporttal csak a tesztkörnyezetig látunk.

Köszönöm
