### ISSUE TITLE
[DEV Support] Séma hibát kaptunk éles rendszerből szeretnénk megtudni az okát mert nem látjuk az adatainkban

### ISSUE THREAD

**Issue by Charcsi** [nav-gov-hu/Online-Invoice#269]
T. Cím,
Éles rendszerből az ügyfelünk séma hibát kapott.
ERROR: SCHEMA_VIOLATION  -  XML contains on line: [65] and column: [505] error: [Invalid byte 2 of 2-byte UTF-8 sequence.]
ERROR: SCHEMA_VIOLATION  -  Xml validation failed

Nem látjuk a saját adatainkban, és a generált XML-ben a hibás karaktert(karaktereket). Szerintünk minden rendben van.

Meg tudnák vizsgálni hogy mi lehet a séma hiba oka. Önök milyen megjegyzést látnak? 
Éles rendszerben a tranzakció ID: 30G70JMBJHIC4HSS              

Köszönöm.
Üdv.

**Comment by NTCA-supporter** [comment]
Szia @Charcsi !
Esetleg be tudnád küldeni teszt környezeten is ugyanazt a számlát?
Hivatalosan a github-os supporttal csak a tesztkörnyezetig látunk.

Köszönöm

**Comment by Charcsi** [comment]
Szia
Megpróbáljuk, de lehet hogy ma nem megy csak hétfőre tudom küldeni.

**Comment by Charcsi** [comment]
Tisztelt Cím 
Sikerült elő állítani a teszt rendszerbe. 
A Hibás feltöltés Tranzakció ID je 
30PA83K3EL393MWG

**Comment by Charcsi** [comment]
@NTCA-supporter 

Sikerült megnézni a küldött adatot?

**Comment by Charcsi** [comment]
@NTCA-supporter 

Közben ebbe az jegybe is bele csatlakoztam. 
De a kérdés ugyan az.

[DEV support] XML contains on line: [56] and column: [19] error: [cvc-pattern-valid #285

**Comment by NTCA-developer** [comment]
Szia @Charcsi 

Mindjárt megnézem, délután valamikor jelentkezem. Addig kérem a türelmedet, igyekszem!

**Comment by NTCA-developer** [comment]
Szia!

Megnéztem.

` <dataValue>Az áru a teljes vételár megfizetéséig a TOOL-TEMP Hungária Kft. tulajdonát képezi.Késedelmes fizetés esetén a mindenkori jegybanki alapkamat kétszeresét számítjuk fel.A csomagolás környezetvédelmi-termékdíj kötelezettség az eladót terheli.A számla értéke közvetített szolgáltatást tartalmaz.Megrendelés:Szállítólevél száma: # TT-137 B&#x2F;BP szerszámtemperáló előzetes javítási ajánlatGépszám: 318-2482-4Hiba: Szivattyú nyomásemelése 2 bar, szállít</dataValue>`

A </dataValue> végén van egy karakter, ami nem UTF-8 valid. Egyébként ilyenkor csináld azt, hogy megnyitod a data XML-t egy valami épkézláb szövegszerkesztőben (Notepad++, Sublime stb) és pozicionálj arra a részre amit a válasz visszaad neked. Tehát ha ezt kapod, hogy:

`index>1</index><invoiceStatus>ABORTED</invoiceStatus><technicalValidationMessages><validationResultCode>ERROR</validationResultCode><validationErrorCode>SCHEMA_VIOLATION</validationErrorCode><message>XML contains on line: [62] and column: [491] error: [Invalid byte 2 of 2-byte UTF-8 sequence.]</message></technicalValidationMessages><technicalValidationMessages><validationResultCode>ERROR</validationResultCode><validationErrorCode>SCHEMA_VIOLATION</validationErrorCode><message>Xml validation failed</message></technicalValidationMessages>`

akkor nézd meg mi van a 62-es sor 491-es karakterén, az pont a 'szállító' stringnek az ó betűje. Valami ott mászik el nálad.

**Comment by Charcsi** [comment]
Kösssz nézzük ujra
