### ISSUE TITLE
[FEATURE] Az előleg pontosabb meghatározása

### ISSUE THREAD

**Issue by peterfordos77** [nav-gov-hu/Online-Invoice#27]
A számlatétel **advanceIndicator** mezője a jelenlegi Boolean helyett legyen Enumeration típusú, az alábbi jelentésekkel:
  - nem előleg
  - előleg vagy ügylet meghiúsulása miatti előleg sztornó
  - végszámlában beszámított (korábban számlázott) előleg

**Comment by NTCA-developer** [comment]
Szia, köszönjük szépen a felvetést.

Mielőtt továbbítom, kérlek írd meg, hogy az enumokat mire használnád, mi volna az üzleti hozzáadott értéke, mert nyilván megvolt az oka, hogy miért boolean lett. (Ha a benefit rész hiányzik, akkor nem biztos hogy hiánytalan lesz a megértés, mire gondoltál és miért javasolod.)

Köszönöm előre is!

**Comment by peterfordos77** [comment]
Egy számlatétel esetén az ELŐLEG fogalma két dolgot is jelenthet (mindkettő megfelel a jogszabályoknak, a konkrét esetben a felhasználó dönt arról, hogy éppen melyik értelmezést használja).
Írok egy példát:
 Első számla:
   - Leelőlegezem "A" terméket és kifizetem a vételár 50%-át 

Második számla:
  - Kifizetem "A" termék árának fennmaradó 50%-át, ( olyan számlát kérek amelyen a feltüntetik az első számlán történt előleg befizetésemet is, ezért "A" termékről két tétel is szerepel majd a számlán )

A második számlán az alábbi tételek szerepelnek (jelölöm a mostani advanceIndicator boolean értékét ):
  - "A" termék árának fennmaradó részének megfizetése ( advanceIndicator  = false )
  - "A" termék árának korábban megfizetett előlegének beszámítása ( advanceIndicator = true )

A második számla alakulhatna úgy is, hogy mégsem akarom megvenni az „A” terméket, ezért visszáruzzák az első számlán leelőlegezett terméket, ekkor a második számla tartalma így nézne ki:
-	„A” termék árának korábban megfizetett előlegének visszáruja ( advanceIndicator = true )

A fenti számlákon két tétel esetében is advanceIndicator = true szerepel, viszont jelentésükben lényeges különbség van, amit a számla könyvelésekor fontos lenne megkülönböztetni. Ha az advanceIndicator enumeration lenne, akkor ez a két eset megkülönböztethető lenne egymástól, mert:

-	Amikor tényleg megveszem a terméket és a számlán feltüntetik a korábban megfizetett előleget, akkor:
advanceIndicator = „végszámlában beszámított (korábban számlázott) előleg”

-	Amikor nem vásárolom meg a terméket és visszakapom a korábban befizetett előleget, akkor:
advanceIndicator = „előleg vagy ügylet meghiúsulása miatti előleg sztornó”

**Comment by KimmerGy** [comment]
Részemről nem javaslom az előleg  eddig alkalmazott  boolean jelölésének a megváltoztatását.
A javasolt 3 eset programon belül is megoldható ,  például ha adok külön lehetőséget az előlegszámla
készítésére ( ahogy -feltételezésem szerint- sokan megoldották )
Valamint: a számlát kiállító személynek egyszerűbb és **_érthetőbb_** a boolean jelölés.

**Comment by NTCA-developer** [comment]
Szia @peterfordos77 !

Átbeszéltük az általad javasolt előleg kezelést. Továbbítom a választ:

> Köszönjük a javaslatodat, átgondoltuk, de nem tudjuk támogatni. A sémában szeretnénk megmaradni a tiszta, egyértelmű jelölésnél, amennyiben összefüggéseket akarunk kimutatni, azt nem elemi szinten célszerű megtenni. Az általad javasolt információ megállapítható a számla típusából és az előleg jelöléséből. Amennyiben egy előleg számlát érvénytelenítünk, akkor nem érezzük annak fontosságát, hogy ezt még külön is jelöljük, elegendőnek látjuk, ha egy sztornó számlán belül szerepel az advanceIndicator jelzés.

A ticketet lezárom, ha van új javaslat vagy kérdés, nyiss nyugodtan egy újat.
