### ISSUE TITLE
[Q&A]Egyszerűsített számla AAM és TAM tételekkel

### ISSUE THREAD

**Issue by SimplifiedSzamla** [nav-gov-hu/Online-Invoice#270]
Szerettünk volna a tesztrendszerbe feladni egy egyszerűsített számlát. 
A számlán 4 tétel van: 2 tétel AAM-es, 2 tétel TAM-es. 
A számlaképen a tétel sorokban az áfa tartalomnál jelöljük, hogy az adott tétel AAM vagy TAM.
A számlaképen az áfa összesítőben a kettő különböző áfa mentességet külön - külön összegeztük (AAM és TAM sorunk is van).

A feladásra 4 WARN-t kaptunk vissza:

INCORRECT_SUMMARY_CALCULATION_VAT_CONTENT_GROSS_AMOUNT_HUF_SUMMARY_SIMPLIFIED
INCORRECT_SUMMARY_CALCULATION_VAT_CONTENT_GROSS_AMOUNT_SUMMARY_SIMPLIFIED
INCORRECT_SUMMARY_CALCULATION_VAT_CONTENT_GROSS_AMOUNT_HUF_SUMMARY_SIMPLIFIED
INCORRECT_SUMMARY_CALCULATION_VAT_CONTENT_GROSS_AMOUNT_SUMMARY_SIMPLIFIED

Ha jól gondolom, akkor ez a négy WARN azért jön, mert ha a summaryban lévő vatContent alapján próbálja szummázni a tételek értékeit, akkor a szumma eltér a summary-ban szereplő összegtől.

A tételeket és a summary-t az alábbi módon adjuk fel:

      <invoiceLines>
        <line>
          <lineNumber>1</lineNumber>
          <lineExpressionIndicator>true</lineExpressionIndicator>
          <lineDescription>AAM szolgáltatás 1</lineDescription>
          <quantity>1.000</quantity>
          <unitOfMeasure>PIECE</unitOfMeasure>
          <unitPrice>4500.00</unitPrice>
          <unitPriceHUF>4500.00</unitPriceHUF>
          <lineAmountsSimplified>
            <lineVatContent>0</lineVatContent>
            <lineGrossAmountSimplified>4500.00</lineGrossAmountSimplified>
            <lineGrossAmountSimplifiedHUF>4500.00</lineGrossAmountSimplifiedHUF>
          </lineAmountsSimplified>
        </line>
        <line>
          <lineNumber>2</lineNumber>
          <lineExpressionIndicator>true</lineExpressionIndicator>
          <lineDescription>AAM szolgáltatás 2</lineDescription>
          <quantity>2.000</quantity>
          <unitOfMeasure>PIECE</unitOfMeasure>
          <unitPrice>5500.00</unitPrice>
          <unitPriceHUF>5500.00</unitPriceHUF>
          <lineAmountsSimplified>
            <lineVatContent>0</lineVatContent>
            <lineGrossAmountSimplified>11000.00</lineGrossAmountSimplified>
            <lineGrossAmountSimplifiedHUF>11000.00</lineGrossAmountSimplifiedHUF>
          </lineAmountsSimplified>
        </line>
        <line>
          <lineNumber>3</lineNumber>
          <lineExpressionIndicator>true</lineExpressionIndicator>
          <lineDescription>TAM szolgátatás 1</lineDescription>
          <quantity>3.000</quantity>
          <unitOfMeasure>PIECE</unitOfMeasure>
          <unitPrice>6500.00</unitPrice>
          <unitPriceHUF>6500.00</unitPriceHUF>
          <lineAmountsSimplified>
            <lineVatContent>0</lineVatContent>
            <lineGrossAmountSimplified>19500.00</lineGrossAmountSimplified>
            <lineGrossAmountSimplifiedHUF>19500.00</lineGrossAmountSimplifiedHUF>
          </lineAmountsSimplified>
        </line>
        <line>
          <lineNumber>4</lineNumber>
          <lineExpressionIndicator>true</lineExpressionIndicator>
          <lineDescription>TAM szolgátatás 2</lineDescription>
          <quantity>4.000</quantity>
          <unitOfMeasure>PIECE</unitOfMeasure>
          <unitPrice>7500.00</unitPrice>
          <unitPriceHUF>7500.00</unitPriceHUF>
          <lineAmountsSimplified>
            <lineVatContent>0</lineVatContent>
            <lineGrossAmountSimplified>30000.00</lineGrossAmountSimplified>
            <lineGrossAmountSimplifiedHUF>30000.00</lineGrossAmountSimplifiedHUF>
          </lineAmountsSimplified>
        </line>
      </invoiceLines>
      <invoiceSummary>
        <summarySimplified>
          <vatContent>0</vatContent>
          <vatContentGrossAmount>49500.00</vatContentGrossAmount>
          <vatContentGrossAmountHUF>49500.00</vatContentGrossAmountHUF>
        </summarySimplified>
        <summarySimplified>
          <vatContent>0</vatContent>
          <vatContentGrossAmount>15500.00</vatContentGrossAmount>
          <vatContentGrossAmountHUF>15500.00</vatContentGrossAmountHUF>
        </summarySimplified>
        <summaryGrossData>
          <invoiceGrossAmount>65000.00</invoiceGrossAmount>
          <invoiceGrossAmountHUF>65000.00</invoiceGrossAmountHUF>
        </summaryGrossData>
      </invoiceSummary>

Normál számlánál tudok választani 0% helyett valamilyen mentességi okot, de ha jól néztem a specifikációt, akkor az egyszerűsített számlánál csak 0%-ot használhatunk.

Hogyan lehetne ezt az egyszerűsített számlát helyesen feladni WARN nélkül? 

Tranzakció azonosító: 30HREKIXTY6KYBIO

Előre is köszönöm a segítséget.

**Comment by NTCA-supporter** [comment]
Szia @SimplifiedSzamla !
Adószakmai részről kikérem @NTCA-tax véleményét, de így ránézésre, mivel simplified számlánál mind a négy tételnél 0 a lineVatContent, így az összegzőben egy summarySimplified csomópont van, 0 vatContent értékkel.
Köszi

**Comment by NTCA-tax** [comment]
A sémában az egyszerűsített adattartalmú számláknál nincs mentesség szerinti összesítés. A számla tételsorok alapján adótartalom arányonként kell az összegzést elvégezni. Így ha egy adótartalom aránynál bár van a tételsorokban különbség (különböző mentességi okok), akkor is egy összegző adatsor lesz az adatszolgáltatásban.

**Comment by pitfla** [comment]
Üdv!
Valahogy nem boldogulok az alanyi mentes számlákkal. Tudna feltenni valaki egy minta XML-t erre?
Köszönöm!

**Comment by NTCA-tax** [comment]
@pitfla  mi a pontos problémád az alanyi mentes számlával? Technikai vagy adójogi?

**Comment by pitfla** [comment]
Már most megoldódott. Egyébként technikai volt, nem volt egyértelmű, hogy mikor kell nullát átadni az áfaértékben, áfakulcsban.
De végül összejött.
