### ISSUE TITLE
[Q&A] Bejelzés kerekítésre

### ISSUE THREAD

**Issue by connorhu** [nav-gov-hu/Online-Invoice#271]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Sziasztok!

Az alábbi tranzakciókra bejelzett INCORRECT_SUMMARY_* hibákat. Én számolok el valamit, vagy az algoritmus jelez hibásan? Akárhonnan nézem, nem látom hogyan jött ki a pointer/value-ban megadott számérték. Ettől függetlenül elképzelhető, hogy én nézek be valamit.

30IG3IK7PG2VM6PA
30IG78QGU8M6CMK1
30IGCYTL7EAB295I

Köszönöm.

**Comment by NTCA-supporter** [comment]
Szia!

Nézzük és nemsokára visszajelzünk.

**Comment by NTCA-supporter** [comment]
30IGCYTL7EAB295I tranzakciót néztem meg részletesen. Ennél az volt a gond, hogy az invoiceSummary résznél a vatRateNetAmountHUF értéke megegyezett a vatRateNetAmount értékkel. A HUF-nál  árfolyammal beszorzott értéknek kell szerepelni.
A többi tranzakciót nem néztem. Ha azoknál más warningok jönnek akkor szólj és ránézek.

**Comment by connorhu** [comment]
Köszönöm a segítséget, meglett a hiba.
