### ISSUE TITLE
[Q&A] smallBusinessIndicator - Kisadózó jelzése

### ISSUE THREAD

**Issue by Rossi73** [nav-gov-hu/Online-Invoice#272]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Bizonyára mindenki számára egyértelmű... A **smallBusinessIndicator** mezőben a _kibocsátóra_, vagy a _vevőre_ vonatkozóan várja a NAV a TRUE/FALSE értéket? A dokumentáció erről nem rendelkezik egyértelműen. A tippem szerint a kibocsátóra, de jobb lenne egy megerősítés is hivatalosan.

Igazából azt nem értem, hogy ez a mező miért az invoiceMain/invoice/invoiceHead/**invoiceDetail** ágra került, miért nem az invoiceMain/invoice/invoiceHead/**supplierInfo** vagy a invoiceMain/invoice/invoiceHead/**customerInfo** ágra? Mint ahogy a másik új mező, az  **individualExemption** is az invoiceMain/invoice/invoiceHead/**supplierInfo** ágon található. Miért a számlához van inkább köze, és nem a kibocsátóhoz/vevőhöz magához?

Lehet, mindenki másnak kerek a történet, ez esetben elnézést. @NTCA-developer biztosan ad rá egy frappáns választ, melyet előre is köszönök. ;-)

**Comment by connorhu** [comment]
A számla kibocsátóját jelöli, hiszen a tövény annak kötelező szerepeltetését írja elő. A befogadóról csak sejteni lehet az áfakódból.

**Comment by omachtandras** [comment]
A számla jelzője, hogy KATA hatálya alá esik-e vagy sem.
A törvény lehetőséget ad arra, hogy egy KATA hatálya alá bejelentkezett adóalany olyan számlát állítson ki, amely nem a KATA hatálya alá tartozik.
Hogy ilyet csinál-e valaki, azt nem tudom, de a lehetőség adott, ezért van szerintem számla szinten a jelzés (és - szerintem - ezért van minden KATÁS bélyegzőjén rajta a KISADÓZÓ felirat, nehogy véletlenül elfelejtse a számlán feltüntetni, hogy azt a KATA hatálya alá tartozik...).

**Comment by szecsenyizoltan** [comment]
> A számla jelzője, hogy KATA hatálya alá esik-e vagy sem.
> A törvény lehetőséget ad arra, hogy egy KATA hatálya alá bejelentkezett adóalany olyan számlát állítson ki, amely nem a KATA hatálya alá tartozik.
> Hogy ilyet csinál-e valaki, azt nem tudom, de a lehetőség adott, ezért van szerintem számla szinten a jelzés (és - szerintem - ezért van minden KATÁS bélyegzőjén rajta a KISADÓZÓ felirat, nehogy véletlenül elfelejtse a számlán feltüntetni, hogy azt a KATA hatálya alá tartozik...).

pl.: KATA + ingatlankiadás

**Comment by fenyvessy** [comment]
Szerintem az ingatlan kiadást az jellemzően inkább adószámos magánszemélyként, KATA-n kívül illik csinálni, de pl. a tárgyi eszköz értékesítését KATA + AAM verzióban is ÁFÁ-t tartalmazó számlán lehet megtenni.

**Comment by NTCA-tax** [comment]
A 2012. évi CXLVII. törvény 12. § (2) bekezdése alapján kötelező feltüntetni a "Kisadózó" szöveget a számlán. A jogszabály alapján csak az értékesítő oldalán van ennek jelentősége.
Mivel ez a kötelezettség nem az áfa törvényen alapul, ezért az adatszolgáltatásban való szerepeltetése opcionális még akkor is, ha a számlán szerepel.

**Comment by Macskafarka** [comment]
**NTCA-tax** -tól érdekes ez a megközelítés.
A KATA-s számláról a befogadónak évente xxK102-es ÁNYK nyomtatványon bevallást kell benyújtani. Erre azt mondani, hogy csak az értékesítő oldalán van jelentősége.... 
Ha ehhez nem érkezik adat a NAV-tól a számla letöltésből, akkor lényegesen romlik az esélye annak, hogy valaki használni akarja-e a letöltést. 
Ráadásul most a kormány éppen egy új adót akar bevezetni arra, hogy a 3 Milla feletti KATA befogadót 40% adóval akarja sújtani.
Hogyan fogják követni a számla befogadó oldalon az összeget, ha a számla letöltésben nincs benne? 
A NAV-tól való adatletöltés kezd HASZNÁLHATATLAN lenni, az egész csak egy reklám volt, mert nem akarják azt, hogy használni lehessen. **Egy megbízhatatlan minőségű adathalmazra lehetetlen feldolgozási logikát építeni.**
Részemről már lassan kezd érdektelenné válni az egész dolog.

**Comment by NTCA-tax** [comment]
Az adatszolgáltatási kötelezettséget az áfa törvény írja elő. Ennek az oka, hogy nem terjeszkedhetünk túl az áfa törvény által előírt követelményrendszeren. Lehetőséget adunk számos nem áfa törvényen alapuló tartalmi elem megjelenítésére, de kötelezettségként nem tudjuk előírni. 

Az a mondatom, hogy csak az értékesítő oldalán van jelentősége, számlakibocsátás szempontjából értendő. Az alapkérdés arra vonatkozott, hogy az értékesítő vagy a vevő kisadózó jelzését takarja ez az elem. Tehát a kérdés szempontjából csak az értékesítő oldalán van jelentősége.
