### ISSUE TITLE
[Q&A] VatRateType - ÁFA kulcsok mezőkhöz rendelése

### ISSUE THREAD

**Issue by Rossi73** [nav-gov-hu/Online-Invoice#274]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Szeretnénk kérni egy összefoglalót, ami pontosan tartalmazza, hogy a jelenleg használt - NAV által alkalmazott - ÁFA kulcsok esetén melyik ÁFA kulcsot melyik mezőben kell szerepeltetni a VatRateType típusban:

**5%** (5%-os áfa): vatPercentage = "0.05"
**18%** (18%-os áfa): vatPercentage = "0.18"
**27%** (27%-os áfa): vatPercentage = "0.27"
**AAM** (alanyi adómentes): vatExemption = "AAM"
**ÁTK** (áfa területi hatályán kívül): vatOutOfScope = "true"
**EAM** (adómentes termékértékesítés a Közösség területén kívülre (termékexport harmadik országba)): vatExemption = "EAM"
**FAD** (belföldi fordított adózás): vatDomesticReverseCharge = "true"
**K7%** (kompenzációs felár 7%): vatPercentage = "0.07"
**K12%** (kompenzációs felár 12%): vatPercentage = "0.12"
**KBA** (Közösségen belüli adómentes termékértékesítés): vatExemption = "KBA"
**NAM** (egyéb nemzetközi ügyletekhez kapcsolódó jogcímen megállapított adómentesség): vatExemption = "NAM"
**TAM** (tárgyi adómentes, ill. a tevékenység közérdekű vagy speciális jellegére tekintettel adómentes): vatExemption = "TAM"
**THK** (területi hatályon kívül): vatExemption = "THK"

A pontos meghatározás azért is fontos, mert bizonyos esetekben nem magát az ÁFA kulcsot kell beküldeni, hanem az annak a jelölésére szolgáló elemet "true" értékkel (pl. "FAD" esetén vatDomesticReverseCharge).

Nyilván, a rövidítések helyett, aki úgy gondolja, használhat teljesen kiírt elnevezést (erre a NAV nem tér ki a doksiban, hogy csak az általa megadott rövidítéseket lehet beküldeni), viszont a rövidítés mögött álló tartalomhoz egyértelműen hozzá kellene rendelnünk, hogy melyiket melyik mezőben küldjük be. Ehhez kérném a fenti lista áttekintését, illetve javítását a NAV-os kollégák részéről.

Előre is köszönöm!

**Comment by szecsenyizoltan** [comment]
Rácsatlakoznék a kérdésre:
Ha a számla AAM és TAM is, akkor melyikkel kell beküldeni?

**Comment by NTCA-tax** [comment]
A @Rossi73 által felsorolt elemek megjelennek tételsorokban és összesítőben is egy hatos choice-ban. Ennek az elemei a következők:
- vatPercentage: ide kell írni az 5, 18, 27%-os adókulcsokat, valamint a kompenzációs felárat (amennyiben számla és nem felvásárlási jegy kerül kiállításra)
- vatExemption: az adómentes értékesítés szövegét kell feltüntetni, melynek nagyon sok oka lehet (pl. alanyi mentes, tárgyi mentes stb.)
- vatOutOfScope: áfa hatályán kívüli értékesítés, melyet nem szabad összekeverni az adómentességgel!
- vatDomesticReverseCharge: belföldi fordított adózás
- marginSchemeVat: adót tartalmazó különbözet szerinti adózás
- marginSchemeNoVat: adót nem tartalmazó különbözet szerinti adózás

Amennyiben a számla alanyi mentes és tárgyi mentes tételeket is tartalmaz, akkor mindegyik tételsort be kell küldeni. Mindegyik adómentességi ok, tehát a vatExemption elemben kell feltüntetni.

**Comment by NTCA-developer** [comment]
Sziasztok!

Csak FYI, de úgy tudom hogy a 3.0-ban a mentességi jogcímek enummá fognak válni. Ez elég egzakt összefoglalás lesz.
