### ISSUE TITLE
[Q&A] ELECTRONIC PDF számla magánszemély részére

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#276]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
ELECTRONIC **PDF** számla magánszemély részére
Mi van abban az esetben, ha magánszemély, akinek a számláját nem kell még felküldeni a NAV-nak, de PDF-formában kéri a számlát?
A PDF file-ból generálok egy HASH-t és ezt a **electronicInvoiceHash** elembe kell felküldenem.
De a magánszemélyek számláit még nem kell felküldeni.
Most akkor kell a hash vagy nem? Vagy mindenképpen tároljam el és amikor e-mailben kiküldöm neki a számlát, akkor mellékelem a hasht, de nem küldöm fel a NAV-nak? Hogy is van ez?

Mi a megoldás?

Köszönöm

**Comment by NTCA-tax** [comment]
Az electronicInvoiceHash nem kötelezettség, hanem lehetőség. Amennyiben belföldi adóalany a vevő, akkor mindkét oldalon egy viszonylag egyszerű megőrzési szabály tartozik ehhez a mezőhöz (jelen példában a PDF-et és a hash kódot kell megőrizni). 

Magánszemélynek kiállított számlát egyelőre nem hoznám be ebbe a körbe, mivel még 2020. július 1-től sem lehetséges adatot szolgáltatni, amennyiben a vevő nem belföldi adóalany. Tehát a magánszemély vevő számára nem lehet olyan elektronikus számlát kiállítani, ahol ezt a hash kódot szeretné alkalmazni az értékesítő. Majd 2021. január 1-től kötelező lesz ezekről a számlákról az adatszolgáltatás, de ezen a hídon akkor menjünk át, ha már látjuk a 3.0-ás verziót.

**Comment by zjacint** [comment]
Sziasztok,

a kérdésre adott válaszban kitértek arra, hogy a magánszemélynek kiállított számlát nem lehet beküldeni. Ennek ellenére a felületre adószám nélkül is fel lehet tölteni a kiállított számlát, így gyakorlatilag a magánszemélynek kiállított bizonylatot is be lehetne küldeni.
Az adószám megléte nem kötelező adat? 

köszönöm!

**Comment by NTCA-tax** [comment]
Az adatszolgáltatási kötelezettség belföldi adóalany által belföldi adóalanynak kiállított számlákra vonatkozik. Mivel a magánszemély nem áfa adóalany, ezért nem lehet a magánszemély vevőnek kiállított számláról adatot szolgáltatni.

Jogszabályi oka van, miért nem kötelező mező az adószám. Egyrészt a jogszabályoknak nem teljesen megfelelő számláról is lehet így adatot szolgáltatni (warning üzenet ugyanakkor keletkezik), másrészt az áfa törvény 169. § dc) alapján az áfa regisztrált adózóknak nincs olyan kötelezettségük, hogy a belföldi teljesítésű ügyletek esetén a vevő adószámát feltüntessék.
