### ISSUE TITLE
0%-os áfa

### ISSUE THREAD

**Issue by eztEgyed** [nav-gov-hu/Online-Invoice#277]
Kérdésem a 0% áfát tartalmazó számlákkal kapcsolatos. Régi adatok beküldése során a 0%-áfát tartalmazó sorokhoz a:

<validationResultCode>ERROR</validationResultCode>
<validationErrorCode>INVALID_VAT_DATA</validationErrorCode>
<message>A számlában megadott áfakulcs vagy áfaérték nem engedélyezett.</message>
<pointer>
<tag>Invoice/invoiceExchange/invoiceSummary/summaryNormal/summaryByVatRate/vatRate/vatPercentage</tag>
<value>0</value>
</pointer>

Választ kapom. Mi lenne ilyenkor a helyes beküldési mód?

**Comment by szecsenyizoltan** [comment]
Ebbe én is belefutottam :)

https://onlineszamla-test.nav.gov.hu/api/files/container/download/Online%20Szamla_interfesz%20specifik%C3%A1ci%C3%B3_HU_v2.0.pdf

103. oldal
"Ez a típus szolgál egy számlatétel, vagy a számla összesítés (invoiceSummary) esetén az áfa mértékének
feltüntetésére, vagy annak jelölésére, hogy az adott tétel – különböző okokból – nem tartalmaz áfát.
A VatRateType típusú elemek az alábbi hat elem közül pontosan az egyiket tartalmazhatják,
sorrendben jelölve."

**Comment by csiakgyula** [comment]
> Ebbe én is belefutottam :)
> 
> https://onlineszamla-test.nav.gov.hu/api/files/container/download/Online%20Szamla_interfesz%20specifik%C3%A1ci%C3%B3_HU_v2.0.pdf
> 
> 1. oldal
>    "Ez a típus szolgál egy számlatétel, vagy a számla összesítés (invoiceSummary) esetén az áfa mértékének
>    feltüntetésére, vagy annak jelölésére, hogy az adott tétel – különböző okokból – nem tartalmaz áfát.
>    A VatRateType típusú elemek az alábbi hat elem közül pontosan az egyiket tartalmazhatják,
>    sorrendben jelölve."
> 
> +doksi 212. oldal

Üdvözletem,

Na igen, ezt próbáltuk mi is, de:

- VatExempt-et nem fogad el, normál számla esetében nem értelmezi a 0-t, mint lehetséges ÁFA-százalék értéket, csak egyszerűsített számla esetében, ami mondjuk egy késedelmi kamat vagy külön kerekítési sor kapcsán (pl. KP-s számla esetén) szintén probléma
- VatExempt esetében fogalmam sincs, hogy milyen string-eket fogad el (Áfamentes, Adómentes, ÁKK, TAM, KK nem működik, az biztos vagy legalábbis más hiba miatt nem tudtam leellenőrizni az érvényességét), ez hol van leírva? Se a törvényben nem találtam, se az API dokumentációban
- VatOutofScope = true XML értéket sem VatPercentage = 0, sem önállóan nem fogad be VatPercentage és VatExempt XML Tagok nélkül, INVALID_VAT_DATA a válasz erre is és ERROR

Próbáltam ma reggel is elérni a NAV Online Számla bejelentés kapcsán az informatikai segítséget, de 7 jogi osztályos kolléga után sajnos muszáj volt feladni, akkora a terheltségük. A ma reggeli napon már az Online Számla weboldal is beborult, így sem regisztrálni, sem belépni nem tudtunk oda, pedig nagyon fontos volna.

Nos, akkor most kérnék szépen segítséget vagy példa XML-t, amiben van késedelmi kamat sor vagy bármilyen nullás ÁFA-jú tétel, mert szeretném jól csinálni és kialakítani a saját rendszerben az API Invoice Content XML-jét annak érdekében, hogy minden egyes beküldött számla esetében zöld pipa legyen a visszajelzés.

Arról már nem is merek szólni, hogy önszámlázást is végez a megbízóm, így variálódik sokszor a technikai bejelentkezési adat, ezáltal nagyon fontos lenne, hogy megfelelően menjenek a számla beküldések.

Előre is köszönöm,

 Üdvözlettel,

Csiák Gyula
JADE Tanácsadó Kft.
+36 (70) 596-6590
csiak.gyula@jadeconsulting.eu

(Ideírom az összes elérhetőségem, hátha kapok gyors segítséget!)

**Comment by eztEgyed** [comment]
Nekem végül így befogadta, természetesen figyelni kell, hogy a summary részen is eszerint legyen beeírva.
A "vatExemption" tag tartalmára a kollégám - dokumentáció hiányában - a "Az adómentesség jelölése - Áfatv. 169. § m)" szöveget javasolta :-)))

<line>
          <lineNumber>1</lineNumber>
          <lineExpressionIndicator>true</lineExpressionIndicator>
          <lineDescription>XXXX</lineDescription>
          <quantity>1.000000</quantity>
          <unitOfMeasure>OWN</unitOfMeasure>
          <unitOfMeasureOwn>db</unitOfMeasureOwn>
          <unitPrice>12000.0000</unitPrice>
          <lineAmountsNormal>
            <lineNetAmountData>
              <lineNetAmount>12000.0000</lineNetAmount>
              <lineNetAmountHUF>4223640</lineNetAmountHUF>
            </lineNetAmountData>
            <lineVatRate>
              <vatExemption>Mentes</vatExemption>
            </lineVatRate>
          </lineAmountsNormal>
        </line>

**Comment by NTCA-tax** [comment]
Az áfa törvény alapján nem létezik 0%-os adókulcs. Ezek a termék/szolgáltatás értékesítések jellemzően valamilyen adómentes értékesítések, vagy területi hatályon kívüli értékesítések. Tehát az áthárított adót nem tartalmazó számlák esetén nem a vatPercentage elemet kell használni, hanem a lineVatRate többi 5 eleme közül az egyiket.

Amennyiben adómentes az értékesítés, akkor a mentesség okát a számlán szövegesen is jelölni szükséges. Ezt a szöveget kell a vatExemption elembe elhelyezni. Ez a mező maximum 50 karakter hosszúságú szöveget tartalmazhat, és a számlán megjelenő szöveggel kell azonosnak lennie. A mentesség okának leírása lehet rövidítés is, nem feltétlenül hosszú szövegre kell gondolni. A séma nem követel meg semmilyen konvenciót, nem tartalmaz enum listát.

**Comment by eztEgyed** [comment]
> Az áfa törvény alapján nem létezik 0%-os adókulcs. Ezek a termék/szolgáltatás értékesítések jellemzően valamilyen adómentes értékesítések, vagy területi hatályon kívüli értékesítések. Tehát az áthárított adót nem tartalmazó számlák esetén nem a vatPercentage elemet kell használni, hanem a lineVatRate többi 5 eleme közül az egyiket.
> 
> Amennyiben adómentes az értékesítés, akkor a mentesség okát a számlán szövegesen is jelölni szükséges. Ezt a szöveget kell a vatExemption elembe elhelyezni. Ez a mező maximum 50 karakter hosszúságú szöveget tartalmazhat, és a számlán megjelenő szöveggel kell azonosnak lennie. A mentesség okának leírása lehet rövidítés is, nem feltétlenül hosszú szövegre kell gondolni. A séma nem követel meg semmilyen konvenciót, nem tartalmaz enum listát.

Ez rendben van, de nem lett volna akkor már egyszerűbb, ha konkrétan van egy felsorolás a mentességekből? Gondolom ez azért véges számosságú indok lehet.

**Comment by NTCA-tax** [comment]
A jogszabály a mentesség okának leírását követeli meg, ezért került szöveges adattartalomba bele. A tételes felsorolást a gyakoribb mentességi okokra lehet készíteni, de nem feltétlenül véges a lista...

**Comment by csiakgyula** [comment]
Köszönöm a segítséget, a megoldás a következő, amit sikeresen leteszteltünk:

- VatPercentage, ha nulla, akkor nem szerepelhet se a LineVatRate csoportban a tételeknél, se a Summary csoportban az XML végén, csak a VatOutOfScope = true és akkor már elfogadja a rendszer, VatExempt-re sem a kerekítés, sem a késedelmi kamat esetében nem volt szükség.

**Comment by NTCA-developer** [comment]
Sziasztok!

Úgy látom megvan a kérdésre a válasz, engedelmetekkel ezt lezárom.
