### ISSUE TITLE
Nulla értékű számlák jelentése

### ISSUE THREAD

**Issue by zsbaranyai** [nav-gov-hu/Online-Invoice#279]
Sziasztok,

Van olyan folyamat, amely során nulla értékű számla kerül kiállításra (azaz nem csak az ÁFA értéke, hanem a számla nettó és bruttó értéke is nulla. Ebben az esetben [cvc-complex-type.2.4.a: Invalid content was fou nd starting with element '{"http://schemas.nav.gov .hu/OSA/2.0/data":invoiceNetAmount} hibaüzenet érkezik. Azaz már a séma validáció jelez hibát.
Az API dokumentáció nem szól erről az esetről, csak negatív értékű eredeti számlákról. Mi a teendő ilyen esetekben? Számíthatunk módosításra, vagy ezek a számlák kimaradnak az adatszolgáltatásból?
Köszönöm!

**Comment by clapygeza** [comment]
A hibát az okozza, hogy az xml végén a <summaryByVatRate> tag kötelező. Amikor nullás a számla vége akkor ez nem képződik, hiszen nincs mit összegezni. (Így volt eredetileg, de bejött a hiba, amit írtál)
Külön kell lekezelni a programban, hogy ilyenkor egy tetszőleges, de létező áfa kulccsal (27%) képezzen egy nulla nettó, nulla áfa, nulla bruttó összesítő sort. Ezután már jó lesz.

Így kell kinézni az xml végén:

<invoiceSummary>
<summaryNormal>
<summaryByVatRate>
<vatRate>
<vatPercentage>0.27</vatPercentage>
</vatRate>
<vatRateNetData>
<vatRateNetAmount>0.00</vatRateNetAmount>
<vatRateNetAmountHUF>0.00</vatRateNetAmountHUF>
</vatRateNetData>
<vatRateVatData>
<vatRateVatAmount>0.00</vatRateVatAmount>
<vatRateVatAmountHUF>0.00</vatRateVatAmountHUF>
</vatRateVatData>
</summaryByVatRate>
<invoiceNetAmount>0.00</invoiceNetAmount>
<invoiceNetAmountHUF>0.00</invoiceNetAmountHUF>
<invoiceVatAmount>0.00</invoiceVatAmount>
<invoiceVatAmountHUF>0.00</invoiceVatAmountHUF>
</summaryNormal>
<summaryGrossData>
<invoiceGrossAmount>0.00</invoiceGrossAmount>
<invoiceGrossAmountHUF>0.00</invoiceGrossAmountHUF>
</summaryGrossData>
</invoiceSummary>

Nem biztos, hogy így gondolták, de működik :)

**Comment by clapygeza** [comment]
Bocsi, kicsit átszerkesztette ami írtam.
A hibát az okozza, hogy az xml végén a "summaryByVatRate" tag kötelező. Amikor nullás a számla vége akkor ez nem képződik, hiszen nincs mit összegezni.
Külön kell lekezelni a programban, hogy ilyenkor egy tetszőleges áfa kulccsal (27%) képezzen egy nulla nettó, nulla áfa, nulla bruttó összesítő sort. Ezután már jó lesz.

Így kell kinézni az xml végén:

"invoiceSummary"
"summaryNormal"
"summaryByVatRate"
"vatRate"
"vatPercentage>0.27</vatPercentage"
"/vatRate"
"vatRateNetData"
"vatRateNetAmount>0.00</vatRateNetAmount"
"vatRateNetAmountHUF>0.00</vatRateNetAmountHUF"
"/vatRateNetData"
"vatRateVatData"
"vatRateVatAmount>0.00</vatRateVatAmount"
"vatRateVatAmountHUF>0.00</vatRateVatAmountHUF"
"/vatRateVatData"
"/summaryByVatRate"
"invoiceNetAmount>0.00</invoiceNetAmount"
"invoiceNetAmountHUF>0.00</invoiceNetAmountHUF"
"invoiceVatAmount>0.00</invoiceVatAmount"
"invoiceVatAmountHUF>0.00</invoiceVatAmountHUF"
"/summaryNormal"
"summaryGrossData"
"invoiceGrossAmount>0.00</invoiceGrossAmount"
"invoiceGrossAmountHUF>0.00</invoiceGrossAmountHUF"
"/summaryGrossData"
"/invoiceSummary"

**Comment by connorhu** [comment]
Off: a 3 db ` karakter adja a markdownban a kódok beillesztésének lehetőségét (html, xml részleteket, amit escapel a github). Lásd:
https://guides.github.com/features/mastering-markdown/

**Comment by Rossi73** [comment]
> 
> 
> A hibát az okozza, hogy az xml végén a tag kötelező. Amikor nullás a számla vége akkor ez nem képződik, hiszen nincs mit összegezni. (Így volt eredetileg, de bejött a hiba, amit írtál)

A mi rendszerünk az összes számlatételt végignézi, és kulcsonként képezi az összesítőt: kulcs, alap, áfa összege. Azaz, tök mindegy, hogy mi az áfa kulcs, van-e nettó, bruttó, bármi, ha van legalább egy tétel a számlán, akkor lesz összesítő is... Lehet, hogy mi nem gondoltuk át, hogy ha valami nulla, akkor abból miért is kellene bármilyen összesítőt generálni, de most talán épp az a jó a fenti megoldásban, hogy minden esetben jól működik...

**Comment by NTCA-supporter** [comment]
Szia @zsbaranyai 

Ha jól látom akkor a többiek megválaszolták a kérdésedet. Ha igen akkor légyszi zárd le a ticketet. köszi

**Comment by zsbaranyai** [comment]
Így történt. Köszönjük a válaszokat!
