### ISSUE TITLE
[invoiceApi] Az ezred másodpercek legyenek opcionálisan megadhatók a timestamp tagban

### ISSUE THREAD

**Issue by NTCA-developer** [nav-gov-hu/Online-Invoice#28]
https://github.com/nav-gov-hu/Online-Invoice/issues/10

**Comment by Amn3s1a2018** [comment]
Annyit tennék hozzá, hogy a javasolt megoldással furán néz majd ki, hogy nem kötelező a tört rész, de tizedespont igen.
Így a "2019-05-30T011:34:01.T" helyes lenne, a "2019-05-30T011:34:01T" pedig nem.
`\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(.\d{1,3})?Z` lenne a jó szerintem, vagy ez:
`\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{1,3}Z`
