### ISSUE TITLE
ManageInvoiceRequest kérésre "The remote server returned an error: (500) Internal Server Error." hibát kapok. A kivételen belül annyit látok, hogy protocol error. TLS 1.2 engedélyezve van, a tokenexchange, QueryTaxpayerRequest rendben működik. Mi lehet a gond?

### ISSUE THREAD

**Issue by dorax** [nav-gov-hu/Online-Invoice#280]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[x] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[x] 2.0

**A requestId értéke / requestId value**
```
595852B48CE7437F858FDA33AC7AC0
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
The remote server returned an error: (500) Internal Server Error.

Status: ProtocolError

*Egyéb tartalom / Additional content*

TLS 1.2 engedélyezve, tokenExchange működik, parter adószám ellenőrzés működik

**Comment by NTCA-supporter** [comment]
Kedves @dorax!

Megnéztem a küldött requestId-t és a beküldött requestSignature értéke nem megfelelő. Annak a képzésében lesz valami gond a Te oldaladon.

**Comment by dorax** [comment]
Megtaláltuk a hibát. Egy Base64 konvertálás hiányzott az invoiceData-ra. Köszönjük.
