### ISSUE TITLE
[Q&A] Egyéni vállakozónak kiállított számla

### ISSUE THREAD

**Issue by zonehun** [nav-gov-hu/Online-Invoice#281]
Sziasztok,

Azt szeretném kérdezni, hogy egyéni vállalkozók adószámát is le lehet kérdezni a queryTaxpayer operációval? Azaz lehet a helyességét ellenőrizni?

Köszönöm!

**Comment by connorhu** [comment]
Igen. Több EVvel is teszteltem és visszaadta a helyes választ.

**Comment by zonehun** [comment]
Köszönöm!

**Comment by NTCA-supporter** [comment]
Ha jól látom akkor meglett a válasz, ezért lezárom.
