### ISSUE TITLE
[Q&A] WARN esetén mi a teendő? (Kiállító és vevő ugyanaz)

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#282]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Sikerült egy számlát saját részre kiállítani és WARN-nal jött vissza a lekérdezés, hogy a két adószám megegyezik a kiállító és az ügyfél esetén. Ugyan a számla 100+ Ft-os tételt tartalmaz, nem nagy összeg, de akkor is helyre kellene tenni, úgy érzem.
Mi legyen a következő lépés?
Köszönöm

**Comment by NTCA-tax** [comment]
Leginkább érvényteleníteni kellene a számlát, mivel nem történt gazdasági esemény.
