### ISSUE TITLE
TransactionRequest-re kapott üres válasz

### ISSUE THREAD

**Issue by era910413** [nav-gov-hu/Online-Invoice#283]
A mai nap folyamán folyamatosan üres válaszokat kapunk vissza a QueryTransactionStatusRequest során.
pl.
requestid=GAE656202007013781529

Megnéznétek mi a gond?

**Comment by NTCA-developer** [comment]
Szia @era910413 !

A teszt rendszeren nem találok ilyen requestId-vel bejövő kérést. Ezt hová (melyik környezetre) és mikor küldted? Egyébként általánosságban 2 esetben kaphatsz ilyen üres (és itt az egyébként séma valid, de processingResults tag nélküli válaszra gondolok) választ: ha a kérdezett transactionId nem létezik vagy nem a tiéd.

**Comment by era910413** [comment]
Szia!

Igen, az kimaradt hogy az élesre.. bocsánat.
Ugyanazt a számlát próbálom lekérdezni ezzel:
GAE83A202007025362894

És igazából nem ad vissza semmit, tehát nem processingResult nincs, hanem semmilyen respond-ot nem kapunk.

Az az érdekes, hogy a számlák nagy részét le tudjuk kérdezni, viszont több esetben futottunk ebbe bele.
A weben megnéztem és a transactionId rendben van.

Megnéznéd?
Köszönöm!

**Comment by era910413** [comment]
Látom, hogy több issue alatt odaírtátok, hogy a tesztre kellene beküldeni és ott megnézni, mert ott tudtok részletesen keresni. Az a baj, hogy ott ez a probléma nem áll fent, az élesben is csak a 06.30-án történt leállás után érzékeltük.

**Comment by NTCA-developer** [comment]
Szia @era910413 

Ezt  légy szíves a NAV HD-re beküldeni. Ha a felületen látod akkor biztos a tiéd és létezik is, meg kellene nézni. Szeretnék neked segíteni, de sajnos jelen keretek között nem tudok többet tenni.
