### ISSUE TITLE
INVALID REQUEST hiba

### ISSUE THREAD

**Issue by karasu-code** [nav-gov-hu/Online-Invoice#284]
Sziasztok,

kérnék egy kis segítséget, számlaküldés során INVALID REQUEST hibát kapok, néztem az xml formázottságát, a címet ahova a krését küldöm, de nem látom a hibát. HTTP 400 hibával érkezik vissza a kérés, tehát biztosan valami címzésbeli probléma van, de nem tudok rájönni.
[url] => https://api.onlineszamla.nav.gov.hu/invoiceService/v2/manageInvoice
[requestId]=>PIC0001593666233234

A tokenkérés működik, ott érkezik válasz is

**Comment by NTCA-supporter** [comment]
Szia @karasu-code,

Részletes hiba keresésre nekünk csak a teszt környezeten van jogunk, így légyszi oda küld be a számlát. Ott már meg tudjuk nézni, mi lehet a gond.
Köszi

**Comment by karasu-code** [comment]
Beküldtem, a requestId:PIC3061593699784333
Nekem segítség lenne az is, ha tudnám mi válthatja ki ezt a hibát.
Köszönöm.

**Comment by karasu-code** [comment]
Köszönöm megtaláltam a hibát.
