### ISSUE TITLE
[DEV support] XML contains on line: [56] and column: [19] error: [cvc-pattern-valid

### ISSUE THREAD

**Issue by kharonx** [nav-gov-hu/Online-Invoice#285]
Kedves Fejlesztők,

az alábbi hibát kapom ellenőrzéskor és nem sikerül máshol reprodukálnom. 
Mi lehet a probléma a cikknévvel?:

-<processingResult>

<index>1</index>

<invoiceStatus>ABORTED</invoiceStatus>

-<technicalValidationMessages>

<validationResultCode>ERROR</validationResultCode>

<validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>

<message>XML contains on line: [56] and column: [19] error: [cvc-pattern-valid: Value '2 toklász eltávolítása (+ altatás) ' is not facet-valid with respect to pattern '.{1,512}' for type 'SimpleText512NotBlankType'.]</message>

</technicalValidationMessages>

-<technicalValidationMessages>

<validationResultCode>ERROR</validationResultCode>

<validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>

<message>XML contains on line: [56] and column: [19] error: [cvc-type.3.1.3: The value '2 toklász eltávolítása (+ altatás) ' of element 'lineDescription' is not valid.]</message>

</technicalValidationMessages>

-<technicalValidationMessages>

<validationResultCode>ERROR</validationResultCode>

<validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>

<message>Xml validation failed</message>

</technicalValidationMessages>

<compressedContentIndicator>false</compressedContentIndicator>

</processingResult>

<originalRequestVersion>2.0</originalRequestVersion>

</processingResults>

Előre is köszönöm!

**Comment by NTCA-developer** [comment]
Szia @kharonx !

Trailing whitespace. Vedd ki a string végén lévő CR/LF karaktert.

**Comment by Charcsi** [comment]
Hasonló hibám van nekem is 
T. Cím,
Éles rendszerből az ügyfelünk séma hibát kapott.
ERROR: SCHEMA_VIOLATION - XML contains on line: [65] and column: [505] error: [Invalid byte 2 of 2-byte UTF-8 sequence.]
ERROR: SCHEMA_VIOLATION - Xml validation failed

Tesztrendszerben a Tran ID  30PA83K3EL393MWG

Nincsen tudomásom szerint nem küldjük az XML ben a  CR/LF.

Meg tudjátok nézni hogy mi megy be.
Én nem látok semi spécit

**Comment by connorhu** [comment]
Beküldés előtt érdemes az elkészülő XML-eket a rendelkezésre álló XSD alapján validálni és akkor még kliens oldalon ki fog derülni, hogy hol a hiba.

**Comment by NTCA-developer** [comment]
@Charcsi 

A te hibádnak semmi köze ehhez a kérdéskörhöz. Ilyen hibát amit te írsz akkor látok általában amikor a Data XML UTF-8 kódolása BOM-os. Ilyenkor azt kell javítani sima UTF-8-ra. De ez csak általános megjegyzés részemről. Az éles rendszerre nem tudunk supportot nyújtani, ne haragudjatok!

**Comment by Charcsi** [comment]
Ok 
Teszt rendszerbe ment be az adat ezzel a Tran ID val  30PA83K3EL393MWG
A probléma az ügyfélnél keletkezett azért indultam ezzel, de feltöltöttem adatot a tesztrendszerbe is annak lett id ja.
Nem látjuk a hibás karaktert az XML be .

Ti láttok ebből a Tranzakcióból valamit ?

**Comment by kharonx** [comment]
Köszönöm!

**Comment by Charcsi** [comment]
@NTCA-developer 

Köszönöm a választ. 

De Örülnék annak hogy tényleg meg tudnátok vizsgálni a beküldött adatot.
Ugyanis minden számlánk (nem kevés) bemegy mind a tesztbe mind az élesbe a programból,
Most van két ügyfelünk akiknék jelentkezik hiba egy-egy számla esetéban. (A hibás számla előtti 50 X számla gond nélkül bemegy az utána lévő 50 X számla gond nélkül bemegy)

Beküldtük a tesztrendszerbe a számlát azzal a megjegyzés szöveggel amit az ügyfél az éles számlájába megadott, és a teszt rendszer is dobta a hibát.
Mi nem látunk olyan karakter az XML-ben ami gondot okozna, ezért kérem a segítségeteket.

Teszt rendszerbe küldött számla Tran Id- ja : 30PA83K3EL393MWG              
Visszakapott hiba:
ERROR: SCHEMA_VIOLATION  -  XML contains on line: [62] and column: [491] error: [Invalid byte 2 of 2-byte UTF-8 sequence.]
ERROR: SCHEMA_VIOLATION  -  Xml validation failed

**Comment by szecsenyizoltan** [comment]
XML 62. sorát, ha bevágod, akkor lehet valaki észreveszi.

**Comment by Charcsi** [comment]
<dataValue>Az áru a teljes vételár megfizetéséig a TOOL-TEMP Hungária Kft. tulajdonát képezi.Késedelmes fizetés esetén a mindenkori jegybanki alapkamat kétszeresét számítjuk fel.A csomagolás környezetvédelmi-termékdíj kötelezettség az eladót terheli.A számla értéke közvetített szolgáltatást tartalmaz.Megrendelés:Szállítólevél száma: # TT-137 B&#x2F;BP szerszámtemperáló előzetes javítási ajánlatGépszám: 318-2482-4Hiba: Szivattyú nyomásemelése 2 bar, szállítá</dataValue>

Ebből nem látni. :(

**Comment by szecsenyizoltan** [comment]
Milyen kódolást használsz? UTF-8 vagy Latin-x?

**Comment by Charcsi** [comment]
Latin 2 az adatbázis és konvertálunk UTF8-ra küldéskor.

**Comment by szecsenyizoltan** [comment]
Tipp: a 491. oszlop kb a "ő" betű környéke lehet. Nem biztos, de megvizsgálnám őű-ket, mert azzal lehetnek gondok.

**Comment by topybear** [comment]
> 
> 
> ```
>                           <dataValue>Az áru a teljes vételár megfizetéséig a TOOL-TEMP Hungária Kft. tulajdonát képezi.Késedelmes fizetés esetén a mindenkori jegybanki alapkamat kétszeresét számítjuk fel.A csomagolás környezetvédelmi-termékdíj kötelezettség az eladót terheli.A számla értéke közvetített szolgáltatást tartalmaz.Megrendelés:Szállítólevél száma: # TT-137 B&#x2F;BP szerszámtemperáló előzetes javítási ajánlatGépszám: 318-2482-4Hiba: Szivattyú nyomásemelése 2 bar, szállítá</dataValue>
> ```
> 
> Ebből nem látni. :(

Az azért érdekes, hogy email-ben így jelenik meg:
"Szállítólevél száma: # TT-137 B&#x2F;BP szerszámtemperáló". Szerintem nézz rá arra a cégnévre...

**Comment by topybear** [comment]
> 
> 
> > ```
> >                           <dataValue>Az áru a teljes vételár megfizetéséig a TOOL-TEMP Hungária Kft. tulajdonát képezi.Késedelmes fizetés esetén a mindenkori jegybanki alapkamat kétszeresét számítjuk fel.A csomagolás környezetvédelmi-termékdíj kötelezettség az eladót terheli.A számla értéke közvetített szolgáltatást tartalmaz.Megrendelés:Szállítólevél száma: # TT-137 B&#x2F;BP szerszámtemperáló előzetes javítási ajánlatGépszám: 318-2482-4Hiba: Szivattyú nyomásemelése 2 bar, szállítá</dataValue>
> > ```
> > 
> > 
> > Ebből nem látni. :(
> 
> Az azért érdekes, hogy email-ben így jelenik meg:
> "Szállítólevél száma: # TT-137 B/BP szerszámtemperáló". Szerintem nézz rá arra a cégnévre...

Pontosabban a szállítólevél számban szereplő cégnévre, mert a sima cégnév jó. Persze a vad karaktereket jól kiszedte, így néz ki nálam:
[https://imgur.com/ilzoBcf](url)
