### ISSUE TITLE
Sokéves API support

### ISSUE THREAD

**Issue by hontvari** [nav-gov-hu/Online-Invoice#286]
Szeretném, ha a régi API verziókat legalább 10 évig engedné a NAV használni.

A 2.0 upgrade két munkanapunkat vette el, amit sokallok. Sőt, tényszerűen négyet, mert éjszakai meló lett belőle. Nem számlázó programot gyártunk, csak egy mellékes funkciója a programnak, hogy elküldi a számlákat, és csak egyetlen fajta, legegyszerűbb számlával foglalkozunk, talán még a stornózást támogatjuk. Gond, költség, idő volt újra elővenni a már elfelejtett kódot, felidézni, hogy mit hol találunk a NAV számlázás honlapon, hogy lehet tesztelni. Még úgy is, hogy igyekeztem mindent dokumentálni, és automatizáltan tesztelni. A számlák 100 éve pontosan ugyanolyanok, azt szeretném, hogy ezt tükrözze a számunkra kötelezően szükséges API változtatások gyakorisága.

(Javára legyen mondva, hogy azáltal, hogy a NAV visszautasította a számlaküldéseinket, legalább kiderült számunkra, hogy ezentúl a tízforintos számlát is fel kell küldeni, egyébként nem hallottunk volna az új rendelkezésről.)

Az rendben van számomra, hogy a régi verzióra azt mondjátok, hogy deprecated, és új fejlesztésnél ne használja senki, és javítani se fogjátok a hibákat. Elég ha ami eddig működik az ezentúl is működik. Az önmagában tetszik, hogy fejlesztetek, egyre tisztább lesz az API. 

Nyilván a NAV-nak ez többletmunka lenne, viszont isten tudja milyen sok alapvetően, napi szinten nem ezzel foglalkozó embernek egy csomó munkát megspórolnátok, országos szinten megtérül. A szakmai gyakorlat is az, hogy hosszútávú supportot adnak a fontosabb termékekhez. Pl. Ubuntu LTS verziók, 5 év ingyen + 3 év fizetős support. Windowsnál még hosszabb is talán a support.

Alternatívaként az is felmerült, hogy azok számára, akik naponta minimális mennyiségű számlát állítanak ki, adjatok egy egyszerűsített felületet.  Egy email címet, amire a program elküldi csatolva a számla XML-t, benne plusz két mezővel authentikációnak. Az SMTP pont arra van kitalálva, hogy ne vesszen el nyom nélkül soha levél. 50 éve működik, nagyon jó ebben, ez az email erőssége. A visszapattant leveleket, hibákat, pedig kézzel elintézné a felhasználó, az online számlafelvivő felületeteken.

**Comment by connorhu** [comment]
Távol álljon tőlem, hogy olyanba szóljak bele amihez semmi közöm, de most tételezzük fel a következő esetet. A NAV tovább supportálja az 1.x-es API-t, nem veszitek észre, hogy változott a jogszabályi környezet és a számláitok egy részéről nem szolgáltattok adatot, majd megy a büntetés és onnan veszitek észre. A jogszabályi környezet változásának követése pl egy olyan dolog amit magatoktól kéne csinálni, hiszen számláztok. Ugyan ez az API változások lekövetése is a fejlesztő feladata. Ha ennyire maginális számotokra a számlázás akkor vagy olyat kell megbízni a feladattal akinek ez a dolga és magától is követi, elfedi előletek egy 3rd party APIval az adatszolgáltatás változásait, vagy magatoktól kell ezt időről időre pingelni.
Ez utóbbi követés segítésére én örülnék olyan csatornának ami engem szólít meg (fejlesztői hírlevél a "Fejlesztői napló" oldal tartalomváltozásáról), és nem nekem kell időről időre felmenni az online számla oldalára és kitúrni onnan, hogy mi a következő változás.
Az én ügyfeleimnek is maginális feladat a számlázás, így én is ebben a cipőben vagyok és látom a szükséges feladatokat a pénzügyi környezet jogi és techinkai változásaival kapcsolatban. Mivel csinálom kell, így követnem is kell.

**Comment by eztEgyed** [comment]
Én pedig azt gondolom, hogy nem normális hogy félévente változzon egy API...
Nyilván azoknak a programozóknak akik a NAV rendszerét írják ez az élet, de mindenki másnak csak pluszmunka.
A tavalyi éveben 1.0-1.6-ig ért verzió ami gyakorlatilag állandó munkát jelentett volna.  Még jó hivatalosan 1.1-nél zártunk.

Egy API-t jól ki kell találni, szűk 1000-res körön (állami cégek) tesztelni és utána bevezetni.

**Comment by NTCA-developer** [comment]
Szia @hontvari !

Először is gratula, ha nem is ez a fő profilotok és 2 nap alatt átjutottatok a 2.0-ás átálláson.

Másrészről nincs mérlegelési jogunk abban, hogy a NAV meddig mit supportál, és rögtön arra is tudok válaszolni hogy miért nem fogja abban a formában teljesíteni amit kérsz. Az API iteratíven fejlődik az igaz, de közben elfelejtitek hogy az evolúció sem egy nagy waterfall projekt, elég zsákutcás koncepció lett volna nem lejönni a fáról addig amíg nincs PS4 meg Xbox.

Az API verzióit húzni kell fölfelé, mert a követelmények organikusan változnak, plusz a többlet szolgáltatások csak úgy alapíthatók rá, ha nem opció hogy valaki lemaradjon. Strukturálisan rossz, ha nincs egy minimum verzió megkövetelve mindenkitől. Viszont a magasabb verziójú API mindig visszafelé kompatibilis a régivel, a kérésednek ez a része legalább teljesül.

Sajnálom, de ez a kérés nem teljesíthető.
