### ISSUE TITLE
Onlineszámla oldalon technikai érvénytelenítés tömeges jóváhagyása

### ISSUE THREAD

**Issue by KKARACSONY** [nav-gov-hu/Online-Invoice#287]
Sziasztok, 

16000 beküldött számlát szeretnénk technikailag érvényteleníteni, de nem találjuk a lehetőséget a NAV felületen a tömeges érvénytelenítés jóváhagyására. 

Az ok, amiért érvényteleníteni szeretnénk a számlát: a számlaszám (invoicenumber tag) pl. 100 helyett 000100 -al lett beküldve korábban. 

Hogy van erre lehetőségünk? 

Köszönjük,

**Comment by NTCA-developer** [comment]
Szia @KKARACSONY 

Ez az API-n ez 160 darab, százasával kötegelt /manageAnnulment hívásba és a felületen ezt követően 160 darab elsődleges felhasználó általi jóváhagyásba fog kerülni. Nincs ilyen hipp-hopp tüntessük el az adatokat a rendszerből funkció, kifejezetten az volt a követelmény hogy ehhez explicit user jóváhagyás kell és kötegenként. (gyakorlatilag már a százas kötegelés is engedmény az eredeti koncepcióhoz képest)

**Comment by NTCA-developer** [comment]
@KKARACSONY  lezárhatom?

**Comment by KKARACSONY** [comment]
Igen, köszönjük! Ez jó megoldásnak tűnik a problémánkra :)
