### ISSUE TITLE
[Q&A] Végszámla adatszolgáltatás

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#288]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
**Miért változott meg a NAV jogértelmezése? És miért változik meg folyton?**
Az ÁFA tv. 10.sz. melléklete 2020.07.01-től bevezette azt, hogy a végszámla esetén csak a KÜLÖNBÖZET-ről kell adatot szolgáltatni.
Itt a GitHubon is többször volt erről szó, ahol én kicsit talán sokat is kérdeztem erről, és NTCA-tax próbálta megadni a válaszokat a legjobb tudása szerint. Kialakult egy konszenzusos álláspont. 
Szóba került itt, ezen a fórumon a végszámlának a xx65M bevallásban történő szerepeltetése, ahol szintén a KÜLÖNBÖZET-et kell csak bevallani -legalábbis a törvény megváltozott szövege szerint.  Rákérdeztem, hogy így kell-e, és igen. Lefejlesztettük. 
Az csak hab a tortán, hogy a törvényi változás előtt nem így kellett, de az utóbbi fél évben a NAV az ügyfeleinknek már azt kommunikálta, hogy eddig is csak a különbözetet kellett. Ezzel együtt eltűnt a NAV oldaláról a 2015-ös jogértelmezésük, ami még mást mondott (a törvény ebben a kérdésben akkor változott utoljára).
**Erre, mint derült égből a villámcsapás 2020.07.01-jén a NAV honlapján megjelent egy gyökeresen más jogértelmezés! Kitalálták azt, hogy minden egyes végszámláról 2-2 sorban kell adatot szolgáltatni!** Szerintük nemcsak a különbözet kell, hanem kellenek a termékértékesítő sorok is!
[https://nav.gov.hu/nav/ado/afa/A_szamlaadat_szolgalt20200701.html]
A nyomaték kedvéért ott van az alján ez: "[Pénzügyminisztérium PM/12861-1/2020. – Nemzeti Adó- és Vámhivatal Központi Irányítás 2475546404/2020.]"
Eléggé félreérthetetlenül fogalmaztak példával illusztrálva, ide másolom a szöveget:

" A számla milyen adatait kell szerepeltetni az M lapon?
Az adólevonás alapjául szolgáló számla esetében továbbra is az alábbi adatokat kell szerepeltetni az adatszolgáltatásban:
    a terméket értékesítő, szolgáltatást nyújtó adózó (áfa- vagy evaalany) adószámának – csoportos adóalany esetén csoportazonosító számának – első nyolc számjegyét,
    a számlában feltüntetett áfaalapot,
    a számlában feltüntetett áfaösszeget,
    a számla sorszámát,
    ha a számlában szerepel teljesítési időpont, akkor azt,
    ha a számlán nem szerepel teljesítési időpont, akkor a számlán szereplő számlakibocsátási időpontot.[8]

Ha az adóalany az áfabevallásban végszámla alapján érvényesít adólevonási jogot, akkor a 2020. július 1-jétől hatályos szabályok szerint az előző adatok feltüntetésén kívül, további adatokat is szerepeltetnie kell az adatszolgáltatásban. Végszámla alatt itt olyan, a teljesítésről kibocsátott számlát értünk, amiben az annak ellenértékébe beszámító (Áfa tv. 59. §-a szerinti) előleg elszámolása is megtörténik. Végszámla esetén adatot kell szolgáltatni az előleg figyelembe vételével adódó áfaalap, áfaösszeg különbözetről is.

Így abban az esetben például, ha az értékesített termék adóalapja 200 000 forint, adója 54 000 forint, és előlegként 127 000 forint megfizetése történt, akkor a végszámla alapján adatot kell szolgáltatni a 200 000 forint adóalapról, az 54 000 forint adóról és a 100 000 forint adóalap különbözetről, valamint a 27 000 forint adó különbözetről is."

**Több kérdés is felmerül ezek után:**
Aki eleget akar tenni ennek az elvárásnak a törvénybe ütközik. Aki eleget akar tenni ennek az elvárásnak az nem tudja megtenni az xx65M nyomtatványon, mert erre nincs felkészítve, pedig annak is megjelent egy új verziója 2020.07.01-jén. Mit tegyen az, aki jogkövető magatartást akar végezni? Várjon egy új xx65M nyomtatvány verzióra, hogy eleget tudjon tenni a közzétett elvárásnak?
Hagyja figyelmen kívül a törvényt, hogy a NAV honlapján leírtaknak tehessen eleget?
Vagy kezelje félrevezetésnek a leírtakat, és továbbra is a törvényt tartsa be? Vagy várja meg, amíg nyom nélkül eltűnik ez a szöveg is a honlapról?
Erre a jogértelmezésre NEM lehetett előre felkészülni! **Most sürgősen ki kell fejleszteni ezt a működést is a programunkban?** Lehet, hogy ki-be kapcsolhatóvá kell az ügyfelek számára tenni azért, ha esetleg az ÁFA bevallásig nem változtatják meg a szöveget, vagy ha mégis megváltoztatják? 
Valami ilyen paraméterre gondolok: A törvény szerinti adatszolgáltatást szeretne, vagy inkább a NAV honlapján közzétetteket követi? A felelősség, hogy minek hisz, legyen az ügyfélé.

**Comment by Macskafarka** [comment]
Végülis itt a vége.
Régóta ki lett hirdetve az ÁFA törvény 2020.07.01-től hatályos szövege, volt idő a jogértelmezésre, kérdésekre-válaszokra. 
Ennek figyelembe vételével jelent meg a PM-NAV közleménye, ami egy gyomrossal is felér.
Ezt már nehéz visszavonni. Legjobb esetben inkább csinálnak 2 sort az xx65M-02 lapon, és  közzétesznek egy újabb közleményt. 
**A szokásos csatornákon már nem is érdemes kérdezni sem**, egy NAV Igazgatóság sem bírálhatja felül ezt a közleményt, neki is továbbítani kell fölfelé, és várni a válaszra. Ezért a válasz úgysem érkezik már meg az ÁFA bevallásig. Tegyen mindenki a belátása szerint.

**Comment by Macskafarka** [comment]
Utólag próbálva értelmezni a dolgokat, a következő történhetett:
2015-ben, vagy előtte behozták az előleget is az áfa körbe, hogy előbb érkezzen az adóbevétel. Ezt elbírta a rendszer.
Az xx65M-02 lapon csak a termékértékesítésről kellett adatot szolgáltatni, mert ennek a számnak van gazdasági értelme, az előlegnek nincs (annak csak adótechnikai van), ezért arról nem is kellett Ez szépen működött is.  Az xx65M-02 lap volt az elsődleges adatforrása a NAV-nak. 
Amikor elindult az online vevői adatszolgáltatás, akkor azt gondolták, hogy meg fog szűnni a xx65M-02 lap is, ahogy a 01 lap is megszűnt, mert elsődleges adatforrásként elvesztette az értelmét. 
Amikor kiderült, hogy a számlakiállítói adatszolgáltatás nem kell minőségű, akkor hirtelen átpozicionálásra került a xx65M-02 lap szerepe, így lett belőle ellenőrzési adat . 
Aztán valamilyen okból kitalálták ezt a különbözet dolgot (amely szerintem összefüggésben van a másik kezelhetetlen dologgal a nem akarunk negatív CREATE számlát- elképzeléssel), és beletették a törvénybe a különbözetet számla kiállítói oldalon. Ekkor az összefüggések miatt tenni kellett valami a számla befogadói oldallal is, így a törvénybe belekerült az xx65M lap esetére is a KÜLÖNBÖZET. 
Igen ám, de amikor megkapargatták ezt a dolgot, és eljutott a probléma a szakemberekig, rájöttek, hogy továbbra is szükség van az xx65M-02 lapon a valódi termékértékesítés alapjára és adójára (mert ennek van gazdasági értelme), de az ő szakember szintjükön nem tudták megkerülni azt a (szerencsétlen) törvényi előírást, hogy a különbözet kell bevallani. Valószínűleg ezért született meg az idézett PM-NAV közleménybeli torzszülött, hogy akkor legyen két sor, a termékértékesítés azért, mert arra szakmailag szükség van, a különbözet meg azért, mert ez van a törvény szövegében.
Látni kell azt, hogy a negatív CREATE számla befogadásának ellenzése indíthatta el ezt az egész szálat.

**Comment by fzoli15** [comment]
Sajnos itt megint arról van szó, hogy a NAV jogalap, törvényi felhatalmazás nélkül kér plusz adatokat. 
Ezt már a NAV online adatszolgáltatásban bevezetett új forintosított (nettó) összeg mezők kapcsán is szóvá tettem itt a GitHub-on, de ugyanilyen a NAV által kitalált mértékegységtörzs is, és lehet, hogy van még más is, de hirtelen ezek jutottak eszembe.
Hihetetlen, hogy a NAV gyakorlatilag kénye-kedve szerint kérhet bármit az adatszolgáltatásokban, pedig elméletileg a szolgáltatandó adatok körét a törvény határozza meg...

**Comment by NTCA-developer** [comment]
Sziasztok!

Én teljesen nem értek ahhoz amiről ti diskuráltok, de tulajdonképpen itt van de facto megválaszolandó kérdés? És ez biztos egy technikai fórumra tartozik? Nem agitálok, csak kérdezem.

**Comment by Macskafarka** [comment]
Ide tartozik, mert olyan elvárás van megfogalmazva, ami törvénytelen, és technikailag teljesíthetetlen.
Arra kéne válasz, hogy hogyan lehet az xx65M-02 lapján megjelenő mezőkbe annyi adatot beletuszkolni, amennyit a PM-NAV közlemény tartalmaz, Miért nem fogad el egy számlát 2 soron a nyomtatvány, ha ez az elvárás?  Tervezik-e az xx65M-02 lapjának hozzáigazítását a PM-NAV közleményhez?

**Comment by Macskafarka** [comment]
Megválaszolandó az is, hogy miért használnak olyan technikát, amely ellentmond a közleménynek? Miért nem lehet az adatszolgáltatást TECHNIKAILAG akként teljesíteni, ahogy a PM-NAV közlemény leírja?

**Comment by NTCA-developer** [comment]
N haragudj hogy ismét visszakérdezek, de az Online Számla adatszolgáltatás hogy függ össze az M lappal? Mármint nem logikailag mert arra biztos van válaszod, hanem technikailag.

**Comment by Macskafarka** [comment]
A végszámla kezelést mindkettő esetén az ÁFA tv. 10.sz. melléklete tartalmazza. Mindkét esetben ez megváltozott 2020.07.01-én. Mindét esetben a végszámla esetén a KÜLÖNBÖZET-et írták elő, ami sem számlakiállítói, sem számla befogadói oldalon nem teljesíthető.
Ami a számla kiállítónál NAV Online adatszolgáltatással megy fel, azt a vevő letöltheti a NAV-tól, és abból kell tudnia xx65M-02 bevallást készíteni.
Amúgy pedig közismert, hogy a NAV az xx65M lapokat a NAV online számlaadat szolgáltatás ellenőrzésére használja fel.
Tehát "némi" összefüggés van.

**Comment by Macskafarka** [comment]
Az xx65M bevallást azért borították fel, mert valami rejtélyes okból nem nézik jó szemmel a negatív előjelű CREATE számlát a számla kiállítói oldalon.

**Comment by NTCA-developer** [comment]
Értem, köszi. Akkor sikeres egyeztetést kívánok.

**Comment by NTCA-tax** [comment]
Utána jártam annak, hogy az M lap pontosan hogyan fog kinézni ekkor:
- Amennyiben az előleg összege kevesebb a teljesítés összegénél, akkor az M lapon két sorban fog ugyan az a számlasorszám megjelenni: egyszer a teljesítés összege, egyszer pedig a különbözet. Az M lapot feldolgozzuk akkor is, ha egy számlasorszám kétszer került feltüntetésre.
- Amennyiben az előlegként a teljes összeg megfizetésre került, akkor a végszámláról az M lapot nem kell kitölteni

**Comment by Macskafarka** [comment]
@NTCA-tax  fáradozását köszönöm. Megszerezte a választ és elég gyorsan.
Maga a válasz lesújtó. Inkább lefejlesztik az 2065M-02 lap módosítását, minthogy a félresikerült törvényt korrigálnák. 
Ez a kerülőút kerülő útjának a kerülő útja, minden csak nem egyenes út. Tömegesen fognak elvérezni az adóalanyok a kitöltésnél.
korábban írtam azt, hogy szükség van a termékértékesítés alapjára és adójára, de a törvényben csak a különbözet került. így oda jutottunk, hogy akkor mindkettő kell, Egyik azért, mert értelme is van, a másik pedig azért, mert a törvényben ez szerepel. Ennek a történetnek itt van vége, 4-5 év, mire kimászunk ebből.
**Nincs vége viszont annak, hogy nem kell adatot szolgáltatni arról a végszámláról, amely teljes összege előlegként megfizetésre került.**
Ha az összes vevőmtől a teljesítés napja előtt 1 nappal pont annyi előleget kérek, mint amennyi maga a termékértékesítés lesz, akkor teljesen el tudom kerülni a végszámlának az xx65M-02 lapon való szerepeltetését. Persze adóhiány nem lesz, mert az előlegszámlát bevallom, és ráteszem az M-02 lapra, de sose fogja tudni a NAV, hogy volt-e termék értékesítés, vagy évek óta ott áll az előlegszámla.  Lesz még ebben a kérdésben is fejlemény szerintem.

**Comment by NTCA-tax** [comment]
Ezt az issue-t most lezárom. Jelenleg ehhez a témához többet szerintem nem tudunk hozzátenni... @Macskafarka hozzászólásával egyetértek, ebben a kérdésben ez csak átmeneti állapotnak tűnik...

**Comment by fzoli15** [comment]
> ... de sose fogja tudni a NAV, hogy volt-e termék értékesítés, vagy évek óta ott áll az előlegszámla.

Ezért nem értem én sem ebben a logikát. Ha 100%-os előleg esetén nem érdekes NAV számára a teljesítés (termék értékesítés), akkor 99%-os előleg esetén miért kell két sorban szerepeltetni a számlát, miért nem elég a különbözetet feltüntetni és kész?
