### ISSUE TITLE
[DEV support] Adószám gond 27926392-2-13

### ISSUE THREAD

**Issue by Charcsi** [nav-gov-hu/Online-Invoice#289]
Azt jelzi a rendszer hogy nincsen ilyen adószám ??? 
De van. 

Most mi legyen az Ügyfél nem tud számlázni.

**Comment by NTCA-developer** [comment]
Szia @Charcsi !

Nem értem a problémádat. Illetve értem, de azt nem hogy ezzel mi most mit kezdjünk. Kérlek pontosítsd, hogy mit szeretnél!

**Comment by Charcsi** [comment]
Szia
Az a gondom hogy az ügyfél nem tud partnert rögzíteni. Mert azt a választ adjuk a rendszerben hogy nem jó az adószám. 
Az adószámot a NAV rendszerén keresztül kérjük le, hogy biztosan fel tudjon menni a számla. Az adószám lekérdezés meg azt mondja hogy nem jó az adószám.

22 csapdája.

Vegyük le ezt az erős ellenőrzést, és menjen a számla majd fenn akad a számla beküldésnél? 

Mi a tanács?

**Comment by tkelemen73** [comment]
Ugyanezt a jelenséget tapasztaljuk mi is egy másik adószámmal 27943816-2-13. A nav.gov.hu adatbázislekérdezés szerint viszont létezik 2020.05.26-tól, a NAV Online produktív rendszer szerint viszont nem valós.

**Comment by NTCA-developer** [comment]
Utánakérdezek. Azt viszont nem tudom miért vélelmezi mindenki, hogy a vevői adószámnak validnak kell lennie ahhoz hogy befogadjuk. Egy WARN van rá, nem ERROR. Teljesen valid eset, hogy olyan adózónak kell kibocsátanod számlát, aki már nem létezik.

**Comment by Charcsi** [comment]
Minket Nem érdekel de a Felhasználók Folyamatosan befeszülnek hogy warningot kapnak, és biztos nem ment fel.

Volt olyan esetem hogy perrel fenyegetőzött a felhasználó. (Ezzel nem tudok mit kezden, megváltunk egymástól.)

Szóval akkor nem gond ha nem teljesen Valid az adószám.

Ok köszi a választ.

**Comment by Macskafarka** [comment]
Én számla kiállítást nem szakítanék meg azért, mert a vevő által bediktált adószám nem valid.
A WARN jogos érte, de ezen fájjon a vevő feje, mert ha nem az ő adószáma van a számlán, akkor nem gyakorolhat adólevonási jogot. És kérheti a számla kiállítótól a számla módosítását.
Én csak arra figyelnék szoftveresen, hogy adjak üzenetet, ha a levonható számlák közé olyan bizonylat került be amelynek nem valid a belföldi adószáma.  De a döntést ekkor is a felhasználóra bíznám.

**Comment by Charcsi** [comment]
@Macskafarka
Ez lesz. :)
