### ISSUE TITLE
Csoportos adószám kezelése

### ISSUE THREAD

**Issue by eztEgyed** [nav-gov-hu/Online-Invoice#290]
**Az igény összefoglalása / Summary of the request**
Csoportos ÁFAkód kezelése értelmetlenül bonyolult. A számlázó programok többsége nem kezeli a csoportos adószámot, így érvénytelennek minősíti. Lekérdezéskor az ÁFA csoport vezető cégét adja vissza, nem pedig a kiállítót. Számlát lekérdeni szintúgy nem lehet. A csoporttagok nem tudnak egymásnak számlázni, mert mindkettőnek ugyanaz az adószáma.

**Az általam javasolt megoldás / The solution I propose**
Csoportos ÁFA alanyok is használhatnák a sima a adószámukat, a NAV belső nyilvántartásában úgyis ott van egy egyértelmű összerendelés a sima adószám és csoportos adószám vonatkozásában.
A rendszer MINDEN cégnek a saját adószám használatát írná elő. A regisztrációtól a beküldésig. NAV belső rendszere pedig a csoportos adószám szerint group-olna, úgy hogy akinek nincs csoportos adószáma annak automatikusan a simával helyettesíti.

**Comment by Macskafarka** [comment]
A csoportos adószám alapvetően a NAV és a Csoport tagjai közötti jogviszonyt jeleníti meg. A csoport tagjai vállalják azt, hogy a NAV felé egyként felelnek az ÁFA tartozásért, cserébe az egymás közötti ügyletekj nem áfásak. Eddig értem.
De mi köze van egy harmadik adóalanynak a NAV és a csoport tagjai közötti egyezséghez? Miért kell másoknak azt jelezni a kiállított számlán, hogy "tudom ám, hogy csoporttag vagy". Ennyi erővel mást is rá lehetne írni a számlára, amit a vevőről tudok, vagy vélelmezek. Pláne olyan dolgot, amit vélelmezek a vevő és az adóhatóság közötti egyéb kapcsolatról.

**Comment by Macskafarka** [comment]
Persze, ha az az értelme, hogy lehessen azért büntetni, mert nem tudom azt a számla kiállításkor a vevőmről, hogy érvényes-e még a NAV-val kötött paktuma.   Érzékenyebb lelkűeknek: érvényes-e még a csoport tagsága, vagy 1 napja kilépett, vagy megszüntették.  Hogy ettől a tudástól függjön a számla kiállító adatszolgáltatása, az agyrém!

**Comment by NTCA-developer** [comment]
Sziasztok!

A kérdés eredeti részére @Macskafarka már válaszolt. (azért merek belebeszélni mert ezt a kört én is megfutottam még az elején és pontosan ugyan ezt a választ kaptam) A második kérdést nem értem "mi köze van egy harmadik adóalanynak a NAV és a csoport tagjai közötti egyezséghez", egy opcionális adatról beszéltek, ami ráadásul nem is titkos. Ergó kiállítói oldalon beküldeni nem kötelező, vevői oldalon meg nem baj az sem ha ott van, meg az sem ha nincs.

**Comment by eztEgyed** [comment]
"Ergó kiállítói oldalon beküldeni nem kötelező, vevői oldalon meg nem baj az sem ha ott van, meg az sem ha nincs."
1, Kötelező. Különben ABORT-al jön vissza, mert beküldő adószám hibás.
2, Az eladóim nem tudják nekem kiállítani a számlát - vagy nálam nem látszik lekérdezéskor.

**Comment by Macskafarka** [comment]
Igen a vevő CSASZ kötelező eleme a számlának. Ezt Írja a NAV honlapja:
[https://www.nav.gov.hu/nav/adopercek/Online_szamlaadat_szo20200526.html](url)
"**Online számlaadat-szolgáltatás csoportos adóalany vevő esetén**
A csoportos áfaalanyiság egy olyan speciális adóalanyiság az áfa rendszerében, amit a belföldön letelepedett, együttesen kapcsolt vállalkozásnak minősülő adóalanyok hozhatnak létre. Ők a csoportos adóalanyiság időszakában együtt alkotnak egyetlen áfaalanyt, és a csoport létrejöttével a tagok önálló áfaalanyisága megszűnik.

Ennek megfelelően, ha a terméket beszerző, szolgáltatást igénybevevő személy csoportos áfaalany tagja, akkor a részére kiállított számlán (ha az áthárított adó a 100 ezer forintot eléri vagy meghaladja, 2020. július 1-jétől pedig minden esetben) a csoportazonosító szám első nyolc számjegyét kell feltüntetni, nem pedig a tag adószámát. Így az online számlaadat-szolgáltatás során is a csoportazonosító számot kell a NAV-nak megküldeni."
**Tehát kell a vevő CSASZ a számlára, és akkor be is kell küldeni a vevői adatszolgáltatásban.**

**Comment by Macskafarka** [comment]
Tehát megint oda jutunk, hogy a NAV és a vevő közötti paktum másodpercre pontos ismerete kell ahhoz, hogy ki tudjam állítani a számlát, különben az én károm lesz, ha nem sikerül az adatszolgáltatás.

**Comment by Macskafarka** [comment]
Amikor számlázok, nem tudhatom, és ha a vevőm képviselője éppen ott áll a pultnál, akkor ő sem tudhatja, hogy a cége csoportalanyiságát bejegyezték-e a NAV rendszerébe, vagy a törlést átvezették-e a NAV rendszerén. De az adatszolgáltatásom nekem lesz visszautasítva, ebből nekem lesz munkám, költségem, károm. Ezt értettem az alatt, hogy "mi köze van egy harmadik adóalanynak a NAV és a csoport tagjai közötti egyezséghez". Miért lehet kára valakinek, ha nem tudja ezred másodpercre lekövetni a NAV és a vevő közötti paktum pillanatnyi állapotát?

**Comment by connorhu** [comment]
Mi van akkor ha kapunk egy dry run hívást ami csak annyit ad vissza, hogy
az adatok rendben vannak-e ha így beküldjük?

-- 
Üdvözlettel:
Gossler Károly

**Comment by NTCA-developer** [comment]
Tévedtek.

Eleve nem lehet titkos, ami a cégbírósági és a NAV adataiból publikusan elérhető. 

Másrészt tévedtek ott is ahogy a közleményt értelmezitek. Az csak annyit mondd, hogy ha ÁFA csoportnak számlázol akkor a customerInfo alatti adószámban a csoport adószámát kell szerepeltetni, de ez csak egy kitöltési követelmény. Sem ABORTED nem lesz rá, se meghalni nem fog senki ha rossz adószámot írtok be, lesz rá egy WARN, aztán kijavítod. Ez nekem is kérdésem volt régebben h mennyire elvárható a kiállítótól hogy tudja ÁFA csoport-e a vevője. Azt mondták hogy teljesen, persze ennek a szakmai igazságtartalmát én nem tudom megítélni. De a műszaki rész biztosan nem úgy van ahogy mondjátok.

Olyanon szerintem ne feszüljetek, aminek nincs alapja.

**Comment by eztEgyed** [comment]
"Eleve nem lehet titkos, ami a cégbírósági és a NAV adataiból publikusan elérhető."
Nem állítottuk, hogy titkos.  De:
"ha ÁFA csoportnak számlázol akkor a customerInfo alatti adószámban a csoport adószámát kell szerepeltetni"
Tehát reklámozni kell inden beszállítómnak, különben nem tud nekem számlázni.
És persze ezután én nem tudom letölteni, hogy nekem milyen számlát állítottak ki.

Csoport tag vagyok, úgyhogy örülök ha kijavítasz és segítesz, hogy hogy is kéne csinálnom, mert nem jöttem rá.

**Comment by Macskafarka** [comment]
Valószínűleg azért nem tudod letölteni a Neked kiállított számlákat, mert jogilag nem is neked (a cégednek) állították ki.
Ugyanis az ÁFA tv. 8.§ (2) b) pontja szerint a csoporttagsággal a céged megszűnt önálló cég lenni, nem kaphat és nem fogadhat számlákat, csak és kizárólag a csoportjának egésze jelenik meg mások felé.
**A törvény szövege:**
b: a tagok külső, harmadik féllel szembeni kapcsolataiban a gazdasági tevékenység folytatása olyan adóalanyiságot eredményez, amelyben az ehhez fűződő jogok és kötelezettségek a csoportos adóalanyiságban részt vevő valamennyi tagnak együttesen tudhatók be.
Tehát csak a csoportazonosító számra kérhetsz számlát kiállítani és a Te is csak a csoportazonosító feltüntetésével állíthatsz ki számlát.
Vagyis a saját adószámodat a számlán ne szerepeltesd, viszont a Csoportazonosító számodat pedig kötelező szerepeltetni. Nem megjegyzésként, hanem az adószám mezőben. Azt kell az adatszolgáltatásban is beküldened.
Ha te kapsz számlát, akkor ha nincs rajta a csoportazonosító számod, akkor nem gyakorolhatsz adólevonási jogot. Ha csak az adószámod van rajtam az kevés a levonási jog gyakorlásához.
De ez nem most lépett életbe, így van ez már régóta, csak senki nem követte le a jogszabályt. Se az adóalanyok, se az, aki ellenőrzi őket.

**Comment by Amn3s1a2018** [comment]
Én inkább úgy mondtam volna, hogy mindenkinek igaza van. :)

A mi nézőpontunkból tényleg feleslegesnek tűnik a csoport minden tagjának minden szállítóját ilyen szinten belekeverni az ügybe. Lehet, hogy ettől függetlül van értelme, de ha nincs akkoris így van, már az onlineszámla előtt is így volt, tessék felébredni!

Innentől pedig csak az a kérdés, hogy valid-e az adószám amit a vevőm megadott. Ha a számla kiállítás előtt ellenőrzöm (egy perccel egy nappal vagy egy héttel előtte), és a számla beküldéséig ez megválzoik, akkor így jártam. Régen valóban probléma volt, ha rossz adószámmal kiállítottam egy számlát és nem lehetett beküldeni. Aztán persze sztornó lett a vége és ott álltam két számlával és két teljesítetlen adatszolgáltatási kötelezettséggel. Amióta megváltozott, már kár is róla beszélni. Rengetegszer kell számlát módosítani azért, mert a vevő pl. elköltözött de csak akkor jutott eszébe szólni, mikor már megkapta a számlát és „már éppen ki akarta fizetni”, csak meglátta, hogy rossz. Ehez képest adószám miatti WARN talán ha egyszer fordult elő (és vannak ÁFA csoportos vevők is), pedig sokáig nem is használtuk az ellenőrzés lehetőségét. Ráadásul mivel azonnal küldeni kell a számlát, a WARN-ból kb azonnal tudom azt is, ha valami nem stimmel.

**Comment by Macskafarka** [comment]
Kiegészítés: A céged a csoporttagsággal csak belföldi értékesítésnél szűnt meg külön cég lenni, a határon átnyúló ügyleteknél saját nevében, saját adószámával vagy Közösségi adószámával jár el.

**Comment by NTCA-developer** [comment]
Köszi @Macskafarka a kiegészítést!

**Comment by Macskafarka** [comment]
Csoporttagság esetén valószínűleg érdemes lehet a belföldi számlázást, számla befogadást áfa bevallást a csoporton belül központosítottan kezelni. A csoportos áfa alanyiság választása egy cégtulajdonosi érdek, önkéntes döntés eredmény. Elég nagy rizikót jelent a készfizető kezesség miatt. Ezért tűnik ésszerűnek a közös belső ügyvitel a csoporton belül.

**Comment by eztEgyed** [comment]
"Tehát csak a csoportazonosító számra kérhetsz számlát kiállítani és a Te is csak a csoportazonosító feltüntetésével állíthatsz ki számlát."

Ez rendben van, és OK is. Csakhogy az adatlekérés során - nyilván a csoportazonosító számommal - sem látok semmilyen nekem kiállított számlát.

Ezért írtam, hogy pusztán azért mert a törvény a csoportazonosító feltüntetését kötelező teszi, ettől még a rendszernek nem kéne ilyen bénán működnie. Amikor törvényt kitalálták még elképzelés szinten se volt elektronikus beküldés. 

Viszont most akkor sincs rendben az, hogy ügyfeleim, sem én nem tudom a számlákat szétválogatni.

**Comment by NTCA-tax** [comment]
Amennyiben az áfa csoport tag állít ki számlát, akkor a számlán fel kell tüntetnie a csoportazonosítóját és a csoport tag adószámát is. Amennyiben a vevő az áfa csoport, akkor a jogszabályi kötelezettség kizárólag a csoportazonosító feltüntetésére vonatkozik (mivel ő az adóalany), ugyanakkor több adatot fel lehet tüntetni. A csoport tag adószámának az adatszolgáltatásban is van helye vevői oldalon is, így ha beérkezik az adatszolgáltatásban, azt is le lehet kérdezni.

**Comment by NTCA-developer** [comment]
@eztEgyed igen, értem a problémádat. ÁFA csoport tagjait a rendszer nem is engedi regisztrálni, csak az ÁFA csoportot képviselő adózót. Mivel csak a képviselő regisztrálhat, ezért nyilván csak neki van technikai felhasználója, aki csak a saját adószámára kiállított számlát keresheti. Ha az eladó nem az ÁFA csoport képviselőjére szolgáltatott adatot mind vevő, akkor ennek a számlának a vevő oldali lekérdezése is bukik. De ez egyértelműen hibás adatszolgáltatás így.

Szerintem annuláltasd a kiállítóval és küldjék be újra, immár a helyes adószámra.

**Comment by eztEgyed** [comment]
> @eztEgyed igen, értem a problémádat. ÁFA csoport tagjait a rendszer nem is engedi regisztrálni, csak az ÁFA csoportot képviselő adózót. Mivel csak a képviselő regisztrálhat, ezért nyilván csak neki van technikai felhasználója, aki csak a saját adószámára kiállított számlát keresheti. Ha az eladó nem az ÁFA csoport képviselőjére szolgáltatott adatot mind vevő, akkor ennek a számlának a vevő oldali lekérdezése is bukik. De ez egyértelműen hibás adatszolgáltatás így.
> 
> Szerintem annuláltasd a kiállítóval és küldjék be újra, immár a helyes adószámra.

Sajnos a számlázóprogramok 99% nem tartalmazza a csoportos adószám lehetőségét, csak a sima adószámot. Így max azt tudom elérni, hogy a sima adószám helyére a csoportos adószámomat adják meg (ezt meg jellemzően nem ismerik el adószámnak...), így bár megtehetnék, hogy mindkettőt beküldik, a gyarkorlatban ez nem valósul meg.

Ezért javasoltam, hogy sokkal egyszerűbb lenne mindenki számára (eladó és vevő) ha mindenki csak a sima adószámmal foglalkozna, as "csoportos adózóvá" alakítás a NAV rendszerén belül történne.

**Comment by NTCA-tax** [comment]
Ez nem az adatszolgáltatás miatt van, hanem az áfa törvény miatt. Az áfa törvény 169. § alapján a vevő csoportazonosítóját kell feltüntetni vevő adószámaként...

**Comment by eztEgyed** [comment]
Tehát akkor hogy tüntesse fel az eladó úgy az adatokat, hogy én is értelmesen megkaphassam?

**Comment by Macskafarka** [comment]
Ha az adószám 9. karaktere 5-ös, akkor CSASZ-ról van szó, ha 4-es, akkor csoporttag saját adószámáról. Minden más esetben nem csoporttag adószáma.

**Comment by Amn3s1a2018** [comment]
Esetleg az issue címében javítod, hogy a „csoportazonosító”-ról beszélünk, mivel így hívják?

> Sajnos a számlázóprogramok 99% nem tartalmazza a csoportos adószám lehetőségét

Hmm. Ezt mire alapozod? Egy hirtelen felindulásból elkövetett google keresés ide dobott ki:
http://www.szamlazovalaszto.hu/osszehasonlitas
Ezeknek csak egy töredékét ismerem (messziről), három egész biztos van ahol megadható a csoportazonosító.

Az, hogy a tv. el lett-e rontva, már egy másik kérdés, de pont a lekérdezés oldalról vizsgálva úgy tűnik nekem, hogy nem.

**Comment by Amn3s1a2018** [comment]
> Tehát akkor hogy tüntesse fel az eladó úgy az adatokat, hogy én is értelmesen megkaphassam?

Nem biztos, hogy jól értem, ezért valaki más is erősítse meg, de ha meg akarod kapni a rád mint csoporttagra kiállított számlát, akkor egy a csoportazonosítóhoz rendelt technikai felhasználóval kell kérdezned.
Ha a szállítóval ráíratod a számlára + beküldeted a `groupMemberTaxNumber`-t is (!), akkor szét tudod válogatni a saját számláid a többi csoporttagtól. Gondolom a csoporton belül nem probléma, hogy a tagok látják egymás számláit, hiszen „egyként felelnek” a csoport tevékenységéért.

**Comment by Macskafarka** [comment]
@Amn3s1a2018 Az ötlet tetszik, logikailag rendben van, sajnos én nem tudom kipróbálni, de én is kíváncsi vagyok működik-e.

**Comment by eztEgyed** [comment]
Igen, eddig lehet simán félreértettem az egészet.

Tehát:
"A szállító (eladó) adatai között a számlán kötelező feltüntetni azt az adószámot, ami alatt a gazdasági esemény történt (supplierTaxNumber elem, típusa: TaxNumberType). Amennyiben az eladó csoportos áfa-alany, akkor – az Áfa törvény előírásainak megfelelően – az eladó a csoport. A csoporttag adószámát pedig a groupMemberTaxNumber elemben (típusa: TaxNumberType) kell feltüntetni, amennyiben ez szerepel a számlán. "

Tehát ha az eladó csoportos tag akkor a számlán feltüntetni:
Adószám: XXXXXXX-5-XX  (kötelező)
Csoport tag adószám (???????) YYYYYYYY-4-YY  (opcionális) 

Na most, a világon MINDENKI (Nav saját oldala, cégbíróság stb,stb)  az "YYYYYYYY-4-YY"-t hívja adószámnak. 
A "XXXXXXX-5-XX"-t meg csoport(os) adószámnak.

Kivéve itt, mert itt minden fordítva van.

Az a két félmondat, hogy: "...az eladó a csoport. A csoporttag adószámát pedig..."  így erősen félrevezető, mert most már értem, hogy mire gondolt a szerző, de így leírva pont az ellenkezőjét is ki lehet belőle olvasni.

A kifejezéseknek meg érdemes lenne EGYÉRTELMŰ nevet adni, pl azt kikötni, csoporttag esetén az adószámon kívül kötelező kitölteni a CSASZ (csoportos adóazonosító szám) is az alábbi módon:

CSASZ: XXXXXXX-5-XX  (kötelező)
Adószám: YYYYYYYY-4-YY  (opcionális) 

Ez is teljesíteni tudja a törvényi előírást, de ezerszer egyértelműbb lenne, mint ez a cserebere. Ráadásul a törvény csak azt írja elő hogy szerepeljen, azt nem hogy az "Adószám"-rovatban szerepeljen, azt meg biztosan nem hogy online beküldésnél hogy variálnak vele.

**Comment by eztEgyed** [comment]
> Nem biztos, hogy jól értem, ezért valaki más is erősítse meg, de ha meg akarod kapni a rád mint csoporttagra kiállított számlát, akkor egy a csoportazonosítóhoz rendelt technikai felhasználóval kell kérdezned.

Mással nem is bírod, a tagok külön még csak nem is regisztrálhatnak.

**Comment by eztEgyed** [comment]
A törvény (arról, hogy mit kell tartalmazzon a számla) pontosan:

> c) a termék értékesítőjének, szolgáltatás nyújtójának adószáma, amely alatt a termék értékesítését, szolgáltatás nyújtását teljesítette;
> d) a termék beszerzőjének, szolgáltatás igénybevevőjének
> da) adószáma, amely alatt mint adófizetésre kötelezettnek a termék értékesítését, szolgáltatás nyújtását teljesítették, vagy
> db) adószáma, amely alatt a 89. §-ban meghatározott termékértékesítést részére teljesítették, vagy
> dc) *  adószámának vagy csoportos általános forgalmiadó-alanyiság esetén csoportazonosító számának első nyolc számjegye, amely alatt, mint belföldön nyilvántartásba vett adóalany részére a termékértékesítést, szolgáltatásnyújtást teljesítették, ....
> e) a termék értékesítőjének, szolgáltatás nyújtójának, valamint a termék beszerzőjének, szolgáltatás igénybevevőjének neve és címe;

Tehát a törvényben én nem látok olyat, hogy az ELADÓnak ki kéne írni a CSASZ-át, csak az adószámát.  
A Vevőnek viszont csak a CSASZ-át kéne feltüntetni. 
Ekkor viszont az XML-ben nem lehet egyforma tipusú a két adószám, csak ha felülírjuk a törvényt egy definicíóval.

Természetesen lehet azzal érvelni, hogy a "c"pontban az értékesítő az ÁFA csoport, de akkor az "e"pontban az áfacsoport vezetőjének a nevét kéne feltüntetni. Ami nyilván nonszensz lenne.

**Comment by eztEgyed** [comment]
> Kiegészítés: A céged a csoporttagsággal csak belföldi értékesítésnél szűnt meg külön cég lenni, a határon átnyúló ügyleteknél saját nevében, saját adószámával vagy Közösségi adószámával jár el.

Nem. Egy ideig mi azt hittük, de a csoportos adószámhoz EU adószám is dukál, és azt kell használni.

**Comment by NTCA-tax** [comment]
Elolvasva a bejegyzéseket, lehet, hogy az adóalany fogalmával kellene kezdeni. Amennyiben a jogszabály háttér érdekel valakit, az áfa törvény 8. § foglalkozik a csoportos adóalanyisággal.

Fontos, hogy a csoportos adóalanyiság csak az áfa tekintetében értelmezhető, cégjogilag, más adónem szempontjából önálló adóalanynak tekintendőek a tagok. Ebből a kettősségből adódhatnak a kérdések egy része. Áfa szempontjából a csoporttagok elvesztik önálló adóalanyi mivoltukat, az áfa törvény a csoportot tekinti adóalanynak. Így ha áfa csoport az értékesítő, akkor az adóalany maga az áfacsoport, nem pedig a csoporttag. Egy Art. szabályozás miatt azonban a csoporttag adószámát is fel kell tüntetni a csoporttag által kiállított bizonylatokon, így a számlán is. De ettől függetlenül az áfa törvény szemében a csoport jelenti az adóalanyt, és az adóalanynak vannak kötelezettségei, pl. számla kiállítási kötelezettsége, melyen fel kell tüntetnie saját adószámát, itt egészen pontosan csoportazonosítóját.

Vevői oldalon az áfa törvényben precízebb megfogalmazást találunk. Egyértelmű a szabályozás alapján mit kell feltüntetni áfa csoport vevő esetén. Itt egyértelműen a csoportazonosítót szükséges feltüntetni. Az adókód és megyekód feltüntetése nem kötelező (kivéve belföldi fordított adózású ügyletnél), így nem feltétlenül tűnik fel valakinek, hogy áfa csoport a vevő. Egyébként az áfa csoport adószáma mindig 177-el kezdődik, így ha az adókód nincs is a számlán, akkor is lehet tudni, hogy áfa csoport a vevő.

A vevő esetében a csoporttag adószámát nem kell feltüntetni, ennek inkább praktikus okai vannak. Itt ténylegesen kérdéses, hogy a számlázó program tudja-e kezelni a csoportazonosítót és az adószámot, vagy hogyan tehető a számlaadat részévé a csoporttag adószáma. Ez a kérdés már messze túlmutat az adatszolgáltatáson és a számlázási kérdéseken is...

**Comment by Macskafarka** [comment]
@NTCA-tax végre egy precíz leírás ebben a témában, amit meg is lehet érteni.
