### ISSUE TITLE
[invoiceAPI] Az adószám lekérdezés adja vissza az adózó típusát (cég vagy EV)

### ISSUE THREAD

**Issue by NTCA-developer** [nav-gov-hu/Online-Invoice#291]
https://github.com/nav-gov-hu/Online-Invoice/issues/149

**Comment by lvitya586** [comment]
Végül melyik megoldás lesz erre implementálva?
Korábban volt egy olyan javaslat is, hogy esetleg a statisztikai számjelből a gazdálkodási forma kódja kerülhetne visszaadásra. Ez járható út lehet?

**Comment by NTCA-developer** [comment]
Mivel a 3.0-ban még nem köt semmi bennünket ezért én a szép megoldást preferálnám, és vennék fel új elementet saját enummal a sémába. A DB-ben megvan ez az érték, ezért nem kell találgatni.

**Comment by connorhu** [comment]
Ezek az issuek a 2.0-s boardra kerültek és nem egy újra (pl 3.0).

**Comment by NTCA-developer** [comment]
Köszönöm @connorhu, javítottam!

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ez a feature tesztelhető a v3-as interfészen, teszt rendszeren.

Zárom az issuet, kérdés esetén lehet újranyitni.

Üdv
