### ISSUE TITLE
[Frontend] Sablon létrehozáskor a sablon neve kapja meg a fókuszt OSZ-ben

### ISSUE THREAD

**Issue by NTCA-developer** [nav-gov-hu/Online-Invoice#293]
https://github.com/nav-gov-hu/Online-Invoice/issues/240

**Comment by NTCA-supporter** [comment]
Az Online Számla 1.23-as verziójába fog belekerülni.

**Comment by NTCA-supporter** [comment]
A fejlesztés megtörtént, zárom.
