### ISSUE TITLE
[Frontend] A technikai felhasználó kulcsai legyenek akciógombbal vágólapra másolhatók

### ISSUE THREAD

**Issue by NTCA-developer** [nav-gov-hu/Online-Invoice#294]
https://github.com/nav-gov-hu/Online-Invoice/issues/253

**Comment by RuszinZsolt** [comment]
Egyetértek, a fájlban való letöltés is jó lenne, ha már nem tudtuk elérni, hogy a NAV kiküldje a sok-sok egyszerű adózónak a kulcsokat a tárhelyre. Az egér húzogatásával való copy+paste módszer azért se jó módszer, mert gyakran kerül fölös szóköz, sor a másolásba a felhasználó kézmozgásától függően, a duplaclick pedig azért nem jó módszer, mert az XML kulcsban van egy kötőjel és csak addig tart a kijelölés.

**Comment by eszel** [comment]
Nagyon sok pl. könyvelő inkább képernyőképet küld, amiből kiolvasni a 0/O I/1/L közti különbségeket ugyancsak nehézkes! :) 
Másik gond, hogy a technikai felhasználónak bekéri a rendszer a jelszavát, amit 90%-ban nem jól értenek, megadják az alap felhasználójuk jelszavát újra, azt hiszik, hogy azt kérte biztos-ami-biztos alapon a rendszer be újra. Ezután természetesen nem küldik át a jelszót, csak a felhasználónév/aláíró/cserekulcs hármast, nem tudják, hogy a technikainak állítottak be jelszót.. :)
