### ISSUE TITLE
[Q&A]manageInvoice után azonnali queryTransactionStatus-ra adott gyors Done nem látszik lekérdezettnek

### ISSUE THREAD

**Issue by GyPapi** [nav-gov-hu/Online-Invoice#295]
Miért nem írja felül a lekérdezve státusz a feldolgozva státuszt esetenként? / The question I would like to be answered**
Azon számla beküldések esetén, ahol a mI operációt azonnal követő qTS (1 sec belül) azonnal Done státuszt kapott, az online felületi "Adatszolgáltatások" lista, valamint a használati statisztika sem mutatja a "Lekérdezve" státuszt, helyette "Feldolgozott". Amely számlák nem kapnak azonnal Done-t és később újra le kell kérdezni a státuszt, ez az anomália nem áll fenn. Az interface naplót nem tudom ellenőrizni, mert az jelenleg a kiírás szerint nem működik (tényleg nem). Természetesen újbóli lekérdezéssel a gond orvosolható lenne (gondolom), de a beküldő modul jelenleg nem válogat a hírtelen Done és a később is Done állapotok között. A mostani helyzet viszont nem növeli a bizalmat, hogy nem rajzolt Done -e a program visszajelzése.
Ellenőrizhető-e, hogy mi a helyzet:
Éles online számla rendszer, 2020.07.02
queryTransactionStatusRequest-ek:
RID: RID20200702100340_43420432, Softver ID: HU1200701119950000, TR ID: 30QCMJ1YZWLEV684
RID: RID20200702094125_42085557, Softver ID: HU1200701119950000, TR ID: 30QBTX2BPKBCPC9L

Köszönöm, és Üdv.
NGy.

 / A clear and concise description of the question.

**Comment by NTCA-developer** [comment]
Szia @GyPapi !

Köszönjük szépen a bejelentést és hozzá az alapos körbedokumentálást! Csütörtökön mi is megtaláltuk ezt a hibát, javítás folyamatban.

**Comment by GyPapi** [comment]
Szia @NTCA-developer !

Köszi a gyors reagálást! Sejtettem, hogy a gyors párhuzamos folyamatok adminisztrációja okoz némi 'avart a zűrben. Akkor maradok az eddig megszokott és bevált folyamataimnál, ha majd érkezik Tőletek a megoldás.

Mi a szokás? Zárod, vagy zárjam az Issue-t?

Üdv
NGy.

**Comment by NTCA-developer** [comment]
Kérlek hagyd nyitva, hogy ha más erre téved akkor láthassa. Majd én lezárom ha a javítás élesítve lett.

**Comment by csaszko** [comment]
> Szia @GyPapi !
> 
> Köszönjük szépen a bejelentést és hozzá az alapos körbedokumentálást! Csütörtökön mi is megtaláltuk ezt a hibát, javítás folyamatban. A performancia optimalizálás után gyakorlatilag gyorsabban dolgozunk fel mint valaha, és ahogy te is írod ha pont akkor érkezik be lekérdezés amikor a tételek már végeztek de mi még nem vagyunk készen mindennel belül akkor valóban nem vált a kérés státusza állapotot, ti pedig jóhiszeműen nyugtázzátok hogy készen vagytok.

Szia @NTCA-developer!

Leírom, mert hátha számít a javításnál, ez a hiba már a kezdetektől fenn áll, nem csak most az optimalizálás után. 
Üdv
Csaszko

**Comment by NTCA-developer** [comment]
Szia!

Ez a javítás a múlt hét hétfői telepítésben kikerült élesre. Lezárom, köszi még egyszer a bejelentést!

**Comment by adAAM91** [comment]
Szia @NTCA-developer 

Csak jelezném, hogy nálunk továbbra is elő fordul a leírt jelenség.
@GyPapi nálatok?

Üdv
Á

**Comment by csaszko** [comment]
> Szia!
> 
> Ez a javítás a múlt hét hétfői telepítésben kikerült élesre. Lezárom, köszi még egyszer a bejelentést!

Ez alapján aug 31. volt amikor kikerült élesre. 09.01-el nekem is van ami 113-ból 15 ami Done volt 5mp-n belül és mégis "Feldolgozva" maradt.

**Comment by NTCA-developer** [comment]
Sziasztok!

Az biztos, hogy a javítás csak felmenő rendszerben akadályozza meg ezeknek a helyzeteknek a keletkezését, visszamenőlegesen nem javít státuszt. (nem is szabad nekünk beállítani ezeket)

Visszakerestem közben, a javítás a 2.12-es főverzióval, 2020.09.22-én került élesre. Az általatok jelzett dátum későbbi, ezért ezt a magunk részéről mindenképpen megnéznék. Kérlek küldjetek egy olyan státusz lekérdezés requestId értékét, ami egy ilyen nem átbillent státuszú tranzakcióhoz tartozik, és az elmúlt  napon belül történt. (itt tudunk gyorsan keresni)

Addig a ticketet visszanyitom.

**Comment by csaszko** [comment]
Én ilyet nem tudok már prezentálni, de ha mégis a 09.01-es requestId is segíthet akkor bemásolom majd.

**Comment by NTCA-developer** [comment]
Na várj. Már kicsit összefolyik már hogy mit-hol olvastam, de a javítás természetéből fakad hogy olyan lekérdezést kell keressünk, ami 09.22 utáni. Általánosságban sincs ez után a dátum után olyan lekérdezés, ami produkálja ezt a hibát?

**Comment by GyPapi** [comment]
Én elküldöm, csak ki kell gyűjtenem. Egyenlőre spóradisztikusan megy a lekérdezés, gondolom most mindenki ezt próbálgatja.

**Comment by csaszko** [comment]
Nekem nincs, 09.01. az utolsó ilyen.

**Comment by GyPapi** [comment]
Éles online számla rendszer, 2020.09.30
queryTransactionStatusRequest-ek:
RID: RID20200930065809_32289520, Softver ID: HU1200701119950000, TR ID: 34ARMM2A3604A51N
RID: RID20200930070635_32795424, Softver ID: HU1200701119950000, TR ID: 34ARXGEYXWSP7V9H
RID: RID20200930070637_32797889, Softver ID: HU1200701119950000, TR ID: 34ARXIASKEZPJG0I

Még ellenőrizni akartam a napló bejegyzéseink és az online felület TR ID adatait, de most már nem kapok találatokat, remélem  jól azonosítottam a számlákat. 

Ennél több számla is volt, amelyik az adatszolgáltatás utáni qTS-re azonnal Done-t kapott, így csak egyszer volt lekérdezve a státusza, de ez a három még most se mutat Lekérdezve státuszt.

Üdv.
NGy.

**Comment by alaplap** [comment]
Nekünk is van olyan ügyfelünk, aki kapott ilyen számlát. Most próbáljuk kisilabizálni a rendelkezésre álló adatokból, hogy mivel lehet a probléma. Egyébként ugyan arra hívja fel a figyelmet, mint @GyPapi a ti esetetekben, azaz _"számlázóprogramja „nem győződött meg” az adatszolgáltatás feldolgozásának sikerességéről"_ és hogy _"vegye fel a kapcsolatot a számlázóprogramjának fejlesztőjével, és intézkedjen a hibás működés mielőbbi javításáról"_.

Most azt tapasztaljuk, hogy borzasztóan nehéz visszaellenőrizni és kikeresni a rendelkezésre álló információk alapján a hibákat. Az alábbi problémákkal találkoztam idáig:

- A tájékoztató alapján "2020. július 1-jét követően" beküldött számlákat vizsgálták, ami 3 és fél hónap adata. Tehát az egyik probléma azzal van, hogy a vizsgált időszak túl nagy. 
- Az ügyfél több számlázóprogramot is használhat és a tájékoztató nem tér ki arra, hogy melyik számlázó program esetében tapasztaltak hibás működést. 
- Próbáltuk a tájékoztató alapján javasolt módon lekérdezni a _Szolgáltatások → Használati statisztika_ menüpontban az _interfész statisztikákat_, valamint lekérdezni a _Számlák → Adatszolgáltatások_ menüpontban a . Ott is azt tapasztaltuk, hogy nem lehet egy adott számlázó programra lekérdezni a statisztikákat.
- A _Szolgáltatások → Interfész napló_ menüpontban ugyan lehet számlázó program alapján is leszűrni adatokat, viszont ott kötelezően bekéri a "Kérés azonosítóját". Normál esetben 1 számlához 3 darab request (kérés) tartozik: TokenExchangeRequest, ManageInvoiceRequest, QueryTransactionStatusRequest. Mindegyiknek van egy `requestId`-ja a `head` tag-ben. Továbbá mindegyiknek van egy `softwareId`-ja a `software` tagben. Sajnos semelyik korábbi kérés `requestId` - `softwareId` párosára sincs megjeleníthető adat, tehát ez a menüpont - tapasztalataim szerint - nem működik.
- A lekérdezések sajnos sok esetben nem adnak eredményt. Erről közzéteszek egy képet is és a böngésző konzoljában látható adatokat, hátha segít. A kérés 1 percen belül (kb. 40 mp.) kerül elutasításra, nem az 1 perces timeout-tal függ össze.

A javaslatom az lenne, hogy:
- ha a jövőben is lesznek hasonló ellenőrzések, akkor sűrűbben tegyék azt meg, hogy a hibák kivizsgálása egyszerűbb legyen felhasználóknak/szoftverfejlesztőknek - minél kevesebb adatot kell átnézni, annál egyszerűbb megtalálni a hibát;
- legyen mód arra, hogy a _Szolgáltatások → Használati statisztika_ menüpontban az _interfész statisztikákat_ számlázóprogramonként meg lehessen tekinteni; és/vagy
- legyen mód arra, hogy a _Számlák → Adatszolgáltatások_ menüpontban számlázóprogramonként le lehessen kérdezni az adatszolgáltatásokat;
- továbbá ha megoldható, akkor a legtisztább az lenne, ha a tájékoztató e-mailben eleve fel lenne tűntetve, hogy mely számlázóprogram(ok) esetében tapasztaltak hibákat.

Ha van másnak egyszerű megoldása valakinek az ilyen e-mail kapcsán megtalálni, hogy mely számlák lekérdezésével lehet probléma, úgy szívesen várom a tanácsát.

-- Csatolmány: --
![kép](https://user-images.githubusercontent.com/5063192/95974502-58b08e80-0e15-11eb-99f3-42f59dd18590.png)

```
POST /rest/invoiceService/invoiceRequest/query undefined
Host: onlineszamla.nav.gov.hu
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
Accept: application/json, text/plain, */*
Accept-Language: hu-HU,hu;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
Content-Length: 298
Referer: https://onlineszamla.nav.gov.hu/szamlak/adatszolgaltatasok
Pragma: no-cache
Cache-Control: no-cache
x-language: hu
X-Version: 2.12.1
sessionToken: 8aa58963-4390-4db0-85da-75ba60191bc634UX514216Y8
login: ■■■■■■■■■■■■■■
Origin: https://onlineszamla.nav.gov.hu
Connection: keep-alive
Cookie: _ga=GA1.2.2091159764.1552567125; cookie-accept-did-show=true; _gid=GA1.2.711287577.1602598434; BIGipServer~PROD~PROD_k8s=rd2o00000000000000000000ffffac18822ao80; BIGipServer~PROD~PROD_fe=!2iYkLil4bZRngsJhHw8mNMUpFFR0w7R93ejlEwE4ESAbbvErwdHj+OeC4SxO4FB9gxMxAwKH2NYYzvk=
```

**Comment by alaplap** [comment]
Rossz issue-hoz írtam meg a bejegyzésem. :(

**Comment by NTCA-developer** [comment]
@csaszko , @GyPapi 

Közben megvilágosodásom volt. Ez a hét a nagy üzemzavar hete volt, és a 2.12-ben telepített szolgáltatás ekkor még nem futott a hibakeresés miatt. A javítás effektíve 2020.09.30 18:19 óta működik élesen!

A @GyPapi által mutatott tranzakciók 2020.09.30 reggel 8 és 9 közöttiek, ezért ekkor ők még pont beleestek a hibába. Tehát igazatok van abban hogy 09.22 óta ez nem működik, de azért mert a javítás később települt. 09.30-nál későbbi tranzakciónál nem történhet ilyen már. Így oké?

**Comment by GyPapi** [comment]
Részemről OK. Jelzem, ha mégis előfordul.

**Comment by csaszko** [comment]
Részemről is, köszi.

**Comment by NTCA-developer** [comment]
Mi is köszönjük!

**Comment by HWKF** [comment]
Gondolom itt lesz majd fontos szerepe a queryTransactionList operáció által V3-ban a transaction/requestStatus-ban visszaadott státuszainak, különösen a FINISHED (Feldolgozva), NOTIFIED (Lekérdezve) értékeknek. 
Most pont azok a problémásak, melyek a FINISHED státuszban vannak. Pedig mi úgy tudjuk, hogy DONE, mert azt "hittük", hogy lekérdeztük.

**Comment by EPluribusUnum** [comment]
@NTCA-developer , @renced42 : Még mindig fennál annak a lehetősége hogy a _queryTransactionStatus_() hívás után FINISHED marad az állapot és nem NOTIFIED lesz?
A probléma miatt annó karbantartó ág került a programba ami _queryTransactionList_() hívás kell hogy használjon. Ez a hivás viszont nem futtatható "Számlá kezelése" joggal, kell neki számla lekérdező jog is.
Ha még minidg van ilyen eset és szükség van a karbantartó ágra, akkor a _queryTransactionList_() hívásnak engedni kellene hogy menjen "Számlá kezelése" joggal, ne kelljen lekérdező jogot is adni a technikai felhasználónak,

Köszönöm.

**Comment by renced42** [comment]
Kedves @EPluribusUnum 

Elvileg ilyen eseteknek nem kellene előfordulnia. Ha mégis tapasztalsz ilyet akkor konkrétumok alapján tudjuk megnézni.
A jogosultságok most adottak azon nem tudunk változtatni.
