### ISSUE TITLE
Online Számlázó partner import

### ISSUE THREAD

**Issue by wossx** [nav-gov-hu/Online-Invoice#296]
Szeretnék partnereket importálni az Online Számlázóba, de - biztos az én hibám miatt - sehol nem találok leírást az import file szerkezetére vonatkozóan. Az itt készített exportot sem olvassa vissza a funkció (fejléc nélkül sem).
A dokumentáció egy "böngésző-specifikus CSV"-re hivatkozik, ami számomra ismeretlen fogalom.

Kérem szíveskedjenek egy linket adni az import CSV szerkezetére.

Köszönettel:
Wachter László

**Comment by NTCA-supporter** [comment]
Szia @wossx !
Hibaüzenetet kapsz a felületen?
A kiexportált CSV fájlt elvileg egy az egyben be kellene tudnod importálni simán, szerkesztés nélkül is.
Én most kipróbáltam belső teszt környezeten, és működött rendben.
Köszi

**Comment by wossx** [comment]
Üdv @NTCA-supporter  !

A hibaüzenet ez volt:  **Az importálás nem sikerült !**

De most újfent megpróbáltam az éles rendszeren, és most nekem is sikerült.
Közben arra gondolok, hogy korábban az exportban elrontottam a cégek nevét és adószámát, hogy az import után lássam, hogy történt valami. Az a sejtésem, hogy import-kor adószám-ellenőrzés történik, és amiatt utasíthatta vissza.
Most nem nyúltam hozzá, így megduplázódtak az azonos partnerek.

Elnézést a felesleges körért. Én nem gondoltam teljesen végig a lehetséges működést.

Köszönettel:
Wachter László

U.i.: Megjegyzem, ha már úgyis történik adószám-ellenőrzés, akkor a visszautasításnak (kihagyásnak) oka lehetne a párosság is. De majd odafigyelek.
