### ISSUE TITLE
[Q&A] HASH kód, amivel teljesítettnek tekintendő a megőrzés és az eredeti hitelessége 

### ISSUE THREAD

**Issue by RuszinZsolt** [nav-gov-hu/Online-Invoice#297]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Az 1/2018 ITM rendelet 7.§-a szerint teljesül a megőrzés, ha a HASH kóddal ellátva őrzi a NAV az online számla-adatszolgáltatás keretében beküldött számlát. Ezt hogy kell a gyakorlatban elképzelni? Az API-n keresztül is letöltődik a HASH kód? Az adózónak kell bizonyítania, hogy a HASH kódot őrzi, vagy az amúgy is látszik a NAV nyilvántartásában?

https://net.jogtar.hu/jogszabaly?docid=A1800001.ITM

**Comment by NTCA-tax** [comment]
A számlázó programnak az adatszolgáltatást megelőzően el kell készítenie az elektronikus számla dokumentumot, melynek a hash kódját az electronicInvoiceHash mezőbe kell elhelyeznie. Amennyiben az adatszolgáltatás feldolgozásra került, akkor mind az értékesítő, mind pedig a vevő le tudja tölteni API-n keresztül. 

A rendelet alapján az elektronikus számlát a hash kóddal együtt kell az értékesítőnek és a vevőnek is megőriznie (amennyiben mindkét fél ezzel a technikával biztosítja az archiválását).

**Comment by RuszinZsolt** [comment]
Szuper. Köszönöm a gyors választ. Akkor a https://onlineszamla.nav.gov.hu oldalról letöltött számlákban nincs electronicInvoiceHash mező, vagy legalábbis én nem látom. 

API-n keresztül letöltött számlák esetén van?

**Comment by NTCA-tax** [comment]
Felületen nincsen. API-n keresztül le lehet tölteni a teljes adatszolgáltatást, abban benne van.

**Comment by RuszinZsolt** [comment]
Még egy kérdés: ha a NAV őrzi a hash kódot, akkor az is megőrzés, hogy onnan bármikor letölthető API-n keresztül és tárolásra kerül?

Véleményem szerint ez azért aggályos, mert például az API-n, vagy a  letöltött számla a https://onlineszamla.nav.gov.hu oldalról letöltött számla nem tartalmaz fontos adózási adatot: a fizetési határidőt, ami az Áfa tv. 58.§ miatt szükséges az adókötelezettség pontos megállapításához. Más rovatról egyelőre nem tudok, de a fizetési határidő nagyon hiányzik.

**Comment by NTCA-tax** [comment]
A számla és az adatszolgáltatás adattartalmát nem szabad összekeverni. A hash kód a számláról készül, de a számla nem kerül be a NAV rendszerébe. A NAV rendszerébe az adatszolgáltatás adata kerül be, mely nem feltétlenül tartalmazza a számla összes adattartalmát. Így a NAV nem őriz számlákat, kizárólag egy elektronikus számlához kötődő hash kódot és egy olyan adatszolgáltatást, mely a számla egyfajta kivonatát jelenti.

Egyébként a fizetési határidő a sémában opcionális elem, a paymentDate mező tartalmazza. Ez a mező azért opcionális, mivel az áfa törvény nem írja elő a számla kötelező adattartalmaként, ugyanakkor amennyiben a két fél számára fontos, továbbíthatják az adatszolgáltatási rendszerben ezt a mezőt is.

**Comment by Amn3s1a2018** [comment]
Itt találsz az ITM rendeletnél (egy kicsivel) emberközelibb leírást az elektronikus számláról:
https://nav.gov.hu/nav/ado/afa/Az_elektronikus_szaml20200416.html

A hitelesség kérdésére jó válasz lehet a hash és az onlineszámla rendszer (ha beküldöd a hash-t). @NTCA-tax  válasza lehetne kicsit konkrétabb:
  - ha elkészíted és elküldöd a hasht a számlával együtt, mindkét fél archiválja és megígéri, hogy nem nyúl az adathoz, az még biztosan nem elég? Biztos nem!
  - ha a electronicInvoiceHash szerepel az adatszolgáltatásban, elküldöd a számlával együtt is, mindenki őrzi az adatot, akkor már biztosan nem keveredsz hitelesítetlen elektronikus számlázás gyanújába? Talán nem.

A bizonylat megőrzésre a másik feladat. Fontos, hogy ez a vevőnek is (tőled független) kötelezettsége. A webes számlázóprogramokkal kiállított számlák pl. úgy felelnek meg ennek, hogy a weboldal üzemeltetője megígéri, hogy mindenki helyett őrzi a számlát. Vevőként ilyen esetben nem érezném feladatomnak, hogy vizsgáljam az „őrzés” technikai hátterét, de ha az ígéretet nem sikerül betartani, a bírságot én kapom, nem az időközben esetleg eltűnt webes cég. :(

Akkor is felmerülhet probléma, ha a számla ugyan megvannak, de a hatóság úgy találja, hogy számla megőrzését végző (esetleg harmadik fél) nem kellő gondossággal végzi az őrzést?

**Comment by NTCA-tax** [comment]
Az adatmódosítás összes lehetséges esetét nem gondoltam a kérdés kapcsán kifejteni, de talán nem is erre irányult. Ez a fórum az adatszolgáltatással kapcsolatos kérdések megválaszolására jött létre, ennek megfelelően kell értelmezni a válaszomat. Az issue-t most lezárom, amennyiben a hash kóddal kapcsolatban felmerülne további kérdés, akkor egy új issue-t nyissatok rá.
