### ISSUE TITLE
[Q&A]Milyen adatbázissal lehet majd tesztelni?

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#30]
A V2-ben lehetőség lesz a beérkező (vevői) számlák lekérdezésére.
Az ehhez ügyfél oldalon szükséges programokat is ki kell fejleszteni és le kell tesztelni.
A kérdés az, hogy milyen adatbázissal? A jelenlegi tesz környezet egy adott ügyfélnél nem biztos, hogy tartalmaz bejövő számlákat, mert a partnerek fejlesztői más ügyféllel is tesztelhettek. Ezért elképzelhető, hogy nincs, vagy csak nagyon szűk lehetőség van a tesztelésre a jelenlegi teszt adatokkal. 
Megoldási javaslatom igazán nincs, csak azt tudom elképzelni, hogy a teszteléshez valamilyen módon az éles rendszer adatbázisát lehetne használni.

**Comment by Rossi73** [comment]
Mit szólnál (és szólna a NAV) ahhoz a lehetőséghez, ha vevőként is az eladó adószámát és adatait adnád meg? Akkor tuti le tudod kérdezni, igaz, lesz egy csomó WARN...

**Comment by kabelnet2** [comment]
Ez biztos sokaknak jó lehet, de nem mindenkinek. A saját számláinkat ismerjük, de az koránt sem fedi le az összes lehetőséget, amire pedig a beszállítók esetén fel kell készülni.
Mondok egy példát: nálunk nincs sztorno számla. Mivel áruforgalmi rendszer vagyunk, ha valamit elrontunk (pl. nem jó áron számlázunk), akkor visszavesszük készletre és újra kiírjuk jó áron. Így lesznek jók az áruforgalmi statisztikák is. Persze mondhatod, ha a módosítót jól kezeljük a sztornóval sem lehet nagy gond. Ami igaz. De programozol, tehát tudod, ami nincs kipróbálva, abban lehet hiba. (Persze abban is, ami ki van próbálva, csak kevesebb :)

**Comment by NTCA-developer** [comment]
Sziasztok!

Az teljesen kizárt, hogy síkok között átjárás legyen más DB-k felé, úgyhogy ebben nem tudunk segíteni.

Egy megoldásnak tök jó az, amit Rossi javasol, ergo első körös tesztnek simán megadhatod ugyan azt az adószámot kiállítói és vevői pozíciób, ezt nem tiltja semmi.  (max 1 WARN a teszten) 

Amikor már biztosabbnak érzitek a funkciót egy valid üzleti teszthez, akkor fejlesztőként összeállhattok párba, és adhattok teszt adatokat egymásnak. Más lehetőséget én sem nagyon látok.

@kabelnet2 

Majd kérlek zárd le, ha nem kell már a ticket.
