### ISSUE TITLE
Bocsánat de miért angol?

### ISSUE THREAD

**Issue by eztEgyed** [nav-gov-hu/Online-Invoice#302]
Előre szeretnék elnézést kérni a kérdésért, de nagyon zavar.
Értem a hogy számítástechnika nyelve az angol,
De egy csak Magyarországon használt szoftver miért teljesen angol nyelvű?
Az XML séma még csak OK, úgy ahogy, de hibaüzenetek miért vannak angol nyelven?

**Comment by connorhu** [comment]
Mert a számítástchnika nyelve az angol.
Külföldön fejlesztett szoftver is használhatja és itt is volt már angol nyelvű kérdésfeltevés.
(magam részéről viszketegséget kapok a nem angol megnevezésektől egy szoftverben)

**Comment by NTCA-supporter** [comment]
Szia @eztEgyed !
Mit értesz az alatt, hogy teljesen angol nyelvű? Milyen hibaüzenetnél tapasztalsz ilyet?
Üdv

**Comment by eztEgyed** [comment]
ABORT estén pl:
> <technicalValidationMessages>
> <validationResultCode>ERROR</validationResultCode>
> <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
> <message>XML contains on line: [32] and column: [41] error: [cvc-pattern-valid: Value '' is not facet-valid with respect to pattern '.{1,255}' for type '
> </technicalValidationMessages>

**Comment by NTCA-supporter** [comment]
Szia!

Az összes üzleti hibánk lokalizáltan kerül visszaadásra. Az, hogy nem sémavalid az XML, és abban mi a hiba, ezeket nem fogjuk lokalizálni egyesével, remélem ezt megérted. Ha megnézed a többi ERROR vagy WARN szintű hibaüzenetet, olvashatóan és lokalizáltan kapod vissza, ami szerintem elegendő az értelmezéshez.

Üdv

**Comment by eztEgyed** [comment]
OK
