### ISSUE TITLE
[Q&A]3.0 interfész (2021.01.01. hatályba lépő változások)

### ISSUE THREAD

**Issue by tkelemen73** [nav-gov-hu/Online-Invoice#304]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Sziasztok,
a 2020-as fejlesztési roadmap-ban még azt írtátok, hogy "2020.07.01-től a teszt rendszeren dokumentációval együtt elérhetővé tesszük a 3.0-ás XML API-t". Ebben van változás, és nem 2021.01.01-el lesz bevezetve az új verzió? Kérem oldjátok fel a problémát. Köszönöm!
Üdv
T.

**Comment by Macskafarka** [comment]
Érdekel engem is a válasz.

**Comment by lakatoskevin** [comment]
Én kimondottan örülnék annak, ha már a 3.0-t fejleszthetném.

**Comment by nterhes** [comment]
Nekem is ugyanaz lenne a kérdésem, hogy mikor lesz elérhetö a 3.0-ás XML specifikáció?

**Comment by NTCA-tax** [comment]
Az adóhivatali oldalon folyik a számlaadat-szolgáltatás 3.0 XSD fejlesztése. Az XSD séma, specifikáció publikációjának előre látható időpontja 2020. szeptember hónap. Az áfa törvény számlaadat-szolgáltatást érintő változása 2021. január 1-jén lép hatályba. A fejlesztéseket ennek megfelelően érdemes tervezni.

**Comment by topybear** [comment]
Köszönjük az infót! Ez azért elég nagy szívás lesz, különös tekintettel arra, hogy ha ennyit csúszik a 3.0, akkor azért gyanús, hogy nagyobb változások is lesznek benne.
Az ügyfeleink nagy része év végén freeze-el, azaz változtatási tilalom van az informatikai rendszereken, ami miatt legkésőbb szeptember végére meg szokták kapni bétára a rendszereket, hogy legyen idejük tesztelni, nekünk javítani aztán élesbe állni a freeze idejéig. Na most ha ez a szeptember hónap - az eddigi tapasztalatok alapján - a szeptember végét jelenti és mondjuk nem csak annyi lesz a változtatás, hogy jelölhetjük a magánszemélyt és nem kell róla adatot szolgáltatni, akkor - hiába kezeli már a mostani verziónk is az **ismert(!)** január elsejétől esedékes változásokat -, elég nagy gáz lesz. :(

**Comment by nterhes** [comment]
Köszönöm én is az információt! Lenne egy olyan javaslatunk, hogy a 3.0-ban a saját adószámra mások által beküldött számlariportokra legyen egy olyan opció kifejlesztve, amely vagy automatikusan továbbít minden olyan számlariportot online módon, amely beérkezik a cég ügyfeleitöl, vagy megjelöli azokat a riportokat, amelyeket már letöltöttünk a NAV-os platformról, mivel a 2.0-ban erre nincs utánkövetési lehetöség. Pl: Ha valamelyik cég technikai hiba folytán pár nappal késöbb tölti fel a számla riportokat, mint a kiállítási idöpont, és a megoldásunk minden nap letölti az elözi napi riportokat, ezek a késve feltöltött számlaadatok hiányozni fognak.

**Comment by kzolti** [comment]
Lesz lehetőség véleményezni a 3.0 xsd-t?

**Comment by szalaierika** [comment]
> Az adóhivatali oldalon folyik a számlaadat-szolgáltatás 3.0 XSD fejlesztése. Az XSD séma, specifikáció publikációjának előre látható időpontja 2020. szeptember hónap. Az áfa törvény számlaadat-szolgáltatást érintő változása 2021. január 1-jén lép hatályba. A fejlesztéseket ennek megfelelően érdemes tervezni.

Sziasztok,

köszi szépen a választ. 

Nagyon aggályosnak látom, hogy 3 hónap lesz a hatályba lépés és a specifikáció kiadása között az alábbiak miatt:

- Nagy nemzetközi szoftvercég esetében a fejlesztés több külföldi fejlesztői csapat bevonásával történik, mivel 5 különböző számlázó funkcionalitást kell lefedni.
 - A standard megoldást az ügyfeleknek még illeszteniük kell a saját számlázási gyakorlatukhoz, így a kiszállítás után 1.5-2 hónapra szükségük van az implementáláshoz, teszteléshez, élés üzembe helyezéshez.
- A cloud-os ERP-rendszer 2021.január 1-i változáshoz a novemberi release-ben kell, hogy kiszállításra kerüljenek az XSD 3.0-s változások, aminek a zárása éppen a napokban történik, így a szeptemberi publikálás jóval a határidő után van.
 - Kb. 1000 magyarországi nagy nemzetközi cég (leginkább német tulajdonú autóipari cégek és beszállítóik) érintettek ezzel a problémával.

Az eddigi gyakorlat szerinti 6 hónapos fejlesztési periódusra mindenképpen szükség lenne, különben kétséges, hogy ez a kb. 1000 nagy adózó 2021. január 1-től meg tud-e majd felelni az új követelményeknek.

**Comment by Rossi73** [comment]
> Az adóhivatali oldalon folyik a számlaadat-szolgáltatás 3.0 XSD fejlesztése. Az XSD séma, specifikáció publikációjának előre látható időpontja 2020. szeptember hónap. Az áfa törvény számlaadat-szolgáltatást érintő változása 2021. január 1-jén lép hatályba. A fejlesztéseket ennek megfelelően érdemes tervezni.

Tekintettel arra, hogy a NAV részéről nem hangzott korábban arra vonatkozóan semmilyen jelzés, hogy a koronavírus-járvány miatt később várható a korábban 2020.07.01-re ütemezett XSD 3.0 bevezetésének elhalasztása, joggal feltételeztük, hogy a NAV a tervezett ütemben halad, legalábbis abból a szempontból, hogy 2020.07.01-re már biztosan tudja, hogy milyen változásokat szeretne 2021.01.01-től megvalósítani.

**Szeretnénk kérni ezért egy összefoglalót, ami tartalmazza, hogy az XSD 3.0-ban milyen módosítások, fejlesztések várhatók, különös tekintettel azokra a részekre, amiket kötelező lesz megvalósítani.**

Sokan írták - és teljes joggal -, hogy óriási multicégek rendszereibe kell beépíteni adott esetben egy "kicsike" részt, a számlázó modult, és ezért kellő időre van szükségük, és a telepítés sem 3 nap, amire eljut minden partnerhez.

Én a másik oldalról közelítem meg: sok olyan egyéni/mikro/kis/középvállalkozó is van, akinek van online/offline számlázó programja, akár több is, ehhez 1-2-3 programozója, 1-10-100-1000 ügyfele, és ő is ugyanezzel szembesül. Sőt, még az is elképzelhető, hogy a vállalkozói profiljában nem kizárólag a számlázó program szerepel, hanem az élet más területein is jelen van. És ott is kell folyamatosan fejleszteni.

Ezért nem mindegy tehát, hogy mikor, mit kell módosítani, és mennyire gyakran van rá szükség.

Elindult az 1.0. Aztán pár hónappal később jött az 1.1, majd a 2.0 (amire kaptunk előbb 6, majd +3 hónap fejlesztést - kösz' COVID-19), és mire elkészültünk, már kezdhetjük is a felkészülést a 3.0-ra, ráadásul most csak 2-3 hónappal számolhatunk. A NAV fejében meg már lehet, hogy kész a 3.5 vagy a 4.0 is, ami megint brékingcséndzs, mondjuk 2021.07.01-től...

**Comment by tkelemen73** [comment]
Nekem az jött le a kapott válasz alapján, illetve az eddigi morzsákból, hogy a 3.0 olyan változtatásokat fog tartalmazni, amihez törvény módosítás szükséges. Így kijön majd a specifikáció szeptemberben, amihez majd január 1-el lép életbe a törvényi háttér, de a 3.0 éles indulására majd csak április 1-el fog sok kerülni, mivel továbbra is tartják a 6 hónapos felkészülési időt.
Feltételezem, hogy ennél a verziónál is lesz egy EU-s notifikációs eljárás, és annak is le kell futnia az éles indulásig, így szerintem semmiképp nem szabadba belemagyarázni a január 1-i indulást...

**Comment by Macskafarka** [comment]
@tkelemen73 Az ÁFA tv. 2021.01.01-től hatályba lépő szövege már ki van hirdetve, arra nem kell várni. A 10.sz. mellékletében benne vannak azok a változások, amelyek megteremtik az alapot a 2020.01.01-től életbe lépő adatszolgáltatási változásokra. 
[http://njt.hu/cgi_bin/njt_doc.cgi?docid=111467.357209](url)
Szerintem tehát a törvényi háttér már rendelkezésre áll. Ehhez jön 2020 szeptemberében közzétett 3.0 XSD, ami vagy életbe lép januártól, vagy nem.
Ugyanis a struktúra változáshoz nem kell törvény, azt a NAV bármikor megteheti, ez az ő szuverén döntése. Sehol nem találtam arra jogszabályi előírást, hogy hány hónappal, nappal kellene közzétennie egy struktúra változást.
**Tud valaki olyan jogszabályt, lehetőleg törvényi passzust, amely biztosít bármennyi időt adózói oldalon a szoftver kifejlesztésre?**
A kérdés nem ígéretekre, vagy szokásra, vagy józan észre irányul, hanem kifejezetten jogszabályra.
Szerintem kb annyi van jogilag, hogy a NAV által közzétett struktúrában kell adatot szolgáltatni. Távol vagyunk már attól az állapottól, hogy jogszabályban tegyenek közzé konkrét adatstruktúrát, legutóbb a 23/2014. NGM rendeletben volt.
A lovak közé van dobva a gyeplő, az adóalany és a szoftverfejlesztő küzdjön meg egymással azon, hogy mikorra mit kell kifejleszteni, és az mennyi munkába kerül, és mihez képest minősül jónak. Arra adnak WARN-t, amire akarnak. A PM-NAV közös közleményben a befogadói oldalon a végszámla elvárt két soros adatszolgáltatására a mai napig sárga figyelmeztetést ad a 2065M nyomtatvány ver. 3.0,  Aki eleget tesz a PM-NAV közös közleménybeli elvárásnak az magyarázhatja az ügyfeleinek azt. hogy ezt a figyelmeztetést hagyja kívül.  Nem fogja mindenki elhinni, mert be van építve a rendszerbe az, hogy gyengítsék az adóalany és a szoftverfejlesztő közötti viszonyt.
Ma jogilag az a helyzet, hogy akármikor, akár naponta megváltoztathatja a NAV a struktúrát, ugyanúgy, ahogy az ÁNYK nyomtatványt is megváltoztathatja akár a bevallás napján is.

**Comment by Macskafarka** [comment]
Az a helyzet, hogy a 3.0 XSD-t vagy közzéteszik szeptemberben, vagy nem. Vagy életbe lép januártól, vagy nem. Vagy ki lehet próbálni egy teszt környezetben, vagy nem. Nincs semmi sem előírva jogszabályban. Minden eshetőleges. 
Így tervezz szabadságot, fejlesztést, és tesztelést, és átadási határidőt az ügyfelek felé.

**Comment by lukacsb** [comment]
Itt a szeptember. Mikorra várhatjuk a 3.0 XSD specifikációt?

**Comment by tkelemen73** [comment]
Szerintem az szeptember vége lesz.
Az is fontos lenne, hogy ha kaphatnánk az éles indulásra egy várható dátumot, ahogy még július végén sok kérdés megfogalmazódott ezzel kapcsolatban. A sokat hangoztatott 6 hónap felkészülési idő most is biztosított lesz? 
Mivel még semmi érdemi információ nincs az esetleges 3.0 interfésszel kapcsolatban, fontos lenne mielőbb megkapni a specifikációt, tesztrendszert az új verzióval, illetve a vég dátumot, hogy tervezhetőek legyenek a fejlesztési munkálataink, és az ügyfele fele való kiszállítások is.

**Comment by RvPSc** [comment]
Államtitkár "úr" szerint ma fogják kiadni, szóval várjuk szeretettel. Hogy változás sok lesz-e benne? Gondolom ocsmányul sok, hiszen a kijelentése alapján az Online számla adatszolgáltatás januártól az elektronikus számlázást is ki fogja váltani (ehhez szerintem mind jogilag, mind adattartam ügyileg változtatások kellenek): "_Nemcsak az áfabevallások adóhivatali előkészítését biztosítja az új Online Számla rendszer, hanem még - a koronavírus-járvány idején a magas fertőzési kockázatot jelentő - papírszámlákat is kiválthatja - szögezte le._"

**Comment by NTCA-developer** [comment]
Sziasztok!

A 3.0-ás XML API-hoz a sémák, a changelog, az API sample fájlok és a WADL mastert branchen elérhetők. A 3.0-ás changelogba igyekeztünk egy step-by-step átállási útmutatót is tenni, hogy legyen egy sorvezető a változások lekövetéséhez. Biztosan nem tudtunk mindenre gondolni szóval nyugodtan észrevételezzétek, annak csak örülünk ha a közösség is hozzá teszi a saját gondolatait vagy javít hibákat benne adott esetben.

A határidőkről (interfész dokumentáció, teszt és éles üzem mikor lesz) is találtok a changelogban információt. A határidőkhöz kapcsolódóan plusz információt itt találtok: https://www.kormany.hu/hu/nemzetgazdasagi-miniszterium/adougyekert-felelos-allamtitkarsag/hirek/a-gazdasagfeherites-legujabb-korszaka-veszi-kezdetet-jovore

A ticketet lezárom, ha kérdésetek van vagy elakadtok akkor írjatok bátran, segítünk! Jó munkát mindenkinek!

**Comment by omachtandras** [comment]
Még csak belepillantottam, de nagyon-nagyon örülök, hogy ez megvalósult:

2.7) Uppercase konverzió megszüntetése

A 3.0-ás adatszolgáltatások feldolgozása során minden korábbi nagybetűsítés megszűnik a rendszerben. Minden string típus úgy kerül mentésre ahogy az az adatszolgáltatásban beérkezett.

Maximális respect érte, hogy változtattatok a korábbi merev álláspont ellenére!

**Comment by NTCA-developer** [comment]
@omachtandras 

Köszönjük, de azért ne örülj előre mert ez csak a számla mentés és ha végig gondolod akkor muszáj is hogy így legyen, hiszen az elektronikus számláknak nem jönne ki a hash lenyomata ha konvertálgatnánk a stringeket. Mi meg storageban kifizetjük az uppercase indexek árát.

**Comment by zsom** [comment]
Üdv @NTCA-developer !

A dokumentációk:
https://onlineszamla.nav.gov.hu/dokumentaciok
https://onlineszamla.nav.gov.hu/informatikai_valtozasok

Várhatóan mikor fognak frissülni?
A teszt rendszeren már él? Lehet küldeni 3.0-ás üzeneteket?

**Comment by NTCA-developer** [comment]
Szia @zsom 

Épp most csinálom a publikálást az Online számla felületen. Kis türelmet. :) Egyébként most még ugyan az fog csak felmenni mint amit ide is feltettem. A fejlesztési időpontokról a changelogban találsz információt.

**Comment by zsom** [comment]
Szia @NTCA-developer !

Köszi!
Ebben, vagy egy másikban tudnátok egy kommentben jelezni, ha kikerülnek dolgok?
(csak hogy ne kelljen naponta nézni a weboldalt)

**Comment by omachtandras** [comment]
> Köszönjük, de azért ne örülj előre mert ez csak a számla mentés és ha végig gondolod akkor muszáj is hogy így legyen, hiszen az elektronikus számláknak nem jönne ki a hash lenyomata ha konvertálgatnánk a stringeket. Mi meg storageban kifizetjük az uppercase indexek árát. De az adózó lekérdező még egy ideig marad nagybetűs.

Mi is ki fogjuk / kifizetjük az árát, de nagyon fontos az is, hogy a felhasználó hogy vélekedik egy rendszerről, az általa szolgáltatott adatokról. Márpedig az Online Számla a ráépíthető automatizmusok révén egyre inkább be fogja tölteni azt a szerepet, hogy adatszolgáltatóvá válik (közvetett módon).

Már az eddigi tapasztalatok alapján is azt mondom, hogy ez egy nagy előrelépés a felhasználók komoly zavaró tényezőként hozzák fel a nagybetűsítést, sokan elégedettek lesznek ez a változás miatt, én azt gondolom.

**Comment by NTCA-developer** [comment]
Szia @zsom 

Készen vagyok az élessel, a teszt még folyamatban.

@omachtandras 

Köszi, mi is maximálisan egyetértünk azzal hogy a user experience a fő mozgatórugója egy fejlesztésnek, olyat kell építeni amit örömmel használnak. Igyekszünk ennek megfelelni, köszönjük az elismerő szavakat.
