### ISSUE TITLE
Vevő oldali csoportos adószám estén a rendszer nem dob warning-ot ha az eladó a vevő sima adószámára állít ki számlát.

### ISSUE THREAD

**Issue by eztEgyed** [nav-gov-hu/Online-Invoice#306]
Vevő oldali csoportos adószám estén a rendszer nem dob warning-ot ha az eladó a vevő sima adószámára állít ki számlát.
(Nyilván a kiállítók önbevallása alapján)

Miután így a vevőnél nem jelenik meg a számla és az eladó sem tud a hibáról, így csak a postai beérkezést és feldolgozást követően  lehet reklamálni, de addigra meg átlépjük a 8 napos határidőt.

Javaslat: vagy fogadja el a rendszer a sima adószámot és automatikusan javítsa (Minden info rendelkezésre áll a feldolgozói oldalon) vagy dobjon warningot.

**Comment by NTCA-supporter** [comment]
Szia @eztEgyed !
"automatikusan javítsa": na ilyet biztosan nem fogunk soha csinálni :)
A WARN felvetésről pedig majd @NTCA-tax elmondja az álláspontját.
Köszi

**Comment by NTCA-tax** [comment]
Köszönjük a javaslatot, ez mindenképp hasznos funkciója lenne a rendszernek. A megoldásról egyeztetni fogunk NAV-on belül, így az automatikus javítással szemben ez nem olyan, amit biztos nem fogunk megcsinálni :)
