### ISSUE TITLE
[Q&A] requestId egyedisége különböző végpontokról

### ISSUE THREAD

**Issue by Amn3s1a2018** [nav-gov-hu/Online-Invoice#307]
**A kérés azonosítóknak adózónként egyedinek kell lenni. Nem lenne elég felhasználónként?**

Olyan működés esetén ha partnerünk több telephelyről számláz azonos adószámmal, a számlaszámok egyediségét nyilván meg kell oldani. Hasonló módon kell gondoskodni erről a requestId esetén is, vagy az is megfelel ha két technikai felhasználót regisztrálunk a két munkaállomásnak?

**Comment by NTCA-supporter** [comment]
Szia @Amn3s1a2018 !
Az requestId egyediség adózónként értendő, tehát a requestId-nál is gondoskodni kell erről.
Üdv

**Comment by Amn3s1a2018** [comment]
Szia, köszönöm, közben kipróbáltuk és ugyanerre jutottunk. Vannak félelmeim, mivel most teljesen különböző szoftverek is kapcsolódhatnak azonos adószám nevében. Ha valamilyen okból mégis ütközés van, az milyen problémát okozhat? Ha az interfész visszadobja a kérést, hogy már felhasznált requestId amivel próbálkoztunk, újra tudjuk küldeni... Csak vannak féleleim na :)

**Comment by NTCA-supporter** [comment]
Szia @Amn3s1a2018 !
Ilyenkor REQUEST_ID_NOT_UNIQUE ERROR-t fogsz kapni, tehát sikertelen a beküldés.
Ha pl. random generálod az ID-t akkor feltehetőleg a következő beküldésnél már jó lesz.
Jobb félni, mint megijedni :)

Üdv

**Comment by connorhu** [comment]
Adott telepítés prefixsze és timestamp microtime-mal egészen egyedivé válik. Mi legalább is így csináljuk.

**Comment by Amn3s1a2018** [comment]
Köszi, ha ez így definiálva van, nekem megfelel, ezzel együtt le is csukom.
Olyasmire gondoltam, hogy két független kliens egyszerre ugyanazzal az Idvel küld vmi, a két végpont még nem tud róla, és utána belül lesz vmi fura konfliktus.
