### ISSUE TITLE
Könyvelői szempontból hiányos adatok

### ISSUE THREAD

**Issue by bartanorbi** [nav-gov-hu/Online-Invoice#308]
Sziasztok,
könyvelői szempontból az alábbi problémákkal szembesültem:
hiányos adatok:
- a számla fizetés módja és fizetés határideje nem kötelező adat (naplók, analitika stb probléma)
- felvásárlási jegy hiány
- pénztárgéppel kiállított számlák hiánya (ezeket valahogy be kellene dolgozni az online számlába)
- szürkeszámlák problémája (nem a cég által szerzett, de a cég nevére szóló számlák)
- lekérdezés max 100 számla (ez vicc, ha egy napra szűröm, és meghaladja a 100 db-ot akkor a többit honnan)
- kimenő számlák esetén csak adószámos (számlázóprogram nem küldi a magánszemélyeknek kiállított számlákat, adatvédelmi okokkal indokolják, de január 1-től elméletileg kelleni fog.
- vételi jegyek (ez is egy érdekes probléma)
Egyelőre ennyi, 
Nagyon köszi, és hajrá,, nagyon bízom a rendszerben, hogy egyszer jó és használható lesz.

**Az igény összefoglalása / Summary of the request**
Rövid és tömör leírása a problémának, amiből az igény származik. / A clear and concise description of what the problem is, from which the request arises.

**Az általam javasolt megoldás / The solution I propose**
Rövid és tömör leírása a javasolt megoldásnak. / A clear and concise description of the proposed solution.

**Elfogadható alternatívák / Acceptable alternatives**
Rövid és tömör leírása az elfogadható alternatíváknak, ha az igény nem valósítható meg az eredeti formájában. / A clear and concise description of the acceptable alternative solutions, in case the request is not doable in it's original scope.

**Egyéb tartalom / Additional content**
Szabad szöveges rész. / Own remarks.

**Comment by Amn3s1a2018** [comment]
Szia,

Néhányra ezekből már tudható:

> * a számla fizetés módja és fizetés határideje nem kötelező adat (naplók, analitika stb probléma)

Jogszabály nem kötelez az adatszolgáltatásra, de megállapodhatsz a szállítóddal, akár szerződésben is kikötheted, hogy elvárod ezen adatok szolgáltatását. Kérdés persze, hogy tényleg ér-e annyit.

> * pénztárgéppel kiállított számlák hiánya (ezeket valahogy be kellene dolgozni az online számlába)

Erre már a szándék megvan, az  `QueryInvoiceDigestResponse.invoiceDigestResult.invoiceDigest.source˙ alapján legalábbis. Konkrét adatot még láttam, de pl. a `NAV online számlázó`ban készült számlák és a számlatömbös számlák kézi adatszolgáltatása már lekérdezhető ...

> * szürkeszámlák problémája (nem a cég által szerzett, de a cég nevére szóló számlák)

Mi ezeket csak „metro” számláknak hívjuk ... Ez eddig is létezett, csak nem tudtunk róla, ehez képest már előrébb vagyunk. Lekönyvelni szerintem ezután sem kell, hiszen a cégnek nincs birtokában a számla. Jó hír, hogy kifizetni se :)

> * lekérdezés max 100 számla (ez vicc, ha egy napra szűröm, és meghaladja a 100 db-ot akkor a többit honnan)

Ha a QueryInvoiceDigestRequest-ről beszélünk, akkor a 100dbos limit az egy „oldal”-ra vonatkozik és lehet lapozni ... 

> * kimenő számlák esetén csak adószámos (számlázóprogram nem küldi a magánszemélyeknek kiállított számlákat, adatvédelmi okokkal indokolják, de január 1-től elméletileg kelleni fog.

Nem értem itt mi a kérdés, de a 3.0-ban talán lesz válasz. (42) :) 

> * vételi jegyek (ez is egy érdekes probléma)
> * felvásárlási jegy hiány

Nem várhatjuk mindenre ez a rendelet szállítsa a megoldást, erre szerintem nem lesz más válasz, csak az hogy a felvásárlási jegy nem számla ...

**Comment by omachtandras** [comment]
"

        pénztárgéppel kiállított számlák hiánya (ezeket valahogy be kellene dolgozni az online számlába)

Erre már a szándék megvan, az QueryInvoiceDigestResponse.invoiceDigestResult.invoiceDigest.source˙ alapján legalábbis. Konkrét adatot még láttam, de pl. a NAV online számlázó`ban készült számlák és a számlatömbös számlák kézi adatszolgáltatása már lekérdezhető ..."

Még a Covid előtt promózták egy NAVos megbeszélésen, hogy július 1-től egy, az Online számlától teljesen független interface-en lekérdezhetőek lesznek minden vállalkozás számára a saját pénztárgépek beküldött adatai.
Szóval a szándék megvan NAV részről, gondolom ők is csúsznak néhány fejlesztéssel a bejött plusz munkák miatt.

**Comment by NTCA-supporter** [comment]
Szia @bartanorbi !
Technikai oldalról első körben én is ehhez tudnék hozzászólni:
"lekérdezés max 100 számla" ahogy előttem is írták, van a funkcióban lapozás, természetesen nem csak 100 számla kérdezhető le a megadott keresési feltételekkel.
A többi részéhez @NTCA-tax fűzhet hozzá megjegyzést, de az előttem szólóknak egész jó a meglátása :)

Köszi!

**Comment by NTCA-tax** [comment]
Köszönjük @bartanorbi felvetéseit, NAV oldalról is vizsgáljuk azokat az elemeket, melyekkel lehetne OPCIONÁLISAN bővíteni az adatszolgáltatást. Azért opcionálisan, mivel az áfa törvény alapvetően köti meg a kötelezettséget. Amennyiben egy-egy elem számlán történő feltüntetését nem az áfa törvény írja elő (vagy akár nincs semmilyen jogszabály, ami előírná), akkor azt nem lehet kötelező elemnek tekinteni.

A fenti okok miatt nem kötelező mező a fizetés módja és határideje. A felvásárlási jegy és vételi jegy nem számla, nem is követi a számla adatstruktúráját.

A pénztárgépes számlák egy valid felvetés, ezen még dolgozunk. Önálló lekérdezést is fogunk kialakítani, melynek a dokumentációját a GitHub-on publikáltuk: https://github.com/nav-gov-hu/Online-Cash-Register-Logfile

Szürkeszámlák, Metro számlák stb. megnevezésű bizonylatok egy ingoványos talaj. Amennyiben ténylegesen magánfogyasztáshoz kapcsolódik, akkor az még nem akkora kockázat. Ugyanakkor előfordulnak olyan esetek, hogy azért nem helyez levonásba egy-egy beszerzést az adózó, mert az ehhez kapcsolódó értékesítéséről nem állít ki bizonylatot. Ugyanakkor transzparensen látja adózó (már ha akarja), hogy mik ezek a számlák és talán jogkövető döntést tud hozni. Rendszer oldaláról nem nagyon tudom, mit lehetne kezdeni, mivel ezt nem adatszolgáltatási problémának érzem.

A vevő oldalán az adószám feltüntetésének kötelezettségét jogszabály írja elő belföldi adóalany vevő esetén. Itt nem tudom mi a kérdésed. A séma mindig az aktuális jogszabályi kötelezettséget képezi le, és ahogy @Amn3s1a2018 írta, a 3.0-ban jönnek a magánszemélyek és a külföldi vállalkozások.
