### ISSUE TITLE
supplierInfo bővítés

### ISSUE THREAD

**Issue by topybear** [nav-gov-hu/Online-Invoice#309]
Az ÁFA törvényben meghatározott kötelező elemeken kívül vannak még egyéb jogszabályok is a számla kötelező adattartalmát illetően, pl,:
"Az egyéni vállalkozó a 2009. évi CXV. tv. 16. § (4) bekezdése szerint gazdasági tevékenysége során az “egyéni vállalkozó” megjelölést (vagy annak „e.v.” rövidítését) és **nyilvántartási számát** neve (aláírása) mellett minden esetben köteles feltüntetni."
Lehetne esetleg a nyilvántartási számnak egy saját tag-et csinálni, hogy ne a névhez kelljen "bevarrni"?

**Comment by NTCA-tax** [comment]
Az egyéni vállalkozó nyilvántartási számának számlán való feltüntetése nem áfa törvényen alapuló kötelezettség, ezért nincs benne a sémában. AdditionalData-val bele lehet tenni most is a sémában.

Csak érdeklődnék, hogy számlakibocsátói vagy befogadói oldalon a nyilvántartási számnak milyen szerepét látod? Miért lenne érdemes szerinted egy külön mezőt definiálni neki?

**Comment by connorhu** [comment]
Viszont az AdditionalData-ban történő "standardizálásáról" lehetne elmélkedni.
(lásd: "2020/2 Egyezményes adatmodell kialakítása opcionális adatokra (2020.01.22)" bejegyzés a fejlesztői naplóban)

**Comment by NTCA-tax** [comment]
Standardizálni csak azt érdemes, amit valamilyen célra az eladó, a vevő vagy az adóhivatal rendszere gépileg felhasznál. Ezért érdeklődtem a gyakorlati hasznán. Amennyiben csak rajta van a számlán, de nem kezdünk vele semmit, akkor nem érdemes standardizálni, amennyiben ténylegesen van valami szerepe, akkor érdemes nekifutni. Szóval röviden a felhasználási célt nem látom, de ez nem zárja ki, hogy van ilyen.

**Comment by Macskafarka** [comment]
Az egyéni vállalkozó nyilvántartási számának nincs semmi célja, nem használja semmire sem a kibocsátó, sem a befogadó, sem az adóhatóság. Ezért én szivatásnak érzem a törvényi előírást.

**Comment by NTCA-tax** [comment]
Én arra jutottam, hogy amit nincs értelme megcsinálni, jól megcsinálni duplán értelmetlen... Ezt az issue-t lezárom, ha valaki látja ennek hasznát, akkor egy új issue-n beszéljük meg.
