### ISSUE TITLE
[FEATURE] Keresés számlakibocsátó nevére bejövő számláknál

### ISSUE THREAD

**Issue by Rossi73** [nav-gov-hu/Online-Invoice#31]
**Az igény összefoglalása / Summary of the request**
A bejövő számlák lekérdezésekor legyen lehetőség a lekérdezésre a számlakibocsátó nevének részlete alapján.

**Az általam javasolt megoldás / The solution I propose**
Az AdditionalQueryParamsType típus kiegészítése egy "supplierName" (vagy hasonló) mezővel. A rendszer a válasz üzenetben adja vissza az összes olyan számlát, ahol a számlakibocsátó neve tartalmazza a megadott értéket (... WHERE nev LIKE "%supplierName%"). A vizsgálatot csak akkor hajtsa végre, ha legalább [n] karaktert megadtunk a mezőben. [n] értékét úgy kellene meghatározni, hogy a rövid nevű cégek esetén is adjon vissza találatot (pl. n>=5).

**Elfogadható alternatívák / Acceptable alternatives**
Ha a rendszert túlságosan leterhelné a részleges névegyezőség vizsgálata és ez alapján az eredményhalmaz visszaadása, akkor elfogadható lenne az is, ha csak a név elejét vizsgálná az egyezés szempontjából (... WHERE nev LIKE "supplierName%").

**Egyéb tartalom / Additional content**
Jelenleg csak adószám alapján lehet beazonosítani az egy konkrét partner által kibocsátott számlákat. Ez abban az esetben jó megoldás, ha ismerjük a partner adószámát. Ha a partner már partnerünk (a rendszerünkben tároltuk az adószámát), akkor ez a lehetőség működik. Ha viszont még nem partnerünk, akkor először meg kellene keresni valamilyen rendszerben az ő adószámát, majd erre rákeresni.

Ha valaki olyan rendszert fejleszt, ahol nem kívánja tárolni a bejövő számlákat (mert a NAV-nál úgyis megvan), akkor bármilyen bejövő számla kereséses esetén először meg kell keresnie valahol a számlakibocsátó adószámát, majd erre tud rákeresni. A konkrét partnerre történő keresés ilyen esetben tehát nagyon sokáig tart.

A fenti működést mindenképpen javasolt megvalósítani az online számlázó felületen is, hiszen ott sincs lehetőség a számlakibocsátó nevére keresni, csak az eladó adószámára lehet.

A NAV részéről érthető, hogy az adószámot veszi alapul (az a "kulcs" mező), de a felhasználók szempontjából mindenképpen előnyös és hasznos funkció lenne, ha az adószám mellett a névre történő keresés lehetősége is meglenne. Főleg akkor, amikor a jövőben már minden számláról történik majd kötelező jelleggel adatszolgáltatás, ÁFA értéktől függetlenül. De mivel már most is vannak cégek, amelyek ezt választják, a funkciót érdemes lenne a 2.0 indulására beépíteni.

**Comment by NTCA-developer** [comment]
Szia @Rossi73 

Köszönjük a javaslatot. Külön köszönöm, hogy leírtad, mire használnád a lekérdezést, így rögtön egyértelmű, miért keletkezett az igény. A teljes like veszélyes terep, de kísérleti jelleggel megnézhetjük az alternatív javaslatot, tehát csak szóeleji egyezés kereséssel, legalább 5 karakterrel. Azt viszont kihangsúlyoznám a félreértések elkerülése végett, hogy csak a kötelező keresőparaméterek mellett működhet ez a fajta keresés.

Ez elfogadható számodra?

**Comment by Rossi73** [comment]
Igen, elfogadható.
