### ISSUE TITLE
[DEV support] sztornó számla INVALID_REQUEST_SIGNATURE

### ISSUE THREAD

**Issue by imanzuk** [nav-gov-hu/Online-Invoice#310]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[x] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[x] 2.0

**A requestId értéke / requestId value**
```
RQRTV202007091055415477796
RQRTV202007091242662245998
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
CREATE művelet esetén rendben lefut az adatszolgáltatás, a STORNO művelet viszont "érvénytelen kérés aláírás" hibát ad.
A második requestId-val azonosított kérésben lévő számla egy tételt tartalmaz - így elvileg az adatmennyiségből nem adódhat a hibás hash (mint a #187-ben).
A környezet PHP 7.2, és ```hash("sha3-512", $input)```.

Mi az elvárt érték?

*Egyéb tartalom / Additional content*

**Comment by NTCA-supporter** [comment]
Szia!

Amikor a belső, számlához tartozó hast-t számolod, akkor a STORNO string-gel fűzöd össze a számla base64-elt értékét?
Most pontosan nem tudom megmondani, de első tippem ez lenne, ha valóban CREATE esetén jól működik.

Üdv

**Comment by imanzuk** [comment]
Valóban az volt a hiba, hogy nem a STORNO string-gel lett összefűzve.
Köszönöm a gyors reakciót, zárható.
