### ISSUE TITLE
[FEATURE] kerekítés (újra)

### ISSUE THREAD

**Issue by Amn3s1a2018** [nav-gov-hu/Online-Invoice#311]
**Az összesítés ellenőrzés finomítása**
A #217 vége már egy ígéret volt, hogy az onlineszámla oldalról is hangolják az algoritmust, hogy minél kevesebb legyen a vaklárma, amíg élt a 100e Ftos limit nem is kaptunk ilyesmit szinte soha, de az értékhatár eltörlésével megjelentek a 217ben megjósolt eltérések és `WARN`ok

**Türéshatár hangolása segítene**
A pontos algoritmus nyilván (?) nem publikus de a dokumtáció 1%ot említ, és 1 egységet, ami forintos számlán gondolom 1ft és gondolom mindig a megengedőbb változatot veszi figyelembe. Kis értékű számlákon ahol a kerekítés százalékosan már nagyon könnyen elbukik, emelkedhetne az abszolút limit esetleg 2ftra (egységre), vagy legalább másfélre ...

Köszi

**Comment by connorhu** [comment]
(Mennyire egyszerű lenne ha a NAV adna egy képletet, hogy így tessék számolni oszt jónapot)

**Comment by Amn3s1a2018** [comment]
Azért Te is érzed, hogy ez nem lenne _annyira_ egyszerű. Fórumos és egyéb beszélgetéseken többször felmerült ilyen megoldás, de kötelezővé tenni nehéz lenne (és ha mégis sikerülne akkor meg azért szentségelne mindenki – feltehetőleg velem együtt). Ha pedig azt mondanák, amit eddig (mindenki kerekítsen ahogy akar, matematikailag legyen helyes), de közben mégis lenne egy „jótanács” (kacsintás) azis rendesen borzolná a kedélyeket. 

 Másrészt különböző területeken különböző szempontok vannak.
  - van ahol minden egész forint (tételesen is) van ahol nem.
  - van ahol konkrétan 5Ft-ra kerekítenek mindent _tételesen_
  - van ahol pl. EUR számla van, egységesen két tizedes, van ahol tételesen három vagy több kell (pl. nagy mennyiségek kis egységárak miatt)
  - vannak „nemlétező” bruttó összegek, (pl. 31) ami adott áfakulccsal nem jöhet ki, csak több vagy kevesebb, de mégsem lehet más a számla vagy a tétel vége, mert már ez van a szerződésben
  - van ahol nem igazán számít, de van ahol fontos, hogy forintra stimmeljen a tétel összesítés az áfa bontással, könyveléssel
  - van ahol külön feltüntetnek kerekítést, másnak ez elfogadhatatlan

Szóval az ötlet jó, de inkább köszönjük nem.

**Comment by NTCA-tax** [comment]
Szerintem @Amn3s1a2018 nagyon jól összefoglalta a kérdésre a választ, nagyon nem is tudnék mit hozzátenni :)

**Comment by Amn3s1a2018** [comment]
Igazából az lett volna a kérdés/kérés, hogy a kerekítés elbírálása legyen egy kicsit engedékenyebb, elkerülendő a felesleges téves riasztásokat.

**Comment by NTCA-tax** [comment]
Igen, ezt értettem. Dolgozunk rajta...
