### ISSUE TITLE
[Q&A] WARN: Érvénytelen áfakód. Vevő áfakódja nem lehet 4-es.

### ISSUE THREAD

**Issue by imanzuk** [nav-gov-hu/Online-Invoice#312]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Mi a célja ennek a figyelmeztetésnek, ha vannak ilyen élő adószámok?
10467024-4-11
10537914-4-44

**Comment by connorhu** [comment]
Az, hogy a 4-es áfakód esetén az áfacsoport adószámát kell beküldeni.

76. oldal:
"Az adószám helye a customerTaxNumber elem (típusa: TaxNumberType). Amennyiben a vevő
csoportos áfa-alany, akkor – az Áfa törvény szerint – a vevő adószámaként a csoport adószámát kell
megadni, az egyéni adószámát pedig a groupMemberTaxNumber elemben (típusa: TaxNumberType)
kell feltüntetni, amennyiben ez szerepel a számlán. "

Lekérve a 10467024-t:
```
{
    "validity": true,
    "lastUpdate": "1990-12-21T23:00:00+00:00",
    "name": "GYERMELYI ÉLELMISZERIPARI ZÁRTKÖRŰEN MŰKÖDŐ RÉSZVÉNYTÁRSASÁG",
    "taxpayerId": 10467024,
    "vatCode": 4,
    "addresses": [
        {
            "type": "HQ",
            "countryCode": "HU",
            "postalCode": "2821",
            "city": "GYERMELY",
            "streetName": "BAJNAI UT 1.",
            "publicPlaceCategory": "N/A"
        }
    ],
    "vatGroupMembership": 17780096,
    "shortName": null
}
```

Lekérve a 17780096-et:
```
{
    "validity": true,
    "lastUpdate": "2007-12-31T23:00:00+00:00",
    "name": "GYERMELYI ÉLELMISZERIPARI ZÁRTKÖRŰEN MŰKÖDŐ RÉSZVÉNYTÁRSASÁG ÁLTAL KÉPVISELT CSOPORTOS ÁFA",
    "taxpayerId": 17780096,
    "vatCode": 5,
    "addresses": [
        {
            "type": "HQ",
            "countryCode": "HU",
            "postalCode": "2821",
            "city": "GYERMELY",
            "streetName": "BAJNAI UT 1.",
            "publicPlaceCategory": "N/A"
        }
    ],
    "vatGroupMembership": null,
    "shortName": null
}
```

**Comment by imanzuk** [comment]
Jogos, @connorhu köszönöm a gyors választ!
