### ISSUE TITLE
Hogyan tudok beküldeni olyan módosító számlát, aminek az összegében nem történt változás?

### ISSUE THREAD

**Issue by bvica** [nav-gov-hu/Online-Invoice#313]
Van egy számlám pl. egy tétellel, ami helyiségbérleti díj 20.000 Ft.
Saját számlázó rendszerrel elkészítettem, és beküldöm az eredeti számlát.
Ezek után értesít a vevő, hogy megváltozott az adószámla.
Kiállítom a módosító számlát, ahol az összeg nem változott, tehát egy -20.000 és egy +20.000 tétel szerepel rajta, és természetesen már az új adószámmal van kiállítva.
A különbözetről kellene adatot küldenem, de az 0. Ha üresen küldöm be az invoiceLines-t, akkor hibaüzenetet kapok vissza.
Milyen adatokat kell az adatszolgáltatásnak tartalmaznia ahhoz, hogy sikeres legyen?

**Comment by NTCA-supporter** [comment]
Szia @bvica !
Azt pontosan nem értem, hogy miért kell a -20000 és +20000 tétel.
Szerintem be tudod úgy küldeni, hogy nem szerepeltetsz invoiceLine-t, hiszen az nem kötelező módosító számlánál.
Módosító számlánál ilyen esetben az invoiceSummary.t viszont meg kell adni kötelezően, ahol ugye 0 értékek fognak szerepelni.
Pontosan milyen hiabüzenetet kaptál?
Üdv

**Comment by bvica** [comment]
Helló!

Az xml-ben ez szerepel:
19:27:40,358 INFO  [stdout] (EJB default - 3)                 <invoiceDetail>
19:27:40,358 INFO  [stdout] (EJB default - 3)                     <invoiceCategory>NORMAL</invoiceCategory>
19:27:40,358 INFO  [stdout] (EJB default - 3)                     <invoiceDeliveryDate>2020-07-03</invoiceDeliveryDate>
19:27:40,358 INFO  [stdout] (EJB default - 3)                     <currencyCode>HUF</currencyCode>
19:27:40,358 INFO  [stdout] (EJB default - 3)                     <exchangeRate>1.0</exchangeRate>
19:27:40,358 INFO  [stdout] (EJB default - 3)                     <paymentDate>2020-07-03</paymentDate>
19:27:40,359 INFO  [stdout] (EJB default - 3)                     <invoiceAppearance>PAPER</invoiceAppearance>
19:27:40,359 INFO  [stdout] (EJB default - 3)                 </invoiceDetail>
19:27:40,359 INFO  [stdout] (EJB default - 3)             </invoiceHead>
19:27:40,359 INFO  [stdout] (EJB default - 3)             <invoiceLines/>
19:27:40,359 INFO  [stdout] (EJB default - 3)             <invoiceSummary>
19:27:40,359 INFO  [stdout] (EJB default - 3)                 <summaryNormal>
19:27:40,359 INFO  [stdout] (EJB default - 3)                     <summaryByVatRate>
19:27:40,359 INFO  [stdout] (EJB default - 3)                         <vatRate>
19:27:40,359 INFO  [stdout] (EJB default - 3)                             <vatPercentage>0.27</vatPercentage>
19:27:40,359 INFO  [stdout] (EJB default - 3)                         </vatRate>

És ilyen hibaüzenetet kapok:
<processingResults><processingResult><index>1</index><invoiceStatus>ABORTED</invoiceStatus><technicalValidationMessages><validationResultCode>ERROR</validationResultCode><validationErrorCode>SCHEMA_VIOLATION</validationErrorCode><message>XML contains on line: [54] and column: [28] error: [cvc-complex-type.2.4.b: The content of element ''invoiceLines'' is not complete. One of ''{"http://schemas.nav.gov.hu/OSA/2.0/data":line}'' is expected.]</message></technicalValidationMessages><technicalValidationMessages><validationResultCode>ERROR</validationResultCode><validationErrorCode>SCHEMA_VIOLATION</validationErrorCode><message>Xml validation failed</message></technicalValidationMessages>

Elég lenne akkor, ha nem szerepelne az xml-ben az     <invoiceLines/> ?

**Comment by connorhu** [comment]
Szerintem az empty tag sem kell oda, mert ha van akkor már feltételezi, hogy az szabályos.

**Comment by NTCA-supporter** [comment]
Első körben én is azzal próbálkoznék, hogy meg sem képzed az invoiceLines csomópontot.
Próbáld meg kérlek így.
Köszi

**Comment by bvica** [comment]
Működik, köszönöm mégegyszer :)
