### ISSUE TITLE
Teszt rendszer és Éles rendszer adatbázis azonosság igénye

### ISSUE THREAD

**Issue by Zoller79** [nav-gov-hu/Online-Invoice#314]
Tisztelt Fejlesztők! 

Lehetséges-e, hogy a teszt rendszerben használt adóalany adatbázis azonos legyen az éles rendszernél használttal? 
Több esetben előfordult, hogy egy adószám lekérdezés a teszt rendszer esetén érvénytelen adószám infót adott vissza, majd ugyanezt az adószámot az éles rendszerből lekérdezve valid adatokat kaptunk vissza. 

Körülmények: 
Ügyfelünk kiállított egy olyan számlát ahol a partner egyéni vállalkozó volt. 
A rendszer a számla adatokra egy WARN-t adott vissza, hogy a Vevő adószáma nem létezik. 
Mind a NAV oldalán (https://www.nav.gov.hu/nav/adatbazisok/adatbleker/afaalanyok/afaalanyok_egyszeru), mind az Online számla weboldalon a partner helyes adatait adta vissza a rendszer. 
Mivel fiktív számlát nem szeretnék kiállítani, így a teszt rendszerben próbáltam meg a megadott adószámmal egy számlát beküldeni. 
A teszt rendszer már a queryTaxPayer kérésre is érvénytelen adószám választ ad. 

Az ügyfélnél ellenőriztük és ő kizárólag az éles rendszerhez csatlakozik. 
Plusz kérdés, hogy ilyen esetben az ügyfél hogyan járjon számlázás során? 

Válaszukat előre is köszönöm!

**Comment by NTCA-supporter** [comment]
Szia @Zoller79 !
Ez volt már többször is. A teszt rendszeren nincs megvalósítva a folyamatos szinkronizálás.
A tesztrendszernek ez nem célja, hogy az adózói adatok helyességét itt ellenőrizd.
Persze értem az igényt, de ezzel biztosan nem fogunk foglalkozni. 
Kérlek zárd, ha nincs több kérdés.

Üdv
