### ISSUE TITLE
[Q&A] Időszaki számla jelzése kötelező-e az adatszolgáltatásban?

### ISSUE THREAD

**Issue by betasofthu** [nav-gov-hu/Online-Invoice#315]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Időszaki számla jelzése kötelező-e az adatszolgáltatásban?
A 2.0 sémában új tartalomként bekerült a számla üzleti adatai közé a az időszakos elszámolás (periodicalSettlement) jelzése.
A minOccurs=0 miatt nem kötelező és az áfa törvény sem írja elő. Az áfa törvényben az időszak első és utolsó napja azaz az invoiceDeliveryPeriodStart és az invoiceDeliveryPeriodEnd megfelelője sem található meg. 
Jól gondolom, hogy ezt a három adatot nem kötelező lejelenteni a számlázó programok elektronikus adatszolgáltatásában még akkor sem ha a számla időszaki?

**Comment by Amn3s1a2018** [comment]
Ez a folyamatos teljesítésű számla, aminek a szabályozása nemrég (2016?) változott, vagy attól független téma?
A `periodicalSettlement` ahogy le is vezetted, nem igazán lehetne kötelező, de szerintem helyes lenne ha ez megjelenne az API dokumentációban az adatszótár részben (II.2 265. oldal). Ugyanúgy elég lenne az is, a esetleg említené a táblázat, hogy ami nem szerepel itt, az
  - technikailag nem szükséges
  - Áfa tv. szerint nem kötelező
  - (tehát?) az adatszolgáltatásban sem kötelező.
Mivel ilyen kijelentés nincs és pl. a `supplierBankAccountNumber`-t szerepeltetik a táblázatban, a `periodicalSettlement` és a `smallBusinessIndicator` is megjelenhetne itt.

Azt hiszem közvetlenül a kérdéshez tartoznak még az `invoiceDeliveryPeriodStart` és `invoiceDeliveryPeriodEnd` mezők amiket pl. szintén említ ez a táblázat.

**Comment by NTCA-tax** [comment]
Az áfa törvény alapján nem kötelező adattartalom az időszaki számla jelzése. Ugyan így nem kötelező az időszak kezdő és záró dátumának a feltüntetése. Amennyiben a két fél számára fontos, akkor az adatszolgáltatásban meg van a dedikált helye.
