### ISSUE TITLE
[Q&A] Papírtömbben kiállított számla "számlaadat-rögzítése" számlázórendszerrel

### ISSUE THREAD

**Issue by eszel** [nav-gov-hu/Online-Invoice#316]
Sziasztok! 

Segítséget kérnék: jogilag helytálló-e az, ha meglévő számlázó rendszer (Rendszer) mellett az esetenként mégiscsak papír számlatömbbel kiállított számlát az adózó nem a NAV onlineszámla felületén a "számlaadat-rögzítése" menüpontjában tölti fel, hanem a Rendszerben rögzíti fel és küldi be?
Így működne:
- Egy "külső számlatömbös számla feltöltése" menüponttal tenné.
- A Rendszer nem generál hozzá saját számlaszámot, bekéri a tömb számlaszámát.
- A Rendszer semmiképp sem nyomtat sem eredeti, sem másolat példányt ebből, "tudja", hogy papír számlatömbös számla.
- A Rendszer ezt ugyanúgy beküldi a NAV részére, mintha saját maga állította volna ki.

Technikailag nem látom akadályát, jogilag annál inkább! :)

Remélem sikerült értelmesen megfogalmaznom! Köszönöm előre is!

**Comment by nbeeps2** [comment]
Számlázó program csak a programmal kiállított számlát küldheti be a NAV-nak! A papír számlatömbös számlát a felhasználónak a NAV felületén kell rögzíteni. Rögzítheti persze statisztikai célból a számlázó programban is, de azt a számlázó program nem adhatja fel a NAV részére.

**Comment by omachtandras** [comment]
A valóság az, hogy sokszor előfordul, hogy kézi számlát állítanak ki olyan cégek is, akik nem csak statisztikai célból rögzítik az ERP rendszerükben az ilyen számlákat, hanem azért is, mert ÁFA bevallást készítenek belőle, készlet mozgások generálódnak az ilyen bizonylatokból (mert mondjuk az értékesítő autója egy mozgó raktárként funkcionál és naponta 15-20 helyen is értékesít 1-2-3 terméket), stb. stb.

Jelenleg mi is azt mondjuk az ügyfeleinknek, hogy ha tehetik, akkor kérjék a mobilos applikációt, vagy használják a NAV számlázóját, és majd mi letöltjük azt és rögzítjük az ERP-ben.
De ez sokszor megoldhatatlan (nincs nyomtató az autóban, nincs térerő az adott helyen, ahol az értékesítés történik, a partner eseti, nincs a törzsben, elektronikus számlát nem kaphat, bonyolult a törzset bővíteni az alkalmazottnak, aki nincs azon az informatikai szinten, hogy tudja kezelni a dolgokat, stb....) 

Ilyenkor július 1-től marad a dupla rögzítés. Viszont azt látni kell, hogy az eddigi egy rögzítés optimalizálva volt, gyorsbillentyűkkel, funkciógombokkal pillanatok alatt rögzítettek egy-egy ilyen bizonylatot (mert akár napi több százról is szó lehet), készítették el a készlet mozgást, stb. stb.
Most ez mellé bejön a NAV-os felület, ami akár egy nagyságrenddel több idő is bizonylatonként, mint az optimalizált felületen rögzíteni.

Sajnos mi is azt olvassuk ki, hogy nem szabad géppel átadni az ilyen bizonylatokat, illetve nyilván komoly rizikó az, hogy az adatrögzítői tévedhet, de erre ott az anulálás lehetősége a javításhoz, és természetesen a NAV felületén is tévedhet a rögzítő (ahol ráadásul a mindent engedjünk be elv miatt sokkal kevesebb ellenőrzés van az elgépelések kiszűrésére, mint az eddigi folyamatokban....)

**Comment by NTCA-tax** [comment]
A számlázó program adatszolgáltatási funkcióját kizárólag a programmal kiállított számlákra lehet használni. Amennyiben a számla nyomtatványból lett kiállítva (kézi számla), akkor az Online Számla felületen kell az adatokat begépelni. Jogszabály oldaláról nem lehet megfelelőnek tekinteni a kézi számlák számlázó programon keresztüli adatszolgáltatását.

**Comment by eszel** [comment]
Nagyon köszönöm!
