### ISSUE TITLE
[Q&A] XSD a 2021.01.01. hatályba lépő változásokhoz

### ISSUE THREAD

**Issue by szalaierika** [nav-gov-hu/Online-Invoice#317]
Kedves NAV-os fejlesztők!

Érdeklődni szeretnék, hogy a 2021. január 1-én hatályba lépő online számla adatszolgáltatást érintő változásokhoz kapcsolódóan mikor kerülnek közzétételre az XSD-változások.

A nemzetközi szoftvercégek esetében már el kellene kezdeni ennek a fejlesztését, hogy még kiszállítás után a magyar vállalatok illeszteni tudják a saját üzleti gyakorlatukhoz. Ha ez nem történik meg 2-3 héten belül, akkor nagyon nagy kockázata van annak, hogy ezek a vállalatok nem fognak készen állni a belföldi magánszemélyek és a közösségen belüli adóalanyok részére kiállított számlák regisztrálására.

Előre is köszönöm a választ,
e.

**Comment by connorhu** [comment]
Erre a kérdéskörre próbáltunk választ kapni a #304 issueban.

**Comment by szalaierika** [comment]
Az XSD 3.0-ról már volt hivatalos kommunikáció?

**Comment by connorhu** [comment]
Nem tudni hogyan fogják hívni, de még nem volt semmi hír. A 3.0-t azért előlegeztük meg mert esélyes, hogy visszafele nem lesz kompatibilis, így megint főverziót ugrunk (ill valamelyik issueban valamelyik supporter 3.0-t említett).

**Comment by szalaierika** [comment]
Köszi a magyarázatot, de ez azért a #304 issueból nem derült ki egyértelműen, hogy a 21. január 1-i változásokhoz kapcsolódik.

**Comment by NTCA-supporter** [comment]
Szia @szalaierika !
Ezt az issuet zárom, maradjunk a #304 -nél. Annak a címébe beleírom az általad felvett címet is, egyben kezeljük.
A hivatalos kommunikáció nem tőlem fog jönni, de igyekszünk :)
Köszönöm a türelmet!

**Comment by szalaierika** [comment]
Szia, rendben, köszönöm előre is!
