### ISSUE TITLE
[FEATURE] Számlatömbbel kézzel kiállított papír alapú számla beküldésének lehetősége számlázóprogramon keresztül

### ISSUE THREAD

**Issue by eszel** [nav-gov-hu/Online-Invoice#319]
Kedves Fejlesztők / Jogalkotók!

Kérésem az, hogy adjatok lehetőséget arra, hogy bizonyos adózók az általuk kézzel kiállított számlákat, a NAV Online számla "Számlaadat-rögzítés" menüpontja helyett, az általuk amúgy is használt és ismert számlázó rendszeren keresztül küldjék be a NAV részére. 

Értelemszerűen ugyanazon az API-n keresztül, amin amúgy is beküldésre kerülnek a gépi számláik. Ez esetben a számlázó rendszer bekérné a számlatömb sorszámát és a szokásos adatokat, vigyázna arra, hogy ne engedjen saját "másolatot" adni a számláról, eleve tudja, hogy kézi számláról van szó, viszont a beküldést ugyanúgy azonnal megtenné, mintha saját maga állította volna ki azt. 

A gyakorlati probléma több idősebb gárdával ellátott adózónál az, hogy a cégnél már leginkább csak gépi számla kerül kiállításra, páran nagy nehezen megbarátkoztak a megvásárolt számlázóval, de sokan képtelenek megtanulni azt, és akár másik telephelyen egyedül dolgoznak. A kérés ugye az lenne, hogy megkülönböztetve az ilyen beküldést, jelezve, hogy ez papírtömbös számla, számlázóprogrammal is eleget tudjanak tenni az adatküldési kötelezettségüknek, ne kelljen egy 3. felületet is megismerniük.

Nagyon köszönöm előre is!

**Comment by NTCA-tax** [comment]
A jelenlegi jogszabályi keretekbe nem fér bele ez a megoldás. Az elektronikus módon történő adatszolgáltatás (API-n keresztüli adatszolgáltatás) a számlázó programmal kiállított számla, számlával egy tekintet alá eső okirat esetében lehetséges. Számlatömb esetén ebből kifolyólag kizárólag manuális adatrögzítés lehetséges. Amennyiben számlatömbből kiállított számla adatai API-n keresztül érkeznek be, akkor az nem megfelelően teljesített adatszolgáltatásnak minősülnek. 

A fentiek alapján a jelenlegi jogszabályi keretek alapján az általad leírt folyamat bár technikailag kivitelezhető lehet, ugyanakkor jogszabályi oldalról nem elfogadható.

**Comment by omachtandras** [comment]
NTCA-tax: annyi kérdésem lenne még, hogy látszódik a NAVnál az igény arra, hogy esetleg változzon ez a szabályozás a korábban leírt okok (ERPben amúgy is rögzíteni kell a számlát adóbevallás készítése és egyéb belső folyamatok) miatt?
Tényleg óriási overhead keletkezett egyes helyeken, holott a mondás az volt az egész adatszolgáltatással kapcsolatban, hogy a tisztességes cégeknek ez előnyére válik majd, csökken az adminisztráció, versenyelőnyt szereznek a szürke / fekete gazdasággal szemben, stb. stb.
Most ez nem érződik, tényleg rengeteg időt vesz el a dupla rögzítés kényszere.

A magam részéről azt gondolom, hogy a 3.0 apiba még talán beleférne egy flag, hogy papír alapú bizonylat gépi beküldése, ha a szabályozás is változtatható lenne odáig.

Köszönöm!

**Comment by KMGY100** [comment]
omachtandras  részéről egy korrekt kérés mert  egyszerűsíti a számla NAV-hoz való beküldését.  
Például.  javító szerelő  szolgáltató építőipari szakmát gyakorló vállalkozó számtalan van.
Egy ""rövid"" ideig tartó helyszíni munka után a kézi tömbbel állítja ki a számlát és célszerű lenne ha
otthon a jól ismert telepített számlázójában rögzíthetné ezt a kézi tömbös számlát. Még ide sorolhatjuk
a fuvarozókat is   ( és még ami nekem most nem jut eszembe)   
Ha az egyszerűsítés szempont a NAV-nál akkor e javaslat mellé kell állni.

**Comment by NTCA-tax** [comment]
Ez nem jogértelmezési kérdés, ezért csak továbbítani tudom a döntéshozók számára a javaslatot. 

Csak megerősítésként: A javaslat röviden az, hogy legyen lehetőség a számlatömbbel kiállított számlák adatait API-n keresztül beküldeni. Ez a beküldés az eredetileg számlatömbből kiállított számlának az összes adattartalmára vonatkozik (beleértve az eredeti számlasorszámot, a számla összes tételsorát és áfa törvény szerinti kötelező adattartalmát).

**Comment by omachtandras** [comment]
NTCA-tax: igen, a kérés ez lenne, annyival kiegészítve, hogy megvalósítási oldalon legyen egy flag, ami jelzi, hogy itt a gépi beküldés ellenére számlatömbben kiállított bizonylatról van szó, vagyis a szoftver csak egy "közvetítő" közeg.

Köszönjük a továbbítást!

**Comment by pvmon** [comment]
Én annak örülök ahogy most van!
Nem szívesen vállalnánk át ezt. A kézi számla lehet hibásan kitöltött vagy nem pont úgy viszik be a számlázóba, ahogy a számlán volt. Nem vállalnánk fel ennek a kockázatát, valamint a kapott hibák figyelmeztetések kezelését és az ahhoz kapcsolódó telefonálgatást sem,
Ha segíteni akarsz az ügyfélnek, akkor rögzítse kézzel a NAV-nál és onnan lekérdezheti a program és nem kell újra rögzíteni a rendszeredben és ezt most is meg lehet tenni.

**Comment by omachtandras** [comment]
@pvmon: igen, csak ha rögzítettél már a NAV felületén, akkor tudod, hogy van olyan adat, amit háromszor bekér, ráadásul nem is ellenőriz semmit, tehát pont az elgépelési hibákat nem fogja kiszűrni. Akkor pedig csak a hozzánk történő letöltéskor derül ki, aminek a következménye, hogy mehet vissza a NAV felületre, annulálhat, újra rögzíthet.
Azt gondolom, hogy ennek a támogatása nem lenne kötelező szoftver oldalról. Mi is, ha meglenne plusz támogatási díjért vállalnánk csak a megoldás támogatását.
De igény az van rá, van olyan ügyfél, akinek több plusz embert kellett felvennie azért, mert most rögzítenie kell a NAVhoz az adatokat. Persze, jó lenne, ha akár csak a NAV mobilos applikációját (vagy a miénket) használná számlázásra ott, ahol most kézi számlatömböt használ, de ez úgy tűnik még középtávon sem oldható meg (mert pl. nincs térerő az értékesítés helyén, vagy az értékesítést végző személy betanítása esélytelen, stb.).

(Egyébként, ha a kézi számlát hibásan állítja ki, azt egyértelműen a NAV felületén rögzíttetnénk be mi is, nem gondolom, hogy ez miatt felpuhítanánk a szoftver ellenőrzéseit. (Vagy pedig javítsa a számlán, megteheti, és utána rögzítse már a jó adatokkal.))

**Comment by pvmon** [comment]
Ha szoftverben rögzít kiválasztja a vevőt és a tételeket is. Lesz adószám, helyes cím, ami esetleg a kézi számlán nem is volt jó.
A tétel nevek sem biztos, hogy stimmelnek. A nettó, bruttó, mennyiség szorzat sem stimmel esetleg a kézi számlán, de a programba csak helyes adat kerülhet be.
Aztán az is biztos, hogy elrontják a rögzítést párszor, akkor gondoskodj sztornóról erről arról, szed le a NAV-tól ha már fel is lett küldve stb.
Ha mégis lesz is ilyen, mi nem fogjuk támogatni, mert nem biztos, hogy megvalósul az, hogy olyan legyen a felküldött számla, ahogy kiadták a vevőnek.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ez az issue zárható? Van még kérdés?

Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
