### ISSUE TITLE
[Q&A]TESZOR

### ISSUE THREAD

**Issue by Anddio80** [nav-gov-hu/Online-Invoice#32]
ProductCodeCategoryType új enum értéket kap (TESZOR), az új pattern hossz 5-ről 6-ra nő

ez továbbra is opcionális, vagy be kell vezetni, hogy a számlázó rendszerek ezt is továbbítsák?

**Comment by NTCA-developer** [comment]
Szia!

Feltettem a kérdést a szakmailag illetékeseknek, továbbítom a választ.

> A TESZOR (mint ahogy a VTSZ, SZJ) a számlának nem kötelező eleme. Az Áfa törvény 169. § f) pontja alapján ezen kódoknak a szerepeltetése a számlakibocsátásra kötelezett választása alapján kerül sor. Amennyiben feltüntetésre kerül a számlán, akkor sem kötelező ezen kódok adatszolgáltatásban történő szerepeltetése, mivel az adatszolgáltatási kötelezettség kizárólag az Áfa törvényben előírt kötelező adatokra vonatkozik. Így a számlázó rendszer fejlesztőjének a választásától függ, hogy ezen kódok az adatszolgáltató rendszerbe továbbításra kerülnek-e vagy sem.

Megjegyzendő, hogy a napi gyakorlatban inkább annak igazolására szokták alkalmazni a számlakibocsátók ezeket a kódokat, hogy miért nem a standard 27%-os adókulcsot használják. Amennyiben a vevő az adatszolgáltatások alapján valamilyen feldolgozási folyamatot elindít, akkor megfontolandó ezeknek a kódoknak a szerepeltetése. A sémába éppen a gyakorlati megfontolásból került bele a VTSZ, SZJ és erős adózói kérés volt a TESZOR szerepeltetése is. Tehát üzleti oldalról biztosan lehet szerepe, de nem jogszabályi kötelezettségről beszélünk.

Majd kérlek zárt le a ticketet, ha már nem kell.

**Comment by NTCA-developer** [comment]
Ezt most lezárom, nyiss majd nyugodtan új kérdést, ha idő közben felmerül még valami.
