### ISSUE TITLE
[Q&A] Adatszolgáltatás 2065M lapon

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#320]
Készítjük a fejlesztést az adatszolgáltatáshoz, amelyet a 2065M lapokon kell megtenni.
Azon már túl vagyok, hogy a PM-NAV közös közlemény szerint a végszámláknál olyan plusz sort várnak el, amely nincs az áfa törvény 10.sz. mellékletében, mert ott csak a különbözet  van előírva.
[https://www.nav.gov.hu/nav/ado/afa/A_szamlaadat_szolgalt20200701.html](url)

Azt is megértettem, hogy nem kell a 2065M-02 lapon szerepeltetni azon számlát sem, amelynek érvénytelenítése a bevallás benyújtásáig megérkezik.

**Várható-e még további módosítás a nyomtatványban, vagy várható-e még olyan elvárás a NAV részéről, amely meghaladja az ÁFA törvényben leírtakat?**
1.	Várható-e, hogy azon számlákat sem kell beletenni a 2065M-02 lapra, amelyeknél 500 Ft alatti adóalap és/vagy 500 Ft alatti adó szerepel, vagy azokat 0 alap és 0 adóval kell adatot szolgáltatni?
2.	Fenntartják-e azt a jelenlegi állapotot, hogy ugyanarról a végszámláról másképpen kell adatot szolgáltatni attól függően, hogy a 2065M-02 lapra, vagy a 2065M-02-K lapra kerül? (Az egyikben 2 soron kell szerepeltetni, a másikban csak egy soron.)
Példa: ha a VEG-1 számlaszámú végszámlán szereplő termékértékesítés 499 Ft, az adó 135 Ft, amelybe a 59.§ szerinti előleg betudás történik, amelynek alapja 200 Ft, adója 54 Ft, majd ezt a számlát még ugyanabban az áfa időszakban módosítják MOD-1 számlaszámú módosító okirattal, a módosítás  hatása +1400 Ft alap és +378 Ft adó.
3. **Helyes-e az alábbi kitöltési fejlesztés, ha a 2065M-02 lapra két sorba kerül a végszámla:** 
•	1.sor: Számlaszám: VEG-1, Teljesítés: 20200716, Alap: 0, Adó 0
•	2.sor: Számlaszám: VEG-1, Teljesítés: 20200716, Alap: 0, Adó 0
**A 2065M-02-K lapra** 
•	1.sor: Számlaszám: VEG-1, Típus E Kelt: 2020.07.16 Teljesítés: 2020.07.16., Alap: 0, Adó 0
•	2. sor: Számlaszám: MOD-1, Típus KT Kelt: 2020.07.17 Teljesítés: 2020.07.17., Alap: 1, Adó 0

**Comment by kabelnet2** [comment]
Nekem is lenne egy kérdésem az ÁFA bevallás mellékletével kapcsolatban: ha van egy számla, amit eddig nem szerepeltettünk a mellékleten, mert nem érte el az éppen aktuális ÁFA limitet, akkor egy erre hivatkozó, most kiállított módosító számláról sem kell adatot szolgáltatni. Ez így igaz?

**Comment by Macskafarka** [comment]
@kabelnet2 Szerintem szerepeltetni kell a 2065M-02-K lapon a módosító számlát akkor is, ha az előzményét korábban nem szerepeltettük még soha sem.  KT jelzéssel megy a módosító számla, és előtte lévő sorban az eredeti számla E típussal.
Értelemszerűen, ha több módosítás is megelőzte a mostanit, akkor  a teljes láncolatot szerepeltetni kell, a legelső sorban az eredeti számlát E-vel, aztán szépen sorban a módosítókat K-val, és a tárgyidőszaki módosítókat KT-val.
A problémát igazából a láncolat felépítése jelenti, mert nem biztos, hogy befogadó oldalon a lánc minden eleme megérkezett, és ez sem biztos, hogy a sorrendjük tudható. De ez egy másik történet.

**Comment by nbeeps2** [comment]
Javaslat: Ez az egész 2065M nyomtatvány ebben a formában felesleges... A NAV július 1-től pontosan látja az összes bejövő számlát, így minek erről még egyszer adatot szolgáltatni ilyen formában? Ha pedig erre az a válasz, hogy lehet nem minden számlát akar elszámolni a cég költségként, akkor mivel ez lehet a kevesebb, inkább arról kellenek akkor adatotszolgáltatni, hogy volt 100 bejövő számla, de abból 2-t nem akarunk elszámolni és nem mind a 100-at rátenni, amire így is úgy is rálát a NAV...

**Comment by connorhu** [comment]
Nem lát minden számlát július 1-től. Azt majd január 1-től.

**Comment by Macskafarka** [comment]
@nbeeps2 Nem érted a lényeget. :) 
A kibocsátó kibocsátja az egyszerűsített számlát, amit egy következő ÁFA időszakban módosít. A befogadónak be kell tennie a számlát a pl. a 2065A 66. sorába, de csak az általa levonható részét, majd az M-02 lapra a számla teljes áthárított egyesen adóját, ahol már adóalapra és adóra kell átszámolnia az egyszerűsített számlán ilyen mélységben nem is szereplő adatokat. Ehhez összesíteni kell, amiben nem lehet fordított áfa, és nem lehet áfa körön kívüli tételsor sem. Ha végszámla (ami nem lehet egyszerűsített), akkor 2 sorban kell kerülnie az M-02-ba a végszámlának, de ha azt helyesbítik, akkor  az M-02-K-ba a végszámla már 1 soron kell E jelzéssel.
Ha az érvénytelenítő számla megérkezik az ÁFA bevallásig, akkor kihagyható az M-02 lapról az eredetivel együtt. ha később jön, akkor kell az eredeti a 02 lapra, és a következő bevallásban az egész láncolat a 02-K lapra.
Legyünk büszkék arra, hogy a világ legbonyolultabb ÁFA rendszererét működtetjük!
Aki nálunk egy közepes szintű könyvelő, az más orszgágban adószakértő lenne. :)

**Comment by Macskafarka** [comment]
Az a cél, hogy hiba lehetőséget kell teremteni! Majd ellenőrizni. Összevetni a SUP adatszolgáltatást az EKÁER-rel, és a xx65M lapokkal. Valaki csak téved! Ha másképpen nem, akkor egy nullát O betűnek néz, vagy kihagy egy kötőjelet.
Lehet önrevíziózni, amiért pénzt lehet kérni.
Nemsokára ki fogják találni, hogy a 2065M-02 lapra is tételsorok kellenek. Az adózás már évekkel korábban kisiklott, most csak mélyül a gödör.

**Comment by celeburdi** [comment]
A könyvelőirodában két könyvelőprogram van használatban. Egyik sem alkalmas jelenleg a 65M lapos bevallások előállítására,
Tehát az M lapokat manuálisan kell kitöltögetni. Remek.
Ez egy kis cégnél is 20x annyi munkát jelent mint eddig.+nagy a hibázási lehetőség.
Ki fogja ezt megfizetni?

Belenéztem a bejövő számlákba is.

Hiába használják a számlázó programot - nem tudnak számlázni.

Ha van van checkbox biztos hogy,  elbaltázza (bejelöli a pénzforgalmi áfa-t pedig nem az, nem jelöli az előleget,
Le sem vonja a végszámlánál (simán odaírja 1 db elszámolás)

Ennyit az adminisztráció csökkentéséről..

**Comment by topybear** [comment]
Csaxólok: a 2165M-en megjelent az "előlegből adódó különbözet jelölése" oszlop, hogy lehessen jelölni  a végszámla és a végszámla különbözettel sort.

**Comment by Macskafarka** [comment]
@topybear Köszönöm. Mégiscsak van értelme ide írni ;)

**Comment by Macskafarka** [comment]
Azért arra nagyon kíváncsi vagyok, hogyan fogja elkészíteni a 2165M-02, és M02-K lapokat a NAV 2021.július 01-től. Ki fogja-e hagyni a stornó párokat, a végszámnál a 0 összegűeket kihagyja-e, vagy azt is két soron közli? Továbbá valóban csak az "Egyenes áfa" lesz-e a 2165M-02 lapokon. Magyarul képes-e azt megcsinálni a NAV, amit másoktól elvárt eddig.
