### ISSUE TITLE
[Q&A]Pénztárgépes blokkból egy tétel visszahozása vagy teljes blokk sztornózása

### ISSUE THREAD

**Issue by eszel** [nav-gov-hu/Online-Invoice#321]
Kedves Support/Dev!

Kérdésem, hogy adózó hogyan tud egyszerűen pénzt visszafizetni a blokkos lakossági magánszemély vevőnek (pénztárgépes blokkon vásárolt, nem kért számlát), amikor ő valamit visszahoz?

Eddig adózó ilyen esetben utólag bekérte a vásárló adatait és utólag számlát adott a blokkról, a blokkot ugye hozzátűzte, majd abból visszáruzott.. Ezután bevezette, hogy rögtön mínuszos tételt vitt fel egy egyszerű  (CREATE) számlára, de ugye ez is helytelen, alapbizonylat sorszáma nélkül WARN-t is kap rá.

Telefonon a NAV (1819 / 7 / 2) azt a választ adta a mai nap, hogy adjanak módosító vagy sztornírozó számlát ilyenkor nyugodtan, alapbizonylat sorszámának (_originalInvoiceNumber_) a pénztárgép blokk sorszámát adják meg, arra hivatkozzanak, és jelöljék be feltöltéskor, hogy alapbizonylat nélküli módosítás (_modifyWithoutMaster_).

Kérdésem, hogy ez tényleg járható út? Eleve az originalInvoiceNumber specifikációja: Az eredeti **számla** sorszáma, melyre a módosítás vonatkozik - ÁFA tv. 170. § (1) c) ). Ha pedig nem járható, akkor hogy tud egyszerűen pénzt visszaadni az adózó lakossági blokkos magánszemély vásárlónak?

Nagyon köszönöm! Üdv: Laci

**Comment by NTCA-tax** [comment]
Elvileg a pénztárgép is tud visszáruzni, erre kellene lenni külön funkciónak.

Az Áfa törvény 168. § (2) és 170. § alapján nem megfelelő megoldás a nyugtát számlával egy tekintet alá eső okirattal módosítani, érvényteleníteni.

**Comment by eszel** [comment]
Köszönöm! Ami gond a másik oldalon, hogy az egyszerű (~200eFt) pénztárgépek egy nagyon gyakorlott p.gépkezelő részére is min. 8-10 perc munkával megoldható módon engedélyezik pl. 1 visszahozott tétel visszafizetését. Bekérik a számbillentyűzeten kétféle funkció billentyű segítségével pl. a vevő nevét, címét, a 20 karakteres eredeti blokkszámot. Próbálják bekérni a cég nevét, adószámát (blokk esetén, igen.. nem értem.. de ezeken tovább lehet talán menni), azt hiszem még a termék nevét is kérik.. Billentyűzet nem csatlakoztatható. Ezért sajnos a gyakorlat az én látókörömben az, hogy megpróbálják az adózók inkább számlával megoldani. Tudom, hogy ez innentől nem Online-Invoice issue.. de ennek a jogi és gyakorlati megoldása tényleg hatékonyan segítené az adózókat, akár célzottan erre felé is mehetne a fejlesztés. Gondolom nem valószínű, hogy egykönnyen, emberi időn belül leegyszerűsíthető lenne egy fekete dobozos pénztárgépben ez a funkció.

**Comment by NTCA-tax** [comment]
Ez már online pénztárgép probléma. A fórumon maradjunk meg az Online Számla rendszert érintő kérdéseknél.
