### ISSUE TITLE
TokenExchangeRequest -> INVALID_REQUEST_SIGNATURE

### ISSUE THREAD

**Issue by robozb** [nav-gov-hu/Online-Invoice#322]
Online Invoice Test Tool Build: 2.0.7356.23982

Sziasztok! 

Kérnék szépen egy kis segítséget a program használatához, a Token Exchange funkcióhoz. 

Ha megadok mindent helyesen a Request Setting fülön akkor miért kapom erre a kérésre:

`<?xml version="1.0" encoding="UTF-8"?>`
`<TokenExchangeRequest xmlns="http://schemas.nav.gov.hu/OSA/2.0/api">`
`  <header>`
`    <requestId>RIDC872390831</requestId>`
`    <timestamp>2020-07-17T22:56:24.598Z</timestamp>`
`    <requestVersion>2.0</requestVersion>`
`    <headerVersion>1.0</headerVersion>`
`  </header>`
`  <user>`
`    <login>e4aupkuyvqrk5yv</login>`  `<passwordHash>94FC66501EC8F1B6B6CE99364B5382280A69843D56DAD0E98902F149DAD3359BE602490D01831E1F7F5FCCEF5887E46B19098255F76B4249030466A374C93EAB</passwordHash>`
 `   <taxNumber>62635927</taxNumber>`
    `<requestSignature>280FAA53BEF9505031AD7771A947202BEBC75D2882413FCA9B9EE55CF500E2879C86739BA339CCAE2AD8A69EA7A71B388DC7A4EF582884B4F92F178B20DA1ECE</requestSignature>`
`  </user>`
`  <software>`
`    <softwareId>123456789012345678</softwareId>`
`    <softwareName>WFSUgyviteliRendszer</softwareName>`
`    <softwareOperation>LOCAL_SOFTWARE</softwareOperation>`
`    <softwareMainVersion>1.0.0</softwareMainVersion>`
`    <softwareDevName>WFS</softwareDevName>`
`    <softwareDevContact>0036703155201</softwareDevContact>`
`    <softwareDevCountryCode>HU</softwareDevCountryCode>`
`    <softwareDevTaxNumber>62635927</softwareDevTaxNumber>`
`  </software>`
`</TokenExchangeRequest>`

ezt az elutasító választ?

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
`<GeneralErrorResponse xmlns="http://schemas.nav.gov.hu/OSA/2.0/api" `xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/data">`
`  <header>`
 `   <requestId>RIDC872390831</requestId>`
`    <timestamp>2020-07-17T22:56:24.598Z</timestamp>`
`    <requestVersion>2.0</requestVersion>`
`    <headerVersion>1.0</headerVersion>`
`  </header>`
`  <result>`
`    <funcCode>ERROR</funcCode>`
`    <errorCode>INVALID_REQUEST_SIGNATURE</errorCode>`
`    <message>Érvénytelen kérés aláírás!</message>`
`  </result>`
`  <software>`
`    <softwareId>123456789012345678</softwareId>`
`    <softwareName>WFSUgyviteliRendszer</softwareName>`
`    <softwareOperation>LOCAL_SOFTWARE</softwareOperation>`
`    <softwareMainVersion>1.0.0</softwareMainVersion>`
`    <softwareDevName>WFS</softwareDevName>`
`    <softwareDevContact>0036703155201</softwareDevContact>`
`    <softwareDevCountryCode>HU</softwareDevCountryCode>`
`    <softwareDevTaxNumber>62635927</softwareDevTaxNumber>`
`  </software>`
`</GeneralErrorResponse>`

Előre is köszönöm!

Üdv: Béci

**Comment by connorhu** [comment]
Hogyan képzed az aláírást? Ott lehet valami probléma.

```
        $buffer = '';
        $buffer .= $request->getRequestId();
        $buffer .= $request->getHeader()->getTimestamp()->format('YmdHis');
        $buffer .= $request->getUser()->getSignKey();
        
        $requestVersion = $request->getHeader()->getRequestVersion();
        if ($requestVersion === Header::REQUEST_VERSION_V10 || $requestVersion === Header::REQUEST_VERSION_V11) {
            return strtoupper(hash('sha512', $buffer));
        }
        if ($requestVersion === Header::REQUEST_VERSION_V20) {
            return strtoupper(hash('sha3-512', $buffer));
        }
```

**Comment by robozb** [comment]
Nagyon köszönöm a gyors infót, a "Online Invoice Test Tool" GUI állítja elő automatán, de
közben meg is lett a probléma, a technikai felhasználó cserekulcsát írtam el. Én voltam a ludas :)

Üdv: Béci
