### ISSUE TITLE
Invalid byte 1 of 1-byte UTF-8 sequence.

### ISSUE THREAD

**Issue by robozb** [nav-gov-hu/Online-Invoice#323]
Sziasztok!

Vajon mit rontok el, ha ezt a hibaüzenetet kapom számla beküldés után, státuszként?

`<?xml version="1.0" encoding="UTF-8"?><QueryTransactionStatusResponse xmlns="http://schemas.nav.gov.hu/OSA/2.0/api" xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/data">`
     `<header>`
`          <requestId>62635927_1_1595364475013</requestId>`
`          <timestamp>2020-07-21T20:47:55.013Z</timestamp>`
`          <requestVersion>2.0</requestVersion>`
`          <headerVersion>1.0</headerVersion>`
`     </header>`
`     <result>`
`          <funcCode>OK</funcCode>`
`     </result>`
`     <software>`
`          <softwareId>000000000000000001</softwareId>`
`          <softwareName>WFSUgyviteliRendszer</softwareName>`
`          <softwareOperation>LOCAL_SOFTWARE</softwareOperation>`
`          <softwareMainVersion>1.0.0</softwareMainVersion>`
`          <softwareDevName>WFS</softwareDevName>`
`          <softwareDevContact>0036703155201</softwareDevContact>`
`          <softwareDevCountryCode>HU</softwareDevCountryCode>`
`          <softwareDevTaxNumber>62635927</softwareDevTaxNumber>`
`     </software>`
`     <processingResults>`
`          <processingResult>`
`               <index>1</index>`
`               <invoiceStatus>ABORTED</invoiceStatus>`
`               <technicalValidationMessages>`
`                    <validationResultCode>ERROR</validationResultCode>`
`                    <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>`
`                    <message>XML contains on line: [14] and column: [46] error: [Invalid byte 1 of 1-byte UTF-8 sequence.]</message>`
`               </technicalValidationMessages>`
`              <technicalValidationMessages>`
`                    <validationResultCode>ERROR</validationResultCode>`
`                   <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>`
`                    <message>Xml validation failed</message>`
`               </technicalValidationMessages>`
`               <compressedContentIndicator>false</compressedContentIndicator>`
`          </processingResult>`
`          <originalRequestVersion>2.0</originalRequestVersion>`
 `    </processingResults>`
`</QueryTransactionStatusResponse>`

A számla a séma szerint érvényes!

Köszönöm a segítséget!

Üdv: Béci

**Comment by connorhu** [comment]
Szia!

Nem jó karakterkódolásban van az elküldött adat. UTF-8nek mondott valami mást (pl középeurópai iso8859-2) küldesz el.

**Comment by robozb** [comment]
Köszönöm, nézem, én is erre gyanakodtam, de nem tudom még, hogy hol kell beállítani

**Comment by robozb** [comment]
Óriási, sikerült :)  Java-ban(JAXB), a szamla adat beállításánál tudtam végre meghatározni :)

`iot.setInvoiceData(szamlaXmlStr.getBytes("UTF-8"));`

Ez volt az utolsó lépés, végre minden stimmel a számla beküldésével!

Hálás köszönet!
