### ISSUE TITLE
[Q&A] Sztornó és helyesbítő számlák esetén a referencia hivatkozások kezelése

### ISSUE THREAD

**Issue by schvoy** [nav-gov-hu/Online-Invoice#325]
Kedves Fejlesztők!

Érdeklődni szeretnék, hogy mi a helyes eljárás az xml generálása során a `lineModificationReference` értékeit illetően?

Összesítésben úgy gondoljuk, hogy meglévő tételsorok esetén mindig a MODIFY-t kell használni (sztornó esetén csak ilyen sor lesz). Míg új sorok esetén a CREATE-t.
Kérdés, hogy helyes-e az értelmezésünk, illetve ha valamelyik esetben nem, akkor miként kellene pontosan a hivatkozásokat szerepeltetni?

### Sztornó számla kiállításakor

1. tétel sor:

```xml
<line>
    <lineNumber>1</lineNumber>
    <lineModificationReference>
        <lineNumberReference>1</lineNumberReference>
        <lineOperation>MODIFY</lineOperation>
    </lineModificationReference>
    [...]
</line>
```

2. tétel sor:

```xml
<line>
    <lineNumber>2</lineNumber>
    <lineModificationReference>
        <lineNumberReference>2</lineNumberReference>
        <lineOperation>MODIFY</lineOperation>
    </lineModificationReference>
    [...]
</line>
```

### Helyesbítő számla kiállításakor

2. tétel sor módosítása:

```xml
<line>
    <lineNumber>1</lineNumber>
    <lineModificationReference>
        <lineNumberReference>2</lineNumberReference>
        <lineOperation>MODIFY</lineOperation>
    </lineModificationReference>
    [...]
</line>
```

Új sor hozzáadása

```xml
<line>
    <lineNumber>2</lineNumber>
    <lineModificationReference>
        <lineNumberReference>3</lineNumberReference>
        <lineOperation>CREATE</lineOperation>
    </lineModificationReference>
    [...]
</line>
```

**Comment by NTCA-supporter** [comment]
Szia @schvoy !
Én úgy látom teljesen jó az értelmezésed, a megfelelő sorszámokat/hivatkozásokat használod.
Üdv

**Comment by laladisc** [comment]
A kitöltési útmutató az mondja, hogy mind CREATE, mind MODIFY használható mind a két esetben (nyilván a megfelelő lineNumberReference értékek használatával). Én csak CREATE-et használok, mindig új tételt hozok létre akár stornónál, akár helyesbítőnél. Véleményem szerint így egyszerűbb és átláthatóbb a módosítás.

**Comment by schvoy** [comment]
Köszi a válaszokat! 

@NTCA-supporter Az is valid megoldásnak számít, amit @laladisc írt?

**Comment by NTCA-supporter** [comment]
Szia @schvoy !
Igen, az összesített állapotban ugyanúgy kijön a matek, ha helyes adatokkal küldöd be.
Zárom az issuet, ha van még kérdés nyisd újra.
Köszi
