### ISSUE TITLE
[Q&A] Önszámlázás jelölése / selfBillingIndicator -> SUPPLIER_CUSTOMER_MATCH_TAXPAYER

### ISSUE THREAD

**Issue by amargo** [nav-gov-hu/Online-Invoice#326]
Kedves Dev csapat!

Önszámlázás jelölésére a dokumentáció szerint a selfBillingIndicator használatos. Ez beállításra is kerül az xml-be, amikor az eladónak és a vevőnek ugyanaz az adószáma. Bevallom nem vagyok tisztában, hogy a jogszabály szerint ezt így kell-e kezelni.
Viszont ebben az esetben jön egy warning:
SUPPLIER_CUSTOMER_MATCH_TAXPAYER Eladó és vevő adószáma nem lehet azonos .InvoiceData/invoiceMain//invoice/invoiceHead/supplierInfo/supplierTaxNumber/taxpayerId

_ Figyelmeztet, ha az eladó és a vevő adószám első nyolc számjegye azonos.
Csak akkor fut le, ha mindkét adat létezik.
InvoiceData/invoiceMain/invoice/invoiceHead/supplierInfo/supplierTaxNumber/taxpayerI
d
InvoiceData/invoiceMain/invoice/invoiceHead/customerInfo/customerTaxNumber/taxpay
erId_

Mi nincsen jól beállítva? A dokumentáció szerint önszámlázás esetén elegendő csak a selfBillingIndicator true ra rakni.

Előre is köszönet a segítségért.

**Comment by NTCA-supporter** [comment]
Szia @amargo !
Szerintem technikai oldalról nézve helyesen küldöd be ilyen formában. A WARN jelenleg a selfBillingIndicator-tól függetlenül megfut. Utánakérdezek, hogy ezen szükséges-e finomítani.
Üdv

**Comment by baracsi** [comment]
Az önszámlázás nem azt jelenti, hogy magadnak számlázol, hanem azt, hogy a vevőd (megállapodás alapján) a te nevedben (a te technikai felhasználóddal a te adószámodra) állít ki számlát magának. Vagy itt nem erről van szó?

**Comment by amargo** [comment]
@baracsi bevallom jogi értelemben ennyire nem ismerem a vonatkozó szabályokat. Annyit tudok, hogy van egy Eladó, aki a saját számlázóján keresztül magának (ugyan azaz adószám) mint Vevő kiállít számlát.

**Comment by baracsi** [comment]
Nem lehet azonos a 2 adószám egyik lehetséges esetben sem. Tudni kellene, hogy ebben a történetben te melyik szereplő vagy. Eladó vagy vevő?

1. te vagy az eladó (adószámod X): megbízod a vevődet (adószáma: Y), hogy állítson számlát saját magának, ő elkészíti a számlát saját magának. (X) adószám a számla kiállító (Y) adószám a vevő és beküldi a NAV rendszerébe (X) adózó technikai felhasználójával. A számla megjelenik (X) adózó beküldött számlái között.

2. te vagy a vevő: te állítasz ki egy számlát a saját rendszeredben magadnak, ahol te vagy a vevő (Y) az eladó pedig (X). Az eladótól kapott technikai felhasználói adataival (X adózóhoz tartozó autorizációs adatokkal) beküldöd a számlát a NAV rendszerébe.

Egyik esetben sem fog megegyezni az adószám. Arra kell odafigyelni, hogy ha te adsz (X adózó) technikai felhasználói adatokat (Y)-nak, akkor korlátozd le (Y) adószámra az ilyen technikai felhasználót, különben tetszőleges adószámra tudnak kiállítani számlát a nevedben. Ilyenkor az eladótól kapott technikai felhasználóval egyrészt csak (Y) adószámra tud számlát beküldeni, másrészt nem tud turkálni az eladó által másoknak kiállított számlák között, mivel semmi köze hozzá.

**Comment by amargo** [comment]
@baracsi pedig azonos a két adószám.
Van egy felhasználó - mint eladó -, aki használ egy számlázót x adószámmal, majd felvett egy partnert - saját magát mint vevő - x adószámmal és kiállított egy számlát. A programban nincs semmilyen korlátozás ezzel kapcsolatban, de ilyenkor a program a selfBillingIndicator-t true ra rakja.

**Comment by baracsi** [comment]
Ez nem az általam ismert önszámlázás, hanem valami más. Tehát te gyakorlatilag magadnak adod el, azt ami a tiéd, nem tudom hogy ez szabályos-e. Kérd ki vagy a könyvelőd véleményét vagy a NAV állásfoglalását!

**Comment by laladisc** [comment]
Szia!
Ez nem önszámlázás. Nálunk is előfordul ilyen, pl mezőgazdaságban a tenyészállat aktiválásnál. Készül egy belső számla ahol a szállító is és a vevő is te vagy. Az áfa miatt van erre szükség, mivel ez saját vállalkozásban végzett beruházásnak minősül. Igazából számviteli bizonylattal is megoldható lenne, de az a gyakorlat sok helyen már hosszú évek óta, hogy számlát állítanak ki róla. Kapsz rá egy warn-t, de a számla bemegy.

**Comment by omachtandras** [comment]
Majd jön NTCA-tax és megmondja a tutit, de szerintem erről nem számlát kell kiállítani, csak számviteli bizonylatot, és nem is szabad beküldeni az adatszolgáltatásba.
Ha jól emlékszem egyik ügyfelünk még állásfoglalást is kért róla és ez volt a mondás.

Mindenesetre ez biztosan nem önszámla.

**Comment by amargo** [comment]
@omachtandras Köszi, nem láttam ezt az állásfoglalást, de kíváncsi vagyok rá, mert akkor ebben az esetben rosszul működik a program.

**Comment by amargo** [comment]
@laladisc azt látom, hogy bemegy a számla, csak zavaró a WARN ezért szeretnék utánajárni.

**Comment by NTCA-tax** [comment]
Egy kicsit távolabbról kezdem a kérdést, mert itt lehetnek alapfogalmi problémák is.

Számlát kiállítani az áfa törvény szerinti termékértékesítésről vagy szolgáltatásnyújtásról kell. Az értékesítéshez mindenképpen két fél szükséges, egy eladó és egy vevő. Ez a két fél nem lehet ugyanaz, mivel akkor nem beszélhetünk értékesítésről. Így tehát nem értelmezhető egy vállalkozáson belüli készletmozgásról számla kiállítása. Amennyiben belső mozgás van, akkor azt számviteli bizonylattal és nem számlával kell dokumentálni (számviteli bizonylat esetén nincs számlaadat-szolgáltatás!). A számla mindenképpen értékesítési bizonylatnak minősül, amikor két eltérő félnek mindenképp szükséges lennie.

Számlát kiállíthat az értékesítő vállalkozás saját maga is, de ezzel megbízhat más vállalkozást. Ekkor meghatalmazotti számlázásról beszélünk, melynek speciális szabályai vannak. Például a két fél között írásbeli megállapodás szükséges, a számla kiállítójának elkülönült sorszámtartományban kell kiállítania a számlákat, a számlakibocsátás tekintetében pedig egyetemleges a felelősség. Az ilyen meghatalmazotti számla kiállítás nagyon gyakori például közmű szolgáltatóknál, ahol egy nagy kapacitású nyomda lesz a számla kibocsátója. De lehet például elektronikus számlázási szolgáltató is, amikor az értékesítő egy technikai tevékenységet kiszervez. És még biztosan nagyon hosszan lehet sorolni az ilyen példákat.

Az önszámlázás a meghatalmazotti számlázás speciális esete, amikor a számlázási meghatalmazott maga a vevő. Ekkor jellemzően az értékesítő-vevő viszonylatában a vevő rendelkezik olyan információval, ami alapján a számlákat ki lehet állítani. Ilyen lehet például értékesítési jutalékról szóló számlák, amikor a vevő informatikai rendszerében áll rendelkezésre az adott időszak jutalék számításához szükséges adatok. De nagyon jellemző gyártó tevékenységet folytatóknál, amikor a beszállító beviszi az árut a gyár raktárába, és a megállapodásuk alapján akkor történik meg az értékesítés, amikor az adott árut felhasználja a gyártó társaság. 

Könnyen be lehet látni, hogy a meghatalmazotti számlázáson belül az önszámlázásnak azért vannak kockázatai, talán ebből a logikából kifolyólag kötelező jelezni a számlán, amennyiben önszámlázással került kiállításra a számla. No és itt kanyarodok vissza a kérdésre, tehát az ilyen típusú számlákat kell jelölni a selfBillingIndicator mezőben. Mivel itt fogalmilag két eltérő félről beszélünk, ezért az eladó és a vevő nem lehet azonos.

Talán a kérdéssel kapcsolatban kimaxoltam a választ, de ha valami még kérdéses lenne, akkor visszakanyarodhatunk rá.

**Comment by amargo** [comment]
@NTCA-tax 
A fent leírtak számomra helyre tették a dolgokat egy vállalkozással kapcsolatban, de egy kérdés még maradt bennem, akkor sem értelmezhető, hogy az eladó és a vevő ugyan az, ha ez egy lakásszövetkezet? Ha jól tudom külön szabályozás alá esnek.

**Comment by NTCA-tax** [comment]
A lakásszövetkezet egy önálló adóalany, nem értelmezhető adóalanyon belül semmilyen értékesítés.

**Comment by amargo** [comment]
@NTCA-tax Köszönöm! Továbbítottam az infókat.
Nincs több kérdésem, zárom.
