### ISSUE TITLE
[Q&A] Kaució visszafizetése, negatív számla gond

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#327]
Az eset az alábbi:

Az irodaház (számlakiállító) kiállít egy számlát a bérlő (vevő) részére kaucióról (pl. 3 havi bérleti díj).
A bérlő éveken(!) keresztül fizeti a bérleti díjat, majd pár év múlva felmondja az irodát. 
Az irodaház ilyenkor visszafizetné az évekkel(!) ezelőtt kifizetett kauciót, tehát negatív előjelű számlát állítana ki (de ugye az WARN-t kap...). Helyesbítőt nem állíthat ki, mert az eredeti számla évekkel ezelőtti és önellenőrzéssel járna.

Mi a helyes eljárás konkrétan ebben az esetben, tehát nem visszáruról van szó, ahol elfogadom a helyesbítő alkalmazását, hanem ez egy kaució visszafizetés. A vevő nem számlázhatja ki az iroadháznak a kauciót, mert nincs ilyen szolgáltatás a tevékenységi körében...

**Comment by celeburdi** [comment]
Szerintem a kaució nem termékértékesítés és nem szolgáltatás nyújtás és nem előleg és nem ÁFA-s.
A kaució nem szerepelhet semmilyen ÁFA bevallásban, ezért nem kell önellenőrizni sem.
Számlázni a kaució felhasználását kell. (pl. felhasználják bérleti díjra)
A kaucióról számviteli bizonylatot kell kiállítani. (A számviteli bizonylat lehet akár a szerződés is amiben szerepel a kaució)
A kaució visszafizetéséről is számviteli bizonylatot kell kiállítani.

**Comment by NTCA-tax** [comment]
A kérdést @celeburdi tökéletesen megválaszolta :) A kaució fizetése nem termékértékesítés és nem is előleg. Számviteli bizonylatot kell kiállítani, nem számlát.

**Comment by nbeeps2** [comment]
Sajnálom, de nekem a válasz nem elég részletes.

Milyen fejlécű bizonylatot tekintünk számviteli bizonylatnak? Egy számlázó programmal, ami csak számlát tud kiállítani milyen bizonylatot állítson ki? A számla kiállítása már megtörtént a kaucióról, akkor most hogyan tovább?
