### ISSUE TITLE
[Bug]UTF-8 karakterkódolási hiba

### ISSUE THREAD

**Issue by ntamas91** [nav-gov-hu/Online-Invoice#328]
Sziasztok!

Éles környezetben futottunk bele ebbe a hibába. INBOUND számlák lekérdezésénél a vissza kapott adatok között volt olyan, hogy az ékezetes betűk helyett '?' jel szerepelt. Megnéztük a NAV online felületen is és ott is hibásan jelentek meg annál a számlánál az adatok. 

Üdvözlettel,
Tamás!

**Comment by NTCA-developer** [comment]
Szia @ntamas91 

Ha karakterkódolási hibát látsz, akkor az így jött be, ha mi csak parsoljuk az UTF-8-at, nem konvertálunk vagy csinálunk semmi mást a kódolással. A kiállítónál tudod megreklamálni a dolgot, van ilyen relatíve elég sok. Majd kérlek zárd le ha nincs több kérdésed.
