### ISSUE TITLE
[Q&A]504 Gateway Time-out

### ISSUE THREAD

**Issue by ntamas91** [nav-gov-hu/Online-Invoice#329]
Sziasztok!

Ez elvileg nem API hiba, hanem szerver hiba. Mert a válasz formátuma sem XLM.
De éles rendszerben futunk ebbe a hibába folyamatosan 'QueryInvoiceDigestRequest' esetén. Teszt környezetben ez a hiba nem jön elő és akkor sem ha éles rendszer esetén kevesebb mint négy nap a lekérdezett időintervallum. Illetve a múlt héten még éles rendszerben sem jött elő ez a hiba! Bár jóval lassabban futott le, mint a teszt környezetben, körülbelül 80-90 másodperc. Amíg ugyan ez a teszt környezetben 15-20 másodperc.
 
A lekérdezett idő intervallum:
A feltöltés idejére vonatkozik és körülbelül 58-60 bejövő számla lenne:
2020-07-01T08:52:51.000Z
2020-07-28T09:11:59.000Z

Mindig 60 másodperc után jön vissza ez a hibaüzenet:
504 Gateway Time-out
The server didn't respond in time.

A kérdésem az lenne, hogy nálunk lehet-e a hiba?  Esetleg valami ötlet hogy mi okozhatja ezt a hibát, hogy ha nálunk van a hiba? Vagy tényleg a szervernél lesz a gond?
Köszönöm!

Üdvözlettel,
Tamás

**Comment by omachtandras** [comment]
Ilyen problémák tegnap biztosan voltak az élesen, nálunk is látszódtak a logokban. De ez nem újdonság már többször előfordult, teszten és élesen is.

**Comment by EPluribusUnum** [comment]
Ez NAV oldali hiba. Nem csak számla letöltésnél jöhet, hanem bármelyik függvényhívásra teszt és éles rendszeren is. Fel kell készülni arra a kliensnek hogy nem xml válasz jön vissza. Nekünk már 2018 őszén be lett építve, mert relatíve gyakran jelentkezett a  Gateway Time-out.

**Comment by NTCA-supporter** [comment]
Szia @ntamas91 !
Az éles és teszt rendszer összehasonlítása performancia szompontból teljesen irreleváns, mivel a terhelés és ezzel együtt a számlamennyiség között több nagyságrend eltérés van.
Az egy perces timeoutot szerintem hálózati eszköz beállítás okozza, ami security okok miatt van így, és feltehetőéleg nem is fog változni.
Sajnos a terhelés függvényében ezek szerint előfordul(na) nagyobb válaszidő.
Egyébként a 80-90 másodpercet hogy tudtad számolni, ha 60mp után timeoutot kapsz?
Annyit segíts kérlek, hogy vevő vagy eladó oldalról kérdezted le az intervallumot?
Igyekszünk ezeken a combosabb lekérdezéseken faragni folyamatosan, viszont 100%-ig sosem lesz garantált a 60sec-en belüli válaszidő. Tegnap például volt olyan időszak, amikor extrém magas volt a DB terhelés.

Köszi

**Comment by ntamas91** [comment]
Szia @NTCA-supporter !

Először is köszönöm a gyors válaszokat mindenkinek! 
Az időt onnan tudom hogy volt alkalom amikor még lefutott, legutoljára múlthét pénteken délután. 
Azóta viszont egyszer sem sikerült, minden esetben timeout.
Vevői/INBOUND számlák lekérésről van szó.
Nem tudom segít-e de az időintervallumot nem nézve nem egy combos lekérdezés mert 63 db számlát kellene vissza adnia.
Ki próbáltam úgy is hogy múlt hónapot kérdezze le ahol is 13 db számla van, ugyan ez az eredmény.
Viszont ha le redukálom az idő intervallumot pl 4-5 napra akkor gond nélkül lefut.

Köszi!

**Comment by rgform** [comment]
Sziasztok! 

Egy kiegészítés a témához a saját tapasztalatok alapján. T. NTCA-Supporter, véleményem szerint nem a leterheltség oldaláról kellene a problémát elsődlegesen megközelíteni. Az én esetemben az adott képernyőn egyaránt kérhető digestlist számla kelte és insdate szerint. Számla kelte szerint a havi (kb 500 darab számlás) intervallumra MINDEN ESETBEN érkezik választ,  az insdate lekérés már 7-8 napos intervallum esetében is elvérzik, annál szükebb estében lassan, de leszedi..  Visszaváltva számla keltére ugrik mint bolha...

![navinbound1](https://user-images.githubusercontent.com/6500348/89648149-0dcb4580-d8bf-11ea-9d88-c91916a529d9.jpg)

![navinbound2](https://user-images.githubusercontent.com/6500348/89648167-1885da80-d8bf-11ea-8780-a986cfc96d35.jpg)

Üdvözlettel, PPSOFT

**Comment by csandazoltan** [comment]
1 napot szeretnék queryInvoiceDigest-el lekérni és 504-es timeout-ot kapok.
queryServiceMetrics, reggel 8 óta nem jegyzi az értékeket

**Comment by laladisc** [comment]
Csatlakotznék. Ha insDate-el akarom lekérni a digestet 504-es timeout. Ha invoiceIssueDate-el, azonnal jönnek az adatok.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Elnézést a lassabb reakcióért. Ahogy fentebb írtam, a 60 másodperces timeout security okok miatt van (NAV határvédelem), amin változtatás nem lesz.
Így ugye adódik, hogy a DB lekérdezésen kell javítanunk, hogy mindig beleférjünk ebbe a limitbe. 
A változó számosság és sok egyéb dolog miatt az indexelést karban kell tartanunk. Utánanéztünk a jelzett problémának, a 2.11-es verzióban fogjuk kiadni a javítást, ami remélhetőleg minden esetben beviszi 60 mp alá a lekérdezést.
Köszönjük a jelzést, és ezt a jövőben is várjuk tőletek.

Ha gondoljátok maradhat nyitva az issue a javítás élesre kerüléséig, de mivel további teendőt nem látok, akár zárható is.

Üdv

**Comment by csandazoltan** [comment]
@NTCA-supporter A teszt rendszeren már látok 2.11-et, de nem látok a változások között olyat ami ezzel foglalkozik.
A problélma továbbra is fenn áll, ha nem tud a szerer 60mp-en belül válaszolni akkor 504-es hiba

**Comment by NTCA-supporter** [comment]
Sziasztok!

Tegnap este kikerült élesre is az új verzió.
Kérlek jelezzetek majd vissza, hogy milyen változásokat tapasztaltok.

Köszönöm

**Comment by csandazoltan** [comment]
@NTCA-supporter 
Cégünk digest-jét próbáljuk lekérni 28-ra, invoiceissuedate alapján. Lehet a digest először csak 100-at vissza, de az egész adathalmaz, több ezer számlát tartalmaz.
Gondolom végig kell rajta mennie szervernek, hogy a lehetséges oldalak számát visszaadja

Még mindig 1 perc után 504, gateway timeout

**Comment by NTCA-supporter** [comment]
Szia @csandazoltan !
Ennek nem örülök túlzottan :( Küldj kérlek egy requestId-t, hogy rá tudjanak nézni az illetékesek. 
Köszi

**Comment by csandazoltan** [comment]
@NTCA-supporter 

Kétszer lefuttattam, kétszer timeout:
15989480663611293257723696607
15989481966196996841924451339

**Comment by rgform** [comment]
Üdv!

Nekem most működik:

![navinbound3](https://user-images.githubusercontent.com/6500348/91836548-37238b00-ec4b-11ea-84bd-e2574c71d70b.jpg)

Üdv, PPSOFT

**Comment by csandazoltan** [comment]
Most éppen jó, 14 lap a mienk.
Holnap délelőtt is megnézem "csúcsidőben"

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ez még aktuális probléma?
Ha nem akkor zárjátok kérlek.

Köszi

**Comment by ntamas91** [comment]
Köszönjük a javítást!
Nekem ugyan még nem volt alkalmam tesztelni, de mivel a többiek nem jeleztek gondot, ezért szerintem nálunk se lesz probléma a dologgal!

**Comment by csandazoltan** [comment]
Nem volt mostanában baj vele... mondjuk most teljesen le van állítva, úgyhogy....

**Comment by NTCA-supporter** [comment]
UPDATE:  A szolgáltatás korlátozásat 2020.10.16-án 08 óra 55 perckor feloldottuk.
