### ISSUE TITLE
[Q&A]helyesbítő számla

### ISSUE THREAD

**Issue by Anddio80** [nav-gov-hu/Online-Invoice#33]
Az invoiceReference csomópontból törlésre kerül a modificationIssueDate, a modificationTimestamp és a lastModificationReference. A törlendők közül a modificationIssueDate fogalmilag összevonásra kerül az invoiceIssueDate taggel, így az a 2.0-tól a számla VAGY a módosító okirat kiállítását jelenti. A többi törölt taget a 2.0-ban nem kell küldeni. Új elemként megjelenik a modificationIndex, amelyben a kliens oldalnak kell a módosítás sorrendiségét jelezni. A tag értéke 1-től kezdődik, logikailag az első módosító vagy stornó számlának kell az 1-es értéket kapnia. A szerver oldalon az egyediség vizsgálatra biztosan ERROR kerül bevezetésre, a sorfolytonosság ellenőrzésének lehetőségét még vizsgáljuk. Amennyiben megvalósításra kerül a sorfolytonosság ellenőrzése is, úgy elképzelhető, hogy a szerver oldali feldolgozásba késleltetés kerül be, ekkor - feltéve, hogy az alapszámla már beérkezett a rendszerbe-, adott időkeret állna rendelkezésre az egyes módosító okirat adatszolgáltatására, és a sorfolytonosság csak a késleltetési idő leteltét követően kerülne vizsgálatra. A modificationIndex a /queryInvoiceDigest válaszában visszaadásra kerül arra az esetre, ha az alapbizonylatra több módosító okiratot állítottak volna ki eltérő számlázó rendszerekből, és a módosításkor nem ismert a helyes következő érték.”

Ezzel a változással a tétel szintű /invoiceLines/line/lineModificationReference/lineNumberReference is értelmét veszti? Vagy ezt továbbra is tölteni kell sorfolytonosan a módosító számlákban?

**Comment by NTCA-developer** [comment]
Szia!

A modificationIndex és a lineNumberReference  nem homogén fogalmak. Előbbi arra szolgál, hogy az egyes módosító/stornó számlákat jól lehessen sorrendezni, utóbbi (lineNumberReference) pedig adott módosító vagy stornó számlán belül, az ott szereplő számlasor logikai kapcsolatát mutatja meg az alapszámla hivatkozott számlasorával.

A lineNumberReference tehát megmarad a 2.0-ban.

Majd kérlek zárd le a ticketet, ha nincs több kérdésed.

**Comment by kabelnet2** [comment]
Honnan kell indítani a modificationIndex-et? Amikortól a V2 elindul, a 2018-as indulástól, vagy az eredeti számla kiállításától (ahol lehetséges, hogy egyes módosítások még az online rendszer előtt keletkeztek)?

**Comment by hamvasgy** [comment]
Abban az esetben, ha az eredeti számlát nem kellet beküldeni a NAV-hoz (mert 100eFT alatt volt az áfa) majd az első módosító számlát sem kellett beküldeni, de a második módosító számlát már be kell küldeni, akkor ennek a második módosító számla modificationIndex-ének milyen értéket kell adni? 1, vagy 2 ?

**Comment by NTCA-developer** [comment]
Sziasztok!

Örülök a kérdéseteknek.

A modificationIndex a számlalánc hosszát fejezi ki, tehát az első módosítás kapja az 1-es értéket. A tag elsődlegesen egyediség vizsgálatra lesz használva, tehát semmi baj nincs, ha mondjuk az 5-ös értékkel fogod kezdeni az adatszolgáltatást, mert akkor csak azt mondod, hogy a számlának volt már 4 korábbi, adatszolgáltatáson kívüli módosítása.

Ez remélem válasz mindkét kérdésre.

**Comment by hamvasgy** [comment]
Milyen sorszámot kapjon a 'modificationIndex', ha az eredeti számla más rendszerben lett kiállítva, de nem lett beküldve a NAV-hoz, és az ott készült módosítók sem voltak beküldve? Ilyenkor sem a NAV, sem az aktuális módosító számlát kiállító nem ismeri a tényleges módosító számlák db. számát.

**Comment by NTCA-developer** [comment]
Szia @hamvasgy 

Nem akarok az adójogi és pénzügyi jogi jogászok vadászterületére tévedni, de nehezen tudom elképzelni a magam részéről azt az esetet, hogy például a számviteli törvény engedné azt a fajta negligenciát, hogy egy adózónak nem kell tisztában lennie azzal, hogy adott saját gazdasági eseményéről hány okirat készült.

A véleményem tehát az, hogy ezt az információt a számla kiállítását megelőzően tudni kell, erre a belső workflow-nak meg kell lennie.

**Comment by hamvasgy** [comment]
Nos, én informatikus vagyok, s csak annyit tudok, hogy ilyen eset leginkább akkor fordul(t) elő a Magyar Telekom és a T-Systems életében, amikor megvásároltak és beolvasztottak cégeket - nem tudom, erre mit ír a számviteli törvény. Mindenesetre továbbítom az elvárást az illetékesek felé.

**Comment by NTCA-developer** [comment]
Lezárom a ticketet, ha merül fel új kérdés nyugodtan vegyetek fel újat.

**Comment by szako** [comment]
> Sziasztok!
> 
> Örülök a kérdéseteknek.
> 
> A modificationIndex a számlalánc hosszát fejezi ki, tehát az első módosítás kapja az 1-es értéket. A tag elsődlegesen egyediség vizsgálatra lesz használva, tehát semmi baj nincs, ha mondjuk az 5-ös értékkel fogod kezdeni az adatszolgáltatást, mert akkor csak azt mondod, hogy a számlának volt már 4 korábbi, adatszolgáltatáson kívüli módosítása.
> 
> Ez remélem válasz mindkét kérdésre.

Javaslom, hogy ezt írjátok le a dokumentációba, mint javsolt gyakorlat, mert nálam is felmerült kérdésként és sajnos csak a dokumentáció átolvasása, példa XML-ek megnézésa, majd issue megírása és majdnem elküldése előtt olvastam el. (similar issues átnézés még mindig nem ujjgyakorlat)

**Comment by NTCA-developer** [comment]
Szia @szako 

Az interfész dokumentáció 2.2.1 pontja jelenleg ezt tartalmazza a modificationIndexről, ezt láttad?

> A modificationIndex egyedi módon a módosítás sorrendiségét írja le a kiállító oldalán. Logikailag a számla első alkalommal történő módosításáról modificationIndex = 1 értékkel kell adatot szolgáltatni. Minden további módosítás esetén az elemben meg kell jelölni, hogy a módosító okiratról szóló adatszolgáltatás a számla hanyadik módosítása. A modificationIndex értékét a rendszer a módosító okiratok egyediség vizsgálatára használja fel, kétszer azonos modificationIndex értékkel nem lehet adatot szolgáltatni. Sorrendiség ellenőrzést a rendszer a modificationIndex alapján nem végez.
Az egyediség vizsgálat azt is jelenti, hogy a korábbi verziójú (1.0, 1.1) és módosító vagy stornó adatszolgáltatások (ahol a modificationIndex még nem szerepelt) kiesnek az egyediség vizsgálatból. A rendszer nem vélelmez a korábbi módosító vagy stornó számlák között és az új 2.0-ás módosító és stornó számlák között sorrendiséget, azonban a logikailag inkonszisztens módosítások (pl: a számlának már van 3 korábbi 1.x-es módosítása a rendszerben, és érkezik egy 2.0-ás módosítás, ahol a modificationIndex értéke 1) a kockázatkezelő rendszer bemeneti adataként szolgálhatnak.

Ha igen, akkor mi volt az ami még hiányzik?

**Comment by szako** [comment]
Igen, erre gondoltam. 

Igazából sokszor elolvasva a szöveget az első mondatban mégis lehet, hogy benne van a válasz a kérdésemre, de lehet csak belelátom (_kiállító oldal_).
