### ISSUE TITLE
[Q&A] Mégsem kell minden áfalany részére kiállított számláról adatot szolgáltatni?

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#330]
Újabb NAV-PM közlemény jelent meg a NAV honlapján:
[https://www.nav.gov.hu/nav/ado/afa/Gyakran_ismetelt_kerd20200728.html](url)
Igazi gyöngyszemek bukkantak fel benne , olyan új fogalmak, amelyen sokan el fognak hasalni.

"Nem esik ezért online számlaadat-szolgáltatási kötelezettség alá a közszolgáltatóként végzett adómentes humán-egészségügyi tevékenység bizonylata, mivel ezen ügylet tekintetében az adóalany egyéb számviteli bizonylat kibocsátásával mentesül a számlaadási kötelezettség alól. **Ez akkor is így van, ha az előzőek ellenére mégis olyan bizonylatolási gyakorlatot folytat, hogy saját döntéséből fakadóan számlát állít ki számviteli bizonylatként.**
Ugyanakkor e számviteli bizonylatokat egyértelműen és utólag bizonyítható módon el kell különíteni az olyan számláktól, amelyek esetében az adóalany nem mentesül a számlakibocsátási kötelezettség alól, azaz amelyek tekintetében számlaadat-szolgáltatásra kötelezett. "
Tehát a számláról sem kell adatot szolgáltatni, ha ránézésre számlának látszik ugyan, de **utólag** belemagyarázható az, hogy az csak számviteli bizonylat szerepet tölti be. Miközben a számla maga is számviteli bizonylatnak számít. 
Bevezetésre került ezzel a "bizonylat szerepe" kategória.
Számlázni lehet számlakiállítási kötelezettséggel, és anélkül, de a magánszemély kérésére kiállított számla nem minősül a törvény alapján teljesített számlázási kötelezettségnek, valamint lehet nyugta helyett számlát kiállítani, lehet a számla igazából számviteli bizonylat szerepű, de lehet "számla" valójában módosító okirat szerepű is, és az "érvénytelenítő számla" az igazából egyfajta "módosító okirat" szerepű, amely valójában számviteli bizonylat, de mégsem abban az értelemben számviteli bizonylat, ahogyan sokszor speciális, leszűkített értelmében használják. 
Hurrá.

**Comment by Macskafarka** [comment]
A kérdés lemaradt: Be kell-e vezetni a "Bizonylat szerepe" mezőt a számlaadat szolgáltatásban?

**Comment by celeburdi** [comment]
Mondjuk a NAV Online Számlázóban létrehozunk egy új számlatömböt.
Ebből a "speciális"  nem számlának minősített számlatömbből állítjuk ki az ilyen számlákat.
Biztosított az elkülönítés.
A NAV Számlázó ezeket a "nem számlákat" is feladja. (ha a vevő belföldi adóalany)
Helyes ez így, vagy be kellene vezetni a 'számlatömb típus' minősítést?



Nem lehet a számlatömböket szerep szerint minősíteni.
Ezeket is feladja a rendszer.

**Comment by Macskafarka** [comment]
A NAV Online számlázó jogilag elég necces dolog, mert nem tudod rajta számon kérni azokat, amelyeket a NAV-PM elvár.
Működik, ahogy működik, és sajnos az ügyfelektől hivatkozási alap lehet az üzleti szoftevereket fejlesztők felé, hogy olyan működést várnak el, amelyet az végez.
Egyszerűen ki kell azt mondani, hogy az üzleti számlázó programokra vonatkozó előírások NEM kötik a NAV számlázóját és az azt használók mentesülnek az egyéb szoftvereket használókra vonatkozó szankciók alól.

**Comment by NTCA-developer** [comment]
<OFF>
A számlázó ÁSZF-jében benne van, hogy ő mindenről szolgáltat adatot. Ehhez joga van, ahogy más piaci szolgáltatónak is meglenne ugyan ez a döntési lehetősége. Kifejezetten demagóg dolog belemagyarázni, hogy más szabályok vonatkoznak rá, mint a többi szoftverre. Két teljesen külön dolog, hogy miről kell és miről lehet adatot szolgáltatni. Az elkülönítésre elég sok lehetőséget látok a gyakorlatban, akár additional elemként ráteszed az adatszolgáltatásra, akár külön számlatömbből csinálod, ahogy @celeburdi is javasolta, mindkettő jó lehet. (logikailag, aztán hogy adószakmailag mi a magas mágia arról majd nyilatkoznak az illetékesek)
</OFF>

**Comment by NTCA-tax** [comment]
Az áfa törvény - igaz nem túl hosszasan - felsorol olyan eseteket, amikor az értékesítő mentesül a számlakiállítási kötelezettsége alól. Mivel a számlaadat-szolgáltatás kizárólag azon számlák esetében értelmezhető, amikor az áfa törvény ír elő számlakiállítási kötelezettséget, ezért @Macskafarka által írt esetben nem beszélhetünk adatszolgáltatási kötelezettségről. Amennyiben tárgyi mentes az értékesítés, és az áfa törvény nem ír elő számlakiállítási kötelezettséget, akkor az értékesítő mentesül a számlakiállítási kötelezettsége alól. Ilyen esetekben nem megkövetelhető az áfa törvény 169. §-nak a tartalmi követelményei sem, mivel itt a számviteli törvény 167. §-nak kell megfelelnie a bizonylatnak. Persze ez nem zárja ki, hogy az áfa törvénynek is megfelel a bizonylat, de nem szükségszerűen van ez így.

**Comment by Macskafarka** [comment]
Megkaptam  a választ, lezárom
