### ISSUE TITLE
queryInvoiceChainDigest response XML probléma

### ISSUE THREAD

**Issue by rgform** [nav-gov-hu/Online-Invoice#331]
Jellemzően módosító számláknál, illetve többszörös módosításnál és/vagy már módosított számla érvénytelenítésénél - kiemelten ha éveken átnyúló módosítás van - nehéz a teljes hivatkozási lánc tételszámának kalkulálása.  Ezért erre nem a saját (éves periódusú) adatbázis adatait, hanem a  queryInvoiceChaindigest által visszaadott adatokat használnánk fel.  Első elképzelés szerint az upperbound invoicelines elem, lineNumberIntervalEndelemét használtuk fel. Természetesen minden módosítást és érvénytelenítést CREATE végzünk, így annak monoton növekvőnek kell lennie.  Alapvetően jól működik, de belefutottunk egy számla elutasításba.  Egy 74 tételt tartalmazó számla jellemzően?!  az alábbi módon jön vissza, így a kalkuláció hibás lesz.   Bár volt olyan eset hogy helyesen jelent meg.

      <invoiceLines>
        <maxLineNumber>74</maxLineNumber>
        <newCreatedLines>
          <lineNumberIntervalStart>1</lineNumberIntervalStart>
          <lineNumberIntervalEnd>44</lineNumberIntervalEnd>
        </newCreatedLines>
        <newCreatedLines>
          <lineNumberIntervalStart>48</lineNumberIntervalStart>
          <lineNumberIntervalEnd>48</lineNumberIntervalEnd>
        </newCreatedLines>
        <newCreatedLines>
          <lineNumberIntervalStart>45</lineNumberIntervalStart>
          <lineNumberIntervalEnd>47</lineNumberIntervalEnd>
        </newCreatedLines>
        <newCreatedLines>
          <lineNumberIntervalStart>49</lineNumberIntervalStart>
          <lineNumberIntervalEnd>66</lineNumberIntervalEnd>
        </newCreatedLines>
        <newCreatedLines>
          <lineNumberIntervalStart>70</lineNumberIntervalStart>
          <lineNumberIntervalEnd>70</lineNumberIntervalEnd>
        </newCreatedLines>
        <newCreatedLines>
          <lineNumberIntervalStart>67</lineNumberIntervalStart>
          <lineNumberIntervalEnd>69</lineNumberIntervalEnd>
        </newCreatedLines>
        <newCreatedLines>
          <lineNumberIntervalStart>71</lineNumberIntervalStart>
          <lineNumberIntervalEnd>74</lineNumberIntervalEnd>
        </newCreatedLines>
      </invoiceLines>

Kérdés: ez üzemszerű állapot? Mert abban az esetben át kell dolgoznunk pl. a maxLinenumber elemek szummázatára?
Hangsúlyozzuk volt lekérdezés amiben helyesen jelent meg.

        <newCreatedLines>
          <lineNumberIntervalStart>1</lineNumberIntervalStart>
          <lineNumberIntervalEnd>74</lineNumberIntervalEnd>
        </newCreatedLines>
 
Üdvözlettel, PPSOFT

**Comment by NTCA-supporter** [comment]
Szia @rgform !
Utánanézek kicsit pontosabban. Tehát jól értem, hogy van hogy egy newCreatedLines csomópont szerepel a válaszbna, és van hogy több, ugyanazon számla esetén?
Köszi

**Comment by rgform** [comment]
Igen. Egy darab (72 tételes) számla estében nem egy darab 1 - 72 intervallumot kapok vissza, hanem az ábrázolt több - nem is sor folytonos -részekre tördeltet.   Amennyiben konkrét bizonylatszám, tranzakció ID, stb. kell azok naplózva vannak...

**Comment by rgform** [comment]
Többször megismételve a lekérdezést pl.

jwuBTvzh40WqybM0rgzdMQ  jó RequestID
Hwy5Y6VDkUm4XhS8PgzSqA  rossz RequestID

Az első válasz jó volt, a második pedig rossz (tördelt).

Üdvözlettel, PPSOFT

**Comment by NTCA-supporter** [comment]
Szia @rgform !
A hiba sajnos nálunk van, bár annyira talán nem kritikus :) 
A CREATE alapszámláknál elvileg nem is kellene visszaadnunk a newCreatedLines csomópontokat, csak a maxLineNumbert, hiszen ott egyértelmű, hogy 1..maxLineNumber lesz az intervallum.
Viszont mégis visszaadjuk, és az alapszámlánál az elejéről hiányzik a rendezés, ezért a sorrend attól függ, hogy a DB éppen hogy adja vissza. Ha sorban, akkor ugye pont jó lesz, ha pedig nem, akkor képezzük a több intervallumot.
Ezt javítjuk mindenképp. Azt, hogy alapszámla esetén egyáltalán ne adjuk vissza az intervallumot még átgondolom.
Maradhat nyitva az issue, jelzek majd, ha megvan, hogy melyik verzióban javítjuk.

Köszi a jelzést!

**Comment by rgform** [comment]
Köszönöm a gyors választ. Amennyiben alapszámlánál nem kerül majd visszaadásara az intervallum, akkor sajnos át kell alakítanunk a számoló rutint, hiszen akkor nem lesz lineNumberIntervalEnd eleme az még nem módosított számláknak,  és a maxLinenumber értékével kell dolgoznunk. Viszont ha már módosították, akkor meg a  legutolsó lineNumberIntervalEnd fogja tartalmazni az eddig beküldött tételek számát.    Vagy ciklusban összeadjuk az összes maxLinenumber értékét.  Mindenképpen dolgoznunk kell vele, hogy biztosra menjünk. 

Üdvözlettel, PPSOFT

**Comment by NTCA-supporter** [comment]
Szia @rgform !
A 2.12 verzió fogja tartalmazni a javítást. A működés az interfész dokumentációnak megfelelő lesz.
Zárom az issuet, ha van még kérdés nyisd újra.

Köszi mégegyszer a jelzést!
Üdv

**Comment by rgform** [comment]
A probléma újra fellépett, csak még súlyosabb.
