### ISSUE TITLE
[Q&A] Egy Token-t nem lehet felhasználni több számla beküldéséhez? 

### ISSUE THREAD

**Issue by robozb** [nav-gov-hu/Online-Invoice#332]
Egy token-t nem lehet felhasználni több számla beküldéséhez, a token érvényességi idején belül? 

Nem lehet ugyanazzal a tokennel több ManageInvoiceRequest-et kezdeményezni?

Köszi!

**Comment by connorhu** [comment]
Dokumentáció szerint a token:
"Adatszolgáltatás teljesítéséhez használatos **egyszeri** jegy."

tokenExchange endpoint leírása:
"/tokenExchange: a számlaadat-szolgáltatás és a technikai érvénytelenítés beküldését
megelőző **egyszer** használatos adatszolgáltatási token kiadását végző operáció"

Szerintem nem.

**Comment by NTCA-supporter** [comment]
Szia @robozb !
Az előttem szóló összefoglalta a lényeget.
Ha nincs több kérdés, kérlek zárd az issuet.
Köszi

**Comment by robozb** [comment]
> Dokumentáció szerint a token:
> "Adatszolgáltatás teljesítéséhez használatos **egyszeri** jegy."
> 
> tokenExchange endpoint leírása:
> "/tokenExchange: a számlaadat-szolgáltatás és a technikai érvénytelenítés beküldését
> megelőző **egyszer** használatos adatszolgáltatási token kiadását végző operáció"
> 
> Szerintem nem lehet több requestet kezdeményezni, viszont kötegelten küldheted be max 100 számláig.

Koszonom!
