### ISSUE TITLE
queryInvoiceDigest érvénytelen számla

### ISSUE THREAD

**Issue by csandazoltan** [nav-gov-hu/Online-Invoice#333]
A queryinvoicedigest megjelenít technikailag érvénytelenített számlákat?

A következőt vettük észre:
17782098-as adószámú cég állított ki nekünk számlát (INBOUND számla) 11099286 adószámra 02-04 invoiceissuedate-el
513888 számlaszámot kapott.

A queryInvoiceDigest 2 számlát mutat arra a napra, ugyanazzal a 513888 számlaszámmal
Tranzakció azonosítók:
2UTOAN7K976X3FY2 - insDate 2020-02-04
2UV5VQBH7LOPAUFC - insDate 2020-02-05
![image](https://user-images.githubusercontent.com/6756505/89160727-d0d71a00-d571-11ea-9ee9-588917263378.png)
![image](https://user-images.githubusercontent.com/6756505/89160747-d7659180-d571-11ea-9935-8351411bf23d.png)

Feltételezzük technikai érvénytelenítés és újrabeküldés volt

queryInvoiceData-val lekérve pontosan az adott számla részletes adatait.
invoicedirection INBOUND 
suppliertaxnumber 17782098
invoicenumber 513888 

Az eredmény a 02-05-ös beküldés adatai lettek
![image](https://user-images.githubusercontent.com/6756505/89160983-3c20ec00-d572-11ea-9266-05431cd27e17.png)

A problémánk az, hogy első körben a digest-et kérdezzük le és abból dolgozva kérjük a részletes adatokat, ellenőrzés céljából.
Kétszer szerepel a számla 2 különböző tranzakció azonosítóval.
Ez így rendben van, hogy láthatóak ezek a duplikálások és nekünk kell ezt kezelni, összehasonlítva a számla részletes adatait a digest-el, vagy nem kellene látszódni a digestben ennek a tranzakcióazonosítónak: 2UTOAN7K976X3FY2 

Válaszukat előre is köszönjük!

**Comment by NTCA-supporter** [comment]
Szia @csandazoltan !
Erre globálisan figyelünk, hogy ami technikai érvénytelenítve lett számla, azt sosem adjuk vissza, azt úgy kezeljük mintha meg sem történt volna.
Első körben azt nézd meg kérlek, hogy az invoice_number-ben nincs-e whitespace karakter valamelyik számla esetén?!
A tippem egy jó tipp lesz, de hivatalosan éles adatokkal/id-kkal ezen a fórumon nem foglalkozunk, csak mint info :)
Szóval a feldolgozás oldalon kellene nézni, hogy mindig az eredeti, visszaadott invoice_numbert tárold/kezeld.

Üdv

**Comment by csandazoltan** [comment]
Szia @NTCA-supporter 

Akkor papíron nem szerepel a digest-ben technikailag érvénytelenített számla?


Nem látok whitespace-t, xml adatokat nem trimmelek sehol:

![image](https://user-images.githubusercontent.com/6756505/89165489-ee5bb200-d578-11ea-9527-f1f718f444d4.png)
![image](https://user-images.githubusercontent.com/6756505/89165561-03d0dc00-d579-11ea-8e0b-b0d9846ee1c6.png)

**Comment by NTCA-supporter** [comment]
Szia @csandazoltan!
Nem csak papíron, a valóságban sem :) 
Az eredeti XML-t, amit visszaadunk, meg tudod nézni? Én most tesztrendszeren megpróbáltam tab és szóközzel is, a válaszban helyesen ott volt a whitespace is: <invoiceNumber>digest	</invoiceNumber>

Köszi

**Comment by csandazoltan** [comment]
Szia @NTCA-supporter!

Igen igazad van, vannak karakterek. SimpleXMLLoad ezeket akkor csak eldobja. Módosítjuk a programot
![image](https://user-images.githubusercontent.com/6756505/89174371-0980ee80-d586-11ea-92ef-e68263444cd2.png)

---

Idevágó kérdés, le lehet valahogy kérdezni a technikai érvénytelenített számlák listáját?
pl.: szeretnénk tudni, hogy nkeünk küldött számlák között volt e valami érvénytelenítés

**Comment by NTCA-supporter** [comment]
Szia @csandazoltan !
Akkor megvan a hiba.
A technikai érvénytelenítetteket nem tudod lekérdezni, ahogy írtam, ezt mi úgy tekintjük mintha soha nem léteztek volna. 
Ha egy lekérdezés eredményében többé nem szerepel egy számla, akkor az jelenti azt, hogy technikai érvénytelenítve lett.
Üdv

**Comment by csandazoltan** [comment]
Köszönöm a segítséget!

Az Issue-t zártam
