### ISSUE TITLE
Várható-e, hogy eltünnek a korábbi PM-NAV közlemények

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#334]
2020.07.28-án az adatszolgáltatással kapcsolatban közzétett PM-NAV közös közleményt váratlanul megmásították!
Itt volt: [https://www.nav.gov.hu/nav/ado/afa/Gyakran_ismetelt_kerd20200728.html](url)
Most ugyanezen a helyen és címen egy hasonló szöveg szerepel, melynek 2020.08.04-i a dátuma.
**Ez abszurdum!**
Lefejlesztjük, kiadnánk a verziót, erre váratlanul eltűnik a korábbi szövegváltozat!
Képtelenség megkeresni azt, hogy mi változott benne! 
Utalnék arra, hogy több olyan működési elvárás is van az adatszolgáltatással kapcsolatban, amelyet az ÁFA törvény nem ír elő,
csak és kizárólag a PM-NAV közös közleményekben szerepel.
Gondolok is a xx65M lap kitöltésére.
Hogyan lehet így felelősséggel fejleszteni?

**Comment by Macskafarka** [comment]
Korábban az adott címen ez volt: [•	[NAV KI Ügyfélkapcsolati és Tájékoztatási Főosztály: ÜTF-3685/2020 -Pénzügyminisztérium Fogyasztási és Forgalmi Adók Főosztály: PM/14290/2020.] ](url)

**Most az közlemény eltűnt és egy másik van UGYANOTT:** 
[[Pénzügyminisztérium PM/12861-1/2020. – Nemzeti Adó- és Vámhivatal Központi Irányítás 2475546404/2020.]](url)
Ha valami tarthatatlan, akkor azt NYILVÁNOSAN kell visszavonni, időt hagyva arra, hogy aki elhitte az abban leírtakat, az korrigálni tudja a folyamatait!

**Comment by Macskafarka** [comment]
Tévedtem, ugyanaz a száma, csak más a dátuma és ismeretlen a korábbi szövege.

**Comment by Macskafarka** [comment]
Összeolvastam a két szöveget, és bizony más szöveg szerepel bennük!
Hogyan várható el az adóalanyoktól, az, hogy valaki ne másítsa meg a számla adattartalmát, és ne cseréje ki -nyom nélkül- a tartalom egyes részeit, ha a PM-NAV közös közleményekkel ez megtörténik?
**A kérdésem: melyik a valótlan szövege ennek a közleménynek a kettő közül?**  [NAV KI Ügyfélkapcsolati és Tájékoztatási Főosztály: ÜTF-3685/2020 -Pénzügyminisztérium Fogyasztási és Forgalmi Adók Főosztály: PM/14290/2020.] 
Kérem tegyék közzé egyidejűleg egy helyen  a létező összes szövegváltozatot! Azokat is, amelyeket csak később akarnak megjelentetni.

**Comment by fzoli15** [comment]
Tudomásom szerint ezek a tájékoztatók, GYIK segédletek, tájékoztató füzetek nem kötelezik a NAV-ot semmire, akár ezeknek ellentmondó határozatokat is hozhatnak egy-egy eljárás során. Elméletileg azért adják ki ezeket, hogy segítsék az adózókat a jogszabályok értelmezésében, és ezáltal az előírások betartásában. 
Csakhogy többször előfordult már a múltban, és a jövőben is lesz ilyen, hogy nekik sem sikerült megfelelően értelmezni a jogszabályokat bizonyos esetekben (nyilván ehhez a jogszabályok tökéletlensége is hozzájárul), így félrevezető vagy egymásnak ellentmondó információkat adtak ki ezekben a tájékoztatókban. 
Több esetben előfordult már ilyen, hogy nyom nélkül törölték a korábbi, ellentétes tartalmú tájékoztató szövegét.

Ilyen kérdés volt pl., hogy lehet-e egyszerre online pénztárgépes nyugtát és számlát is kiállítani ugyanarról a kp-s értékesítésről. A jogszabályi előírások szerinte ez egyértelműen szabálytalan. A NAV először azt mondta, hogy nem szabályos, majd mégis szabályosnak tekintették, és jelenleg (az általad is linkelt GYIK-ben) ismét szabálytalannak minősítették. 
Egy érdekes cikk erről 2014-ből: https://www.armacash.hu/hirolvas.php?id=168

Emiatt én egyáltalán nem bízom ezekben a tájékoztatókban, nem érdemes a program működését ezekre alapozni.
Nem tudom, hogy jelen esetben mi módosult, vagy nem módosult ebben a GYIK-ben, de mi csak és kizárólag a törvényben leírtakat tekintjük hitelesnek (ez vonatkozik a végszámlák xx65M-es jelentésére is).

**Comment by Macskafarka** [comment]
Csakhogy ezek közokiratok. 
Olyan elvárások vannak benne megfogalmazva, amelyek az Áfa törvényben nincsenek.  Pl. az. hogy a xx65M-02 lapra nem kell betenni a számlát akkor, ha az érvénytelenítője megérkezett a bevallásig a számlabefogadóhoz. Vagy pl. az, hogy a végszámlát 2 db sorban kell bevallani az xx65M-02 lapon.
Ezeket lehet nem figyelembe venni???? 
Ne beszéljünk itt egy számla hash-ről, amikor az alapokat, amelyek közokiratban megjelennek, megmásítják!
Ha figyelmen kívül kell hagyni ezeket a PM-NAV közleményeket, akkor itt a GitHub-on nincs értelme semmiről sem beszélni, mert ami választ kapunk az mind nem számít.
Nekem tetszene az, hogy ne jelenjenek meg elvárások, se struktúrák a NAV részéről, mert amire nincs jogszabály, azt nem kell betartani. 
Ez lenne a cél?

**Comment by fzoli15** [comment]
Sajnos abban egyetértünk, hogy nincs különösebb értelme itt ilyesmiről beszélni, mert itt is csak egy nem hivatalos, nem kötelező érvényű választ fogunk kapni (ha kapunk).

Hogy lehet-e figyelmen kívül hagyni a PM/NAV közleményeket, tájékoztatókat, arra azt tudom mondani, hogy szerintem igen. Ha a NAV egy eljárásban szabálytalanságot állapít meg, akkor ennek alátámasztásához jogszabályra kell hivatkoznia. Nem hivatkozhat az általa kiadott tájokoztatókra, közleményekre, kitöltési útmutatókra, GYIK oldalakra, stb-re. Remélem ezt jól tudom, és ebben megerősítenek itt.

Szabálytalanság esetén az adózó 2018. január 1-től az Art. 247. §-a szerint elméletileg hivatkozhat arra, hogy ő a NAV tájékoztatóban leírtakat követte, de adóhiány esetén az adóhiányt így is meg kell fizetnie, csak ilyen esetben bünti nem jár érte:

247. § [Jogkövetkezmények alóli mentesülés]
(1) Az adózó terhére jogkövetkezmény nem állapítható meg, ha az adózó az adóhatóság honlapján erre a célra létrehozott felületen közzétett tájékoztatójában meghatározottak szerint járt el.
(2) Az adóhiány megfizetése alól az adózót nem mentesíti, hogy az (1) bekezdésben meghatározottak szerint járt el.

Az xx65M adatszolgáltatás szabálytalansága esetén nem beszélhetünk adóhiányról, ezért itt az Art. 247. § jó kibúvó lehet a büntetés alól, ha a tájékoztatókban leírtakat követed 100%-osan. De amíg ezek az "aktuális széljárás" függvényében változhatnak, addig a gyakorlatban én erre nem alapoznék.

**Comment by Macskafarka** [comment]
@fzoli15 Értem, amit írsz, csak a programot az ügyfeleknek készítjük, így elvárnak ezt-azt. Végülis az ügyfelekből élünk. 
Ráadásul a szoftvercég sem az enyém, tehát valamit figyelembe kell venni.
Akkor is, ha groteszk (komikusan félelmetes) az, ami történik.

**Comment by NTCA-supporter** [comment]
Szia @Macskafarka !
Értem a problémádat, viszont ennek sajnos nem itt a helye.
Kérlek a hivatalos ügyfélszolgálatot keresd ezzel kapcsolatban.
