### ISSUE TITLE
[Q&A] ÁFA összesítés számítása - INCORRECT_SUMMARY_CALCULATION_VAT_RATE_VAT_AMOUNT_HUF_SUMMARY

### ISSUE THREAD

**Issue by aszj2020** [nav-gov-hu/Online-Invoice#335]
Kedves Fejlesztők,

Az adatszolgáltatás során az alább warning üzenet érkezett az elfogadott státusz mellé: INCORRECT_SUMMARY_CALCULATION_VAT_RATE_VAT_AMOUNT_HUF_SUMMARY ami ugye az ÁFA HUF összesítésének >1% -os eltérésére figyelmeztet.

A számlázó rendszer jelenleg a számla ÁFA értékét az alábbi módon számítja:
- kiszámítja számla tételenként a nettó értékből az áfa és a bruttó értéket, a kerekítési szabályokat figyelembe véve
- összeadja a számla tételek nettó, áfa és bruttó értékeit, így számítja aki számla Nettó, áfa, bruttó összértékét
- deviza számlák esetén ugyanez az eljárás és a HUF összesítéseknél az egyes értékekre alkalmazza a szintén szolgáltatott árfolyamot a nettó, áfa, bruttó értékekre

Mivel a vonatkozó jogszabályok (23/2014. (VI. 30.) NGM rendelet, általános forgalmi adóról szóló 2007. évi CXXVII. törvény)
nem határozzák meg a számla Áfa összegének számítását.

A fentiekkel kapcsolatban alábbi kérdések merültek fel:
* Melyik a NAV által használt számla ÁFA összeg számítási módszer (tételek kerekített ÁFA-jának összeadása, vagy a nettó végösszegből számítani a kerekített ÁFA összeget)?
* Deviza számlák HUF ÁFA összesítésénél ez mennyiben módósul (hol kell alkalmazni a deviza - HUF konverziót)
* Van-e olyan jogszabály, amely előírja a számítást?
* Van-e korábban kiadott NAV állásfoglalás a kérdésben?

Előre is köszönöm a segítséget!

**Comment by gajzi** [comment]
Tisztelt fejlesztők,

Nekünk is hasonló gondjaink vannak. Sok ügyfelünknél bukkan fel kis értékű termékek devizás értékesítésénél warning a HUF értékek számításárra.
A tétel ellenőrzések szerintem nincsenek teljesen átgondolva:
-tétel mennyisége (quantity) QuantityType típusú 10 tizedesjeggyel
-tétel egységára (unitPrice) szintén
-lineNetAmount, lineNetAmountHUF, lineVatAmount, lineVatAmountHUF, lineGrossAmount, lineGrossAmountHUF mezők viszont MonetaryType típusúak, ami csak 2 tizedest enged.
Így viszont vannak olyan számlák, ahol nem tudjuk megúszni warning nélkül.
Devizás számlák esetében két lehetőségünk van a lineNetAmountHUF, lineVatAmountHUF, lineGrossAmountHUF, vagy a <quantity>*<unitPrice>* <exchangeRate>  képlettel számoljuk és az eredményt kerekítjük a megengedett 2 tizedre, vagy a lineNetAmount, lineVatAmount, lineGrossAmount már kerekített összeget szorozzuk az árfolyammal és ezután kerekítjük újra 2 tizedre. Mindkét esetben gond lehet, első esetben  „Eltérés a számla tétel eredeti pénznemben és forintban megadott bruttó értéke között.” hibát kapunk, mert a sorértékben elvesző akár 5 ezred egy 350HUF körüli EUR árfolyammal 1HUF feletti eltérést generál, második esetben pedig  „A számlasor(ok) forintban megadott nettó értéke(inek) összege eltér a számla forintban feltüntetett nettó értékétől.” hiba jön elő, hiszen soronként kerekített devizás összegből számoltuk árfolyammal felszorzással a sorok HUF értékét, így ezek összegéből nem jön ki a számla valós deviza értékének forintosított értéke.
Azt gondolom a sorértékek tizedes jegyei miatt át kellene gondolni az ellenőrzés eltérés értékeit.

Előre is köszönettel!

**Comment by gajzi** [comment]
Tisztelt illetékesek,

Ez egy lassan egy hónapos bejegyzés, ami azóta is nap mint nap WARNING választ generál az ügyfeleinknél és gondolom mindenki másnál is, aki kis értékű termékeket is számláz. Egy olvastuk kivizsgáljuk, vagy egy sajnos ezzel együtt kell élni... válaszra azért talán már megérett egy hónap alatt.

Tisztelettel várjuk bármilyen válaszukat!

**Comment by aszj2020** [comment]
Tisztelt Fejlesztők!

A fenti probléma továbbra is gondot okoz számunkra, így szeretnénk rá választ kapni.
Kérjük a jelenleg hatályos kerekítés számítást, vagy ellenőrző képletet átadni részünkre,  így legalább lehetőségünk lenne a számlázó rendszer módosításának megfontolására.

Amennyiben a kérdésre nem áll módjukban válaszolni, abban az esetben kérjük adják meg, a NAV mely részlege illetékes az ügyben.
A hozzászólásokból látható, nem csak egy számlázó rendszert érint a kérdés.

Várjuk szíves válaszukat.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Érdemes átolvasni a #217 és #311 issuekat.

A képlet nagyon egyszerű ennél a figyelmeztető üzenetnél: az adott összesítőben szereplő HUF-os nettó összeget megszorozzuk az áfakulccsal, és ha az adatszolgáltatásban megadott HUF-os áfaösszeg eltér több mint 1%-kal (és legalább 1 egységgel) a számolttól, akkor kapod a WARNING-ot.

Azt, hogy ezt mennyire kell kritikus hibának tekinteni, majd @NTCA-tax megmondja.

Üdv

**Comment by gajzi** [comment]
Sziasztok,

Azt hiszem @aszj2020 nevében is mondhatom, hogy felületesen olvastátok a levelet.
Nem az a gond, hogy a nettó*áfa nem hozza ki az áfa értéket, nekünk a devizás számlák esetében van gondunk azzal, hogy  a forintosított áfa, nettó, bruttó értékek térnek el több, mint 1HUF-fal a devizás értékekből árfolyammal felszorzott értékektől.
Egy példa: ügyfelünk eladott egy számlán többek között 10db 0,0135EUR értékben O-gyűrűt. <lineNetAmount>-ban csak 2 tizedes jegy engedélyezett, így oda 0,135EUR helyet 0,14EUR került, itt vesztettünk 5ezredet, ami felszorozva a 353,34 árfolyammal több, mint 1HUF eltérést fog okozni a valós 0,0135*10*353,34-hez képest és WARNING-ot kapunk rá. Tömegesen kapjuk az ilyen eltérésekről az üzeneteket, ami kivizsgálást igényel, az ügyfeleink és a mi részünkről is. Azt gondolom az sem megoldás, ha @NTCA-tax ezt "ne foglalkozzunk vele" hibának minősíti, mert a sok ilyen felesleges hibajelzéssel óhatatlanul be fog csúszni egyszer-egyszer egy tényleges hiba figyelmen kívül hagyása.

üdvözlettel
