### ISSUE TITLE
Adószám ellenőrzési kérés

### ISSUE THREAD

**Issue by githubbarbara** [nav-gov-hu/Online-Invoice#336]
Üdvözlöm, 
a 14517987-2-43 adószámra, vagyis ennek a törzsszámára a /queryTaxpayerResponse üzenet taxpayerValidity mezőjében true értéket kapunk, pedig az adószám lekérdező oldal szerint ez a törzsszám nem létezik https://www.nav.gov.hu/nav/multilekerdezo.
Szeretnénk pontosan érteni, hogy milyen esetekben kapunk true választ.
Köszönöm.

**Comment by topybear** [comment]
Ha ez a teszt rendszerben történt: az ottani törzs komoly lemaradásban van az éles törzshöz képest (ahogy nézem, úgy egy éve ez még élő adószám volt),

**Comment by githubbarbara** [comment]
köszönöm, közben én is ellenőriztem több szempontból.

**Comment by NTCA-supporter** [comment]
Kedves @githubbarbara 
@topybear meg is válaszolta a kérdésedet. Ha pedig éles környezetről van szó, akkor arra mi látunk rá. 
Ha nincs más kérdés akkor légyszi zárd le a ticketet.
