### ISSUE TITLE
Kisnagybetű érzékenység számlaszámnál

### ISSUE THREAD

**Issue by veerede** [nav-gov-hu/Online-Invoice#337]
Sziasztok!

A számla bizonyos elemei nagybetűsödnek feladáskor. (ezt most nem firtatom)
A számlaszám nem tartozik ebbe körbe. 
Így, egy adatszolgáltató megteheti, hogy ugyanazt a számlaszámot többször, több alakban is felküldheti. (kipróbáltam)
Pl. SZL011, Szl011, szl011
((Ha az ügyfél több számlázó rendszert használ, akkor észrevétlenül is előállhat ez az eset))

Én úgy érzem, hogy ezt nem kéne megengedni, mert zavart okozhat (számomra befogadó oldalon).
Továbbá, számlaszámos lekérdezéskor a szűrés is kis-nagybetű érzékeny, ami néha elég zavaró lehet.

Ez tervezett állapot-e, illetve terveztek-e ezzel kapcsolatos változtatást?

Üdv
Ede

**Comment by NTCA-supporter** [comment]
Szia @veerede !
Ez a kezdetektől így van, és szándékosan, így nem tervezünk ezen változtatni.
Erre fel kell készülni.
Üdv
