### ISSUE TITLE
[Q&A]Cég-felhasználó kapcsolat törlés, Érvénytelen adózó esetén

### ISSUE THREAD

**Issue by tkelemen73** [nav-gov-hu/Online-Invoice#338]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Sziasztok,
az Online számla rendszerben több cég van hozzárendelve a Felhasználóhoz. Az egyik cég ezek közül megszűnt, vagyis már érvénytelen az adószáma. Az Online számla rendszerben (Cég-felhasználó kapcsolatokban) ennek ellenére továbbra is megjelenik a megszűnt cég. Hogy lehetne megszüntetni az összerendelést? Ha a megszűnt cégre a Megnyitás funkciót választjuk, akkor Érvénytelen adózó, a folyamat nem folytatható! hibaüzenet jön fel. Mi a megoldás? Vagy nincs olyan funkció, hogy a megszűnt céggel való összerendelést törölni lehessen? Kicsit zavaró...

**Comment by NTCA-supporter** [comment]
Szia @tkelemen73 !

Igen, ez ismert jelenség a kezdetek óta. Backlogban ott van a megoldása, csak mindig van fontosabb feladat :) 
Igyekszünk beütemezni, ezt fejlesztési oldalon kell megoldanunk, hogy ne is jelenjen meg a listában.
Mivel a validáció mindig megfut, és talán a hibaüzenet is megfejthető, így egyelőre nagy gondot nem okoz.

Sajnos most nem tudok becslést sem adni, hogy mikor fogunk ezzel foglalkozni, ezért zárom az issuet.

Köszi a türelmet!
