### ISSUE TITLE
[Q&A] QueryInvoiceDigestRequest gateway Timeout paraméterfüggő?

### ISSUE THREAD

**Issue by rgform** [nav-gov-hu/Online-Invoice#339]
Az én esetemben az adott képernyőn egyaránt kérhető digestlist számla kelte és insdate szerint. Számla kelte szerint a havi (kb 500 darab számlás) intervallumra MINDEN ESETBEN érkezik választ, az insdate lekérés már 7-8 napos intervallum esetében is elvérzik, annál szűkebb estében lassan, de leszedi.. Visszaváltva számla keltére ugrik mint bolha...  Miért van  ilyen, a felhasználást igen-igen megnehezítő eltérés a kétféle paraméterhívás időigénye között?  

![](https://user-images.githubusercontent.com/6500348/89648149-0dcb4580-d8bf-11ea-9d88-c91916a529d9.jpg)

![](https://user-images.githubusercontent.com/6500348/89648167-1885da80-d8bf-11ea-8780-a986cfc96d35.jpg)

Köszönettel, PPSOFT

**Comment by NTCA-supporter** [comment]
Szia @rgform !
Láttuk a kommentedet a másik issue-ban, így ezt zárom.
Igyekszünk reagálni.
Köszi
