### ISSUE TITLE
[FEATURE] Időintervallum növelése

### ISSUE THREAD

**Issue by Rossi73** [nav-gov-hu/Online-Invoice#34]
**Az igény összefoglalása / Summary of the request**
Bejövő számláknak adószámra (is) történő lekérdezésekor legyen lehetőség nagyobb időintervallum megadására.

**Az általam javasolt megoldás / The solution I propose**
A jelenlegi 35 nap helyett fogadja el a rendszer egy adott napot megelőző év január 1. és az adott nap közötti időszakot: WHERE ... YEAR(időszak_kezdete) >= YEAR(időszak_vége) - 1. Ezt csak akkor engedje meg a rendszer, ha az adószámot (is) megadjuk lekérdezési paraméterként, más esetekben (tehát ha az adószámot nem adtuk meg) maradhat a 35 napos intervallum.

**Elfogadható alternatívák / Acceptable alternatives**
Ha az intervallum megnövelése túl sok vizsgálatot eredményez abban az esetben, ha az adószám mellett másra is keresünk, akkor elfogadható a megoldás úgy is, ha a rendszer csak akkor engedi a nagyobb intervallum megadását, ha kizárólag az adószámot adjuk meg keresési feltételként.

**Egyéb tartalom / Additional content**
Egy rendkívül hasznos funkció lenne egy partner bejövő számláinak lekérdezésekor, ha nemcsak 35 napot lehetne lekérdezni, hanem hosszabb időszakot. Mivel a cégek éves bevallása nem azonos időszakra esik (január 1., május 31.), ezért javaslom azt, hogy a lekérdezéskor a fenti időszakra lehessen lekérdezni. Ez mind könyvelői oldalról, mind felhasználói oldalról nagyon hasznos lenne. Jelenleg, ha le szeretném kérdezni egy konkrét partner számláit, akkor ezt csak 35 napos bontásban tehetem meg.

Könyvelési szempontból a teljesítési dátumnak van jelentősége, így ennél a mezőnél mindenképp javaslom a fenti módosítást. Ha a rendszer rugalmas működése megengedi, akkor ezen kívül mind a kiállítási dátumnál, mind a fizetési határidőnél javaslom a bevezetését.

**Comment by Amn3s1a2018** [comment]
A gép-gép közötti kommunikációban vagy a webes felületen (vagy mindkettőben) szeretnénk ezt?
Mivel az első esetben viszonylag könnyen megkerülhető a korlátozás (többszöri lekérdezéssel), a második lenne hasznos. Van már példa  hasonlóra, hiszen amikor a kimenő számlák között számlaszámra keresünk, egyáltalán nem kell más feltételt megadni.

**Comment by Rossi73** [comment]
Igen, részben igazad van. A kérdés az, hogy mivel bejövő számláról van szó, szeretném egy konkrét partner számláit lekérdezni. Ez csak 35 napra megy, mert ha nem számlaszámra keresek, akkor az intervallum megadása kötelező. (A számlaszámra keresésnél értelemszerűen nincs értelme, ezért választották szét funkciót tekintve is, mivel az tutira egyedi lesz. :-)) A webes felületen mind a kimenő, mind a bejövő számlák esetén kötelező megadni az intervallumot is, bármire is keresek, ugyanez érvényes a gép-gép kapcsolatra: a InvoiceQueryParamsType típusban az invoiceIssueDateFrom és invoiceIssueDateTo mezők megadása kötelező.

Értem én persze, hogy gép-gép kapcsolaton keresztül lehet rá írni amúgy egy ciklust, amivel 12 lekérdezést beküldök, hogy megkapjam az utóbbi 1 év összes számláját egy partnerre, de szerintem nem ez lenne a megoldás (12 token + 12 lekérdezés), hanem az, hogy ezt egyben le tudjam kérdezni. Az is lehet, hogy a 12-ből 9 fölösleges lekérdezés, mert épp abban a 9 hónapban nem volt egyetlen bejövő számla sem. Tehát: fölöslegesen terhelnénk a rendszert.

A webes felületen mindenképp szükséges lenne, viszont, ha ott engedélyezik, akkor nem látom értelmét, hogy gép-gép kapcsolatra miért ne működhetne ugyanez.

**Comment by NTCA-developer** [comment]
Sziasztok!

Köszönjük a felvetést. A dátum intervallumnak az a szerepe, hogy segítsen a művelet során szerver oldali válaszidőt garantálni. Figyelemmel arra, hogy az XML API-s lekérdezés válasza szinkron, és a digestes lekérdezés nem is a teljes számla adattartalommal tér vissza, ezért szerintem ez a funkció nem ide való. 
Tokent egyébként nem kell a lekérdezéshez kérni, de ez csak btw.

Az Online Számla következő, 1.8-as verziója tartalmazza a számla export funkcionalitást, ami aszinkron módon mind vevői, mind kiállítói oldalon is engedi felületről a számla adatok tömeges exportját. Egyelőre a funkció még csak 35 napos bontásban működik és csak excel formátumot ad vissza, ezt lehetne inkább tovább fejleszteni. A funkció a teszten már elérhető, hamarosan települ az élesre.

@Rossi73 elfogadod a választ, vagy folytassuk még?

**Comment by Rossi73** [comment]
Szia!

Úgy vélem, az **adószám megadása** kellően leszűkítené a válaszban érkező adatok mennyiségét, és ezért talán nagyobb intervallum feldolgozása is lehetővé válna (hiszen tuti, hogy adószámra is indexel a rendszer - talán elsődlegesen épp arra?), ezért vetettem fel, hogy **ebben az esetben** lehetne növelni az intervallumot.

Ui.: Token valóban nem kell. :-)

**Comment by NTCA-developer** [comment]
Szia!

Sajnos nem elég. Több mindenre indexelünk a táblában, az adószám is ilyen, de egy indexnek a végrehajtási terve még csak index fast scan-t eredményez, ergó ugyan úgy végig kellene menned a teljes táblán.

A válaszidő szinten tartásához nem a teljes táblára, hanem partícióra kell tudnod bevinni a lekérdezésed, de ha ez a partíció nem **számottevően** kisebb, mint a teljes tábla, akkor fáradtságos munkával eljutottál ugyan oda ahonnan elindultál, és a jövőre nézve egyre inkább romlani fog a lekérdezésed performanciája.

Abban partnerek tudunk lenni, hogy - mivel a digest bevezetésével a válaszobjektum mérete már kevésbé bizonytalan mint az 1.x-ben - a lapozás méretét növeljük. De a lekérdezés mélységét ekkor sem szabad bolygatni.

Minden olyan igény, ami nagyobb intervallumot akar lekérdezni, az már inkább az aszinkron irány, ezért is írtam az előző postban erről.

**Comment by NTCA-developer** [comment]
@Rossi73 

A lapozó paramétert egyébként is akartuk emelni, mivel a lapozás mindig rendezés mentén lehet, a rendezéshez meg végig kell menni ugyan azon a végrehajtási terven minden lapozás alkalmával, szóval nekünk is jobb, ha ez minél kevesebbszer történik meg.

Felvennénk a mostani 10-es lapozó paramétert 100-ra laponként. Ezt tudom felajánlani, bár tudom az eredeti kérés nem erre irányult. Megegyezünk? :)

**Comment by Rossi73** [comment]
Oké, legyen. :-)

**Comment by NTCA-developer** [comment]
Oké, köszi. :)
