### ISSUE TITLE
[Q&A] Új fórum kellene

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#340]
Tudom, hogy nem ide tartozik, de **az xx65 ÁFA bevallásnak is kellene egy fejlesztői fórum**.
Legalább akkora feladat és probléma az xx65 ÁFA bevallás, mint az Online számla adatszolgáltatás.
Folyamatosan figyelmeztetéseket ad a 2065-ös nyomtatvány olyan esetekben, amikor a programunkkal a 2020.07.01-i PM-NAV közös közleménynek megfelelően adjuk át az adatokat.
A nyomtatványba beépített ellenőrzések NEM ismerik a PM-NAV azon elvárását, hogy a végszámlát az xx65M-02 lapon 2 db sorban kell közölni. A 2 db sor összeg NYILVÁNVALÓAN, előre tudottan nagyobb lesz, mint az xx65A lap megfelelő soraiban szereplő (64+65+66+31....) összeg.
A konkrét üzenetek:
F|[Nyomtatvány] [2065A-01-05] 108D <= [2065A] [01 lapokon] SUM(63B+...+66B) + 68B + SUM(72B+...+75B) + 28B + 31B  (Hibakód=<755851/R167>) |||Figyelmeztetés|R167|
F|[Nyomtatvány] [2065A-01-05] 108E <= [2065A] [01 lapokon] SUM(64C+...+66C) + 68C + SUM(72C+...+75C) + 28C + 31C  (Hibakód=<755852/R168>) |||Figyelmeztetés|R168|
F|[Nyomtatvány] [2065A-01-05] 108D <= [2065A-01-03] 76B (Hibakód=<755853/R171>) |||Figyelmeztetés|R171|
F|[Nyomtatvány] [2065A-01-05] 108E <= [2065A-01-03] 76C (Hibakód=<755854/R172>) |||Figyelmeztetés|R172|
 Nem itt akarom megvitatni, de ennek is kellene egy hatékony fórum lehetőség.
**Jelenleg nagyon leterheli az ügyfélszolgálatunkat ezeknek a hibás, átgondolatlan üzeneteknek az ügyfeleink felé való kezelése.**
Amikor megláttam a 2020.07.01-es PM-NAV közleményt, már sejtettem, hogy ezt nem fogja tudni kezelni a 2065 nyomtatvány.

**Comment by Macskafarka** [comment]
Elkezdődtek a már benyújtott áfa bevallások miatt az ügyfelek kiértesítései, zaklatásai a NAV által.
Miért lehet korábban átgondolni azokat a hibás ellenőrzéseket, amelyek alapján eltérést állapítanak meg?
Előre lehetett látni azt, hogyha az xx65M-02 és 02K lapon számlánként kell ezer Ft-ra kerekíteni, majd ezt összesítve más szám jön ki, mintha a mesterségesen szétválasztottan ezer Ft-ban kifejezett   64+65+66+... sorokat összesítik.
Ha van 10 db 751 Ft adótartalmú számla, akkor az M-02 lapon 10x1.000=10.000 Ft-ként, ezerben kifejezve 10-ként lesz összesítve. Ha mindegyik a 66. sorba kerül, akkor 7.510 Ft lesz, ami ezer Ft-ban kifejezve 8.  És azt ellenőrzik, hogy a 10kisebb-e, mint a 8! Továbbá a 02M lapokon a részben levonható áfának a 100%-át kell szerepeltetni, a ellenőrzéshez használt 54+65+66 stb sorokban a 70, vagy az 50%-át. És hibaként kezelik, ha a 70% kisebb, mint a 100%.
És akkor még ott van az az előírás is, hogy az xx65M-02 lapon a számlának nemcsak a levonható áfát tartalmazó sorai is kellenek, tehát ez eleve nagyobb lesz, mint a 64+65+66+... -sorokban szereplő levonható. Ez is megy hibaüzenetre.
Mindezeket a hibaüzeneteket több száz, vagy több ezer xx65-M lap esetén még átolvasni is képtelenség!
Ez groteszk (siralmasan nevetséges).

**Comment by Macskafarka** [comment]
Helyesen a 2. sor: "Miért NEM lehetett korábban átgondolni...."

**Comment by celeburdi** [comment]
Ha az államnak kellenek ezek az adatok, akkor fizessen érte,
Mondjuk M lap tételenként egy bizonyos összeget.
Mert így majd jön a diadaljelentés, hogy mennyi adóbevételt hozott a jelentési határ eltörlése. 
A plusz ráfordított munka árát meg nem veszik figyelembe.
