### ISSUE TITLE
[Q&A] Felénk kiállított számlák ütemezett lekérdezése

### ISSUE THREAD

**Issue by kovadam69** [nav-gov-hu/Online-Invoice#341]
Sziasztok!

Miután minden cégünk felé kiállított számla lejelentésre kerül a rendszerben, jó lenne, ha ezeket automatizáltan (pl. naponta egyszer reggel) le tudnám kérdezni, így tudnám segíteni a kollégák bejövő számla adatainak rögzítését.

Viszont ilyen funkciót nem találok az API-ban. Ami van, oda kötelező a számlaszám, viszont azt ugye nem tudjuk. A felületen van lehetőség dátum-intervallumra lekérdezni az összes bejövő számlát, az API-ban nem találtam.

Kérdés: én vagyok láma, és nem vettem észre, vagy tényleg nincs ilyen lehetőség?
Kérdés#2: ha nincs ilyen lehetőség, lehetne-e ilyen? Sokban segítené az adminisztrációs munkát, ha minden adatot megkapnánk és nem kéne bevinni (dátumok, összegek, stb.) csak ellenőrizni a számla és a NAV rendszere között...

Köszi!

Üdv

**Comment by connorhu** [comment]
Szia!

Szerintem az invoiceDirection INBOUND-ot keresed. 22. oldal:
https://onlineszamla.nav.gov.hu/files/container/download/Online%20Szamla_interfesz%20specifik%C3%A1ci%C3%B3_HU_v2.0.pdf

**Comment by kovadam69** [comment]
Szia!

Igen, ezt néztem, de itt a Request-ben az InvoiceNumber kötelező. Én meg nem egy konkrét számlára szeretnék keresni, hanem mondjuk a tegnap reggel 6 óta beküldött összes számlát le szeretném kérni...

Igaz így is megoldható, max nem listáról választ a user, hanem partnert és számlaszámot ad be, az alapján lekérdem a konkrét számlát, de jobb lenne, ha tudnánk minden számláról, amit felént kiállítottak, mert jobban ellenőrizhető.

A webes felületen van ilyen lehetőség, hogy minden számlát láss, csak dátumintervallummal szűrve, az API-ban ilyet nem találtam.

**Comment by kovadam69** [comment]
Azért lenne jó, mert ha pl. valaki céges számlára vesz valamit, de nem adja le a számlát, a NAV rendszeréből erről értesülünk, míg egyébként max akkor, ha büntetnek érte.
Ha meg már van egy vállalatirányítási rendszer, egyszerűbb, ha ott vannak az adatok, nem kell még külön webes felületet böngészni.

**Comment by laladisc** [comment]
Szia!

Erre való az Invoicedigest. Azzal megkapod az összes számla sorszámot. Majd annak birtokában már le tudod kérdezni tételesen a számlákat.

**Comment by kovadam69** [comment]
Szia!

Hmmm... néztem, de a MandatoryQueryParams-ban az originalInvoiceNumber és a supplierTaxNumber is kötelező elem, vagyis még mindig kell valami adatot beadni a dátumokon kívül...
Bár ahogy olvasom a magyarázó részt vagy a dátumok, vagy a beküldési dátumok vagy a számlalánc kötelező (tehát nem mind).

Megpróbálok futtatni egy ilyen lekérdezést, meglátom mit ad vissza.

Köszi a tippet!

**Comment by kabelnet2** [comment]
Mi így használjuk:
[invoiceDirection]INBOUND[/invoiceDirection]                
[invoiceQueryParams]                                        
  [mandatoryQueryParams]                                    
    [insDate]                                               
      [dateTimeFrom]2020-08-21T00:00:00Z[/dateTimeFrom]     
      [dateTimeTo]2020-08-24T00:00:00Z[/dateTimeTo]         
    [/insDate]                                              
  [/mandatoryQueryParams]                                   
[/invoiceQueryParams]                                       
([=<, ]=>)
A from date az előző lekérdezés dátuma. Idővel nem foglalkozunk, de természetesen lehet.

**Comment by NTCA-supporter** [comment]
Szia @kovadam69 !
Ahogy fentebb is írták, a queryInvoiceDigest való erre.
A manadatoryQueryParams csomóponton belül egy choice van, tehát nem feltétlenül a számla sorszám alapján kell keresni, lehet kiállítási és feldolgozási időpont szerint is intervallumosan keresni.
Üdv

**Comment by kovadam69** [comment]
Köszönöm mindenkinek! Ha oda jutok, kipróbálom, biztos működni fog! :)
