### ISSUE TITLE
[DOC] invoiceDigest operációban áfacsoport azonosító és csoporttag adószám megnevezések keveredése

### ISSUE THREAD

**Issue by laladisc** [nav-gov-hu/Online-Invoice#342]
Az invoiceDigest operációban a supplierGroupTaxNumber tag leírásában ez szerepel: "Számla kiállítójának áfacsoport azonosító száma" vevőnél ugyanaz a helyzet. A leírásból és a tag nevéből arra következtettem, hogy itt a csoportazonosítót fogom visszakapni, de az a helyzet, hogy ugyanúgy a csoporttag adószáma kerül a mezőbe mint amit a számlaküldésnél a groupMemberTaxNumber tag ba írunk. Szóval elég megtévesztő hogy a tag nevéből kikerült a "Member" kifejezés valamint hogy a dokumentáció is csoportazonosítóról beszél csoport tag adószám helyett.

**Comment by NTCA-supporter** [comment]
Szia @laladisc !
Köszönjük a jelzést. Validnak tartom a felvetést, a 3.0 XSD-ben supplierGroupMemberTaxNumber és customerGroupMemberTaxNumber lesznek. Az interfész dokumentációt pedig szintén a 3.0 verzióhoz pontosítjuk, hogy egyértelmű legyen.
Ha nincs több kérdés, kérlek zárd az issuet.
Üdv

**Comment by laladisc** [comment]
Köszi, zárom.
