### ISSUE TITLE
Kérdés a  Manageinvoice/QueryInvoiceData/QueryInvoiceChainDigest kapcsolatáról...

### ISSUE THREAD

**Issue by rgform** [nav-gov-hu/Online-Invoice#343]
Üdv.

Egy módosító számlát ModifyWithoutMaster -> true értékkel bekülve az alábbi hibaüzenet érkezett:

			<businessValidationMessages>
				<validationResultCode>ERROR</validationResultCode>
				<validationErrorCode>MODIFY_WITHOUT_MASTER_MISMATCH</validationErrorCode>
				<message>A módosítás vagy érvénytelenítés olyan okiratra hivatkozik, amelyrõl létezik érvényes adatszolgáltatás.</message>
				<pointer>
					<tag>InvoiceData/invoiceMain//invoice/invoiceReference/modifyWithoutMaster</tag>
					<value>2019/00368</value>
					<originalInvoiceNumber>2019/00368</originalInvoiceNumber>
				</pointer>
			</businessValidationMessages>

Nem gond, rákeresek a 
számlára:

![navaq1](https://user-images.githubusercontent.com/6500348/90631376-f24b2d80-e222-11ea-84b2-758ba4ddbe8a.jpg)

Szerintem ez azt jelenti nincs ilyen feltöltve.  Megnézem a számlalánc felől is:

![navaq2](https://user-images.githubusercontent.com/6500348/90631728-83220900-e223-11ea-8d06-c3cabdcafb47.jpg)

Ezek szerint sincs meg. 

Mi is történhetett?  A cég év elején programot cserélt.  Lehet hogy új technikai usert hoztak létre.  A fentieken okoskodva lehet a tavalyi számlát más technikai user küldte be?  Ezek szerint egy másik technikai user küldhet be módosítást a régi számlára, de nem jelenik meg neki a lekérdezésekben?  Nem jelenik meg a számlaláncban? Vagy mi okozza ezt?  Programcsere / technikai usercsere esetében elvesznek? a lekérdezésnek az eddigi adatok?    

Természetesen requestid-től kezdve minden naplózva ha szükséges...

Üdvözlettel, PPSOFT

**Comment by NTCA-supporter** [comment]
Szia @rgform !
Csak tippelek, a lekérdező techikai felhasználódnak lehet csak saját számlák lekérdezés jogosultsága van, így valóban, ha más tech userrel let beküldve a kérdéses számla, akkor azt nem fogod látni.
Üdv

**Comment by rgform** [comment]
Szia!

Mivel programozóként NEM menedzselem az Onlineszámla  WEB hozzáférését a cégnek, ezek szerint meg kellene kérnem, hogy az új technikai usert állítsa úgy be hogy az az előző user által beküldötteket is lássa?  Ezek szerint **lehetséges,** csak a felhasználók nem tudják-  hogy pl. programváltáskor- ezt így kell beállítaniuk?  Hab a tortán, hogy jellemzően nem a felhasználó, hanem a könyvelőjük menedzseli ezt, így áttéteken keresztül kell instruálnom őket, mig jó lesz.  

De akkor beállítható, hogy visszamenőlegesen egy adószám, bármilyen technikai usere által beküldött számlát lekérdezhessem interface felől is?

Köszönettel, PPSOFT
