### ISSUE TITLE
[Q&A] Nem engedélyezett vevői adószám

### ISSUE THREAD

**Issue by Csomb** [nav-gov-hu/Online-Invoice#344]
Sziasztok!

Segítséget kérnék, mert nem találom az okát annak, hogy egy vevő bizonyos számlákon miért "nem engedélyezett", más számlákon pedig nincsen vele probléma. Egyszerre kb. 50-60 számlát állítunk ki, amiből kettő lesz hibás. A hiba konkrétan:

<message>Nem engedélyezett vevői adószám.</message>
<pointer>					 
  <tag>InvoiceData/invoiceMain//invoice/invoiceHead/customerInfo/customerTaxNumber/taxpayerId</tag>
</pointer>

Ez az adat mindegyik számlánál ugyanaz.

Sikeres beküldés tranzakciója, pl: 32VEVN94NKOO0G5J
Hibás beküldés: 32WV5VTIPFUHTBGW

Köszönöm a segítséget előre is!

**Comment by NTCA-supporter** [comment]
Szia @Csomb !
Az interfész doksi elég jól leírja az ellenőrzést:
"Ha az adatszolgáltatást teljesítő technikai felhasználót a bejelentő elsődleges technikai felhasználója egy bizonyos vevői
körre korlátozta, akkor a technikai felhasználó csak a korlátozásban szereplő vevők nevére (adószámára) állíthat ki
számlaadat-szolgáltatást. A hibakód akkor kerül visszaadásra, ha az adatszolgáltatásban nem engedélyezett vevői
adószám szerepel, vagy a vevő adószáma üres"

Mielőtt ránéznék, kérlek ellenőrizd, hogy az 50-60 számlát ugyanazzal a technikai felhasználóval küldöd be és ugyanannak a vevőnek állítod ki?
Ha igen, akkor nyomozunk tovább majd.

Köszi

**Comment by Csomb** [comment]
Sziasztok!
Nem, mivel ezek önszámlázás során készülnek, így mindegyik számla különböző technikai felhasználó által kerül betöltésre, de ugyanannak a vevőnek számláznak. Sajnos arra nincsen rálátásom, hogy az adott technikai felhasználók le lettek-e korlátozva egy-egy adószámra vagy sem, úgyhogy lezárom a hibajegyet és ha kapok további infót (és nincsen korlátozva), akkor inkább újranyitom.
Köszi!
