### ISSUE TITLE
[Q&A] /queryInvoiceDigest lassúság 

### ISSUE THREAD

**Issue by vbela75** [nav-gov-hu/Online-Invoice#345]
Tisztelt Cím!

Szerintem vagyunk itt egy páran akik a NAV üzleti szolgáltatását veszi igénybe (letöltjük a számlákat) ezzel kapcsolatban lenne egy pár kérdésem. Miért van az hogy a /queryInvoiceDigest operáció sebessége a 0 és 100 % között bármikor bármennyi lehet. Ezalatt azt értem hogy sokszor ha 1 napos intervallumot kérek le akkor is simán "Time Out"-ra fut. Vannak olyan időszakok amikor óránként le lehet tölteni 2000 db számlát de van amikor 200 db sem jön le. 

Alkalmaznak valamilyen szűrést (IP, vagy programid, percenkénti max lekérdezésszám) vagy csak a rendszer leterheltsége miatt van ez a folyamatos lassulás. Naponta csak 1x akarok letölteni, viszont akkor akár több ezer adózó adatait 1 gépről 1 esetleg 2 szálon. Publikussá lehetne-e tenni valahogy az szűrési feltételeket ha használnak. Több céggel tárgyaltam már és mindenki hasonló problémákkal küzd.

Aki ilyenbe ütközött már kérem szintén kommentáljon hátha látszik hogy nem egyedül vagyok.

**Comment by laladisc** [comment]
Szia! 

Itt is ez a téma: #329

**Comment by NTCA-supporter** [comment]
Szia @vbela75 !
Ahogy jelezték kommentben, már van erre nyitott issue.
Hamarosan kerül ki új verzió éles környezetre, amiben lesznek performancia javulások.
Zárom, üdv.
