### ISSUE TITLE
[Q&A] Bejövő számlák dátum szűrése

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#346]
A NAVOnline számla felületen a Számlák/Bejövő számlák menüben jelenleg a dátum mezőkben csak max.35 napos intervallumokra lehet lekérdezni.  Ez elég nehézkes a negyedéves, és az éves adózóknak.
Tervezik-e azt, hogy a lekérdezési dátum intervallumokat összehangolják az áfa törvénybeli bevallási intervallumokkal?
Figyelembe veszik-e a dátum intervallumnál azt, hogy az EU vonatkozó irányelve szerint a hozzáadott érték adó az éves adó?
Többek között ezért is van február 20-ig éves módosítási lehetőség.

**Comment by NTCA-supporter** [comment]
Szia @Macskafarka !
Ez a kezdetektől így van, és szándékosan, performancia okokból.
Az interfészes lekérdezéseknél is ugyanúgy 35 nap a megadható maximum intervallum.
Visszamenőleg a rendszer indulálásig lekérdezhetőek a számlák, például havi bontásban.

Technikai oldalról nem értem hogy jön a képbe az EU vonatkozó irányelve a lekérdező felülethez.

Üdv

**Comment by Macskafarka** [comment]
Igazából azt nem értem, hogy miért nem lehet a törvényeket figyelembe venni, miért vannak saját döntések a technikai oldalon?
Miért nehéz elképzelni, hogy az is akarja használni a lekérdezéseket, aki nem havi áfa bevalló?
Akkor a nagyedéves adózó is mondhatja azt, hogy "performancia okokból" a negyedév helyett csak 35 nap számláit szerepeltetem a bevallásban?
Az EU úgy jön ide, hogy nemzetközi szerződés übereli a magyar jogot. 
Az EU direktíva szerint áfa éves adó, ebből következően lehetővé kellene tenni az éves lekérdezési intervallumot is.

**Comment by NTCA-supporter** [comment]
Az, hogy egyszerre 35 nap számláit tudod lekérdezni egyáltalán nem azt jelenti, hogy egy negyedév vagy egy teljes év számláit ne tudnád lekérdezni. Arra, hogy a felületen/interészen milyen intervallumot engedélyezünk egy lekérdezésben, szerintem nincs törvényi hivatkozás :)

**Comment by vajayattila** [comment]
És 3x30 nap számláit lekérdezni kevesebb erőforrás, mint egy szer 90 nap számláit? Elfogadom ha azt mondod igen, csak kíváncsiságból kérdezem.

**Comment by Macskafarka** [comment]
Vagy a 12x30 napot. Most nem a gépi lekérdezésről beszélek, hanem a felületen a kisebb vállalkozásoknak.
Azoknak is rá kell nézni, és XLS-be kiexportálni, hogy mit adott föl a számlakibocsátó. 
Aztán el kell döntenie, ha a számlán nem szerepelt ugyan adószám, de a számlát mégis adószámmal töltötték föl, akkor levonható-e, vagy ha a számlán szerepel ÁFA, de a számlakibocsátó adómentesen adta fel.
Szóval én teljesen máshogy képzeltem el az adminisztráció csökkenést.

**Comment by Macskafarka** [comment]
@NTCA-supporter  Igazad van, mivel nincs rá törvényi előírás, akkor lehetne kérni azt, hogy egyszerre csak 12 napot lehessen lekérdezni?  Csak, mert lehet ilyent is dönteni, végülis nem ütközik semmibe.

**Comment by NTCA-developer** [comment]
A performancia kétirányú utca. Nekünk aszinkron lekérdezést kellene fejleszteni a nagyobb intervallumhoz, mivel a HVR miatt 60 sec alatt minden válasznak vissza kell érni a klienshez, különben jön a gateway timeout. Abba viszont nem gondotok bele, hogy az asztali alkalmazások négy kilences százaléka egy 200 megás XML-be is belehal. A méretkorlát nem kizárólag a szerver oldal miatt van. Akinek sérti a világnézetét hogy egy évet 11 lekérdezésből fog csak tudni lekérdezni akkor azt sajnáljuk.

Egyebekben megválaszoltuk a kérdést. @Macskafarka úgy látom nem érted ennek a fórumnak a lényegét. Ez egy fejlesztőknek szóló technikai oldal aminek az a célja, hogy közösen tudjunk gondolkozni a fejlesztésekben. Nem egy általános NAV gateway ahol elmagyarázhatod hogy csak te érted jól a jogszabályokat, vagy kommentálhatod a PM közleményeket vagy hőzönghetsz a világra, erre a blog műfaj jobban alkalmas.

Ez az első és egyben utolsó figyelmeztetés, a trollkodást fejezd be. Utána jön a ban.
