### ISSUE TITLE
08.31. napján  TrId - t nem kapott a beküldött számla

### ISSUE THREAD

**Issue by KMGY100** [nav-gov-hu/Online-Invoice#347]
A PROG.HU fórumon többen is jelezték, valamint nálam is előfordult az alábbi eset.
A számlát beküldtük, de nem kapott TrId -t ezért a számla feldolgozási állapotát nem lehet lekérdezni.
Mi a Teendő
Köszönöm a választ

**Comment by NTCA-supporter** [comment]
Szia @KMGY100 !
https://onlineszamla.nav.gov.hu/files/container/download/Online%20Szamla_interfesz%20specifik%C3%A1ci%C3%B3_HU_v2.0.pdf
1.8.7 A /queryTransactionList operáció 

Ez direkt az ilyen esetekre lett lefejlesztve.

Üdv

**Comment by KMGY100** [comment]
Köszönöm a választ
