### ISSUE TITLE
[Q&A] XSD 3.0 és elektronikus számlázás

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#348]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

A 3.0-ás XSD kapcsán ezt olvashattuk: "Az eladó a meghatározott számlaadatokat beküldi az adóhivatalhoz, a vevő pedig egyszerűen letölti a szükséges adatokat, így az adatszolgáltatás lehet maga az elektronikus számla."

Ezt kérném, hogy fejtsék ki bővebben.
1. A "meghatározott számlaadatokon" azt értik, amit eddig is küldeni kellett vagy van e kapcsán új kötelezően küldendő adat?
2. " a vevő pedig egyszerűen letölti a szükséges adatokat": Hogyan és honnan? Ezt úgy kell érteni, hogy be kell lépnie a vevőnek az online számla felületre és onnan tölti le a számlát?

**Comment by NTCA-developer** [comment]
Szia @nbeeps2 

Ezt a 3.0-ás changelogból ki fog derülni. Keress rá a completenessIndicator-os bejegyzésekre.

**Comment by nbeeps2** [comment]
> Szia @nbeeps2
> 
> Ez a 3.0-ás changelogból ki fog derülni. Keress rá a completenessIndicator-os bejegyzésekre.

Ok, rendben, de erre nem találtam utalást: " a vevő pedig egyszerűen letölti a szükséges adatokat". Hogy jut el a vevőhöz a számla? Mindig amikor ilyen számlát kap, be kell lépjen az Online NAV rendszerbe, hogy letöltse magának a számlát?

**Comment by connorhu** [comment]
Vagy úgy, vagy API-n keresztül lehúzza az INBOUND számlákat.

**Comment by nbeeps2** [comment]
> Vagy úgy, vagy API-n keresztül lehúzza az INBOUND számlákat.

Mondjuk egy külföldi vevő bármilyen külföldi ügyviteli rendszerrel? Csak nem... ;)

Azt sem értem még, hogy ha maga az adatszolgáltatás az e-számla, akkor ilyen esetben nem keletkezik számlakép? Vagyis a program nem generálhat számlaképet, mert nem az a számla? Hogy fog akkor kinézni a számla, mit lát majd a vevő? Ez nekem kicsit zavaros.

**Comment by fenyvessy** [comment]
@nbeeps2, szerintem képzeld úgy el, mint az EDI.
Olyan módon jeleníted meg magadnak az XML-ből (tájékoztató jelleggel), ahogy az neked tetszik, nem kell az ezerféle számlaképen keresgetni, hogy ki-mit-hol tüntet fel rajta. De ez inkább olyan helyeken hordoz előnyt, ahol nem manuális a feldolgozás és rendszeres a vásárlás, pl. nagyker-kisker. Vagy olyan helyeken, ahol sokszáz tételes számlák alapján történik mondjuk egy raktári bevételezés, igencsak fel tudja gyorsítani a folyamatot. Eddig nem volt standard formátum, több olyan rendszert ismerek, ami saját egyedi formátumban adata oda a papír vagy e-számla adatait, így mindegyik beszállító formátumához csinálni kellett egy beolvasó részt. Ha ez most egységesedik, ráadásul hiteles forrásból azonnal megérkezik az adat, akkor az nagyon nagy előny tud lenni.

**Comment by NTCA-developer** [comment]
Azt gyorsan hozzáteszem, hogy a jogszabályi változást majd hozzá kell olvasni ehhez a megoldáshoz, úgy lesz teljes a kép, de alapvetően @fenyvessy jól mondja, ez volt az eredeti szándék.

Egyébként azon én is gondolkoztam már nem egyszer, hogy kellene egy NAV általi XSLT-t kiadni, akkor lenne egy generál megjelenítő módozat a Data XML-re, ami ráadásul már feltehetően nem mozog nagyon. Csak hát idő, idő, idő....

**Comment by NTCA-developer** [comment]
Egyébként hallassátok a hangotok XSLT ügyben, most már lehet szavazni!
https://github.com/nav-gov-hu/Online-Invoice/issues/349

**Comment by NTCA-developer** [comment]
Engedelmetekkel ezt most lezárom, jelen idő szerint a rendelet nélkül nem tudunk többet hozzátenni most. Ha történik változás az ügyben akkor nyugodtan nyissátok újra vagy csináljatok új ticketet.
