### ISSUE TITLE
[FEATURE]modificationIndex

### ISSUE THREAD

**Issue by Anddio80** [nav-gov-hu/Online-Invoice#35]
A módosító számlák kezelése átalakul a data sémaleíróban ….Új elemként megjelenik a modificationIndex, amelyben a kliens oldalnak kell a módosítás sorrendiségét jelezni. A tag értéke 1-től kezdődik, logikailag az első módosító vagy stornó számlának kell az 1-es értéket kapnia. A szerver oldalon az egyediség vizsgálatra biztosan ERROR kerül bevezetésre, a sorfolytonosság ellenőrzésének lehetőségét még vizsgáljuk.

Ez könnyen problémát okozhat azon módosító és stornó számlák esetén, melyek eredeti számláját egy másik számlázó rendszerben állították ki. Az aktuális számlázó rendszernek ugyanis nincs információja, történt-e és hány módosító vagy stornó számla kiállítás az eredeti számlát kiállító rendszerben, emiatt nem tud jó modificationindex értéket adni. Erre ajánlja megoldásként a NAV: A modificationIndex a /queryInvoiceDigest válaszában visszaadásra kerül arra az esetre, ha az alapbizonylatra több módosító okiratot állítottak volna ki eltérő számlázó rendszerekből, és a módosításkor nem ismert a helyes következő érték. Ehhez intelligens beküldést kellene megvalósítani, ami a válaszul kapott hibát elemezve előbb lekérdezi az utolsó modificationIndex-et a NAV-tól, beleírja helyes értéket az aktuális módosító számlába és újra beküldi a számlát. 

Erősen strukturált rendszerek esetén egy ilyen intelligens kezelés kialakítása helyett javasolt alternatíva: az előzmény nélküli módosító számla létrehozásakor a számlázó rendszerben manuálisan kellene rögzíteni a NAV-tól (manuálisan) lekérdezett utolsó modificationIndex-et.

**Comment by NTCA-developer** [comment]
Szia!

Továbbítottam a javaslatodat az illetékeseknek, ide másolom a választ.

> A gyakorlatban ténylegesen előfordulnak olyan számla kibocsátási módszerek, amikor az alapszámla kibocsátása és a módosító számla/számlák kibocsátása más informatikai rendszerben történnek meg. Ugyanakkor az alapvető jogszabályi elvárás, hogy az alapszámlának, valamint a módosító számlának/számláknak együttesen kell leírniuk a valós gazdasági eseményt. Így bár előfordulhat, hogy két vagy több eltérő informatikai megoldásban készülnek a számlák, az ugyanakkor egy nagyon rossz ügyviteli megoldás, hogy lehetőség van arra, hogy két felhasználó egymástól függetlenül, egymás munkájának tudta nélkül elkülönült informatikai rendszerben elkezdjen módosító számlákat kibocsátani. Ezzel sem a vállalkozás, sem a vevője számára nem lenne egyértelmű, hogy pontosan mi mire változik.

> Mivel az adatszolgáltatási rendszer a számlakiállítási gyakorlatnak egyfajta leképeződése, így az egymással versengő felhasználók miatti hibás módosító számla adatszolgáltatást nem adatszolgáltatási problémának, hanem üzleti problémának látom. Egy nem megfelelően kialakított megoldás esetében nem feltétlenül az adatszolgáltatási rendszerben kell a megoldást megkeresni, hanem az ügyviteli folyamatok kialakításában. Amennyiben a felhasználók ismernék egymás munkáját, akkor logikailag összeállnának mind a helyes módosító számlák, mind pedig a helyes adatszolgáltatások.

> A fentiek alapján a felvetést nem tudjuk támogatni, inkább üzleti oldalról lenne érdemes átgondolni a kiállítási folyamatot.

A ticketet lezárom, ha új kérdésed van, nyugodtan nyiss egy újat.
