### ISSUE TITLE
3.0 előleg kezelés

### ISSUE THREAD

**Issue by rtoth0407** [nav-gov-hu/Online-Invoice#352]
A tervezett változtatások leírásából az olvasható ki, hogy az előleges tételeknél kötelező lesz megadni az előleg számla számát, előlegfizetés dátumát és árfolyamát. 
Ez azt jelenti, hogy kötelezően össze kell kötni a végszámlát az előlegszámlával?
Kaphatnánk erről részletes info-t?

**Comment by NTCA-developer** [comment]
Szia @rtoth0407 

Köszi a kérdést. Van egy másik ticket is ebben a témában, is mivel az a hosszabb, kérlek hadd folytassuk azon a szálon a beszélgetést! (https://github.com/nav-gov-hu/Online-Invoice/issues/354)
