### ISSUE TITLE
[FEATURE] Magánszemélynek kiállított számla adatainak lekérdezése

### ISSUE THREAD

**Issue by alaplap** [nav-gov-hu/Online-Invoice#353]
**Az igény összefoglalása**
Magánszemélynek kiállított számla adatainak lekérdezése az Online Számla Rendszer weboldalán és API-n keresztül. Mivel a magánszemélynek kiállított számláknál a vevő nevét és címét nem szabad megadni, így a jelenlegi formában nem lesz lehetőség arra, hogy egy magánszemély le tudja kérdezni a neki kiállított számlák adatait (még abban az esetben sem, ha kibővülne az Online Számla Rendszer úgy, hogy magánszemély is regisztrálhasson gazdálkodó szervezetek és egyéni vállalkozók mellet).

**Az általam javasolt megoldás**
Lehetővé kellene tenni, hogy magánszemély is regisztrálhasson az Online Számla Rendszebe. Regisztrációkor a gazdálkodó szervezet/egyéni vállalkozó választékok mellett megjelenne a magánszemély, mint opció. Továbbá lehetővé kellene tenni, hogy magánszemélynek kiállított számlák lekérdezhetők legyenek az Online Számlra Rendszeren keresztül magánszemélyként belépve (vagy API kapcsolaton keresztül más programból, technikai felhasználó használatával). Ha egy számlakibocsátó szeretne élni a lehetőséggel/gesztussal, hogy a vevői felé biztosítja az Online Számla Rendszerben a számláinak a lekérdezhetőségét, úgy beazonosíthatóvá kell valahogy tenni a számlaadat-szolgáltatását valamilyen biztonságos módon. Az alábbiakban megpróbáltam leírni egy módszert erre.
A customerInfo kibővítésre kerülne egy értékpárral, pl. a privatePresonIdentification/hash (type="CryptoType") és privatePersonIdentification/customerId (type="common:SimpleText100NotBlankType") értékpárokkal, amiket CustomerInfo/privatePersonIndicator=true esetén engedne kitölteni. A customerId a vevő azonosítóját tartalmazná, amit a számlakibocsátótól kapott (szerződésszáma, vagy vevőkód, vagy vevőkártya kódja, stb.), a hash pedig a customerId és a magánszemély nevéből konkatenált string nagybetűs SHA3-512 hash értékét tartalmazná. 
Így a számlabejelentésnél szerepelne egy olyan azonosító (a privatePresonIdentification/hash), ami a vevőazonosítót (ami nem személyes adat, azaz GDPR kompatibilis) és az Online Számla Regisztrációhoz tartozó magánszemély nevét használva kiszámítható, így beazonosítható lenne az számla anélkül, hogy a magánszemély adatait meg kelljen adni az adatszolgáltatásban. A számla adatok lekérdezéshez meg kellene adni a számlakibocsátó adószámát és a számlakibocsátótól kapott vevőazonosítót.

**Elfogadható alternatívák**
Más módszer arra, hogy magánszemély számlái is lekérdezhetők legyenek az Online Számla Rendszerben és API-n keresztül is.

**Comment by NTCA-tax** [comment]
Hasonló megoldásokon mi is sokat töprengtünk, és felmerültek a magánszemélyi adatszolgáltatás lekérdezés mellett és ellen is érvek. Végül a jogszabályban is látható megoldás született, hogy nem gyűjtünk magánszemélyre vonatkozó adatokat, és nincs magánszemélyeknek regisztrálási lehetősége sem a rendszerben.

Csak érdeklődnék, hogy milyen hozzáadott értéket látsz abban, hogy a magánszemély le tudja kérdezni az adatszolgáltatást?

**Comment by alaplap** [comment]
Az adatszolgáltatás, mint elektronikus számla esetében a magánszemély az Online Számla Rendszeren keresztül hozzá tudna férni a számlájához. Nem nagyon világos, hogy hogyan máshogy tudná a számlakibocsátó az ilyen elektronikus számláit kibocsátani a magánszemély vevők felé. Továbbá ide kapcsolódó kérdésként: mennyi ideig őrzi meg az Online Számla Rendszer a számlaadat-szolgáltatásokat?
Ha pedig API-n keresztül lekérdezhetők lennének a magánszemélyek számlái is, azt fintech alkalmazásokban lehetne kihasználni.

**Comment by connorhu** [comment]
Alap esetben egy magánszemély ritkán kezd valamit egy számlával. Nekem most pont van ilyen ügyem ami miatt számlát kell kérnem és gyűjtenem, de ezen felül nagyon maximum csak az elektronikus eszközök garanciája esetén (ha az eladó köti a garanciát a számla meglétéhez) látom értelmét a magánszemélyes számlázásnak.

**Comment by NTCA-tax** [comment]
Itt az az alapvető probléma, hogy az Áfa törvény szerint a számla kötelező adattartalma a vevő neve és címe. Ugyanakkor szerintem nagyon logikusan a magánszemélyek esetén ezen adatok nem kerülhetnek be az adóhivatal adatszolgáltatási rendszerébe. Ezen adatkör nélkül pedig az adatszolgáltatás nem lehet az elektronikus számla is. Tehát ebben az esetben az adatszolgáltatáson kívül kell előállnia az elektronikus számlának.

**Comment by alaplap** [comment]
> 
> 
> Itt az az alapvető probléma, hogy az Áfa törvény szerint a számla kötelező adattartalma a vevő neve és címe. Ugyanakkor szerintem nagyon logikusan a magánszemélyek esetén ezen adatok nem kerülhetnek be az adóhivatal adatszolgáltatási rendszerébe. Ezen adatkör nélkül pedig az adatszolgáltatás nem lehet az elektronikus számla is. Tehát ebben az esetben az adatszolgáltatáson kívül kell előállnia az elektronikus számlának.

Értem. Ez az összefüggés elkerülte a figyelmem, hogy a magánszemélynél nem lehet majd ilyen módon elektronikus számlát készíteni.

**Comment by janisoft** [comment]
Jelentosen egyszerusodne az adminisztracio, ha a maganszemelyeknek is ki tudnank allitani eszamlat nem csak vallalkozasoknak. Legalabb a kiallitast meg kellene oldani, ha a lekerdezes nem is valosul meg.

**Comment by fenyvessy** [comment]
@janisoft szerintem ki fogsz tudni állítani magánszemélynek is e-számlát. Ott van a félreértés, hogy kétféle NAV-os e-számla lesz: nagyon leegyszerűsítve az egyik hasonló a jelenlegi e-számla megoldásokhoz, csak éppen nem külső hitelesítő adja az előállított PDF-hez az elektronikus aláírást és opcionálisan az időbélyeget, hanem a NAV adatszolgáltatásba feltöltött hash garantálja a hitelességet. Ilyet fogsz tudni kiállítani magánszemélynek is, és erről anonimizált adatszolgáltatást is tudsz készíteni, hiszen magát a PDF-et nem töltöd fel. A másik megoldás az, amit nem lehet  majd magánszemély esetén alkalmazni, azaz amikor maga az adatszolgáltatás (XML) az e-számla, amihez nem kell tartoznia semmilyen megjelenített nyomtatási képnek.

**Comment by NTCA-tax** [comment]
Ez csupán az elektronikus számla kiállításnak egyik módja, nem az egyetlen. Ettől függetlenül lehet a magánszemélyeknek e-számlát kiállítani más megoldással. Amennyiben nagyon az adatszolgáltatáshoz akarjátok becsatornázni, akkor előállítotok egy PDF-et, melynek a hash kódját bekülditek adatszolgáltatásként. Amennyiben belföldi társaság a vevő, akkor az adatszolgáltatás lehet az e-számla is. A magánszemélyeket az adatszolgáltatásban úgyis külön kellene kezelni.

Míg legépeltem, @fenyvessy gyorsabb volt...

**Comment by alaplap** [comment]
> 
> 
> Hasonló megoldásokon mi is sokat töprengtünk, és felmerültek a magánszemélyi adatszolgáltatás lekérdezés mellett és ellen is érvek. Végül a jogszabályban is látható megoldás született, hogy nem gyűjtünk magánszemélyre vonatkozó adatokat, és nincs magánszemélyeknek regisztrálási lehetősége sem a rendszerben.
> 
> Csak érdeklődnék, hogy milyen hozzáadott értéket látsz abban, hogy a magánszemély le tudja kérdezni az adatszolgáltatást?

Engem érdekelne, hogy mi szólt mellette és ellene?
Nem feltétlen kellene magánszemélyre vonatkozó adatot gyűjteni ahhoz, hogy lekérdezhető legyen.
Igazából csak azért vetettem fel a témát, hogy - ha lenne rá hajlandóság, hogy ilyen irányú fejlesztés megvalósuljon - már tartalmazza az XSD az ehhez szükséges mezőket, mielőtt azt véglegesítenék.

**Comment by lvitya586** [comment]
> 
> 
> Itt az az alapvető probléma, hogy az Áfa törvény szerint a számla kötelező adattartalma a vevő neve és címe. Ugyanakkor szerintem nagyon logikusan a magánszemélyek esetén ezen adatok nem kerülhetnek be az adóhivatal adatszolgáltatási rendszerébe. Ezen adatkör nélkül pedig az adatszolgáltatás nem lehet az elektronikus számla is. Tehát ebben az esetben az adatszolgáltatáson kívül kell előállnia az elektronikus számlának.

Mi a helyzet a közüzemi/szolgáltatói számlákkal? A személyes véleményem az, hogy sokkal egyszerűbb lenne a polgárok élete, ha egyetlen felületen tudnák kezelni a számláikat és nem kellene csillió féle rendszert kezelni.

**Comment by lvitya586** [comment]
> 
> 
> Jelentősebb volt az adatvédelmi aggály és az ezzel együtt járó problémahalmaz, mint az az előny, hogy a magánszemély meg tudja nézni az adatszolgáltatásokat. A magánszemélyeknél a jelentős probléma az, hogy nem tudjuk motiválttá tenni őket, hogy nyugtát, vagy számlát kérjenek. Ebben az adatszolgáltatás megnézésének lehetősége sem feltétlenül sokat segít. Ezzel szemben az adatvédelmi aggályok súlyosabbak voltak.
> 
> A közüzemi számlák a magánszemély adatainak védelme szempontjából ugyan olyanok, mint bármely más számla lenne. A személyes adatok védelme nem csupán egy orvosi, ügyvédi számlánál fontos, hanem a közüzemi számláknál is.

Szigorúan saját vélemény, de sokkal egyszerűbb lenne, ha megszűnne a nyugta és mindenről számlát kéne adni. Így nem kell motiválni a magánszemélyeket, hogy kérjenek számlát, mert automatikusan azt kapnának. Továbbá sokkal egyszerűbb lenne az élet, ha az ügyfélkapun belépve egy felületen láthatóvá válna az összes számla függetlenül attól, hogy szolgáltató, orvos, ügyvéd, stb. állította ki. Egyszersmind az állam őrizné meg ezeket a számlákat az elévülési idejükig.

**Comment by fzoli15** [comment]
> Szigorúan saját vélemény, de sokkal egyszerűbb lenne, ha megszűnne a nyugta és mindenről számlát kéne adni. Így nem kell motiválni a magánszemélyeket, hogy kérjenek számlát, mert automatikusan azt kapnának. Továbbá sokkal egyszerűbb lenne az élet, ha az ügyfélkapun belépve egy felületen láthatóvá válna az összes számla függetlenül attól, hogy szolgáltató, orvos, ügyvéd, stb. állította ki. Egyszersmind az állam őrizné meg ezeket a számlákat az elévülési idejükig.

Azért az nem lenne jó, ha Tesco pénztárnál minden vevő részére számlát kellene kiállítania a pénztárosnak. Szerintem a nyugtának van létjogosultsága.
De azzal a gondolattal egyetértek, hogy jó lenne, ha minden számla egyetlen központi nyilvántartásban elérhető lenne, és egy helyről le tudná tölteni mindenki (akár cég, akár magánszemély) a részére kiállított számlákat.

**Comment by lvitya586** [comment]
> Azért az nem lenne jó, ha Tesco pénztárnál minden vevő részére számlát kellene kiállítania a pénztárosnak. Szerintem a nyugtának van létjogosultsága.

Elnézést, ha offtopic a téma, de én speciel rendszeresen vásárolok az említett egységben és ezt kizárólag clubcard használatával teszem, így a név és cím eleve adott. De pl. a karámban (önkiszolgáló pénztár) a kedves vevő be is tudja pötyögni ezeket az adatokat. Vagy ha visszatérő a vevő, akkor kérhet kódot, amire rá lehetne tenni pl. egy vonalkódot, amit lecsippantva szintén megvan az adat és még pötyögni sem kell, csak egyszer a kód létrehozásakor.

**Comment by alaplap** [comment]
Off Topic.

> nem külső hitelesítő adja az előállított PDF-hez az elektronikus aláírást és opcionálisan az időbélyeget, hanem a NAV adatszolgáltatásba feltöltött hash garantálja a hitelességet

Ez (is) elkerülte eddig a figyelmemet. Hol találok erről az e-számla megoldásról bővebb információt?

**Comment by fenyvessy** [comment]
@alaplap : 1/2018. (VI. 29.) ITM rendelet 7. §

**Comment by NTCA-tax** [comment]
Ezt a topicot lezárom, ha felmerülne újabb kérdés, akkor inkább nyissatok újat.
