### ISSUE TITLE
[Q&A]XSD 3.0 privatePersonIndicator

### ISSUE THREAD

**Issue by fzoli15** [nav-gov-hu/Online-Invoice#354]
A changelog alapján az új privatePersonIndicator jelző töltése így elsőre elég bonyolult feladatnak látszik.

Pl. ha jól értem, akkor az adószámos magánszemély és az egyéni vállalkozó itt nem minősül majd magánszemélynek, mert van adószáma, és a changelog alapján "ha a vevő magánszemély akkor ....  vevő adószámot (customerVatData) tartalmazó csomópont nem adható meg", tehát nem magánszemélyként kell jelölnünk, hogy az adószámot be tudjuk küldeni. 
Kérdés: Ebben az esetben a - jogilag egyébként magánszemélynek minősülő - vevő nevét és címét is be kell küldeni?

Nem mondhatjuk, hogy NAV online 3.0 értelemben az a magánszemély, akinek nincs adószáma, mert ahogy írtátok, pl. a gazdasági tevékenységet nem folytató társasház, egyesület, stb. nem minősül magánszemélynek.
Az eddigi infók alapján tehát valóban nehéz vagy lehetetlen erre tökéletes algoritmust írni. 

Javasoltátok, hogy a felhasználó adja be ezt a jelzőt. Ezzel az a gond, hogy a sokéves tapasztalat azt mondatja velem, hogy a számlázó szoftver (vagy ERP) kódokban felhalmozott "üzleti tudás" általában magasabb szintű szokott lenni, mint a (jogi, adózási, számviteli, stb. végzettséggel nem rendelkező) egyszerű számlázó felhasználó képességei. Szerintem naiv gondolat azt hinni, hogy képesek lesznek a felhasználók ezt helyesebben kitölteni, mint egy nem tökéletes algoritmus. A bonyolult esetekkel nekik is meg fog gyűlni a bajuk, és találomra beállítják majd valahogy, plusz emellett benne van az a lehetőség, hogy a felhasználó azt is elronthatja, amit az algoritmust nem rontana el.
(off: Egyébként kis túlzással lassan ott tartunk, hogy 2 diploma kell majd ahhoz, hogy egy számlát helyesen ki tudjon állítani az ember.)

Nem vagyok a témában elég tájékozott (nekem sincs jogi diplomám), ezért kérlek segítsetek nekem, hogy pontosan miért is kell ez a jelző. Ha jól gondolom, akkor adatvédelmi okok miatt.
A GDPR a magánszemélyek személyes adatainak védelméről szól (ha jól tudom). De az adószámos magánszemély és az egyéni vállalkozó is magánszemély. Az esetükben mégis más adatvédelmi szabályokat kell alkalmazni? Ha igen, akkor pontosan hogyan van ez meghatározva, hol van leírva a pontos szabály?

Az adószám nélküli magánszemély vevő amikor számlát kér, akkor ezzel együtt beleegyezik abba, hogy a számlára rákerülnek az adatai, és azt a számlakiállító megőrzi a jogszabályi kötelezettségnek megfelelően. A számlakiállító nem semmisítheti meg vagy anonimizálhatja ezt a számlát a magánszemély kérésére sem, mert jogszabályok írják elő a megőrzést x évig. A NAV online adatszolgáltatás adattartalmát is jogszabály írja elő (ÁFA tv. 169. §), ami tartalmazza a számlán szereplő vevő nevét és címét (magánszemély esetén is!). Ez nem elég indok arra, hogy ezeket az adatokat be lehessen küldeni magánszemély esetén is?
A régi (és még most is érvényben lévő), "offline" számla XML adatszolgáltatásban is átadtuk a számlázó programból a NAV részére a magánszemélyek adatait. Ha egy ellenőrzés során fizikailag kérik be a számlákat az adóellenőrök, akkor azon is szerepelni fognak ezek az adatok. Miért más ebből a szempontból a NAV online adatszolgáltatás? Azért mert publikusan elérhető?

**Comment by connorhu** [comment]
"A régi (és még most is érvényben lévő), "offline" számla XML adatszolgáltatásban is átadtuk a számlázó programból a NAV részére a magánszemélyek adatait."

Ez csak egy apró gondolat. Szerintem ez az Adóhatósági ellenőrzési adatszolgáltatás nem lett igazítva GDPR-hoz. Lényegében mióta van nem nagyon nyúltak hozzá.

**Comment by zonehun** [comment]
Pontosan úgy van most is, ahogy @connorhu írta. Jelenleg is be kell küldenünk az adószámos magánszemély és EV adatait.

Amúgy a felvétéssel én is egyetértek. Ha lehet ne bonyolítsuk túl a már így is nehezen érthető számlázási szabályokat. Mi is látjuk a hétköznapi felhasználókat és tényleg meggyűlik a bajuk a számlák kiállításával. Jelenleg mi (számlázó és ERP szoftver fejlesztők és csapataik) tanítjuk meg nekik, hogy miként is kell számlázni.

Én amellett tenném le a voksomat, hogy az adószám döntsön. Ha van adószáma a vevőnek, akkor minden adat bemegy, ha nincs, akkor vizsgáljuk, hogy magánszemély vagy jogi személy. Ha magánszemély, akkor anonimizálunk.

**Comment by NTCA-developer** [comment]
Sziasztok!

Köszi a kérdéseket. Reagálva az eredeti felvetésre: `De az adószámos magánszemély és az egyéni vállalkozó is magánszemély. Az esetükben mégis más adatvédelmi szabályokat kell alkalmazni? Ha igen, akkor pontosan hogyan van ez meghatározva, hol van leírva a pontos szabály?`

A jog világa kicsit más mint az IT. Csomó mindent explicit várnál leírva, miközben valójában csak implicit következik az egyik állítás a másikból. Magánvéleményem szerint jelen esetben a megoldás ott van, hogy személyhez fűződő jogai csak természetes személynek vannak, így az adatvédelem (és GDPR és a többi) is csak abban az esetben alkalmazhatók rá nézve, ha az ügyletben ilyen minőségben, nem pedig ÁFA alanyként vesz részt. A jelölőnek pedig pont az az értelme, hogy a NAV csak ennek a birtokában tud kötelezettséget vállalni arra, hogy az esetleges számlázási tévedéseket kivédje.

De @NTCA-tax elmondja a PC megoldást.

**Comment by NTCA-tax** [comment]
A kérdésekben is több minden keveredik, megpróbálok minden kérdésre, felvetésre és aggodalomra válaszolni.

Az Áfa törvény szellemiségében vannak adóalanyok és nem adóalanyok. A "nem adóalany" fogalma alá tartoznak például a gazdasági tevékenységet nem folytató társasházak, egyesületek, de a magánszemélyek is. Amennyiben egy gazdasági tevékenységet nem végző entitás a vevő, akkor ott nincs olyan személyes adat, amit különösen védeni kellene, azok bejönnek adatszolgáltatásba. Ugyanakkor nem feltétlenül lesz adószámuk. Például egy gazdasági tevékenységet nem végző társasháznak nem feltétlenül van adószáma, de attól neve, címe van, amit a számlán is fel kell tüntetni, és az adatszolgáltatásba is be kell nyújtani.

A magánszemély némelyike bonyolult tud lenni, nem beszélve az adózási szempontokról. Amennyiben egy magánszemélynek egyéni vállalkozóként folytat gazdasági tevékenységet, akkor a vállalkozási tevékenységéhez történő beszerzéseknél a megadja az adószámát. Ebben az esetben nem mint magánszemély, hanem mint adóalany van jelen, és így a számlán és az adatszolgáltatásban is benne kell lennie a nevének, címének, adószámának. Ugyan ez a magánszemély vásárol például egy TV-t a lakásába, akkor azt nem a vállalkozói tevékenysége miatt teszi (legalább kellene elszámolnia a vállalkozásához), ezért nem adja meg az adószámát az értékesítőnek. Az értékesítő ebből azt a következtetést vonja le, hogy a vevő magánszemély, és bár a számlán (ha a vevő kér egyáltalán számlát) szerepel a neve, címe, ugyanakkor az adatszolgáltatásában nem. 

Az adatszolgáltatásban azért próbálunk minél jobban elhatárolódni a személyes adatoktól, mivel annak tárolását nem tennénk, kezelni pedig nem kezelhetjük. Nem akarunk magánszemélyeket profilozni, követni, de ennek gyanúját is messze próbáljuk elkerülni. Az adatszolgáltatás nem a magánszemélyről szól, hanem az adóalanyokról.

Az ellenőrzés egy teljesen más történet. Ott van egy megbízólevél, mely felhatalmazást ad az adóellenőr számára, hogy bármely az ellenőrzési időszakba tartozó bizonylatot megtekintsen, beemeljen az ellenőrzésébe. Nagyjából ez a legfontosabb különbség az adatszolgáltatás és az ellenőrzési adatátadás között számla adattartalom oldaláról.

Visszatérve az adatszolgáltatásra. Az is egy válasz lehet, hogy ha a vevő nem adja meg az adószámát és a név alapján magánszemély, akkor megy rá a magánszemély jelölő. Persze tudnék extrém eseteket mondani, hogy mikor van ezzel baj, de ez is egy megközelítés. Üzleti modell kérdése, hogy a magánszemélyi kört hogyan tudjuk elhatárolni. Például webáruháznál a rendelésnél is lehet nyilatkoztatni, de előfordulhat, hogy mindig szerződést kötünk a vevőinkkel és abból kiderül. Tehát nem lehet egyetlen jó megoldást mondani, hiszen mögé kell gondolni a vállalkozásnak a saját belső folyamatait. Mindenki számára tökéletes megoldás nincsen, ezt vállalkozói szinten kell mérlegelni. 

Elnézést, hogy ennyire hosszú volt a válaszom, legközelebb próbálom rövidebbre fogni...

**Comment by alaplap** [comment]
> Ott van egy megbízólevél, mely felhatalmazást ad az adóellenőr számára, hogy bármely az ellenőrzési időszakba tartozó bizonylatot megtekintsen, beemeljen az ellenőrzésébe.

Ha ez ilyen egyszerű, hogy csak a számlakibocsátótól kell kérni egy felhatalmazást ahhoz, hogy a NAV beemelhesse a számlákat az ellenőrzésbe, akkor nem lehetne az Online Számla Rendszeren keresztül a felhatalmazást bekérni a regisztrált adózóktól? Vagy elfogadtatni (a használati feltételekben), hogy a számlakibocsátó a számlaadat-szolgáltatással egyidejűleg megadja a szükséges felhatalmazást is?

Én úgy látom, hogy a jelenlegi megoldás is csak törvénymódosítással állná meg a helyét, hiszen az _23/2014. (VI. 30.) NGM rendelet_-ben a _4. Számlázó programmal szembeni követelmények fejezet 8. § (1)_ bekezdés _d)_ pontja kimondja, hogy _"A számlázó programmal szemben követelmény, hogy biztosítsa a kiállított számla, valamint számlával egy tekintet alá eső okirat legalább Áfa tv. szerinti kötelező adattartalmának az állami adó- és vámhatóság részére történő, 13/A-13/B. § szerinti elektronikus úton történő továbbítását."_. A _2007. évi CXXVII._ "ÁFA törvény" _X. Fejezet 169. §  e)_  pontja pedig kimondja, hogy _"a termék értékesítőjének, szolgáltatás nyújtójának, valamint a termék beszerzőjének, szolgáltatás igénybevevőjének neve és címe"_ kötelező adattartalom.
Ha már úgyis törvénymódosítás szükséges, nem lehetne inkább azt elérni törvénymódosítással, hogy a magánszemélyeknek kiállított számlák adatszolgáltatásában a termék beszerzőjének, szolgáltatás igénybevevőjének neve és címe is szerepelhessen? 

A NAV amúgy is kezeli a magánszemélyek személyes adatait, már most is. Bár nem vagyok én sem jogász, de szerintem jó példa erre az, hogy évente megkapom az adóbevallást postai úton, a nevemre címezve, tehát most is tudják a nevemet és címemet. Ráadásul a fizetésemet is tudják, hiszen kitöltik helyettem elektronikusan az adóbevallást.
Az online pénztárgépeken való nyugta sztornózásakor is meg kell adni a vevő nevét és címét.

**Comment by alaplap** [comment]
> Ott van egy megbízólevél, mely felhatalmazást ad az adóellenőr számára, hogy bármely az ellenőrzési időszakba tartozó bizonylatot megtekintsen, beemeljen az ellenőrzésébe.

Az Online Számla Rendszer indulásával illetve a számlaadat-szolgáltatással elkezdődött egy véget nem érő ellenőrzési időszak. :)

**Comment by NTCA-tax** [comment]
@alaplap , szerintem Te sem örülnél felhőtlenül, ha az adóhivatal annyi mindent tudna rólad, mint amit fent leírtál. Mint magánszemély, jelenleg tudjuk a lakcímedet, ismerjük hol dolgozol, mennyit keresel, tudunk szja bevallást kiajánlani Neked. A számlaadat egy teljesen más adatkört jelent, melynek nem biztos, hogy sok köze lenne a magánszemély adózásához. Amennyiben a számlaadatokat is beemelnénk, akkor az adóhivatal tudna arról, milyen orvosi kezelésekre jársz, milyen ügyvédi szolgáltatást vettél igénybe, vagy éppen milyen termékeket szoktál vásárolni. Ezt adóhivatali oldalon egyrészt nem akarjuk látni, másrészt a lehetőségét is el akarjuk kerülni, hogy magánszemélyeket profilozzunk. És ez nem jogszabály módosításról szól, hanem egy nagyon fontos alapelvi kérdés.

**Comment by alaplap** [comment]
> Ezt adóhivatali oldalon egyrészt nem akarjuk látni, másrészt a lehetőségét is el akarjuk kerülni, hogy magánszemélyeket profilozzunk.

Hát ne tegyétek. Ne teremtsétek meg a lehetőséget a háttérrendszerben erre. (Csak egy példa: a rendőrségnél használt rendszerben is le lehet kérdezni ügyek adatait, de látják, hogy ki mit kér le. Ha valaki olyan ügy adatát/adatait kéri le, amihez nincs is köze a munkája révén, akkor bizony nagyon megütheti a bokáját.)
Egyébként erre is van más lehetőség: legyen mindenhol kötelező az online pénztárgép és ha anonim akarok eljárni mondjuk az ügyvédemnél, akkor csak nyugtát kérek. Mert amúgy is 99%-ban egy magánszemély nem vásárol számlára. Vagy lehessen anonim számlát kérni magánszemélyként.

De elfogadom, ha így marad. Csak jelenlegi formájában így nem fog a számlázóprogram megfelelni a törvényi előírásoknak.

**Comment by fenyvessy** [comment]
Nekem erről inkább a klasszikus "vadász, vadász, te .... jársz ide" jut eszembe, de vannak akik szeretnek veszélyesen élni :) Mindenesetre ez opt-in jelleggel kivitelezhető lesz annak, aki tényleg akarja, ráadásul nem is kellenek hozzá jelentős módosítások. Ha kiváltasz egy adószámot, és adószámos magánszemélyként veszed igénybe a szolgáltatást, akkor be fognak menni az adatok, és lekérdezhető is lesz. Ez a megoldás szerintem kb. minden elvárásnak megfelel, mert a többségnek nem kell aggódni a NAV profilozás miatt, aki meg mindent megtesz annak érdekében, hogy a NAV birtokába kerüljenek az adatai, annak adott a lehetőség rá.  @NTCA-tax, rosszul gondolom?  Tudom, hogy nem erre van kitalálva az adószámos magánszemély, de van valami törvényi akadálya annak, hogy erre is legyen használva?

**Comment by alaplap** [comment]
@fenyvessy jól érzem, hogy félig-meddig a magánszemély általi Online Számla Rendszer elérhetőség és számla lekérdezés témára gondoltál? Mert arra lehet leírtál egy jó megoldást. #353

**Comment by fenyvessy** [comment]
@alaplap Igen arra is, csak mintha ebben a szálban lett volna jobban kifejtve ez a téma.

**Comment by fzoli15** [comment]
> Az adatszolgáltatásban azért próbálunk minél jobban elhatárolódni a személyes adatoktól, mivel annak tárolását nem tennénk, kezelni pedig nem kezelhetjük. Nem akarunk magánszemélyeket profilozni, követni, de ennek gyanúját is messze próbáljuk elkerülni. Az adatszolgáltatás nem a magánszemélyről szól, hanem az adóalanyokról.
> 
> Az ellenőrzés egy teljesen más történet. Ott van egy megbízólevél, mely felhatalmazást ad az adóellenőr számára, hogy bármely az ellenőrzési időszakba tartozó bizonylatot megtekintsen, beemeljen az ellenőrzésébe. Nagyjából ez a legfontosabb különbség az adatszolgáltatás és az ellenőrzési adatátadás között számla adattartalom oldaláról.

@NTCA-tax A PTGSZLAH adatszolgáltatásban jelenleg be kell küldenünk a NAV részére a nyugta helyett kiállított számlákról a magánszemély vevők nevét és címét. Ebben az esetben ugyanúgy nincs szó ellenőrzésről, megbízólevélről, mint a NAV online adatszolgáltatásnál. Szerintem a magánszemélyek személyes adatainak kezelése és védelme szempontjából a NAV online adatszolgáltatás és a PTGSZLAH adatszolgáltatás azonos megítélés alá kellene, hogy essen.
Ezek tükrében várható, hogy a PTGSZLAH adatszolgáltatásban is anonimizálni kell majd a számlákat? 
Egyébként szerintem 2021.01.01-től feleslegessé válik a PTGSZLAH adatszolgáltatás, mert a NAV online adatszolgáltatásban úgyis be fogunk küldeni minden számlát. Várható, hogy 2021.01.01-től megszűnik a PTGSZLAH?

**Comment by NTCA-tax** [comment]
A PTGSZLAH nyomtatvány az adatszolgáltatás kiterjedésével ténylegesen feleslegessé fog válni, ezért a megszűnése várható.

**Comment by NTCA-developer** [comment]
@fzoli15 mit gondolsz, lezárható, vagy van még bennünk téma?

**Comment by alaplap** [comment]
@NTCA-developer Még van egy nyitott kérdés. 

Hogyan lesz feloldva az ellentmondás, ami abból adódik, hogy a törvényi előírás\* a számlázó programoktól legalább a számla kötelező adattartalmát várja el a számlaadat-szolgáltatásban, míg az interfész specifikáció tiltja magánszemélyek nevének és címének a bejelentését?

\* 23/2014. (VI. 30.) NGM rendelet 4. Számlázó programmal szembeni követelmények fejezet 8. § (1) bekezdés d) pontja, valamint 4/A. *  Számlázó programok adatszolgáltatása fejezete 13/A. § (1) bekezdés.

**Comment by fzoli15** [comment]
@alaplap Az ÁFA tv. 2021.01.01-től hatályos változatában a 10. számú melléklet 2. bekezdésébe bekerült ez a kivétel:
> Nem adóalany természetes személy részére kibocsátott számla, számlával egy tekintet alá eső okirat esetében az adatszolgáltatás nem terjed ki a termék beszerzőjének, szolgáltatás igénybevevőjének nevére és címére.
Mondjuk ha az általad hivatkozott 23/2014. (VI. 30.) NGM rendeletet nézzük, akkor valóban fennáll az ellentmondás.

**Comment by jozanesz** [comment]
> 
> Hogyan lesz feloldva az ellentmondás, ami abból adódik, hogy a törvényi előírás* a számlázó programoktól legalább a számla kötelező adattartalmát várja el a számlaadat-szolgáltatásban, míg az interfész specifikáció tiltja magánszemélyek nevének és címének a bejelentését?

Ezt mondja [majd ](http://njt.hu/cgi_bin/njt_doc.cgi?docid=111467.357209) a törvény (de igen rosszul eltalált pontban és cím alatt):
>Nem adóalany természetes személy részére kibocsátott számla, számlával egy tekintet alá eső okirat esetében az adatszolgáltatás nem terjed ki a termék beszerzőjének, szolgáltatás igénybevevőjének nevére és címére.

Ennek valóban ellentmond az NGM rendelet, de az amúgy rég hatálytalan GKM rendeletre is hivatkozik, úgyhogy githubra a jogalkotást is! :)

**Comment by fzoli15** [comment]
@NTCA-developer Részemről zárható az issue. A kérdéseimre választ kaptam. A jogi ellentmondásokat meg majd gondolom rendezi a jogalkotó...
