### ISSUE TITLE
[Q&A] XSD 3.0 advanceData

### ISSUE THREAD

**Issue by fzoli15** [nav-gov-hu/Online-Invoice#355]
A changelog-ban látok némi ellentmondást az advanceData töltésével kapcsolatban:

> Az ÁFA bevallások készítéséhez szükség van az előlegszámla-végszámla kérdés rendezésére is. A 3.0-ás sémában sorszinten átalakul az előleg jelzés kezelése, és egy új, advanceData csomópontban lehetőség lesz megadni végszámla esetén - sorszinten - az előleget tartalmazó számla sorszámát, a teljesítés időpontját, valamint az alkalmazott árfolyamot.

> új ERROR: ha az advancePayment értéke true, akkor az advancePaymentData csomópont megadása kötelező

> Ha a számlasor előleg adotokat tartalmaz, akkor azokat új Xpath alatt, a line/advanceData alatt adhatod meg. Figyelj rá, hogy ha van előleg adat (advanceIndicator=true) akkor az advancePaymentData csomópont alatt kötelező megadnod az előleg számla sorszámát (advanceOriginalInvoice), az előleg fizetés időpontját (advancePaymentDate) és az alkalmazott árfolyamot (advanceExchangeRate).

1.) "advancePayment" nevű element-et nem látok az XSD-ben. Ez advanceIndicator akart lenni?

2.) Az advanceIndicator 'true' értéket vesz fel az előlegszámlák tételeinél is, nem csak a végszámla előleg beszámítás soránál. De logikailag nem látom értelmét annak, hogy az előlegszámlánál is töltsük az advanceData-t, illetve ezzel egyezik az első idézet is. Most akkor mi az elképzelés?

**Comment by laladisc** [comment]
Egyetértek. Az advancePaymentData csak végszámla készítésekor vagy előleg beszámításakor tölthető ki az advanceIndicator jelölése mellett. Előleg számla készítésekor pedig csak az advanceIndicator-t lehet jelölni.

**Comment by NTCA-developer** [comment]
Sziasztok!

Köszi a felvetést, ezt megvizsgáljuk. Gyanítom hogy igazatok van és rossz a szabály amit leírtunk, de visszajelzek.

**Comment by rtoth0407** [comment]
Végszámla készítésekor csak a beszámított előleg összegét kell megjeleníteni a számlán, és nem kötelező összekötni az előlegszámlával. Nagyon sok számlázó rendszerben ez az összekötés szinte megoldhatatlan.
Lehetne opcionálisra állítani advanceData-t?

**Comment by omachtandras** [comment]
> 
> 
> Végszámla készítésekor csak a beszámított előleg összegét kell megjeleníteni a számlán, és nem kötelező összekötni az előlegszámlával. Nagyon sok számlázó rendszerben ez az összekötés szinte megoldhatatlan.
> Lehetne opcionálisra állítani advanceData-t?

Az lenne a kérdésem, hogy ha nincs összekötve, akkor hogy ellenőrzi a szoftver, hogy nem "használnak túl" egy előleget a végszámlák készítése során?
Én azt gondolom, hogy jó ez a megközelítés, igenis legyen kapcsolat, akkor lehet látni, hogy mi történik, véletlenül sem gépel el egy adatrögzítő egy összeget, pontosan tudható, hogy melyik előleget melyik számlába tudtuk be, melyikből mennyi a még felhasználható, stb. stb.

**Comment by rtoth0407** [comment]
Igen, ha készítünk egy számlázó programot a magyar piacra, akkor valóban célszerű belerakni ilyen ellenőrzéseket az előleg kezelésbe. De azért vannak integrált rendszerek nagy vállalatoknak és nemzetközi cégeknek és azokban egyáltalán nem könnyű megoldani a magyar szabályok szerinti előlegkezelést, amely már így is lényegesen bonyolultabb a nemzetközi gyakorlatnál. Egy ilyen plusz adatszolgáltatási elvárás miatt sok helyen több hónapos rendszer átalakítási projektet kell indítani. Olyan adatot nem szabadna kötelezően bekérni amelynek nem kell szerepelnie a számlán.

**Comment by NTCA-developer** [comment]
Sziasztok!

Ígértem visszajelzést. Igazatok van, a changelog által említett ERROR nem valid. Töröltem a dokumentációból, a fejlesztésbe pedig nem került be. Mindjárt adok fel pullt.
