### ISSUE TITLE
[Q&A] - hol található a  changelog a v3.0-hoz?

### ISSUE THREAD

**Issue by hamvasgy** [nav-gov-hu/Online-Invoice#356]
Az Issues között látok hivatkozásokat a v3.0 changelog-ra, de nem tudom, hogyan lehetne hozzáférni. Ebben kérek segítséget (pl. egy linket)
A https://onlineszamla.nav.gov.hu/dokumentaciok és a https://onlineszamla-test.nav.gov.hu/dokumentaciok helyen még nincs fent az API dokumentáció

**Comment by NTCA-supporter** [comment]
Szia!

Egyelőre a githubon publikált changelog van, ezt itt találod:
https://github.com/nav-gov-hu/Online-Invoice/blob/master/src/schemas/nav/gov/hu/OSA/CHANGELOG_3.0.md

A hivatalos interfész dokumentáció folyamatban.
Üdv

**Comment by hamvasgy** [comment]
Szia,

Köszönöm. 
Angol nyelven is előbb elkészül és elérhető lesz a changelog mint az interfész dokumentáció?

Üdv.

**Comment by NTCA-supporter** [comment]
Szia!

Igen.

Üdv

**Comment by hamvasgy** [comment]
Mikorra várható az angol nyelvű changelog?
Vagy kaphatok erre az issue-ra bejegyzést ha elkészül?
Köszönöm

**Comment by NTCA-supporter** [comment]
Jelzek majd, már folyamatban van a fordítás, így túl sokat remélhetőleg nem kell rá várni.
Üdv

**Comment by NTCA-developer** [comment]
Sziasztok! Publikáltuk az angol nyelvű changelogot is. Ezt lezárom.
