### ISSUE TITLE
Konyveles nem latja a kiallitott szamlakat

### ISSUE THREAD

**Issue by unixgirl** [nav-gov-hu/Online-Invoice#357]
Az ügyfél regisztrált az onlineszamla.nav.gov.hu oldalon, már állított ki számlákat desktop-on, viszont amikor belépett nálunk (könyvelő iroda) a főkönyvelő gépén, a már kiállított számlák nem látszódnak, ellenben az ügyfél mobiltelefonján látszodnak a számlák. Könyvelés céljából ki kellene nyomtatni számlákat, ami a hiba végett nem lehetséges mert az online felületen nem jelennek meg a számlák. Ebben a kérdésben esetleg tudni valaki segíteni, hogy mi lehet a baj?

**Comment by NTCA-supporter** [comment]
Szia @unixgirl !
Ez így sajnos kevés információ, azt remélem te is érzed :)
Kezdjük azzal, hogy az Online Számla felületés történt kézi rögzítés, vagy az Online Számlázóban lettek kiállítva számlák?
A frontenden amikor a kimenő számlák oldalra navigálsz, akkor történik egy szűrés az adott napra.
Küldj egy screenshotot ha nagyon nem megy, persze szenzitív adatok nélkül!

Üdv

**Comment by unixgirl** [comment]
Szia, persze tudom, hogy kevés az info csak egyenlőre nekem sem áll több info a rendelkezésemre. A főkönyvelővel beszéltem, és azt mondta, hogy az ügyfél,hogy  az online számla felületén történt a kézi rögzítés. Nem nem történt szűrés egy adott napra sem. Belépéskor baloldalon található "számláim" menüre kattintva kellene hogy megjelenjenek a kiálított számlák. Legalábbis most a főkönyvelő gépén ezt látom amikor belépek. Viszont ugyanezt már nem látni amikor belép az ügyfél a user/pass adatokkal. A "számláim" menüpont ra klikkelve nem jelenik meg számla.  Screenshotot nem tudok küldeni, mert nincs jelen az ügyfél és a  főkönyvelő nem kezeli az accountját. A baj, hogy én már látom, hogy ez valami user issue lesz, és nehéz az ügyféllel kommunikálni. :) Bármi kérdés van szóljatok és beszélek az ügyféllel. Köszi

**Comment by unixgirl** [comment]
Update - onlineszamla.nav.gov.hu oldalon belép az ügyfél, és Ő a "számlaadat rögzítés" menüben viszi fel a számlákat. Ezek a számlák miként hívhatóak elő? Illetve a "számláim" menüben ezek a kiállított számlák nem látszódnak, továbbá az ügyfél elmondása szerint amikor vásárol azok a számlák sem jelennek meg nála.

**Comment by NTCA-developer** [comment]
@unixgirl 

Az nem lehetséges, hogy az ügyfél másodlagos felhasználóval lép be, akinek nincs jogosultsága valamihez?

**Comment by fzoli15** [comment]
Az a probléma, hogy a szerencsétlenül választott elnevezések miatt keveredik az ügyfeleknél az Online Számlázó és az Online Számla rendszer fogalma. 
Ha jól értelmezem a @unixgirl által leírtakat, akkor ők számlát akartak kiállítani, amit az Online Számlázóban kellett volna megtenniük. Ehelyett az Online Számla felületen a "számlaadat rögzítés" menüpontban próbálkoztak, ami ugyebár nem számlakiállításra való, hanem az Online Számla adatszolgáltatás manuális teljesítésére. Emiatt nem találják a számlát, és nem tudják kinyomtatni, hiszen nem is állítottak ki számlát, csak egy adatszolgáltatást rögzítettek.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ez a probléma még aktuális?
Ha nem akkor zárjátok az issuet kérlek.

Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet. Ha van még kérdés nyissátok újra nyugodtan.
Üdv
