### ISSUE TITLE
[Q&A]

### ISSUE THREAD

**Issue by Tonee1111** [nav-gov-hu/Online-Invoice#358]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
[Teszt 2.0] Mitől lehet az ha állandóan Content not allowed in prolog üzenetet kapok managinvoice esetén ? Net alapján UTF-8 spec karakter van valahol de ezeket eltüntetve sem müködött ugyanaz a hiba. 
Pár transaction id:
33JO3EWYGFAP4WWW
33JNZ066B830C81Z
33JMG6O02OQB56BQ

**Comment by EPluribusUnum** [comment]
Tipp : Valójában "HTTP/1.0 404 Not Found" vagy egyéb "palin text" üzenetet kapsz vissza ami nem xml, és mivel hiba volt, megpróbálsz a GeneralErrorResponse objektumot gyártani belőle és a "Content not allowed in prolog" üzenetet a JaxB Unmarshaller dobja mikor nem bírkózik meg a ezzel a konvertálással.

**Comment by Tonee1111** [comment]
Igazából én a manageinvoice requestemre kapok egy jó kövér OK-ot vissza csak az online felületen mint adatszolgáltatás látom ezt a hibát.
![image](https://user-images.githubusercontent.com/70951464/92924893-f2150b00-f439-11ea-9e33-250ab209849b.png)

**Comment by Tonee1111** [comment]
Hát kérdésként inkább lezárom átvittem dev support kérésbe
