### ISSUE TITLE
[FEATURE] WARN/ERROR üzenetek esetén részletesebb leírás

### ISSUE THREAD

**Issue by ragnud830** [nav-gov-hu/Online-Invoice#36]
**Az igény összefoglalása / Summary of the request**
Az Online számla interfész rengeteg típusú WARN/ERROR üzenetet küldhet vissza. Az ügyfeleink döntő hányada ha egy ilyen választ lát, gyakorlatilag pánikolva hívja az support-ot, hogy gond van az interfésszel és azonnal megoldást várnak a problémára. Ez a pánikhangulat legtöbbször pillanatok alatt orvosolható, ha megadják számunkra a kapott figyelmeztetés és/vagy hiba kódját, amelyre a dokumentációban rákeresve részletesebb információt tudunk bizotsítani számukra, hogy az ő konkrét esetükben ez mit jelent. Lassan 1 év után se sikerült még rászoktatni az ügyfeleket arra, hogy a NAV hivatalos dokumentációját megnyissák és a részletesebb magyarázat, teendők segítségével maguk is feltárják a WARN/ERROR üzenetek jelentését, arról nem is beszélve, hogy ezek folyamatosan változ(hat)nak, ahogy egyik-másik megszűnik, miközben újabbak kerülnek bevezetésre. 
Sokat javíthatna/gyorsíthatna az ügyfeleknél történő problémakezelésben, ha a rövid leírás mellett
az API a válaszában visszaadná a Működés/Teendő mezőben leírtakat is.

**Példa**: 530-as azonosítójú WARN üzenet (pdf 129. oldal)
Ezt kapjuk vissza az interfészen keresztül:
    Kód: INCORRECT_HEAD_DATA_FISCALREPRESENTATIVE
    Szöveg: Hibás pénzügyi képviselő adat.

Viszont ebből szerencsétlen könyvelő nem fogja tudni, hogy azért hibás, mert a megyekód nem 51, ugyanis ez a kiegészítő információ már csak a Működés részben van megadva.

Az előzőhöz hasonlóan a Technikai hibakódok, a Validációs hibakódok esetén is hasznos lenne a részletes leírás, teendők visszaadása.

**Az általam javasolt megoldás / The solution I propose**
Olyan dokumentációs felület kialakítása a jelenlegi pdf helyett, ahol egy egyszerű GET paraméterrel megadható a <validationErrorCode> tag-ben érkező azonosító. Így egyszerűen összeállítható egy link, amivel egyből a dokumentáció megfelelő részére ugorhatnánk.

**Elfogadható alternatívák / Acceptable alternatives**
A businessValidationMessages, technicalValidationMessages, errorCode stb. részben visszaküldésre kerülne vagy a teljes link, amely a dokumentáció megfelelő helyére mutatna; vagy a jelenleg a pdf-ben megtalálható Működés/Teendő mező tartalmát adná vissza az interfész.

**Comment by NTCA-developer** [comment]
Szia!

Köszönjük szépen a felvetést.

Több megoldási lehetőséget is átbeszéltünk, de a végén mindig az jött ki, hogy a legegyszerűbb ha a message-ben visszaadott leírásokat olyan beszédes leírással látjuk el, amiből a végfelhasználóknak az is kiderül, hogy mi a teendő az adott WARN esetén. Ezt átdolgozzuk a 2.0-ban.
