### ISSUE TITLE
[Q&A] INCORRECT_SUMMARY_DATA_INVOICE_NET_AMOUNT nullás számlán

### ISSUE THREAD

**Issue by Amn3s1a2018** [nav-gov-hu/Online-Invoice#360]
**A fenti WARN érkezik látszólag teljesen ok számlákra**

Abban az esetben ha egy terméket akciósan (jelen esetben teljesen ingyen) adunk és nem tartozik hozzá egyéb értékesítés, az eladott termék/szolgáltatás  áfáját meg kell fizetni. Ezt úgy oldjuk meg, hogy a kedvezményt áfakörön kívüli tételként szerepeltetjük, ennek pedig egyenes következménye, hogy a nettó összesen valóban negatív lesz (az áfa összegével)

A kérdés az lenne, kezelhető-e ez az eset a NAV oldalán? Pl. bizonyos peremfeltételek teljesülésekor elnyomni a figyelmeztetést. Esetleg tudjuk-e ezt a mi oldalunkról úgy adminisztrálni, hogy ne kapjunk WARN-t. (pl. ha csak a nettó kedvezményt vonnánk le az eredeti (CREATE) számlán és a maradékot egy helyesbítő számlán azzal talán elkerülnénk a figyelmeztetést, de ez a megoldás nem elfogadható).

**Comment by szecsenyizoltan** [comment]
Jobb megoldás a teli ár valamint egy extra tétel ami kedvezmény és a teli árral azonos, de ellenkező előjelű tétel. Mindez adózási szempontból, ugyanis sok esetben az ajándék SZJA köteles lenne valamint kérdéseket vethet fel, hogy miért értékest egy cég beszerzési ár alatt.

**Comment by Amn3s1a2018** [comment]
Pont erről van szó, hogy a kedvezmény egy külön tétel, és nem áfás. A pozitív tételre meg kell fizetni az ÁFÁt, a kedvezmény után pedig nem igényelhető vissza, a két tétel bruttó azonos, de ÁFÁt csak az eladásra számolunk amitől az összesen nettó tényleg negatív. Jó lenne ezt a warningot vhogy felokosítani. Pl. nulla vagy pozitív végösszegre ne adja... Lenne még ötletem, pl. elnyomi ezt a warningot a mi oldalunkon, bizonyos feltételek mellett, de nem igazán tetszik, ahogy az sem, hogy minden ilyen számlát valakinek külön okézni kell.

**Comment by NTCA-tax** [comment]
Ezt a problémát 2.0-ban nem lehet warning mentesen megoldani. A 3.0-ban ezekre az ügyletekre már lesz külön jelölő, amivel szét tudjuk választani a számszaki hibákat az ingyenes ügyletektől.
