### ISSUE TITLE
[DEV support]

### ISSUE THREAD

**Issue by Tonee1111** [nav-gov-hu/Online-Invoice#361]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[X] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[X] 2.0
[] 3.0

**A requestId értéke / requestId value**
```

```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**

Kérdésként nem igazán kaptam választ szóval kérlek nézzetek rá hogy mi lehet a baj?
A manageinvoice requestemre kapok egy OK-ot vissza csak az online felületen mint adatszolgáltatás látom ezt a hibát.
image
![image](https://user-images.githubusercontent.com/70951464/92991576-21cd1d00-f4e5-11ea-814a-37626bdaf76d.png)

```<ManageInvoiceResponse xmlns="http://schemas.nav.gov.hu/OSA/2.0/api" xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/data">
  <header>
    <requestId>BEPUMP200911141559</requestId>
    <timestamp>2020-09-11T12:15:59.000Z</timestamp>
    <requestVersion>2.0</requestVersion>
  </header>
  <result>
    <funcCode>OK</funcCode>
  </result>
  <software>
    <softwareId>HU8393225264BEPUMP</softwareId>
    <softwareName>BePump</softwareName>
    <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
    <softwareMainVersion>20180701.01</softwareMainVersion>
    <softwareDevName>Csiszár Antal</softwareDevName>
    <softwareDevContact>dle943@gmail.com</softwareDevContact>
    <softwareDevCountryCode>HU</softwareDevCountryCode>
    <softwareDevTaxNumber>8393225264</softwareDevTaxNumber>
  </software>
  <transactionId>33JXM93JXVDTFKOP</transactionId>
</ManageInvoiceResponse>```

*Egyéb tartalom / Additional content*

**Comment by Tonee1111** [comment]
Jó lenne egy kis segítség, mert mindent mindennel összenéztem és nem vágom mi a nem jó az xml-el

**Comment by NTCA-supporter** [comment]
Szia @Tonee1111!

Megnéztem a beküldött a request xlt-t és az a gond, hogy a invoiceData duplán van base 64 kódolva és csak egyszer kell.

**Comment by Tonee1111** [comment]
Szia,

 Köszi, megnézem hogy sikerült ezt elkövetnem. Visszajelzek ha megvan.

**Comment by Tonee1111** [comment]
Szia, valóban elég banális hiba volt. Meglett. Köszönöm sokat segítettél. Zárom is.
