### ISSUE TITLE
Rossz adószám

### ISSUE THREAD

**Issue by robozb** [nav-gov-hu/Online-Invoice#362]
Sziasztok! 

Kérlek segítsetek, hogy lehet feloldani azt a helyzetet, hogy rossz adószámmal lett felvéve egy számla, +1 karakter az adószám törzs  szám részében. Ilyenkor a számlát nem lehet beküldeni. Lesztornozzuk, de ugye azt sem lehet beküldeni. Nem kell beküldeni ilyenkor, nem is kell? 

Köszi: Béci

**Comment by Amn3s1a2018** [comment]
Ez a törvény betűje szerint ez két számla amiről nem teljesítették az adatszolgáltatási kötelezettséget és számlánként 500e Ft-ig terjedő bírsággal sújtható. Az eljáró ellenőrnek mérlegelési  joga van, fogja látni, hogy sztornózták a számlát, nem lett kibocsátva, nyilván eltekint a bírságtól ilyen esetben.

Valamikor az első fórumok egyikén elhangzott, hogy a számlázóprogram fejlesztőjétől minimálisan elvárt annyi körültekintés, hogy nem megfelelő adószámot ne engedjen beírni, ill. ilyen adószámra ne engedjen számlák kiállítani.

Ha mégis sikerült ilyen számlákat csinálni, akkor lehet róla készíteni egy jegyzőkönyvet, amiben leírják, hogy „hopppá” ... meg valószínűleg az is jó pont ha tesznek lépéseket azügyben, hogy ne forduljon elő többet. Például a jegyzőkönyben lehet olyan, hogy „a fejlesztő ígérete szerint a következő verzióban nem lehet belföldi számlát kiállítani, ha a vevő adószáma nem megfelelő (a törzsszám nem pontosan 8 karakter vagy nem csupa számjegyből áll)”.

Nyilván technikailag megoldható, hogy a számlák (eredeti és sztornó) eltárolt adataiban javítod az adószámot, hogy legalább a formátum stimmeljen. Ha már közben eltelt némi idő és ugye készültek egyéb számlák amik rendben felmentek, akkor egy ilyen „javítás” is felvet kérdéseket. Azért töltötték fel a számlákat 3 órával később mert át kellett írni rajta az adószámot? Hát ebben a programban át lehet írni utólag a számlákat? Aztán lehet magyarázni azt is, hogy ja nem, különleges esetben csak, a fejlesztő csinálta két hardverkulccsal és a vezérigazgatótól kellett ujjlenyomat meg egy fél deci vér hozzá, stb.

**Comment by omachtandras** [comment]
Az Online Számla felületen van lehetőség kézzel rögzíteni gépi számlát, én megpróbálnám ott. Sokkal kevesebb ellenőrzés fut rá, mint a gép-gép interface-nél.

Nálunk volt olyan ügyfél, aki peres ügy miatt 2010. előtti teljesítésű számlát volt kénytelen kiállítani, már a validáción sem ment át az adat, a webes felületen viszont fel tudta tölteni gond nélkül.

**Comment by Amn3s1a2018** [comment]
> kézzel rögzíteni gépi számlát

Igen azután arról is készülhet jegyzőkönyv, hogy azért választottuk ezt a megoldást, mert „valamiért” a gép-gép interfészen nem sikerült beküldeni a számlát, aztán később meg arról, hogy „jaj nem vettük észre, hogy a webes felületen csak 8 karakter fér adószámba és a számlán valahogy véletlenül 9 volt”.

Én személy szerint biztosan nem játszanék ilyennel, az adott cég könyvelője aki eldöntheti, hogy csinálja vagy nem.

**Comment by omachtandras** [comment]
Szerintem nem véletlenül lett egy ilyen "funkció" a webes felületen. Az elsődleges célja az egész törvénynek az, hogy a kiállított számlákról adatszolgáltatás történjen. Valószínűleg kevésbé rossz az, ha - a hiba javítása mellett - ilyen módon megtörténik az adatszolgáltatás, mint az, hogy egyáltalán nem történik meg.
Én, ha ellenőr lennék biztosan megkérdezném a jegyzőkönyvet lobogtató vállalkozótól, hogy ok, hogy jegyzőkönyvezte, hogy gépi úton nem sikerült az adatszolgáltatás, de mit tett annak érdekében, hogy a konkrét számla esetén az adatszolgáltatási kötelezettsége mégis teljesüljön?

A számla ki lett bocsátva attól még, hogy utána sztornózták. Nem igaz az, hogy a sztornózás miatt akkor már nem is kell róla adatot szolgáltatni. Ráadásul, mivel vélhetőleg erről a gazdasági eseményről kiállításra került egy másik számla, annak gépi adatszolgáltatásakor meg kell hivatkozni ezt a számlát, mint előzmény számlát, mert ugyanarról a gazdasági eseményről szól.

**Comment by Amn3s1a2018** [comment]
> számla ki lett bocsátva attól még, hogy utána sztornózták

Ezen már végképp nem akarnék itt jogászkodni, pláne hogy igazán nem is értek hozzá, de a kiállítás és a kibocsátás két külön dolog. Az utóbbi kb azt jelenti, hogy oda is adtad a vevőnek, de valószínűleg a navos error már vissza is jött mire a nyomtatóból kivették a számlát, akkor meg csak nem küldték vele haza, hogy tessék vigyed, úgyse fogod tudni lekönyvelni, mert nem a te adószámod van rajta. Valahol le is van írva, hogy ilyen esetben ok, ha nem fojtatja a számlaláncot, hanem a sztornó után kiállít egy harmadik számlát mintha az lenne az első.

**Comment by NTCA-tax** [comment]
Egy megfelelően felkészített programnál ilyen esetnek nem szabadott volna előfordulnia, már az adószám rögzítésénél jobb lett volna ellenkeznie a felhasználó ilyetén akaratának. Amennyiben ezen a részen már túl van a felhasználó (és sikerült rögzítenie a számla adószámát 9 karakter hosszan), akkor kapott a kiállításnál egy azonnali error-t. Ekkor rájött a problémára, érvénytelenítette a számlát (erre is jön az error) és kiállítja helyes adattartalommal a számlát.

A hibás adószámú számla adatszolgáltatása nem volt befogadható, ezért azt nem fogjuk keresni. Viszont amit keresni fogunk, az a fenti folyamatban a harmadik számla, mely ténylegesen kibocsátásra került, mely alapján a vevő élt (vagy élhetett) a levonási jogával.
