### ISSUE TITLE
Az éles rendszerbe be lehetett küldeni rossz ÁFA összesítőt...

### ISSUE THREAD

**Issue by robozb** [nav-gov-hu/Online-Invoice#363]
Sziasztok!

Kérnék szépen segítséget! 
Az éles rendszerbe be lehetett küldeni rossz ÁFA összesítőt, a nettó és adó érték jó volt, de sajnos a bruttó értékre rossz érték lett meghatározva, viszont a rendszer nem dobott vissza hibát és rögzítették a rossz beküldést, mit lehet ilyenkor tenni, hogy lehet korrigálni?

Köszi: Béci

**Comment by NTCA-developer** [comment]
Szia @robozb 

Igen, ezek az ellenőrzések kezdettől fogva nem blokkoló hibák, WARN jön rá. Ha a számlán jó érték szerepelt és csak az adatszolgáltatás a rossz, akkor technikai érvénytelenítés (+ jóváhagyás a felületről) és az adatszolgáltatás újbóli beküldése. Ha a számla adata is rossz, akkor helyesbíted módosító számlával.

**Comment by NTCA-developer** [comment]
@robozb lezárom a ticketet. Ha van új kérdés akkor állunk rendelkezésre.
