### ISSUE TITLE
[FEATURE]Leiter Jakab

### ISSUE THREAD

**Issue by jozanesz** [nav-gov-hu/Online-Invoice#364]
Ez szemet szúrt: **ERRATIC**_ELECTRONIC_HASH_VALUE

See https://wikidiff.com/erratic/erroneous

**Comment by NTCA-developer** [comment]
Szia @jozanesz 

Köszönjük a felvetést. Igazad van, de a másik 3 annulmentReason is ERRATIC prefixes, ezen már nem szeretnénk változtatni.
