### ISSUE TITLE
[DEV support] Sikertelen számlaadat lekérés

### ISSUE THREAD

**Issue by kastonoriginal** [nav-gov-hu/Online-Invoice#365]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[x] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[x] 2.0
[] 3.0

`<?xml version="1.0" encoding="utf-8"?>`
`<QueryInvoiceDataRequest xmlns="http://schemas.nav.gov.hu/OSA/2.0/api">`
`  <header>`
`    <requestId>80bec6e04a5942df80101bfe8987f0</requestId>`
`    <timestamp>2020-09-14T12:38:41</timestamp>`
`    <requestVersion>2.0</requestVersion>`
`  </header>`
`  <user>`
`    <login>uqppjq3f8dy7edp</login>`
`    <passwordHash>B4286A45FED95442F6BDC6CA03D29687AED2D25F9AF548F099D05DCDDCCE291182BB900D2519B36A0B708A027204708E3959320A4AA3F4E79C6D94C6932018EB</passwordHash>`
`    <taxNumber>10336328</taxNumber>`
`    <requestSignature>3EACA027EE4C3CC1CC2F7BADB0DD10FDEAB698460A10916AE11683F1A3F6CE6570CD0184A4A746CA24DFA8508A08742A30B54743F8423F7480176E6E3B5602CF</requestSignature>`
`  </user>`
`  <software>`
`    <softwareId>123451234512345123</softwareId>`
`    <softwareName>Teszt</softwareName>`
`    <softwareOperation>LOCAL_SOFTWARE</softwareOperation>`
`    <softwareMainVersion>1.0</softwareMainVersion>`
`    <softwareDevName>teszt</softwareDevName>`
`    <softwareDevContact>teszt@teszt.com</softwareDevContact>`
`    <softwareDevCountryCode />`
`    <softwareDevTaxNumber />`
`  </software>`
`  <invoiceNumberQuery>`
`    <invoiceNumber>L/K2020/014162</invoiceNumber>`
`    <invoiceDirection>INBOUND</invoiceDirection>`
`    <supplierTaxNumber>10591589</supplierTaxNumber>`
`  </invoiceNumberQuery>`
`</QueryInvoiceDataRequest>`

[POST]  https://api-test.onlineszamla.nav.gov.hu/invoiceService/v2/queryInvoiceData 

C# programozási környezetben PostAsync kéréssel próbálunk számlaadatot lekérni a fent leírt XML kéréssel.
Kétféle választ kapunk a szervertől apróbb konfiguráció módosítások határása: ERROR 500, vagy ERROR 400

Nem tudjuk hogy a kérés az helyesen van-e összeállítva, vagy esetleg a kérés paraméterezése az amit nem állítunk be megfelelően.

**Comment by NTCA-supporter** [comment]
Szia @kastonoriginal !

A 80bec6e04a5942df80101bfe8987f0 requestetdnél softwareDevCountryCode és a softwareDevTaxNumber van gond. Ha azokat szeretnéd megadni, akkor ne is tedd bele az xml-be. Plusz a headerben a megadott timestamp formátuma sem megfelelő.

**Comment by NTCA-developer** [comment]
@kastonoriginal ezt sikerült megoldani? Hagyjam még nyitva vagy lezárható?
