### ISSUE TITLE
[Q&A] Előleg jellegűnek (advanceIndicator) kell-e jelölni az előleg beszámító számlát stornózó számla tételét?

### ISSUE THREAD

**Issue by betasofthu** [nav-gov-hu/Online-Invoice#367]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Az előleg beszámító számlán (más néven végszámlán)  mínusz mennyiségű tételként szerepel az beszámított előleg mínuszos értékkel. Ezen számla stornózása (azaz érvénytelenítése) esetén a stornó számláról készülő adatszolgáltatásban az **advanceIndicator-t true-ra kell-e állítani**. Ez ugyanis szerintem nem előleg jellegű, mivel ez maga a stornó tétel ami itt már plusz mennyiséggel szerepel az előjel fordítás miatt. Ez egy technikai tétel, ami stornózás miatt lett ellenkező előjelű. Formailag úgy néz ki mintha előleg lenne, mert pozitív a mennyiség. Ugyanez a kérdés felmerül az ugyanerről a számláról készülő adóhatósági ellenőrzési adatszolgáltatásban is. Itt nem csak az előleg jelleget, hanem "1-Előlegszámla" vagy "2-végszámla" jelet is ki kellene tenni az "eloleg_tipus"-ban. Ezt már végkép nem tudom megmondani, hogy a kettő közül melyik lehetne, ha előleg jellegűnek számít a stornó tétel. **De nem számít annak. Legalábbis szerintem nem. Jól gondolom?**

**Comment by NTCA-tax** [comment]
A végszámla érvénytelenítése esetén az előleg tételsor nem veszti el előleg jellegét. Teljesen logikusan egy érvénytelenítő számlában ez pozitív összeg lesz, ugyanakkor attól ez egy érvénytelenítő (de még módosítónál is) teljesen értelmezhető.

**Comment by betasofthu** [comment]
Rendben. Az online adatszolgáltatásban az érvénytelenítő számlán a pozitív összegnek marad az előleg jellege.  Az adóhatósági ellenőrzési adatszolgáltatásban az érvénytelenítő számlán is "2-végszámla" jelet kapjon az "eloleg_tipus" ?

**Comment by NTCA-tax** [comment]
A fenti logika alapján az adatexportnál a végszámla érvénytelenítésénél is kell jelölni az előleg jelleget.

**Comment by ju00ro** [comment]
Ehhez a témához lenne kérdésem.
Végszámlát stornózok és az alábbi HIBA üzenetet kapom: 
XML contains on line: [68] and column: [38] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element ''{"http://schemas.nav.gov.hu/OSA/3.0/data":lineModificationReference}''. One of ''{"http://schemas.nav.gov.hu/OSA/3.0/data":productCodes, "http://schemas.nav.gov.hu/OSA/3.0/data":lineExpressionIndicator}'' is expected.]

A sor pedig így néz ki:
        <line>
          <lineNumber>1</lineNumber>
          <advanceData>
            <advanceIndicator>true</advanceIndicator>
          </advanceData>
          <lineModificationReference>
            <lineNumberReference>3</lineNumberReference>
            <lineOperation>CREATE</lineOperation>
          </lineModificationReference>
          <lineExpressionIndicator>true</lineExpressionIndicator>
          <lineDescription>ELŐLEG;TESZT</lineDescription>
          <quantity>1</quantity>
          <unitOfMeasure>PIECE</unitOfMeasure>
          <unitPrice>1</unitPrice>
          <unitPriceHUF>1</unitPriceHUF>
          <lineAmountsNormal>
            <lineNetAmountData>
              <lineNetAmount>1</lineNetAmount>
              <lineNetAmountHUF>1</lineNetAmountHUF>
            </lineNetAmountData>
            <lineVatRate>
              <vatPercentage>0.27</vatPercentage>
            </lineVatRate>
            <lineVatData>
              <lineVatAmount>0.27</lineVatAmount>
              <lineVatAmountHUF>0</lineVatAmountHUF>
            </lineVatData>
            <lineGrossAmountData>
              <lineGrossAmountNormal>1.27</lineGrossAmountNormal>
              <lineGrossAmountNormalHUF>1</lineGrossAmountNormalHUF>
            </lineGrossAmountData>
          </lineAmountsNormal>
        </line>

Viszont, ha az 'advanceData' tagot kiveszem, vagyis nem jelölöm a tétellt előlegként, akkor rendesen elfogadja.
Mi lehet a gond?

**Comment by ju00ro** [comment]
A sor még egyszer:
        // <line>
        //  <lineNumber>1</lineNumber>
        //  <advanceData>
        //    <advanceIndicator>true</advanceIndicator>
        //  </advanceData>
        //  <lineModificationReference>
        //    <lineNumberReference>3</lineNumberReference>
        //    <lineOperation>CREATE</lineOperation>
        //  </lineModificationReference>
        //  <lineExpressionIndicator>true</lineExpressionIndicator>
        //  <lineDescription>ELŐLEG;TESZT</lineDescription>
        //  <quantity>1</quantity>
        //  <unitOfMeasure>PIECE</unitOfMeasure>
        //  <unitPrice>1</unitPrice>
        //  <unitPriceHUF>1</unitPriceHUF>
        //  <lineAmountsNormal>
        //    <lineNetAmountData>
        //      <lineNetAmount>1</lineNetAmount>
        //      <lineNetAmountHUF>1</lineNetAmountHUF>
        //    </lineNetAmountData>
        //    <lineVatRate>
        //      <vatPercentage>0.27</vatPercentage>
        //    </lineVatRate>
        //    <lineVatData>
        //      <lineVatAmount>0.27</lineVatAmount>
        //      <lineVatAmountHUF>0</lineVatAmountHUF>
        //    </lineVatData>
        //    <lineGrossAmountData>
        //      <lineGrossAmountNormal>1.27</lineGrossAmountNormal>
        //      <lineGrossAmountNormalHUF>1</lineGrossAmountNormalHUF>
        //    </lineGrossAmountData>
        //  </lineAmountsNormal>
        //</line>
