### ISSUE TITLE
3.0 alatti invoiceData.xsd "hiba"

### ISSUE THREAD

**Issue by gksaphu** [nav-gov-hu/Online-Invoice#368]
3.0 alatti invoiceData.xsd-ben hibát látunk:
invoiceType->invoiceHead->customerInfo->customerVatData
node alatt  customerTaxNumber node alatt a groupTaxnumber van, viszont nincs customer tax Number

**Comment by EPluribusUnum** [comment]
customerVatData-ban van 
customerTaxNumber, aminek a típusa CustomerTaxNumberType.

A CustomerTaxNumberType extends TaxNumberType, ezen keresztül lehet a sima customerTaxNumber értéket megadni.

CXF ezt generálja nekem:

public class CustomerVatDataType {
    @Valid
    protected CustomerTaxNumberType customerTaxNumber;
    @Size(min = 4, max = 15)
    @Pattern(regexp = "[A-Z]{2}[0-9A-Z]{2,13}")
    protected String communityVatNumber;
    @Size(min = 1, max = 50)
    @Pattern(regexp = ".*[^\\s].*")
    protected String thirdStateTaxId;
...
}

public class CustomerTaxNumberType **extends TaxNumberType** {
    protected TaxNumberType groupMemberTaxNumber;
...
}

**Comment by jozanesz** [comment]
Ezt is túl lehetne élni, de nem szép dolog a tiszta kompozíció helyett örököltetést keverni ebbe. Javaslom a javítását.

**Comment by NTCA-developer** [comment]
A customerTaxNumber csomópont ugyan ezen a néven már létezett az 1.0 óta, most ami változás hogy létrejött egy új típus (CustomerTaxNumberType) ami kiterjeszti a - logikailag - azonos korábbi szerkezetet és mellé teszi a groupMemberTaxNumber csomópontot.

Erre azért van szükség mert kívül choice van, és a belföldi ágon kell szerepelnie a 2 elemnek. Ezen követelmény mentén ezt csak úgy lehetne javítani, hogy ki kellene találni egy plusz összefogó elemet a belföldi ágra és minden további elemet eltolni lefelé egy szinttel, de ekkor a choice-os nevezéktan lenne inkonzisztens. 

Most azt látom, hogy a jelenlegi állapot a kisebbik rossz. Esetleg más ötlet? (hátha én nem ébredtem még fel)

**Comment by gksaphu** [comment]
Köszi, értem, igazából maradhat is így.
Ami nekem feltűnt, hogy a ennek a pandantja a supplier vonalon, három elemet hoz, ha ott is van belföldi ág (most nincs előttem), akkor meg az nem jó.
Az is lehet, hogy nem kell ezeknek egyformának lenni.

**Comment by NTCA-developer** [comment]
A supplier oldalon nincsenek ágak, ott a sequence-ben valóban 3 értéket adhatsz meg, de ezek csak a kiállító addícionális adószám adatai, nem pedig egymást kizáró minőségek, ahogy a vevőnél. Akkor lezárom, köszi szépen a jelzést!

**Comment by gksaphu** [comment]
Rendben, köszi!
