### ISSUE TITLE
[Q&A]XSD 2.0 használata 2021. január 1. után

### ISSUE THREAD

**Issue by szalaierika** [nav-gov-hu/Online-Invoice#369]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Sziasztok,

nagyon örültünk, mikor kijött a hivatalos tájékoztatás az XSD 2.0 január 1. után is használatható lesz március 31-ig. Viszont az ÁFA-törvényváltozás, mely kiterjeszti az online számla regisztrációt magánszemélynek kiállított és közösségen belüli értékesítések számláira január 1-én lép hatályba.

Kérdésem az, hogy ezeket az újonnan jelentendő számlákat be lehet majd küldeni az XSD 2.0-val is?

Köszönöm előre is

**Comment by szalaierika** [comment]
Szia @NTCA-tax ,

már nagyon kellene ez a válasz nekünk, mert jelenleg teljesen el vagyunk akadva. Ugyanis a tesztelés során kiderült, hogy az XSD 2.0-val nem lehet magánszemélyek részére kiállított számlát küldeni, ha magán személynek nincs érvényes taxPayerId-ja.

Ebből az következik, hogy ilyen számlát csak az XSD 3.0-val lehet beküldeni, viszont annak a bevezetésére meg vonatkozik a türelmi időszak 2021.március 31-ig.

Kérdéseim az alábbiak:
1. Kell-e küldeni 2021.január 1-től a magánszemélyeknek kiállított számlákat, ha még az adózó nem állt át az XSD 3.0?
2. Vagy ha majd átállt, akkor kell utólag küldeni?
3. Esetleg nem kell utólag sem küldeni ezeket?

Előre is köszönöm a válaszokat.

**Comment by nbeeps2** [comment]
2021. március 31-ig KELL áttérni a 3.0-ra, melyből egyenesen következik, hogy 2021. március 31-ig használható a 2.0-ás adatszolgáltatás a 2.0-ás érintettségi körrel. Magyarán, ha majd megjelenik a 3.0-ás XSD élesben, akkor 2021. január 1-től már küldhető MINDEN számla, de NEM KÖTELEZŐ és nem is kell ezeket utólag pótolni. 

@szalaierika , de hát a válaszok:
1-es pont: NEM
2-es pont: NEM
3-as pont: NEM

Semmit nem kell tehát utólag küldeni, az adatszolgáltatás továbbra is "azonnali" és nem utólagos.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet. Ha van még kérdés nyissátok újra nyugodtan.
Üdv

**Comment by szalaierika** [comment]
Szia @nbeeps2,

köszönöm a választ. Azért az ezzel kapcsolatos ÁFA-törvényváltozás azért hatályba lép 2021. január 1-én.

**Comment by jozanesz** [comment]
> Azért az ezzel kapcsolatos ÁFA-törvényváltozás azért hatályba lép 2021. január 1-én.

Már az sem: [Az 59. §, 68. § (1) bekezdése és az 5. melléklet 2021. január 4-én lép hatályba.](http://njt.hu/cgi_bin/njt_doc.cgi?docid=222979.392100)
