### ISSUE TITLE
[Q&A] SAVED invoiceStatus

### ISSUE THREAD

**Issue by era910413** [nav-gov-hu/Online-Invoice#37]
A dokumentációban található, hogy a PROCESSING és a DONE státusz között meg fog jelenni a SAVED státusz is, mely esetben már lekérdezhetőek a számla adatai, arra módosító vagy stornó adatszolgáltatás küldhető. Ezt követően lesz a státusz DONE vagy ABORTED.

Módosító számlák esetében a modifyWithoutMaster elemet is szükséges küldeni.
Amennyiben olyan alapszámlára hivatkozunk, mely már be lett küldve, de még SAVED státuszban van, akkor a modifyWithoutMaster elem false értéke elfogadásra kerül?
Gondolok itt arra, hogy SAVED után még ABORTED is lehet a számla.. 
Jelenleg az INVALID_INVOICE_REFERENCE error kerül visszaadásra, ha a módosítás vagy érvénytelenítés által hivatkozott számla nem található meg az adózó számlái között a rendszerben, és a kérésben nem jelölték, hogy a módosításhoz nem tartozik korábbi adatszolgáltatás.

**Comment by NTCA-developer** [comment]
Szia @era910413 !

Valódan a SAVED státusz után jön a DONE státusz, de SAVED státuszban a számla már nem lehet ABORTED. (még nincs teljesen kész, de túljutott azokon az ellenőrzéseken, ahol bukni tudott volna)

Egy SAVED státuszú alapszámlára már küldhető módosító/stornó számla, és ezen módosító/stornó adatszolgáltatásokat modifyWithoutMaster = false esetén be fogjuk fogadni, modifyWithoutMaster  = true esetén pedig el fogjuk utasítani, ugyan úgy, mintha DONE lett volna az alapszámla.

Majd kérlek zárd le a ticketet, ha nincs több kérdésed.
