### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by dupplak** [nav-gov-hu/Online-Invoice#370]
Üdv,

A 3.0-s invoice XML-ben van egy rosszul fordított tag, amely angolul egy pénzügyi szakembernek értelmezhetetlen.

A "conventionalInvoiceInfo" alatt van a "generalLedgerInvoiceNumbers" tag, ami a magyarázat szerint a főkönyvi számlaszámot tartalmazza majd.

Ennek a helyes angol fordítása "generalLedgerAccountNumbers" lenne. Kérem javítsák, hogy a külföldi programozók is tudják értelmezni a tag-et!

Üdv, jó munkát!

**Comment by NTCA-developer** [comment]
Szia @dupplak 

Köszönjük a jelzést, rákérdezünk. (nem magunktól találjuk ki az üzleti tagek neveit)

**Comment by NTCA-tax** [comment]
Köszönjük a jelzést, és ténylegesen helyes a felvetés. A főkönyvi számlának account-nak és nem invoice-nak kell lennie.
