### ISSUE TITLE
WARN üzenet HU karakterhiba (ÿfa)

### ISSUE THREAD

**Issue by KKARACSONY** [nav-gov-hu/Online-Invoice#371]
Sziasztok, 

Tudnátok kérlek javítani ezt a hibaüzenet karakterhibát?  ÁFA szónál van probléma és elhasal tőle a programunk. 
Ez a response üzenet nem jön át az alapértelmezett character encoding UTF-8-on ha magyar komm. nyelv van beállítva. 

Köszönjük szépen!

<validationResultCode>WARN</validationResultCode>
<validationErrorCode>INCORRECT_SUMMARY_DATA_VAT_OUT_OF_SCOPE</validationErrorCode>
<message>Az **ÿfa** törvény hatályán kívüli jelölés a tételsorok és az összesítő közül csak az egyikben fordul elő, a másikból hiányzik.</message>

**Comment by KKARACSONY** [comment]
Sziasztok, 

Meg tudtátok ezt esetleg nézni? 

Köszi szépen!

**Comment by NTCA-supporter** [comment]
Szia @KKARACSONY !

Megnéztük a kódban és a logban is, mindenhol rendesen szerepel. Tesztrendszeren kipróbáltam és utf-8-al simán visszajött:
<validationResultCode>WARN</validationResultCode>
				<validationErrorCode>INCORRECT_SUMMARY_DATA_VAT_OUT_OF_SCOPE</validationErrorCode>
				<message>Az Áfa törvény hatályán kívüli jelölés a tételsorok és az összesítő közül csak az egyikben fordul elő, a másikból hiányzik.</message>

Nem lehet, hogy kliens oldali hiba? Gondolom más is jelezte volna már, ha ez rossz. 

Üdv

**Comment by KKARACSONY** [comment]
Köszi, hogy megnéztétek! 
Közben mi is kiküszöböltük már a problémát azzal, hogy a kommunikáció nyelvét átállítottuk angolra, csak tudni szerettük volna, hogy itt láttok-e valamit a ti oldalatokról. 

Üdv
