### ISSUE TITLE
FELIR azonosító

### ISSUE THREAD

**Issue by janisoft** [nav-gov-hu/Online-Invoice#372]
**Az igény összefoglalása / Summary of the request**
A szállító adatai között supplierInfo szerepelhetne a FELIR azonosító, amivel az összes élelmiszerforgalmazó vállalkozásnak rendelkeznie kell.

**Comment by NTCA-developer** [comment]
Szia @janisoft 

Csak hogy pontosan értsük a kérést. Ezt a conventionalInfo részeként javasolnád, vagy általában a kiállító adatai mellé tennéd?

**Comment by janisoft** [comment]
Szia!

conventionalInfo részeként szerintem elegendő.

János

**Comment by NTCA-supporter** [comment]
Szia @janisoft !
Ez végül nem került bele a sémába, additionalInvoiceData-ként megadhatod.
Zárom az issuet.
Üdv
