### ISSUE TITLE
[FEATURE] QueryInvoiceDigestResponse kiegészítése

### ISSUE THREAD

**Issue by veerede** [nav-gov-hu/Online-Invoice#373]
Sziasztok!

A QueryInvoiceDigestResponse SIMPLIFIED számla esetén nem ad semmilyen összeg információt.
(invoiceNetAmount,invoiceNetAmountHUF,invoiceVatAmount,invoiceVatAmountHUF elemek ebben az esetben töltetlenek)

Korábban már jeleztem azt a hiányosságot, lehetne esetleg ezt orvosolni a 3.0 megjelenésével?
Például az summaryGrossData/summaryGrossAmount szerepeltetésével?

Üdv
Ede

**Comment by NTCA-supporter** [comment]
Szia @veerede !
Ezzel sajnos nem tudtunk foglalkozni, sok volt a magasabb prioritású feladat.
Zárom az issuet.
Üdv
