### ISSUE TITLE
SZÁMLA KIBOCSÁJTÁSA,  SZÁMLA ELJUTTATÁSA A VEVŐHÖZ

### ISSUE THREAD

**Issue by KMGY100** [nav-gov-hu/Online-Invoice#374]
Miután az adózó rögzítette  a számlát, a számla  XML állománya azonnal beküldésre került.
A számla megjelenési formája: PAPER
Ezt követően kinyomtatja a számlát  -PDF állományból-  bármennyi példányban.

A kinyomtatott számlát eljuttathatja a vevőhöz:
   - személyes átadással
   - postai küldéssel
   - email mellékleteként 
              ( az email mellékletből a vevő kinyomtatja bármennyi példányban )

Bármelyik módon jut a vevőhöz a számla, a számla képe és tartalma minden esetben ugyanaz,
 ( valamint azonnal ellenőrizni tudja a bejövő számlái között )

Kérdésem:   a számla kibocsájtója eljuttathatja-e a számlát email mellékletként
                  a vevőjéhez.
                  A számla kibocsájtója és a számla befogadója kizárólag papírformában őrzi a számlákat.

Megjegyzésem:  a személyesen átadott  papír formátumú számla  pontosan és minden ízében azonos
                         az email mellékleteként küldött , a vevő által kinyomtatott számlával

**Comment by nbeeps2** [comment]
Hm, hát ez már egy lerágott csont ;) A NAV-tól azt a választ fogják neked írni, hogy ha e-mailben PDF-ként küldöd a számlát, akkor az elektronikus számlának minősül, így elektronikusan szükséges azt megőrizni. A szakmai fórumok (MKOE, Adózona, Önadózó) szakemberei szerint, azonban teljesen megengedett és semmi nem tiltja a papír alapú számla e-mailben való elküldését a vevőnek, nem mellesleg az egész ellenőrizhetetlen, így a NAV sem tudja és vélhető nem is fogja, mivel egy könyvelésbe betett papír alapú számláról az életben nem mondják meg, hogy miként került oda (pl. személyesen mentek érte, személyesen hozták, kinek a nyomtatóján nyomtatták, e-mailben kapták, stb.). A válasz röviden: a NAV szerint elméletben nem lehet, mindenki más szerint a gyakorlatban igen. ;)

**Comment by KMGY100** [comment]
@nbeeps2 
Köszönöm a reagálásod, én is így gondolom,  és tisztában vagyok azzal hogy ez már egy lerágott csont,
de látod, van még rajta rágcsálni való. 
Szakmai fórumok vs NAV

Véleményem szerint:
Szükségtelen a számla PDF állományának e-mail küldésénél a cryptotext, hiszen a számla nem csak
számla kibocsájtó és számla befogadó   birtokában van hanem egy numero 1-es helyen, a csúcson,
a NAV-nál.
Éppen ezért semmilyen alapon nem tud ellentétbe kerülni a számla kibocsájtója és számla befogadója.

Csak akkor van értelme egy dokumentum cryptotext azonosítóra , ha az adott dokumentum
csak két fél birtokában van.

**Comment by NTCA-tax** [comment]
Ne raboljuk egymás idejét olyan kérdésekkel, amelyekre biztosan tudjátok a választ. Egy elektronikusan megküldött és befogadott számla elektronikus számla lesz, függetlenül annak formátumától, a küldés technikájától stb.

**Comment by csaszko** [comment]
> Ne raboljuk egymás idejét olyan kérdésekkel, amelyekre biztosan tudjátok a választ. Egy elektronikusan megküldött és befogadott számla elektronikus számla lesz, függetlenül annak formátumától, a küldés technikájától stb.

Szia!

Bocs, hogy itt is hozzászólok, de szerintem ez nem időrablás, mi alapján mondod ezt? 
https://nav.gov.hu/nav/ado/afa/Az_elektronikus_szaml20200416.html
#415 

> Ezért elektronikusszámlának minősül **a kizárólag** e-mailben, egyéb elektronikus üzenetben megküldött PDF számla is.

Szerintem ezzel a témával is kellene foglalkozni megfelelően és nem tovább bonyolítani és így lezárni. 
Időrablás az amikor naponta kell 1...10...50 számláról a kollégáknak ügyfeleknek elmagyarázni, hogy ez most minek is minősül... 
Köszönöm

**Comment by NTCA-tax** [comment]
@csaszko: a bejegyzésedet nem teljesen értem. A kérdés arra vonatkozott, hogy az elektronikus számla lehet-e papírszámla a vevői oldalon.

**Comment by csaszko** [comment]
#415 -nél jobban leírtam, de szerintem szorosan ide kapcsolódik.

**Comment by NTCA-tax** [comment]
A kérdésedet ott megválaszoltam.

**Comment by csaszko** [comment]
> Az is egy nagyon fontos dolog, amit írtál, hogy te PAPER-ként állítod ki és küldöd be a NAV-nak, tehát ezt nem tud elektronikusra változni utólag, szóval ilyen szempontból sincs kihatással, hogy e-mailben küldöd el a vevőnek vagy sem, mert az már bizony PAPER marad és az életben nem lesz e-számla...

NTCA-tax 2020.09.28. 09:51-es hozzászólása alapján ez nem így van, és nekem itt a problémám, meg majd másoknak is lesz amikor ráébrednek erre.
