### ISSUE TITLE
Elemek kötelezősége

### ISSUE THREAD

**Issue by Zoller79** [nav-gov-hu/Online-Invoice#375]
Tisztelt Címzett! 

A NAV rendszerből történő adatlekérdezések során kiderült, hogy bizonyos számlázó rendszerek nem szolgáltatnak adatot minden - egyébként a számlaképen található - kötelező elemről, mert a NAV XSD validációja nem végez ellenőrzést az adott elemre. 
Konkrétan a 2.0-ás leírás alapján a pénzforgalmi elszámolás (cashAccountingIndicator) elem technikailag nem szükséges, így a számlázó program ezt az elemet nem küldte be a NAV rendszerhez. 
A könyvelő programba történő feldolgozás során ez egy lényeges elem, hiszen, ha nem jelölt az elem, akkor a program egyből levonásba helyezi a számlát, míg, ha jelölt, akkor a bizonylat is jelölést kap és a levonást csak a kiegyenlítés keletkezteti. 

A kérdés, hogy esetleg ezek a lényeges elemek nem kaphatnának kötelezőséget, és a fejlesztő true/false értékkel jelölhetné, hogy melyik halmazba tartozik az adott számla.

Hasonlóan hasznos lenne kötelező elemként a kisadózó (smallBusinessIndicator) jelölés, vagy akár a időszakos elszámolás (periodicalSettlement).

Válaszaikat előre is köszönöm! 

Üdvözlettel:
Kispál Zoltán

**Comment by Macskafarka** [comment]
Jó lenne végre eldöntenie a NAV-nak, hogy mire is akarja használni a Online számla adatszolgáltatást.
Mert a befogadói oldalon csak akkor lehet építkezni rá, ha a számla **kötelező elemei** szerepelnek benne.
A kötelező mezőket nem lehet leszűkíteni arra, hogy "csak az ÁFA törvény szerint kötelező" elemeket kell adatszolgáltatni!
A KATA és a "pénzforgalmi elszámolás" jelölés elengedhetetlen eleme a számlának, ennek ÁFA bevallási és más adótechnikai kihatásai vannak.
Messze több ez a két mező, mint egy cikkszám, vagy szerződésszám.
Ha ezek a mezők nem kötelezők az adatszolgáltatásban, akkor a számla befogadói oldalon nincs értelme építkezni a számla lekérdezésre.

**Comment by NTCA-tax** [comment]
A pénzforgalmi elszámolást csak azon számlák esetében kell jelölni, mely ezzel érintett. Tehát ha nincs kitöltve az adatszolgáltatásban ez a mező, akkor úgy kell tekinteni a számlát, hogy nem pénzforgalmi elszámolás alá tartozik.

A kisadózó jelzése éppen nem az áfa törvényben előírt kötelezettség, ezért a mezőt kötelezően nem szerepeltethetjük az adatszolgáltatásban. Az időszakos elszámolás jelzésére nincs jogszabályi kötelezettség, hanem egy opcionális adat lehet csak az adatszolgáltatásban. Amennyiben ennek a két mezőnek a kötelezőségét bevezetnénk, akkor túlnyúlnánk a jogszabályi felhatalmazásunkon.

**Comment by Macskafarka** [comment]
Köszönjük a választ, érthető volt.
Ez alapján eldönthető, hogy a befogadó oldali számla letöltés nem használható komolyan, csak tesztelgetésre. 
Azt értelmetlennek látom, hogy a letöltött számlákat még kézzel kelljen kiegészítgetni a számlakép alapján.

**Comment by omachtandras** [comment]
"A pénzforgalmi elszámolást csak azon számlák esetében kell jelölni, mely ezzel érintett. Tehát ha nincs kitöltve az adatszolgáltatásban ez a mező, akkor úgy kell tekinteni a számlát, hogy nem pénzforgalmi elszámolás alá tartozik."

NTCA-tax: ez akkor azt jelenti, hogy ha a befogadó oldal a kapott papír alapú számla alapján pénzforgalmúként kezel egy számlát, mert nem jár utána, hogy a NAVhoz milyen adatot küldött be a kibocsátó, az hibásan jár el és bírsággal sújtható? Vagyis könyveléskor minden számlát ellenőrizni kell, hogy ilyen szempontból milyen adat jelenik meg a NAVnál?
Vagy ebben az esetben a befogadót nem, de a kibocsátót fogja bírságolni / bírságolhatja a NAV?

**Comment by Macskafarka** [comment]
Én a magam részéről a törvényt fogom követni, és ha az általam kézhez kapott papír alapú számlán rajta van az, hogy "Pénzforgalmi elszámolás", akkor súlytan az, hogy az adatszolgáltatásban mit kapott a NAV (vagy mit mutat meg belőle).
Amúgy pedig kíváncsi vagyok, hogyan fogja elkészíteni  a NAV az áfa bevallást 2020.07.01-től, ahogy a pénzügyminiszter ma nyilatkozta. Biztosan tudni fogja a pénzforgalmi számla kiegyenlítését is? Vagy megint csak egy marketing fogás ez az egész.

**Comment by Zoller79** [comment]
Köszönöm a választ! 
Akkor maradjunk csak a pénzforgalmi résznél. A legnagyobb gondom, hogy azzal, hogy nem kötelező cashAccountingIndicator elem, hogy nem tudom eldönteni, hogy azért nincs az adatszolgáltatásban, mert hibás esetleg az adatot szolgáltató rendszer, vagy azért nincs, mert valóban nem választották ezt az elszámolási módot.
Ha egy rendszer hibásan - ezen adat nélkül küldte be a számla adatokat - majd én bízva az adatszolgáltatás helyességében átveszem és könyvelem az adatokat, akkor az ilyen számlának az áfa összegét levonásba helyezem. Míg ha helyesen ment volna be az adat, akkor más módon kerül könyvelésre és csak a kiegyenlítés időpontjában (akár eltérő adómegállapítási időszakban) kerülne levonásra. 
Ahogy @omachtandras is írta:
A fentiek alapján minden egyes számlát papíron is ellenőrizni kell, hogy az adatszolgáltatásban található adatok megegyeznek-e bizonylaton található adatokkal? 
Ha ez a GitHub kommunikáció arra szolgál, hogy fejlesszük és kevesebb hibával kerüljenek adatok a NAV-hoz, akkor kérem, hogy fontolják meg, hogy ezen elemet mégis kötelezővé tegyék a jövőbeli verziókban, mert vagy többlet (felesleges) munkát adnak a könyvelőknek, vagy pedig bírságolási kaput nyitnak a nem megfelelő időpontban történt adólevonás miatt! 

Köszönettel! 
Kispál Zoltán

**Comment by NTCA-tax** [comment]
Remélhetőleg nincs olyan adózó, aki KIZÁRÓLAG az adatszolgáltatás alapján helyez levonásba adót. Az adólevonás tárgyi feltétele a számla, melyet mindenképpen meg kell vizsgálni. A vevői oldalon az adatszolgáltatás könyvelő programba való betöltését követően egy emberi felügyelet nélküli automatizmust építeni jelentős problémákat okozhat. Az adatszolgáltatás a vevői oldalon nem helyettesíti, hanem megkönnyíti az emberi munkavégzést. Egy esetben van létjogosultsága egy ilyen fajta automatizmusnak, ha az adatszolgáltatás önmaga az elektronikus számla is. De erre csak 2021-től nyílik lehetőség.

Amennyiben egy számlán pénzforgalmi elszámolással kapcsolatban egy hibás adatszolgáltatás következményeiről beszélünk a vevői oldalon. Ugyanakkor attól még az adatszolgáltatás a hibás, melyet az adóhivatal az értékesítő oldalán szankcionálhat is.

**Comment by omachtandras** [comment]
"Remélhetőleg nincs olyan adózó, aki KIZÁRÓLAG az adatszolgáltatás alapján helyez levonásba adót. ...."

Jelenleg természetesen nincs ilyen (leglábbis a mi ügyfélkörünkben), de az early-bird-ök igénye és elvárása az, hogy bizony hamar eljussanak arra a szintre, hogy elengedhetik a papírt...
Az látszik, hogy az adatszolgáltatás minősége hagy kívánni valót maga után (még egy nagyon-nagy cég sem képes mondjuk ugyanazt az elszámolási időszak kezdete és vége dátumot beküldeni, mint amit a számlára ír, hogy csak egy számomra megdöbbentő példát mondjak).

Valamit azonban kellene NAV oldalról is tenni, hogy ez javuljon, mert 
- a NAV oldali kommunikáció most már jó ideje az, hogy használjátok az adatokat, automatizáljatok, ezért (is) csináltuk az egészet
- a NAV fog adóbevallás tervezetet készíteni, de ez a tervezet így semmit nem fog érni, mert hibás adatokra alapoz (amellett, hogy egy csomó mindenről egyébként sem látszik, hogy honnan fog információt szerezni (pl. pénzforgalmi kiegyenlítettség, a számlát egyáltalán befogadom-e, vagy csak az én adószámomra állították ki, stb.))
- a NAV deklaráltan a beküldött adatokat arra szeretné használni, hogy automatizáltan szűrje ki a csalókat, de ha az adatok minősége olyan, mint most, akkor nem vagyok benne biztos, hogy ez sikerülni fog (itt is leírásra került sokszor, hogy a KATA jelzés nem kötelező, de ha ez így van és a többség nem adja, akkor hogy lehet erre bármilyen ellenőrző automatizmust építeni NAV oldalon?) (Javaslat egyébként az utólagos bizonylat rögzítő felületre, a KATA jelző alapban meg sem jelenik, nyomni kell hozzá egy plusz gombot, hogy bepipálhassa az ember, ez így szerintem sokszorozza annak a valószínűségét, hogy ez megtörténik....)

Én (mi) hiszünk abban, hogy az automatizálás jó irány és foglalkozni kell vele, de az ügyfelek jelenleg úgy érzik, hogy az egész inkább szól arról, hogy a NAV (és mi szoftverszállítók) arra akarja használni őket, hogy hívogassák a partnereiket és jelezzék / magyarázzák nekik, hogy mit és hogy csinálnak rosszul az adatszolgáltatásuk során, mert ők bizony látják a feldolgozásnál, hogy ez-meg-az nem ok kibocsátói oldalon... Ez azonban csak akkor működik, ha a partneri kapcsolatban a befogadó oldal van olyan pozícióban, hogy változást érjen el a kiállítónál...

Bocsánat a hosszú és nem technikai kérdésekkel foglalkozó eszmefuttatásért, de azt gondolom ezek a tapasztalatok, amelyek itt leírásra kerülnek fontosak lehetnek a NAVnak, mert az ide írók azok, akik láthatóan aktívan foglalkoznak a témával és van olyan ügyfélkörük és ezáltal tapasztalatuk, ami közelebb viheti a NAVot is a mindennapi élethez és problémákhoz.

**Comment by Macskafarka** [comment]
Az a baj, hogy éppen az az ország kezdte el ezt a számla beküldőzgetősdit, amelynek talán a legbonyolultabb áfa rendszere van, olyan dolgokkal, amelyek rendkívüli módon megnehezítik az automatizálást. Remélem, hogy a tapasztalatok alapján a jogalkotó is érezni fogja a nyomást az egyszerűsítésre (pl. pénzforgalmi áfa, előlegről áfás bizonylat stb.)
Annyira messziről indulunk,  hogy még a fogalmaink sem tiszták!
A pénzügyminiszter "cégek" áfabevallásáról beszél, a magyarázatban a "vállalkozás" szó szerepel, itt a GitHub-on felbukkant a "jogi személy", nálunk a "gazdálkodó szervezet". miközben ezek a fogalmak más-mást jelentenek.
A "magánszemély" alatt mindenki mást ért, pedig az ő számláikat kell anonimizálni. Kialakult egy olyan jogértelmezés, hogy az "egyéni vállalkozó" az nem magánszemély, ugyanakkor a GDPR szerint, és a Ptk szerint is az, ergó védettek a személyes adatai. Ott van még az "adószámos magánszemély", amely még több bizonytalanságot jelent. 
Miközben ugyanaz a személy egyidőben lehet egyéni vállalkozó, adószámos magánszemély és sima magánszemély, csupán az adott gazdasági eseményben vesz így, vagy úgy részt.
Tényleg furcsa a NAV részéről azzal védekezni, hogy a magánszemélyek  adatai GDPR okok miatt nem kerülhetnek a számla adatszolgáltatásban a NAV tudomására, adatkezelésébe, miközben a PTGSZLAH nyomtatványon meg a NAV tudomására kell hozni személyes adatokat. Ez a skizofrén helyzet a szabályozási problémákból fakad, a NAV is olyan bizonytalan, amilyen a jogszabályi talaj, amelyen áll, plusz még mi is őt kérdezzük....
Jó lenne előbb a fogalmakat rendbe tenni, egyértelműsíteni, kevesebb lenne a hiba.

**Comment by Zoller79** [comment]
Nyilván fontos, hogy a bizonylatok is rendelkezésre álljanak. Fontos az ellenőrzés is, de ezektől függetlenül ez az "egyszerű" elem kötelezővé tétele nagyban segíthetné a helyes áfabevallás elkészítését. 

A NAV kommunikációjából a könyvelők azt szűrik le, hogy nekik az adatszolgáltatás adatok importálásával a munkájuk lényegesen könnyebbé válik. Hajlamosak úgy tekinteni az adat átvételekre, hogy a programok megoldanak mindent helyettük. 
Nagy segítség lenne a fejlesztőknek, ha a NAV kommunikáció során nagyobb hangsúlyt kapna, hogy ezek az adat átvételek csak lehetőségként vannak és továbbra mennyire fontos az adatok ellenőrzése és bizonyos hibás adatszolgáltatások átvétele esetén a felelősség a befogadói oldalt is érinti.
