### ISSUE TITLE
[Q&A] Számla tételek között lévő szövegsorok 

### ISSUE THREAD

**Issue by PalPalotai** [nav-gov-hu/Online-Invoice#376]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Sziasztok,
A rendszerünkben lehetőség van a számlázott tételek közöt mennyiség és ár nélküli egyszerű szövegsorok rögzítésére, ílyen módon  hosszabb szövegek, tétel leírások is szerepeltethetőek a számlán. Azért fontos a tétel sorok között ezeket szerepeltetni mert az egyes számlázott tételekhez kapcsolódnak. Mivel minden tétel sor esetében az ÁFA kódot kötelezően meg kell adni ezért ezeket vatOutOfScope-ként jelöltük meg. A tervezett változások között szerepel hogy a vatOutOfScope és vatExemption jelölések esetén külön API kód és szöveges indoklás lesz elvárt, de az ilyen szövegsor esetében ezek nem lesznek értelmezhetőek, a rendszer használóitól sem elvárható hogy feleslegesen adjanak meg ilyen adatokat.

**Comment by PalPalotai** [comment]
Sziasztok,
Véletlenül küldtem be, még befejezem a kérdést:
A rendszerünkben lehetőség van a számlázott tételek közöt mennyiség és ár nélküli egyszerű szövegsorok rögzítésére, ílyen módon hosszabb szövegek, tétel leírások is szerepeltethetőek a számlán. Azért fontos a tétel sorok között ezeket szerepeltetni mert az egyes számlázott tételekhez kapcsolódnak. Mivel minden tétel sor esetében az ÁFA kódot kötelezően meg kell adni ezért ezeket vatOutOfScope-ként jelöltük meg. A tervezett változások között szerepel hogy a vatOutOfScope és vatExemption jelölések esetén külön API kód és szöveges indoklás lesz elvárt, de az ilyen szövegsor esetében ezek nem lesznek értelmezhetőek, a rendszer használóitól sem elvárható hogy feleslegesen adjanak meg ilyen adatokat. Mi lenne ilyenkor a helyes eljárás az ilyen szövegsorok esetében? Vagy esetleg van lehetőség más módon az ilyen sorok lejelentése?
Köszönettel,

**Comment by betasofthu** [comment]
Ezt jelenleg úgy tudod megcsinálni, hogy a számla tétel csak megnevezést (lineDescription) és áfa kulcsot tartalmaz, a többi adatot nem. Megjegyzést fűz hozzá az adóhivatal, de elfogadja.   Ezt be kell vállalni. Én megmondtam a felhasználóknak, hogy továbbra is lehet ilyet, de megjegyzés jön rá. Nálam ez ugyanabba az áfa kulcsba tartozik, ahová a számla tétel, így nem kell külön összesíteni.

**Comment by omachtandras** [comment]
PalPalotai: a szövegnek van sorszáma, vagy nincs és sorszámilag a megelőző sorhoz tartozik? Egy ideig a mi rendszerünkben lehetett olyan szövegsort felvenni, amelynek külön sorszáma volt, és betasofthu által leírt módon adtuk át a NAVnak, egészen addig, míg az egyik ügyfelünk nem kapott egy ellenőrzést, amelyben leírták, hogy ez így nem ok, mert bizony egy olyan sor kerül hozzájuk átadásra, ami a számlán nem szerepel (lévén a szöveg sornak valóban nincs ÁFA kulcsa a számlaképen), és ezt a gyakorlatot szüntesse meg amilyen gyorsan tudja, mert ebből büntetés lesz, ha nem így tesz.
Úgyhogy mi úgy döntöttünk, hogy megszüntetjük az önálló sorszámmal bíró sorok lehetőségét, megjegyzést írhat egy sorhoz tetszőlegesen, de az nem külön sorszámmal jelenik meg, és a NAVhoz sem kerül átadásra, mert ez a lineDescription-ön túli plusz megjegyzés.

**Comment by PalPalotai** [comment]
@omachtandras : Van sorszáma a szövegsoroknak, ez nem egyedi, nem eltérő a normál tétel sorokétól, követi az értékkel rendelkező sorszámozást. Ha nem küldjük be a NAV-hoz akkor akár az értékkel rendelkező sorok tétel leírása befejezetlen, értelmetlen is lehet.

**Comment by sinick2** [comment]
Én az ilyen szöveget additionalLineData taggal hozzápattintom az előző tételsorhoz.

**Comment by PalPalotai** [comment]
@sinick2: Köszi, de ez amiatt nem tud működni hogy lehetnek, vannak esetek amikor nem érték adatokat tartalmazó(ak) az első számla sor(ok) hanem szövegsor, ezt a megoldást ezért nem választottuk.

**Comment by sinick2** [comment]
@PalPalotai: Értem, nyilván. (Első sor ilyen jellegű felvitelét tiltottam, mert nem akartam megvárni, amikor a WARN-ból ERROR lesz. Szerencsémre az ügyfelek kb. két százaléka számlázott így, ők megértették.)

**Comment by NTCA-tax** [comment]
Amennyiben egy adott tételsor leírásához kapcsolódik a megjegyzés (és nélküle a gazdasági esemény nem értelmezhető), akkor a lineDescription-nek kellene tartalmaznia. Amennyiben egyéb más információk vannak benne, akkor vagy kihagyjátok az adatszolgáltatásból (hiszen az áfa törvény kizárólag az értékesített termék, szolgáltatás megnevezését várja el), vagy pedig additionalData-ban lesz benne.

Azt az esetet nem tudom hirtelen értelmezni, hogy az első tételsor egy megjegyzés a számlán. Egy megjegyzés szerintem vagy tételsorhoz kapcsolódik, vagy a számla egészéhez. Lehet, hogy a felhasználók számára engedett ilyen mértékű szabadságfok jobban túlbonyolítja a rendszert, mint amekkora érdek fűződik annak fenntartásában.

**Comment by PalPalotai** [comment]
@NTCA-tax: Nagyon sok cég kiemelkedő figyelmet fordít az általa kiadott, nyomtatott dokumentumok, így a számla megjelenésére, annak kinézetére, ezeknek marketing értéke is van. Miért elképzelhetetlen az hogy a partner által elvárt hosszabb szövegezést tartalmazzon (pl. pályázathoz kapcsolódó számlázás esetén) akár több sorban is egy számla? Ilyenkor simán előfordulhat hogy formai, alaki okokból csak szöbeggel kezdődik egy számla, a hosszabb szövegezés miatt több sorban nyomtatjuk, mert egyetlen sorban nem fér ki a szöveg, az érték adatok pedig az utolsó szövegrészlethez tartozó sorban szerepelnek. Ha egyszerűen kihagyjuk a szövegsorokat akkor értelmezhetetlen lehet a számlázott tétel. Illetve az eddigi NAV kommunikáció szerint arra törekszik a NAV hogy akár adatcsere is megvalósulhasson az adózók között. Ha kihagyjuk a szövegsorokat ill. nem biztosít a NAV ennek feltüntetésére egyszerű lehetőséget akkor hogy lesz teljes körűen megvalósítható ez az adatcsere? Most lehet az lesz a válasz, hogy tiltsuk meg azt hogy az első sor csak szövegsor legyen, de azért ne már a mai világban hogy ilyen korlátozásokat kelljen bevezetni.

**Comment by EPluribusUnum** [comment]
Szerintem mást értetek "sor" alatt és ebből van a zavar.
NAV szerintem a sor alatt nem a FIZIKAI nyomtatott sorra hivatkozik, hanem egy tételhez tartozó összes adatra, a tétel tábla egy sorára, egyetlen rekordra. Az a rekord nyomtatva fizikailag lehet több oldal is, ha a lorem ipsum be van téve megjegyzésnek a tételhez. Nyomtatásnál és beküldésnél is a sorszámozás a számla tételsorra vonatkozik, és nem az hogy a nyomtatásban hanyadik soron jelenik meg a szöveg.
Nem a fizikai reprezentációt kell feltölteni hanem a fizikai reprezentáción megjelenő adatokat logikai struktúrába öntve.

**Comment by PalPalotai** [comment]
@EPluribusUnum: Mit lehet ezen szerinted eltérően értelmezni? Egy nagyon egyszerű példát csatolok, ami napi szintű egy számlán, és nem kirívó eset. Ha valóban komplex adatcserét is biztosítani akar a NAV, ami egyébként dicséretes és tök jó törekvés, akkor a szövegsorokat is le kellene kezelniük véleményem szerint. De szerintem maradunk az eddigi gyakorlatunknál.
![Minta_Szamla](https://user-images.githubusercontent.com/68586300/94679482-78798a00-0320-11eb-8f3f-9b7313a918e3.png)

**Comment by KMGY100** [comment]
Szerencsésebb lenne:   **additionalInvoiceData** - val
A tételek előtt megjelenő szövegrész 
És még szükség lehet a tételek után megjelenő megjegyzés szövegrészre is.

VAGY:
A tétel szövege kiegészül a Leírás szövegével (mindkettő tételnél)

**Comment by PalPalotai** [comment]
Hú srácok, nem gondoltam hogy ez ennyire felkavar itt többeket is... Még egyszer, szöveges információkkal kezdődik a számla ami nem feltétlenül a számla egészére vonatkozik hanem az utána következő, értékkel rendelkező sorokra, Ha egy számlát továbbítani akarok a partnernek akkor nem technikailag additional adatként akarom továbbítani hanem ahogyan a számlán szerepel, elsődleges információként. Mert formailag, kinézetre így tartja a számla kiállítója normálisnak, elfogadható kinézetűnek a számlát. és az hogy ha csak az értékkel bíró sort küldjük be a NAV-nak, hogy pl. "szerint számlázott összeg" (mert ez esik éppen a számlázási értéket tartalamazó sorba) nem igazán fedi le a számlázott tétel egyértelmű megnevezését,

**Comment by PalPalotai** [comment]
Ja, és látszik a korábban küldött példán hogy még olyan unortodox sorok is szerepelnek a számlán mint pl. üres sorok, csak a formailag "pofásabb" kinézet miatt. Ez is tök elképzelhetelen ugye, mert az ÁFA törvény ilyet nem tartalmaz? Csak az ügyfél akar ilyen "nem normális" adatokat egy nyomtatott dokumentumon és adott esetben a partner felé is továbbítani. Nem szeretnénk extra lekezelést, csak pl. egy nagyon egyszerű boolean mezőt amivel lehetne jelölni hogy ez szövegsor, nem kell az ÁFA kódokat megadni (nem is lehet) és felesleges nullás sorokat generálni az ÁFA összesítőben, és az adatcsere lehetőségét is fenntarva megjelölni a sort, hogy ehhez érték adatok nem tartoznak, csak szöveges információt tartalmaz amit a másik fél is láthat ha úgy dönt, hogy a NAV felületéről tölti le a felé kiállított számlákat. Ennyire egyszerű amit szeretnénk, és nem gondolom hogy ezzel egyedül lennénk, egy számla nem csak egyszerűen egy számla, nagyon sok esetben egy piaci és marketing szempontból is rendkívül értékes dokumentum, ezt a NAV-nak is tudomásul kell vennie. Ha ez most valóban egy vízválasztó, hosszabb időtartamra is meghatározó fejlesztési stratégiát meghatározó verzió lesz (mármint a 3.0) akkor ezt a módosítást most kell megcsinálni, ennyi az oka amiért ezen "rugózok". És nem gondolom hogy ez egy megugorhatatlan, óriási problémát okozó fejlesztés lenne a NAV részéről.

**Comment by betasofthu** [comment]
"csak pl. egy nagyon egyszerű boolean mezőt "
Inkább ne már! Volt már ilyen, a "lineNatureIndicator". Ennek a bevezetése is elég sok problémát okozott. Miattatok írják át a többiek a programjukat? Ne már!

**Comment by PalPalotai** [comment]
@betasofthu: egy opcionális és nem kötelező mező használata neked ennyire problémás lenne? szerintem jobban gondold át mielőtt ilyet írsz és gondold át mivel fpglalkozol, mi az amivel dolgozol

**Comment by KMGY100** [comment]
@PalPalotai     """ezt a módosítást most kell megcsinálni"""
A kijelentés határozott, de rossz pozícióban vagy.
Szerintem rajtad kívül senkinek sem kell az ötleted, mivel
a meglévő eszközökkel el lehet érni amit gondolsz.

**Comment by PalPalotai** [comment]
@KMGY100: Szerintem meg Te vagy rossz pozízióban vagy rossz felhasználónévvel kommentelsz, ha ennyire a NAV állíápontját képviseled. Tegnapig volt a véleményezési időszak, eddig lehetett az igényeket jelezni. Ez az volt. Valamint mi lenne ha mielőtt bármilyen hasonló tiszteletre méltó és magasröptű hozzászólást írsz egy topic-ra előtte elolvasnád az előzményeket? Nem vagyunk egyedül ezzel a problémával. Lehet hogy Te egy dobozos szoftverrel dolgozol, de tudod vannak még az SAP-hoz hasonló rendszerek, annál bizonyos modulok szempontjából még kifinomultabbak is, amelyek maximálisan igyekeznek az ügyfelek igényeit kielégíteni, olyanokét is akik rendkívül kényesek egy dokumentum kinézetére.
1. Nem csak a mi rendszerünkben van ilyen "elvetemült" adat, másnál is.
2. Mindenki valamilyen úton, módon ezt lekezelte eddig is, a jövőben is le fogja. Mivel indoklást is meg kell adni, röviden mi be fogjuk írni hogy "szövegsor" és kész.
3. Miért ne lehetne ezt sokkal egyszerűbben, nem kötelező mező, jelölés alkalmazásával ezt megtenni? Mivel ez most egy hosszú távra tervezett NAV Online verzió, miért olyan oltári nagy probléma ennek az igénynek a jelzése? Semmi drámai módosítás, nem kötelező jelleg, csak egy opcionális adat, és mindenki boldog. Ilyen óriási probléma ez? Ami időt itt a levelezéskkel eltöltöttünk már ennek töredéke alatt a saját fejlesztőink már réges régen megoldották volna. Röhej....

**Comment by PalPalotai** [comment]
Lezártátok, gratula, ennyit a felhasználói igényekről....

**Comment by NTCA-developer** [comment]
@PalPalotai 

Csak felhívnám a figyelmed erre az apróságra:
>  @PalPalotai PalPalotai closed this 2 days ago 

De nincs pánik, fel tudod nyitni.
