### ISSUE TITLE
Email üzeneteik intelligenssé tétele

### ISSUE THREAD

**Issue by pvmon** [nav-gov-hu/Online-Invoice#377]
Megoldható lenne, hogy az automata e-mail küldözgetőjük ne jelezzen a felhasználó felé, amikor a szerverük rosszul működik (mint ma is) és vagy befogad egy számlát vagy nem, de nem ad vissza ID-t timeouton belül?
Emiatt nem lehet biztosra tudni, hogy a számla felment-e. Ilyenkor a program újraküldi és ha a rendszerük mégis befogadta csak nem adott választ időben, akkor a rendszerük később küld egy e-mailt a felhasználónak hogy kétszer szolgáltatta ugyanazt a számlát.
Jó lenne, ha az automata levelező figyelné, hogy mikor van ez a NAV szerverének hibája miatt és olyan időszakra eső esetekre nem küldözgetne leveleket.

**Comment by fenyvessy** [comment]
Nem védeni akarom őket, de szerintem szolgáltatói szempontból az egyetlen helyes megoldás a hibajelzés küldése abban az esetben, ha tényleg dupla adatszolgáltatás történik. Az már irreleváns, hogy kinek a hibájából és miért történt, de megtörtént. Viszont téged semmi nem akadályoz meg abban, hogy ha az első küldés alkalmával nem kaptál vissza tranzakció azonosítót, akkor az újraküldés _előtt_ számlaszám alapján csinálsz egy status lekérdezést, és csak akkor küldöd újra, ha azt kapod vissza, hogy nincs ilyen számla. Ha meg már van ilyen számlaszámmal feltöltött számla, akkor ellenőrizheted az adatait (partner adószám, végösszeg, stb.), és ha egyezik, akkor mehet a tranzakció id és a feldolgozottsági állapot kezelése a szokásos módon...

**Comment by pvmon** [comment]
> Nem védeni akarom őket, de szerintem szolgáltatói szempontból az egyetlen helyes megoldás a hibajelzés küldése abban az esetben, ha tényleg dupla adatszolgáltatás történik. Az már irreleváns, hogy kinek a hibájából és miért történt, de megtörtént. Viszont téged semmi nem akadályoz meg abban, hogy ha az első küldés alkalmával nem kaptál vissza tranzakció azonosítót, akkor az újraküldés _előtt_ számlaszám alapján csinálsz egy status lekérdezést, és csak akkor küldöd újra, ha azt kapod vissza, hogy nincs ilyen számla. Ha meg már van ilyen számlaszámmal feltöltött számla, akkor ellenőrizheted az adatait (partner adószám, végösszeg, stb.), és ha egyezik, akkor mehet a tranzakció id és a feldolgozottsági állapot kezelése a szokásos módon az újraküldés helyett...

Ne felejtsük el, hogy a régebbi verziókban nem volt ilyen lehetőség, ezért az ID-t használtuk. E-mailezgetés sem volt...

**Comment by EPluribusUnum** [comment]
@fenyvessy , ha minden beküldés előtt mindenki még tol egy extra lekérdezést, szerinted az mennyire fogja megfekteni a NAV szervereket az extra terhelés? Még most sem képesek kiszolgálni minket, pedig a magánszemély és a külföldi számla lejelentés el sem indult még.
Doksiba beleírták hog yelvárás a kliens oldaltól hogy a unique hiba le legyen kezelve, mert performace miatt nem tudják szerver oldalon ennek az ellenőrzését bevállalni. Ha a kliens ezt teljesíti (és mi teljesítjük) is, akkor minek zaklatják az ügyfeleinket ilyen levéllel. A dupla beküldés alapvetően nem kliens hiba, hanem a NAV oldali hiba, hogy nem képes időben választ adni a beküldésre.

**Comment by pvmon** [comment]
>  Ha a kliens ezt teljesíti (és mi teljesítjük) is, akkor minek zaklatják az ügyfeleinket ilyen levéllel. A dupla beküldés alapvetően nem kliens hiba, hanem a NAV oldali hiba, hogy nem képes időben választ adni.

Teljesen egyetértek! És nem is volt ezzel gond, amíg nem jött a NAV-tól az email, akkor is amikor tudhatnák, hogy miattuk van.

**Comment by pvmon** [comment]
Elhangozott hogy nem a NAV végzi a beküldést, De a NAV-nak kellene az átvételről visszaigazolást adnia és azt viszont nem végzi el időn belül, de az adatot visszajelzés nélkül letárolja. Itt a probléma a szerver oldalról érkezik, ami máskor normálisan működik. Lehet lekérdezgetni számlaszámot, de ilyen NAV szerver állapotban az sem működik. Az elmúlt napok jól mutatják ezt.

Viszont törvény írja elő, hogy mennyi időn belül  kell beküldeni a számlát. Nem várhat a kliens program napokig arra, hogy most felment vagy sem és stabilan működik a NAV szerver vagy véletlenszerűen akadozik. Ezért mi inkább újra küldjük, ha nem tudunk biztosat a számla állapotáról, mert a nem beküldött számlára viszont van büntetés előírás.

Csak annyit szeretnék, amikor NAV-nál is tudják, hogy akadozott a szolgáltatásuk, akkor ne küldjenek ki ilyen jellegű levelet. az aznapi számlákkal kapcsolatban, máskor nyugodtan, mert akkor általában nincs is mit. Ez könnyítené az ügyfélszolgálat munkáját, ami már úgyis kap elég terhelést, amikor leáll vagy akadozik a NAV szerver.

**Comment by csaszko** [comment]
#433 
Újabb példa arra, hogy jobb lenne az emailek küldözgetését jobban átgondolni.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ezt zárom, ha van még aktuális probléma, akkor nyissatok új issuet kérlek.
Üdv
