### ISSUE TITLE
queryInvoiceChainDigest response XML probléma újra

### ISSUE THREAD

**Issue by rgform** [nav-gov-hu/Online-Invoice#379]
Az eredeti probléma itt lett kitárgyalva, de újra elő jött és súlyosbodott helyzet.  
[https://github.com/nav-gov-hu/Online-Invoice/issues/331](https://github.com/nav-gov-hu/Online-Invoice/issues/331)

A QueryInvoiceChaindigest nemhogy több részletben adja vissza a sorok intervallumát, de már az összes sort (maxLineNumber) is rosszul adja vissza?!  **A számla alapszámla és 14 soros.**
```

      </invoiceChainDigest>
      <invoiceLines>
        <maxLineNumber>9</maxLineNumber>
        <newCreatedLines>
          <lineNumberIntervalStart>10</lineNumberIntervalStart>
          <lineNumberIntervalEnd>14</lineNumberIntervalEnd>
        </newCreatedLines>
        <newCreatedLines>
          <lineNumberIntervalStart>1</lineNumberIntervalStart>
          <lineNumberIntervalEnd>9</lineNumberIntervalEnd>
        </newCreatedLines>
      </invoiceLines>
      <invoiceReferenceData>
        <modifyWithoutMaster>false</modifyWithoutMaster>
      </invoiceReferenceData>
    </invoiceChainElement>
  </invoiceChainDigestResult>
</QueryInvoiceChainDigestResponse>
```

Minden Módosító és Érvénytelenítő beküldése előtt lekérjük a számlaláncot a helyes sorszámozás végett, ez innentől ABORTED számlát eredményez.
 
Üdvözlettel, PPSOFT

**Comment by EPluribusUnum** [comment]
@NTCA-tax , @NTCA-developer , @NTCA-supporter , a queryInvoiceChainDigest fixen le lett kapcsolva? 404-es választ kapunk folyamatosan.
Így a tegnapi instabilitás után ma nem lehet az INVOICE_NUMBER_NOT_UNIQUE hibákat lekezelni, mert ahhoz szükség van a queryInvoiceChainDigest használatára.

**Comment by rgform** [comment]
T. NTCA Supporter!

Mi az eddigi megállapítás a hibáról?  Ellenkezik a 2.12 frissítésben kihirdetettel:

"A „queryInvoiceChainDigest” válaszban a rendszer már nem adja vissza CREATE számla esetén a „newCreatedLines”, illetve az „invoiceReferenceData” csomópontot. "

Továbbá rosszul számolja a beküldött sorokat.  Így nem lehetséges a módosító számla beküldése, mert ABORT lesz az ismétlődő sorok miatt...

Üdvözlettel, PPSOFT

**Comment by NTCA-supporter** [comment]
Sziasztok!

Fennáll még a probléma?
Ha igen, akkor kérlek küldj azonosítót a teszt rendszerből, mivel ezen fórumot hivatalosan azt supportáljuk.
Köszönöm

**Comment by EPluribusUnum** [comment]
@NTCA-supporter , részemről zárható, rendben van. Aznap délutánra rendbe jött, azóta jönnek a válaszok.
