### ISSUE TITLE
[FEATURE] A kötelező adatok körének csökkentése

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#38]
**Az igény összefoglalása / Summary of the request**
Deklaráltan két cél van a NAV részéről az OSZ megszületésénerk : #1 ellenőrzés, #2 jövőben bevallás készítése a NAV oldalon. Ezek egyikse sem indokolja hogy ennyi kötelező adatot kelljen beküldeni.

**Az általam javasolt megoldás / The solution I propose**
Csak a fenti két célt szolgáló adatok töltése legyen kötelező.

**Elfogadható alternatívák / Acceptable alternatives**
Opcionálisan egy base64 mezőbe betölthető adat ami a vevő publikus kulcsával került titkosításra még a feladó oldalán, így a vevő a számla letöltésnél támogatást kap a számlaadatok beemelésére a saját ERP rendszerébe., viszont a NAV így nem látna rá olyan adatokra ami nem tartozik rá, csak a vevőre és a szállítóra.

**Comment by NTCA-developer** [comment]
Szia!

Köszönjük a felvetésed. 

Az érvelésed eléggé radikális, de ez persze nem baj. Az ellenőrzés és a jövőbeni bevallás készítés mint kizárólagos cél kicsit sarkos, ezen felül vannak még más okból megkövetelt adatok is és más felhasználási területek is.

Van az Online Számla holnapon egy előadás csomag, ahol van egy nagyon jó összefoglalás arról, hogy mikor-mit-miért kell beküldeni. A linkjét ide másolom: https://onlineszamla.nav.gov.hu/api/files/container/download/OnlineSzamlaFejlesztoiForum_Prezentaciok_es_prog_mintak.zip 

Remélem nem haragszol meg érte, de ezt a ticketet (mint javaslatot) most rövidre zárnám. Ha van kérdésed, hogy melyik taget miért kérjük be, akkor nyugodtan adj fel rá külön Q&A jegyet.
