### ISSUE TITLE
[Q&A]Parallel Support of NAV version 2.0 and 3.0

### ISSUE THREAD

**Issue by sabine089** [nav-gov-hu/Online-Invoice#380]
Hi,
in the Changelog I found this:
> Based on our experiences with upgrading to 2.0, our internal processing systems have been prepared to receive production data using v2.0 and v3.0 format in parallel.

That is very good for us as a software provider, as we update our clients in early December with the new version. So we can start sending v3.0 format already at that time.

But some lines further down, the Changelog says:
> New ERROR: A new generic temporary error code has been added to be returned the first time when a v3.0 data exchange equivalent to an electronic invoice is received before 01.01.2021.

How does that match? Is the focus on "electronic" invoice? Will I be able to send a v3.0 format with invoiceAppearance "Paper" before 01.01.2021? If so, then all is fine.

Thanks for your attention!
Sabine

**Comment by NTCA-supporter** [comment]
Hi @sabine089 !

The new error message you mentioned is related to the new completenessIndicator tag. So you won't be able to send v3.0 data reports where the completenessIndicator is true, before 01.01.2021.

You'll be able to send v3.0 format with all the possible invoiceAppearance types (and with completenessIndicator = false value).

Br

**Comment by NTCA-supporter** [comment]
Hi!

I close this issue. If you have any further question, please reopen it.

Thanks
