### ISSUE TITLE
Technikai felhasználó kizárólag adószám ellenőrzésre

### ISSUE THREAD

**Issue by veerede** [nav-gov-hu/Online-Invoice#381]
Az ügyfélkörünkben felmerült az igény, hogy kliens programból tudjanak adószámot lekérdezni, ellenőrizni de ne tudjanak (átmenetileg vagy tartósan) számlát lekérdezni vagy feltölteni. Természetesen a szoftverben meg tudjuk valósítani ezt a korlátozást de a megbízóinknak az lenne a megnyugtató, ha ezen igények kiszolgálására olyan technikai felhasználót tudnának létrehozni, amely kizárólag az adószám lekérdezésére jogosult.

Lehet, hogy én vagyok a béna de ezt a jogosultsági beállítást technikai felhasználónál nem tudtam elérni.

Üdv
Ede

**Comment by NTCA-supporter** [comment]
Szia @veerede !
A queryTaxpayer operáció a Számlák kezelése (technikai felhasználó) jogosultsághoz kötött, mivel úgy kerek a történet, hogy ha számlát tudsz beküldeni, akkor előtte pl. lekérdezhesd a vevői adószámot. 
Mivel ez kis funkció, így erre külön saját jogosultságot nem terveztünk, és eddig nem is volt rá igény.
Esetleg a felületen a Szolgáltatások/Adózó lekérdező nem elegendő az ügyfélnek?
Vagy ugye a NAV holnapon is van ilyen.

Üdv

**Comment by veerede** [comment]
Természetesen nem:).
Valójában ez a funkció anonim módon is elérhető lehetne, de megértem, hogy azonosítás nélkül nem működtethető. Úgy érzem, hogy nem vagyok egyedül ezzel az igénnyel. 
Nem is kérnék rá külön jogot. Szerintem a technikai felhasználó érvényes állapota is elegendő lehetne ehhez a funkcióhoz. 
((Vagy esetleg kaphatna egy új jogot, ami majd későbbi hasonló funkciókra is engedélyül szolgálhatna.))

**Comment by NTCA-supporter** [comment]
Szia @veerede !
Ezt az új jogosultságot sajnos nem tudjuk támogatni, vannak ettől nagyobb prioriátású dolgok.
Maradnak az eddigi megoldások.
Köszi a megértést, zárom az issuet.
Üdv
