### ISSUE TITLE
[Q&A] Egyszerűsített számla esetén 0%os adókulcs elfogadott?

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#382]
NTCA-tax-hoz lenne egy kérdésem.

Normál számla esetén ha 0%os kulcsot küldünk be, akkor error kóddal visszajön:
Business validation :
ERROR/INVALID_VAT_DATA : A számlában megadott áfakulcs vagy áfaérték nem engedélyezett. (1. számla tétel : InvoiceData/invoiceMain/invoice/invoiceLines/line/lineAmountsNormal/lineVatRate/vatPercentage = 0.0000)

Egyik ügyfelünknél a NAVtól olyan tárgyi adómentes EGYSZERŰSÍTETT számlaadat érkezett, amelyben 0%os ÁFA kulcs szerepel (VATPercentage van töltve).
Az eredeti bizonylaton, amelyről az adatszolgáltatás szól a következő szöveg található: E TAM (0.00%).

A kérdésem a következő: egyszerűsített számla esetén megengedett, hogy az adómentes tételeket 0%os kulccsal szolgáltassa a számla kiállító szoftver? Kell erre készülnünk? Vagy ezen az ágon elmaradt ez az ERROR típusú ellenőrzés?

Köszönöm!

**Comment by celeburdi** [comment]
A kézi adatszolgáltatásnál az egyszerűsített számla lejelentésnél nem lehet csak %-os ÁFA-t választani.
Hogyan kell lejelenteni helyesen az egyszerűsített számlán kiállított adómentes értékesítést.
-0% áfa tartalom és kész?

**Comment by NTCA-tax** [comment]
2.0-ban az egyszerűsített számla esetén az adótartalom nélküli számlákat 0%-kal kellett jelenteni. A 3.0-ás verziótól erre már nincs lehetőség. Az áfa törvény alapján a mentesség okát számla típustól függetlenül meg kell adni, tehát az egyszerűsítés erre nem terjed ki. Bár hozzá kell tenni, hogy adattartalmilag egy adómentes számla és egyszerűsített számla egymástól nem tér el (az egyszerűsítés épp az adóalap, adó összeg megbontásnak az egyszerűsítését jelenti), ezért túlságosan sok gyakorlati értelme nincs számlázó program esetén egyszerűsített adómentes számlát kiállítani. Ugyanakkor az Online Számla rendszerből azt látjuk, hogy többen mégis ezt csinálják, ezért vezettük be a 3.0-ban a mentességnek, hatályon kívüliségnek stb. jelölési kötelezettségét.

**Comment by omachtandras** [comment]
Köszönöm a választ, megpróbáljuk március végéig kezelni a problémát.
