### ISSUE TITLE
[Q&A] DONE státusz esetén nem található számla

### ISSUE THREAD

**Issue by lvitya586** [nav-gov-hu/Online-Invoice#385]
Múlt hét óta több számlám is úgy járt, hogy van hozzá visszaigazolt DONE státusz, de ha lekérem queryInvoiceDigest-el, akkor az nem hozza fel, továbbá a queryInvoiceCheck is False értéket ad vissza, mintha nem létezne a számla. Ilyen esetben mi a teendő? Be kéne küldeni újra őket? De mi van azokkal, amik már több naposak? 

Már csak azért is érdekes ez a jelenség, mert a törvényi kötelezettség csak odáig terjed ki, hogy legyen a számlához DONE státusz a NAV részéről, azt nem kell nézegetni a visszaigazolás ellenére, hogy a felküldött számla valóban bent van-e.

Itt van példának néhány tranzakció:

33PD34ZEJM9JMWGY
33PD3B0U0LJUVW7M
33PFWZS2AMGF7AP0
33PFX5GV8J9ROU02
33PFXDMY6XAXIOGS
33PFXNU0QP3OP9XI
33PFXU0FG6JCBLYG
33QX7J4BTHRLAI7Y
33QXC1CL1NVQE3OZ
33S60JF28Q6KDSHP
33TVMFCRRUIKDGQT
33TVPH46RV3KQQ75
33TVT1ULL5YZ6B52
33XZC6S6KWBCE4QK
33XZCDU3T9CT8PR8
343LQTVKBQQWI27W
343LVH4NK13YNN7B
343LYIOOAT12R6UM
343LYRIR03WY2SBU
343M38Q543ETGDFD
3441OB9IJLXTE3KI
3441OH5Q9Y3RNU6M
3441SKPXCX2S8TZE
3441YTZ8X576E3VG

**Comment by laladisc** [comment]
Ez komoly? Ilyen tényleg előfordulhat? Mert ha igen, akkor igencsak át kell értékelni a DONE státusz jelentőségét. Megmondom őszintén, hogy eddig teljesen nyugodt voltam, ha DONE-t kapott egy adatszolgáltatás akkor az biztos hogy bent van és mindenki nyugodtan hátradőlhet.

**Comment by NTCA-supporter** [comment]
Szia @lvitya586 !

Kezdjük azzal, hogy ez teszt vagy éles környezet?
Amit küldtél azonosító, az a számlabeküldéskor válaszban kapott transactionId vagy az általad generált requestId?

Köszi

**Comment by NTCA-developer** [comment]
És bármi is lesz a válasz, ez mellett kellene egy transactionId párt is írnod. Egy azonosítót arra a státusz lekérdezésre, amire DONE-t kaptál, és egy másikat amiben azt a számlát kérdezed le, amire DONE-t adtunk vissza. Ezt kérlek küldd el és vagy mi, vagy a HD megnézi.

**Comment by lvitya586** [comment]
Szia @NTCA-supporter és @NTCA-developer !

Először is köszönöm, hogy hétvégén is foglalkoztok ezzel a kérdéssel. 
Az általam megadott tranzakciók természetesen az éles rendszerben vannak és a manageInvoice hivások NAV által visszaküldött transactionID-jai.
De vegyük akkor az elsőt példának, csatoltam hozzá fálokat (az érzékenyebb adatokat kivettem).

[manageInvoiceRequest.txt](https://github.com/nav-gov-hu/Online-Invoice/files/5288399/manageInvoiceRequest.txt)

[manageInvoiceResponse.txt](https://github.com/nav-gov-hu/Online-Invoice/files/5288414/manageInvoiceResponse.txt)

[queryTransactionStatusRequest.txt](https://github.com/nav-gov-hu/Online-Invoice/files/5288418/queryTransactionStatusRequest.txt)

[queryTransactionStatusResponse.txt](https://github.com/nav-gov-hu/Online-Invoice/files/5288419/queryTransactionStatusResponse.txt)

**Comment by NTCA-developer** [comment]
Szia @lvitya586 

Megnéztük a HD-val az élest és a tesztet. Az a szomorú hírem hogy a kérésben szereplő 33PD34ZEJM9JMWGY tranzakció azonosító globálisan nincs az élesen, ellenben a teszten megtaláltam, pontosan azzal az exchangeToken értékkel, amit a beküldésbe is beírtál.

Szóval ez nálad keveredhetett össze nagyon. Majd nézzétek meg, hogy mi hiányzik és pótoljátok az élesen.

**Comment by lvitya586** [comment]
@NTCA-developer , köszönöm az utánajárást.
Nem tudom ezt hogy sikerült összehozni.
Zárom a issue-t.

**Comment by NTCA-developer** [comment]
Nincs mit. Azon gondolkozom, hogy lehet hogy a tesztes beküldések válaszában fixen vissza kellene adnunk egy notification-t, hogy az ilyen esetek nálatok is detektálhatók legyenek.

Ehhez az kellene hogy a mostani common-ban listává alakítjuk a notification taget, és akkor már key-value alapon adnánk vissza, hogy nektek mégse a szövegből kelljen substringelgetni ha feltételezni akartok rá. Valahogy így:
`<notifications>
   <notification>
      <code>TEST_001</code>
      <message>Ezt az üzenetet az Online számla teszt rendszer dolgozta fel.</message>
   </notification>
</notifications>
`

**Comment by lvitya586** [comment]
Az mondjuk nem lenne rossz, ha egy ilyen figyelmeztetés lenne, mert akkor rögtön észre lehetne venni az ilyen kavarodást.

**Comment by NTCA-developer** [comment]
Szia @lvitya586 

Most mergeltem be a common repository alá azt a módosítást, hogy a notification lista legyen. Adtam ki új RC-t is és az Online számla oldalon is kint van az új common. 

Valamikor a 3.0 mellékvágányaként megcsináljuk ezt a fejlesztést akkor.

**Comment by lvitya586** [comment]
Köszönöm a fejlesztést @NTCA-developer !
