### ISSUE TITLE
Számla szátusza folyamatosan "Feldolgozás alatt" napok óta semmi változás

### ISSUE THREAD

**Issue by WittmannWien** [nav-gov-hu/Online-Invoice#387]
Kedves Support,

a következő problémával szembesülök, hogy a múlt héten történt technikai probléma óta: csekély mértékben, de számlák ragadnak "feldolgozás alatti" státuszba, és ez a státusz nem változik.

Emiatt sajnos a számla soha nem kerül befogadásra, és ez egy nagy probléma.

Mit kellene tenni? Mi a mechanizmus, ilyen jellegü hibák javítására? Email küldés a Nav-hoz megtörtént, egyelőre semmi reakció.

Előre is köszönöm.

Üdv
Péter

**Comment by era910413** [comment]
Ez engem is érdekelne, mivel nálunk is van néhány ilyen számla. Jelentettem a helpdesk-en, de számomra sem jeleztek még vissza...

**Comment by WittmannWien** [comment]
mint Info:
ma reggel a függö számláim Done-nal visszaigazolásra kerültek. Nálunk jelenleg minden rendben.
