### ISSUE TITLE
Prod: no answer for QueryInvoiceDigestRequest

### ISSUE THREAD

**Issue by hamvasgy** [nav-gov-hu/Online-Invoice#388]
A produktív online számla adatszolgáltatás környezetben próbálunk QueryInvoiceDigestRequest funkciót használni, de nem kapunk rá választ. Pl:
<requestId>e3618e67c03f4ffd95b539bcfca421</requestId>
<timestamp>2020-09-28T10:10:02.427Z</timestamp>
:::
<originalInvoiceNumber>4000013441</originalInvoiceNumber>

A programunk hibaüzenete:
{"inboundPortBindingId":"ProductionInfrastructure@de.telekom.dms.architecture.DMS:DMS4ERP:NAV_HU_v2@UsingPort","outboundPortBindingId":"ProductionInfrastructure@de.external.navhu.architecture.NAV_HU:Core:NavHu_v2@ProvidingPort","errorMessage":"Sending message failed: 'Read timed out'","errorCode":2079,"systemIdentifier":"extern","timestamp":"2020-09-28T10:10:12.491Z","logPointId":"6082A9374CB2DB7A4A4E53D144ACB76E","requestId":"3f0560af-9d18-4966-a790-1a4a85fd8651"}

Kérjük a hiba kivizsgálását/javítását

Köszönettel
Hamvas György /Magyar Telekom Nyrt

**Comment by connorhu** [comment]
Prod környezet hibáit nem itt kell jelezni. Itt csak teszt rendszert és fejlesztést érintő problémákkal foglalkoznak.

**Comment by hamvasgy** [comment]
A prod hibák jelzése itt: https://www.nav.gov.hu/nav/e-ugyfsz/levelkuldes ?
Vagy van más csatorna is?

**Comment by NTCA-supporter** [comment]
Szia @hamvasgy !
Ez csak egyedi probléma, vagy minden lekérdezésnél ezt kapod?
Nem tudunk általános hibáról, hogy pl. senkinél se működne a szolgáltatás.
Üdv

**Comment by hamvasgy** [comment]
Szia,

A lekérdezés be van építve az adatszolgáltatásba. Ritkán adunk fel olyan számlát, ahol erre szükség van, de 2020.09.28 és 2020.09.29 közt ötből számlánál is előfordult.
Közös jellemző, hogy a lekérdezett számla nem szerepelt a NAV rendszerében.

Négy számla esetén a QueryInvoiceDigestRequest-re nem kaptunk választ:
2891113706
  /requestId/ e3618e67c03f4ffd95b539bcfca421
  /timestamp/ 2020-09-28T10:10:02.427Z
  megismételve új lekérdezésként sok alkalommal
2891113759
  /requestId/ 0971b14327374d2fbadd0ad4d688f1
  /timestamp/ 2020-09-29T07:50:01.418Z
és még megismételve új lekérdezésként öt alkalommal, az utolsó:
  /requestId/ 218c874b44634fbb8994b00b2b3803
  /timestamp/ 2020-09-29T10:30:03.649Z

2891113761
  /requestId/ d3ce7ded10794eb58550625e655817
  /timestamp/ 2020-09-29T08:00:15.708Z
  megismételve új lekérdezésként öt alkalommal

2891113763
QueryInvoiceDigestRequest
   /requestId/ 45e6f54614d34bbcbcb8c6b4980289
   /timestamp/ 2020-09-29T08:17:12.124Z
  megismételve új lekérdezésként öt alkalommal

Erre a számlára a második lekérdezéskor kaptunk választ és végül be is tudtuk küldeni a számlát:
2891113762
     /transactionId/  349ERP3GTV7D3RR9
QueryInvoiceDigestRequest
   /requestId/ 3817b17a03134b179c84f1f8ad822b
   /timestamp/ 2020-09-29T08:10:17.483Z

QueryInvoiceDigestResponse
  /requestId/ 3817b17a03134b179c84f1f8ad822b
  /timestamp/ 2020-09-29T08:10:17.483Z
 /availablePag/ 0

Üdv:

György Hamvas
SAP Center of Expertise<http://telefonkonyv.telekom.intra/phonebook/showOrganizationalUnit.do?oucode=1009087>
tel:         +36 30 4119744
e-mail:  hamvas.gyorgy@ext.telekom.hu

**Comment by NTCA-supporter** [comment]
Szia @hamvasgy !

Ezzel sajnos nem tudtunk foglalkozni az elmúlt időszakban.
Fennáll még a probléma?

Köszönöm

**Comment by hamvasgy** [comment]
Sziasztok,

Azóta nem fordult elő. Évente csak 20-30 olyan számla készül, ahol szükséges lekérni az előzmény számla adatait.

Üdvözlettel
Hamvas György

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet. Ha van még kérdés nyissátok újra nyugodtan.
Üdv
