### ISSUE TITLE
[Q&A] Számlabeküldés utána téves(?) hibakód

### ISSUE THREAD

**Issue by tothlp** [nav-gov-hu/Online-Invoice#389]
**Előfordulhat-e az, hogy a manageInvoice operáció hívása után a válasz szövegben megadott kód (503) és a tényleges HTTP státusz eltér?**
Alkalmazásunkban az összes 5**-as státusz esetén Újraküldés státuszba rakjuk a számlákat. Van egy javítandó státuszunk, ami 400-ra, és null válasz esetén van használva. Néhány számla esetén sajnos ebbe a státuszba álltunk, pedig a kapott  response-ban látszólag 503, Service is currently not available szöveg van. Lehetséges az, hogy valamiért az a szöveg valójában 400-as státuszkóddal jön vissza a NAV szerveréről?

A választ előre is köszönöm!

**Comment by NTCA-supporter** [comment]
Szia @tothlp !
Azóta tapasztaltál ilyet?
Teszt rendszeren is előfordult ilyen, vagy ez csak az üzemszünet során volt tapasztalható?
Ilyen jellegű működésről nem tudok.

Üdv

**Comment by NTCA-supporter** [comment]
Ezzel kapcsolatban sikerült infot szerezni?
Üdv

**Comment by tothlp** [comment]
Szia @NTCA-developer !

Nagyon sajnálom, sajnos nem kaptam a válaszokról értesítést. 😡 A probléma azóta megoldódott. Éles és teszt rendszeren is volt ilyen, de csak az üzemszünetek során. Az volt a gond, hogy az 503-mas hibáknál a válasz nem ManageInvoiceResponse-ként jött vissza, hanem HttpStatus (?) exception-ként, és a többi hibával ellentétben teljesen máshogy kellett lekezelnem.

Mindenesetre köszönöm a válaszokat!
Üdv!

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet. Ha van még kérdés nyissátok újra nyugodtan.
Üdv
