### ISSUE TITLE
[Q&A]Mi a helyzet?

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#39]
Érdeklődnék, hogy akkor most mi a helyzet ezzel a fórummal és a V2-vel?
Két hét óta a NAV részéről nincs hozzászólás.
Lejárt a V2 véleményezésére adott határidő, de számos kérdés van függőben. Vagyis még el sem indult a V2, de már csúszásban van. Lesz egyáltalán? Valamikor?

**Comment by NTCA-developer** [comment]
Sziasztok!

Bocsánat, elúsztunk jó sok mindennel, de természetesen utol fogjuk érni magunkat. Egyelőre tartjuk a határidőt, a 2.0 gyártása az eredeti tervek szerint is csak júliusban indul, így nincs csúszás. Csak annyi történt, hogy valamin időt kellett nyerni a feladatok szorításában és a reszponzivitásunkat áldoztuk be. De nincs egy kérdés/kérés sem elfelejtve, mindjárt elkezdek válaszolgatni.

Az első funkció, amit 2.0 alatt meg fogunk nyitni a számla lekérdezések lesznek. A feladatok státuszát, haladását a project board-on fogjátok tudni követni.

**Comment by NTCA-developer** [comment]
@kabelnet2 Majd zárd le kérlek, ha nem kell már a ticket.
