### ISSUE TITLE
[Q&A]Olyan adószám amihez van több cím rögzítve tesztrendszerben

### ISSUE THREAD

**Issue by martonmiklos** [nav-gov-hu/Online-Invoice#391]
Kedves @NTCA-supporter 

Tudnátok egy olyan adószámot mondani amihez van több cím is rendelve a tesztrendszerben?
(queryTaxpayerResponse/taxpayerData/taxpayerAddressList nem egy elemet tartalmaz)

Köszönöm előre is!

**Comment by NTCA-supporter** [comment]
Szia @martonmiklos !
Nem tudok ilyenről. Egyelőre úgy tudom csak elő van készítve az api a listára, de még csak 1 címet kapunk a törzsadatokba.
Üdv

**Comment by martonmiklos** [comment]
Kedves @NTCA-developer !

Köszönöm a választ! Nem lehetne-e esetleg egy adószámot betenni a teszt adatbázisba amihez van több cím rendelve?

Nyilván ki tudom mockolni az API-t a teszteléshez, de ha egy mód van nem küzdenék vele. Illetve szerintem ez a kérdés fel fog vetődni másoknál is és egy csomó időt meg tudhatnánk spórolni azzal, ha lenne erre egy teszt adószám.

**Comment by alaplap** [comment]
@martonmiklos én már annak is örülnék, ha tudna valaki mondani egy olyan adószámot, amihez a teszt rendszerben a `taypayerData`-n belül nem csak a `taypayerName`-nek van értéke. Te tudsz ilyet?

**Comment by martonmiklos** [comment]
Szia @alaplap !
Mire gondolsz pontosan? Én csak a taxPayerName-t illetve a taxPayerAddress-t használtam eddig, olyan számot tudok amihez van egy cím rendelve (de eddig én csak ilyet találtam).

**Comment by alaplap** [comment]
> Edit: juteszembe, nem amiatt üresek az adatok mert a régi sémát használod? Volt egy változtatás ami után a címek listaként vannak átadva.

De. Igazad volt, a régi (2019 decemberi) XSD alapján működött a program. Most már vannak címadataim.

> A vatCode, countyCode, vatGroupMembership AFAIK az adószámból kikalkulálható.

A `vatCode`-ot és a `vatGroupMembership`-et is küldi (csoportos adóalany pl.: MOL Nyrt, adószám: 10625790). A `countyCode`-ot viszont nem.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Továbbítom az igényt az illetékeseknek, hogy legyen egy olyan adózó, ami maximális adattartalommal fel van töltve.
Nyilván ezt mindenki alacsony prioritással fogja kezelni, de igyekszünk.

Addig maradhat nyitva az issue.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ez sem mai téma, de sikerült telephely adatokat betölteni a teszt környezetbe is.
Példa adószám: 10000537 vagy 10003035

Zárom az issuet,ha van még kérdés nyissátok újra kérlek.
Üdv

**Comment by sinick2** [comment]
Arról van már infó, hogy a telephely adatok várhatóan mikor kerülnek be az éles rendszerbe is?
Ez lesz publikálva a hírekben vagy technikai változásokban?

Köszi!

**Comment by NTCA-supporter** [comment]
Szia @sinick2 !
Hamarosan elérhetőek lesznek, pontosat nem tudok, lesz róla publikáció.
Üdv
