### ISSUE TITLE
MAINTENACE_MODE haználatban van?

### ISSUE THREAD

**Issue by rgform** [nav-gov-hu/Online-Invoice#392]
A dokumentáció szerint van ilyen hibaüzenet:
"HTTP 527 SERVICE_UNAVAILABLE
GeneralErrorResponse XML tag
ERROR MAINTENANCE_MODE"

Amihez egy megjegyzés:
a ... hibakódot a rendszer publikus végpontja mögött lévő hálózati eszköz HTTP 503 SERVICE_UNAVAILABLE üzenetre átforgatja

A tegnapi tervezett karbantartás ideje alatt azonban a műveletekre 504 időtúllépés vagy durvább "Bezárták az alapul szolgáló kapcsolatot: Váratlan hiba történt fogadáskor" - azaz semmi sem érkezett.

Ez a hibaüzenet nincs bekapcsolva tervezett karbantartáskor?

Üdvözlettel, PPSOFT

**Comment by NTCA-developer** [comment]
Szia @rgform 

Ennek a beállításnak akkor van értelme amikor olyan verzióváltás zajlik, amiben nincs DB rész. Ez jelenleg elenyésző százaléka az összes release-nek, és jelenleg sajnos a kiugró tranzakciószám miatt az alkalmazás tervezett leállítása egyszerűbb. (ez miatt is vannak mindig a karbantartási ablakok előre publikálva) Ezért a válaszom az hogy jelenleg ez a hibakód nincs nagyon használva.

Viszont jelenleg is dolgozunk egy olyan blue-green install metodológián, ami lekezeli ezt, így a jövőben talán nagyobb létjogosultsága lesz ennek a működésnek. Ez válasz a kérdésedre?

**Comment by rgform** [comment]
Szia NTCA-developer!

Nézd el nekem az ilyen kérdéseket, mert nem ismer(het)em a rendszeretek felépítését, Abból indultam ki, hogy ilyen méretű aszinkron rendszereknél a balancer ad maintenance üzenetet, ha leáll mögötte a feldolgozó rendszer.   Eszembe nem jutott, hogy ez a feldolgozó rendszert üzenete!  Egyébként "user satisfaction" indikálta a kérdést.   Sok user berzenkedik attól, hogy hibaüzeneteket -  főleg hívja az IT-t mert IT jellegű hiba van - kapjon, még akkor is ha a rendszerünk azt később automatikusan lekezeli.  A batch, illetve workflow jellegű számlázás lehetővé tenné  megfelelő maintenance üzenet esetén a köteg halasztását - az engedélyezett időablakon belül - a leállás utánra.

Egyénként így zárható, köszönöm. PPSOFT

**Comment by NTCA-developer** [comment]
Nem volt rossz kérdés PPSOFT, nem kell szabadkozni.

Valójában a sejtésed helyes, az 503-at ténylegesen a load balancer mondja akkor, amikor a probe elhasal a mögötte lévő szerverek leállása miatt. A MAINTENANCE_MODE amit az interfész dokumentáció ír ezzel szemben arra van, hogy egy rolling update során az alkalmazást le lehessen cserélni úgy, hogy közben pl a frontend betöltsön és működjenek a nem API jellegű segédfunkciók, tehát ne essünk ki a kiszolgálásból. Ezt a hibakódot viszont muszáj magának az alkalmazásnak mondani, mert ha az LB elvágja a forgalmat akkor a maradék funkciót is elveszítjük.
