### ISSUE TITLE
[Q&A] queryTransactionStatus válaszban ABORTED státusz hibakód nélkül

### ISSUE THREAD

**Issue by szako** [nav-gov-hu/Online-Invoice#393]
Sziasztok,

létezhet olyan, hogy queryTransactionStatus lekérdezésnél ABORTED invoiceStatus mellé nem érkezik hibakód? Az élesben történt meg velünk 2020.09.23-án és elméletileg INVOICE_NUMBER_NOT_UNIQUE kódot kellett volna visszaadnia a NAV rendszerének, mert már bent volt a számla, ezért hasalt el. A hiányzó hibakód problémás, mert reagálni szeretnénk rá és ha nem érkezik semmi, akkor nem tudunk. Három számla lett beküldve egyszerre, a harmadik egy módosító, aminél már szépen visszaadta a NAV az értékekeket:

```xml
<processingResult>
  <index>1</index>
  <invoiceStatus>ABORTED</invoiceStatus>
  <compressedContentIndicator>true</compressedContentIndicator>
</processingResult>
<processingResult>
  <index>2</index>
  <invoiceStatus>ABORTED</invoiceStatus>
  <compressedContentIndicator>true</compressedContentIndicator>
</processingResult>
<processingResult>
  <index>3</index>
  <invoiceStatus>ABORTED</invoiceStatus>
  <businessValidationMessages>
    <validationResultCode>ERROR</validationResultCode>
    <validationErrorCode>MODIFICATION_INDEX_NOT_UNIQUE</validationErrorCode>
    <message>A módosító okirat sorszáma nem egyedi a számlaláncon belül.</message>
    <pointer>
      <tag>InvoiceData/invoiceMain/invoice/invoiceReference/modificationIndex</tag>
      <value>1</value>
      <originalInvoiceNumber>XX</originalInvoiceNumber>
    </pointer>
  </businessValidationMessages>
  <businessValidationMessages>
    <validationResultCode>ERROR</validationResultCode>
    <validationErrorCode>INVOICE_NUMBER_NOT_UNIQUE</validationErrorCode>
    <message>A megadott számla sorszámmal már történt adatszolgáltatás.</message>
    <pointer>
      <tag>InvoiceData/invoiceNumber</tag>
    </pointer>
  </businessValidationMessages>
  <businessValidationMessages>
    <validationResultCode>ERROR</validationResultCode>
    <validationErrorCode>INVOICE_LINE_ALREADY_EXISTS</validationErrorCode>
    <message>A megadott sorszámmal már létezik tétel a számlaláncban.</message>
    <pointer>
      <tag>InvoiceData/invoiceMain/invoice/invoiceLines/line/lineModificationReference/lineNumberReference</tag>
      <value>3</value>
      <line>1</line>
      <originalInvoiceNumber>XX</originalInvoiceNumber>
    </pointer>
  </businessValidationMessages>
  <businessValidationMessages>
    <validationResultCode>ERROR</validationResultCode>
    <validationErrorCode>INVOICE_LINE_ALREADY_EXISTS</validationErrorCode>
    <message>A megadott sorszámmal már létezik tétel a számlaláncban.</message>
    <pointer>
      <tag>InvoiceData/invoiceMain/invoice/invoiceLines/line/lineModificationReference/lineNumberReference</tag>
      <value>4</value>
      <line>2</line>
      <originalInvoiceNumber>XX</originalInvoiceNumber>
    </pointer>
  </businessValidationMessages>
  <compressedContentIndicator>true</compressedContentIndicator>
</processingResult>
```

Megvan mindenféle azonosító, mi a következő lépés? Mivel éles rendszerről van szó, így a DEV support tikett nem játszott.

**Comment by NTCA-supporter** [comment]
Szia @szako !
Ilyennek nem szabadnak előfordulnia.
Teszt rendszeren ezt tudod repordukálni?

Ha most lekérdezed, akkor is ezt a választ kapod rá?
Üdv

**Comment by EPluribusUnum** [comment]
Egyetlen egyszer volt nekem is ilyen eset, be is építetten null vizsgálatot. Azt már nem tudom megmondani hogy éles vagy teszt rendszer esetén volt.

**Comment by szako** [comment]
> Szia @szako !
> Ilyennek nem szabadnak előfordulnia.
> Teszt rendszeren ezt tudod repordukálni?
> 
> Ha most lekérdezed, akkor is ezt a választ kapod rá?
> Üdv

Nem tudom teszt rendszeren reprodukálni. Mivel éles rendszerről van szó és a szálakat elvarrtuk már, így elég nehéz újra lekérdezni. De azért megpróbálom és visszajelzek. Hátha más is idetalál @EPluribusUnum-on kívül és van valami használhatóbb infója.

**Comment by szako** [comment]
@NTCA-supporter Ismételt queryTransactionStatus lekérdezésre is ugyanaz a válasz, amit korábban mutattam. Az első két tranzakció index-re nem érkezik hibakód.

**Comment by szako** [comment]
@NTCA-supporter Próbálkozzak HD bejelentéssel, jól gondolom?

**Comment by NTCA-supporter** [comment]
Szia @szako !
Küldj kérlek egy transactionId-t és amennyiben lehetséges, kérdezd le megint a mai napon, hogy pontosan lássák a HD-sok.
Megkérem, hogy nézzenek rá, mert ilyen hibának nem szabadna előfordulnia.

Üdv

**Comment by szako** [comment]
341H8P0VBN6DE4TD és lekértem újra.

**Comment by NTCA-supporter** [comment]
Szia @szako !
Amit megtudtam: INVOICE_NUMBER_NOT_UNIQUE a hibaüzenet mindkét számlánál. Azt, hogy a lekérdezésben miért nem szerepelnek egyelőre nem tudom, nekem az üzemszünet tűnik logikus magyarázatnak, mivel megnézték, és több ilyen hibaüzenet is lett visszaadva a lekérdezésben. Ezért lehetségesnek tartom, hogy ez egyedi eset. Kérlek jelezz, ha új beküldés során is tapasztalsz ilyet.
Az issuet most zárom mivel jelenlegi tudomásunk alapján csak ez az egy tranzakció érintett. Ha lesz bármi változás vagy újra tapasztalod, kérlek nyisd újra vagy adj fel új ticketet.
Köszönöm a türelmed.
Üdv

**Comment by szako** [comment]
Kedves @NTCA-supporter, @NTCA-developer  !

![image](https://user-images.githubusercontent.com/2895406/95751830-6e9c4300-0c9f-11eb-837d-b2bf861d5f72.png)

Sikerült belépnem az éles NAV Online rendszerbe az ügyfél fiókjával és a tranzakció lekérdezésénél sem látszódnak a INVOICE_NUMBER_NOT_UNIQUE hibakódok. Tehát elég könnyen reprodukálható. Miért nem látszódik a lekérdezésben, ha azt mondta HD, hogy elvileg látják a hibakódokat? Most, hogy jól szuperál a NAV rendszere, nem kellene jól visszaadnia a tárolt értékeket? Hogyan kezeljem, ha ilyen felmerül?

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ez az issue kicsit el lett hanyagolva. Van még kérdés/probléma?
Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet.
Ha van még kérdés nyissátok újra kérlek.
Üdv
