### ISSUE TITLE
Tranzakció tételeinek feldolgozási sorrendje

### ISSUE THREAD

**Issue by topybear** [nav-gov-hu/Online-Invoice#394]
Egy furcsaságot találtunk a teszten. Egy csomagban került felküldésre egy számla és annak a módosítása. Index szerint jó sorrendben van, első az eredeti, második a módosító. Ehhez képest a módosítóra kapunk egy blokolót, hogy "A módosítás vagy érvénytelenítés olyan okiratra hivatkozik, amire vonatkozóan nem történt adatszolgáltatás." 
OK, nem üzemszerű, hogy egy csomagban legyen a számla és a módosítása, de pl. a múltkori leállásnál, vagy mondjuk egy internet kapcsolati hiba miatt simán előfordulhat.
A tranzakció screenshotja:
![navblokkolo](https://user-images.githubusercontent.com/3189331/94827131-5f4c0880-0408-11eb-8d77-bfa8d870cb7c.jpg)
Úgy tűnik nem a megfelelő sorrendben történik a tranzakció tételeinek a feldolgozása. Ránéznétek,? Köszi!

**Comment by topybear** [comment]
Mielőtt beküldtem, próbáltam rákeresni, hogy volt-e már ilyen, de nem találtam. Még azt tudom elképzelni, hogy csak a már befogadottak közt keresik a hivatkozott számlát, az aktuálisan feldolgozott csomagban nem.

**Comment by EPluribusUnum** [comment]
@topybear , meg kell várni a DONE/WARN jelzést a hivatkozott számlára, csak utána lehet beküldeni. Így nem kerülhet egy csomagba a kettő.

**Comment by jozanesz** [comment]
Ezt most nem találtam meg a specifikációban. Ha benne van valahol, akkor is ki kellene emelni az 1.8.2 és 2.5-ös fejezeteken belül.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Előttem összefoglalták a lényeget.
Az API doksiba bele fogjuk írni, ez valóban hasznos információ-

Köszi

**Comment by topybear** [comment]
Ezzel kapcsolatban egyetlen (apró?) ellentmondást érzek: az azonnali jelentési kötelezettséget. Mert amíg a módosított számlára nem kapok DONE/WARNING választ bármilyen technikai probléma miatt, akkor addig megpróbálni sem érdemes a módosító küldését - ez esetben viszont sérül az azonnali beküldés. Igen, nem ez az üzemszerű működés, de előfordulhat, így érdemes lenne majd a doksiban ezt is feloldani valahogy.

**Comment by lvitya586** [comment]
Azért az hihetetlen, hogy több mint 2 éve megy már élesben az OSZ, de valaki még mindig az azonnaliságon akad fenn.

[Kérdések és válaszok, 31. kérdés](https://onlineszamla.nav.gov.hu/kerdesek_es_valaszok)

> Mit jelent az, hogy a számlázó programból teljesítendő adatszolgáltatást a számla kiállításakor azonnal teljesíteni kell?
> 
> Természetesen az azonnaliság az észszerűség határain belül értelmezendő. Így például, ha egy adózó úgy alakította ki a saját ügyviteli rendszerét, hogy abban több száz számla adatának jóváhagyása és lezárása egyszerre valósul meg, és az adatok továbbítása a számlák lezárásakor megkezdődik, akkor az azonnali továbbítás megvalósul akkor is, ha a továbbítás több órát vesz igénybe.

@NTCA-tax , nem lehetne jelezni a jogszabályalkotók felé, hogy pontosítsanak a jogszabály azonnaliságra vonatkozó passzusán? Mint látható, még mindig félreértésekre adhat okot.

**Comment by jozanesz** [comment]
> > Természetesen az azonnaliság az észszerűség határain belül értelmezendő.

Az észszerűség szubjektív, és a felhozott példa sem teszi egyértelmű a megítélését. Nekem akár az is észszerű, ha óránként vagy naponta egyszer van pollozás. Czöndör nyilatkozata alapján viszont egyáltalán nem szabad számlát - úgymond - „gyűjtögetni” beküldés előtt.

**Comment by topybear** [comment]
Pontosan, a személyes konzultáción külön kihangsúlyozták ezt, emiatt rugózik "valaki" :) még két év után is ezen. 
Ha beküldjük a módosítót vakon és mégsem ment be, kezdődik a telefonálgatás, egyedi ellenőrizgetés, kézzel egyedileg indított újraküldések - viszont bizonyítottan elküldtük a számla kiállítííst követően azonnal. Csak belefullad a support és az ügyfelek is nyűglődnek. (Az is igaz, hogy ha ez pont beleszaladna a tömeges számlázásba, hát hogy nem szálaznám át egy-egy ügyfélnél azt a pár ezer módosítót, az is biztos, újraküldeném az egészet, aztán majd ami azután is fennakad, azzal foglalkozzunk).
Ha bevárjuk a visszaigazolás letölthetőségét, akkor  - a legutőbbi leállás alapján több órán keresztül -várakozunk; amire kerek perec megmondták, hogy ilyet nem lehet.

**Comment by lvitya586** [comment]
> Az észszerűség szubjektív, és a felhozott példa sem teszi egyértelművé a megítélését. Nekem akár az is észszerű, ha óránként vagy naponta egyszer van pollozás. Czöndör nyilatkozata alapján viszont egyáltalán nem szabad számlát - úgymond - „gyűjtögetni” beküldés előtt.

Az azonnaliság is szubjektív, pont ezért nem lehet betartani/betartatni. Ami objektív a rendeletben, az a 24/48 órás eljárások.
Czöndör Úr meg szerintem butaságot mondott, mert mivel nincs deklarálva, hogy mit tekint a jogszabály azonnaliságnak, ezért simán megtehető az, hogy összevárok 2-100 db számlát és egyszerre küldöm el (az objektív határidőn belül), hiszen a jogszabály nem tiltja és a rendszer erre kifejezetten lehetőséget ad. Amúgy meg konzultáljon a kollégákkal, hogy mit is tesznek ki a honlapjukra válaszként és miket nyilatkoznak. Sajnálatos, hogy a mai napig eltérően nyilvánulnak meg és ezért folyamatosan zavart okoznak a fejekben.

> Ha bevárjuk a visszaigazolás letölthetőségét, akkor - a legutőbbi leállás alapján több órán keresztül -várakozunk; amire kerek perec megmondták, hogy ilyet nem lehet.

Már hogyne lehetne? Erre van meghatározva objektíven a jogszabályban 24 óra, hiszen a NAV hibájából nem lehetett beküldeni a módosítót.

> (3) Ha a számla, számlával egy tekintet alá eső okirat kiállításának időpontjában a számla, számlával egy tekintet alá eső okirat adatait fogadó elektronikus rendszer üzemzavar, karbantartás vagy az internetszolgáltatás elégtelensége miatt nem érhető el, a számlázó programnak a kiállított számla, számlával egy tekintet alá eső okirat legalább Áfa tv. szerinti kötelező adattartalmát az üzemzavar, karbantartás vagy az internetszolgáltatás elégtelensége megszűnését követő 24 órán belül kell az állami adó- és vámhatóság részére elektronikus úton továbbítania.

**Comment by topybear** [comment]
Nem akarok itt jogászkodni, de betű szerint ez van: "...adatait fogadó elektronikus rendszer üzemzavar, karbantartás vagy az internetszolgáltatás elégtelensége miatt nem érhető el" - na most pont elérhető volt a rendszer. 
Tébyleg nem szőrszálhasogatás, már a saját jogászunk is árgus szemekkel figyeli, hogy mit hogyan csinálunk, mióta egyetemleges a felelősségünk a számlázó program üzemeltetőjével - és akkor még ott vannak az ügyfelek jogászai. Esetleg egy megfelelőségi audit...

**Comment by lvitya586** [comment]
Mintha az írtad volna, hogy legutóbb több órás leállás volt, most meg azt, hogy pont elérhető volt. Akkor most melyik? 
Amúgy jelen pillanatban megint nem érhető el. :)
Mindenesetre ezért javasoltam, hogy pontosítani kéne a jogszabályt.

**Comment by topybear** [comment]
Úgy állt le, hogy fel tudtál csatlakozni, meg küldeni is tudtál, de aztán leszakadtál.  A végeredmény kiszámíthatatlan volt, de ezen számláknak egy részét befogadta (saccra még a döglődés elején), egy részét már nem.
