### ISSUE TITLE
Az OSZ oldalon az újabb XSD helyett  az előző (régi) XSD van ?

### ISSUE THREAD

**Issue by KMGY100** [nav-gov-hu/Online-Invoice#396]
Ez a friss 3.0-ás Ez a github-on található itt:
nav-gov-hu/Online-Invoice.  
# Project: Magyar Online Számla Rendszer invoiceData XML séma
# Author: NAV Informatikai Intézet
# Version: v3.0 2020/09/16

Itt valamit összekeveredett
mert amit közöltetek utoljára az OSZ oldalon az a régebbi
Ez az előző a régi 3.0 -ás
# Project: Magyar Online Számla Rendszer invoiceData XML séma
# Author: NAV Informatikai Intézet
# Version: v3.0 2020/07/31

Jól látom ?
Bocsánat a nagy betűkért, nem direkt volt.

**Comment by NTCA-supporter** [comment]
Szia @KMGY100 !

Köszi a jelzést, lecseréltem.
Kérlek jelezz majd vissza ha rendben találod.

Üdv

**Comment by KMGY100** [comment]
Igen. Rendben.

**Comment by KMGY100** [comment]
Ez a legfrissebb common ?
# Project: NAV NTCA Common XML séma
# Author: NAV Informatikai Intézet
# Version: v1.0 **_2020/07/31_**
Ez van az OSZ oldalon.
