### ISSUE TITLE
Nincs common XSD itt a GitHub-on

### ISSUE THREAD

**Issue by KMGY100** [nav-gov-hu/Online-Invoice#397]
Nincs common XSD itt a GitHub-on
Jól látpm ?

**Comment by lvitya586** [comment]
Elvileg külön projekt van hozzá.

[common.xsd](https://github.com/nav-gov-hu/Common/blob/master/src/schemas/nav/gov/hu/NTCA/common.xsd)

**Comment by NTCA-developer** [comment]
Pontosabban, itt a repó: https://github.com/nav-gov-hu/Common

Amúgy a changelogban is benne van, de sok az infó egyszerre, nem baj ha elsikkadt a többi között.
