### ISSUE TITLE
[Q&A]taxPayerData válasz mezőinek kapitalizációja

### ISSUE THREAD

**Issue by martonmiklos** [nav-gov-hu/Online-Invoice#398]
Kedves @NTCA-supporter 

Ha jól látom a 2.0-s API-n keresztül a  queryTaxPayerData-ra érkező érkező válaszban jelenleg minden nagybetűs (név címek, stb.). 

Mielőtt vadul elkezdenék "dekapitalizáló" feature-t fejleszteni gondoltam megkérdezem, hogy van-e tervben/láttok-e elvi lehetőséget arra, hogy a jövőben ez változzon úgy, hogy a nevek/címek helyes kis/nagybetűkkel érkezzenek.

Köszönöm előre is a választ, szép hétvégét!

**Comment by NTCA-supporter** [comment]
Szia @martonmiklos !

Az adózói  törzsadatokat mi is így kapjuk, azokon az Online Számla rendszer semmilyen konverziót nem végez, így arra kell készülni, hogy ezt így adjuk vissza.

Zárom az issuet, ha van még kérdés nyisd újra nyugodtan.

Üdv
