### ISSUE TITLE
[Q&A]API V3.0-ás teszteléssel kapcsolatos kérdések, észrevételek

### ISSUE THREAD

**Issue by EnokhSys** [nav-gov-hu/Online-Invoice#399]
Sziasztok!

Bocsánat, teljesen új vagyok ezen a fórumon, első dolgom volt utánanézni, hogy van-e már ilyen téma, de nem találtam. 

Szóval, az lenne az lenne az első kérdésem, hogy a v3.0-át lehet-e már tesztelgetni, vagy ez későbbre várható? Egyelőre csak egy tokenkérést eresztettem meg a tesztszervernek az új szabvány szerint, de "HTTP/1.0 404 Not Found"-ot kaptam vissza. 

A másik kérdésem, hogy az "adatszolgáltatás, mint elektronikus számla" (completenessIndicator=True) tesztelését is csak 2021.01.01 után lehet elkezdeni, vagy arra már hamarabb is sor kerülhet? 

Köszi & üdv.

**Comment by szabogab** [comment]
Hi!
token tesztelésnél (v3) , nekem is csak ezt jött vissza.
RAW:
HTTP/1.0 404 Not Found
Cache-Control: no-cache
Connection: close
Content-Type: text/plain
Strict-Transport-Security: max-age=31536000; includeSubDomains

Érdekes, hogy a válasz nem xml, hanem "text/plain"

**Comment by vivacomp** [comment]
**Changelog 3.0**
Úgy becsüljük, hogy a 3.0-ás XML API-t tartalmazó fejlesztés szeptember végére lesz elérhető a teszt környezeten, a hozzá kapcsolódó magyar nyelvű interfész dokumentációval együtt.
Okulva a 2.0-ás átállás tapasztalataiból felkészítettük a belső feldolgozó rendszereinket arra, hogy egyszerre kaphatnak éles adatot a 2.0-ás és a 3.0-ás számla adatokkal is. Így a 3.0-ás XML API már nem csak teszt rendszeren, hanem rögtön az éles környezetben is fogadhat adatot. Ettől azt reméljük, hogy akit verziókezelési okokból blokkol ha a NAV API nem működik az éles környezetben, azok tudni fognak haladni az átállással. A hardveres környezet elkészül a 3.0 élesítésére, ezért azonos performanciával fogjuk tudni kiszolgálni mindkét verziójú API kéréseit.

Engem is nagyon érdekel, hogy mikor indul a 3.0? Ha valakinek sikerült a 3.0 API használata, kérem közölje.
Üdv.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Még nem elérhető a 3.0 tesztkörnyezeten, ezért ne is próbálkozzatok.
Természetesen minden fórumon jelezni fogjuk, ha elérhetővé válik.

Üdv

**Comment by EnokhSys** [comment]
Kedves NTCA-supporter,
rendben, köszönjük, végül is nem kerget a tatár. :-)
Üdv.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Elnézést a késői reakcióért, de sok más dolog is van..
Elérhető a v3-as interfész teszt rendszeren.

Üdv
