### ISSUE TITLE
[FEATURE] RequestSignature

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#4]
Szerintem az ügyfél oldalon egyszerüsítené a munkát, ha nem kellene operation + base64 stringet képezni az SHA3 előtt. Az operation mehetne a request signature-be magába a base64 SHA3-a elé.
Persze a tervezetben leírtak szerint is meg lehet csinálni.

**Comment by NTCA-developer** [comment]
Szia!

Köszönjük a javaslatot, van benne ráció.

A jelenlegi konkatenációs logikát azért választottuk, mert kriptoanalitikai szempontból mindig jobb egy hash hashét venni, mint egy literál értéket és egy hash-t. Mivel az SHA2 és SHA3 hash függvénye is hasonló logikán nyugszik mint egy block cipher (tördel, XOR-oz, permutál, forgat, visszatölt) az előkép szempontjából jobb, ha az egyik magába foglalja a másikat, mintha csak egymás mellett állnának. (Ezt szokták még avalance effect-nek is nevezni.)

Szinte hallom a kérdést, hogy akkor az aláírókulcs miért literál értéken van a requestSignature-ben a számítás előtt. Úgy gondolkodtunk, hogy nem baj, ha a requestSignature-nek van egy teljesen literál része (requestId+timestamp+signKey), de a konkatenáció másik része már legyen hash alapú, ezért született a most tervezett működés. Természetesen azt is meg lehetne tenni, hogy két egyenértékű parciális hash-ből legyen a requestSignature összetéve, amiben az egyik parciális hash a literál értékek összefűzött hashe, míg a másik az invoice tartalomé, a tervezet szerinti módon. De ez már felesleges túlbonyolítás volna.

Kérem a visszajelzésed, hogy lezárható-e az issue vagy folytassuk még?
