### ISSUE TITLE
[FEATURE] Adózó rövid nevének lekérdezése

### ISSUE THREAD

**Issue by Rossi73** [nav-gov-hu/Online-Invoice#40]
**Az igény összefoglalása / Summary of the request**
Az adózó rövid nevének lekérdezése a queryTaxpayer operáció meghívásával.

**Az általam javasolt megoldás / The solution I propose**
A TaxpayerDataType típus bővítése a taxpayerShortName elemmel, melynek típusa data:SimpleText512NotBlankType lenne, és az adózó rövid nevét tartalmazná.

**Egyéb tartalom / Additional content**
A partnerek részéről felmerült jogos igény, hogy az adószám lekérdezésekor az adózó teljes neve mellett a rövid nevét is le tudjuk kérdezni. A számlákon sok esetben az adózó rövid nevét tüntetik fel. A teljes név lekérdezése segíti ugyan a kitöltést, de ebbe az esetek nagy többségében "bele kell nyúlni". A számlázó programok segíthetik a felhasználót azzal, hogy a cégformákat automatikusan rövidítik (pl.: korlátolt felelősségű társaság --> kft.), de a név sok esetben még így is hosszú. Ha a TaxpayerDataType típus tartalmazná az adózó rövid nevét is, akkor a queryTaxpayer operáció meghívását követően a felhasználó ki tudná választani, hogy a rövid vagy hosszú nevet szeretné a számlán megjeleníteni.

**Comment by NTCA-developer** [comment]
Szia @Rossi73 !

Nyitott kapukat döngetsz. :) Pvmon kolléga már felvette a rövid név problémáját itt: https://github.com/nav-gov-hu/Online-Invoice/issues/13

Ugyan azt tudom mondani, amit ott: nem rajtunk múlik, a 2.0-ás sémában előkészítjük a helyét, és amikor megkapjuk, onnantól tudjuk szolgáltatni is kifelé.

Majd kérlek zárd le, ha nem kell már a ticket.

**Comment by Rossi73** [comment]
Upsz, valóban, csak elkerülte a figyelmem.

**Comment by NTCA-developer** [comment]
Np, inkább kétszer mint egyszer se. :)
