### ISSUE TITLE
[FEATURE] Online Számlázó REST API publikussá tétele

### ISSUE THREAD

**Issue by BalintBanyasz** [nav-gov-hu/Online-Invoice#400]
**Az igény összefoglalása / Summary of the request**
Kedves Fejlesztők, NAV!

Remélem, hogy a megfelelő helyre írok, tekintve hogy az Online Számlázónak nincs külön GitHub repo-ja. Ha mégsem, kérem továbbítsák a kérésemet az illetékeseknek.

Ha minden igaz, az Online Számlázó webes és mobil alkalmazás is ugyanazt a REST API-t (oszInvoiceService) használják a háttérben, azonban ez az API egyelőre nem publikus, nincs nyilvánosan elérhető dokumentációja.

Véleményem szerint, amennyiben ez nem igényel túlzott ráfordítást fejlesztői oldalról, érdemes lenne az API-t nyilvánossá tenni, ugyanis ez lehetővé tenne egy sor újabb felhasználási módot. A legnagyobb hozzáadott értéke talán abban lenne, hogy (jellemzően kisebb) cégek így be tudnák építeni számlázó modulként a jelenlegi folyamataikba. Például egy webshop rendelésnél az Online Számlázón keresztül tudna kiállítani egy elektronikus számlát a megrendelő felé PDF formátumban (ami így nem mellesleg automatikusan jelentve lenne az Online Számla rendszerben is).

Tekintve hogy több, kereskedelmi forgalomban kapható online számlázó is rendelkezik hasonló (azonban jellemzően fizetős) szolgáltatással, ezzel a funkcióval a NAV Online Számlázó (feltehetően csekély ráfordítással) egy NAV által hivatalosan támogatott, ingyenes alternatívává válna minden olyan vállalat számára, aki automatizálni szeretné folyamatait.

**Az általam javasolt megoldás / The solution I propose**
- API dokumentáció elérhetővé tétele (akár egy OpenAPI Specification vagy WADL is elegendő lehet)
- API authentikáció lehetővé tétele automatizált megoldások esetén - pl. az Online Számlához hasonlóan technikai felhasználó hozzáadásával

**Comment by szako** [comment]
Ld itt #227

**Comment by szako** [comment]
Kapcsolódó: #227

**Comment by BalintBanyasz** [comment]
@szako Köszönöm a linket.

A mostani kérés annyiban különbözik, hogy nem egy új interface-re irányul, mindössze a meglévő megnyitását szeretném kérni fejlesztők felé. Véleményem szerint a jelenlegi architektúra lehetővé tenné, hogy a meglévő kliens alkamazásokhoz (SPA, illetve mobil app) hasonlóan külső alkalmazások is használhassák a backend API-t és így a vállalatok a meglévő folyamataikba/alkalmazásaikba tudják integrálni az Online Számlázót. Ahogy fentebb is írtam, számos haszna lenne, továbbá elkerülhetőek lennének a manuális adatbevitelből adódó hibák is. A linkelt kérés és a fenti bejegyzésemre érkezett reakciók alapján azt mondanám, hogy igény biztosan lenne rá.

Bízom benne, hogy a felvetés NAV oldalról is támogatásra talál.

**Comment by csaszko** [comment]
Csatlakozom az igényhez!

**Comment by NTCA-supporter** [comment]
Ezt zárom, legyen a #438 a fő issue ezzel kapcsolatban.
