### ISSUE TITLE
API 3.0 question

### ISSUE THREAD

**Issue by Antonikas58** [nav-gov-hu/Online-Invoice#402]
Hi development team,

Can you give me a hint about 3.0 version?
When the test webservice will start to work on following endpoints:
https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3/manageInvoice 
https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3/tokenExchange
And also if the credentials from 2.0 version will also work for 3.0, or the customer should apply for a new one?

Best regards
Anton

**Comment by NTCA-supporter** [comment]
Hi Anton!

Version 3.0 will be launched soon, but is not yet available. The release will be published on all platforms.
Existing credentials also work for 3.0.

Br
