### ISSUE TITLE
API v3.0 - thirdStateTaxId töltése

### ISSUE THREAD

**Issue by hamvasgy** [nav-gov-hu/Online-Invoice#403]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**

Az API v3.0 specifikációban nem egyértelmű a thirdStateTaxId tag töltése.

A 2.1.4.1 Vevői adószám fejezetben (81.oldal) ez van: "Harmadik országbeli fél harmadik országbeli adószáma a thirdStateTaxId elemben (típusa: ...) **szerepeltethető, ha szerepel a számlán**." -értelmezésünk szerint, ha a vevő harmadik országbeli, de az adószáma nem szerepel a számlán, akkor a mező töltése nem kötelező. Ezzel szemben a "A vevő adószámának szerepeltetése lehetséges esetei táblázatban" (83.oldal) ez szerepel:
4. | Vevő nem Magyarországon   nyilvántartásba   vett áfaalany (pl. más   EU-beli vagy harmadik országbeli adóalany) | privatePersonIndicator =   false    customerInfo/customerVatData/communityVatNumber   **vagy** customerInfo/customerVatData/thirdStateTaxId **töltése kötelező**. |

Kérdések: ha vevő harmadik országbeli akkor az adószámának (thirdStateTaxId) töltése kötelező vagy nem?
Nagyon sok esetbe ez nem ismert vagy ellenőrizhetetlen. Ilyen ellenőrizhetetlen adattal töltsük a mezőt? Ez lehet akár valami "dummy" adószám is? Vagy adhatjuk üresen?

**Comment by NTCA-tax** [comment]
A harmadik országbeli vevő adószáma nem kötelező eleme a számlának az áfa törvény szerint, de ettől még rajta lehet. Az adatszolgáltatás csak olyan adatokat tartalmazhat, amely a számlán szerepel. Amennyiben a számlán egy nem ellenőrzött harmadik országbeli vevő adószáma szerepel, akkor azt kell az adatszolgáltatásban szerepeltetni. Amennyiben nincs a számlán harmadik országbeli vevő adószáma, akkor értelem szerűen nem is fog szerepelni az adatszolgáltatásban.

Egyébként szoftver működése szempontjából a belföldi és közösségi adószám szerepeltetése sokkal fontosabb lehet, mivel ahhoz az adózó részére jogkövetkezmény is társul, ha nem szerepel a számlán, vagy például a közösségi adószámot nem validálta a kiállítást megelőzően.

**Comment by hamvasgy** [comment]
Köszönöm a választ, akkor már csak az a kérdésem, hogy harmadik országbeli vevő esetén, ha nincs adószáma, akkor mit írjunk a customerInfo/customerVatData/thirdStateTaxId tag-be.
A invoiceData.xsd szerint: 
<xs:choice>
    <xs:element name="customerTaxNumber" type="CustomerTaxNumberType">
             ::: (belföldi adószám)
    <xs:element name="communityVatNumber" type="common:CommunityVatNumberType">
             ::: (EU adószám)
   <xs:element name="thirdStateTaxId" type="common:SimpleText50NotBlankType">
             ::: (harmadik országbeli adószám)
 </xs:choice>
vagyis a ez esetben a thirdStateTaxId egy kötelező, nem, üres max. 50 hosszú szöveg

**Comment by HWKF** [comment]
Kicsit bővebben, de ez is szerepel ebben: [384](https://github.com/nav-gov-hu/Online-Invoice/issues/384)

**Comment by hamvasgy** [comment]
384-ben megtaláltam:
•harmadik országbeli adóalany, nincs adószám -> nincs CustomerVatDataType

**Comment by hamvasgy** [comment]
köszönöm
