### ISSUE TITLE
[DOC] WARN 1072 s/vetCon/vatCon/

### ISSUE THREAD

**Issue by bcdel** [nav-gov-hu/Online-Invoice#404]
**A hibás dokumentum neve / Document name containing the error**
API dokumentáció: Online Számla 3.0 rendszer interfész specifikáció (utoljára frissítve: 2020.10.01.)

**Oldalszám / Page number**
276. oldal (PDF 286 page)

**A dokumentációs hiba leírása / Description of the documentation error**
Azonosito: 1072.
Mukodes: Toleralt elteres: vetContent...

vat lesz az

**Comment by NTCA-supporter** [comment]
Köszi a jelzést. A következő verzióban javítjuk, addig maradjon nyitva az issue.
Üdv

**Comment by NTCA-supporter** [comment]
Javítottuk. Köszi a jelzést mégegyszer.
