### ISSUE TITLE
Adószámok és CompletenessIndicator kapcsolata

### ISSUE THREAD

**Issue by rgform** [nav-gov-hu/Online-Invoice#405]
A dokumentáció lapszámozás szerinti 81. oldalán az alábbi szerepel:

"A három adószám közül az adatszolgáltatásban csak egy adható meg. Ha a számlán esetlegesen több vevői adószám szerepel (pl. belföldi adószám, közösségi adószám), akkor az adatszolgáltatásnál azt az adószámot kell kiválasztani, amit Áfa törvény szerint a számlán egyébként fel kell tüntetni."

Vagyis adatszolgáltatási szempontból hallgatólagosan is megengedett "egyéb adószámok" számlán való feltüntetése.  Azonban ez esetben explicite nem használható elektronikus számlának, hiszen nem állíthatom be a Completenessindicatort mert van olyan adat a számlán ami nem kerül be a jelentésbe?!    Lehetséges nem említett alternatíva kiegészítő adatként az adatszolgáltatásban elhelyezni a "nem jelentett" adószámot, vagy tegyünk le régi gyakorlatról, miszerint a belföldi és közösségi adószámot "párban" tüntetjük fel a számlán?

Üdvözlettel, PPSOFT

**Comment by NTCA-tax** [comment]
Leginkább le kellene tenni a hibás gyakorlatról...

Amit leírtál, az két külön eset. Amennyiben valaki nem tesz le a hibás gyakorlatról, akkor a számlázó programra bízza azt, hogy melyik adószám kerül bele az adatszolgáltatásba. Nincs olyan opció a vevői oldalon, hogy egyéb adószámként kerül be az adatszolgáltatásba, mivel nincs ilyen mező (hacsak valaki létre nem hoz additionalData-ban ilyet). A dokumentációban ezt írtuk le, hogy ha a szoftver nem követeli meg az egyetlen vevői adószám feltüntetését, akkor az adatszolgáltatási folyamat fogja kikövetelni. Nem biztos, hogy ez lenne az optimális adatszolgáltatási folyamat, de attól még persze ki lehet találni a számla adattartalmából, melyik a helyes adószám (hacsak nem két közösségi adószám van feltüntetve...)

A CompletnessIndicator azt jelöli, hogy az adatszolgáltatás adattartalma maga a számla adattartalma (vagy maga a számla). Ott értelmezhetetlen, hogy más kerül feltüntetésre a számlán és az adatszolgáltatásban.
