### ISSUE TITLE
[Q&A] Már megint nem megy a NAV szervere... Biztos nem lehetne ezt jobban csinálni?

### ISSUE THREAD

**Issue by vankcuf** [nav-gov-hu/Online-Invoice#406]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

A kérdéseim:
Miért ilyen megbízhatatlan a NAV rendszere mostanában?
Mi ezeknek a leállásoknak az oka, hiszen most nem is volt frissítés?
Milyen névre és számlaszámra küldhetjük a számlát, hogy valaki kompenzálja az ilyenkor fellépő plusz költségeinket? 
Uraim mást se csinálunk már, mint vagy NAV-os elvárásokat fejlesztjük vagy az üzemszünetek alatt próbáljuk csitítani a hozzánk forduló tömegeket. A munkánkat már nem tudjuk elvégezni. Fejleszteni szeretnénk. Innovatív dolgokat, új funkciókat, kényelmi funkciókat, de erre nincsen módunk, mert az egész életünket ez a NAV-os nem működő rendszer dominálja...

**Comment by nbeeps2** [comment]
100%-ban egyetértek, ez már a vicc kategória...

**Comment by zsfoto** [comment]
Ilyenkor áll a fél ország? (Mármint azon fele akiknek jelentési kötelezettsége van ;-) )

**Comment by zsfoto** [comment]
Mi lesz jövőre?

**Comment by NTCA-developer** [comment]
Sziasztok!

A frusztrációt értem, de ez egy fejlesztői felület, nem pedig egy általános NAV gateway vagy a prog.hu. Mi nem üzemeltetünk, és ahogy a kérdező is írja, ez nem alkalmazással összefüggő performancia probléma, vagy release érintettségű dolog. Legyetek nyugodtak, amint elhullott a monitoring probe a kollégák már el is dobtak mindent és azóta rajta vannak a megoldáson.

**Comment by Macskafarka** [comment]
Sajnos a NAV nem működtet más fórumot, ezért oda írunk, ahol elolvassák.

**Comment by NTCA-developer** [comment]
Ezt is értem, de akik olvassák, ők mit csináljanak vele?

**Comment by fzoli15** [comment]
> Ezt is értem, de akik olvassák, ők mit csináljanak vele?

Légy szíves továbbítsátok az illetékesek felé. 
Gyakorlatilag tényleg nincs más fórumunk, ahol eljuttathatjuk a panaszunkat a NAV felé. A NAV telefonos ügyfélszolgálat ilyenkor rend szerint azt a választ adja az ügyfeleinknek, hogy a NAV rendszerével semmi gond nincs. A onlineszamla.nav.gov.hu-n semmilyen tájékoztatás nem jelent meg, pedig órák óta fennáll a hibaállapot (ez sem az első ilyen alkalom). 
Ez a szolgáltatási színvonal egy ennél kisebb volumenű rendszer/projekt esetén is elfogadhatatlan lenne. Nem azzal van a baj, hogy nem 100%-os a rendszer rendelkezésre állása, hanem azzal, hogy az üzemzavarokat soha nem sikerül korrekt módon kezelnie a NAV-nak, pedig már nem kis tapasztalatot szerezhettek ebben az elmúlt 2 évben.

**Comment by NTCA-developer** [comment]
Ok, rendben, ezzel részben egyet is értek.

**Comment by NTCA-developer** [comment]
Egyébként egy kérdés azért volna itt. A mai eseménynél a metrika végpont sem válaszolt, tehát ebből az üzemzavar ténye is kiderülhetett. Miért nem használjátok ezt? Egy képernyőt kell kitenni csak ilyenkor, hogy "Nem megy a NAV, keep calm és ne hívjál fel." Ez miért nem járható út?

**Comment by rgform** [comment]
Akkor egy válasz volna. Mi elkövettük azt a hibát, hogy azt hittük a metrika  - azért hogy riportozhassa a kritikus lassulását is a rendszernek - független attól.  Vagyis ha a rendszer leáll, akkor a metrika nem leáll, hanem reportozza a leállást. Így csak sima "IT hibát" tudtunk dobni a felhasználónak.  

PPSOFT

**Comment by omachtandras** [comment]
Mert, hiába írjuk ki, ha a NAV ügyfélszolgálat azt mondja, hogy megy, a weboldalon pedig semmi utalás rá, hogy valóban gond van.
Az ügyfél a NAVval szemben esélytelennek érzi magát, fél, hogy megbüntetik. Ezért, ha ott azt a választ kapja, hogy minden rendben, akkor egyből a szállító ügyfélszolgálatát bombázza, hogy oldjuk meg a problémát, hiszen akkor csak ő lehet a hibás...

**Comment by NTCA-developer** [comment]
@rgform Pedig erre számolni kell, hogy a mintavételezés is meghibásodhat. Teljes szintű függetlenség nem lehet sosem. (és ráadásul ma sem meghibásodott / leállt a metrika, szépen termelt, csak nem értétek el hálózat miatt)

**Comment by rgform** [comment]
"@rgform Pedig erre számolni kell, hogy a mintavételezés is meghibásodhat. Teljes szintű függetlenség nem lehet sosem. (és ráadásul ma sem meghibásodott / leállt a metrika, szépen termelt, csak nem értétek el hálózat miatt)"

Bocsánat, de ez most tipikus Csubakka védelem a részedről.  Igaz az íróniát sem vetted le a beírásból. Arról volt szó ugyanis, hogy NEM MEGY AZ ONLINESZAMLA BEKÜLDÉS-t akarjuk lekezelni.   Természetesen  ha nem megy a metrika kiírjuk, hogy IT hiba, nem megy a metrika. De most arról van szó, hogy mit lehetne tenni hogy minél nagyobb biztonsággal azt tudjuk a felhasználónak a tudomására hozni, hogy nem a saját hálózata, nem a .... probléma ,hanem az Onlineszámla fogadás a NAV oldalon nem megy.

Üdv, PPSOFT

**Comment by Macskafarka** [comment]
Osztom @omachtandras véleményét, mert egy átlag felhasználó nem tudhatja meg azt, hogy a NAV-nál van-e hiba, és minket
kezd el hibáztatni.
Amikor azt látja, hogy durva kirohanások jelennek meg a NAV fő lapján: https://nav.gov.hu/nav/friss_informaciok/Valotlan_hir_jelent_m20201001.html
Miközben arról ott egyetlen hír sem jelent meg a NAV fő lapján, hogy ha nem is 30-án, de korábban volt nagy gubanc.
Tehát egy dátum elírás miatt van közlemény a NAV fő oldalán, de a valódi probléma el van tusolva.
Szükség lenne bizalomerősítő lépésekre a NAV részéről.

**Comment by EnokhSys** [comment]
Én ezt a problémát úgy oldottam meg, hogy egy háttérben futó folyamat óránként megpróbálja beküldeni a számlákat. Amikor a felhasználók azt látják, hogy valamely számla nem kapott a NAV-tól elfogadott vagy hibás státuszt, akkor nyitva hagyják a rendszert egy-két órára, vagy akár egész éjszakára, és csak másnap szólnak, ha továbbra sem jött válasz a NAV-tól.

**Comment by nbeeps2** [comment]
@NTCA-developer : "Egy képernyőt kell kitenni csak ilyenkor, hogy "Nem megy a NAV, keep calm és ne hívjál fel." Ez miért nem járható út?" Óóó ezen már régen túl vagyunk. A program bármilyen (akár tűzfalból adódó) kommunikációs hiba után kiírja, hogy ellenőrizze, hogy a NAV oldala elérhető vagy a NAV oldalán nincs-e kihirdetve üzemszünet! E-mailben és a honlapon is tájékoztatva vannak az ügyfelek AZONNAL, de amint beüt egy NAV üzemszünet az összes vonalunk támadnak az ügyfelek ennek ellenére és elárasztanak e-maillel. Szóval, aki dolgozott már profitorientált cégnél és volt nagyon-nagyon-nagyon sok ügyfele (nem pár száz, vagy pár ezer), az tudja, hogy ez nem megoldás, hogy "keep cal és ne hívjál fel". Volt, akik azzal hívott fel minket, hogy "igen látta és olvasta is amit küldtünk, DE". Egy megoldást látok, egy STABIL NAV működést, illetve bármilyen rendellenes működésnél AZONNALI információ az onlineszamla.nav.gov.hu oldalán.

@EnokhSys "ezt a problémát úgy oldottam meg, hogy egy háttérben futó folyamat óránként megpróbálja beküldeni a számlákat" Szerintem ezzel nem vagy egyedül. A probléma nem ebből ered. A program folyamatosan megpróbálja beküldeni a számlát, viszont ha bármi rendelleneset tapasztal az ügyfél (pl. nem ment be a számla vagy kapcsolat hiba van), akkor minden tájékoztatástól független azonnal telefonhívást vagy e-mailt generál. A NAV üzemszünetek számunkra felérnek egy felénk célzott terheléses hacker támadással...

**Comment by NTCA-developer** [comment]
@nbeeps2 oké, köszi! Jelenleg is ezen dolgozunk, hamarosan jelentkezünk.

**Comment by EnokhSys** [comment]
@nbeeps2 "A NAV üzemszünetek számunkra felérnek egy felénk célzott terheléses hacker támadással..."

Csendben röhögök, igazán plasztikus megfogalmazás. :-)

**Comment by EnokhSys** [comment]
Töprengtem egy sort ezen az üzemszünet megoldáson, gondoltam bedobok a közösbe egy ötletet.

Az esetleg nem lenne járható út, hogy váratlan üzemszünet esetén minden token-request átirányításra kerülne egy olyan szerverhez, amely a token-response egy újonnan bevezetendő XML-szegmens-csoportjában visszaadná a nem várt üzemszünet várható időtartamát? De ugyanígy lehetne előre tájékoztatni mindenkit a token-response-ban a soron következő tervezett üzemszünetről, amit aztán minden fejlesztő be tudna építeni a saját ízlése szerint a felhasználói programba.

Gondoljatok bele, ha a felhasználók előre tudnák, hogy nagyjából mikor lesz üzemszünet, vagy, ha tudnák azt, hogy a nem várt üzemszünet meddig tart, át tudnák csoportosítani a munkájukat, és sem a fejlesztőiket, sem pedig a NAV-ot nem bombáznák kérdésekkel. Persze, lehet azt mondani, hogy minden tervezett üzemszünet felkerül a NAV honlapjára, na de könyörgöm, hány felhasználó nézi ezt? 

A lényeg az, hogyha már amúgy is van egy kommunikációs csatornánk, akkor miért ne használnánk arra is, hogy egy egész ország dolgát megkönnyítsük vele?

**Comment by rgform** [comment]
Elméletileg járható út lenne és gyakorlatilag is.  Még a NAV doksiban is van szó róla. A loadbalancer "maintenance" üzenetéről érdeklődtem... Itt feszegettem hasonló módon, de kiderült a NAV úgy alakította ki, hogy csak saját magának adjon infót:

[https://github.com/nav-gov-hu/Online-Invoice/issues/392](https://github.com/nav-gov-hu/Online-Invoice/issues/392)

**Comment by vivacomp** [comment]
EnokhSys ötlete jó, de.... a NAV a tervezett üzemszünetet nem teszi munkaidőre, a váratlanról pedig nem tuja, hogy mikor lesz vége.
A váratlan kiakadások általában tovább tartottak, mint azt az érdeklődésünkre jelezték. A mi szerverünk rendelkezésre állása 99.99%, ezt a NAV-nak is biztosítania kellene.

**Comment by EnokhSys** [comment]
@rgform Kifejezetten örülök, hogy egymástól függetlenül hasonló megoldáson törpöltünk, mert ez azt jelenti, hogy lenne létjogosultsága.

@vivacomp Az még nem baj, ha a NAV nem tudja, mikor lesz vége, de - ha jól olvasom itt a panaszáradatot - már az is nagy segítség lenne, ha ilyen esetekben javítana a kommunikáción. Amikor valami váratlan helyzet adódik, az első negyed-fél órában kiderül, hogy adott esetben 1 órán belül elhárítható vagy több órát venne igénybe. Tehát maga a token-response-ban  lehetne a várható "-ig" időket folyamatosan közölni, vagy kitolni, ahogy a helyzet megkívánja. Ami pedig a tervezett üzemszünetet illeti, valóban a legtöbb cég munkanapokon, munkaidőben számláz, de számos cég van, ahol este 6 után indul a banzáj. (Az egyik partneremnél, egy óriás-gyógyszernagykernél, este expediálnak, a számlák többsége is jellemzően akkor készül.)

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ha senki nem haragszik meg, akkor zárom ezt az issuet. Igyekszünk továbbra is.
Üdv

**Comment by EnokhSys** [comment]
Szia @NTCA-supporter, 
igazából csak annyit kérdeznék, hogy elgondolkodtatok azon a javaslatomon, hogy a tokenresponse-ban lehessen országosan üzenni, ha valami fennforgás van, vagy valami esemény van tervbe véve?
Üdv.
