### ISSUE TITLE
[Q&A] MIt jelent a türelmi időszak?

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#407]
A határidőkkel és az adatszolgáltatással kapcsolatban kérdezem az alábbiakat:
1. Mikortól lehet technikailag a NAV-Online Számla Teszt-be beküldeni az első OSA 3.0-s adatszolgáltatást?
2. Mikortól lehet technikailag a NAV-Online Számla Éles-be beküldeni az első OSA 3.0-s adatszolgáltatást?
3. Mit jelent technikailag a 2021.03.31-ig meghirdetett türelmi időszak?
3/a Azt jelenti, hogy aki OSA 2.0 struktúrában adatszolgáltat, annak 2021.03.31-ig továbbra sem kell sem a magánszemélyek számláit, sem a közösségi számlákat, sem a 3. országbeli számlákat beküldenie?
3/b Vagy azt jelenti, hogy akinek lesz 2021,01.01-től akár magánszemély felé számlája, akár közösségi, akár 3. országbeli számlája, annak muszáj áttérnie a NAV 3.0-ra legkésőbb az első ilyen számla elkészültekor.
3/c Megoldják a NAV 2.0-ban a magánszemélyek és a közösségi számlák adatszolgáltatását, ha igen, mikor? 
3/d Nem lesz türelmi időszak, sem teszt rendszer,. mert semmi nem írja elő.

**Comment by GabiSzamla77** [comment]
Sziasztok!
A fenti kérdésekre nagyon-nagyon várjuk a választ. 
Köszönjük.

**Comment by NTCA-tax** [comment]
Én is nagyon-nagyon várom, hogy kirakhassam ide...

**Comment by nbeeps2** [comment]
Hát ez nem szerencsés, annyi szent. Ha a jogszabály úgy írja elő, hogy 2021-től küldeni kell a magánszemélyeknek kiállított számlát is és addig a program valamiért nem fogja tudni, akkor a felhasználók verni fogják a palávert... Jön majd a konkurens termékekre való mutogatás, hogy aki megoldotta, annak miért megy, vagy a beparáztatott ügyfél, hogy őt most emiatt megbüntetik? Nem büntetik meg, de majd generálja a cirkuszt. A legjobb megoldás tehát az lenne, ha a jogszabályt is úgy hirdetnék ki/módosítanák, hogy csak 2021.04.01-től kell jelenteni minden számlát és nem január 1-től.

**Comment by jozanesz** [comment]
Ha esetleg a 3/a lenne igaz, akkor további kérdésem, hogy mennyi türelmi időt adjunk a NAV-nak a felkészülésre, mielőtt elkezdenénk bezúdítani az irdatlan mennyiségű, magánszemélynek szóló elszámoló számlát (a hozzájuk tartozó queryTransactionStatusokkal), hogy ne okozzunk egymásnak túl sok problémát.

**Comment by szako** [comment]
Korábban kétszer "változott" a törvény az adatszolgáltatás bővítésével kapcsolatban:
- Bevezetés kezdeti időpontja: 2018.07.01
- Értékhatár levitele: 2020.07.01

Mindkét időszakban biztosított a NAV szankciómentes időszakot / türelmi időt (2018.08.31-is illetve 2020.09.30-ig), de azzal a kitétellel, hogy az időszakban keletkezett - nem megfelelően vagy nem jelentett - számlákat utólagosan pótolni kell.

A kérdésem az, hogy ha a 3.0 adatszolgáltatással nem sikerül 2021 január elsejével elindulni, akkor 
a 2021.01.01 -> 2021.03.31 (vagy hamarabb, a 3.0 élesítésétől függ) között keletkezett számlákat pótolni kell?

**Comment by kurucza** [comment]
Sziasztok,  

A fenti kérdésre valamikor fogtok tudni válaszolni?
Nagyon köszi!

**Comment by lukacsb** [comment]
Most már nagyon kellenének ezek a válaszok. Jövő héten már szeretnénk elkezdeni a 3.0-ás fejlesztés kirakását az ügyfeleinkhez.

**Comment by Macskafarka** [comment]
dettó

**Comment by nbeeps2** [comment]
@lukacsb Ezt mondjuk nem teljesen értem, hiszen 3.0-val leghamarabb is max. 2021-től tudsz adatot szolgáltatni. Ennek ellenére engem is nagyon érdekel a válasz, pláne, hogy kivegyük-e a programból 2021-től a PTGSZLAH funkciót...

**Comment by lukacsb** [comment]
hát mi pont abban reménykedünk, hogy idén élesítik a 3.0-t (lehetőleg még novemberben), és lehet küldeni a számlákat (beleértve azokat a számlákat is, amelyeket jogszabály szerint csak január 1-től kéne küldeni)

1.1-re és 2.0-ra átálláskor is így volt, már határidő előtt lehetett úgy küldeni a számlákat

**Comment by nbeeps2** [comment]
@lukacsb én erre nagyon kicsi esélyt látok, mivel (most nem tudok konkrétumot írni) láttam a 3.0-ás fejlesztés integrálása alatt olyan dolgokat, amik nem engednek meg 2021 előtti esetet...

**Comment by szako** [comment]
> Korábban kétszer "változott" a törvény az adatszolgáltatás bővítésével kapcsolatban:
> 
> * Bevezetés kezdeti időpontja: 2018.07.01
> * Értékhatár levitele: 2020.07.01
> 
> Mindkét időszakban biztosított a NAV szankciómentes időszakot / türelmi időt (2018.08.31-is illetve 2020.09.30-ig), de azzal a kitétellel, hogy az időszakban keletkezett - nem megfelelően vagy nem jelentett - számlákat utólagosan pótolni kell.
> 
> **A kérdésem az, hogy ha a 3.0 adatszolgáltatással nem sikerül 2021 január elsejével elindulni, akkor**
> **a 2021.01.01 -> 2021.03.31 (vagy hamarabb, a 3.0 élesítésétől függ) között keletkezett számlákat pótolni kell?**

Ügyféltől jött az információ, hogy a legutóbbi NAV-os előadáson, amit végighallgatott azt az információt kapta, hogy a számlákat pótolni kell. Meg tudjátok ezt erősíteni?

**Comment by nbeeps2** [comment]
Az adatszolgáltatásnak azonnalinak kell lennie, így ez igen csak ütközik azzal az elmélettel, hogy utólag kellene feladni több hónapnyi számlát... korábban is volt már ilyen szankciómentes időszak és ott csak kellett pótolni, ez jó kiindulási alap lehet ;)

**Comment by KMGY100** [comment]
@nbeeps2   azt még tedd hozzá hogy (jelen állás szerint) 2021.01.01  és 2021.03.31 között  a 2.0 -val is küldhető a számla.

**Comment by jozanesz** [comment]
Nem: https://github.com/nav-gov-hu/Online-Invoice/issues/502#issuecomment-723840410

**Comment by Macskafarka** [comment]
Ha az "azonnali adatszolgáltatás"-ban türelmi időszak van, akkor az csak azt jelentheti, hogy nem kell feladni. 
Az utólagos feladás az más technológiát igényel.

**Comment by kurucza** [comment]
@NTCA-tax 
A türelmi időszakkal kapcsolatban valamikor fogtok tudni választ adni? Mi történik akkor, ha valakinek csak export számlái vannak, így eddig nem volt adatszolgáltatásra kötelezett? Január 1-től neki automatikusan él a beküldési kötelezettség? Vagy rá is vonatkozik a türelmi időszak? 
Mostmár egyre sürgősebb és égetőbb a kérdés.

Köszönöm, ha tudsz válaszolni: Andi

**Comment by omachtandras** [comment]
Igen, nagyon szeretnénk választ kapni.

Mi a kedd esti változások előtt elkezdtük részlegesen teríteni a tervezett megoldást az ügyfeleink felé, hogy legalább a törzseket tudják addig is igazítani az elvárásokhoz. Többek közt az ÁFA kulcsokkal kapcsolatos törzset, amit a kedd esti módosítás elkaszált, újabb átalakításokat indukálva. A diff-ből ráadásul az látszik, hogy ez egy 11.09-i állapot, így az is kérdéses, hogy lesz-e még újabb változás esetleg, amiről még nem is tudunk.

Itt vagyunk december elején, se frissített dokumentáció, se - a sokak által várt - példák, se teszt környezet, ahol a megváltozott sémával lehetne próbálkozni, csak a bizonytalanság, hogy változik-e még valami és ennek tetőzéseként azt sem tudjuk, hogy mit jelent a moratórium.

Az ügyfelek természetesen felénk mozgolódnak, érthető, hiszen ők sem látnak tisztán, hogy mi várható. Tőlünk várnak megoldást, miközben rajtunk kívül álló okokból csak toporgunk, esetleg néha hátrálunk.

**Comment by lukacsb** [comment]
@omachtandras 

Bocsi de ezt átaludtuk. Milyen változások voltak kedd este?

**Comment by Macskafarka** [comment]
Új XSD séma definíciók kerültek kiadásra:
*XML séma definíciók: OSA v3 Sémák (utoljára frissítve: 2020.12.01.)

**Comment by kurucza** [comment]
@lukacsb 
https://onlineszamla-test.nav.gov.hu/fejlesztoi_naplo  (2020/5 3.0 XSD módosítások (2020.12.01))

**Comment by Macskafarka** [comment]
Elég nagy a gáz, mert sok mindent megváltoztattak, amiket már lefejlesztettünk. Kapkodás ez az egész.

**Comment by lukacsb** [comment]
köszi szépen!

**Comment by kurucza** [comment]
> Elég nagy a gáz, mert sok mindent megváltoztattak, amiket már lefejlesztettünk. Kapkodás ez az egész.

És ugye emiatt, az eddig telepített dolgokat, mint ahogy @omachtandras is írta, javítani, módosítani kell. Vannak ám a külföldi cégek, ahol a transzport nem 2 perc, nem 2 nap.......és mindjárt karácsony van és már csak 2 hetünk van és........és nem tudjuk a türelmi időszakra vonatkozó szabályokat.....

**Comment by PistikeSzoftver** [comment]
Nagyon nem hiányzott szerintem senkinek sem hogy most új XSD-vel fogalkozzon, ráadásúl ben lehet tesztelni sem, mert a teszt még a régi XSD-vel dolgozik !!!

**Comment by billsoftltd** [comment]
@NTCA-tax lehet már tudni valamit?

**Comment by nbeeps2** [comment]
@billsoftltd : https://github.com/nav-gov-hu/Online-Invoice/issues/502#issuecomment-723840410

**Comment by omachtandras** [comment]
Jött ki kommunikáció!

https://nav.gov.hu/nav/ado/afa/Online_Szamla__Marciu20201216.html

**Comment by Macskafarka** [comment]
Végre. 
Le is mentettem, mert ez az a hely, ahonnan el szoktak tűnni, és megmásulnak idővel a szövegek.

**Comment by NTCA-tax** [comment]
Hosszú volt az út, hogy végre tudjuk publikálni, de csak ott van a honlapon :) Remélhetőleg minden kérdésetekre megtaláljátok a választ benne...

**Comment by omachtandras** [comment]
Köszönjük szépen!
Tényleg jó, hogy lett.
Mi készülünk a január 4-i éles indulásra, de az ügyfeleknek ez jól jöhet, mert nem mindenkinek fér már bele a felkészülés.

**Comment by judipo** [comment]
Kedves NTCA-tax,
a biztonság kedvéért kérdezem: NAV nem alkalmaz szankciót "Ha az áfaalany olyan számláról teljesít adatszolgáltatást, amiről a 2020. július 1-jén érvényben lévő szabályok szerint nem kötelező adatot szolgáltatni, azonban az adatszolgáltatása nem megfelelő."
Ha pl. az export számlát 2.0 verzióban küldjük (megoldható, csak 3.0-hoz képest kevesebb adatot küldünk), akkor az a fentebb idézett esetnek felel meg?
Köszönöm!

**Comment by jozanesz** [comment]
> Remélhetőleg minden kérdésetekre megtaláljátok a választ benne

Az enyémre ugyan nem, de akkor döntjük/csöpögtetjük, ami a csövön átfér.

**Comment by Macskafarka** [comment]
@judipo Már miért küldenéd be az exportszámlát olyan formátumben, ami nem ahhoz való?
A v2.0-ba nem kezelhető számlákat nem kell v2.0-ban beküldeni!
Az export számlákat nem muszáj beküldeni március 31-ig, de ha úgy döntesz, hogy beküldöd, akkor azt csak v3.0-ban tudod, mert az a formátum van felkészítve azon adattartalom kezelésére.
Mellőzzük azt, hogy "mindenképpen beküldöm, így, vagy úgy, akkor is, ha nem tudom jól", mert akkor a fogadó oldal adatbázisa tele lesz sok szeméttel.

**Comment by judipo** [comment]
@Macskafarka Az ügyfél ragaszkodik hozzá, hogy küldjük be. Talán a mostani Türelmi időszakra vonatkozó kommunikáció meggyőzi őket, hogy nincs szankció és utólagos adatszolgáltatást sem írnak elő.

**Comment by Macskafarka** [comment]
@judipo Így már értem.

**Comment by Macskafarka** [comment]
@judipo  Erre mondtam korábban azt, hogy teljesen más az, ha a jogszabály biztosít türelmi időt, mintha a NAV "szankciómentes időszakot" hirdet. Az előbbi azt jelentené, hogy nem valósul meg jogszabálysértés, az utóbbi viszont azt, hogy megvalósul ugyan a jogszabálysértés, de a NAV azt a saját döntése alapján nem szankcionálja. Ez messze nem jelenti azt,l hogy más hatóság, esetleg nyomozó hatóság, ügyészség ne indíthatna eljárást. És nem jelenti azt sem, hogy a vevő ne követelhetné a jogszabály betartását.

**Comment by Macskafarka** [comment]
Csakhogy se a NAV. se a PM fel sem fogja a kettő közötti hatalmas különbséget!

**Comment by Macskafarka** [comment]
És valószínűleg ezért a szankciómentes időszakért is valakinek keményen kellett lobbiznia a NAV-on belül.

**Comment by NTCA-supporter** [comment]
Zárom az issuet. Ha van még kérdés, kérlek nyissátok újra.
Üdv
