### ISSUE TITLE
[DOC] metric/queryServiceMetrics/metric

### ISSUE THREAD

**Issue by bcdel** [nav-gov-hu/Online-Invoice#409]
**A hibás dokumentum neve / Document name containing the error**
Onlineszamla 3.0 API doksi

**Oldalszám / Page number**
192. oldal (pdf page 202)es kornyeke

**A dokumentációs hiba leírása / Description of the documentation error**
Gyanus, hogy a 8.3.1.1. pontban a 8-as fejezet tobbi adatahoz kepest nem ugyanaz a permutacioja szerepel a 
metric, queryServiceMetrics stb. szavaknak. Jelenleg nem okoz problemat a mukodesben, mert mintha ugyanazt csinalna minden formaban (http 404) de gyanus, hogy valahol eliras lesz.

**Comment by NTCA-supporter** [comment]
Köszi a jelzést. A következő verzióban javítjuk, addig maradjon nyitva az issue.
Üdv

**Comment by NTCA-supporter** [comment]
Javítottuk. Köszi a jelzést mégegyszer.
