### ISSUE TITLE
[FEATURE] Telephely adatok lekérdezése

### ISSUE THREAD

**Issue by Rossi73** [nav-gov-hu/Online-Invoice#41]
**Az igény összefoglalása / Summary of the request**
Az adózó telephely adatainak lekérdezése a queryTaxpayer operáció meghívásával.

**Az általam javasolt megoldás / The solution I propose**
A TaxpayerDataType típus bővítése a taxpayerSitesAddress elemmel, melynek típusa data:DetailedAddressType elemből álló tömb lenne (minOccurs="0"), mivel egy adózónak több telephelye is lehet.

**Egyéb tartalom / Additional content**
A partnerek részéről felmerült jogos igény, hogy az adószám lekérdezésekor az adózó székhely címe mellett lekérdezhető legyen a telephelyek címe is, mivel sok esetben nem a székhely nevére kell kiállítani a számlákat. A NAV weboldalán jelenleg van lehetőség egy adózó telephely címeinek lekérdezésére, így az információ a NAV rendszerében rendelkezésre kell, hogy álljon. A https://nav.gov.hu/nav/adatbazisok/adatbleker/afaalanyok/afaalanyok_egyszeru oldalon rákeresve az adószámra, majd a találatok közül kiválasztva a megfelelőt, a következő oldalon megjelenik az adózó telephelyeinek listája.

A queryTaxpayer operáció meghívását követően a program felajánlaná a székhely mellett a telephelyek címét is, így a felhasználó ki tudná azt választani egy listából.

Ennek előnye többek között az lenne, hogy már a kiállításkor ellenőrizni lehetne, hogy valóban a megfelelő címre történik-e meg a számla kiállítása. Adott esetben visszafelé is jótékony hatása lenne: ha a vevő olyan címre kéri a számlát, ami nem szerepel a telephelyek között, akkor jelezni lehet a vevőnek, hogy a NAV felé jelentse be a telephelyet, ha esetleg elfelejtette volna. (Nyilván a számla kiállítását ez nem akadályozná, mert olyan eset is lehet, hogy a NAV még nem vett nyilvántartásba egy címet.)

**Comment by NTCA-developer** [comment]
Szia!

Ennek utána kell nézzek, türelmet kérek. (hosszú lesz)

**Comment by NTCA-developer** [comment]
Szia @Rossi73!

Köszönöm a türelmet. Befogadjuk az igényt. A 2.0-ban az adózó lekérdezőt átalakítjuk úgy, hogy a címadat listás legyen. A lista mellett visszaadjuk azt az információt, hogy a cím székhelyre, telephelyre vagy fióktelephelyre vonatkozik.

Ahogy a rövid név esetében, itt sem fog azonnal működni a dolog, mivel jelenleg az Online Számla csak a székhelyadatokat kapja meg. De a helyét megcsináljuk a sémában, és amikor összeért az adatkapcsolat akkor jelezzük majd hogy mostantól lehet lekérdezni a telephely adatokat is.
