### ISSUE TITLE
[DOC] AdvanceDataType leírása

### ISSUE THREAD

**Issue by alaplap** [nav-gov-hu/Online-Invoice#410]
**A hibás dokumentum neve / Document name containing the error**
Online Szamla_interfesz specifikáció_HU_v3.0.pdf

**Oldalszám / Page number**
108. oldal

**A dokumentációs hiba leírása / Description of the documentation error**
Az 57. ábra alatti táblázat "Tartalma" oszlopában lévő leírás nincs szinkronban az ábrában látható leírásokkal.
Valamint a "Facetek és leírók" táblázatban a `advancePaymentData/advanceExchangeRate` tag-hez tartozó "Pattern" nem egyezik az invoiceData.xsd-ben megadott `ExchangeRateType`-nak a "restriction"-jével.

**Comment by NTCA-supporter** [comment]
Köszi a jelzést. A következő verzióban javítjuk, addig maradjon nyitva az issue.
Üdv

**Comment by NTCA-supporter** [comment]
Javítottuk. Köszi a jelzést mégegyszer.
