### ISSUE TITLE
[Q&A] Online pénztárgépes számlák

### ISSUE THREAD

**Issue by laladisc** [nav-gov-hu/Online-Invoice#411]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Van e tervben azoknak a számláknak az queryinvoicedigest-el történő lekérdezhetősége, amelyek jelenleg nincsenek fent az Online számla rendszerben, mert pénztárgéppel lettek kiállítva?

**Comment by Macskafarka** [comment]
Én egyszerűen már nem vásárolok ott, ahol azt látom, hogy pénztárgéppel készítik a számlát.
A Posta az trükkös, mert ugyannnál az ablaknál tudnak pénztárgéppel is és számlázóval is készíteni. A számla utóbbi esetben "SZ/"-rel kezdődik.

**Comment by omachtandras** [comment]
Tavasszal volt róla szó, júliusra ígérték.
Nálunk is nagyon várják már az ügyfelek, hogy legyen rá valamilyen megoldás.

**Comment by NTCA-tax** [comment]
Adóhivatali oldalról is nagyon fontos lenne a pénztárgépes számlákat is visszamutatni az Online Számla rendszerben. @omachtandras bejegyzésére utalva júliusra most is meg tudjuk ígérni :) Remélhetőleg ennél korábban meg tudjuk csinálni, de határozott időpontot jelenleg nem tudok mondani.

**Comment by laladisc** [comment]
Köszönjük @NTCA-tax a választ. Még az a kérdés merült fel bennem, hogy jelenleg nem látok a dokumentációban a Digest-el kapcsolatban olyan jellegű változtatást ami arra utalna, hogy a digest vissza fogja adni az EU-s, export és magánszemélyes kimenő számlák adatait. Jól gondolom, hogy ezeknek a számláknak a lekérdezhetősége is egy későbbi fejlesztés keretében fog megvalósulni?

**Comment by NTCA-developer** [comment]
Szia @laladisc 

Keresőfeltételt hiányolsz az új vevői adatokra vagy a válaszban szeretnéd az adatokat látni? (esetleg mindkettő) Tudomásom szerint ezekről azért nem volt eddig gondolkodás, mivel ezeknek a számláknak a vevői oldalas lekérdezése nem jön szóba. (nincs se regisztráció se API user ezekre a vevőkre) Csak kiállítói oldalról pedig egyelőre nem látjuk az értelmét ezeknek az adatoknak a kivonatolására.

De figyelek ha mondasz valid use caset.

**Comment by laladisc** [comment]
@NTCA-developer , kibocsájtói oldalról értettem a lekérdezhetőséget. Tehát, ha én számlázok EU-s, Export partnernek, vagy magánszemélynek, akkor a könyvelőm látni fogja e digest lekérdezésben ezeket a kimenő számlákat? A digest esetleg vissza adhatáná az EU-s adószámot, vagy ha export vevő volt a thirdtaxid-t, magánszemély esetén a privatepersonindicator-t. Szóval erre irányult volna a kérdésem.

**Comment by NTCA-supporter** [comment]
Sziasztok!

A pénztárgépes számlák integrációja meg lesz valósítva már biztosan, határidőt azonban nem tudok mondani, így maradhat nyitva az issue. A digest api véglegesedett a 3.0-ban, változást és újabb verziót nem tervezünk.

Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok! 

FYI: 

Tájékoztatjuk, hogy 2021. október 2-től a NAV Online Számla rendszerből lekérdezhetők az online pénztárgépek adatszolgáltatásából származó, egyszerűsített számlák 3.0-ás XSD formátumban.

Az online pénztárgépi adatok áttöltődnek az Online Számla rendszerbe mindennap hajnalban,  tehát naponta egyszer frissülnek. Ennek megfelelően mindig másnap reggel lehet számítani az új pénztárgépes egyszerűsített számlák megjelenésére. Az online pénztárgéppel kiállított, egyszerűsített számlák automatikusan konvertálódnak, majd betöltődnek az Online Számla szerinti 3.0-s XSD formátum alapján, így a kliens oldalon azok lekérdezésére automatikusan lehetőség nyílik külön fejlesztés nélkül.

Az áttöltés a 2021. október 1-jétől kiállított bizonylatokkal indul, amiket október 2-ától lehet lekérdezni az Online Számla rendszerből.

forrás: https://onlineszamla.nav.gov.hu/home

**Comment by omachtandras** [comment]
Szuper hír!

**Comment by omachtandras** [comment]
Sziasztok!

Az lenne a kérdésem, hogy ilyenkor az insDate az a pénztárgéptől kapott tényleges tranzakciós időpont lesz, vagy pedig az, amikor az OSZ adatbázisba bekerül?
Azért kérdezem, mert szerintem sokan csináljuk azt, hogy lekérjük a számlákat, megjegyezzük, hogy melyik volt az utolsó insDate, majd x idő múlva már csak az ettől a pillanattól bekerült számlákat kérjük le.
Ha a pénztárgépes számlák másnap az eredeti dátumukkal kerülnek be az OSZ-ba, akkor ezeket mi sosem fogjuk megkapni, hacsak át nem írjuk a lekérdezési logikát, ami nem lenne túl szerencsés, mert (felesleges) plusz terhelést adna a NAV oldalon...  (Nálunk megvan a logika, hogy ilyenkor felismerjük az újra letöltést, de feleslegesen sok kommunikáció lenne minden 15 percben az elmúlt 24-25 óra minden számlájáról dönteni...)

András

**Comment by omachtandras** [comment]
Sziasztok!
Ha ma 11:20ra történt a betöltés, akkor rossz érzésem van....
Azóta a letöltő szálak rengeteg cégnél dobják a következő hibát:
Incorrect / incomplete data - hu.gov.nav.schemas.osa._3_0.api.QueryInvoiceDataResponse
  invoiceDataResult
    auditData
      insCusUser = null
      - may not be null (ConstraintViolationException)

A doksiból: "A login tag a technikai felhasználó nevét tartalmazza. A login nevet a rendszer véletlenszerűen 
generálja  a  technikai  felhasználó  létrehozásakor 15 karakter hosszan. A login tag az 
authentikáció egyik eleme. "

Lehet, hogy a pénztárgépes számlák betöltése nem schema valid?

András

**Comment by NTCA-supporter** [comment]
Sziasztok!

Az insdate minden esetben az a dátum lesz, amikor bekerül az Online Számla rendszerbe.

Ha nincs több észrevétel, akkor zárom ezt az issuet. A lekérdezés insCusUser problémájára lett felvéve külön issue, abban lesz jelezve ha elérhető a javítás.

Kérdés esetén nyissátok újra nyugodtan.
Üdv
