### ISSUE TITLE
API 3.0: queryTransactionList response új mezők

### ISSUE THREAD

**Issue by HWKF** [nav-gov-hu/Online-Invoice#412]
Az új response mezők:
- transaction/technicalAnnulment: gondolom ez azt jelenti, hogy egy technikai érvénytelenítéshez tartozó tranzakcióról van szó.
- transaction/requestStatus: melynek értékei az alábbiak lehetnek RECEIVED,PROCESSING,SAVED,FINISHED,NOTIFIED.
Gondolom, hogy itt a tranzakció státuszát kapnánk meg. Csak nem értem az eltérést az eddig ismert státuszokkal szemben. Vagy ez csak egy elírás?
Mit jelent a FINISHED és a NOTIFIED státusz?
Miért nem szerepel az ABORTED és a DONE?

**Comment by NTCA-supporter** [comment]
Szia @HWKF !

1.: igen azt jelenti
2.: ezek a státuszok azért kellenek, mert itt nem számlánként adjuk vissza a státuszt, hanem tranzakciónként.
Az xsd-ből bemásolom az enum leírásokat:
			<xs:enumeration value="RECEIVED">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Befogadva</xs:documentation>
					<xs:documentation xml:lang="en">Received</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="PROCESSING">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Feldolgozás alatt</xs:documentation>
					<xs:documentation xml:lang="en">Processing</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="SAVED">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Elmentve</xs:documentation>
					<xs:documentation xml:lang="en">Saved</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="FINISHED">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Feldolgozás befejezve</xs:documentation>
					<xs:documentation xml:lang="en">Finished processing</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="NOTIFIED">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Lekérdezve</xs:documentation>
					<xs:documentation xml:lang="en">Notified</xs:documentation>
				</xs:annotation>
			</xs:enumeration>

Az interfész dokumentáció következő verziójában írunk róla részletesebben, hogy egyértelmű legyen.

Üdv
