### ISSUE TITLE
[Q&A] advancePaymentData kötelező-e végszámla esetén?

### ISSUE THREAD

**Issue by fzoli15** [nav-gov-hu/Online-Invoice#413]
Az interfész specifikáció v3.0 "2.9 Előlegszámla, végszámla adatszolgáltatása" fejezetében ez szerepel:

> A végszámla adatszolgáltatásánál az <advanceIndicator> értékét „true”-ra kell állítani és amennyiben a számla tartalmazza (vagy a számlázó program ki tudja tölteni), akkor az <advancePaymentData> csomópontot is **ki lehet tölteni**. 

Ezzel szemben a Changelog 3.0-ban:

>Ha a számlasor előleg adotokat tartalmaz, akkor azokat új Xpath alatt, a line/advanceData alatt adhatod meg. Figyelj rá, hogy **ha van előleg adat (advanceIndicator=true) akkor az advancePaymentData csomópont alatt kötelező megadnod** az előleg számla sorszámát (advanceOriginalInvoice), az előleg fizetés időpontját (advancePaymentDate) és az alkalmazott árfolyamot (advanceExchangeRate).

 A https://github.com/nav-gov-hu/Online-Invoice/issues/355 issue-ban írtátok, hogy a korábban tervezett ERROR törlésre kerül, ami ennek a csomópontnak a kötelezőségét vizsgálta volna. Ez így rendben van, tehát nem fogok ERROR hibaüzenetet kapni, ha enélkül küldöm be a végszámlát.
Viszont a látszólag egymásnak ellentmondó, ködös leírások alapján nekem még nem teljesen egyértelmű, hogy üzletileg, jogilag kötelezők lesznek-e ezek az adatok a végszámlák esetén.
Az interfész specifikáció "II.2 Kötelezőségek" részében nem látom az advancePaymentData-t. De ha jól gondolom, akkor technikailag nem kötelező, és az ÁFA tv. szerint sem kötelező, tehát nem kötelező.

Szeretnék egyértelmű választ kapni a következőkre:
1. Az advancePaymentData adatok beküldése kötelező-e a végszámláról küldött adatszolgáltatásban, ha a végszámla tartalmazza ezeket az adatokat?
2. Az advancePaymentData adatok beküldése kötelező-e a végszámláról küldött adatszolgáltatásban, ha a végszámla nem tartalmazza ezeket az adatokat?

**Comment by NTCA-tax** [comment]
A végszámla adatszolgáltatásában mindenképpen jelölni szükséges az előleg tételsorát. Az advancePaymentData kitöltésére nincs jogszabályi kötelezettség és adatszolgáltatásból eredő technikai kötelezőség sem. Ugyanakkor ha egy szoftver kitölti, akkor mindhárom értéket ki kell töltenie.

**Comment by fzoli15** [comment]
Köszönöm a választ!
Akkor ennek megfelelően kérjük, javítsátok a Changelog 3.0-ban ezt a részt:

> Ha a számlasor előleg adotokat tartalmaz, akkor azokat új Xpath alatt, a line/advanceData alatt adhatod meg. Figyelj rá, hogy **ha van előleg adat (advanceIndicator=true) akkor az advancePaymentData csomópont alatt kötelező megadnod** az előleg számla sorszámát (advanceOriginalInvoice), az előleg fizetés időpontját (advancePaymentDate) és az alkalmazott árfolyamot (advanceExchangeRate).

És kérjük, hogy az interfész specifikáció "II.2 Kötelezőségek" részébe kerüljön bele ez is, hogy mindenki számára egyértelmű legyen.

**Comment by nbeeps2** [comment]
Nem mellesleg a advancePaymentData struktúra hiányossága, hogy egy előleghez egy kiegyenlítési dátumot lehet megadni... Mi van ha én kiállítottam egy előleg számlát és az ügyfél két (vagy több) összegben fizeti ki, ne adj Isten két külön napon, amikor még az árfolyam is más... Minél jobban bonyolítunk valamit, annál több lehetetlen helyzet adódik...

**Comment by omachtandras** [comment]
> 
> 
> Nem mellesleg a advancePaymentData struktúra hiányossága, hogy egy előleghez egy kiegyenlítési dátumot lehet megadni... Mi van ha én kiállítottam egy előleg számlát és az ügyfél két (vagy több) összegben fizeti ki, ne adj Isten két külön napon, amikor még az árfolyam is más... Minél jobban bonyolítunk valamit, annál több lehetetlen helyzet adódik...

Valószínű nem helyes az ilyen gyakorlat. Előleg számlát akkor kell kiállítani, ha a pénz megérkezett és akkora összegben, amennyi érkezett. Ha különböző napokon érkezik pénz, akkor az több előleg számlával bizonylatolandó.

Ha csak szeretnék pénzt kérni a partnertől, akkor díjbekérőt (vagy hívjuk bárminek) kell kiállítani felé, nem előleg számlát, mert korántsem biztos, hogy fizetni is fog.

**Comment by nbeeps2** [comment]
A díjbekérő alkalmazása nem elterjedt, nagyon sokan nem fizetnek pro formára csak számlára. A díjbekérő nincs sehol előírva, gyakorlatilag egy papíron nem létező, nem szabályozott dolog, vagyis sehol nincs leírva, hogy így kell bekérni előleget. Az előleg bekérése nem különbözik egy sima számázástól. Nagyon sokan állítanak ki számlát termékről, szolgáltatásról előre ott is előfordulhat, hogy a vevő nem fizet. Olyankor stornózzák a számlát. Praktikus díjbekérőt fizettetni a vevővel (én is ezt alkalmazom), de semmi nem zárja ki az, hogy átutalásos előleg számlát állíts ki.

**Comment by Macskafarka** [comment]
@nbeeps2 A díjbekérő (előlegbekérő) alkalmazása valóban nem kötelező. Ettől még használható a polgári jogviszony keretében.
Tehát az előreutalást vagy szóbeli megállapodásra, vagy szerződésre, vagy előlegbekérőre (díjbekérésre) szokták fizetni.
Előleg bekérés nem kötelező, a pénz jöhet "csak úgy" is.
**Ha az előleg összege beérkezik, akkor arról előleg számlát KELL kiállítani.**
Termékértékesítésről számla NEM állítható viszont ki a termékértékesítés előtt, azaz ezzel előleg nem kérhető.
Ha már számla volt, akkor a beékező pénz nem előleg, hanem Értékesítés kiegyenlítése.
Van egy könnyítés: Nem kell előlegszámlát kiállítani akkor, ha a pénz beérkezése után, (azt hiszem, hogy még aznap) megtörténik a termék értékesítése is.

**Comment by nbeeps2** [comment]
_"Ha az előleg összege beérkezik, akkor arról előleg számlát KELL kiállítani."_
Ez tiszta sor. Én arról beszélek, hogy kiállítasz mondjuk egy papír alapú előleg számlát, elküldöd a vevőnek postán. Mindezt azért, mert ő nem hajlandó csak úgy fizetni, illetve díjbekérőre sem fizet. Hozzáteszem a legtöbb állami szervezet ilyen bürokratikusan működik, saját tapasztalat. Kiállítod tehát az átutalásos előleg számlát 8 napos fizetési határidővel és majd ezt valamikor kifizeti az ügyfél... Ilyen is van, mert van.

**Comment by Macskafarka** [comment]
Elhiszem, hogy van ilyen, de akkor is helytelen. Elegszámla csakis a pénz kézhezvétele UTÁN állítható ki.
Az előlegszámla a pénz átvételét igazolja.

**Comment by nbeeps2** [comment]
Ott kezdődik a probléma, hogy nem létezik olyan, hogy előleg számla. Igazából ugyebár csak számla létezik, a számlára meg azt ír rá a kiállító, amit akar. A számlára írt dolgokból derül csak ki, hogy valójában az az számla egy előleg kifizetését bizonylatolja, ennek felismerése azonban nem mindig lehetséges.

**Comment by Macskafarka** [comment]
Van előleg számla, az áfa tv. 127.§ szerint.
"127. § (1) Az adólevonási jog gyakorlásának tárgyi feltétele, hogy az adóalany személyes rendelkezésére álljon
d) a 120. § d) pontjában említett esetben a nevére szóló, az előleg megfizetését tanúsító számla"

valamint az 59.§ arról szól, hogy az előleg kézhez vételekor kell az áfát megállapítani.
"59. § (1) Termék értékesítése, szolgáltatás nyújtása esetében, ha a teljesítést megelőzően ellenértékbe beszámítható vagyoni előnyt juttatnak (a továbbiakban: előleg), a fizetendő adót pénz vagy készpénz-helyettesítő fizetési eszköz formájában juttatott előleg esetében annak jóváírásakor, kézhezvételekor, egyéb esetben annak megszerzésekor kell megállapítani."
Megállapítani bizonylattal kell, ezt hívják a köznapi nyelven előleg számlának.
A NAV struktúrában az előleg az tételsor jelölő adat, de a gyakorlatban nem szoktak az előleg kézhezvételéről készülő számlára más termékértékesítő sorokat is belekeverni, ezért az előleg kézhezvételéről készülő számla általában csak előleg tételsorokat tartalmaz.

**Comment by Macskafarka** [comment]
Ha valaki termékértékesítés ELŐTT állít ki termékértékesítésről számlát, az "fiktív számla", mivel a termékértékesítés még nem jött létre. Ebből fakadóan a befogadó oldalon áfa levonásra nem jogosít.

**Comment by Macskafarka** [comment]
Viszont a számlakibocsátónál a termékértékesítés ELŐTT kibocsátott számla után a fizetendő adót meg kell állapítani. Az ilyen számla jó az államnak, mert adófizetést keletkeztet, de levonási jog nem tartozik hozzá.

**Comment by Macskafarka** [comment]
@nbeeps2 Így már értem.
Nekünk is betenne egy olyan NORMAL számla, amelyen egyszerre szerepel termék értékesítő sor és előleg sor. A törvény annyira  laza, hogy annak összes lehetőségét lehetetlen leképezni.

**Comment by Macskafarka** [comment]
Egy normális országban az előleg fizetést nem vonnák be az áfa körbe, így megúsznák az előlegszámlát, a végszámlába betudást, a végszámlába túlzottan betudott előleg miatti negatív végszámlát, az előleg számlán való utólagos módosítgatásokat az áfa kulcsok miatt.
Ez egy élhetetlen ország abnormális adórendszere...

**Comment by topybear** [comment]
Pontosabban egy túlzottan "élelmes" ország (lakosság) miatt elbonyolított adórendszer.
Szoktam mondani: vannak az élhető, de nem betartatható szabályok. Ha ezeket nem tartjuk be, olyankor jönnek az élhetetlen, de betartatható szabályok. 
A mostani adórendszerünk az elmúlt évtizedek trükközéseinek inverz lenyomata...

**Comment by bakter80** [comment]
> Elhiszem, hogy van ilyen, de akkor is helytelen. Elegszámla csakis a pénz kézhezvétele UTÁN állítható ki.
> Az előlegszámla a pénz átvételét igazolja.

Ha ez így lenne, akkor előlegszámla csak és kizárólag készpénzes lehetne.
Nem lehetne átutalásos, sőt még bankkártyás se.
A semmire senki nem fog utalni semmit, és bankkártyával se fog fizetni, hogy a jóváírás után kapja meg a kiállított számlát.
Szerintem itt arról van szó, hogy az adólevonási jog keletkezik a kifizetés/jóváírás után, nem maga az előlegszámla.

**Comment by Macskafarka** [comment]
Nem értem @bakter80 készpénzes felvetését. 
A számlának nem kötelező eleme a fizetési mód, mert az nem jelent semmit. Ha valaki kap egy átutalásos számlát, akkor is kifizetheti készpénzzel, sőt, akár több részletben más-más fizetési móddal, egy részét bankkártyával, más részét készpénzzel, a fennmaradót meg kompenzálással (beszámítással). 
Amúgy a bankkártya nem is önálló fizetési mód, az készpénz-helyettesítő, azaz jogilag készpénznek minősül.
Visszatérve az előlegszámlára, azt csak a pénz megérkezése UTÁN szabad kiállítani, pontosan úgy, amikor csak a termék értékesítése után szabad számlázni.  Az ÁFA tv. 59.§:
59. § (1) Termék értékesítése, szolgáltatás nyújtása esetében, ha a teljesítést megelőzően ellenértékbe beszámítható vagyoni előnyt juttatnak (a továbbiakban: előleg), a fizetendő adót pénz vagy készpénz-helyettesítő fizetési eszköz formájában juttatott **előleg esetében annak jóváírásakor,** kézhezvételekor, egyéb esetben annak megszerzésekor kell megállapítani.

Az előlegszámla a kiállítónál a keltezési dátuma napjával áfa fizetést keletkeztet, a számla befogadónál pedig áfa levonási jogot teremt (ha nem a kivételek valamelyike). Jól is nézne ki, ha a ki nem fizetett összeg után a számla befogadó adólevonási jogot gyakorolhatna. 
Adólevonási jogot csak bizonylat keletkeztet, ez pedig az adót tartalmazó számla. Maga a pénz mozgása, utalása bruttó összeg, annak nincs adókulcs, ezért az adótartalma nem állapítható meg.
A "semmire senki nem fog utalni semmit" -re: díjbekérőre, vagy szerződésre, megállapodásra is lehet utalni.

**Comment by bakter80** [comment]
Azt akartam, mondani, hogy van átutalásos előlegszámla, ahol a számla kiállítása után utalnak, és ez szabályos
"59. § (1) Termék értékesítése, szolgáltatás nyújtása esetében, ha a teljesítést megelőzően ellenértékbe beszámítható vagyoni előnyt juttatnak (a továbbiakban: előleg), **a fizetendő adót** pénz vagy készpénz-helyettesítő fizetési eszköz formájában juttatott előleg esetében annak jóváírásakor, kézhezvételekor, egyéb esetben annak megszerzésekor **kell megállapítani**."
A fizetendő adó az alany, nem az előlegszámla.
Szóval nem a számlát kell utána kiállítani, hanem utána lehet betenni az áfa bevallásba.

**Comment by fzoli15** [comment]
@bakter80 Az előlegszámla az előleg átadását-átvételét bizonylatolja, nemcsak magát a tényt, hanem annak az időpontját/dátumát is. Ezért csak az előleg tényleges átvétele, beérkezése, jóváírása után lehet kiállítani az előlegszámlát.
Hogyan tudnád helyesen előre bizonylatolni azt, ami még meg sem történt, és lehet, hogy nem is fog megtörténni, vagy esetleg nem azon a napon fog megtörténni, amire előzetesen számítasz?

**Comment by Macskafarka** [comment]
A dologra legjobban a belföldi értékesítésre adott devizás előleg mutatja meg.
Deviza összeg érkezik utalással. A pénz bankszámlára történő jóváírásának napján érvényes árfolyammal KELL az előleg áfáját megállapítani ft-ban, ezért csak a jóváírást követően lehet az előlegszámlát kiállítani. 
Belföldi deviza számlán az áthárított adó Ft összegének is szerepelnie kell, amihez ismerni kell az árfolyamot.

Továbbá előleg esetén a fizetendő adó megállapításakor érvényes adókulcsot kell használni. Mivel az adó megállapítása @bakter80 szerint is a pénz jóváírásának napján történik, ezért a jóváírás napján érvényes áfa kulccsal kell kiállítani az előlegszámlát. Ha pl a következő év január 01-én megváltozik az adott termék áfa kulcsa 27%-ról 5%-ra, pl .lakások esetén, akkor december 15-én nem állíthatsz ki előlegszámlát 5%-os kulccsal azért, mert hátha csak január 01 után fogják elutalni. A dolog még sarkosabb, ha a 27% megszűnik, és mondjuk 23% lesz az áfa kulcsa.
Azt előre nem lehet tudni, hogy az előleget milyen módon (készpénz, utalás, beszámítás, nem pénzbeni teljesítés), milyen napon, milyen összeggel (devizás esetben az árfolyamot is befolyásolja) rendezik pénzügyileg.
Újabb érv, hogy a NAV az áfa bevallást az előlegszámlák alapján fogja elkészíteni, mert az előlegszámlával történt az áfa összegének **a megállapítása.**

**Comment by Macskafarka** [comment]
Még azt sem lehet előre tudni, hogy milyen devizában utalják az előleget.

**Comment by bakter80** [comment]
Nekem a törvény szövegéből nem következik, hogy akkor kell kiállítani a számlát, amikor a pénz megvan.
De ha jobban belegondolok, ezt úgyse tudom rendszer szinten kikényszeríteni.
Nem fogom tudni, hogy fizikailag mikor jött meg a pénz.
Azt se tudom garantálni, hogy amint megjön a bank kivonat egyből berögzítik, és egyből kiállítják az előlegszámlát.
Ha átutalás vagy bankkártyás fizetés van, akkor a gyakorlatban a legjobb szándék esetén se biztos, hogy aznap lesz kiállítva az előlegszámla.

**Comment by KMGY100** [comment]
Kedves Hölgy !   @Macskafarka    
( nem valószínű hogy férfi Macskafarka nevet ad magának)

Törvényismeretből és törvény magyarázatból jeles !
DE hidd el, vagy éppen Te is tudod hogy több cég nem ad előleget számla nélkül,
vagyis előbb kéri a számlát (mely előlegszámla) és arra fizeti ki az előleget.
Önkormányzati pályázati ép.ip. munkák esetében ezt több prg. használómnál
tapasztalom, pedig gondolhatnánk hogy önkormányzati szinten ebben a tekintetben
képzettebb emberek vannak mint egy "egyszerű"  vállalkozás szintjén.

Bizonyára @bakter80 is tapasztalt hasonlót,

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet. Ha van még kérdés nyissátok újra nyugodtan.
Az interfész dokumentáció frissítve lett, és ugye séma szinten is opcinális lett a csomópont.
Üdv
