### ISSUE TITLE
Warning kontra Aborted 

### ISSUE THREAD

**Issue by kurucza** [nav-gov-hu/Online-Invoice#414]
SZiasztok,  A NAV specifikációba a következő megfogalmazás áll a warning üzenetekhez:

''figyelmeztetést (olyan üzleti hiba, amely az adatszolgáltatás befogadását nem blokkolja,
azonban a számla, vagy az erről nyújtott adatszolgáltatás tartalmilag helytelen vagy helytelen
lehet => WARN típusú visszajelzés)''

Ez számomra azt jelenti, hogy a warning üzenetű számlák, ott vannak a NAVnál, befogadták de nem teljesek.
Már 2 esetben tapasztaltuk azt, hogy a warning üzenettel bement számla nincs ott a NAV oldalon, sőt a NAV felől volt egy megkeresés is ezzel kapcsolatban. Lényegében olyan, mintha Aborted státusza lenne. 

Tudtok nekem abban segíteni, hogy mit is jelent konkrétan a warning üzenet, mert nem mindegy, hogy azt hiszem vagy tudom, hogy beküldtem a számlát.

Köszönöm,
Andi

**Comment by NTCA-supporter** [comment]
Szia @kurucza !
Az értelmezésed helyes. Ha csak WARN figyelmeztető üzenet van, akkor a számlát befogadtuk, feldolgozuk, elmentettük.
Mit jelent az, hogy nincs ott a NAV oldalon?
Ha szükséges a konkrét eset nyomozása akkor kérlek teszt rendszeren próbáld meg repordukálni és utána nézünk.
Üdv

**Comment by kurucza** [comment]
Szia,

Köszönöm a villámgyors válaszod.
Nagyon leegyszerűsítve azt jelenti, hogy Aborted státuszú számlával egyenrangú a beküldött számla, ami warningos visszaigazolást kapott. Azt gondolom beküldtem, a NAV jelezte, hogy ott van, de hiányosan, közben az adatszolgáltatás nem történt meg.
Sajnos az éles redszeren van rá példánk, de előállítjuk a tesztrendszerben is és kérném a segítséged majd abban, hogy mi a probléma.

Andi

**Comment by NTCA-supporter** [comment]
Rendben, egy tranzakcióazonosítót vagy requestId-t küldj majd és megnézzük.

**Comment by kurucza** [comment]
SZia,

Tranzakciós ID:34L5ITPTZN5XQTJ2  (Ugyanez a példa volt az éles rendszeren.)
A NAV megkeresésben az állt, hogy pár számlát nem jelentettük le, és ez úgy derült ki, hogy a fogadó fél visszaigényelte az áfát.

Köszi a segítséget,
Andi

**Comment by NTCA-supporter** [comment]
Szia @kurucza !
Ez rendben bement, hol nem látod ezt a számlát?
Vagy élesen mást tapasztaltál mint teszt rendszeren?
Üdv

**Comment by kurucza** [comment]
SZia,
Ez nem mehetett be rendben, mert meg is kaptuk a warningos visszajelzést, miszerint:
vevő adószáma (első nyolc karaktere) hiányzik, tehát nincs a vevőnek adószáma...
A száma a NAV oldalán ott van, látszik a sárga kis háromszög, de mégsem látja a NAV, ha egy olyan megkeresése van, miszerint ezt a számlát nem jelentettük le.  
A kérdés az, hogy amikor ellenőrzi XY adott cég beküldött számláit és kiküld egy levelet, hogy hiányzik bármi is, mit ellenőríz. Mert hiába megy be a számla warning-al, ha utána azt nem ott lévőként kezeli a NAV. 
Ha a vevőnek nincs adószáma és valaki ez alapján keres vagy szűr akkor nincs számla, hiába van ott.
Ez nem warning, az ilyen típusú esetnek Abortednak kellene lenni.

**Comment by NTCA-supporter** [comment]
Így már értem a problémád, viszont szerintem ez nem technikai kérdés.
Szigorúan véve, ha ABORTED-ot kapsz vissza akkor nem fogadtuk be az adatszolgáltatást, abban blokkoló hiba van. Ha pedig DONE státuszt, akkor ugye maximum WARN figyelmeztetés van benne.
Az, hogy melyik üzleti ellenőrzés blokkoló és melyik figyelmeztető, adószakmai döntés, és szerintem nem github téma.
Emellett szerintem az sem, hogy a NAV mi alapján ellenőriz, nekünk fejlesztői oldalon ehhez semmi közünk.
Ha esetleg @NTCA-tax szeretne valamit hozzáfűzni szakmai oldalról, akkor azt megteheti, addig nyitva hagyom az issuet, viszont szerintem ez tényleg nem ide való topic.
Köszönöm

**Comment by kurucza** [comment]
Köszönöm szépen a segítséget és az átirányítást.

**Comment by NTCA-tax** [comment]
Egyetértek @NTCA-supporter kommentjével. Az, hogy valamelyik adattartalmi hibára error-t vagy warning-ot adunk vissza olyan adószakmai és kockázatelemzési kérdés, melyet nem magyarázunk meg.
