### ISSUE TITLE
[Q&A] E-számla, papír számla

### ISSUE THREAD

**Issue by csaszko** [nav-gov-hu/Online-Invoice#415]
Sziasztok!

Nem csak ide tartozik ez az kérdés, de nem nagyon van ötletem, hogyan kezeljük, ha nem Ti vagytok a kompetensek, akkor kérlek továbbítsátok a megfelelő fórumra. 
https://nav.gov.hu/nav/ado/afa/Az_elektronikus_szaml20200416.html
Adott a fenti állásfoglalás, ami részletezi -szerintem rettentően zavaros módon -, hogy mi az e-számla és mi nem. 

Probléma ami az online számlát is érinti: 
Szállító kiállít egy (szándék szerint) papír számlát amit elküld emailben a vevőnek. (az állásfoglalás alapján jelen esetben ez már innentől e-számlának minősül) Elküldik papír alapon is az eredeti adatszolgáltatásnak megfelelően, de nem érkezik meg, a vevő nem keresi, nem érdekli, elfelejtette, hogy a másik 1000 számlája közül itt még kellene, hogy megérkezzen papíron is., stb teljesen lényegtelen a miért. A vevőnél ezért ez e-számla, a szállítónál papír.

Van még pár eset ami eszembe jutott, de talán ennyiből is látszik mi szerintem a probléma. 
Mi ilyenkor a teendő? Módosítani kellene az adatszolgáltatást? Honnan fog értesülni egyik, vagy másik oldal, hogy kellene egyáltalán? Mindegyik verzió teljesen felesleges terhet ró minden érintett félre. 

A egyszerű megoldást nem IT oldalon látom, hanem a számla és e-számla ilyen formán való megkülönböztetését (miután minden bemegy már online) már el lehetne teljesen felejteni.

Köszi

**Comment by NTCA-tax** [comment]
Itt két eltérő dologról beszélünk és nem is feltétlenül adatszolgáltatási problémát érint.

Az invoiceAppearance mezőben azt kell megadni, hogy mit tud a számlázó program akkor, amikor a számla kiállításra került. Ez lehet elektronikus számla, lehet papíralapú számla, de előfordulhat, hogy akkor ez még nem tudott, egy későbbi folyamatban dől el. Tehát ez a kiállítás időpillanatában tudott ténynek a rögzítése.

Az elektronikus számla két partner megegyezésétől függ. Fontos, hogy az elektronikus számlázásba a vevő beleegyezzen. Ugyanakkor nem csupán az elektronikus számlázásba egyezhetnek meg, hanem abba a folyamatba is, amit Te leírtál. Kiállításra kerül elektronikus és papír formában is a számla, a két partner pedig megegyezik arról, hogy kölcsönösen melyiket tartja hitelesnek. Amennyiben a papíralapú számlát, akkor mindkét oldalon a papíralapú számla alapján történik meg a könyvelés, adólevonás vagy az adó befizetése. Ekkor az elektronikusan megküldött dokumentumot egyik fél sem tekinti hitelesnek, ugyanakkor a két fél közötti kommunikáció hatékonyságában nagy segítségre lehet. 

A fentiek alapján amit levezettél, az azt jelenti, hogy kizárólag azért tekinti az elektronikus dokumentumot elektronikus számlának valaki, mert a mindkét fél által hitelesnek tekintett papíralapú számla kibocsátása, megküldése, esetleg megőrzése nem történt meg. Ezt azért jogszabályból nehezen lehetne levezetni... 

A teljes kérdéskör ugyanakkor az adatszolgáltatáshoz nem nagyon kapcsolódik. A kapcsolódási pontot az InvoiceAppearance résznél megadtam.

**Comment by csaszko** [comment]
Köszönöm a részletes válaszod.   

Szerintem nagyon is kapcsolódik az adatszolgáltatáshoz:
A válaszod alapján :
 
A rendszer elkészíti a számlát, adatszolgáltatásnál invoiceAppearance=PAPER, a számlát végül a számlázó ügyintéző (vagy a rendszer automatikusan)  mégis emailben küldi el. 

> Egy elektronikusan megküldött és befogadott számla elektronikus számla lesz, függetlenül annak formátumától, a küldés technikájától stb.

Tehát innentől kezdve elektronikus számlaként tekintendő, itt érinti az adatszolgáltatást, mert ott viszont papír van megadva.  
Akkor hacsak nem elektronikus számla alapból, a fentiek alapján a InvoiceAppearance=PAPER helyett, az UNKNOWN -ot célszerű használni? Vagyis azt mondom, mi biztosan nem fogjuk akkor a "PAPER"-t küldeni, mert nem tudhatom, hogy végül az vevő milyen formában kapta meg. (pdf nyomtató stb stb, mint használó, és mint fejlesztői oldalról is nézve).  

/OFF
Azért próbáltam ezt az egészet felhozni, - de ha nem szeretnétek vele foglalkozni azt is megértem-, mert a számlázó programok nagy része egy linket küld, ahonnan a számlát pdf formában tudod letölteni és nyomtatni, vagy simán emailben elküldik a számlát.. (online adatszolgáltatás InvoiceAppearance=PAPER),  
A tapasztalataim alapján a számlázásnál az emberek többségének fogalma sincs mi az e-számla és papír számla, és hogyan érkezett hozzájuk, ki nyomtatta ki... ezért célszerű lenne, ezt a témában valóban jártasnak ( mint Ti akik az Online számlát fejlesztitek) elővenni és a törvényalkotóknak megfogalmazni és végre pontot rakni egy sok éve tartó bizonytalanságnak, szűrkezónának, vagy nevezzük bárhogyan, mert létező elég jelentős tényező. A hash tárolással léptetek egyet az e-számla felé ami jó, de jelenleg tudomásom szerint nem megoldott, az ha valaki nem akar, vagy nem tud e-számlát kezelni, mert semmiféle apparátusa, tudása, hogy úgy archíválja az e-számlákat, ahogy a jogszabályok megkövetelnék. 
(de legtöbb esetben fogalma sincs, hogy amit kapott az egy e-számla!!!) 
De mégis szeretné kevesebb papír, boríték és egyéb teljesen felesleges költség nélkül megoldani az életét (járványról nem is beszélve). Korábban lényegesen egyszerűbb volt, mert minden e-számla volt, ami alá van írva digitálisan és hitelesítve volt, ezzel szemben ma... érzésem szerint léptünk egyet oldalra... ha nem vissza.

**Comment by HWKF** [comment]
Igazából a ráutaló magatartás megengedése a problémás helyzet:
_"Az elektronikus számla alkalmazásának feltétele: 
     a számla befogadó beleegyezése (ami nem csak formális lehet, hanem megvalósulhat például a kapott számlán szereplő ellenérték kifizetésével, hallgatólagos beleegyezés révén is)"_
2 feltétel van, de most csak az első a fontos, főleg a zárójeles rész!!!

**Comment by csaszko** [comment]
> Igazából a ráutaló magatartás megengedése a problémás helyzet:
> _"Az elektronikus számla alkalmazásának feltétele: - a számla befogadó beleegyezése (**ami nem csak formális lehet, hanem megvalósulhat például a kapott számlán szereplő ellenérték kifizetésével, hallgatólagos beleegyezés révén is**)"_
> 2 feltétel van, de most csak az első a fontos, főleg a zárójeles rész!!!

Főleg, hogy nem is tudja a befogadók nagy része, hogy NAV-nak milyen szuper állásfoglalása van ez ügyben...

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet. Ha van még további kérdés, nyissatok újat kérlek.
Üdv
