### ISSUE TITLE
[Q&A] lineVatRate "kijátszása" - warning vagy error járhatna érte esetleg?

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#416]
NTCA-tax-hez fordulnék ismét egy kérdéssel.

Belebotlottunk egyik ügyfelünknél egy olyan adatszolgáltatásba, ahol a partner nagyon kreatívan töltötte ki a lineVatRate részt:

`<lineVatRate>
<vatDomesticReverseCharge>false</vatDomesticReverseCharge>
</lineVatRate>`

A számlán látszik, hogy fordított ÁFÁ-s, de az adatszolgáltatásból ez csak erős képzelőerővel olvasható ki.

Annak az elvárásnak a partner szoftvere megfelelt, hogy a choice-ból egyet kiválasszon, de azt ügyesen false értékkel töltötte fel.

Lehet, hogy kellene egy olyan validáció is, hogy ha kiválaszt egyet, akkor arra csak true-t adhasson, vagy valami hasonló....

Meg tudnánk oldani mi is a dolgot, csak inkább azt szeretnénk, ha nem lenne eltérés a számlakép és az adatszolgáltatás közt, mert ha már nem lesz számlakép, akkor nem vállalnánk fel azt a felelősséget, hogy a szoftver mondta azt, hogy fordított ÁFA....

**Comment by NTCA-tax** [comment]
Köszönjük a jelzést, továbbítottam a warning/error validációért felelős kolléga számára. Amennyiben találnál még hasonló problémát, akkor örömmel várjuk :)

**Comment by omachtandras** [comment]
Még annyit tennék hozzá, hogy a choice-on belül több ilyen elem is van, ami ha kiválasztásra kerül, akkor true kell, hogy legyen mind 2.0, mind 3.0 alatt.

És, ha a felfedezői joggal élve lehet kérni, akkor azt szeretnénk, ha az ilyen hiba ERROR-ra dobná az adatszolgáltatást. :)

Befogadói oldalon akkor ér valamit az egész validáció, ha el sem jut az ilyen adatszolgáltatás.

Köszönöm!

**Comment by NTCA-developer** [comment]
@omachtandras A kérdéses számla ami felbukkant az 1.x-es verziójú, ha jól sejtem. Meg tudod erősíteni?

**Comment by omachtandras** [comment]
Sajnos nem tudom megerősíteni. A számla 07.03. keltezésű és 2.0-s verziójú.
Ha kell holnap tudok mondani tranzakció azonosítót is, de sajnos ez az éles rendszerben van, nem a tesztben.

**Comment by NTCA-supporter** [comment]
Szia @omachtandras !
A 3.0 XSD-ben ez ki lett kényszerítve fixed:true jelöléssel, így csak igaz értékekkel jöhetnek be a boolean áfamértékek.
Részlekerért lásd interfész dokumentáció.
Zárom az issuet, köszi a jó ötletet.
Üdv

**Comment by omachtandras** [comment]
Köszönjük szépen!
