### ISSUE TITLE
[DOC] SHA[2]-512

### ISSUE THREAD

**Issue by bcdel** [nav-gov-hu/Online-Invoice#417]
**A hibás dokumentum neve / Document name containing the error**
OSZ API 3.0.pdf

**A dokumentációs hiba leírása / Description of the documentation error**

Benzeztem. Kronikus Binaris diszkalkulia miatt osszekevertem ezt-azt.

**Oldalszám / Page  number**
  8. oldal (18 page) 3. ábra
a requestSignature is SHA-512 epdig SHA3-512 lenne a jó

**Comment by bcdel** [comment]
A 3. ábrán a requestSignature is SHA-512 epdig SHA3-512 lenne a jó

**Comment by NTCA-developer** [comment]
Szia @bcdel 

Igen, ezt mi is észrevettük már. Szerintem a cryptoType-ban is javítani fogjuk, mert lehetséges hogy data séma módosítás is kell. Addig hagyjuk nyitva amíg nem rendeződik.

Köszi szépen hogy jelezted!

**Comment by NTCA-supporter** [comment]
Javítottuk. SHA-512 lesz az elfogadott érték.
A doksit már utánahúztuk, az alkalmazás a hét második felében lesz elérhető teszt rendszeren.
Zárom az issuet, köszi a megjegyzést mégegyszer.
Üdv
