### ISSUE TITLE
[Q&A] vatAmountMismatch/reason mérete vs. dokumnetációs magyarázó szöveg

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#418]
A 3.0-s dokumentáció 116. és 117. oldalán a vatAmountMismatch/case értékkészletét nézve a REFUNDABLE_VAT és NONREFUNDABLE_VAT esetek leírása hosszabb, mint 100 karakter:
104 karakter: Az áfa felszámítása a 11. vagy 14. § alapján történt és az áfát a számla címzettjének meg kell térítenie
107 karakter: Az áfa felszámítása a 11. vagy 14. § alapján történt és az áfát a számla címzettjének nem kell megtérítenie

Mi azt terveztük, hogy a vatAmountMismatch/reason részbe felkínáljuk a törzsgazdának, hogy a NAV által megadott magyarázatot rögzítse, maximum módosítva azt, ha a jogértelmezése úgy kívánja.

A vatAmountMismatch/reason mérete azonban csak 100 karakter (common:SimpleText100NotBlankType).

Nem tudom, hogy másnak okoz-e ez gondot / problémát, de szívesen vennénk, ha vagy a méret kerülnek növelésre, vagy pedig a dokumentációban magyarázó rész rövidítésre oly módon, hogy azt az ügyfél felé beajánlásként használhassuk.

Köszönöm!

**Comment by KMGY100** [comment]
Fenti kérdéshez kapcsolom ezt is :
https://github.com/nav-gov-hu/Online-Invoice/issues/401

**Comment by omachtandras** [comment]
@KMGY100: köszönöm, nem voltam elég figyelmes.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezt zárom, a #424 ugyanerről szól.

Valószínűleg menni fog a bővítés, de még nincs róla döntés. Az említett issueban menni fog a visszajelzés.
Üdv
