### ISSUE TITLE
[Q&A] invoiceIssueDate kötelező?

### ISSUE THREAD

**Issue by bcdel** [nav-gov-hu/Online-Invoice#420]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
API3.0 doksi 74. oldal invoiceIssueDate Nem kötelezőnek van jelölve. 

Van olyan eset amikor tényleg nem kötelező, vagypedig hibás a doksi?
Az XSD-ben nem látok minoccurs=0 -t

**Comment by NTCA-supporter** [comment]
Köszi az észrevételt.
Kötelező, a doksit javítjuk majd.
Üdv

**Comment by NTCA-supporter** [comment]
Köszi a jelzést, javítottuk.
