### ISSUE TITLE
queryTransactionStatus üres response-t küld néhány számlánál

### ISSUE THREAD

**Issue by dupplak** [nav-gov-hu/Online-Invoice#421]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Üdv,
a múltheti NAV karbantartás után 2 számlát nem sikerült beküldeni, illetve sikerült beküldeni, de a státuszlekéréskor a következő rész teljesen hiányzik. 

`<processingResults>
<processingResult>
<index>1</index>
<invoiceStatus>DONE</invoiceStatus>
<compressedContentIndicator>false</compressedContentIndicator>
</processingResult>
<originalRequestVersion>2.0</originalRequestVersion>
</processingResults>`

2 számla kivételével az összes számlánál működik, ezért érthetetlen hogy mi lehet a hiba. A 2 számla a NAV-nál egyébként "DONE"-ként szerepel, csak ezt nem lehet lekérdezni. A konkrét Transaction ID-t is tudom küldeni ha valaki ez alapján utána tud nézni. Ha nem ez a jó kommunikációs út ehhez a problémához, kérjük küldjétek el, hogy hova fordulhatunk ilyen egyedi esetekkel!

Köszönöm!
_

**Comment by NTCA-supporter** [comment]
Szia!
Küldj kérlek transactionId-t. Van egy hasonló issue, amit már elküldtem a helpdesknek, ezt is hozzátenném mert szerintem ugyanaz a probléma forrása. Hátha így több info alapján jobban haladunk.
Köszönöm

**Comment by dupplak** [comment]
Üdv, Köszi a visszajelzést.
Két számláról lenne szó:
TransactionID-k: **34NRTTK2URRGELBC** (Küldési dátum/Idő 2020.10.07 / 20:30) és **34NRZAYBIVT5EJ2V** (Küldési dátum/Idő 2020.10.08 / 10:44) 

Köszönöm!
Üdv,

**Comment by NTCA-supporter** [comment]
Szia @dupplak !

Ez egy frontenden berögzített számla, amit olyan technikai felhasználóval próbálsz meg lekérdezni, akinek csak Saját számlák lekérdezése joga van. Mivel nem az adott technikai felhasználóval lett beküldve interfészen a számla, így ő nem kérdezheti le azt.
Javíts ki kérlek, ha valamit rosszul látunk.

Üdv

**Comment by NTCA-supporter** [comment]
Van még kérdés ezzel kapcsolatban?
Üdv

**Comment by dupplak** [comment]
Üdv,
egyelőre megkértük az ügyfelet, hogy a jogosultságot állítsa át, hogy minden számlát lekérdezhessen.
Még kérném egy kis türelmet, amíg válaszol.

Köszi, üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet. Ha van még kérdés nyissátok újra nyugodtan.
Üdv
