### ISSUE TITLE
[FEATURE] Termékek együttes törlése

### ISSUE THREAD

**Issue by hbalint2100** [nav-gov-hu/Online-Invoice#422]
Kedves Fejlesztők!

Javasolnám az online számla rendszer webes felületén a 'termékek együttes törlése' funkció hozzáadását, ami jelentősen megkönnyítené a felhasználók termék adatbázisának managelését. Egyesével lehetetlen egy nagy terméklistát letörölni.

Bízom benne, hogy javaslatom támogatásra talál.

**Comment by NTCA-developer** [comment]
Szia @hbalint2100 

Itt ugye igazából az Online számlázóról ("a kék") szól a gondolat, nem pedig a központi rendszerről, mert ott ilyen funkció nincs.

**Comment by hbalint2100** [comment]
Szia @NTCA-developer!
Igen, a "kék"-re gondoltam

**Comment by NTCA-developer** [comment]
Köszi, @NTCA-supporter megnézi, csak addig is pontosítani akartam az igényt.

**Comment by hbalint2100** [comment]
Köszönöm szépen!

**Comment by NTCA-supporter** [comment]
Szia @hbalint2100 !
Köszi a jelzést. Az igényt alapvetően mi is támogatjuk technikai oldalról. Továbbítottam az illetékeseknek, ha rábólintanak, akkor (nyilván alacsony prioritással) megvalósulhat.
Visszajelzésig mindenképp maradjon nyitva az issue.

Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok! 

A fejlesztés meg lesz valósítva, hamarosan teszt rendszeren elérhető lesz, majd utána élesen is.
Jelzek ha kikerült.

Üdv

**Comment by NTCA-supporter** [comment]
Szia @hbalint2100 !
A fejlesztés elkészült és élesen is van, zárom az issuet.
Észrevétel/kérdés esetén kérlek nyisd újra.
Köszönöm

**Comment by hbalint2100** [comment]
Köszönöm! 😊
