### ISSUE TITLE
[Q&A] Data példa vatAmountMismatch eseteire

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#423]
Szeretnénk látni a "Data példák" között az ÁFA tv. 11.§ és a 14.§, valamint a 17.§-ba tartozó példa bizonylatokat PDF-ben és XML-ben is. 
A kérdés a vevőre, illetve a vatAmountMismatch case esetekre vonatkozik: REFUNDABLE_VAT, NONREFUNDABLE_VAT illetve a NO_VAT_CHARGE.
A vevő lehet-e maga a számlakibocsátó, mert ezekben az esetekben erre szükség lehet, de eddig nem engedte meg a validáció. 
Eddig ilyen példák nem szerepeltek a korábban közzétett bizonylatok között.
Sokat segítene elképzelni az eddig sokféleképpen leképezett eseteket.

**Comment by NTCA-tax** [comment]
A vatAmountMismatch példa XML javaslatot köszönjük, továbbítom a megfelelő kolléga részére.

A vevő lehet maga a számlakibocsátó esetet nem értem. Az áfa törvény alapján ilyen eshetőség nincsen számla esetén. Ezt kifejtenéd, hogy mire gondoltál?

**Comment by Macskafarka** [comment]
@NTCA-tax  Kifejtem. A vatAmountMismatch/case alatt olyan értékeket lehet szerepeltetni, amely az ÁFA tv. 11.§, 14.§ és 17. szakasza alapján bizonylatoltak. Azonban ezeket szerintem nem számlával szokás bizonylatolni. 
Vagy fölöslegesek ezek az értékek a számla adatszolgáltatásba, vagy számlával kell bizonylatolni a sajátrezsis beruházásokat, ahol a cég maga a termékbeszerző, vagy a másik eset, amikor a  az adóalany a terméket vállalkozásából véglegesen kivonja. ezt sem számlával szokás bizonylatolni. 
A 14.§ (1)-ben "vagy általában, vállalkozásától idegen célok elérésére ingyenesen használja" - ezt számla adatszolgáltatásban egyáltalán hogyan kell elképzelni, ki a vevő?

**Comment by NTCA-tax** [comment]
Az Áfa törvény 159. § alapján számla nem állítható ki akkor, ha az eladó és a vevő is ugyanaz az adóalany. 

Mindegyik szakasz egyébként eléggé sok esetet tartalmaz, amikor van számlakiállítási kötelezettség és az eladó és vevő eltérő adóalany, vagy magánszemély a vevő.

**Comment by jozanesz** [comment]
> Az Áfa törvény 159. § alapján számla nem állítható ki akkor, ha az eladó és a vevő is ugyanaz az adóalany.

Ezt pontosan hogyan lehet kiérteni az idézett paragrafusból?

> 159. § (1) Az adóalany köteles - ha e törvény másként nem rendelkezik - a 2. § a) pontja szerinti termékértékesítéséről, szolgáltatásnyújtásáról a termék beszerzője, szolgáltatás igénybevevője részére, ha az az adóalanytól eltérő más személy vagy szervezet, számla kibocsátásáról gondoskodni.

Ugye attól, hogy nem köteles, még nincs is megtiltva. Mit nem találtam meg a szövegben az említett értelmezéshez?

Lásd https://www.origo.hu/gazdasag/20180813-kiallithate-sajat-maganak-szamlat-a-vallalkozas.html

**Comment by Macskafarka** [comment]
@jozanesz Tömegesen várhatók ilyen probblémák felbukkanása, mert a NAV adatzolgáltatáshoz elengedhetetlen az, hogy egzaktan valami le legyen szabályozva. Ide már nem elég a belemagyarázás, amit évtiizedekig gyakorlat volt. Olyan az eszöz, ami egyértelmű helyzeteket, egyértlelmű megfogalmazásokat  kíván meg.
Azt továbbra sem értem, hogyha az ÁFA tv. 11.§ (2) bek szerint áfa köteles a "Szintén ellenérték fejében teljesített szolgáltatásnyújtás, ha az **adóalany saját** vagy alkalmazottai magánszükségletének kielégítésére..."
Az áfa csak számlán szerepelhet, ha a "saját" szükségletei kielégítését áfás számlával kell bizonylatolni, akkor kell a számla online adatszolgáltatásba is. Akkor azonos a vevő és az eladó, amit állítólag tilt a 159.§, és elutasít az adatszolgáltatás is. 
22-es csapdája.

**Comment by NTCA-tax** [comment]
Számlának pedig csak két ELTÉRŐ adóalany között van értelmezési tartománya. Amennyiben az adóalany saját magának nyújt szolgáltatást vagy kvázi saját magának értékesít valamit, akkor arról számviteli bizonylatot kellene kiállítania, nem számlát. Az a kitétel sem igaz, hogy "áfa csak számlán szerepelhet". A számlától eltérő bizonylatok esetén is lehet áfa felszámítási kötelezettség, vagy éppen egy áfa könyvelés alapbizonylata nem feltétlenül egy számla.

Egyébként azon adatszolgáltatásoknál, amikor az eladó és a vevő megegyezik, akkor éppen a fenti okok miatt adunk vissza warningot.

**Comment by Macskafarka** [comment]
Nehéz ügy ez. Értem @NTCA-tax okfejtését, hogy a magának való értékesítésről számviteli bizonylatot kell kiállítani, de pl. nem minden áfa alany tartozik a számviteli tv. hatálya alá.  
Ha pedig áfát nem számlán számítanak fel, akkor nem fog bekerülni a számla adatszolgáltatásba, így a nem fog tudni a NAV sem ÁFA bevallást készíteni a számla adatszolgáltatásból. Megjegyzem már a Parlament előtt vannak a törvények tervezetei, amelyek tartalmazzák a NAV áfa tervezet készítését.

**Comment by NTCA-tax** [comment]
Az áfa bevallás tervezete sohasem fog tudni minden adózónál tökéletes lenni. Hosszan tudnám sorolni azokat az eseteket, amikor számla és nyugta adatokból nem fogjuk tudni eltalálni a "tökéletes" adóbevallást. A célunk maximum az lehet, hogy az adózók egy része számára próbálunk használható megoldást adni, a többi adózó számára pedig olyan szolgáltatásokat nyújtani, ami segíti őket az adóbevallásban.

De mindenesetre köszönöm, hogy együttérzel velünk ezzel kapcsolatban :)

**Comment by EnokhSys** [comment]
> @NTCA-tax Kifejtem. A vatAmountMismatch/case alatt olyan értékeket lehet szerepeltetni, amely az ÁFA tv. 11.§, 14.§ és 17. szakasza alapján bizonylatoltak. Azonban ezeket szerintem nem számlával szokás bizonylatolni.

Kedves @Macskafarka , olvasom a changelog-ban a "vatAmountMismatch"-ra vonatkozó részt, és mivel eddig nem nagyon találkoztam olyan esettel, amely beleesne az ÁFA tv. 11.§, 14.§ és 17. hatályába, tudnál esetleg mondani ezekre életből vett példákat?

**Comment by Macskafarka** [comment]
@EnokhSys Szerintem éppen azért nem találkoztál ilyennel, mert nem számlával szokták bizonylatolni., Azzal, hogy megjelentették a "vatAmountMismatch"-t a v3.0-ban, nagyon úgy tűnik, hogy megint jogot akar alkotni a NAV.
Ahogyan jogot alkotott azzal, amikor becsempészte a "nem lehet negatív" számla dolgot, és ezzel túllépte a hatáskörét.
Most is valami ilyesmire gyanakszom, hogy ki akarják találni, hogy számlával kell bizonylatolni.
Azzal is hatáskörét túllépve jogot alkotott a NAV, hogy ne lehetne saját magának számlát kiállítani, és ehhez alaptalanul hivatkoznak az ÁFA tv. 159.§-ra, mert az ezt kifejezetten nem tiltja, hogy a számlán az eladó és a vevő azonos legyen.
Akkor a példák:
1.	ÁFA tv. 14.§ (2) bek. alá tartozik, ha a valaki az alkalmazottai magánszükségletének kielégítésére másnak ingyenesen nyújt szolgáltatást. Pl. a cég bálázó gépével a dolgozó földjén elvégzi a bálázást.
2.	ÁFA tv. 14.§ (1) bek. alá tartozik, ha a cég számítógépét kölcsön adja valakinek, hogy azzal menjen egy e-sport versenyre.
3.	ÁFA tv. 14.§ (1) bek. alá tartozik, ha a vállalkozás a cég egyik ingatlanát egy rendezvényre díjmentesen odaadja. Pl. esküvőre, nyaralásra.
4.	ÁFA tv. 11.§ (1) bek. alá tartozik, ha a cég számítógépének tulajdonjogát ingyen adja oda valakinek, hogy azzal a gyereke részt vehessen távoktatásban.
5.	Szintén ide tartozik, ha a játékokat gyártó cég a késztermék játékokat ingyenesen odaadja egy óvodának.
6.	ÁFA tv. 11.§ (1) bek. alá tartozik, ha az állattenyésztéssel foglalkozó cég a tenyésztett állatot a dolgozói megvendégelésére használva ételként szolgálja fel.
7.	ÁFA tv. 11.§ (2) bek. ba) pontja alá tartozik, ha a kavicsbányával rendelkező, és kavics értékesítéssel foglalkozó cég a kibányászott kavicsot a cég területén útépítéshez használja fel.
8.	ÁFA tv. 11.§ (2) bek. a) pontja alá tartozik, ha a cég saját maga végzi el az cég újonnan épülő melléképületének falazási és burkolási, festési munkáit.
9.	ÁFA tv. 11.§ (2) bek. d) pontja alá tartozik, a szántóföldi növénytermesztéssel foglalkozó vállalkozás megszűnésekor készleten lévő műtrágya, talajbaktérium, valamint vetőmag, növényvédő, és gyomortó szerek. 

**Ezen példák kapcsán engem csakis a fizetendő áfa számlával való bizonylatolása és a számlakiállító adatszolgáltatása érdekel.** Mivel a v3.0-ban a számlakiállítói adatszolgáltatás kapcsán az ÁFA tv. 11., 14, és 17.§-ra hivatkoznak, ebből azt gondolom, hogy ezeket SZÁMLA-ként várják az adatszolgáltatásban.
Sok esetben nem ismert a vevő, vagy a számlakibocsátó egyben a vevő is, más esetben áfa keletkezik, de mivel ingyenes volt a termékértékesítés, vagy a szolgáltatás nyújtás, kérdés a számomra az, hogy néz ki egy ilyen számla.
Aki összeállította a v3.0-ban a specifikációt, annak bizonyára volt valami elképzelése arról, hogy is kell kinéznie a tv. 11.; 14.§ 17.§-ában megnevezett eseményről kiállított számlának.
Hagyjuk azt, hogy esetleg nem számlával kell bizonylatolni, mert a v3.0 kifejezetten csak a SZÁMLA adatszolgáltatásról szólva említi meg ezeket a gazdasági eseményeket, és engem is csak a számla érdekel. 
Ha számlával kell bizonylatolni a saját vállalkozás részére végzett szolgáltatásokat, és értékesítéseket, akkor az eladó és a vevő lehet azonos, ebben az esetben ki kell venni ennek az ellenőrzését és tiltását a v3.0-ból.
Ha ezeket a gazdasági eseményeket nem számlával kell bizonylatolni, akkor pedig a számla adatszolgáltatásból kell kivenni a "vatAmountMismatch"-t.
Jó lenne példát látni arról, hogy is képzeli el a NAV, illetve a PM ezen bizonylatolásokat számlával, vagy mire találta ki a "vatAmountMismatch"-t.

**Comment by EnokhSys** [comment]
Kedves @Macskafarka,

nagyon szépen köszönöm, fantasztikusan jól világossá tetted a példáiddal, hogy az ÁFA tv. ezen szakaszai milyen esetekre vonatkoznak, és rendkívül jól érthetően összefoglaltad a "vatAmountMismatch" problémáját, gratulálok!! Így már mindent értek, minden világos ezzel kapcsolatban.

Szerencsére aligha érint engem, ugyanakkor, ha végül közös nevezőre fogtok jutni a NAV-val, javaslom, hogy a példádat vegyék be a NAV dokumentációba is. Sőt, talán érdemes lenne a NAV dokumentáció végére egy "Törvényi értelmezést elősegítő példák" fejezetet nyitni, mert ez nagy segítséget jelentene a mindenkori programfejlesztőknek.

Még egy dologra reagálnék:

> Ahogyan jogot alkotott azzal, amikor becsempészte a "nem lehet negatív" számla dolgot, és ezzel túllépte a hatáskörét.  

Ehhe, igen. :-) Speciel én nem aggódom emiatt, mert meggyőződésem, hogy még a Parlament sem hozhat olyan törvényt, amely ezt megtiltaná. Egyelőre a NAV OnLine Számla rendszerében sincs ez tiltásként kezelve, és aligha hiszem, hogy ez lenne a céljuk, de ez már nem e topiknak a témája.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Itt van még kérdés?
A példaszámlák feltöltésre kerültek.
Üdv

**Comment by EnokhSys** [comment]
> Sziasztok!
> Itt van még kérdés?
> A példaszámlák feltöltésre kerültek.
> Üdv

Szia @NTCA-supporter és @NTCA-tax , szerintem ez is eléggé ki lett vesézve, ha @Macskafarka -nak nincs több észrevétele, részemről zárható. Külön köszönet azért, hogy az új dokumentáció 121-ik oldalától kezdődően, életből vett példákkal alátámasztott magyarázatokkal segítitek a CASE érték megfeleltetését.

**Comment by NTCA-tax** [comment]
@EnokhSys köszönjük a dicséretet a magyarázatokkal kapcsolatban. A GitHub-on olvasottak alapján ugrottunk neki, úgyhogy mi is köszönjük a jelzéseket 👍 
Ezt az issue-t lezárom, amennyiben felmerülne még kérdés a vatAmountMismatch-al kapcsolatban, akkor új issue-t nyissunk rá.

**Comment by EnokhSys** [comment]
@NTCA-tax nagyon szívesen.
