### ISSUE TITLE
[Q&A] 3.0 vatExemption/reason és vatOutOfScope/reason - impleText100NotBlankType - nem elég a karakterszám

### ISSUE THREAD

**Issue by WittmannWien** [nav-gov-hu/Online-Invoice#424]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Kedves Fejlesztők.
Hamarosan esedékes lesz a nemzetközi és harmadik országba történő áru vagy/és szolgáltatás értékesítésének online jelentése.
Ezekben az esetekben a számlákat a 3.0 leírás szerint  ÁFA megfelelőség szerint kategorizálni kell, majd a szöveges magyarázatát is mellékelni kell.
Erre adott 100 karakter a vatExemption/reason és vatOutOfScope/reason objektumokban.
Fontos gyakorlatilag is érteni, hogy ha egy nemzetközi számlát kiállítunk, akkor az indoklás kb sohasem csak egy nyelven történik, hanem általában két nyelven. Mivel értenie kell a vevőnek is, miről van szó, emiatt használnunk kell idegen nyelvet is a magyar mellett.
Így szerintem jogos lenne a felvetés, hogy ne csak 100 karakter álljon rendelkezésre. A tapasztalatom alapján 200 karakter már elégséges lenne.
Mekkora az esélye annak, hogy ez módosítható?

Előre is köszönöm.

**Comment by NTCA-developer** [comment]
Szia @WittmannWien 

Köszönjük a jelzést. Szerintem gond nélkül megoldható. Kérlek maradjon nyitva, visszajelzek!

**Comment by WittmannWien** [comment]
Köszönöm szépen.  Várom a visszajelzést.
Szép napot.

**Comment by NTCA-supporter** [comment]
Szia @WittmannWien !
A limit növelése 200-ra megtörtént a sémában.
Zárom az issuet, köszi az észrevételt.
Üdv
