### ISSUE TITLE
Módosító számla érvénytelenítése

### ISSUE THREAD

**Issue by ampista** [nav-gov-hu/Online-Invoice#425]
Sziasztok!

A következő probléma megoldásában kérném a segítségeteket.

Kiállítottam egy normál, eredeti számlát: SZLA01
Ehhez készítettem egy módosító számlát: SZLA02. 
Ezután érvénytelenítettem a módosító számlát: SZLA03

A módosító számlánál az OriginalInvoiceNumber a SZLA01, a ManageinvoiceOperation: MODIFY.

Az érvénytelenítő számlánál az OriginalInvoiceNumber szintén a SZLA01, hiszen mindig az eredeti számlára kell hivatkozni. A manageInvoiceOperation STORNO.

Kérdés, hogy a módosítást érvénytelenítő számla feladásánál helyes-e a STORNO operation megadása, vagy a módosítás érvénytelenítését is az eredeti számla módosításának kell tekinteni, és MODIFY operationnel kell feladni?

Köszönöm,
István

**Comment by lvitya586** [comment]
A probléma ott kezdődik, hogy módosító számlát nem lehet érvényteleníteni. Ha az eredeti állapotot szeretnéd visszaállítani, akkor egy másik módosítót kell kiállítani. Éppen ezért a kérdésedben a második eset a helyes.

**Comment by NTCA-supporter** [comment]
Szia @ampista !
Technikailag mindkét módon beküldhetnéd, de én is úgy gondolom, hogy a 2. mód a helyes.
Ha nincs több kérdés kérlek zárd az issuet.
Üdv

**Comment by jeezy1984** [comment]
Sziasztok!

A következő kérdésem lenne:
- egyik ügyfelünk kiállított egy kiállított egy számlát 509 sorszámmal (NAV befogadta).
- 509-et módosította az 529-es sorszámon módosító számlával (NAV befogadta)
- az 529-es módosító számlát sztornózta az 571-es sorszámú számlával (NAV befogadta)
- majd stornózta a 663-as sorszámon az 509-es (eredeti számlát). Ezt viszont már a NAV elutasította a következő hibával: "A módosító okirat sorszáma nem egyedi a számlaláncon belül".

Van rá hasonló topic a GitHub-on (github.com/nav-gov-hu/Online-Invoice/issues/425) de nincs rá érdemi válasz amivel le tudnám ezt kezelni.

Most akkor ezzel mit kéne kezdeni hogyan kéne kezelni?
- letiltom a jövőben hogy módosító / módosított számlát nem lehet sztornózni?
- vagy a módosító számlát ha sztornózom az érvényteleníti az erdeti számlát is és az eredeti és a módosító számla összes sorát fel kell tüntetni a sztornón, és ki kell ütni egy sztornóval két (módosító + eredeti) számlát úgy hogy az eredetire hivatkozok?

A válaszokat előre is köszönöm

**Comment by jeezy1984** [comment]
Bocsánat a Prog.hu-ról gyorsan bemásoltam mielőtt lezárnátok a topicot.

Annyira jutottunk hogy ezt nem lehet megengedni és hogy módosító számlát nem szabad engedni sztornózni. Rendben javítjuk a programot. A kérdés hogy hogyan kezeljem a jelenlegi helyzetet. 
 - technikai érvénytelenítés és újra beküldés modify-két az két sztornót teljes listával (annak ellenére hogy nem látszik most minden tétel a számlán?)
 - vagy kézi beküldése az utolsó 663-as számlának 
 - vagy be lehet küldeni a második sztornót is valahogy csak nem a 509-re kell hivatkozni?

A válaszokat előre is köszönöm
