### ISSUE TITLE
[DEV support] 3.0 tesztrendszer még nem teljesen működik?

### ISSUE THREAD

**Issue by csandazoltan** [nav-gov-hu/Online-Invoice#427]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[x] /tokenExchange
[x] /queryTaxpayer

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
DERP16025816413388546554176974

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Próbálok tesztelni a tesztrendszeren, hogy a fejléceket és a kapcsolati kulcsokat rendesen megcsináltam e.
V3 adószám infót probálok lekérdezni és csak annyit kapok válaszban, hogy OK.
V2 működik.

Valamit én csinálok rosszul, vagy a tesztrendszer még nem 100%?

*Egyéb tartalom / Additional content*

![image](https://user-images.githubusercontent.com/6756505/95843560-22590d80-0d48-11eb-92e6-6cb0dd372d09.png)

**Comment by NTCA-supporter** [comment]
Szia @csandazoltan !

A logban én azt látom, hogy ugyanúgy visszaadtuk a lekérdezett adózó adatait. Így szerintem nálad lesz a gond.

Ezt adtuk vissza xml-ben (a sw adatokat kiszedtem):

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:QueryTaxpayerResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">
	<header>
		<requestId>DERP16025816413388546554176974</requestId>
		<timestamp>2020-10-13T09:34:01.000Z</timestamp>
		<requestVersion>3.0</requestVersion>
		<headerVersion>1.0</headerVersion>
	</header>
	<result>
		<funcCode>OK</funcCode>
	</result>
	<ns2:software>
	</ns2:software>
	<ns2:infoDate>1999-08-18T22:00:00.000Z</ns2:infoDate>
	<ns2:taxpayerValidity>true</ns2:taxpayerValidity>
	<ns2:taxpayerData>
		<ns2:taxpayerName>VODAFONE MAGYARORSZÁG MOBIL TÁVKÖZLÉSI ZÁRTKÖRŰEN MŰKÖDŐ RÉSZVÉNYTÁRSASÁG</ns2:taxpayerName>
		<ns2:taxNumberDetail>
			<ns3:taxpayerId>11895927</ns3:taxpayerId>
			<ns3:vatCode>2</ns3:vatCode>
		</ns2:taxNumberDetail>
		<ns2:incorporation>ORGANIZATION</ns2:incorporation>
		<ns2:taxpayerAddressList>
			<ns2:taxpayerAddressItem>
				<ns2:taxpayerAddressType>HQ</ns2:taxpayerAddressType>
				<ns2:taxpayerAddress>
					<ns3:countryCode>HU</ns3:countryCode>
					<ns3:postalCode>1096</ns3:postalCode>
					<ns3:city>BUDAPEST</ns3:city>
					<ns3:streetName>LECHNER ÖDÖN</ns3:streetName>
					<ns3:publicPlaceCategory>FASOR</ns3:publicPlaceCategory>
					<ns3:number>6</ns3:number>
				</ns2:taxpayerAddress>
			</ns2:taxpayerAddressItem>
		</ns2:taxpayerAddressList>
	</ns2:taxpayerData>
</ns2:QueryTaxpayerResponse>`

**Comment by laladisc** [comment]
@csandazoltan szerintem a probléma abból fakad, hogy a 3.0-ás respons-okba a result node-tól lefele bekerült a namspace(ns2:) kb így:
`<?xml version="1.0" standalone="yes"?>
<ns2:TokenExchangeResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">
	<header>
		<requestId>K20_XY_AMD20201013123958</requestId>
		<timestamp>2020-10-13T10:39:58.000Z</timestamp>
		<requestVersion>3.0</requestVersion>
		<headerVersion>1.0</headerVersion>
	</header>
	<result>
		<funcCode>OK</funcCode>
	</result>
	<ns2:software>
		<ns2:softwareId>XXXXX</ns2:softwareId>
		<ns2:softwareName>XXXX</ns2:softwareName>
		<ns2:softwareOperation>LOCAL_SOFTWARE</ns2:softwareOperation>
		<ns2:softwareMainVersion>21.1.1</ns2:softwareMainVersion>
		<ns2:softwareDevName>XXXX</ns2:softwareDevName>
		<ns2:softwareDevContact>XXXXX</ns2:softwareDevContact>
		<ns2:softwareDevCountryCode>HU</ns2:softwareDevCountryCode>
		<ns2:softwareDevTaxNumber>XXXX</ns2:softwareDevTaxNumber>
	</ns2:software>
	<ns2:encodedExchangeToken>TOKEN</ns2:encodedExchangeToken>
	<ns2:tokenValidityFrom>2020-10-13T12:39:58.539+02:00</ns2:tokenValidityFrom>
	<ns2:tokenValidityTo>2020-10-13T12:44:58.539+02:00</ns2:tokenValidityTo>
</ns2:TokenExchangeResponse>`

**Comment by csandazoltan** [comment]
@laladisc Köszi, látom! és nem csak lefele 

A simple_xml-t próbálom rávenni, hogy betöltse a többi namespace-t is

**Comment by csandazoltan** [comment]
Igen, ez volt a baj, namespace-ekkel kell játszanom és minden adat meglesz.
