### ISSUE TITLE
Érvénytelen token kérés 3.0

### ISSUE THREAD

**Issue by NyBela** [nav-gov-hu/Online-Invoice#428]
Tisztelt Címzett!
Az alábbi kérdéssel fordulok Önökhöz.
Várom válaszukat, 
köszönöm.

Mi lehet az oka az "Érvénytelen kérés" üzenetnek?

* az összeállított kérés
* az adattartalom megegyezik a 2.0 adattartalmával. (login, Hash.stb...)
* a 2.0-val kezdettől fogva működik.

    <?xml version="1.0" encoding="UTF-8"?>
    <TokenExchangeRequest xmlns="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common">
		<common:header>
			<common:requestId>RID2020101310443788</common:requestId>
		  	<common:timestamp>2020-10-13T08:44:37.000Z</common:timestamp>
		  	<common:requestVersion>3.0</common:requestVersion>
		  	<common:headerVersion>1.0</common:headerVersion>
		</common:header>
		<common:user>
			<common:login>ugyanaz, mint a 2.0</common:login>
			<common:passwordHash cryptoType="SHA2-512">B428D12.stb..ugyanaz, mint a 2.0..7F94</common:passwordHash>
			<common:taxNumber>ugyanaz, mint a 2.0</common:taxNumber>
			<common:requestSignature cryptoType="SHA3-512">06CB745.stb..ugyanaz, mint a 2.0..183F</common:requestSignature>
		</common:user>
		<software>
			<softwareId>ugyanaz, mint a 2.0</softwareId>
			<softwareName>ugyanaz, mint a 2.0</softwareName>
			<softwareOperation>LOCAL_SOFTWARE</softwareOperation>
			<softwareMainVersion>ugyanaz, mint a 2.0</softwareMainVersion>
			<softwareDevName>ugyanaz, mint a 2.0</softwareDevName>
			<softwareDevContact>ugyanaz, mint a 2.0</softwareDevContact>
			<softwareDevCountryCode>HU</softwareDevCountryCode>
			<softwareDevTaxNumber>ugyanaz, mint a 2.0</softwareDevTaxNumber>
		</software>
	</TokenExchangeRequest>

* ahová küldöm:
https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3/tokenExchange

* a kapott válasz:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GeneralExceptionResponse 
xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" 
xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" 
xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" 
xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">
<funcCode>ERROR</funcCode>
<errorCode>INVALID_REQUEST</errorCode>
<message>Érvénytelen kérés!</message>
</GeneralExceptionResponse>

**Comment by NyBela** [comment]
Most látom, hogy sajnos az XML tag-ek nem látszanak, így nem értelmezhető a kérdésem...

**Comment by NyBela** [comment]
![ervenytelen_keres](https://user-images.githubusercontent.com/53435679/95856365-31e15200-0d5a-11eb-86bc-e24e97c94291.jpg)

**Comment by NTCA-supporter** [comment]
Szia!

Esetleg whitespace nincs az xml-ed elején?
Séma szerint validnak tűnik első ránézésre, de majd még nézem.
Üdv

**Comment by NyBela** [comment]
Szia!
Volt bent egy space...! Most csak tab van. Erre nem gondoltam.
Működik
köszönöm szépen.
