### ISSUE TITLE
[DOC] "Nem magánszemély és nem adóalany" hiányzik a doksiból

### ISSUE THREAD

**Issue by HWKF** [nav-gov-hu/Online-Invoice#429]
Az API 3.0 doksiban a 83. (93.) oldalon lévő táblázatból hiányzik ez a "Nem magánszemély és nem adóalany" / "Adószám nélküli jogi személy" / "Nem adóalany jogi személy" lehetőség kifejtése.

_Nem magánszemély és nem adóalany: név, cím kötelező a számlán és az adatszolgáltatásban, adószámuk nincsen._

Ez fontos lenne, mivel úgy tűnik, hogy adatszolgáltatásilag nem lehet megkülönböztetni az adószám nélküli a Harmadik országbeli adóalanytól (név, cím kötelező, a harmadik országbeli adószám nem kötelező, de ha szerepel a számlán, megvan a dedikált helye az adatszolgáltatásban is.)

A [384](https://github.com/nav-gov-hu/Online-Invoice/issues/384)-ben ezt a választ kaptuk:
_"A két vevői csoportot az adójogszabályok alapján nem lehet megkülönböztetni, hanem a számla adattartalma alapján. Mindkét csoportnál az elvárt jogszabályi minimum a név és cím feltüntetése a számlán és az adatszolgáltatásban, a harmadik országos adózónál az adószám opcionális, de attól még megadható."_

**Comment by NTCA-supporter** [comment]
Szia @HWKF !

A következő módosításba igyekszünk beletenni a kért infokat.

Addig maradjon nyitva az issue.
Köszi

**Comment by NTCA-supporter** [comment]
Javítottuk a sémát és a leírást is.
A doksit már utánahúztuk, az alkalmazás a hét második felében lesz elérhető teszt rendszeren.
Zárom az issuet, köszi a megjegyzést mégegyszer.
Üdv
