### ISSUE TITLE
[WARN] A WARN leírások legyen beszédesebbek, derüljön ki a szövegből, hogy mi a teendő

### ISSUE THREAD

**Issue by NTCA-developer** [nav-gov-hu/Online-Invoice#43]
https://github.com/nav-gov-hu/Online-Invoice/issues/36

**Comment by lakatoskevin** [comment]
Ezt az ötletet csak támogatni tudom. Jó lenne ha az adott számlaadatok tükrében azt is megmondaná, hogy milyen értéket várt, és az helyett mit kapott. Azt elismerem, hogy ez lehet, hogy túl sok elvárás, de mindenki életét megkönnyítené.
