### ISSUE TITLE
[DOC] thirdStateTaxId nem kotelezo

### ISSUE THREAD

**Issue by bcdel** [nav-gov-hu/Online-Invoice#430]
**A hibás dokumentum neve / Document name containing the error**
 (API doksi 3.0) 83. (93) oldalon, irva ez van:

**Oldalszám / Page number**
83. (93) oldalon, irva ez van

**A dokumentációs hiba leírása / Description of the documentation error**

    pont: .../communityVatNumber vagy .../thirdStateTaxId töltése kötelező.

A changelog, de még ez a issue is nem elég jogalap, hogy lehagyjam a harmadikországbeli adózó adószámát, ha a doksi szerint kötelező. Tehát ezt IS javitani kellene a doksiban.

**Comment by NTCA-supporter** [comment]
Szia @bcdel !

Pontosítsd kérlek kicsit, hogy mit szeretnél.
Vevő nem Magyarországon nyilvántartásba vett áfaalany (pl. más EUbeli vagy harmadik országbeli adóalany) -> 
customerInfo/customerVatData/communityVatNumber vagy
customerInfo/customerVatData/thirdStateTaxId töltése kötelező.

Itt mi a probléma?
Köszi

**Comment by bcdel** [comment]
A: 81. oldal (91 p) 

Harmadik orszagbeli fel harmadik orszagbeli adoszama a thirdStateTaxid elemben (...) szerepeltetheto, ha szerepel a szamlan

B: 83. oldal

..... vagy thirdStateTaxId töltése kötelező ....
(ez alapján úgy is értelmezhető, hogy ugyanúgy kötelező, mint a közösségi adószám)

C: 285++. oldal II.2 Kötelezőségek

nincs leírás a thirdStateTaxId -ről

D: #384 NTCA-tax commented Sep 28, 2020

Harmadik országbeli adóalany: név, cím kötelező, a harmadik országbeli adószám nem kötelező, de ha szerepel a számlán, megvan a dedikált helye az adatszolgáltatásban is.

----

A: Szerepeltethető ha szerelep a számlán <-> D: megvan a dedikált helye <-> B: kötelező 

A fenti 3 kifejezésből nem egyértelmű, hogy a lenti a,b,c esetekből akkor melyikre kell asszociálni.

Azt kellene tisztázni, hogy:

a: 3-dik ország adószáma kötelező (a számlán is); ekkor rossz az A,D leírás; pontos a B

b: 3-dik ország adószáma nem kötelező a számlán, de ha releváns, akkor kötelező az adatszolgáltatásban; ekkor pontatlan a B,D; nem rossz az A, de nem is pontos

c: 3-dik ország adószáma nem kötelező a számlán, adatszolgáltatni sem kötelező, de megvan a helye; ekkor rossz a B, és nem kristálytiszta az A,D

+1: a,b,c: minden esetben hiányzik a C részről a leírás

----

amit tehát javasolnék, egy tiszta döntést az a,b,c esetek közül és ennek a dokumentáció javítását/pótlását az A,B,C helyeken

**Comment by NTCA-supporter** [comment]
Javítottuk a sémát és a leírást, kérlek ellenőrizd.
Zárom az issuet, köszi a megjegyzést mégegyszer.
Üdv
