### ISSUE TITLE
[Q&A] ABORTED státuszú számlák

### ISSUE THREAD

**Issue by PalPalotai** [nav-gov-hu/Online-Invoice#431]
Sziasztok,
Mi a teendő akkor ha olyan számla került adminisztrációs, számla kiállítási hiba miatt beküldésre amelyet nem kell lejelenteni, és ABORTED státuszba került? Nem a számla beküldött adataiban van a hiba, a számla hibás kiállítása miatt került beküldésre. Jelenleg nem látunk a NAV felületén erre lehetőséget, pl. technikai érvénytelenítés is csak a sikeresen beküldött számlákra lehetséges, de a NAV felületén továbbra is megtalálható ezzel a státusszal. Az ilyen számlák státuszát lekérdeztük, beküldését a rendszerünkben leállítjuk, hogy ne történjenek felesleges próbálkozások, így nem is próbáljuk a továbbiakban újra beküldeni.
Köszönettel,
Üdv

**Comment by NTCA-supporter** [comment]
Szia @PalPalotai!

Technikai részrél az ilyen jellegű (ABORTED) beküldés olyan, mintha be sem küldted volna.
Szerintem nincs vele további teendő. Erősíts meg kérlek @NTCA-tax .

Köszi

**Comment by PalPalotai** [comment]
OK, Köszi

**Comment by NTCA-tax** [comment]
Megerősítem @NTCA-supporter válaszát, ezért zárom ezt az issue-t. Nem kell azzal foglalkozni, aminek egyébként sem kellett bekerülnie és be sem került az adatszolgáltató rendszerbe.
