### ISSUE TITLE
[Q&A] NetHuf 0 elfogadott-e Eu és export esetén?

### ISSUE THREAD

**Issue by mlnrdns** [nav-gov-hu/Online-Invoice#434]
Sziasztok,

nekem az a kérdésem, hogy a 3.0 fog-e hibajelzést küldeni, ha egy számlán a devizás nettó X, a forintos nettó pedig 0 és az árfolyam is 0 (EU, export)? Elvileg így kijön a matek, ugye ez a helyes eljárás ebben az esetben, nincs olyan elvárás a NAV részéről, hogy ilyen esetben is fel kell tüntetni egy 0-tól eltérő értéket?

**Comment by NTCA-tax** [comment]
Itt egy kicsit lassítanék az őszi adóscsomag miatt. A 10. számú melléklet módosítását nem tudom ki mennyire nézegeti, de pont ezt a kérdést érinti a 2. és 4. pont változása. Ott a jogszabály az adóalap meghatározásához használt árfolyamról vár el adatszolgáltatási kötelezettséget. Amennyiben a jogszabály ezzel a módosítási javaslattal elfogadásra kerül, akkor ezt a Ti oldalatokon és a mi oldalunkon is át kell gondolnunk és a szükséges módosításokat megtenni.

**Comment by mlnrdns** [comment]
@NTCA-tax azt néztük, hogy a melléklet általad említett pontjai a számlatömbös számlákra vonatkoznak, ott nincs utalás számlázórendszerek által kiállított számlákra

**Comment by NTCA-tax** [comment]
A 4. pont szól a számlázó programokról:

„4. A számlázási funkcióval rendelkező programmal kiállított számla, számlával egy tekintet alá eső okirat esetében az adóalany külön jogszabályban meghatározott elektronikus módon teljesít adatszolgáltatást a számla, számlával egy tekintet alá eső okirat e törvény szerinti adattartalmáról, továbbá az adó alapjának meghatározásakor használt pénznemről, külföldi pénznem  esetén a forintra átszámított  adatokról  és  a forintra  történő átszámításhoz alkalmazott, 80. § és 80/A. § szerinti árfolyamról. Nem adóalany természetes személy részére kibocsátott számla, számlával egy tekintet alá eső okirat esetében az adatszolgáltatás nem terjed ki a termék beszerzőjének, szolgáltatás igénybevevőjének nevére és címére.”

**Comment by mlnrdns** [comment]
Köszönöm, akkor izgatottan várjuk. :)
