### ISSUE TITLE
[Q&A] Miért warning a negatív nettó végösszegű számla, amikor a bruttó végösszeg nulla?

### ISSUE THREAD

**Issue by HWKF** [nav-gov-hu/Online-Invoice#436]
Rendszeresen kapják a partnereink, hogy a warning megjegyzést , hogy az "Eredeti (CREATE) számla nettó összege nem lehet negatív" (INCORRECT_SUMMARY_DATA_INVOICE_NET_AMOUNT).
Olyan számlák esetén áll ez elő, ahol a bruttó végösszeg 0 és előlegfelhasználás történt. Az előleg számlán 5%-os előleg számláztak. A végszámlában viszont volt még 18% vagy 27%-os tétel. Emiatt az összesítés "eredménye"képpen előáll, hogy a nettó végösszeg negatív, azzal egyenértékű plusz ÁFA végösszeg szerepel. A bruttó meg marad 0.
Ez OSZv2 estén úgy tűnik független attól, hogy az előlegfelhasználás tétele a végszámla adatszolgáltatásában meg van-e jelölve előlegnek vagy sem.
OSZ v3 alatt, ha feltöltjük az előlegszámla adatokat, akkor is érkezni fog a warning? Vagy várható, hogy csak akkor legyen warning, ha nincs előlegként megjelölve az előlegfelhasználás tétele? Ha igen, akkor esetleg várható ez irányban már változás v2 alatt is?

**Comment by Macskafarka** [comment]
A problémába mi is belefutottunk. Úgy lehet ezen átlendülni, hogy egészen más értelmezéssel kell hozzáállni.
Ha az előleg 5%-os volt, akkor azt szerintem csak 5%-os végssámla sorba szabad felhasználni. Tehát a végszámla áfa kulcsonként sem mehet negatívba.
Ez abból vezethető le, hogy az előleget konkrét valamire kapod, tehát ismert a majdani végszámlán szereplő termék és így ismert annak az áfa kulcsa, ezért ennek megfelelően kell a bankszámlára érkezett összegről előleg számlát készíteni.
A gyakorlatban előforduló, általad is jelzett esetet úgy képzeli el a NAV, hogy ebben az esetben a végszámla kiállításakor derült ki, hogy az előlegszámla módosításra szorul, azaz a végszámla előtt az előlegszámlát a végszámla keltezési dátumával kiállított  módosító okirattal módosítsák meg akként, hogy a végszámla által megkívánt áfa kulcsokat tartalmazza.  A módosítás után már be tudod számítani a végszámlába több soron úgy, hogy nem lesz negatív a nettó összeged az áfa kulcsonkénti összesítőben. 
Ugyanígy kellhet eljárni, ha az előlegszámla után megváltozik az előlegezett termék áfa kulcsa pl. törvényi változás esetén (hacsak nincsenek átmeneti szabályok erre az esetre). 
Ha az előlegszámla belföldi devizás volt, akkor a módosító számla árfolyamának is az eredeti (CREATE) előlegszámla árfolyamával egyezőnek kell lennie, függetlenül attól, hogy a módosító számla későbbi, akár hónapokkal későbbi keltezésű.
Tudom, hogy elég nyakatekert ez így, de kb. így lehet levezetni a NAV elvárását.
Ceterum censeo: mi a világ legbonyolultabb áfa rendszerét működtetjük. 
De várjuk meg @NTCA-tax véleményét.

**Comment by NTCA-tax** [comment]
@Macskafarka leírása alapvetően a helyes irányt tartalmazza, bár nem annyira nyakatekert. Az előleget egy konkrét termékértékestésre vagy szolgáltatás nyújtásra fizeti a vevő. Így a termék/szolgáltatás adókulcsa már az előleg kiállításakor ismert, egyébként nem előlegről beszélnénk... Így az előleg-végszámla kapcsolatban nem lehetne adókulcs különbözet. Persze hibázni lehet, de ekkor az előleg számlát kellene módosítani, hogy mégsem 5%-os, hanem 27%-os az adókulcs. A jogszabályi változásokat szerintem figyelmen kívül hagyhatjuk, mivel egyrészt erre az átmeneti szabályok szoktak választ adni, másrészt nem látszik olyan szabályozás változás, ami az adókulcsokat érintené.

A negatív összegű számla globálisan kap warningot, itt nem vizsgáljuk, hogy szerepel-e benne előleg beszámítás vagy sem. Tehát független a számla tételsoraitól, amennyiben a számla végösszege negatív, akkor jelez a rendszer, hogy ez nem helyes.

**Comment by NTCA-tax** [comment]
Ezt az issue-t most lezárom, ha felmerülne további kérdés, akkor egy újban vitassuk meg.
