### ISSUE TITLE
[DOC] privatePersonIndicator - Áfa törvény szerint kötelező ?

### ISSUE THREAD

**Issue by hamvasgy** [nav-gov-hu/Online-Invoice#437]
**A hibás dokumentum neve / Document name containing the error**
Online Szamla_interfesz specifikáció_HU_v3.0.pdf

**Oldalszám / Page number**
286. oldal

**A dokumentációs hiba leírása / Description of the documentation error**
A "privatePersonIndicator" elemnévnél az "Áfa törvény szerint kötelező" oszlopban "Igen" van.
Nem találjuk az Áfa törvényben, hogy hol szerepel az, hogy a számlán fel kell tüntetni a vevő "Magánszemély" mivoltát.
Kérjük a hivatkozást megadni (akár itt az issue-ban), vagy a jelzett helyen a dokumentáció javítását "Nem" értékre.

**Comment by NTCA-supporter** [comment]
Szia @hamvasgy !
Valószínűleg igazad van, és csak elírás történt.
Utánakérdezek és visszajelzek.

Üdv

**Comment by NTCA-supporter** [comment]
Nem kötelező Áfa tv. szerint, javítottuk.
