### ISSUE TITLE
[Q&A] 2.8 Közmű elszámoló számlájának adatszolgáltatása

### ISSUE THREAD

**Issue by jozanesz** [nav-gov-hu/Online-Invoice#439]
A #299  sajnos idejekorán lezárult, és nem kaptam választ a kérdéseimre.

> A közmű szolgáltatókra vonatkozó iparági szabályozás alapján egy olyan elszámolószámlát kell kibocsátaniuk, mely tartalmaz**hat** adott időszaki teljesítésen kívül korábbi időszaki számlák módosításait is. Adatszolgáltatás tekintetében az alapvető probléma, hogy egy számla nem lehet egyszerre alapszámla és módosító számla is. Az adatszolgáltatás során **ezeket a számlákat** MODIFY operációval, batchInvoice számlaként **kell** beküldeni

* Mint említettem, "egy elszámoló számla az 0 vagy 1 CREATE és 0 vagy több MODIFY invoice összessége". Ha csak egy CREATE, azaz nincs részszámla-jóváírás (pl. ez az ügyfél első számlája), akkor ugyanúgy kellene beküldeni, mint bármely más normál számlát, vagy akkor is az e fejezetben leírtak szerint, vagy mindegy? Az időközben megjelent specifikáció fent idézett részéből nem világos, hogy az _ezeket a számlákat_  kifejezés az összes elszámoló számlára vonatkozik, vagy csak a módosításokat tartalmazókra.

> A rendszernek egy adatszolgáltatási kérés során csak egyetlen batchInvoice csomópontot tartalmazó kérés adható át.

*  Ennek azért van jelentősége, mert ha így marad, jelentősen nőni fog a kérések száma: rengeteg magánszemély rengeteg elszámoló számlája egyesével lesz beküldve. Ráadásul most hirtelen be lesz vezetve egy további korlátozás (#435). Ha jól értem, így az elvi maximum valamivel kevesebb, mint 60 számla státuszának lekérdezése lenne percenként, ha csak egy cég számláit küldenénk be egy időben egy ip-címről. Jól értem?

>   "A közszolgáltatói elszámolószámlákra vonatkozó speciális szabályok miatt a sémába bekerült egy új, utilitySettlementIndicator nevű jelölő. Ha a tag értéke true, akkor az előzmény nélküli módosítások (a modifyWithoutMaster tag értéke true) feldolgozása akkor is megtörténik, ha egyébként a hivatkozott alapszámla a rendszerben már létezik."

* Az új információk alapján ez továbbra sem érthető: utilitySettlementIndicator=true csak a "számla" részben ("adott időszaki teljesítés") lesz, amikor "originalInvoiceNumber az aktuálisan beküldött elszámoló számla sorszáma", így hogyan fordulhatna elő, hogy "a hivatkozott alapszámla a rendszerben már létezik"? És milyen "előzmény nélküli módosítások", amikor ez pont nem a módosító részben fordul elő?

**Comment by NTCA-supporter** [comment]
Szia @jozanesz !

Összefoglalom én hogy látom technikai oldalról, és ha valami nem helyes/pontos, akkor @NTCA-tax majd helyesbít.

Csak akkor van szükség szerintem erre a "trükkös" CREATE és MODIFY egyben beküldésre, ha erre valóban szükség van, tehát van az adott számlán alapszámla és módosítás is. Ha csak az egyik típus szerepel, akkor ugyanúgy beküldeni, mint alapesetben.

A hivatkozott issueban jeleztük, hogy egylőre nem lesz korlátozás, az viszont marad, hogy egy kérésben 1 batchInvoice szerepelhet.

A 3. részt gondolom a changelogból idézted, ezt majd erősítsd meg kérlek. Valóban kissé félrevezető. Jól látod, a "CREATE" jellegű számlánál kell ezt (utilitySettlementIndicator=true ) jelezned , modifyWithoutMaster = true jelzéssel. Ezáltal azt úszod meg, hogy nem kapsz warningot, hogy az originalInvoiceNumber-ben a saját számla sorszámra hivatkozol.
Részletesebb leírás: 3.0-ás interfész doksi, 2.8 fejezet.
https://onlineszamla.nav.gov.hu/files/container/download/Online%20Szamla_interfesz%20specifik%C3%A1ci%C3%B3_HU_v3.0.pdf

További kérdés esetén állunk rendelkezésre.
Üdv

**Comment by jozanesz** [comment]
Kösz. 
* Várom a mielőbbi megerősítést, és jó lenne a *szerintem*nél erősebb dokumentáció, lehetőleg a specifikációban. Mert ugye én is pont arról a fejezetről neveztem el az issue-t, amelyre hivatkozol. Ennek jelentős fejlesztési-tesztelési vonzata van nálunk, és elvileg január 1-től működnie kell (a türelmi időszak kérdése még tisztázatlan).

* A korlátozásban az _egyelőre_ a nyugtalanító. Több nagy cég sok-sok ezer számlájáról van szó. Már érdeklődtem az ip-cím tartományunk bővítéséről, de ehhez is fejlesztés kell, nem lehet hipp-hopp bevezetni, és semmiképpen sem szeretném, ha egymásnak keresztbe tennénk. Inkább együtt kellene működni, részletesebb ajánlásokat kiadni. Pl. az egyesével beküldött batchInvoice elszámoló számlák mellett külön csomagoljuk-e 100-asával a hagyományosan is beküldhetőket, vagy erre nincs szükség, lehet a számlákat keletkezési sorrendben beküldni. Pl. 1 batchInvoice, 3 normál, 1 batchInvoice , 1 normál, 1 batchInvoice , stb.

* Az idézet a changelogból van, és innen: https://github.com/nav-gov-hu/Online-Invoice/issues/299#issuecomment-688761002

**Comment by NTCA-tax** [comment]
A dokumentációt újból elolvastam, de számomra (és nagy hiba, ha csak számomra) egyértelmű. Amennyiben az elszámoló számla korábbi időszaknak a módosításáról szól, akkor kell az általad is idézett fejezetben levezetett módon az adatszolgáltatást teljesíteni. Amennyiben nincs előző időszak módosítása, akkor nem áll fenn a számla-módosító számla hibrid, mivel számláról beszélünk. Így azokat CREATE-tel kell beküldeni.

**Comment by jozanesz** [comment]
Bizony nagy baj, hogy azoknak nem egyértelműek a szabályok, akiknek ilyen számlákat elő kell állítaniuk. És nagyon kevés idő maradt ennek a tisztázására és a rendszerek új elvárások szerinti átalakítására. A [2013. évi CLXXXVIII. törvény](http://njt.hu/cgi_bin/njt_doc.cgi?docid=165033.376088)t az „érthető és átlátható számlakép megteremtése érdekében” alkották saját állítása szerint. Csak meg kell nézni az előírt számlaképeket, és rögtön látszik, hogy egyáltalán nem áll összhangban a NAV (és az áfatörvény) által elvárt szerkezettel. („Az elszámoló számla harmadik oldala” kifejezésből is látszik, hogy tömörre, „söralátétnek” tervezték.) Az adatszolgáltatásban csak olyan adat szerepelhet, amely a számlán is. Hogyan lehetne ezeket összhangba hozni? Mért fogyasztás esetén egy szolgáltató 1-3 havonta részszámlákat bocsáthat ki. Ezek gyakorlatilag becsült fogyasztásokat és egyéb díjakat tartalmaznak. Ha jól értem az elnagyolt 2.8-as fejezetet, ezeket a becsléseket korrigálni kell a későbbi, tipikusan évenkénti leolvasás alapján (de az időszak ennél gyakran rövidebb lehet, mert pl. fogyasztói adatközlés történt az éves leolvasást követően). Ennek mi lenne a módja? A leolvasás alapján a teljes időszakra számított fogyasztást el kell osztani a részszámlákban elszámolt és az aktuális fogyasztási időszakra? Hogy jelenne ez meg a számlaképen, amely tejesen más struktúrát követel?
Pl. 
* Részszámlákban elszámolt energiadíj
Itt eddig 1 db negatív nettó és bruttó érték szerepelt. Ez alatt ezentúl mérőnként és díjkategóriánként (pl. lakossági A1 kedv. és lakossági A1 normál) legfeljebb 11 havi részszámla-tételt kellene megjeleníteni?
Minden sorban meg kell írni a hozzá tartozó részszámla 1-11. vagy az áfatörvény szerint sorszámát az azonosíthatóság érdekében? Hogy nézne ez ki?
Ezekkel valahogyan (de hogyan?) tételenként párosítva, feljebb meg kellene jeleníteni a korrigált tételeket? Hogyan lesz egyértelmű, hogy mely tételek módosítóak, és azok melyik eredeti számlához tartoznak?
* Részszámlákban elszámolt rendszerhasználati díjak
Az energiadíjtól eltérően ezeket valószínűleg nem kell korrigálni, tehát itt megúszható a részletezés, ugye?
* Az elszámoló számlában elszámolt részszámlák sorszáma és a számla végösszege
**Sorszám:    Számla végösszeg (Ft)**
Ez micsoda? Az eredeti végösszeg vagy a korrigált?

Ha a szolgáltató nem tudja az éves leolvasást elvégezni, becsült számát kell kiállítania. Ez nagyjából megegyezik az imént tárgyalt számlaképpel. De mi történik, ha a későbbi leolvasás során a becsült mérőállásnál kisebbet állapítanak meg? A elszámoló számlát módosító okirat a számlaképtörvény szerinti elszámoló számlának számít? Hogyan korrigálja az új elszámoló számla az előzőt? A _Részszámlákban elszámolt_ díjak ugye itt már az előzőleg korrigáltakat tartalmazzák összesítve és tételesen? Hogy jelenik meg az előző elszámoló számla legutóbbi elszámolási időszakára vonatkozó tételek korrigálása? Hol lesz jelölve a korrigált számlának a száma?

**Comment by littlecutieorion** [comment]
Szia @jozanesz!

Új vagyok itt, érdekel ez a téma. 
Eddig a gyakorlat az az elszámoló számláknál, hogy a kibocsátott 12 rész számlát összevontan írtuk jóvá szolgáltatásonként. (illetve a kezdet kezdetén áranként összevonva is). 

Ezt a MODIFY részt nem fogom fel. Miért nem lehet nemes egyszerűséggel CREATE -ként felküldeni úgy, ahogyan sorról-sorra szerepel a számlán?

A negatív előjelű számla is számtalan esetben előfordul. Ez az Élet. 
De nem akarlak ismételni, nekem is pont ezek a kételyeim, amiket ecseteltél itt és a #299-ben is.

@NTCA-supporter !
Ha fel lenne téve egy konkrét példa .XML-ben, amiben egy elszámoló számla az előzőleg kibocsátott rész-számláival együtt le van vezetve, nagyon sokat segítene minden közmű számlázó-rendszer fejlesztőjének.

**Comment by Macskafarka** [comment]
A NAV részéről fel kellene hagyni a negatív lánckezdő számla kifogásolásával.
Jogilag semmi, de semmi NEM tiltja!
A való életet kell elfogadni, és nem önkényesen szabályokat felállítani.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Itt van még kérdés?
Üdv

**Comment by NTCA-tax** [comment]
Az interfész dokumentációban a közmű elszámoló számlával kapcsolatos kérdéseket próbáltuk teljesen körbejárni, valamint példán is levezetni. Amennyiben a dokumentáció alapján még valami kérdés felmerülne, akkor azt új issue-ban beszéljük meg.

**Comment by jozanesz** [comment]
Nem válaszolták meg a második issue-ban sem a kérdéseimet, Az új dokumentáció sem. Sajnos a szabadságom alatt nem tudom folyamatosan ezt figyelni, de tegnap reggel még nem volt itt, semmi másfél hónap hallgatás után, ma meg már le van zárva. Ez nem korrekt kommunikáció. Ha holnap reggelre nem lesz visszanyitva, akkor átmásolom a kérdéseimet másodszor is egy új issue-ba. :(

**Comment by NTCA-tax** [comment]
Igen, kérlek nyissál új issue-t, így számomra is egyértelműbb melyek a dokumentáció alapján sem megválaszolható kérdéseid. De ezzel zártam le ezt az issue-t, hogy ami még mindig kérdéses, arra nyissunk egy újat...

**Comment by jozanesz** [comment]
Meg fogom nyitni az újat, de ha továbbra is specifikáción keresztül válaszoltok hetek-hónapok múlva a feltett kérdések megválaszolása helyett, mint ennél és az előzmény issue-nál, akkor még évekig elbeszélhetünk egymás mellett. :(
