### ISSUE TITLE
[Q&A] A V3-as queryTransactionList operáció visszamenőlegesen majd visszaadná a V2-ben FINISHED állapotban lévő tranzakciók státuszát?

### ISSUE THREAD

**Issue by HWKF** [nav-gov-hu/Online-Invoice#440]
[295](https://github.com/nav-gov-hu/Online-Invoice/issues/295)
Gondolom a 295 issueban felmerült problémához hasonló esetekben lenne majd fontos szerepe a queryTransactionList operáció által V3-ban a transaction/requestStatus-ban visszaadott státuszainak, különösen a FINISHED (Feldolgozva), NOTIFIED (Lekérdezve) értékeknek.
Most pont azok a problémásak, melyek a FINISHED státuszban vannak. Pedig mi úgy tudjuk, hogy DONE, mert azt "hittük", hogy lekérdeztük.
Ha az élesben megjelenik a V3, akkor ezek a tranzakciók visszafelé még lekérdezhetőek és visszakapnánk a FINISHED státuszt? (már ha addig nem kérdezzük le azokat)

**Comment by NTCA-supporter** [comment]
Szia @HWKF !

Igen, lekérdezhetőek lesznek, és a megfelelő státuszt fogod visszakapni.
Üdv

**Comment by NTCA-supporter** [comment]
Ezzel kapcsolatban van még kérdés?
Köszi

**Comment by HWKF** [comment]
Ha volt le nem kérdezett FINISHED tranzakció, majd le lett kérdezve, akkor a lekérdezés után van-e valamilyen lehetőség annak kimutatására, hogy a fenn állt korábban a probléma?

**Comment by NTCA-supporter** [comment]
Röviden: nincs.
A válaszban mindig aktuális állapotot adunk vissza, sosem historikusat.
Üdv

**Comment by HWKF** [comment]
Csak azért kérdeztem, mert a Használati statisztika is csak az aktuális állapotokat hozza.
