### ISSUE TITLE
queryInvoiceChainDigest probléma

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#441]
A queryInvoiceChainDigest lassú, és nem a GeneralErrorResponse-nak megfelelő xml-t ad vissza hiba esetén.

A probléma nem fix, de már jóval 50% felett van a sikertelen kérések aránya. Az utóbbi 24 órában alig volt sikeres kiszolgálása a kérésnek.

Válasz:

< html>< body>< h1>504 Gateway Time-out< /h1>
The server didn't respond in time.
< /body>< /html >

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !
Köszi a jelzést.
A 3.0 tesztre adása volt mostanában a fő prioritásunk, de már foglalkozunk a problémával.
Amíg nem megy ki legalább teszt környezetig az optimalizálás, addig maradhat nyitva az issue, hogy ezen témakörben ne keletkezzen új.

Köszi

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !
Fennáll még a probléma?
Üdv

**Comment by EPluribusUnum** [comment]
11.16. volt az utolsó ilyen hiba a logok alapján. Zárom a jegyet.
