### ISSUE TITLE
[Q&A] Csoportos adószám kérdés újratöltve, hibás warning

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#442]
Amennyiben a kiállító csoportos adóalany, akkor a számlán adószámként az 5-ös adószámát (pontosabban CSASZ) tünteti fel. A számlán nincs több adószám feltüntetve, az ÁFA törvény nem is írja elő kötelezően, hogy emellett tüntesse fel a 4-es adószámát is. 

groupMemberTaxNumber=sose kerül kitöltésre...
supplierTaxNumber=XXXXXXXX-5-XX
(doksi 262. oldal, supplierTaxNumber= Belföldi adószám, amely alatt a számlán szereplő termékértékesítés vagy szolgáltatásnyújtás történt. Lehet csoportazonosító szám is)

A számla adatszolgáltatása sikeres lesz, de WARN üzenet jön, miszerint:
"INCORRECT_VAT_CODE_SUPPLIER_GROUPMEMBER_MISSING", Tehát figyelmeztet, ha az eladó áfacsoport tagja és a csoporttag adószáma nincs megadva.

A 4-es adószám valóban nincs kitöltve az adatszolgáltatásban, mivel a számlán sem lett megadva, mivel az ÁFA törvény szerint sem kötelező. Szerintem emiatt a WARN nem jogos! Az ügyfelek viszont minket zaklatnak, hogy miért kap üzenetet.

Javaslatom, hogy legyen kivezetve ez a WARN üzenet, vagy kérném a pontos ÁFA törvény hivatkozást, ami előírja, hogy a csoportos adóalanynak egyszerre fel kell tüntetnie a számlán a saját adószámát és a csoportos adószámát is! Ha ennek nincs jogszabályi alapja, akkor a WARN-t meg kell szüntetni!

**Comment by PalPalotai** [comment]
@nbeeps2: 23/2014. (VI. 30.) NGM rendelet
a számla és a nyugta adóigazgatási azonosításáról, valamint az elektronikus formában megőrzött számlák adóhatósági ellenőrzéséről
13/A. § *  (1) A számlázó programnak a gép-gép interfész használatához szükséges azonosító adatok megküldése mellett a kiállított számla, számlával egy tekintet alá eső okirat legalább Áfa tv. szerinti kötelező adattartalmát a számla, számlával egy tekintet alá eső okirat kiállításakor azonnal, XML-formátumban, az állami adó- és vámhatóság közleményében meghatározott módon és adatszerkezetben, elektronikus úton továbbítania kell az állami adó- és vámhatóság részére.

Azaz a NAV mondja meg mi legyen az adattartalma és különböző előadásokon is elhangzott, hogy lehetnek olyan adatok amelyek ÁFA tv. szerint nem kötelezőek, de adatszolgáltatás miatt viszont igen.

**Comment by nbeeps2** [comment]
@PalPalotai , Nem tudom feltüntetni az adatszolgáltatásban, ha a számlán nem szerepel. A számlán pedig csak 1 adószámot kell feltüntetni!

**Comment by nbeeps2** [comment]
@PalPalotai " lehetnek olyan adatok amelyek ÁFA tv. szerint nem kötelezőek, de adatszolgáltatás miatt viszont igen." Ez a technikai mezőkre vonatkozott, mint pl. a modifywithoutmaster, modificationindex, invoicecategory, stb.

**Comment by lvitya586** [comment]
@PalPalotai a saját magad által idézett paragrafust is rosszul értelmezted. A hangsúly a " legalább Áfa tv. szerinti kötelező adattartalmát" mondatrészen van, tehát mivel ez nem tartozik bele a fenti kitételbe és az interfész doksi szerint sem kötelező, ezért ezt nem kell küldeni.

**Comment by PalPalotai** [comment]
@nbeeps2 @lvitya586 : Az annyira nem elképzelhető és ezek szerint elő sem fordult nálatok, hogy az ügyfeletek vevője ( többnyire multi) azt mondta nem hajlandó befogadni a számlát ha mind a saját és mind a csoportazonosító adószám nem szerepel rajta? Hivatkozhattok akármire, mehettek bíróságra, perre, náluk ez a policy és kész. Mindezt csak azért mert nehogy az ügyfeletek lásson egy WARN üzenetet, ugyanakkor meg nem tudod az ügyfél igényét kielégíteni. Akkor nem lesz probléma a piac vesztésetek, mert az ügyfeled azt mondja ha a Te programod ezt nem tudja akkor "dob" és mást fog a számlázásra használni ami erre képes? Itt most egyáltalán nem a számla lejelentésről van szó, hanem arról, hogy a számlázó rendszered képes e megjeleníteni a normál és a csoportos adószámot vagy sem. Nálunk egyáltalán nem egyedi ez az igény, teljesen természetes több ügyfelünk esetében. De ezt már nagyon nem itt kellene megbeszélni, ez nagyon nem a NAV-ra tartozik, ők majd eldöntik hogy kell e a WARN vagy sem, saját véleményem szerint nem gond ha van WARN, magyarázzátok meg az ügyfélnek mit jelent és majd edönti hogy használja a Te programod vagy lát benne kockázatot és "lecserél".

**Comment by lvitya586** [comment]
> 
> 
> De ezt már nagyon nem itt kellene megbeszélni, ez nagyon nem a NAV-ra tartozik, ők majd eldöntik hogy kell e a WARN vagy sem, saját véleményem szerint nem gond ha van WARN, magyarázzátok meg az ügyfélnek mit jelent és majd edönti hogy használja a Te programod vagy lát benne kockázatot és "lecserél".

Már ne haragudj, de te írod, hogy nem itt kéne megbeszélni, és ehhez képest ideírod ezt a "véleményt". Nem személyeskedésnek szánom, de neked tényleg szövegértési problémád lehet.

Nem arról van szó, hogy egyáltalán ne is kelljen küldeni a csoporttag adószámát, hanem arról, hogy ne kelljen kötelezően küldeni, csak legyen opcionális és ennélfogva ne legyen érte WARN, ha nincs. Nem arról beszéltünk, hogy majd a programunknak lesz egy olyan hiányossága, hogy nem kezeli a csoporttag adószámát és akkor majd az ügyfél jól lecseréli, ezt nem tudom honnan vetted. Ha az ügyfél felviszi a tag adószámát, akkor rákerülhet a számlára és bekerülhet az adatszolgáltatásba, ha nem, akkor nem. Ez az ügyfél felelőssége, nem a fejlesztőé.

Amúgy meg a multik jellemzően leegyeztetik előre a beszállítóikkal, hogy milyen kondíciókkal történik meg a fizetés, tehát nem fogadnak be csak úgy számlákat (legalábbis nálunk így működik).

**Comment by PalPalotai** [comment]
@lvitya586 Nem akarsz személyeskedni, de azt teszed, mindezt azért mert nem hiszed el amit a gyakorlat produkál, és nem olvasod el amit a bejelentő ír. nbeeps2 maga írta "Nem tudom feltüntetni az adatszolgáltatásban, ha a számlán nem szerepel." Ezen nincs mit szövegérteni. Valamint nem a kisujjamból szoptam hogy nem fogadja be a vevő a számlát, utólag reklamál hogy nem szerepel a számlán a csoportos adószám, ez gyakorlati tapasztalat. Ennek okát felesleges firtatni, de ha a felvetésedből indulunk ki, hogy ha előre megegyeznek a számlázási kondíciókban és már tudják hogy csak úgy lehet számlát kiállítani hogy mindkét adószám szerepel rajta és még tisztában is van vele hogy nem lehet a programjában ezt megvalósítani, akkor mi az érthetetlen abban hogy az ő döntése hogy a jelenlegit használja, vagy esetleg vált? Még véletlenül sem kívánom ezt senkinek sem, ezt csak azért emeltem ki, mert az elmúlt napokban többen is folyamatosan azon aggódnak hogy akár egy WARN miatt az ügyfelükben bizalmatlanság fog a termékükkel kapcsolatban kialakulni. De a WARN-t el lehet magyarázni az ügyfélnek, akár át is lehet alakítani milyen szövegezéssel jelenítjük meg, amibe szintén akár beleírható hogy ez nem kötelező adat, és ha még olyan is az ügyfél, akkor sem fog frászt kapni.

**Comment by NTCA-tax** [comment]
Ennek a warningnak az alapja nem egy Áfa törvénybeli szabályozás, hanem az Art. 30. §-án alapul. Az Art. 30. § alapján az áfa csoport értékesítőnek az összes adózással kapcsolatos iratokon, így az általa kiállított számlákon is fel kell tüntetnie az áfa csoport tagnak az adószámát. A warning erre a kötelezettségre hívja fel a figyelmet.

**Comment by lvitya586** [comment]
> 
> 
> mert az elmúlt napokban többen is folyamatosan azon aggódnak hogy akár egy WARN miatt az ügyfelükben bizalmatlanság fog a termékükkel kapcsolatban kialakulni.

Ez téged miért zavar? Miért zavar, ha valaki minden apróságra oda akar figyelni? Eleve Q&A témakörben lett javasolva, te meg már programváltással jössz. Ha téged nem érint, nem kell feltétlen billentyűzetet ragadni.

**Comment by lvitya586** [comment]
@NTCA-tax kérlek tisztázzuk ezt a kérdést, mert megint azt érzem, hogy egymásnak ellentmondó utasítások vannak.

Az Art. ominózus paragrafusa így szól:

> (2) A csoportképviselő a csoportazonosító számot, közösségi adószámot az adóhatóság előtti eljárása során a csoport adózással kapcsolatos iratain, így különösen a csoport általános forgalmi adóbevallásán (összesítő nyilatkozatán) feltünteti. A csoporttag a harmadik személyekkel kapcsolatos, adózással összefüggő egyéb jogviszonyaiban az adózással kapcsolatos iratokon a csoportazonosító számot, közösségi adószámot és saját adószámát is köteles feltüntetni.

Namármost itt arról van szó, hogy nemhogy 2, hanem 3 adószámot kell feltüntetni az adózással kapcsolatos iratokon. Ha a számlát is "adózással kapcsolatos irat"-nak kéne tekinteni, akkor ennek ellentmond az ÁFA törvény 169. § a számla kötelező adattartalmáról:

> dc) *  adószámának vagy csoportos általános forgalmiadó-alanyiság esetén csoportazonosító számának első nyolc számjegye, amely alatt, mint belföldön nyilvántartásba vett adóalany részére a termékértékesítést, szolgáltatásnyújtást teljesítették, feltéve, hogy a termék értékesítője, szolgáltatás nyújtója gazdasági céllal belföldön telepedett le, gazdasági célú letelepedés hiányában pedig lakóhelye vagy szokásos tartózkodási helye van belföldön;

**Comment by NTCA-tax** [comment]
A feloldás abban van, hogy az Art. a számla kibocsátóra vonatkozik, az Áfa. 169. § dc) pedig a vevőre.

**Comment by lvitya586** [comment]
> 
> 
> A feloldás abban van, hogy az Art. a számla kibocsátóra vonatkozik, az Áfa. 169. § dc) pedig a vevőre.

Valóban, ezt eltévesztettem. A 169. § c) vonatkozik a a kibocsátóra, de ott meg csak annyi van, hogy "a termék értékesítőjének, szolgáltatás nyújtójának adószáma, amely alatt a termék értékesítését, szolgáltatás nyújtását teljesítette". Itt sincs ellentmondás az Art-vel?

**Comment by NTCA-tax** [comment]
Nincs ellentmondás, mivel az Art. nem felülírja az Áfa szabályait, hanem kiegészíti azt. Az Áfa törvény azt mondja, hogy ebben az esetben az áfa csoport azonosítóját kell feltüntetni, az Art. pedig kiegészíti a csoporttag adószámával.

**Comment by DrotosTot** [comment]
A dokumentáció szerint nem kötelező küldeni a csoporttag adószámát.
V2.0 75. oldal alja, V3.0 79. oldal alja:
"Amennyiben az eladó csoportos áfa-alany, akkor – az Áfa törvény előírásainak megfelelően – az eladó a csoport. A csoporttag adószámát pedig a groupMemberTaxNumber elemben (típusa: TaxNumberType) kell feltüntetni, amennyiben ez szerepel a számlán."
A hangsúly az "amennyiben ez szerepel a számlán" szövegrészen van.

**Comment by lvitya586** [comment]
Pont erről beszéltem, hogy ezzel kapcsolatban nem teljesen konzisztens az álláspont. A legtöbben az Áfa törvényre hivatkoznak, a fejlesztői doksi is arra hivatkozik, meg sem említi az Art-t, továbbá az onlineszamla jogszabályok oldalán lévő 23/2014. (VI. 30.) NGM rendelet is a legalább Áfa törvény szerinti adatokat kéri, ráadásul hosszabb rendszerleállás esetén is a legalább Áfa törvény szerinti adatokat kell kézzel rögzíteni a weboldalon.

Nyilván a törvény erősebb, mint a rendelet, de akkor ha valóban az Art a mérvadó, akkor miért nincsen ez kihangsúlyozva, továbbá akkor miért warn jár, ha nincs feltüntetve a csoporttag adószáma is, hiszen akkor az Art szerint kötelező. Teljesen logikátlan ennek a kezelése.

**Comment by DrotosTot** [comment]
Abszolút. Vevő oldalon viszont elég a csoportazonosító beküldése, ott nem jár érte bünti.

**Comment by nbeeps2** [comment]
@NTCA-tax  nem győztél meg (lásd fentiek kommentjei), ráadásul ha az adószámként a CSAZ első 8 karakterét tünteti fel a kiállító, akkor az ellenőrzés kikerülhető és nem is jön WARN...
@PalPalotai A felhasználónak nem kell lecserélni a programunkat, mert ezt minden programban meg lehet oldani. Minden programban van lehetőség megjegyzést adni. Nálunk is így történik. Az adószám mezőbe a kiállító 5-ös adószáma szerepel, a 4-es adószámát meg ha akarja a megjegyzésbe fel tudja tüntetni. Emiatt persze nem töltöm a groupMemberTaxNumber mezőt, de ettől függetlenül a számlán szerepel, NAV által nem kifogásolható a számla, és az adatszolgáltatásba is belekerül additionalinformacióként...

**Comment by nbeeps2** [comment]
2. kérdés: "Ha használsz DTO generálást a projektedben, akkor az új sémákkal a projekt már nem fog fordulni. Vagy használj catalog XSD-t a common és a base sémák importálására és ezt kösd be a projekthez, vagy írd be a letöltött sémákba a schemaLocation attribútumot olyan filepath értékkel, ami neked megfelelő." 

Itt mire gondolt a költő? Nem használok DTO generálást (életemben nem használtam és fogalmam sincs mi az...), tehát az utasítás 2. része vonatkozik rá, csak nem tudom mit kell csinálni: 
a) catalog XSD-t a common és a base sémák importálására és ezt kösd be a projekthez (ezt hogyan kell?)
b)  írd be a letöltött sémákba a schemaLocation attribútumot olyan filepath értékkel, ami neked megfelelő (ez egyszerűbbnek hangzik, de nem tudom, hogy mit ért az alatt, hogy ami nekem megfelelő)

**Comment by NTCA-tax** [comment]
@nbeeps2 Itt azt kellett mérlegelnünk, hogy melyik a nagyobb probléma: ha egy ismert jogszabályi összefüggésre nem hívjuk fel a figyelmet, vagy felhívjuk a figyelmet akkor is, ha nem áfa törvény oldalán van a kötelezettség. Ez utóbbi mellett maradtunk, mivel egy áfa csoport esetén ennek a csoporttag adószámának mindenképp ott kellene lennie, ha pedig lemaradna, akkor nem lenne megfelelő a számla adattartalma. Amennyiben nem is szerepel az adatszolgáltatásban, attól az adatszolgáltatást feldolgozzuk.

Egyébként pedig hiba lenne a warningra büntetésként gondolni. Amennyiben a warningból lát a felhasználó egy olyan összefüggést, amelyre nem gondolt, vagy nem tudott, akkor még mindig sokkal hatékonyabb módja a figyelem felhívásnak, mint minden ilyen esetre adóellenőrt tartanánk fenn. A warning kapcsán éppen azt látjuk, hogy számos olyan kérdést nyitottunk ki, amelyet korábban ilyen hatékonysággal nem tudtunk volna megbeszélni.

**Comment by nbeeps2** [comment]
@NTCA-tax ok, rendben, megteszem a szükséges kiegészítéseket. Ellentmondás érzek az ÁFA törvény és az ART erre vonatkozó részénél, amit már fent is megfogalmaztak, de ez már nem a NAV hatásköre, így elfogadom a választ. Csak valóban fura, hogy ha az ART szertin ha a csoporttag harmadik féllel üzletel, akkor mindig szerepeltetni kell mindkét adószámát, viszont az ÁFA törvény meg azt írja elő, hogy ha vevő az illető, akkor elég csak a csoportazonosítója (5-ös adószám), illetve ha már a ÁFA törvény külön kitért a vevői oldalon a csoportos adószámosokra, akkor ezt megtehették volna a kiállító oldalon és belekerülhetett volna az ÁFA törvénybe, hogy kiállító oldalon szükség van a kiállító adószámára, csoportos adóalany esetén pedig mindkét adószámra. Ez így lenne tiszta. Ráadásul a NAV doksiból is úgy értelmezhető, hogy nem kell a kiállító oldalon mindkét adószám, csak akkor ha szerepel... Persze mélyen beleásva magam már értem, hogy itt nyilván arra gondolt a költő, hogy ha csoportagok egymásnak állítanak ki számlát, akkor nincs szükség a saját adószámukra és ilyen esetben fordulhat csak elő, hogy kiállítóként csak az 5-ös adószámuk szerepel, míg ha harmadik félnek állítanak ki számlát, akkor már rá kell kerüljön a 4-es adószám is.  Részemről zárható akkor a topik, köszönöm.

**Comment by NTCA-tax** [comment]
Ezt most lezárom, ha a csoportos adószámmal további kérdés merülne fel, akkor egy új issue-ban beszéljük meg.
