### ISSUE TITLE
[Q&A] lineVatRate és summaryByVatRate validáció nem számol?

### ISSUE THREAD

**Issue by DrotosTot** [nav-gov-hu/Online-Invoice#443]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Ha a VatRateType elemben olyan jelölést alkalmazunk, hogy a tétel nem tartalmaz áfát, akkor a beküldött számszaki adatok validációja nem történik meg és a hibás számadatok ellenére DONE az eredmény.
Célszerű lenne ezen esetekben a lineVatAmount, lineVatAmountHUF, vatRateVatAmount és vatRateVatAmountHUF elemek értékét 0-ra ellenőrizni.
Tesztben levő tranzakció azonosító: 34WEWH7ZGZTWCFDW
Például egy hibás XML részlet:
`<lineAmountsNormal>
<lineNetAmountData>
<lineNetAmount>15000.00</lineNetAmount>
<lineNetAmountHUF>15000.00</lineNetAmountHUF>
</lineNetAmountData>
<lineVatRate>
<vatOutOfScope>true</vatOutOfScope>
</lineVatRate>
<lineVatData>
<lineVatAmount>14700.00</lineVatAmount>
<lineVatAmountHUF>14700.00</lineVatAmountHUF>
</lineVatData>
<lineGrossAmountData>
<lineGrossAmountNormal>29700.00</lineGrossAmountNormal>
<lineGrossAmountNormalHUF>29700.00</lineGrossAmountNormalHUF>
</lineGrossAmountData>
</lineAmountsNormal>`
A problémánk összefügghet a #416 issue-ban közöltekkel.

**Comment by NTCA-tax** [comment]
Köszönjük a jelzést, továbbítottam a warningokkal foglalkozó kolléga felé. A hasonló jelzéseket örömmel fogadjuk :)
