### ISSUE TITLE
[Q&A] INCORRECT_SUMMARY_CALCULATION, tolerált eltérés értelmezése

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#444]
INCORRECT_SUMMARY_CALCULATION_VAT_RATE_VAT_AMOUNT_HUF_SUMMARY üzenetet kapok.

A számlasorok összesen értéke alapján az összesen nettó 330 Ft, az ÁFA érték 88 Ft. 
Ha a 330 Ft-ból számolom a 27% ÁFA-t , az 89.10 Ft lenne. 
A hibaüzenet erre az 1.1 értékre (különbség) hivatkozik.

A dokumentáció ezt írja: 
Tolerált eltérés: vatRateNetAmountHUF 1%-a, de legalább 1 egység

Na már most a 330 Ft 1%-a 3.3 Ft, akkor nem értem, hogy miért dob Warningot 1.1-re. A "legalább" az én értelmezésemben nem azt jelenti, hogy "legfeljebb".

**Comment by NTCA-supporter** [comment]
Köszi a jelzést.
Utánanézek, hogy pontosan hogy számolunk. Azok alapján amit leírtál, valóban nem kellene warn-t kapnod.
Kis türelmet kérek.
Üdv

**Comment by gajzi** [comment]
Gondolom itt a leírást rontották el és
"Tolerált eltérés: vatRateNetAmountHUF 1%-a, de legalább 1 egység"
helyett
"Tolerált eltérés: vatRateVatAmountHUF 1%-a, de legalább 1 egység"
kellene szerepeljen benne.
De arről a problémáról már a nyár folyamán írtunk többen is ( #335 ) , itt egyszerűen átgondolatlan az ellenőrzés, illetve maga az adatszerkezet. Sorértékekben (nettó, áfa, bruttó) 2 tizedes van engedélyezve, mind eredeti devizában, mind HUF-ban. Ezzel ellentétben az egységár lehet akár 10 tizedes (mi 4-et használunk is), így az eredeti devizában rejtőzhet 5 ezred eltérés, ami egy mai EUR árfolyammal felszorozva 1 HUF fölé megy .
Nálunk (1-2 partnerünknél, akik apróságokat is árulnak pl.: alátét) igen gyakori az ilyen WARNING.
Jelenleg megoldhatatlan ez a  probléma, mert ha soronként benyelnénk az ezredes helyiértéken lévő értéket, akkor soronként ugyan jók lennénk, de akkor a számla összesenben bukna ki,

**Comment by nbeeps2** [comment]
@gajzi: Nos a számlán nem kötelező egyáltalán filléreket használni, ez lehet beállítás kérdése egy adott programnál. Nagyon sok felhasználónál tehát nincsenek tizedesek. Az összesen szó meg elég egyértelmű, tehát a számlán lévő tételesen felsorolt számokat kell összeadni. Írok egy félig szélsőséges példát:

Legyen 4 darab tétel a számlán:
1.  1 db nettó 10 ft, ÁFA 3 ft, bruttó 13 Ft
2.  1 db nettó 10 ft, ÁFA 3 ft, bruttó 13 Ft
3.  1 db nettó 10 ft, ÁFA 3 ft, bruttó 13 Ft
4.  1 db nettó 10 ft, ÁFA 3 ft, bruttó 13 Ft
-----------------------------------------------
Összesen nettó 40 Ft, ÁFA 12 Ft, bruttó 52 Ft 
Az ÁFA természetesen 27% és nem 30%, viszont nem tüntetünk fel 2.7 Ft-ot a számlatételeinél, mert nincs bekapcsolva a tizedesek kezelése, az ügyfél nem akar tizedeseket látni a számlán.

Furcsán néznek ki, ha a fenti 4 tétel után az összesen sor, nem az összesent tartalmazná és se az ÁFA, se a bruttó nem stimmelne...:
Összesen nettó 40 Ft, ÁFA ÁFA 11 Ft bruttó 51 Ft (lévén a 40 Ft * 0,27 = 10.8 -> 11 Ft ÁFA)

**Comment by nbeeps2** [comment]
Egy egészen másról szóló topikban azt kaptam hivatalosan válaszként, hogy  "hiba lenne a warningra büntetésként gondolni." Vagyis igazából ne kéne vele egyáltalán foglalkozni, én nem is akarnék vele, de a felhasználónál ez másképp csapódik le. Ő úgy érzi, ha ilyen üzenetet kap (amibe ráadásul szerepel az INCORRECT szó is), hogy hibás a program és egyrészt minket csesztet vele, másrészt a programot tünteti fel rossz színben, én tehát ezért vagyok ellene a felesleges Warningoknak.

**Comment by gajzi** [comment]
Egyetértek, a sok felesleges WARNING-ból az lesz, hogy a felhasználók olyan üzenetre sem fognak semmit tenni, amit lenne lehetőségük, sőt kötelességük lenne korrigálni.
Mi a következő számlára
<invoiceDetail>	
		<invoiceCategory>NORMAL</invoiceCategory>
		<invoiceDeliveryDate>2020-10-20</invoiceDeliveryDate>
		<invoiceAccountingDeliveryDate>2020-10-20</invoiceAccountingDeliveryDate>
		<currencyCode>EUR</currencyCode>
		<exchangeRate>353.980000</exchangeRate>
		<paymentMethod>TRANSFER</paymentMethod>
		<paymentDate>2020-10-30</paymentDate>
		<invoiceAppearance>PAPER</invoiceAppearance>
	</invoiceDetail>
</invoiceHead>

	<invoiceLines>
		<line>
			<lineNumber>1</lineNumber>
			<lineExpressionIndicator>true</lineExpressionIndicator>
			<lineDescription>Alátét</lineDescription>
			<quantity>8.000</quantity>
			<unitOfMeasure>OWN</unitOfMeasure>
			<unitOfMeasureOwn>pc</unitOfMeasureOwn>
			<unitPrice>0.0135</unitPrice>
			<lineAmountsNormal>
				<lineNetAmountData>
					<lineNetAmount>0.11</lineNetAmount>
					<lineNetAmountHUF>38.23</lineNetAmountHUF>
				</lineNetAmountData>
				<lineVatRate>
					<vatPercentage>0.27</vatPercentage>
				</lineVatRate>
				<lineVatData>
					<lineVatAmount>0.03</lineVatAmount>
					<lineVatAmountHUF>10.32</lineVatAmountHUF>
				</lineVatData>
				<lineGrossAmountData>
					<lineGrossAmountNormal>0.14</lineGrossAmountNormal>
					<lineGrossAmountNormalHUF>48.55</lineGrossAmountNormalHUF>
				</lineGrossAmountData>
			</lineAmountsNormal>
		</line>
	</invoiceLines>

kapjuk az alábbi hibát:
<processingResults>
	<processingResult>
		<index>1</index>
		<invoiceStatus>DONE</invoiceStatus>
		<businessValidationMessages>
			<validationResultCode>WARN</validationResultCode>
			<validationErrorCode>INCORRECT_LINE_CALCULATION_LINE_GROSS_AMOUNT_NORMAL_HUF</validationErrorCode>
			<message>Eltérés a számla tétel eredeti pénznemben és forintban megadott bruttó értéke között.</message>
			<pointer>
				<tag>InvoiceData/invoiceMain/invoice/invoiceLines/line/lineAmountsNormal/lineGrossAmountData/lineGrossAmountNormalHUF</tag>
				<value>1.00720000</value>
				<line>1</line>
			</pointer>
		</businessValidationMessages>
		<compressedContentIndicator>false</compressedContentIndicator>
	</processingResult>
	<originalRequestVersion>2.0</originalRequestVersion>
</processingResults>

Mert szerinte a már lekerekített bruttó forintosítva 0.14*353.98=49,5572, szerintem meg 8*0.0135*1.27*353.98=48.5519.

**Comment by rtoth0407** [comment]
> @gajzi: Nos a számlán nem kötelező egyáltalán filléreket használni, ez lehet beállítás kérdése egy adott programnál. Nagyon sok felhasználónál tehát nincsenek tizedesek. Az összesen szó meg elég egyértelmű, tehát a számlán lévő tételesen felsorolt számokat kell összeadni. Írok egy félig szélsőséges példát:
> 
> Legyen 4 darab tétel a számlán:
> 
> 1. 1 db nettó 10 ft, ÁFA 3 ft, bruttó 13 Ft
> 2. 1 db nettó 10 ft, ÁFA 3 ft, bruttó 13 Ft
> 3. 1 db nettó 10 ft, ÁFA 3 ft, bruttó 13 Ft
> 4. 1 db nettó 10 ft, ÁFA 3 ft, bruttó 13 Ft
> 
> Összesen nettó 40 Ft, ÁFA 12 Ft, bruttó 52 Ft
> Az ÁFA természetesen 27% és nem 30%, viszont nem tüntetünk fel 2.7 Ft-ot a számlatételeinél, mert nincs bekapcsolva a tizedesek kezelése, az ügyfél nem akar tizedeseket látni a számlán.
> 
> Furcsán néznek ki, ha a fenti 4 tétel után az összesen sor, nem az összesent tartalmazná és se az ÁFA, se a bruttó nem stimmelne...:
> Összesen nettó 40 Ft, ÁFA ÁFA 11 Ft bruttó 51 Ft (lévén a 40 Ft * 0,27 = 10.8 -> 11 Ft ÁFA)

A törvényi előírás szerint - nem egyszerűsített számlák esetén - a helyes ÁFA értéket az ÁFA alapok összegére kell számolni, tehát a helyes ÁFA összeg fenti példád szerint 40 Ft * 0,27 = 10.8 -> 11 Ft .
Ha tétel szinten is megjeleníted az ÁFA értékét, akkor tutira kerekítési problémákba fogsz ütközni. A nyomtatott számlaképen már nem kötelező a tétel szintű ÁFA érték, de sajnos a NAV Online adatszolgáltatásban igen.
SAP rendszerek viszonylag korrekten kezelik a problémát: a kétféle számítási módból keletkező különbözetet a legnagyobb nettó értékű tételre osztják rá. Sok tételes számla és egész HUF kerekítés esetén igen komoly eltérések is adódhatnak, így az 1%-os tűrés kevés lesz.

**Comment by nbeeps2** [comment]
@rtoth0407 Nem tudom te milyen üzleti rendszerekben mozogsz, de a magyarországi számlázó programok jelentős többsége feltüntet a számlán nettó, áfa, bruttó értéket tételesen. Ez egyrészt felhasználói igény is. Innentől kezdve meg igen érdekesen nézne ki, ha fenti számlának 51 Ft lenne a bruttója és a 11 Ft az ÁFA-ja, viszont az is igaz, hogy a gyakorlatban nem ilyen kis összegeket számláznak, így a gyakorlatban nincs is ilyen mértékű eltérés, csak az elméleti lehetőségekről társalogtunk.

**Comment by omachtandras** [comment]
@rtoth0407 
> 
> A törvényi előírás szerint - nem egyszerűsített számlák esetén - a helyes ÁFA értéket az ÁFA alapok összegére kell számolni, tehát a helyes ÁFA összeg fenti példád szerint 40 Ft * 0,27 = 10.8 -> 11 Ft .
> Ha tétel szinten is megjeleníted az ÁFA értékét, akkor tutira kerekítési problémákba fogsz ütközni. A nyomtatott számlaképen már nem kötelező a tétel szintű ÁFA érték, de sajnos a NAV Online adatszolgáltatásban igen.
> SAP rendszerek viszonylag korrekten kezelik a problémát: a kétféle számítási módból keletkező különbözetet a legnagyobb nettó értékű tételre osztják rá. Sok tételes számla és egész HUF kerekítés esetén igen komoly eltérések is adódhatnak, így az 1%-os tűrés kevés lesz.

Tudnál esetleg konkrét törvényi hivatkozást adni?

Nálunk az a szakmai oldal véleménye, hogy a számlának a tételsor az elemi egysége, ezt lehet érvényteleníteni, helyesbíteni, engedménnyel ellátni, ÁFA bevallási alapegységként értelmezni stb., ezért tételsor szinten meg kell állnia az alap +adó = bruttó elvárásnak.

(Láttunk már NAV Igazgatóságonként eltérő állásfoglalásokat az ügyben, hol ez, hol az mellett érveltek, de egyik esetben sem volt egyértelmű törvényi hivatkozás, ami konkrétan leírta volna, hogy melyik megközelítés a helyes.)

Esetleg NTCA-Tax véleményét is szívesen vennénk, ha kérhető. :)

Köszönöm!

**Comment by nbeeps2** [comment]
@rtoth0407 : egyetértek veled. Egyébként jó (mindig működő) megoldás nincs. Mindkét számolási móddal lehet anomáliákat előhozni, de a WhatYouSeeWhatYouGet elv alapján is a számlatételből számolt összesen érték a jobban emészthető a megoldás. Ismerek olyan számlázó programot, ahol a számla tételinél kerekített kijelzés zajlik, de valójában a kerekítetlen összegeket adja össze, na azzal lehet ám olyan számlákat kiállítani, hogy a 2x2 néha 5 :)

**Comment by EnokhSys** [comment]
> Tudnál esetleg konkrét törvényi hivatkozást adni?

Nincs rá törvényi hivatkozás, ha jól emléxem, az ÁFA tv. fejbőlnemtommelyik cikkelye is csupán azt mondja ki, hogy a számla ÁFA részletezőjében az alapokat és ÁFA összegeket egész Ft-ban kell feltüntetni, amit végezhetsz úgy is, hogy a tételekben kerekítesz és úgy is, hogy áfa-alap nettóra és áfa-ra. 
Tapasztalatom szerint a cégeknél az a bevett gyakorlat, hogy törekednek a legkisebb kerekítési eltérésre, ezért tételekben nem kerekítek - még akkor sem, ha a számlán megjelenítem a tétel áfa és bruttó összegét -, így ez csak az áfa alapoknál történik meg.

**Comment by jozanesz** [comment]
@EnokhSys 
Szerintem túl sokat képzelsz a hatályos áfatörvénybe. Egyáltalán nincs is benne szó számla esetén összesítésről, csak gyűjtőszámlák esetén. Egész forintról meg végképp nincs szó.

**Comment by rtoth0407** [comment]
ÁFA törvényben régebben szerepelt, hogy tételenkénti bruttó összeg és ÁFA érték is kötelező a számlán. Ma már ez nincs benne, tehát nem kötelező. A legtöbb cégnél ezt a változást már nem követték le, ezért maradtak rajta sok számlán ezek az adatok.
Gyakorlati tapasztalatom az, hogy ha 2 tizedesig kezeled az értékeket, akkor meg szabad jeleníteni tétel szinten is ezt a két értéket, mert néhány fillér lesz csak az eltérés. Ha mindenhol egész értékeket jelenítesz meg, az tutira számszaki hibát okoz.

**Comment by EnokhSys** [comment]
> @EnokhSys
> Szerintem túl sokat képzelsz a hatályos áfatörvénybe. Egyáltalán nincs is benne szó számla esetén összesítésről, csak gyűjtőszámlák esetén.

@jozanesz igazad van, egy szó sincs erről a mostani ÁFA tv.-ben, hogy kötelező az alapoknál kerekíteni.

> Egész forintról meg végképp nincs szó.

Nem egészen. Magyarország hivatalos pénzneme a forint és ennek váltója még mindig a fillér. Meg kellene nézni a 90-es évekbeli ÁFA tv.-t, hogy benne volt-e a "forint, fillér" vagy "forint/fillér" kifejezés, mert azáltal, hogy kikerült belőle a "fillér", kötelezővé vált a tizedes kerekítése vagy a levágása. Emléxem, hogy akkor át kellett írnunk a szoftvercég integrált rendszerének számlázó programját, mert bevezetésre került a kerekítés a bruttó összegre (tehát akkoriban még nem ÁFA alapra), csak fogalmam sincs, hogy milyen tv. alapján.

**Comment by EnokhSys** [comment]
**Csendben röhögök: lehet, hogy a számlán a kerekítés kötelezősége csupán "urban legend" kategória? :-))**

Kíváncsiságból, az elmúlt fél órában megpróbáltam feltúrni a netet, hogy a 90-es évektől kezdődően mely jogszabályok írják elő a számlán a kerekítést, de sehol nem találtam. Még az 1999-ben utolsónak bevont-, 50 filléres pénzérme sem jelentette azt, hogy ne lehetne számlázni fillérben.
Azt meg főleg nem találom, hogy az áfa alapok kerekítését mely törvény írja elő.

Lehet, hogy a fillér - mint fizetőeszköz - megszűnésével, csupán egy huszonvalahányéve kialakult társadalmi szokásról van szó, amelyről mindenki azt hitte, hogy valamely tv. írja elő? :-)

**Comment by fenyvessy** [comment]
Az ÁFA tv. 172. §: " A számlán az áthárított adót [...]  forintban kifejezve abban az esetben is fel kell tüntetni, ha az egyéb adatok külföldi pénznemben kifejezettek."
Ezt lehet úgy **is** értelmezni, hogy fillér nélkül, kizárólag egész forintban kell feltüntetni. De én még soha nem láttam olyan embert, aki hallott volna olyanról, akinek az ismerősének a barátját a kerekítés meg a fillérek miatt hurcolták volna meg annak ellenére, hogy  a bizonylat végén az áfa összesítő számszakilag stimmelt.

**Comment by betasofthu** [comment]
Nincs előírva kerekítési kötelezettség. Az adóhivatal online számlázója nem is kerekít. Ez meglehetősen furcsán hat, de ez a helyes.
Itt egy korábbi hozzászólásom a témában: https://github.com/nav-gov-hu/Online-Invoice/issues/217#issuecomment-623951040

**Comment by lvitya586** [comment]
@betasofthu ehhez képest az egyik online számlázó [oldal](https://www.szamlazz.hu/szamla/tudastar/funkcionalitas/hogyan_kerekitunk) egészen mást állít, csak azt nem részletezi mi alapján.

**Comment by EnokhSys** [comment]
> Az ÁFA tv. 172. §: " A számlán az áthárított adót [...] forintban kifejezve abban az esetben is fel kell tüntetni, ha az egyéb adatok külföldi pénznemben kifejezettek."
> Ezt lehet úgy **is** értelmezni, hogy fillér nélkül, kizárólag egész forintban kell feltüntetni. De én még soha nem láttam olyan embert, aki hallott volna olyanról, akinek az ismerősének a barátját a kerekítés meg a fillérek miatt hurcolták volna meg annak ellenére, hogy a bizonylat végén az áfa összesítő számszakilag stimmelt.

@fenyvessy Igen, jól mondod, lehet így **IS** értelmezni. Ugyanakkor továbbra is jelzem, hogy az értelmezés során az is sokat nyom a latban, hogy a régi törvényben használatos volt-e a "forint, fillér", "forint-fillér" kifejezés.

**Comment by EnokhSys** [comment]
Elég sokat szoktam hülyéskedni :-), de most egy picit komolyabbra fordítom a szót, és kikaparom a tűzből a gesztenyét a NAV-nak (@NTCA-tax, ez biztos érdekelni fog)

Eltöprengtem a kerekítés jogi kérdésén, és az a helyzet, hogy a NAV-nak mégiscsak van jogalapja ahhoz, hogy ne fogadjon el bizonyos kerekítési módszereket. Ezt a jogalapot nem az ÁFA tv. teremti meg, hanem a polgári törvénykönyv, annak is az alábbi bekezdésnek a második mondata:

"6:63. § (5) A szerződés tartalmává válik minden szokás, amelynek alkalmazásában a felek korábbi üzleti kapcsolatukban megegyeztek, és minden gyakorlat, amelyet egymás között kialakítottak. **A szerződés tartalmává válik továbbá minden, az adott üzletágban a hasonló jellegű szerződés alanyai által széles körben ismert és rendszeresen alkalmazott szokás,** kivéve, ha annak alkalmazása a felek között - korábbi kapcsolatukra is figyelemmel - indokolatlan volna._"

Tudni kell azt, hogy a NAV - mint közteherviselést biztosító és érvényesítő hatóság -, minden olyan szerződésben PASSZÍV, ÉRDEKELT FÉLKÉNT vesz részt, amelynek teljesítése során adókötelezettség keletkezik. Arra ugyan nincs jogköre, hogy általánosságban beleavatkozzon a szerződésekbe, arra viszont van, hogy hivatalos állásfoglalásával támogassa az eddig kialakult leggyakoribb kerekítési módszert, mint "széles körben ismert és rendszeresen alkalmazott szokás", és elutasítsa a többit. 

Ugyanakkor hatóságként joga van ahhoz, hogy ellenőrizze a számlákat, különösen ÁFA tekintetében, és amennyiben úgy ítéli meg, hogy az abban alkalmazott kerekítési módszer nem felel meg a széles körben elterjedt gyakorlatnak, küldhet rá figyelmeztetést a NAV OnLine Számla rendszeréből, vagy akár el is utasíthatja annak befogadását.
(Most nem akarok olyanba belemenni, hogy erre hivatkozásul akár meg is támadhat a bíróságon szerződéseket, mert ez már hülyeség és túlzás lenne, ezt csupán azért írtam, mert van hozzá jogalapja.) 

Összefoglalva: habár egyetlen törvény sem határoz meg kerekítési módot, a NAV - passzív érdekelt félként - megteheti azt, hogy az utóbbi két évtizedben a gazdasági életben alkalmazott egy-két leggyakoribb módszert fogadja el, és a többit elutasítsa. (Azt, hogy melyek a leggyakoribb kerekítési módszerek, a 2020. július 1 óta kötelező számlabeküldés alapján könnyen alá tudja támasztani.)

**Comment by Macskafarka** [comment]
@EnokhSys Akkor ez alapján a NAV akár fel is hagyhatna a negatív lánckezdő számla kifogásolásával, hiszen széles körben elterjedt gyakorlat, amely nem ütközik jogszabályba. 
Mondhatnám így is: "A negatív számla javallatokra való alkalmazása a régóta fennálló használaton alapul." :)

**Comment by EnokhSys** [comment]
> @EnokhSys Akkor ez alapján a NAV akár fel is hagyhatna a negatív lánckezdő számla kifogásolásával, hiszen széles körben elterjedt gyakorlat, amely nem ütközik jogszabályba.
> Mondhatnám így is: "A negatív számla javallatokra való alkalmazása a régóta fennálló használaton alapul." :)

Naigen, volt is a NAV-val egy csörtém még tavasszal ez ügyben (1090-es warning), és mivel totális patthelyzet alakult ki közöttünk, a törvényszékhez fordultam közérdekű bejelentéssel, hogy öntsön már tiszta vizet a pohárba jogértelmezés-ügyileg. A törvényszék nagyon kedvesen visszaírt, hogy mivel közöttünk nem jogvita áll fenn, hanem jogértelmezési vita, ezért visszautalja NAV hatáskörbe az ügyet, merthogy nem illetékes az ügyben. Hát akkor ki? Ha nem akarok rosszindulatúan pereskedni, pusztán egy széles gazdasági réteget érintő jogi kérdésben szeretnék állásfoglalást kérni, amelyre a törvényszék szakmai kollégiuma lenne az illetékes, mégis kihez forduljak? 
A NAV pedig egy szintén nagyon kedves levelet küldött, amelyben megismételte a tavaszi álláspontját, ugyanakkor azt is kiolvastam belőle, hogy nem tervezi tiltásként bevezetni a negatív számlákra vonatkozó figyelmeztetést. Én meg úgy voltam vele, hogy bármilyen további erőfeszítés már a "sok hűhó semmiért" kategória lenne, ott egye meg a fene a 1090-es warning-ot, amíg az csak figyelmeztetés marad és nem tiltás, nem okoz kárt senkinek, különben sem szeretek harcolni. (Yoda mester első könyve, ámen.) 

A lényeg az, hogy a negatív összegű számlákat nem azért nem lehet tiltani, mert a gazdaság szereplői között ez a számla fajta már régóta bevett szokás, hanem azért mert maga az ügylet (pl. termék visszáruzás, pénzügyi jóváírás) egy széles körben elterjedt szokás, és mivel a számla a tényleges gazdasági cselekményt kell tartalmazza, a negatív számla tiltásával áttételesen megtiltanák az ügyletet is. Ezt viszont nem teheti meg sem a NAV, sem más jogszabály, mert az már sérti a szerződéskötés szabadságának alkotmányos kitételét. Tehát még a Parlament sem hozhat ilyen irányú általános jogszabályt, mert azt az Alkotmánybíróság biztosan elkaszálná (hiszen bármilyen szabadságjogot csak nagyon erős indokkal lehet korlátozni).

Na, de eléggé elkanyarodtunk a kerekítéstől, térjünk vissza a topik eredeti témájához, mielőtt kivágnak minket innen. :-)

**Comment by fzoli15** [comment]
A számla végösszegének egész forintra történő kerekítése kapcsán kialakult gyakorlat szerintem nem törvényi szabályozásból ered, hanem praktikussági okai vannak, mivel filléreket már nem lehet kifizetni (sem készpénzben, sem utalással). Emiatt alakult ki az is az 1 és 2 Ft-os érme kivezetése után, hogy a készpénzes nyugták és számlák végösszegét rendszerint 5 Ft-ra kerekítik.

**Comment by EnokhSys** [comment]
> A számla végösszegének egész forintra történő kerekítése kapcsán kialakult gyakorlat szerintem nem törvényi szabályozásból ered, hanem praktikussági okai vannak, mivel filléreket már nem lehet kifizetni (sem készpénzben, sem utalással). Emiatt alakult ki az is az 1 és 2 Ft-os érme kivezetése után, hogy a készpénzes nyugták és számlák végösszegét rendszerint 5 Ft-ra kerekítik.

Igen, valószínűleg ez történt. Az viszont továbbra is rejtély, hogy hogyan terjedt el az ÁFA alapokra történő kerekítés - mint jogszabályi előírás - gyakorlata.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ez kissé lemaradt.
"Tolerált eltérés: vatRateVatAmountHUF 1%-a, de legalább 1 egység"
Ez lenne helyesen, mindig a saját típushoz hasonlítunk, javítjuk majd a doksiban.
Zárom az issuet.
Üdv

**Comment by Rossi73** [comment]
@nbeeps2 nyitó hozzászólásához kapcsolódnék, mielőtt a javítjátok a doksiban:

_A "legalább" az én értelmezésemben nem azt jelenti, hogy "legfeljebb"._

Én is ezzel értek egyet. Ha arról szól a történet, hogy egy ellenőrző rutin tolerál (azaz engedélyez, "elnéz", figyelmen kívül hagy) egy eltérést "valameddig", akkor a toleranciának **felső** (szélső) határa kell, hogy legyen. Ergo a helyes szó a "legfeljebb":

"Tolerált eltérés: vatRateVatAmountHUF 1%-a, de **legfeljebb** 1 egység"

**Comment by NTCA-supporter** [comment]
Jó az a legalább.
Ezt úgy kell értelmezni, hogy a tolerált eltérés az xy 1%-a, efölött jön a WARN, viszont csak akkor, ha az legalább 1 HUF/EUR/stb.
Ha pl. az eltérés 3%, de az csak 0.99HUF, akkor nem kapod a WARN-t.
Így világos?
Köszi

**Comment by Rossi73** [comment]
Igen, köszönöm, így már világos.
