### ISSUE TITLE
application.wadl resource path (v3.0)

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#445]
Jelenleg bele van égetve a teszt rendszer path-ja. Jó lenne olyan változatot kiadni belőle, amibe nincs benne az égetés. Direktbe kód generálás esetén így generált kódba is égetésre került a teszt URL.

< resource path="https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3">
helyett
< resource>

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !
Köztes megoldásként ezt tudom felajánlani:
`<resource path="/invoiceService/v3">`
Mit szólsz?
Üdv

**Comment by EPluribusUnum** [comment]
@NTCA-supporter, kipróbáltam, megfelel a köztes megoldás is.

**Comment by NTCA-supporter** [comment]
Köztes megoldás feltöltve teszt/éles környezetre.
Üdv
