### ISSUE TITLE
[Q&A] metricService/v3 hibás namespace

### ISSUE THREAD

**Issue by vectorkovacspeter** [nav-gov-hu/Online-Invoice#446]
A /metricService/v3 -as végpontok xml válaszában a namespace még 2.0, ami deserializációs hibát okoz.

pl:
https://api-test.onlineszamla.nav.gov.hu/metricService/v3/queryServiceMetrics/list
`<QueryServiceMetricsListResponse xmlns="http://schemas.nav.gov.hu/OSA/2.0/metrics" xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/api">`

pedig XSD és logika szerint is a root attribútum `http://schemas.nav.gov.hu/OSA/3.0/metrics` kellene, hogy legyen.

**Comment by NTCA-supporter** [comment]
Köszi a jelzést, javítani fogjuk.
Addig maradhat nyitva az issue.
Üdv

**Comment by NTCA-supporter** [comment]
A namespace javult. Valamiért most nem töltődnek az értékek, amire van külön issue #554 
Záromm az issuet, köszi a jelzést.
Üdv
