### ISSUE TITLE
[Q&A] /v2/queryInvoiceDigest korlátozásra került

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#448]
Sziasztok!

"Online Számla rendszer API forgalom korlátozás
2020-10-15 20:39
Az Online Számla rendszer V2-es API interfészen 2020. október 15-én 18 óra 5 perckor  a NAV korlátozta a /v2/queryInvoiceDigest operációt. Az operációra küldött hívásokat a rendszer a korlátozás feloldásáig nem szolgálja ki. Az eseménnyel kapcsolatos új információ esetén frissítést teszünk közzé, kérjük kísérje figyelemmel a tájékoztatásokat!
Megértését és türelmét köszönjük!"

Azt szeretném megkérdezni, hogy ez a korlátozás miért történt? Várhatóan meddig fog tartani?

Kezdem a kisebb problémával:
Ez egy nagyon rosszkor jött és nagyon rossz üzenetet hordozó korlátozás. Nálunk az ügyfelek egy része már a NAVtól letöltött adatokra alapozva rögzíti a szállítói számláit, számukra - így ÁFA bevallás előtt - ez nagyon rossz üzenet, finoman szólva is megbízhatatlanságot sugároz azzal kapcsolatban, hogy ez egy stabil, működő modell...

És a komolyabb:
Ez a tiltás megakadályozza az adatszolgáltatást olyan esetben, ha egy módosító okiratot kell kiállítani egy számlázó rendszerben úgy, hogy az előzmény számla egy másik rendszerben volt még kiállítva (pl. a cég átalakulása/egyesülése miatt). Nem tudom más rendszerek hogy oldották meg ezt a kérdés, mi ilyenkor a NAVtól töltjük le a szükséges adatokat, hogy az adatszolgáltatást meg tudjuk tenni. Ez most nem működik.

**Comment by vastag60** [comment]
"Megértését és türelmét köszönjük!"

Akkor szoktam látni ezt közleményekben, amikor nagy a gáz.

**Comment by renced42** [comment]
@omachtandras 

Bizonyára olvastad az elmúlt napokban az API korlátozással kapcsolatos topicot. Sajnos vannak olyan esetek, amikor bármit választunk az kényelmetlen megoldás, és sajnos vannak olyan szoftverek, amik nagyon nem ésszerűen működnek és sajnos ezek nem egy ügyfélhez vannak kitelepítve. Választani kell hogy vagy az egész rendszert leállítjuk, vagy hagyjuk beszakadni ezek miatt vagy csak annak egy kényelmi szolgáltatását állítjuk meg amíg a káros hatásokat kiszűrjük. Most ez utóbbi történt. Remélhetőleg a korlátozást hamarosan, 1-2 órán belül feloldjuk.

**Comment by csandazoltan** [comment]
Most érte utól magát a probléma.... Mióta ezzel a projekt-el foglalkozom, minden leírásban kerestem a "korlátozásokat" Adott IP cím, percenként/óránként/naponta elküldhető kérések száma. 
Nincs ilyen! 
Na majd most lesz.

Azon mosolyogtam, hogy "még mindig jelentős az 1.0-ás és 1.1-es kérések mennyisége"

**Comment by omachtandras** [comment]
> Bizonyára olvastad az elmúlt napokban az API korlátozással kapcsolatos topicot. 

Igen, olvastam - és hozzá is szóltam -, ahogy a közleményt is, ami kiváltotta, de a közleményben sem volt szó arról, hogy ez is korlátozásra kerül.
Azt látjuk napok óta a logokban, hogy ez is köhög, meg is értem bizonyos szintig, ha korlátozni kell, csak jó lett volna ezt is előre tudni, hogy kezelni tudjuk az ügyfelek problémáit, fel lehessen készíteni a kollégákat az ügyfélszolgálaton arra, hogy mi is van valójában, mit kommunikáljon az ügyfelek felé.

Köszönöm az információt, várjuk a feloldást.

**Comment by vbela75** [comment]
Az a baj ezzel hogy a korlátozásokban sehol nem volt említve az queryInvoiceDigest erre pont ez lett megállítva mint kényelmi szolgáltatás. A 2.11 frissítés óta szépen működött nem lett említve egyszer sem hogy itt baj van miért nem lehet kommunikál ha idióta a user oldal és rángatja a rendszert. Akkor ide is kellene korlát tudok olyan rendszereket amik 5 percenkét letalozzák az összes beállított kulcsot. Naponta 1x töltök pont ezért éjszaka hogy a nappali csúcsidőben terheljem a rendszert. Legyen erre is valami szabályozás.

**Comment by renced42** [comment]
Kedves @omachtandras, @vbela igyekszünk mindent elkövetni, hogy a rendszer rendben kiszolgáljon benneteket illetve minden ügyfelet. Sajnos viszont vannak olyan helyzetek, amikor nem tudjuk, hogy a következő percben mi történik. Sajnos ezeket nem tudjuk előre kommunikálni, ha tudnánk megtennénk ez is egy ilyen nem tervezett helyzet volt.

Kérjük a türelmeteket. Ha a szolgáltatás korlátozás feloldásra kerül jelezni fogjuk.

**Comment by EPluribusUnum** [comment]
@vbela75 , a probléma hogy nem csak kényelmi szolgáltatáshoz kell a queryInvoiceDigest, hanem helyesbítő és sztornó esetén beküldéshez is a modificationIndex helyes meghatározásához. A modificationIndex nem határozható meg feltétlenül csak saját adatbázisból, mert az előzmény lehet egy másik, már lecserélt számlázó adatbázisában amire nincs rálátása a jelenlegi rendszerünknek.

**Comment by omachtandras** [comment]
Még annyi kérésem lenne a jövőre vonatkozóan, hogy gondoljatok arra, hogy most már vannak ügyfeleitek. És azok nem (csak) a fejlesztők, hanem az átlagemberek, akiknek le kell írni, hogy a queryInvoceDigest leállítása olyan következményekkel járhat a szoftverekben, hogy
- nem tudják letölteni a bejövő (szállító) számla adatokat
- nem tudják letölteni a kimenő (vevő) számla adatokat
...
ezért az ezen műveletekre támaszkodó folyamatok esetlegesen nem működhetnek.
Amellett, hogy csökkenhet a Ti HelpDesk hívásaitok száma nekünk is nagy segítség, hogy hivatkozhatunk a NAV hivatalos oldalára és nem megint azt próbáljuk bizonygatni az ügyfeleknek, hogy nem a mi szoftverünk a rossz, hanem bizony itt egy komoly probléma elhárításának ideiglenes mellékhatásáról van szó.

**Comment by vbela75** [comment]
@renced42 köszönjük a munkátokat, csak akikkel baj van azokat próbáljátok kigyomlálni hogy a többiek tudjanak normálisan szolgáltatni. Nekem nem is volt célom a rendszeres lekérdezés naponta 1x letöltök 3-4 ezer számlát 1500 vállalkozásnak és aztán nem bántom a rendszereteket egész nap. :) 
@EPluribusUnum értem hogy ezzel dolgoztok de várjuk egy kicsit és reméljük elindul. A jövöben meg vezessenek ide is korlátot mind a token és status lekérdezésekre.

**Comment by renced42** [comment]
A szolgáltatás korlátozásat 2020.10.16-án 08 óra 55 perckor feloldottuk.

**Comment by NTCA-supporter** [comment]
UPDATE:  A szolgáltatás korlátozásat 2020.10.16-án 08 óra 55 perckor feloldottuk.

**Comment by tkelemen73** [comment]
Nagy jövőbe látók lehetnek odaát:
"UPDATE:  A szolgáltatás korlátozása feloldásra került 2020.10.16-án 10 óra 35 perckor."
Csak az még több, mint egy óra múlva lesz... ;)

**Comment by omachtandras** [comment]
Köszönjük szépen.
