### ISSUE TITLE
v2 API -ban készült számla stornózása v3 API val

### ISSUE THREAD

**Issue by white420** [nav-gov-hu/Online-Invoice#449]
Hogyan lehet v2 API-val készített számlát sztornózni v3 API-val?

a /invoice/invoiceLines/line/lineAmountsNormal/lineVatRate/vatExemption/case és a /invoice/invoiceLines/line/lineAmountsNormal/lineVatRate/vatOutOfScope/case

ágakon bevezetett ÁFA mentességek kódja még nem volt a v2-ban így ha sztornózom v3-ban ABORTEDET kapok
pl: ha az eredeti számlán az Alanyi Mentes AM -el van jelölve a v3 ban ez már nem elfogadott csak az AAM jelölés

**Comment by NTCA-supporter** [comment]
Szia!

Az, hogy v3-as interfészen módosíts/sztornózz/technikai érvényteleníts egy v2-es számlát ugye megengedett.
Viszont nyilván ilyenkor a 3.0-ás xsd-nek kell megfelelned.
Amíg párhuzamosan megy a két főverzió, és nem tudod sehogy megoldani v3-ban, akkor v2-vel tudod sztornózni.
Üdv

**Comment by white420** [comment]
köszönöm a gyors választ, esetleg közzé tudnátok tenni egy listát az eddigi leggyakrabban használt áfa mentesség jelölésére használt "kódokról", így talán a minimálisra lehetne csökkenteni a hibák lehetőségét.
üdv.

**Comment by NTCA-supporter** [comment]
Szia @white420 !
Közben vevezetésre került az UNKNOWN mint lehetőség a case-es adómértékekhez, pont az ilyen esetekre.
Részletek az interfész dokumentációban.
Zárom az issuet.
Üdv
