### ISSUE TITLE
forgalomkorlátozás mire terjed ki?

### ISSUE THREAD

**Issue by vbela75** [nav-gov-hu/Online-Invoice#450]
Nem csak a /v2/queryTransactionStatus és a /v2/tokenExchange lett bevezetve a forgalomkorlátozás. Az észlelem hogy ha v2/queryInvoiceDigest-ben is bejött a 4 mp várakozás be kell vezetnünk az 1 mp szüneteket?

**Comment by renced42** [comment]
Kedves @vbela75 Nem lett bevezetve korlátozás sem a /v2/queryTransactionStatus sem a /v2/tokenExchange operáción.
Azt tudni kell, hogy a v2/queryInvoiceDigest operációt intenzíven használják a számla adatok lekérdezésére (főleg így 20-a környékén), így előfordulhat esetleges minimális várakozási idő növekedés, de az elvárt kiszolgálási időn belül marad. 
A v2/queryInvoiceDigest operáción alapértelmezett védelem van beállítva a múlt heti csütörtöki problémák miatt az operáción, ami a rendszer indokolatlan kérésekkel történő el floodolását akadályozza meg, de egyébként a normál vagy megnövekedett kiszolgálási igényeket nem korlátozza. 
Ez mutatja az is, hogy nem is kaptunk ilyen visszajelzést senkitől, még a nagy "fogyasztóktól" sem.
De az eredeti kérésre válaszolva, ha egy operációra a rate limiting szabály az, hogy 1 kérés/másodperc jöhet, de ezt a kliens nem tartja be, és egy idő után eléri a 60 sec halmazati késleltetést, akkor 1 percet kell várni az újraküldésig.

**Comment by vbela75** [comment]
Kedves @renced42 Én azt tapasztalom múlthét csütörtök óta, hogy a letöltést végző programomon semmit nem változtatva beleesek a rate limit-be. Az eljárásom az, hogy egy IP-ről elindítom a programot 1 szálon 1600 kulcsot letallóz v2/queryInvoiceDigest INBOUND és OUTBOUND irányba. Ez tehát 3200 lekérdezés amelyikben van adat azt elkezdi számlánként az xml-t letölteni. A gyors egymást követő v2/queryInvoiceDigest miatt ha nem teszek közé 2.1 mp várakozást akkor 4 mp kapok rendszeresen de ez nő folyamatosan ha nem lassítok. Ma éjszaka is tökéletesen megkaptam az adatokat csak a lassítással. Eddig le lehetett tölteni kb. 2000 db számlát ezzel a módszerrel óránként most ez jelentősen lecsökkent kb. 800 db jön le óránként.

**Comment by renced42** [comment]
Kedves @vbela75 tudsz egy IP címet mondani?

**Comment by vbela75** [comment]
@renced42  itt nyilvánosan vagy el tudom valahogy küldeni?

**Comment by vbela75** [comment]
Az IP cím:  185.75.194.50

Üdvözlettel:
Várdai Béla
+36203982340

2020.10.21. 9:08 keltezéssel, NTCA-Developer írta:

**Comment by renced42** [comment]
Kedves @vbela75 mekkora az idő intervallum és melyik paraméterben adod ezt át (ins date, issue date) amit lekérdezel? Csak egy adózót kérdezel le vagy többet is?

**Comment by vbela75** [comment]
@renced42  akiket folyamatosan kérek le mert már régen be van állatva a kulcs az 1 nap (előző egész nap) intervallum és ins date-re, ha új kulcs jön be azt 07.01-től jelenleg 10 napos intervallumokra leosztva egymás után (nagyobban time out-os volt  a héten). Múlt hétig 1 napos intervallummal kértem le az új kulcsokat, de akkor ment rendesen nem lassult. Kb. 1.600 adózott kérdezek le napi 1 alkalommal 1 szálon.

**Comment by renced42** [comment]
Kedves @vbela75 Megnéztem. Ha jól látom egyszerre sokszáz adózót kérdezel le amihez sokszáz kapcsolatot építesz fel. Ennek a kiszolgálása viszont limitekbe ütközik, ami majd nem a DDOS kategória. Érdemes lenne ezen az implementáción változtatni. A kapcsolatot egyszer példányosítani és abban indítani a lekérdezéseket. Érdekes, hogy valamikor egyébként ez sikerül a programodnak mert van amikor lényegesen több kérés érkezik be egyszerre, de az is látszik, hogy akkor nem sokszáz kérést indítasz hanem 2-3 adózót csak. Próbáld meg a lekérdezéseket 1 napra szűkíteni és egyszerre 1 adózót kérdezz le a fentiek szerint.

**Comment by nbeeps2** [comment]
@renced42 Világos az, amit írsz és javasolt, viszont érthetetlen ha nincs bevezetve a v2-re limit, akkor hogy lehetséges ennek ellenére, hogy @vbela75 ezt tapasztalja: " 4 mp kapok rendszeresen de ez nő folyamatosan ha nem lassítok"

**Comment by renced42** [comment]
> @renced42 Világos az, amit írsz és javasolt, viszont érthetetlen ha nincs bevezetve a v2-re limit, akkor hogy lehetséges ennek ellenére, hogy @vbela75 ezt tapasztalja: " 4 mp kapok rendszeresen de ez nő folyamatosan ha nem lassítok"
> 
> "Ennek a kiszolgálása viszont limitekbe ütközik": ezek szerint mégis van valamilyen nem publikált limit?

@nbeeps2  Sok olyan beállítás van egy sok rétegből álló rendszerben, amit egyébként nem publikálunk ki és más sem. Próbáljuk megérteni a problémát és próbálunk rajta segíteni. Ezért kérünk egy kis türelmet.

**Comment by vbela75** [comment]
@renced42 a kapcsolatokat nem indítom párhuzamosan mindig csak egy lekérdezés fut egyszerre és ha véges csak utána indítom a következőt. Először beolvasom a számlák listáját v2/queryInvoiceDigest majd ha van benne adata akkor a v2/queryInvoiceData letöltöm egyesével a számla adatokat. Az igaz hogy av2/queryInvoiceData között nem tarok szünetet de a v2/queryInvoiceDigest igen. Mellékelek egy képet 1.1 mp állítottam az időközt és ezt kapom: 
![válaszidő](https://user-images.githubusercontent.com/70314733/96704823-cc621680-1394-11eb-8e6a-0f364305e659.jpg)
Eszem ágában sincs DDOS támadást indítani. :)

**Comment by vbela75** [comment]
@renced42 még annyit szerettem volna hogy kb. 2 óra alatt indítok 3600 db v2/queryInvoiceDigest és kb 4000 db v2/queryInvoiceData ez összesen max 8000 db hívás 2 óra alatt vannak ennél nagyobb lekérdezők biztosan a rendszerben. 😊

**Comment by EnokhSys** [comment]
Kedves @renced42,

szeretném megkérdezni, hogy amennyiben valamely ip-cím forgalomkorlátozásra kerül az éles rendszerben, ez azt jelenti, hogy a tesztrendszert is csak késleltetve tudja elérni? Tehát tulajdonképpen a layer, ahol a forgalomkorlátozás be van vezetve, az a tesztrendszer felé is szűri a forgalmat?

**Comment by renced42** [comment]
Kedves @EnokhSys 
A teszt rendszer és az éles rendszer egymástól független ezen a téren, tudomásom szerint.
Annyi azonosság lehet, hogy globális beállításokat a lehető leghasonlóbb működés miatt (PL.: V1 végpont forgalomkorlátozás), mindkét síkon beállíthatják a kollégák.

**Comment by EnokhSys** [comment]
> Kedves @EnokhSys
> A teszt rendszer és az éles rendszer egymástól független ezen a téren, tudomásom szerint.
> Annyi azonosság lehet, hogy globális beállításokat a lehető leghasonlóbb működés miatt (PL.: V1 végpont forgalomkorlátozás), mindkét síkon beállíthatják a kollégák.

Kedves @renced42,

köszi szépen a választ. Azért kérdezem, mert egy nagyon furcsa hibajelenség ügyében nyomozok tegnap éjjel óta, amely csak az egyik partneremnél jelentkezett, és csak a NAV OnLine számla kommunikációt érintette. Leírom a hibajelenséget, hátha van ötleted:
- tegnap este, 19:36-kor a partnerem készített egy számlát, amit a rendszer megpróbált beküldeni a NAV OnLine Számla rendszerébe, de a tokenrequestre nem érkezett válasz, ezért értesített engem. A requestId: "2020V000109026193625"
- én is megpróbáltam beküldeni a számlát 22:23-kor, majd 22:34-kor, de ezekre sem érkezett válasz. Ismét megpróbáltam 00:35-kor, erre végül érkezett válasz, ennek a kérés-válasznak a requestId értéke: "2020V000109027003553". A kapott tokennel a rendszer meghívta a ManageRequest-et, de erre már szintén nem érkezett válasz, tehát nem is kaptam vissza a "transactionId"-t. 
- a későbbiek során több alkalommal megpróbáltam lekérdeztetni QueryInvoiceDataRequest-el a számlát, hogy egyáltalán bement-e a NAV rendszerébe és milyen tranzakció azonosítóval, de egyik kérésre sem kaptam választ.
- éjszaka több alkalommal végigellenőriztem a partnerem internetkapcsolatát, minden honlapot meg tudtam nyitni, tudtam kapcsolódni az MNB szerverhez is, tudtam kommunikálni az EKAER szerverével is ugyanolyan gyorsan, mint máskor. Egyedül a NAV OnLine szerveréhez történő kapcsolódásra nem jött válasz, akár a v2-es élest próbáltam, akár a v3-as tesztszervert. Ezen kívül a NAV OnLine Számla honlapjának a "Hírek" része nem akart betöltődni, vagy pedig borzalmasan lassan és folyton "homokórázott".
- ma reggel 8:58-kor ismét megpróbáltam beküldeni a számlát, és most már minden gyors volt mint máskor, a számla hibátlanul fel is ment, és a feldolgozási igazolást is megkaptam róla.  

Naszóval ezügyben pörgök, de nem azért, mert mazochista vagyok, hanem mert ez egy ismeretlen, furcsa hiba, amelyet még nem tapasztaltam, és amelyről még nem tudom, hogy a partnerem tűzfal-szűrése, vagy internetszolgáltatói DNS probléma, vagy valamilyen NAV szűrés okozta.

**Comment by EnokhSys** [comment]
Kedves @renced42,

ha nálatok nincs szűrés IP-címre, hogy magyarázod meg az alábbi, legfrisebb tesztet, amelyről ha kéred, elküldhetem a RQID-ket és TRID-ket:

A). 
Megpróbáltam beküldeni két számlát 21:27-kor, **a v2 éles rendszerbe**, az ügyfelem IP-címéről:
- az első számla megkapta a tokent, a beküldés sikerült, de már a statusreq-re nem jött válasz.
- a második számla még csak nem is kapott választ a tokenrequestre

B). 
Megpróbáltam beküldeni két számlát 21:45-kor, **a v3 teszt rendszerbe**, szintén az ügyfelem IP-címéről
- mindkét számla még csak nem is kapott választ a tokenrequestre
Megpróbáltam beküldeni ugyanezt a két számlát 21:47-kor a v3 teszt rendszerbe, de már egy másik IP-címről
- mindkét számlát másodpercek alatt befogadta a NAV szervere

Itt egyértelmű, hogy konkrét IP-címet blokkol/lassít le a NAV tűzfala, vagy pedig az OnLine Számlán bevezetett új szűrés.

**Comment by renced42** [comment]
Kedves @EnokhSys 
A másik issueban #491 most tracingoltuk végig a fejlesztő kollégával a kérését, (reggel folytatjuk) szerinted, ha tudom, hogy van szűrés a rendszerben (márpedig ha van, akkor azt én biztosan tudom), akkor órákat töltök azzal, hogy segítsek kideríteni mi történik? Valamiért nem kaptok választ és azt kell kideríteni, hogy miért. 
Ez ugyan az az ügyfél?

**Comment by EnokhSys** [comment]
> Kedves @EnokhSys
> A másik issueban #491 most tracingoltuk végig a fejlesztő kollégával a kérését, (reggel folytatjuk) szerinted, ha tudom, hogy van szűrés a rendszerben (márpedig ha van/lenne, akkor azt én biztosan tudom/tudnám), akkor órákat töltök azzal, hogy segítsek kideríteni mi történik? Valamiért nem kaptok választ és azt kell kideríteni, hogy miért.
> Ez ugyan az az ügyfél?

Kedves @renced42, nem azt mondtam, hogy tudsz róla, vagy, hogy ez szándékos lenne. Hanem azt, hogy van valamilyen ip-szűrés a NAV oldalán. 
Most figyelj, elvégeztem ugyanazt a tesztet, mint @tacshu a https://github.com/nav-gov-hu/Online-Invoice/issues/491 topicban, és én is ugyanazt az eredményt kaptam.

C teszt).
Megpróbáltam beküldeni egy számlát, a v3 teszt rendszerbe, szintén az ügyfelem IP-címéről, az alábbi módokon:
- első próbálkozásra nem kaptam választ a tokenRequestre
- a második próbálkozást úgy csináltam, hogy szándékos hibát tettem a kérésbe, a "softwareId" helyett "software"t küldtem, amelyre 10 mp.-en "SCHEMA_VIOLATION" válasz érkezett:
" Request body contains on line: [19] and column: [15] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/api":software}'. One of '{"http://schemas.nav.gov.hu/OSA/3.0/api":softwareId}' is expected.]"

**Comment by renced42** [comment]
Kedves @EnokhSys Nem tudom, ez biztos nem normális működés. De továbbra sem gondolom, hogy ez szűrés vagy tiltás eredménye, főleg, hogy ha rossz, amit beküldesz arra meg kapsz választ. Holnap reggel többet fogunk tudni.

Még egy kérdés, mi a környezet amiből behívsz? Windows/Linux curl, c#, SAP vagy micsoda?

**Comment by EnokhSys** [comment]
> Kedves @EnokhSys Nem tudom, ez biztos nem normális működés. De továbbra sem gondolom, hogy ez szűrés vagy tiltás eredménye, főleg, hogy ha rossz, amit beküldesz arra meg kapsz választ. Holnap reggel többet fogunk tudni.

Ne értsd félre, nem hibáztatlak, de én 24 órája szinte csak ezzel a problémával foglalkozom, alig aludtam valamit. Tudom, hogy nem akarattal csináljátok, de itt nagyon félrement valami, méghozzá ip-cím alapján.
 
> Még egy kérdés, mi a környezet amiből behívsz? Windows/Linux curl, c#, SAP vagy micsoda?

Windows 7/Windows Server, és curl.exe.

**Comment by EnokhSys** [comment]
Kedves @renced42 , 

még egy fontos infó segítségként: ha néhány óráig nem próbálkozom az ügyfelem Ip-címéről, az első két számla problémamentesen bemegy és feldolgozásra kerül, de a harmadik számlánál elkezdődik a "néma szerver" állapot.

**Comment by renced42** [comment]
@EnokhSys A curl milyen verzió?

**Comment by EnokhSys** [comment]
> @EnokhSys A curl milyen verzió?

curl 7.58.0 (i386-pc-win32) libcurl/7.58.0 OpenSSL/1.1.0g (WinSSL) zlib/1.2.11 WinIDN libssh2/1.8.0 nghttp2/1.30.0
Release-Date: 2018-01-24

**Comment by renced42** [comment]
Kedves @EnokhSys  kérlek olvasd ezt meg #300

**Comment by EnokhSys** [comment]
> Kedves @EnokhSys kérlek olvasd ezt meg #300

Kedves @renced42, 
elolvastam, ha jól értem a lényege az volt, hogy abban az issue-ban a curl frissítése megoldotta a problémát.
Feltettem a legfrissebb curl-t (7.73.0), nem segített.

**Comment by EnokhSys** [comment]
> Akkor még annyit, hogy ha parancssorból meghívod a curl-t akkor mit látsz a konzolon?

Hogy érted, hogy mit látok? Csak arra vagy kíváncsi, hogyha kiadom a "curl.exe" parancsot, akkor mit látok, vagy pedig úgy, hogy parancssorból hívjam meg a NAV számla feladást?

**Comment by renced42** [comment]
Igen írasd ki a verziót és add fel parancssorból légyszives ha van olyan kapcsoló akkor minél beszédesebb legyen.

**Comment by renced42** [comment]
curl -S -v kiírat mindent

**Comment by EnokhSys** [comment]
Kis türelmet...

**Comment by EnokhSys** [comment]
Kedves @renced42,

két tesztet csináltam, itt vannak az eredmények:
- a bal oldali DOS ablakban látod azt, amikor a tokenrequest-ben helyesen szerepel a "softwareId"
- a jobb oldali DOS ablakban látod azt, amikor a tokenrequest-ben helytelenül, "software" szerepel

![image](https://user-images.githubusercontent.com/72287954/97372178-4cb3da80-18b3-11eb-9d38-4709757d2fdf.png)

**Comment by renced42** [comment]
request id-t küldenél?

**Comment by EnokhSys** [comment]
pillanat...

**Comment by EnokhSys** [comment]
A jobb oldali ablaké: 2020V000014228001152
A bal oldali ablaké: 2020V000013427235727

**Comment by renced42** [comment]
Megnéztem egy korábbi programomat abban ez volt:
$ curl
 -X POST
 -d @console_token.xml
 -H "Accept:application/xml"
 -H "Content-type:application/xml" 

próbáld már meg ezzel a kapcsoló settel + insecure http 1.1 nem kell ha anélkül is megy

**Comment by EnokhSys** [comment]
> Megnéztem egy korábbi programomat abban ez volt:
> $ curl
> -X POST
> -d @akarmi.xml
> -H "Accept:application/xml"
> -H "Content-type:application/xml"
> 
> próbáld már meg ezzel a kapcsoló settel + insecure http 1.1 nem kell ha anélkül is megy

Ezt csak hajnali 2-3 óra között tudnám kipróbálni, most mennem kell egy időre. 
Az insecure kapcsoló azért kell, mert keresi a tanúsítványt, semmi kedvem tökölni vele.

**Comment by renced42** [comment]
ok,  a http1.1 nem kell :)

**Comment by EnokhSys** [comment]
> ok, a http1.1 nem kell :)

Akkor kell a - http1.0, de ez sem jelent problémát.

**Comment by renced42** [comment]
@EnokhSys 
Letöltöttem a curl-t zip formátumban (https://curl.haxx.se/windows/) windows alá kicsomagoltam és a bin könyvtárból ezt futtattam (-k val vagy anélkül ugyanaz) :
curl -s -v -k -X POST -d c:\temp\x.xml -H "Accept:application/xml" -H "Content-type:application/xml" https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3/tokenExchange

C:\temp\curl-7.73.0-win64-mingw\bin>curl -s -v -X POST -d c:\temp\x.xml -H "Accept:application/xml" -H "Content-type:application/xml" https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3/tokenExchange
* Uses proxy env variable no_proxy == '192.168.99.100'
*   Trying 84.206.52.71:443...
* Connected to api-test.onlineszamla.nav.gov.hu (84.206.52.71) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: C:\Temp\curl-7.73.0-win64-mingw\bin\curl-ca-bundle.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=HU; L=Budapest; O=Nemzeti Adó- és Vámhivatal; CN=*.onlineszamla.nav.gov.hu
*  start date: Jan 16 08:04:03 2020 GMT
*  expire date: Jan 15 08:04:03 2022 GMT
*  subjectAltName: host "api-test.onlineszamla.nav.gov.hu" matched cert's "*.onlineszamla.nav.gov.hu"
*  issuer: C=HU; L=Budapest; O=NetLock Kft.; OU=Tanúsítványkiadók (Certification Services); CN=NetLock Expressz (Class C) Tanúsítványkiadó
*  SSL certificate verify ok.
> POST /invoiceService/v3/tokenExchange HTTP/1.1
> Host: api-test.onlineszamla.nav.gov.hu
> User-Agent: curl/7.73.0
> Accept:application/xml
> Content-type:application/xml
> Content-Length: 13
>
* upload completely sent off: 13 out of 13 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/xml;charset=UTF-8
< Content-Length: 415
< Date: Wed, 28 Oct 2020 00:07:24 GMT
< X-Via: epsbicxmlapi2.eszamla-edu.local
< X-Server: backend_invoiceService-v3-tokenExchange/XML_kpx_B1
< Strict-Transport-Security: max-age=31536000; includeSubDomains
<
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><GeneralExceptionResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data"><funcCode>ERROR</funcCode><errorCode>INVALID_REQUEST</errorCode><message>Érvénytelen kérés!</message></GeneralExceptionResponse>* Connection #0 to host api-test.onlineszamla.nav.gov.hu left intact

**Comment by hszdevelop** [comment]
Bocsánat, hogy beleszólok:
a "-d c:\temp\x.xml" paraméter magát a paramétert veszi POST tartalomnak (erre utal az "upload completely sent off: 13 out of 13 bytes"). Ehelyett a "-d @c:\temp\x.xml" kell, így kezelné fájlként, abból olvassa be.

**Comment by EnokhSys** [comment]
> @EnokhSys
> Letöltöttem a curl-t zip formátumban (https://curl.haxx.se/windows/) windows alá kicsomagoltam és a bin könyvtárból ezt futtattam (-k val vagy anélkül ugyanaz) :

Kedves @renced42 oké, de ezzel az eredménnyel mit kezdjek? Vagy a parancssor miatt tetted be, mintának?

**Comment by EnokhSys** [comment]
Kedves @renced42 , de ugye egy FONTOS szempontot szem előtt tartasz az elemzések során: a hiba nem jelentkezik, ha más ip-címet használok, nem pedig az ügyfélnek az ip-címét. 

Akkor teljesen problémamentesen megy minden, pedig a gép, az op.rendszer, a környezet, a parancssor, a tesztadat stb egyszóval minden ugyanaz, kivéve az ip.címet. Ezen eltöprengtél?

**Comment by EnokhSys** [comment]
@renced42 Nem kellene inkább abba az irányba elvinni a hibakeresést, hogy a legelső pillanattól kezdődően amikor megérkezik a HTTPPost utasítás, megnézitek, hogy mi történik az egyik ip cím esetén, és mi történik a másik ip cím esetén? Megbeszélhetünk egy időpontot, amikor ezt így leteszteljük.

**Comment by EnokhSys** [comment]
Ma reggelre megjavult minden, az éles szerver is válaszol, a tesztszerver is, ez utóbbinak beküldtem néhány perc alatt 35 db. számlát.

Hmm... kedves @renced42, most akkor hogy is állunk azzal a kijelentéssel, hogy nincs ip-cím szűrés ill. azzal, hogy "a NAV nem korlátozza a számlabeküldést", ami csekély 25 órámba került?

**Comment by NTCA-supporter** [comment]
Szia @EnokhSys !
Nagyon jól állunk ezekkel a kijelentésekkel. Semmilyen hálózati beállításon nem változtattunk. Nézzük a logokat, keressük a nyomokat, és közben örülünk, hogy rendbejött a működés.
Kérlek ezeket a felvetéseket mellőzd, mi sem hobbiból foglalkozunk a témával!
Üdv

**Comment by renced42** [comment]
> Hmm... kedves @renced42, most akkor hogy is állunk azzal a kijelentéssel, hogy nincs ip-cím szűrés ill. azzal, hogy "a NAV nem korlátozza a számlabeküldést", ami csekély 25 órámba került?

Kedves @EnokhSys ne keverjük össze a fogalmakat, mert félreértésre adhat okot. Más, hogy valami, valami miért nem működik és megint más, ha szándékos bannolás van. 

Mégegyszer megerősítem - és ha keresztre feszítetek -, akkor sem fogok mást mondani, NINCS KORLÁTOZÁS ÉS IP SZŰRÉS a RENDSZEREN BEÁLLÍTVA, ami akadályozza a számla beküldést és annak státusz lekérdezését! 

Még egy dolgot kérek, küld meg kérlek azt az IP címet és a küldés PONTOS idejét (ami nem sikerült) éles és teszt rendszerre vonatkozóan és még megnézetjük a hálózati logokat. Kérlek, hogy a témát a #491 es topicba folytassuk, mert mindenképpen szeretnénk kideríteni, hogy mi történt, bármi is legyen az.
Köszi!

**Comment by EnokhSys** [comment]
Kedves @NTCA-supporter és @renced42!

Mindkettőtöknek egyszerre válaszolok. Elhiszem, hogy nem szándékosan történt ami történt, de kérlek válaszoljátok meg logikusan az alábbi kérdést, amelyre fentebb megtaláljátok az átalam betett DOS képernyős bizonyítékokat:

**Hogy lehet az, hogy ugyanabból a szerver és szoftverkörnyezetből továbbá ugyanarról az ip.címről és csupán néhány másodperces időkülönbséggel indított "TokenRequest" kérés abban az esetben azonnal kapott választ a NAV v3-as tesztszervertől, ha a "softwareId" tag helyett hibásan "software" tagot használtam, míg abban az esetben, ha helyesen használtam a "softwareId" tagot, akkor nem jött semmi válasz?** 

Mert ez azt jelenti, hogy még csak azt sem lehet feltételezni, hogy esetleg az internetszolgáltatónál lett volna valami szűrés vagy probléma (pl. DNS hiba), mert akkor egyik kérésre sem kaptam volna választ a NAV szerverétől.

És ne mondjátok azt, hogy curl verzió meg Windows, meg bármi más, mert hangsúlyozom: minden ugyanabból a szoftverkörnyezetből, ugyanarról az ip.címről indult, a különbség a két kérés között csupán az a 2 byte eltérés volt a "TokenRequest.xml"-nek a "softwareId" szegmensében. És ezt a tesztet még csak nem is én találtam ki, hanem tegnap olvastam a @tacshu által indított, https://github.com/nav-gov-hu/Online-Invoice/issues/491 issue-ban, és gondoltam kipróbálom én is. Bejött.

Na erre kellene logikus, elfogadható magyarázatot találnotok. 

> Még egy dolgot kérek, küld meg kérlek azt az IP címet és a küldés PONTOS idejét (ami nem sikerült) éles és teszt rendszerre vonatkozóan és még megnézetjük a hálózati logokat. Kérlek, hogy a témát a #491 es topicba folytassuk, mert mindenképpen szeretnénk kideríteni, hogy mi történt, bármi is legyen az.

@renced42 Oké, folytassuk ott, én is nagyon szeretném kideríteni, hogy mi történt, mert ez egyértelműen felvet néhány vizsgálati kérdést. Szívesen küldök ip-címet, de nem nyilvánosan, hanem levélben. Bocs, de nem szeretném a partnerem ip-címét egy nyilvános fórumon beírni az engedélye nélkül. Az én e-mail címemet ki tudod olvasni valamely tokenkérés "software" csoportjából, ha erre küldesz egy e-mailt, válaszolok rá.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ez zárható? Tapasztaltok még bármi problémát?
Üdv

**Comment by tacshu** [comment]
Reszemről rendben van már. Nem tapasztalok semmi ilyesmit.
Üdvözlettel
