### ISSUE TITLE
queryTransationList - tranzakciók lekérdezése

### ISSUE THREAD

**Issue by Mocsa1974** [nav-gov-hu/Online-Invoice#452]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Azt szeretném kérdezni, hogy a közeljövőben lesz-e lehetőség arra, hogy a queryTransactionList operáció csak a kérésben megadott requestStatus-al rendelkező tranzakciók listáját adja vissza?

Válaszukat előre is köszönve,
Mocsári Péter

**Comment by NTCA-supporter** [comment]
Szia @Mocsa1974 !

Értem az igényt, bár azért ezt nem érzem olyannak, hogy request paraméterként szükséges lenne bevezetni.
Rákérdezek nagyobb körben.
Üdv

**Comment by Mocsa1974** [comment]
Köszönöm a gyors választ!
Csak azért kérdeztem, mert úgy látom hogy a queryTransactionList lapozható formában adja vissza a tranzakciók listáját (talán egy lapon 30 elemet). Igy ha egy teljes hónap tranzakciói közül kell megkeresnem a FINISHD státuszúakat és ha a hónapban volt mondjuk 240 tranzakció amiből csak 3 van FINISHED státuszban a többi NOTIFIED akkor a szerver felé lehet hogy el kell küldenem legrosszabb esetben 8 kérést, hogy megtudjam annak a 3 tranzakciónak az azonosítóját. Ha el tudnám küldeni a request-ben hogy milyen státuszó tranzakciókra vagyok kíváncsi akkor fenti esetben elég egy request-et küldenem. Igy a szerver terhelése is csökkenne.

Elnézést ha rosszul látom a queryTransactionList operáció működését és van valami egyszerűbb módszer arra, hogy megkapjam a FINISHED státuszú tranzakciók listáját.

Köszönöm.

**Comment by NTCA-supporter** [comment]
Értem, én is erre gondoltam.
Viszont szerintem valós üzleti igény csak az lenne, hogy azokat ne adjuk vissza, amik már NOTIFIED-ban vannak.
Tehát csak egy flaggel jelölni, hogy add vissza az összeset, vagy add vissza azokat ami nem NOTIFIED.
Így ok? Továbbra sem ígérek semmit, csak hogy utánajárok :) 
Üdv

**Comment by Mocsa1974** [comment]
Köszönöm.
Nekem már a Te általad leírt megoldás is előrelépés lenne, de az álláspontom szerint több funcionalitást lehetne elérni ha mi tudnánk megadni azt a státuszt amire kíváncsiak vagyunk. Az onlineszamla webes felülete lehetőséget biztosít a tranzakciók ilyen lekérdezésére. Ezért gondoltam hogy a backend fel van készítve erre.

**Comment by NTCA-supporter** [comment]
Szia @Mocsa1974 !
Sikerült megvalósítani a kérésed, lehet szűrni státuszra. Részletekért lásd XSD, és interfész dokumnetáció.
Üdv
