### ISSUE TITLE
TrasactionId lekérdezését és pótlását melyik operációval célszerű elvégezni?

### ISSUE THREAD

**Issue by EnokhSys** [nav-gov-hu/Online-Invoice#455]
Azt szeretném kérdezni, hogy amennyiben akár a felhasználó oldalán, akár a NAV oldalán olyan hálózatkimaradás lép fel, hogy a ManageInvoiceResponse épp nem érkezik meg, és ezáltal a transactionId nem áll rendelkezésre a számla státuszának lekérdezéséhez, akkor melyik operációt célszerű használni annak pótlásához/azonosításhoz?
- a /queryInvoiceData operációt, vagy
- a /queryTransactionList operációt

Azért kérdezem ezt, mert én a /queryInvoiceData operációt használom, de úgy rémlik, mintha korábban azt olvastam volna valamelyik topikban, hogy ez nem biztonságos. Ugyanis, ha a NAV oldalán történik valami lassulás, akkor a /queryinvoiceData nem mindig tudja visszaadni rövid időn belül a transactionId-t, viszont a queryTransactionList operáció által visszaadott transactionId-k ill. az azokhoz tartozó felhasználónév és beküldési idő alapján beazonosíthatom, hogy mely számlához tartozik.

Bocs a kérdésért, próbáltam megkeresni, hogy melyik topikban olvashattam, de sajnos nem találom.

**Comment by renced42** [comment]
Használd a /queryTransactionList operációt

**Comment by EnokhSys** [comment]
> Használd a /queryTransactionList operációt

Köszi szépen, a v3-ban sort kerítek rá. Addig is egy fontos kérdés: a legrosszabb esetben kb. mennyi idő alatt kapja meg a számla a transactionId-t, tehát amennyiben szolgáltatás-késés van, kb. mennyi időt érdemes várni a  /queryInvoiceData operáció elindításával?

**Comment by nbeeps2** [comment]
@EnokhSys szerintem ezt a topikot kerested: https://github.com/nav-gov-hu/Online-Invoice/issues/386

**Comment by EnokhSys** [comment]
> @EnokhSys szerintem ezt a topikot kerested: #386

@nbeeps2 Köszi szépen, erről van szó, kifejezetten az általad is említett 4-es, 5-ös pontról, tudtam, hogy valahol olvastam. Zárom is a topicot, mert mindenre választ kaptam.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Úgy látom ez zárható, mert már létezik a topic.
Üdv

**Comment by EnokhSys** [comment]
@NTCA-supporter Bocs, elfelejtettem lezárni, köszi szépen!
