### ISSUE TITLE
[DOC] Közmű elszámoló számlájának adatszolgáltatása, modifyWithoutMaster flag

### ISSUE THREAD

**Issue by szako** [nav-gov-hu/Online-Invoice#456]
**A hibás dokumentum neve**
Online Szamla_interfesz specifikáció_HU_v3.0 / 2020.10.01-es verzió.

**Oldalszám**
151  / 152

**A dokumentációs hiba leírása**
2.8 Közmű elszámoló számlájának adatszolgáltatása fejezeten belül:

_korábbi időszaki számlák módosításait pedig értelemszerűen kell megadni:
o az ```<originalInvoiceNumber>``` a részszámla sorszáma,
**o a ```<modifyWithoutMaster>``` értéke false,**
o a ```<utilitySettlementIndicator>``` értéke false vagy nem megadott
o a ```<modificationIndex>``` értéke az adott részszámla soron következő módosításának indexe._

A kiemelt részben a modifyWithoutMaster tag mindig false? Mit kell megadni akkor, ha olyan korábbi részszámlát módosítunk, amiről nem történt még adatszolgáltatás? Köszönöm.

**Comment by jozanesz** [comment]
Hát igen, [itt ](https://github.com/nav-gov-hu/Online-Invoice/issues/299#issuecomment-692527958)még mást írtak. Ezen az *értelemszerűen*en már csak kínomban tudok mosolyogni. Lásd  még #439.

**Comment by szako** [comment]
Köszi a linket! Akkor dokumentációs hiba, volt is ilyen, lesz is ilyen. Kijavítják és mehetünk tovább.

**Comment by jozanesz** [comment]
Várjuk meg a hivatalos megerősítést, mert a specifikáció későbbi kiadású, mint a linkelt bejegyzés.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Valóban nem helyes a fix false érték. A módosításnál annak megfelelően kell tölteni, hogy történt-e adatszolgáltatás a hivatkozott számláról.
Javítani fogjuk, addig maradjon nyitva az issue.
Üdv

**Comment by gzsolnay** [comment]
Sziasztok,

Részünkről is nagyon megköszönnénk, ha az @NTCA-supporter tenne fel példa XML-eket.
Számunkra érdekes lehet, ha az elszámoló számla végösszege pozitív, ha nulla és ha negatív (több a résszámlákban elszámolt fogyasztás, mint, a valós). 
...és ha ezeknek az elszámolóknak a stonójáról, módosításáról is kapnánk 1-1et, az már csak hab lenne a tortán.

Előre is köszönjük!

üdv

**Comment by NTCA-supporter** [comment]
Javítottuk a leírást.
Zárom az issuet, köszi a megjegyzést mégegyszer.
Üdv
