### ISSUE TITLE
[Q&A] Technikai érvénytelenítés visszamenőleg. 

### ISSUE THREAD

**Issue by janosnad** [nav-gov-hu/Online-Invoice#457]
Sziasztok!
Kérlek segítsetek a következő problémában: 
A rendszer több árfolyamot használ (Áfa szerinti és Számviteli árfolyam,stb). Emiatt egyes devizás számlák esetekben a LineNetAmountHUF (ami alapesetben a számlán meg sem jelenik) nem az Áfa szerinti árfolyamon került beküldésre. A számlán egyébként szereplő vatRateVatAmountHUF és a invoiceNetAmountHUF azonban már megfelelő volt. WARN: INCORRECT_SUMMARY_DATA_INVOICE_VAT_RATE_VAT_AMOUNT_HUF
A fő probléma az, hogy 2018 és 2019-ben is van 9db számla ilyen jellegű számlánk.

Kérdésem az lenne, hogy a számlák technikai érvénytelenítése a fent jelzett esetben szükséges -e?
Amennyiben szükséges, akkor milyen dátumig visszamenőleg kell az érvénytelenítést elvégezni?
Későbbiekben lesz-e valami tervezett korlát, hogy a problémás számlákat milyen dátumig visszamenőleg kell javítani (figyelembe véve a jövőbeni tervet miszerint a NAV kiküldi az ÁFAbevallás tervezeteket)?

**Comment by NTCA-tax** [comment]
Ez egyértelműen adatszolgáltatási hiba, melyet az NGM rendelet alapján a hiba észlelésétől számított 3 munkanapon belül kell javítani. A jogszabály nem tartalmaz olyan korlátozást, hogy meddig visszamenőleg kell a hibás adatszolgáltatást javítani, kizárólag a javítási kötelezettséget írja elő. Számomra nem ismert, hogy a visszamenőleges javítás korlátozására jogszabály módosítási törekvés lenne.

**Comment by janosnad** [comment]
Köszönöm a választ.
