### ISSUE TITLE
[Q&A] queryTaxpayer incorporation tag hiányosság

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#458]
A queryTaxpayer operáció a 3.0-ban bővült az incorporation taggal, aminek értéke lehet ORGANIZATION (gazdasági társaság) vagy  SELF_EMPLOYED (egyéni vállalkozó). Sajnos azonban továbbra sem tudom megkülönböztetni az egyéni vállalkozót az adószámos magánszemélytől.  Tehát a taxpayerName azt adja vissza, hogy Kovács Péter akkor is, ha egyéni vállalkozóról vagy ha adószámos magánszemélyről van szó. Az incorporation tagot tehát ki kellene bővíteni egy 3. értékkel (adószámos magánszemély), így tudnám, hogy a Kovács Péter neve mögé odategyem az "e.v." jelzést vagy sem.

**Comment by NTCA-supporter** [comment]
Szia @nbeeps2 !
A törzsadataink között nem áll rendelkezésre ez az információ.
Ha a jövőben meglesz esetleg, akkor visszatérhetünk erre. Ezt sajnos nem tudom megmondani, hogy lesz-e ilyen jellegű adatkör bővítés.
Üdv

**Comment by nbeeps2** [comment]
@NTCA-supporter Értem. Igazából viszont így nem látom értelmét, hogy ezt mire lehet használni. Mert az adószámos magánszemély adószámára is azt adja vissza, hogy egyéni vállalkozó, ami egyértelműen HAMIS. Tehát igazából, ha ORGANIZATION-t kapok vissza, akkor biztos lehetek benne, hogy gazdasági társaságról van szó, ha pedig a másik értéket, az lehet egyéni vállalkozó vagy adószámos magánszemély is. Ez hol/mire lehet hasznos? Hol lehet nekem érdekes, hogy az adószám alapján, akit visszakaptam az gazdasági társaság-e vagy sem?

**Comment by NTCA-supporter** [comment]
Szia @nbeeps2 !
A törzsadatok körének bővítéséről lesz egyeztetés, ott felvetem ezt is, mint igényt.
Ígérni nem tudok semmit, ez már nem annyira a mi hatáskörünk, de igyekszünk.
Üdv

**Comment by NTCA-supporter** [comment]
Szia @nbeeps2 !
Kibővítettük a típust, lásd XSD és dokumentáció.
Az alkalmazás is elérhető lesz a hét második felében, ami már az új értéket is vissza tudja adni.
Zárom az issuet, köszi az igényt, jogos volt :)
Üdv
