### ISSUE TITLE
[Q&A] 3.0 mire jó a notification tag?

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#459]
_"A notification csomópontot a NAV a jövőben egyéb, API hívásokban értelmezhető tájékoztató
üzenetek közlésére fogja használni, kulcs-érték struktúrában"_
Ez eléggé ködös megfogalmazás, esetleg lenne valami konkrét példa, hogy itt mire lehet számítani?
a resultypeban már eleve szerepelt egy kód és egy üzenet mező, eléggé értelmetlennek tűnik így látatlanban még egy ilyen párosítás, vagyis egy hiba/figyelmeztető üzenethez minek két kód és két szöveg?

Mekkora probléma, ha nem kötöm be egyáltalán? Ezért kéne tudnom, hogy itt mi várható....

**Comment by NTCA-supporter** [comment]
Szia @nbeeps2 !
Egyelőre még nincs töltve semelyik response-ban sem.
Tervezünk bele olyat, hogy pl. tesztrendszer esetén kitöltjük:
ENVIRONMENT -> TEST

De amint lesz ebből megvalósítás, jelezni fogjuk és dokumentációban is kiadjuk.
Üdv

**Comment by NTCA-supporter** [comment]
Ezt zárom, egyelőre nincs tölve semelyik operációnál. Ha lecsengett minden asap fejlesztés, majd visszatérünk rá.
Üdv
