### ISSUE TITLE
[Q&A] Miért hiányoznak a pénztárgépes számlák az adatszolgáltatásból?

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#460]
Az ÁFA tv 10.sz. mellékletében foglalt adatszolgáltatási elvárás minden számlázó programra kiterjedően szabályozza a számlakibocsátói adatszolgáltatást.
Miért nem láthatók az adatszolgáltatás között a pénztárgéppel kiállított számlák?
A törvényi előírás arra is kiterjed, hiszen azokat a számlákat is "számlázó program készíti"
Számomra  jogilag értelmezhetetlen a "pénztárgéppel készült számla" megkülönböztetése. Ennyi erővel lehetne "mobiltelefonnal készített számla" és "tablettel készített számla" vagy "esztergagéppel készített számla" továbbá "Intel processzorral", vagy akár "DDR4 memóriával készített számla" -ról beszélni.
A pénztárgépben is számlázó program van, tehát ugyanazoknak az adatszolgáltatási elvárásoknak kellene megfelelniük.
Mivel nem felelnek meg, ezért a használatuk aggályos.  
Nincs ilyen a törvényben, hogy "számlázó programmal készített számla, kivéve, ha a számlázó program pénztárgépen, vagy gereblye nyélen fut."

**Comment by bakter80** [comment]
a pénztárgépen kiállított számlák az online pénztárgép rendszerbe mennek.
a dupla adatszolgáltatás miatt nem jelentik az online számla rendszerbe.
a probléma inkább az, hogy jelenleg nem kerülnek át az online számla rendszerbe, így nem tudjuk lekérdezni.
mondjuk a megyekódot se bírták megoldani már kb 4 hónapja, úgyhogy semmi remény

**Comment by renced42** [comment]
Kedves @Macskafarka, jogos a kérés, hogy egy felületen minden számla látható legyen. Ebben mindenki egyet ért és ezért is van már csőben a tervezése/fejlesztése. Mivel az OPG-s adatok egy teljesen más rendszerben, más szemléletű adatstruktúrában vannak, kell egy kis igazítás. Az információim szerint pár hónapon belül ezek az adatok is lekérdezhetők lesznek.
Ha a válasz elfogadható, akkor kérlek zárd az issuet. Köszönöm szépen!

**Comment by Macskafarka** [comment]
@renced42 Köszönöm a választ. Lezárom.
