### ISSUE TITLE
Új jelszó kérése a teszt rendszeren

### ISSUE THREAD

**Issue by szecsenyizoltan** [nav-gov-hu/Online-Invoice#461]
Nem tudok belépni a teszt rendszerre. Azon felhasználóim amiket elmentettem egyikére sem tudok jelszó emlékeztetőt kérni.
Az alábbi üzenetet kapom:
FORGOT_PASSWORD_FORM.ERROR.INVALID_XML

Regisztrálni sem enged, mert akkor meg ezt kapom:
REG_DATACHECK_FORM.MESSAGES.ERROR.INVALID_XML

Kihez lehet fordulni ez ügyben?  (A hivatali út kb 3 hét és kapok egy nem kompetens embertől egy pingvinezést. Ettől szeretném megkímélni magam.)
Köszönöm.

**Comment by NTCA-supporter** [comment]
Szia @szecsenyizoltan !
Én kipróbáltam most a teszt rendszeren, másodlagos felhasználóval hibátlanul ment a jelszóemlékeztető.
Segíts kérlek, hogy milyen típusú felhasználóval probálkozol, illetve esetleg egy felhasználónév is segíthet, hogy nézhessem a logokat.
Milyen böngészőben próbáltad? 
Köszi

**Comment by szecsenyizoltan** [comment]
User: SzecsenyiZEV
OS: Kubuntu 20.04
Browser: Up2date Chrome

**Comment by szecsenyizoltan** [comment]
inspector szerint:
Failed to load resource: the server responded with a status of 400 (Bad Request)  /rest/userService/customerUser/check:1

**Comment by NTCA-supporter** [comment]
Szia @szecsenyizoltan !
A captcha lesz a ludas, de ez úgy néz ki csak nálad jelentkezik, legalábbis eddig csak te jelezted, illetve ahogy írtam nekem is működött minden.
Hamarosan kikapcsoljuk a captcha-t és menni fog minden.
Jelzek majd.
Üdv

**Comment by szecsenyizoltan** [comment]
Köszi. (BTW:Élesen minden oké.)

**Comment by szecsenyizoltan** [comment]
FF console:
https://onlineszamla-test.nav.gov.hu/rest/userService/createSession
[HTTP/1.1 400 Bad Request 0ms]

**Comment by NTCA-supporter** [comment]
Próbáld újra kérlek.
Köszi

**Comment by szecsenyizoltan** [comment]
Semmi változás. Minden probléma és tünet ugyanaz.

**Comment by szecsenyizoltan** [comment]
![Screenshot_20201021_105045](https://user-images.githubusercontent.com/31820823/96696651-4c837e80-138b-11eb-8c06-f41c0c902df2.png)

**Comment by szecsenyizoltan** [comment]
Már megy. Cache-ből jött a js gondolom.

**Comment by NTCA-supporter** [comment]
Igen, valószínűleg az volt a gond.
Zárom az issuet.
Üdv
