### ISSUE TITLE
[Q&A] When will be available the API documentation in english?

### ISSUE THREAD

**Issue by danton-edi** [nav-gov-hu/Online-Invoice#462]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Dear NAV team,
When do you plan to publish the english version of the API documentation? You published the hungarian version 3 weeks ago. 
Thank you.
Daniel Antón

**Comment by WittmannWien** [comment]
Dear Nav Team,

this information would be also important to us. 
Thanks.

Regards
Peter Kovacs

**Comment by NTCA-supporter** [comment]
Hi!

It will be published next week.
I'll inform you here when it's available.
Br

**Comment by danton-edi** [comment]
Thank you!

**Comment by attilaszoke** [comment]
Tisztelt NAV csapat,

Még minding In progress az angol nyelvű API dokumentáció, várható esetleg November első hetén?

Köszönettel,
Attila

**Comment by renced42** [comment]
> Tisztelt NAV csapat,
> 
> Még minding In progress az angol nyelvű API dokumentáció, várható esetleg November első hetén?
> 
> Köszönettel,
> Attila

@attilaszoke  Várhatóan jövőhéten publikáljuk.

**Comment by attilaszoke** [comment]
Tisztelt NAV csapat,
Köszönöm szépen. És a 2.0 api dokumentáció is módosult 10.23-án a Magyar verzióban, az is elérhető lesz Angolul is?
Köszönettel,
Attila

**Comment by sebastian-walz** [comment]
Dear all,

is there a new release date for the English version? This is currently blocking our development.

Regards,
Sebastian

**Comment by EnokhSys** [comment]
Hi Sebastian and all,

I think there are some developers here from many areas, who have some english skills (however we are not perfect for far), and can help you to start developing the v3 API, until the english documentation will be released. I suggest you to start a new issue in english, where you, or your developers can ask about the step by step changes from the beginning. 

Regards,
Csaba

**Comment by attilaszoke** [comment]
Tisztelt NAV csapat,  sajnos még mindig nem érhető el az angol nyelvű leírás.
Valami biztató infó lenne esetleg?
Köszönettel,
Attila

**Comment by WittmannWien** [comment]
Jó reggelt Mindenkinek,
Igen, jó lenne mielőbb megkapni, hiszen lassan már 6 hete várunk a fordításra, hogy a nemzetközi csapatunk el tudja kezdeni az érdemi munkát. Valamiért most mintha nehezebben menne az idegen nyelvű anyagok összeállítása, mint korábbi átállásoknál.
Sajnos az nem lehet alternatíva, hogy más fejlesztők segítségével induljunk neki a fejlesztésnek. Dokumentáció kell, hogy el tudjunk indulni. 
Várjuk a dokumentáció mielőbb megjelenését.
Üdvözlettel:
Péter

**Comment by Alex3146** [comment]
So far still no technical specifications in English. V3.0 will become really soon ... hmm I guess. Guys in my team investigated a little about new schema. Their conclusion that changes can be rather severe. The only what I’ve found is some summary about technical changes in https://onlineszamla-test.nav.gov.hu/informatikai_valtozasok

With all due respect to NAV the implementation of the next version with no specifications in English will be tricky business for international software vendors. Usually it concerns large customers at the end of the day. Knowing common practices and very strict rules in Hungary would it be fair to expect right solutions and functional behaviors  with no specifications ?

**Comment by NTCA-supporter** [comment]
Dear All!

Suprise: https://onlineszamla.nav.gov.hu/api/files/container/download/Online%20Szamla_Interfesz%20specifik%C3%A1ci%C3%B3_EN_v3.0.pdf

If you have any questions or need further information, please feel free to contact us. 
Sorry for the late publish.

Br

**Comment by danton-edi** [comment]
Thank you a lot!

By the way, when do you plan to publish the Data example XML? They are really useful!

**Comment by NTCA-supporter** [comment]
Hi All!
I close this issue.
The data samples are published (in hungarian), the transaltion is in progress.
Regards
