### ISSUE TITLE
[Q&A] web felület excel exportok - több azonos bejövő számlaszám

### ISSUE THREAD

**Issue by csaszko** [nav-gov-hu/Online-Invoice#463]
@NTCA-developer 
Szia, 

Ide átmenteném a #435 -ben elkezdett dolgokat. 
Írjam át ide a javaslatokat amiket tegnap a fenti topicban tettem?

Más: 
Az export zip fájl neveit nézve találtam hibát is közben, vagyis szerintem nem jól kezelt dolgot. 
Bejövő számla exportnál, ha egy exportban van egy vagy több azonos számlaszám (különböző partnerektől) , akkor nem tudja kezelni a rendszer. (a zipben csak a saját adószám és a számla száma van fájlnévnek megadva, így ott is ütközés lenne).  
Kipróbáltam és "érvénytelen bemenettel" elutasítja az exportot ebben az esetben. Ez szerintem nem jó így, mert akár a teljes oldalon lehet, ugyan az a számlaszám ekkor egyesével kellene exportálni.

**Comment by renced42** [comment]
@csaszko Igen köszi!

**Comment by csaszko** [comment]
Köszi így megtaláltam, nem jelöltem ki számlát így inaktív volt a gomb. Ezért a felső exportot használtam (feltételezem nem én voltam az egyetlen. Igaz valóban nem olvastam a felhasználóit. Nem hiszem, hogy mostanában sokan szoktak.. persze nem mentség, de ez a valóság :) )

Megnéztem, szerintem (számomra biztosan nem lenne az) ez a formátum nem segítség azoknak akik egyeztetni akarnak, hiszen minden számla külön excelben van. Ha egy táblában vannak az adatok akkor lényegesen egyszerűbb listázni, szűrni ahogy csak szeretnének.
Biztos van létjogosultsága ennek is, de így elsőre nekem a sok tételes számla átláthatatlan.

Továbbra is a voksom arra adom, hogy a sima lista használhatóbb, csak fej valamint fej/részletek, esetleg hasonló aszinkron
módon működjön itt is a letöltés lehetősége. (a 100 tételes limit nagyobbra emelésével)

**Comment by csaszko** [comment]
Nem tudom pontosan mik kellenek vagy kellettek volna, de szerintem ha a fej adatokat ki lehetne exportálni (ami már szűrés után is rendelkezésre áll) az biztosan elég lenne időnként. (Számla bruttó vagy nettó vegösszeggel, most nincs előttem a lista nem.tudom benne van-e)

**Comment by csaszko** [comment]
En most tesztelési célból töltöttem. De könyvelőnk szerette volna leszedni korábban az áfa bevalláshoz az összehasonlítás miatt. A zip-es megoldást nem láttam, de nem is kerestem. Szűrés es export szemet szúr ezt találtam.
A bejövő számla lekérdezés fejlesztését jegeltem, nem fejeztem be, jeleztem is akkor problémákat, hogy ne engedjetek kézi számlát rögzíteni úgy, hogy köszönő viszonyban nincsenek a számok egymással. Sajnos nálunk továbbra is előfordulnak, olyanok (bejövő), hogy vagy számolni nem tudnak vagy rosszul értelmezik (nem kutattam miért) mit hova kell beírni es ezért használhatatlan adok kerülnek bele, azt ellenőrizni kell embernek úgyis... valakit egyszerűen nem lehet meggyőzni, hogy felejtse már el a papírt...

**Comment by csaszko** [comment]
@renced42 
Bemásolgattam.
Összefoglalva:
-Zip-nél nincs kezelve az ha több szállítónak azonos a számlaszáma egy exportban
- sima exportnál (nem zip) jó lenne csak fej adatokra listázás lehetősége (már leszűrt js tábla excelbe mentése) 
- exportnál fej és részletek mentési lehetősége jelenlegi formájában, de aszinkron módon (zip) 
- ha van lekért dokumentum (zip) már ami elkészült, lehet átláthatóbb lenne ha a szűrési feltételeket kezelő felületen is van valami hivatkozás a szolgáltatás>>dokumentumok menüpontra.

**Comment by EnokhSys** [comment]
@NTCA-developer, hadd tegyek hozzá @csaszko javaslatához egy józan javaslatot, mert tőlem a könyvelők évtizedek óta, minden hónapban ezt kérik/húzzák le, mondhatni ez a Top-1:

Időszakos ÁFA analitika, amely külön a bejövő számlákra és külön a kimenő számlákra lekérdezhető.

Szűrési képernyő:
- teljesítés dátuma (tól-ig; kötelező megadni)
- vevő vagy szállító (attól függően, hogy bejövő vagy kimenő számlák; opcionális)

Képernyőn vagy Excelben lejövő lista, amely az alábbi adatokat tartalmazza:
- Teljesítés dátuma (első növekvő sorrend)
- Számlaszám (második növekvő sorrend)
- Vevő vagy szállító neve és adószáma
- Adónem százaléka (vatPercentage; - harmadik növekvő sorrend) 
- Adómentesség jelölése (vatExemption/case)
- Adónem nettó értéke Ft (vatRateNetData/vatRateNetAmountHUF)
- Adónem ÁFA érték Ft (vatRateVatData/vatRateVatAmountHUF)
- Adónem Bruttó érték Ft (vatRateGrossData/vatRateGrossAmountHUF)

Ennek a listának csak akkor van értelme, ha nincs tétel-limit, ugyanakkor, hogy ne terhelje túl a rendszert, max 1 hónapos szűrést adhatna meg a felhasználó.

(Megjegyzés: ahhoz, hogy a lista gyors legyen, el kell kerülni a one2many relációból eredő adatbázis-többlethívásokat, ezért a számla fej táblából a számlaszámot, a teljesítés dátumát és a vevő/adószámát redundánsan le kellene vinni, ill. redundánsan kellene kezelni a számla ÁFA-táblájában, és az analitika elkészítéséhez csak ezt az egy táblát lenne célszerű használni. A redundanciakezelés nem jelenthet különösebb problémát, mert ezek az adatok soha nem változnak a számla elkészülte után. Én sem szeretem a redundáns megoldásokat, de van amikor ez elkerülhetetlen, javíts ki, ha ebben az esetben tévednék.)

**Comment by csaszko** [comment]
Miután megírtam a kommentet, kollégák mondták szintén amit @EnokhSys felvetett. Illetve, hogy jelen esetben nem tudnak csak több részben szűrni az áfa teljesítésre, mert a számla kiállítás dátum megadása kötelező, így ha 45-60 napos számla van akkor azokat külön kell leszűrni. 

Biztosan nagy segítség lenne a könyvelőknek és @EnokhSys -el egyetértve, talán nem lenne akkora terhelés sem, mert nem próbálkozna mindenki 50x.
Megoldási javaslatom az is, hogy egyetlen gomb lenne erre akár csak hónapválasztóval "áfa analitika" ami vagy beállítja a keresőmezőket a megfelelő állapotokra vagy pedig egy külön szűrésben lehozza az adott hónap ki vagy bejövő számláit.

**Comment by EnokhSys** [comment]
@csaszko Csak annyit fűznék hozzá, hogy akár nagyvállalatná-, akár kisvállalatnál fejlesztettünk, a könyvelők szinte változatlanul ezeket az adatokat kérték mindenhol, ez olyan nekik mint apácáknak a zsolozsma.

**Comment by fzoli15** [comment]
Én csak azt nem értem, hogy a könyvelők miért a NAV online számla rendszerből akarnak hozzájutni az ÁFA bevallás analitika összeállításához szükséges adatokhoz. Ez a rendszer (jelenleg) nem erre való.
A teljesség igénye nélkül:

1. Általánosan igaz, hogy az adatminőség jelenleg még nem olyan a NAV online számla adatszolgáltatásban, amiben "vakon" meg lehetne bízni, és felelősen erre lehetne alapozni az ÁFA bevallást.
2. Fizetendő ÁFA oldalon nincs bent a rendszerben minden számla (magánszemély vevők, EU-s és export értékesítések).
3. Fizetendő oldalon vannak olyan tételek, amik nincsenek benne (és várhatóan nem is lesznek benne) a rendszerben, pl.: saját rezsis beruházások, ajándék/grátisz értékesítések után fizetendő ÁFA.
4. Fizetendő ÁFA oldalon hiányoznak a speciális esetekre vonatkozó jelölések (pl. tárgyi eszköz értékesítés, fordított ÁFA-s értékesítés esetének pontos jelölése).
5. Levonható ÁFA oldalon sincs bent minden számla a rendszerben (pl. közösségen belüli beszerzések).
6. Levonható ÁFA oldalon sok információ nem nyerhető ki a rendszerből pl.:
- A számlát befogadt-e a vevő.
- A számla után levonható ÁFA-t elszámol-e a vevő, és ha igen, akkor milyen összegben (gondoljatok pl. az üzemanyag számlákra).
- A számlát melyik időszakban helyezi levonásba a vevő (nem feltétlenül egyenlő az ÁFA tv. szerinti teljesítési dátummal).
- Pénzforgalmi elszámolású számlák esetén a kifizetési dátuma.

A fentiek miatt (és mivel korábban nem volt NAV online számla rendszer), a könyvelőknek jelenleg is rendelkezniük kell egy olyan rendszerrel (könyvelő program, ERP), ami képes a könyvelés alapján az ÁFA bevallás analitika teljeskörű előállítására.
Miért nem megfelelő ez korábbi/jelenlegi, jól működő rendszer a továbbiakban is?

+1 Ha valóban születik egy ilyen "ÁFA analitika lista", akkor a dátumszűrések tervezésekor vegyétek figyelembe, hogy nem mindenki havi bevalló, vannak negyedéves, sőt akár éves bevallásra kötelezettek is. Ezen kívül, vannak olyan teljesen szabályos esetek, amikor az ÁFA törvény által meghatározott teljesítési dátum (ami az adatszolgáltatásban megjelenik) nem egyezik azzal a dátummal, bevallási időszakkal, amikor az ÁFA bevallásba kerül a számla.

**Comment by csaszko** [comment]
Más nevében nem beszélhetek, de nálunk az biztos, hogy korábban is gond volt a bejövő számlák érkezésével... valahogy valahonnan.. mindig sikerült előkerülnie egy-egy számlának ami módosította az ÁFÁ-t... így önellenőrizni kellett.
Itt most még ha nem is megfelelően vannak az adatok, de legalább támpont, hogy mit kell keresni vagy kell-e valamit.
Kimenő oldal tételeit természetesen a saját rendszereinkből nyerjük ki, ez nem is érdekes számunkra. 

Az általad leírtaknak biztos sokan megfelelnek és ezért nem tudják használni tényleg, de olyanok is vannak akinek viszont hasznos lehet, mert nincs közösségi beszerzés, nincs pénzforgalmi stb.
Elhangzott már másoktól is, de szerintem is, ha valami szolgáltatás publikussá teszel, akkor nem kell csodálkozni azon, hogy használni is szeretnék?! Amikor egy ilyen lekérdezési lehetőséget létrehoztak, feltételezem tisztában voltak vele, hogy nem a cégvezetők fogják nézegetni (legalábbis a többségük biztosan nem), hanem a gazdasági vagy könyvelő munkatársak és azt, hogy mire használják a kinyert adatokat nem gondolom, hogy releváns és hibáztathatok lennének, mert tiltva nem volt senki... (nem a floodolásról beszélek természetesen meg társairól)

**Comment by jozanesz** [comment]
> Miért nem megfelelő ez korábbi/jelenlegi, jól működő rendszer a továbbiakban is?

Azon kívül, amit csaszko írt

[2020. július 1-től az áfatörvény alapján minden befogadott szállítói számláról, amelyre a cég áfalevonási jogát gyakorolni akarja, áfaösszeghatárra tekintet nélkül adatot kell szolgáltatni a NAV felé az M lapon](https://www.rsm.hu/blog/2020/05/connectax-afabevallas-julius-1-tol-a-szamlakat-az-m-lapokon-is-ertekhatar-nelkul-kell-jelenteni)

**Comment by csaszko** [comment]
Jaa igen, tényleg az m lapok... már el is felejtettem..  az áltaunk használt könyvelő program fejlesztőknek sem sikerült elsőre, sem másodikra megoldani, hogy 100%-ban jó adatok legyenek a bevallásban, az elején még bekerült ez-az :)

**Comment by EnokhSys** [comment]
> Én csak azt nem értem, hogy a könyvelők miért a NAV online számla rendszerből akarnak hozzájutni az ÁFA bevallás analitika összeállításához szükséges adatokhoz. Ez a rendszer (jelenleg) nem erre való.

Persze, hogy nem erre való, szerintem csupán arról van szó, hogy a könyvelők szeretik bebiztosítani magukat a tévedések ellen; - ha a bejövő, kimenő számlák összege egyezik azzal ami a saját rendszerükben/nyilvántartásukban van, akkor a bevalláshoz szükséges nagyobb halmazt kipipálhatják.
Ezen kívül rengeteg olyan mikrovállalkozás és kis cég van, akiknek hónapokon keresztül semmi spécibb esetük nincs, egy ilyen áfa analitika bőven elegendő az ÁFA bevalláshoz. 

> +1 Ha valóban születik egy ilyen "ÁFA analitika lista", akkor a dátumszűrések tervezésekor vegyétek figyelembe, hogy nem mindenki havi bevalló, vannak negyedéves, sőt akár éves bevallásra kötelezettek is. 

Persze, ha nem lesz túlterhelve a NAV adatbázis-szervere, akkor ez lenne az ideális. De a jelenlegi áfa analitika is egyrészt azt a célt szolgálná, hogy az adatszerver terheltségét lényegesen csökkentse, főleg ÁFA-bevallás időszakában.

>Ezen kívül, vannak olyan teljesen szabályos esetek, amikor az ÁFA törvény által meghatározott teljesítési dátum (ami az adatszolgáltatásban megjelenik) nem egyezik azzal a dátummal, bevallási időszakkal, amikor az ÁFA bevallásba kerül a számla.

Például?

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ez az issue kissé el lett hanyagolva.
Van itt még nyitott kérdés?
A bejövő számla exportnál az azonos számla sorszám még fennál ha jól tudom, ezt majd javítjuk.
Gyorsan átfutottam a kommenteket, a lista export nem megoldás ezekre a problémákra?
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezt átalakítom buggá, a bejövő számla többszörös invoiceNumber miatt és a javításig nyitva hagyom. A listaexportot továbbra is tudom javasolni a fentiekre, de azóta szerintem használtátok biztosan.

Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

A hiba javításra került, élesen is jónak kell már lennie.

Köszi a jelzést.
