### ISSUE TITLE
[DOC] communitiyVatNumber , thirdStateTaxId nincs dokumentálva

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#465]
customerInfo leírásából (tag,típus,kötelező,tartalma), illetve facetek és leírók résznél hiányzik a communitiyVatNumber , thirdStateTaxId mezők dokumentálása a dokumentáció 82-83. oldalán.

**Comment by NTCA-supporter** [comment]
Köszi a jelzést, pótolni fogjuk.
Addig maradjon nyitva.
Üdv

**Comment by NTCA-supporter** [comment]
Javítottuk.
Zárom az issuet, köszi a megjegyzést mégegyszer.
Üdv
