### ISSUE TITLE
[Q&A] 3.0 customerVatData hibás döntés a choice

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#466]
Dokumentáció 81. oldala: "A három adószám közül az adatszolgáltatásban csak egy adható meg. Ha a számlán esetlegesen több
vevői adószám szerepel (pl. belföldi adószám, közösségi adószám), akkor az adatszolgáltatásnál azt az
adószámot kell kiválasztani, amit Áfa törvény szerint a számlán egyébként fel kell tüntetni. "

A számlázó program nem kompetens ennek az eldöntésében, nem lehet a számlázó programra tolni ennek a felelősségét. Gyakori eset, hogy amikor felrögzítenek egy ügyfelet, akkor kitöltik az összes adószám rubrikát, így a számlázáskor ezek az adószámok mind rá kerülnek a számlára.  A számlázó program nem fogja tudni eldönteni, hogy az adott gazdasági esemény, amit épp az ügyfél számlázott az ÁFA törvény alapján hova sorolható be, így nem fogja tudni 100% biztonsággal azt sem meghatározni, hogy mely adószámot kell feltüntetni az adatszolgáltatásban.

Javaslom ennek vissza alakítását a 2.0 szerint, vagyis, hogy párhuzamos meg lehessen adni az adószámokat, különös tekintettel, ha több adószám szerepelt a számlán, akkor eleve így van párhuzamban a számla adattartalma az adatszolgáltatással. Nem értem, hogy a NAV-nak miért volt akkor probléma, hogy kapott egyszerre egy belföldi és egy EU-s adószámot, ha a számlán amúgy is mindkettő fel volt tüntetve. A feldolgozás során használják azt, amelyikükre szükség van. A choice-nak nincs értelme!

**Comment by NTCA-supporter** [comment]
Szia @nbeeps2 !
Folytassuk a #469 -ben kérlek, eléggé ugyanaz a témakör.
Köszi
