### ISSUE TITLE
[Q&A] Hiba: XML generálás XSD alapján

### ISSUE THREAD

**Issue by lakatoskevin** [nav-gov-hu/Online-Invoice#467]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Sziasztok! Amikor próbálok példa XML-t generálni az XSD-k alapján akkor arra hivatkozik az összes hiba, hogy adott típusok nincsenek definiálva, vagy hogy olyan típust használna bázisként az XSD amit nem szabad. Ti hogy oldjátok meg a problémát, vagy hogy kerülitek meg?
Próbáltam online XML generátorral, de a Visual Studio-val is, de mindig csak hibaüzeneteket kapok. A specifikációban pedig csak egy XML validátorra találtam hivatkozást.

**Comment by EnokhSys** [comment]
@lakatoskevin Szia, nézd meg ezt, hátha itt választ kapsz:

https://github.com/nav-gov-hu/Online-Invoice/issues/447

**Comment by lakatoskevin** [comment]
Köszi szépen! Legközelebb a closed issue-kat jobban meg fogom nézni mielőtt kérdezek.

**Comment by EnokhSys** [comment]
@lakatoskevin nem gond, én is belefutok ilyesmibe, hogy nem találok valamit, pedig tudom, hogy korábban volt itt róla szó.
