### ISSUE TITLE
[Q&A] V3.0 Létezik, hogy ugyanazon operáció válasza más és más névtérben jön vissza?

### ISSUE THREAD

**Issue by DrotosTot** [nav-gov-hu/Online-Invoice#468]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Létezik, hogy ugyanaz az operáció egyszer névtér nélkül, egyszer névtérrel válaszol?
Alábbiakban a példa, a tesztben visszakereshető:
`<TokenExchangeResponse xmlns="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns2="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data"><ns2:header><ns2:requestId>DE2IDMN7p7XifhRn8mfxq</ns2:requestId><ns2:timestamp>2020-10-21T10:52:24.000Z</ns2:timestamp><ns2:requestVersion>3.0</ns2:requestVersion><ns2:headerVersion>1.0</ns2:headerVersion></ns2:header><ns2:result><ns2:funcCode>OK</ns2:funcCode>`

`<ns2:TokenExchangeResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data"><header><requestId>DE2IDPqPuzBHmxm8B1JdM</requestId><timestamp>2020-10-21T09:59:06.000Z</timestamp><requestVersion>3.0</requestVersion><headerVersion>1.0</headerVersion></header><result><funcCode>OK</funcCode>`

Megerősítést szeretnénk kérni, hogy ez lesz a végleges működés.

**Comment by szako** [comment]
https://github.com/nav-gov-hu/Online-Invoice/issues/453#issuecomment-712097397

> A namespace-ek sorrendje nem garantált, tehát nem égetheted be, hogy pl. a common lesz a default namespace!

Ez nálunk is probléma, még vizsgáljuk a hatásait.

**Comment by ocsike** [comment]
Ez engem is érdekelne,mert tegnap pl. benne volt az ns: ma meg nem...........

**Comment by NTCA-supporter** [comment]
Sziasztok!

Az említett #453 -ban ott van minden.
Ezt zárom.
Üdv
