### ISSUE TITLE
[Q&A] 3.0 hibás új aszinkron-hibaüzenet CUSTOMER_DATA_EXPECTED

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#469]
A leírás szerint CUSTOMER_DATA_EXPECTED aszinkron-hibaüzenet fog érkezni, ha a vevő nem magánszemély (privatePersonIndicator=false) ÉS nincs megadva adószám/név/cím a vevőnél, HOLOTT a gazdasági tevékenységet nem folytató társasházaknál például ez a három mező egyszerre nem lesz kitöltve, mert az adószám hiányozni fog. Az is lehet, hogy csak dokumentációs hiba, még nem tudtam kipróbálni.

**Comment by NTCA-supporter** [comment]
Szia @nbeeps2 !

Jól látod, ez valóban egy olyan eset, amikor nem kellene a hiba.
Ennek átgondolása már folyamatban van, a hibaüzenet miatt nem kell aggódni, le lesz lezelve az eset és nem lesz hiba ilyenkor.

A pontos megoldásról jelezni fogunk mindenhol is. :) 
Üdv

**Comment by NTCA-supporter** [comment]
Szia @nbeeps2 !
A sémaváltozás miatt ez az issue már nem releváns szerintem. Ha az új sémával kapcsolatban van kérdés, akkor nyiss új issuet kérlek.
Üdv
