### ISSUE TITLE
[Q&A] V3.0 queryInvoiceData validáció hiba magánszemélyes számlánál

### ISSUE THREAD

**Issue by DrotosTot** [nav-gov-hu/Online-Invoice#470]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
QueryInvoiceDataResponse sémasértést ír:
Request body contains on line: [-1] and column: [-1] error: [cvc-complex-type.2.4.b: The content of element 'customerTaxNumber' is not complete. One of '{"http://schemas.nav.gov.hu/OSA/3.0/base":taxpayerId}' is expected.]

Request body contains on line: [-1] and column: [-1] error: [cvc-complex-type.2.4.b: The content of element 'customerAddress' is not complete. One of '{"http://schemas.nav.gov.hu/OSA/3.0/base":simpleAddress, "http://schemas.nav.gov.hu/OSA/3.0/base":detailedAddress}' is expected.]

A beküldött QueryInvoiceDataRequest tartalma valid. Tesztben levő requestId: DE2IDNxcNQJMkLvze9VCK

**Comment by NTCA-supporter** [comment]
Szia @DrotosTot !
A requested valóban rendben van. Itt a lekérdezett számla adattartalmánál nem kerek valami. Vlaószínűleg nálunk van a hiba, de utánanézek majd és jelzek.
Üdv

**Comment by DrotosTot** [comment]
Köszönöm @NTCA-supporter , várom a választ!

**Comment by NTCA-supporter** [comment]
Szia @DrotosTot !
Köszi a türelmet. Nálunk van a hiba, ennél az új magánszemélyes (privatePersonIndicator = true) számlánál nem működik a queryInvoiceData lekérdezés.
Javítjuk, addig maradjon nyitva az issue szerintem, hogy más ne nyisson újat ezzel kapcsolatban.
Köszi a jelzést!
Üdv

**Comment by NTCA-supporter** [comment]
Szia @DrotosTot !
Kérlek próbáld meg új beküldött számláknál a lekérdezést.
Már jónak kell lennie. Korábbi számlákra nem lesz jó, mert változott a séma.
Üdv

**Comment by DrotosTot** [comment]
Köszönöm, működik, zárom!
