### ISSUE TITLE
[Q&A] A számlaszám többször szerepel a rendszerben, de hibára fut a technikai érvénytelenítés elfogadása

### ISSUE THREAD

**Issue by HWKF** [nav-gov-hu/Online-Invoice#471]
Számla adatszolgáltatás beküldésekor a MULTIPLE_QUERY_RESULT_FOUND hiba üzenetet kapta vissza az ügyfél, azaz **a keresett számlaszám többször szerepel érvényesként a rendszerben** 
_A hibaüzenet a /queryInvoiceData és /queryInvoiceCheck operációkban adható vissza akkor, ha a lekérdezett számlaszám többször érvényesként szerepel a rendszerben. Ebben az esetben a számlaszámot technikailag érvényteleníteni kell, majd a jóváhagyást követően az adatszolgáltatást meg kell ismételni a helyes adatokkal._
Többszöri próbálkozásra sikerült beküldeni a számlát, de mikor lekérdeztük a státuszát, akkor kaptuk az INVOICE_NUMBER_NOT_UNIQUE hiba üzenetet. Ezután próbáltuk lekérdezni a számla adatszolgáltatás állapotát, amelyre viszont a fenti hibaüzenet érkezett.
Bejelentkeztünk együtt az ügyféllel, hogy megvizsgáljuk a kérdést. 
A számla 3szor szerepel a rendszerben, feldolgozva státuszban. Lekérdezve nem lehet, mert elakadt a lekérdezés. A NOT UNIQUE hiba miatt. (utólagosan lefrissítettük a státuszokat, így már mind 3 lekérdezve állapotba került. **Mind 3 tranzakció Rendben státuszban van**)
Ezután az utasítás szerint próbálta az ügyfél kiadni a technikai érvénytelenítést a számlaszámra. 
Viszont a technikai érvénytelenítést nem tudta elfogadni elsődleges felhasználóként, mert csak annyit írt ki a rendszer, hogy "Hiba történt!" (Ezt megismételtük a státuszok frissítése után, akkor sem ment tovább)
Majd elutasítottuk az érvénytelenítést, és próbálkoztunk az első beküldésre kiadni, de továbbra sem sikerül.
Kérnénk segítséget az érvénytelenítéshez. Illetve az engedélyező felület hiba üzenetének bővítését.

**Comment by NTCA-supporter** [comment]
Szia @HWKF !
Első olvasásra az eljárás helyes lenne, mármint hogy technikai érvényteleníted és jóváhagyod.
Az általános "Hiba történt!" üzenet egy default hibakódból jön, tehát itt valami nem tervezett hiba történt. Ami ismert üzleti hiba, azt pontosan ki szoktuk írni.
Utánanézek mi lehet a gond.
Üdv

**Comment by NTCA-supporter** [comment]
Szia @HWKF !
Nálunk van a hiba. Maradjon nyitva az issue, amíg élesedik a javítás.
Az eljárásod teljesen helyes lesz egyébként (technikai érvényteleníted a többszörösen előforduló számlákat, jóváhagyod, majd beküldöd újra).
Üdv

**Comment by HWKF** [comment]
Szia @NTCA-supporter !
Van hír a hiba javítását illetően?
Mert az ügyfél közben a NAV ügyfélszolgáltatához fordult, ahonnan azt a választ kapta, hogy:
**_Tájékoztatjuk, hogy a technikai érvénytelenítéssel csak a számla adatszolgáltatását érvényteleníti, magát a számlát nem. Kérjük utasítsa el a technikai érvénytelenítést, majd a Számla érvénytelenítése funkció használatával érvénytelenítse a számlát._** 
Azaz sztornózza a számlát, amikor az adatszolgáltatás befogadásával van a gond.

**Comment by NTCA-supporter** [comment]
Szia @HWKF !
Az eljárás, ahogy írtam, helyes, technikai érvénytelenítés szükséges ilyenkor, ha a számla létezik, csak többször lett beküldve. Technikai érvénytelenítés jóváhagyás után lehet újra beküldeni.
A javítás folyamatban van, de nem csak ezt adjuk ki javító verzióban, ezért pontos időpontot nem tudok mondani.
Üdv

**Comment by HWKF** [comment]
Sziasztok!
Látom a teszt rendszerben már javult.
2.12.5 mikor lesz élesítve? Mert az élesben még 2.12.1 az érvényes a Technikai információi kapcsán, de a teszten már ki van írva az éles verziószáma, amiben benne van.

**Comment by NTCA-supporter** [comment]
Szia @HWKF!
A 2.12.5 élesítése jövő héten várható. Ha megvan a pontos dátum, akkor az éles környzeten a Hírek alatt látható lesz, de ide is beírom.

**Comment by NTCA-supporter** [comment]
@HWKF kikerült a javítás élesre, kérlek ellenőrizzétek. Ha rendben van, zárd az issuet.
Üdv

**Comment by HWKF** [comment]
Köszönöm a jelzést. Jeleztem a supportunknak.

**Comment by HWKF** [comment]
Rendben van. Sikerült a kérdéses számlák esetén technikai érvénytelenítés és sikerült rendben beküldeni a számlák adatszolgáltatását.
