### ISSUE TITLE
[Q&A] V3.0 bevezetése

### ISSUE THREAD

**Issue by tib99** [nav-gov-hu/Online-Invoice#472]
A V3.0 bevezetése 2021. január 1. ami azt jelenti, hogy az éles rendszer ettől a dátumtól lesz elérhető vagy már előbb is lehet 3.0 adatokat küldeni? Néhány helyen olvasható, hogy március 31-ig párhuzamosan fog működni a 2.0 és a 3.0 verzió és április elsejétől lesz kötelező a 3.0. Ezeket az információkat meg tudják erősíteni? Köszönöm

**Comment by nbeeps2** [comment]
@tib99 szerintem fura lenne a 3.0-val 2020-ban számlát beküldeni, mivel még nem szabad küldeni a magánszemélyeket és a külföldieknek kiállított számlákat és egy csomó validáció, ennek megfelelően működik a 3.0-ban, aminek viszont 2021 előtt nincs értelme. Az hogy átmenetileg megy a 2.0 és a 3.0 az nagyon jó, mert nem egy adott napon (január 1) kell mindenkinek áttérni, hanem az áttérés lehet fokozatos.

**Comment by szako** [comment]
Kapcsolódó: #407

**Comment by vivacomp** [comment]
Meglepődve tapasztalom a namespaces változását pl. V3.0 TokenExchangeResponse -ban. Azt gondoltam év vagyok a hibás (ez is lehet). Infót szeretnénk arról, amit változtattok.
Üdv.

**Comment by renced42** [comment]
@vivacomp minden lényeges változást megtalálsz a https://github.com/nav-gov-hu/Online-Invoice/blob/master/src/schemas/nav/gov/hu/OSA/CHANGELOG_3.0.md oldalon.

**Comment by vivacomp** [comment]
@renced42 Köszi a linket, szükség lesz rá. Arra céloztam, hogy a V3 tesztben a tokenkérés válaszában a funcCode eddig simán elérhető volt, da a mai naptó ns2:funcCode lett. Ez nem probléma nekem, csak furcsa volt, hogy eddig simán ment a tokenkérés, majd egyik percről a másikra bejött a válaszba az ns2 itt is. Tehát a mai napig ns2 nélkül ment a V3, mától ns2-vel. Ismétlem, nem gond, de nem szeretem, ha váratlan változások miatt mindig vissza kell nyúlni valamihez.....
Üdv.

**Comment by vivacomp** [comment]
Kiegészítés az előzőhöz. Még valami.... az ns2:encodedExchangeToken helyett most ismét encodedExchangeToken
Igazán semmiség....
Üdv.

**Comment by szako** [comment]
> Kiegészítés az előzőhöz. Még valami.... az ns2:encodedExchangeToken helyett most ismét encodedExchangeToken
> Igazán semmiség....
> Üdv.

#468

**Comment by vivacomp** [comment]
@szako Köszönöm. Legyen így, megoldom.
Üdv.

**Comment by NTCA-supporter** [comment]
Szia @tib99 !
Azt, hogy mikor lesz élesítve a 3.0 nem ebben az issueban fogjuk megválaszolni, és még mi sem tudjuk. Nyilván minden fórumon publikálva lesz, ahogy korábban is.
A párhuzamos működés várható igen.
Zárom az issuet, további kérdés esetén nyissátok újra nyugodtan.
Üdv

**Comment by zsfoto** [comment]
Kedves @vivacomp!
Csináltam egy olyan xml érték lekérdező függvényt aminek a ns2: illetve bármi hasonló nélküli kulcsértéket adhatok meg.
A fg() megállapítja az először ns-t, hozzáfűzi a kulcshoz, majd ns:kulcs-ként megkeresi a kulcsot és visszaadja az értéket. Így bármikor bármilyen ns van vagy nincs, a fg() működik és értéket ad vissza.
