### ISSUE TITLE
[Q&A] A supplierInfo kódolt mezőinek értéke hogyan képezhető?

### ISSUE THREAD

**Issue by vajayattila** [nav-gov-hu/Online-Invoice#474]
Segítséget kérek. Nem tudom megfejteni, hogyan kell létrehoznom  a mintában talált kódolt mezők értékeit. Ilyen mező például a supplierName, city, streetName stb.
Ezeket az adatokat az AES-128-al és a cserekulccsal kell elkódolnom? A doksiban nem találtam utalást ezeknek a mezőknek a kódolására (valószínűleg én vagyok a hibás). Előre is köszönöm a segítséget.

```
            <supplierInfo>
               <supplierTaxNumber>
                  <ns2:taxpayerId>48258036</ns2:taxpayerId>
                  <ns2:vatCode>5</ns2:vatCode>
                  <ns2:countyCode>51</ns2:countyCode>
               </supplierTaxNumber>
               <groupMemberTaxNumber>
                  <ns2:taxpayerId>44444444</ns2:taxpayerId>
                  <ns2:vatCode>4</ns2:vatCode>
                  <ns2:countyCode>51</ns2:countyCode>
               </groupMemberTaxNumber>
               <communityVatNumber>AS16514193</communityVatNumber>
               <supplierName>wMgLGqTrETzRHXvhVsevMicRTeKrknbcRnMlnjzmwvjXmofxpnQWIoIXqYMFSoslcmgPgboYnBlZkWVFCYLYjFeexFBRxSyMVDkjglfhkplrTMXFoxewORkTYbrkbVzwLbZNRXLXMaMenbDerIOfnwsxACUMKuJDkCQxRjqJOCKUmuaxVxmgqpFtslytkgcZkHJWyDVDMhRidyqJnTXLaxxPFiWosiPQrylrEhdmZcBNBNAcOwnzkGzrTpFWLIQwbvKhCSCsJCxWxvQZJcfpfKfObyhVzRtFzkonbGvcCoBpaUkXCnximlWRhlDejOKMmNhYmmwHWJOssJLJCFNdnImFgFhTFECwnIZmYhRaNeUMkqAlZCSJAQFxVmeZgXXhlMLqYUssjRpcaYSNaAvJxIlQazzqrNTGtVFXQszGDERFkfjWRwoFAKxycwNdjZqXdRholAafGZrWtUWKuupahZZIsuWnyyBUPcnXxTvULFyXFSImvXCFKNhpxBQoorDH</supplierName>
               <supplierAddress>
                  <ns2:detailedAddress>
                     <ns2:countryCode>HU</ns2:countryCode>
                     <ns2:region>Békés</ns2:region>
                     <ns2:postalCode>5600</ns2:postalCode>
                     <ns2:city>KQofhSV1r8VvktC9Dc8oJqhXDqr2XM</ns2:city>
                     <ns2:streetName>wxRlJXqzgwj7IHuMgKy21U6kc4Wtyr</ns2:streetName>
                     <ns2:publicPlaceCategory>KJmrDZZJoq</ns2:publicPlaceCategory>
                     <ns2:number>47</ns2:number>
                     <ns2:building>BB</ns2:building>
                     <ns2:staircase>99</ns2:staircase>
                     <ns2:floor>1</ns2:floor>
                     <ns2:door>35</ns2:door>
                     <ns2:lotNumber>252576</ns2:lotNumber>
                  </ns2:detailedAddress>
               </supplierAddress>
```

**Comment by NTCA-supporter** [comment]
Szia @vajayattila !
Ezeket az adatokat honnan kapod?
Itt nincs szükség semmilyen kódolásra sem beküldésnél, sem lekérdezésnél.
Segíts kérlek, hogy milyen oprációt hívtal, melyik környezeten, melyik api verziót...
Köszi

**Comment by vajayattila** [comment]
Nem hívtam semmit. Gondoltam megnézzem a minta xml csomagotokat (API sample XML 3.0) és a manageInvioce.xml első invoiceData tagjéből kiszedtem a BASE64 értéket, dekódoltam és abban található a korábban hivatkozott részlet. Csak próbáltam végigszaladni mennyire változtak a dolgok a 2.0-ához képest és akkor ütötte meg a szemem hogy kódolt adatok vannak.

**Comment by NTCA-supporter** [comment]
Ezek szerintem csak generált tesztadatok. Nincs szükség kódolásra, ezek csak random stringek.
Üdv

**Comment by vajayattila** [comment]
Értem. Akkor megnyugodtam. 
Azért rosszmájúan megjegyezném, hogy a "Teszt suplier", "Teszt város" stb. teszt adatok nem hoznák az emberre a szívrohamot :D
Köszönöm szépen, zárhatod a hibajegyet.

**Comment by NTCA-supporter** [comment]
Jogoasnak érzem a felvetést, megpróbálunk rajta javítani majd.
Köszi
