### ISSUE TITLE
[DOC] Doksiban customerTaxNumber helyett sok helyen customerTaxnumber szerepel

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#475]
A 43. ábra A CustomerVatDataType felépítését követő táblázatban mindenhol kis "n" betűs a customerTaxNumber szöveg. PDF jobb alján lévő számozás szerint 82-83. oldal.

**Comment by NTCA-supporter** [comment]
Javítottuk. Köszi a jelzést mégegyszer.
