### ISSUE TITLE
[Q&A] Hogyan tudom validálni az InvoiceData által tartalmazott xmlt notepad++ segítségével?

### ISSUE THREAD

**Issue by vajayattila** [nav-gov-hu/Online-Invoice#476]
Helló!

A kérdésem arra irányul, hogy az eddigiekben a notepad++ eszközt használtam az általunk elkészült xmlek validására a fejlesztési stádiumban. Ott egyszerű volt a helyzet, betöltöttem az XML-t és a validálásnál megadtam az invoiceData.xsdt. Ez szépen kiírta ha valamit nem jól hoztunk létre az xmlben és már szaladtunk is javítani.

Viszont a 3.0 verziójú interfacenél falnak futottunk ezzel. Amit idáig csináltam:
Az API sample XML 3.0.zipből kivettem a  manageInvoice.xmlt és a legelső InvoiceData tagból kiszedtem a BASE64 kódolású számla adatot, dekódoltam és az így kapott xmlt kiírtam egy minta.xml nevű fájlba.

Ezután az elején a következő módosítást követtem el:

a követekző sort cseréltem:
`<InvoiceData xmlns="http://schemas.nav.gov.hu/OSA/3.0/data" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/base">`

erre:
```
<InvoiceData 
	xmlns:common="http://schemas.nav.gov.hu/OSA/3.0/common" common:noNamespaceSchemaLocation="./common.xsd"
	xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/base" ns2:noNamespaceSchemaLocation="./invoiceBase.xsd"
	xmlns="http://schemas.nav.gov.hu/OSA/3.0/data" noNamespaceSchemaLocation="./invoiceData.xsd"
>
```

A xsdket (OSA Schemas_v3) birka módjára betettem a minta.xml mellé.

Boldogan kiválasztom a validálás funkciót és ezt a hibaüzenetet kapom:
```
Validation of current file using XML schema:

ERROR: Element '{http://schemas.nav.gov.hu/OSA/3.0/data}InvoiceData': No matching global declaration available for the validation root.
```

Na és itt a nagy kérdés. Mit csináljak, hogy jó legyen. Szeretném a fejlesztési ciklusban mindenképpen validálni és tesztelni a beküldendő xmleket, mert ezzel sok szarvasmarhaságtól tudom megkímélni teszt rendszert. Ez szerintem mindenki érdeke lenne.
Van esetleg erről valami egyszerű nem túl bonyolult leírás (olyan ezt írd be haver megoldásra gondolok)? Szívesen látnám. 
Előre is köszönöm.

**Comment by renced42** [comment]
@vajayattila A notepad++ nem ismeri alapból a katalógus xml-t ezért a fapados ellenőrzéshez az invoiceData.xsdben fel kell venni a schemaLocation attribútumot az import tagokba oda pedig a megfelelő elérési úttal az xsd-ket.

<xs:import namespace="http://schemas.nav.gov.hu/NTCA/1.0/common" schemaLocation="common.xsd"/>
	<xs:import namespace="http://schemas.nav.gov.hu/OSA/3.0/base" schemaLocation="invoiceBase.xsd"/>
Ezt követően a validáció jó lesz.

![image](https://user-images.githubusercontent.com/44041065/96873026-af9d1000-1474-11eb-92e0-e000ed9e0509.png)

**Comment by vajayattila** [comment]
Rendben, kipróbáltam működik.
Köszönöm szépen a segítséget, zárom a hibajegyet.
