### ISSUE TITLE
queryTransactionList operáció elérhetővé tétele a v3-as végponton

### ISSUE THREAD

**Issue by Mocsa1974** [nav-gov-hu/Online-Invoice#477]
Sziasztok!
Az lenne a kérdésem, hogy van-e arra lehetőség, hogy a v3-as végponton egyelőre csak a queryTransactionList operációt elérhetővé tegyétek?
A használati statisztika szerint vannak le nem kérdezett tranzakcióim (összesen 5 darab). A v2-es queryTransactionList sajnos nem adja vissza a tranzakciók aktuális státuszát. Igy minden tranzakciót újra le kell kérdezni, hogy a használati statisztika helyreálljon.
Nem szeretnék több száz tranzakciót végigkérdezni csak azért, hogy az 5 darab helyrejöjjön. Ha a v3-as menne az éles adatbázison akkor csak annak az 5-nek kérdezném le a statuszát amelyeknek a v3 Response-ban a requestStatus értéke FINISHED.

Előre is köszönöm

**Comment by NTCA-supporter** [comment]
Szia @Mocsa1974 !
Erre sajnos nincs lehetőség, mivel a 3.0-nak majd egy jóváhagyás után szabad csak élesednie, és egyszerre.
Ha esetleg írsz a hivatalos helpdesknek, lehet segítenek neked, hogy melyik az az 5 tranzakció.
Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet, további kérdés esetén nyisd újra kérlek.
Üdv
