### ISSUE TITLE
HTTP protokoll 1.0-s verzió kivezetésének tervezése

### ISSUE THREAD

**Issue by renced42** [nav-gov-hu/Online-Invoice#478]
A NAV az Online Számla rendszerrel kapcsolatos szoftveres és architektúra fejlesztésekkel összefüggésben kivezetni tervezi a HTTP 1.0-s protokoll támogatását. Tekintettel arra, hogy a mérések szerint az Online Számla rendszerbe érkező HTTP hívások jelentős számban tartalmaznak 1.0-s verzió számú hívásokat, szükséges felmérni ennek hatását. A kivezetés pontos dátumának meghatározását a felmérés eredményétől függően később tesszük közzé, előzetes tervek szerint a megvalósítást néhány hónapon belül kívánja végrehajtani a NAV. A HTTP 1.1-es protokoll továbbra is támogatott marad.
A témával kapcsolatos észrevételeket/kéréseket ebben a topicban várjuk.

**Comment by nbeeps2** [comment]
Hogy lehet erről meggyőződni, hogy ez érinti a számlázó programot vagy sem? Ha a program képest TLS1.2-es https oldalt megnyitni, akkor érintett lehet ebben a változásban vagy sem?

**Comment by DrotosTot** [comment]
Jó kérdés, hogy hogyan lehet a HTTP verziót kliensoldalon kikényszeríteni. Pl. a MS XMLHttpRequest esetén még nem láttam erre dokumentációt.

**Comment by renced42** [comment]
> Jó kérdés, hogy hogyan lehet a HTTP verziót kliensoldalon kikényszeríteni. Pl. a MS XMLHttpRequest esetén még nem láttam erre dokumentációt.

Nem tudod, nincs ilyen lehetőség. Ha jól tudom az XMLHttpRequest scriptben/böngészőben fut. Ezáltal a böngésző fogja ezt eldönteni, hogy miben küldi a kérést. Itt a böngészőnek kell támogatnia a Http 1.1-et.

**Comment by DrotosTot** [comment]
@renced42 : Nem csak böngészőből hívható, megy az még VB6-ból is:
[https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms762709(v=vs.85)]
Böngészőnél egyszerű lenne, mert ott a böngésző választ protokollt.

**Comment by nbeeps2** [comment]
Én indy10-en keresztül érem el a nav-os api-t, honnan tudom, hogy az milyen http 1.0-át vagy mit használ?

**Comment by DrotosTot** [comment]
@nbeeps2 :
Például https helyett (ami titkosított), http-n próbálunk meg egy tokenExchange operációt, közben Wireshark logolja a 84.206.52.71-es IP cím (ez a api-test.onlineszamla.nav.gov.hu IP-je) felé menő forgalmat.
Ebből már látszik is az eredmény, a kliens HTTP 1.1-el kommunikál:
![image](https://user-images.githubusercontent.com/70751006/97201914-43dbdf80-17b3-11eb-989d-9b6ee87ea679.png)

**Comment by renced42** [comment]
> Én indy10-en keresztül érem el a nav-os api-t, honnan tudom, hogy az http 1.0-át vagy mit használ?

Kedves @nbeeps2, @DrotosTot  nagyon sok framework, vagy programozási nyelv alapból 1.0-t használ, ha azt külön nem állítjuk át vagy nem tudja az oprendszer hívásán keresztül automatikusan kezelni.
Szerintem az Indy10 sem tér el ettől a hagyománytól.
Tesztelni úgy tudod, hogy ha telepítesz pl.: webszervert és meghívod egy mintaprogrammal, ami adott nyelvvel készült. Annak az access logjából azonnal kiderül, mit használ. Vagy logolod a forgalmat HTTP-n

**Comment by DrotosTot** [comment]
@renced42 Sokáig ezért nem szóltam hozzá, mert kicsit furcsának tartottam az 1.0 kivezetésének ötletét a részetekről.

**Comment by renced42** [comment]
> @renced42 Sokáig ezért nem szóltam hozzá, mert kicsit furcsának tartottam az 1.0 kivezetésének ötletét a részetekről.

Kedves @DrotosTot , nincs ebben semmi furcsa, az idő halad, a technológiák fejlődnek, új szoftver verziókban meg már nem rakják bele vagy kikapcsolják alapból a régi protokollok támogatását. Defacto alapértelmezett http protokoll az 1.1 és már valahol a 2.0.
A http 1.0 szép karriert futott be, de nagyon elkopott.

**Comment by nbeeps2** [comment]
@renced42 ok, megtaláltam Indy10 gyárilag 1.1-t használ, annál újabbat nem szóval örülnék, hogy ha ugyanígy később majd az 1.1  nem lenne kivezetve, mert akkor meg leszek lőve és gondolom így lehetnek mások is most az 1.0-val, de majd csak jelentkeznek. Értem, hogy ha valami kikopott, akkor kivezetitek, csak abba is gondoljatok bele, hogy vannak 20 éves olyan kiforrott rendszerek, amibe 20 évnyi munka van, nyilván régi technóligán alapul, viszont ezeket nem lehet csak úgy egyik hónapról a másikra átírni egy új programnyelvbe.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet. Ha van még kérdés nyissátok újra nyugodtan.
Üdv
