### ISSUE TITLE
[FEATURE]Javaslat QueryTransactionList és/vagy QueryTransactionStatus lekérdezés bővítésére

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#479]
A V2 dokumentáció utolsó bővítése javasolja a meg nem kapott tranzakció azonosítók elérésére a transactionList-ben található, nem ismert azonosítók esetében a számla visszakérését és annak adatai alapján a beazonosítást.
V3 esetén véleményem szerint sokkal egyszerűbb lenne az electronicHash alapján történő azonosítás (már persze akkor, ha van ilyen, de ez talán többeket rávenne a használatára). A V3-ban ez már API szinten van, vagyis a szervernek nem jelentene gondot visszaadni.
QueryTransactionStatus esetén a processingresult-ban, transactionList esetén a transactionType-ban visszaadható.
Ezzel a változtatással a számlák visszakérése és kliens oldalon azok elemzése nélkül azonosítható lenne a számla, amihez a tranzakció tartozik, feltéve, hogy a kliens használja és tárolja a hash értékeket.

**Comment by NTCA-supporter** [comment]
Szia @kabelnet2 !

Az electronicInvoiceHash számla szintű adat, nem pedig trnazakció szintű, és ugye optional is. 
Ennek így nem látom értelmét, főleg nem hogy egy alsóbb szintű adat alapján keressünk.

Üdv

**Comment by kabelnet2** [comment]
"electronicInvoiceHash számla szintű adat"
Természetesen. Egy ismeretlen tranzakció beazonosítása csak a benne található számlák alapján történhet. Ti azt javasoljátok, olvassuk vissza magát a számlát és abból szedjük ki pl. a számlaszámot. Az ugyan úgy számlaszintű adat.
Az, hogy egy tranzakcióhoz több számla is tartozhat, szerintem szintén nem gond, hiszen senki nem fogja a tranzakció összes számláját visszaolvasni és elemezni a beazonosításhoz. Mivel a számlaszám és a hash is egyedi, egy ilyen is elég a beazonosításhoz.
" alsóbb szintű adat alapján keressünk"
valami félreértés van, biztosan nem jól fogalmaztam. Nem ti, hanem mi keresnénk. Az egész ötlet arra jött, amit a V2 doku kiegészítésében írtatok az 1.9.2 fejezetben:
"Ha a listában (queryTransactionList) szerepel olyan tranzakció azonosító, amelyet a kliens nem ismer, akkor ott a feldolgozási eredmény lekérdezésével (/queryTransactionStatus, ügyelve arra, hogy a returnOriginalRequest tag értéke legyen true) vissza lehet kérni a beküldött számla adatokat is, amely által a válasz adatai alapján a számlázóprogram adatbázisában összevezethető, hogy mely számlák mely tranzakció azonosítóhoz tartoznak."
Ezt a beazonosítást lehetne - szerintem - egyszerűbben megoldani a leírt módon.
Az, hogy nem mindenki használ electronicHash-t - nem ez az egyetlen dolog, amit nem mindenki használ, mégis visszaadtok. Ebből még nem lenne gond.
Én tartom, hogy lenne értelme, de ahogy gondoljátok.

**Comment by renced42** [comment]
Kedves @kabelnet2  Ha jól értelmezem itt az igény az volna, hogy, egyszerűen meg győződjön a program arról, hogy a számlája bent van-e vagy sem. Nem akarj a számlát vagy annak más adatát visszakérni csak a számlához tartozó TRID-t. 
Vagyis lenne egy olyan lekérdezés, ami tartalmazza az eladó adószám + számla sorszám + kiállítás dátuma  triót és az visszaadja a hozzá tartozó TRID-t?

**Comment by kabelnet2** [comment]
Nem, ez a lekérdezés létezik, ez a queryTransactionList.
A szituáció a következő (leírom, ami a V2 doku 1.9.2-ben van): a felhasználó szeretne meggyőződni, hogy mindenben megfelelt a jogszabályi kövezelményeknek és minden beküldött adatát le is kérdezte. Ezért egy tól-ig dátum tartományra lekérdezi a transakciók listáját. Az visszaadja a tranzakciók azonosítóját és állapotát.
Ebben a listában lehet olyan tranzakció is, amit a felhasználó nem ismer. Mert elküldte a számlát, de közben megszakadt az Internet és nem kapta vissza a tranzakció azonosítóját. Ebben az esetben valahogy össze kell hozni a számláit és a tranzakció azonosítót, amit nem ismer.
Erre javasoljátok a dokuban, hogy kérje le a számla adatait és vegye ki belőle a számlaszámot, amivel azonosítani tudja, hogy melyik számlájához tartozik a tranzakció.
Itt merült fel bennem, hogy ezt az azonosítást lehetne egyszerűsíteni, ha a tranzakció listában visszaadnátok egy electronicHash értéket is, hiszen azzal pontosan olyan jól lehet azonosítani, mint számlaszámmal. Már persze, ha használja. Ez nem igényelne újabb lekérdezést a számlaadatokra, ami ráadásul nagy adatforgalmat is generálhat, ha nagy a számla, a queryTransactionList-ben minden meglenne, ami a beazonosításhoz szükséges.
Tehát semmi új lekérdezés, a queryTransactionListResponse-ban a transaction listában az azonosítók mellett lenne pluszban ez az adat (electronicHash). Így a felhasználó a hash alapján, külön lekérdezés nélkül meg tudná keresni, hogy melyik számlája tartozik a tranzakcióhoz. Ha több számla is van a transakcióban, szerintem elég lenne egyet megadni, mert azzal is azonosítható a cliens oldalon a csomag, aminek az azonosítója nem ismert.

**Comment by NTCA-supporter** [comment]
Szia @kabelnet2 !
Értem a motivációdat, hogy 1 lépést meg akarsz spórolni, de nem támogatom.
A tranzakciólistázó arra való, hogy a tranzakciókat kilistázzuk. A tranzakción belüli számlák adatainak lekérdezésére ott van a queryTransactionStatus.
Ha már a queryTrancationListResponse-ba beletennénk a hask-ek listáját, akkor már beletehetnénk az invoiceNumberek listáját is és így tovább, akkor már a WARN-okat is beletehetnénk stb. 
Szerintem a leírás alapján megoldható a beazonosítás.
Üdv

**Comment by kabelnet2** [comment]
Szia, és a queryTransactionStatusResponse-ba? Mert az issue címében és/vagy-al mindkettő benne van. Mert különben csak az invoiceData-val kaphatom meg, amihez viszont már invoice number is kell, ha meg az megvan, akkor már minek...

**Comment by NTCA-supporter** [comment]
@kabelnet2 na ez már nekem is szimpatikusabb, az originalRequest mellett el tudnám képzelni a helyét.
Futok vele egy kört és visszajelzek.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ez végül nem jutott el a megvalósításig, voltak fontosabb feladatok.
Zárom az issuet.
Üdv
