### ISSUE TITLE
Authentication doesn't work on test api: https://api-test.onlineszamla.nav.gov.hu/invoiceService/tokenExchange

### ISSUE THREAD

**Issue by danielrusu** [nav-gov-hu/Online-Invoice#48]
Hello,
As developer I received the credentials from the client and tried to make a request to https://api-test.onlineszamla.nav.gov.hu/invoiceService/tokenExchange using following xml structure:
```
<?xml version="1.0" encoding="UTF-8"?>
<TokenExchangeRequest xmlns="http://schemas.nav.gov.hu/OSA/1.0/api">
    <header>
        <requestId>RID027473100156208548513577</requestId>
        <timestamp>2019-07-02T16:38:05.275Z</timestamp>
        <requestVersion>1.1</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
    <user>
        <login>************</login>
        <passwordHash>*******</passwordHash>
        <taxNumber>*******</taxNumber>
        <requestSignature>*******</requestSignature>
    </user>
</TokenExchangeRequest>
```

On test environment (https://api-test.onlineszamla.nav.gov.hu/invoiceService/tokenExchange)  response is: 
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GeneralErrorResponse xmlns="http://schemas.nav.gov.hu/OSA/1.0/api" xmlns:ns2="http://schemas.nav.gov.hu/OSA/1.0/data">
    <header>
        <requestId>RID027473100156208548513577</requestId>
        <timestamp>2019-07-02T16:38:05.275Z</timestamp>
        <requestVersion>1.1</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
    <result>
        <funcCode>ERROR</funcCode>
        <errorCode>INVALID_SECURITY_USER</errorCode>
        <message>Helytelen authentikációs adatok!</message>
    </result>
</GeneralErrorResponse>
```

On live environment (https://api.onlineszamla.nav.gov.hu/invoiceService/tokenExchange) response is:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TokenExchangeResponse xmlns="http://schemas.nav.gov.hu/OSA/1.0/api" xmlns:ns2="http://schemas.nav.gov.hu/OSA/1.0/data">
    <header>
        <requestId>RID027473100156208548513577</requestId>
        <timestamp>2019-07-02T16:38:05.275Z</timestamp>
        <requestVersion>1.1</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
    <result>
        <funcCode>OK</funcCode>
    </result>
    <encodedExchangeToken>***********</encodedExchangeToken>
    <tokenValidityFrom>2019-07-02T18:39:53.475+02:00</tokenValidityFrom>
    <tokenValidityTo>2019-07-02T18:44:53.475+02:00</tokenValidityTo>
</TokenExchangeResponse>
```
Am I missing something? Because in this point cannot proceed to send invoice on live environment without proper testing, which fails as I described above.

**Comment by bsibsi** [comment]
Hi Daniel,
based on the above I suspect that you're trying to use the very same credentials for both TEST and LIVE environments, however they are completely separate, with different users and passwords. Ask your client to generate a technical user in the TEST environment too and try again with that.

**Comment by danielrusu** [comment]
> Hi Daniel,
> based on the above I suspect that you're trying to use the very same credentials for both TEST and LIVE environments, however they are completely separate, with different users and passwords. Ask your client to generate a technical user in the TEST environment too and try again with that.

This is exactly what I did. I transmitted to the client to generate a test account. Thank you very much for the prompt response. 
Best regards, 

Daniel.
