### ISSUE TITLE
Q&A issue Class generálás hiba XSD 3.0-ból

### ISSUE THREAD

**Issue by scheeri** [nav-gov-hu/Online-Invoice#480]
Üdv!

Valamiért semmilyen módon nem sikerül a classokat legenrálni az xsd-ből:

**_scheeri@istvan:~/work/navonline$ xjc -catalog catalog.xml -classpath . *.xsd
parsing a schema...
[ERROR] src-resolve: Cannot resolve the name 'base:InvoiceTimestampType' to a(n) 'type definition' component.
  line 55 of file:/home/scheeri/work/navonline/invoiceAnnulment.xsd

Failed to parse a schema.
scheeri@istvan:~/work/navonline$_** 

Az InvoiceTimestampType definíciót nem találja.
Kérem segítsenek! Lehet hogy hibás az XSD vagy én csinélom rosszul? Ez eddig működött.

**Comment by renced42** [comment]
Szia! 

Mondok egy egyszerű megoldást majd később kidolgozunk egy szebbet és kipublikáljuk:

Másold az össes XSD-t egy mappába (pl: c:\temp) a catalog.xml-el együtt.

Catalog xml így nézzen ki: 

<?xml version='1.0' encoding='UTF-8'?>
<catalog xmlns='urn:oasis:names:tc:entity:xmlns:xml:catalog' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='urn:oasis:names:tc:entity:xmlns:xml:catalog Catalog.xsd' prefer="public">
	<uri name="http://schemas.nav.gov.hu/NTCA/1.0/common" uri="common.xsd"/>
	<uri name="http://schemas.nav.gov.hu/OSA/3.0/base" uri="invoiceBase.xsd"/>
</catalog>

Ezután minden XSD-ben ahol van egészítsd ki így az importokat (kivéve az invoiceBase.xsd-t ott csak a common.xsd kell):

<xs:import namespace="http://schemas.nav.gov.hu/NTCA/1.0/common" schemaLocation="common.xsd"/>
<xs:import namespace="http://schemas.nav.gov.hu/OSA/3.0/base" schemaLocation="invoiceBase.xsd"/>

hozd létre a c:\temp\out mappát

Ha ez meg van akkor add ki az alábbi parancsokat:
xjc.exe -d c:\temp\out -catalog c:\temp\catalog.xml c:\temp\invoiceApi.xsd
xjc.exe -d c:\temp\out -catalog c:\temp\catalog.xml c:\temp\invoiceData.xsd
stb...
és már kész is :)

![image](https://user-images.githubusercontent.com/44041065/97082821-c1192000-160c-11eb-9ea8-eeb273519747.png)

**Comment by renced42** [comment]
A fenti normál osztálygeneráláson kívül másik megoldás ha a catalog.xml belsejét az alábbiak szerint szerkeszted meg:

Ez helyett:
	<uri name="http://schemas.nav.gov.hu/NTCA/1.0/common" uri="common.xsd"/>
	<uri name="http://schemas.nav.gov.hu/OSA/3.0/base" uri="invoiceBase.xsd"/>

Ezt teszed be:
	<public publicId="http://schemas.nav.gov.hu/NTCA/1.0/common" uri="common.xsd"/>
	<public publicId="http://schemas.nav.gov.hu/OSA/3.0/base" uri="invoiceBase.xsd"/>


Ebben az esetben az XSD-k belsejébe nem kell a schemaLocation attribútumot felveni.

Ezzel a paranccsal lehet az osztályokat legenerálni:

c:\Program Files\Java\jdk1.8.0_191\bin>xjc -d c:\temp\out -catalog c:\temp\catalog.xml c:\temp\invoiceApi.xsd

**Comment by scheeri** [comment]
Nem szép, de működik. Köszönöm a segítséget!
