### ISSUE TITLE
[FEATURE] VatRateType - Boolean vs. case/reason

### ISSUE THREAD

**Issue by Rossi73** [nav-gov-hu/Online-Invoice#481]
**Az igény összefoglalása / Summary of the request**
A 3.0-ban módosított VatRateType típusban a „reason” egy ideje izgatja a fantáziámat. Eddig egy Boolean értéket kellett megadni, most viszont case/reason értékpárt vár a rendszer kötelezően.

Utánaolvastam a dokumentációban és a ChangeLogban is. Ez utóbbiban ennyi szerepel:

_„Ha a programod kezel ÁFA mentes (vatExemption) és ÁFA hatályon kívüli (vatOutOfScope) számlákat, akkor a különböző esetekre az interfész dokumentáció által meghatározott értékkészlet alapján kínálj fel listás beviteli lehetőséget a UI-on, vagy a felhasználó által transzparensen feleltesd meg a saját értékeid ennek az értékkészletnek, ha erre lehetőséged van. Az enumerált értéket a case tagban, a felhasználó által a számlára felvitt értéket pedig a reason tagba helyezd el az XML-en belül mind számlasor, mind számlaösszesítő szinten. (értékkészlethez ld: PDF 126. oldal)”_

A dokumentációban a „reason” szó és az „adómentesség” szó mindössze a struktúraleírásban, illetve a hibakódokban fordul elő. Tehát, hogy mi az „oka” a reason használatának, azt igazából nem indokolták.

Ugyanakkor a GitHubon kapott infó szerint elegendő az, ha a program felajánl egy listát, amiből választhat a felhasználó, és ha code = „AAM”, akkor megfelelő, ha reason = „alanyi adómentes” (PDF 126. oldal).

Ha a NAV-nak megfelelő tehát, hogy a NAV saját értékkészletében meghatározott adatot küldjük be minden esetben a reason tagben, akkor felmerül a kérdés, hogy vajon mi értelme van a reason tag használatának?

Félre ne értsen senki, természetesen elfogadom, hogy lehet ennek értelme, csak nehezen tudom elképzelni, hogy lesz olyan fejlesztő, aki a következőképpen oldja ezt meg:

„Az 5. számlatétel áfa kulcsa AAM. A NAV leírás szerint ennek jelentése „alanyi adómentes”. Szeretné ezt használni, vagy szeretne megadni más szöveget az AAM áfa kulcshoz?” (ráadásul ezt minden egyes érintett számlatétel esetén fel kellene tenni, esetleg a „válasz megjegyzése” opció használatával – de akkor az csak erre a számlára vonatkozik, vagy erre a partnerre, esetleg innét kezdve minden „AAM” áfa kulcsos tételre?)

Ha a NAV arra kíváncsi, hogy milyen, a saját értékkészletétől eltérő egyedi elnevezések, indoklások fordulhatnak elő, akkor persze maradhat ez a dolog, de ha „csak” arra kíváncsi, hogy melyik ÁFA kulcs hányszor fordul elő, akkor talán elegendő lenne csak a case tag használata, esetleg a reason tag opcionálissá tétele...

**Comment by nbeeps2** [comment]
@Rossi73 A reason-be a számlán a felhasználó által FELTÜNTETETT indokot kell megadni (hogy miért 0% az ÁFA), ami nem feltétlen az ÁFA kulcs neve. Erről valamelyik másik topikban volt említés.

**Comment by nbeeps2** [comment]
Na megtaláltam: #454 "Amennyiben egy számlán van valamilyen adómentes tétel, akkor az adómentesség okát a számlán szerepeltetni kell. Ez lehet akár a felhasználó által beírt szöveg, de a számlázó program is adhat valamilyen előre elkészített szöveget, vagy rövidítést. Ennek a szövegnek kell mennie a reason elembe"

**Comment by nbeeps2** [comment]
Nekem az alábbi kérdésem lenne valószínűleg @NTCA-tax -hoz:

1.
Mi a különbség a vatExemption/case "KBAET - adómentes Közösségen belüli termékértékesítés" és a vatOutOfScope/case "EUE - Másik tagállamban teljesített nem fordítottan adózó ügylet" között?

Ha EU-n belül értékesítek valamit 0% ÁFA-val, akkor a KBAET vagy az EUE kulcsot kell használni?

2.
Mi a különbség a vatExemption/case "EAM - adómentes termékértékesítés a Közösség területén kívülre (termékexport harmadik országba" és a vatOutOfScope/case "HO - Harmadik országban teljesített ügylet" között?

Ha az USA-ba adok el valamit 0% ÁFA-val, akkor az EAM vagy a HU kulcsot kell használni?

**Comment by NTCA-tax** [comment]
Az eredeti kérdést egész jól megmagyaráztátok, köszönet érte :)

Az utolsó kérdés kapcsán az elkülönítés:
KBAET: ez a klasszikus közösségi értékesítés, amikor közösségi fordított adózás van.
EUE: másik tagállamban teljesített ügylet, ami után nem a másik tagállami termékbeszerzőt, szolgáltatás igénybevevőt terheli az adófizetési kötelezettség. Fontos, hogy ez hatályon kívüli értékesítés és nem mentes, mint a KBAET.

EAM: Áfa törvény 98-109. §-ai alapján mentes ügyletek tartoznak ide (fontos, hogy ez adómentes és nem hatályon kívüli!).
HO - harmadik országban teljesített ügyletek esetében az áfa hatályán kívüli értékesítés van.

**Comment by EnokhSys** [comment]
> Az eredeti kérdést egész jól megmagyaráztátok, köszönet érte :)
> 
> Az utolsó kérdés kapcsán az elkülönítés:
> KBAET: ez a klasszikus közösségi értékesítés, amikor közösségi fordított adózás van.
> EUE: másik tagállamban teljesített ügylet, ami után nem a másik tagállami termékbeszerzőt, szolgáltatás igénybevevőt terheli az adófizetési kötelezettség. Fontos, hogy ez hatályon kívüli értékesítés és nem mentes, mint a KBAET.
> 
> EAM: Áfa törvény 98-109. §-ai alapján mentes ügyletek tartoznak ide (fontos, hogy ez adómentes és nem hatályon kívüli!).
> HO - harmadik országban teljesített ügyletek esetében az áfa hatályán kívüli értékesítés van.

Kedves @NTCA-tax,

köszönöm/köszönjük a magyarázatot, de valahol jó lenne példákkal is szemléltetni mindezt, mert annyira bonyolult ez az egész ÁFA menteségi/kívüliségi törvény, hogy még a könyvelők is tanakodnak rajta.

Szóval, van EU-s adószámom, importálok az EU-ból pl. dán szalámit, majd ezt eladom egyaránt belföldre és külföldre az EU-n belül. A külföldi vevőnek is van EU-s adószáma, export számlát állítok ki neki 0 ÁFA-val, de amikor beküldöm a NAV-hoz a számlát, akkor "KBAET"-et, vagy "EUE"-t kell használnom?

**Comment by NTCA-tax** [comment]
A módosított interfész dokumentáció tartalmazza az általatok kért példákat. Ezért ezt az issue-t lezárom.
