### ISSUE TITLE
[FEATURE] Számla megjegyzés átadása sortörés és tabulátor vezérlőkarakterekkel. 

### ISSUE THREAD

**Issue by EnokhSys** [nav-gov-hu/Online-Invoice#484]
**Az igény összefoglalása / Summary of the request**

A kinyomtatott számlán, a felhasználók szeretnek megjeleníteni különböző szöveges információkat az adott ügylettel kapcsolatban. Ha az információ sokrétű, akkor a megjegyzés mezőt úgy szerkesztik, hogy azt két-három sorba tördelik enterrel (CR+LF). De olyan eset is van, amikor a felsorolás jellegű információkhoz, tabulátort használnak. 
Már tavasszal is jeleztem, hogy amikor a megjegyzés mezőt próbálom átadni az "additionalInvoiceData" szegmenscsoportban, akkor "SCHEMA_VIOLATION"-nel hibára fut a feldolgozás:

_XML contains on line: [76] and column: [26] error: [cvc-pattern-valid: Value 'Sortörés próba, első sor; második sor; harmadik sor.' is not facet-valid with respect to pattern '.*[^\s].*' for type 'SimpleText512NotBlankType'.]_

**Az általam javasolt megoldás / The solution I propose**

Tekintettel az "adatszolgáltatás mint elektronikus számla" funkció bevezetésére a v3.0-ás verziótól, egy füst alatt érdemes lenne megoldani ezt a problémát is. Eddig ugyanis nem volt fontos a megjegyzés mező átadása, de elektronikus számla esetén fontos információkat tartalmazhat, ezért célszerű lenne bevezetni egy olyan szövegtípust, amely elfogadja a sortörést és a tabulátort. Vagy akár a "common:SimpleText512NotBlankType" készletértékét is ki lehetne bővíteni ezekkel. 

**Elfogadható alternatívák / Acceptable alternatives**

Nem hiszem, hogy lenne. Programozásilag, semmiből sem állna kivakarni átadás előtt a sortörés és tabulátor vezérlő-karaktereket, de azzal különbség jönne létre a lezárt számla kinyomtatott/tárolt adattartalma és a NAV OnLine Számlának átadott adattartalom között.

**Comment by Rossi73** [comment]
> Tekintettel az "adatszolgáltatás mint elektronikus számla" funkció bevezetésére a v3.0-ás verziótól, egy füst alatt érdemes lenne megoldani ezt a problémát is. Eddig ugyanis nem volt fontos a megjegyzés mező átadása, de elektronikus számla esetén fontos információkat tartalmazhat, ezért célszerű lenne bevezetni egy olyan szövegtípust, amely elfogadja a sortörést és a tabulátort. Vagy akár a "common:SimpleText512NotBlankType" készletértékét is ki lehetne bővíteni ezekkel.

Esetleg érdemes lenne megfontolni a kiterjesztést az additionalInvoiceData mellett az additionalLineData elemre is...

**Comment by EnokhSys** [comment]
> > Tekintettel az "adatszolgáltatás mint elektronikus számla" funkció bevezetésére a v3.0-ás verziótól, egy füst alatt érdemes lenne megoldani ezt a problémát is. Eddig ugyanis nem volt fontos a megjegyzés mező átadása, de elektronikus számla esetén fontos információkat tartalmazhat, ezért célszerű lenne bevezetni egy olyan szövegtípust, amely elfogadja a sortörést és a tabulátort. Vagy akár a "common:SimpleText512NotBlankType" készletértékét is ki lehetne bővíteni ezekkel.
> 
> Esetleg érdemes lenne megfontolni a kiterjesztést az additionalInvoiceData mellett az additionalLineData elemre is...

@Rossi73 egyetértek. Habár én nem használom, de másoknak lehet, hogy szükséges.

**Comment by DrotosTot** [comment]
Jaj, de jó, hogy nyitva van, mi is beleszaladtunk. Egyelőre kiszedjük a sortörést.

**Comment by jozanesz** [comment]
Valószínűleg nem szándékos a korlátozás, csak nem vették figyelembe, hogy a legtöbb regexpértelmezés alapján a sortörés nem illeszkedik a pont karakterre. Helyesen a minta: `[\s\S]*\S[\s\S]*` lenne. Ahol pedig fontos a kezdő és záró \s kizárása, ott `\S([\s\S]*\S)?`.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Az xsd-n már nem tervezünk változtatni, ezért zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
