### ISSUE TITLE
GLN számok szerepeltetése az API-ban - ebben a formában értelmetlen.

### ISSUE THREAD

**Issue by EnokhSys** [nav-gov-hu/Online-Invoice#485]
**Az igény összefoglalása / Summary of the request**

A v3.0-ban bevezetésre került a "conventionalInvoiceInfo" szegmenscsoport, amelyben szerepel a "glnNumber" szegmens. A leírásból nem derül ki, hogy ez most a szállítónak vagy a vevőnek a GLN száma, de akár több GLN számot is fel lehet sorolni. Ez viszont így értelmetlen, hiszen a GLN számokat az esetek +90%-ban az EDI-n küldött elektronikus rendelésekben és elektronikus számlákban használjuk, de ott kötelezően. Az is fontos, hogy azok a vevők, akik EDI-n kommunikálnak, szinte minden esetben kérik, hogy a számlán legyen feltüntetve a szállítási cím is, annak GLN kódjával együtt. Tehát látni kell azt, hogy az áruházláncok nem egy-, hanem két címet kérnek a számlára. (Van olyan áruházlánc, amely három gln-es címet kér, na őmiatta már többször dőltem kardomba : 1. rendelést küldő; 2. számlabefogadó; 3. szállítási cím.) 

**Az általam javasolt megoldás / The solution I propose**

El kellene dönteni, hogy van-e értelme olyan adatokat szerepeltetni a NAV OnLine Számla rendszerében, amelyek az EDI-számlázás során napi használatban vannak. Amennyiben igen, akkor valamely jövőbeni verzióban, az alábbi adatokat célszerű lenne felvenni:

Számla fej szinten:
- a "supplierInfo" szegmenscsoport bővítése a GLN számmal
- a "customerInfo" szegmenscsoport bővítése a GLN számmal
- "deliveryInfo" szegmenscsoport bevezetése a szállítási címnek (név, címadat, GLN szám)
- "customerOrderNumber" szegmens, a vevő által küldött rendelésszámhoz
- "customerOrderDate" szegmens a vevő rendelésének dátumához

Számla tétel szinten:
- "itemEAN" a termék EAN kódja
- "customerItemNumber" a vevő cikkszáma

Megjegyzés: az "itemEAN"-t egyébként is érdemes lenne betenni a "conventionalLineInfo" szegmenscsoportba.

**Comment by Amn3s1a2018** [comment]
A jelenlegi xsd alapján az egyes infókból feladható több is, tehát lehet akár három _`glnNumbers/glnNumber`_ node, az meg egyéni megállapodás kérdése, hogy mindig mind szerepel-e és melyik-melyik.
Az, hogy EDI-vel párhuzamosan az OnlineSzámla rendszeren keresztül IS kommunikálj a vevővel valóban már önmagában értelmetlennek tűnhet, hacsak nem egy már megkövesedett „legacy” rendszert akarsz vele kiegészíteni. (Pl. nem tudsz három GLN-t küldeni EDI-n, de szerződéskódokat vagy gyártási számokat, vagy az egyedi dobozok/gyűjtők kódjait meg nem akarod a NAV-on keresztül tuszkolni)
Ezek a lehetőségek egyébként abba az irányba mutatnak, hogy a beküldött számlák adattartalma cégpáronként eltérő lesz, és nem tudom ez mennyire jó irány (bár a nyomtatott és EDI számlákon már régóta ez a helyzet)
A fent javasoltak jók lehetnek ezeknek az egységesítésére, de mivel csak opcionálisan lehetne bevezetni és keveseket érint akiknek egy része már most is használja a saját sufni megoldását ezért nincs igénye másra, nem egyhamar lesz ennek gyakorlati haszna.

**Comment by EnokhSys** [comment]
@Amn3s1a2018 Hosszabban fogok válaszolni, mert a javaslatom egy koncepció része, csak most kissé összecsapnak a fejem fölött a hullámok, pedig nem én vagyok az Unicum-os ember.

**Comment by EnokhSys** [comment]
Kedves @Amn3s1a2018 (és @NTCA-developer)!

Megígértem, hogy bővebben fogok válaszolni, amelyben felvázolom a koncepciómat, amiről tulajdonképpen egy szót sem ejtettem a topiknyitó hozzászólásomban.

Tisztában vagyok azzal, hogy több GLN számot is meg lehet adni a "conventionalInvoiceInfo" szegmenscsoportban, de mint mondtam, ebben a formában nincs sok értelme. Elsősorban azért, mert minden vevő-szállító megállapodik egy-egy GLN szegmensnévben, amely ritkán azonos, ezért aztán ezek a szabvány, nemzetközi kódok annyi néven fognak futni, ahány vevő+szállító megállapodás van, és általában a vevő diktál, a szoftverfejlesztő meg megbolondul tőle. Ezért is lenne célszerű eldönteni, hogy amennyiben a jövőben komolyabb szerepe lesz, akkor bővíteni kellene a megfelelő ügyfél-adatokat.

Látni kell azt, hogy ma Mo-n leginkább az áruházláncokkal nagykereskedelmi tevékenységet folytató cégek használják az EDI-t. (Javítsatok ki kérlek, ha tudtok még olyan gazdasági szektort, ahol ez használatban van, mert nekem nem jut eszembe.)
Ezt viszont nem csupán elektronikus számlázásra, hanem rendelésküldésre és annak visszaigazolásra is aktívan használják. Ugyanakkor a szállítólevelek továbbra is papíralapon mennek, annál is inkább, mert a sofőr egy útellenőrzés során be tudja mutatni a szállítólevélen szereplő EKAER számot. Ezen kívül van egy sor bolthálozat, akik nem használnak EDI-t, a rendeléseket e-mailben adják le, az ügyintéző berögzíti, és legfeljebb csak a számlát kapják elektronikusan, PKI-n. Ugyanez a helyzet az export-import nagyker esetén.

Ebben a relációban, a NAV jelenleg két külön kommunikációs csatornát működtet, az egyik az 5 éve bevezetett EKAER, a másik az OnLine Számla. Én nagyon remélem, hogy a NAV felső vezetői között vannak olyan nyitott- és jövőben gondolkodó informatikai szakemberek, akik megértik azt, hogy milyen hatalmas potenciál rejlik abban, ha a jelenlegi két csatornát összevonják, és egy olyan kommunikációs platformot fejlesztenek ki, amely nem csupán a NAV-nak hasznos, hanem a gazdasági társaságok is előszeretettel fognak használni.

Szerintem a jövőben első lépésként a jelenlegi EKAER rendszert kellene újragondolni, és párhuzamos ágként bele kellene vonni a NAV OnLine Számla rendszerébe (pl. NAV OnLine Szállítólevél néven). Ez a NAV-nak hatalmas előnyt jelentene, hiszen attól kezdve nem csupán az EKAER számok kiadását, ellenőrzését látná el, hanem (szinte minden) OnLine Számla rendszerbe beküldött számla mellett ott lenne a teljesítés dokumentuma. Ugyanakkor az is fontos, hogy ahogyan jelenleg az OnLine Számla rendszerében megteremtették az "adatszolgáltatás mint elektronikus számla" lehetőségét, a szállítólevelet se kelljen kinyomtatni papíron, hanem elektronikusan mehetne az is a vevőnek a NAV rendszerén keresztül. A vevő pedig az áru átvételét követően korrigálhatja az átvett mennyiségeket pont úgy mint most, amikor papíron áthúzza a sérült, hiányos stb. át nem vett mennyiségeket, majd ezt leigazolná a szállító felé. 

De ne álljunk meg itt, hiszen az egész platform akkor jelentene igazi előnyt, ha utolsó lépcsőként, ezek mellé párhuzamosan kifejlesztésre kerülne a NAV OnLine Rendelés rendszere is, ami azon nagyker cégek számára jelentene megoldást, akiknek nem éri meg EDI-vel foglalkozni, viszont egy egyszerű, folyamatosan terjedő kommunikációs platform jócskán megkönnyítené az életüket. Azt hiszem egy ilyen megoldásra egész Európában felkapnák a fejüket, mert nem csak azt mutatná meg, hogy egy állami adóhivatal miként tudja hatóságként alkalmazni a technológiát, hanem azt is, hogy miként tud partnerként beszállni egy ország gazdasági életének működtetésébe.

Természetesen ez a NAV féle platform nem lenne konkurenciája az EDI-szolgáltatóknak. Akik eddig is EDI-alapon kommunikáltak, azok szinte biztos nem fognak váltani, mert már "bejáratott motorjuk" van, és eleve valamely nemzetközi holdingba, cégcsoportba tartoznak, ezért az ott szabványosított technológiákat fogják továbbra is alkalmazni. 

Röviden ez lenne a lényeg; van ugyan még egy-két dolog a fejemben ezzel kapcsolatban, de mivel ez az egész egy hosszú távú koncepció, per pillanat nem fontos.

**Comment by NTCA-tax** [comment]
A conventionalInvoiceInfo elemeit hozzánk beérkezett javaslatok alapján alakítottuk ki. Köszönjük a fenti észrevételt, javaslatot is. A sémában ennek megfelelően pontosítottuk a GLN számokat. @EnokhSys

**Comment by EnokhSys** [comment]
@NTCA-tax nagyon szívesen! :-)
