### ISSUE TITLE
[Q&A] completenessIndicator használata

### ISSUE THREAD

**Issue by vajayattila** [nav-gov-hu/Online-Invoice#487]
Hali. Számomra még egyelőre nem egyértelmű mi is ez a completenessIndicator. Azt látom, hogy a minta xml-ben ez true-ra van állítva.

Nekünk van egy számlázó programunk, amely saját maga nyomtat ki fizikailag számlát, és ezt kapja meg a vevő. Ebben az esetben a completenessIndicator értéket false-ra kell állítani az adatok átadásakor?

**Comment by EnokhSys** [comment]
> Hali. Számomra még egyelőre nem egyértelmű mi is ez a completenessIndicator. Azt látom, hogy a minta xml-ben ez true-ra van állítva.
> 
> Nekünk van egy számlázó programunk, amely saját maga nyomtat ki fizikailag számlát, és ezt kapja meg a vevő. Ebben az esetben a completenessIndicator értéket false-ra kell állítani az adatok átadásakor?

A "completenessIndicator" azt jelenti, hogy maga az XML-számlaadat, amit átadsz a NAV rendszerének, minősüljön-e elektronikus számlának. Amennyiben úgy döntesz, hogy igen, a számla XML-adatának BASE64 csomagjából képezned kell egy SHA3-512-es kódot, amit a "ManageInvoiceRequest"-ben átadsz a számla mellé az electronicInvoiceHash cryptoType="SHA3-512 szegmensben. Ezáltal van biztosítva a BASE64-ben képzett XML-számla eredetisége.

**Comment by vajayattila** [comment]
Az jár valamilyen szankcióval, ha én nem kívánom elektronikus számlaként kezelni az átadott adatokat?

**Comment by EnokhSys** [comment]
> Az jár valamilyen szankcióval, ha én nem kívánom elektronikus számlaként kezelni az átadott adatokat?

Dehogy jár. Ez számodra/számunkra egy pozitív lehetőség, hogy ne papíron, hanem pl. pdf-ben küldhessünk elektronikus számlát digitális aláírás nélkül. Hiszen azáltal, hogy mellékelsz egy biztonsági kódot a NAV feladásba, és ezt a kódot elküldöd a pdf számla mellé a vevőnek (vagy akár rá is nyomtatod a számlára), hitelessé teszed azt. (Ehhez még némi jogszabály-változtatás is szükséges, ami most őszre várható.)
Olvasd el a v3-as dokumentációjából a "2.6 Elektronikus számlázás támogatása" fejezetet a 149-ik oldalon.

**Comment by vajayattila** [comment]
Rendben. Köszönöm szépen az információt. Lezárom a jegyet.

**Comment by aperger** [comment]
Ezzel kapcsolatos kérdésemet feltettem itt:

https://github.com/nav-gov-hu/Online-Invoice/issues/566

De hátha tudja valaki a választ. Azért kommentelek lezárt issue-hoz. Köszi
