### ISSUE TITLE
invoiceDigestResult.availablePage v3.0-ában hibás?

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#488]
invoiceDigestResult.availablePage-ben 0-át kapunk, holott az xsd szerint >=1 kellene hogy legyen.
2.0-ban még nem volt ez a megszorítás a válaszon, ott a 0 is elfogadott volt az xsd szerint

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !
Köszi a jelzést.
Én úgy látom, hogy a v2-ben is 1-től kellene indulnia:
`	<xs:simpleType name="PageType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Lapozó paraméter típus</xs:documentation>
			<xs:documentation xml:lang="en">Page parameter type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:int">
			<xs:minInclusive value="1"/>
		</xs:restriction>`

A v3-ban igyekszünk ezt orvosolni.
Üdv

**Comment by EPluribusUnum** [comment]
Érdekes @DecimalMin("1") rá van generálva az 3.0-ban az objektumokra, de 2.0 alatt nincs, holott látszólag tényleg egyezik 2.0 és 3.0 xsd, csak namespace eltérés van. Lehet itt valamilyen cxf wadl2java anomális van.

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !
Valószínűleg az lesz a megoldás, hogy a PageType-ot kettébontjuk pl. RequestPageType és ResponsePageType-ra a common xsd-ben, mivel ugye ha a lekérdezésnek nincs eredménye, akkor 0 elérhető oldal van, viszont kérésnél beküldeni olyat, hogy a 0. oldalt kérem nem valid.
Ha odaérünk, hogy a konkrét megvalósítás legyen, jelzünk.
Köszi a jelzést mégegyszer.
Üdv

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !
A common XSD-ben kettébontottuk két típusra.
Köszi a jelzést, jogos volt.
Üdv
