### ISSUE TITLE
[Q&A] Technikai felhasználó queryInvoiceData, queryTransactionStatus csak lekérdezési joggal lehetséges?

### ISSUE THREAD

**Issue by HWKF** [nav-gov-hu/Online-Invoice#489]
Egy technikai felhasználó jogait be lehet állítani úgy, hogy csak a queryInvoiceData, queryInvoiceCheck, queryTransactionStatus (esetleg a queryTransactionList) operációkhoz legyen joga?
Igazából az a lényeg, hogy a queryInvoiceData és a queryTransactionStatus csak lekérdezési joggal, adatszolgáltatási lehetőség nélkül használható-e?
Azaz adószám változás esetén a korábbi adatok lekérdezhetőek maradjanak, de újakat ne lehessen rögzíteni. A tranzakció lekérdezhetősége is fontos lenne.

**Comment by NTCA-supporter** [comment]
Szia @HWKF !

Igen. Ha elveszed tőle a "Számlák kezelése" jogosukltságot, akkor nem tud beküldeni új számlát.
A lekérdezés menni fog, ha megmarad a Számlák lekérdezése vagy a Saját számlák lekérdezése jog.
Utóbbival csak azt a számlát tudja lekérdezni, amit saját maga küldött be, míg előbbinél az adózó összes számlája lekérdezhető.
Üdv

**Comment by HWKF** [comment]
Nekem igazából abban kell a megerősítés, hogy ha elvesszük a "Számlák kezelése" jogosultságot, akkor is elérhető a queryTransactionStatus operáció?
Valahol le van írva, hogy a technikai felhasználó melyik jogosultságai melyik operáció igénybevételére adnak lehetőséget?

**Comment by NTCA-supporter** [comment]
A queryTransactionStatus nem lesz elérhető, csak a queryInvoiceData.
Számlák kezelése: queryTransactionStatus, tokenExchange, manageInvoice, queryTaxpayer, manageAnnulment, queryTransactionList.
Az összes többihez kell a lekérdező jogosultság (digest/check/data/chainDigest).
Üdv

**Comment by HWKF** [comment]
Az API-t használva, hogyan tudjuk az adott operáció jogosultságát ellenőrizni?
Azaz ha a "Számlák kezelése" jogosultság nincs meg és meghívom a queryTransactionStatus operációt, akkor melyik hibaüzenet adja meg egyértelműen, hogy nincs joga lekérdezni?
Jól tippelem, hogy a válasz a (9) FORBIDDEN hiba üzenet (_a kérésben szereplő technikai felhasználó nem jogosult az endpoint szolgáltatását hívni_)? Azaz jogosultság hiba esetén ezt a hibát kapom és nem a (7) INVALID_CUSTOMER vagy a (8) INVALID_USER_RELATION hibaüzeneteket?
- INVALID_CUSTOMER: _A user tagban megadott adószám vagy nem létezik, vagy **a státusza nem engedi a számlaműveletek végzését**._
- INVALID_USER_RELATION: _... vagy **a felhasználó státusza már nem engedélyezi a művelet elvégzésé**t._

**Comment by NTCA-supporter** [comment]
Szia @HWKF !
Jól gondolod igen, a FORBIDDEN-t kapod ilyenkor.
Üdv

**Comment by HWKF** [comment]
Köszönöm az információt, zárom az issuet.
