### ISSUE TITLE
[DEV support] Üres response 

### ISSUE THREAD

**Issue by tacshu** [nav-gov-hu/Online-Invoice#491]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[x] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
20201020141540998
20201027105342530

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Egy vállalatirányítási rendszeren fejlesztem a 3.0-ás verzió módosítását és a tokenkérésre nem kapok választ. Teljesen üres lesz a válasz. Nem tudom mi a gond. Gyanakodtam, mivel a passwordHash titkosítása megváltozott, mert még a 2.0-ban csak SHA-512 volt írva, de itt már SHA2-512, ezért ez okozhatja a gondot. Úgy tudom, hogy a kettő azonos, ezért mégsem lehet ez baj. Ha bármi sémát érintő hibát teszek az xml-be, akkor szépen kapok választ a hibával. Ha viszont látszólag minden rendben, akkor nincs se válasz se token.
Előre is köszönöm a segítséget.

*Egyéb tartalom / Additional content*

**Comment by EnokhSys** [comment]
Szia @tacshu ,
nálam is hasonló hiba volt éjjel és hajnalban, ill. most megint 14:20 óta. TokenRequestre nem jön válasz, ha véletlenül mégis érkezik, a ManageRequest nem megy be.

**Comment by EnokhSys** [comment]
Most egy számlát sikerült beküldeni, de a következő számlánál megint ugyanez a hiba történt.

**Comment by renced42** [comment]
> Most egy számlát sikerült beküldeni, de a következő számlánál megint ugyanez a hiba történt.

Rákérdeztem a kollégáknál, hogy mit látnak, várom a válaszukat.

**Comment by EnokhSys** [comment]
> > Most egy számlát sikerült beküldeni, de a következő számlánál megint ugyanez a hiba történt.
> 
> Rákérdeztem a kollégáknál, hogy mit látnak, várom a válaszukat.

Köszi, ha szükséges, küldök e-mailben ip.címet.

**Comment by renced42** [comment]
> > > Most egy számlát sikerült beküldeni, de a következő számlánál megint ugyanez a hiba történt.
> > 
> > 
> > Rákérdeztem a kollégáknál, hogy mit látnak, várom a válaszukat.
> 
> Köszi, ha szükséges, küldök e-mailben ip.címet.

Inkább request adat kellene először.

**Comment by EnokhSys** [comment]
Mindjárt csinálok, pill....

**Comment by renced42** [comment]
> Mindjárt csinálok, pill....

Amire nem kaptál választ az kellene. A kollégák nem látnak semmi problémát egyébként.

**Comment by EnokhSys** [comment]
tokenRequest: 2020V000109527160310, válasz megérkezett némi késéssel
manageRequest: 2020V000109527160321, erre is megjött a válasz elég nagy késéssel
statusRequest: 2020V000109527160332, **nem jött rá válasz, pedig 3 perce lett beküldve**

**Comment by tacshu** [comment]
Én 2020.10.09 óta próbálkozom és idáig nem sikerült még egy token kérés sem nekem.
Túl rövid lenne a timeout?

**Comment by EnokhSys** [comment]
> Én 2020.10.09 óta próbálkozom és idáig nem sikerült még egy token kérés sem nekem.
> Túl rövid lenne a timeout?

@tacshu Akkor biztos, hogy valami hiba van nálad, mert általában 1-2 mp alatt megjön a token. Ha nem kapsz választ, akkor szerintem HTTPPost problémád van, probálj ki egy másik programmal küldeni. Ezelőtt 2 éve nekem is volt ilyen problémám.

**Comment by tacshu** [comment]
Akkor jutott oda a fejlesztés, hogy el tudtam kezdeni tesztelni. Korábban nem volt beküldésem 3.0-val, viszont 2.0-val gond nélkül megy jelenleg is.

**Comment by EnokhSys** [comment]
> Akkor jutott oda a fejlesztés, hogy el tudtam kezdeni tesztelni. Korábban nem volt beküldésem 3.0-val, viszont 2.0-val gond nélkül megy jelenleg is.

@tacshu Akkor bocs, nem valószínű, hogy HTTPPost a gond. Nézd át, hogy jó-e a tesztszerver URL, továbbá, hogy a tokenRequest-ben beállítottad-e a common: namespaceket, hogy a jelszót kibővítetted-e a cryptoType="SHA2-512" és az aláírást a cryptoType="SHA3-512" jelzőkkel. (Maga a jelszó és az aláírás kódolása nem változott a v2-eshez képest, csak a szegmensek jelölése.)

**Comment by renced42** [comment]
> manageRequest: 2020V000109527160321, erre is megjött a válasz némi késéssel

@EnokhSys  Egy TR ID-t tudnál mondani?

**Comment by EnokhSys** [comment]
> > manageRequest: 2020V000109527160321, erre is megjött a válasz némi késéssel
> 
> @EnokhSys Egy TR ID-t tudnál mondani?

transactionId: 35DTUS8H509L82Q5

**Comment by renced42** [comment]
> > manageRequest: 2020V000109527160321, erre is megjött a válasz némi késéssel
> 
> @EnokhSys Egy TR ID-t tudnál mondani?
@EnokhSys Ezt a requestID-t a teszt rendszerbe külted?

**Comment by EnokhSys** [comment]
> > > manageRequest: 2020V000109527160321, erre is megjött a válasz némi késéssel
> 
> @EnokhSys Ezt a requestID-t a teszt rendszerbe külted?

Nem, már fentebb is módosítottam a beírásomat, hogy itt v2-es éles számlákról van szó, mint ahogyan tegnap éjszaka is.

**Comment by renced42** [comment]
No akkor egy kicsit ácsi :) 
@EnokhSys  Ez az issue a teszt környezetre vonatkozik és a V3-ra, nem az élesre és a V2-re. Így kicsit nehezebb.
@tacshu Kérem erősítsd meg, hogy akkor hova nem sikerül beküldeni a kérésedet és küldj egy TRID-t is.

**Comment by EnokhSys** [comment]
> No akkor egy kicsit ácsi :)
> @EnokhSys Ez az issue a teszt környezetre vonatkozik és a V3-ra, nem az élesre és a V2-re. Így kicsit nehezebb.

Amikor fentebb, ezelőtt 2 órája megadtam a TRID-t, rá 5 percre jutott eszembe, hogy gyorsan írjam be, hogy ez a v2-es éles rendszerre vonatkozik, nehogy belefuss egy üres körbe.... ezexerint nem sikerült, gyorsabb voltál. :-) Még1x bocs!

**Comment by tacshu** [comment]
Amit az issue-ban írtam az elején azok nekem a teszt v3-ba lettek küldve. Benne vannak az új namespace-ek, benne vannak a cryptoType jelzők is.

**Comment by renced42** [comment]
> Amit az issue-ban írtam az elején azok nekem a teszt v3-ba lettek küldve. Benne vannak az új namespace-ek, benne vannak a cryptoType jelzők is.

Kedves @tacshu probálj meg egy beküldést kérlek.

**Comment by tacshu** [comment]
Most sem kaptam választ. kérés az.: 20201027203328798

**Comment by renced42** [comment]
> Most sem kaptam választ. kérés az.: 20201027203328798
Légyszives az url-t amit hívsz add meg kérlek

**Comment by tacshu** [comment]
https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3/tokenExchange

**Comment by renced42** [comment]
> https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3/tokenExchange

Ha böngészőbe beírod ezt az URL-t mit kapsz vissza?

**Comment by tacshu** [comment]
Ok, ezt nem probáltam.

**Comment by tacshu** [comment]
<GeneralExceptionResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">
<funcCode>ERROR</funcCode>
<errorCode>OPERATION_FAILED</errorCode>
<message>Nincs ilyen művelet!</message>
</GeneralExceptionResponse>

**Comment by renced42** [comment]
Akkor az URL-jó és a gépről elérhető

**Comment by tacshu** [comment]
Bocsánat. Azt hittem az URL-lel gond van. Most megnéztem a szerverről is és ott más jön:  
"The website cannot display the page".

**Comment by renced42** [comment]
Hát akkor onnan nem elérhető az url, meg van a hiba.

**Comment by tacshu** [comment]
Ok, tegyük fel ez a baj. Ha viszont hibát teszek az XML-be, pl.: olyan taget, ami nincs az xsd-ben, akkor miért kapok mégis választ annak ellenére, hogy nem elérhető az URL arról a gépről?

**Comment by tacshu** [comment]
Valamint a https://api-test.onlineszamla.nav.gov.hu/invoiceService/v2/tokenExchange URL sem érhető el onnan így böngészőben, de az mégis gond nélkül működik. Mármint a tokenkérés majd a számla beküldés.

**Comment by renced42** [comment]
Kedves @tacshu használtad, már az Online Invoice Test Tool-t?

**Comment by tacshu** [comment]
Még nem volt rá szükségem idáig. Akkor próbáljam meg azzal beküldeni?

**Comment by renced42** [comment]
Jó, lenne, de most jut eszembe, hogy a kipublikált nem beszél, még 3.0-ul, majd holnap lesz kirakva a legfrisebb verzió.
A hibás kérésnek mi lesz a válasza?

**Comment by tacshu** [comment]
Ezt most nem értem. Akkor még ez helyes működés a jelen pillanatban?
Ha a softwareId helyett csak software-t raktam bele, akkor ezt kaptam:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns2:GeneralErrorResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data"><result><funcCode>ERROR</funcCode><errorCode>INVALID_REQUEST</errorCode><message>Helytelen kérés!</message></result><ns2:technicalValidationMessages><validationResultCode>ERROR</validationResultCode><validationErrorCode>SCHEMA_VIOLATION</validationErrorCode><message>Request body contains on line: [16] and column: [12] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/api":software}'. One of '{"http://schemas.nav.gov.hu/OSA/3.0/api":softwareId}' is expected.]</message></ns2:technicalValidationMessages></ns2:GeneralErrorResponse>

**Comment by renced42** [comment]
Ez a válasz helyes.
Ha ezt kapod akkor a kérés eljut hozzánk, mert az XML parsolódik és validáljuk.

**Comment by tacshu** [comment]
Így gondoltam én is. Ellenben, ha nincs benne hiba, akkor viszont nincs semmi válasz.

**Comment by renced42** [comment]
Most küldj kérlek egy tokenrequestet és add meg a RID-et

**Comment by tacshu** [comment]
Az immént akkor ment egy ezzel: 20201027212343646

**Comment by renced42** [comment]
No Itt is van, és jónak is tűnik. Holnap reggel megnézzük a visszafele irányt és jelentkezünk. Addig kis türelmet. Köszönöm!

**Comment by tacshu** [comment]
Én is köszönöm a kitartó supportot.

**Comment by EnokhSys** [comment]
> Ezt most nem értem. Akkor még ez helyes működés a jelen pillanatban?
> Ha a softwareId helyett csak software-t raktam bele, akkor ezt kaptam:
> 
> ERRORINVALID_REQUESTHelytelen kérés!ERRORSCHEMA_VIOLATIONRequest body contains on line: [16] and column: [12] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/api":software}'. One of '{"http://schemas.nav.gov.hu/OSA/3.0/api":softwareId}' is expected.]

Kedves @tacshu, nagyon szépen köszönöm az ötletet, ezzel sokat segítettél, mert én is elvégeztem ezt a tesztet, hajszálra ugyanezzel az eredménnyel. Ezáltal bizonyítva van, hogy a NAV oldalához eljut a kérés, de nem válaszol, és az én esetemben, a korábbi tesztek alapján egyértelműen ip-cím alapján történik a blokkolás.

**Comment by renced42** [comment]
Kedves @tacshu  téged is megkérdezlek, hogy használsz-e curl-t ha igen milyen verziót?

**Comment by tacshu** [comment]
Ez az alkalmazás java-ban van. Itt nincs curl használva.

**Comment by renced42** [comment]
> Ez az alkalmazás java-ban van. Itt nincs curl használva.

Java verzió?

**Comment by tacshu** [comment]
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)

**Comment by renced42** [comment]
Megnéztem a tegnap küldött kérést. A kérés beérkezett és válaszoltunk is rá!!!

Megtennéd, hogy a csatolt tartalmat beteszed egy java-s IDE-be és megfuttatod és visszaküldöd az eredményét?

[transporter.txt](https://github.com/nav-gov-hu/Online-Invoice/files/5450409/transporter.txt)
A lentieket be kell állítani a helyi sajátosságoknak megfelelően

 private static String loggerpath = "c://temp//log.txt";
 private static String xmlpath = "C://temp//token.xml";

**Comment by tacshu** [comment]
Megcsináltam a  korábbi xml-lel, akkor szépen jött is vissza, hogy
    <funcCode>ERROR</funcCode>
    <errorCode>REQUEST_ID_NOT_UNIQUE</errorCode>
    <message>A megadott kérés azonosítója már létezik!</message>
De ha teljesen új kérés azonosítóval, új xml-t küldtem, akkor továbbra sincs válasz és a log.txt-be sem ír semmit ezzel kapcsolatban.

**Comment by NTCA-supporter** [comment]
@tacshu kérlek küld el a frissen beküldött valamelyik azonosítóját (amelyikre nem kaptál választ), nézem én is.
Köszi

**Comment by tacshu** [comment]
20201028103627787
Gondolom a log.txt-t nem tölthetem ide fel, igaz?
Köszönöm a tárgy javítását.

**Comment by renced42** [comment]
> Gondolom a log.txt-t nem tölthetem ide fel, igaz?

Feltöltheted. A login nevet, meg az adószámot töröld ki, ezek esetleg szenzitívek.

**Comment by tacshu** [comment]
[log.txt](https://github.com/nav-gov-hu/Online-Invoice/files/5451026/log.txt)
Remélem, kiszedtem minden helyről.

**Comment by NTCA-supporter** [comment]
Hmm. Logban http 200 response van az alábbi tartalommal:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:TokenExchangeResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">
	<header>
		<requestId>20201028103627787</requestId>
		<timestamp>2020-10-28T09:36:27.787Z</timestamp>
		<requestVersion>3.0</requestVersion>
		<headerVersion>1.0</headerVersion>
	</header>
	<result>
		<funcCode>OK</funcCode>
	</result>
	<ns2:software>
		<ns2:softwareId>HU695892IFSAPP9XXX</ns2:softwareId>
		<ns2:softwareName>IFS Applications</ns2:softwareName>
		<ns2:softwareOperation>LOCAL_SOFTWARE</ns2:softwareOperation>
		<ns2:softwareMainVersion>9</ns2:softwareMainVersion>
		<ns2:softwareDevName>InfoConsulting Hungary Kft.</ns2:softwareDevName>
		<ns2:softwareDevContact>infohu@infoconsulting.eu</ns2:softwareDevContact>
		<ns2:softwareDevCountryCode>HU</ns2:softwareDevCountryCode>
		<ns2:softwareDevTaxNumber>12469589-2-41</ns2:softwareDevTaxNumber>
	</ns2:software>
	<ns2:encodedExchangeToken>5c4kMdl0llEIhAF1kWANrMm8McW/ZDP1cXyBjOeMdV+yHDx03ny7i9TQ64ssZJiJcjuyKkE1ra1hNcckUceMpw==</ns2:encodedExchangeToken>
	<ns2:tokenValidityFrom>2020-10-28T10:37:22.535+01:00</ns2:tokenValidityFrom>
	<ns2:tokenValidityTo>2020-10-28T10:42:22.535+01:00</ns2:tokenValidityTo></ns2:TokenExchangeResponse>`

Nézzük tovább.
Üdv

**Comment by renced42** [comment]
"Hogy lehet az, hogy ugyanabból a szerver és szoftverkörnyezetből továbbá ugyanarról az ip.címről és csupán néhány másodperces időkülönbséggel indított "TokenRequest" kérés abban az esetben azonnal kapott választ a NAV v3-as tesztszervertől, ha a "softwareId" tag helyett hibásan "software" tagot használtam, míg abban az esetben, ha helyesen használtam a "softwareId" tagot, akkor nem jött semmi válasz?"

Kedves @EnokhSys ezt kell pontosan meghatározni, ebből is az látszik, hogy nem korlátozásról vagy IP szűrésről van szó, hanem valami valahol nem úgy működik ahogyan kellene. 
Küldtem levelet :)

**Comment by EnokhSys** [comment]
> "Hogy lehet az, hogy ugyanabból a szerver és szoftverkörnyezetből továbbá ugyanarról az ip.címről és csupán néhány másodperces időkülönbséggel indított "TokenRequest" kérés abban az esetben azonnal kapott választ a NAV v3-as tesztszervertől, ha a "softwareId" tag helyett hibásan "software" tagot használtam, míg abban az esetben, ha helyesen használtam a "softwareId" tagot, akkor nem jött semmi válasz?"
> 
> Kedves @EnokhSys ezt kell pontosan meghatározni, ebből is az látszik, hogy nem korlátozásról vagy IP szűrésről van szó, hanem valami valahol nem úgy működik ahogyan kellene.
> Küldtem levelet :)

Köszi, válaszoltam rá, benne a partner ip.címével és a kért időkkel. :-)

**Comment by szako** [comment]
A #450-es tikett irányított ide. Az elmúlt hónapokban kétszer futottam bele olyan esetbe, hogy ügyfélnél kb. 2 napon keresztül hirtelen jött kommunikációs problémák jelentkeztek a NAV szervere fele, operációtól függetlenül. Az egyik ilyen esemény 2020.07.07 -> 2020.07.08 között történt, a másik eset 2020.09.10 -> 2020.09.11 között, az esetek izoláltak, teljesen más ügyfélnél jöttek elő. Azért vannak meg a pontos dátumok, mert még engem (a program fejlesztőjét) is mozgósítottak, miközben nyilvánvalóan hálózati problémáról volt szó. Ha jól tudom mindkét esetben a NAV-val történt konzultáció (legalábbis hozzám ez az információ jutott el) és az volt a mondás, hogy az ő oldalukon minden rendben van, ügyfél hiba.

A közös a két esetben, hogy:
- csak az éles volt érintett az esetben, a teszt rendszer tökéletesen működött
- a hálózatos infra csoportok a tűzfalat figyelve azt látták, hogy a NAV fele kimennek a csomagok, de visszafele már nem érkezik válasz
- 2 nap után minden jel nélkül elmúltak a problémák, senki nem nyúlt semmihez (egyik ügyfélnél a két nap utáni éjfél után pár perccel megszűnt a probléma)
- Kb. 30%-os siker ráta volt a kéréseknél
- Adott időszakban más nem jelentett ilyen jellegű problémát, tehát egyedi érintettségű volt

**Comment by EnokhSys** [comment]
Kedves @szako, köszi, hogy ezt leírtad, mert nagyon hasonló az én jelenlegi esetemhez; - a különbség talán abban van, hogy nálam egyaránt jelentkezett a v2-es éles rendszerben, és a v3-as tesztrendszerben.

**Comment by renced42** [comment]
Kedves @tacshu 
Megnéztük a logokat. A megadott IP alapján ezeket a forgalmakat láttuk.
Ami a megadott IP címről jött arra válaszoltunk is.

Oct | 27 | 10:47:42 | POST /invoiceService/v3/tokenExchange   HTTP/1.1 | 400
Oct | 27 | 10:53:43 | POST /invoiceService/v3/tokenExchange HTTP/1.1 | 200
Oct | 27 | 15:59:37 | POST /invoiceService/v3/tokenExchange HTTP/1.1 | 200
Oct | 27 | 16:00:18 | POST /invoiceService/v3/tokenExchange HTTP/1.1 | 200
Oct | 27 | 16:05:52 | POST /invoiceService/v3/tokenExchange HTTP/1.1 | 200
Oct | 27 | 20:33:29 | POST /invoiceService/v3/tokenExchange HTTP/1.1 | 200
Oct | 27 | 20:44:54 | GET /invoiceService/v3/tokenExchange HTTP/1.1 | 500
Oct | 27 | 20:44:54 | GET /favicon.ico HTTP/1.1 | 503
Oct | 27 | 20:54:50 | GET /invoiceService/v3/tokenExchange HTTP/1.1 | 500
Oct | 27 | 20:55:35 | GET /invoiceService/v3/tokenExchange HTTP/1.1 | 500
Oct | 27 | 20:55:38 | GET /invoiceService/v3/tokenExchange HTTP/1.1 | 500
Oct | 27 | 21:01:43 | GET /invoiceService/v2/tokenExchange HTTP/1.1 | 500
Oct | 27 | 21:01:48 | GET /invoiceService/v2/tokenExchange HTTP/1.1 | 500
Oct | 27 | 21:23:44 | POST /invoiceService/v3/tokenExchange HTTP/1.1 | 200
Oct | 28 | 10:27:00 | POST /invoiceService/v3/tokenExchange HTTP/1.1 | 500
Oct | 28 | 10:27:32 | POST /invoiceService/v3/tokenExchange HTTP/1.1 | 500
Oct | 28 | 10:30:26 | POST /invoiceService/v3/tokenExchange HTTP/1.1 | 500
Oct | 28 | 10:37:22 | POST /invoiceService/v3/tokenExchange HTTP/1.1 | 200

Kellene még pár hívás, a hívások RID-je és pontos dátuma, hogy holnap a tűzfalakon is tudjunk nézelődni. A cégnek egy fix címe van?

**Comment by tacshu** [comment]
Most csináltam egy újat: 20201028181408329
Igen, ez az egy fix IP címünk van.

**Comment by tacshu** [comment]
A tegnapi dátuma: 2020.10.28 17:15:23(A Transporter ezt írta ki)
Most küldtem még egyet: 20201029080234740
ennek dátuma: 2020.10.29 07:05:05

**Comment by renced42** [comment]
> A tegnapi dátuma: 2020.10.28 17:15:23(A Transporter ezt írta ki)
> Most küldtem még egyet: 20201029080234740
> ennek dátuma: 2020.10.29 07:05:05

Köszi igen látom, a hálózatos kollegákkal megnézetem. A kerések bejönnek, vannak is válaszaink, de az nem jut vissza hozzád.

**Comment by tacshu** [comment]
Az derült ki, hogy az én készülékemben van a hiba. Pontosabban az én szoftveremben. Ezek a namespacek megzavarják és nem talál rá a tagekre, ezért fut hibaágra.
Köszönöm az alapos tesztelést és supportot renced42.

**Comment by renced42** [comment]
> Az derült ki, hogy az én készülékemben van a hiba. Pontosabban az én szoftveremben. Ezek a namespacek megzavarják és nem talál rá a tagekre, ezért fut hibaágra.
> Köszönöm az alapos tesztelést és supportot renced42.

@tacshu Your Welcome!
Nagy futás volt, de legalább megtudtuk, hogy nem szűrjük az IP címedet. Most már tudok nyugodtan aludni :)

Tanulságok:
- Ha nem jó valami, telepítsd fel az Online Invoice Test Tool programot és próbáld ki azzal a kapcsolatot, illetve kipróbálhatod ezt a java kódot [transporter.txt](https://github.com/nav-gov-hu/Online-Invoice/files/5461324/transporter.txt). Ha ezek működnek és mennek és a tied nem, akkor biztosan nálad van a hiba.
- Mivel a rendszer http státuszkódokkal operál és nincs minden státuszkód lekezelve a programban, olyan mintha nem kapnál választ pedig DE! (Persze azért előfordulhat hogy nem, de akkor ott a timeout és az más mintha nem kapsz választ)
- XML namespace kezelésére figyelni kell

@EnokhSys Holnap te jössz :)

**Comment by EnokhSys** [comment]
> Tanulságok:
> 
> * Ha nem jó valami, telepítsd fel az Online Invoice Test Tool programot és próbáld ki azzal a kapcsolatot, illetve kipróbálhatod ezt a java kódot [transporter.txt](https://github.com/nav-gov-hu/Online-Invoice/files/5461324/transporter.txt). Ha ezek működnek és mennek és a tied nem, akkor biztosan nálad van a hiba.
> * Mivel a rendszer http státuszkódokkal operál és nincs minden státuszkód lekezelve a programban, olyan mintha nem kapnál választ pedig DE! (Persze azért előfordulhat hogy nem, de akkor ott a timeout és az más mintha nem kapsz választ)
> * XML namespace kezelésére figyelni kell
> 
> @EnokhSys Holnap te jössz :)

Kedves @renced42, türelemmel, de nagy érdeklődéssel várom az eredményt. :-) 

1000%-ban biztos vagyok, hogy az én oldalamon nincs hiba, legalábbis azon a területen, amire van rálátásom. Minden token-kérés kijutott tőlünk a tűzfalon kívülre... és itt még nem értek véget a mi vizsgálatainknak sem. ;-)

**Comment by szecsenyizoltan** [comment]
@szako Én elképzelhetőnek tartom, hogy különböző időpontban frissült egy sw komponens ami a problémát okozta. (lásd curl)

**Comment by renced42** [comment]
Kedves @tacshu Kérlek zárd az issuet.
Kedves @EnokhSys Ha ismét jelentkezik a hiba és nem üzemszünet van akkor jelezd nyugodtan, meg nézzük.

**Comment by EnokhSys** [comment]
![image](https://user-images.githubusercontent.com/72287954/97711388-5872ed00-1abd-11eb-86b4-a05a7b7e862e.png)

:-)
