### ISSUE TITLE
Egyszerűsített számlánál hibás összegzés figyelmeztetés

### ISSUE THREAD

**Issue by gyurmanz** [nav-gov-hu/Online-Invoice#492]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**

[X] /manageInvoice
[X] /queryTransactionStatus

**A kérés verziója / version of the request**
[] 1.1
[X] 2.0
[] 3.0

**A requestId értéke / requestId value**

TransactionId: 35D4J6YC98QXTXE1

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
INCORRECT_SUMMARY_CALCULATION_VAT_CONTENT_GROSS_AMOUNT_HUF_SUMMARY_SIMPLIFIED
Warning-ot kapok minden esetben, pedig a tételek össszege megegyezik a végösszeggel.

*Egyéb tartalom / Additional content*

<?xml version="1.0" encoding="utf-8"?>
<InvoiceData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.nav.gov.hu/OSA/2.0/data">
  <invoiceNumber>XOCEA018603</invoiceNumber>
  <invoiceIssueDate>2020-10-19</invoiceIssueDate>
  <invoiceMain>
    <invoice>
      <invoiceHead>
        <supplierInfo>
          <supplierTaxNumber>
            <taxpayerId>********</taxpayerId>
          </supplierTaxNumber>
          <supplierName>********</supplierName>
          <supplierAddress>
            <simpleAddress>
              <countryCode>********</countryCode>
              <postalCode>********</postalCode>
              <city>********</city>
              <additionalAddressDetail>********</additionalAddressDetail>
            </simpleAddress>
          </supplierAddress>
        </supplierInfo>
        <customerInfo>
          <customerTaxNumber>
            <taxpayerId>********</taxpayerId>
          </customerTaxNumber>
          <customerName>********</customerName>
          <customerAddress>
            <simpleAddress>
              <countryCode>********</countryCode>
              <postalCode>********</postalCode>
              <city>********</city>
              <additionalAddressDetail>********</additionalAddressDetail>
            </simpleAddress>
          </customerAddress>
        </customerInfo>
        <invoiceDetail>
          <invoiceCategory>SIMPLIFIED</invoiceCategory>
          <invoiceDeliveryDate>2020-10-19</invoiceDeliveryDate>
          <currencyCode>HUF</currencyCode>
          <exchangeRate>1</exchangeRate>
          <paymentMethod>CASH</paymentMethod>
          <paymentDate>2020-10-19</paymentDate>
          <invoiceAppearance>PAPER</invoiceAppearance>
        </invoiceDetail>
      </invoiceHead>
      <invoiceLines>
        <line>
          <lineNumber>1</lineNumber>
          <lineExpressionIndicator>false</lineExpressionIndicator>
          <lineDescription>ENHS</lineDescription>
          <quantity>1</quantity>
          <unitPrice>2895.60</unitPrice>
          <unitPriceHUF>2895.60</unitPriceHUF>
          <lineAmountsSimplified>
            <lineGrossAmountSimplified>2896</lineGrossAmountSimplified>
            <lineGrossAmountSimplifiedHUF>2896</lineGrossAmountSimplifiedHUF>
          </lineAmountsSimplified>
        </line>
        <line>
          <lineNumber>2</lineNumber>
          <lineExpressionIndicator>false</lineExpressionIndicator>
          <lineDescription>ENHS</lineDescription>
          <quantity>1</quantity>
          <unitPrice>863.60</unitPrice>
          <unitPriceHUF>863.60</unitPriceHUF>
          <lineAmountsSimplified>
            <lineGrossAmountSimplified>864</lineGrossAmountSimplified>
            <lineGrossAmountSimplifiedHUF>864</lineGrossAmountSimplifiedHUF>
          </lineAmountsSimplified>
        </line>
        <line>
          <lineNumber>3</lineNumber>
          <lineExpressionIndicator>false</lineExpressionIndicator>
          <lineDescription>ENHS</lineDescription>
          <quantity>1</quantity>
          <unitPrice>508.00</unitPrice>
          <unitPriceHUF>508.00</unitPriceHUF>
          <lineAmountsSimplified>
            <lineGrossAmountSimplified>508</lineGrossAmountSimplified>
            <lineGrossAmountSimplifiedHUF>508</lineGrossAmountSimplifiedHUF>
          </lineAmountsSimplified>
        </line>
        <line>
          <lineNumber>4</lineNumber>
          <lineExpressionIndicator>false</lineExpressionIndicator>
          <lineDescription>ET</lineDescription>
          <quantity>1</quantity>
          <unitPrice>1524.00</unitPrice>
          <unitPriceHUF>1524.00</unitPriceHUF>
          <lineAmountsSimplified>
            <lineGrossAmountSimplified>1524</lineGrossAmountSimplified>
            <lineGrossAmountSimplifiedHUF>1524</lineGrossAmountSimplifiedHUF>
          </lineAmountsSimplified>
        </line>
        <line>
          <lineNumber>5</lineNumber>
          <lineExpressionIndicator>false</lineExpressionIndicator>
          <lineDescription>Kiszállási díj KP-val / átvételi elismervénnyel</lineDescription>
          <quantity>1</quantity>
          <unitPrice>5080</unitPrice>
          <unitPriceHUF>5080</unitPriceHUF>
          <lineAmountsSimplified>
            <lineGrossAmountSimplified>5080</lineGrossAmountSimplified>
            <lineGrossAmountSimplifiedHUF>5080</lineGrossAmountSimplifiedHUF>
          </lineAmountsSimplified>
        </line>
      </invoiceLines>
      <invoiceSummary>
        <summarySimplified>
          <vatContent>0.2126</vatContent>
          <vatContentGrossAmount>10872</vatContentGrossAmount>
          <vatContentGrossAmountHUF>10872</vatContentGrossAmountHUF>
        </summarySimplified>
        <summaryGrossData>
          <invoiceGrossAmount>10872</invoiceGrossAmount>
          <invoiceGrossAmountHUF>10872</invoiceGrossAmountHUF>
        </summaryGrossData>
      </invoiceSummary>
    </invoice>
  </invoiceMain>
</InvoiceData>

**Comment by NTCA-supporter** [comment]
Szia @gyurmanz !
Szerintem a gond az, hogy tétel szinten nincs megadva vatContent, összesítő szinten viszont igen.
Komolyabb utánajárás nélkül azt gondolom, hogy az ellenőrzés úgy működik, hogy látja, hogy van egy 0.2126-os összesítőd, ahhoz megkeresi és összegzi a 0.2126-os tételeket (ami mivel nem adtad meg, így 0), és a 0-t összehasonlítja a -10719-el.

Üdv

**Comment by gyurmanz** [comment]
Köszönöm, ez volt a baj!
