### ISSUE TITLE
[Q&A] 3.0 MISSING_HEAD_DATA_CUSTOMER üzenet tévesen

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#493]
A 3.0-ban, ha gazdasági tevékenységet nem végző társasháznak állítok ki számlát (nincs adószáma, de nem magánszemély), akkor jelenleg tévesen a MISSING_HEAD_DATA_CUSTOMER warn jön a beküldött számlára.

**Comment by nbeeps2** [comment]
Kiegészítem, az üzenet csak a 100 ezer forintot elérő és azt megadó számlák esetében jön. A háttérben benne maradhatott a régi ÁFA érték figyelés valahol...

**Comment by NTCA-supporter** [comment]
Szia @nbeeps2 !
A WARN-ok szakmai felülvizsgálata folyamatban van.
Az interfész doksiban is ez szerepel. Ha megtörtént az ilyen fals figyelmeztetések kivezetése, illetve aktualizálása, a doksi is tartalmazni fogja. Ezt most zárom, ha van még kérdés nyisd újra.
Üdv
