### ISSUE TITLE
[Q&A] 3.0 Kérdés a marginSchemeVat, marginSchemeNoVat ill. a marginSchemeIndicator mezők helyes használatáról.

### ISSUE THREAD

**Issue by vajayattila** [nav-gov-hu/Online-Invoice#494]
Helló!

Segítséget szeretnék kérni a Különbözeti Adózással kapcsolatban.

Az interfaceben megtalálható a marginSchemeIndicator:
```
<xs:element name="marginSchemeIndicator" type="MarginSchemeType" minOccurs="0">
  <xs:annotation>
    <xs:documentation xml:lang="hu">Különbözet szerinti szabályozás jelölése - ÁFA tv. 169. § p) q)</xs:documentation>
    <xs:documentation xml:lang="en">Marking the margin-scheme taxation as per section 169 (p)(q)</xs:documentation>
  </xs:annotation>
</xs:element>
```
Ennek értékei a következők lehetnek:
```
<xs:simpleType name="MarginSchemeType">
	<xs:annotation>
		<xs:documentation xml:lang="hu">Különbözet szerinti szabályozás típus</xs:documentation>
		<xs:documentation xml:lang="en">Field type for inputting margin-scheme taxation</xs:documentation>
	</xs:annotation>
	<xs:restriction base="common:AtomicStringType15">
		<xs:enumeration value="TRAVEL_AGENCY">
			<xs:annotation>
				<xs:documentation xml:lang="hu">Utazási irodák</xs:documentation>
				<xs:documentation xml:lang="en">Travel agencies</xs:documentation>
			</xs:annotation>
		</xs:enumeration>
		<xs:enumeration value="SECOND_HAND">
			<xs:annotation>
				<xs:documentation xml:lang="hu">Használt cikkek</xs:documentation>
				<xs:documentation xml:lang="en">Second-hand goods</xs:documentation>
			</xs:annotation>
		</xs:enumeration>
		<xs:enumeration value="ARTWORK">
			<xs:annotation>
				<xs:documentation xml:lang="hu">Műalkotások</xs:documentation>
				<xs:documentation xml:lang="en">Works of art</xs:documentation>
			</xs:annotation>
		</xs:enumeration>
		<xs:enumeration value="ANTIQUES">
			<xs:annotation>
				<xs:documentation xml:lang="hu">Gyűjteménydarabok és régiségek</xs:documentation>
				<xs:documentation xml:lang="en">Collector’s items and antiques</xs:documentation>
			</xs:annotation>
		</xs:enumeration>
	</xs:restriction>
</xs:simpleType>
```

Egy kivételével sikerült fogóval kihúzni az NAV ügyfélszolgálatból a megfelelő áfakódokat:
```
Utazási irodák                               -> TRAVEL_AGENCY -> ??? (ezt nem sikerült megtudni)
Használt cikkek                              -> SECOND_HAND   -> KAH
Műalkotások                                  -> ARTWORK       -> KAM 
Gyűjteménydarabok és régiségek               -> ANTIQUES      -> KAR
```

Az első kérdés: A TRAVEL_AGENCY értékhez milyen ÁFA kód tartozik?

Második kérdés: Az egyes áfakódok függvényében milyen értékre kell állítani a marginSchemeVat és marginSchemeNoVat értékeket?

Ezek boolean értékek:
```
<xs:element name="marginSchemeVat" type="xs:boolean">
	<xs:annotation>
		<xs:documentation xml:lang="hu">Áthárított adót tartalmazó különbözet szerinti adózás</xs:documentation>
		<xs:documentation xml:lang="en">Margin scheme including input tax</xs:documentation>
	</xs:annotation>
</xs:element>
<xs:element name="marginSchemeNoVat" type="xs:boolean">
	<xs:annotation>
		<xs:documentation xml:lang="hu">Áthárított adót nem tartalmazó különbözet szerinti adózás</xs:documentation>
		<xs:documentation xml:lang="en">Margin scheme not including input tax</xs:documentation>
	</xs:annotation>
</xs:element>
```
A segítséget előre is köszönöm.

**Comment by nbeeps2** [comment]
KAU? ;)

**Comment by nbeeps2** [comment]
Ez a különbözet szerint adózás, amúgy nekem sem teljesen tiszta. A marginSchemeVat és a marginSchemeNoVat choice-ként szerepel a vatRateType-ban és mindkettő esetben az ÁFA kulcs 0% lesz, hiszen ha nem 0 lenne, azt a vatPercentage alatt kellene jelezni (kivéve egyszerűsített számla esetén, mert ott a vatConent-nél). 

Szóval a számlán mindkettő így néz ki: Nettó 100 Ft, ÁFA 0 Ft, Bruttó 100 Ft

A marginSchemeNoVat szövegezése ezzel passzol is miszerint "Áthárított adót nem tartalmazó különbözet szerinti adózás", viszont a marginSchemeVat szövegezése nekem furcsa "Áthárított adót tartalmazó különbözet szerinti adózás" holott az ÁFA 0 Ft a számlán. Ez így jó?

**Comment by KMGY100** [comment]
Az előzőhöz kapcsolódik ez is:

vatAmountMismatch 3 lehetséges adata:

NO_VAT CHARGE: nincs felszámított áfa a 17.$ alapján
ez rendben, itt nincs áfa

REFUNDABLE_VAT: az áfa felszámítása a 11. vagy 14.$ alapján történt és az áfát a számla
címzettjének meg kell térítenie
itt van áfa ? ( **ha igen nem lehet vat_Percentag**e )

NONREFUNDABLE_VAT: az áfa felszámítása a 11. vagy 14. $ alapján történt és az áfát a számla
címzettjének nem kell megtérítenie
és itt ? van áfa felszámítás , áfa kulcs és bruttó érték ? (**ha igen nem lehet vat_Percentag**e)

Van felszámított áfa vagy nincs ?

@NTCA-tax  két héttel ezelőtt ezt válaszolta:  ""Elnézést, hogy erre még nem válaszoltam. Egy nagyon jó kérdést tettél fel, mellyel kapcsolatban felmerült egy olyan alkérdés, melyről több kollégával kell konzultálnom. A teljes válaszomig a türelmedet kérném.""

**Comment by nbeeps2** [comment]
Ez valami olyasmi lehet, mint a fordított ÁFA (vatDomesticReverseCharge). A számlán ott sincs ÁFA összeg feltüntetve, ennek ellenére az ÁFA-t a vevőnek kell majd megfizetnie.

**Comment by EnokhSys** [comment]
> Az előzőhöz kapcsolódik ez is:
> 
> vatAmountMismatch 3 lehetséges adata:

@KMGY100 bocs a kérdésért, de ez a három eset mikor szokott előfordulni az életben? Ismeretlen területnek tűnik számomra, azért kérdezem, hogy nagyjából tudjam mihez kapcsolni az ÁFA tv. ezen paragrafusait. Köszi.

**Comment by KMGY100** [comment]
@EnokhSys lila gőzöm sincs, ezért kérdeztem én is.

**Comment by EnokhSys** [comment]
> @EnokhSys lila gőzöm sincs, ezért kérdeztem én is.

Kedves @KMGY100 , a https://github.com/nav-gov-hu/Online-Invoice/issues/423 topikban @Macskafarka nagyon szépen összefoglalta példákkal a "vatAmountMismatch" témakörét és problémáját.

**Comment by NTCA-tax** [comment]
@vajayattila : a KAH, KAM, KAR áfakódok nagy valószínűséggel az Online Számlázóból erednek, azonban ott nincs utazási irodás különbözet szerinti adózás. Ezeket a számlákat jelenleg az Online Számlázóban nem lehet kiállítani.

Az utazási iroda különbözet szerinti számlája az egyedüli, ahol van áthárított adó. Az áthárított adó alapja az utazási iroda haszonkulcsa alapján kalkulált összeg. A többi különbözet szerinti adózás esetén nincs áthárított adó. Így az összefüggést a következő módon lehet levezetni:
TRAVEL_AGENCY -> marginSchemeVat
SECOND_HAND > marginSchemeNoVat
ARTWORK -> marginSchemeNoVat
ANTIQUES -> marginSchemeNoVat

@nbeeps2 : Nincs 0%-os adókulcs. Mindegyik különbözet szerinti adózásnál az értékesítőnél van fizetendő adó, de az az utazási iroda kivételével nem a számla tartalmazza. Az utazási iroda esetében van kizárólag áthárított adó. Ezért is van a VatRateType-ban külön jelölő a különbözet szerinti adózásra.

@KMGY100 kérdését az adott topicban válaszolom meg.

**Comment by vajayattila** [comment]
Részemről köszönöm a választ.

**Comment by NTCA-tax** [comment]
Lezárom ezt az issue-t. Ha felmerülne még ezzel kapcsolatban kérdés, akkor nyissatok újat.
