### ISSUE TITLE
3.0 /queryTransactionStatus - returnOriginalRequest

### ISSUE THREAD

**Issue by tkelemen73** [nav-gov-hu/Online-Invoice#495]
Sziasztok,
olyat tapasztaltam, hogy amikor egy 3.0-s /queryTransactionStatus operációban visszakértem egy bármilyen 3.0 előtti számlaadat-szolgáltatás eredeti kérését (returnOriginalRequest = true), nem kaptam rá választ, pontosabban úgy működött, mintha a returnOriginalRequest tag értéke csak false lett volna, és a válaszban a originalRequest tag nem érkezett vissza. Ha egy 3.0-s számlaadat-szogáltatásra kérdeztem le ugyanígy (returnOriginalRequest = true), akkor viszont megérkezett a originalRequest tag is. Ez egy szándékos működés? Inkább hibának tűnik számomra.
Üdv
T.

**Környezet / Environment**
[X] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[X] /queryTransactionStatus

**A kérés verziója / version of the request**
[X] 3.0

**Comment by NTCA-supporter** [comment]
Szia @tkelemen73 !
Köszi a jelzést. Már mi is észrevettük, ki is van javítva, a következő verzióban lesz majd elérhető a fix.
Üdv

**Comment by tkelemen73** [comment]
Sziasztok,
a következő verzió, amiben ez a hiba is javításra került, az mikorra várható? Haladnánk a fejlesztéssel, de....
Köszi!
Üdv
T.

**Comment by drbogar** [comment]
Kapcsolódó kérdés:
Ha egy kérés Aborted vagy van validation message, akkor annál nem lehet elkérni az eredetit vagy emiatt van az is?

**Comment by tkelemen73** [comment]
Sziasztok,
a "következő verziónak" a szombati új verziót gondoltuk, ezek szerint tévedtünk. Azt írtátok október 29-én, hogy már ki is van javítva. A hibajelenség továbbra is fennáll, jelenleg is. Látható, hogy mi a probléma oka? Látható, hogy mikor, melyik verzióban fog megjavulni?
Köszi!
Üdv
T.

**Comment by NTCA-supporter** [comment]
Szia @tkelemen73 !
Ezt sajnos összekevertem egy másik javítással. Ez a funkció korábban (2.0-ban) is így működött, hogy csak az aktuális verziójú lekérdezésnél tudja visszaadni az originalRequestet. Ettől még jogos az igény, hogy visszafelé is legyen kompatibilis, azonban ennek megoldása jövőre várható. Elnézést a fals infóért! Meg fogjuk csinálni, de most nem ez a fő prioritás.
Maradjon nyitva az issue, és jelzek, ha van fejlemény.
Üdv

**Comment by tkelemen73** [comment]
Sziasztok,
hasonló a helyzet /queryInvoiceData esetén is. Van 2018-as számla, amire a kérésre van a válaszban invoiceDataResult (invoiceData lenne a fontos belőle), de ugyanaz a kérés egy másik számlára már invoiceDataResult nélkül jön vissza. PL. ABIFNGVRW4POXIVSJF652QVYFM requestId, ma. Mindkét esetben 1.0-s adatszolgáltatásra kérdezek rá.
üdv
T.

**Comment by NTCA-supporter** [comment]
Szia @tkelemen73 !
A queryTransactionStatus megoldás a héten kerül ki, 3.5 verzióval teszt és éles rendszerre is.
A queryInvoiceData-t nézem, de szerintem az más lesz, lehet, hogy a #751 . Azt is nézem.
Üdv

**Comment by NTCA-supporter** [comment]
Megválaszoltam a másik issueban.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
