### ISSUE TITLE
queryTramsactionStatus annulment

### ISSUE THREAD

**Issue by Mocsa1974** [nav-gov-hu/Online-Invoice#496]
Sziasztok!
Olyat tapasztaltam, hogy a manageAnnulment után az online felületen jóváhagytam a technikai érvénytelenítést, majd a queryTransactionStatus-al lekérdezve a tranzakció állapotát a Response-ban a az annulmentData node alatt a annulmentDecisionDate-ben nem UTC időben jött vissza az érvénytelenítés elfogadásának dátuma.
A response header részében a timeStamp 2020-10-29T08:42:11.000Z az annulmentDecisionDate pedig 2020-10-29T09:41:52.000Z
Valóban 2020-10-29 9 óra 41-kor hagytam jóvá a technikai érvénytelenítést.
A kérdésem az hogy iolyenkor nem 2020-10-29T08:41:52.000Z-nek kellene a annulmentDecisionDate-nek lennie?

Köszönöm

**Comment by NTCA-supporter** [comment]
Köszi a jelzést!
Én is úgy gondolom, hogy UTC-ben kellene visszaadni, már csak az XSD annotáció miatt is.
Javítjuk majd.
Üdv

**Comment by NTCA-supporter** [comment]
A javítás kikerült teszt környezetre.
Zárom  az issuet, köszönjük a jelzést.
Üdv
