### ISSUE TITLE
[Q&A] Sémák lokációja

### ISSUE THREAD

**Issue by gaqskft** [nav-gov-hu/Online-Invoice#497]
Hamarosan megindul a 3.0-ás Online Számla fejlesztése a cégünkben. Az eddigi verzióknál a sémákban nem tapasztaltunk hibát, azonban most a 3.0 XSD interface generálása hibára fut ismeretlen adattípus miatt (common:SimpleText50NotBlankType). Altova XMLSpy-al megnyitva is schemaLocation hibát kapunk. 
A 2.0-ás verzióban megtalálható volt a hivatkozás `<xs:import namespace="..../2.0/data" schemaLocation="invoiceData.xsd"/>`, amíg a 3.0-ás verzióban a common.xsd-re nem látok ilyet jellegű hivatkozást, és gondolom, hogy emiatt nem sikerül megfelelően használni az XSD-ket.
Mivel az XSD felépítésben nem vagyok jártas a kérdésem, hogy ez hiba, és javítva lesz, vagy nekünk kell a kiadott XSD-t kibővíteni a schemaLocation taggal. Ha ez utóbbi a járható, akkor ezt pontosan hol tehetjük meg az XSD-kben? 

Segítségüket előre is köszönöm!

**Comment by renced42** [comment]
Kedves @gaqskft 

Ha Altovád van:

A windows-os verzió beégetetten keres egy catalog.xml fájl a "Program Files(x86)/Altova/Common%verziószám%/Schemas/altova" vagy "Program Files/Common%verziószám%/Schemas/altova" elérési útvonalon. Ha nincs ilyen akkor hozd létre vagy szerkeszd a meglévőt. Működik lokális fájllal és internetes erőforrással is.  

Ha a catalogon változtattál az egész XMLSpy-t be kell zárni és újraindítani mert cacheli a fájlt. Helyes catalognál az XSD validácók (F8) ugyan úgy lefutnak a catalog alatt lévő namespacekre is mint a lokálisokra, működik a "schemaLocation" nélküli xs:import.

**Comment by gaqskft** [comment]
A mai napon folyamán megnézzük, de úgy tűnik, hogy ez így jó lesz. Köszönöm a gyors választ!
