### ISSUE TITLE
queryInvoiceChainDigestRequest OPERATION_FAILED : Feldolgozás sikertelen! (HTTP 500 Internal Server Error)

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#498]
Hello!

Az egyik cégnél az egyik queryInvoiceChainDigestRequest hívásunk fixen hibára fut.

ÉLES v2.0 rendszer. Ha kellenek < user > adatok is, akkor azokat is tudom küldeni.

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<QueryInvoiceChainDigestRequest xmlns="http://schemas.nav.gov.hu/OSA/2.0/api" xmlns:ns2="http://schemas.nav.gov.hu
/OSA/2.0/data">
	<header>
		<requestId>LBR_20201030_09534207</requestId>
		<timestamp>2020-10-30T08:53:53.939Z</timestamp>
		<requestVersion>2.0</requestVersion>
		<headerVersion>1.0</headerVersion>
	</header>
	<user>...</user>
	<software>...</software>
	<page>1</page>
	<invoiceChainQuery>
		<invoiceNumber>E2020\10271</invoiceNumber>
		<invoiceDirection>INBOUND</invoiceDirection>
		<taxNumber>10845204</taxNumber>
	</invoiceChainQuery>
</QueryInvoiceChainDigestRequest>
`

Köszönöm.

**Comment by fenyvessy** [comment]
Van egy space a xmlns:ns2-ben a .hu után.

**Comment by EPluribusUnum** [comment]
@fenyvessy , azt a github tette oda amikor beformázta, én nem úgy küldöm be. Amúgy sem kézzel állítom össze az xml-t hanem JAXB felel érte. Fél éve mindenhol megy gond nélkül, ilyenbe most futottam bele először.

**Comment by EPluribusUnum** [comment]
A teljes request. Jelszót küldöm igény esetén.

[LBR_20201030_10371607.zip](https://github.com/nav-gov-hu/Online-Invoice/files/5464297/LBR_20201030_10371607.zip)

**Comment by NTCA-supporter** [comment]
Kedves @EPluribusUnum !
Ahogy már többször jeleztük, a github nem az éles rendszer helpdesk-je.
Tudod esetleg reprodukálni tesztrendszeren? Ott nagyon szívesen megnézzük.
Üdv

**Comment by EPluribusUnum** [comment]
@NTCA-supporter, https://nav.gov.hu/nav/e-ugyfsz/levelkuldes Ez a megfelelő csatolna?

**Comment by NTCA-supporter** [comment]
@EPluribusUnum igen, az jó lesz.
Viszont ha tudod reprodukálni teszt környezetben, akkor hamarabb fogsz választ kapni :) 
Üdv

**Comment by EPluribusUnum** [comment]
Ügyfélszolgálattól megjött a válasz

"Tisztelt Ügyfelünk!

Köszönettel vettük, hogy kérdésével, észrevételével hozzánk fordult.
Megvizsgáltuk a beküldött számlákat, a kapcsolódó lekérdezést és valóban alkalmazáshiba állapítható meg abban az esetben ha a 
queryInvoiceChainDigestRequest kérés válaszában olyan számlaelem szerepel, amelynek nincs tétel adata.
 
A hibát jeleztük a fejlesztési szakterületnek, javításáról a szokott módon a https://onlineszamla.nav.gov.hu/informatikai_valtozasok oldalon teszünk
közzé tájékoztatást. 


Üdvözlettel:
Online Számla Informatikai HelpDesk
Nemzeti Adó- és Vámhivatal Informatikai Intézet"

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !
A probléma javításra került, teszt rendszeren tudod ellenőrizni egyelőre.
Üdv

**Comment by EPluribusUnum** [comment]
@NTCA-supporter , ez megoldódott, előjött egy másik probléma.

https://github.com/nav-gov-hu/Online-Invoice/issues/628
