### ISSUE TITLE
[Q&A] - Mikor várhatóak a 3.0-s data xml példák?

### ISSUE THREAD

**Issue by lesda** [nav-gov-hu/Online-Invoice#499]

**Comment by csandazoltan** [comment]
Ezt egy másik issue-ban leírtam már, de istenért nem találom se a nyitott, se a zártak között.

"Van példa már", a manageInvoice példában az invoiceData egy base64 encódolt számlapélda, 3db is van. Elég részletesek

bas64decode-el kiadja a számla adat példákat:
Itt az első eleje:

```
<?xml version="1.0" encoding="UTF-8"?>
<InvoiceData xmlns="http://schemas.nav.gov.hu/OSA/3.0/data" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/base">
   <invoiceNumber>03280155079294312882</invoiceNumber>
   <invoiceIssueDate>2020-09-04</invoiceIssueDate>
   <completenessIndicator>true</completenessIndicator>
   <invoiceMain>
      <invoice>
         <invoiceHead>
            <supplierInfo>
               <supplierTaxNumber>
                  <ns2:taxpayerId>48258036</ns2:taxpayerId>
                  <ns2:vatCode>5</ns2:vatCode>
                  <ns2:countyCode>51</ns2:countyCode>
               </supplierTaxNumber>
               <groupMemberTaxNumber>
                  <ns2:taxpayerId>44444444</ns2:taxpayerId>
                  <ns2:vatCode>4</ns2:vatCode>
                  <ns2:countyCode>51</ns2:countyCode>
               </groupMemberTaxNumber>
               <communityVatNumber>AS16514193</communityVatNumber>
               
```

**Comment by lesda** [comment]
Köszönöm, persze ki tudom hámozni, de a 2.0-s XSD-hez voltak/vannak külön data példák a sample/Data sample/ mappában amik 3.0-ra minden bizonnyal invalidak, így vagy törölni vagy frissíteni lenne érdemes őket.

+ a https://onlineszamla-test.nav.gov.hu/dokumentaciok oldalon az alábbi sor szerepel:
"Data példa XML: folyamatban"

**Comment by jozanesz** [comment]
És akkor már az új, zavaros elvárásoknak megfelelő példákat is kérünk. Részszámlákat módosító(?) elszámoló számlát xml-ekként és (pdf) számlaképpel együtt.

**Comment by csandazoltan** [comment]
Január 1-től már ez a kötelező?

**Comment by zsfoto** [comment]
Köszönöm a tippet. 
Visszakódoltam a mintából, de a                

`**<supplierName>wMgLGqTrETzRHXvhVs.......ImvXCFKNhpxBQoorDH</supplierName>**`

Tagról leírást nem találok sehol.
Erről valaki tudna mondani valami hasznosat?
Köszönöm

**Comment by NTCA-supporter** [comment]
Szia @zsfoto !
Az csak egy random string, nincs vele teendő, kezeld úgy mind ABC Kft. :) 

A többeiknek: nem tudom mikor lesznek mintapéldák, nyilván tudjuk, hogy fontos segítség.
Üdv

**Comment by zsfoto** [comment]
Szia @NTCA-supporter!
Köszönöm.
(Már megijedtem ;-) )

Többieknek:
A minta alapján végül sikerült egy számlát beküldenem amit elfogadásra került. Jó volt a tipp, hogy dekódoljuk a 3 mintát.

Zs.

**Comment by EnokhSys** [comment]
Sziasztok,
az alábbi két generált mintát még @NTCA-developer tette be egy másik issue-ba, szerintem nagyon jók, minden benne van:

https://github.com/nav-gov-hu/Online-Invoice/files/5435487/invoiceData.txt
https://github.com/nav-gov-hu/Online-Invoice/files/5435494/invoiceDataXSDValid.txt

**Comment by csandazoltan** [comment]
> Sziasztok,
> az alábbi két generált mintát még @NTCA-developer tette be egy másik issue-ba, szerintem nagyon jók, minden benne van:
> 
> https://github.com/nav-gov-hu/Online-Invoice/files/5435487/invoiceData.txt
> https://github.com/nav-gov-hu/Online-Invoice/files/5435494/invoiceDataXSDValid.txt

Érdekes, hogy az alap namespace és ki van írva, a base64-es példában nincs a "data" namespacenek külön "n0" név adva

**Comment by EnokhSys** [comment]
> Érdekes, hogy az alap namespace és ki van írva, a base64-es példában nincs a "data" namespacenek külön "n0" név adva

Igen, mert az issuet valójában a namespace miatt nyitottam: https://github.com/nav-gov-hu/Online-Invoice/issues/483

Az InvoiceData esetében nem kötelező namespace-t adni, hiszen a "http://schemas.nav.gov.hu/OSA/3.0/data" az alapértelmezett. Ettől függetlenül én minden szegmenst elláttam namespace-el, ha később változik valamelyik, csak kicserélem.

**Comment by KMGY100** [comment]
Az első, invoiceData.tx  mintában a
vatAmountMismatch -nek nincs
case  és reason   ága.
Az   Online Szamla_interfesz specifikáció_HU_v3.0   viszont jelöli hogy van.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet, elérhetőek a példaszámlák. Ha van még kérdés nyissátok újra nyugodtan.
Üdv
