### ISSUE TITLE
[FEATURE] unitOfMeasureType bővítése

### ISSUE THREAD

**Issue by chuckufarleyNAV** [nav-gov-hu/Online-Invoice#5]
**Az igény összefoglalása / Summary of the request**
XSD1.1-be bekerült a unitOfMeasure. Fájóan hiányzik belőle egy pár érték, pl. **négyzetméter, négyzetkilométer, négyszögöl, hektár, illetve a gramm.**

**Az általam javasolt megoldás / The solution I propose**
Javaslom a UnitOfMeasureType lista bővítését a fentiekkel.

**Elfogadható alternatívák / Acceptable alternatives**
-

**Egyéb tartalom / Additional content**
Köszönöm.

**Comment by NTCA-developer** [comment]
Köszönjük a felvetést, megvitatjuk és visszajelzünk.

**Comment by connorhu** [comment]
Sziasztok!

Kolléga még összeszedett párat:
- fő (részvételi díj típusú igények vagy éppen program típusú igények /pl. buszkirándulás/ esetén)
- éj (szállás esetén) – ha már van nap (DAY) mennyiségi egység a NAV-nál, legyen éj is!
- oldal (hirdetéselhelyezés mennyisége a programfüzetben)
- típus (hány féle szórólap kerüljön bele a kongresszusi táskába)
- alkalom (szponzorált előadás tartásának mennyisége. Pl. 2 alkalom) Mondjuk a masszázst is alkalomra fizetem és nem darab-ra
- szint (társasházban található gyűjtő jellegű égéstermékelvezető hossza az épület érintett szintjeinek számában megadva – bővebb info a vonatkozó BM rendeletben)

**Comment by NTCA-developer** [comment]
Sziasztok!

Megvitattuk a kérdést és sajnos nemet kell mondjak. Nem azért, mert nem támogatjuk a felvetést, hanem elvi okokból. Minden lehetséges helyen igyekeztünk kommunikálni, hogy a listának nem célja minden SI mértékegységet tartalmaznia, az összeállításában inkább belső szempontok domináltak. Ezért is vezettük be a unitOfMeasureOwn taget, hogy a kivételszabályokat kezelni tudjuk.

Ehhez az elvhez ragaszkodnunk kell, ha most engedünk egy módosításnak, akkor soha véget nem érő sztori fog kerekedni belőle. (nagyon jól példázza az állítás igazság tartalmát, hogy jött még újabb javaslat az eredeti felvetés mellé is)

Kérem a megértéseteket, a javaslatot pedig mindenképpen köszönjük. Ha van még javaslatotok, ötletetek, akkor nagy örömmel várjuk.

**Comment by chuckufarleyNAV** [comment]
De hogyha a mindennapi életben használt mértékegységek jelentős része nem kerül be a szabványos értékkészletbe, akkor mit nyertek a dologgal? Az volt az indoklás, hogy ne összevissza kódok menjenek be a rendszerbe. Így viszont vállaltan továbbra is sok esetben összevissza kódok mennek be, ami sem statisztikára, sem elemzésre nem használható. Az én egyik ügyfelemnél értékkészletből jönnek a mértékegységek, miután megcsináltam a map-et köztük és a NAV között, azt láttam, hogy a 20 fajta kódból kb. 12 feleltethető meg NAV-kódnak, a másik 8 pedig továbbra is OWN-ként megy be...
