### ISSUE TITLE
WARN = MISSING_HEAD_DATA_CUSTOMER  nem magánszemély de nem is adóalany vevő esetén

### ISSUE THREAD

**Issue by KMGY100** [nav-gov-hu/Online-Invoice#500]
queryTransactionStatus kérésre az alábbi WARN üzenetetkapom akkor, amikor
a vevő  NEM MAGÁNSZEMÉLY DE NEM IS ADÓALANY

"MISSING_HEAD_DATA_CUSTOMER"
"Vevő adószám (első nyolc karaktere) hiányzik"

Vevő címadatok szerepelnek az XML-ben
Vevő adószám nem szerepel  (mert nincs)

transactionId = 35L8CLK2HXBDMS3Y

Vagy:  MAGÁNSZEMÉLY vevő esetén ugyanaz a WARN üzenet
transactionId = 35L3ACEY5J3DJSQQ

Legyetek szívesek nézzétek meg.
Nem jövök rá mit rontottam el.

**Comment by NTCA-supporter** [comment]
Szia @KMGY100 !
Azt hiszem korábban már volt ez a kérdés, de már nem tudom biztosan.
A WARN készlet szakmai felülvizsgálat alatt van, az interfész dokumentációban is még csak annyit írtunk, hogy felülvizsgálat alatt.
Amíg ez nem történik meg a fejlesztéssel együtt, addig előfordulhat ilyen.
Szerintem zárható az issue, ha megtörténik ez a felülvizsgálat, akkor frissíteni fogunk minden doksit.
Üdv

**Comment by KMGY100** [comment]
Még annyit hozzáteszek:
MAGÁNSZEMÉLYnek
transactionId = 35KUH6DE81PN4OL    ez rendben  nincs WARN
szintén MAGÁNSZEMÉLYnek
transactionId=35L321UQZTL5VXFF   itt jön a MISSING_HEAD_DATA_CUSTOMER

A kérdésem az, hogy ez a WARN lehet labilis ?
mert nem konzekvensen adja a WARN üzenetet

**Comment by NTCA-supporter** [comment]
Szerintem ez tippre még a korábban érvényben lévő 100.000-es áfa értékhatártól függ.
Ahogy mondtam ezeket átnézzük, és aktualizáljuk.
Üdv

**Comment by KMGY100** [comment]
Ok.  Köszönöm a választ.

**Comment by nbeeps2** [comment]
@KMGY100 itt volt erről szó: #493
