### ISSUE TITLE
[Q&A] Data példa adószám nélküli belföldi számla eseteire

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#501]
Szükség lenne DATA példákra pdf + xml is azokra az esetekre, amikor számlázó programmal készített számlával bizonylatoltan belföldi termékértékesítés történik egyenes áfás tételsorral, és a vevőnek nincs magyar adószáma.
Ezeket a számlákat eddig nem kellett adatszolgáltatni, de 2021.január 01-től kell, azonban a v3.0 specifikációja szerint lehetetlen feladni.
Két példa is kellene. **Az egyik, amikor nem adóalany belföldi vevőnek** (pl. gazdasági tevékenységet nem folytató alapítványnak, vagy nem jogi személy, de korlátozott jogképességgel rendelkező nem adóalany társasháznak) történik az értékesítés.
**A másik, amikor adóalanynak, de nem az adóalanyiságára tekintettel történik az értékesítés.** pl. Közösségi adószámmal rendelkező, de magyar adószámmal nem rendelkező vevőnek belföldi értékesítés keretébe tartozó termékértékesítés történik (az termék nem hagyja el Magyarországot).
Különösen érdekel mindkét esetben a magyar adószám hiányának kezelése, valamint az, hogy kell-e nevet, címet szerepeltetni az adatszolgáltatásban.
A második esetben az is érdekel, hogyha a számlaképen annak ellenére szerepel a vevő közösségi adószáma, hogy nem arra tekintettel történik a termékértékesítés, akkor ezt az EU adószámot lehet,-e, kell-e szerepeltetni az XML-ben, mondjuk, mert a NAV ebből tudja azonosítani a vevőt. Ha mégsem akarja azonosítani a vevőt, ha nincs magyar adószáma, akkor kell-e a nevét és a címét szerepeltetni?
Azért kérdezem, mert az adatszolgáltatási struktúra elvárásainak való megfelelés a számlázó programok készítői számára sokkal nagyobb súllyal esik latba, mint maga a törvény.

**Comment by nbeeps2** [comment]
@Macskafarka Nekem sikerült ilyen 3.0-s számlákat feladni. Ha nem magánszemélyről van szó, akkor a privatePersonIndicator legyen False és ha nincs adószáma akkor a customerVatData rész ne legyen kitöltve csak a a customerName és a customerAddress. A NAV adatszolgáltatásban a számlán lévő adószámot kell szerepeltetni, viszont ha több adószám szerepel a számlán (pl. megadott magyar adószámot és közösségi adószámot), akkor azt az adószámot kell szerepeltetni a choice-ban, ami az ÁFA törvény szerint az adott számla esetén kötelező volt.

**Comment by nbeeps2** [comment]
Igazából nagyon egyszerű a logikája, ha a magán személy, akkor privatePersonIndicator True és nincs értelmezve se az adószám, se a cím rész, nem kell tölteni. Minden más esetben a privatePersonIndicator  False és kell a cím is. Ha pedig nincs adószáma, akkor nem töltöd a customerVatData részt, egyéb esetben meg töltöd azt is a számlán megadottak szerint. Ha pedig több adószámot adott meg, akkor meg próbálod kitalálni, hogy melyiket lenne jó feladni. Na ezt a részét tartom butaságnak, mert ezt a számlázó program nem minden esetben fogja jól automatizálni, így jobb lett volna, ha több adószám esetén fel lehetett volna párhuzamosan adni az adószámokat, mint a 2.0-ban (pl. magyar és közösségi adószám együtt)

**Comment by Macskafarka** [comment]
Köszi @nbeeps2!

**Comment by Macskafarka** [comment]
Köszi @nbeeps2!  Azt kellene mások által is lekövethető módon tisztázni, hogy "működik, ahogy működik", vagy van benne átgondolt és értelmezhető logika is. Világossá kell tenni, hogy van-e értelme nem adóalany esetén a cím és név küldésének.
Van-e szükség nem adóalanyokról csupán készletezésre nevet és címet gyűjteni?
Azzal nem értek egyet, hogy a  "adatszolgáltatásban a számlán lévő adószámot kell szerepeltetni". Az ÁFA tv. 169.§ da) pontja kifejezetten csak annak az adószámnak a szerepeltetését teszi kötelezővé, "amely alatt mint adófizetésre kötelezettnek a termék értékesítését, szolgáltatás nyújtását teljesítették". A második példám esetén éppen arra vagyok kíváncsi, hogy bár szerepel a belföldi értékesítésről készült számlán a vevő EU adószáma, de a számlázűskor tudjuk, hogy ez irreleváns, mert belföldi értékesítés nem történhet a közösségi adószám "alatt".

**Comment by nbeeps2** [comment]
@Macskafarka "A második példám esetén éppen arra vagyok kíváncsi, hogy bár szerepel a belföldi értékesítésről készült számlán a vevő EU adószáma, de a számlázáskor tudjuk, hogy ez irreleváns, mert belföldi értékesítés nem történhet a közösségi adószám "alatt"."

Ez esetben vagy tiltsd a programodban az ilyen számlák kiállítását, vagy hagyd rá a felhasználóra és akkor ő lehet majd kap később erre egy Warningot. Az biztos nem lehet a megoldás, hogy amikor a számlán csak közösségi adószám szerepel, a számlázó program ennek ellenére egy sima adószámot küld az adatszolgáltatásban.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet, feltöltésre kerültek a példaszámlák.
Ha van még kérdés, nyissátok újra.
Üdv
