### ISSUE TITLE
[Q&A]

### ISSUE THREAD

**Issue by hape1022** [nav-gov-hu/Online-Invoice#502]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Sziasztok,

Egy kérdésem lenne a 2021/Jan/1 - 2021/Marcius/31 közötti "szankciómentes" idöszakkal illetve a retroaktivitással kapcsolatban. 
Ha egy cég jövö év Marcius 1-en áll majd át a v2.0-ról v3.0-ra, akkor jelentenie kell majd retroaktiv módon például a B2C és export szamláit Január és Februárra a v3.0 specifikációt alkalmazva?

Üdv

**Comment by NTCA-tax** [comment]
Nincs ilyen kötelezettsége. A szankciómentes időszakhoz nincs párosítva utólagos, visszamenőleges adatszolgáltatási kötelezettség. A 2021-es szankcionálási moratórium ebben nagyon hasonlít a 2020. július-szeptemberi időszakhoz.

**Comment by szako** [comment]
> Nincs ilyen kötelezettsége. A szankciómentes időszakhoz nincs párosítva utólagos, visszamenőleges adatszolgáltatási kötelezettség. A 2021-es szankcionálási moratórium ebben nagyon hasonlít a 2020. július-szeptemberi időszakhoz.

Akkor okosítsátok ki a NAV ügyfélszolgálatot is, mert a telefonos ügyfélszolgálatot felhívva szeptemberben ők azt mondták, hogy pótolni kell az elmaradt számlákat 2020.07.01->2020.09.30 (vagy az limit levitelének élesítése) között.

**Comment by NTCA-tax** [comment]
@szako : megtörtént.
