### ISSUE TITLE
[FEATURE] Warning küldése, ha az invoiceDeliveryPeriodEnd ki van töltve, de a periodicalSettlement false

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#503]
**Az igény összefoglalása / Summary of the request**
Partnereink a szállítói (bejövő) számlákat automatikusan dolgoztatják fel a rendszerünkkel, és ennek kapcsán találkozunk több olyan beküldéssel, ahol az invoiceDeliveryPeriodStart/invoiceDeliveryPeriodEnd szépen ki van töltve (vagy minimum az End), de a periodicalSettlement false értéket vesz fel. Természetesen a beolvasást el tudjuk végezni, de ilyenkor egy figyelmeztetés azért jár mellé, ami plusz munkát jelent az ügyfeleknek az ellenőrzés során, amit hosszú távon azért jó lenne elkerülni, jobb lenne pontos adatokat kapni.

**Az általam javasolt megoldás / The solution I propose**
Teszteltük, ilyenkor nem érkezik a feldolgozás visszaigazolása mellé Warning, pedig úgy gondoljuk, hogy érdemes lenne jelezni az adatszolgáltató felé, hogy nem teljesen helyesen végzi az adatszolgáltatást.

Köszönjük!

**Comment by NTCA-tax** [comment]
Köszönjük a javaslatot, megküldtem a megfelelő kolléga számára :)
