### ISSUE TITLE
[Q&A] SCHEMA_VIOLATION hibakód queryInvoiceData kérés esetén, 3.0

### ISSUE THREAD

**Issue by szako** [nav-gov-hu/Online-Invoice#504]
A számla duplikációk kezelését fejlesztjük és belefutottunk egy olyan problémába, amire nincs megoldásunk. A teszt rendszerben 3.0-ás kérésekkel az alábbi tevékenység történt időben sorrendben:

Tranzakció azonosító | Időpont | Tevékenység
------------ | ------------- | -------------
35MAKZ4U4P8FIYY0 | 2020-11-02 14:13:54 | számlabeküldés: hiba
35MBHKP9WQ3DUR2I | 2020-11-02 14:39:15 | számlabeküldés: warning
35MBIDD84ZIGJM5B | 2020-11-02 14:39:52 | érvénytelenítés
35MQ5YN962AUG9P1| 2020-11-02 21:30:08 | számlabeküldés: warning
35MQNEDUF2M8APGR| 2020-11-02 21:43:41 | számlabeküldés: hiba duplikáció miatt

A vége az lett, hogy figyelmeztetésekkel ugyan, de a számlát befogadta a NAV:

![image](https://user-images.githubusercontent.com/2895406/98126150-8e491480-1eb5-11eb-82a9-419a14372b1f.png)

A figyelmeztetéshez a releváns számla XML metszet:

```xml
<customerInfo>
  <privatePersonIndicator>false</privatePersonIndicator>
  <customerVatData>
    <communityVatNumber>DE109754231</communityVatNumber>
  </customerVatData>
  <customerName>Software Systeme GmbH</customerName>
    <customerAddress>
      <ns3:simpleAddress xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base">
      <ns3:countryCode>DE</ns3:countryCode>
      <ns3:region>05</ns3:region>
      <ns3:postalCode>53125</ns3:postalCode>
      <ns3:city>Bonn</ns3:city>
      <ns3:additionalAddressDetail>In der Wieste 53</ns3:additionalAddressDetail>
    </ns3:simpleAddress>
  </customerAddress>
</customerInfo>
```
Amikor a sikeres tranzakció azonosítót szeretném lekérni a NAV-tól a queryInvoiceData segítségével, akkor c hibakódot kapunk.

Kérés részlet:
```xml
<invoiceNumberQuery>
  <invoiceNumber>90034968</invoiceNumber>
  <invoiceDirection>OUTBOUND</invoiceDirection>
</invoiceNumberQuery>
```

Válasz részlet:
```xml
<ns2:technicalValidationMessages>
  <validationResultCode>ERROR</validationResultCode>
  <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
  <message>Request body contains on line: [-1] and column: [-1] error: [cvc-complex-type.2.4.b: The content of element 'customerTaxNumber' is not complete. One of '{"http://schemas.nav.gov.hu/OSA/3.0/base":taxpayerId}' is expected.]</message>
</ns2:technicalValidationMessages>
<ns2:technicalValidationMessages>
  <validationResultCode>ERROR</validationResultCode>
  <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
  <message>Request body contains on line: [-1] and column: [-1] error: [cvc-complex-type.2.4.d: Invalid content was found starting with element 'communityVatNumber'. No child element is expected at this point.]</message>
</ns2:technicalValidationMessages>
```

11.02-án is ugyanezt az eredményt kaptam, de a mai napi kérésem aktuálisabb:
A kérés requestId-je: 20110415FpdGI+AIw4swcXJ426hz9W
A kérés timestampje: 2020-11-04T14:18:51.000Z

A queryTransactionList, queryInvoiceChainDigest, queryInvoiceCheckRequest jól működik a számlára. A webes felületen az adatszolgáltatásnál a számla részletező funkcióval és a kimenő számláknál a részletes nézetettel is sikeresen meg tudom nézni az adatokat.

A kérdésem az, hogy miért kapunk hibát és miért ilyen jellegűeket? Olyan, mintha számla validációs hibákat adna vissza az interfész. De a rendszer befogadta, szóval nem ez az elvárt működés. Köszönöm.

**Comment by NTCA-supporter** [comment]
Szia @szako !
Szerintem ez ugyanaz mint a #470  . Utánanézek és jelentkezem.
Üdv

**Comment by kurucza** [comment]
SZiasztok,

Nálunk ugyenez a hiba jelenzkezet.
Tranzakció azonosító:35RZ8UGAJX9NK18L 
FR a vevőnk. A specifikáció szerint:
Eset:
Vevő nem Magyarországon nyilvántartásba vett áfaalany (pl. más EUbeli vagy harmadik országbeli adóalany)
Leírás:
privatePersonIndicator = false
customerInfo/customerVatData/communityVatNumber vagy
customerInfo/customerVatData/thirdStateTaxId töltése kötelező.



XML tartalma, amire kapjuk a warning üzenetet:
InvoiceData:
<customerInfo>
	<privatePersonIndicator>false</privatePersonIndicator>
	<customerVatData>
		<communityVatNumber>FR12345678910</communityVatNumber>
	</customerVatData>
	<customerName>EU Customer</customerName>
	<customerAddress>
		<base:simpleAddress xmlns:base="http://schemas.nav.gov.hu/OSA/3.0/base">
		<base:countryCode>FR</base:countryCode>
		<base:postalCode>21603</base:postalCode>
		<base:city>Longvic</base:city>
		<base:additionalAddressDetail>1 Eiffel</base:additionalAddressDetail>
		</base:simpleAddress>
	</customerAddress>
</customerInfo>

Hiba:
<businessValidationMessages>
	<validationResultCode>WARN</validationResultCode>
	<validationErrorCode>MISSING_HEAD_DATA_CUSTOMER</validationErrorCode>
	<message>Missing customer’s tax number (or its first eight characters).</message>
	<pointer>
		<tag>InvoiceData/invoiceMain/invoice/invoiceHead/customerInfo/customerVatData/customerTaxNumber</tag>
	</pointer>
</businessValidationMessages>

Köszi,
Andi

**Comment by kurucza** [comment]
természetesen a jelentkezett, 2 tt :-)

**Comment by lernerz** [comment]
> Szia @szako !
> Szerintem ez ugyanaz mint a #470 . Utánanézek és jelentkezem.
> Üdv

Sziasztok!

A hiba nem ugyanaz mint a #470-es, ezt külön kellene kezelni.

Köszi!
Üdv,
Z

**Comment by KMGY100** [comment]
@kurucza 
A   queryInvoiceData lekérdezés jelen pillanatban kizárólag magyar adószámos vevővel működik.
Reméljük kijavítják hamarosan

**Comment by lernerz** [comment]
Csakhogy nekünk nem a QueryInvoceData-val van bajunk…

**Comment by kurucza** [comment]
> > Szia @szako !
> > Szerintem ez ugyanaz mint a #470 . Utánanézek és jelentkezem.
> > Üdv
> 
> Sziasztok!
> 
> A hiba nem ugyanaz mint a #470-es, ezt külön kellene kezelni.
> 
> Köszi!
> Üdv,
> Z

Sziasztok,

Nálunk a hiba az, hogy 'külföldi' a vevő (EU tagállam), kitöltjük a `<communityVatNumber>FR12345678910</communityVatNumber>` értéket helyesen és mégis hiányolja az üzenet szerint a vevő adószámát a `customerTaxNumber` értéket, amit értésünk szerint nem kell tölteni, de nem is tudnánk mivel.

Andi

**Comment by NTCA-supporter** [comment]
Szia @kurucza !
Az általad jelzett WARN működés már többször felmerült. A teljes 3.0 kapcsán már folyamatban van a WARN "készlet" felülvizsgálata. Jelenleg még figyelmen kívül hagyható.
Az interfész dokumentációban is jeleztük, hogy felülvizsgálat folyamatban.
Köszi a türelmet és a jelzést is természetesen.
Üdv

**Comment by kurucza** [comment]
> Szia @kurucza !
> Az általad jelzett WARN működés már többször felmerült. A teljes 3.0 kapcsán már folyamatban van a WARN "készlet" felülvizsgálata. Jelenleg még figyelmen kívül hagyható.
> Az interfész dokumentációban is jeleztük, hogy felülvizsgálat folyamatban.
> Köszi a türelmet és a jelzést is természetesen.
> Üdv

Köszönöm szépen a válaszod!

**Comment by NTCA-supporter** [comment]
Szia @szako !
Elvileg ezt már nem kellene tapasztalnod új beküldött számláknál.
Kérlek ellenőrizd.
Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet.
