### ISSUE TITLE
[Q&A] vatPercentage vs. vatExemption használata normál számla esetén

### ISSUE THREAD

**Issue by alaplap** [nav-gov-hu/Online-Invoice#505]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**

A kérdések normál (nem egyszerűsített) számlákra vonatkoznak.

- Használhatom a `lineVatRate`-on belül minden 0% ÁFA-s termék esetben a `vatPercentage` tag-et 0 értékkel a `vatExemption` helyett?
- Akkor is használhatom a `vatPercentage`-t, ha a számlán AAM, TAM, AJT, stb. kódok szerepelnek az ÁFA mérték jelölésére?
- Szabályos az a számla, amin az adó mentesség jelölésére az [Online Számla interfész specifikáció](https://onlineszamla.nav.gov.hu/api/files/container/download/Online%20Szamla_interfesz%20specifik%C3%A1ci%C3%B3_HU_v3.0.pdf) 116. oldalon felsorolt `vatExemption`/`case `-től eltérő kódok szerepelnek?

A válaszokat előre is köszönöm.

**Comment by DrotosTot** [comment]
Szia! 166. oldal alján, "érvénytelen áfakulcs vagy áfatartalom - A rendszer validációval kényszeríti az elévülési időn belül lévő áfakulcsok vagy tartalmak helyes megadását." alapján hibát fogsz kapni 0%-os vatPercentage esetén.
A case-re szintén, csak a speckóban megadott tartalom szerepelhet, amit az összesítőben is fel kell tüntetni. Arra is brummog a rendszer, ha sorszinten szerepel egy case, de az összesítőben nem vagy fordítva.

**Comment by alaplap** [comment]
Köszönöm.
