### ISSUE TITLE
[Q&A] Szeretném kérdezni, hogy mi a probléma? TESZT - TrID: 35QE01RAX8W1ZWHV

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#506]
Szeretném kérdezni, hogy a **35QE01RAX8W1ZWHV** tranzakció id alatti **TESZT** beküldésnél mi a pontos probléma.

Köszönöm

**Comment by NTCA-supporter** [comment]
Szia @zsfoto !
Az invoiceData xml-ed még 2.0-ás, és v3-as interfészen próbálod beküldeni.
Üdv

**Comment by zsfoto** [comment]
Köszönöm
Hol találok erre példa XML-t?
