### ISSUE TITLE
[FEATURE] V3.0 Warning, ha a thirdStateTaxId mellett a countryCode=HU

### ISSUE THREAD

**Issue by DrotosTot** [nav-gov-hu/Online-Invoice#507]
**Az igény összefoglalása / Summary of the request**
Rövid és tömör leírása a problémának, amiből az igény származik. / A clear and concise description of what the problem is, from which the request arises.
Jelenleg beküldhető és DONE eredményű lesz az olyan adatszolgáltatás, ahol thirdStateTaxId mellett a vevői címadatban országkódként HU szerepel.

**Az általam javasolt megoldás / The solution I propose**
Rövid és tömör leírása a javasolt megoldásnak. / A clear and concise description of the proposed solution.
Célszerű lenne validálni a vevői adatot a customerVatData csomópontban levő adatok alapján. Ha az adószám típusa communityVatNumber, akkor csak EU-s, ha thirdStateTaxId akkor az EU-n kívül bármelyik országkód.

**Elfogadható alternatívák / Acceptable alternatives**
Rövid és tömör leírása az elfogadható alternatíváknak, ha az igény nem valósítható meg az eredeti formájában. / A clear and concise description of the acceptable alternative solutions, in case the request is not doable in it's original scope.
Megelégednénk a thirdStateTaxId validációjával is.

**Egyéb tartalom / Additional content**
Szabad szöveges rész. / Own remarks.
A kérésünk lehet, hogy határeset, hogy a validáció kliens vagy szerveroldalon történjen meg. Nyugodtabbak lennénk, ha mindkét oldalon.

**Comment by nbeeps2** [comment]
Szerintem a cím és az adószám nem feltétlen van közvetlen kapcsolatban egymással. Például nekünk van olyan ügyfelünk, aki külföldi, külföldi címe van, de adózási okokból van kiváltott magyar adószáma... és ez ugyanígy fordítva is igaz lehet. Szerintem minél kevesebb a bekötött Warning, nekünk fejlesztőknek annál jobb és egyszerűbb az élet, szóval én nem támogatom :)

**Comment by Macskafarka** [comment]
Ahogy @nbeeps2 írta, az adószámnak, és a címnek nincs köze egymáshoz. A cím a számlázási cím, az adószámnak meg a termékértékesítéshez van köze.  Az ÁFA tv. úgy fogalmaz, hogy adószám, **amely alatt** a termékértékesítés történt. Ezt pedig attól függ, hogy a termék elhagyta-e Magyarországot, vagy az EU határát átlépte-e. 
A számlázó programok eddig elkövették azt az egyszerűsítést, hogyha magyar a vevő címe, akkor belföldi a termékértékesítés, ha közösségi adószáma van, akkor közösségi ügyletről van szó. 
Pedig a termékértékesítés jellege független a vevő országkódjától. Magyar című partnernek is lehet Közösségi értékesítés, ha az áru elhagyta Magyarországot, és 3. országbeli címmel és adószámmal rendelkező partnernek is készülhet belföldi számla, rajta 27%-os egyenes áfás sorral. Pl. Kenyai cég Magyarországon vacsorázott, és erről számlát kért. Kenyai lesz a cím, de belföldinek számít a termékértékesítés.

**Comment by topybear** [comment]
Nem lenne jó összekötni a címet az adószámmal, mert nincs összefüggés. Pl. pont a napokban kaptunk olyan számlát, amit egy amerikai cég állított ki közösségi adószámmal.

**Comment by NTCA-tax** [comment]
Sajnos az áfa szabályrendszere ennél bonyolultabb. Nem a vevő címe, hanem az adott tranzakciónál játszott státusza a döntő. Így lehet például egy Németországban letelepedett vevő esetében belföldi a teljesítés (így alapesetben 27%-os az áfa), de lehet közösségi is. Egy harmadik országbelinek is lehet áfa regisztrációja (akár Magyarországon is). Amennyiben az általad javasolt irányba mennénk, akkor nagyon sokszor mi általunk is tudottan fals warningokat adnánk vissza. Arról pedig már több bejegyzésben megerősítettetek, hogy ez nem lenne jó irány.

**Comment by DrotosTot** [comment]
Mindenkinek köszönöm a választ és hogy megosztottátok a véleményeteket!
