### ISSUE TITLE
UTC időpont  kontra  Helyi idő  

### ISSUE THREAD

**Issue by KMGY100** [nav-gov-hu/Online-Invoice#508]
próbaképpen a V3 tesztben minden kérés timestamp  értékére a helyi időt tettem és
a requestSignature  számítását is a helyi idővel számoltam. ( NEM UTC idővel)

Minden kérésem működik és teljes értékű választ kapok minden kérésre.

Ez később a V3 élesben problémát okozhat ?
Ha igen milyen jellegű problémát ?

**Comment by NTCA-supporter** [comment]
Szia @KMGY100 !
Az új INVALID_TIMESTAMP validáció +-1 nap toleranciát engedélyez.
Üdv

**Comment by KMGY100** [comment]
@NTCA-supporter 
Online Szamla_interfesz specifikáció_HU_v3.0   doksiban nem szerepel 
ez az üzenet.

**Comment by NTCA-supporter** [comment]
Szia @KMGY100 !
Ez így van, teljesen jogos. A 2.0-sban már szerepel, a 3.0 doksi új verzió még review-n van és utána publikáljuk, amiben már ez is benne lesz.
Üdv

**Comment by KMGY100** [comment]
@NTCA-supporter 
Igen a A 2.0-sban szerepel, de nem működött a nyári időszámítás szerint INVALID_TIMESTAMP validáció +-1 nap toleranciával
Akkor kellett volna működnie.
Jól látom ?
Most téli időszámítás szerint beleférünk a +-1 napba.

**Comment by KMGY100** [comment]
@NTCA-supporter 
bocs. hirtelen kevertem az órát a nappal.
Zárok
