### ISSUE TITLE
[DEV support] - Üres válasz az API hívásra

### ISSUE THREAD

**Issue by lesda** [nav-gov-hu/Online-Invoice#509]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[x] /tokenExchange

**A kérés verziója / version of the request**
[x] 3.0

**A requestId értéke / requestId value**
```
TOKEN5fa3ff56a8916
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Semmilyen válasz nem érkezett és ez nem egyedi eset. Néha érkezik válasz, néha nem. API operációtól sem függ, van példám adószám ellenőrzésre is.
PHP+cURL környezetből indul a hívás, ha ez releváns. Ugyanabben a környezetben a 2.0 gond nélkül fut

*Egyéb tartalom / Additional content*
Nov. 5. 14:34-kor küldve

**Comment by NTCA-supporter** [comment]
Szia @lesda !
Valamilyen timeout értéked van beállítva?
Logban azt látom, hogy http 200-al visszaadtuk sikeresen a tokent.
Köszi

**Comment by lesda** [comment]
Szia,
 igen 10sec, ugyan úgy mint a 2.0 környezetben, ott sose volt belőle gond. Ha jól értem a specifikációt akkor 5sec-en belül meg kellene kapni a választ.

**Comment by NTCA-supporter** [comment]
Az egy olyan érték, amit nagyon nagy %-ban tudunk teljesíteni, azonban nem garantált. A NAV határvédelem minden hívásnál 60 sec, így afölött biztosan nem adunk választ. A logból az derül ki, hogy ez a kérésed pont kicsúszott a 10 sec-en.
Kérlek fontold meg ezt a 10 sec szabályt.
Üdv

**Comment by lesda** [comment]
Oké, akkor nyilván emelünk rajta.

Ez alapján löttük be: "A szerver jellemzően 200ms alatti válaszidőkkel szolgál ki. A szinkronhívások blokkoló timeout értéke 5000   ms."

**Comment by lesda** [comment]
Felvettem 60sec-re a timeout-ot, de az előbb a TOKEN5fa41633712e6 trid-el megint üres volt a válasz (érzésre megvolt a ~egy perces várakozás)

**Comment by EPluribusUnum** [comment]
@lesda , frissíts curl-t. Valamelyik korábbi issue-ban kinyomozták hogy az nem működik jól.

**Comment by lesda** [comment]
@EPluribusUnum , de ha curl a hibás akkor a 2.0-s verzió hogy mehet gond nélkül hónapok óta? Illetve érzésre is timeotnak tűnt, tényleg ~60 secig tekert a browser, mire megjelenítette a semmit.

**Comment by renced42** [comment]
Kedves @lesda Javaslom nézd meg a programodban a namespace keztelést. előfordul, hogy a namespacek nem konzekvensen egyformán térnek vissza.
Egy korábbi issue miatt is ezen pörögtünk, hogy üres a válasz 2.0-n viszont ugyanaz a kód tökéletes. Aztán kiderült, hogy a 3.0-ban bevezetett namespace miatt nem jól működik a program és olyan, mintha nem kapna választ. 
Nézd meg ezt #491 illetve a végén van egy minta java program txt,ben, azt is felhasználhatod.  .

**Comment by lesda** [comment]
Kedves @renced42 , a namespace issue-n már túl vagyok, éppen ezért első körban a még xml parsolás nélküli api választ, mint stringet nézem. Ez az ami üres volt az említett esetben.

**Comment by szako** [comment]
Mai nap többször timeoutolt a teszt rendszer nekünk is, lehet pont ilyenekbe futottál bele.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Jelentkezik még a probléma?
Ha nem, akkor zárjátok kérlek.
Üdv

**Comment by lesda** [comment]
Szia!

 Az utóbbi napokban rendben volt nálam, a 60sec-re növelt timeoutnál csak egyszer nem kaptam választ a múlt héten (TOKEN5fa41633712e6), ezt még lehet érdemes ellenőrizni.

**Comment by connorhu** [comment]
Ez volt a curl verzióval összefüggő issue:
https://github.com/nav-gov-hu/Online-Invoice/issues/300

**Comment by lesda** [comment]
@connorhu , szerintem nálam nem ez volt, nem kaptam 200-as választ, hanem 60sec várakozás után timeout volt. Most ezt lezárom, max nyitok majd egy új issue-t ha esetleg újra előfordul.
