### ISSUE TITLE
[DEV support] A 2.0 QueryInvoiceData hívás hibát ad vissza

### ISSUE THREAD

**Issue by vajayattila** [nav-gov-hu/Online-Invoice#511]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[x] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[x] 2.0
[] 3.0

```
RID742606105412
```
A 2.0-ás teszt felületen hívtam meg a QueryInvoiceDataRequest metódust, egy már korábban sikeresen beküldött és ellenőrzött számla számlaszámával.

Válaszként ezt kapom (az olvashatóság kedvéért formáztam az xml-t):
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GeneralExceptionResponse xmlns="http://schemas.nav.gov.hu/OSA/2.0/api" xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/data">
  <funcCode>ERROR</funcCode>
  <errorCode>OPERATION_FAILED</errorCode>
  <message>Érvénytelen kérés!</message>
</GeneralExceptionResponse>
```
Biztosan én vagyok a ludas a dologban, de nem bírok rájönni a hibámra.
A segítséget előre is köszönöm.

**Comment by NTCA-supporter** [comment]
Kedves @vajayattila 

Én a logból azt látom, hogy a queryInvoiceData url-je helyett a queryTransactionStatus url-je lett meghívva. Ezt meg tudnád nézni, hogy tényleg így van-e? Ha nem akkor szólj és tovább nézem.

**Comment by vajayattila** [comment]
Tényleg ez volt a baja. Javítottam és most vissza is tér. 

Viszont lekérdezek egy olyan számlát ami tutira bent van (tranzakciós ID=336Z62KS31BKVFCS) és a válaszban a invoiceDataResult ág nincs benne.

A lekérés RequestID-je: RID334477426520

Response:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<QueryInvoiceDataResponse xmlns="http://schemas.nav.gov.hu/OSA/2.0/api" xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/data">
  <header>
    <requestId>RID334477426520</requestId>
    <timestamp>2020-11-06T10:23:34.000Z</timestamp>
    <requestVersion>2.0</requestVersion>
    <headerVersion>1.0</headerVersion>
  </header>
  <result>
    <funcCode>OK</funcCode>
  </result>
  <software>
    <softwareId>HU13191308MOU00750</softwareId>
    <softwareName>MODUPROU</softwareName>
    <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
    <softwareMainVersion>7.33</softwareMainVersion>
    <softwareDevName>Indas Kft.</softwareDevName>
    <softwareDevContact>info@indas.hu</softwareDevContact>
  </software>
</QueryInvoiceDataResponse>
```

**Comment by NTCA-supporter** [comment]
Azt látom, hogy a kérésben megadtál batchIndex értéket, de amit le szeretnél kérdezni számla az nem kötegelt kérésben beküldött számla. Ha azt kiveszed akkor szerintem kapni fogsz vissza adatokat.

**Comment by vajayattila** [comment]
Valóban ez volt a baj. Köszönöm szépen a segítséget. Zárom a jegyet.
