### ISSUE TITLE
[DEV support] 3.0 bug - QueryServiceMetricsListResponse 2.0 namespace-el tér vissza

### ISSUE THREAD

**Issue by zambodaniel** [nav-gov-hu/Online-Invoice#512]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange
[x] /metricService

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
null
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
A https://api-test.onlineszamla.nav.gov.hu/metricService/v3/queryServiceMetrics/list hívására v2 namespace válasz jön:
```
xmlns="http://schemas.nav.gov.hu/OSA/2.0/metrics" xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/api"
```
holott az xsd szerint:
```
xmlns="http://schemas.nav.gov.hu/OSA/3.0/metrics" xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:base="http://schemas.nav.gov.hu/OSA/3.0/base" targetNamespace="http://schemas.nav.gov.hu/OSA/3.0/metrics"
```
kellene, hogy legyen.

*Egyéb tartalom / Additional content*

**Comment by NTCA-supporter** [comment]
Szia @zambodaniel !
Köszi a jelzést. A javítás már megvan, a következő verzióba belekerül.
Zárom az issuet.
Üdv
