### ISSUE TITLE
[Q&A] 2021-es törvényi változások

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#513]
A Parlament Gazdasági Bizottsága lezárta a vitát és elfogadta a 2021-es adótörvények módosítását.
**T/13258 Törvényjavaslat** a 2021. évi adóváltozásokról.
[https://www.parlament.hu/irom41/13258/13258.pdf](url)

A javaslat 9. oldalától hosszan taglalja az ÁFA tv. változását, a látszólag fogalmi pontosítások is lényegesek. 
A GitHub-on felmerültek közül sok minden bekerült, úgy látszik **érdemes volt itt felvetni témákat az  @NTCA-Tax  -nak.** 

Ami az adatszolgáltatást (beleértve a xx65M-et is)  közvetlenül érinti, az a tv. 10.sz. mellékletének módosulása, amit a  
T/13258 Törvényjavaslat 6. és 7.sz. mellékletei tartalmaznak a 83. oldalon.
Van ahol csak egy "IS" szó került bele, ami itt a GitHub-on kb 6 hónapja ment nagyot (végszámla adatszolgáltatás témában),
de így érthetőbbé váltak dolgok.

**Comment by EnokhSys** [comment]
@Macskafarka köszi ! Reméltem, hogy az "adatszolgáltatás mint elektronikus számla" témával kapcsolatban is lesz benne pontosítás, de ez egyelőre kimaradt.

**Comment by NTCA-tax** [comment]
@EnokhSys az NGM rendeletet kell megvárnod, mert ez technikai lehetőség szabályozása...

**Comment by EnokhSys** [comment]
> @EnokhSys az NGM rendeletet kell megvárnod, mert ez technikai lehetőség szabályozása...

@NTCA-tax Ja értem, köszi!

**Comment by Macskafarka** [comment]
Ami ugyebár PM rendelet lesz a 23/2014 NGM rendelet módosításáról. :)

**Comment by NTCA-tax** [comment]
Köszi a pontosítást :)

**Comment by NTCA-tax** [comment]
Ezt az issue-t lezárom, amennyiben felmerülne a 2021-es jogszabályi változásokkal kérdés, akkor nyissatok új issue-t rá.

**Comment by jozanesz** [comment]
@Macskafarka
> PM rendelet lesz a 23/2014 NGM rendelet módosításáról

És akkor egyúttal végre kiveszik a 114/2007. (XII. 29.) GKM rendeletre hivatkozást?
