### ISSUE TITLE
[Q&A] Normális dolog az, hogy pénteken még jól ment a token kérés, ma már nem?

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#514]
Ma már ez jön válasznak: "ns2:TokenExchangeResponse", "ns2:encodedExchangeToken", ...
Pénteken még "ns2:" nélkül volt.
Illetve "ns2:funcCode" volt, ma már csak "funcCode".

(Ha jól tudom egy ideje folyamatosan változtatnak a válasz XML-eken.)

**Comment by NTCA-supporter** [comment]
Szia @zsfoto !
Röviden: igen.
Hosszabban: #453 
Üdv

**Comment by lesda** [comment]
Kedves @NTCA-supporter!

 Nyilván nem ismerem a mögöttes rendszereket, de olyan nagy munka lenne garantálni a response xml-eknél a namespace-ek sorrendjét?
 Szerintem nagyon sok szívástól/extra munkától meg lehetne kímélni az alacsonyabb absztakciós szinten feljesztőket.

**Comment by NTCA-supporter** [comment]
Zárom az issuet. Ha maradt kérdés, nyissátok újra kérlek.
Üdv
