### ISSUE TITLE
[DEV support] V3.0 privatePersonIndicator=true esetén a validáció "Vevő adószám (első nyolc karaktere) hiányzik." WARN-t ad vissza

### ISSUE THREAD

**Issue by DrotosTot** [nav-gov-hu/Online-Invoice#515]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[X] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[X] 3.0

**A requestId értéke / requestId value**
```
DE2IDsiNV5QggGiCqUdIz
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Magánszemélynek kiállított számla adatszolgáltatásában a customerInfo csomópontban egyedül a privatePersonIndicator tag szerepel, true értékkel. A validáció mégis "Vevő adószám (első nyolc karaktere) hiányzik." hibára fut.

*Egyéb tartalom / Additional content*

**Comment by NTCA-supporter** [comment]
Szia @DrotosTot  !
Az általad jelzett WARN működés már többször felmerült. A teljes 3.0 kapcsán már folyamatban van a WARN "készlet" felülvizsgálata. Jelenleg még figyelmen kívül hagyható.
Az interfész dokumentációban is jeleztük, hogy felülvizsgálat folyamatban.
Köszi a türelmet és a jelzést is természetesen.
Üdv
