### ISSUE TITLE
Magánszemélyeknél a lakhatási támogatás, kompenzálás a számlában

### ISSUE THREAD

**Issue by littlecutieorion** [nav-gov-hu/Online-Invoice#516]
Magánszemélyeknél a közműszámláknál a lakhatási támogatást, vagy az előző elszámolószámla kompenzálását bele kell-e tenni az adatszolgáltatásba, És ha igen, akkor a sémán belül hová? 
Mivel ez nem érinti az adóalapot és az ÁFA-t sem, csak az ügyfél fizetendőjét.

**Comment by NTCA-tax** [comment]
Lehet, hogy itt nekem is képeznem kellene magamat, mert a lakhatási támogatás azért nem feltétlen adóhivatali alap skill-ek közé tartozik. Amennyiben jól értelmezem ennek a lényegét, akkor kiállításra kerül például egy 10 ezer forintos számla, melynek egy részét nem a vevő fizeti meg. Ez akár számlán is megjelenhet, de ez nem érinti a számla áfa törvény szerinti kötelező adattartalmát, mivel ez egy fizetés elszámolási kérdés. Amennyiben ez így van (ebben kérnék Tőled megerősítést), akkor az adatszolgáltatásba ezt nem kell szerepeltetni, mivel nem áfa törvény szerinti kötelező adattartalom.

**Comment by littlecutieorion** [comment]
@NTCA-tax !
Köszönöm a választ, pontosan így van, ahogy leírtad.
Én is ezen tételek nélkül gondolom az adatszolgáltatást,  mivel ez csupán pénzügyi rendezés. 
Ezzel lezárom az Issue-t.
