### ISSUE TITLE
[DEV support] queryInvoiceData + Ékezetes invoiceNumber --> InternalServerError

### ISSUE THREAD

**Issue by jtoberling** [nav-gov-hu/Online-Invoice#517]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[X] /queryInvoiceData

**A kérés verziója / version of the request**
[x] 2.0

**A requestId értéke / requestId value**
XX202011111718177892UQGbpscV6A

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Amennyiben az invoiceNumber ékezetes karaktert tartalmaz a rendszer 500-InternalError-t válaszol.
Pl:
... &lt;invoiceNumber>Á-2020-2&lt;/invoiceNumber> ...

Válasz:

HTTP/1.1 500 Internal Server Error [Content-Type: application/xml;charset=UTF-8, Content-Length: 310, Date: Wed, 11 Nov 2020 16:25:48 GMT, X-Via: epsaicxmlapi3.eszamla-edu.local, X-Server: backend_invoiceService-v2-queryInvoiceData/XML_kpx_B1, Connection: keep-alive, Strict-Transport-Security: max-age=31536000; includeSubDomains]

*Egyéb tartalom / Additional content*

**Comment by DrotosTot** [comment]
@jtoberling kipróbáltuk mi is, nekünk "Ő"-vel befogadta, feldolgozta:
<invoiceNumber>DŐ2-000026/2020</invoiceNumber>
Nem lehet, hogy a szokásos szolgáltatáskiesés okozta?

**Comment by jtoberling** [comment]
Köszönöm az útmutatást - alacsony szintű protokolláris trace-el sikerült kideríteni, hogy a hibát lekérdezői oldalon a html kérés rossz encode-olása okozat (az ékezetek UTF-8 helyett ISO-8859-2-ben kerültek küldésre). 
A kódolást helyesre állítva a hibajelenség megszűnt.

Köszönjük.

**Comment by NTCA-supporter** [comment]
Ha jól látom akkor a hiba elhárult, így lezárom a ticketet.
