### ISSUE TITLE
[Q&A] ÁFA kulcsok értelmezése lenne szükséges, lehetőleg példákkal

### ISSUE THREAD

**Issue by peacefuldev** [nav-gov-hu/Online-Invoice#518]
Kedves Fejlesztők,

A 3.0-ás verzió bevezeti a kötelezően alkalmazandó ÁFA kódokat (case) és magyarázatokat (reason), amivel a lecke alaposan feladásra került. Eddig az ügyfeleink többsége olyan kódokat szerepeltetett a számlán, mint ÁHK (ÁFA trv. hatályán kívüli), most viszont jóval több opcióból kell kisilabizálni a megfelelő kódot és leírást.

Ebben szeretnénk a segítségüket kérni, mert sok mindent még a könyvelővel egyeztetve sem sikerült megfejteni.

1. A git-es issue-k átolvasása után úgy értelmezzük, hogy elegendő, ha a számlázó programunkban a felsorolt case-eket szerepeltetjük és a reason mezőben a dokumentációban szereplő leírás szerepel (116. oldal). Ezt kérem, hogy erősítsék meg.

2. Megtehetjük-e azt számlázó program fejlesztőként, hogy bizonyos kulcsokat egyszerűen nem rakunk a programba? Az ügyfeleink többsége szellemi szolgáltatást értékesít Magyarországon vagy az EU-n belül (ritka esetekben egyéb EU-n kívüli országba), mondhatjuk-e azt, hogy egész egyszerűen ezeket az ügyleteket támogatjuk, és az ehhez tartozó ÁFA kódokat visszük fel?

Ez már csak azért is praktikus lenne, mert egyrészt fix ÁFA-kódok nélkül a programot jelentősen át kellene írni (minden ÁFA kódos tételnél külön leírás mező), másrészt 15 új, eddig nem létező kód alaposan megkavarja az ügyfeleket, akik a mi szupportunknak okoznának jelentős többlet terhelést, vagy rosszabb esetben hibás kódon rögzítenék a tételeket.

3. Tudnának esetleg **példákkal** részletes magyarázatot adni az összes dokumentációban szereplő ÁFA kódhoz, és hogy tipikusan melyik esetben kell őket alkalmazni?

A korábbi issue-ekból az alábbiakat sikerült összegyűjteni, megtennék, hogy ezt kiegészítik?

KBAET: ez a klasszikus közösségi értékesítés, amikor közösségi fordított adózás van.
EUE: másik tagállamban teljesített ügylet, ami után nem a másik tagállami termékbeszerzőt, szolgáltatás igénybevevőt terheli az adófizetési kötelezettség. Fontos, hogy ez hatályon kívüli értékesítés és nem mentes, mint a KBAET.
EAM: Áfa törvény 98-109. §-ai alapján mentes ügyletek tartoznak ide (fontos, hogy ez adómentes és nem hatályon kívüli!).
HO - harmadik országban teljesített ügyletek esetében az áfa hatályán kívüli értékesítés van.

Mit jelent például az ATK és a THK, ezek mikor alkalmazandók?

vatAmountMismatch eseteihez is fontosak lennének a példák, mert nehezen tudjuk értelmezni ezt a részt.

Előre is köszönjük!

**Comment by laladisc** [comment]
Teljesen egyetéretek @peacefuldev -el. Kellene bővebb magyarázat az áfa kódokhoz, példákkal.

**Comment by DrotosTot** [comment]
A #464 ben ígéretet kaptunk, hogy a doksiba bekerül annak lehetősége, hogy a case-hez tartozó reason a NAV által megadott szövegezés legyen a tételeknél.

Arra viszont nem kaptunk megoldási javaslatot, hogyha az ügyfél saját maga kívánja megadni a reason-t és az tételenként más és más, akkor melyik reason kerüljön az összesítőbe.

Az alkalmazandó kódokat az ügyfélre bízzuk, neki kell tudni, hogy a jogszabályok alapján melyik kódot kell egy adott számlán használni.

**Comment by nbeeps2** [comment]
A reason-be a felhasználó(!) által megadott számlazáradék szöveget kell megadni (amennyiben van erre szolgáló külön mező a számlázó programban). Természetesen megteheted, hogy az ÁFA kulcsokat és case/reason-ket beégeted a programodba, de fontos, hogy 0%-esetén fel legyen tüntetve a számlán a mentesség oka, vagyis, hogy miért nem került ÁFA felszámításra. Ez egyébként mindig is így volt, legalábbis, már nagyon régóta így van.

**Comment by NTCA-tax** [comment]
A módosított interfész dokumentáció tartalmazza a példákat, így a kéréseteket teljesítettük. Amennyiben a dokumentáció alapján sem lenne valami egyértelmű, akkor azt új issue-ban beszéljük meg.
