### ISSUE TITLE
[Q&A] Lehetséges-e 0-val kezdődő adószám?

### ISSUE THREAD

**Issue by HWKF** [nav-gov-hu/Online-Invoice#519]
Miért "[0-9]{8}" a taxpayerId pattern? Lehetséges 0-val kezdődő adószám?
Lehetne ez módosítani "[1-9]{1}[0-9]{7}" pattern-re?
Például simán átcsúszik minden adószámos logikai ellenőrzésen a "00000000" taxpayerid (pattern, ellenőrző szám).
Ha viszont a kezdő 0 kizárható, akkor már azokat sem lehetne beküldeni.

**Comment by nbeeps2** [comment]
Egészítsd ki a programot a NAV online adószám ellenőrzés funkcióval (queryTaxPayer) és akkor kizárod a nem létező adószámokat. A pattern ugyanis édes kevés, mivel bármilyen 8 számot elfogad. Megfelelő 11. karakter, ellenőrzőszám mellett formailag rendes adószám, mégsem létezik.

**Comment by HWKF** [comment]
Ez szép és nagyon jó, viszont minden formai ellenőrzéshez ne kelljen webservice hívást intézni. Ez csak egy apró javaslat volt. Amit nem kéne külön intézni. 
Másrészt tényleg érdekel, hogy lehetséges-e?
Nekem az is jó, ha valaki belinkeli az adószám felépítését.
Néhány dolgot már találtam (ebben a cikkben: https://adopraxis.hu/Cikk/az-adoszam-szerepeltetese-a-szamlan)
_Az adószámot nem lehet egy véletlen generátornak tekinteni, mivel számos információt hordoz magában. Az adószám első nyolc karakterét nevezzük törzsszámnak. A törzsszám kezdete is tartalmaz lényeges információkat. Az 1-es és 2-es karakterrel kezdődő törzsszámok jellemzően társaságokat azonosítanak, a 4-es, 5-ös, 6-os karakterrel kezdődő törzsszámok egyéni vállalkozókat, 7-es karakterrel kezdődő törzsszámok pedig jellemzően adószámos magánszemélyeket. Tehát alapvetően már az adószám kezdete alapján meg tudjuk állapítani, hogy milyen gazdálkodóval állunk szemben._

**Comment by lvitya586** [comment]
Gyors guglizás után [adószám checksum](http://muzso.hu/2011/10/26/adoszam-ellenorzo-osszeg-generator):

A nyolcadik helyen álló ellenőrző-összeg számítása a következő algoritmus szerint zajlik: az adószám első hét számjegyét megszorozzuk a 9, 7, 3, 1, 9, 7, 3 sorozatból a megfelelővel (a számjegy sorszáma alapján kiválasztva a szorzót), majd ezeket összeadjuk, vesszük az összeg utolsó számjegyét és ha az nulla, akkor az lesz az ellenőrző-összeg, ha nem nulla, akkor vonjuk ki 10-ből és az lesz az ellenőrző-összeg.

Egy példa: az 1389545 törzsszám nyolcadik számjegyének kiszámítása:
az összeg képzése: 9 * 1 + 7 * 3 + 3 * 8 + 1 * 9 + 9 * 5 + 7 * 4 + 3 * 5 = 151
az összeg utolsó számjegye: 1
mivel ez nem nulla, így az ellenőrző-összeg: 10 - 1 = 9
azaz a teljes törzsszám így fog kinézni: 13895459

**Comment by HWKF** [comment]
@lvitya586 Erre akart utalni a kérdésben az ellenőrző szám. Köszönöm, de ezen túlmenően érdekelne a törzsszám, ha lehetséges.
_Például simán átcsúszik minden adószámos logikai ellenőrzésen a "00000000" taxpayerid (pattern, **ellenőrző szám**)._

**Comment by KMGY100** [comment]
@HWKF    gyanítom ez a 00000000  csak neked egyedül  jutott eszedbe.
DE ok.   Letiltom első karakterként a 0 bevitelét, illetve  LEFT( adoszam,1)  nem lehet 0
és nem engedem továbblépni.

**Comment by lvitya586** [comment]
Bocs, nem olvastam az előzményt, csak az értesítő email-re reagáltam, amiben meg ez volt:

> Ez szép és nagyon jó, viszont minden formai ellenőrzéshez ne kelljen webservice hívást intézni. 

Amúgy meg feltételezem a 00000000-t akkor lehet(ne) használni, ha nem érhető el az adószám, de kötelező kitölteni ezt az adatot. De majd valamelyik NAV-os kolléga megválaszolja.

**Comment by HWKF** [comment]
@KMGY100 Sajnos nem saját ötlet! :( Ügyfél adatbázisban találtam.
@NTCA-supporter De tényleg érdekel, hogy lehet kezdődhet-e 0-val adószám. A NAV válasza szerintem eldöntené a kérdést.

**Comment by alaplap** [comment]
Érdekességnek: Már kaptam olyan számlát magánszemélyként vásárolva, ahol az adószámom 00000000-0-00 volt a számlán. Mondta is a kasszás hölgy, hogy neki magánszemélynél ezt az adószámot kell megadni a programban, mert az adószám megadása kötelező.

**Comment by NTCA-tax** [comment]
Jelenleg nem létezik 0-val kezdődő adószám, ugyanakkor ez nem jelenti azt, hogy valamilyen előre nem látható okok miatt egy adószám nullával kezdődjön a jövőben.

**Comment by bakter80** [comment]
> Érdekességnek: Már kaptam olyan számlát magánszemélyként vásárolva, ahol az adószámom 00000000-0-00 volt a számlán. Mondta is a kasszás hölgy, hogy neki magánszemélynél ezt az adószámot kell megadni a programban, mert az adószám megadása kötelező.
beküldéskor a 9. számjegyen ez megbukna, mivel az 1-5 közötti.
további érdekesség: az 11111111, 22222222, 33333333 ... is jó törzsszámok.

**Comment by HWKF** [comment]
Az ÁFAkód és a megyekód nem kötelező eleme a beküldésnek. Csak a törzsszám kötelező.
Az 11111111-1-11-et is használom teszteléshez a tesztre beküldéshez.

**Comment by NTCA-tax** [comment]
Mivel a kérdés megválaszolásra került, ezért lezárom ezt az issue-t.
