### ISSUE TITLE
Magánszemély számlájára - WARN adószám hiány?

### ISSUE THREAD

**Issue by pvmon** [nav-gov-hu/Online-Invoice#520]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[x] /manageInvoice
**A kérés verziója / version of the request**
[x] 3.0
**A probléma rövid és tömör leírása / Clear and concise description of the problem**

Magánszemély számlájának feltöltése:
NORMAL számla esetén válasz Warn - Adószám első 8 karaktere hiányzik. Bár látszik, hogy magánszemélynek vette (pipa) a megfelelő dobozban a számla néző oldalon. :-(
SIMPLIFIED - Egyszerűsített számla esetén - ugyanolyan vevőadat tartalmú számlánál nincs WARN jelzés. :-)

**Comment by NTCA-supporter** [comment]
#515 #500 kérlek kicsit nézz körbe mielőtt új issue-t nyitsz.
Köszi!

**Comment by pvmon** [comment]
Elnézést, de nem láttam nyitottban. A zártakat meg nem néztem, Gondolván az zárt ami megoldott...Bocsi.
Köszönöm!
