### ISSUE TITLE
Lehet már tudni, mikorra várható a v3.0 éles indulása?

### ISSUE THREAD

**Issue by vectorkovacspeter** [nav-gov-hu/Online-Invoice#521]
Érdeklődnék, hogy van-e már nagyságrendileg tudható élesítési dátum a v3.0 verzióhoz?

Elég fonts lenne a rá épülő szoftverek roadmapja szempontjából.

**Comment by lukacsb** [comment]
nagyon nagy a csend ebben a témában...

**Comment by renced42** [comment]
> Érdeklődnék, hogy van-e már nagyságrendileg tudható élesítési dátum a v3.0 verzióhoz?
> 
> Elég fonts lenne a rá épülő szoftverek roadmapja szempontjából.

Kedves @vectorkovacspeter napra pontos időpontot nem tudunk még mondani a januártól hamarabbi időpontra vonatkozóan. Jogszabály szerinti indulásra számítsatok, ha attól hamarabb fogunk indulni azt is jelezni fogjuk.

**Comment by DrotosTot** [comment]
Kedves @renced42 ! Izer Norbert államtitkár úr nyilatkozatát megtudod erősíteni, hogy a 3.0-ra legkésőbb 2021. április 01-ig kell áttérni?

**Comment by szako** [comment]
@DrotosTot Forrást linkelnél? Köszi.

**Comment by DrotosTot** [comment]
@szako: Sok helyen olvastuk. Például:
https://perfekt.blog.hu/2020/09/21/a_szamlaszintu_adatszolgaltatas_valtozasai_565
https://www.grantthornton.hu/hirlevel/202009112021adatszolgaltatas
https://www.bkmkik.hu/en/news-2/economic-news/4298-uj-hatarido-a-szamlaadat-szolgaltatasban-2021-januar-1

**Comment by GabiSzamla77** [comment]
Sziasztok! A problémát és a sok kérdést az az ellentmondás is okozza, hogy a 3.0-ra áttérni elegendő lenne 04.01-jétől, miközben a jogszabályi előírások a beküldés adattartalmára már 01.04-től élni fognak (az időpont a kihirdetés előtti törvénymódosításból származik, T13258 az Országgyűlés honlapján). 
Tehát a 2.0-val kellene tudni teljesíteni a 2021-től érvényes jogszabályi előírásokat. Erre nem kapunk már jó ideje választ, hogy ez jogszerűen és/vagy technikailag megengedett-e, de várunk türelemmel. 
Tudom, ez inkább ide tartozna: https://github.com/nav-gov-hu/Online-Invoice/issues/407

**Comment by WittmannWien** [comment]
Sziasztok, Sajnos a "várunk türelemmel" nem igazán használható már november vége felé, hiszen ha 2.0-val kell január 1-től küldeni az eddig nem beküldendő számlákat (nemzetközi számlák, magánszemélyenek kiállított számlát) akkor már most kellene tudni hogyan fejleszzük a meglévő 2.0-ás megoldást, mivel ezeket ez nem tartalmazza. Ha viszont a 2.0-át nem akarja a NAV tovább fejleszteni, akkor csakis a 3.0-val lehet ezeket lejelenteni. Viszont akkor azt január 1-től kötelező lesz használni, mivel a törvényt ezt várja el. 
Nagyon nagyon hiányzik egy tiszta, egyértelmű kommunikáció a NAV-tól, hogy egész pontosan mi, mikor, hogyan lesz!!
Valójában most egyelőre mindenki abban bízik, hogy a 3.0 majd csak áprilistól lesz kötelező. Mi lesz ha nem? Mi lesz ha január 1-től kell indulni vele? Hogyan készüljünk fel egy átállásra hiteles információk hiányában? Nem beszélve arról hogy a hivatalos angol fordításra 6 hetet kellett várnunk. 
Szinte érthetetlen, hogy egy adóhivatal a 21-ik században nem tud kommunikálni megfelelő módon Magyarországon, egy olyan fontos projektben, ahol számlánként 500.000 Ft a büntetés!
Már megint mi a baj kedves NAV? Legalább 3 issue-ban várunk a válaszokra hetek óta. 

Várok (várunk) egy mielőbbi hivatalos (nem csak itt megjelenő, hanem a https://onlineszamla.nav.gov.hu/home weboldalon is kommunikált) timeline-t, ami alapján végre tudunk rendesen dolgozni/tervezni.
Nem lehet ez olyan nagy kérés, ugye? Vagy forduljunk mi is a sajtóhoz, hogy végre történjék vmi? Ezzel sincs gond, csak tudni kell.

Köszönöm szépen.
Üdvözlettel
Kovács Péter

**Comment by Macskafarka** [comment]
Eccerű. **A magánszemélyek és közösségi számlák etc.-re vonatkozó adatszolgáltatás NEM léphet életbe 2021 januárjában!**
A jogalkotásról szóló 2010. évi CXXX. tv. 2.§ (3) bekezdése:
_"(3) A jogszabály hatálybalépésének időpontját úgy kell megállapítani, hogy elegendő idő álljon rendelkezésre a jogszabály alkalmazására való felkészülésre."_
No, a kellő idő itten nincsen biztosítva, ezt mindenki látja. Se végleges v3.0 speci, se végleges XSD, egyetlen árva data példa+XML, se elfogadott törvény, de még 23/2014 NGM rendelet módosításnak sincs nyoma. Szóval ez bukó.
-én szóltam.

**Comment by Macskafarka** [comment]
A határidő eltolásához a NAV kevés, de elég a járvány miatt egy pátens is (elöljárói engedélyirat, nyílt parancs, vagy szalonképesebben: törvényerejű rendelet)

**Comment by nbeeps2** [comment]
Akkor ide is bevágom:

"AZ ÚJ KORSZAK 2021. ÁPRILIS 1-JÉN A MAGÁNSZEMÉLYEK RÉSZÉRE KIÁLLÍTOTT SZÁMLÁK BECSATORNÁZÁSÁVAL VESZI KEZDETÉT, UGYANIS AKKORTÓL VÁLIK TELJESSÉ MAGYARORSZÁGON A SZÁMLA-ADATSZOLGÁLTATÁS."
(forrás: Pénzügyminisztérium (PM) adóügyekért felelős államtitkára)

Tehát legkésőbb 2021. április 1-ig KELL áttérni a 3.0-ra, melyből egyenesen következik, hogy 2021. március 31-ig használható a 2.0-ás adatszolgáltatás a 2.0-ás érintettségi körrel. Magyarán, ha majd megjelenik a 3.0-ás XSD élesben, akkor 2021. január 1-től már küldhető MINDEN számla, de NEM KÖTELEZŐ és nem is kell ezeket utólag pótolni.

A **szankciómentes időszak** pont azt jelenti, hogy ha még jogszabály szerint, akár kötelező is lenne küldeni 2021. január 1-től minden számlát, ettől teljes mértékben eltekintek, tehát nem kell küldeni és utólag sem kell pótolni.

**Comment by Macskafarka** [comment]
Kedves @nbeeps2 ! Jó lenne ezt5 nemcsak Tőled hallani, és nem valamiféle államtitkártól, hanem hivatalosan közzétéve törvénnyel.
Ugyanis a 2021.01.01-et az ÁFA törvény mondja ki, ehhez egy ilyen bejelentés lófütty. Mindenre lehet találni egy államtitkári bejelentést.

**Comment by nbeeps2** [comment]
@Macskafarka közel két és fél éve ilyen lófüttyök alapján dolgozunk :D

**Comment by WittmannWien** [comment]
Igen én is hasonlót akartam reagálni. A politikus bármit mondhat, a törvény számít, Valamint ha akár hiteles is lenne, ez a kijelentés nem érvényes a nemzetközi számlákra, mivel azt nem említi. Szóval marad a teljes bizonytalanság továbbra is :-)

**Comment by Macskafarka** [comment]
Ott van a Parlament előtt a T/13258. számú törvényjavaslat az ÁFA tv. módosításáról. Szó van benne bármiféle moratóriumról? 
Nincs.  A törvény alól se a NAV, se egy államtitkár nem adhat felmentést.

**Comment by vectorkovacspeter** [comment]
> Akkor ide is bevágom:
> 
> "AZ ÚJ KORSZAK 2021. ÁPRILIS 1-JÉN A MAGÁNSZEMÉLYEK RÉSZÉRE KIÁLLÍTOTT SZÁMLÁK BECSATORNÁZÁSÁVAL VESZI KEZDETÉT, UGYANIS AKKORTÓL VÁLIK TELJESSÉ MAGYARORSZÁGON A SZÁMLA-ADATSZOLGÁLTATÁS."
> (forrás: Pénzügyminisztérium (PM) adóügyekért felelős államtitkára)
> 
> Tehát legkésőbb 2021. április 1-ig KELL áttérni a 3.0-ra, melyből egyenesen következik, hogy 2021. március 31-ig használható a 2.0-ás adatszolgáltatás a 2.0-ás érintettségi körrel. Magyarán, ha majd megjelenik a 3.0-ás XSD élesben, akkor 2021. január 1-től már küldhető MINDEN számla, de NEM KÖTELEZŐ és nem is kell ezeket utólag pótolni.
> 
> A **szankciómentes időszak** pont azt jelenti, hogy ha még jogszabály szerint, akár kötelező is lenne küldeni 2021. január 1-től minden számlát, ettől teljes mértékben eltekintenek, tehát nem kell küldeni és utólag sem kell pótolni.

Ez nekem nagyon szimpatikus lenne, de hol tudom ezt mint hivatalos forrás behivatkozni például az ügyfélkörnek, könyvelőknek, stb. ?

**Comment by Macskafarka** [comment]
**Szerintem a szankciómentesség mást jelent, mint az indulás elhalasztása.**
Ha nem halasztják el, akkor HIBÁZOL, ha nem teszel eleget a jogszabálynak, akkor is, ha per pillanat nem jár érte szankció.
Aztán, amikor vége a szankciómentességnek, addigra már hibáztál 445.622-ször, és ha véletlenül még egyet hibázol, akkor rád lehet fogni, hogy többszörös visszaeső hibázó vagy, ergó sokkal súlyosabb szankcióra számíthatsz.

**Comment by bakter80** [comment]
> Ott van a Parlament előtt a T/13258. számú törvényjavaslat az ÁFA tv. módosításáról. Szó van benne bármiféle moratóriumról?
> Nincs. A törvény alól se a NAV, se egy államtitkár nem adhat felmentést.

Vannak fontosabb dolgok is, az apa férfi, az anya nő, és minden elveszti közpénz jellegét, a vírus és soros miatt...

**Comment by nbeeps2** [comment]
@Macskafarka A szankciómentesség szerintem sem az indulás elhalasztása, hanem az, hogy nem büntetnek egy átmeneti időszak alatt azért, hogy nem küldöd be a magánszemélynek- és a külföldi cégeknek kiállított számlát.

**Comment by renced42** [comment]
Kedves @vectorkovacspeter 

Amennyiben nincs további kérdés kérlek zárd az issuet.
