### ISSUE TITLE
[DOC] CustomerTaxNumber töltése

### ISSUE THREAD

**Issue by GOnSzlaDev** [nav-gov-hu/Online-Invoice#522]
Az Online Szamla_interfesz specifikáció szerint a CustomerTaxNumberType mindhárom al-tag-jét csak akkor kell kitölteni, ha szerepel a számlán (81.oldal). Ehhez képest a séma szerint legalább az egyik Kötelező. Vannak belföldi adószám nélküli nem magánszemély vevők, és vannak adószám nélküli harmadik országbeli vevők. Hogy lehetne feloldani ezt az ellentmondást?

**Comment by NTCA-supporter** [comment]
Szia @GOnSzlaDev !
A customerVatData csomópont opcionális.
A hármas choice-ból egyet megadni csak akkor kötelező, ha magát a customerVatData csomópontot megképzed.
Üdv

**Comment by GOnSzlaDev** [comment]
Köszönöm!
