### ISSUE TITLE
[DOC] Közmű számla

### ISSUE THREAD

**Issue by GOnSzlaDev** [nav-gov-hu/Online-Invoice#523]
A Közmű számláknál a részszámla tag-ek szerepeltetésére a batcInvoice-ban azt mondja a leírás, hogy a modifyWithoutMaster tag értéke legyen false. (151-152.oldal) Ez a tag és ennek a false értéke azt jelenti általában, hogy úgy adunk be egy számlára módosítást, hogy az eredeti számlát már beadtuk. Vagyis itt az elszámoló számlában a részszámla hivatkozásos részt úgy kellene beadni, hogy azt jelöljük meg, hogy már be volt adva korábban a részszámla. Szerintem ez nem egyértelmű, mert elképzelhető, hogy a részszámla 202012 dátumú, és még nem volt beküldve online, az elszámolószámla pedig 202102. Mi a helyes eljárás?
Véleményünk szerint a batchInvoice-ban a utilitySettlementIndicator=false jelölésű számlánál is lehet true a modifyWithoutMaster.

**Comment by szako** [comment]
https://github.com/nav-gov-hu/Online-Invoice/issues/456

**Comment by GOnSzlaDev** [comment]
Köszönöm!
Én is így gondolom, hogy a "józan ész...", de a tegnap este kirakott doksiban ez még mindig nem látszik.  Reméljük, hogy jan.01-től már tényleg így lesz.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Köszi a jelzést. Ezt most zárom, mivel erre már van issue, lásd a belinkelt #456 
Amikor javítva lesz, fogom jelezni abban az issueban.
Üdv
