### ISSUE TITLE
3.0 verzió

### ISSUE THREAD

**Issue by GOnSzlaDev** [nav-gov-hu/Online-Invoice#524]
Mikortól kötelező használni?

**Comment by renced42** [comment]
Kedves @GOnSzlaDev 2021. január 1-től hatályba lép az Áfa törvény adatszolgáltatásokra
vonatkozó változása.
Szivesen válaszolunk mindenre, de nem volna baj, ha előtte a kapcsolódó anyagokat jogszabályi helyeket és topikokat átnézegetnéd. 
Köszi!
Kérlek zárd az issuekat.
