### ISSUE TITLE
Magánszemély - 2.0

### ISSUE THREAD

**Issue by GOnSzlaDev** [nav-gov-hu/Online-Invoice#526]
2.0 verzióval lehet magánszemélynek kiállított számlát beküldeni?

**Comment by connorhu** [comment]
A github nem cset, lehetne, hogy nem spameled végig az issue trackert egysorosokkal?

**Comment by renced42** [comment]
> 2.0 verzióval lehet magánszemélynek kiállított számlát beküldeni?

Kedved0 @GOnSzlaDev nem lehet.
