### ISSUE TITLE
[Q&A] Számlát számlával is lehet módosítani nem kell módosító okirat!

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#528]
Megtévesztők a v3.0 speci kifejezései, egyáltalán nem kell módosító okirat, ha valaki számlát akar módosítani!
Számlát számlával is lehet módosítani, a NAV kommunikációja a számlaláncolatról felülvizsgálatra szorul.
**Hozzá kell igazítani a v3.0 fogalmait, ellenőrzéseit, elvárásait , valamint a NAV kommunikációját a MEGVÁLTOZOTT jogi környezethez!**
A ma megjelent 501/2020 (XI.14.) Korm rendelet 2§ (3) pontja kifejezetten a 2020. decemberi számlában rendeli jóváírni a korábbi számlában már kiszámlázott díjat.
_"2.§ (3) Az elektronikus hírközlésről szóló törvény szerinti szolgáltató (a továbbiakban: szolgáltató) 2020. december hónapban kibocsátásra kerülő számlában az 1. § (1) bekezdése szerinti 30 nap időtartamú kedvezményt jóváírja. "_
Ebből következik, hogy most **már jogszabály írja elő azt, hogy számla módosítható számlával**, ehhez szükségtelen módosító okiratot használni.

**Comment by Macskafarka** [comment]
A fentiekből következően negatív számla is előállhat, amire viszont WARN-t kapunk.
A jogszabályoknak megfelelő számlára WARN küldése megtévesztő, főleg veszélyhelyzetben.
Mindig oda lyukadunk ki, hogy van negatív számla, és az a nem normális, ahogy a NAV WARN-t küld rá. 
**Meg kellene békélni azzal a NAV-nak, hogy van negatív számla.**
Megjegyzem a negatív számlát nem tudja kezelni az ÁFA bevallás xx65M-02 lapja sem, az is korrekcióra szorul..

**Comment by EnokhSys** [comment]
@Macskafarka szerintem engedd el. Én is ezt tettem, mert amint korábban írtam, leveleztem velük egy sort, és eszük ágában sincs betiltani, csupán egy figyelmeztetéssel ijesztgetnek. Amúgy meg, abból a szempontból igaza van a NAV-nak, hogy minden olyan számlamódosítás amelynél konkrétan beazonosítható az eredeti ügylet, ott hivatkozni kell az eredeti számlára, és csak azokban az esetekben van helyet a negatív számlának, amikor mindkét fél önálló ügyletnek tekint valamilyen korábbi ügyletből származó áru visszaszállítást/jóváírást.

**Comment by renced42** [comment]
Kedves @Macskafarka 

Kérlek ezt ezt olvasd el elég jól le van írva.
https://ado.hu/szamvitel/kibovult-adatszolgaltatas-mire-figyeljunk-az-m-lapok-kitoltese-soran-iii-resz/

Mivel ez adózási témájú kérdés és nem fejlesztői/informatikai, kérlek zárd az issuet.

Köszönöm szépen!

**Comment by Macskafarka** [comment]
@renced42 Ismertem ezt korábban is. Az áll benne, hogy nem lehet negatív alapszámla. Ami az általam idézett friss jogszabály alapján elavult nézetté vált, Csak jelezni akartam, hogy a NAV által képviselt álláspont tarthatatlan, életszerűtlen.
De megértettem: jogszabálynak megfelelő, sőt kifejezetten előírt  számlára is WARN-t küld a NAV.

**Comment by EnokhSys** [comment]
@renced42 én is elolvastam a cikket, szép kis zöldségek szerepelnek az utolsó fejezet környékén. Kicsit olyan, mint amikor a cikk szerzője összeszorított fogakkal döfködi magát egy golyóstollal, hogy valahogy kipréselje ezt a nyakatekert magyarázatokat. :-))

**Comment by Macskafarka** [comment]
Ez áll a cikkben: "A negatív irányú elszámolást tehát számlával egy tekintet alá eső okirattal kell elvégezni, amelynek az adatait a 2065M-02-K lapon kell szerepeltetni."
Az általam jelzett rendelettel viszont ez az állítás nyilvánosan, rútul-nyomorultul megbukott.
Ideje lenne levonni a konzekvenciákat, hogy a NAV eddigi álláspontja a negatív számlákról tarthatatlan. 
A NAV, mint jogalkalmazó nem mehet szembe a hatályos jogszabályokkal.

**Comment by Macskafarka** [comment]
Eddig mondhatta a NAV a saját álláspontját a számla módosításáról, meg a negatív számláról, azonban most már a jogalkotó RENDEZTE ezt a kérdést, a jogszabály hatályba lépett.
Számlát számlával lehet és KELL módosítani, a módosítás eredménye lehet negatív is.

**Comment by EnokhSys** [comment]
@Macskafarka az általad említett rendeletben lehet pusztán egy figyelmetlenség is, és mivel csak egy rendeletről van szó, azt könnyen korrigálhatják és kicserélhetik a "számla" kifejezést "számlával egy tekintet alá eső okirat" kifejezéssel.

Itt azt kell szem előtt tartani, hogy a jogrendszer olyan mint egy karácsonyfa: fentről, a csúcsból indul az Alkotmánytól, és lefelé ágazik szét. A lent lévő ágak nem akadályozhatják a fentebb lévő ágakat. Jelen esetben a PTK erősebb. Hiába tiltja be egy alsóbb ágon (pl. ÁFA tv.) a jogalkotó, vagy egy még alsóbb ágon a NAV (pl. egy határozatban) az önálló ügyletű negatív számlák alkalmazását, ha az olyan kényszerhelyzetet teremt egy vállalkozói szerződésben, hogy a felek szabad akaratát csorbítja, akkor azt nem lehet alkalmazni.
Magyarul: bevezetheti az országgyűlés vagy a NAV, az önálló ügyletű negatív összegű számlák globális tiltását, de csak akkor, ha olyan alternatívát mutat a vállalkozásoknak, hogy a szerződéskötés szabadságát ne sértse. Ilyet pedig nem tud-, és logikusan végiggondolva a folyamatot, nem is fog tudni mutatni.
