### ISSUE TITLE
A Magyar Telekom Nyrt.-re nem vonatkozik a 4 napos számla jelentési határídö?

### ISSUE THREAD

**Issue by celeburdi** [nav-gov-hu/Online-Invoice#529]
A nekünk küldött Magyar Telekom havi számlán a kiállítás dátuma:
2020.11.05

A számla lejelentés dátuma (InsDate):  2020-11-12

Ez ugye több mint 4 nap.

Ez így szabályos, ha nagy mennyiségű számlát kell feladni és a feladások nem férnek bele a 4 napba?

**Comment by Macskafarka** [comment]
Számlatömbbel számláztak? **Kizárólag a nyomdai úton előállított számlára van 4 nap türelmi idő.**
Ha számlázó programmal számláztak, akkor haladéktalanul kell adatot szolgáltatniuk, kivéve, ha igazolják, hogy rajtuk kívülálló ok miatt nem voltak képesek. Pl. nem volt internetjük, és a bizonyítékokat elő kell tárniuk. 
Az internetre is csak akkor hivatkozhatnak, ha nem nekik felróható, pl. másik szolgáltató biztosítja az internet elérést a részükre, ami a Telekom esetében érdekes lenne.

**Comment by celeburdi** [comment]
Igazad van. A 4 nap csak a kézi számlákra vonatkozik.
A számlázó programnál mennyi lehet az "elfogadott" türelmi idő?

**Comment by nbeeps2** [comment]
@celeburdi 24 óra

**Comment by renced42** [comment]
Kedves @celeburdi 

Ez nem fejlesztői kérdés kérlek zárd az issuet.
Köszönöm szépen!

**Comment by Macskafarka** [comment]
Igaza van @renced42 -nek, az, hogy ki mit tehet meg a jogszabályok ellenére, és azt miért tűrik meg az nem fejlesztői kérdés.

**Comment by alaplap** [comment]
> 
> 
> Igaza van @renced42 -nek, az, hogy ki mit tehet meg a jogszabályok ellenére, és azt miért tűrik meg az nem fejlesztői kérdés.

Még az sem biztos, hogy tűrik.

**Comment by NTCA-tax** [comment]
Konkrét adózónak esetleges adatszolgáltatási hiányosságaira, problémáira nem fogunk válaszolni, véleményt nyilvánítani. Amennyiben felmerül az adóhivatali oldalon bármilyen adatszolgáltatási aggály bármely adózóval kapcsolatban, azt közvetlenül az adózóval beszéljük meg, nem pedig fórumon keresztül.
