### ISSUE TITLE
[DEV support] tokenExchange 500-as hiba(?)

### ISSUE THREAD

**Issue by kasza68** [nav-gov-hu/Online-Invoice#530]
Tisztelt Nav Fejlesztés!

Fejlesztői környezeten próbálom kiépíteni a kapcsolatot, egy új számlázó és az NAV online számla rendszere között, de sajnos sikertelenül.  Nem tudom én rontok-e el  valamit vagy esetleg központi hiba van-e teszt api-n, de folyamatosan 500-as (internal server error) választ kapok. A doksi szerint ezt szinkron hívásnál kellene csak kapnom, de az egész logika aszinkron működésen alapul, illetve a leírás még azt javasolja, hogy próbáljam újra több alkalommal, de ez sem vezetett eredményre (ugyan azzal a requestId-val sem).

Bemásolok  1-1 példát (a bemásolt kérés / válasz nem összetartozó pár, de miden esetben ezt ua. küldtem be és kaptam vissza, csak a header paraméterek térnek el  [requestId, timestamp])

**Küldött kérés:**
<?xml version='1.0' encoding='UTF-8'?><ns2:TokenExchangeRequest xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common"><header><requestId>95327b2b7ecd47cc908c3d576d659</requestId><timestamp>2020-11-15T20:23:17.413Z</timestamp><requestVersion>3.0</requestVersion><headerVersion>1.0</headerVersion></header><user><login>i2anju6buvdgrnk</login><passwordHash cryptoType="SHA2-512">da310c12a150757c620078f44584093c988c1d369440bf7ad31c4a3b5112777c0047d4cfbf66cf7f74a096db0d9a5dfd785e5a6fedc830f08e774f1461c86286</passwordHash><taxNumber>68871378</taxNumber><requestSignature cryptoType="SHA3-512">b38f001ca484354bdaf225f072a0b2c15abcb87957cc92686ebcda072fb2ab228e2ac70b297ce1fd37d4d8d318d9736c06554afcd79c5122ee928f566807c8a6</requestSignature></user><ns2:software><ns2:softwareId>HU19910324ELTEDIPL</ns2:softwareId><ns2:softwareName>Számla Világ (Szakdolgozat)</ns2:softwareName><ns2:softwareOperation>ONLINE_SERVICE</ns2:softwareOperation><ns2:softwareMainVersion>0.0.1-SNAPSHOT</ns2:softwareMainVersion><ns2:softwareDevName>Kaszás Zsolt</ns2:softwareDevName><ns2:softwareDevContact>924553428</ns2:softwareDevContact><ns2:softwareDevCountryCode>HU</ns2:softwareDevCountryCode><ns2:softwareDevTaxNumber>68871378</ns2:softwareDevTaxNumber></ns2:software></ns2:TokenExchangeRequest>

**Kapott válasz:**
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns2:GeneralErrorResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data"><header><requestId>b72c5c2297da49799b0b8d02ee19c</requestId><timestamp>2020-11-15T20:04:42.106Z</timestamp><requestVersion>3.0</requestVersion><headerVersion>1.0</headerVersion></header><result><funcCode>ERROR</funcCode><errorCode>OPERATION_FAILED</errorCode><message>Feldolgozás sikertelen!</message></result><ns2:software><ns2:softwareId>HU19910324ELTEDIPL</ns2:softwareId><ns2:softwareName>Számla Világ (Szakdolgozat)</ns2:softwareName><ns2:softwareOperation>ONLINE_SERVICE</ns2:softwareOperation><ns2:softwareMainVersion>0.0.1-SNAPSHOT</ns2:softwareMainVersion><ns2:softwareDevName>Kaszás Zsolt</ns2:softwareDevName><ns2:softwareDevContact>924553428</ns2:softwareDevContact><ns2:softwareDevCountryCode>HU</ns2:softwareDevCountryCode><ns2:softwareDevTaxNumber>68871378</ns2:softwareDevTaxNumber></ns2:software></ns2:GeneralErrorResponse>

Előre is köszönöm a segítséget.

**Comment by NTCA-supporter** [comment]
Keves @kasza68!

Az a gond, hogy a passwordHash értékét uppercase-elni kell. Ugyanez igaz a requestSignature értékére is.

**Comment by kasza68** [comment]
Kedves @NTCA-supporter !

Az Ön által javasolt megoldást valóban orvosolta a hibát, de ez azonnal egy másik hibához vezetett:
INVALID_REQUEST_SIGNATURE

Több formában ellenőriztem, az általam előállított SHA3-512-es hash-t és jónak tűnik. 
HASH: B38F001CA484354BDAF225F072A0B2C15ABCB87957CC92686EBCDA072FB2AB228E2AC70B297CE1FD37D4D8D318D9736C06554AFCD79C5122EE928F566807C8A6

Mi lehet a probléma?

**Comment by dancixx** [comment]
Tisztelt NAV!

Postmanben próbálok token requestet indítani a https://api-test.onlineszamla.nav.gov.hu/  endpointra, de folyamatosan 500 errort kapok. Minta kód plusz a technikai felhasználó adataival próbálkoztam de eddig eredménytelenül. A https://api-test.onlineszamla.nav.gov.hu/tokenExchange-re pedig 404-et kapok.

```
<?xml version="1.0" encoding="UTF-8"?>
<TokenExchangeRequest xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns="http://schemas.nav.gov.hu/OSA/3.0/api">
	<common:header>
		<common:requestId>RID896801578450</common:requestId>
		<common:timestamp>2020-11-21T10:55:31.440Z</common:timestamp>
		<common:requestVersion>3.0</common:requestVersion>
		<common:headerVersion>1.0</common:headerVersion>
	</common:header>
	<common:user>
		<common:login>mm6yehu3vw2hw4u</common:login>
		<common:passwordHash cryptoType="SHA2-512">A69C4DB4ABD90DDABF2D0B3D563B2855D7FF0A05E3FBD1224C257F26CACB5CAF3CCCB6DCFF36899E95D890E7ECA8B190614C30C2F2A93B3ECE8DAD35FADE108A</common:passwordHash>
		<common:taxNumber>24142126</common:taxNumber>
		<common:requestSignature cryptoType="SHA3-512">BFD134339BC9FA7DDB81EE09376ACA23674523FB8ABBE08F4D960845BEAA96FC157823493C4CCABA0A83FF73957718E56528D454D56A721D151C8D57513D6B7B</common:requestSignature>
		<!--<signKey>ac-ac3a-7f661bff7d342N43CYX4U9FG</signKey>-->
	</common:user>
	<software>
		<softwareId>123456789123456789</softwareId>
		<softwareName>string</softwareName>
		<softwareOperation>LOCAL_SOFTWARE</softwareOperation>
		<softwareMainVersion>string</softwareMainVersion>
		<softwareDevName>string</softwareDevName>
		<softwareDevContact>string</softwareDevContact>
		<softwareDevCountryCode>HU</softwareDevCountryCode>
		<softwareDevTaxNumber>string</softwareDevTaxNumber>
	</software>
</TokenExchangeRequest>
```

Köszönöm a segítséget.

**Comment by renced42** [comment]
Kedves @dancixx kérlek olvasd el a specifikációban a környezetek elérhetőségét a 6. Fejezetben. Nem jó url-re postolod a kérést.

**Comment by dancixx** [comment]
Szuper köszi. Ez közben megoldódott, viszont ha az XML-aláríró kulcsot SHA3-512 hashelem invalid request signature errort kapok, itt mi lehet gond?

**Comment by kasza68** [comment]
> 
> 
> Szuper köszi. Ez közben megoldódott, viszont ha az XML-aláríró kulcsot SHA3-512 hashelem invalid request signature errort kapok, itt mi lehet gond?

Szia, látatlanban az mondanám,  hogy nem jól csinálod és csak az aláíró kulcsot hash-eled, de a következőt csináld:
Konkatenáld a requestId-t +  timestamp-et (de mindenféle elválasztás nélkül a másodpercig bezárólag pl 20201121122010) + Aláírókulcs és ezt a masszát hash-eld le és küld be.

Remélem tudtam segíteni.

**Comment by dancixx** [comment]
Szia, manageInvoice operation-nél láttam, hogy így kell de vajon az összes többinél is?

**Comment by kasza68** [comment]
> 
> 
> Szia, manageInvoice operation-nél láttam, hogy így kell de vajon az összes többinél is?

Igen ez a logika érvényes az összes aláírásra.

**Comment by dancixx** [comment]
Szerinted egy külső számlázót érdemesebb közvetlen a navra kötni vagy inkább egy működő magyar számlázóra kimondottan a Stripe-ra gondolok?

**Comment by kasza68** [comment]
Én a helyedben, fognék egy már Magyarországon működő számázót aminek van pl. egy restApi  interface-e amin be tudod küldeni a számlákat. Egy kvázi új saját számlázót létrehozni sok idő  és folyamatosan követned kell a változásokat (szerintem felesleges költség, még akkor is ha te fejleszted).

**Comment by kasza68** [comment]
> 
> 
> Szerinted egy külső számlázót érdemesebb közvetlen a navra kötni vagy inkább egy működő magyar számlázóra kimondottan a Stripe-ra gondolok?

Én a helyedben, fognék egy már Magyarországon működő számázót aminek van pl. egy restApi  interface-e amin be tudod küldeni a számlákat. Egy kvázi új saját számlázót létrehozni sok idő  és folyamatosan követned kell a változásokat (szerintem felesleges költség, még akkor is ha te fejleszted).
