### ISSUE TITLE
INVALID_ANNULMENT_REFERENCE

### ISSUE THREAD

**Issue by kurucza** [nav-gov-hu/Online-Invoice#531]
Sziasztok,

Segítségetek kérem Annulment kérdésben.
Tranzakciós ID: 365Y74JY4ZEK7C2C
Egy már DONE státusszal beküldött számla annulálásakor ABORTED státusszal érkezik vissza a számlánk a következő hibaüzenettel:

`The technical annulment pertains to a document for which no data was provided`

`<annulmentReference>` értéke helyesen van megadva, egy már sikeresen beküldött számlára hivatkozunk.
Az eredeti beküldés Tranzakciós IDja:2YAFSD1NM58R1XJV

Megnéztük a sikeres 3.0 számla beküldést és 2.0ként beküldött számla annulálását is. Ugyanaz a hiba jelentkezik mind a 2 esetben.
Légyszíves segítsetek nekünk abban, hol lehet a hiba.

Nagyon szépen köszönjük a segítséget!

Andi

**Comment by Amn3s1a2018** [comment]
Nekem volt hasonló még az 1.0-ban. Egy ottfelejtett space okozta a számlaszám végén

**Comment by NTCA-supporter** [comment]
Szia @kurucza !

A beküldött számlád invoiceNumber értéke '90045021  '.
Van két szóköz a számok után.
Az annulmentben pedig szóközök nélkül küldted be, ezért nincs találat.
Üdv

**Comment by Amn3s1a2018** [comment]
Nemtudom hány ilyen volt eddig, de esetleg érdemes lenne (lett volna) megfontolni, hogy a struktúra ne is engedjen whitespace karaktert a számlaszám elején/végén. Már csak azért, mert pl. a kinyomtatott számlán (vagy a webes felületen) ez nem is látszik.
