### ISSUE TITLE
[Q&A] INVALID_EXCHANGE_TOKEN hibaüzenet ManageInvoiceRequest híváskor

### ISSUE THREAD

**Issue by imanzuk** [nav-gov-hu/Online-Invoice#532]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

A ManageInvoiceRequest API hívás ugyanazzal az adatcsomaggal először INVALID_EXCHANGE_TOKEN hibát adott, majd hiba nélkül lefutott. Mi lehetett az oka? Az eset az éles környezetben jelentkezett, 2020.11.12-én. Az első hívás 14:00-kor, a második 21:29-kor történt.

**Comment by DrotosTot** [comment]
Szia, itt csak a tesztrendszer hibáival foglalkoznak, az éles rendszerrel kapcsolatos észrevételeket ezen az elérhetőségeken lehet jelezni: 
"Az adatszolgáltatási kötelezettséggel, a regisztrációval kapcsolatban több csatornán is kérhet segítséget:

a NAV Infóvonalán, a 1819-es telefonszámon, a 7. menüpont kiválasztásával (1. almenüpont – Segítségnyújtás Online Számla regisztrációhoz, 2. almenüpont – Jogszabály értelmezése, 3. almenüpont – Informatikai segítségnyújtás, 4. almenüpont – NAV Online Számlázó program használatával kapcsolatos segítségnyújtás)
írásban a https://www.nav.gov.hu/nav/e-ugyfsz/e-ugyfsz.html elérési úton a levélküldés funkciónál a „Számla adatszolgáltatás, jogértelmezési kérdések” vagy a „Számla adatszolgáltatás, informatikai problémák ÉLES környezetben”, illetve az „Online Számlázó informatikai problémák ÉLES környezetben” tárgy kiválasztásával."

**Comment by imanzuk** [comment]
@DrotosTot Köszönöm, zárom.
