### ISSUE TITLE
[Q&A]Végszámla devizás előleggel

### ISSUE THREAD

**Issue by burnyo** [nav-gov-hu/Online-Invoice#534]
Tisztelt NAV!

A végszámla küldésekor a devizás előlegsort eddig az előlegszámlán szereplő árfolyammal számított forintértékkel küldtük, és erre WARNING érkezett, mert a végszámla árfolyamával számított értéket vár tudomásunk szerint (nem is volt lehetőség más árfolyamot megadni). Tudom, hogy ez egy többször körbejárt történet, azonban az új 3.0 sémában megjelentek azok az új mezők, amelyekkel megadható az előlegszámla eredeti árfolyama és időpontja (advancePaymentData/advancePaymentDate, advancePaymentData/advanceExchangeRate).  
Ezen mezők feltöltése után is pontosan ugyanazokat a figyelmeztetéseket kapjuk, mint a 2.0-ban, ezért azt szeretném kérdezni, hogy pontosan milyen szerepe van ezen új mezőknek, várható-e, hogy figyelembe veszi a rendszer ezek értékét az ellenőrzések során.
Egy példa transactionid: 368W6CR6M14HEK1M

**Comment by NTCA-tax** [comment]
A végszámlánál az előleg számla összegeit a végszámla árfolyamával kell átszámolni. Ezt az interfész specifikáció is tartalmazza. Az áfa törvény változása is ezt támasztja alá, mivel a külföldi pénznemben kiállított számla összegeit az adóalap számításhoz használt árfolyammal kell megadni forintban. De ettől természetesen nem változik meg az előlegszámla adókötelezettsége, itt egy számla adatszolgáltatásánál használt árfolyamról beszélünk.

Az általad is említett felvetések alapján képeztük meg a sémában az advanceExchangeRate-et. Így amennyiben fontos a végszámla adatszolgáltatásánál az előleg számla árfolyama, akkor itt megadható. De ettől függetlenül az exchangeRate-el kell átszámolni az összeg adatokat.

**Comment by NTCA-tax** [comment]
Ezt az issue-t lezárom, ha lenne még kérdés, akkor új issue-ban beszéljük meg.
