### ISSUE TITLE
[Q&A] közösségen belüli szolgáltatásnyújtás

### ISSUE THREAD

**Issue by janisoft** [nav-gov-hu/Online-Invoice#535]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

A közösségen belüli szolgáltatásnyújtást is KBAET ÁFA kóddal kell benyújtani?
A dokumentációban a kód leírásában csak termékértékesítés van.

**Comment by NTCA-tax** [comment]
Nagy eséllyel az EUFAD37 lesz, amennyiben adóalany a vevő. A módosított interfész specifikációban részletes magyarázatot adtunk az egyes kódokra, ezért ezt az issue-t lezárom. Amennyiben a magyarázat elolvasását követően sem lenne valami egyértelmű, akkor új issue-t nyissunk erre.
