### ISSUE TITLE
[Q&A] Token kérés válasz XML validáltatási hiba XSD 3.0

### ISSUE THREAD

**Issue by samuferenc** [nav-gov-hu/Online-Invoice#536]
Env: Teszt

Hasonló hibát szeretnék jelezni mint a invoiceDigestResult esetén #488
Csak ezúttal a **QueryTransactionListResponse** esetében. Ha nincs eleme a listának akkor az **availablePage** megsérti a megszorítást, **0-ás** érték szerepel az xml-ben.

Egy hasonló hiba a token kérésnél is előfordul.
**TokenExchangeResponse** esetében a válaszban a **tokenValidityFrom** és **tokenValidityTo** **InvoiceTimestampType** típusú, viszont a kapott érték ennek nem megfelelő formátumú '**2020-11-20T08:45:53.783+01:00**'

Az ilyen jellegű hibákat össze lehet gyűjteni akár ezen issue alatt, vagy inkább nyissunk mindíg újat?

**Comment by NTCA-supporter** [comment]
Szia @samuferenc!

Az első hibát a  #488 jelzett megoldás, ezt is meg fogja oldani. 

A TokenExchangeResponse valóban nem tökéletes. Köszi a jelzést. 
Hogy minden ilyen jelzés biztosan ne vesszen el inkább nyissatok újat. Ez akkor legyen a TokenExchangeResponse hiba.

**Comment by NTCA-supporter** [comment]
Szia @samuferenc!

A mai teszt release-l ez a javítás is kiment. Kérlek nézd meg és ha rendben van akkor zárd le az issuet. Köszi
