### ISSUE TITLE
[DEV support]

### ISSUE THREAD

**Issue by lakatoskevin** [nav-gov-hu/Online-Invoice#537]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageInvoice

**A kérés verziója / version of the request**
[] 3.0

**A requestId értéke / requestId value**
```
CIBQQCLFUH20201120102835
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Sziasztok! A fentebbi request ID-vel jelölt ManageInvoiceRequest miért tekinthető hibás kérelemnek? (400-at kaptam rá)

Most a fejlesztés során nem tudom a úgy a saját módszerem szerint validálni az XML-eket XSD alapján mint a 2.0 esetében, ezért titeket kérdeznék azzal kapcsolatosan, hogy egyrészt miért hibás a kérelem, másrészt hogy tudom önállóan validálni az általam generált XML-eket XSD alapján, hogy ne mindig titeket kelljen zavarnom?

*Egyéb tartalom / Additional content*

**Comment by NTCA-supporter** [comment]
Szia!

Az a gond, hogy a kérésben nem adtál meg exchangeToken-t.

**Comment by lakatoskevin** [comment]
Bocsánat, már a Token kérés sem működik. A token exchange request azonosítója: "0C477ZZLRS2020112312044"

A hibaüzenet pedig a következő: "A [Begin]GetResponse hívása előtt ContentLength számú bájtot kell írnia a kérelemfolyamba."

Ez nem csak azért érdekes mert a kódban amit írtam ez konkrétan benne van, hanem mert ez korábban működött. Nem csak a korábbi verziókban, hanem most a v3.0 fejlesztése során a teszteknél is ment.

**Comment by NTCA-supporter** [comment]
Szia @lakatoskevin !
A tokenkérést amit említesz, mikor küldted be?
0C477ZZLRS2020112312044

köszi

**Comment by lakatoskevin** [comment]
2020.11.23. 13:00:46 -kor

**Comment by NTCA-supporter** [comment]
Kérlek másold be ide az xml-t, amit küldesz a token exchange-nél, mert a logban semmit nem látok. Nekem működik hibátlanul a tokenexchange, ezért kliens oldali hibára tippelek.
Teszt környezet ugye? Az xml-ből szedd ki kérlek a szenzitív adatokat.
Köszi

**Comment by lakatoskevin** [comment]
<TokenExchangeRequest xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns="http://schemas.nav.gov.hu/OSA/3.0/api">
<common:header>
<common:requestId>0C477ZZLRS2020112312044</common:requestId>
<common:timestamp>2020-11-23T11:00:44.000Z</common:timestamp>
<common:requestVersion>3.0</common:requestVersion>
<common:headerVersion>1.0</common:headerVersion>
</common:header>
<common:user>
<common:login>SzenzitivLoginnev</common:login>
<common:passwordHash cryptoType="SHA2-512">7D1BC99D91C1715FE26D6F569BCADF71DA797CA2C1355EB7061F0D6AF31E1D35FE1599D1CCF28CD377999CF9EEB4AD45A426995F53FF270A96D63644C366CBAC</common:passwordHash>
<common:taxNumber>123456789</common:taxNumber>
<common:requestSignature cryptoType="SHA3-512">4B867F167F5D9C4842F721071A6F392980DCFF140B0D6DE78F2B24A350F761106A83D764D82DE027EDB2D568DB9C45DBE02BFF5748B6EEC0EF9986844500E007</common:requestSignature>
</common:user>
<software>
<softwareId>HARIBOONLINESZLAV2</softwareId>
<softwareName>SZENZITÍV ONLINE SZÁMLA SZOFTVER</softwareName>
<softwareOperation>LOCAL_SOFTWARE</softwareOperation>
<softwareMainVersion>3.0</softwareMainVersion>
<softwareDevName>SZENZITÍV CÉG KFT.</softwareDevName>
<softwareDevContact>szenzitiv@emailcim.com</softwareDevContact>
</software>
</TokenExchangeRequest>

**Comment by lakatoskevin** [comment]
`<TokenExchangeRequest xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns="http://schemas.nav.gov.hu/OSA/3.0/api">
<common:header>
<common:requestId>0C477ZZLRS2020112312044</common:requestId>
<common:timestamp>2020-11-23T11:00:44.000Z</common:timestamp>
<common:requestVersion>3.0</common:requestVersion>
<common:headerVersion>1.0</common:headerVersion>
</common:header>
<common:user>
<common:login>SzenzitívLoginnév</common:login>
<common:passwordHash cryptoType="SHA2-512">7D1BC99D91C1715FE26D6F569BCADF71DA797CA2C1355EB7061F0D6AF31E1D35FE1599D1CCF28CD377999CF9EEB4AD45A426995F53FF270A96D63644C366CBAC</common:passwordHash>
<common:taxNumber>10540703</common:taxNumber>
<common:requestSignature cryptoType="SHA3-512">4B867F167F5D9C4842F721071A6F392980DCFF140B0D6DE78F2B24A350F761106A83D764D82DE027EDB2D568DB9C45DBE02BFF5748B6EEC0EF9986844500E007</common:requestSignature>
</common:user>
<software>
<softwareId>SzenzitívSoftwareID</softwareId>
<softwareName>Szenzitív Software Név</softwareName>
<softwareOperation>LOCAL_SOFTWARE</softwareOperation>
<softwareMainVersion>3.0</softwareMainVersion>
<softwareDevName>Szenzitív Cég KFT.</softwareDevName>
<softwareDevContact>szenzitiv@email.com</softwareDevContact>
</software>
</TokenExchangeRequest>`

**Comment by lakatoskevin** [comment]
`<TokenExchangeRequest xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns="http://schemas.nav.gov.hu/OSA/3.0/api">
<common:header>
<common:requestId>0C477ZZLRS2020112312044</common:requestId>
<common:timestamp>2020-11-23T11:00:44.000Z</common:timestamp>
<common:requestVersion>3.0</common:requestVersion>
<common:headerVersion>1.0</common:headerVersion>
</common:header>
<common:user>
<common:login>Gpp0EHUFc4KqxlE</common:login>
<common:passwordHash cryptoType="SHA2-512">7D1BC99D91C1715FE26D6F569BCADF71DA797CA2C1355EB7061F0D6AF31E1D35FE1599D1CCF28CD377999CF9EEB4AD45A426995F53FF270A96D63644C366CBAC</common:passwordHash>
<common:taxNumber>123456789</common:taxNumber>
<common:requestSignature cryptoType="SHA3-512">4B867F167F5D9C4842F721071A6F392980DCFF140B0D6DE78F2B24A350F761106A83D764D82DE027EDB2D568DB9C45DBE02BFF5748B6EEC0EF9986844500E007</common:requestSignature>
</common:user>
<software>
<softwareId>SZENZITIVADAT</softwareId>
<softwareName>Szenzitiv SZOFTVER</softwareName>
<softwareOperation>LOCAL_SOFTWARE</softwareOperation>
<softwareMainVersion>3.0</softwareMainVersion>
<softwareDevName>SZENZITIV KFT.</softwareDevName>
<softwareDevContact>szenzitiv@email.com</softwareDevContact>
</software>
</TokenExchangeRequest>`

**Comment by lakatoskevin** [comment]
Amúgy igen, teszt környezet.

**Comment by NTCA-supporter** [comment]
Szia @lakatoskevin !
Köszi az infot.
Közben jött más jelzés is, hogy vannak szolgáltatáskimaradások teszt környezeten. Várjuk meg annak eredményét, szerintem utána a te részed is megoldódik.
Üdv

**Comment by lakatoskevin** [comment]
Oké, rendben. Ha nem gond addig ne zárjuk le ezt az issue-t.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ez az issue zárható? Van még kérdés?
Üdv

**Comment by lakatoskevin** [comment]
Sziasztok! Igen, zárható az issue.
