### ISSUE TITLE
[FEATURE] lejárati idő a conventionalinfoban

### ISSUE THREAD

**Issue by janisoft** [nav-gov-hu/Online-Invoice#538]
**Az igény összefoglalása / Summary of the request**
Rövid és tömör leírása a problémának, amiből az igény származik. / A clear and concise description of what the problem is, from which the request arises.

A kiegeszito adatokba a termek lejarati idot javaslom felvenni.

Janos

**Comment by NTCA-tax** [comment]
Ezt conventionalInfo-ba nem raktuk bele, de ha szükséges, akkor additionalData-ként megadható.
