### ISSUE TITLE
[DEV support] XSD calatog usage

### ISSUE THREAD

**Issue by LeeMcMahon** [nav-gov-hu/Online-Invoice#539]
Hi,

This is my first post on Github; I have a question with regards to the new new XSD (Version 3.0). We are currently using tooling to map invoices to the required XML (Altova).

However, when I open the new 3.0 XSD to see what changes I need to make I receive a few errors which I am not sure about

![image](https://user-images.githubusercontent.com/74786379/99826566-d4aa9e80-2b58-11eb-8cc6-69e465cbb600.png)

Any point in the right direction would be appreciated.

Thanks

**Comment by renced42** [comment]
Dear @LeeMcMahon 

In 3.0 version we modularized the XML schema files. 
These changes are described in https://github.com/nav-gov-hu/Online-Invoice/blob/master/src/schemas/nav/gov/hu/OSA/CHANGELOG_3.0.md (English part in the second part)

However if you use Altova XML Spy you have to set your catalog.xml file

The windows version of Altova looking for a catalog.xml on path "Program Files(x86)/Altova/Common%version number%/Schemas/altova" or "Program Files/Common%version number%/Schemas/altova".
If you don't have that catalog file, just create one or edit the existing one. It is work with local or Internet resurce.

For example:
<uri name="http://schemas.nav.gov.hu/NTCA/1.0/common" uri="./files/NTCA/Common/common.xsd"/>
<uri name="http://schemas.nav.gov.hu/OSA/3.0/base" uri="./files/OSA/Invoice/invoiceBase.xsd"/>


If you change the catakog file close and restart the program because it is caching the file content. If your catalog file is correct, the xsd schema validation will be run perfectly. 

If you don't want to use the catalog.xml solution, you must be set the schemalocation (with right path) attributes inside the import tags just like 
down below:

<xs:import namespace="http://schemas.nav.gov.hu/NTCA/1.0/common" schemaLocation="common.xsd"/>
<xs:import namespace="http://schemas.nav.gov.hu/OSA/3.0/base" schemaLocation="invoiceBase.xsd"/>

**Comment by LeeMcMahon** [comment]
Hi,

Thank you for the speedy response. I have tried to go with the solution of adding the catalog.xml to the location you described. I have added the file (which was included the OSA schemas download from the NAV website)in this location;

![image](https://user-images.githubusercontent.com/74786379/100119117-cd480580-2e76-11eb-943a-24184af619ca.png)

unfortunately I am still get getting the same results when opening the XSD.

Lee

**Comment by NTCA-supporter** [comment]
Hi Lee!

Did you change the uri values in the file? You have to set your own valid path to these files.

Br

**Comment by renced42** [comment]
Dear @LeeMcMahon I forgot a step, sorry.

You must set the correct path of the uri attibute (where as the xsd files can be found) value in the catalog.xml

For example: 
![image](https://user-images.githubusercontent.com/44041065/100122852-30876700-2e7a-11eb-8bc9-03db445fe1c2.png)

or this

![image](https://user-images.githubusercontent.com/44041065/100123190-8825d280-2e7a-11eb-8142-037c925624ee.png)

**Comment by LeeMcMahon** [comment]
Hi @renced42,

Thanks for the support but again I am still struggling.

I have tried all 3 of you suggestions above but nothing seems to work, I guess I am missing something simple, this is now my catalog.xml;
![image](https://user-images.githubusercontent.com/74786379/100357423-f5f60980-2ff4-11eb-930a-b87e950cf4f3.png)

I would like to user the option of validating against the github url if possible but when I open the "InvoiceData.XSD" in XMLSpy for example I still get the blow errors;

![image](https://user-images.githubusercontent.com/74786379/100357690-4ff6cf00-2ff5-11eb-9e24-c595c5ff40a6.png)

When I try to use in Mapfore I get the below;

![image](https://user-images.githubusercontent.com/74786379/100357841-80d70400-2ff5-11eb-80de-cdf7d32dce41.png)

Thanks again in advance

**Comment by NTCA-supporter** [comment]
Hi!

Please try this format:
`<public publicId="http://schemas.nav.gov.hu/NTCA/1.0/common" uri="https://raw.githubusercontent.com/nav-gov-hu/Common/Common-1.0.RC3/src/schemas/nav/gov/hu/NTCA/common.xsd"/>`

**Comment by LeeMcMahon** [comment]
Me again,

Same result :(

![image](https://user-images.githubusercontent.com/74786379/100431367-58ecac80-3098-11eb-9f8d-26b4a6d65599.png)

**Comment by renced42** [comment]
Dear @LeeMcMahon can you show me the begining of your invoiceData.xsd?

**Comment by LeeMcMahon** [comment]
Sure,
![image](https://user-images.githubusercontent.com/74786379/100434518-e6ca9680-309c-11eb-9c5a-5c8b544df79f.png)

**Comment by renced42** [comment]
Dear @LeeMcMahon did you manage to solve the problem?

**Comment by LeeMcMahon** [comment]
Hi renced,

Unfortunately no not yet, I am working on multiple projects at the moment so have not had much time to check into other solutions but I can not see what I am doing wrong. The steps seem pretty logical but something is not quite right :(

Lee

**Comment by renced42** [comment]
> The steps seem pretty logical but something is not quite right :(

Dear @LeeMcMahon  On finally case you can set the schemaLocation attribute inside the import TAG. Copy all of the XSD into a folder. Like here: https://github.com/nav-gov-hu/Online-Invoice/issues/480#issuecomment-715914613 

<xs:import namespace="http://schemas.nav.gov.hu/NTCA/1.0/common" schemaLocation="common.xsd"/>
<xs:import namespace="http://schemas.nav.gov.hu/OSA/3.0/base" schemaLocation="invoiceBase.xsd"/>

**Comment by LeeMcMahon** [comment]
Hi,

I have now changed the "InvoiceData.xsd" to the below;
![image](https://user-images.githubusercontent.com/74786379/101803781-2cfa0e00-3b11-11eb-9117-5821d8be628a.png)

When I open this XSD in Altova Mapforce I get the below error;
![image](https://user-images.githubusercontent.com/74786379/101803878-4ac77300-3b11-11eb-9a64-d20f871c8ce6.png)

any pointers would be appreciated?

What is the reason that the XSD are not available at the url's stated in the XSD anyway? (http://schemas.nav.gov.hu/NTCA/1.0/common and http://schemas.nav.gov.hu/OSA/3.0/base) or am I missing something?  This feels like a step that should not be needed

Thanks

Lee

**Comment by renced42** [comment]
Dear @LeeMcMahon 

Send your email address. I help you remotely if you don't mind :)

**Comment by LeeMcMahon** [comment]
Hi renced42,

Thanks its appreciated you can get me on l.mcmahon@pincvision.com

Lee

**Comment by iolah2** [comment]
Hi renced42!
Can you help me too?
iolah2@gmail.com
I probe testing validation by only InvoiceData.xsd from nav source, but this say not see common:
I not understand this catalog.xml case
I would like use InvoiceData, InvoiceBase and Common.xsd from same folder if not need other.
But it should run in notepad++ too, and mybe online validator.
Thanks
Steve

**Comment by renced42** [comment]
Dear @iolah2 

Notepad++ does not know the catalog xml by default, so you have to add the schemaLocation attribute to the import tags.
Copy all of the xsd into one folder from here : https://github.com/nav-gov-hu/Online-Invoice/tree/master/src/schemas/nav/gov/hu/OSA

Don't forget  about he common.xsd which is in a different project (https://github.com/nav-gov-hu/Common)

Open every xsd file find and edit the import tag like in the the example below  

Example:

<xs: import namespace = "http://schemas.nav.gov.hu/NTCA/1.0/common" schemaLocation = "common.xsd" />
<xs: import namespace = "http://schemas.nav.gov.hu/OSA/3.0/base" schemaLocation = "invoiceBase.xsd" />

After that, the validation will be good.

**Comment by NTCA-supporter** [comment]
Is there any further question?

**Comment by NTCA-supporter** [comment]
I close this issue due to inactivity. 
Br
