### ISSUE TITLE
[Q&A]Céges vagy magán vásárlás

### ISSUE THREAD

**Issue by tkelemen73** [nav-gov-hu/Online-Invoice#541]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Olyan helyen történő vásárlás esetén, ahova cégként lehet csak bemenni (pl. Metro áruházban a Metrokártyával, ami a cég nevére szól) a pénztárnál mindig megkérdezik, hogy céges vagy magán vásárlásról van szó. Jelenleg ezzel tudják elkülöníteni azt, hogy beküldjék az adatszogáltatást vagy sem. Jövőre, amikor mindent be kell küldeni, ebben az esetben mi a teendő? Magánszemélyként kellene kezelni, vagy belföldi adóalanyként beküldeni? Ha beküldenék a magán vásárlást, mert a kártyához tartozó cég adatai szerepelnek a számlán, akkor a NAV-os ÁFA bevallás kiajánlás téves lesz, cégben nem elszámolt, fals tételeket is tartalmazni fogja. Ebben az esetben, ha magánvásárlásként kezelik, akkor a számlán feltételezem, nem szabadna megjelenni a vevő (cég) neve. De akkor a pénztárban a tényleges vevő, a magánszemély nevét/címét kellene bekérni? Vagy elegendő lenne a számlán csak azt szerepeltetni, hogy Magánszemély, bármilyen más adat nélkül?  Ezzel a számla kötelező tartalmi elemei közül a név, cím nem lenne helyes, vagy hiányos. Ha a cég neve, címe kerül fel a számlára, adószámmal, akkor az nem lenne helyes meglátásom szerint. Úgy vélem, ott a magánszemély adatainak kellene szerepelnie, így az adatszolgáltatásban is a magánszemély jelölésével, név és cím nélkül végezni az adatszolgáltatást, de a számlán a tényleges vevő adatainak kellene szerepelnie. Jól gondolom? Vagy mi a helyes eljárás ilyen esetben? Cégre nem szabadna a számlát kiállítani, nem kapcsolódik az adott vásárlás a cég gazdasági tevékenységéhez, nincs összefüggésben azzal.

**Comment by nbeeps2** [comment]
Az ÁFA bevallás kiajánlás SOHA SEM lehet pontos, mivel az, hogy egy cég nevére szól egy számla egyáltalán nem jelenti azt, hogy azt a cég költségként el is akarja/fogja majd számolni a könyvelésben. Az tehát, hogy a cég nevére szól egy számlát még nem jelent semmit.

**Comment by Macskafarka** [comment]
Ahogy @nbeeps2 helyesen leírta abból továbbgondolva egyenesen az következik, hogy a NAV által készítendő ÁFA bevallás csak egy porhintés. Emlékeztetőül: Ezzel indokolták anno a számla adatszolgáltatást!.
Így most még egy feladatot tolta az adóalanyokra: ellenőrizzék és pipálgassák a NAV által elkészített bevallás tervezetet.
Megjegyzem, ugyanilyen gond a részben levonható áfa esete is. Ha továbbszámlázom a telefonszámlát, akkor 100%-ban levonhatom, ha nem, akkor csak 70%-ban. Amúgy a 70% is TESZOR számtól függ, ami viszont nem kötelező az adatszolgáltatásban.
Ergó, amelyik vállalkozásnak van telefonszámlája, annak eleve nem lesz jó az ÁFA bevallás tervezet.
Akkor kinek is lesz jó a politikásokon kívül?

**Comment by Macskafarka** [comment]
A NAV által készítendő ÁFA bevallás nem egy felhasználói hibából adódik, hanem a valóság eleve tudottan elvi szinten is hibás leképezéséből.
Hibás pusztán a kiállított számlákból összeállítani az ÁFA bevallást. Ezt minden könyvelő tudja. 
A törvény is a befogadáshoz köti.

**Comment by nbeeps2** [comment]
@Macskafarka igen, ergo nem fog változni semmi, teljesen mindegy mint ajánl ki majd a NAV ÁFA bevallásnak figyelmen kívül kell hagyni és ugyanúgy kell könyvelni és eljárni, mint eddig... Bárki bármit is mond teljesen egyértelmű, hogy itt nem az ÁFA bevallás állami kitöltésén van a hangsúly, hanem, hogy mindenre rá lehessen látni és ezt az ellenőrzésékhez, ÁFA csalások felderítéséhez tudják használni. Ezzel nincs semmi baj, csak tényleg nem kéne hype-olni ezt az automata NAV ÁFA bevallást, mert ez egy nagy humbuk...

**Comment by Macskafarka** [comment]
100%-ban egyetértek @nbeeps2 -vel!

**Comment by kovadam69** [comment]
Hallottam egy olyat (vagy olvastam valahol, már nem rémlik), hogy céges számlára, de nem a cég érdekében történt vásárlás SZJA fizetési kötelezettséget vonhat maga után annak ellenére, hogy nem fogadta be a cég a számlát, ugyanis mi van akkor, ha magánszemélyként megkapom az árut 100Ft-ért, de ha kérek róla a cégre számlát, akkor megkapom 90Ft-ért (mert mondjuk a cégnek 10% kedvezménye van). A számlát ugyan nem teszem be a könyvelésbe, ugyanakkor a dolgozó, ismerős, magánszemély, akárki, aki a számlát kérte 10Ft "juttatást" kapott csak azzal a ténnyel, hogy számlát kért, ami mivel juttatásnak minősül, adóköteles.
Vagyis a NAV ÁFA bevallása az alapján pontos lehet, hogy elvileg nem lehet olyan számla, amit a cég nevére állítanak ki és nincs benne a könyvelésben ... Tudom, nem életszerű, de ha igaz, amit fentebb leírtam, akkor vagy be kéne tenni a könyvelésbe, vagy SZJA-t kéne fizetni utána... 
Már ha igaz persze...

**Comment by Macskafarka** [comment]
Tetszik, amit @kovadam69 írt. Ha eljátszunk a gondolattal, akkor kinek is kellene fizetnie? Az engedményt ugye a számlakibocsátó adta, ő viszont nem tud arról, hogy a vevő befogadta-e a számlát. 
Ennél sokkal nagyobb kapás lenne, ha a kuka holdingot vonnák felelősségre azért, mert a késve számláz. A késve számlázás miatt a költségvetés ugyebár kárt szenved, mert késve jut hozzá az áfához. Mégsem hallottam volna, hogy valaki utána eredne ennek és elkezdene pl. költségvetési csalás ügyben vizsgálódni.

**Comment by nbeeps2** [comment]
@kovadam69 És akkor mi van, ha én kicseszésből veszek a céged nevére valamit...? Ugyanis a pénztárnál bármilyen valós cégnevet, címet bediktálhatok.... Szóval ezért nem úgy működnek a dolgok, ahogy Te leírtad...

**Comment by kovadam69** [comment]
@nbeeps2 igen, van is ezzel probléma, mert utána kell menni, és stornóztatni kell a kiállítókkal a számlákat, amik hozzánk nem érkeztek be... meg kéne nézni az ide vágó rendelkezéseket, de én fejlesztő vagyok, nem jogász, ugyanakkor valahol ezt olvastam, méghozzá pont ennek kapcsán, hogy minden számla lejelentésre kerül, így lesz a NAV-nak egy listája, hogy milyen számlákat állítottak ki a cégre és neked egy listád, hogy abból mit fogadtál be. A különbözet a problémás, mert ott benne van a levegőben a "juttatás" lehetősége... igaz azt kinyomozni, hogy ki vette, meg egyáltalán kapott-e rá kedvezményt vagy sem, nem triviális...

**Comment by topybear** [comment]
Nem tudod sztornóztatni, mert neki - mivel a valódi igénybevevő nem ismert - vagy egy fiktív számlát kellene kiállítania (amit nyilvánvalóan nem fog) - vagy vissza kellene állítania az eredeti állapotot, azaz vissza kellene vennie a terméket. A szolgáltatásról ne is beszéljünk...

**Comment by kovadam69** [comment]
most is fiktív emberekre van kiállítva a számlák 99%-a, ha nem cégre kéred... sehol nem kérdik a nevem, kinyomnak egy kb. Gipsz Jakab névre meg valami default budapesti címre számlát...

**Comment by NTCA-tax** [comment]
Az eredeti kérdésre fogok csak válaszolni, az áfa bevallás kiajánlásával kapcsolatos kérdéseket hagyjuk másik fórumra...

Amennyiben az értékesítő belföldi adóalanynak állít ki számlát, akkor kötelező feltüntetni annak az adószámát és nem küldheti be magánszemélynek történő értékesítésként. Ha magánszemélynek történik az értékesítés és erről számla kerül kiállításra, akkor a számlának a magánszemély nevét, címét kell tartalmaznia. Ez utóbbi esetben viszont az adatszolgáltatásban nem szerepelhet a magánszemély adata.

Tehát a számla adatából következik az, hogy magánszemély vagy adóalany a vevő.

**Comment by Amn3s1a2018** [comment]
Az eredeti kérdés így szerintem tiszta. Alapvetően már a felvetés is fura, csak azért nem mertem vitatkozni, mert nincs ilyen személyes tapasztalat (se metró se más hasonló bolt esetén), tőlem nem kérdezte még egy sem, hogy magán-e a vásárlás ha céges kártyával mentem. De ha ilyen esetben a kereskedő kiállítja a számlát cégre de nem küldi, mondván, hogy magán vásárlás, az biztosan aggályos. Ha meg ilyenkor nyugtát kapsz (vagy saját névre számlát) a céges kedvezmény amit kaptál (ha volt egyáltalán) nem lehet SZJA köteles, hiszen a munkáltató nem érintett.

**Comment by NTCA-tax** [comment]
Ezt az issue-t lezárom, amennyiben felmerülne ezzel kapcsolatos kérdés, akkor nyissunk rá újat.
