### ISSUE TITLE
2.0-s számla struktúra helyesbítése/sztornózása

### ISSUE THREAD

**Issue by moferi** [nav-gov-hu/Online-Invoice#542]
Ez az xml részlet 2.0-s számla xml-ből való:

![image](https://user-images.githubusercontent.com/584501/99878548-818f2500-2c06-11eb-894b-60d41c17b59c.png)

Ha ezt a számlát esetleg sztornózni kellene, akkor ezt a tételt hogyan alakítsuk át 3.0-s xml-lé:
ugyanis ugyanezt a tételt negatív előjellel szerepeltetjük a sztornó számlán.

A vatExemption a 3.0-ban már egy csomóponttá alakul, aminek két mezője case és reason is van. Úgy gondoltam, hogy a 2.0-ás vatExemption értéket beleteszem a 3.0-ás vatExemption->reason-ba. Viszont a kötelező case mezőbe vajon mit írjak bele?

Ugyanez a kérdésem a 2.0-ban lévő vatOutOfScope kapcsán, ami egy boolean típusú mező volt. Ezt hogyan alakítsuk 3.0-vá, ahol egy case és egy reason mezőt is ki kellene tölteni - egy sztornózás vagy helyesbítés esetén.

Előre is nagyon köszönöm a segítséget!
Feri

**Comment by white420** [comment]
talán lesz rá megoldás:
https://github.com/nav-gov-hu/Online-Invoice/issues/454

**Comment by NTCA-supporter** [comment]
Szia @moferi !
A belinkelt #454 megadja a választ. Ott lesz jelezve az is, amikor már használható teszt környezeten az UNKNOWN érték.
Zárom az issuet.
Üdv
