### ISSUE TITLE
exchangeRate = 0

### ISSUE THREAD

**Issue by moferi** [nav-gov-hu/Online-Invoice#543]
A dokumentció 189 oldalán ezt olvashatjuk:
11) Az exchangeRate tagban a 3.0-tól kezdődően megadható 0 értékű árfolyam, mert azon devizás
ügyleteknél, amelyek felszámított adót nem tartalmaznak az árfolyam nem számítható ki helyesen.

Amennyiben egy 100 EURós tételt 0% áfával állítok ki, akkor felszámított adót nem tartalmaz. Beküldés után ezt a WARNING tömeget kapjuk:

_ErrorCode: INCORRECT_SUMMARY_DATA_INVOICE_NET_AMOUNT_HUF
Message: Eltérés a számla eredeti pénznemben és forintban megadott nettó értékei között.
BusinessResultCodeType: WARN
ErrorCode: INCORRECT_LINE_CALCULATION_LINE_GROSS_AMOUNT_NORMAL_HUF
Message: Eltérés a számla tétel eredeti pénznemben és forintban megadott bruttó értéke között.
BusinessResultCodeType: WARN
ErrorCode: INCORRECT_LINE_CALCULATION_LINE_NET_AMOUNT_HUF
Message: Eltérés a számla tétel eredeti pénznemben és forintban megadott nettó értéke között.
BusinessResultCodeType: WARN
ErrorCode: INCORRECT_SUMMARY_DATA_INVOICE_VAT_RATE_NET_AMOUNT_HUF
Message: Eltérés a számla eredeti pénznemben és forintban megadott adómértékhez tartozó értékesítés vagy szolgáltatásnyújtás nettó összegei között.
BusinessResultCodeType: WARN
ErrorCode: INCORRECT_SUMMARY_DATA_INVOICE_GROSS_AMOUNT_HUF
Message: Eltérés a számla eredeti pénznemben és forintban megadott bruttó összegei között.
BusinessResultCodeType: WARN_

Rosszul értelmeztem a 11es pontot? Az exchangeRate bizonyos esetekben kötelezően 0, vagy csak lehet 0? Ha kötelezően 0, akkor mikor kell 0-t beállítani? Köszönöm a választ előre is.

**Comment by nbeeps2** [comment]
Én nem tapasztaltam, hogy az exchangeRate bizonyos esetekben kötelezően 0 kell legyen. Warning nélkül sikeres lett az olyan EUR-os számla, amin volt árfolyam megadva, de felszámított ÁFA-t nem tartalmazott.

**Comment by Amn3s1a2018** [comment]
Engem is érdekelne, hogy ezzel a mondattal mire gondolt a szerző ...
Az ok, hogy a devizás áfa összegből (ami ugye lehet nulla) kiszámítható a számla áfatartalma forintban, és ezt bizonyos esetben rá is kell írni a számlára. De miért akarná valaki ebből visszaszámolni az árfolyamot? (viszont jelenteni már nem csak ezt a forint összeget kell, hanem mindent is, ami egyébként tök törvénytelen, de ezen már túlléptünk)
Ráadásul ha áfabevallást akar valaki készíteni (az adózó magának, vagy a NAV a beküldött számlák alapján) akkor úgyis kell egy igazi (nem nulla) árfolyam, a nettók forint összegének bevallásához. Ha meg pl. a nettó is nulla akkor nem mindegy mi van árfolyamban? Lehet akár fixen 1 is, vagy valami értelmes árfolyam az adott számlához ha már úgyis jelentek valamit. Ha nullákat szorzok vele az forintban is nulla lesz.
Az `exchangeRate` már a 2.0-ás interfészen is kötelező volt, feltehetőleg az áfabevalláshoz használt árfolyamot kérik benne, de a példákban nem sikerült bemutatni a használatát. A 3.0-hoz pedig a mai napig egy darab példa sincs és jövő héten december...

**Comment by NTCA-tax** [comment]
Az elfogadott áfa törvény módosítással az adatszolgáltatásban minden esetben kötelező lesz az árfolyam szerepeltetése. Ez is az egyik oka volt az XSD és dokumentáció változtatásnak. A jogszabály változása miatt az árfolyam logikáját meg kellett változtatnunk, így a nulla forint az árfolyamnál már nem elfogadható. Ugyanis nincs olyan eset, amikor az árfolyam nem megadható.

Fontos figyelni arra, hogy a 10. számú melléklet 4. pontja alapján a külföldi pénznemben kiállított számla adóalapjának forintra történő átszámításához használt árfolyamot az adatszolgáltatásnak tartalmaznia kell és ezzel az árfolyammal kell az összeg adatokat az adatszolgáltatásban átszámolni. Amennyiben az árfolyam a felhasználó által megadott adatok alapján nem tölthető ki, akkor a felhasználótól ezt érdemes elkérnie a programnak.

**Comment by Amn3s1a2018** [comment]
Akkor a dokumentumból is kikerül a problémás mondat?

**Comment by NTCA-tax** [comment]
Persze.

**Comment by NTCA-tax** [comment]
Mivel a módosított interfész specifikáció is publikálásra került, ezért ezt az issue-t lezárom.
