### ISSUE TITLE
Tesztrendszer karbantartása 2020.11.21. óta a Dokumentációk menüpontból elérhető dokumentumoknál ERROR

### ISSUE THREAD

**Issue by tkelemen73** [nav-gov-hu/Online-Invoice#544]
Sziasztok,
a tegnapi karbantartás óta bármelyik verzióhoz tartozó dokumentum megnyitásakor 404-es hiba és ERROR üzenet van, pl:

3.0
error |  
statusCode | 404
name | "Error"
message | "Cannot GET /files/container/download/Online%20Szamla_interfesz%20specifik%C3%A1ci%C3%B3_HU_v3.0.pdf"

2.0
error |  
statusCode | 404
name | "Error"
message | "Cannot GET /files/container/download/OSA%20Schemas_v2.zip"

1.1
error |  
statusCode | 404
name | "Error"
message | "Cannot GET /files/container/download/Online%20Szamla_Interfesz%20specifik%C3%A1ci%C3%B3_HU_v1.1.pdf"

Teljesen mindegy, hogy melyik verzióhoz tartozó, és bármilyen dokumentum megnyitása ugyanezt az eredményt adja.

Csak a tesztrendszernél, az éles rendszernél ok.

üdv
T.

**Comment by vectorkovacspeter** [comment]
Maga az api (https://api-test.onlineszamla.nav.gov.hu) se válaszol a GET -re

**Comment by NTCA-supporter** [comment]
Köszi a jelzést, dolgozunk rajta. Jelzek, ha elérhető.
Üdv

**Comment by nbeeps2** [comment]
Elérhető ;)

**Comment by vectorkovacspeter** [comment]
> Elérhető ;)

Reggel nekem is megszólalt egy pillanatra, de ez már a tartós állapot? :)

**Comment by vectorkovacspeter** [comment]
pl.: az imént OK helyett: 'no healthy upstraem' vagy efféle villant át előttem
