### ISSUE TITLE
[Q&A]API forgalom korlátozás

### ISSUE THREAD

**Issue by hape1022** [nav-gov-hu/Online-Invoice#545]
Sziasztok!

Egy kérdésem lenne az XML API működés forgalomkorlátozásával kapcsolatban. Cégünk, EDI rendszeren keresztüli NAV-os számlajelentési szolgáltatást nyújt több 70 magyarországi vállalatnak, emiatt gondolom nagyobb az API-forgalmunk mint egy átlagos adó bevallónak. Kérdésem pedig az lenne, hogy milyen lehetőségek lennének arra, hogy a nagyobb forgalommal rendelkező kommunikációs vállaltok számara kivételt/különbséget tegyenek a forgalomkorlátozás terén és ne blokkolják le az IP-t mint ahogy az múlt héten megtörtént. 

Üdv

**Comment by renced42** [comment]
Kedves @hape1022 a NAV a meghirdetett V1-es forgalomkorlátozáson kívül más blokkolást nem foganatosított.

Láttam múlt héten ilyen blokkolós hibajegyet, de ott mint kiderült nem a NAV blokkolta az ügyfelet. Nem tudom, hogy benne voltatok-e. 
Ami még gyakori probléma a timeout rossz beállítása (alacsony értek) kliens oldalon, így hamarabb timeoutol a kliens mint ahogy megérkezik a válasz, nagyobb terhelés esetén. Ezt is vizsgáljátok meg kérlek, hogy ez nálatok mekkora érték vagy a köztes rétegben mekkora ez az érték.

**Comment by NTCA-supporter** [comment]
Zárom az issuet. Ha van még kérdés, nyisd újra kérlek.
Üdv
