### ISSUE TITLE
Teszt rendszer nem működik [DEV support]

### ISSUE THREAD

**Issue by tib99** [nav-gov-hu/Online-Invoice#546]
Sziasztok

A teszt rendszer ma egész nap elég bizonytalan, hol működik hol nem. Connection reset jön különböző helyeken: tokenExchange, queryTransactionStatus
utolsók pl.:
2020-11-23 13:39:41.896 [https-jsse-nio-8443-exec-5] ERROR java.net.SocketException: Connection reset
2020-11-23 13:52:52.764 [https-jsse-nio-8443-exec-3] ERROR java.net.SocketException: Connection reset

**Comment by NTCA-supporter** [comment]
Köszi a jelzést, nézik az illetékesek.
Üdv

**Comment by zsolt-takacs** [comment]
Ráolvasással?

**Comment by ballonyi** [comment]
Kb. mikor lesz újból elérhető?

**Comment by tkelemen73** [comment]
no healthy upstream 
Srácok, jól vagytok odaát?

**Comment by tkelemen73** [comment]
Érdekes válaszok jönnek vissza, bármelyik operációt (pl. token kérés, adózó ellenőrzés) hívom meg:

<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<TechnicalFault xmlns:ns27="http://notification.dto.coffee.icellmobilsoft.hu/notification" xmlns:ns26="http://common.dto.icon.icellmobilsoft.hu/jms" xmlns:ns25="http://invoice.dto.icon.icellmobilsoft.hu/invoiceExport" xmlns:ns24="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns23="http://schemas.nav.gov.hu/OSA/3.0/annul" xmlns:ns22="http://common.dto.icon.icellmobilsoft.hu/export" xmlns:ns21="http://common.dto.icon.icellmobilsoft.hu/commonservice" xmlns:ns20="http://common.dto.icon.icellmobilsoft.hu/commonsecurity" xmlns:ns19="http://user.dto.icon.icellmobilsoft.hu/user" xmlns:ns18="http://user.dto.icon.icellmobilsoft.hu/device" xmlns:ns17="http://user.dto.icon.icellmobilsoft.hu/twostep" xmlns:ns16="http://navdata.dto.icon.icellmobilsoft.hu/navdata" xmlns:ns15="http://invoice.dto.icon.icellmobilsoft.hu/invoice/history/v1" xmlns:ns14="http://invoice.dto.icon.icellmobilsoft.hu/invoice" xmlns:ns13="http://invoice.dto.icon.icellmobilsoft.hu/invoice/history/v2" xmlns:ns12="http://config.dto.icon.icellmobilsoft.hu/config" xmlns:ns11="http://artemis.dto.icon.icellmobilsoft.hu/artemis" xmlns:ns10="http://document.dto.icon.icellmobilsoft.hu/document" xmlns:ns9="http://common.dto.coffee.icellmobilsoft.hu/common" xmlns:ns8="http://invoice.dto.icon.icellmobilsoft.hu/invoiceitem" xmlns:ns7="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns6="http://schemas.nav.gov.hu/OSA/3.0/data" xmlns:ns5="http://schemas.nav.gov.hu/OSA/2.0/data" xmlns:ns4="http://test.dto.icon.icellmobilsoft.hu/invoicetest" xmlns:ns3="http://schemas.nav.gov.hu/OSA/1.0/data" xmlns:ns2="http://invoice.dto.icon.icellmobilsoft.hu/invoiceStatistics" xmlns="http://common.dto.coffee.icellmobilsoft.hu/commonservice">


-<context>

<requestId>36GOG8P8UO9HPNEV</requestId>

<timestamp>2020-11-23T20:35:13.676+01:00</timestamp>

</context>

<funcCode>ERROR</funcCode>

<message>RESTEASY003210: Could not find resource for full path: [protocol://host]/testAliveinvoiceService/v3/queryTaxpayer</message>

<faultType>OPERATION_FAILED</faultType>

</TechnicalFault>

**Comment by ballonyi** [comment]
Nekem továbbra sem megy. 
Tegnap 9:52 óta tapasztalom a problémát.  Az onlineszamla-test.nav.gov.hu -n nem találtam értesítést, hogy üzemszünet lenne.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Mi is látjuk a hibákat. Dolgozunk rajta, hogy minél hamarabb minden hiba elháruljon. Addig is a türelmeteket kérjük! Amint van előre lépés szólunk. Köszi

**Comment by ballonyi** [comment]
Érdemes lenne kitenni értesítést a webre, mert tegnap több órán át kerestem, hogy mit rontottam el - feleselegesen.

**Comment by littlecutieorion** [comment]
Én is kerestem egész délután a nagy semmit, mi lehet a bibi... Hol jó volt amit felküldtem, hol nem... 
Valóban jó lenne kitenni a teszt oldalra, hogy bizonytalan a teszt-szerver, próbálkozzatok később.

**Comment by drbogar** [comment]
Én egy XML választ kaptam már TechnicalFault root node-dal.

**Comment by tkelemen73** [comment]
Erre az üzenetre gondolsz? RESTEASY003210: Could not find resource for full path: [protocol://host]/testAliveinvoiceService/v3/tokenExchange
Nem tűnik üzemszerű működésnek, főleg nem a fejléc...

**Comment by hosszuful** [comment]
Üdv!
Ezek szerint még nem működik...  OPERATION_FAILED Feldolgozás sikertelen! üzenetet kapok.
Mikor lesz működőképes?

**Comment by renced42** [comment]
Kedves @hosszuful 

Sok üzenet érkezik be, és valóban van ami elhasal, kollégák dolgoznak rajta. Nem tudjuk még mikor lesz jó. Igyekszünk. Köszönjük a megértést és a türelmet.

**Comment by hosszuful** [comment]
@renced42 
Köszi... várok... ha működik majd írd meg légyszi... Köszi.

**Comment by varpade4** [comment]
Kedves @NTCA-supporter !

Érdeklődnék, hogy mikorra várható a megoldás?
Mert a 3.0-s fejlesztéshez is jó lenne, ha lehetne tesztelni a NAV feltöltést.
Előre is köszönöm a választ!

**Comment by NyBela** [comment]
Egy kicsit bővebb választ szeretnénk. Nekünk is dolgozni kellene. Köszönöm

**Comment by mynameiszsofia** [comment]
Sziasztok! Azt szeretném megkérdezni, hogy a 2.0-ás tokenExchange sem jó nálatok, vagy csak a 3.0 ? Mert nálam a 2.0-ás is 500-as hibával és OPERATION_FAILED üzenettel jön.

**Comment by nbeeps2** [comment]
Nekem ma már ment be 3.0-s számla, szóval ma 90%-ban működött, az egyik manageInvoice-nál volt csak egy kis elakadás, de 2. próbára már az is bement.

**Comment by hosszuful** [comment]
> Sziasztok! Azt szeretném megkérdezni, hogy a 2.0-ás tokenExchange sem jó nálatok, vagy csak a 3.0 ? Mert nálam a 2.0-ás is 500-as hibával és OPERATION_FAILED üzenettel jön.

Nekem ment a 2.0... a 3.0 mondott OPERATION_FAILED-et.

Most már megy a tokenkérés.

**Comment by NyBela** [comment]
Működik. A 3.0-t próbáltam. Belföldi, közösségen belüli, közösségen kívüli, magánszemély, Normál, érvénytelenítő, helyesbítő okirat stb.. Jó.

**Comment by ballonyi** [comment]
Fentebb @NTCA-supporter írta hogy javítanak valamit. Itt azóta nem jelezték még hogy újból üzemképes lenne a rendszer. Ami elbizonytalanít, hogy a "[Hírekbe](https://onlineszamla-test.nav.gov.hu/home)" viszont kikerült hogy csak tegnap volt gond. Tehát szándék szerint már megy? Mert nekem sajnos továbbra sem. Az Online Invoice Test Tool-al is megpróbáltam, azzal sem sikerült tokent kérni.

**Comment by NyBela** [comment]
Ne a híreket nézd! Ma sem működött. Most viszont működik a 3.0

**Comment by NTCA-supporter** [comment]
Sziasztok!

Tájkoztatást azért nem adtunk, mert még 100%-osan nem tudjuk állítani, hogy minden tökéletes.
Most úgy látjuk működik az alkalmazás, folyamatos a számlafeldolgozás.
Nekem több teszt után is stabilan működött a tokenkérés, v2 és v3 esetben is.
Garantált jó működés akkor lesz, ha a hírt is frissítjük és itt is jelzek. Mivel jó ideje nem látok hibát, így lehet próbálgatni a beküldést, és az esetleges hibára futott requestId-t ide megírni, igyekszem reagálni rájuk, (persze ha az egyedi hiba).

Köszi a türelmet!

**Comment by ballonyi** [comment]
Ezt az imént próbáltam: 
```
<common:requestId>TEXCH_000000308077</common:requestId>
<common:timestamp>2020-11-25T12:50:24.592Z</common:timestamp>
```

**Comment by littlecutieorion** [comment]
Sziasztok!
Most próbáltam ki a 3.0-t és hiba nélkül felment.

**Comment by clapygeza** [comment]
Sziasztok!
Tegnap (14:50 után ) és ma is a teszfelületen számlabeküldésre csak ezt kapom vissza:
'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><GeneralExceptionResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data"><funcCode>ERROR</funcCode><errorCode>OPERATION_FAILED</errorCode><message>RESTEASY003210: Could not find resource for full path: [protocol://host]/external/public/invoiceService/invoice/interface/invoiceRequest</message></GeneralExceptionResponse>
Tr.code 1-2-3 kisérletre megjön.
requestId: RID202011270945165,  beküldve ma 9:53-kor
Megnéznétek? Köszi

**Comment by renced42** [comment]
> Sziasztok!
> Tegnap (14:50 után ) és ma is a teszfelületen számlabeküldésre csak ezt kapom vissza:
> '''ERROROPERATION_FAILEDRESTEASY003210: Could not find resource for full path: [protocol://host]/external/public/invoiceService/invoice/interface/invoiceRequest
> Tr.code 1-2-3 kisérletre megjön.
> requestId: RID202011270945165, beküldve ma 9:53-kor
> Megnéznétek? Köszi

Kedves @clapygeza ellenőrizd az URL-t, hogy mire küldöd a kérést.
Az URL vége simán manageInvoice, de úgy néz ki, hogy hozzáteszel még egy Request toldalékot, ami nem létezik.

**Comment by clapygeza** [comment]
Megoldódott, köszönöm

**Comment by ballonyi** [comment]
Kedves @NTCA-supporter!

Kérnek nézd meg `TEXCH_000000309030` request-et miért nem sikeres (timestamp: 2020-11-27T13:38:36.294Z).
Az URL: https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3/tokenExchange

Köszönöm

**Comment by ballonyi** [comment]
> 
> 
> Kedves @NTCA-supporter!
> 
> Kérlek nézd meg `TEXCH_000000309030` request-et miért nem sikeres (timestamp: 2020-11-27T13:38:36.294Z).
> Az URL: https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3/tokenExchange
> 
> Köszönöm

Megoldódott, köszönöm

**Comment by lacih** [comment]
Kedves @NTCA-supporter!

Lehetséges, hogy 1-2 hete történt a teszt szerveren vmi olyan beállítás, konfiguráció, ami miatt az stunnel-en keresztül küldött request-ek, bármelyik végponttal is próbálom, kivétel nélkül 404-es hibát adnak? Az URL-ek biztosan jók, 2 hete még vígan ment a tesztszerverre való beküldés v3 alatt is. Jelenleg v2-vel és v3-mal is ugyanaz a helyzet (404).
Az éles szerverrel továbbra sincs gond, megy minden, mint eddig. Mind az élesen, mind a gyakorlón ugyanaz a megoldás működik a kezdetek óta, természetesen a megfelelő URL-ekkel.

Előre is köszönöm a választ.
üdv

**Comment by renced42** [comment]
Kedves @lacih 
A 404 az 404, kérlek ellenőrizd arról a gépről amiről küldesz adatot, böngészőből vagy wget-ből, hogy eléred-e a https://api-test.onlineszamla.nav.gov.hu/ oldalt itt egy OK-t kell kapj vissza. Ha nem éred el akkor hálózati problémád van.

**Comment by lacih** [comment]
> Kedves @lacih
> A 404 az 404, kérlek ellenőrizd arról a gépről amiről küldesz adatot, böngészőből vagy wget-ből, hogy eléred-e a https://api-test.onlineszamla.nav.gov.hu/ oldalt itt egy OK-t kell kapj vissza. Ha nem éred el akkor hálózati problémád van.

Kedves @renced42 !

Igen, elérem természetesen, OK jön vissza.
A request-eknél ahogy írtam egy stunnel van közbeiktatva, csak arra tudok gyanakodni, hogy akörül nem stimmel valami a szerver oldalon. A topik témáját jelentő üzemzavar utántól van ez a 404-es jelenség. Az a frusztráló, hogy előtte már évek óta ment mind a teszt, mind az éles beküldés. Az éles most is megy gond nélkül, ugyanezzel a struktúrával.

üdv

**Comment by renced42** [comment]
> A topik témáját jelentő üzemzavar utántól van ez a 404-es jelenség.

Légyszíves küldj IP címet meg időpontot esetleg RequestID-t, bár ha 404-et kapsz vissza nyílván el sem tudod küldeni.
az stunelből kellene valami verbose logot kicsikarni, hogy hol akad el a folymat.

**Comment by lacih** [comment]
stunnel.conf vonatkozó tartalom:

[nav-https-test]
client = yes
accept = 127.0.0.1:8008
connect = api-test.onlineszamla.nav.gov.hu:443
CAfile = ca-certs.pem
OCSPaia = yes

friss próbálkozás egy queryTaxpayer request-tel, az stunnel log tartalma:

2020.12.02 11:06:25 LOG5[main]: stunnel 5.57 on x64-pc-mingw32-gnu platform
2020.12.02 11:06:25 LOG5[main]: Compiled/running with OpenSSL 1.1.1h  22 Sep 2020
2020.12.02 11:06:25 LOG5[main]: Threading:WIN32 Sockets:SELECT,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2020.12.02 11:06:25 LOG5[main]: Reading configuration from file stunnel.conf
2020.12.02 11:06:25 LOG5[main]: UTF-8 byte order mark detected
2020.12.02 11:06:25 LOG4[main]: Service [nav-https-test] needs authentication to prevent MITM attacks
2020.12.02 11:06:25 LOG5[main]: Configuration successful
2020.12.02 11:06:52 LOG5[0]: Service [nav-https-test] accepted connection from 127.0.0.1:64071
2020.12.02 11:06:52 LOG5[0]: s_connect: connected 84.206.52.71:443
2020.12.02 11:06:52 LOG5[0]: Service [nav-https-test] connected remote server from 192.168.168.76:64072
2020.12.02 11:06:52 LOG5[0]: Connection closed: 1373 byte(s) sent to TLS, 326 byte(s) sent to socket

**Comment by lacih** [comment]
> Légyszíves küldj IP címet meg időpontot esetleg RequestID-t, bár ha 404-et kapsz vissza nyílván el sem tudod küldeni.
> az stunelből kellene valami verbose logot kicsikarni, hogy hol akad el a folymat.

stunnel.conf vonatkozó tartalom:

[nav-https-test]
client = yes
accept = 127.0.0.1:8008
connect = api-test.onlineszamla.nav.gov.hu:443
CAfile = ca-certs.pem
OCSPaia = yes

friss próbálkozás egy queryTaxpayer request-tel, az stunnel log tartalma:

2020.12.02 11:06:25 LOG5[main]: stunnel 5.57 on x64-pc-mingw32-gnu platform
2020.12.02 11:06:25 LOG5[main]: Compiled/running with OpenSSL 1.1.1h  22 Sep 2020
2020.12.02 11:06:25 LOG5[main]: Threading:WIN32 Sockets:SELECT,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2020.12.02 11:06:25 LOG5[main]: Reading configuration from file stunnel.conf
2020.12.02 11:06:25 LOG5[main]: UTF-8 byte order mark detected
2020.12.02 11:06:25 LOG4[main]: Service [nav-https-test] needs authentication to prevent MITM attacks
2020.12.02 11:06:25 LOG5[main]: Configuration successful
2020.12.02 11:06:52 LOG5[0]: Service [nav-https-test] accepted connection from 127.0.0.1:64071
2020.12.02 11:06:52 LOG5[0]: s_connect: connected 84.206.52.71:443
2020.12.02 11:06:52 LOG5[0]: Service [nav-https-test] connected remote server from 192.168.168.76:64072
2020.12.02 11:06:52 LOG5[0]: Connection closed: 1373 byte(s) sent to TLS, 326 byte(s) sent to socket

**Comment by renced42** [comment]
Kedves @lacih  mindenképpen kellene a NAT-olt címetek, mert biztosan nem 192.168.168.76-al jöttök hozzánk.
Még pár dolog TLS és Http protocol verzió ok?, A TLS-nek 1.2-nek kellene lennie.
Ha jó látom ez egy Windowson futtatot cygwin-es környezet, de lehet, hogy tévedek. Mire kell az Stunnel? Ezen keresztül látsz ki a hálózatodból?
Egy Wget-es parancsot ki tudsz adni ezen a csatornán?

**Comment by lacih** [comment]
> Egy Wget-es parancsot ki tudsz adni ezen a csatornán?

Szia!

NAT-olt IP:  78.131.11.206
TLS 1.2

stunnelt azért használunk, mert a szerver, ami küldi a request-et nem tud csak http-t, át kell fordítani https-re

wget és az stunnel debug logjait (teszt, éles) csatoltam:
[wget_log_eles.txt](https://github.com/nav-gov-hu/Online-Invoice/files/5630157/wget_log_eles.txt)
[wget_log_teszt.txt](https://github.com/nav-gov-hu/Online-Invoice/files/5630153/wget_log_teszt.txt)
[stunnel_log_teszt.txt](https://github.com/nav-gov-hu/Online-Invoice/files/5630160/stunnel_log_teszt.txt)
[stunnel_log_eles.txt](https://github.com/nav-gov-hu/Online-Invoice/files/5630159/stunnel_log_eles.txt)

**Comment by lacih** [comment]
> Kedves @lacih mindenképpen kellene a NAT-olt címetek, mert biztosan nem 192.168.168.76-al jöttök hozzánk.
> Még pár dolog TLS és Http protocol verzió ok?, A TLS-nek 1.2-nek kellene lennie.
> Ha jó látom ez egy Windowson futtatot cygwin-es környezet, de lehet, hogy tévedek. Mire kell az Stunnel? Ezen keresztül látsz ki a hálózatodból?
> Egy Wget-es parancsot ki tudsz adni ezen a csatornán?

Üdv!

Sikerült esetleg valamire jutni ezzel a linkelt log-ok és adatok alapján?

**Comment by renced42** [comment]
Kedves @lacih kérlek próbálj egy újat.

**Comment by lacih** [comment]
> Kedves @lacih kérlek próbálj egy újat.

Szia!

Linkelem a két friss mai próbálkozás stunnel-es logját.

Ami látszik belőlük, hogy éles rendszerre kiadott request esetén a logban lévő
**2020.12.08 11:29:18 LOG7[0]: Compression: null, expansion: null**

sor után egy fél perc múlva a socket és minden egyéb lezáródik:
**2020.12.08 11:29:48 LOG6[0]: SSL_read: Socket is closed**


Ezzel szemben a tesztre kiadott request esetén szintén eljutunk a fenti sorig:
**2020.12.08 11:36:32 LOG7[0]: Compression: null, expansion: null**

majd ezután se kép, se hang, semmilyen újabb történés. Mintha nem jönne válasz a teszt szervertől többet.
Ez a request oldalán 404-es hibaként jelenik meg.


[stunnel_log_eles.txt](https://github.com/nav-gov-hu/Online-Invoice/files/5658725/stunnel_log_eles.txt)
[stunnel_log_teszt.txt](https://github.com/nav-gov-hu/Online-Invoice/files/5658726/stunnel_log_teszt.txt)

**Comment by renced42** [comment]
Kedves @lacih 
Látjuk a próbálkozásokat, de valami nem stimmel a küldéssel
Kérlek küldj egy rendes POST-os kérést és küldmeg a pontos URL-t hogy mit hívsz.
Vagy egy printscreent, hogy lássuk :) 

Azt nem teljesen értettem, hogy a gép amiről küldötök nem tud https-t.

**Comment by lacih** [comment]
> Kedves @lacih
> Látjuk a próbálkozásokat, de valami nem stimmel a küldéssel
> Kérlek küldj egy rendes POST-os kérést és küldmeg a pontos URL-t hogy mit hívsz.
> Vagy egy printscreent, hogy lássuk :)
> 
> Azt nem teljesen értettem, hogy a gép amiről küldötök nem tud https-t.

Kedves @renced42!

Az ERP rendszer szervere, amin tesztelek, http request-et tud kiadni, azért kell az stunnel, hogy azon keresztül https request mehessen a NAV szerverre.

Most indítottam egy queryTaxpayer operációt, stunnel log linkelve.
URL: 127.0.0.1:8008/invoiceService/v2/queryTaxpayer

**Az stunnel config vonatkozó részlete:**
[nav-https-test]
client = yes
accept = 127.0.0.1:8008
;connect = api.onlineszamla.nav.gov.hu:443
connect = api-test.onlineszamla.nav.gov.hu:443
CAfile = ca-certs.pem
OCSPaia = yes

_Azaz:_
**accept = 127.0.0.1:8008**
A localhoston (ezen megy az ERP rendszer szervere, ami a NAV-ot megszólítja) a 8008-as porton érkező request-et https-re fordítva küldje tovább 

**connect = api-test.onlineszamla.nav.gov.hu:443**
a NAV teszt szerverére

[stunnel_teszt.log](https://github.com/nav-gov-hu/Online-Invoice/files/5659378/stunnel_teszt.log)

Ez az egész konstrukció 2018 óta megy partnereknél is mind az éles, mind a teszt szerveren. Az élesen most sincs vele semmi baj, a teszt szerveren a novemberi karbantartás óta van a jelenség (404).

**Comment by renced42** [comment]
Kedves @lacih 
Még egy próbát kérlek

**Comment by lacih** [comment]
> Kedves @lacih
> Még egy próbát kérlek

Friss próba, ugyanaz az operáció.

[stunnel_teszt.log](https://github.com/nav-gov-hu/Online-Invoice/files/5659539/stunnel_teszt.log)

**Comment by renced42** [comment]
Kedves @lacih 

Kicsit nézegettem az stunel doksikat.

Kérlek a konfighoz add hozzá ezt a sort és próbáld meg

[nav-https-test]

**sni = api-test.onlineszamla.nav.gov.hu**

**Comment by lacih** [comment]
> Kedves @lacih
> 
> Kicsit nézegettem az stunel doksikat.
> 
> Kérlek a konfighoz add hozzá ezt a sort és próbáld meg
> 
> [nav-https-test]
> 
> **sni = api-test.onlineszamla.nav.gov.hu**

Kedves @renced42!

Kipróbáltam, nincs változás. A linkelt logban is úgy láttam, hogy használ SNI-t.

**Comment by renced42** [comment]
Kedves @lacih

Na mégegyszer :)

**Comment by lacih** [comment]
> Kedves @lacih
> 
> Na mégegyszer :)

No, mi történt? Visszadugtátok a konnektorba? :-)

**Comment by renced42** [comment]
Kedves @lacih 

Persze a srácok szóltak, hogy a kávéfőző volt eddig bedugva, most visszatették a teavíz forralót :)

De félre a tréfával, a probléma az, hogy a host header érték amit küldesz nem jó, hiába van az SNI belőve nálad, mégis 127.0.0.1:8008-at kapunk és ez hibás működés sajnos.

Azért tudtál eddig működni, mert eddig ezt a hibát nem vettük figyelembe az átállás óta viszont már erre is figyelünk.
 
Ideiglenesen ezt a szabályt most módosítottuk, hogy jó legyen a beküldésed.

Kérlek, hogy ezen dolgozzatok, mert ezt a vizsgálatot neked most az EDU-n kikapcsoltuk, de az élesen a decemberi átállásnál vagy azt követően nagy valószínűséggel be lesz kapcsolva.

Köszi a sok tesztet ezzel valószínűleg pár emberen most segítettünk általad illetve mi is tudunk egy plusz vizsgálnivalót mondani.

**Comment by lacih** [comment]
> Kedves @lacih
> 
> Persze a srácok szóltak, hogy a kávéfőző volt eddig bedugva, most visszatették a teavíz forralót :)
> 
> De félre a tréfával, a probléma az, hogy a host header érték amit küldesz nem jó, hiába van az SNI belőve nálad, mégis 127.0.0.1:8008-at kapunk és ez hibás működés sajnos.
> 
> Azért tudtál eddig működni, mert eddig ezt a hibát nem vettük figyelembe az átállás óta viszont már erre is figyelünk.
> 
> Ideiglenesen ezt a szabályt most módosítottuk, hogy jó legyen a beküldésed.
> 
> Kérlek, hogy ezen dolgozzatok, mert ezt a vizsgálatot neked most az EDU-n kikapcsoltuk, de az élesen a decemberi átállásnál vagy azt követően nagy valószínűséggel be lesz kapcsolva.
> 
> Köszi a sok tesztet ezzel valószínűleg pár emberen most segítettünk általad illetve mi is tudunk egy plusz vizsgálnivalót mondani.

Kedves @renced42 !

Mit kell küldenem, hogy elfogadja a szerveretek?

**Comment by renced42** [comment]
> Mit kell küldenem, hogy elfogadja a szerveretek?

api-test.onlineszamla.nav.gov.hu a teszten 
api.onlineszamla.nav.gov.hu az élesen

**Comment by lacih** [comment]
> api.onlineszamla.nav.gov.hu

Kedves @renced42!

Jelezz majd kérlek, ha rá tudtok nézni megint egy konkrét request-re. Próbáltam módosítani a headert, hogy még az stunnel előtt belekerüljön a host.

**Comment by lacih** [comment]
> > api.onlineszamla.nav.gov.hu
> 
> Kedves @renced42!
> 
> Jelezz majd kérlek a holnapi nap folyamán, ha rá tudtok nézni megint egy konkrét request-re valamikor, amit beküldök.
> Próbáltam módosítani a headert, hogy még az stunnel előtt belekerüljön a host.

Kedves @renced42!

Én készen állok egy esetleges vizsgálatra most.

üdv

**Comment by renced42** [comment]
Kedves @lacih 

Akkor próbálj meg egyet :)

**Comment by lacih** [comment]
> Kedves @lacih
> 
> Akkor próbálj meg egyet :)

Friss próba ment 11:48-kor

**Comment by renced42** [comment]
> Friss próba ment 11:48-kor (queryTaxpayer)

Szia sajnos nem sikerült :(

**Comment by lacih** [comment]
> > Friss próba ment 11:48-kor (queryTaxpayer)
> 
> Szia sajnos nem sikerült :(

El tudnád küldeni az egész struktúrát, amit láttok?
cyraxx22@gmail.com

**Comment by renced42** [comment]
Kedves @lacih 
Sajnos nem sok mindent tudok küldeni. 
A lényeg hogy a post header-ben van egy  host nevű mező (ez most 127.0.0.1:8008) pl mint a content type oda kell bevarázsolni az aip-test.nav.gov.hu értéket.

> content-type: text/xml
> host: 127.0.0.1:8008

**Comment by lacih** [comment]
> > Friss próba ment 11:48-kor (queryTaxpayer)
> 
> Szia sajnos nem sikerült :(

12:58-kor ment egy újabb próba (queryTaxpayer)

**Comment by renced42** [comment]
Kedves @lacih 

Ez szemmel láthatóan jobb lett:
> host: api-test.onlineszamla.nav.gov.hu

**Comment by lacih** [comment]
> Kedves @lacih
> 
> Ez szemmel láthatóan jobb lett:
> 
> > host: api-test.onlineszamla.nav.gov.hu

Akkor esetleg kipróbálhatnánk, hogy visszakapcsoljátok a szigorítást és úgy próbálok kiadni egy request-et, ha nem nagy gebasz.

**Comment by renced42** [comment]
Kedves @lacih 

Visszakapcsoltuk a V2-n, próbáld meg.

**Comment by lacih** [comment]
> Kedves @lacih
> 
> Visszakapcsoltuk a V2-n, próbáld meg.

Kedves @renced42!

Kipróbáltam, működik a  dolog a megszorítással is. Hálás köszönet a segítségért és a kitartó türelemért! :-D

üdv

**Comment by renced42** [comment]
Kedves @lacih 
Nincs mit, szívesen 👍 
A megoldást megosztanád velünk ha nem titkos? :)

**Comment by lacih** [comment]
> Kedves @lacih
> Nincs mit, szívesen 👍
> A megoldást megosztanád velünk ha nem titkos? :)

Persze.
A szerverünkben a HTTP request-et előállító metódus az eredeti URL-ből határozta meg a host-ot, ezért láttátok azt, amit.
Ide kellett egy config lehetőség, hogy azzal megmondjuk, mi a valódi host. Ha ez meg van adva, akkor kicseréli az első lépésben meghatározott host-ot a valódira.
Maga az stunnel és az SNI megadása nem játszott szerepet a problémában.

**Comment by lacih** [comment]
Kedves @renced42!

Tettem egy próbát a teszten a V3 csatornán is, ott most Internal Server Error (500) üzenet jön. Erről tudsz esetleg valamit?

**Comment by renced42** [comment]
Kedves @lacih 
Igen nem jó a passwordhash crypto a kérésben. Még az SHA2-512-t kell megadni.

**Comment by lacih** [comment]
> Kedves @lacih
> Igen nem jó a passwordhash crypto a kérésben. Még az SHA2-512-t kell megadni.

Kedves @renced42!

Oh, értem. Esetleg van hozzávetőleges infó, hogy mikor lépnek életbe a friss sémaváltozások?

**Comment by renced42** [comment]
> Oh, értem. Esetleg van hozzávetőleges infó, hogy mikor lépnek életbe a friss sémaváltozások?
Reményeim szerint a hétvége felé.

**Comment by lacih** [comment]
> > Oh, értem. Esetleg van hozzávetőleges infó, hogy mikor lépnek életbe a friss sémaváltozások?
> > Reményeim szerint a hétvége felé.

Rendben, köszönöm szépen!
üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

Itt van még kérdés? A séma elérhető teszt környezeten.

Üdv
