### ISSUE TITLE
Data példa xml-ek

### ISSUE THREAD

**Issue by lengyelistvan1970** [nav-gov-hu/Online-Invoice#547]
A 3.0-ás dokumentáció, XSD-k már régóta elérhetőek, de a Data példa xml-ek-nél még "folyamatban" szerepel. Mikor lesznek elérhetőek?

**Comment by littlecutieorion** [comment]
Szorít az idő... Kíváncsian és nagyon várom a "Közmű elszámoló számla" példa xml-jét. Persze a többit is, de ez a legmacerkásabb.
Sürgős és fontos lenne.

**Comment by NyBela** [comment]
Én is választ szeretnék, kapni, hogy mikor lesznek fent a példák!
Köszönöm.

**Comment by Amn3s1a2018** [comment]
+1  :)

**Comment by sapatag** [comment]
Ez most már nagyon gáz

**Comment by Macskafarka** [comment]
Éget az idő bennünket is!

**Comment by moczaand** [comment]
Sajnos nálunk külföldről készítik az új verziót és ők is nagyon várják a példafile-kat, addig nem kezdenek hozzá, kérlek mondjátok meg mikor lesz elérhető a Data példa xml rész. Nagyon köszönöm

**Comment by gaqskft** [comment]
Ez minket is érdekelne. Mikor lesz elérhető a példa XML a 3.0-ás verzióhoz? Válaszukat előre is köszönjük!

**Comment by NTCA-supporter** [comment]
Sziasztok!

Mai napon lesznek publikálva.

Üdv

**Comment by NTCA-supporter** [comment]
https://onlineszamla.nav.gov.hu/dokumentaciok

Sziasztok!

A publikálás megtörtént. 
Az issuet zárom, ha van még kérdés, kérlek nyissátok újra.
Üdv

**Comment by moczaand** [comment]
Köszönöm!

Az angol nyelvű verzió is el fog készülni? Bár szerintem csak a számlák megnevezése az amiben különböznek.

Best regards,

Andrea Moczarne
Site Accounting Manager Service and Finance
MARS MAGYARORSZÁG KISÁLLATELEDEL GYÁRTÓ KFT
T: +36 63 579 513 | M: +36 30 3366904 | F: +36 63 479 489
E: andrea.moczarne@effem.com<mailto:andrea.moczarne@eu.effem.com>
W: www.mars.com<http://www.mars.com/>

MXP SSO link-  https://xp5.mobilexpense.com/effem<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fxp5.mobilexpense.com%2Feffem&data=02%7C01%7Candrea.moczarne%40effem.com%7C773e3c2362bc4aeec7e608d77edfc246%7C2fc13e34f03f498b982a7cb446e25bc6%7C0%7C0%7C637117371811361452&sdata=RR1IGGUpeErGnFOSK7eTyejPG0bbB6yZoVXhDxtSnNQ%3D&reserved=0>

**Comment by lengyelistvan1970** [comment]
A 2.0-ás verzióban 1 xsd-vel lehetett validálni a készülő számla xml file-t.
Most, a 3.0-ban már több xsd-ben van tárolva az xml-hez szükséges formátum leírás.
Tudnak mondani javaslatot, hogy hogy lehet az xml-t több xsd-vel validálni?
Az elérhető validálási módok (pl. Online validáló web oldalak, vagy pl. a Notepad ++) 1 xsd megadását engedélyezik.
Köszönöm

**Comment by renced42** [comment]
Kedves @lengyelistvan1970 

A filterbe írd be ezt:
is:issue is:open is:closed schemaLocation="common.xsd" 

A megjelenő topicokban választ kapsz rá.
