### ISSUE TITLE
Helytelen termékdíj számítás WARN üzenet

### ISSUE THREAD

**Issue by NyBela** [nav-gov-hu/Online-Invoice#549]
Az alábbi problémára keresek választ.
Érvénytelenítő , vagy helyesbítő számla esetén, a  számla beküldése után ezt az üzenetet kapjuk vissza.  
WARN / INCORRECT_PRODUCT_FEE_CALCULAT
A "Helytelen termékdíj-számítás. A termékdíjak termékkódonkénti összege eltér a termékdíj összesen értéktől. "

Az eredeti számla probléma nélkül elfogadásra került. Ez a jelenség kizárólag az érvénytelenítő, vagy a helyesbítő (vagyis negatív) előjelű esetben fordul elő. Ez már a 2.0-ban is probléma volt, de még a 3.0-ban is ezt tapasztaljuk.
A küldött XLS tartalma pontosan megegyezik az eredeti adattartalommal, a termékdíj számításban sincs semmilyen változás.
Bármilyen más érvénytelenítő számla (amin nincs termékdíj) megfelelően működik.
A számla tétele és az összesítő a számlavégén is megegyezik.

Kérek, választ arra, hogy hol van a probléma.
Köszönöm szépen

Itt egy példa, a TAG jeleket most kicseréltem:

tételsor:
[obligatedForProductFee]true[/obligatedForProductFee]

[lineProductFeeContent]
[productFeeCode]
[productCodeCategory]CSK[/productCodeCategory]
[productCodeValue]E201701[/productCodeValue]
[/productFeeCode]
[productFeeQuantity]-3.0000[/productFeeQuantity]
[productFeeMeasuringUnit]KG[/productFeeMeasuringUnit]
[productFeeRate]60.00[/productFeeRate]
[productFeeAmount]-180.00[/productFeeAmount]
[/lineProductFeeContent]

Összesítés

[productFeeSummary]
[productFeeOperation]DEPOSIT[/productFeeOperation]
[productFeeData]
[productFeeCode]
[productCodeCategory]CSK[/productCodeCategory]
[productCodeValue]E201701[/productCodeValue]
[/productFeeCode]
[productFeeQuantity]-3.0000[/productFeeQuantity]
[productFeeMeasuringUnit]KG[/productFeeMeasuringUnit]
[productFeeRate]60.00[/productFeeRate]
[productFeeAmount]-180.00[/productFeeAmount]
[/productFeeData]
[productChargeSum]-180.00[/productChargeSum]
[/productFeeSummary]

**Comment by NTCA-supporter** [comment]
Kérlek vagy küld el a számla teljes tétel és összegző adatait vagy ha beküldöd a teszt környzetre a számlát és elküldöd a tranzakció azonosítóját akkor azt meg tudom nézni. Köszi

**Comment by NyBela** [comment]
Köszönöm, itt, van:
Eredeti számla X20/547 sorszámú ID:36KC6RMPWJU8OB29 : Ez jó.
Érvénytelenítő számla: X20/548 sorszámú: ID: 36KCAZCFXERIE7YU : WARN
üzenet: INCORRECT_PRODUCT_FEE_CALCULAT
Köszönöm a segítséget.
Itt a file is.
Az azonosító adatokat X.re cseréltem és a TAG jeleket [ ]-re
[?xml version="1.0" encoding="UTF-8"?]
[InvoiceData xsi:schemaLocation="http://schemas.nav.gov.hu/OSA/3.0/data invoiceData.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:base="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns="http://schemas.nav.gov.hu/OSA/3.0/data"]
[invoiceNumber]X20/548[/invoiceNumber]
[invoiceIssueDate]2020-11-26[/invoiceIssueDate]
[completenessIndicator]false[/completenessIndicator]
[invoiceMain]
[invoice]
[invoiceReference]
[originalInvoiceNumber]X20/547[/originalInvoiceNumber]
[modifyWithoutMaster]false[/modifyWithoutMaster]
[modificationIndex]1[/modificationIndex]
[/invoiceReference]
[invoiceHead]
[supplierInfo]
[supplierTaxNumber]
[base:taxpayerId]XXXXXXXX[/base:taxpayerId]
[base:vatCode]X[/base:vatCode]
[base:countyCode]XX[/base:countyCode]
[/supplierTaxNumber]
[supplierName]DEMO2020 Kft[/supplierName]
[supplierAddress]
[base:simpleAddress]
[base:countryCode]HU[/base:countryCode]
[base:postalCode]9700[/base:postalCode]
[base:city]Szombathely[/base:city]
[base:additionalAddressDetail]Hosszú utca 28[/base:additionalAddressDetail]
[/base:simpleAddress]
[/supplierAddress]
[supplierBankAccountNumber]11111111-11111111-11111111[/supplierBankAccountNumber]
[/supplierInfo]
[customerInfo]
[privatePersonIndicator]false[/privatePersonIndicator]
[customerVatData]
[customerTaxNumber]
[base:taxpayerId]XXXXXXXX[/base:taxpayerId]
[base:vatCode]X[/base:vatCode]
[base:countyCode]XX[/base:countyCode]
[/customerTaxNumber]
[/customerVatData]
[customerName]DEMO KERESKEDELMI ES SZOLGALTATO KFT[/customerName]
[customerAddress]
[base:simpleAddress]
[base:countryCode]HU[/base:countryCode]
[base:postalCode]3527[/base:postalCode]
[base:city]MISKOLC[/base:city]
[base:additionalAddressDetail]XXXXXXXXXXXXXXXXX[/base:additionalAddressDetail]
[/base:simpleAddress]
[/customerAddress]
[/customerInfo]
[invoiceDetail]
[invoiceCategory]NORMAL[/invoiceCategory]
[invoiceDeliveryDate]2020-11-26[/invoiceDeliveryDate]
[currencyCode]HUF[/currencyCode]
[exchangeRate]1.000000[/exchangeRate]
[paymentMethod]TRANSFER[/paymentMethod]
[paymentDate]2020-11-26[/paymentDate]
[cashAccountingIndicator]false[/cashAccountingIndicator]
[invoiceAppearance]PAPER[/invoiceAppearance]
[/invoiceDetail]
[/invoiceHead]
[invoiceLines]
[mergedItemIndicator]false[/mergedItemIndicator]
[line]
[lineNumber]1[/lineNumber]
[lineModificationReference]
[lineNumberReference]1[/lineNumberReference]
[lineOperation]MODIFY[/lineOperation]
[/lineModificationReference]
[lineExpressionIndicator]true[/lineExpressionIndicator]
[lineDescription]Fedél 600[/lineDescription]
[quantity]-1.0000[/quantity]
[unitOfMeasure]PIECE[/unitOfMeasure]
[unitPrice]1000.0000[/unitPrice]
[lineAmountsNormal]
[lineNetAmountData]
[lineNetAmount]-1000.00[/lineNetAmount]
[lineNetAmountHUF]-1000.00[/lineNetAmountHUF]
[/lineNetAmountData]
[lineVatRate]
[vatPercentage]0.27[/vatPercentage]
[/lineVatRate]
[lineVatData]
[lineVatAmount]-270.00[/lineVatAmount]
[lineVatAmountHUF]-270.00[/lineVatAmountHUF]
[/lineVatData]
[lineGrossAmountData]
[lineGrossAmountNormal]-1270.00[/lineGrossAmountNormal]
[lineGrossAmountNormalHUF]-1270.00[/lineGrossAmountNormalHUF]
[/lineGrossAmountData]
[/lineAmountsNormal]
[intermediatedService]false[/intermediatedService]
[obligatedForProductFee]true[/obligatedForProductFee]
[lineProductFeeContent]
[productFeeCode]
[productCodeCategory]CSK[/productCodeCategory]
[productCodeValue]E201701[/productCodeValue]
[/productFeeCode]
[productFeeQuantity]-3.0000[/productFeeQuantity]
[productFeeMeasuringUnit]KG[/productFeeMeasuringUnit]
[productFeeRate]60.00[/productFeeRate]
[productFeeAmount]-180.00[/productFeeAmount]
[/lineProductFeeContent]
[/line]
[/invoiceLines]
[productFeeSummary]
[productFeeOperation]DEPOSIT[/productFeeOperation]
[productFeeData]
[productFeeCode]
[productCodeCategory]CSK[/productCodeCategory]
[productCodeValue]E201701[/productCodeValue]
[/productFeeCode]
[productFeeQuantity]-3.0000[/productFeeQuantity]
[productFeeMeasuringUnit]KG[/productFeeMeasuringUnit]
[productFeeRate]60.00[/productFeeRate]
[productFeeAmount]-180.00[/productFeeAmount]
[/productFeeData]
[productChargeSum]-180.00[/productChargeSum]
[/productFeeSummary]
[invoiceSummary]
[summaryNormal]
[summaryByVatRate]
[vatRate]
[vatPercentage]0.27[/vatPercentage]
[/vatRate]
[vatRateNetData]
[vatRateNetAmount]-1000.00[/vatRateNetAmount]
[vatRateNetAmountHUF]-1000.00[/vatRateNetAmountHUF]
[/vatRateNetData]
[vatRateVatData]
[vatRateVatAmount]-270.00[/vatRateVatAmount]
[vatRateVatAmountHUF]-270.00[/vatRateVatAmountHUF]
[/vatRateVatData]
[/summaryByVatRate]
[invoiceNetAmount]-1000.00[/invoiceNetAmount]
[invoiceNetAmountHUF]-1000.00[/invoiceNetAmountHUF]
[invoiceVatAmount]-270.00[/invoiceVatAmount]
[invoiceVatAmountHUF]-270.00[/invoiceVatAmountHUF]
[/summaryNormal]
[summaryGrossData]
[invoiceGrossAmount]-1270.00[/invoiceGrossAmount]
[invoiceGrossAmountHUF]-1270.00[/invoiceGrossAmountHUF]
[/summaryGrossData]
[/invoiceSummary]
[/invoice]
[/invoiceMain]
[/InvoiceData]

**Comment by NTCA-supporter** [comment]
Köszi! Nézem és visszajelzek.

**Comment by NTCA-supporter** [comment]
Megnéztem és valóban nem működik jól a warn. A 3.0 kapcsán amúgy is lesz egy nagyobb warning módosítás. Abba belevesszük ezt is. Köszi a jelzést!

**Comment by NyBela** [comment]
Köszönöm, szépen.

**Comment by NyBela** [comment]
A hiba nem oldódott meg a 2020.12.12.-i frissítéssel sem.

**Comment by NyBela** [comment]
Választ várok továbbra is. Köszönöm.

**Comment by NTCA-supporter** [comment]
Sziasztok!

A bug javításra került már, zárom az issuet. Ha van még kérdés/hiba nyissatok újat kérlek.
Üdv
