### ISSUE TITLE
[Q&A] Fordított ÁFA-s egyszerűsített számla

### ISSUE THREAD

**Issue by timjoe** [nav-gov-hu/Online-Invoice#550]
"SIMPLIFIED" formátumú, csak fordított ÁFA-s tételt tartalmazó számla esetében az alábbi warning-ot kapom:

Az egyszerűsített számla egy vagy több adótartalomhoz tartozó tételsoraiban szereplő bruttó értékek összege eltér az összesítésében a hozzá tartozó adótartalomnál szereplő bruttó összegtől.
Érték: 5315

A vonatkozó XML-részlet:

`<invoiceLines>
<mergedItemIndicator>false</mergedItemIndicator>
<line>
<lineNumber>1</lineNumber>
<advanceData>
<advanceIndicator>false</advanceIndicator>
</advanceData>
<lineExpressionIndicator>true</lineExpressionIndicator>
<lineDescription>Valami</lineDescription>
<quantity>1.000</quantity>
<unitOfMeasure>OWN</unitOfMeasure>
<unitOfMeasureOwn>tábla</unitOfMeasureOwn>
<unitPrice>5315.00</unitPrice>
<unitPriceHUF>5315.00</unitPriceHUF>
<lineAmountsSimplified>
<lineVatRate>
<vatDomesticReverseCharge>true</vatDomesticReverseCharge>
</lineVatRate>
<lineGrossAmountSimplified>5315.00</lineGrossAmountSimplified>
<lineGrossAmountSimplifiedHUF>5315.00</lineGrossAmountSimplifiedHUF>
</lineAmountsSimplified>
</line>
</invoiceLines>
<invoiceSummary>
<summarySimplified>
<vatRate>
<vatDomesticReverseCharge>true</vatDomesticReverseCharge>
</vatRate>
<vatContentGrossAmount>5315.00</vatContentGrossAmount>
<vatContentGrossAmountHUF>5315.00</vatContentGrossAmountHUF>
</summarySimplified>
<summaryGrossData>
<invoiceGrossAmount>5315.00</invoiceGrossAmount>
<invoiceGrossAmountHUF>5315.00</invoiceGrossAmountHUF>
</summaryGrossData>
</invoiceSummary>
`

"NORMAL" formátumú (ugyanilyen tételt tartalmazó) számla esetén nem jön hasonló üzenet.

Mit / hol rontottam el?

**Comment by NTCA-supporter** [comment]
Szia @timjoe 

A teljes számla csak ezt az egy <vatDomesticReverseCharge>true</vatDomesticReverseCharge> line-t tartalmazza?

**Comment by timjoe** [comment]
Igen, ez az egyetlen tételsor a számlában.
Tranzakcióazonosító: 36J9PNJ9F42PK6V3

**Comment by NTCA-supporter** [comment]
Ok, köszi az infót. Utána nézek és jelentkezem.

**Comment by NTCA-supporter** [comment]
Megnéztem és valóban nem működik jól a warn. A 3.0 kapcsán amúgy is lesz egy nagyobb warning módosítás. Abba belevesszük ezt is. Köszi a jelzést!

**Comment by tkelemen73** [comment]
Sziasztok,
ez a jelenség még most is fenn áll. Tudjátok már, hogy mikor lesz javítva?
Ma újra próbáltam, tranzakció azonosító: 37BYLUUJXIBTL7XY
Ez a számla a data példák között megadott számla (3.7.1 példa: Belföldi termékértékesítés egyszerűsített számla, Belfoldi egyszerusitett szamla.xml). Ennél is jön a figyelmeztető üzenet, ugyanúgy az ÁFA mentes tétel összegével van baja. Nem kellene erre figyelmeztetést adni.
üdv
T.

**Comment by SimplifiedSzamla** [comment]
Nem tudom ehhez a problémához tartozik-e, vagy az Én feladásom a hibás. Tudnátok segíteni?

Egyszerűsített számlát adok fel, van rajta TAM-os és AAM-es tétel is.

Kettő WARN-t kapok vissza, mind kettő: INCORRECT_SUMMARY_CALCULATION_VAT_CONTENT_GROSS_AMOUNT_SUMMARY_SIMPLIFIED .

A feladás tételei, összegzői:

      <invoiceLines>
        <mergedItemIndicator>false</mergedItemIndicator>
        <line>
          <lineNumber>1</lineNumber>
          <advanceData>
            <advanceIndicator>false</advanceIndicator>
          </advanceData>
          <lineExpressionIndicator>true</lineExpressionIndicator>
          <lineDescription>EEEE1</lineDescription>
          <quantity>15.000</quantity>
          <unitOfMeasure>PIECE</unitOfMeasure>
          <unitPrice>8500.00</unitPrice>
          <unitPriceHUF>8500.00</unitPriceHUF>
          <lineAmountsSimplified>
            <lineVatRate>
              <vatExemption>
                <case>TAM</case>
                <reason>Tárgyi adómentes értékesítés</reason>
              </vatExemption>
            </lineVatRate>
            <lineGrossAmountSimplified>127500.00</lineGrossAmountSimplified>
            <lineGrossAmountSimplifiedHUF>127500.00</lineGrossAmountSimplifiedHUF>
          </lineAmountsSimplified>
        </line>
        <line>
          <lineNumber>2</lineNumber>
          <advanceData>
            <advanceIndicator>false</advanceIndicator>
          </advanceData>
          <lineExpressionIndicator>true</lineExpressionIndicator>
          <lineDescription>EEEE2</lineDescription>
          <quantity>15.000</quantity>
          <unitOfMeasure>PIECE</unitOfMeasure>
          <unitPrice>3700.00</unitPrice>
          <unitPriceHUF>3700.00</unitPriceHUF>
          <lineAmountsSimplified>
            <lineVatRate>
              <vatExemption>
                <case>AAM</case>
                <reason>A 2007. évi CXXVII. tv. XIII. fejezete alapján alanyi adómentességet alkalmazok.</reason>
              </vatExemption>
            </lineVatRate>
            <lineGrossAmountSimplified>55500.00</lineGrossAmountSimplified>
            <lineGrossAmountSimplifiedHUF>55500.00</lineGrossAmountSimplifiedHUF>
          </lineAmountsSimplified>
        </line>
      </invoiceLines>
      <invoiceSummary>
        <summarySimplified>
          <vatRate>
            <vatExemption>
              <case>TAM</case>
              <reason>Tárgyi adómentes értékesítés</reason>
            </vatExemption>
          </vatRate>
          <vatContentGrossAmount>127500.00</vatContentGrossAmount>
          <vatContentGrossAmountHUF>127500.00</vatContentGrossAmountHUF>
        </summarySimplified>
        <summarySimplified>
          <vatRate>
            <vatExemption>
              <case>AAM</case>
              <reason>A 2007. évi CXXVII. tv. XIII. fejezete alapján alanyi adómentességet alkalmazok.</reason>
            </vatExemption>
          </vatRate>
          <vatContentGrossAmount>55500.00</vatContentGrossAmount>
          <vatContentGrossAmountHUF>55500.00</vatContentGrossAmountHUF>
        </summarySimplified>
        <summaryGrossData>
          <invoiceGrossAmount>183000.00</invoiceGrossAmount>
          <invoiceGrossAmountHUF>183000.00</invoiceGrossAmountHUF>
        </summaryGrossData>
      </invoiceSummary>

**Comment by tkelemen73** [comment]
Úgy gondolom, reprodukáltad a jelenséget, ami továbbra is hibás működést mutat...

**Comment by SimplifiedSzamla** [comment]
A probléma jelentkezik akkor is, ha csak egy AAM-es tétel van az egyszerűsített számlán.
Van esetleg valami információ arról, hogy mikor készül el javítás?
Köszönöm

**Comment by klammert** [comment]
Hi, I'm still having this issue. When will there be a solution?

**Comment by Tilupan** [comment]
Nálunk is fennáll a probléma. A párom alanyi adómentes. Ezek szerint ezzel a hibaüzenettel nem kell foglalkoznunk?

**Comment by NTCA-supporter** [comment]
Sziasztok!

A hiba javításra került, így zárom az issuet. Ha van még kérdés/hiba nyissatok újat kérlek és küldjetek számla adatokat.
Üdv
