### ISSUE TITLE
[Q&A] vatDomesticReverseCharge=true egynél többször szerepeltetése a számla összesítőben

### ISSUE THREAD

**Issue by laladisc** [nav-gov-hu/Online-Invoice#552]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
A #533 issue nyomán fejlesztésbe kedtünk és ezzel kapcsolatban felmerült egy kérdésünk. Amennyiben, a számlán két FAD-os tétel szerepel, amelyek áfakulcsa ugyan FAD, de megnevezésében különbözőek (pl (FAD) -  Fordított adózás és (FAD) - Fordítottan adózó előleg), ennek megfelelően a számlán az áfa összesítőben is külön soron kerül feltüntetésre, elfogadható e az adatszolgáltatás során, hogy ha ezt a két FAD-os tételt az összesítőben nem összevontan, hanem szintén két tételbe küldjük. Az eddig beküldött teszt számlákra nem kaptunk WARN-t.

Az adatszolgáltatás összesítője:
`<summaryNormal>
          <summaryByVatRate>
            <vatRate>
              <vatDomesticReverseCharge>true</vatDomesticReverseCharge>
            </vatRate>
            <vatRateNetData>
              <vatRateNetAmount>101400</vatRateNetAmount>
              <vatRateNetAmountHUF>101400</vatRateNetAmountHUF>
            </vatRateNetData>
            <vatRateVatData>
              <vatRateVatAmount>0</vatRateVatAmount>
              <vatRateVatAmountHUF>0</vatRateVatAmountHUF>
            </vatRateVatData>
            <vatRateGrossData>
              <vatRateGrossAmount>101400</vatRateGrossAmount>
              <vatRateGrossAmountHUF>101400</vatRateGrossAmountHUF>
            </vatRateGrossData>
          </summaryByVatRate>
          <summaryByVatRate>
            <vatRate>
              <vatDomesticReverseCharge>true</vatDomesticReverseCharge>
            </vatRate>
            <vatRateNetData>
              <vatRateNetAmount>-100000</vatRateNetAmount>
              <vatRateNetAmountHUF>-100000</vatRateNetAmountHUF>
            </vatRateNetData>
            <vatRateVatData>
              <vatRateVatAmount>0</vatRateVatAmount>
              <vatRateVatAmountHUF>0</vatRateVatAmountHUF>
            </vatRateVatData>
            <vatRateGrossData>
              <vatRateGrossAmount>-100000</vatRateGrossAmount>
              <vatRateGrossAmountHUF>-100000</vatRateGrossAmountHUF>
            </vatRateGrossData>
          </summaryByVatRate>
          <invoiceNetAmount>1400</invoiceNetAmount>
          <invoiceNetAmountHUF>1400</invoiceNetAmountHUF>
          <invoiceVatAmount>0</invoiceVatAmount>
          <invoiceVatAmountHUF>0</invoiceVatAmountHUF>
        </summaryNormal>`

**Comment by nbeeps2** [comment]
Az én meglátásom alapján igen, melyet 3 dolog támaszt alá:
1. nem kapsz rá most sem WARN-t
2. az is előfordulhat, hogy a két ÁFA-kulcs rövidmegnevezése is különböző, de ettől még lehet mindkettő fordított ÁFA-s (pl. FAD, FAO). Tehát, ha van a számlán egy FAD és egy FAO kulcs, az KETTŐ darab ÁFA kulcs, csak mindkettő jellege szerint fordított ÁFA-s, de ez csak egy tulajdonsága magának az ÁFA kulcsnak, ez a tulajdonság van jelölve vatDomesticReverseCharge mező alatt.
3. Más esetben is, amikor "0%" az ÁFA (pl. adómentesség, ÁFA tv. hatályán kívüli, stb.), is előfordulhat elméleti síkon, hogy különböző számla záradék szövegek kerülnek az adott tételsorhoz.

**Comment by NTCA-tax** [comment]
Az adatszolgáltatásban amennyiben ugyanaz a vatRateType case, akkor azokat össze lehet vonni. Tehát például ha több FAD, TAM stb. tételsor van, akkor az összevonható. Így ha még az ok más is lehet, ettől még összevonható ugyanazon case. Ezt a dokumentációban is meg fogjuk jeleníteni. Ugyanakkor ez egy lehetőség, nem kötelezettség.

**Comment by laladisc** [comment]
Köszönöm @NTCA-tax , akkor ha ez így elfogadható, maradnék a külön soron szerepeltetésnél, igazodva a számlaképhez.

**Comment by NTCA-tax** [comment]
OK, akkor zárom az issue-t.
