### ISSUE TITLE
[DEV support]Közmű számla módosítása, érvénytelenítése

### ISSUE THREAD

**Issue by GOnSzlaDev** [nav-gov-hu/Online-Invoice#553]
Hogy kell előállítani egy közmű számlának (batchInvoice) a módosító vagy érvénytelenítő számláját?

Beküldtük az eredeti elszámolószámlát, a batchIndex=1-ben az originalInvoiceNumber-ben maga az elszámoló számla,  ugyanaz, mint az invoiceNumber, invoiceOperation=MODIFY, és még volt 1-2 részszámla. Ezt a számlát befogadta a NAV tesztrendszer.  Ez a számla a mi rendszerünkben alapszámla, ahogy ez a dokumentációból is sejthető ("Adatszolgáltatáskor az alapvető probléma, hogy egy számla nem lehet egyszerre alapszámla és módosító számla is."  153.oldal)

Lesztornóztuk az elszámolószámlát. Erre úgy állítottuk elő az XML-t, hogy az invoiceNumber a stornó számla, és a batchIndex=1-ben az originalInvoiceNumber-ben az eredeti elszámoló számla. Sajnos erre 2 hibát kapunk:
MULTIPLE_INVOICES_FOUND - 1 ERROR:A hivatkozott alapszámla egynél többször szerepel érvényesként a rendszerben. 
INVALID_INVOICE_REFERENCE - 1 ERROR:A módosítás vagy érvénytelenítés olyan okiratra hivatkozik, amire vonatkozóan nem történt adatszolgáltatás.

Értem a második hibát, azért van, mert az eredeti elszámoló számla nem CREATE-ként, hanem MODIFY-ként ment be. De nem tudom, hogy kell feloldani. Hogy kell beküldeni egy elszámoló számla módosítását, érvénytelenítését?
Az első hibát (MULTIPLE...) pedig nem is értem. de lehet, hogy a második hiba feloldása megoldja az elsőt is.

Előre is köszönöm a mihamarabbi választ!
Üdv!

**Comment by NTCA-supporter** [comment]
Szia @GOnSzlaDev !

Ez egy jogos és fogós kérdés.
Leellenőriztem, valóban ez a működés jelenleg. Kitalálunk valamit az ERROR nélküli beküldésre és visszajelzek.

Üdv

**Comment by NTCA-supporter** [comment]
Szia @GOnSzlaDev !
Nem láttam a fától az erdőt..
Az interfész dokumentáció 2.8 fejezetének utolsó bekezdése pont erről szól.
Tehát ilyen esetben nem az elszámolószámlát kell módosítanod, hanem vagy a korábbi rész számlákat (negatív irányú módosítánál), vagy egy új számlát kell kiállítani create-ként új invoiceNumberrel (pozitív iránynál).
Erről @NTCA-tax is megerősített, így ez adószakmai oldalról is az elvárt megoldás.
Üdv

**Comment by GOnSzlaDev** [comment]
Szia @NTCA-supporter! 
Köszönöm a választ. A 2.8 fejezet ebben a formában, tartalommal 12.07 óta elérhető. Azóta olvastam már.
Már csak az a kérdés, hogy a felhasználóink is így gondolják-e. (Sajnos egyelőre nem.)
Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet. Ha van még kérdés nyisd újra kérlek.
Üdv

**Comment by EnergiaSZLA** [comment]
Sziasztok!

A fenti problèmàval küzdünk storno szàmla beküldèsènèl, az alàbbi üzenetett kapjuk:

MULTIPLE_INVOICES_FOUND - 1 ERROR:A hivatkozott alapszámla egynél többször szerepel érvényesként a rendszerben.
INVALID_INVOICE_REFERENCE - 1 ERROR:A módosítás vagy érvénytelenítés olyan okiratra hivatkozik, amire vonatkozóan nem történt adatszolgáltatás.

Sikerült megoldàst talàlni a Storno beküldèsère? Hogy ne dobja aza alàbbi üzenetet?

**Comment by GOnSzlaDev** [comment]
Szia!
Különböző kerülő megoldásokat alkalmaztunk. 
1. Ha egy elszámoló számla pluszos, akkor azt nem batchInvoice-ként küldjük be, hanem normál számlaként. Így a pluszos elszámolószámlának nincs gond a stornó számlájával sem.
2. Ha az elszámoló számla mínuszos, akkor az nyilván batchInvoce-ként megy be. Viszont ennek a stornóját egy új batchInvoice-ként küldjük be, ahol az originalInvoiceNumber-ben nem hivatkozunk az eredeti számlára, hanem maga a stornó az originalInvoiceNumber.
Ezek valószínű nem elegáns megoldások, de rákényszerített a szoftver. Nem kaptunk támogatást ezen probléma megoldásra.

**Comment by EnergiaSZLA** [comment]
Köszönöm szèpen a gyors vàlaszt. Sajnos mi sem làttunk màs megoldàst.

**Comment by EnergiaSZLA** [comment]
A Storno szàmlàt MODIFY vagy STORNO-val külditek?

**Comment by GOnSzlaDev** [comment]
Természetesen MODIFY. Hiszen a sztornó számlában önmaga az original, és nem hivatkozunk az eredetire. Így nem lenne indokolt, hogy STORNO legyen. Sőt, attól tartok, azt visszavágná.
