### ISSUE TITLE
[Q&A]queryServiceMetrics/metric hiba, Metrika értéke hiányzik

### ISSUE THREAD

**Issue by tkelemen73** [nav-gov-hu/Online-Invoice#554]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Tesztrendszerről lekért metrikák értékei (metricValues) hiányoznak, v2-nél is és v3-nál is.
https://api-test.onlineszamla.nav.gov.hu/metricService/v2/queryServiceMetrics/metric
https://api-test.onlineszamla.nav.gov.hu/metricService/v3/queryServiceMetrics/metric
Az éles rendszeren jól működik, csak a teszten tűnt el a válaszból az adat.
https://api.onlineszamla.nav.gov.hu/metricService/v2/queryServiceMetrics/metric

**Comment by NTCA-supporter** [comment]
Köszi a jelzést!
Már vizsgáljuk a problémát. Ha javult, akkor jelzek, addig maradjon nyitva az issue.
Üdv

**Comment by tkelemen73** [comment]
Sziasztok, látható, hogy mi a probléma oka? Azt látom, hogy most már 3.0-s fejléccel jön vissza a response, de adat még mindig nincs benne. Látható, hogy mikor, melyik verzióban fog megjavulni?
Köszi!
Üdv
T.

**Comment by wrobi** [comment]
Mai napon már az éles rendszer is értékek nélkül adja vissza a metrikát. Úgy látszik erre a szolgáltatásra sem érdemes építeni, pedig ez alapján szeretném eldönteni, hogy milyen timeout értékekkel indítsam útjára a kéréseket.

**Comment by tkelemen73** [comment]
Szuper, sikerült élesíteni azt, amire már majd egy jónapja jeleztem, hogy a tesztben sem jó, a 2.0-ban sem...

**Comment by skovacs70** [comment]
Sziasztok,
Még most sem ad vissza egyik metrika sem értékeket (nincsenek "value" tag-ek). Valami központi hiba lehet?
Mi is használnánk ezt a szolgáltatás, de így elég nehéz lesz.

@NTCA-developer rá tudnál nézni?

Köszönöm.

**Comment by NTCA-supporter** [comment]
Sziasztok!

A javítás már folyamatban, kis türelmet kérünk amíg kikerült teszt/éles rendszerig.

Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

Úgy tűnik megvan mi okozta a hibát.
Kérlek ellenőrizzétek és ha rendben találjátok, zárható az issue.

Köszi a türelmet!
Üdv

**Comment by NTCA-supporter** [comment]
A v3-as verzió szintén elérhető lett, így már az is figyelhető.

**Comment by tkelemen73** [comment]
Sziasztok, ellenőriztem, élesen is és a teszten is működik 2.0-val is és 3.0-val is. Viszont az az érdekes, hogy a válaszidők a 3.0-s verziónál nagyobb értékeket mutat, mint a 2.0-s, mindkét rendszeren. Pl. responseTimeAverageMsManageInvoice 18:12-kor 2.0-nál 49.20, 3.0-nál 68.80, de a más időpontnál is hasonló differenciák vannak. Nem jelentős érték egyik sem, félre ne értsetek, de valamiért a 3.0 lassabbnak tűnik, amikor elvileg ott még nem nagyon van mozgás, bár ezt ti jobban látjátok.
Üdv

**Comment by vectorkovacspeter** [comment]
Nekem nem kerek még mindig, mert a https://api-test.onlineszamla.nav.gov.hu/metricService/v3/queryServiceMetrics/metric pl minden metrikát lead egyben, és megy a lista is a https://api-test.onlineszamla.nav.gov.hu/metricService/v3/queryServiceMetrics/list címen, viszont, a soksi alapján rá lehetne kérdezni konkrét metrikára is, ami viszont nem megy pl.: https://api-test.onlineszamla.nav.gov.hu/metricService/v3/queryServiceMetrics/metric/responseTimeAverageMsQueryInvoiceData

**Comment by NTCA-supporter** [comment]
Sziasztok!

Hamarosan elkészül az adott metrikát lekérdező oldal elérhetősége is.

Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ez közben megjavult szerintem, kérlek ellenőrizzétek és zárjátok az issuet ha rendben van.
Üdv

**Comment by skovacs70** [comment]
Szia, @NTCA-supporter 
Igen, úgy néz ki, működik mindegyik.
Köszönjük.

**Comment by NTCA-supporter** [comment]
Köszi a visszajelzést, zárom az issuet.
Üdv

**Comment by sinick2** [comment]
@NTCA-supporter Tisztelt fejlesztők! Figyelik a lezárt issue-kat is? (Nem nyitnék újat ugyanarról a témáról, ha nem muszáj.)
