### ISSUE TITLE
QueryInvoiceDigestRequest kérésem érvénytelen. Mit rontok el?

### ISSUE THREAD

**Issue by moferi** [nav-gov-hu/Online-Invoice#555]
Alábbi kérésre a lenti választ kapom. Mit rontok el a kérésben, hogy "Érvénytelen kérés!" a válasz? Köszönöm!

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
`<ns2:QueryInvoiceDigestRequest xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common">`
`    <header>`
`        <requestId>1606643891104</requestId>`
`        <timestamp>2020-11-29T09:58:11.107Z</timestamp>`
`        <requestVersion>3.0</requestVersion>`
`        <headerVersion>1.0</headerVersion>`
`    </header>`
`    <user>`
`        <login>ccccccccccccccc</login>`
`        <passwordHash cryptoType="SHA2-512">8841D47215934E15D8C5ADAE52E9E4AA23151494A4ABDA8ECA65A6C119B8CA477C486F2D1E1BC607877A45835E44151223B2F1C2D585DC9E97DDEFB8B573F918</passwordHash>`
`        <taxNumber>22222222</taxNumber>`
`        <requestSignature cryptoType="SHA3-512">6C4F7AF34347A52118468B3AE527929742DF2561DFA5BAB12E7D00987BC690C8FC3047863A6FC58323AA4C9AF8FBB51C0946EA40FE54FB1D4A86DB7209EAD5DD</requestSignature>`
`    </user>`
`    <ns2:software>`
`        <ns2:softwareId>HUxxxx2222222200xy</ns2:softwareId>`
`        <ns2:softwareName>dddddd</ns2:softwareName>`
`        <ns2:softwareOperation>LOCAL_SOFTWARE</ns2:softwareOperation>`
`        <ns2:softwareMainVersion>x.y</ns2:softwareMainVersion>`
`        <ns2:softwareDevName>eeeeeeeeeee</ns2:softwareDevName>`
`        <ns2:softwareDevContact>eeeeeee@gmail.com</ns2:softwareDevContact>`
`        <ns2:softwareDevCountryCode>HU</ns2:softwareDevCountryCode>`
`        <ns2:softwareDevTaxNumber>22222222-2-13</ns2:softwareDevTaxNumber>`
`    </ns2:software>`
`    <ns2:page>1</ns2:page>`
`    <ns2:invoiceDirection>INBOUND</ns2:invoiceDirection>`
`    <ns2:invoiceQueryParams>`
`        <ns2:mandatoryQueryParams>`
`            <ns2:invoiceIssueDate>`
`                <ns2:dateFrom>2020-11-01</ns2:dateFrom>`
`                <ns2:dateTo>2020-11-28</ns2:dateTo>`
`            </ns2:invoiceIssueDate>`
`        </ns2:mandatoryQueryParams>`
`    </ns2:invoiceQueryParams>`
`</ns2:QueryInvoiceDigestRequest>`

---------------------------------------
Válasz:

`<GeneralExceptionResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">
<funcCode>ERROR</funcCode>
<errorCode>OPERATION_FAILED</errorCode>
<message>Érvénytelen kérés!</message>
</GeneralExceptionResponse>`

Köszönöm!

**Comment by KMGY100** [comment]
Hasonlítsd össze ezzel

https://github.com/nav-gov-hu/Online-Invoice/blob/master/sample/API%20sample/queryInvoiceDigest_outbound_query_params.xml

**Comment by NTCA-supporter** [comment]
Szia @moferi !
Szerintem az, hogy a queryInvoiceData végpontot hívtad meg invoiceDigest-es request body-val.
Üdv

**Comment by moferi** [comment]
Köszönöm a segítséget!
