### ISSUE TITLE
[Q&A]  Online Invoice Test Tool XML validálás

### ISSUE THREAD

**Issue by boxi78** [nav-gov-hu/Online-Invoice#556]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Szia!

Szeretném kérdezni, hogyan lehet az Online Invoice Test Tool-lal validálni egy XML-t?
A hivatalosan közzétett API példák közül sem tudok egyet sem validálni, az alábbi hibát kapom vissza:

"Call helper:C:\Program Files (x86)\Online Invoice Test Tool\OnlineInvoiceTool_v1.1.exe -xmlvalidate -xmlfile=E:\NAV\3.0\Peldak\tokenExchange.xml -xsdfile=E:\NAV\3.0\Semak\invoiceApi.xsd
src-resolve: Cannot resolve the name 'common:AtomicStringType32' to a(n) 'type definition' component.
XML OK"

Köszönöm!

**Comment by renced42** [comment]
Kedves @boxi78 
Másold az XSD-ket egy mappába. (Figyelem a Common namesapcehez tartozó common.xsd-t külön projektből kell letölteni a GitHub-ról)

Aztán az XSD fájlokban az import elemeket egészítsd ki az schemaLocation  attribútummal megadva az elérési útvonalakat.

pl:
<xs:import namespace="http://schemas.nav.gov.hu/NTCA/1.0/common" schemaLocation="common.xsd"/>
<xs:import namespace="http://schemas.nav.gov.hu/OSA/3.0/base" schemaLocation="invoiceBase.xsd"/>

Ezután tallózd ki az XML-t és az XSD-t a teszt toolban válassz rágiógombot majd és kész.

![image](https://user-images.githubusercontent.com/44041065/100552909-9a44ae00-328a-11eb-8360-1985deadae75.png)

**Comment by boxi78** [comment]
Köszönöm!
És ezt pontosan hol találom? _"Figyelem a Common namesapcehez tartozó common.xsd-t külön projektből kell letölteni a GitHub-ról"_

**Comment by renced42** [comment]
> Köszönöm!
> És ezt pontosan hol találom? _"Figyelem a Common namesapcehez tartozó common.xsd-t külön projektből kell letölteni a GitHub-ról"_

Innen:
https://github.com/nav-gov-hu/Common

**Comment by boxi78** [comment]
Összes XSD egy mappában, invoiceApi.XSD-ben benne a namespace hivatkozás, és a példa tokenExchange.xml-t próbálom validálni.
![image](https://user-images.githubusercontent.com/50459341/100579342-58e0ec80-32e4-11eb-88e9-2a4f2de3cd44.png)

**Comment by boxi78** [comment]
Ugyanez a 2.0-ás verziónál szépen működik.
![image](https://user-images.githubusercontent.com/50459341/100589012-d01d7d00-32f2-11eb-8a01-036cb1eff9db.png)

**Comment by renced42** [comment]
Kedves @boxi78

A képen látszik, hogy ezt a lépést nem tetted meg:

Aztán az XSD fájlokban az import elemeket egészítsd ki az schemaLocation attribútummal megadva az elérési útvonalakat.

pl:
<xs:import namespace="http://schemas.nav.gov.hu/NTCA/1.0/common" **schemaLocation="common.xsd"**/>
<xs:import namespace="http://schemas.nav.gov.hu/OSA/3.0/base" **schemaLocation="invoiceBase.xsd"**/>

**Comment by boxi78** [comment]
Valóban. Így már működik.
Köszönöm.
