### ISSUE TITLE
QueryInvoiceDataRequest - Helytelen kérés! - közösségen belüli és 3.országbeli esetén

### ISSUE THREAD

**Issue by NyBela** [nav-gov-hu/Online-Invoice#557]
A kiállított számla tételék lekérdezése a belföldi számlák esetén működik.
Két átadott paraméterrel: az irány és a számla száma. 
(TAG karakter cserélve [ ] ) 
pl.
[invoiceNumberQuery]
[invoiceNumber]X20/575[/invoiceNumber]
[invoiceDirection]OUTBOUND[/invoiceDirection]
[/invoiceNumberQuery]
Ez így rendben is van, működik.

De a Közösségen belüli és a 3. országbeli esetében, ugyanez a küldés, már hibával jön vissza.
[result][funcCode]ERROR[/funcCode]
[errorCode]INVALID_REQUEST[/errorCode]
[message]Helytelen kérés![/message]
[/result]
majd az üzenet:
[message]Request body contains on line: [-1] and column: [-1] error: [cvc-complex-type.2.4.b: The content of element 'customerTaxNumber' is not complete. 
One of '{"http://schemas.nav.gov.hu/OSA/3.0/base":taxpayerId}' is expected.][/message]
[/ns2:technicalValidationMessages][ns2:technicalValidationMessages][validationResultCode]ERROR[/validationResultCode]
[validationErrorCode]SCHEMA_VIOLATION[/validationErrorCode]
[message]Request body contains on line: [-1] and column: [-1] error: [cvc-complex-type.2.4.d: Invalid content was found starting with element 'communityVatNumber'. 
No child element is expected at this point.][/message][/ns2:technicalValidationMessages]
[/ns2:GeneralErrorResponse]

A specifikációban nem találok utalást arra, hogy más paramétert is meg kellene adni ezekben az esetekben.
Segítséget kérek, köszönöm.

**Comment by NTCA-supporter** [comment]
Szia @NyBela !
Köszi a jelzést. A #470 technikaliag ugyanez, az új vevői adatok lekezelése nem megfelelő nálunk a queryInvoiceData-nal.
Javítani fogjuk. Ezt az issuet zárom, a #470-ben fogom jelezni, ha kikerül a javítás teszt környezetre.
Üdv
