### ISSUE TITLE
[DEV support] 3.0 Digest nem adja vissza a vevő csoport tag adószámát

### ISSUE THREAD

**Issue by laladisc** [nav-gov-hu/Online-Invoice#559]
Sziasztok!

Tesztelés során az alábbi hibára bukkantunk.
3.0-val felküldött csoportos adóalany részére kiállított számlák esetében a 3.0-ás digest nem adja vissza a customerGroupMemberTaxNumber node-ot. Ha ugyanazt a számlát 2.0-val küldöm fel, akkor a 3.0-ás digest tartalmazza a csoport tag adószámát. Mind a két beküldött XML tartalmazza a csoport tag adószámot is, web-es felületen is minden esetben látszik hogy ki van töltve az adat.

**Comment by NTCA-supporter** [comment]
Szia @laladisc !
Küldj kérlek azonosítót, hogy könnyebb legyen a nyomozás.
Köszi

**Comment by laladisc** [comment]
Szia @NTCA-supporter !

A 3.0-val küldött számla tranzakciós azonosítója: 36Q2MFY8Y33WPRFJ
A 2.0-val küldött számla tranzakciós azonosítója: 36Q2WQUV7GR868FB

A 3.0-ás digest kérés sorszáma: K20_XY_JUM20201130103522
A digesten belül 3 számla található, az utolsó kettő számla ugyanannak a csoportos adóalanynak készült, mind a két esetben ki volt töltve a csoport tag adószáma, de csak annál a számlánál kapom vissza, amelyiket 2.0-val küldtem fel.

**Comment by NTCA-supporter** [comment]
Köszi!
Valami trükkös  dolog lehet, mert amíg elküldted addig küldtem be csoporttagos számlát és nekem jó volt minden, de látom, hogy a te esetedben valóban nem oké.
Jelzek ha jutottam valamire.

**Comment by NTCA-supporter** [comment]
Szia @laladisc !

Valóban nálnunk volt a hiba. Javítani fogjuk.
Addig maradhat nyitva.
Üdv

**Comment by NTCA-supporter** [comment]
Szia @laladisc !
Ez közben szerintem javításra került, kérlek ellenőrizd.
Üdv

**Comment by laladisc** [comment]
Szia @NTCA-supporter !

Mostmár rendben vissza adja a csoport tag adószámát is.

**Comment by NTCA-supporter** [comment]
Szuper!
Köszi a jelzést!
