### ISSUE TITLE
[Q&A] Csoportos adóalanyiság

### ISSUE THREAD

**Issue by izll** [nav-gov-hu/Online-Invoice#560]
Kedves @NTCA-supporter!

Cégcsoportunk csoportos adóalany és a tagok egymás között állítanak ki számlát. A számlákban a tételeknek az Áfa tv. 8.§ és 85/A.§ szerint áfa nem kerül felszámításra, ez a 3.0-ás specifikáció alapján a vatExemption, vatOutOfScope, vatAmountMismatch egyik kategóriájába se illik bele. Arról szeretnék információt kérni, hogy melyik kategóriába sorolhatom a tételeket?
Másik problémánk, hogy az előbb említett számláknál az eladó és a vevő adószáma ugyanaz, és ezért a 2.0-ás adatszolgáltatásnál hibát kapunk, hiába van kitöltve a csoport tag adószáma, ezt eddig úgy oldottuk meg, hogy csak a tagok adószámát adtuk meg az adatszolgáltatás során. Lehet-e rá számítani, hogy ezt a problémát orvosolják?

Köszönöm előre is a válaszokat!

**Comment by laladisc** [comment]
A mi ügyfeleink között is van csoportos adóalany. Az egymás közötti ügyletekről nem számlát, hanem számviteli bizonylatot állítanak ki, amelyről nem történik adatszolgáltatás.

**Comment by nbeeps2** [comment]
@laladisc írta meg a lényeget. A te esetedben nem számlát kell kiállítani, hanem számviteli bizonylatot. A számlán a vevőnek nem lehet 4-es az adószáma, tehát az 5-ös adószámot (CSASZ) kell feltüntetni, a kiállító és a vevő adószáma pedig nem lehet azonos. Sajnos nagyon sok tévhit és rossz beidegződés kering a csoportos adóalanyiság témakörben, melyek közül az egyik, amit Te is írtál, a másik pedig, amikor azzal jönnek, hogy a vevő mindenképp megköveteli, hogy legyen mindkét adószáma feltüntetve a számlán, holott ott csak a CSASZ első 8 karaktere a kötelező.

**Comment by NTCA-tax** [comment]
Az adómentességre vonatkozó kérdésre a rövidesen publikálásra kerülő interfész specifikáció módosítást érdemes megvárni. Minden esethez adunk jogszabályi hivatkozást (amennyiben az egyértelműen meghatározható) és bővebb leírást példa esetekkel. A dokumentációnak ez a része remélhetőleg megválaszolja ezt a kérdésedet.

A csoportos adóalany esetében nincs csoporton belüli számlakiállítás az Áfa törvény alapján. Az Áfa törvény egy adóalanynak tekinti a csoportot, ezért az Áfa esetében nem értelmezhető a számla kiállítása. Természetesen bizonylatot ki kell állítani, mivel minden más tekintetben nem lehet önálló entitásnak nevezni. De ezt a témát szerintem már többször megbeszéltük több issue-ban.

A fentiek miatt ezt az issue-t lezárom. Amennyiben felmerülne még kérdés, akkor új issue-t nyissál.
