### ISSUE TITLE
[DOC] CUSTOMER_DATA_NOT_EXPECTED

### ISSUE THREAD

**Issue by hosszuful** [nav-gov-hu/Online-Invoice#561]
**A hibás dokumentum neve / Document name containing the error**
Fájlnév vagy hostolt URL / File name or hosted URL.
Online Szamla_interfesz specifikáció_HU_v3.0.pdf

**Oldalszám / Page number**
A hibát tartalmazó oldal száma / Page number containing the error.
165.oldal 24.pont / 170. oldal 24.pont ellentmond a 94.oldal sémaleírással 

**A dokumentációs hiba leírása / Description of the documentation error**
Rövid és tömör összefoglalása a hibának. / A clear and concise description of the summary of the error.
A 94.oldal customerInfo elem customerName, customerAddress kötelezőnek van jelölve, de magánszemély megadása esetén a 165. oldal / 170. oldal 24. pontjának megfelelő üzenetet (CUSTOMER_DATA_NOT_EXPECTED) kapom, ami szerint ezek a mezők nem tölthetőek, tehát nem is lehetnek kötelezőek.

**Comment by NTCA-supporter** [comment]
Jogos, javítani fogjuk, köszi.

**Comment by NTCA-supporter** [comment]
Javítottuk a leírást. Zárom az issuet, köszi a megjegyzést mégegyszer.
Üdv
