### ISSUE TITLE
Számla megjelenési formája   UNKNOWN   ?

### ISSUE THREAD

**Issue by KMGY100** [nav-gov-hu/Online-Invoice#562]
@NTCA-tax  !
@NTCA-developer !
A doksiban ez áll a számla UNKNOWN  megjelenési formája alatt:
"""Az „UNKNOWN” érték például abban az esetben lehet használatos az adatszolgáltatásban, ha a számlázó szoftver a számla kiállításakor még nem ismeri vagy nem képes azonosítani a számla megjelenési formáját."""

Az Áfa törvény 259. § 5. pontjában ez áll:
"""5.   elektronikus számla: az e törvényben előírt adatokat tartalmazó számla, amelyet elektronikus formában bocsátottak ki és fogadtak be;"""

Vagyis, értelmezésem szerint:
a számlázó szoftver a számla kiállításakor még nem ismeri  a számla megjelenési formáját, illetve a kibocsájtás módját, ha
eladó ( a számla kiállítója) nem döntötte el hogy személyesen vagy pl. egy email mellékletként (vagy más módon) adja át a számlát  a vevőnek. (ebben az esetben nincs szó Hash-elésről)

**Ha  UNKNOWN a megjelenési forma az adatszolgáltatásban, akkor a számla kibocsájtása bármilyen formában megtörténhet.
Online Szamla_interfesz specifikáció_HU_v3.0   szerint helyes az állításom.**

Jól látom ? Helyes az állításom ?

**Comment by nbeeps2** [comment]
Ha szó szerint vesszük az UNKNOWN leírását, akkor igazából szinte minden esetben a UNKNOWN-t kellene megadni ;) ...mármint, ha az április NAV közleményből indulunk ki... A programmal kiállítok egy papír alapú számlát, ki is nyomtatom azt, de utána azt a kiállító PDF-ben küldi meg a vevőnek...

**Comment by KMGY100** [comment]
@nbeeps2 
Újra átolvasva a NAV közleményt:
- Ha a számla kiállítója ELEKTRONIC megjelenési formát választ (Hash-eli a PDF állományt)  és
  email mellékletben adja át a vevőnek a számlát. ( a Hash kód az állomány nevében szerepel ! )
  DE a vevő miután megkapta az email-t, a számlát, azt kinyomtatja  viszont a PDF állomány
  archiválásával (megőrzésével) már nem foglalkozik ,  esetlegesen törli is a kapott email-t és így a
  számla PDF állományát is. Mert Ő, a számla befogadója papír alapon őrzi a számlákat,
  (holott neki is elektronikusan kellene őrizni).

Ebben az esetben a számla befogadót terhelő büntetés mértéke , esetleg annak elengedése kizárólag
a NAV ellenőrzés szigorán múlik. 

Ezzel azt próbáltam érzékeltetni, hogy a számla kiállítója ( aki teljes mértékben helyesen jár el )
veszélybe sodorhatja a számla befogadóját ( aki egy átlagos vállalkozó, vállalkozás )

**Comment by Rossi73** [comment]
> 
> 
> @nbeeps2
> Újra átolvasva a NAV közleményt:
> 
>     * Ha a számla kiállítója ELEKTRONIC megjelenési formát választ (Hash-eli a PDF állományt)  és
>       email mellékletben adja át a vevőnek a számlát. ( a Hash kód az állomány nevében szerepel ! )
>       DE a vevő miután megkapta az email-t, a számlát, azt kinyomtatja  viszont a PDF állomány
>       archiválásával (megőrzésével) már nem foglalkozik ,  esetlegesen törli is a kapott email-t és így a
>       számla PDF állományát is. Mert Ő, a számla befogadója papír alapon őrzi a számlákat,
>       (holott neki is elektronikusan kellene őrizni).
> 
> 
> Ebben az esetben a számla befogadót terhelő büntetés mértéke , esetleg annak elengedése kizárólag
> a NAV ellenőrzés szigorán múlik.
> 
> Ezzel azt próbáltam érzékeltetni, hogy a számla kiállítója ( aki teljes mértékben helyesen jár el )
> veszélybe sodorhatja a számla befogadóját ( aki egy átlagos vállalkozó, vállalkozás )

... milyen egyszerű is lenne az élet, ha a jogszabály úgy rendelkezne, hogy a számla befogadója lehet az adóhatóság is abban az esetben, ha elektronikus számla kiállítása történik (azaz van hash a beküldött xml-ben), és innét kezdve neki kell elektronikusan megőrizni. Értitek: a NAV amúgy is megőrzi elektronikus formában az elévülési idő végéig, ráadásul hitelesen, módosíthatatlan formában... Ha lenne egy kis rugalmasság a jogalkotó részéről, akkor belevenné ezt valamilyen formában a jogszabályba, és innét kezdve valóban nem lenne szükség a vevő részéről megkövetelt tárolásra... A NAV-tól bármikor lekérdezhető, csak program kérdése. Vagy még az sem (Ha csak 1-2 számlát kell lekérdezni), mert van manuális, webes lekérdezési lehetőség is...

**Comment by KMGY100** [comment]
Idézet az április NAV közleményből :
"""Ha az adóalany a NAV Online Számlázó programjával kíván elektronikus számlát előállítani, a következőkre kell figyelemmel lennie. Abban az esetben, ha a számla kiállításakor a számla megjelenési formájaként az elektronikus számlát választja, akkor az elkészített dokumentumon megjelenik az Elektronikus számla felirat, és a számlát a program megfelelő elektronikus aláírással látja el. Az így előállított számlát a számlakibocsátónak kell elektronikus úton eljuttatnia a számla címzettjéhez. **A számlát az adóhivatal – a számlakibocsátó részére – archiválja,** így az értékesítőnek a számla elektronikus megküldésén kívül nincs más feladata."""

Vagyis:  Elkülönítetten őrzi , archiválja a NAV az oldalukon kiállított elektronikus formátumú számlákat ?
Szerintem egységesen őriz és **_archivál minden egyes számlát a NAV_**, amihez a számla befogadója
is hozzáférhet.

**Comment by DrotosTot** [comment]
Ezzel kapcsolatban én erre emlékszem:
"Ha törvény iratnak vagy okiratnak a megőrzését, illetve eredeti példány megőrzését írja elő, akkor – főszabály szerint – az irat, okirat (pl. számla, számlával egy tekintet alá eső okirat) elektronikus úton való megőrzését a Rendelet szerint kell teljesíteni."

https://nav.gov.hu/nav/ado/afa/Valtoznak_a_digitalis20180630.html

Az 1/2018. (VI. 29.) ITM rendelet a digitális archiválás szabályairól alapján a megőrzésre kötelezett az, akinek a részére a számlát kiállították, így a NAV nem lehet a számlák őrzője. :-)

**Comment by KMGY100** [comment]
@DrotosTot 
Elkanyarodsz a fő témától :  az  UNKNOWN - tól.
(csak zárójelben : mindkét fél kötelezett a számla megőrzésére akkor is ha elektronikus a forma )

**Comment by DrotosTot** [comment]
> @DrotosTot
> Elkanyarodsz a fő témától : az UNKNOWN - tól.
Jogos, bocs, töröltem.

**Comment by KMGY100** [comment]
@NTCA-tax !
Kiállítható ELEKTRONIC számla a a NAV weboldalán.
Ekkor a NAV őrzi, archiválja a számlát.
A számla kiállítója ezt követően akár email mellékletében is elküldheti
a számla PDF állományát.

A számla befogadójának ezt a számlát elegendő PAPIR formában megőriznie ?
Szerintem igen, mert a megkapott számlapéldányból nem derül ki ,hogy az ELEKTRONIC
(a számlán nem kötelező feltüntetni, hogy az milyen formában lett kiállítva) 

Mert:
Ha a programommal a számla kiállítója elkészít egy PDF-en Hash-elt számlát,
és azt elküldi a vevőjének email- mellékletben akkor elegendő a számla kibocsájtójának
elektronikusan őrizni a PDF-et a Hash kóddal együtt.

**Comment by NTCA-tax** [comment]
Nincs olyan kötelezettség, hogy a számlán fel kellene tüntetni, hogy az elektronikus számla. Az adatszolgáltatásban ez a mező a számla egy olyan jellemzője, melyet vagy tud a számlázó program vagy nem. Amennyiben UNKNOWN-al történik meg az adatszolgáltatás, akkor a számla akár papíralapon, akár elektronikusan is kibocsátható. 

Elektronikus számlát csak elektronikus formában lehet megőrizni mind eladói és mind vevői oldalon. A papíralapú számlát pedig papíralapon kell megőrizni, bár lehet elektronikus másolatot készíteni belőle. Amennyiben a vevő az elektronikus számlát papíralapon őrzi meg, annak nincs kihatása az eladóra és az eladó számlázó programjára. A számla kibocsátója nem felel a befogadó nem megfelelő bizonylatkezelésére.

**Comment by jozanesz** [comment]
> A papíralapú számlát pedig papíralapon kell megőrizni

Ez régóta nem igaz.

**Comment by KMGY100** [comment]
@jozanesz !
"""Ez régóta nem igaz."""
Miért állítod ezt (egy idelökött pár szóval) ???

Ha PAPER a számla Számla megjelenési formája és 
személyesen vagy
postai úton vagy
távnyomtatással
bocsájtod a vevő rendelkezésére akkor
papír alapon kell megőrizni a számla kibocsájtójának is meg
a számla befogadójának is.

Ha UNKNOWN a számla Számla megjelenési formája és ha
személyesen, postai úton, vagy távnyomtatással 
bocsájtod a vevő rendelkezésére akkor
papír alapon kell megőrizni a számla kibocsájtójának is meg
a számla befogadójának is.

Ha UNKNOWN a számla Számla megjelenési formája és ha
elektronikusan (például email mellékletben)
bocsájtod a vevő rendelkezésére akkor
elektronikus alapon kell megőrizni a számla kibocsájtójának is meg
a számla befogadójának is.
E mellett, ha akarják papír alapon is őrizhetik.

@NTCA-tax    Így van ?

**Comment by jozanesz** [comment]
> Miért állítod ezt (egy idelökött pár szóval) ???

Mert erről biztosan tudnia kell a NAV áfa-szakértőjének. Ha tud róla, akkor kijavítja a hibásan fogalmazott állítását. Ha esetleg mégsem tudna róla, akkor utánanéz. Részben ugyanabban az NGM-rendeletben, amely az adatszolgáltatást előírja.

**Comment by NTCA-tax** [comment]
@jozanesz a következőt írtam: "A papíralapú számlát pedig papíralapon kell megőrizni, bár lehet elektronikus másolatot készíteni belőle." Ezen mondat után próbáltam értelmezni a hozzászólásodat, de bevallom nem sikerült. Elmondanád mire gondoltál pontosan?

**Comment by jozanesz** [comment]
Alapvetően a _kell_ szó használata helytelen. A papíralapú megőrzés csak az egyik lehetőség.

23/2014. (VI. 30.) NGM rendelet:
> 17. § (1) A számlázó programmal előállított és papírra nyomtatott számla, valamint a számítógéppel előállított és papírra nyomtatott nyugta kibocsátónál maradó példánya – papírra nyomtatás **helyett** – elektronikus adatállományként is megőrizhető, feltéve, hogy a megőrzés a digitális archiválás szabályairól szóló 114/2007. (XII. 29.) GKM rendelet (sic!) rendelkezései szerint, annak 3. § a) vagy b) pontjában meghatározott mód valamelyikeként történik.

Lásd még _1/2018. (VI. 29.) ITM rendelet a digitális archiválás szabályairól_. Nem akarom az egészet idemásolni (és abban is lenne mit javítani).

**Comment by NTCA-tax** [comment]
OK, bocs @jozanesz ha félreérthető volt amit írtam. Egyébként vevői oldalon is lehet papírszámlát elektronikusan megőrizni, valamint ahogy fent levezetted kiállítói oldalon is. Ebbe nem akartam belemenni ilyen mélyen, mivel az alapvető kérdés nem ez volt... De a jövőben próbálok figyelni jobban az ilyen odavetett megjegyzéseimre is :)
