### ISSUE TITLE
Új Séma definíciók [DEV support]

### ISSUE THREAD

**Issue by tib99** [nav-gov-hu/Online-Invoice#565]
A dokumentációk alatt látható, hogy változott a séma definíció 
XML séma definíciók: OSA v3 Sémák (utoljára frissítve: 2020.12.01.) 
de a tartalma ugyan az mint az előző verziónak. (Mindegyik file dátuma 2020.10.02)

**Comment by NTCA-supporter** [comment]
Szia @tib99 !

Köszi a jelzést.
Kérlek ellenőrizd innen a githubos forráskódból, vagy az éles rendszer honlapjáról: https://onlineszamla.nav.gov.hu/dokumentaciok

Köszi

**Comment by tib99** [comment]
Igen, az éles rendszeren jó
Köszi

**Comment by tib99** [comment]
Szia

Mikorra várható, hogy a teszt rendszer az új sémát fogadja?
Jelenleg séma validációs hibát kapunk a customerVatStatus miatt.

**Comment by EPluribusUnum** [comment]
Jó lenne ha már ma este le lenne frissítve a teszt környezet. Kár életbe tartani mikor úgy sincs értelme raja tesztelni.

**Comment by white420** [comment]
Mikorra várható a végleges 3.0 API éles használata?

**Comment by EPluribusUnum** [comment]
@white420 , jelenleg ott tartunk, hogy még teszt sincs, nem hogy éles....

**Comment by tib99** [comment]
Továbbra sem működik a teszt rendszer az új sémával.
Mikorra várható? 
Jelenleg blokkolja  a teszteléseket és már több napja állunk. Nem tudjuk kiadni az új verziót az ügyfeleknek tesztelésre.
Álljunk vissza az előző sémára vagy mi legyen?

**Comment by NTCA-supporter** [comment]
Sziasztok!

Éles indulás: január 4.
Sémaváltozások tesztre kerülése: mostani hét második fele

A frissített interfész dokumentáció és a példaszámlák a mai napon lesznek publikálva.

Üdv

**Comment by nbeeps2** [comment]
Jól értem, hogy ez is változott?

```
<common:passwordHash cryptoType="SHA2-512"></passwordHash>
helyette:
<common:passwordHash cryptoType="SHA-512"></passwordHash>
```

**Comment by NTCA-supporter** [comment]
Sziasztok!

Igen, jól érted. Itt: https://github.com/nav-gov-hu/Online-Invoice/blob/master/src/schemas/nav/gov/hu/OSA/CHANGELOG_3.0.md írtunk egy új fejezetet (2.8) ami tisztán az új változásokat tartalmazza.

Üdv

**Comment by atimeg** [comment]
Jól látom, hogy a tegnapi frissítés után is még privatePersonIndicator-t vár a teszt customerVatStatus helyett?
