### ISSUE TITLE
[Q&A] Elektronikus számla támogatás

### ISSUE THREAD

**Issue by aperger** [nav-gov-hu/Online-Invoice#566]
A NAV Online Számla rendszere az új XSD 3.0-val két ponton támogatja az elektronikus számla kiállításának lehetőségét (Online Szamla_interfesz specifikáció_HU_v3.0.pdf szerint).

A dokumentáció értelmezését szeretném tisztázni. 

1. Az eddig is megengedett, jogszabálynak megfelelő elektronikus számlákat (aláírással és időbélyeggel ellátott dokumentum, például PDF fájl) kiállító rendszereknek nem kötelező a beküldött XML dokumentumban az »electronicInvoiceHash« értéket kitölteni, ez egy lehetőség a digitális archiváláshoz. A hash-értékét ebben az esetben SHA3-512 vagy SHA-256 kódolással kell előállítani, az »completenessIndicator» jelölő értéke »false«. 

2. Ellenben, ha az „Adatszolgáltatás elektronikus számla beküldésével” történik, akkor kötelezően a »completenessIndicator« értéke »true« és kötelező kitölteni »electronicInvoiceHash« értékét SHA3-512 kódolással számítva. A hash-kód az invoiceData csomópont BASE64 értékéből számolódik.

Tehát értelmezésem szerint az első esetben a PDF állomány a minősül elektronikus dokumentumnak (ahogy korábbi években is), míg a második esetben a NAV-hoz beküldött XML állomány. A dokumentáció szerint: „Az XSD 3.0 verziója lehetőséget biztosít arra, hogy az adatszolgáltatást az eladó a teljes adattartalmú elektronikus számla beküldésével valósítsa meg, ha ez az elektronikus számla éppen az ezen dokumentáció szerinti invoiceData.xsd séma szerinti XML állomány.” 

Az első esetben a vevőnek a PDF állományt, míg második esetben a NAV rendszeréből letölthető XML állományt kell archiválnia a vevőnek.

Tehát a második esetben hiába készül aláírás és időbélyeg nélküli PDF állomány is a programmal (vagy kinyomtatott papír alapú példány, ahogy a digitálisan aláírt időbélyegzett PDF esetében sem), az nem minősül hiteles dokumentumnak, hiszen az ellenőrző kód és az eredetiség igazolása az XML állomány alapján történik. 

A NAV Infovonaláról (Tel.: 1819) irányítottak ide, mivel ennek megválaszolása informatikai kérdés.

Köszönettel

**Comment by EnokhSys** [comment]
Kedves @aperger, szerintem zárd le ezt az issue-t, mert van erről egy eléggé kivesézett, ami még továbbra is nyitott:

[NAV 3.0 Elektronikus számla #419](https://github.com/nav-gov-hu/Online-Invoice/issues/419)

**Comment by NTCA-tax** [comment]
Amennyiben PDF számla és a 3.0-ás verzióban lévő XML-es e-számla IS készül, akkor a két partner megállapodása, melyiket tekintik hiteles számlának. Amennyiben a PDF-et, akkor azt kell megőrizni, amennyiben az XML-t, akkor azt kell megőrizni. A megőrzés szabályait most nem részletezném, az nem is adatszolgáltatási kérdés. 

A fentiek alapján ezt az issue-t lezárom, ha felmerülne kérdés, akkor új issue-ban beszéljük meg.
