### ISSUE TITLE
DOMESTIC áfa regisztrált eladónál

### ISSUE THREAD

**Issue by KMGY100** [nav-gov-hu/Online-Invoice#567]
Idézet a Fejlesztői Naplóból:
""A DOMESTIC enum esetében el fogjuk várni a belföldi adószám feltüntetését (kivéve az áfa regisztrált **_eladónál_**""

- Ha az **_eladó_** az áfaregisztrált akkor  kinek az adószáma nem kell ?
  az eladóé vagy a vevőé ?

- Ha a **_vevő_** az áfaregisztrált akkor  kinek az adószáma nem kell ?
  az eladóé vagy a vevőé ?

**Comment by NTCA-supporter** [comment]
Szia @KMGY100 !
Az eladó adószáma séma szinten kötelező, így azt mindig meg kell adni.
Az idézett mondat tehát azt jeletni, hogy ha az eladó áfa regisztrált, akkor a vevőnél a belföldi adószámot nem kötelező megadni.
Üdv

**Comment by KMGY100** [comment]
Akkor az idézett mondat így hangzik helyesen ?
A DOMESTIC enum esetében el fogjuk várni a belföldi adószám feltüntetését (kivéve az áfa regisztrált **_VEVŐNÉL_**
