### ISSUE TITLE
[Q&A] ÁFA kulcsok rendezése

### ISSUE THREAD

**Issue by zsolt-takacs** [nav-gov-hu/Online-Invoice#568]
A dokumentáció alapján szereplő elfogadott ÁFA kódokat nem találom teljes egészében a teszt környezet számlázójában kiválaszthatóak közül. 
Gondolok itt arra, hogy a számlázóban KBA míg a dokumentációban KBAET és KBAUK is szerepel.
Ezek frissülnek a jövőben vagy ez a jó és ezekkel lehet dolgozni?

**Comment by NTCA-supporter** [comment]
Szia @zsolt-takacs !
A számlázó átalakítása a 3.0-ás sémára még folyamatban van. Természetesen egységesek lesznek a jövőben.
Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet. Ha van még kérdés, nyisd újra kérlek.
