### ISSUE TITLE
[Q&A] When will be available the Data example XML for version 3.0?

### ISSUE THREAD

**Issue by danton-edi** [nav-gov-hu/Online-Invoice#569]
When do you plan to publish the data example XML adapted to version 3.0 ? 

They are really useful to be sure how to generate the file data.

Thank you.
Regards.
Daniel Antón

**Comment by csandazoltan** [comment]
It is not an official example, but the manageInvoice.xml contains base64 encoded invoicedata.

Decode it, it's a start, i worked with that.

**Comment by danton-edi** [comment]
Thank you, Zoltan. I did the same but I would like to have the official examples to see how to implement the new scenarios.

**Comment by NTCA-supporter** [comment]
Hi @danton-edi !
We published the new 3.0 samples today: https://github.com/nav-gov-hu/Online-Invoice/tree/master/sample/Data%20sample
The translation to english is in progress.
Br

**Comment by NTCA-supporter** [comment]
@danton-edi We published the examples in English. You can find it here: https://onlineszamla.nav.gov.hu/dokumentaciok
