### ISSUE TITLE
Rendszeren kívüli érvénytelenítő számla kiállítása nav online számlázóval

### ISSUE THREAD

**Issue by vastag60** [nav-gov-hu/Online-Invoice#570]
A teszt környezetben próbáltam "Rendszeren kívüli érvénytelenítő számlát"  kiállítani, de a létrejött xml hibás és nem tudja a számlázó  beküldeni. (https://szamlazo-test.nav.gov.hu/uj_szamla) .
A hiba , hogy a line number és a line number reference is 1, ezért "A megadott sorszámmal már létezik tétel a számlaláncban." hibát kapom A számlakép PDF jó.
.
Vagy valamit rosszul csináltam ?

**Comment by NTCA-supporter** [comment]
Szia!

Tudnál küldeni egy adószámot és egy számlaszámot? Akkor utána tudok nézni.

**Comment by vastag60** [comment]
ADÓszám: 62294647-2-42

számlaszámok:

eredeti: ESHOP 001

érvénytelenítő: VL-2020-11

Az xml mellékelve

 

 

Elvileg ilyen nem lehetne, csak ha 0 tétel  lenne az eredeti számlában

<lineNumber>1</lineNumber>

 <file:///C:/Users/L/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/BJTCDWXT/adatexport_2020-12-04-1505.xml> <lineModificationReference>

<lineNumberReference>1</lineNumberReference>

<lineOperation>CREATE</lineOperation>

**Comment by NTCA-supporter** [comment]
Köszi szépen! 
Megnéztem mi lehet a gond. A teszt rendszerben szerepel a ESHOP 001 számla, ahol van benne egy sor (Ez XML API-n keresztül lett beküldve az Online Számlába). Ez korábban lett rögzítve, mint a VL-2020-11. Mivel a Számlázó nem tud erről a beküldésről, ezért az ott felvett rendszeren kivüli számla esetén az line=1 állítja be az első tételnél. Az XML API-n beküldött számlákat stornózni, csak az XML API-n keresztül és az Online Számla felületen lehet.

**Comment by vastag60** [comment]
Ezt most nem pontosan értem:
Az XML API-n beküldött számlákat stornózni, csak az XML API-n keresztül és az **Online Számla felületen lehet.**

Igen beküldtem korábban egy számlát (ez a rendszeren kívüli számla ESHOP 001) 
Próbálom az online Számla felületen érvényteleníteni,az ESHOP 001-et. Amikor beírom a" Hivatkozott  számlaszámot,( azaz az  ESHOP 001-et ) a program észreveszi , hogy ez már korábban beküldött számla és kiveszi automatikusan a pipát a "Még nem történt adatszolgáltatás az alapszámlára."  felismeri, hogy ez már a rendszerben lévő számla, ennek ellenére 1-et ad a line-nak.

Ráasásul igy kiállítottam egy olyan számlát amit azután se törölni se beküldeni nem lehet. A számlák sorszámai nem lesznek folyamatosak a NAV online számlázóból . Jelen esetben a VL-2020-11  nem érvénytelenithető és nem beküldhető, csak a számlázóban áll és csak vár vár.

**Comment by vastag60** [comment]
Bocs , most látom hogy van "egyszerüsített számlaadat rögzités, kipróbálom.
Ettől függetlenül a nav számlázóval elő lehet állítani beküldhetetlen számlát a fenti módszerrel.

**Comment by vastag60** [comment]
Nem jó, mert itt csak elözmény nélkülit lehet érvényteleníteni , az elözmény nélküli érvénytelenítés a nav számlázóban is jól működik, (https://szamlazo-test.nav.gov.hu/szamlaim) . A hiba a rendszeren kívüli, de már beküldött alapszámla esetén van.

**Comment by vastag60** [comment]
Átolvasva a kézikönyv 9.3 pontját, arra tudok következtetni, hogy a nav számlázó ezen funkciója hibás. 
 Részlet:

**_Speciális esetekben_** előfordulhat, hogy olyan érvénytelenítő okiratról történik
adatszolgáltatás, amelynek az eredeti számlájáról még nem történt, és nem is fog történni
adatszolgáltatás.
Ezt a tényt a "Számla adatai" szekcióban található "Még nem történt adatszolgáltatás"
jelölőnégyzet bejelölésével kell jelezni.
Ha a “Még nem történt adatszolgáltatás” jelölőnégyzet értéke hibásan lett megadva, (Ha a
“Hivatkozott számla sorszáma” mező értékével megegyező számlasorszámmal található
sikeres adatszolgáltatás a rendszerben, és a jelölőnégyzet értéke igaz) számlakiállításkor a
rendszer egy felugró üzenetben értesít a hibáról és annak okáról.

Amit irtatok:
Az XML API-n beküldött számlákat stornózni, csak az XML API-n keresztül és az Online Számla felületen lehet.

Várható a javítás ?

**Comment by NTCA-supporter** [comment]
Közben mi is megnéztük a jelenséget, azért nem jelentkeztem. Valóban hiba van és nem jelenik meg a felugró ablak. Köszi szépen a jelzést! Adunk majd rá javítást. Addig nyitva hagyom a ticketet, hogy ne legyen elfelejtve.

**Comment by vastag60** [comment]
Köszi, csak szólok , hogy a "beküldött rendszeren kívüli mósdositó"  számlánál  ugyanez, hibás a generált XML.

**Comment by NTCA-supporter** [comment]
Sziasztok!

A fejlesztés meg lesz valósítva, hamarosan teszt rendszeren elérhető lesz, majd utána élesen is.
Jelzek ha kikerült.

Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezzel kapcsolatban a javítás kikerült, kérlek nézzetek rá és jelezzetek vissza.

Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet, ha van még kérdés, kérlek nyissátok újra.
Üdv
