### ISSUE TITLE
Éles 3.0 interfész elérés

### ISSUE THREAD

**Issue by toothattila** [nav-gov-hu/Online-Invoice#571]
Kedves @NTCA-supporter!

Mikortól lesz elérhető és stabilan használható az **éles NAV 3.0-s interfész**? Jelenleg 404-es választ kapunk vissza.

Előre is köszönöm, ha kapunk erre gyorsan választ. Nagy segítség lenne ez nekünk...

Üdv:
Attila

**Comment by omachtandras** [comment]
Illetve mikorra várható a keddi változtatásokat tartalmazó TESZT elérése?
Nekünk ez egy fokkal nagyobb segítség lenne. :)

**Comment by csandazoltan** [comment]
Még mindig nem elérhető a 12-01-es változást használó teszt? Most akartam elkezdeni....

**Comment by toothattila** [comment]
@NTCA-supporter nagyon várjuk erre a választ! Kérlek szépen, osszatok meg ezzel kapcsolatban információt velünk.

Előre is köszönettel:
Attila

**Comment by NTCA-supporter** [comment]
Sziasztok!

Éles indulás: január 4.
Sémaváltozások tesztre kerülése: mostani hét második fele

Plusz info, de ezt majd a megfelelő issuekban is megírom, ha odajutok: a frissített interfész dokumentáció és a példaszámlák a mai napon lesznek publikálva.

Üdv

**Comment by toothattila** [comment]
Köszi szépen!

**Comment by nbeeps2** [comment]
Március 31-ig elegendő átállnod a 3.0-ra, nem kell pont január 4-el...

**Comment by toothattila** [comment]
> Március 31-ig elegendő átállnod a 3.0-ra, nem kell pont január 4-el...

Oké, de a 2-es interfészen hogy teljesíted a bővített adatszolgáltatási kötelezettséget?

**Comment by nbeeps2** [comment]
Nem kell teljesítened. Március 31-ig szankciómentes időszak van és nem kell utólag se beküldeni, az addig be nem küldött számlákat.

**Comment by omachtandras** [comment]
@nbeeps: tudsz erre linket adni? Mert itt a GITHub-on a konkrét kérdésre nem született még válasz, csak egy megjegyzés, hogy már nagyon várják, hogy kiírhassák, hogy mi lesz a türelmi időszakban... (https://github.com/nav-gov-hu/Online-Invoice/issues/407#issuecomment-705485119)

**Comment by nbeeps2** [comment]
Itt a link: https://github.com/nav-gov-hu/Online-Invoice/issues/502#issuecomment-723840410

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ha nincs több kérdés, zárom az issuet, helytállóak az előző kommentek.

Üdv

**Comment by GabiSzamla77** [comment]
Sziasztok!
Igen, a kommentek helytállóak, és egyértelmű, hogy nem kell visszamenőlegesen beküldeni a számlákat, de továbbra sincs egyértelmű válasz a januári indulás módjára. 
**Érdekességképpen:** 12.03-án felhívtam a NAV ügyfélszolgálatot, hogy akkor kötelező-e beküldeni a magánszemélyes és egyéb számlákat januártól - nagyon határozottan mondta, hogy a jogszabályi kötelem megvan január 1-jével, tehát igen. Azt még nem tudják, hogy lesz-e ebben módosítás, elképzelhető.

Említettem neki, hogy már pár hónapja megy ez a bizonytalanság itt a fejlesztési oldalon. Erre annyit reagált, hogy „lehet, hogy ők kaptak erre nézve konkrét instrukciót, de mi nem” , ezért csak ezt tudja mondani, hogy jogszabályi előírás szerint kell küldeni januártól az "új" számlákat is.

Lássuk be, még nem került fel ide, vagy bármelyik jegyre a konkrét válasz, ami ennek ellentmondana.

**Comment by kurucza** [comment]
@GabiSzamla77 , A fejlesztői naplóban a tegnapi bejegyzésben ez olvasható:

`Sokan` kérdezik és érdeklődnek a türelmi vagy szankciómentes időszakra vonatkozó szabályokról. Ígérem, hogy néhány napon belül erről is publikálni fogunk hírt, illetve a GitHub-on is válaszolunk az erről szóló topic-ban.
 
https://onlineszamla-test.nav.gov.hu/fejlesztoi_naplo

Bízzunk benne, hogy meglesz a válasz, amit az ügyfelek felé is tudunk továbbítani majd hivatkozásnak.

Andi
