### ISSUE TITLE
[Q&A] custometVatStatus helyes implementálása

### ISSUE THREAD

**Issue by peacefuldev** [nav-gov-hu/Online-Invoice#572]
Kedves Fejlesztők,

Elég érzékenyen érintett minket a 2020.12.01. fejlesztői naplóban szereplő bejegyzés az új custometVatStatus mező kapcsán, mivel már majdnem elkészültünk a teljes implementációval, és adatbázis szinten/felhasználói felületen létrehoztuk az IsPrivatePerson mezőt, amellyel a felhasználó jelölhette volna, ha magánszemélynek készül a számla.

Szeretnénk elkerülni, hogy 3 héttel a határidő előtt ismételten nagyobb mértékben kelljen hozzányúlni a kódhoz/UI-hoz, ezért az alábbi kérdéssel fordulunk Önökhöz:

Megfelelő működés-e a következő (custometVatStatus töltéséhez):
- Magánszemély vevő jelölőnégyzet kipipálva = PRIVATE_PERSON;
- Ha az adószám meg van adva és magyar a számlázási ország = DOMESTIC;
- Ha az adószám nincs megadva vagy külföldi a számlázási ország = OTHER.
Ezen kívül magyar vevő esetén ha az adószám nincs megadva és nem magánszemély, megjelenítünk egy felugró ablakban egy figyelmeztetést, hogy belföldi ÁFA alany esetén az adószám kitöltése kötelező.

**Comment by nbeeps2** [comment]
Jesszusom, köszi ezt a bejegyzést, én nem is láttam sehol, hogy változtattak, ha ezt nem olvasom. A fejlesztői napló menüpontot nem szoktam rendszeresen nézegetni, mert egy évben 2-3szor frissül csak, hihetetlen, hogy nem került ki ez a hír a főoldalra... Annak sem örülök, hogy a már kész programokat, akkor lehet ismét módosítgatni...

**Comment by NTCA-tax** [comment]
A kérdésedre a választ itt találod: https://github.com/nav-gov-hu/Online-Invoice/issues/582

Mivel erről a kérdésről ott folyik a beszélgetés, ezért ezt az issue-t itt lezárom. Amennyiben a bejegyzésemet követően lenne még kérdésed, akkor abban az issue-ban beszéljük meg.
