### ISSUE TITLE
3.0 INVALID_HEADER_VERSION [DOC]

### ISSUE THREAD

**Issue by jozanesz** [nav-gov-hu/Online-Invoice#573]
**A hibás dokumentum neve**
Online Szamla_interfesz specifikácó_HU_v3.0.pdf

**Oldalszám**
Több, meg amúgy is, melyik számrendszerben? Másképp számozza az olvasó, mint az író.
17/6:headerVersion;Kötelező:nem
18/7:A headerVersion opcionális elem a kérésben
171/161:A hibaüzenet akkor adható vissza, ha a /header/headerVersion értéke meg van adva és nem 1.0

**A dokumentációs hiba leírása**
Nem világos, hogy a dokumentáció hibás, vagy a 3.0 implementációja. Mert 2.0-ig rendesen működött _headerVersion_ nélkül, de a 3.0 ezt a hibát dobja:
`<ns2:errorCode>INVALID_HEADER_VERSION</ns2:errorCode><ns2:message>Érvénytelen header verziószám!</ns2:message>`

**Comment by NTCA-supporter** [comment]
Szia @jozanesz !

Köszi a jelzést, ez implementációs hiba, ilyenkor nem kellene, hogy kapd ezt az üzenetet.
Javítani fogjuk.
Üdv

**Comment by NTCA-supporter** [comment]
Javítva, tesztelhető teszt környezeten.
Ha van még probléma, nyisd újra kérlek.
Köszi a jelzést!
Üdv
