### ISSUE TITLE
[DEV support] ns2 namespace

### ISSUE THREAD

**Issue by boxi78** [nav-gov-hu/Online-Invoice#574]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[X] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[X] 3.0

**A requestId értéke / requestId value**
```
SZB2064667320201202104552525
SZB2064667320201204190956439
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Kicsit el vagyok keveredve a namespace-ek használatával. A fenti két requestId-n jött, két response egyikében használ ns2 namspace-t a <processingResults> tag-ben, a mások esetén nem. Ennek mi az oka?
Köszönöm!

**Comment by DrotosTot** [comment]
Szia!
#453 -ban már ki lett vesézve, a lényeg, hogy a NAV nem garantálja a névterek állandó, kiszámítható sorrendjét. Lehet, hogy a választ egyszer az ns2-ben, egyszer az ns3-ban kapod vissza.

**Comment by KMGY100** [comment]
Ha megengedsz egy javaslatot:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:QueryTransactionStatusResponse 
xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" 
xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" 
xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" 

A fenti status válaszban látható hogy milyen namespace-ek  vannak 
a válasz XML-ben.
Ezeket kigyűjtöm és törlöm a teljes XML-ből.

Ezután bármilyen namespace-t ad meg a Response  már érdektelen,
független a feldolgozás a namespace - ektől.

**Comment by boxi78** [comment]
> Ha megengedsz egy javaslatot:
> 
> <ns2:QueryTransactionStatusResponse
> xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common"
> xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api"
> xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base"
> 
> A fenti status válaszban látható hogy milyen namespace-ek vannak
> a válasz XML-ben.
> Ezeket kigyűjtöm és törlöm a teljes XML-ből.
> 
> Ezután bármilyen namespace-t ad meg a Response már érdektelen,
> független a feldolgozás a namespace - ektől.

Köszönöm, ez valóban jó ötlet!

**Comment by boxi78** [comment]
> Szia!
> #453 -ban már ki lett vesézve, a lényeg, hogy a NAV nem garantálja a névterek állandó, kiszámítható sorrendjét. Lehet, hogy a választ egyszer az ns2-ben, egyszer az ns3-ban kapod vissza.

Köszönöm, de nem olvasom el az összes bejegyzést, csak a címeket max, és a 453-as címe sem utal erre, így esély sem volt rá, hogy megtaláljam. Mellesleg ez a "nem garantálja" dolog egyáltalán nem fogja megkönnyíteni a válasz feldolgozását.

**Comment by KMGY100** [comment]
@boxi78 
Ha elolvasod az előző bejegyzésemet (javaslatomat)
akkor megkönnyíti a válasz feldolgozását.
Bármikor, bármilyen namespece van a Response-ban
azokat kigyűjtheted és törölheted a teljes XML válaszból.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Mivel ez már többször volt tárgyalva, zárom az issuet. Ha a lezárt issuek átnézése után is maradt még kérdés, állunk rendelkezésre.

Üdv
