### ISSUE TITLE
[Q&A] Hibaüzenet 10 Mb-os POST body limit túllépésekor

### ISSUE THREAD

**Issue by szako** [nav-gov-hu/Online-Invoice#575]
Mi a NAV rendszer pontos reakciója, ha egy http kérés mérete túllépi a 10 mb-os limitet?

Az alábbit kapom egy kb. 10,4 Mb-os kérésre jelenleg:

<?xml version="1.0" encoding="UTF-8" standalone="true"?>

```xml
<GeneralExceptionResponse xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common">
  <funcCode>ERROR</funcCode>
  <errorCode>INVALID_REQUEST</errorCode>
  <message>Érvénytelen kérés!</message>
</GeneralExceptionResponse>
```

A dokumentációt átnéztem, de ilyen hibaüzenet kombinációt és leírást a limit túllépésére vonatkozóan nem találtam.

Köszönöm!

**Comment by NTCA-supporter** [comment]
Szia @szako !

Küldj kérlek egy requestId-t hogy megnézhessem a konkrét esetet.

Köszi

**Comment by szako** [comment]
20120422rQYsXP0T7jkDpfGyDUjWrG

**Comment by NTCA-supporter** [comment]
Segíts kérlek, hogy ez ugye tesztrendszer? Pontosan mikor küldted be?
Esetleg meg tudod ismételni, hogy legyen friss logom? Bár ha 2 napja küldted be akkor meg kellene találnom, viszont sem DB-ben sem logban nem látom az adott requestId-t.
Köszi

**Comment by szako** [comment]
Igen, a teszt rendszer, 3.0-ás végpont. Tesztelési céllal és egyszerűsítés miatt egy tömörítetlen számlát küldtem be.

A küldés ideje UTC-ben: 2020.12.04 / 21:19:53

**Comment by szako** [comment]
Újraküldtem: 20120722rQYsXP0T7jkEcV21afi0rG

**Comment by NTCA-supporter** [comment]
Szia @szako !

Erre vonatkozóan a COMPRESSION_TOLERANCE_EXCEEDED hibakódunk van, amit viszont kitömörítés után ellenőrzünk.
A te esetetedben szerintem egy általános hibakezelés fut meg, ezért az INVALID_REQUEST hibakód.
A logban és a DB-ben sem látom, ezért gondolom, hogy ez hamarabb blokkolódik, minthogy eljutna a backendig.
Utánanézek alaposabban.
Üdv

**Comment by szako** [comment]
@NTCA-supporter 16Mb-os tömörítetlen méretű állománynál valóban COMPRESSION_TOLERANCE_EXCEEDED kódot kapok vissza, azt teszteltem is sikeresen korábban.  Itt a kérdés az volt, hogy 10Mb-os kérés limit felett hogyan reagál a rendszer. Pl. teszteltem, hogy 8 megás kérésnél már nem kapok INVALID_REQUEST hibakódot, hanem továbbmegy a belső rétegek fele a feldolgozás.

Ennek a tesztelését azért kell elővennem, mert az egyik ügyfelemnél korábban volt rá példa, hogy több nagy számla belekeveredett a 100-as csomagok közé és a kötegelt küldést elutasította a NAV, mivel _valószínűleg_ a POST limit-et átlépte a kérés. Egyedi küldéssel később be tudott menni a számla.

A dokumentációban a `<GeneralExceptionResponse>` típusnál (3.1.1 fejezet) az alábbi leírás található:
_A szolgáltatás minden operációjában a technikailag feldolgozhatatlan üzenetre (rosszul formázott XML,
helytelen namespace, vagy helytelen context root) a GeneralTechnicalException hibatípus kerül
visszaadásra._

Érzésem szerint itt kellene lennie a limit elérésének, de biztosat nem tudok.

Köszönöm.

**Comment by ragnud830** [comment]
Sziasztok,

Ugyanezt a hibaüzenet kapjuk mi is, annyi kiegészítéssel, hogy kb. 7 MB-os méret felett minden esetben az `INVALID_REQUEST` választ kapjuk. A `COMPRESSION_TOLERANCE_EXCEEDED` hibakódot még egyetlenegy esetben sem kaptuk vissza (kb. 50 MB-ig próbáltuk).

@NTCA-supporter: van esetleg ezzel kapcsolatban bármi előrelépés, kb. mikorra várható megoldás?

Köszönöm

**Comment by NTCA-developer** [comment]
Sziasztok!

Volt 2 kósza percem és erre vetődtem. A 10MB post body size limit az alkalmazásszerver konfigje. Azaz ha ezt meghaladod akkor a HTTP kérés be sem megy az alkalmazásnak. Ezért nem is látja @NTCA-supporter sem logban sem máshol.

Fentiek miatt nincs az esetre dedikált hibakód. (nem is lehet, hiszen szerverként meg sem kapod az ilyen kéréseket) Amit a kliens oldal lát ilyenkor, az op rendszer specifikus, de általában valamilyen hálózati hibára van átfordítva.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
