### ISSUE TITLE
[Q&A] QueryTransactionStatusResponse névtér

### ISSUE THREAD

**Issue by ballonyi** [nav-gov-hu/Online-Invoice#576]
Az imént kaptam vissza egy QueryTransactionStatusResponse-t, melynek részlete az alábbi:
A businessValidationMessages alatti validationResultCode,validationErrorCode,message értékek az `ns2` névtérbe tartoznak , míg a technicalValidationMessages alattiak pedig nem. 

Gondoltam jelzem, mert látszólag következetlenség. Vagy szándékos? 

```
...
  <ns2:processingResults>
    <ns2:processingResult>
      <ns2:index>1</ns2:index>
      <ns2:invoiceStatus>DONE</ns2:invoiceStatus>
      <ns2:businessValidationMessages>
        <ns2:validationResultCode>WARN</ns2:validationResultCode>                      <!-- NS2: -->
        <ns2:validationErrorCode>MISSING_HEAD_DATA_CUSTOMER</ns2:validationErrorCode>  <!-- NS2: -->
        <ns2:message>....</ns2:message>                                                <!-- NS2: -->
        <ns2:pointer>
          <ns2:tag>...</ns2:tag>
        </ns2:pointer>
      </ns2:businessValidationMessages>
      <ns2:compressedContentIndicator>false</ns2:compressedContentIndicator>
    </ns2:processingResult>
    <ns2:processingResult>
      <ns2:index>2</ns2:index>
      <ns2:invoiceStatus>ABORTED</ns2:invoiceStatus>
      <ns2:technicalValidationMessages>
        <validationResultCode>ERROR</validationResultCode>                   <!-- NINCS -->
        <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>          <!-- NINCS -->
        <message>...</message>                                               <!-- NINCS -->
...
```

**Comment by csandazoltan** [comment]
Ez így "Jó"... legalábbis "rendeltetésszerűen működik"

Ugyanaz a név, más típus.... furán néz ki, de elvileg pont erre valók namespace-ek
![image](https://user-images.githubusercontent.com/6756505/101315881-baacd380-385b-11eb-80c0-d2b496e2bcde.png)

Az egyik typus a common xsd-ben van
Mondjuk vannak ebben a projektben "érdekes" esetek, amikor a fő elem default namespace, de minden eleme más namespace, pont mint a  példáid

**Comment by NTCA-supporter** [comment]
Sziasztok!

Mivel ez már többször volt tárgyalva, zárom az issuet. Ha a lezárt issuek átnézése után is maradt még kérdés, állunk rendelkezésre.

Üdv
