### ISSUE TITLE
[Q&A] 3.0 IncorporationType TAXABLE_PERSON még nem működik

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#577]
A saját ügyfél adatbázisból kipróbáltam véletlenszerűen 10 olyan adószámot, akik adószámos magánszemélyek és nem egyéni vállalkozók, de a 3.0 teszt rendszer mindegyiknél a SELF_EMPLOYED adott vissza TAXABLE_PERSON helyett. Ezt mikortól lehet majd tesztelni?

**Comment by NTCA-supporter** [comment]
Szia @nbeeps2 !

A hét második felétől lesz elérhető.

Üdv
