### ISSUE TITLE
[DOC] VatRateType eltérés

### ISSUE THREAD

**Issue by csandazoltan** [nav-gov-hu/Online-Invoice#578]
Online Szamla_interfesz specifikáció_HU_v3.0.pdf
https://onlineszamla-test.nav.gov.hu/api/files/container/download/Online%20Szamla_interfesz%20specifik%C3%A1ci%C3%B3_HU_v3.0.pdf
(Az éles verziója ennek a PDF-nek nem elérhető)

126-os PDF oldal / 115-ös dokumentáció oldal

VatRateType
A leírás ellentmond az új XSD-nek, hiányoznak a leírásban szereplő boolean típusú mezők marginSchemeVat és marginSchemeNoVat.
"Helyettük" marginSchemeIndicator van az XSD-ben. (Ez a kulcs a LíneType típusban található leírásban)

![image](https://user-images.githubusercontent.com/6756505/101337486-07a0a200-387c-11eb-8328-83eba3e075fc.png)

---

A fejlesztő naplóban látom a változtatást:

> A VatRateType csomóponton belül több változtatást hajtunk végre. Ezeknek célja az egyes esetek egyértelmű elhatárolása, valamint a sémában fellelt párhuzamosságok megszűntetése.
> A különbözet szerinti adózású számlák esetén használandó marginSchemeIndicator elemet a VatRateType csomópontba helyezzük át, mellyel párhuzamosan töröljük az ott lévő marginSchemeVat és marginSchemeNoVat elemeket. Ezzel a változtatással egyszerűsödik valamelyest a séma.

**Kérném a leírás frissítését, hogy ezt a változást implementálni tudjam**, addig nem tudok az új XSD-nek megfelelni!

---

Ezzel szerintem nem egyszerűsödött a típus mert ezzel csak egy új variáns lett a választási lehetőségek között

- normál vatPercentage
- fix boolean true
- case/reason páros
- +1 típus MarginSchemeType, fix listás string

Továbbá nem látok kapcsolatot a régi és az új mező között:

Volt: "Áthárított adót tartalmazó különbözet szerinti adózásra" és "Áthárított adót nem tartalmazó különbözet szerinti adózásra"
Lett: "Különbözet szerinti szabályozás típus" - Utazási irodák - Használt cikkek - Műalkotások - Gyűjteménydarabok és régiségek

**Comment by NTCA-supporter** [comment]
Szia @csandazoltan !

Már több issueban is jeleztem, hogy a mai napon fogjuk publikálni a frissített dokumnetációt.
Jelzek ha ez megtörtént, addig maradjon nyitva.
Üdv

**Comment by NTCA-supporter** [comment]
https://onlineszamla.nav.gov.hu/dokumentaciok

Kérlek zárd az issuet, ha nincs több kérdés.
Üdv

**Comment by samuferenc** [comment]
Jól látom, hogy a vatOutOfScope/case-ból a THK (területi hatályon kívül) kikerült?

**Comment by szako** [comment]
@samuferenc Jól látod! Én direkt kerestem a példáknál, mert egy adóosztályos szakértő kolleganő a lelkemre kötötte, hogy derítsem ki mire lehet ráhúzni, mert ő nem tudja.

**Comment by csandazoltan** [comment]
@NTCA-supporter 
Az élesen megjelent az új dokumentáció, a tesztrendszeren nem.
Eltérő dokumentációk félreértésekre adhatnak okot

**Comment by NTCA-supporter** [comment]
Szia @csandazoltan !
Ki fogjuk tenni oda is, kis türelmet kérek.
A THK valóban kikerült.
Üdv

**Comment by csandazoltan** [comment]
@NTCA-supporter és akkor most megint várunk 4-5 napot, hogy érdemben lehessen fejleszteni és tesztelni és lesz körülbelül 2 munkahetünk, hogy a január 4-re elkészüljön a 3.0?

**Comment by RvPSc** [comment]
Téves elképzelés... Pontosabban egy ideális világban 2 munkahét lenne. Azt is számításba kell venni azonban, hogy verzióváltási időszakban a nav tesztrendszere kb. 5-10%-os elérhetőséggel szokott üzemelni. Szóval a nettó időd a tesztelésre jóval kevesebb marad, ezt kalkuláld be. Lehet, hogy jobb lenne elengedni ezt a január 4-es dátumot, tekintve, hogy múlt héten több kardinális dolgot megváltoztattak, de ahogy látom most is frissült a doksi (legalábbis az éles tekintetében). Úgy tűnik, hogy még nagyon nincsenek vele kész a srácok. Jó lenne ezt hivatalos körülmények között is publikálni nem csak a fejlesztőknek, hanem az adózóknak is! Sajnos ez a 3.0 nem győzött meg arról, hogy a #sohavégetnemérős játék nem fog a közeljövőben egy 4.0-val folytatódni.

**Comment by NTCA-supporter** [comment]
Sziasztok!

A teszt rendszerre is feltöltésre került a frissített interfész dokumentációt és az XSD-ket.
Megértem a problémátokat teljes mértékben. A türelmi időszakot vegyétek vigyelembe kérlek. A sémaváltozások nagy része githubos és egyéb megkeresések szüleménye, nem hobbiból csinálunk ilyen változásokat ennyire közel az élesítéshez.
Ha nincs több kérdés, zárom az issuet.

Üdv
