### ISSUE TITLE
queryInvoiceDigest jogosultság hiba

### ISSUE THREAD

**Issue by toothattila** [nav-gov-hu/Online-Invoice#579]
Sziasztok! Kedves @NTCA-supporter !

A **https://api.onlineszamla.nav.gov.hu/invoiceService/v2/queryInvoiceDigest** interfészhíváskor sok esetben ezt kapjuk válaszul:

```
<funcCode>ERROR</funcCode>
<errorCode>FORBIDDEN</errorCode>
<message>Jogosultság szükséges!</message>
```

Hogy kell beállítani a technikai usert, hogy ne dobjon az interfész jogosultság hibát.

Úgy látjuk, hogy megváltozott a felületen a jelölők működése, egyszerre mindhármat nem lehet bejelölni a technikai usernél. Hogyan kell eljárni, hogy az adott usernek legyen joga a lekérdezéshez?

Üdv:
Attila

**Comment by NTCA-supporter** [comment]
Szia @toothattila !
Küldj kérlek egy requestId-t, úgy konkrétabban meg tudom nézni.
A Számlák lekérdezése és Saját számlák lekérdezése sosem volt egyszerre kiadható.
A Számlák lekérdezése a bővebb, azzal azt a számlát is lekérdezheted, amit nem az adott technikai felhasználóval állítottál ki, illetve ezzel a jogosultsággal használható a vevő oldali lekérdezés.
A Saját számlák lekérdezése joggal csak kimenő irányú számlákat kérdezhetsz le, és csak azokat amit az adott tech userrel küldtél be.
Üdv

**Comment by NTCA-supporter** [comment]
Szia @toothattila !
Sikerült megoldani?
Van még kérdés?
Üdv

**Comment by KMGY100** [comment]
@toothattila 
![Jogosultságok](https://user-images.githubusercontent.com/57392809/101982344-8e39f280-3c73-11eb-8a24-df65913704c5.png)
A második és a harmadik jelölőnégyzet legyen kipipálva.

**Comment by toothattila** [comment]
Köszi! De ez van bepipálva és mégis forbidden-t kapunk válaszul... Pont ez okozza a fejtörés és ezért várom nagyon @NTCA-supporter válaszát, mert nem tudjuk, mi mást mondhatnánk még az ügyfélnek.

> @toothattila
> ![Jogosultságok](https://user-images.githubusercontent.com/57392809/101982344-8e39f280-3c73-11eb-8a24-df65913704c5.png)
> A második és a harmadik jelölőnégyzet legyen kipipálva.

**Comment by NTCA-supporter** [comment]
Szia @toothattila !

Hivatalosan az éles rendszert nem supportáljuk itt githubon, arra van NAV ügyfélszolgálat.
Mivel sok ügyfeled érintett, így a példa requestnél használt 1p5cglj... technikai felhasználó jogosultságait megnézettem, és csak Saját számlák lekérdezése jogosultsága van, nem pedig a Számlák lekérdezése.
A Mentés gombra rányomtatok? :) 

Ennyi egyébként a probléma, semmi több.

Üdv

**Comment by toothattila** [comment]
Köszi szépen, ezzel visszamegyünk az ügyfélhez.

**Comment by NTCA-supporter** [comment]
@toothattila van előrehaladás?
Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet.
Ha van még kérdés, nyisd újra nyugodtan.
Üdv
