### ISSUE TITLE
customerVatStatus 

### ISSUE THREAD

**Issue by NyBela** [nav-gov-hu/Online-Invoice#583]
Tisztelt Fejlesztők!
Érdeklődöm, hogy a teszt környezetben a customerVatStatus mikortől lesz használható?
Jelenleg:
Invalid content was found starting with element "{"http://schemas.nav.gov.hu/OSA/3.0/data":customerVatStatus....
Köszönöm.

**Comment by NTCA-supporter** [comment]
Szia @NyBela !
A hét második felében, péntek/szombat magasságában.
Jelezni fogjuk.
Üdv

**Comment by NyBela** [comment]
Köszönöm a választ.

**Comment by scheeri** [comment]
Üdv!

Nálam még mindig sikertelen a számla beküldése a customerVatStatus miatt! Érdeklődnék mikorra lesz jó?

**Comment by NyBela** [comment]
Pedig működik.

**Comment by scheeri** [comment]
Igen látom, sémát kellett frissíteni. De nem értem ezt hogy képzelik, hogy dec 8-án sémát változtatnak, jan. 1-től meg kötelező a használata!
