### ISSUE TITLE
Sémaváltozások changelog segítség

### ISSUE THREAD

**Issue by NTCA-supporter** [nav-gov-hu/Online-Invoice#584]
Sziasztok!

A teszt rendszeren elérhető alkalmazásverzióhoz képest történtek séma szintű és egyéb változások.
A könnyebb átláthatóság miatt ezt egy külön fejezetben (2.8) összefoglaltuk a changelogban:
https://github.com/nav-gov-hu/Online-Invoice/blob/master/src/schemas/nav/gov/hu/OSA/CHANGELOG_3.0.md

Az összes dokumentáció feltöltésre került ide githubra, a teszt rendszer és az éles rendszer dokumentációk oldalára.
Az alkalmazás, ami az új sémát támogatja, a hét második felétől lesz elérhető teszt környezeten.

Üdv

**Comment by szottokar** [comment]
Szia,
az az ultra nagy gáz, hogy a teszt rendszer dokumentációk oldalára mai dátummal [XML séma definíciók: OSA v3 Sémák (utoljára frissítve: 2020.12.08.)] az eggyel ezelőtti sémafájlok kerültek fel!

**Comment by NTCA-supporter** [comment]
@szottokar javítottuk, köszi a jelzést.

**Comment by renced42** [comment]
Kedves @bcdel, semmi különbség nincs, csak a publikálás dátuma, mivel az éles oldalra hamarabb került ki mint a tesztre.

**Comment by NTCA-supporter** [comment]
Telepítésre került az alkalmazásnak az a verziója, ami az új sémát támogatja.
