### ISSUE TITLE
Példa data XML vatAmountMismatch esethez - milyen keresztellenőrzések lesznek?

### ISSUE THREAD

**Issue by rtoth0407** [nav-gov-hu/Online-Invoice#586]
Sziasztok! Kedves @NTCA-supporter !

Kérünk szépen példa XML-t a térítés nélküli átadásos esetekhez!
A vatRateType kitöltése még kitalálható, de az egyes érték mezők töltése már nem.
Meg kell jeleníteni az ÁFA alapot, vagy elegendő csak az ÁFA érték?
Az érték mezők konzisztenciájára számos ellenőrzés van beépítve. Lefutnak ezek erre az esetre is? Hogyan?

Köszönettel
Réka

**Comment by rtoth0407** [comment]
Tudtok infot adni a témában? Nem tudunk haladni a fejlesztéssel!

**Comment by NTCA-tax** [comment]
A vatAmountMismatch éppen azon eseteket takarja, ahol bármilyen kombinációban lehet vagy éppen nem lehet összeg kitöltve. Ezért nem is adunk warningot akkor, ha az adóalap nincs, de adóösszeg van, vagy fordítva, vagy egyik sincsen. Ezeket az eseteket nehéz is programozni, mivel a felhasználónak kell tudnia például egy ingyenes eszközátadásnál, hogy a számlát mikor hogyan kell helyes adattartalommal kiállítani.
