### ISSUE TITLE
[Q&A]INCORRECT_SUMMARY_CALCULATION_VAT_CONTENT_GROSS_AMOUNT_SUMMARY_SIMPLIFIED

### ISSUE THREAD

**Issue by tkelemen73** [nav-gov-hu/Online-Invoice#587]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Egyszerűsített számlát küldtem be, amire kaptam a INCORRECT_SUMMARY_CALCULATION_VAT_CONTENT_GROSS_AMOUNT_SUMMARY_SIMPLIFIED figyelmeztető üzenetet, ami nem tűnik jogosnak.
A számlában 1 tétel van, ami TAMos, 200.000 Bruttó értékkel, az összesítőben is ez a 200.000 jelenik meg, mégis jön a figyelmeztető üzenet, hogy 200.000-el eltér.
Tranzakció azonosító: 372DOF6VS417N9EQ

Ha ugyanezt a számlát, csak nem volt benne TAM-osként küldöm be, hanem 27%-os ÁFÁval (vagyis vatContent 0.2126), akkor viszont nincs figyelmeztető üzenet.
Tranzakció azonosító: 372DOZC3H5MSW8FI

Ugyanaz a két számla, csak a ÁFA tartalom tér el egymástól, a 0%-osnál jön figyelmeztető, szerintem tévesen, az ÁFÁsnál nem.

Összeraktam a data példák között megadott számlát (3.7.1 példa: Belföldi termékértékesítés egyszerűsítet számla, Belfoldi egyszerusitett szamla.xml), ennél is jön a figyelmeztető üzenet, ugyanúgy az ÁFA mentesre vonatkozólag.
Tranzakció azonosító: 372DHL0F15RW3BEH

**Comment by NTCA-supporter** [comment]
Szia @tkelemen73 !
Nem néztem meg a beküldött számládat, de elhiszem, hogy helyes :) A hibáról mi is tudunk, fogjuk majd javítani.
Addig maradjon nyitva, hogy más ne nyisson új issuet.
Köszi

**Comment by NTCA-supporter** [comment]
Közben látom, hogy az #550 ugyanez a hiba szerintem, így ezt zárom.
Üdv
