### ISSUE TITLE
[Q&A] Külföldi ügyfeleknek kiállított számlák beküldési rendje 2021.01.04-től

### ISSUE THREAD

**Issue by zonehun** [nav-gov-hu/Online-Invoice#589]
Csak tisztázásként szeretném leírni és egyben kérdezni, hogy jól látjuk-e, hogy 2021. január 4-től az összes:
- belföldi adóalany
- belföldi nem adóalany és nem magánszemély
- belföldi magánszemély
- külföldi közösségi adóalany (EU országbeli)
- külföldi nem közösségi adóalany és nem  magánszemély
- harmadik országbeli adóalany (EU-n kívüli)
- harmadik országbeli nem adóalany és nem magánszemély
- külföldi magánszemély
számára kiállított minden számlát be kell küldeni? 

Tehát tömören: korlátozás, válogatás nélkül minden számlát beküldünk, ugye? (nyilván az anonimizálási és egyéb szabályok betartása mellett)

Köszönöm a válaszokat.

**Comment by GabiSzamla77** [comment]
Sziasztok!
Szerintem kétféle biztosan kimarad:
- ha a teljesítési hely nem belföldön van
- ha számviteli bizonylat helyett számlát állítottak ki.
Az elsőnél nem pontosan idéztem a jogszabályt, a második pedig le volt írva a korábbi tájékoztatókban, hogy nem kell beküldeni. Nem láttam, hogy ebben lenne változás, de még nem veséztem ki az Áfa törvény módosítást szóról szóra, hogy ezt érintette-e (165.§.).
Persze ezt nyilván befolyásolja, hogy az adott számlázó program kezeli-e ezeket az eseteket, vagy akarjuk-e, hogy kezelje, vagy az ügyfelünk akarja-e...
Azért majd megnézem még pontosan, de ez a két eset maradt az emlékeimben.

**Comment by zonehun** [comment]
Nemt tudom.... programozóként azt szeretném, hogy olyan esetek legyenek, amik teljesen egyértelműen azonosítható és algoritmizálhatók. Nem véletlenül kérdeztem, mert jó lenne nem agyon nyomni a szoftvereinket mindenféle eszement jogalkotói szabályokkal - melyek olyan eseteket kezelnek le, amik jó, ha egy évben egyszer vannak.

Amúgy most a nagy kedvencem a 3.0-ban az áfa kódok mellé a reason megjelenítése :) Tök vicces, hogy ha már beküldök egy kódot, akkor ahhoz minek a reason, amikor azt a NAV amúgy is látja. Hozzáteszem a reason-t sztem eleve mindenki úgy fogja beküldeni, ahogy a kézikönyvből kimásolja - nem fogja ezzel szenvedtetni ez egyszeri pénzügyes kislányokat, akik a számlázó mögött ülnek. Erről mintha mindig mindenki elfeledkezne..... mármint, hogy kik ezeknek a rendszereknek a felhasználói. Sajnos az ő munkájukat nehezítjük minden extra szabállyal.

**Comment by betasofthu** [comment]
@GabiSzamla77 Erről még nem nagyon volt szó, mármint arról, hogy a teljesítési hely külföldön van. Ráadásul van egy "és" -sel csatolt mellékmondat, ami megváltoztatja az értelmét:
_Az adóalany köteles adatot szolgáltatni az adó- és vámhatóság részére azon általa teljesített termékértékesítésekről, szolgáltatásnyújtásokról kibocsátott vagy kiállított számláról, számlával egy tekintet alá eső okiratról, amelyre e törvény rendelkezéseit kell alkalmazni a 158/A. § értelmében, kivéve azon termékértékesítésről, szolgáltatásnyújtásról, melynek teljesítési helye a Közösség másik tagállama, **és amely termékértékesítés, szolgáltatásnyújtás tekintetében az adóalany adófizetési kötelezettségének az Art. távolról is nyújtható szolgáltatásokat nyújtó adózókra vonatkozó különös szabályai szerint tesz eleget._**
A két feltétel együttes teljesülése esetén nem kell beküldeni ezeket a számlákat? (A 2021.január 1-től érvényes áfa törvény 10. melléklet 1. -ben "és" van, amit lehet felsorolásnak is értelmezni.)

**Comment by szecsenyizoltan** [comment]
https://op.europa.eu/webpub/grow/factsheets/vat-for-companies/hu/

**Comment by zonehun** [comment]
A kérdés továbbra is fennáll. Én nem szeretnék jogászkodni. Jogalkotói szándékot kitalálni, stb. Egyértelmű állásfoglalást várok. A szoftvereket működtető algoritmusok egyértelmű szabályok mentén íródnak és működnek.

Tehát tömören: **korlátozás, válogatás nélkül minden számlát beküldünk, ugye?** (nyilván az anonimizálási és egyéb szabályok betartása mellett)

köszönöm.


ps. 2021.01.04 indulni kellene. Addig van 25 naptári nap és persze közben Karácsony, ünneplés, miegymás.

**Comment by nbeeps2** [comment]
Én szerintem nem kell elveszni a részletekben... Küldjél be minden számlát a 3.0 XSD-nek megfelelően. Ennek nem tárgya, hogy hol van a teljesítés helye vagy hogy a számlát számviteli bizonylat helyett állították-e ki vagy sem. Ahogy írtad ezzel csak a felhasználók életét nehezítenéd és utána magadat szívatod vele, hogy válaszolhatsz az ezzel kapcsolatos értetlenkedő keresztkérdésekre. Sőt, ha meg is kérdezed egyáltalán nem biztos, hogy a számla kiállítója fogja-e tudni, hogy hol lesz a teljesítés helye vagy hogy neki nem is kellett volna számlát kiállítani, mert elég lett volna egy számviteli bizonylat. Ilyet számlázó programmal nem is igazán lehet kiállítani, a Word-del meg nem fog cseszegetni, szóval úgyis az lesz a vége, hogy számlát állít ki. 

Nem január 4-től kell indulni, hanem április 1-el, de ha lesz éles 3.0 január 4-től (az ígéretek szerint) és Te is kész leszel addigra, akkor indulhatsz január 4-től, de egyáltalán nem kötelező addigra mindenkinek kész lenni és áttérni a 3.0-ra.

**Comment by GabiSzamla77** [comment]
Sajnálom, hogy némi indulatot váltott ki a bejegyzésem. 
Természetesen mindenki mérlegeli az ügyfélkörét, gyakorlatát, rendszerét. Csak jelezni szerettem volna, hogy én úgy tudom, nem minden számlának nevezett számlát kell beküldeni az előírások alapján. 

- A számviteli bizonylat most júliusban volt "nagy" téma, itt találjátok a NAV álláspontját, amit abban a tájékoztatóban is szerepeltetett, amit közvetlenül kiküldött az adózóknak.
 https://nav.gov.hu/nav/ado/afa/Gyakran_ismetelt_kerd20200728.html
Nekünk ezt muszáj volt beépítenünk, mert volt olyan ügyfelünk, aki csak ilyen számlát állított ki, és ragaszkodott ahhoz, hogy neki bizony ezért nem kell regisztrálnia, hiszen nincs adatszolgáltatási kötelezettsége. De más ügyfeleinket pedig egyáltalán nem zavarta, hogy folyamatosan bemennek ezek a számlái is.
- A teljesítési hely kivétellel egyelőre mi sem látunk tisztán, igaz, nem is fordul elő nálunk (még...).

Teljesen egyetértek és együttérzek veletek abban, hogy ezek nélkül is van elég feladatunk az átállással mind fejlesztői, mind az azt támogató szakmai szempontból. A hiteles választ pedig egyértelmű, hogy a NAV mondja majd ki ebben a témában is.

**Comment by zonehun** [comment]
@nbeeps2 és @GabiSzamla77 köszönöm szépen a válaszaitokat. 

Én azért szeretnék látni egy hivatalos álláspontot, mert éppen ezen a fejlesztői fórumon láttam egy olyan bejegyzést anno külföldi ügyfeleknek kiállított számlákkal kapcsolatosan (még az 1.1 verzió környékén), hogy amennyiben beküldünk olyan számlát, amit nem lenne szabad, akkor a NAV szankcionálhat! Persze azt is leírta @NTCA-tax akkor, hogy a hatóság minden körülményt mérlegel a szankció kiszabásakor. 

Ez engem - és talán másokat - sem nyugtat meg. Szeretném tisztán látni, hogy mindenféle kilátásba helyezett szankció nélkül beküldhetünk-e mindent és nyugodtan hajthatjuk minden este álomra a fejünket. :)

**Comment by renced42** [comment]
Kedves @zonehun 

Hivatalos álláspont a hatályos ÁFA tv-ben van 10.sz melléklet.
Minden kell jelenteni illetve van kivétel, még:

Azon termékértékesítés, szolgáltatásnyújtás, melynek teljesítési helye a Közösség másik tagállama, és amely termékértékesítés, szolgáltatásnyújtás tekintetében az adóalany adófizetési kötelezettségének az Art. távolról is nyújtható szolgáltatásokat nyújtó adózókra vonatkozó különös szabályai szerint tesz eleget.

Ha esetleg nem így van @NTCA-tax kérlek korrigáld

**Comment by szecsenyizoltan** [comment]
@zonehun Nem neked írtam, hanem @betasofthu -nak. (Ő volt felettem, bár nem hivatkoztam rá.)  Kicsit finomabban a minősítésekkel, ha kérhetem.

**Comment by nbeeps2** [comment]
@renced42 @NTCA-tax : tegyük fel a program ezt nem tudja detektálni, illetve ha van erre GUI akkor a felhasználó nem jól ítéli meg és bemennek az ilyen számlák is a NAV-hoz. Ez probléma? ;)

**Comment by zonehun** [comment]
@szecsenyizoltan megkövetlek, nem állt szándékomban minősíteni, csak a témát mederben tartani.

@nbeeps2 Köszi, a pontosítást! ;)

**Comment by nbeeps2** [comment]
@renced42:  "Azon termékértékesítés, szolgáltatásnyújtás, melynek teljesítési helye a Közösség másik tagállama"
Hát mi csak azt látjuk, hogy a vevőnek megadtak EU adószámot, a customerVatStatus-a OTHER lesz, ki lesz töltve a neve és a címe, valamint az EU adószámot, azt csókolom. A számlázó programnak fogalma sincs arról, hogy hol a teljesítés helye vagy távolról nyújtatható szolgáltatást számláz, sőt egyáltalán szolgáltatást számláz vagy terméket ;) Szóval ezek a számlák is annak rendje és módja szerint BE FOGNAK MENNI ;)

**Comment by topybear** [comment]
Nálunk ez úgy lett megoldva, hogy az ilyen tranzakciókat egy erre dedikált bizonylattípussal kell számlázniuk, annál meg nincs beállítva, hogy NAV felé jelentendő. 

Az meg, hogy a felhasználó a számlakiállítás során tudatosan csal vagy csak trehány, hitem szerint nem a számlázó program felelőssége. Mint ahogy azt sem tudod a számlázó programból ellenőrizni, hogy mind a 20 mázsa cement rajta van-e a számlán, vagy csak 5 és a többit megoldották "okosba", úgy az ellen sem tudsz védekezni, ha szándékosan rosszul állítja be a teljesítési helyet.

**Comment by nbeeps2** [comment]
@topybear: és akkor elérkeztünk az általam írt 1-es ponthoz, miszerint a felhasználó rosszul ítéli meg a gazdasági eseményt (a te szóhasználatodban "trehány") és nem megy be a számla a NAV-hoz, pedig be kéne. Mennyivel jobb akkor már az a megoldás, amikor nem próbálsz belemászni a részletekbe és egyszerűen csak küldöd az összes számlát. Mindenkinek egyszerűbb, neked se kell vele foglalkozni és a felhasználó sem bosszankodik, hogy miért tettél be egy 23 ezredik kapcsolót, legördülő menüt a programodba, ráadásul azért, ami a felhasználók 99%-nál nem is fog soha felmerülni...

**Comment by NTCA-tax** [comment]
Lehet, hogy túlbonyolítjátok ezt a kérdést, de hozzá kell tenni, hogy nem vagyok számlázó szoftver fejlesztő...

Az áfa törvény rendelkezéseit próbáljátok meg algoritmizálni, mintha szimplán gépi algoritmusokkal leírható követelményhalmaz lenne. Előfordulhat, hogy nem reménytelen lenne az ilyen kísérlet, viszont azzal is egyetértek, hogy ha nem valami nagyon erős gépi intelligencia húzódik meg benne, akkor egy túlbonyolított program lehet ennek a vége. És még egyszer hangsúlyoznám, hogy nem vagyok szoftver fejlesztő, ezért ha van valami egyszerű megoldás, akkor cáfoljatok meg.

A külföldi ügyfeleknek kiállított számlák esetében a kötelező adattartalom megtalálását lehet, hogy egyszerűbb a felhasználóra bízni, még akkor is, ha hibázhat. Egy informatikai rendszerben általában az ember jelenti a legnagyobb kockázatot, mivel a gép mindig logikusan jár el, de az ember nem mindig. Azonban az ember rendelkezik azzal az ismeretanyaggal, ami alapján az olyan eseteket is le tudja kezelni, amire a gép nem képes.

Visszatérve az alapkérdésre, ha 3.0-ban korlátozás nélkül beküldi egy program a számlákat, akkor nagyot nem hibázhat. Persze a megfelelő adatstruktúrát el kell találni, a magánszemély adatait ki kell szedni stb.... Amennyiben persze csak számlák vannak benne, és nem szállítóleveleket, belső elszámolásokat is megküld valaki számlaadat-szolgáltatásként.

**Comment by betasofthu** [comment]
@NTCA-tax: A két feltétel (külföldi teljesítési hely,távoli szolgáltatás) együttes teljesülése esetén nem kell beküldeni ezeket a számlákat vagy bármelyik feltétel teljesülése esetén nem kell beküldeni a számlákat?

**Comment by zonehun** [comment]
@NTCA-tax Nagyon szépen köszönöm a választ! E szerint fogunk eljárni. Természetesen csak számlákat küldünk be, tartva az előírt 3.0-ás struktúrát. :) 

A választ megkaptam, a témát zárom. Köszönöm.

**Comment by nbeeps2** [comment]
@NTCA-tax : "Visszatérve az alapkérdésre, ha 3.0-ban korlátozás nélkül beküldi egy program a számlákat, akkor nagyot nem hibázhat. Persze a megfelelő adatstruktúrát el kell találni, a magánszemély adatait ki kell szedni stb"
Na ez a beszéd, köszönjük! Én is így gondoltam! ;)

**Comment by betasofthu** [comment]
@NTCA-tax: A két feltétel (külföldi teljesítési hely,távoli szolgáltatás) együttes teljesülése esetén nem kell beküldeni ezeket a számlákat vagy bármelyik feltétel teljesülése esetén nem kell beküldeni a számlákat?

**Comment by betasofthu** [comment]
#608 alatt új kérdést indítottam a melléklet szövegének értelmezéséről.

**Comment by NTCA-tax** [comment]
OK, akkor nem nyitom újra ezt az issue-t. Csak egy kis türelmedet kérem...
