### ISSUE TITLE
[FEATURE]query paraméterek

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#59]
Az insDate a querydigest-ben jelenleg csak from-to dátumot tartalmazhat. Szerintem érdemes lenne megengedni időpont megadását is, ez csökkentené a szerver terhelését. Ha ugyanis napjában többször futtatjuk, akkor elegendő lenne a korábbi lekérdezés időpontjától indítani. Kliens oldalon persze a jelenlegivel is megoldható a dolog, a már korábban lekérdezett számlák kihagyásával az eredmények feldolgozásánál, de a szerver feleslegesen fog dolgozni.

**Comment by kabelnet2** [comment]
Ez is query feature, nem nyitok új issue-t:
invoiceNumberQuery-ben érdemes lenne engedélyezni az adószámot, mint nem kötelező paramétert. Bejövő számláknál ugyanis két partner kibocsáthat azonos számlaszámmal számlát. Ilyenkor az egyértelmű lekérdezéshez szerintem kellene az adószám is.

**Comment by csaszko** [comment]
Ezt én is felvetettem már korábban, meg azt, hogy legyen esetleg valami változó amit vissza tudunk adni, hogy már lekértük, hogy a lekérdezéseket illetve az adathalmazt csökkentsük ezáltal  szerverek terhelését is. A válasz az volt úgy emlékszem, hogy valami időben(már nem emlékszem pontosan melyik volt) amit a NAV szolgáltat abban bízhatunk.. és az alapján lehet lekérdezni....

**Comment by kabelnet2** [comment]
csaszko: jó ráhagyunk egy óra pluszt, de még akkor is jobb, mintha az egész napot kérdeznénk le.

**Comment by csaszko** [comment]
Igy van! De a legkevesebb adatforgalom meg terheles az lett volna ha van erre egy valtozo...akkor biztosan nem kersz le atfedessel...nem hat nem.

**Comment by kabelnet2** [comment]
És ha két telephelyről akarod nézegetni a számlákat? Az egyik lekéri, a másik meg nem kapja meg, mert az első már beállította a flag-et. Nem ezt szerintem nem a NAV oldalon, központilag kell megoldani.

**Comment by csaszko** [comment]
Én a bejövő számlákról beszélek.. de, lehet hogy, rosszul értelmeztem a felvetésed és totál elbeszéltem melletted :) arra vonatkoznak az alábbiak is.

Az én felvetésemben Te állítod az értékét be amikor jónak látod, de ettől elhatárolódtak. De amúgy 2 telephelyen ha akarod lekérni a számlákat (ha tényleg egy dologról beszélünk) akkor letöltöd az egyiken és átadod a másiknak is valami formában az infót házon belül. Az én elképzelésemben amúgy ezt vagy központilag célszerű megoldani vagy sehogy. Mert telephelyenként bejövő számlákat lekérni mi alapján szeretnéd? Miért kell mindegyiknek mindenhol meglennie? Gondolom a feldolgozása egy központi helyen történik (általában) vagy mindenki foglalkozik mindennel...?

**Comment by kabelnet2** [comment]
Az InvoiceDigestType csak a batch index-et tartalmazza, de nincs benne a módosított számla száma. A batch index a NAV-on (és a számla kiállítóján) kívül senkinek nem mond semmit, még a számlaszám lekérdezéséhez sem jó, ahhoz a tranzakció azonosítót és az index-et lehet használni.
Ezen az oldalon a két számlaszámra van szükség (módosító és módosított), mert pl. ez kell az ÁFA bevallás mellékletének összeállításához.
Mindenképpen hasznos lenne, ha a QueryInvoiceDigest visszaadná a módosított számla számát is.

**Comment by NTCA-developer** [comment]
Sziasztok!

Nagyon köszönjük a felvetéseteket. Reagálok hamarosan.

**Comment by NTCA-developer** [comment]
Sziasztok!

Itt is vagyok. Ha jól számolom, 3 felvetést fogalmaztatok meg.

1) insDate paraméter legyen dateTime-os. Rendben, a soron következő verzióban átállunk óra perces bemenetre a dátum alapúról, és akkor lehet 24 óránál kisebb intervallumot is megadni. Breaking change lesz, de most még nem gond. És legalább egységes lesz a kimenettel, mivel a listázó válaszban eleve timestamp megy vissza.
2) Számlaszám lekérdezőben lehessen a kiállító vagy a vevő adószámára szűrni. Nagyon köszi még egyszer a felvetést, ez nem csak hogy kell hanem most konkrétan hibás is, mert ha több kiállító számlázott ugyan annak a vevőnek ugyan azzal a számlaszámmal, akkor azt a jelenlegi séma alapján nem lehet vevői oldalon lekérdezni. Javítjuk.
3) InvoiceDigestType típusban legyen benne az eredeti számla száma. Beletehetjük, bár a benefitjét nem látom, mivel kötegelt módosításnál minden számlának 1 számlaszáma lesz csak, az igény ennyi erővel a "normál" módosító számláknál is hiányolhatná ugyan ezt az adatot. De nem fáj, úgyhogy beletesszük, de akkor már bementő paraméterként is, mivel szeretnénk szimmetrikusnak megtartani a paramétereket: amire szűrhetsz azt megkapod válaszban is.

+1) Mivel a 2) pont miatt a /queryInvoiceCheck operációhoz is hozzá kell nyúlni, felvetődött bennem hogy mi volna, ha a válasz tartalmazná a tranzakció azonosító értékét is. Tegnap éppen volt egy lassulás az éles környezetben, és láttam hogy többen elvesztették a beküldés válaszüzenetét. Az operációt pont lehetne erre az esetre is használni, hiszen nem csak a számla létezése derülne ki belőle a teljes adat felolvasása nélkül, hanem a tranzactionId értéke is. Mivel @csaszko -val ti ketten elég sok lekérdezési ötletet adtatok, érdekelne a véleményetek.

A módosítások terv szerint a 2.3-as release-ben fognak kikerülni.

**Comment by kabelnet2** [comment]
Szia,

1. Én úgy tervezem, hogy automatikusan napjában egyszer kérem le az előző napi számlákat (pl. hajnalban) és ha valaki dolgozni akar a számlákkal, akkor csinálok egy lekérdezést az aznapiakra, az adott időpontig. Ha csak dátum van, akkor itt lehet átfedés pl. másnap hajnalban, ha pontosabban lehet megadni, akkor csökkenthető a terhelésetek. Mivel nálatok idő adat is van az insDate-ben, ez biztosan nem okoz nektek problémát.

2. Igen erre szükség van. Tovább is lehet gondolni, mert nincs szükség az invoiceDirection-re: az outbound-nál a saját adószámot kell megadni. Persze ha más az adatbázisotok felépítése és ezért kell a direction, nem gond megadni.
**Figyelem! Ugyan ez a gond akkor is, ha QueryInvoiceDigest-et akarunk használni originalInvoiceNumber paraméterrel.**

3. Igen, gondoltam rá, hogy átfogalmazom amit beírtam, hogy ne a batchIndexre, hanem a hiányzó második számlaszámra vonatkozzon. A bejövő számlák lekérdezésének fontos szerepe lesz az ÁFA bevallás mellékletének összeállítása. Ehhez kell az eredeti számla száma és annak módosítási története (ha nem saját adatbázisban tartom, akkor egy queryInvoiceDigest számlánként). Az eredeti számla számát mindenképpen elő kell bányászni, ezért gondoltam, hogy kisebb a terhelés, ha nem külön lekérdezésben történik, hanem beteszitek a result-ba.

Ha nem lesznek gyakoriak nálatok a hibák, akkor a checkResult változtatást nem igazán érzem indokoltnak. Ha a számla létezik és nincs meg a trid, akkor egy queryDigest-el lekérhető.

UI: működik a teszt rendszer support-ja? Szerettem volna tesztelgetni, de RESTEASY003210 hibát kaptam mindkét rendszerben a V2-es query-kre. Természetesen nem kizárva, hogy én szúrtam el valamit, várom a helpdesk válaszát. Küldjem inkább az éles support-nak?

**Comment by NTCA-developer** [comment]
Szia @kabelnet2 

Köszi a válaszokat. A 2-est tudom, egy az ősük, de köszi hogy felhívtad a figyelmem. Van support a tesztre is, de még nem láttam megérkezni V2-es témájú kérést. Ha beírod mit küldesz és hova akkor megnézem szívesen.

**Comment by kabelnet2** [comment]
Szia, a mellékelt levelet küldtem a supportnak (beletettem a mellékleteket is, ennyi a változtatás).
Előre is köszönök minden ötletet.

[V2query_problem.txt](https://github.com/nav-gov-hu/Online-Invoice/files/3472046/V2query_problem.txt)

**Comment by NTCA-developer** [comment]
Szia!

Az URL-en a V2 az v2. AS/400? :)

**Comment by kabelnet2** [comment]
Köszi! Így már működik a dolog.

**Comment by kabelnet2** [comment]
Még egy dolog: tegyük fel, hogy van egy trid és egy indexem és semmi más. Akkor a queryDigest-el nem tudom lekérdezni a számla adatait, mert valamit ki kell töltenem a mandatory paraméter szekcióban, de egyik adatot sem ismerem. A trid+index az szerintem azonos az originalinvoice number-rel, hiszen az egy számlát (illetve annak egy műveletét) jelenti. Vagyis szerintem ott lenne a helye a mandatory szekcióban.
A csak trid ugyan ez: nem ismert a többi adat, nem lehet megadni a mandatory szekciót.
Vagyis szerintem a transactionqueryparam-nak a mandatory részben a helye, választható paraméterként.

Ebből szerintem az is következik, hogy amíg nem teszitek be a módosított számla számát a digestresultba, nincs más megoldás, mint lekérni a módosító számlát magát és elemezni azt. 
Más ötlet?

**Comment by kabelnet2** [comment]
A módosított számla elérése úgy is lehetséges lenne, ha a digest lekérdezés számlaszámmal művelet akkor is az eredeti számlát és annak összes módosítóját adná vissza, ha számlaszámként egy módosító számlát adunk meg. Jelenleg ilyenkon nincs eredmény, page=0-t ad vissza.

**Comment by kabelnet2** [comment]
Módosító számla feltöltéséhez az online számlák közé két (CREATE line oper. esetén) adat is kell, ami a számla kiállításához nem kell: a modificationIndex és az utolsó használt sorszám. A modificationIndex meghatározható egy digest lekérdezéssel, de az utolsó sorszám nem. Amennyiben nem nagy probléma, szerintem érdemes lenne visszaadni valamilyen digest lekérdezésben, mert akkor nem lenne szükség ennek nyilvántartására a számla kiállítói oldalon és biztosan jó lenne a megadott sorszám.

**Comment by NTCA-developer** [comment]
Szia @kabelnet2 

Ha láttad az új sémát és doksit, akkor tudod hogy a 3 felvetést beépítettük a működésbe. Kell-e ez a bejelentés még, vársz-e még választ valamire?

**Comment by kabelnet2** [comment]
Igen, köszönöm, láttam a változásokat. Egy kérdés maradt: mikortól lesz használható az élesben az új xsd-nek megfelelő lekérdezés? Mi ugyanis már használjuk élesben bevételezéshez, persze kiegészítőkkel, amik most már elhagyhatók lesznek.

**Comment by KimmerGy** [comment]
Előzőhöz kapcsolódóan:
A 2.0 XSD élesbe állításakor lesz olyan időszak (pl 1 hónap) amikor az 1.1 XSD -vel is és a 2.0 XSD -vel is lehet számlát beküldeni és lekérdezéseket végrehajtani ?

**Comment by NTCA-developer** [comment]
Sziasztok!

@kabelnet2 
Nehéz megmondani, még van több elkészült release előtte, hogy települne a módosítás. Szerintem egy hónap kb, de nem tőlünk függ az átfutása onnantól, hogy elkészültünk.

@KimmerGy 
Igen, lesz. Az erről szóló hír már készül, az oldalon meg fog jelenni.

Köszönöm mindenkinek, akkor lezárom.
