### ISSUE TITLE
[Q&A]  csoportazonosító adószám hiányzik  

### ISSUE THREAD

**Issue by kristofbela** [nav-gov-hu/Online-Invoice#590]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**

A leírásban ez szerepel 
Ha   a   szállító   (eladó)   csoportos áfaalany,   akkor   a csoportazonosító    számát    (áfa-kódja:    „5”)    kell    a    supplierInfo/supplierTaxNumberelemben szerepeltetni, míg a csoporttag „saját” adószámát (áfakódja: „4”) a supplierInfo/groupMemberTaxNumberelemben kell megadni

Mi van abban az esetben ha nem tudjuk  csoportazonosító  adószámot  amiben az "5"  áfa-kód szerepel,
csak a csoporttag „saját” adószámát

**Comment by NTCA-supporter** [comment]
Szia!
Ha ki van töltve az áfakód is, akkor kapsz egy INCORRECT_VAT_CODE_SUPPLIER WARN-t.

Üdv

**Comment by kristofbela** [comment]
**Mi a megoldás**  ha csoporttag „saját” adószámának  (áfakódja: „4”)   ezt ismert ez le is tudjuk kérdezni ezzel nincs probléma
de nem tudjuk a hozzátartozó csoportazonosító  (áfa-kódja: „5”) adószámot (pl a vevő sem tudja nincs a pecséten sem) ! 

Ebben az esetben kötelező mind kettő adószám küldése ,vagy ennek hiányában nem tudok számlát kiállítani ?

**Comment by nemethszilvia** [comment]
Ha tudjátok a csoporttag adószámát, akkor a NAV oldalán le tudjátok kérni hozzá a csoportazonosítót: https://nav.gov.hu/nav/adatbazisok/adatbleker/csoportos_afaalanyok

**Comment by NTCA-supporter** [comment]
Sziasztok!
A queryTaxPayer-ben visszaadjuk, ha csoporttag adószámmal kérdezel be, hogy az melyik csoportnak a tagja, ez a vatGroupMembership tag a válaszban.
Ezzel szerintem megoldható a problémakör.
Üdv

**Comment by kristofbela** [comment]
köszi a segítséget vatGroupMembership a jó megoldás
Üdv
