### ISSUE TITLE
NAV Online Számlázóból kiállított számlánál miből látszik, hogy teszt vagy éles rendszerből lett kiállítva?

### ISSUE THREAD

**Issue by nemethszilvia** [nav-gov-hu/Online-Invoice#591]
A számla kibocsátója megküldött egy NAV Online Számlázó programmal készített számlát augusztusban. Később küldött egy újabbat, másik sorszámtartományból. Ezen újra kiszámlázta az ügyletet. A szöveges részbe megjegyzésként beleírta, hogy "Helyesbítő számla. Téves számlázás", valamint hogy az eredetileg megküldött számla a NAV teszt rendszeréből lett kiállítva. Állítása szerint az eredeti nem hiteles bizonylat, de azt érvényteleníteni sem tudja, mert időközben a NAV teszt rendszeréből is eltűnt. Ezért is nem számlával egy tekintet alá eső okiratként állította ki az újat, hanem alapszámlaként, a szöveges részben hivatkozva az eredeti sorszámára.

A kérdésem az, hogy befogadói oldalról hogyan lehet ellenőrizni, hogy tényleg teszt rendszerből lett kiállítva az eredeti bizonylat? A számlán semmi nem utal erre. Nem kellene a kinyomtatott számlán is megjelennie az "online számlázó MINTA" vízjelnek? 

Mivel a számla még szeptember 30. előtt, tehát a moratórium idején lett kibocsátva, az, hogy a NAV Online Számlázóból történő lekérdezésben nem látszik a bizonylat, még nem feltétlenül jelenti azt, hogy teszt rendszerből lett kiállítva. (Sőt, a moratórium lejártát követően is előfordulhat, hogy éles rendszerből kiállított számla nem jelenik meg valamilyen hiba folytán, tehát ez sem ad támpontot.)

Az ügylet áfája levonható, ezért az M-lapon adatot kell szolgáltatni. A fentiek miatt viszont nem egyértelmű, hogy melyik számla szolgálhat a levonás tárgyi feltételéül, és ehhez kapcsolódóan melyik adatait kell jelenteni a 2065M-en.

Előre is köszönöm a segítséget!

**Comment by NTCA-supporter** [comment]
Kedves @nemethszilvia!

Az "online Számlázó Teszt" vízjelnek kell ott lennie. Én most gyorsan megnéztem és jelenleg nem kerül oda a teszt környzeten. Utána nézünk. Köszi a jelzést.

**Comment by nemethszilvia** [comment]
Köszi! Ezek szerint sajnos a mi esetünkben a vízjel hiánya alapján sem egyértelmű, hogy milyen rendszerből lett kiállítva. Jól gondolom, hogy marad az, hogy a kibocsátó nyilatkozata alapján elfogadjuk, hogy az elsőként átadott számla tesztrendszeres volt, és ezért nem az, hanem a második a hiteles bizonylat?

**Comment by Macskafarka** [comment]
@nemethszilvia A helyzet bonyolult, de lehet tisztázni.
Ha a számla papír alapú volt, és a számla befogadó nem tudott a számlaképből meggyőződni arról, hogy ez csak játékból kiállított számla, akkor helyesen járt ez, ha az alapján adólevonási jogot gyakorolt (feltéve, ha egyéb körülmények is megvoltak, magyarul volt alapja a számlának, volt mögötte termékértékesítés, vagy szolgáltatás nyújtás). 
Ezt a számlát a számlakibocsátó érvénytelenítheti, de az érvénytelenítő bizonylatnak vannak alaki és tartami kellékei, amit az áfa tv. cogens előírásként tartalmaz. Plusz vonatkozik rá a szigorú számadás alá vétel.
A számla befogadónak észnél kell lennie, amikor újabb számlát kap ugyanarról a gazdasági eseményről. Egyrészt csak akkor fogadhatja be módosító okiratként, ha megfelel a módosító okirattal szemben támasztott követelményeknek, másrészt csak számlát lehet módosítani, a "nemszámlát" nem lehet módosítani. tehát, ha a számlakibocsátó megjegyzésben hozza a vevő tudomására azt, hogy a legelső számla nem is érvényes számla volt, akkor azt érvényes módosító okirattal nem tudja módosítani.
Ettől függetlenül a számlakibocsátó egy gazdasági eseményről csak egyszer gyakorolhat adólevonási jogot, jelen esetben az első számlát kell annak tekintenie, és a későbbit visszautasítania. (Feltéve, ha az első számlán nem látszott, hogy az csak fiktív számla).
Azonban itt felvetődik a "hamis közokirat", illetve a "költségvetési csalás" tényállási elemei is, amelyben érintett a számlakibocsátó, és érintett a számlázó program forgalmazója is. Értem én, hogy a NAV programnak is van ÁSZF-e, de az polgári jogi eszköz, a bűncselekmények alól az nem mentesít. 
A számlázó program kidolgozója véleményem szerint akkor jár el helyesen, ha eleve kizárja a programjával készített "próba", "teszt", "előnézet" stb-nek nevezett számlaképek fiktív bizonylatként való felhasználását. Az adólevonási jogra való felhasználást ELEVE ki kell zárni. Ennek egyik eleme lehet a vízjel, vagy a számlaszám hiánya, vagy más, egyértelműen szembetűnő jelölés.
Ha ezek nem voltak a számlán, akkor a számlázó program részéről minimum a gondatlanság megáll (ha a fiktív számla kibocsátásában való egyéb közreműködés nem valósul meg).
Abszurd az a helyzet, amikor egy ellenőrzésre hivatott hatóság, mint a NAV, maga is részt veszt szolgáltatással, számlázó programokkal a piacon. El lehet képzelni, mennyire képes hatóságként a csalás, a költségvetési csalás miatt maga ellen feljelentést tenni. Miközben nem köteles senki magát bűncselekménnyel vádolni.

**Comment by Macskafarka** [comment]
A számla "eltűnése' az tényleg a számlakibocsátó és a számlázó program forgalmazója közötti polgári jog keretébe tartozik, ez irreleváns a számla befogadójának.

**Comment by NTCA-supporter** [comment]
@nemethszilvia  Még egy dolgot meg tudsz nézni. A teszten nem csak a vízjel hiányzik hanem a számlakép tetejéről a online számlázó program logo. Ez az élesen rajta van. Ezt még meg tudjátok nézni.

**Comment by renced42** [comment]
> Jól gondolom, hogy marad az, hogy a kibocsátó nyilatkozata alapján elfogadjuk, hogy az elsőként átadott számla tesztrendszeres volt, és ezért nem az, hanem a második a hiteles bizonylat?

A teszt rendszerben meg lehet nézni, hogy ha lekérdezed benne van-e, ugyan ezt az élesben is meg lehet tenni mind vevői mind eladói oldalon.

**Comment by nemethszilvia** [comment]
> @nemethszilvia Még egy dolgot meg tudsz nézni. A teszten nem csak a vízjel hiányzik hanem a számlakép tetejéről a online számlázó program logo. Ez az élesen rajta van. Ezt még meg tudjátok nézni.

Én teszt rendszert nem használtam, de ebben a videóban a tesztszámla tetején is van online számlázó program logo: https://www.youtube.com/watch?v=5Npu0bCtaqM (pl. 20:13-nál), nyomtatásban az nem jelenik meg?

**Comment by nemethszilvia** [comment]
@Macskafarka Igen, a kérdés pont a miatt érdekes, hogy most melyik számla alapján is lehet gyakorolni a levonási jogot, ezért nyomozunk.

@renced42 Befogadói oldalról lekérdezve a későbbi számla látszik a lekérdezőben, az első nem. A teszt rendszerben nem csak a kibocsátó tud keresni? Ő azt állítja, hogy az első számla ott sem jelenik meg, de ezt befogadói oldalról nem tudjuk ellenőrizni.

**Comment by renced42** [comment]
> A teszt rendszerben nem csak a kibocsátó tud keresni? Ő azt állítja, hogy az első számla ott sem jelenik meg, de ezt befogadói oldalról nem tudjuk ellenőrizni.

A kimenőt és a bejövőt is le lehet kérdezni API-n és felületen is

![image](https://user-images.githubusercontent.com/44041065/101805118-ab0ae480-3b12-11eb-81f9-4461254d94f1.png)

**Comment by nemethszilvia** [comment]
@renced42 Köszi, akkor szólok, hogy regisztrálják a céget a teszt rendszerbe is, hogy le lehessen ellenőrizni az ottani bejövőket.

**Comment by Macskafarka** [comment]
@nemethszilvia Adólevonási jogot papír alapú számla esetén mindazon bizonylat alapján lehet gyakorolni, amely valódi gazdasági eseményről szól, és tartalmilag megfelel az ÁFA törvénynek, valamint a számla befogadótól elvárható gondossággal nem állapítható meg a valótlansága, hamissága. Tehát jelen esetben a legelső bizonylat alapján gyakorolható az adólevonási jog.

**Comment by Macskafarka** [comment]
Az elvárható gondosságba NEM tartozik bele a számlakibocsátó számlázó rendszerébe való betekintés, sem a NAV adatszolgáltatásba való beérkezés vizsgálgatása, sem a számlán szereplő logók esetleges meglétének, vagy hiányának az elemezgetése.

**Comment by nemethszilvia** [comment]
@Macskafarka Az alapvetéssel tökéletesen egyetértek: ha van nálunk egy számla, ami hiteles számlának néz ki, az adott ügylet adatait tartalmazza, és semmi nem utal arra, hogy nem hiteles, akkor az alapján gyakorolható a levonási jog. Viszont ha a partner jelzi, hogy nem hiteles a bizonylat, akkor a befogadótól elvárható gondosságba szerintem már beletartozik, hogy megpróbáljuk leellenőrizni a kibocsátó állítását. Jelen esetben amikor a kibocsátó azt jelezte, hogy az első számla a teszt rendszerből lett kiállítva, ezzel lényegében megkérdőjelezte a dokumentum adóigazgatási azonosításra alkalmasságát, hiszen annak feltétele a 23/2014. NGM rendelet 1. § (3) bekezdése és 13/A. §-a alapján az, hogy az adatszolgáltatást megfelelően teljesítő számlázó programmal legyen előállítva a számla. Tehát attól a ponttól kezdve, hogy a partner jelezte az első számláról, hogy az nem felelt meg ennek a feltételnek, befogadói oldalon szerintem nem úszható meg az utánajárás.

Az viszont egyértelműen problémás, hogy a teszt rendszerből előállhatnak olyan bizonylatok, amiről a befogadó ránézésre nem tudja megállapítani, hogy nem hitelesek.

@renced42 Köszönöm, megvan a teszt rendszerben a számla, így legalább van egyértelmű adat arra, hogy onnan lett kiállítva. Viszont mindenképpen szükséges lenne változtatni rendszerbeállításokon, mivel ezek szerint így egy teszt rendszerből kiállított számla is lehet teljesen olyan, mint egy éles rendszerbeli. Szerintem jó lenne, ha a láblécben "Készült: Online Számlázó TESZT program | onlineszamla-test.nav.gov.hu" jelenne meg, és már a fejlécben is ott lenne, hogy pl. "Teszt rendszerből készült bizonylat, adólevonásra nem jogosít!" Mivel itt hiányzott a "MINTA"-vízjel, viszont ott volt a logó a fejlécben, tényleg simán elment normál számlának az első változat is.

**Comment by renced42** [comment]
Kedves @nemethszilvia 
Igen ez korábban megvolt és ez egy hiba amit korrigálunk, köszönjük a jelzést. Örülök, hogy sikerült lecsekkolni.
Kérlek zárd az Issuet.
