### ISSUE TITLE
INCORRECT_DATE_INVOICE_ISSUE_DATE_LATE

### ISSUE THREAD

**Issue by tnagymelinda** [nav-gov-hu/Online-Invoice#592]
Sziasztok!

Tévesen jövőbeli keltezéssel került kiállításra egy számla, amire INCORRECT_DATE_INVOICE_ISSUE_DATE_LATE warning jött. Mivel nem error, csak warning, az adatszolgáltatás megtörtént. Utánaolvastam a dokumentációban, és a tolerált eltérés 5 naptári nap, és ez azon túl volt.
A számla sztornózva lett ugyanazzal a keltezéssel mint az eredeti (nyilván ugyanazzal a warning üzenettel történt meg az adatszolgáltatás is hozzá). Viszont az utána következő számlák korábbi keltezésűek lettek. Több kérdésem van ezzel kapcsolatban:

Mi a helyes eljárás ebben a helyzetben? Egyrész mennyire oké, hogy egy későbbi, de sztornózott számla után egy korábbi számla jön (a rendszer elfogadta a korábbi keltezésű számlákhoz az adatszolgáltatást hibaüzenet nélkül), másrészt egyáltalán a warning-os számlákkal mi a teendő? Hogyan kellene javítani, hiszen a számlázóban már lezárt számlákról van szó, amik nem módosíthatóak? Sztornó + új számla kiállítása helyesen?

Miért 5 nap a dátum tolerancia, ha számlát elvileg nem szabad előre dátumozni? (az egy napot érteném eltérő timestamp miatt, de 5 nap csúszás engedélyezése kicsit soknak tűnik)

**Comment by NTCA-supporter** [comment]
Szia @tnagymelinda !
Első körben szerintem a https://onlineszamla.nav.gov.hu/api/files/container/download/Online_Szamla_interfesz%20specifikacio_HU_v3.0.pdf doksiban nézd át a 2.4 fejezetet, ami a technikai érvénytelenítésről szól.
Mivel az INVOICE_ISSUE_DATE az adott számlára/módosító okiratra vonatkozik, így azt nem tudod módosítani az eredeti számlánál, ezért van olyan technikai érvénytelenítés indok, hogy ERRATIC_INVOICE_ISSUE_DATE.
Miután technikai érvénytelenítetted (és a felületen jóváhagyta egy elsődleges felhasználó a technikai érvénytlenítést), újból beküldheted, ugyanazzal a számla sorszámmal.
A megerősítést és a többi kérdésre válaszolást rábízom @NTCA-tax -ra.
Köszi

**Comment by bakter80** [comment]
Miért kéne technikailag érvényteleníteni a számlát, ha a hiba nem technikai, hanem az adattartalomban van, ami ráadásul nem megváltoztatható?
A számla kiállításra került.
A hiba nem az adatszolgáltatásban van, hanem a számlában.
Hivatalosan az érvénytelenítés után se módosítható a számla dátuma.

**Comment by pitfla** [comment]
Erre én is várnám a választ! Többször belefutottunk hasonlóba, eddig nem volt jó megoldás rá. Telefonos support azt mondta, hogy hagyjuk úgy, jó az...
Tehát a kérdés kicsit másképp megfogalmazva: helytelen adatokkal kiállított, kinyomtatott, ügyfél által elvitt, warn-os (vagy error-os) számlát, hogy kell beküldeni ahhoz, hogy teljesítsük az adatszolgáltatási kötelezettségünket? 
A technikai érvénytelenítés nem jó, mert továbbra is csak a hibás adatokkal tudjuk beküldeni a számlá(kat), mivel azok adata nyomtatás után már nem módosítható.
Ezt a számlát csak sztornózni lehet és a sztornóval is ugyanazok a bajok lesznek, mint az eredetivel.

**Comment by NTCA-supporter** [comment]
@NTCA-tax kérlek foglalj állást ezügyben :)

**Comment by NTCA-supporter** [comment]
@NTCA-tax  kérlek foglalj állást ezügyben :)

**Comment by NTCA-tax** [comment]
Számlát tilos előre és visszadátumozni. A számla kiállításának dátuma többnyire az a nap, amikor ténylegesen kiállításra kerül. Ugyanakkor az áfa törvényünk nem a kiállítás napját mondja a kötelező adattartalomban, hanem a "számla kibocsátásának keltét". Ráadásul léteznek olyan automata rendszerek, amelyek pontosan tudják, hogy mikor fog megtörténni a kibocsátás és ehhez különböző következmények vagy jogszabályi elvárások kapcsolódnak. Jellemzően ilyenek a közmű szolgáltatók. Amennyiben nagyüzemben történik meg a számlák kiállítása, akkor nem a kiállítás napján történik feltétlenül a kibocsátás, hanem előre ütemezetten. Ilyenkor előfordul, hogy a hétfőn és kedden "legyártott" számlák kibocsátására csütörtökön kerül sor, mivel az adott társaság mindig a hét egyetlen napján bocsát ki számlát. A jogszabályból nem következik, hogy ez hibás gyakorlat lenne.

A fenti bizonytalanság fogalmazódik meg abban, hogy 5 nap a tolerancia. Az elemzésünk során arra a következtetésre jutottunk, hogy a jogszerű előre dátumozás ennél a gyakorlatban nem nagyon szokott több lenni. 

A tolerált idővel kapcsolatban talán a fentiek alapján érthető, miért 5 napban határoztuk meg, és nem 1 napban (az éjfél problémája miatt) az eltérést. 

Node vissza a lényegi kérdéshez. A számlán vannak olyan adatok, amelyek nem korrigálhatók módosító számlával. Ilyen például ha nem volt megfelelő az eladó adata, vagy a vevő adatánál más létező vállalkozás adatát írtuk bele, de ide tartozik a számla sorszáma vagy a kiállítás időpontja. Amennyiben ezekben hibázik egy számlázó program, akkor a hibás számlát érvényteleníteni lehet csak és új számla kibocsátásáról gondoskodni (amennyiben a gazdasági esemény ténylegesen megtörtént). 

A kiállítás dátuma és a számla sorszáma olyan adatok, amelyek egy számlázó programban beégetettnek kellene lennie és nem szabad módosítani azokat. 

A kérdésedben írtad, hogy nem jelent-e problémát, hogy a számla kiállítás időbelisége nem monoton növekszik egy előre dátumozott számla miatt. Mindenképpen probléma, de nem a helyes időpontú számlák, hanem a helytelen időpontú számlák miatt. Azt érdemes megvizsgálni, hogy mi okozhatta a jelenséget. Nem szokványos helyzet, ha a számla kiállításának dátuma manipulálható, vagy módosítható. Persze bármikor lehet valamilyen technikai hiba, de az mindenképp vizsgálandó, hogy mi okozhatta azt.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Inaktivitás miatt zárom az issuet. Ha valami nem lett megválaszolva, kérlek nyissatok újat.

Üdv
