### ISSUE TITLE
[DEV support] Séma validációs hibák - most van privatePersonIndicator tag vagy nincs? (a specben már nincs)

### ISSUE THREAD

**Issue by zonehun** [nav-gov-hu/Online-Invoice#593]
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[x] /manageInvoice

**A kérés verziója / version of the request**
[x] 3.0

**A requestId értéke / requestId value**
```
373PK5KLDLOI7H6C
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
XML contains on line: [26] and column: [30] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerVatStatus}'. One of '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerVatData, "http://schemas.nav.gov.hu/OSA/3.0/data":customerName, "http://schemas.nav.gov.hu/OSA/3.0/data":customerAddress, "http://schemas.nav.gov.hu/OSA/3.0/data":customerBankAccountNumber}' is expected.

*Egyéb tartalom / Additional content*

Kérlek segítsetek mert nem értem, hogy a friss spec szerint már nincs is privatePersonIndicator tag. Ha ez nincs, akkor jön a séma valódációs hiba, hogy ez hiányzik. Ezt most betettem az XML-be, az új customerVatStatus taggel együtt. Erre a fentit kapom.

A customerVatStatus, customerVatData, customerName, customerAddress természetesen mind kitöltve.
A customerBankAccountNumber meg nem kötelező mező.

Hol lehet a probléma?

Köszönöm.

**Comment by EnokhSys** [comment]
@zonehun nincs már "privatePersonIndicator", helyette van a "customerVatStatus". Hibaüzenetet pedig azért kapsz, mert még nem állították át a tesztrendszert erre a változásra; ez állítólag hétvégéig megtörténik.

**Comment by zonehun** [comment]
@EnokhSys köszönöm! A hétvégéig milyen InvoiceData XML változattal lehet tesztelni? Még tegyem bele a pPI-t és vegyem ki a customerVatStatus-t?

**Comment by zonehun** [comment]
A pPI-t választva és a customerVatStatust-t kivéve minden rendben jelenleg.

Kár, hogy ezt az információt nem a kiadott changelog-ban jelenítették meg - "FIGYELEM! A customerVatStatus tag élesítése 2020.12.12-i hétvégén történik meg." vagy valami hasonló. Spórolhattam volna kb. 2 órát magamnak tegnap este.

**Comment by EnokhSys** [comment]
@zonehun Szívesen!

**Comment by NTCA-supporter** [comment]
Úgy látom ez megválaszolásra került, zárom.
Üdv
