### ISSUE TITLE
AdditionalDataType DataValue problema

### ISSUE THREAD

**Issue by robozb** [nav-gov-hu/Online-Invoice#596]
Kedves Közösség!

Itt vajon mi lehet a hiba? Értékátadás előtt trim()-elem az értéket :(
https://www.dropbox.com/s/epqt5h19lwkrqte/hiba.JPG?dl=0

Köszönöm a segítséget!

Üdv: Béla

**Comment by robozb** [comment]
Lehet, hogy sortörés van benne

**Comment by EnokhSys** [comment]
[[FEATURE] Számla megjegyzés átadása sortörés és tabulátor vezérlőkarakterekkel. #484](https://github.com/nav-gov-hu/Online-Invoice/issues/484)

**Comment by robozb** [comment]
Igen, a sortörés volt a probléma!
