### ISSUE TITLE
Jelentési kötelezettség Q&A

### ISSUE THREAD

**Issue by clapygeza** [nav-gov-hu/Online-Invoice#598]
Sziasztok!
Egy érdekes eset esett be hozzánk számlázó program vásárlási céllal:
Egyéni vállalkozó (adószámmal természetesen) örökölt egy lakást (mint magánszemély természetesen). A lakást kiadta egy Kft.-nek. A Kft azt mondta, hogy csak és kizárólag számla ellenében hajlandóak fizetni. A bérleti díjakat szeretné számlázni a programmal automatikusan, minden hónap elején. Az Áfa. Tv. 86.§ l.) szerint nem köteles számlát adni, de ha mégis kérik akkor kell jelenteni? Ha igen, akkor milyen adószám alatt? Két adószáma nem lehet, tehát akkor nyilván köteles az ingatlan bérbeadást tev. körként felvenni?
Köszi a választ előre is.

**Comment by fenyvessy** [comment]
Ha a kiadásról állít ki számlát, akkor nem EV, hanem adószámos magánszemélyként teszi, és akkor azt NEM kell beküldenie, de pontosan ugyan azt az adószámot kell ráírnia, mint ami EV-ként használ. Amikor EV-ként állít ki számlát, akkor az EV nyilvántartási számát is fel kell tüntetni a szállítónál, viszont amikor adószámos magánszemélyként, akkor nem írhatja oda. Ez gyakorlatban azt jelenti, hogy használ egy számlatömböt (programot) EV-ként, amiből mennek a tevékenységéhez köthető beküldések, és használ egy másik számlatömböt (programot) adószámos magánszemélyként, ahol meg nem küldi be a bérleti díjról számviteli bizonylat helyett kiállított TAM számlát.

**Comment by nbeeps2** [comment]
fenyvessy: "NEM kell beküldenie": és ha beküldi, akkor mi fog történni? megbüntetik, mert túlteljesítette az adatszolgáltatást? A legtöbb számlázó programban nem tudsz magyar adószámmal számlát kiállítani, ha nem vagy összekötve a NAV-val. Így marad az a lehetőség, hogy a felhasználó az E.V-re megvett programmal egy másik számlatömbben (amin nincs rajta a nyilvántartási száma és az egyéni vállalkozó titulus) számláz és akkor bemennek ezek a számlák is a NAV-hoz... Másik lehetőség, hogy nem állít ki számlát csak számviteli bizonylatot, de e kapcsán meg általában megy a hiszti, hogy neki (a vevő nyomására) számla kell.

**Comment by NTCA-tax** [comment]
Amennyiben tárgyi mentes az ingatlan bérbeadás, akkor nem áfa hatálya alá tartozó számlát állít ki, hanem számviteli bizonylatot. Ezt a számviteli bizonylatot elnevezheti akár számlának is, de ettől nem lesz az áfa törvény szerinti számla. Ennek következménye, hogy erről a bizonylatról nem kell adatot szolgáltatnia. Amennyiben mégis beküldi ennek a bizonylatnak az adatait, attól még nem fogjuk kommandósokkal rátörni az ajtót :) 

Megoldás jelenthet, hogy elkülönült tartományban állítja ki a számláit és a számviteli bizonylatait, és az utóbbinál nincs adatszolgáltatás. Adószáma viszont csak egy van, tehát nem itt kell elválasztani a két esetet, hanem bizonylati szinten.

**Comment by clapygeza** [comment]
Ok, köszi a választ és a hozzászólásokat is ... Zárom.
