### ISSUE TITLE
[FEATURE] Kézi számla adatszolgáltatásnál a számlaszám ellenőrzése.

### ISSUE THREAD

**Issue by celeburdi** [nav-gov-hu/Online-Invoice#60]
Egyik partnerünk leporellós számlát állít ki.
A számlaszám CO8LA-val kezdődik.
Ránézésre nem lehet megállapítani, hogy a C után 0 'szám' vagy O 'betű' van.
A NAV kiadott számlasorszámok adatbázisa szerint a betű (O) a helyes.
Partnerünk általában a kézi adatszolgáltatáskor a nullát írja be.
(néha azért ír O betűt is). Ellenőrizve a bejövő számlák lekérdezésével  
Mi a 19A65-M-en a helyes O betűvel jelentjük.
Nyilván ez egy hibás állapothoz vezet.

A kézi adatszolgáltatásnál ellenőrizni lehetne a számlaszám helyességét.
(pl. a számlasorszámok kiadásának algoritmusa szerint, vagy a NAV kiadott számlasorszámok   
adatbázisa alapján)

**Comment by NTCA-developer** [comment]
Szia @celeburdi!

Köszönjük a felvetést, megnézzük milyen lehetőségeink vannak és visszajelzek.

**Comment by NTCA-developer** [comment]
Szia @celeburdi 

Ebben a témában jelenleg nincs előrelépés, még nyitva hagyom.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Csak egy visszajelzés: ez a feature továbbra is tervben van, csak nagyon alacsony prioritással.
Jelzünk, ha megtörtént a fejlesztés.

Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
A fejlesztés megtörtént, már nem lehet úgy elmenteni frontendes rögzítésnél, hogy létezik az a számla sorszám.
Köszönjük az építő jellegű ötletet és persze a türelmet is.
Zárom az issuet, kérdés/észrevétel esetén kérlek nyissátok újra.
Üdv
