### ISSUE TITLE
[DEV support]  SCHEMA_VIOLATION : Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerVatStatus}'

### ISSUE THREAD

**Issue by marcipunk** [nav-gov-hu/Online-Invoice#602]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**

[x] /manageInvoice

**A kérés verziója / version of the request**
[x] 3.0

**A requestId értéke / requestId value**
```
374RT4LJXW3TNUKA
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Implementáltuk a ```<customerVatStatus>``` taget és töltjük.
A teszt api-ra beküldve viszont hibaüzenetet kapunk:
SCHEMA_VIOLATION    XML contains on line: [1] and column: [848] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerVatStatus}'. One of '{"http://schemas.nav.gov.hu/OSA/3.0/data":privatePersonIndicator}' is expected.]

Vonatkozó rész a beküldött XML-ből:
```
<customerInfo>
					<customerVatStatus>DOMESTIC</customerVatStatus>
					<customerVatData>
						<customerTaxNumber>
							<base:taxpayerId>11914055</base:taxpayerId>
							<base:vatCode>2</base:vatCode>
							<base:countyCode>42</base:countyCode>
						</customerTaxNumber>
					</customerVatData>
					<customerName>Partner1 telephelyekkel NÉV A BIZONYLATON</customerName>
					<customerAddress>
						<base:simpleAddress>
							<base:countryCode>HU</base:countryCode>
							<base:postalCode>1024</base:postalCode>
							<base:city>Budapest</base:city>
							<base:additionalAddressDetail>Központ 48 A 2. em 34.</base:additionalAddressDetail>
						</base:simpleAddress>
					</customerAddress>
</customerInfo>
```

**Comment by tkelemen73** [comment]
A tesztrendszer még mindig a régi verzió, vagyis ott még privatPersonIndiator a valid... Azt vártam, hogy a mai karbantartással megugorják az új verziót, hát nem...

**Comment by marcipunk** [comment]
Köszi, nekem is ez a sejtésem, de azért ez több mint bosszantó, hogy alig van a határidőig hátra, megváltoztatják a sémát, és még a saját oldalukon se tudják követni.

**Comment by Kulcs** [comment]
Remélem mihamarabb kijavítják, mert én is belefutottam...

**Comment by nbeeps2** [comment]
Én is jeleztem már a hét elején, akkor a hét második felére ígérték a frissítést. Még tart a hét :D

**Comment by NTCA-supporter** [comment]
Sziasztok! A mai telepítéssel került ki a végleges 3.0-as XSD-t támogató release. Ha a hiba elhárult akkor kérlek zárjátok le az issuet. Köszi
