### ISSUE TITLE
[DOC] régi 3.0 dokumentáció még mindig elérhető

### ISSUE THREAD

**Issue by csandazoltan** [nav-gov-hu/Online-Invoice#603]
Kedves Support!

Egy kérés Önökhöz és egy figyelmeztetés másoknak!
A 2020-12-01-es XSD változás előtti dokumentáció még mindig elérhető a régi linkjén, nem felülírva lett, hanem átírva/"elírva", teszten és élesen egyaránt.
A linkek dokumentáció oldalon HELYESEN az új verzióra mutatnak, viszont kérném, a régi már elavult dokumentáció eltávolítását.

A többi fejlesztő aki esetleg úgy csinálta mint én, hogy a pdf-nek a linkjét mentette le, hogy "majd esetleg" mindig a legfrissebb dokumentációra fog az a link mutatni, az rosszl járhat, mert az a link az elavult dokumentációra mutat

Régi teszt:
https://onlineszamla-test.nav.gov.hu/api/files/container/download/Online%20Szamla_interfesz%20specifik%C3%A1ci%C3%B3_HU_v3.0.pdf

Új teszt:
https://onlineszamla-test.nav.gov.hu/api/files/container/download/Online_Szamla_interfesz%20specifikacio_HU_v3.0.pdf

Régi éles: 
https://onlineszamla.nav.gov.hu/api/files/container/download/Online%20Szamla_interfesz%20specifik%C3%A1ci%C3%B3_HU_v3.0.pdf

Új éles:
https://onlineszamla.nav.gov.hu/api/files/container/download/Online_Szamla_interfesz%20specifikacio_HU_v3.0.pdf

Az eltérések a fájlnevekben ékezetek és az url encode-olt alulvonások miatt van

**Comment by csandazoltan** [comment]
Az invalid label-t nem én adtam hozzá :)

**Comment by NTCA-supporter** [comment]
Rendben, jelzek ha megcsináltuk.
Üdv

**Comment by NTCA-supporter** [comment]
Javítva.
Köszönöm a jelzést.
Üdv
