### ISSUE TITLE
[Q&A] Közmű elszámoló számla példa 1

### ISSUE THREAD

**Issue by KozmuvesKelemen** [nav-gov-hu/Online-Invoice#605]
A 2.8 Közmű elszámoló számlájának adatszolgáltatása fejezetben ez a példa szerepel:
Elszámoló számla adatai: 
•	Utolsó havi alapdíj: 100 
•	11. havi részszámla 200 
•	10. havi részszámla 200 
•	Elszámolt összeg leolvasást követően -500 (mely az utolsó időszaki alapdíjnak, és a 10. és 11. havi részszámlának a korrekcióját jelenti). 

Ennek az adatszolgáltatása a következően néz ki:
•	Utolsó havi alapdíj (100) adatszolgáltatása: számlasorszám hivatkozás (originalInvoiceNumber) az elszámoló számla sorszáma, közmű elszámoló számla jelölése true (utilitySettlementIndicator=true). 
•	Utolsó havi alapdíj csökkentésének adatszolgáltatása az elszámolás miatt (-100): számlasorszám hivatkozás (originalInvoiceNumber) az elszámoló számla sorszáma, közmű elszámoló számla jelölése true (utilitySettlementIndicator=true) 
•	11. havi részszámla módosítása (-200): számlasorszám hivatkozás (originalInvoiceNumber) a 11. havi részszámla sorszáma, közmű elszámoló számla jelölése false (utilitySettlementIndicator=false) 
•	10. havi részszámla módosítása (-200): számlasorszám hivatkozás (originalInvoiceNumber) a 10. havi részszámla sorszáma, közmű elszámoló számla jelölése false (utilitySettlementIndicator=false) 

Ezt a példát nem is tudom értelmezni. Egyrészt kavarodnak a fogalmak. „Utolsó havi alapdíj: 100”-at írnak, de -500 fogyasztásnál visszavonják, tehát az alapdíj és a fogyasztás arányos díj keveredik.
Ráadásul 4 pontban sorolják fel az adatszolgáltatás lépéseit, amiből nekem úgy tűnik, hogy az elszámoló számla adatát két darabban kérnék:
•	Utolsó havi alapdíj (100) adatszolgáltatása: számlasorszám hivatkozás (originalInvoiceNumber) az elszámoló számla sorszáma, közmű elszámoló számla jelölése true (utilitySettlementIndicator=true). 
•	Utolsó havi alapdíj csökkentésének adatszolgáltatása az elszámolás miatt (-100): számlasorszám hivatkozás (originalInvoiceNumber) az elszámoló számla sorszáma, közmű elszámoló számla jelölése true (utilitySettlementIndicator=true) 

De felette ebben a részben ez szerepel:
Az adatszolgáltatáskor ezeket a számlákat MODIFY operációval, batchInvoice számlaként kell beküldeni a következő módon: 
•	adott időszaki teljesítésről (például alapdíj) az adatszolgáltatást a következők szerint kell teljesíteni: 
o	az originalInvoiceNumber az aktuális számla sorszáma, 
o	a modifyWithoutMaster értéke true, 
o	a utilitySettlementIndicator értéke true 
o	a modificationIndex értéke’1’. 
Itt úgy tűnik, hogy egy darabban kell beküldeni az elszámoló számlát, mert a modificationIndex értéke’1’. Mivel egy batchInvoice állományban nem lehet ugyanannak a számlának ugyanazon módosítását többször szerepeltetni a specifikáció 153.  oldalán szereplő alábbi rész szerint, ezért feltételezem a példa a rossz:
•	„Kötegelt módosításról történő adatszolgáltatáskor nem lehet ugyanannak a számlának ugyanazon módosítását többször szerepeltetni a kérésben. Másként fogalmazva, a teljes XML-ben a módosítások által hivatkozott számla számának (invoiceReference) és a módosítás sorrendiségét leíró elemnek (modificationIndex) egyedinek kell lennie. A fenti szabálynak nem megfelelő kérések feldolgozását a rendszer elutasítja és ABORTED státuszba teszi.”

A feltételezésemet tovább erősíti, hogy a példának ez a része amúgy sem helyes:
•	Utolsó havi alapdíj csökkentésének adatszolgáltatása az elszámolás miatt (-100): számlasorszám hivatkozás (originalInvoiceNumber) az elszámoló számla sorszáma, közmű elszámoló számla jelölése true (utilitySettlementIndicator=true) 

A 12. havi elszámoló számlában a 12. hónapra elszámolt alapdíjat amúgy sem kellene visszavonni, hiszen a 11 részszámlában 11 havi alapdíjat fizetett meg az ügyfél, tehát a 12. havi alapdíj elszámolása semmilyen módon nem befolyásolja a korábban a részszámlákban kiszámlázott alapdíjakat. Azt az ügyfélnek meg kell fizetnie.

Nézzünk egy teljesen egyszerű valódi példát (egy teljesen sima alap esetet, mert még ennek a beküldése sem egyértelmű, addig kár is azon elmélkedni, hogy a bonyolultabb esetekben mit kellene tennünk):
•	Van 11 részszámlánk, részszámlánként az alábbi tételekkel:
o	1 havi alapdíj 60 Ft
o	10 m3 fogyasztás m3-enként 100 Ft = 1.000 Ft
o	ÁFA összesítő:
	Nettó: 1.060 Ft
	ÁFA (27%-kal): 286 Ft
	Bruttó: 1.346 Ft
•	Van egy elszámoló számlánk az alábbi tételekkel, mert 15 m3-rel kevesebbet olvastunk le, mint amit részszámláztunk:
o	12 havi alapdíj 720 Ft
o	11 havi alapdíj levonás, amit már a részszámlákban elszámoltunk -660 Ft
o	95 m3 éves fogyasztás 9.500 Ft
o	110 m3 fogyasztás levonás, amit már a részszámlákban elszámoltunk -11.000 Ft
o	ÁFA összesítő:
	Nettó: -1.440 Ft
	ÁFA (27%-kal): -389 Ft
	Bruttó: -1.829 Ft

Ha jól értelmezem, akkor a NAV véleménye szerint a fenti példa esetén a fogyasztás alapú díjat kellene csökkentenünk az elszámoló számlában annyival, hogy pontosan megegyezzen a részszámlákban kiszámlázottal, az elszámoló számlából kihagyott összegeket pedig, mint részszámla helyesbítéseket kellene beküldenünk. Tehát így néz ne ki a batchInvoice:
•	1. bizonylata az elszámoló számla elcsalt értékekkel, így:
o	12 havi alapdíj 720 Ft
o	11 havi alapdíj levonás, amit már a részszámlákban elszámoltunk -660 Ft
o	95 m3 éves fogyasztás 9.500 Ft
o	110 m3 fogyasztás levonás, amit már a részszámlákban elszámoltunk -11.000 Ft
o	95 m3 fogyasztás levonás, amit már a részszámlákban elszámoltunk (nem a 110, mert a 15 különbözetet a részszámlák helyesbítéseként tüntetjük fel) -9.500 Ft
o	ÁFA összesítő:
	Nettó: 60 Ft
	ÁFA (27%-kal): 16 Ft
	Bruttó: 76 Ft
•	2. bizonylat a 11. részszámla helyesbítése (úgy mintha tényleg helyesbítenénk, tehát az eredeti sorok mínusszal az újak plusszal):
o	1 havi alapdíj visszavonás -60 Ft
o	10 m3 fogyasztás visszavonás = -1.000 Ft
o	1 havi alapdíj elszámolás, mert ennek maradnia kell 60 Ft 
o	ÁFA összesítő:
	Nettó: -1.000 Ft
	ÁFA (27%-kal): -270 Ft
	Bruttó: -1.270 Ft
•	3. bizonylat a 10. részszámla helyesbítése (úgy mintha tényleg helyesbítenénk, tehát az eredeti sorok mínusszal az újak plusszal):
o	1 havi alapdíj visszavonás -60 Ft
o	10 m3 fogyasztás visszavonás = -1.000 Ft
o	1 havi alapdíj elszámolás, mert ennek maradnia kell 60 Ft 
o	5 m3 fogyasztás elszámolás, mert itt már nem a teljes mennyiséget kell visszavonni, hiszen 15 m3-nyi fogyasztással kell csökkentenünk, a 11. részszámlában pedig már 10 m3-t visszavontunk 500 Ft
o	ÁFA összesítő:
	Nettó: -500 Ft
	ÁFA (27%-kal): -135 Ft
	Bruttó: -635 Ft

Ezt kellene tennünk?
Ha igen, akkor a fenti példa esetén a közműcég számlázó rendszerében ez lesz könyvelve:
•	10. részszámla Bruttó: 1.346 Ft
•	11. részszámla Bruttó: 1.346 Ft
•	12. havi elszámoló számla Bruttó: -1.829 Ft
Eközben a NAV rendszerében, ha részszámla helyesbítésként küldjük be az elszámoló számla egy részét:
•	10. részszámla Bruttó: 1.346 Ft
•	11. részszámla Bruttó: 1.346 Ft
•	12. havi elszámoló számla Bruttó: -1.829 Ft
•	11. részszámla helyesbítése Bruttó: -1.270 Ft
•	10. részszámla helyesbítése Bruttó: -635 Ft
 
Ha eddig nem értelmeztem semmit tévesen, akkor jön a következő kérdés, hogy hogyan kellene az elszámoló számlán megjelenítenünk a tétel adatokat, az ÁFA összesítőt és a részszámlák „helyesbített” tételsorait a 2013. évi CLXXXVIII. törvény az egységes közszolgáltatói számlaképről törvényben meghatározott villamos energia, földgáz, távhő és víziközmű számlák számlaképein?

Hangsúlyozom, hogy Magyarország legnagyobb közmű vállalatai az SAP vállalatirányítási rendszerének IS-U közmű modulját használják a számlák kiállítására. Ez a modul nem képes egyszerre elszámoló számlát és helyesbítő számlát kiállítani. Képes elszámoló számlában kibocsátott részszámlákat jóváírni és képes külön számlát helyesbíteni, de a kettőt egyszerre nem. Tehát, ha össze is hazudjuk az online számla beküldésben a fent leírt módon az adatokat, akkor a rendszerben még nem ez lesz pl.: egy részszámlát megtekintve semmi sem utal arra, hogy azt „helyesbítettük”.

És itt el is érkeztünk a NAV másik csodafegyveréhez a számlázó programoktól elvárt NAV adóhatósági ellenőrző adatszolgáltatás funkcióhoz. Hozzáteszem ezt be is szánthatnánk, ha már online számlázunk.
Tegyük fel kijön a NAV ellenőrizni is letölti a rendszerből a fenti példa számláit. Mivel a rendszerben az eredetileg kibocsátott számlaadatok érhetőek el, nem az online számla adatszolgáltatásban összehazudott adatok, ezért a program az online számla beküldésben „helyesbített” részszámlákat úgy fogja letölteni, ahogy helyesbítés nélkül eredetileg ki lettek bocsájtva és egyébként az ügyfélnél lévő számlaképen is szerepelnek az adatok és az elszámoló számlát is negatív elszámoló számlaként fogja letölteni, pedig az online számla adatszolgáltatásban ez már pozitív volt.

A kérdés az lenne, hogy akár a szolgáltató, akár a számlázó rendszer fejlesztője, vagy bárki más büntethető, bírságolható, bármilyen módon felelősségre vonható, hogy a NAV felé történt két adatszolgáltatás során eltérő adatokat közölt?

**Comment by KozmuvesKelemen** [comment]
A fenti példánál, amikor az elcsalt elszámoló számla adatait írtam le hibásan került be ez a sor:
o 110 m3 fogyasztás levonás, amit már a részszámlákban elszámoltunk -11.000 Ft

Word-ből másoltam be és eltüntette a szöveg áthúzását. Pusztán emiatt újra bemásolom ide csak a példát és most már rendesen megformáztam, hogy így átláthatóbb legyen:

Nézzünk egy teljesen egyszerű valódi példát (egy teljesen sima alap esetet, mert még ennek a beküldése sem egyértelmű, addig kár is azon elmélkedni, hogy a bonyolultabb esetekben mit kellene tennünk):
* Van 11 részszámlánk, részszámlánként az alábbi tételekkel:
  * 1 havi alapdíj 60 Ft
  * 10 m3 fogyasztás m3-enként 100 Ft = 1.000 Ft
  * ÁFA összesítő:
    * Nettó: 1.060 Ft
    * ÁFA (27%-kal): 286 Ft
    * Bruttó: 1.346 Ft
* Van egy elszámoló számlánk az alábbi tételekkel, mert 15 m3-rel kevesebbet olvastunk le, mint amit részszámláztunk:
  * 12 havi alapdíj 720 Ft
  * 11 havi alapdíj levonás, amit már a részszámlákban elszámoltunk -660 Ft
  * 95 m3 éves fogyasztás 9.500 Ft
  * 110 m3 fogyasztás levonás, amit már a részszámlákban elszámoltunk -11.000 Ft
  * ÁFA összesítő:
    * Nettó: -1.440 Ft
    * ÁFA (27%-kal): -389 Ft
    * Bruttó: -1.829 Ft

Ha jól értelmezem, akkor a NAV véleménye szerint a fenti példa esetén a fogyasztás alapú díjat kellene csökkentenünk az elszámoló számlában annyival, hogy pontosan megegyezzen a részszámlákban kiszámlázottal, az elszámoló számlából kihagyott összegeket pedig, mint részszámla helyesbítéseket kellene beküldenünk. Tehát így néz ne ki a batchInvoice:
* Az 1. bizonylata az elszámoló számla elcsalt értékekkel, így:
    * 12 havi alapdíj 720 Ft
    * 11 havi alapdíj levonás, amit már a részszámlákban elszámoltunk -660 Ft
    * 95 m3 éves fogyasztás 9.500 Ft
    * ~~110 m3 fogyasztás levonás, amit már a részszámlákban elszámoltunk -11.000 Ft~~
    * 95 m3 fogyasztás levonás, amit már a részszámlákban elszámoltunk (nem a 110, mert a 15 különbözetet a részszámlák helyesbítéseként tüntetjük fel) -9.500 Ft
    * ÁFA összesítő:
      * Nettó: 60 Ft
      * ÁFA (27%-kal): 16 Ft
      * Bruttó: 76 Ft
* A 2. bizonylat a 11. részszámla helyesbítése (úgy mintha tényleg helyesbítenénk, tehát az eredeti sorok mínusszal az újak plusszal):
    * 1 havi alapdíj visszavonás -60 Ft
    * 10 m3 fogyasztás visszavonás = -1.000 Ft
    * 1 havi alapdíj elszámolás, mert ennek maradnia kell 60 Ft
    * ÁFA összesítő:
      * Nettó: -1.000 Ft
      * ÁFA (27%-kal): -270 Ft
      * Bruttó: -1.270 Ft
* A 3. bizonylat a 10. részszámla helyesbítése (úgy mintha tényleg helyesbítenénk, tehát az eredeti sorok mínusszal az újak plusszal):
    * 1 havi alapdíj visszavonás -60 Ft
    * 10 m3 fogyasztás visszavonás = -1.000 Ft
    * 1 havi alapdíj elszámolás, mert ennek maradnia kell 60 Ft
    * 5 m3 fogyasztás elszámolás, mert itt már nem a teljes mennyiséget kell visszavonni, hiszen 15 m3-nyi fogyasztással kell csökkentenünk, a 11. részszámlában pedig már 10 m3-t visszavontunk 500 Ft
    * ÁFA összesítő:
      * Nettó: -500 Ft
      * ÁFA (27%-kal): -135 Ft
      * Bruttó: -635 Ft

Ezt kellene tennünk?

**Comment by NTCA-tax** [comment]
Próbálok minden felvetésedre reagálni.

"Mivel egy batchInvoice állományban nem lehet ugyanannak a számlának ugyanazon módosítását többször szerepeltetni a specifikáció 153. oldalán szereplő alábbi rész szerint, " (...)
Éppen ezt a problémát oldja meg a utilitySettlementIndicator, amennyiben ennek értéke true, akkor nincs ilyen tiltás.

"A 12. havi elszámoló számlában a 12. hónapra elszámolt alapdíjat amúgy sem kellene visszavonni, hiszen a 11 részszámlában 11 havi alapdíjat fizetett meg az ügyfél, tehát a 12. havi alapdíj elszámolása semmilyen módon nem befolyásolja a korábban a részszámlákban kiszámlázott alapdíjakat. Azt az ügyfélnek meg kell fizetnie."
Amennyiben egy közmű szolgáltató díja alapdíjból és fogyasztás arányos díjból áll, akkor mind a 12 hónapra ki kell számláznia az alapdíjat. Az áfa törvény szempontjából teljesen mindegy, hogy a folyamatosan nyújtott szolgáltatásnál hogy épül fel a szolgáltatási díj, az összegek korrekcióját kell elvégezni. Tehát a példában nem az alapdíj elengedése történik, hanem a -500 forint elszámolása. 

A példádban az "Az 1. bizonylata az elszámoló számla elcsalt értékekkel" részt egy kicsit túlbonyolítod. Az áfa szempontjából történt egy teljesítés nettó 60 forint összegen. Ezt megjelenik önálló tételsoron az adatszolgáltatásban. Majd a következő tételsorokon elkezdheted csökkenteni az összegeket. Ebben a pillanatban így állsz:
- Utolsó időszaki számla összege nettó 60
- 11. időszak összege nettó 1060
- 10.  időszak összege nettó 1060
- ...

Amennyiben szeretnéd, akkor bonyolíthatod azzal, hogy az alapdíjat nem engeded csökkenteni nullára. Ez is egy megoldás, áfa szempontjából egyébként nincs relevanciája. Tehát megteheted azt is, hogy az alapdíjat mindegyik hónapban meghagyod és csak a feletti összeget csökkented le nullára, de akár a teljes összeget is csökkentheted nullára, de akár arányosan a teljes elszámolási időszakra is eloszthatod. Ugyanakkor bármelyiket is választod, annak a számlaképen szerepelnie kell. Ne felejtsed el, hogy az adóalany vevő ezen adatok alapján tudja összeállítani a saját belföldi összesítőjét, és a 65-ös bevallás mellékletébe azt kell beleírnia, amit a közmű szolgáltató a számláján levezet.

**Comment by KozmuvesKelemen** [comment]
Azért vagyok kénytelen "túlbonyolítani", mert a számlán a tételsoroknál feltüntetem díjelemenként, hogy mennyi volt a részszámlákban és az elszámoló számlában. Még ha az ÁFA törvénynek meg is felelne nem csökkentgethetem össze-vissza a díjelemeket, mert annak aztán végképp semmi köze nem lenne a számlaképhez.

Azt te is írod, hogy "az adóalany vevő ezen adatok alapján tudja összeállítani a saját belföldi összesítőjét, és a 65-ös bevallás mellékletébe azt kell beleírnia, amit a közmű szolgáltató a számláján levezet." Ha már itt tartunk erre a kérdésre nem válaszoltatok:
"Ha eddig nem értelmeztem semmit tévesen, akkor jön a következő kérdés, hogy hogyan kellene az elszámoló számlán megjelenítenünk a tétel adatokat, az ÁFA összesítőt és a részszámlák „helyesbített” tételsorait a 2013. évi CLXXXVIII. törvény az egységes közszolgáltatói számlaképről törvényben meghatározott villamos energia, földgáz, távhő és víziközmű számlák számlaképein?"
A fenti törvény által meghatározott számlaképek fejrészében helyesbítő, vagy stornó számlák esetén egy eredeti bizonylatszám megjelenítésére van lehetőség. Nincs hely 11 részszámla sorszámának a felsorolására. Melyik számlát kell több számla módosítása esetén eredeti számlaként feltüntetni a számlaképeken? A számlaképen hol és hogyan tudom megjeleníteni a NAV online számla adatszolgáltatásnak megfelelő levezetést, hogy az adóalany vevő is össze tudja állítani az összesítőjét?

Ezt a kérdést elfelejtettétek megválaszolni:
"És itt el is érkeztünk a NAV másik csodafegyveréhez a számlázó programoktól elvárt NAV adóhatósági ellenőrző adatszolgáltatás funkcióhoz. Hozzáteszem ezt be is szánthatnánk, ha már online számlázunk.
Tegyük fel kijön a NAV ellenőrizni is letölti a rendszerből a fenti példa számláit. Mivel a rendszerben az eredetileg kibocsátott számlaadatok érhetőek el, nem az online számla adatszolgáltatásban összehazudott adatok, ezért a program az online számla beküldésben „helyesbített” részszámlákat úgy fogja letölteni, ahogy helyesbítés nélkül eredetileg ki lettek bocsájtva és egyébként az ügyfélnél lévő számlaképen is szerepelnek az adatok és az elszámoló számlát is negatív elszámoló számlaként fogja letölteni, pedig az online számla adatszolgáltatásban ez már pozitív volt.

A kérdés az lenne, hogy akár a szolgáltató, akár a számlázó rendszer fejlesztője, vagy bárki más büntethető, bírságolható, bármilyen módon felelősségre vonható, hogy a NAV felé történt két adatszolgáltatás során eltérő adatokat közölt?"

**Comment by NTCA-tax** [comment]
"A fenti törvény által meghatározott számlaképek fejrészében helyesbítő, vagy stornó számlák esetén egy eredeti bizonylatszám megjelenítésére van lehetőség. Nincs hely 11 részszámla sorszámának a felsorolására. Melyik számlát kell több számla módosítása esetén eredeti számlaként feltüntetni a számlaképeken? A számlaképen hol és hogyan tudom megjeleníteni a NAV online számla adatszolgáltatásnak megfelelő levezetést, hogy az adóalany vevő is össze tudja állítani az összesítőjét?"

A számlakép törvény lehetőséget ad további információk megjelenítésére is. Amit az áfa törvény előír olyan követelményként, ami nem szokott rajta lenni egy közmű szolgáltatós elszámoló számlán, azt lényegében egy táblázatban össze lehet foglalni. A számlakép ilyen jellegű bővítését nem tiltja a számlakép törvény, az áfa törvény alapján viszont épp törvényi előírás.

Az adatexporttal kapcsolatban amit fontos tudnod, hogy ott nem csupán egy gépi elemzés van, ott van mögötte az adóellenőr is. Tehát ha bármilyen eltérés lenne az adatexport adattartalma és az adatszolgáltatás adattartalma között, azt az adóellenőrnek kell értékelnie. Persze alapvetően nem lenne jó, ha teljesen más adatok vannak az adatszolgáltatásban és az adatexportban. Végösszeg szempontjából ugyan annak kell kijönnie, független attól, hogy a számlakép törvényi szerinti levezetést, vagy az áfa törvény szerinti levezetést is nézzük.

Ezzel kapcsolatban amit nem értek, hogy egy negatív elszámoló számla hogyan lesz az adatszolgáltatásban pozitív? Ezt meg tudnád még világítani.

**Comment by KozmuvesKelemen** [comment]
"Ezzel kapcsolatban amit nem értek, hogy egy negatív elszámoló számla hogyan lesz az adatszolgáltatásban pozitív? Ezt meg tudnád még világítani."

Az online számla adatszolgáltatásban az elszámoló számlát úgy küldöm be, hogy csak 1 havi alapdíj 60 Ft van benne, mert a negatív fogyasztás alapú díjat, mint részszámla helyesbítést küldtem be.
Az adóhatósági ellenőrző adatszolgáltatás letöltésekor pedig a valódi számlát töltöm le, ami valójában negatív összegű.

**Comment by NTCA-tax** [comment]
De ettől még egy elszámoló számlád lesz, amiről van egy adatszolgáltatásod. Az elszámoló számla adatszolgáltatását nem bontod szét és nem is bonthatod szét két számlára, mivel nem is létezik két számla és két számlasorszám. Megteheted, hogy csak a részszámlákat módosítod az alapdíj összegéig, akkor az elszámoló számlád adatszolgáltatásának tételsorai a következők lesznek ha az elszámoló számla végösszege -1500 Ft:

12. havi alapdíj 60 Ft (hivatkozott számlasorszám ELSZ1, ez azért kell, mert MODIFY az egész adatszolgáltatás, utilitySettlementIndicatort pedig true-ra állítod, hogy warning nélkül feldolgozzuk)
11. havi részszámla módosítása -1000 Ft (hivatkozott számlasorszám RSZ1)
10. havi részszámla módosítása -560 Ft (hivatkozott számlasorszám RSZ2)

Tehát ha a tételsorokat összeadom, akkor itt is -1500 forint lesz, nem lesz a végösszeg pozitív. Amennyiben jól értelemezem az általad elmondottakat, akkor annyi a különbség, hogy a számlakép törvény szerinti számlaképen a 60 Ft, -1000 Ft, -560 Ft így nem jelenik meg, hanem csupán egy áfa összesítő mellékletben. De függetlenül attól, hogyan jutunk el a végeredményig, a végeredmény ugyan az lesz, csak a tételsorok térnek el.

**Comment by KozmuvesKelemen** [comment]
Ha a teljes batchInvoice állományt egyben nézitek, akkor a benne lévő Invoice állományok (elszámoló számla és részszámla helyesbítők) összegeként valóban kijön az eredeti számla.

Ebben az issue-ban lévő kérdést szerintem zárhatjuk, részemről ehhez a sima esethez nincs már kérdés.
