### ISSUE TITLE
3.0 QueryInvoiceDigestResponse XML namespace

### ISSUE THREAD

**Issue by ntamas91** [nav-gov-hu/Online-Invoice#606]
Sziasztok!

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[x] /queryInvoiceDigest
[x] /queryInvoiceData

**A kérés verziója / version of the request**
[x] 3.0

**A requestId értéke / requestId value**
[x] T0131160767779628626132

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
A különböző (QueryInvoiceDigestRequest és QueryInvoiceDataRequest)  response-ból visszakapott adatokban találtam egy furcsaságot ami hiba lehet.
A visszakapott adatokban bizonyos XML namespacekben szerepel "ns2:" pl.: ns2:software, ns2:invoiceDigestResult másokban pedig nem pl: header, funcCode.
Ez azt eredményezte hogy az XML-ben történő feldolgozás esetén az egyik esetben az "ns2:" namespaces adatok jelentek meg, a másik esetben pedig a "ns2:" nélküliek. 
Ilyen problémával 2.0 során nem találkoztunk, ezért feltételezem hogy ez hiba lehet.

Köszönöm!

**Comment by tkelemen73** [comment]
Ugyanilyen jelenséget tapasztaltunk a GeneralErrorResponse-nál is.

**Comment by clapygeza** [comment]
Sziasztok!
Ez nem hiba, a névtér használat miatt van. A CHANGELOG -ban: _Ha használsz response validációt a projektedben, akkor ha szükséges készülj fel arra, hogy az API üzleti válaszait nem minden esetben (pl token kérésnél az encodedExchangeToken, számlabeküldésnél a transactionId vagy a lekérdezéseknél a válasz adatok) a default, hanem esetlegesen más namespace alatt fogod visszakapni mint ahogy az korábban a 2.0 alatt történt._ Ez a common XSD importálásának egyik következménye.

Mi ezt úgy oldottuk meg egyszer s mindenkorra, hogy írtunk egy nskiller függvényt, amit ráengedünk feldolgozás előtt a visszakapott responsra, kiszed minden névtér hivatkozást és "szűz" xml-t ad vissza, ami ezután a szokásos módon feldolgozható.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ez már sokszor volt téma, zárom az issuet.
Ha van még kérdés nyissátok újra kérlek.

Üdv
