### ISSUE TITLE
[Q&A] Külföldi teljesítési hely és/vagy távoli szolgáltatás együttes teljesülése esetén nem kell beküldeni a számlákat ?

### ISSUE THREAD

**Issue by betasofthu** [nav-gov-hu/Online-Invoice#608]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
A 2021 január 1-től érvényes áfa törvény  10.melléklet 1. szerint nem kell beküldeni  azt a számlát _"melynek teljesítési helye a Közösség másik tagállama, és amely termékértékesítés, szolgáltatásnyújtás tekintetében az adóalany adófizetési kötelezettségének az Art. távolról is nyújtható szolgáltatásokat nyújtó adózókra vonatkozó különös szabályai szerint tesz eleget."_
**A két feltétel (külföldi teljesítési hely,távoli szolgáltatás) együttes teljesülése esetén nem kell beküldeni ezeket a számlákat vagy bármelyik feltétel teljesülése esetén nem kell beküldeni a számlákat?**
@NTCA-tax: Kérem a 2021.január 1-től érvényes áfa törvény 10. melléklet 1. -ben lévő szöveg értelmezését.

**Comment by AronSzigetvari** [comment]
Jól értem-e, hogy "az Art. távolról is nyújtható szolgáltatásokat nyújtó adózókra vonatkozó különös szabályai szerint" a teljesítési hely a Közösség másik tagállama akkor lesz, ha a szolgáltatás igénybevevője a közösség más országában lakó magánszemély, és neki a saját országában érvényes ÁFA-mértékekkel kell számlázni.

ld: https://www.nav.gov.hu/nav/ado/afa/tavolrol_nyujthato_szolgaltatsok.html

Azaz ez az eset valójában nem olyan nehezen detektálható, hiszen ilyenkor ez egyúttal azt is jelenti, hogy német, spanyol, stb áfamértékek szerepelnek a számlán a 27%-os magyar helyett, és ezekről vagy egy másik tagállamban kell áfa-bevallást benyújtani a megfelelő tagállami adóhatóságnak, vagy ha a mOSS-t (mini egyablakos rendszert) használja, akkor a magyar adóhatóságnak is benyújthatja az összeset egy külön bevallásban, de akkor is külön megadva, hogy melyik tagállamhoz tartozik. Ennek megfelelően tudni kell minden számláról, ha a teljesítési helye más tagállam.

Ugyan van lehetősége az adóalanynak évi 10 000 EUR erejéig a saját országának az áfájával számlázni, olyan esetben viszont a szolgáltatás teljesítési helye is belföld lesz, tehát akkor a feltétel első része nem teljesül.

**Comment by betasofthu** [comment]
Attól tartok, hogy például egy fuvarozó cég az Unióba szállít, akkor a külföldi szakasz teljesítési helye miatt nem kell beküldeni a számlát. Vagy a másik eset, ha magyar fuvarozó cég Unión belül külföldön fuvaroz. Ez persze akkor, ha az első feltétel (a teljesítés helye külföld) önállóan is elegendő a nem beküldéshez. Ezért kérdezem, hogy a két feltételnek együtt kell fennállni vagy külön értendő. A szöveg ugyanis félreérthető.

**Comment by AronSzigetvari** [comment]
@betasofthu a másik issue-ban már leírta NTCA-tax, hogy a két feltétel együtt, és kapcsolatban értendő, tehát csak akkor nem kell beküldeni, ha az és kapcsolat mindkét része teljesül, tehát eleve csak a távolról nyújtható szolgáltatások esetén merül fel, és gyanítom, hogy azért, mert ebben az esetben a számla valójában nem a magyar adóhatóság hatáskörébe tartozik.
2019 előtt az egyablakos rendszer alkalmazásakor is az adott másik tagország bizonylatolási szabályait kellett alkalmazni ilyen esetben, ez 2019-ben úgy változott, hogy annak az országnak a szabályai érvényesek, amelyben az adóalany regisztrált az egyablakos rendszerbe (hogy ne kelljen minden tagállam szabályait követni). Gyanítom, hogy ez a kivétel pont azért került be a szabályba, hogy ezeket annak ellenére ne kelljen beküldeni, hogy a magyar bizonylatolási szabályokat alkalmazzák.
Az egyablakos rendszerben pedig negyedévente be kell vallani teljesítési helyenként (tagállamonként) és áfakulcsonként az abba a tagországba teljesített szolgáltatásokat, és egyetlen átutalással teljesíteni, majd azt a NAV továbbítja a megfelelő tagállami adóhatóságokhoz.

**Comment by betasofthu** [comment]
@AronSzigetvari: Ez a az #589 ben volt, de nem kaptam választ. Időt kért a válaszra. Erre várok.

**Comment by alaplap** [comment]
Engem az is érdekelne, hogy szabad-e, amiért nem kell? Mert ha a többlet bejelentésből nincs gond, akkor inkább menjen minden számla, minthogy ne menjen be valami, amire büntetést szabhatnak ki.

**Comment by betasofthu** [comment]
Az adóhivatal honlapján megjelent közleményben nagyjából megkaptam a választ a kérdésemre:
https://nav.gov.hu/nav/ado/afa/Online_Szamla__Marciu20201216.html

_1.) Kivételt képez, így nem kell adatot szolgáltatni azon távolról is nyújtható szolgáltatások bizonylatáról, amely szolgáltatások után az adóbevallási és fizetési kötelezettségét az adóalany az egyablakos (MOSS) rendszerben teljesíti.
2.) Azt, hogy az ügylet belföldön teljesített-e, az általános forgalmi adóról szóló 2007. évi CXXVII. törvény (a továbbiakban: Áfa tv.) előírásai alapján kell megállapítani. Fontos megjegyezni, hogy egyes, **nem belföldi teljesítési helyű ügyletek bizonylatáról is keletkezhet számlaadat-szolgáltatási kötelezettség, ha a bizonylatolás során az Áfa tv. számlára vonatkozó rendelkezéseit kell alkalmazni._**

Ha a teljesítés helye nem belföld, akkor nincs számla kiállítási kötelezettség. Jól gondolom?
A gyakorlatban erről is számlát állítanak ki.  Ebben az esetben adatszolgáltatási kötelezettség is van. Jól gondolom?
Mik azok az "egyes" esetek, amiről keletkezhet számla-adatszolgáltatási kötelezettség?
@NTCA-tax tól várom a választ.

**Comment by andrew-azarov** [comment]
Ez nagyon fontos. Szinte minden számlát átmenni MOSS-ba. Jelentkezzünk a NAV-nak is? Kettős jelentés? Akkor mi a helyzet az állatkert áfakulcsok, mindannyian megy a nélkül áfakulcs és beszámolunk a nettó és bruttó csak, mint említett másik kérdés?

**Comment by betasofthu** [comment]
Úgy látom az emberek a két kivételt összemossák és csak a MOSS számlákat tekintik kivételnek a beküldési kötelezettség alól. **Jól gondolom, hogy ez két külön eset és a külföldi teljesítési helyű számlákat sem kell beküldeni?** Az adóhivatal közleménye szerint azonban a kivétel alól is van kivétel, mert egyes esetekben mégis be kell küldeni.

Továbbra is várom a választ az előző hozzászólásban feltett kérdéseimre is:
**Ha a teljesítés helye nem belföld, akkor nincs számla kiállítási kötelezettség. Jól gondolom?
A gyakorlatban erről is számlát állítanak ki. Ebben az esetben adatszolgáltatási kötelezettség is van. Jól gondolom?
Mik azok az "egyes" esetek, amiről keletkezhet számla-adatszolgáltatási kötelezettség?**
@NTCA-tax tól várom a választ.

**Comment by NTCA-tax** [comment]
Sziasztok!

Mivel ez a kérdés sokakban felmerült, ezért nem GitHub bejegyzés formájában, hanem adóhivatali közleményben adtuk meg a választ. A közleményt itt éritek el: https://nav.gov.hu/nav/ado/afa/A_szamlakibocsatok_sz20201231.html. A közlemény nem csupán a jogszabályhelyeket sorolja fel, hanem tartalmaz egy listát arról, mely ügyleteknél kötelező az adatszolgáltatás, mely ügyleteknél nem.

**Comment by betasofthu** [comment]
Köszönöm a válaszokat és a hozzászólásokat. Lezárom.
