### ISSUE TITLE
v1-es verzió lekapcsolása

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#609]
https://onlineszamla.nav.gov.hu/home
2020-12-04 11:54
"Felhívjuk a figyelmüket, hogy a karbantartás után az Online Számla v1-es végpontja, ami egyébként adatszolgáltatást már nem fogad, elérhetlenné válik."

Ez bizots hogy jó? A számlákat 5+1 évig meg kell tartani. Ezidő alatt felmerülő adatszolgáltatási problémát javítani kell tudni. Hogy lesz így anulálás + újra felküldés ha nem megy a szolgáltatás?

**Comment by renced42** [comment]
Kedves @EPluribusUnum 
A verziók lefele kompatibilisek, tehát egy 1.0,1.1-es számlát tudsz 3.0-n annulálni és módosítani is.

**Comment by EPluribusUnum** [comment]
@renced42 , Nem tudunk magasabb verzió feladni régi számlát, mert hiányoznak mellőle adatok amik kellenének a magasabb verziós kitöltéshez. Hogy lehetne v1.x-es számlát feladni az új formátumban, mikor olyan fogalmak vannak az újabb xml-ben amik a számla kiállítás pillanatában nem léteztek és nincsenek az adatok a számla mellett letárolva?

**Comment by renced42** [comment]
Kedves @EPluribusUnum

Kérlek, mondj ilyen példát.

**Comment by EPluribusUnum** [comment]
@renced42 , 2018.07.01-kor ki lett állítva egy számla, be lett küldve 1.0-ás verzióval. Jövőre kiderül hogy volt egy programhibánk ami miatt anulálni + újra be kellene küldeni ezt a számlát. Azt állítod hogy 3.0ás API-ba be lehet tenni 1.0-ás számla XML-t is?

**Comment by renced42** [comment]
Kedves @EPluribusUnum 
Nem. Azt mondom, hogy a 3.0-s sémával be lehet küldeni a 2018-as számlád módosítását.

**Comment by EPluribusUnum** [comment]
@renced42 , először is nem számla módosításról beszélek hanem érvénytelenítés (anulálás) + beküldésről.
Másodszor 2018-ban nem voltak olyan követelmények a xml adattartalommal szemben mint most, így nincs elegendő adat letárolva a számla mellett, mert akkor még nem követelte ezt meg semmi. Csak úgy lehetne ezeket a számlákat magasabb verzión beküldeni, ha minden egyes számlához kézzel hozzá kellene nyúlni és kipótólni az új adatokkal, amit azóta a magasabb verzió megkövetel.

**Comment by renced42** [comment]
Kedves @EPluribusUnum 
Erre mondottam volt hogy monjd, olyat amit nem tudsz kitölteni vagy problémás és persze kötelező.

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !
Az 1.1-es XML API július 1 óta nem támogatott.
Nem tudom ez a topic most hogyan jött létre...
Ez ismert tény volt korábban is, hogy így kell eljárni. Ezektől függetlenül írd meg, hogy mivel van problémád, és megpróbálunk segítemini.
Üdv

**Comment by omachtandras** [comment]
Szerintem itt most elméleti kérdésről van szó, legalább is én így közelítem most meg.

Nekem a következő issue ugrott be: https://github.com/nav-gov-hu/Online-Invoice/issues/457
Itt ugye @NTCA-tax  egyértelműen leírta, hogy technikai érvénytelenítés és újra átadás, bármikor, bármeddig visszamenően, ha kiderül egy probléma.

Ha a mi szoftverünkben egy ilyen hiba kiderülne biztos, hogy nem tudnánk mondjuk az 1.0-s számlákat 3.0-s verzióval beküldeni egy technikai érvénytelenítés után, mert pl. az ÁFA mentességi ok változások miatt nem tudjuk produkálni egy adómentes kulcsnál a mentességi okot. Akkor még ez nem volt követelmény és így nincs is letárolva az adott számla tételsorai mellé (de pl. egy 2.0-s számla esetében is szűkebb adattartam és más szerkezetben van tárolva, mint a 3.0-ban)). (A számlán nyilván a mentességi szöveg szerepelt "valahol" (akkoriban még több módszert támogattunk, hogy hogyan és hová írja a számlaképen a szoftver), de ezek a megoldások nem nevesített mezők voltak, hanem az ügyfél által paraméterezhető szabad szöveges "dobozok", tetszőleges adattartalommal, így nem is kerültek letárolásra az adatátadás tranzakciós tábláiban. Ezeket utólag szövegből kinyerni lehetetlenség, minden ügyfél maga írta meg a mentességi okot, nem kötelezte őket a szoftver egy sablon szöveg használatára (és pláne nem "NAVos" értékkészletnek való megfeleltetésre).)

Szerintem hasonlóra gondolt @EPluribusUnum. Úgy sejtem van/volt néhány szoftver, ahol az OnlineSzámla elvárásai miatt kerültek bizonyos adatok külön mezőben nevesítésre az idők folyamán, értékkészlettel párosítva, stb. stb.

**Comment by lvitya586** [comment]
> Ha a mi szoftverünkben egy ilyen hiba kiderülne biztos, hogy nem tudnánk mondjuk az 1.0-s számlákat 3.0-s verzióval beküldeni egy technikai érvénytelenítés után, mert pl. az ÁFA mentességi ok változások miatt nem tudjuk produkálni egy adómentes kulcsnál a mentességi okot. Akkor még ez nem volt követelmény és így nincs is letárolva az adott számla tételsorai mellé (de pl. egy 2.0-s számla esetében is szűkebb adattartam és más szerkezetben van tárolva, mint a 3.0-ban)). (A számlán nyilván a mentességi szöveg szerepelt "valahol" (akkoriban még több módszert támogattunk, hogy hogyan és hová írja a számlaképen a szoftver), de ezek a megoldások nem nevesített mezők voltak, hanem az ügyfél által paraméterezhető szabad szöveges "dobozok", tetszőleges adattartalommal, így nem is kerültek letárolásra az adatátadás tranzakciós tábláiban. Ezeket utólag szövegből kinyerni lehetetlenség, minden ügyfél maga írta meg a mentességi okot, nem kötelezte őket a szoftver egy sablon szöveg használatára (és pláne nem "NAVos" értékkészletnek való megfeleltetésre).)
> 
Bocs, hogy beleszólok, de mi akadályoz meg abban, hogy bekérd a felhasználótól az esetleg hiányzó/nem algoritmizálható adatokat? Az annuláláshoz eleve kell interakció, akkor meg nem mindegy mennyi input van a felhasználóra bízva? Amúgy sem gondolnám, hogy ez az eset annyira gyakori lenne.

**Comment by renced42** [comment]
Kedves @EPluribusUnum, Kedves Fejlesztő Kollégák!

Én azt gondolom a döntésről, hogy elvárt egy olyan interfész lekapcsolása amit már nem lehet adatszolgáltatásra használni.

Ezért egyrészt aki ezen az interfészen akar adatot szolgáltatni vagy bármi mást is csinálni:
- nem követte a jogszabályt, tehát bukta
- ha nem küldte be az adatait akkor is bukta
- ha így akar érvényteleníteni azt megteheti.
- ha ez tömeges akkor nyílvánvaló a hiba is tömeges, gépi javítással megoldható, tehát nem kell kézzel egyesével matatni az adatok között, így az beküldhető v3-al. 
- Ha mégsem mert bizonytalan, vagy valamit nem ért, akkor meg kérdést intéz felénk és javaslunk megoldást a problémájára.

Mivel jelenleg senki nem keresett fel múlt hét szombat óta, hogy nem tud adatot szolgáltatni, módosítani, érvényteleníteni vagy egyéb mást a V1-es végponton, nem gondolom, hogy tovább kellene ezt a csontot rágni :)

Kérem, hogy zárjuk az issuet és ha majd belefuttok konkrét problémába, akkor nyissuk meg újra.

**Comment by omachtandras** [comment]
@lvitya586: néhány számla esetében az ügyfél felrögzíti kézzel, aztán el van felejtve a dolog.
De ha több száz/ezer számla érintett, akkor:
- a probléma felfedezésétől kezdve 3 nap alatt
- javítani kell a programot (és tesztelni kell)
- írni kell egy programot, ami az adatkiegészítést lehetővé teszi (és tesztelni kell)
- annulálni kell (ami két részből áll, az első gyors, a program annulál, de a második részre kell embert találni, aki a cég nevében egyesével jóváhagyja azt a NAV felületén)
- kell embert találni a cégnél, aki minden bizonylaton egyesével elvégzi az adatkiegészítést, hogy aztán átadható legyen a NAVnak.
Ez utóbbi megspórolható lenne.

@renced42: remélem a lekapcsolás azért történt, mert ezen a végponton térdeltették le a rendszert nemrég és bármikor visszakapcsolható egy gyors adatátadásra. :) És remélem soha senkinek nem lesz rá szüksége. :)

Egyik ügyfelünk ahogy áttért a NAVtól letöltés alapján szállítói számla rögzítésre egyből talált egy olyan partnert, aki hibásan szolgáltatott adatot (konkrétan sokszorozva küldte be a számla tételsorait és összesítő adatait, gondolom egy rossz join miatt). Nem voltam közvetlen kapcsolatban velük, de azt láttam, hogy amikor elkészültek a javítással az összes korábbi - a partnerünk felé kiállított - bizonylatot annulálták és újra átadták. Verziószámot sajnos nem néztem, de eléggé sajnáltam őket, nem lehetett kis munka és senki nem vette észre odáig, hogy gond van... Pedig csak az nem hibázik, aki...

Ahogy írtam én most elméleti kérdésként tekintettem @EPluribusUnum felvetésére, remélem sosem lesz senkinek szüksége arra, hogy korábbi verzióval kelljen ismét átadnia a már egyszer letudott adatokat.

**Comment by nbeeps2** [comment]
@NTCA-supporter : Az egész issue innen indult: https://github.com/nav-gov-hu/Online-Invoice/issues/607

Én említettem, hogy én, amikor bevezettek egy új sémát, akkor én mindig kidobom az előzőt. Most is így lesz. Ha élesedik a 3.0, akkor az én programban nem lesz 2.0-ra vonatkozó dolog. Erre EPluribusUnum felvetette, hogy az nagyon nem jó, mert akkor hogy fogok újra beküldeni egy korábbi számlát, mert ő úgy tudta, hogy csak azzal a sémával lehet beküldeni számlát, ami a számla keltét tekintve adott időben aktuális volt. Innen volt számára a félreértés, de akkor ezek szerint az én eljárásom (is) jó, mert 3.0-val be tudok küldeni, majd bármilyen keltezésű számlát visszamenőleg, ha mégis szükség lenne rá.

**Comment by EPluribusUnum** [comment]
Igen, a kérdés elméleti, nincs **jelenleg** ilyen helyezet, DE  lehetséges forgatókönyv ez, és a törvény szeritnt erre is fel kell készíteni a szoftvert.
@renced42 , nem lehetséges a tömeges 3.0-ba felküldés ami 2 éve készült, mert például nem volt így megbontva az ÁFA rész. Így ilyenkor az összes számlához kézzel hozzá kellene nyúlni, ahol nem egyértelműen csak 1 adat kerülne be és felhasználónak kell választania.
Kérésre zárom, mert nem nem konkrét esetről van szó, de jó lenne ha weboldalra, vagy dokumentációba belekerülne a "Ha mégsem mert bizonytalan, vagy valamit nem ért, akkor meg kérdést intéz felénk és javaslunk megoldást a problémájára." rész hogy NAV elismeri hogy nem triviális régi számla új verzióban felküldésre és ilyen esetben elvárható a NAV részéről is együttműködés.

Köszönöm.
