### ISSUE TITLE
[Q&A] API-ban szoftver adatok vonatkozásának pontosítása

### ISSUE THREAD

**Issue by szako** [nav-gov-hu/Online-Invoice#61]
Tekintettel arra, hogy a 2.0-ás XSD-ben a szoftver adatok kötelezően töltendők, így szeretném tisztázni a szoftver fogalmát az XSD-ben, mert szerintem nem egyértelmű az 1.x-es dokumentációkban.

A három mondat három féle képpen definiálja a szoftver adatot:

1. A https://onlineszamla-test.nav.gov.hu/technikai_kerdesek_valaszok oldalon az alábbi van: „_A softwareId az adott számlázó program azonosítására szolgáló 18 elemű karaktersorozat._”
2. NAV dokumentáció a BasicRequestType leírásánál: „_míg a software a műveletet végző számlázó program adatait tartalmazza_”
3. Míg később a típus leírások után: "_A típus adatszolgáltatást végző szoftverre vonatkozó információkat tartalmazza._"

A számlázó program definiciójánál az található, hogy a számlázó program is az adatszolgáltató program egyben. 

Első eset:
Mire kell utalnia (számlázó komponensre vagy adatszolgáltató komponensre) a szoftver azonosítónak, ha a számlázó komponenst és az adatszolgáltató komponenst eltérő szoftver szállító fejlesztette? 

Második eset:
Egy adózó lekérdezését egy teljesen különálló, a számlázó moduloktól független programkomponens végzi el adott integrált szoftverrendszeren belül, amit az adózó cég belső fejlesztői készítettek (vagy akár az adatszolgáltató modul fejlesztői). Ebben az esetben mit kell küldeni szoftver adatként?

**Comment by NTCA-developer** [comment]
Szia @szako !

Továbbítom a kérdésedet, visszajelzek.

**Comment by NTCA-developer** [comment]
Szia!

Csatolom a kapott választ. Ha nincs több kérdéses, akkor kérlek zárd majd le a ticketet.

>Az adatszolgáltatásban szereplő softwareId elem az adatszolgáltatást végző szoftver azonosítására szolgál annak érdekében, hogy az adatszolgáltatásokban megjelenő technikai hibák, pontatlanságok okainak feltárása nagyobb hatékonysággal történhessen.

>Ennek megfelelően, összhangban a 23/2014 (VI.30.) NGM rendelet szemléletével, a számla elkészítését és az adatszolgáltatást végző szoftvert kell számlázó programnak tekinteni függetlenül attól, hogy a folyamat különböző lépéseit adott esetben több modul végzi, amelyeket adott esetben különböző gyártók, különböző időpontban fejlesztettek, és a különböző modulok adott esetben külön hardveren futnak.

>Amennyiben egy már meglévő rendszerhez utólag fejlesztett adatszolgáltató modul végzi az adatszolgáltatást, akkor javasolt az adatszolgáltató modulra képezni a softwareId-t, mivel az adatszolgáltatást kísérő technikai hibák elsősorban itt keletkeznek.

>Javasolt még a III.6 számú kérdés-válasz tanulmányozása: https://onlineszamla.nav.gov.hu/technikai_kerdesek_valaszok
