### ISSUE TITLE
XSD error - MonetaryType - vatRateVatAmountHUF[DOC]

### ISSUE THREAD

**Issue by Bart189** [nav-gov-hu/Online-Invoice#610]
We generated a new "XML", but when we try to validate against the XSD, we always get the attached error.

any idea what's wrong? Even we the examples provided, we get these errors

![image](https://user-images.githubusercontent.com/75844032/101912164-ac471a80-3bc1-11eb-965d-d90ae555ff82.png)
![error](https://user-images.githubusercontent.com/75844032/101912197-b5d08280-3bc1-11eb-89f9-383fa7656fd2.PNG)

**Comment by NTCA-supporter** [comment]
Hi @Bart189 !

First of all, I recommend you to read this: https://github.com/nav-gov-hu/Online-Invoice/blob/master/src/schemas/nav/gov/hu/OSA/CHANGELOG_3.0.md

Here's another issue related to this topic: #539 
There you can read suggestions and hints.

Br

**Comment by NTCA-supporter** [comment]
I close this issue due to inactivity.
Br
