### ISSUE TITLE
queryInvoiceChainDigest nem ad vissza számla adatot

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#611]
queryInvoiceData() visszaadja az 1.0 xml-t, DE queryInvoiceChainDigest-ben a invoiceChainDigestResult.invoiceChainElement az üres, nem adja azt vissza amit koréábban visszaadott.

TransactionID : 27QFGAJYG6TJ
taxNumber : 48508063
invoiceNumber : 59/VOT/2018

**Comment by EPluribusUnum** [comment]
Úgy tűnik ez általános gond, nem csak 1.0.

Erre a 2.0 számlára is üres invoiceChainDigestResult.invoiceChainElement jön a válaszban.

TransactionID : 2W0MDGH9ADUEK6KK
taxNumber : 48508063
invoiceNumber : 16/VMH1/2020

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !

Egy kicsit pontosíts kérlek, mert az, hogy nem adja vissza amit korábban visszaadott nem túl specifikus.

Ha jól értem, egy 1.0-ás számla adatait szeretnéd lekérdezni 2.0-ás queryInvoiceChainDigest operációval, és annak válasza nem tartalmazza az 1.0-ás számlát?
A queryInvoiceChainDigest lekérdezés requestId-ját küld el kérlek, és akkor meg tudom nézni.

Üdv

**Comment by EPluribusUnum** [comment]
@NTCA-supporter

version: 1.0
taxNumber: 48508063
invoiceNumber: 59/VOT/2018
requestId: LBR_20201214_09391016

version: 2.0
taxNumber: 12166602
invoiceNumber: UM/1045/20
requestId: LBR_20201214_09315940

**Comment by EPluribusUnum** [comment]
Nem csak a 2. hanem 3.0 API is érintett

request API : 3.0
response invoice xml version: 2.0
taxNumber: 48508063
invoiceNumber: 27/VOTGN/2020
requestId: LBR_20201214_09564003

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !
Csak a legutolsó request-re néztem rá.
Az említett2 7/VOT... számla nem alapszámla.
A queryInvoiceChainDigest-nél a CREATE-es számla invoiceNumber-ét kell megadni, és a hozzá tartozó számlalánc adatait adjuk vissza.
Kérlek ellenőrizd, hogy a többi kérésnél is ez a probléma vagy sem.
Ha más a gond, akkor nézem tovább.
Üdv

**Comment by EPluribusUnum** [comment]
@NTCA-supporter , ez valóban egy ilyen számla, de az életemet teszem rá hogy a teszt környezetben a frissítés előtt a queryInvoiceChainDigest működött asz összes (2018.07.01-től kezdődően) számlaszámra, amit a QueryInvoiceDigest() adott vissza. Akkor az utóbbi kezdett el olyan számlákat is visszaadni amiket eddig nem tett meg?

**Comment by NTCA-supporter** [comment]
@EPluribusUnum : megnéztem, már a 2.0-ás interfész dokumentációban is ez szerepelt a queryInvoiceChainDigest-nél:
"Az invoiceNumber tagban a keresett alapszámla számát kell megadni. Az operáció fel van
készítve az előzmény nélküli módosítások listázására is, ezért nem követelmény, hogy a
megadott számlaszám ténylegesen létezzen is a rendszerben, de az előzmény nélküli módosító
számláknak hivatkozni kell a keresett értékre."

A QueryInvoiceDigest visszaad mindent, ami megfelel a keresési feltételeknek :) 
Üdv

**Comment by EPluribusUnum** [comment]
@NTCA-supporter , rendben, ez alapján módosítottam a letötlés feldolgozó kódunkat és megy szépen.
