### ISSUE TITLE
INVALID_PASSWORD_HASH_CRYPTO

### ISSUE THREAD

**Issue by samuferenc** [nav-gov-hu/Online-Invoice#613]
A frissített (2020-12-12 13:00) teszt környezetben az operációk nem elérhetőek 
INVALID_PASSWORD_HASH_CRYPTO
Mi az elvárt hash algoritmus? Változtatás történt?

**Comment by samuferenc** [comment]
`<passwordHash cryptoType="SHA2-512">` 
helyett
`<passwordHash cryptoType="SHA-512">`

**Comment by NTCA-supporter** [comment]
Igen ez a változás történt. A mai telepítéssel került ki a végleges 3.0-as XSD-t támogató release, amiben már ezt kell küldeni. Ha már nem áll fent a hiba, akkor kérlek zárd le az issuet. Köszi

**Comment by HWKF** [comment]
Changelogból:
módosított ERROR: a passwordHash cryptoType attribútumának elfogadott értéke SHA-512 értékre módosult (a korábbi helytelenül definiált SHA2-512 helyett)

**Comment by wolfram265** [comment]
> 
> 
> Igen ez a változás történt. A mai telepítéssel került ki a végleges 3.0-as XSD-t támogató release, amiben már ezt kell küldeni. Ha már nem áll fent a hiba, akkor kérlek zárd le az issuet. Köszi

Mikor várható a Online Invoice Test Tool frissítése?
