### ISSUE TITLE
[Q&A] Változás történt a queryInvoiceData lekérdezés paramétereiben?

### ISSUE THREAD

**Issue by HWKF** [nav-gov-hu/Online-Invoice#614]
Mert most vagy üres válasz jön vagy "Helytelen kérés" hiba.
    <validationResultCode>ERROR</validationResultCode>
    <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
    <message>Request body contains on line: [-1] and column: [-1] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerVatData}'. One of '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerVatStatus}' is expected.]</message>

**Comment by ocsike** [comment]
privatePersonIndicator helyett van a customerVatData

**Comment by laladisc** [comment]
Amit a korábbi 3.0-ás verzióval (privatePersonIndicator) küldtünk be, azokat nagyon úgy tűnik hogy a queryInvoiceData-val nem fogjuk visszakapni.

**Comment by HWKF** [comment]
Miért? Volt benne privatePersonIndicator valamikor? 
Miért ne kaphatnánk vissza?
A hiba a kérés (request) adataira vonatkozik, abban meg még nem szerepelt semmilyen változtatás. Ott még most is csak 4 node van az InvoiceNumberQuery-ben: InvoiceNumber, InvoiceDirection, BatchIndex, SupplierTaxNumber
Ennyi volt beállítva:
  <invoiceNumberQuery>
    <invoiceNumber>"számlaszám"</invoiceNumber>
    <invoiceDirection>OUTBOUND</invoiceDirection>
  </invoiceNumberQuery>

**Comment by DrotosTot** [comment]
Nálunk sem működik. Amit a mai napnál korábban küldtünk be 3.0-val és DONE lett a feldolgozása, nem kapjuk vissza.
Ez a válasz jön a queryInvoiceData kérésre:
validationResultCode>ERROR
validationErrorCode>SCHEMA_VIOLATION
message>Request body contains on line: [-1] and column: [-1] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerName}'. One of '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerVatStatus}' is expected.]

Ellenben, ami ma ment be, azt hibátlanul visszaadja.

**Comment by laladisc** [comment]
Hasonló hibaüzenet jött korábban a 3.0-ás felküldött magánszemélyes és külföldi számlákra. Nem a kérésed rossz, hanem a számla amit le akarsz kérni elbukik a validáláson, mivel akkor még volt benne privatePersonIndicator most viszont customerVatStatus van.
