### ISSUE TITLE
[DEV support]INVALID_SUMMARY_VAT_OUT_OF_SCOPE_CODE okát nem látom a dokumentációban

### ISSUE THREAD

**Issue by scheeri** [nav-gov-hu/Online-Invoice#615]
Nem értem a hiba okát, mit nem töltöttem ki jól a TAM adókategória esetén?

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[X] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[X] 3.0

**A requestId értéke / requestId value**
```
1274862220201212163207
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
BusinessValidation result - ErrorCode: INVALID_LINE_VAT_OUT_OF_SCOPE_CODE, Message: Érvénytelen ÁFA törvény határán kívüliséget jelölő kód!, ResultCode: ERROR, Result: ERROR
BusinessValidation result - ErrorCode: INVALID_SUMMARY_VAT_OUT_OF_SCOPE_CODE, Message: Érvénytelen ÁFA törvény határán kívüliséget jelölő kód!, ResultCode: ERROR, Result: ERROR

*Egyéb tartalom / Additional content*

Transaction ID: 377NACAE12XFD6FV

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<InvoiceData xmlns="http://schemas.nav.gov.hu/OSA/3.0/data" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/base">
    <invoiceNumber>1103/2020</invoiceNumber>
    <invoiceIssueDate>2020-07-31</invoiceIssueDate>
    <completenessIndicator>false</completenessIndicator>
    <invoiceMain>
        <invoice>
            <invoiceHead>
                <supplierInfo>
.....................................
                </supplierInfo>
                <customerInfo>
............................................
                </customerInfo>
                <invoiceDetail>
                    <invoiceCategory>NORMAL</invoiceCategory>
                    <invoiceDeliveryDate>2020-07-30</invoiceDeliveryDate>
                    <invoiceAccountingDeliveryDate>2020-07-30</invoiceAccountingDeliveryDate>
                    <currencyCode>EUR</currencyCode>
                    <exchangeRate>345.71</exchangeRate>
                    <paymentMethod>TRANSFER</paymentMethod>
                    <paymentDate>2020-08-13</paymentDate>
                    <invoiceAppearance>PAPER</invoiceAppearance>
                </invoiceDetail>
            </invoiceHead>
            <invoiceLines>
                <mergedItemIndicator>false</mergedItemIndicator>
                <line>
                    <lineNumber>1</lineNumber>
                    <lineExpressionIndicator>true</lineExpressionIndicator>
                    <lineDescription>FUVARDÍJ</lineDescription>
                    <quantity>1538.39</quantity>
                    <unitOfMeasure>TON</unitOfMeasure>
                    <unitPrice>10.5</unitPrice>
                    <lineAmountsNormal>
                        <lineNetAmountData>
                            <lineNetAmount>16153.1</lineNetAmount>
                            <lineNetAmountHUF>5584288.20</lineNetAmountHUF>
                        </lineNetAmountData>
                        <lineVatRate>
                            <vatOutOfScope>
                                <case>TAM</case>
                                <reason>-</reason>
                            </vatOutOfScope>
                        </lineVatRate>
                        <lineVatData>
                            <lineVatAmount>0</lineVatAmount>
                            <lineVatAmountHUF>0</lineVatAmountHUF>
                        </lineVatData>
                        <lineGrossAmountData>
                            <lineGrossAmountNormal>16153.1</lineGrossAmountNormal>
                            <lineGrossAmountNormalHUF>5584288.20</lineGrossAmountNormalHUF>
                        </lineGrossAmountData>
                    </lineAmountsNormal>
                    <intermediatedService>false</intermediatedService>
                </line>
            </invoiceLines>
            <invoiceSummary>
                <summaryNormal>
                    <summaryByVatRate>
                        <vatRate>
                            <vatOutOfScope>
                                <case>TAM</case>
                                <reason>-</reason>
                            </vatOutOfScope>
                        </vatRate>
                        <vatRateNetData>
                            <vatRateNetAmount>16153.10</vatRateNetAmount>
                            <vatRateNetAmountHUF>5584288.20</vatRateNetAmountHUF>
                        </vatRateNetData>
                        <vatRateVatData>
                            <vatRateVatAmount>0.00</vatRateVatAmount>
                            <vatRateVatAmountHUF>0.00</vatRateVatAmountHUF>
                        </vatRateVatData>
                        <vatRateGrossData>
                            <vatRateGrossAmount>16153.10</vatRateGrossAmount>
                            <vatRateGrossAmountHUF>5584288.20</vatRateGrossAmountHUF>
                        </vatRateGrossData>
                    </summaryByVatRate>
                    <invoiceNetAmount>16153.10</invoiceNetAmount>
                    <invoiceNetAmountHUF>5584288.20</invoiceNetAmountHUF>
                    <invoiceVatAmount>0.00</invoiceVatAmount>
                    <invoiceVatAmountHUF>0.00</invoiceVatAmountHUF>
                </summaryNormal>
                <summaryGrossData>
                    <invoiceGrossAmount>16153.10</invoiceGrossAmount>
                    <invoiceGrossAmountHUF>5584288.20</invoiceGrossAmountHUF>
                </summaryGrossData>
            </invoiceSummary>
        </invoice>
    </invoiceMain>
</InvoiceData>

**Comment by laladisc** [comment]
Szia!

Szerintem az a baj, hogy a TAM-ot rossz helyre sorolod. Nem vatOutOfScope,  hanem vatExemption kategóriába tartozik.

**Comment by scheeri** [comment]
Ó, de figyelmetlen vagyok! Köszönöm szépen a gyors kiigazítást!
