### ISSUE TITLE
[Q&A]Mikortól használható az éles rendszeren a 3.0-ás API?

### ISSUE THREAD

**Issue by scheeri** [nav-gov-hu/Online-Invoice#616]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Amennyiben kész a 3.0 implementációnk, szeretnénk már most élesbe állítani, hogy addig lássuk élesbe működni, amíg nem mulasztás, ha mégis 2.0-ra kell visszaállni.
Mikortól fogadó kész a 3.0-ás hívásokra a NAV éles rendszere?
A választ elre is köszönöm!

**Comment by nbeeps2** [comment]
2021. január 4.

**Comment by NTCA-supporter** [comment]
Igen.
