### ISSUE TITLE
"vevő adószám első nyolc karaktere hiányzik"  WARN üzenet jön még mindig  ?

### ISSUE THREAD

**Issue by KMGY100** [nav-gov-hu/Online-Invoice#617]
Szerintem egy WARN bent maradt még most is

Ha előállítok egy olyan számlát melynek az áfája > 100000
de nincs magyar adószám akkor  (pl magánszemély)
"vevő adószám első nyolc karaktere hiányzik"  WARN üzenet jön.

**Comment by NTCA-supporter** [comment]
Szia @KMGY100 !
A WARN-ok aktualizálása még nem tesztelhető, az interfész dokumentációban is az szerepel, hogy folyamatban.
A sémaváltozás miatt ezek hátrébb szorultak sajnos.
Nyilvan az ilyen jellegű, már nem releváns WARN-ok ki lesznek vezetve.

Köszi a jelzést, az issuet zárom. Szólni fogunk, ha elérhető az aktualizálás.
Üdv
