### ISSUE TITLE
passwordHash értéke

### ISSUE THREAD

**Issue by boxi78** [nav-gov-hu/Online-Invoice#619]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[X] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[X] 3.0

**A requestId értéke / requestId value**
```
SZB2064667320201213192043773
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
A küldést elkaszálja: INVALID_PASSWORD_HASH_CRYPTO üzenettel.
A password Hash, amit küldök, megyegezik a doksi alapján itt: https://www.convertstring.com/Hash/SHA512 generálttal. 

*Egyéb tartalom / Additional content*

**Comment by DrotosTot** [comment]
Küldöd a cryptoType-ot is?
common:passwordHash cryptoType="SHA-512"

**Comment by boxi78** [comment]
Igen. A legutóbbi módosításig szépen tudtam is tesztelni.

**Comment by boxi78** [comment]
Ok, amit írtál, abból látom mi volt a baj: SHA-512.
Eddig (és a példa XML-ekben is) ez SHA2-512 volt.

**Comment by zonehun** [comment]
Nálam is ez volt a hiba. A példákban XML-kben még mindig így szerepel!

**Comment by NTCA-supporter** [comment]
Sziasztok!

Az API példa XML-ekben is frissítettük SHA-512-re.
Köszi!

Üdv
