### ISSUE TITLE
[FEATURE] 2.0 dokumentáció: Linkek létrehozása és oldalszámok szinkronizálása

### ISSUE THREAD

**Issue by Rossi73** [nav-gov-hu/Online-Invoice#62]
**Az igény összefoglalása / Summary of the request**
A 2.0 dokumentációban - https://onlineszamla-test.nav.gov.hu/api/files/container/download/Online%20Szamla_Interfesz%20specifik%C3%A1ci%C3%B3_HU_v2.0.pdf - az oldalszámok szinkronizálása a valós oldalszámokkal, valamint hivatkozások (linkek) létrehozása a tartalomjegyzékben.

**Az általam javasolt megoldás / The solution I propose**
A címoldalt és a tartalomjegyzéket is vegyék figyelembe az oldalszámozásnál, és legyenek linkek a tartalomjegyzékben szereplő címek.

**Egyéb tartalom / Additional content**
A 2.0 dokumentációban a tartalomjegyzéket követi az 1. oldal. Mivel PDF fájlról van szó, amiben ráadásul a tartalomjegyzékben a link kezelés sincs megoldva sajnos, ezért rendkívül megnehezíti a dokumentáció olvasását, használatát és a rá történő hivatkozást az, hogy nem lehet a tartalomjegyzékben kattintani, így a megfelelő részhez ugrani, valamint, hogy a tartalomjegyzékben az oldalszámozás nem a PDF-ben lévő valódi oldalszámot tartalmazza. Tehát a 1. BEVEZETÉS a 10. oldal legyen és ne az 1., és így tovább.

A doksiban az 5.3. pontban szerepel a 2.0-s verzió változáskövetése, ami a tartalomjegyzék szerint a 147. oldal. A 147. oldalra ellépve ezt látom:

"- mennyiség
- mennyiségi egység
- egységár
Ha a lineExpressionIndicator tag értéke false, akkor a számlasorban csak a termék vagy szolgáltatás megnevezésének megadása kötelező. Javítani kell az adatszolgáltatást"

Valójában a 156. oldalra kell ugrani, ha az 5.3-as pontot el szeretném olvasni...

**Comment by NTCA-developer** [comment]
Szia @Rossi73!

A beágyazott linkeket megcsináltam és feltöltöttem tesztre és élesre is. Az oldalszámozás a "nehezebb" mert van egy arculat ami szerint az oldalszámozás a tartalomjegyzék 1. pontjától kezdődik. Ebben nem ígérek gyors előrejutást, de a másik részét fixáltam. Remélem ez is segít.

**Comment by NTCA-developer** [comment]
Lezárom a jegyet, a doksi számozáson nem szeretnénk változtatni.

**Comment by Rossi73** [comment]
Rendben, köszönöm a gyors intézkedést, most már valóban lehet ugrani, ez nagy segítség. A számozást csak azért sajnálom kicsit, mert amikor hivatkozunk itt-ott a doksi bizonyos részeire oldalszámmal, akkor dilemma, hogy a valós, vagy a doksiban lévő oldalszámot írjuk-e le. Az arculatot nyilván nem fogja miattam megváltoztatni a NAV, így ezt kénytelen vagyok elfogadni. :-(
