### ISSUE TITLE
Mikor élesedik a verzió, amiben megszűnik a privatePersonIndicator tag?

### ISSUE THREAD

**Issue by zonehun** [nav-gov-hu/Online-Invoice#620]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[X] /manageInvoice

**A kérés verziója / version of the request**
[X] 3.0

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
A 3.0 élesítés határideje közeleg. A rendszerünkben a teszteléseket - ha egy mód van rá - nem szeretnénk feleslegesen ismételgetni. Ugyanakkor jelenleg nem tudjuk mikorra tervezni a teszteket, mivel elnézve a híreket a https://onlineszamla-test.nav.gov.hu/home oldalon és a technikai információk oldalon a verziók tartamát, azt látom, hogy a 3.1.3-mal nem került fel a privatePersonIndicator tag helyes kezelése és a customerVatStatus bevezetése.

Abban szeretnék segítséget kérni, hogy pontosan mikorra várható annak a fogadó oldali verziónak a felkerülése, aminél már probléma mentesen lehet a legutolsó specifikáció szerinti tartalmat beküldeni - azaz a customerVatStatus -t a rendszer elfogadja és nem várja ppi-t?

Köszönöm.

**Comment by marcipunk** [comment]
Szombaton rakták ki a véglegeset a tesztre eszerint: https://github.com/nav-gov-hu/Online-Invoice/issues/602
Ma már tudunk feladni tesztre  customerVatStatus-os XML-t.

**Comment by zonehun** [comment]
@marcipunk a release notes-ban nem láttam - bár elég fontos változás. De akkor ránézünk, hogy működik-e.
Köszönöm!

**Comment by NTCA-supporter** [comment]
Sziasztok!

Köszi a kommenteket. Igen már elérhető tesztrendszeren, élesen pedig január 4-től lesz a 3.0 elérhető, ezzel a verzióval.
Üdv

**Comment by zonehun** [comment]
@NTCA-supporter köszönöm a választ. A rend kedvéért kipróbáltuk szoftveresen és már valóban működik az API a customerVatStatus-szal rendben.

A téma zárható. Köszönöm.
