### ISSUE TITLE
[Q&A] Mi történt péntek óta? -> INVALID_PASSWORD_HASH_CRYPTO

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#621]
Pénteken még jó volt, most már ezzel tér vissza.
Mi változott?

**Comment by zsfoto** [comment]
Elnéztem valamit.
Zárom az issue-t.

**Comment by Amn3s1a2018** [comment]
Csak ideírom, hogy aki a hibaüzenetre keres, és valószínűleg ezt az issue-t fogja megtalálni, ne kelljen tovább keresni:
Az eredeti doksikban (Changelog és példák is)  a `user.passwordHash@cryptoType` értéke `SHA2-512` volt, a 3.0 teszt korai változatában telepítve is lett. Mostmár mindenhol `SHA-512` szerepel. (igen az SHA utáni 2-es a különbség. Az algoritmust nem kell változtatni, csak a nevet írták el az első változatokban, amit később javítottak)

https://en.wikipedia.org/wiki/SHA-3#Comparison_of_SHA_functions
