### ISSUE TITLE
[DEV support] Érvénytelen jelszó hash algoritmus

### ISSUE THREAD

**Issue by kharonx** [nav-gov-hu/Online-Invoice#622]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[X] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[X] 3.0

**A requestId értéke / requestId value**
```

```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Tisztelt Fejlesztők,

hétvége óta ezt kapom a token lekérdezésekor:

"Érvénytelen jelszó hash algoritmus"

Mi lehet a gond és mi a megoldás? Bocs, de nem találtam rá választ.

*Egyéb tartalom / Additional content*

**Comment by renced42** [comment]
Kedves @kharonx 
Nagy valószínűséggel az a baj, hogy a passwordhash cryptoType attribútumba "SHA2-512"-t írsz, jelenleg "SHA-512"-t kell használni.
A hétvégi karbantartást követően a legújabb specifikáció szerint működik az ellenőrzés.

**Comment by kharonx** [comment]
Köszönöm szépen a gyors választ! Ez fog maradni előre láthatólag?

**Comment by kharonx** [comment]
Működik , köszönöm!
Javaslom az api példákban is javítani. Ott még SHA2-512 van.

**Comment by renced42** [comment]
> Javaslom az api példákban is javítani. Ott még SHA2-512 van.

Én most megnéztem, de ott ki van javítva. Biztosan jó linket nézel?

**Comment by renced42** [comment]
> Köszönöm szépen a gyors választ! Ez fog maradni előre láthatólag?

Egyenlőre igen.

**Comment by kharonx** [comment]
Jó lett az api példa is. Köszi!
