### ISSUE TITLE
[DEV support] Teszt rendszer üzemzavar (web felület és API)

### ISSUE THREAD

**Issue by szecsenyizoltan** [nav-gov-hu/Online-Invoice#624]
Belépés ->  Reláció kiválasztása:
![Screenshot_20201215_112057](https://user-images.githubusercontent.com/31820823/102202882-25978380-3ec8-11eb-8c74-5372ed933531.png)

**Comment by NTCA-supporter** [comment]
Köszi, nézzük.

**Comment by szecsenyizoltan** [comment]
Nekem most a token kérés sem megy.

**Comment by NTCA-supporter** [comment]
Sziasztok!

A frontend login és az API-s hívások is mennek.
Kicsit még nyitva hagyom az issuet, ha bárki tapasztalna még problémát.

Üdv

**Comment by Charcsi** [comment]
IKöszöjük 
Nekünk vannak még Password gondjaink lehet az 
'Érvénytelen jelszó hash algoritmus!'
Tegnap semmi gond nem volt ezzel
Mi változott?

**Comment by NTCA-supporter** [comment]
@Charcsi az más. SHA-512-t adja meg pawwprdHash cryptoType-nak és jó lesz.
<common:passwordHash cryptoType="SHA-512">
Erről volt szó több helyen is. 
Üdv

**Comment by Charcsi** [comment]
Igen.
Ez alapján lett megoldva.
És pénteken tökéletesen tudtunk tesztelni 3.0 funkciókat.

**Comment by Charcsi** [comment]
Bocs látom 
módosított ERROR: a passwordHash cryptoType attribútumának elfogadott értéke SHA-512 értékre módosult (a korábbi helytelenül definiált SHA2-512 helyett)

**Comment by Charcsi** [comment]
Nincsen gondunk :)

**Comment by EPluribusUnum** [comment]
@NTCA-supporter , számla fel és letöltés is megy.

**Comment by Charcsi** [comment]
Azt most nem teszteltem még.  De menni fog mert a hiba a  cryptoType = SHA2-512 -> SHA-512 jelzéssel volt.
Kösszi

**Comment by NTCA-supporter** [comment]
Zárom az issuet, azóta senki nem jelzett problémát.
Köszönjük a jelzést!
Üdv
