### ISSUE TITLE
OTHER:   háromból customerVatData -ból egy megadható  ?

### ISSUE THREAD

**Issue by KMGY100** [nav-gov-hu/Online-Invoice#625]
A  12.12-én  deklarált  3.0-ás XSD sémaváltozások
Vevő státusza a számlával bizonylatolt ügyletben  (fejezetben)

"""OTHER: egyéb (belföldi nem áfaalany, nem természetes személy, külföldi áfaalany és külföldi nem áfaalany, nem természetes személy). Ilyenkor a vevő nevének és címének (customerName, customerAddress) megadása kötelező. Az adószámok közül (customerVatData) a **_háromból egy megadható_**, de nem kötelező."""

Nem csak kettőből adható meg egy ?
communityVatNumbar  vagy a 
thirdStatetaxId

**Comment by NTCA-supporter** [comment]
A customerVatData egy hármas choice-t tartalmaz: customerTaxNumber, communityVatNumber, thirdStateTaxId.
Szerintem innen jön a mondat :)

**Comment by HWKF** [comment]
Ezt kérdeztem én is, hogy mikor adható meg az OTHER mellett a customerTaxNumber? [618](https://github.com/nav-gov-hu/Online-Invoice/issues/618)

**Comment by KMGY100** [comment]
OTHER mellett a customerTaxNumber   SOHASEM adható meg.
Ezért hibás az a mondat.

**Comment by HWKF** [comment]
Tesztelve, bement warning nélkül.

**Comment by NTCA-supporter** [comment]
Ja értem, akkor ez ugyanarra vonatkozik, mint a #618 . Azt majd megválaszoljuk ott, ezt most zárom.
Üdv
