### ISSUE TITLE
3.0 queryInvoiceDigest le lett állítva?

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#626]
"OPERATION_FAILED : Feldolgozás sikertelen!
(HTTP 500 Internal Server Error)"

jött egy ideig, most meg már "connection reset."

**Comment by vivacomp** [comment]
"Csak" a teszt rendszer állt le.....

**Comment by mynameiszsofia** [comment]
@vivacomp az egész teszt rendszer ? Csak mert gondjaim adódtak a tokenigényléssel egyik pillanatról a másikra.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Már nézzük, igyekszünk.
#624 marad nyitva, ezt zárom.
Üdv
