### ISSUE TITLE
[Q&A] 3.0 customerVatStatus validációs hiba?

### ISSUE THREAD

**Issue by DrotosTot** [nav-gov-hu/Online-Invoice#627]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Adószám nélküli jogi személynek állítunk ki számlát.
1., probléma
Doksi alapján: 
"A vevő nem adóalany, ugyanakkor nem is magánszemély
customerVatStatus = OTHER 
customerInfo/customerVatData egyik eleme sem adható meg, mivel a vevő nem rendelkezik adószámmal."
Ennek megfelelően név, cím, customerVatStatus: OTHER megadva, adószám nincs kitöltve az adatszolgáltatásban, ami WARN-t kap: "Vevő adószám (első nyolc karaktere) hiányzik."
Tesztben TRID: 37BCV3B1MK6PKB86

2., probléma
Itt lehet, hogy mi értelmeztük rosszul, viszont ez működik.
Vevőnél név, cím, customerVatStatus: DOMESTIC megadva, adószám nincs kitöltve az adatszolgáltatásban, a feldolgozás hibamentesen megtörténik.
Tesztben TRID: 37BOE6XAJWGXNR3W

Úgy érzem elvesztünk...

**Comment by KMGY100** [comment]
Ez a NAV-nál hibás WARN    javítani fogják.
Akkor jelentkezik ez a hibás WARN amikor  áfa > 100000
de nincs magyar adószám
Csak türelem kell

**Comment by DrotosTot** [comment]
Köszi az infót @KMGY100 !
Az áfa határra nem is gondoltunk!
Várunk türelemmel, zárom az issue-t, gondolom máshol van már nyitva.
