### ISSUE TITLE
QueryInvoiceChainDigestResponse maxLineNumber hibás megszorítás

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#628]
Léteznek 0 soros számlák (csak fejet érintő helyesbítés), de az erre a láncra hívott QueryInvoiceChainDigest eredményében olyan válasz jön, ami nem felel meg az xsd-nek, QueryInvoiceChainDigestResponse nem enged a maxLineNumber-be 0 értéket, csak pozitív lehet. A 0-át is engedni kellene a válaszban.

Helytelen / hiányos adatok - hu.gov.nav.schemas.osa._3_0.api.QueryInvoiceChainDigestResponse
invoiceChainDigestResult/invoiceChainElement/invoiceLines/maxLineNumber = 0 : nagyobb vagy egyenlő kell legyen mint 1 (ConstraintViolationException)

2.0 és 3.0 API is érintett

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !
Köszi a jelzést.
A hibát hamarosan javítjuk, jelzek ha elérhető teszten.
Üdv

**Comment by NTCA-supporter** [comment]
Javítva lett tesztkörnyezeten.
Kérlek nyisd újra ha van még probléma.
Üdv
