### ISSUE TITLE
[Q&A] Az éles rendszer szokás szerint behalt a frissítés után

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#629]
Ezt most már a nagyon sokadik eset. Rendszeres, ha valami történik az éles rendszeren (jelen esetben a 2.12.5 frissítés telepítése), az azt követően napon behal a NAV Online számla rendszer. A sima válaszidők 300-400 msec-ről 1200-2000 msec-re szöktek még ÉJJEL is, ráadásul hajnali 4kor is volt egy hatalmas "lag". Reggel 7-től pedig jóformán használhatatlan.

Mitől hal be ilyenkor a rendszer (a túlterheléstől nem lehet, mert van forgalomkorlátozás, akkor mitől)? Nem lehet ezt megelőzni? Nem lehet valahogy másképp frissíteni a rendszert?
És miért nem lehet a Hírekben AZONNAL kiírni, hogy gond van? Már 9.20 és még mindig semmi nincs kint, nálunk meg égnek a vonalak.

**Comment by vivacomp** [comment]
A mi szoftverünk az alábbi üzenetet kapja:
SERVICE_UNAVAILABLE
A hívott operáció karbantartás miatt átmenetileg nem szolgál ki kéréseket!

Szép megfogalmazása a problémának.

**Comment by nbeeps2** [comment]
Számomra két dolog aggasztó:
1. Eddig azt hittük, hogy a korábbi nagy leállások túlterhelés miatt voltak, hisz e hatására vezették be a forgalomkorlátozás intézkedéseket.
2. Lehet, hogy nem így van, de nagyon úgy tűnik, hogy a szolgáltató által nincs 24 órában non-stop monitorozva a szolgáltatás, mert ha így lett volna, akkor éjjel az illetőnek észre kellett volna vegye, hogy baj van a rendszerrel. Egy ekkora rendszernél, ami az egész ország számlázását viszi szerintem elvárható, hogy legyen non-stop felügyelet, ami azonnal cselekszik és azonnal informálja a közérdeműt a Hírek oldalon.

**Comment by renner72** [comment]
Most már be lehet küldeni, kapok is vissza azonosítót, viszont a lekérdezéskor nem jön semmilyen inó a sikerességről vagy sikertelenségről...

**Comment by WittmannWien** [comment]
Sziasztok,
Nekünk továbbra sem sikerül számlákat lejelenteni. Token request elvileg ok, de a számla beküldés eredménytelen és hibával leáll
Nektek is van hasonló hiba?
Elöre is köszia választ.

**Comment by toothattila** [comment]
Tisztelettel szeretnénk kérni valamilyen **hiteles** információt @NTCA-developer vagy @NTCA-supporter tőletek, hogy valójában mi történik az éles rendszerrel? A 2020-12-16 22:35 -i hír megjelenése után sem állt helyre a szoláltatás.

**Comment by renced42** [comment]
Kedves @toothattila 
A NAV oldalán egyenlőre technikai problémák vannak ennek megoldásán dolgoznak a kollégák.

**Comment by WittmannWien** [comment]
Köszi az infot @renced42.

**Comment by toothattila** [comment]
Köszönöm én is @renced42!

**Comment by nbeeps2** [comment]
Nem tudom ki, de valaki mondjon le... Ez már kabaré... Az ügyfelek most már azon sírnak, hogy kicsúsztak a 24 órás törvény által előírt adatszolgáltatásból, mert nem tudják beküldeni a tegnap reggel 7-kor kiállított számlákat sem. Aláírásos, pecsétes garanciát , jegyszőkönyvet, biztosítékot követelnek, hogy nem lesznek megbüntetve, stb. Ez így év végére nagyon kellett!

**Comment by renced42** [comment]
Kedves @nbeeps2

Nem kell sírni, NAV üzemzavar esetén akkor kell beküldeni a számlát amikor arra lehetőség van az üzemzavar elhárítását követően. Jelenleg üzemzavar van.

Ha a számla, számlával egy tekintet alá eső okirat kiállításának időpontjában a számla, számlával egy tekintet alá eső okirat adatait fogadó elektronikus rendszer üzemzavar, karbantartás vagy az internetszolgáltatás elégtelensége miatt nem érhető el, a számlázó programnak a kiállított számla, számlával egy tekintet alá eső okirat legalább Áfa tv. szerinti kötelező adattartalmát az üzemzavar, karbantartás vagy az internetszolgáltatás elégtelensége megszűnését követő 24 órán belül kell az állami adó- és vámhatóság részére elektronikus úton továbbítania.

**Comment by nbeeps2** [comment]
@renced42 Én ezt pontosan tudom... Az ügyfél azonban nem így működik.

**Comment by renced42** [comment]
Igen sajnos tudom :(

**Comment by nbeeps2** [comment]
És ne haragudj, de  kikérem magamnak, hogy "nem kell sírni". 
1. Amikor hosszú évek munkájával kifejlesztesz egy jó és sikeres terméket és mégis a szoftvert anyázzák , hogy miért nem megy be a számla, amikor nem tud hova bemenni.
2. Amikor a fentiek miatt lecserélik a programodat másra, és mindegy, hogy ott is ezzel szembesül majd az ügyfél, akkor a Te programodat már lecserélték, profitot vesztesz.
3. Amikor már mindent mindenhová kiírtál e kapcsán a programodban, a honlapodra, hírlevélben, stb. és a megkeresések olyan szinten özönlenek, hogy képtelen vagy elvégezni a napi munkádat.
4. Amikor az ügyfélszolgálati kollégák már a felmondásukat fontolgatják, mert nem bírják ezeket a rohamokat és visszasírják a 2018 előtti időket.
5. Amikor úgy érzed, hogy hiába végzed maximálisan, 100% odaadással a munkádat, ennek a külső körülménynek állandóan ki vagy téve, amit teljesen bizonytalan és tehetetlen vagy és nincs megoldás rá.
6. Amikor már nem tudod normálisan fejleszteni a termékedet, mert a főcsapásirány az, hogy mindig frissítsd a programot a NAV XSD szerint 

Sokkal többről van itt szó annál, mint hogy most épp nem megy a NAV szervere, az az igazság...

**Comment by EPluribusUnum** [comment]
@renced42 , **a probléma hogy a hivatalos kommunikációban szó sincs üzemzavarról.**
https://onlineszamla.nav.gov.hu/home
„_...lassulás és esetenként kapcsolódási problémák tapasztalhatók_”. 
Nagyon nem ez a helyez. Egyszerűen **HAZUGSÁG** ami ki van oda írva.

**Comment by nbeeps2** [comment]
Ja és még valami fontos. Láttam az az élő közvetítést, amikor a NAV valamelyik vezető kollégája nagy pökhendien azt mondja, hogy hát az ilyen üzemszünetekre a programnak fel kell lennie készülve. Nem is ezzel van a gond. A mi programunkkal is lehet tökéletesen számlázni NAV üzemszünet alatt is. A problémát az generálja, hogy nem mennek be a a számlák a NAV-hoz és e kapcsán megy az értelenkedés és nem azért, mert nem tud számlázni. Szívesen beültetném ezeket az embereket az ügyfélszolgálatra, hogy szembesüljenek a gyakorlattal és ne egy íróasztal mögött mondjon ilyeneket, amikor még életében nem látott szoftver ügyfélszolgálatot közelről.

**Comment by toothattila** [comment]
> Kedves @nbeeps2
> 
> Nem kell sírni, NAV üzemzavar esetén ...

Bár nem nekem szól, de az én kérdésem kapcsán jött elő... Ezt a megfogalmazást azért én is elutasítom.

**Comment by renced42** [comment]
Kedves @toothattila @nbeeps2 

Sajnálom, nem akartam senkit megbántani én csak idéztem @nbeeps2  leveléből ahol azt jelzi, hogy sírnak az ügyfelek :(

@EPluribusUnum
Jelenleg is kiszolgálunk és megy a rendszer. Fogadjuk a számlákat jobb rosszab kisebb vagy nagyobb válaszidővel. Nem állunk.

**Comment by omachtandras** [comment]
Mindenki feszült, mégis kérem, ne essünk egymásnak, nem jutunk vele előrébb.

Nálunk a felhős környezetben hajnal óta gyűltek a számlák, nem volt részleges sikeresség sem a beküldésre. Le is állítottuk a szolgáltatást, ne jelezzen az ügyfelek felé, hogy nem sikerült beküldeni a számlákat.

Most újraindításra került, szép lassan kezdenek bemenni, sikeres válaszokat 15 perc múlva fogunk kérdezni, meglátjuk az megy-e.

**Comment by EPluribusUnum** [comment]
@renced42 . Ha nem vagytok képesek stabilan kiszolgálni az ország 100.00%-át, akkor már üzemzavart kell hogy jelentsetek. Nagyon fontos következményei/követeleményei lehetnek az ügyfelekre nézve a helytelen/nem valós kommunikáció.

**Comment by renner72** [comment]
Nálunk a beküldés megy, a beküldés ellenőrzésre nem érkezik válasz... Tegnap este is ez volt, de ma reggelre minden tegnapi beküldött számlánk DONE állapotra állt.

**Comment by nbeeps2** [comment]
@omachtandras "ne jelezzen az ügyfelek felé, hogy nem sikerült beküldeni a számlákat." Ezzel határozottan nem értek egyet. Az ügyfélnek látnia kell, hogy mely számlának beküldésével van gond, mely számla adatszolgáltatás sikerült és melyik nem. Ezt az információt nem szabad elrejteni az ügyfél elől, sőt a programból való kilépéskor is figyelmeztetni kell őt erre. Most a karáncsonyi időszakban pedig különösen.  Sokan például tegnap azzal kerestek meg minket, hogy tegnapi nap az utolsó munkanapjuk idén és mit csináljanak, ha nem megy be a számlát, mert ő már idén nem lesz, vagyis legközelebb a tegnap be nem küldött számla, majd valamikor januárban fog bemenni. Hoppá...

**Comment by betasofthu** [comment]
_Ha a számla, számlával egy tekintet alá eső okirat kiállításának időpontjában a számla, számlával egy tekintet alá eső okirat adatait fogadó elektronikus rendszer üzemzavar, karbantartás vagy az internetszolgáltatás elégtelensége miatt nem érhető el, a számlázó programnak a kiállított számla, számlával egy tekintet alá eső okirat legalább Áfa tv. szerinti kötelező adattartalmát az üzemzavar, karbantartás vagy az internetszolgáltatás elégtelensége megszűnését követő 24 órán belül kell az állami adó- és vámhatóság részére elektronikus úton továbbítania._
@renced42 Idézted a 24 órás szabályt. **Szerintem kevés a 24 óra.** Főleg ha szombat 10-12 óra közé helyezitek a karbantartást.(Ami 16 óráig tart.) A felhasználó 12 órakor kikapcsolja a PC-t és hazamegy. Nem fog vasárnap 16 óra előtt bejönni.
**Miért nem 48 óra van ebben az esetben is, mint a küldő oldali üzemzavarnál?** 
Tudom, hogy a törvény szövegét nem tudjátok befolyásolni, de talán meg kellene próbálni. Könyörgöm, legalább a tervezett karbantartást ne tegyétek szombat délre!

**Comment by omachtandras** [comment]
@nbeeps2 : nálunk nem teljesen úgy működik, ahogy Nálatok. Nem a kliens küldözgeti az adatokat, hanem szerver oldali alkalmazás. A kliens mutatja az ügyfélnek, hogy a szerver oldali alkalmazás éppen aktív-e vagy sem, ebből tájékozódhat, hogy egyáltalán van-e NAV-os kommunikáció.
De ha az e-mail értesítést bekapcsolta a kommunikációs hibákra, akkor minden számláról EGY e-mailt kap, hogy hiba van a kommunikációban, majd EGY másikat, ha az helyreállt és sikerült a beküldés. Egyébként nem kapna levelet, max. a sikeres beküldésekről, ha azt külön bekapcsolta, de ma már szerintem mindenki kikapcsolta ezt, még az 1.0 esetén használták, mert újdonság volt és korlátozott számú volt a beküldött számlák száma.
Felesleges bombázni számlánként két levéllel őket, ha tudjuk, hogy ez nem olyan hiba, amire "figyelni" kell (mert nem a mi oldalunkon van).

**Comment by nbeeps2** [comment]
@omachtandras: De a felhasználói felületen nem tudja megnézni nálad az ügyfél, hogy a számlának mi az adatszolgáltatás státusza? Bement, nem mentben, sikeres, sikertelen, stb. Én ez utóbbiról beszélek, hogy ott látja az okostojás, hogy még mindig nem ment be a számlája.

**Comment by omachtandras** [comment]
@nbeeps2 : de, természetesen van erre riport, ott látja, hogy mi az, ami még nincs beküldve, vagy "megakadt", mert a beküldés utáni visszakérdezésnél a NAV már nem adott választ.
Ami a leállítás előtt már próbálkozás alatt volt, ott látja azt is, hogy mikortól próbálkozott a service, hányszor és milyen választ kapott.
Amelyik a leállítás után került érvényesítésre, ott meg azt látja, hogy még nem próbálkozott a service.

**Comment by renced42** [comment]
> . Könyörgöm, legalább a tervezett karbantartást ne tegyétek szombat délre!

Kedves @betasofthu , mit szeretnél mikorra tegyük? De olyat mondjál ami mindenkinek jó :)

**Comment by nbeeps2** [comment]
"2020.12.17-én 13 óra 30 perctől 14 óra 30 percig az Online Számla rendszer gépi interfészén elérhető szolgáltatások leállításra kerülnek rendkívüli karbantartás miatt."

**Comment by betasofthu** [comment]
_mit szeretnél mikorra tegyük? De olyat mondjál ami mindenkinek jó :)_
@renced42: Tervezett karbantartásra javaslom a munkaidőn kívüli időpontokat pl. 22:00-06:00.

**Comment by vivacomp** [comment]
@renced42 A rendszer most (MOST és MOST) megy mint a golyó. Ez a normális állapot. Nem kell megmagyarázni a NAV kommunikációjában, hogy minden jó, csak most van egy kis szünet... egy kis karbantartás... egy kis szünet... egy kis karbantartás..., stb.
Mi bíztunk a rendszeretekben. Onnan kérjük le az adószám validációkat. Onnan kérjük le a szállítói számlákat. Csak hibátlan adószámmal engedünk számlázni. Ez a bizalom azonban törékeny.
Kérlek, nyugtass meg bennünket, hogy részetekről mindent megtesztek, mint ahogy mi is, annak érdekében, hogy bátran számíthatunk egymásra, bátran számíthatunk az őszinteségre.
Nálunk azt is mondják (O.V. szerint is): Nem most jöttünk le a falvédőről.
Üdvözlettel.

**Comment by renced42** [comment]
> Kérlek, nyugtass meg bennünket, hogy részetekről mindent megtesztek, mint ahogy mi is, annak érdekében, hogy bátran számíthatunk egymásra, bátran számíthatunk az őszinteségre.

Kedves @vivacomp 
Megnyugtatlak, hogy mindent, megteszünk, hogy bízzatok bennünk. Én személy szerint is ezen vagyok. Azt azért lásd, hogy ez egy nagy szervezet szabályokkal megkötésekkel, de soha nem publikálunk ki olyat ami nem igaz (még ha úgy is tűnik). Ez a bizalom elsődleges kulcsa. Az tény, hogy lehet, hogy nem feltétlenül ítéljük meg egyformán a működést, gondolok itt lassulás fogalmára vagy a nem működés fogalmára és ez miatt a kommunikáció nem egynszilárdságú. Megpróbálunk ebben is fejlődni és tanulni és olyan módon tájékoztatást adni, ami mindenki számára egyértelmű.

**Comment by NyBela** [comment]
Kicsit vitatkoznék a publikálásról. Amikor egyértelműen nem működött a rendszer, ügyfelünk hívta a NAV ügyfélszolgálatot, ahol azt a tájékoztatást kapta, hogy minden rendben, hívja a fejlesztőt. És Ő ezt el is hiszi, hiszen a NAV-tól mondták, neki ne magyarázzuk, hogy a NAV rendszer nem működik. Rossz a program, javítsuk.
Ez így nem korrekt. Tessék felvállani, közölni és nem félretájékoztatni. Megértjük, hogy ott is technika működik, ami elromolhat, emberek dolgoznak akik tévedhetnek. Rendben. Nincs ezzel probléma. Csak vállalja már fel valaki és merje korrekt módon  közölni, hogy "Emberek baj van, ne a fejlesztőt ostromoljátok! Leállt a motor, berúgjuk és mehet tovább!"

**Comment by renced42** [comment]
Kedves @nbeeps2

Köszönjük az észrevételeket neked és mindenki másnak. 
Ha nincs több igény és az az adott válaszokat elfogadod továbbá az éles rendszer ismét elérhető kérem, hogy zárd az issuet.

Köszönöm!
