### ISSUE TITLE
[FEATURE] QueryTaxpayerResponse: Adózó teljes adószámának lekérdezése

### ISSUE THREAD

**Issue by bmatyi94** [nav-gov-hu/Online-Invoice#63]
Az igény összefoglalása / Summary of the request
Számlázás vagy az áfa bevallás készítése során is, fontos információ a partner adószámának 9. és 10-11. karaktere is. Többször előfordul, hogy az adózók nem tájékoztatják egymást időben például egy székhely cím váltás során, ami az adott adózó 10-11. karakterének változását is eredményezi.

Az általam javasolt megoldás / The solution I propose
Adózó teljes adószámának (mind a 11. karakterének) lekérdezési lehetősége. TaxpayerDataType tartalmazza a teljes adószámot.

Egyéb tartalom / Additional content
Az adóhatóság oldalán elérhető a "több adatbázis együttes lekérdezője", ami visszaadja, hogy az adózó partnere áfaalany-e, végrehajtás alatt áll-e, köztartozásmentes adózó-e. Adóhatóság részéről elvárás, hogy az adózók körültekintően járjanak el az üzleti kapcsolataik során. Így ha a Taxpayer lekérdezés visszaadná a fenti adatokat is, nagyban megkönnyítené az adózók körültekintését, a manuális lekérdezés helyett.
Valamint a megbízható adózói státusz is lekérdezhető manuálisan az adóhatóság honlapján. Ez szintén olyan információ, amely a kellő körültekintést segítené, ha az taxpayer lekérdezés tartalmazná.

**Comment by NTCA-developer** [comment]
Szia @bmatyi94 

Ez egy IT stratégiai kérdés is, amit írsz. Ezek közül az első, hogy akarjuk-e, hogy az Online Számla rendszer legyen az elsődleges kiszolgálója ezeknek a lekérdezéseknek, mert például a számlázás szempontjából a köztartozásmentesség teljesen irreleváns.

Az igényt értem, továbbítani fogom. Addig is a türelmedet kérem.

**Comment by bmatyi94** [comment]
@NTCA-developer 

Köszönöm válaszod. A köztartozásmentesség az már egy extra dolog, azonban az adószám mind a 11.karakterének visszaadása, az viszont a helyes számlázást segíti.

**Comment by Amn3s1a2018** [comment]
@bmatyi94 
Nemtudom a konkrét problémádon segít-e, de az tv. szerint (néhány kivétellel) elegendő a vevői adószám első 8 számjegye. Persze a számlázószoftvert elbonyolítja ha a kivételeket is korrektül akarod kezelni, de onnantól, hogy eleve csak 8 karakteres adószám kerül a számlára és a feladásba is (amikor csak lehet), nem okoz problémát, ha az adószám maradékát esetleg helytelenül adták meg, vagy ha pl. változik és „elfelejtenek” szólni.

**Comment by NTCA-developer** [comment]
Szia @bmatyi94 

Befogadjuk az igényt. A 2.0-ás adózó lekérdező válaszában szolgáltatjuk a törzsszámot, az ÁFA kódot és a megyekódot is. A típus a Data XSD-ből származik le, úgyhogy ami a válaszban visszajön azt objektum szinten egy az egyben be lehet tölteni a számla kiállítás során a vevőhöz.

A megyekódra külön adatkapcsolati fejlesztés szükséges, tehát a sémában most csak a helyét csináljuk meg. Ha már megkapjuk az adatokat akkor jelezzük külön.
