### ISSUE TITLE
[Q&A] 2.0 queryTransactionStatus üres válaszüzenet

### ISSUE THREAD

**Issue by ViskovicsKrisztian** [nav-gov-hu/Online-Invoice#630]
A 2.0 API-ban sikeresen (OK státusszal) bemegy a számla a **v2/manageInvoice** végponton, meg is kapom rá a tranzakció azonosítót.
Néhány esetben viszont a visszakapott tranzakció azonosítóval amikor a **v2/queryTransactionStatus** végpontot meghívom, akkor nem jön semmilyen válasz rá vissza, C#-ban ezt null referencia kivétel hibaként kapom vissza. Normál esetben OK, ABORTED vagy egyéb státuszt kapok XML válaszként. Próbálkoztunk újraküldeni a problémás számlát, sajnos az új tranzakció azonosítójára is ugyanaz a probléma.

Mitől lehet ez? Mit tudunk ilyenkor csinálni? A beküldött számla nem látható a webes listában sem.

**Comment by nbeeps2** [comment]
Ha az éles rendszerben próbálod, akkor ne törd magad, nem működik, leállás van.

**Comment by ViskovicsKrisztian** [comment]
Éles rendszerbe próbálom, viszont ez a probléma már előző héten is jelen volt. Tegnapi napon a számlák 5%-ával ez történt, ugyanabban az időben lettek felküldve. A többségük létrejött és le is kérdezhető a státusza, más számlákat akármennyiszer újraküldve sem hajlandó státuszt visszaadni, és nem is látható a webes felületen,

**Comment by ViskovicsKrisztian** [comment]
Továbbra is fennáll a probléma.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ez még továbbra is fennáll? Teszt rendszereről tudtok küldeni azonosítókat az elmúlt pár napból?
Köszi

**Comment by ViskovicsKrisztian** [comment]
Szia!

Annyiból más már a helyzet, hogy a webes felületen meg lehet találni a tranzakció alapján, ami ABORTED státuszt kap. Ott a hibát meg is találjuk, javítás után már OK státusszal tér vissza az üres helyett. Viszont ugyanúgy nem jön néhány esetben a státusz, ha nem jó a számla adatokban valami.
Nem tudom hogy mikor fog előfordulni újra, mert véletlenszerűen jön elő. Megírom az azonosítóját, amint belefutunk újra.

**Comment by ViskovicsKrisztian** [comment]
Sikerült találnom olyan XML-t amire előjön újra a hiba, ezek a beküldött tranzakció azonosítói:
3A7RG3X3EDRN4DCX
3A7RG7GHTY4MMYAY
3A7RGAY1DNIOUQBI

**Comment by NTCA-supporter** [comment]
Köszi @ViskovicsKrisztian !
Utánanézek és jelentkezem.
Üdv

**Comment by NTCA-supporter** [comment]
Szia @ViskovicsKrisztian !
Az említett beküldések nem sémavalidak.
A válaszban ott van, hogy mi a problémás:
Value '2038 Sóskút' is not facet-valid with respect to pattern '[A-Z0-9][A-Z0-9\s\-]{1,8}[A-Z0-9]' for type 'PostalCodeType'.]

A te oldaladon lesz valami probléma a parseolásnál.
Üdv

**Comment by ViskovicsKrisztian** [comment]
Szia @NTCA-supporter !
Köszönöm, ez alapján sikerült megtalálnom a hiba pontos helyét. A válaszüzenet kezelésben null ellenőrzés elmaradt.
