### ISSUE TITLE
SERVICE_UNAVAILABLE válasz esetén válasz xml nem felel meg xsd-nek

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#631]
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><GeneralErrorResponse xmlns="http://schemas.nav.gov.hu/OSA/2.0/api" xmlns:ns2="http://schemas.nav.gov.hu/OSA/2.0/data"><result><funcCode>ERROR</funcCode><errorCode>SERVICE_UNAVAILABLE</errorCode><message>A hívott operáció karbantartás miatt átmenetileg nem szolgál ki kéréseket!</message></result></GeneralErrorResponse>`

cvc-complex-type.2.4.a: Invalid content was found starting with element 'result'. One of '{"http://schemas.nav.gov.hu/OSA/2.0/api":header}' is expected. (SAXParseException)

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ez még továbbra is probléma? Ha nincs teendőnk, kérlek zárjátok.

Üdv

**Comment by EPluribusUnum** [comment]
Nem fordult elő azóta ilyen.
