### ISSUE TITLE
[Q&A] Nem működő szolgáltatás esetén a queryServiceMetrics szerint minden rendben

### ISSUE THREAD

**Issue by zonehun** [nav-gov-hu/Online-Invoice#633]
Sziasztok,

A mai üzemelési probléma miatt jobban megnézegettük a queryServiceMetrics szolgáltatást a v2-ben. Azt látjuk, hogy a tokenRequest esetén SERVICE_UNAVAILABLE jön vissza, miközben a https://api.onlineszamla.nav.gov.hu/metricService/v2/queryServiceMetrics/metric/responseTimeAverageMsTokenExchange

XML szerint meg minden OK, csak a válaszidő kicsit hosszabb:
...
`<ns2:metricValues>
<ns2:value>82.77123665113254</ns2:value>
<ns2:timestamp>2020-12-16T14:16:15.035Z</ns2:timestamp>
</ns2:metricValues>`
...

A korábbi és mai tapasztalatokból is kiindulva, szeretnénk építeni erre a szolgáltatásra, hogy a felhasználóink azonnal értesülhessenek, ha gond van és ne minket hívogassanak.  Egyelőre azonban ez így nem megbízható.

Ugyanakkor szerintem az sem megoldás, hogy teljesen felesleges tokenExchange kérésekkel bombázzuk a végpontot.  Ugyanis ez a végpont ad korrekt hibaüzenetet. Próbáltuk például a queryTaxpayert is, de ott egyszerűen kapunk egy 28-as curl üzenetet - timeout.

Mi a javaslatotok? Mikortól lehet erre a szolgáltatásra valóban építeni? Vagy ez így fog működni a jövőben is?

Köszönöm.

**Comment by zonehun** [comment]
Azt elfelejtettem, hogy természetesen az lenne a szuper, ha a serviceMetrics teljesen konzisztens lenne a valós működéssel. Ugyanis az elképzelés nagyon jó, hiszen gyorsan tudjuk olvasni az adatokat és kiértékelni. Tehát tényleg jó lenne ebbe az irányba menni és építkezni.

Már az is jó lenne, ha a rendszer üzemképtelensége esetén, egyszerűen nem generálódnának újabb és újabb serviceMetrics bejegyzések. Tehát, ha a tokenExchange a SERVICE_UNAVAILABLE státuszt dobja, akkor a kapcsolódó responseTimeAverageMsTokenExchange metrika ne adjon értékeket (kifuttatja szépen az utoljára mérteket) - vagy dobjatok arra is egy általános SERVICE_UNAVAILABLE státuszt. 

Mi a véleményetek?

**Comment by MiskaPista** [comment]
Mi sem raktuk bele a programunkba, mert semmi értelmeset nem lehet kihámozni belőle. Ha van valakinek megoldása, arra én is kíváncsi lennék ;)

**Comment by zonehun** [comment]
Remélem, hogy @NTCA-developer olvassa majd a topicot és tud nekünk tanácsot adni, vagy a háttérben utánakérdezni.

**Comment by KMGY100** [comment]
Csak  a tokenExchange  válasza  adja a SERVICE_UNAVAILABLE státuszt ?
A többi kérésbe nincs beépítv ez a válasz   ????????????????????????

**Comment by zonehun** [comment]
A serviceMetrics szimpla GET lekérdezés. És ott ilyen egyelőre nem jön - bár jó lenne. 

De pl. ma próbáltuk a queryTaxpayert és ott sem jött a SERVICE_UNAVAILABLE, csak szimpla 404.

**Comment by skovacs70** [comment]
Sziasztok, 
Jelenleg egyik metrika sem ad vissza értékeket (nincsenek "value" tag-ek). Valami központi hiba lehet?
Mi használnánk ezt a szolgáltatás, de így elég nehéz.

@NTCA-developer rá tudnál nézni?

Köszönöm.

**Comment by NTCA-supporter** [comment]
Sziasztok!

A metrika értékek töltése működik (utolsó komment). Az általános, független visszajelző oldal/api tervben van, a #408 szól erről.
Ezt az issuet zárom, ha van még kérdés nyissatok újat kérlek.

Üdv
