### ISSUE TITLE
[Q&A] Vevő adószám (első nyolc karaktere) hiányzik OTHER és PRIVATE_PERSON esetén is

### ISSUE THREAD

**Issue by marcipunk** [nav-gov-hu/Online-Invoice#634]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Nem tudom, hogy bug vagy feature. OTHER és PRIVATE_PERSON tartalmú customerVatStatus esetén is figyelmeztetést kapunk a teszt rendszerben:
Figyelmeztetés
MISSING_HEAD_DATA_CUSTOMER	Vevő adószám (első nyolc karaktere) hiányzik.
InvoiceData/invoiceMain/invoice/invoiceHead/customerInfo/customerVatData/customerTaxNumber

Ez normális?

edit: bocsánat, a vonatkozó rész lemaradt:
```
			<invoiceHead>
				<supplierInfo>
					<supplierTaxNumber>
						<base:taxpayerId>12103519</base:taxpayerId>
						<base:vatCode>2</base:vatCode>
						<base:countyCode>44</base:countyCode>
					</supplierTaxNumber>
					<supplierName>mLightDemoMOSZR3 Kftr.</supplierName>
					<supplierAddress>
						<base:simpleAddress>
							<base:countryCode>HU</base:countryCode>
							<base:postalCode>1011</base:postalCode>
							<base:city>Budapest</base:city>
							<base:additionalAddressDetail>Szenes Iván bányatelep 5.</base:additionalAddressDetail>
						</base:simpleAddress>
					</supplierAddress>
				</supplierInfo>
				<customerInfo>
					<customerVatStatus>PRIVATE_PERSON</customerVatStatus>
				</customerInfo>
				<invoiceDetail>
					<invoiceCategory>NORMAL</invoiceCategory>
					<invoiceDeliveryDate>2020-12-16</invoiceDeliveryDate>
					<currencyCode>EUR</currencyCode>
					<exchangeRate>360.900000</exchangeRate>
					<paymentMethod>TRANSFER</paymentMethod>
					<invoiceAppearance>PAPER</invoiceAppearance>
				</invoiceDetail>
			</invoiceHead>
```

**Comment by NTCA-supporter** [comment]
Szia @marcipunk !
A WARN aktualizálás még nem történt meg. Természetesen ez figyelmen kívül hagyható, ilyen esetben nem szükséges a magyar adószám megadása.
Ha megtörtént a WARN aktualizálás a 3.0 sémára, fogunk jelezni, és az interfész dokumentáció is aktualizálva lesz.
Zárom az issuet.
Üdv
