### ISSUE TITLE
[Q&A] Tételekben ÁFA és bruttó érték szerepeltetése

### ISSUE THREAD

**Issue by szako** [nav-gov-hu/Online-Invoice#635]
A Data példa XML-ek végignéztem és bizonyos példákban nincsen töltve a tételeknél az ÁFA és a bruttó érték. A séma szerint nem elvártak ezek az mezőkés be is fogadja a NAV ezen adatok nélkül a számlákat, normál számlánál is.

Az alábbi esetek ezek:
- 3.1.2.1 példa: Belföldi előlegszámla
- 3.1.2.2 példa: Belföldi előlegszámla mennyiség és egységár megjelölése nélkül
- 3.1.3.1 példa: Belföldi végszámla
- 4.6 Több számla módosítása egy okirattal

A kérdésem, hogy ezekben a példákban (és a hozzájuk tartozó leírásban) mi alapján nem lettek töltve ezek az adatok? Azért kérdezem, mert számlák méretének csökkentésénél lehet esetleg ennek szerepe nálunk.

**Comment by NTCA-supporter** [comment]
Szia @szako !

A példaszámlák elkészítésekor a mindenkori xsd-k és üzleti validációk szabályai alapján, a forgalomban lévő papír számlaképek tartalmából indultunk ki.
Tétel szinten ezek a minták sem tartalmazták az ÁFA-, és a bruttó  összeget. Mivel a közölt számlakép nem tartalmazta, az xml-be sem került bele.
Ugyanakkor lehet olyan számla, amelyeken szerepelnek az érintett adatok. Van ilyen mintánk is. Akkor ezek az xml-ben is megjelentek.
Mindkét számlakép, és mindkét adatszolgáltatás szabályos.

A példaszámlákat tartalmazó dokumentumba igyekeztünk többféle mintát betenni, de az elején kiemelten szedve írtuk:
Az itt bemutatott számlaképek kizárólag az adatszolgáltatáshoz nyújtanak segítséget. A bemutatott számlaképek semmiképp sem tekinthetők kötelező mintának.
Az adózók által használt számláknál az adatok köre, sorrendje, elhelyezkedése, a szóhasználat eltérhet az itt bemutatottaktól.

Ha ezeket az adatokat valamilyen célszerű okból el akarod hagyni nyugodtan megteheted. Természetesen, ha azok nélkül is sikeres adatszolgáltatást tudsz teljesíteni.

Üdv

**Comment by szako** [comment]
Köszönöm!

**Comment by szako** [comment]
Még egy kérdés: Akkor is lehagyhatók a mezők (tételben adóérték és bruttó), ha a számlán szerepel?

**Comment by NTCA-supporter** [comment]
@NTCA-tax megválaszolja.
Üdv

**Comment by szako** [comment]
@NTCA-tax Meg tudnád válaszolni ezt a kérdést? Köszönöm!

**Comment by NTCA-supporter** [comment]
@NTCA-tax kérlek válaszold meg.
