### ISSUE TITLE
v3 tokenExchange error 404

### ISSUE THREAD

**Issue by irsl** [nav-gov-hu/Online-Invoice#637]
Hello,

Mult vasarnap ota error 404 -et kapot a v3-as API-n keresztul a tokenExchange metodus meghivasakor. Ugyanaz a kodbazis hibatlanul mukodott vasarnapot megelozoen. Feltetelezem nem ez a legmegfelelobb hibabejelentesi csatorna, de a hivataloson keresztul legutobb semmi valaszt nem kaptam :) 
Szoval a kerdes: mikor lesz ez a cucc ujra elerheto, vagy nekem kene downgradelnem v2-re, hogy ne buntessenek meg a szamlabekuldes elmulasztasa miatt?

Koszi.

**Comment by renced42** [comment]
Kedves @irsl 
A teszt rendszerről van szó?

**Comment by NTCA-supporter** [comment]
Szia @irsl !
Próbálkozz a passwordHash-nél az SHA-512 értékkel.
https://github.com/nav-gov-hu/Online-Invoice/blob/master/src/schemas/nav/gov/hu/OSA/CHANGELOG_3.0.md 2.8 fejezet.
Üdv

**Comment by irsl** [comment]
A teszt rendszer es az eles is csinalja. Vasarnapot megelozoen sikeresek voltak a bekuldesek, a protokoll valtozasokat leimplementaltam.

**Comment by renced42** [comment]
> es az eles is csinalja

Kedves @irsl a teszt rendszert meg tudjuk nézni, ha küldesz request ID-t. Az éles rendszerre meg biztos nem tudsz V3-at beküldeni, mert még nincs kipublikálva a gépi interfész hozzá.

**Comment by irsl** [comment]
Korrekcio: most ellenoriztem, a teszt rendszer valoban amiatt dobta vissza a requestet, mert a passwordHash cryptoType-nak SHA2-512-t kuldtem SHA-512 helyett (Nem tudtam errol a backward incompatible modositasrol). Ezt most modositottam, a szamlakat a teszt rendszernek bekuldte.

Az eles rendszer (https://api.onlineszamla.nav.gov.hu/invoiceService/v3/tokenExchange) tovabbra is error 404-et dob.

**Comment by renced42** [comment]
> Az eles rendszer (https://api.onlineszamla.nav.gov.hu/invoiceService/v3/tokenExchange) tovabbra is error 404-et dob.

Mert nincs ilyen! Nincs még v3-ra küldési lehetőség azt majd 2021. január 04-től teheted meg

**Comment by irsl** [comment]
"Nincs még v3-ra küldési lehetőség azt majd 2021. január 04-től teheted meg"

De hiszen januar 1 a torvenyi hatarido az atallasra, nem?

**Comment by renced42** [comment]
> De hiszen januar 1 a torvenyi hatarido az atallasra, nem?

Nem. 2021 január 04. 
Átállni átállhatsz, de hamarabb nem küldhetsz be.

**Comment by irsl** [comment]
Ok, koszi.
