### ISSUE TITLE
[DEV support] hello world teszt program

### ISSUE THREAD

**Issue by wolfram265** [nav-gov-hu/Online-Invoice#638]
Honnan lehet letölteni példa kódot (C#,java) ami kitölt és beküld egy egyszerű számlát a v3.0-ás teszt rendszerbe?

**Comment by csandazoltan** [comment]
Szerintem ilyen nincs, ez egy XML alapú adatközlő rendszer, az XML az platformfüggetlen.
A dokumentáció a létrhozandó struktúrát tartalmazza, hogy azt milyen nyelven generálódik az mindegy és független ettől a projekttől.

C#, Java, PHP, .NET, Python, Ruby és hozzájuk tartozó adatbázisok, implementálási szinten nem hiszem, hogy itt válaszokat fogsz találni.

Dokumentáció
> Cél:
> A dokumentum célja az online számlaadat-szolgáltatás interfész üzleti funkcionalitásaiért felelős
> /invoiceService működésének, illetve az általa használt XML üzenetstruktúrának bemutatása, valamint
> a számlázó programok interfészhez történő integrációjának támogatása.

**Comment by renced42** [comment]
Kedves @wolfram265 
A küldésre vannak példák a honlapon, Dokumentációk alatt itt https://onlineszamla.nav.gov.hu/api/files/container/download/OnlineSzamlaFejlesztoiForum_Prezentaciok_es_prog_mintak.zip , de a felküldendő  xml állományt neked kell elkészíteni. Vannak példa xmlek is az api hívásokra itt  https://onlineszamla.nav.gov.hu/api/files/container/download/API%20sample%20XML%203.0.zip és a tartalmukra is itt https://onlineszamla.nav.gov.hu/api/files/container/download/Peldaszamlak_v3.0.zip . Illetve érdemes a specit is elolvasni :) . Ha megakadsz akkor az Onlineinvoice Tool is használhatod Test Toolt is használhatod.

**Comment by lakatoskevin** [comment]
Na helló mi a helyzet? Szerintem "Hellóvörld" gyanánt megpróbálhatsz egy tokenkérést indítani. Ha jön vissza egy XML akkor jó irányban haladsz. Ajánlották itt az Onlineinvoice Tool-t, de nagyon jó -ÁLTALÁNOS- célokra még a SOAP UI is. Az is egy nagyon jó eszköz API-k tesztelésére-kipróbálására.

**Comment by NTCA-supporter** [comment]
@wolfram265 van még kérdés? Ha nincs akkor zárd az issuet kérlek.
Üdv

**Comment by NTCA-supporter** [comment]
Zárom. Ha van kérdés, nyisd újra kérlek.
