### ISSUE TITLE
[FEATURE] INVOICE_NUMBER_NOT_UNIQUE esetén szeretnénk visszakapni a transactionId-t

### ISSUE THREAD

**Issue by wrobi** [nav-gov-hu/Online-Invoice#639]
**Az igény összefoglalása / Summary of the request**

Amikor a manageInvoice operáció timeout-tal elszáll, csak több művelettel lehet kinyerni a hiányzó tranzakciós azonosítót. (az egyszerűbbik út, queryInvoiceDigest ilyenkor legtöbbször nem ad vissza semmit) Szeretném kérni, ha lehetséges, hogy INVOICE_NUMBER_NOT_UNIQUE hibaüzenetben kapjuk vissza az eredeti adatszolgáltatás tranzakciós azonosítóját! Ezzel jó pár tranzakciót tudunk megspórolni, és implementálni is jóval könnyebb. Lehetséges lenne ez?
Köszönöm a választ!

**Comment by nbeeps2** [comment]
Nem rossz ötlet, de az igazi az, ha nem küldöd be kétszer a számlát és ezt próbálod meg foggal-körömmel kivédeni. A dupla beküldésről ugyanis az ügyfél e-mailben fog értesülni, illetve a webes felületen is lát majd egy jó nagy piros X-et az adatszolgáltalásnál, miközben ez a 2. adatszolgáltatásra vonatkozik, mert az első sikeres volt.

**Comment by renner72** [comment]
A queryInvoiceDigest visszaadja a transactionId értéket (értékeket). Ha újraküldés előtt lekérjük, hogy beküldtük-e már, akkor elvileg innen megtudhatjuk és utána párosíthatjuk a számlához az eredeti transactionId értéket... Ha jól értelmezem...

**Comment by wrobi** [comment]
nbeeps2: Igazad van, azonban az eddigi tapasztalataim azt mutatják, hogy 50 db elakadt számlából kettő, amit befogadott a NAV, a többi nincs tárolva. Ilyen arány mellett nem látom értelmét a befektetett munkának. Inkább újraküldök mindent, amint hajlandó adatokat fogadni a szerver. Amúgy az ügyfeleimet nem zavarja az ilyen jellegű piros X, és e-mail. Az hogy nem mennek be a számlák, viszont sokkal jobban.

renner72: Elméletben igen (ha vársz vele legalább 5 percet), de gyakorlatban queryInvoiceDigest szolgáltatás ilyenkor 10-15 sec! válaszidővel dolgozik, ha egyáltalában szóba áll. Ez volt nekem is az ötletem a hiba lekezelésére még szeptemberben. A héten ez is elhasalt. Több időm nincs ilyen problémakörrel foglalkozni, amikor év végi hajtás van.

**Comment by lvitya586** [comment]
Ez az igény már felvetődött egyszer, de ha jól látom nem került megválaszolásra, ugye @NTCA-supporter ?

https://github.com/nav-gov-hu/Online-Invoice/issues/386#issuecomment-700674260

Amúgy szerintem se ártana ez az opció.

**Comment by nbeeps2** [comment]
Azért az INVOICE_NUMBER_NOT_UNIQUE -al csak óvatosan, mert ez előjöhet olyan szituációban is, amikor több telephelyről számláznak és nem állítanak be kezdősorszámot vagy bizonylatszám előtagot.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezzel eddig nem tudtunk foglalkozni, de megvizsgáljuk. Egy INFO szintű üzenetet el tudnék hirtelen képzelni, de majd kitaláljuk.
Jelzek majd.

Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

Mivel a transactionId megszerzése megoldható a jelenlegi módszerekkel, így nem várható ilyen jellegű változtatás.
Köszönjük a megértést és a türelmet. Zárom az issuet.

Üdv
