### ISSUE TITLE
[Q&A] application.wadl 2.0 hol érhető el?

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#64]
Az application.wadl nincs benne ebbe a repo-ban, és a https://onlineszamla-test.nav.gov.hu/dokumentaciok oldalon sem lett publikálva. Honnan lehet hozzájutni?

**Comment by NTCA-developer** [comment]
Szia!

Még nem készült el, de hamarosan meglesz. A hónap végéig biztosan. Addig is a típuskötések kiolvashatók a sémából, a névkonvenciók segítenek benne. Esetleg van konkrét request, amivel kapcsolatban van kérdésed és tudok benne segíteni, vagy a kérdésed csak az általánosságra vonatkozott?

**Comment by EPluribusUnum** [comment]
Csak általánosságban. Várom a megjelenést. Hol lesz publikálva?

**Comment by NTCA-developer** [comment]
Szia!

Mindkét helyen publikálva lesz. A központi honlapon azért, mert ott a helye, itt pedig azért mert szeretnénk verziókezelni, plusz ha typoztunk valamit akkor itt lehet kommentelni is hozzá. Mindjárt pusholom.
