### ISSUE TITLE
v2/queryInvoiceData lassulás

### ISSUE THREAD

**Issue by vbela75** [nav-gov-hu/Online-Invoice#640]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

A legújabb frissítést követően az v2/queryInvoiceDigest nagyon felgyorsult és stabil lett. Köszönjük :) 
Viszont a v2/queryInvoiceData folyamatos lekérdezés közben rendszeresen lelassul ennek mi az oka? 
Forgalomkorlátozás lett bevezetve vagy csak a rendszer ne érte még utol magát?

200 db vagy több számlát is a frissítés előtt simán le lehetett tölteni folyamatosan most pár számla után is akár timeout-ra fút a rendszer.

**Comment by NTCA-supporter** [comment]
Szia @vbela75 !
Először is örülünk a digest gyorsulásnak :) 
Forgalomkorlátozás természetesen nincs, azt mindenképp publikálnunk kellene mindenhol, és nem is tervezünk ilyet.
Segíts kérlek egy requestId-val, és arról kérek logokat az illetékesektől. 
Általános lassulásról nem tudunk az incidens helyreállítása óta.

Köszi

**Comment by vbela75** [comment]
Sajnos nem logoltam pontosan csak időpontjaim vannak (eddig nem volt rá szükségem) és válasz a timout-ról 
magyar időzóna szerint most pár perce is:   2020-12-18 15:01:14 megcsinálom hogy betegye a logba a requestId-it és majd jelentkezek holnap. :)

**Comment by vbela75** [comment]
@NTCA-supporter  elindítottam a logot az requestId-ra ha van adat küldöm.

**Comment by vbela75** [comment]
@NTCA-supporter 

RID20201218152352250, RID20201218153340577, RID20201218153926794, RID20201218154027378 az elmúlt 20 perc termése. :)

**Comment by vbela75** [comment]
@NTCA-supporter 

Az előző írásom óta nem volt time out hibám. Lehet hogy sikerült megoldani?

A másik megint szeretnék egy pár jó szót szólni. :)

Több mint 2000 ügyfél adatát töltöm le napi rendszerességgel éjszakánkét az frissítés előtt 2-4 óra között sikerült ezt megoldani. Ma reggelre egy tejes nap után (hétfő amikor keletkezik is elég számla) ez a folyamat jelentősen felgyorsult. 3737 db számlát 36 perc alatt sikerült letölteni 2 különálló gépen 1-1 szálon. Ez jelentős gyorsulás, nagyon köszönjük a fejlesztést remélem a 3.0-ba már ez benne lesz és ilyen sebességgel tudunk majd dolgozni. 

Kellemes ünnepeket, az idei kemény év után. :)

**Comment by rtoth0407** [comment]
Szia @NTCA-supporter,
a teszt rendszerben sok számlánk SAVED státuszban van órák óta.
Tranzakció azonosítók:
37WXV8628WC91MDM
37WXV9HLQHFG5FDP
37WXVL60WS1CEAGJ
37WXVMID0QDQ8ZEV
37WY177P2VYL8EK8
37WYONJOS8YDZ11A
37WYOOUT2LGGNK1I
37WYOQ6Q0QK01F1N
37WYORIRBA6JQJ1S
37WYOSUUZVSDI5PP
37WZ0OQ413YFSXR1
37WZ0Q04WBY127R9
37WZ0RAF5YLF5R98
37WZ10IV7PFNAVX4
37W1THQPGZ5YPTU6
Tegnap is akadozott a feldolgozás, de úgy tűnik ma teljesen leállt.

**Comment by NTCA-supporter** [comment]
Sziasztok!

@vbela75 köszi, idén is igyekszünk :) 

@rtoth0407 kérlek nyiss egy új issuet, mert az általad jelzett probléma más, nem ehhez kapcsolódik (ott majd reagálok rá).

Az issuet zárom.
Üdv
