### ISSUE TITLE
[Q&A]unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by scheeri** [nav-gov-hu/Online-Invoice#641]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
A hét elején a teljes kommunikáció működött (roken, manageinvoice..), most az aábbi hibaüzenet jön a token kérésre:
I/O error on POST request for "https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3/tokenExchange": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Az alkamazásban azóta semmi nem változott.

**Comment by renced42** [comment]
Kedves @scheeri 
Ez tipikus java tanusítvány hiba.
Ha eddig jól működött, akkor a java futtató környezetednek megadott alapértelmezett vagy beállított keystoreból eltünt a nav publikus szervertanúsítványa. ez esetleg java telepítéskor felül szokott íródni.
Így ismét hozzá kell adni.

**Comment by scheeri** [comment]
Valóban. Köszönöm a segítséget!
