### ISSUE TITLE
[DEV support] Online Invoice Test Tool INVALID_REQUEST_SIGNATURE

### ISSUE THREAD

**Issue by wolfram265** [nav-gov-hu/Online-Invoice#642]
Az Online Invoice Test Tool Build:3.0.7649.17762
INVALID_REQUEST_SIGNATURE hibát ad v3-as teszt TokenExchange kérésnél.
Mi lehet a gond?

**Comment by KMGY100** [comment]
Már sokszor és több helyen leírták, hogy:
SHA2-512   helyett   SHA-512
<common:passwordHash cryptoType="SHA-512">'+passwordHash_+'</common:passwordHash>
Minden kérésben így kell.

**Comment by wolfram265** [comment]
> 
> 
> Már sokszor és több helyen leírták, hogy:
> SHA2-512 helyett SHA-512
> <common:passwordHash cryptoType="SHA-512">'+passwordHash_+'</common:passwordHash>
> Minden kérésben így kell.

A legújabb Online Invoice Test Tool Build:3.0.7649.17762-ról van szó, a nav oldaláról letöltve.

**Comment by renced42** [comment]
Kedves @wolfram265 
A Test Tool akkor tud ilyen hibát generálni, ha a Request settings fülön nem jól adod meg az adatokat a User goupban.  Vagy be van klikkelve a Force CRC32  checkbox a főoldalon.

**Comment by renced42** [comment]
> Már sokszor és több helyen leírták, hogy:
> SHA2-512 helyett SHA-512
> <common:passwordHash cryptoType="SHA-512">'+passwordHash_+'</common:passwordHash>
> Minden kérésben így kell.

Ez a hiba már a passwordhash ellenörzése után jön.

**Comment by wolfram265** [comment]
> 
> 
> Kedves @wolfram265
> A Test Tool akkor tud ilyen hibát generálni, ha a Request settings fülön nem jól adod meg az adatokat a User goupban. Vagy be van klikkelve a Force CRC32 checkbox a főoldalon.

Talált, süllyedt, rossz aláírókulcs volt megadva. :+1: 
Egy kiegészítő "Check your login credentials" hibaüzenet elég sokat segítene egy ilyen helyzetben.

**Comment by renced42** [comment]
> Egy kiegészítő "Check your login credentials" hibaüzenet elég sokat segítene egy ilyen helyzetben.

Kedves  @wolfram265 a login credentials féle hibákra  vannk az invalid seurity user és társai :) 
A requestsignature hiba más hibacsoportot képvisel :)
