### ISSUE TITLE
[Q&A] EU-s HÉA-t tartalmazó számla beküldése

### ISSUE THREAD

**Issue by millsanthony** [nav-gov-hu/Online-Invoice#643]
Egy EU tagállamban lévő ügyfél számára állítok ki számlát, amely tartalmazza az EU tagállamban alkalmazandó adókulcsnak (HÉA) megfelelő EU-s adóértéket (pl. egy digitális szolgáltatásról szóló B2C számlát állítok ki, ahol a példában legyen a szolgáltatás helye a vevő letelepedési helye szerinti EU tagállam).
Ebben az esetben a számlán szerepel adó (külföldi adó - HÉA), de magyar ÁFA nem szerepel rajta. 

Az alábbiak szerinti számla tartalom és NAV Online adatszolgáltatás megfelelő?:

A számla tartalma ez lenne:
Nettó 230 HUF
Adó: DE 19%: 43,7 HUF (mondjuk egy német adókulcs szerinti HÉA)
Bruttó: 273,7 HUF

A NAV Online-on beküldendő ez lenne:
Nettó 230 HUF
ÁFA: - (Out of scope: EUE Másik tagállamban teljesített, nem fordítottan adózó ügylet)
Bruttó: 230 HUF

Ez így rendben van?

**Comment by nbeeps2** [comment]
Véleményem szerint a vatPercentage az nem a magyar ÁFA %-át kell, hogy jelentse az adatszolgáltatásban, hanem a számla ÁFA %-ot, ami a példa alapján 19%. Számomra igen furcsa lenne, hogy a számlán van 19% ÁFA, de az adatszolgáltatásban meg nincs. Másodlagos dolog ehhez képest, hogy mint bejövő számla értelmezhetetlen lenne, mert honnan lehetne kitalálni a 19%-ot?

**Comment by AronSzigetvari** [comment]
@millsanthony 
A számlán feltüntetett adatokat kell beküldeni (kivéve a nem adóalany magánszemély vásárló személyes adatait), tehát ha német áfa van rajta, akkor a német áfával együtt kell beküldeni véleményem szerint, és főleg nem szabad olyat csinálni, hogy áfát teszünk a számlára a papír számlán, de áfamentesként küldjük be a NAV-nak. 
Viszont ez is fontos:
„1. Az adóalany köteles adatot szolgáltatni az adó- és vámhatóság részére azon általa teljesített
termékértékesítésekről, szolgáltatásnyújtásokról kibocsátott vagy kiállított számláról, számlával egy
tekintet alá eső okiratról, amelyre e törvény rendelkezéseit kell alkalmazni a 158/A. § értelmében,
**kivéve azon szolgáltatásnyújtásról, melynek teljesítési helye a Közösség másik tagállama, és amely
tekintetében az adóalany adófizetési kötelezettségének az Art. távolról is nyújtható szolgáltatásokat
nyújtó adózókra vonatkozó különös szabályai szerint tesz eleget**"
Márpedig a kiemelt rész pont a távolról nyújtott szolgáltatásokról szól, és azért van rajta német ÁFA, mert a teljesítés helye ilyenkor Németország.
Tehát ezek a számlák pont nem is esnek a riportálandó körbe.

**Comment by NTCA-tax** [comment]
Egyetértek @AronSzigetvari azon megállapításával, hogy ezen számlákról nem kell és egyébként nem is lehet adatot szolgáltatni. Az adatszolgáltatásnál kizárólag a magyar adókulcsok adhatóak meg. Amennyiben 19%-os adókulccsal próbálnál adatot szolgáltatni, akkor error-t kapnál mindaddig, amíg a magyar áfa törvényben nem kerülne bevezetésre a 19%-os adómérték...

**Comment by millsanthony** [comment]
Köszönöm a válaszokat.
