### ISSUE TITLE
[DEV support] Online Invoice Test Tool ManageInvoice SCHEMA_VIOLATION

### ISSUE THREAD

**Issue by wolfram265** [nav-gov-hu/Online-Invoice#644]
Invoice teszt programot használva:
Sikeres token exchange kérés után, a gyári manageInvoice.xml-el generált (basic xml) ManageInvoice kérésben az 'exchangeToken' mező üresen marad, ennek megfelelően a kérés az alábbi hibákat dobja:

<validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
    <message>Request body contains on line: [26] and column: [19] error: [cvc-pattern-valid: Value '
  ' is not facet-valid with respect to pattern '.*[^\s].*' for type 'SimpleText50NotBlankType'.]</message>
  </ns2:technicalValidationMessages>

<validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
    <message>Request body contains on line: [26] and column: [19] error: [cvc-type.3.1.3: The value '
  ' of element 'exchangeToken' is not valid.]</message>

A log ablakban nem látható hibajelzés a generálás, küldés során.

**Comment by renced42** [comment]
Kedves @wolfram265 

Nem teljesen értem az első mondatodat. A Tool önmagában minden kérést legenerál, a szükséges értékeket vissza fejti, beteszi a megfeleő struktúrába. A tokent két dolog miatt nem töltheti ki, ha az Exchangekey (Cserekulcs) amit megadtál hibás, vagy a token kérés nem volt mégsem sikeres (vagy nem küldted el vagy rossz url van beállítva). A logoláshoz érdemes beklikkelni a "Log to file" opciót.

**Comment by wolfram265** [comment]
> 
> 
> Kedves @wolfram265
> 
> Nem teljesen értem az első mondatodat. A Tool önmagában minden kérést legenerál, a szükséges értékeket vissza fejti, beteszi a megfeleő struktúrába. A tokent két dolog miatt nem töltheti ki, ha az Exchangekey (Cserekulcs) amit megadtál hibás, vagy a token kérés nem volt mégsem sikeres (vagy nem küldted el vagy rossz url van beállítva). A logoláshoz érdemes beklikkelni a "Log to file" opciót.

Megint talált, süllyedt, hibás volt az exchange key. Ideális lenne egy hibaüzenet a mező üresen hagyása helyett.

**Comment by renced42** [comment]
> Ideális lenne egy hibaüzenet a mező üresen hagyása helyett.

Kedves @wolfram265 Ha figyelmesen elolvasid a logot a program ebben az esetben küld hibát. Valami ilyesmit: No returned token value.
