### ISSUE TITLE
[Q&A] Mikortól kell indulni (pontosan) a V3 adatszolgáltatással

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#645]
Mivel már nem egészen két hét van hátra a V3 eddig ismert januári indulásáig, szeretnék választ kapni arra, hogy pontosan mikortól lehet illetve kell V3-nak megfelelően küldeni a számlákat.
Mivel esetünkben nem emberek, hanem gépek számláznak, azoknak mindegy, hogy ünnep van vagy sem, jan 1.-én este le fogja számlázni az esedékes tételeket. Tudni kellene, hogy ezeket milyen formában küldjük be. Vagy más szóval, mikor kell átállni V2-ről V3-ra?

**Comment by omachtandras** [comment]
2021. 01. 04-én lép életbe a törvény, onnantól kell adatot szolgáltatni az v3.0-val.

**Comment by burnyo** [comment]
Szerintem ez téves infó!. 16-án megjelent a NAV hivatalos közleménye, hogy
március végéig nem büntetnek a régi verzióért, tehát 1.-től lehet, de nem
kötelező a 3.0 használata. Érdemes ezt átolvasni:

https://nav.gov.hu/nav/ado/afa/Online_Szamla__Marciu20201216.html


omachtandras <notifications@github.com> ezt írta (időpont: 2020. dec. 20.,
V, 18:57):

**Comment by burnyo** [comment]
A szankciómentességet egyebek mellett az is indokolja, hogy a COVID-19
járvány újabb hulláma miatti korlátozások akadályozhatták az adózókat az új
szabályokra való felkészülésben.

2021. március végéig tehát még van lehetőség a számlázó programok
felkészítésére és a kiterjesztett, kötelező számlaadat-szolgáltatás
teljesítésére. Akik még kézi számlatömböt használnak, ez alatt az idő alatt
áttérhetnek a gépi számlázásra, ami megkönnyíti az adatszolgáltatást.

*2021. március 31-ig a NAV nem alkalmaz szankciót az alábbi esetekben*:

   - Ha az adatszolgáltatásra kötelezett áfaalany a számlázó programmal
   kiállított olyan számláról, amiről a 2020. július 1-jén érvényes szabályok
   szerint kötelező adatot szolgáltatni, a 2020. július 1-jétől érvényes
   szabályok szerint (vagyis 2.0-ás verziójú séma alkalmazásával) szolgáltat
   adatot.
   - Ha az áfaalany nem teljesíti a kötelező adatszolgáltatást az olyan
   számláról, amiről csak 2021. január 4-től kell adatot szolgáltatni.
   - Ha az áfaalany olyan számláról teljesít adatszolgáltatást, amiről a
   2020. július 1-jén érvényben lévő szabályok szerint nem kötelező adatot
   szolgáltatni, azonban az adatszolgáltatása nem megfelelő.

A számlakibocsátó adóalanyok közül azok, akiknek 2021. január 4. előtt nem
kellett online számlaadat-szolgáltatást teljesíteniük, kizárólag akkor
mentesülnek a szankció alól, ha legkésőbb az adatszolgáltatási
kötelezettséggel érintett első számla kiállításának napjáig regisztrálnak a
NAV Online Számla rendszerben. A fentieknek megfelelő esetekben a
szankciómentességnek nem feltétele a jelzett időszakban nem teljesített
adatszolgáltatás utólagos pótlása vagy a nem megfelelő adatszolgáltatás
utólagos korrekciója.



Imre Burnyóczki <burnyoczki.imre@gmail.com> ezt írta (időpont: 2020. dec.
20., V, 19:39):

**Comment by omachtandras** [comment]
@burnyo: 01.04-től van kötelezettség. Azt mindenki maga dönti el, hogy törvényt sért és bízik a szankció mentességben, vagy teljesíti az adatszolgáltatást az elvárt módon.
@kabelnet2 kérdése a január 1-jei számlázásra vonatkozott, akkor még nem lép hatályba a törvény, így akkor biztosan nem kell v3.0-val és a kibővült körben adatot szolgáltatni (pl. magánszemélyek számlái, ami gondolom a nevéből ítélve náluk van bőven).

**Comment by kabelnet2** [comment]
(((Ne zavarjon meg a nick, az egy régi történet. Egyszer még az Axelero korában rossz helyre írtam a kapcsolat típusát, de azóta megszoktam :) )))
Engem különben nem a **_kell_**, hanem a **_lehet_** érdekel. A program kész, szeretnék már mással foglalkozni.

**Comment by omachtandras** [comment]
Majd NTCA* megerősíti vagy cáfolja, de legutóbb már azt írták, hogy csak 01.04-től lesz az élesen aktiválva, nincs már szó arról, hogy v3.0-val küldhetőek be korábban az adatok. (De akkor is arról volt szó, hogy akkor sem lehet 01.04. előtt a kibővített körre vonatkozó számlákat beküldeni, azokat megfogja / megfogta volna a v3.0 is.)

**Comment by nbeeps2** [comment]
@kabelnet2 Január 4 előtt nem lesz éles 3.0-ás beküldés, szóval ha mindenáron előtte akarod küldeni a számlákat, akkor marad a 2.0 és kimaradnak a magánszemélyek és a külföldi cégek.

**Comment by ballonyi** [comment]
Most próbáltam élesben: "Service Unavailable" A 2.0 esetében a határidőt megelőzően meg lehetett ugrani az átállást. Persze érthető hogy a jogszabály jan 4-től hatályos, ezért előtte nem fogad be hash alapon hitelesített számlát, de a többi azért mehetne. A leírásban úgy fogalmaznak (156. oldal) hogy a completenessIndicator _"használatát legkorábban 2021. január 4-én szabad alkalmazni"_  Ezt szerintem lehet úgy érteni, hogy completenessIndicator=false értékkel viszont lehet. 
De ezek szerint nem. :(

**Comment by nbeeps2** [comment]
@ballonyi: azért írtam, hogy január 4. előtt nem lesz beküldés, mert nem lesz, mert külön írták, hogy jan. 4-el indul a V3 élesben, ami pedig azt jelenti szó szerint, hogy jan. 4. előtt hiába próbálod bárhogy nem fog menni. Szóval felesleges próbálgatnod, pláne Karácsonykor inkább csináltál volna valamit mást :)

**Comment by ballonyi** [comment]
@nbeeps2 : természetesen nem unalmamban próbáltam, hanem mert nem találkoztam sem jelen issue-val, sem az idézett "külön írták, hogy jan. 4-el indul a V3 élesben" kijelentéssel... (aminél egyébként nem írtál hivatkozást)

**Comment by renced42** [comment]
Kedves @kabelnet2 
Úgy látom, hogy az eredeti kérdésedre megkaptad a választ - vagyis 2021.01.04 00:00:00-től - kérlek zárd az Issue-t.

Köszönjük!
