### ISSUE TITLE
MISSING_HEAD_DATA_CUSTOMER WARN majd ERROR

### ISSUE THREAD

**Issue by NyBela** [nav-gov-hu/Online-Invoice#646]
Tisztelt fejlesztők!
Továbbra is fenn áll az a probléma, hogy közösségen belüli, adószám nélküli, de ÁFÁ-t megfizető vevő esetén az alábbi üzenet kerül visszaküldésre: (500e nettó +135eÁFA)
(WARN: MISSING_HEAD_DATA_CUSTOMER / Vevő adószám (első nyolc karaktere) hiányzik.)
Ez önmagában nem is lenne probléma, de a következmény már igen.
A számlázó, ha ilyen számlát helyesbít, akkor már az alábbi üzenetet kapja.
(ERROR: MODIFY_WITHOUT_MASTER_MISMATCH
A módosítás vagy érvénytelenítés olyan okiratra hivatkozik, amelyről létezik érvényes adatszolgáltatás. )
Kérdésem, mikor lesz erre megoldás?
Ez az eset vevőkörünkben teljesen hétköznapi, úgy gondolom, hogy az első munkanap már lesz ilyen.
Ami még nagyobb probléma, hogy ugyanez történik akkor is, ha Közösségen belüli, adószámmal rendelkező, ÁFÁt- megfizető vevő kapja a számlát. Ilyen eset pedig tényleg sok van. 

Várom a választ. Köszönöm.

**Comment by KMGY100** [comment]
@NyBela 
A NAV-nál van a hiba mert ez a WARN üzenet:  
"""MISSING_HEAD_DATA_CUSTOMER / Vevő adószám (első nyolc karaktere hiányzik"""
mindig jön ha:
a számlában az áfa > 100000   és nincs magyar adószám.

a NAV is tudja ezt a hibás WARN-t.

**Comment by NyBela** [comment]
Kedves KMGY100!
Mint írtam "továbbra is fenn áll a probléma". Nem az a kérdés, hogy mi a probléma, mert tudjuk, hanem az, hogy mikor lesz megoldva!

**Comment by NTCA-supporter** [comment]
Kedves @NyBela!

Köszönjük a jelzésedet! Jelenleg is még azt tudom mondani amit a [500](https://github.com/nav-gov-hu/Online-Invoice/issues/500) is van. Felülvizsgálat alatt van a 3.0 kapcsán az összes WARN készlet. Ezt is bele fogjuk venni.
