### ISSUE TITLE
[Q&A] Áll a teszt rendszer?

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#647]
Ma kb. 8:40-től nem kapok vissza feldolgozási eredményt a teszt-ből, így nem lehet láncokat próbálni (Modify), mert az előzmény számla nincs feldolgozva.
Mikor fog ismét működni?

**Comment by NTCA-supporter** [comment]
Küldj kérlek transactionId-t/requestId-t, hogy tudjam nézni a konkrét esetet.
Köszi

**Comment by NTCA-supporter** [comment]
Az elmúlt órában több ezer számla lett feldolgozva teszt környezeten, így biztosan nem áll a teszt rendszer.
A konkrét esetet nézem szívesen.
Üdv

**Comment by Macskafarka** [comment]
Kedves @NTCA-supporter  Transaction ID-k: 37LIQC06QA77IL1Z és 37LJCMPYWIBQJN00

**Comment by Macskafarka** [comment]
És is 2 óra alatt lett feldolgozva: 37LEOS49VMJ88SFY

**Comment by KMGY100** [comment]
@NTCA-supporter  !
Másoknak is beragadt több számla SAVED  állapotba (Prog.hu - n olvasható).
valszeg nem egyedi a probléma.

**Comment by NTCA-supporter** [comment]
Köszi, nézzük!
Üdv

**Comment by ZoranHeinczinger** [comment]
Sziasztok,

nekem is akad pár transaction ID-m 12:25 óta álldogálnak, megtennétek, hogy ránéztek?
 
- 37LMPTOBM01KC0D3
- 37LMPUY7SV5LGWIW
- 37LMWRN95Y8OC0C8
- 37LMQBKO7T2TVHLA
- 37LMPWVG2QVYBJV9

Előre is köszi,
Zorán

**Comment by NTCA-supporter** [comment]
Sziasztok!

Valóban van némi hátralék, de a feldolgozás folyamatos, csak lassabb mint szokott.
Nézzük és jelzek ha van érdemi változás.

Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

A hátralékok eltűntek, most mindent jónak látok.
Zárom az issuet, ha van még elakadás jelezzétek kérlek.
Köszönjük a jelzést!

Üdv
