### ISSUE TITLE
[Q&A] technikai érvénytelenítés tömeges jóváhagyása

### ISSUE THREAD

**Issue by kristofbela** [nav-gov-hu/Online-Invoice#649]
Miért kell a technikai érvénytelenitést két lépcsőben elvégezni ??
Ha szoftverből csinálok egy technikai érvénytelenítést akkor azt még meg kell erősíteni az online felületen is !
Szerintem ha érvénytelenítek egy számlát akkor mi értelme van mégegyszer megerősíteni ?
Ha az érvénytelenítés rendben lefutott a  válasz VERIFICATION_PENDING  (és utána mehetünk az online felületre ha megtaláljuk az az ember aki tudja a bejelntkezési adatokat).
Egyszerűbb lenne ha VERIFICATION_DONE lenne a válasz. Azt szeretném megtudni miért van ez így és lesz-e valami változás ?

**Comment by renced42** [comment]
Kedves @kristofbela 
Ennek biztonsági okai vannak. Leginkább az, hogy ne lehessen kontroll nélkül technikai érvénytelenítést végrehajtani, bármilyen szándékkal vagy okkal. Ebben a működésben nem tervezünk változást.

**Comment by omachtandras** [comment]
@renced42 : esetleg abban nem gondolkodtok, hogy csoportosan is lehessen megerősíteni a felületen az érvénytelenítéseket. (Elnézést, ha elavultak az információim, de tudomásom szerint egyesével kell jóváhagyni minden technikailag érvénytelenített számlával kapcsolatban az érvénytelenítést és nem láttam ezzel kapcsolatban változásra utaló írást.)

**Comment by nbeeps2** [comment]
@kristofbela : "Szerintem ha érvénytelenítek egy számlát..."
Csak egy apró kiigazítás, nehogy valaki "új" félreértse, amit itt olvas. Nem a számlát érvényteleníted, hanem az adatszolgáltatást. Ha valaki a számlát akarja érvényteleníteni, akkor nincs más dolga, mint kiállítani egy stornó számla is kész ;)

**Comment by renced42** [comment]
> esetleg abban nem gondolkodtok, hogy csoportosan is lehessen megerősíteni a felületen az érvénytelenítéseket.

Kedves @omachtandras jól látod jelenleg nincsn ilyen funkció és nincs fejlesztésbe felvéve ilyen igény. Új feature-ként fel lehet venni.

**Comment by omachtandras** [comment]
@renced42 : javaslom akkor felvenni a fejlesztendő feature-ként.
Indoklás: ha a gép-gép kapcsolaton átadott számlák adatszolgáltatásának technikai érvénytelenítésre van szükség, akkor valószínű több/sok számlát érintett, hiszen vélhetően típushiba miatt a program nem egy esetben hibáz(ott), hanem minden olyan számla esetén, ami érintett az adott adattal / üzleti logikával.
Azzal teljesen egyetértek, hogy az adózó egy képviselője tudtával/jóváhagyásával történhessen csak adatszolgáltatás technikai érvénytelenítése, azonban azt gondolom, hogy ha sok bizonylat érintett, akkor az ő kényelmét szolgálja (az egész funkció használhatóságát jelentősen javítja), ha csoportosan is jóvá tud hagyni adatszolgáltatás érvénytelenítést (akár dátum intervallum alapján, de sokkal inkább a(z érvénytelenítést kezdeményező) technikai user kódjára szűrve).

**Comment by jozanesz** [comment]
> valószínű több/sok számla érintett

Így van. Mi pl. januártól százezres nagyságrendben indítunk útnak számlát némelyik napon. Ha véletlenül ilyen gond lenne, ezek közül igen sok be lehet küldve, mire a hibát észlelik, és az adatszolgáltatás leállítását elrendelik és végrehajtják.

**Comment by NTCA-tax** [comment]
Köszönjük a felvetést az érvénytelenítések csoportos jóváhagyására. Szakmai és informatikai szempontból átbeszéljük, utána jelentkezünk.

A felhasználói jóváhagyásnak nem csupán biztonsági, hanem felelősségi okai is vannak. Így az adatszolgáltatás érvénytelenítésének kétlépcsős megoldását nem fogjuk tudni elengedni.

**Comment by NTCA-supporter** [comment]
Annyi kiegészítés, hogy egy annulment beküldésben ugyanúgy 100 érvénytelenítés lehet, mint a számla adatszolgáltatásnál, így tömegesen küldhető be az érvénytelenítés, és a 100 egyszerre hagyható jóvá, mert az 1 sor a felületen.
Üdv

**Comment by EPluribusUnum** [comment]
@NTCA-supporter , mi például nem használjuk hogy egy kérésbe több számlát teszünk be. Így x darab számla érvényesítésekor x darab jóváhagyás is kell. Ezen a gyakorlaton nem vagyunk hajlandók változtatni és kötegelni, amíg NAV számlánként büntet, addig szeparáltan vannak kezelve request szinten is a számlák. nics kötelezettség arra hogy kötegeljünk, így illene ehhez a módszerhe is támogatást adni annul oldalra.

**Comment by NTCA-supporter** [comment]
Nyilván nem kötelező, csak mint könnyítés javasoltam.
Az igényt átbeszéljük.
Üdv

**Comment by szkomaromi-contactplus** [comment]
@NTCA-tax Lett esetleg eredménye az átbeszálásnek? Várhatunk egy ilyen fejlesztést?

**Comment by NTCA-supporter** [comment]
@NTCA-tax kérlek jelezz vissza ezzel kapcsolatban.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Lesz tömeges jóváhagyás, a következő verzióban már tesztelhető lesz.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
A tömeges jóváhagyás/elutasítás már egy ideje élesen van és használható, így zárom az issuet.
Üdv
