### ISSUE TITLE
[DOC] 2.0 changelog értelmezése

### ISSUE THREAD

**Issue by vankcuf** [nav-gov-hu/Online-Invoice#65]
A CHANGELOG_2.0.md tartalmát hogyan kell értelmezni?

Ami érthető:
1.3) A requestSignature számítása a 2.0 verziótól
2.1) API sémaleíró
2.2) DATA sémaleíró
3) ÁFA analitika előkészítés

Mi a helyzet az 1.1 (Megoldani kívánt főbb problémák) és 1.2 (A tervezett megoldások) fejezetekkel? Ezeknek mennyi köze van a "valósághoz"? Vagyis mennyire csak filozófikus okfejtések és mennyire megvalósult dolgok? A megfogalmazása alapján "megoldani kívánt" és "tervezett megoldások" ezek nem valódi changelog leírások, nem egyértelmű, hogy ebből mi valósult meg és mi az, ami jelenleg is csak egy terv.

Kellene egy olyan tételes felsorolás, mint a 2.1 és 2.2 fejezetben, ahová konkrétan/tételesen le van írva, hogy mi változott, hogy ne kelljen majd végigolvasni a 2.0-ás fejlesztéshez készült több száz oldalas dokumentációt (újra).

**Comment by nbeeps2** [comment]
Lassan most már én is neki kezdenék a fejlesztésnek, de én is azzal szembesültem, hogy nincs semmi támpont. Az API és DATA séma változásokon át tudom rágni magam, de azon kívül tényleg nem tudni, hogy mi változott, csak az olvasható el, hogy mi van tervben. Jól jönne egy használható changelog.

**Comment by NTCA-developer** [comment]
Sziasztok!

Bocsánat a késői válaszért. A changelog 1.1 és 1.2-es részének csupán annyi lett volna a feladata, hogy kontextusba helyezze a változásokat és a véleményezéshez támpontul szolgáljon.

Az üzleti logika változásához néztétek már az interfész dokumentáció 5.3 pontját? Ott témakörökre szétbontva szerepelnek a változások pont azért, hogy ne kelljen a teljes dokumentációt szemmel verni.

**Comment by vankcuf** [comment]
Szuper, akkor elég átnézni az 5.3 pontot és tételesen végig menni rajta. Ezt kerestük, köszönjük!

**Comment by NTCA-developer** [comment]
Nm. Ha lesz konkrét kérdés, akkor írjatok nyugodtan, segítünk.

**Comment by magyarfejlesztovagyok** [comment]
Sziasztok, nem látom itt az 5.3-ban a lineNetAmountHuf kötelezővé válását, illetve sem a summarybyvatrate, sem a végső summary-ben történő közelető szerepeltetését. Ezt javítanátok, kérlek? Köszi előre is. (Ha csak én néztem be valamit, akkor elnézést)

**Comment by NTCA-developer** [comment]
@magyarfejlesztovagyok 

Igazad van, köszönjük szépen hogy szóltál. Mindjárt ki is teszem a javított változatot.

**Comment by NTCA-developer** [comment]
Feltettem az új változatot, köszi még egyszer! Az 5.3 fejezet változott, plusz a számlasorok közül egy feleslegesen benne maradt átváltásos bekezdést töröltem.
