### ISSUE TITLE
Bérfőzési szeszadó az adatszolgáltatásban hogyan szerepel? ÁFA besorolása áfa trv. hatályán kívüli?

### ISSUE THREAD

**Issue by szittya** [nav-gov-hu/Online-Invoice#650]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

**Comment by NTCA-tax** [comment]
Ez az Áfa törvény tárgyi hatályán kívüli tétel, ezért ATK case-el kell beküldeni. Amennyiben kizárólag erről szól a bizonylat, arról nem kell számlát kiállítani.
