### ISSUE TITLE
[Q&A] 1.9.2, 2.5 Módosító számla beküldése 5 percen túl jogszabályszerű-e?

### ISSUE THREAD

**Issue by bcdel** [nav-gov-hu/Online-Invoice#651]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

A kérdés lehet hogy nem megválaszolható, inkább csak felvetném:

OSA doksi 2.5 utolsó bekezdése szerint: ("... érdemes annak DONE státuszát megvárni a módosítás beküldése előtt ...")

Ezt hogyan lehet értelmezni az 1.9.2 fejezet "... mentésre pedig 5 perc áll rendelkezésre... " mondata és a token érvényesség 5 perces idejét tekintve? 

A kérdést jogilag és műszakilag is javasolt megvizsgálni (az 1.9-es fejezet szellemiségében)

**Comment by nbeeps2** [comment]
@bcdel : "érdemes" nem egyenlő "kötelező/kell". Ha zavar téged a "jogszabályszerűség problémája", akkor küld be a módosító számlát is azonnal (én ezt javaslom), ez viszont csak akkor lesz majd DONE, ha az előzmény számla is DONE lesz. Erre vonatkozik a leírásban az "érdemes" utalás. Azt se felejtsük el, hogy pláne üzemszünet/lassulás esetén előfordulhat, hogy akár 12-24 órába is telhet, mire az előzményszámla DONE-t kap (emiatt nem is várnák a módosító számla beküldésével), ennek fényében eltörpülni látszik, hogy egy token érvényessége csak 5 perc...

**Comment by RvPSc** [comment]
Nem jó, ha beküldöd azonnal, mert warn-t fog kapni tétel hivatkozási hibával. Pont most alakítottuk át mi is, törekedve a "lehető legjobb, minőségibb adatszolgáltatásra". Amíg nem jön vissza done, addig nem küldjük. Legkésőbb az adatszolgáltatási határidő lejárta előtt kevéssel elkezdjük beküldeni akkor is, ha az eredetit még mindig nem igazolták vissza (vállalva ezzel, hogy warn lesz).

**Comment by jozanesz** [comment]
> nem biztos, hogy warn-t kap

Tényleg nem, mert lehet, hogy errort:
`INVALID_INVOICE_REFERENCE
A módosítás vagy érvénytelenítés által hivatkozott számla nem található meg az adózó alapszámlái (ahol invoiceOperation = CREATE) között a rendszerben, és a kérésben nem jelölték, hogy a módosításhoz nem tartozik korábbi adatszolgáltatás (invoiceReference-ben a modifyWithoutMaster tag értéke false). `

**Comment by NTCA-supporter** [comment]
@NTCA-tax kérlek reagálj erre is.

**Comment by NTCA-tax** [comment]
A dokumentációban egy ajánlást olvashattok, hogyan érdemes technikailag megvalósítani az adatszolgáltatást. Az 5 perc egy token érvényességére vonatkozik, nem pedig az adatszolgáltatásra. No és valahol itt válik ketté a technika és a jogszabály. A jogszabály azt mondja, hogy a kiállítást követően azonnal meg kell történnie az adatszolgáltatásnak, amelynek automatikusnak, emberi beavatkozástól mentesnek kell lennie. Technikailag azonban lehet eltérés a számla kiállítás időpillanata és az adatszolgáltatás időpillanata között. Amennyiben ennek az időeltérésnek kizárólag technikai, műszaki magyarázata van, akkor megfelel a jogszabályi követelménynek.

**Comment by bcdel** [comment]
köszönöm a választ...
