### ISSUE TITLE
Várhatóan mikor lesz elérhető az OnlineInvoiceTool konzolos segédprogram?

### ISSUE THREAD

**Issue by szittya** [nav-gov-hu/Online-Invoice#652]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

**Comment by renced42** [comment]
Kedves @szittya 
A legújabb verzió letölthető az onlineszamla rendszer teszt oldaláról.

Grafikus segédprogram: OnlineInvoiceTool GUI v3.0.7649, Felhasználói dokumentáció (utoljára frissítve: 2020.12.16.)
https://onlineszamla-test.nav.gov.hu/api/files/container/download/OnlineInvoiceTool_installer_2020_12_10.zip

**Comment by renced42** [comment]
> Kedves @szittya
> A legújabb verzió letölthető az onlineszamla rendszer teszt oldaláról.
> 
> Grafikus segédprogram: OnlineInvoiceTool GUI v3.0.7649, Felhasználói dokumentáció (utoljára frissítve: 2020.12.16.)
> https://onlineszamla-test.nav.gov.hu/api/files/container/download/OnlineInvoiceTool_installer_2020_12_10.zip

Ebben benne van minden amire szükség van, a konzolos segédprogram is

**Comment by szittya** [comment]
Köszönöm, bár telepítve xml validálásra így még nem használható.

**Comment by renced42** [comment]
> Köszönöm, bár telepítve xml validálásra így még nem használható.

Használható, ha az XSD-be a schemalocation attributum belekerül az import tagoknál.
Lásd #556

**Comment by szittya** [comment]
Köszönöm. Így kerek.
