### ISSUE TITLE
Harmadik ország adószám nélkül [Q&A]

### ISSUE THREAD

**Issue by annaszilvasi** [nav-gov-hu/Online-Invoice#654]
Segítséget szeretnék kérni abban, hogy harmadik országbeli cég adószám nélküli számláját simán csak a <customerVatStatus>OTHER</customerVatStatus> -re lehet-e küldeni <thirdStateTaxId> nélkül? vagy valami dummy adószámot használjunk ebben az esetben?
Konkrétan USA cég, ahol nem kötelező adószámmal rendelkeznie a cégeknek.
Választ erőre is köszönöm.

**Comment by NTCA-tax** [comment]
A számlán ekkor nincs vevői adószám, adatszolgáltatásban pedig OTHER-ként kell beküldeni adószám nélkül.

**Comment by NTCA-supporter** [comment]
Van még kérdés ezzel kapcsolatban @annaszilvasi ?
Ha nincs, zárd kérlek az issuet.
Üdv
