### ISSUE TITLE
[Q&A]queryInvoiceData SCHEMA_VIOLATION

### ISSUE THREAD

**Issue by tkelemen73** [nav-gov-hu/Online-Invoice#656]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Egy december 1-én beküldött számlát próbálok lekérdezni, de /queryInvoiceData operációval 3.0-s verzióval, de csak egy INVALID_REQUEST Helytelen kérés! válasz érkezik, az alábbi hibaüzenettel:

Request body contains on line: [-1] and column: [-1] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerVatData}'. One of '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerVatStatus}' is expected.]</

A számla, amit le akarok kérdezni, az nem magánszemélyes számla, csak még az eredeti októbertől-december 12-ig élt verzióval beküldött számla. A queryInvoiceDataRequest-ben semmi olyan nincs, amiről a hibaüzenet szól, az max a válaszba becsatolandó eredeti invoice-ra vonatkozhatna.

Tranzakció azonosító: 36QYNKLIQ6DQBVZT
RequestID: ABIFNPZ7O4POXEV5IBMAQSSYCA

A számla a felületen megtalálható, le is tudom kérdezni, pl. a /queryTransactionStatus, /queryTransactionList operációkkal is, csak a /queryInvoiceData operációnál fut hibára.

**Comment by DrotosTot** [comment]
A séma változása miatt csak az új verzióval beküldött számlákat tudod visszakérni a queryInvoiceData operációval, a régiek mind hibára futnak.
#470 -es issue-t olvasd át.

**Comment by tkelemen73** [comment]
Úgy gondolom, hogy az nem helyes, ha eldobnának az alig 3 hónapnyi tesztelési lehetőségből 2,5 hónapnyi tesztadatot...

**Comment by NTCA-supporter** [comment]
Sziasztok!
Megoldjuk, hogy átforgassuk az adatokat a tesztrendszeren az új sémának megfelelő állapotra.
Jelzek ha ez megtörtént.
Üdv

**Comment by NTCA-supporter** [comment]
@tkelemen73 megpróbálod újra?
Köszi

**Comment by tkelemen73** [comment]
Nekem jónak tűnik. Megfeleltettétek a megszűnt és új tag-eket egymásnak. Szerintem ok.

**Comment by tothtms** [comment]
Üdv!
Ugyan ilyen hibát kapok. Ezt a számlát már nem is fogom tudni visszanyerni? Vagy rá valamilyen megoldás?
```
requestId = "RID062700300165591752397252"
timestamp = "2022-06-22T17:05:23.627Z"
requestVersion = "3.0"
headerVersion = "1.0"
```

`
Request body contains on line: [-1] and column: [-1] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/2.0/data":invoiceDetail}'. One of '{"http://schemas.nav.gov.hu/OSA/2.0/data":supplierInfo}' is expected.]`[2]

**Comment by tothtms** [comment]
Szia @NTCA-supporter!
Igen pár infó lemaradt. Ma indítottam egy új kérést az éles rendszerre
 
```
requestXml:
rootName QueryInvoiceDataRequest
baseUrl https://api.onlineszamla.nav.gov.hu/invoiceService/v3
requestId RID081551800165597391153718
timestamp 2022-06-23T08:45:11.816Z
```

**Comment by NTCA-supporter** [comment]
Szia!
Éles rendszert itt nem támogatunk, arra használd ezt kérlek: https://nav.gov.hu/ugyfeliranytu/keressen_minket/levelkuldes/e-ugyfsz
Ha tudod tesztrendszeren reprodukálni akkor megnézzük szívesen.
Üdv

**Comment by tothtms** [comment]
Szia! 
Rendben, köszönöm az infot :)
