### ISSUE TITLE
Érvénytelen ÁFA törvény hátárán kívüliséget jelölő kód

### ISSUE THREAD

**Issue by wolfram265** [nav-gov-hu/Online-Invoice#657]
A https://szamlazo-test.nav.gov.hu/ oldalán adatszolgáltatásra beküldött számla "Érvénytelen ÁFA törvény hátárán kívüliséget jelölő kód" hibával megáll. Ki és mikor fogja kijavítani ezt a hibát? Az éles rendszer 5 nap múlva indul.

**Comment by NTCA-supporter** [comment]
Szia @wolfram265!

Kérlek segíts a nyomozásban. Tudnál küldeni adószámot és számlaszámot? Vagy röviden leírni, hogy milyen lépések után kapod ezt a hibát? Köszi

**Comment by wolfram265** [comment]
> 
> 
> Szia @wolfram265!
> 
> Kérlek segíts a nyomozásban. Tudnál küldeni adószámot és számlaszámot? Vagy röviden leírni, hogy milyen lépések után kapod ezt a hibát? Köszi

Szolgáltatás nyújtás harmadik országba, áfa kulcs: THK.  Megpróbáltam létrehozni egy új számlát ezekkel az adatokkal, de a THK már nem választható, lehet hogy javítottátok a hibát?

**Comment by wolfram265** [comment]
Zárom mert az új áfa kulcsokkal (HO/EUE) átmegy a számla.
