### ISSUE TITLE
INVALID_REQUEST_SIGNATURE - verzió frissítést követően

### ISSUE THREAD

**Issue by KZsuzsanna** [nav-gov-hu/Online-Invoice#658]
Kedves Mindenki!

A hétfői verzió frissítést követően folyamatos hibaüzenetekkel kűzdünk az adatszolgáltatás során.
Hibaüzenet: Exchange Token request failed / Invali_request_signature
Technikai felhasználó jelszavát azóta megváltoztattuk, de a hibát nem szüntette meg. Mi lehet az ok?

Előre is köszönöm!

Üdv.,
Koncz Zsuzsanna

**Comment by renced42** [comment]
Kedves @KZsuzsanna  az Invalid request signature nem a jelszó hibáját jelzi, így annak cseréje szükségtelen.
10 esetből 9-szer a cserekulcsot rontják el a felhasználók. Esetleg érdemes azt megnézni.

**Comment by NTCA-supporter** [comment]
Szia @KZsuzsanna !
Ez megoldódott? Ha küldesz konkrét requestId-t akkor rá tudunk nézni.
Üdv

**Comment by KZsuzsanna** [comment]
Kedves renced42 és NTCA-supporter!
Köszönöm, szerencsére a probléma 01.01-jével magától megoldódott, sajnos a 12.28-ai számlákat manuálisan kellett feltölteni a rendszer limiten túli próbálkozásainak száma miatt. És sajnos az sem derült ki, hogy mi lehetett az igazi ok, mert a kulcsok is megfelelőek voltak. Sajnos konkrét requestID-t nem tudok :(

**Comment by NTCA-supporter** [comment]
Rendben. Az issuet zárom, ha van még kérdés nyisd újra kérlek.
Üdv
