### ISSUE TITLE
[Q&A] v2 v3 mennyire független egymástól?

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#659]
A kérdésem arra vonatkozik, hogy ha majd 2021. január 4-től elindul a v3 API és mondjuk lassulás áll be valamiért, az párhuzamosan érinti a v2-t is? Tehát a teljesítményt tekintve mennyire függ egymástól a v2, v3 API? Ugyanez a kérdés vonatkozik a karbantartásra is akár.

**Comment by NTCA-supporter** [comment]
Szia @nbeeps2 !

A két alkalmazásverzió egymástól függetlenül fut viszont ugyanabban a környezetben. A lassulás okától függ, hogy globális vagy csak az adott verziót érinti. A karbantartás esetén ha leállás van, akkor az általában az adatbázisváltozások miatt vannak, ezért jellemzően ilyenkor mindkét verzió leállításra kerül majd.

Üdv

**Comment by NTCA-supporter** [comment]
Kérlek zárd az issuet, ha nincs további kérdés.
Üdv
