### ISSUE TITLE
Több számlát módosító okirat

### ISSUE THREAD

**Issue by skovacs70** [nav-gov-hu/Online-Invoice#66]
Kérdésem a következő lenne:

A changelog_2.0 -ban az van, hogy az 'egyes' adatszolgáltatás nem változik, de több számlát módosító okiratok beküldéséhez muszáj lefejleszteni a kötegelt (batchInvoice-os) működést, vagy azokat továbbra is lehet a korábbi módon (1.1-s verzió szerint), azaz több számlára „szétszedve”, ^ -os bizonylatszámmal beküldeni?

Köszönöm.

**Comment by Amn3s1a2018** [comment]
Szia,
úgy értelmeztem, hogy a batchInvoice egyik célja kifejezetten a ^ leváltása. Vagyis a jövőben ez eltűnik. Az előző verzióváltás alapján a már beküldött számlák maradnak ahogy vannak, (^-vel 1.1-es verziószámmal) a 2.0-ban pedig a batchInvoice az egyik lehetőség a másik pedig, hogy nem állítasz ki olyan számlát amit így kellene küldeni (külön helyesbítesz minden darabot). Nyilván kapsz majd rendes választ is az illetékestől, ill ha félreérthető akkor a doksit is javítják idővel, de addig is érdemes itt olvasgatni:
https://github.com/nav-gov-hu/Online-Invoice/issues/3

**Comment by skovacs70** [comment]
Szia,
Köszönöm a választ.
A linkelt szálat követtük, de ez a ^ leváltása nem egyértelmű a doksiban.
Persze, készülünk, hogy csak a batchinvoice lesz, de jó lenne, ha ez ki is lenne mondva (írva).

**Comment by NTCA-developer** [comment]
Sziasztok!

Én is ugyanúgy értelmezem a kérdést mint @Amn3s1a2018 , szerintem a caretezés (^) elhagyását implicit kimondja az interfész dokumentáció amikor azt írja, hogy: 
> "Amennyiben egy módosító okirattal több korábbi számla kerül módosításra, úgy kizárólag ebben az esetben az adatszolgáltatási XML-ben képezhető a batchInvoice csomópont". 

Technikailag nyilván meg fogjátok tudni tenni a 2.0-ban is, hogy ezeket a számlákat caretes számlaszámmal jelentitek, de ezzel mostantól csak a saját életeteket fogjátok nehezíteni (meg a vevőkét) akik le akarják az adatokat kérdezni.

**Comment by skovacs70** [comment]
Szia, 
Köszönöm a választ. Akkor zárható is a kérdés.

**Comment by NTCA-developer** [comment]
@skovacs70 
Oké, mi is köszönjük!
