### ISSUE TITLE
[Q&A] Hibás WARN?

### ISSUE THREAD

**Issue by macokkk** [nav-gov-hu/Online-Invoice#661]
Újabban már másodszor kapja a programunk egyik felhasználója ezt a hibát egy érvénytelenítő(módosító) küldésekor (éles 2.0):
DONE       B: <vRC>WARN</vRC><validationErrorCode>INCORRECT_LINE_REFERENCE</validationErrorCode><message>A módosító számla hivatkozott tételsora nem szerepel a tárolt számlában, vagy annak utolsó módosításában.
Az eredeti (hivatkozott) egysoros számla NAV-tól lekért beküldött xml-jének sorai:

            <invoiceLines>
                <line>
                    <lineNumber>1</lineNumber>
                    <advanceIndicator>false</advanceIndicator>
                    <lineExpressionIndicator>true</lineExpressionIndicator>
                    <lineDescription>INGATLAN ÉRTÉKBECSLÉS</lineDescription>
                    <quantity>1</quantity>
                    <unitOfMeasure>PIECE</unitOfMeasure>
                    <unitPrice>1500</unitPrice>
                    <unitPriceHUF>531720</unitPriceHUF>
                    <lineAmountsNormal>
                        <lineNetAmountData>
                            <lineNetAmount>1500</lineNetAmount>
                            <lineNetAmountHUF>531720</lineNetAmountHUF>
                        </lineNetAmountData>
                        <lineVatRate>
                            <vatPercentage>0.27</vatPercentage>
                        </lineVatRate>
                    </lineAmountsNormal>
                </line>
            </invoiceLines>

az érvénytelenítő számla NAV-tól lekért beküldött sorai:

            <invoiceLines>
                <line>
                    <lineNumber>1</lineNumber>
                    <lineModificationReference>
                        <lineNumberReference>1</lineNumberReference>
                        <lineOperation>MODIFY</lineOperation>
                    </lineModificationReference>
                    <advanceIndicator>false</advanceIndicator>
                    <lineExpressionIndicator>true</lineExpressionIndicator>
                    <lineDescription>INGATLAN ÉRTÉKBECSLÉS</lineDescription>
                    <quantity>-1</quantity>
                    <unitOfMeasure>PIECE</unitOfMeasure>
                    <unitPrice>1500</unitPrice>
                    <unitPriceHUF>531720</unitPriceHUF>
                    <lineAmountsNormal>
                        <lineNetAmountData>
                            <lineNetAmount>-1500</lineNetAmount>
                            <lineNetAmountHUF>-531720</lineNetAmountHUF>
                        </lineNetAmountData>
                        <lineVatRate>
                            <vatPercentage>0.27</vatPercentage>
                        </lineVatRate>
                    </lineAmountsNormal>
                </line>
            </invoiceLines>

A pontosan ugyanígy már évek óta beküldött sok száz érvénytelenítő nem kapja ezt a WARN-t.
Kiállító adószáma: 10940828
Eredeti számla száma: 2020/1108
Érvényteenítő száma: 2020/1157

Jól látom, hogy ez a NAV oldalon levő hiba, vagy én nézek el valamit?

**Comment by NTCA-supporter** [comment]
Szia @macokkk !
Valóban fals riasztás, így figyelmen kívül hagyhatod ezt a WARN-t.
Javítani fogjuk, hogy az új beküldéseknél már ne kapj ilyen üzenetet, addig maradjon nyitva az issue.

Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

A javítás kint van élesen, zárom az issuet. (A korábban beküldött és fals WARN-t kapott számlával nincs teendő.)

Üdv
