### ISSUE TITLE
MISSING_HEAD_DATA_CUSTOMER  (még mindig jön a hibás WARN)

### ISSUE THREAD

**Issue by KMGY100** [nav-gov-hu/Online-Invoice#662]
Még mindig jön a tesztben a WARN üzenet (Vevő adószám (első nyolc karaktere) hiányzik)  amikor
olyan számlát állítunk ki **_melyben az áfa tartalom > 100000    és nincs magyar adószám,_**
a vevő akár magánszemély, akár külföldi vevő, akár adószám nélküli magyar nem magánszemély.....

Az élesben is ott fog maradni ?

**Comment by DrotosTot** [comment]
Éjfél után kiderül. :-)
Komolyra fordítva, minket is érdekelne a válasz.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Az összes ilyen jellegű issueban leírtuk már, hogy  ezt figyelmen kívül lehet hagyni, így most is leírom :) 
Fogjuk jelezni az összes fórumon, ha frissül a WARN működés. Ezt ne a napokban várjátok, pontos időpontot nem tudok.

Üdv
