### ISSUE TITLE
[DOC]Régiek a hibaüzenet-file-ok

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#663]
A letölthető file-ok között található, a hibaüzeneteket tartalmazó file régi, szeptemberi, nem tartalmazza az összes hibaüzenetet - vagy másképp megfogalmazva: honnan lehet letölteni egy aktuális hibaüzenet file-t?
Egy példa: a validations_en_public.properties-ben nincs benne a INVOICE_COMPLETENESS_MERGED_ITEM_INDICATOR_MISMATCH
hibaüzenet.
Most bevezetéskor kellene egy teljes, aktuális lista. Köszi!

**Comment by NTCA-supporter** [comment]
Köszi a jelzést, hamarosan frissíteni fogjuk a szövegfájlokat is.

**Comment by NTCA-supporter** [comment]
Frissítettem, köszi a türelmet.
Üdv
