### ISSUE TITLE
[Q&A] queryInvoiceChainDigest hiba?

### ISSUE THREAD

**Issue by adAAM91** [nav-gov-hu/Online-Invoice#664]
Sziasztok!

Röviden: 2 külön számlázót használunk így mindig lekérdezzük a modifyIndexet stb. módosító szla felküldése előtt.

3.0 ra állásnál döbbenten vettük észre, hogy december 21-22 van néhány bizonylatunk amire nem ad választ a queryInvoiceChainDigest, pedig az queryInvoiceData ad rá választ (konkrét számlaszámra kérdezünk rá minden esetben). 
A kérdés, az hogy a queryInvoiceChainDigest miért nem lát rá azóta sem?

példa szla ha érdekes: 37K20OL2QPBW2XEX (éles api)

Köszi előre is a választ!

**Comment by NTCA-supporter** [comment]
Szia @adAAM91!

Kérlek küld el a lekérdezés requestId-ját, hogy tudjak kérni logokat.

Üdv

**Comment by EPluribusUnum** [comment]
@adAAM91 , @NTCA-supporter , nem lehet hogy nálad is a https://github.com/nav-gov-hu/Online-Invoice/issues/611 eset van?

**Comment by adAAM91** [comment]
@NTCA-supporter 

A fenti számlára vontakozóan (pár percel ezelőtti requestId-k):

**queryInvoiceChainDigest: RIDGt2Xf6Ss7Nb8 (válasz semmi)**
queryInvoiceData: RIDBp9Ak8Tu4Mn0 (válasz rendben)

@EPluribusUnum nincs invoiceChainElement csak ennyi:

`<invoiceChainDigestResult><currentPage>1</currentPage><availablePage>0</availablePage></invoiceChainDigestResult</QueryInvoiceChainDigestResponse>
`

**Comment by NTCA-supporter** [comment]
@adAAM91 nálunk van a hiba a dec 15-22. között beküldött számláknál.
Pótolni fogjuk, hogy ezek a számlák is lekérdezhetőek legyenek.
Addig maradjon nyitva az issue.
Üdv

**Comment by NTCA-supporter** [comment]
Javítva lett.
Kérlek ellenőrizd és zárd az issuet, ha rendben találod.
Üdv

**Comment by adAAM91** [comment]
@NTCA-supporter Igen, most már lekérdezhető, remélem az okozója is időközben felderítésre került, mert nagyon sokan csak a InvoiceChainDigest -re tudunk támaszkodni. Köszönöm a javítást!
