### ISSUE TITLE
[DEV support] invalid request signature for manageinvoice request

### ISSUE THREAD

**Issue by andrew-azarov** [nav-gov-hu/Online-Invoice#665]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[x] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
8PVCR8dd3rHoNzRyLWslxtMgHp7cSv
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**

Receiving the following error on invoice request. I've checked and rechecked the value of requestsignature and everything is correct. Using python 3.7 3.8 to connect and perform operations.

`<ns2:GeneralErrorResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">      
  <header>
    <requestId>8PVCR8dd3rHoNzRyLWslxtMgHp7cSv</requestId>
    <timestamp>2021-01-04T02:52:01.566Z</timestamp>
    <requestVersion>3.0</requestVersion>
    <headerVersion>1.0</headerVersion>
  </header>
  <result>
    <funcCode>ERROR</funcCode>
    <errorCode>INVALID_REQUEST_SIGNATURE</errorCode>
    <message>&#201;rv&#233;nytelen k&#233;r&#233;s al&#225;&#237;r&#225;s!</message>
  </result>
  <ns2:software>
    ...
  </ns2:software>
</ns2:GeneralErrorResponse>`

*Egyéb tartalom / Additional content*
This we got from test environment, live provides similar errors so we can't report data at the moment.
Other requests, namely tokenExchange and queryTaxPayer work without issues.
But the most important is manageInvoice..
What already tried:
- normalising invoice data to php version of base64 (the one with latin-7 truncation).
- disabling compression
- just sending one invoice
- doing manual recalculations
- comparing to php (1-to-1 exact value)

What am I missing?

**Comment by NTCA-supporter** [comment]
Hi @andrew-azarov !

I checked the request you mentioned and I can see the following in the log:
"Invalid request signature, actual:[AB3AE915146D384F2C9ED59F10168A50B3F935DF5969E40046DDFABE20656E73114232DCD5C33D8DB857F9F0149084A92379B72B271DE6BA8319A43E3700817A], expected:[FA38ABB11A782839166AFB21E9854CDE86A8594A2E67B3F883A6C6A47A8094375A89FA88D6701EF3BEE9358DFAB71A83987511A7980146B169458E5831BAA124]"

I hope this could help you. If not please check the steps manually again.

Br

**Comment by andrew-azarov** [comment]
Dear NTCA-supporter,

Thank you! Better not work at night.
internal xml is stored as utf8 string, converting to bytes and encoding back added an \n to the signature, however the base64 sent had no additional line feed this resulted in difference.

Also got another error - INVALID_REQUEST, SCHEMA_VIOLATION
python base64 adds newline by default every 64 characters, php doesn't discard them on base64decode (spec specifies that the handling of any other characters is per implementation). Using alternative encoder (called b64encode) helped to alleviate the problem. Maybe this will help someone.

I think due to malleability of base64 spec this should be specified in Documentation that the base64 should be a single long string without line breaks of any kind. I see Java will most likely have similar issues.

P.S.: Would be great to have a true REST interface though to just send bytes instead of embedded b64 (which is a bit lousy in implementations). The Documentation mentions REST interface but we got non-standard SOAP-alike.,.
