### ISSUE TITLE
[Q&A] Onlineszámla rendszer aktuális verziója 3.0 telepítése sikeres?

### ISSUE THREAD

**Issue by Amn3s1a2018** [nav-gov-hu/Online-Invoice#666]
A hírekben előrejelzett karbantartáshoz érkezett egy update,
_UPDATE : A karbantartás 2021. január 4-án 00:00 órakor befejeződött._

A hivatkozott https://onlineszamla.nav.gov.hu/informatikai_valtozasok oldalon azonban azt látom, hogy továbbra is a 2020-ban telepített 2-es verziók vannak az éles rendszeren. (Ellentétben a teszt rendszerrel, ahol már decemberben megérkeztek a 3-as verziók)

**Comment by renced42** [comment]
Kedves @Amn3s1a2018 

Igen, átálltunk. Hamarosan frissülni fog az infó az oldalon.

**Comment by zonehun** [comment]
@Amn3s1a2018 ilyen pontos még soha nem volt a NAV 0:01-kor elindult a rendszer. Ekkor a v3-as séma szerint beküldtünk egy éles számlát, amire annak rendje és módja szerint meg is jött a válasz.

Tehát a v3 jelenleg működik és elérhető.
