### ISSUE TITLE
MISSING_CUSTOMER_DOMESTIC_TAXNUMBER hibaüzenet külföldi vevőnél

### ISSUE THREAD

**Issue by dupplak** [nav-gov-hu/Online-Invoice#667]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Üdv,
A 3.0 éles indulása óta a külföldi vevőknek kiállított számlák MISSING_CUSTOMER_DOMESTIC_TAXNUMBER hibaüzenettel el vannak utasítva. A customerinfo tag-ban egyértelműen látszik, hogy külföldi a vevő. Meg tudnátok nézni, hogy mi lehet a hiba?

Ez a customerInfo tartalma:
```
<customerInfo>
<customerVatStatus>OTHER</customerVatStatus>
<customerVatData>
<communityVatNumber>BG202742205</communityVatNumber>
</customerVatData>
<customerName>MAKS DELIVERI EOOD </customerName>
<customerAddress>
<ns2:simpleAddress>
<ns2:countryCode>BG</ns2:countryCode>
<ns2:postalCode>1606</ns2:postalCode>
<ns2:city>Sofia</ns2:city>
<ns2:additionalAddressDetail>Liulin Planina N21A, app. 3</ns2:additionalAddressDetail>
</ns2:simpleAddress>
</customerAddress>
</customerInfo>
```

A hibaüzenet:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><QueryTransactionStatusResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data"><header><requestId>bea0d77fbae79096442ea45d1a1348</requestId><timestamp>2021-01-04T09:26:01.000Z</timestamp><requestVersion>3.0</requestVersion><headerVersion>1.0</headerVersion></header><result><funcCode>OK</funcCode></result><software><softwareId>HU14xxxxxxxSYM00001</softwareId><softwareName>xyz</softwareName><softwareOperation>ONLINE_SERVICE</softwareOperation><softwareMainVersion>1.3</softwareMainVersion><softwareDevName>xyz</softwareDevName><softwareDevContact>info@xyz.com</softwareDevContact><softwareDevCountryCode>HU</softwareDevCountryCode><softwareDevTaxNumber>14xxxxxx-2-10</softwareDevTaxNumber></software><processingResults><processingResult><index>1</index><invoiceStatus>ABORTED</invoiceStatus><businessValidationMessages><validationResultCode>ERROR</validationResultCode><validationErrorCode>MISSING_CUSTOMER_DOMESTIC_TAXNUMBER</validationErrorCode><message>Vevő belföldi adószám hiányzik.</message><pointer><tag>InvoiceData/invoiceMain/invoice/invoiceHead/customerInfo/customerVatStatus</tag></pointer></businessValidationMessages><compressedContentIndicator>false</compressedContentIndicator></processingResult><originalRequestVersion>3.0</originalRequestVersion></processingResults></QueryTransactionStatusResponse>`

Köszönöm!

**Comment by NTCA-supporter** [comment]
Szia @dupplak !

Kérlek próbáld meg a tesztrendszerbe is beküldeni az ilyen jellegű számládat, hogy nézhessük. Az éles rendszert itt nem supportáljuk.

Első tippre azt mondanám, hogy azért kapod a hibát, mert a tételek között van olyan, ami belföldi fordított adózású, azaz vatDomesticReverseCharge = true.

Üdv

**Comment by dupplak** [comment]
Igen ez volt, köszönöm!

**Comment by KMGY100** [comment]
Másik:
#662  MISSING_HEAD_DATA_CUSTOMER (még mindig jön a hibás WARN)
a 3.0 tesztben.
Az 3.0 élesben is ?
Válaszoljatok, legyetek szívesek.
