### ISSUE TITLE
[Q&A] invoiceDigest - EU-s vevő számlájának lekérése

### ISSUE THREAD

**Issue by lukacsb** [nav-gov-hu/Online-Invoice#668]
sziasztok,

invoiceDigest-el szeretnénk lekérdezni az általunk beküldött kimenő számlákat, úgy, hogy a kérésben paraméternél megadjuk a vevő adószámát.
Ez egy magyar adóalany esetén rendben működik, de egy EU-s vevő esetén nem megy, mert az additionalQueryParams/taxNumber csak számokat fogad el ([0-9]{8}), így egy országkóddal kezdődő EU-s adószámot nem tudunk megadni.
Mi a megoldás? Mi nem vettünk észre valamit?

Köszi,

Balázs

**Comment by NTCA-supporter** [comment]
Szia @lukacsb !
Az adószám szűrés csak a magyar adószámra vonatkozik (ahogy tapasztalod is). Külföldi adószámra szűkítésre nem volt eddig igény, így nem foglalkoztunk vele a 3.0 kapcsán sem. 
Üdv

**Comment by lukacsb** [comment]
Szia,

Nálunk lenne rá igény, bár a mi szoftverünkben sem tömegesen.
Akkor használjuk a lekérdezés funkciót az általunk kiállított számlákra, amikor az ügyfél újonnan kezdi el használni a vállaltirányítási rendszerünket, és módosítani akar egy olyan számlát, amit nem a mi rendszerünkből állított ki. Ilyenkor lekérdezzük a NAV-tól az általunk kiállított számlákat, a szűrésben a bizonylatszámot és a vevő adószámát adjuk meg, ha nincs találat, akkor nem jó számlaszámot írt be.

Várható ennek a lekérdezésnek a bővítése?

Mert ha nem, akkor nekünk kell átalakítani a programot, hogy csak a számlaszámra szűrünk lekéréskor, és a visszakapott számlaadatokban vizsgáljuk meg, hogy a vevő adószáma egyezik-e azzal, akinek az új módosító számlát ki akarjuk állítani...

Köszi

**Comment by NTCA-supporter** [comment]
Szia @lukacsb !

Mivel már lezárult a 3.0 tesztelési szakasz, és élesen van, így nem tervezünk sémamódosítást.
Az issuet zárom, további kérdés esetén nyisd újra kérlek.

Üdv
