### ISSUE TITLE
Eltérő séma a ManageInvoiceResponse és QueryTransactionStatusResponse xml válaszokban[Q&A]

### ISSUE THREAD

**Issue by istaban** [nav-gov-hu/Online-Invoice#669]
Üdvözlet!
  
Látszólag a **ns2** namespace cserélődik fel a fenti két válaszban. 

Első változat:
  

`<ns2:ManageInvoiceResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">`

`<ns2:transactionId>37URW671JLUICCH4</ns2:transactionId> `

Második változat: 

`<ManageInvoiceResponse xmlns="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns2="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">`

`<transactionId>37W7C0HXQWJTE2IU</transactionId>`

A kérdés, hogy ez hiba lehetett vagy lehet rá számítani hogy a namespace módosulhat a jövőben?

Köszönöm.

**Comment by HWKF** [comment]
Szia. A namespace nem változott, csak a prefix lett másik. De soha nem ígérték, hogy a prefix állandó lesz.
Changelogból:
_Ha használsz response validációt a projektedben, akkor ha szükséges készülj fel arra, hogy az API üzleti válaszait nem minden esetben (pl token kérésnél az encodedExchangeToken, számlabeküldésnél a transactionId vagy a lekérdezéseknél a válasz adatok) a default, hanem esetlegesen más namespace alatt fogod visszakapni mint ahogy az korábban a 2.0 alatt történt. Ez a common XSD importálásának egyik következménye._

**Comment by istaban** [comment]
> Szia. A namespace nem változott, csak a prefix lett másik. De soha nem ígérték, hogy a prefix állandó lesz.
> Changelogból:
> _Ha használsz response validációt a projektedben, akkor ha szükséges készülj fel arra, hogy az API üzleti válaszait nem minden esetben (pl token kérésnél az encodedExchangeToken, számlabeküldésnél a transactionId vagy a lekérdezéseknél a válasz adatok) a default, hanem esetlegesen más namespace alatt fogod visszakapni mint ahogy az korábban a 2.0 alatt történt. Ez a common XSD importálásának egyik következménye._

Köszi a választ.

**Comment by NTCA-supporter** [comment]
Előttem megválaszolták, köszönöm!
Zárom az issuet, ha van még kérdés, kérlek nyisd újra.
Üdv
