### ISSUE TITLE
[FEATURE] LineNetAmountHUF kötelezőségének törlése

### ISSUE THREAD

**Issue by magyarfejlesztovagyok** [nav-gov-hu/Online-Invoice#67]
**Az igény összefoglalása / Summary of the request**
A 2.0 verzióban kötelezővé vált a lineNetAmountHUF (A changelogban ez a változtatás nem szerepel). Az áfatörvény szerint nem kötelező elem.
**Az általam javasolt megoldás / The solution I propose**
A lineNetAmount és árfolyam megadása így is kötelező, így indokolatlannak gondolom a lineNetAmountHUF megadását. Véleményem szerint opcionálissá kellene tenni.

**Comment by nbeeps2** [comment]
Changelog 2.0 3-as bekezdés (ÁFA analitika előkészítés):
tétel nettó összege forintban:
...
invoiceLines/line/lineAmountsNormal/lineNetAmountData/lineNetAmountHUF
....
"Az elemek kötelezősége öröklődik a sémában már korábban definiált párjukból."

Gondolom, hogy mivel a lineNetAmount kötelező volt, emiatt alakult így, hogy kötelező lett, de a felvetés jogos. Igazából, ha feladok egy árfolyamot (exchangeRate), akkor mindent fel tudna már szorozni a NAV rendszere, így felesleges duplikálni a mezőket, csak az XML mérete nő tőle.

**Comment by fzoli15** [comment]
A kötelezőségek öröklődése miatt az új elemek között van néhány olyan, ami az ÁFA tv. szerint nem kötelező, de az XSD-ben mégis kötelező lett (pl. az invoiceNetAmountHUF is ilyen).
Az összes új HUF-os elemnek opcionálisnak kellene lennie. Szerintem jelenleg nincs jogszabályi alapja annak, hogy ezek kötelezőek legyenek (de nem vagyok jogász).
Nyilván ha nem lesz kötelező, akkor a nagy többség nem fogja küldeni ezeket az adatokat, így sincs is sok értelme bevezetni ezeket az elemeket.
De mivel szerver oldalon ezeket az adatokat könnyen elő lehet(ne) állítani, ezért egyébként sem tartom szükségesnek ezeket az elemeket.

**Comment by KimmerGy** [comment]
@magyarfejlesztovagyok 
@nbeeps2 
@fzoli15 
Ne haragudjatok ! Nem tudom megállni szó nélkül.
Tényleg olyan nehéz ezeket a HUF-os adatokat megadnunk ?
Nem hiszem.

**Comment by vankcuf** [comment]
> Tényleg olyan nehéz és bonyolult ezeket a HUF-os adatokat megadnunk ?

Nem arról van szó, hogy bonyolult, csak az, hogy felesleges! Ugyanúgy, ahogy felesleges volt anno az is megcsinálni, hogy a DB-ből PIECE-t csináltunk. @nbeeps2  leírta a lényeget, az exchange rate-ből minden kiszámolható a "túloldalt", így felesleges ezzel duzzasztani az XML-t.

Szerintem nem az alapján kell elbírálni dolgokat, hogy nehéz vagy nem nehéz, hanem, hogy van-e értelme vagy nincs. Én azt mondom neked, hogy tegyél be az XML-edben egy olyat tagot, hogy <kakukk>False</kakukk>. Nehéz? Ugye nem. Van értelme? Nincs.

**Comment by KimmerGy** [comment]
@vankcuf 
Ez a párbeszéd szerintem már nem tartozik a NAV-ra, ezért kérlek menjünk át a prog.hu  -ra.

**Comment by szalaierika** [comment]
Sziasztok,
én is problémásnak látom a lineNetAmountHUF mező kötelezőségét, mert ha a vállalat nem HUF-ban vezeti a könyveit és nem HUF-ban állítja ki a számláját, akkor a számlatételek nettó értéke nem áll rendelkezésre HUF-ban. Így csak visszafelé az HUF-ban tárolt ÁFÁ-ból és adóalapból tudjuk kalkulálni. Persze az sem tételenként, hanem adókulcsonként van meg, így fel kell osztani az azonos kulcsú tételek között, ami ugye kerekítési problémákat okozhat.
Szóval szerintem ezt és minden HUF-os mezőt, kivéve a VatRateVatAmountHUF opcionálisra kellene állítani.

**Comment by KimmerGy** [comment]
@szalaierika 
Az exchangeRate (árfolyam) érték kötelező adat a számlán.
A számlatételek nettó (és minden más)  értéke egyetlen szorzás művelet.

**Comment by fzoli15** [comment]
> Tényleg olyan nehéz és bonyolult ezeket a HUF-os adatokat megadnunk ?

Nem bonyolult, csak sokkal hatékonyabb megoldás lenne, ha szerver oldalon számolná ki ezeket az adatokat a NAV, ha szüksége van rá.
Felesleges terhelni a rendszert ezeknek az adatoknak az "utaztatásával".
Emellett, ha nemzetgazdasági szempontból nézzük a dolgot: sokkal több ráfordítást (munkaórát) igényel x száz/ezer számlázóprogramba beépíteni ezt, mint ha egyetlen helyen, a szerver oldalon lenne lefejlesztve a kiszámításuk.

**Comment by szalaierika** [comment]
@KimmerGy Egy szorzás az nem sok, ez már biztos, csak ebből adódhat kerekítési differencia, ha nem a HUF-ban tárolt ÁFA-alapot osztjuk szét a tételek között.

**Comment by magyarfejlesztovagyok** [comment]
Az áfabevallás megajánlásához tehát az online számla 3.0-át tervezik majd használni? Lesz vajon mellette magyar SAF-T vagy ez fogja kiváltani?

**Comment by NTCA-developer** [comment]
Sziasztok!

Titkon reméltem, hogy elkerülhetem a "miért nem a szerver számolja ki" típusú vitába bocsátkozást, mert mi markánsan máshogy látjuk a kérdést és egy rendkívül sok időt felemésztő, meddő vita bontakozhat ki belőle. De tegyünk egy próbát.

Szerintem az első dolog amit rendbe kell tenni, hogy nem kell túlideologizálni a dolgot, ez főként egy felelősség elhatárolási, gyakorlati IT kérdés. Volt annó egy fejlesztői fórum, ahol elhangzott több ízben is, hogy a sémában lévő adatok kötelezőségének lemérésére elégtelen csak az ÁFA törvény szakaszait figyelembe venni. Technikailag több olyan adat is kötelező, amiről az ÁFA törvény nem beszél, ezért kérem hogy ezt az érvet vegyük ki a vitából. (Emlékeim szerint ennek az előadásnak az anyaga fent is van a Dokumentációk között.)

Említhetnék mindenféle fejlesztési módszertant és irányelvet, ami minden téren azt hirdeti hogy a felelősségi körök legyenek elhatárolva egymástól (és itt most nem jogi, hanem a legtisztább értelemben IT funkcionális felelősségre gondolok), ergo egy kliens-szerver kommunikációban a tranzakciós rendszernek nem dolga az, hogy találgassa a kliens által küldött adatot, de én sem ideologizálok, ha már benneteket is erre kértelek. (Az egy másik kérdés, hogy a NAV jogászibb oldalának is ugyan ez a véleménye a felelősség elhatárolásról, de ezt most egy pillanatra tegyük félre.)

A legtöbb esetben amikor ez a kérdés felmerül átsiklotok azon a tényen, hogy a rendszer vevő oldali lekérdezéseket is kiszolgál. (itt ne csak a 2.0-ás interfészes lekérdezésre gondoljatok, mert az 1.0-ban a nulladik nap óta van vevő oldali lekérdezés a frontenden) Ezer kérdést és problémát nyitna meg, ha a lekérdezett adatokban keverve lennének forrásrendszeri adatok és az általunk kiszámítottak. Ennek az útnak a végén olyan káosz van, hogy el sem akarunk kezdeni elindulni rajta, már önmagában az a kérdés, hogyan lehet egy XML-ben tagenként megjelölni, hogy melyik érték kitől származik émelyítő. 

Félreértés ne essék, a tranzakciós rendszer természetesen tesz hozzá a beküldött adatkörhöz. De ezt kizárólag csak saját, belső felhasználásra teszi, más számára ezek az adatok nem láthatók. Figyelemmel arra, hogy a lineNetAmountHUF tag nem ilyen, hanem a publikus adatmodell része, ezért a fenti érvek alapján a leghatározottabban nincs mozgástér annak vonatkozásában, hogy ezt mi tegyük hozzá a beküldött adatokhoz. A kötelezősége pedig valószínűleg adattisztasági okokból fog megmaradni, mivel a kitöltése algoritmizálható ahogy @KimmerGy is írja:

- ha van sorszintű árfolyam megadva, akkor azzal,
- ha nincs sorszintű árfolyam megadva, akkor a számlafejben lévő árfolyammal kell számolni
(ha a számlázóprogram tartja magát ahhoz, hogy forintos számla esetén a számlafejben lévő exchangeRate mindig 1, akkor még a számla pénznemét sem kell figyelni a lineNetAmountHUF képzésénél, mivel forintos számla esetén a lineNetAmount és a lineNetAmountHUF egyenlő)

Természetesen értem, hogy nektek sem ezzel a 6 sor kóddal van problémátok ami ezt megvalósítja, hanem magával az elvvel, mert ha szaporodni fognak ezek a mezők, akkor ez egy soha véget nem érő fejlesztés lehet. Fejlesztési oldalról igyekszünk mértékletesen bánni az ilyen adatokkal amikor nekünk van rá szükségünk, és igyekszünk az üzleti oldalt is ebbe az irányba terelni amikor náluk merül fel az igény. A következő verziókban (3.0-át is ideértve) nem látok már ilyen jellegű származtatott adatot egyébként.

Még nyitva hagyom egy kicsit a ticketet, hogy hozzá tudjatok szólni.

@magyarfejlesztovagyok Én nem láttam a tervek között hogy a kiajánlás használna bármit is a SAF-T-ből. De én elég alacsony szintje vagyok ennek a kérdésnek, sajnos nem vagyok hiteles forrás.

**Comment by vankcuf** [comment]
Nyilván, mi nem vagyunk tisztában a "túloldalon" miképpen is zajlanak a dolgok, de a parasztlogika azt sugallta, hogy:

1. a számlázó program beküldi az XML-t (pl. árfolyam 300, nettó érték 10, pénznem: EUR)
2. a NAV rendszere fogadja az adatot, validálja, majd elmenti magának egy saját belső adatbázisba, ahol nem xml-ek vannak, hanem mint egy rendes adatbázis, rendes táblájában mezők és értékek, és ott eltárolja a forintos értéket is: 10x300 = 3000
3. vevő oldali lekérdezés: bárki, aki lekér adatot a NAV rendszerből, az ebből az adatbázisból dolgozik, és ott már szerepel a forintos összeg, ki lehet olvasni az állományból.

Ezért nem értettük a problémát, hogy ez miért gond ott a "túloldalt". Ugyanebből indult ki a DB->PIECE kérdésköre is.

**Comment by NTCA-developer** [comment]
@vankcuf 

Rendes relációs adatbázis (is) van, ez nem akadály. A gond inkább a határvonal, a te logikád szerint is a lekérdezés már a kiegészített adatbázisból történne. És itt a baj, honnan fogja tudni a vevő, hogy a visszakapott lineNetAmountHUF:
- az amit te küldtél be
- az, amit te nem küldtél és ezért mi tettük hozzá

Ezért írtam, hogy a publikus és a zárt adatmodell között nem lehet átjárás, a kérdéses adat vagy az egyikbe tartozik, vagy a másikba.

**Comment by vankcuf** [comment]
A 10 EUR * 300 árfolyam az akkor is 3000 HUF lesz, ha a számlázó program küldi be és akkor is, ha a NAV számolja ki. Sőt, ha mindig a NAV számolja ki, mert nem lenne ilyen mező (opcionálisan sem), akkor meg eleve nem is lehetne eltérés sem ;)

**Comment by Amn3s1a2018** [comment]
Nekem is lenne egy bánatom ezzel a kérdéssel, mégpedig a kerekítés. Ugye most devizás belföldi számláról beszélünk, ahol az árak pl. euróban léteznek és a nyomtatott számlán (ok, áfatv. már nem érv, de azért mégis) forintos összeg pusztán az egy darab fizetett (visszaigényelhető) áfa van, azt jónapot. Ahogy a unitPrice és unitPriceHUF mezők nem fértek bele a 2 tizedesjegybe (mert pl. egy 17400db-os tételen csúnya kerekítési eltérések keletkeznének) a lineNetAmountHUF lévén MonetaryType pont ugyanezt okozza. Pl. 2 tételnél 1 centes lineNetAmount-tal és 330.49-es árfolyammal már megvan 1 fillér (1.51%). Persze ha benne lesz doksiban, hogy „jóazúgy”, akkor el tudom engedni. Esetleg ha definiáltok valami mindenkire kötelező görgetős kerekítő algoritmust, akkor (csendes anyázás kíséretében) ez is megcsinálható. Azthiszem amit leginkább élhetőnek tartok az a QuantityType ide is.

**Comment by nbeeps2** [comment]
> honnan fogja tudni a vevő

A vevőt egyáltalán nem érdekli, hogy honnan van az adat, hogy azt a számlázó program küldte be, vagy a NAV számolta ki. Őt max. a forintos érték érdekli, de hogy ezt ki szorozta össze, ő ezen nem fog "rezegni". Szóval, ha csak ez a baj, hogy "honnan fogja tudni a vevő", akkor ezzel szerintem nem kell foglalkoznotok.

**Comment by fzoli15** [comment]
> ... a sémában lévő adatok kötelezőségének lemérésére elégtelen csak az ÁFA törvény szakaszait figyelembe venni. Technikailag több olyan adat is kötelező, amiről az ÁFA törvény nem beszél, ezért kérem hogy ezt az érvet vegyük ki a vitából.

A jogszabály (23/2014. NGM rendelet) szerint az adatszolgáltatási kötelezettség az ÁFA tv-ben meghatározott kötelező adatokra terjed ki. A NAV csak az adatszolgáltatás módját és adatszerkezetét határozhatja meg. A NAV nem határozhat meg kénye-kedve szerint új kötelező adatokat, mert ennek (jelenleg) nem biztosított a jogi háttere. A technikai szempontból szükséges adatoknál (pl. számlatétel sorszám) persze más a helyzet, azt érthető, indokolható. De a forintos értékek kötelezővé tétele nem indokolható ilyen érvekkel. Értem, hogy az ÁFA bevallás összeállítása a hosszútávú cél, de az ehhez szükséges plusz adatok bekéréséhez egyelőre nincs jogi felhatalmazása a NAV-nak (hacsak nincs a háttérben készülőben egy jogszabály módosítás, amiről még nem tudunk).
A fentiek miatt nem, ezt az érvet nem vehetjük ki a vitából.

"13/A. § (1) A számlázó programnak a gép-gép interfész használatához szükséges azonosító adatok megküldése mellett a kiállított számla, számlával egy tekintet alá eső okirat **legalább Áfa tv. szerinti kötelező adattartalmát** a számla, számlával egy tekintet alá eső okirat kiállításakor azonnal, XML-formátumban, az **állami adó- és vámhatóság közleményében meghatározott módon és adatszerkezetben**, elektronikus úton továbbítania kell az állami adó- és vámhatóság részére."


A másik dolog:
> A legtöbb esetben amikor ez a kérdés felmerül átsiklotok azon a tényen, hogy a rendszer vevő oldali lekérdezéseket is kiszolgál. (itt ne csak a 2.0-ás interfészes lekérdezésre gondoljatok, mert az 1.0-ban a nulladik nap óta van vevő oldali lekérdezés a frontenden) Ezer kérdést és problémát nyitna meg, ha a lekérdezett adatokban keverve lennének forrásrendszeri adatok és az általunk kiszámítottak.

A vevő oldalnak nincs szüksége ezekre a forintos értékekre. Illetve ha valamilyen okból mégis szüksége van rájuk, akkor ugyanez a kérdés felmerülhet az összes nem kötelező mező esetén. Vagyis, ha a vevőnek kell ez az adat, akkor állapodjon meg a számlakibocsátóval, hogy töltse ezt az adatot is az XML-be (ugyanúgy, ahogy pl. a termékdíj adatokat vagy a VTSZ-t, cikkszámot, akármit).
A vevő oldali lekérdezés eredményében csak azokat az adatokat adja vissza a rendszer, amit a számlakibocsátó beküldött, nem kell pluszban hozzárakni NAV által számított mezőket.
