### ISSUE TITLE
[Q&A] Módosító okiratnál lineNumberReference-re milyen ellenőrzés van (az egyediségen kívül)?

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#670]
Sziasztok! BUÉK!

Egy ügyfelünk partnere olyan adatszolgáltatást hozott össze, amelynél a módosító okirat lineNumberReference mezőjében CREATE esetén bődületesen nagy számok vannak (látszólag a módosító számlaszámához hozzáfűzi a számlán belüli sorszámot (balról nullákkal feltöltve)).
`<lineNumber>1</lineNumber>
<lineModificationReference>
<lineNumberReference>20001560001</lineNumberReference>
<lineOperation>CREATE</lineOperation>
</lineModificationReference>`

Nálunk 4 byte-os integer a számlán belüli sorszám, így bukott ki, hogy 2 milliárdnál nagyobb a tétel sorszáma...
Van valami ellenőrzés arra vonatkozóan, hogy a dokumentációban elvárt folyamatos sorszámozás kikényszerítésre kerüljön?
"Az eredetiszámla módosítással érintett tételének sorszáma, (lineNumber).Új tétel létrehozása esetén az új tétel sorszáma, az eredeti számla folytatásaként."

Gondolom azért került befogadásra a dolog, mert számítotok rá, hogy "össze-vissza" érkezhetnek a módosítók és ezért nem kerül ERROR státuszba a számla, ha lyukas a sorszámozás.
Ha ez így van (nem tudom gyorsan kipróbálni, mert a mi szoftverünk csak láncolati sorrendben hajlandó átadni a módosításokat), akkor elég nehéz kitalálni bármit is a problémára, pedig jó lenne, ha számítani lehetne arra, hogy a folytonosság megvan (mi ilyenkor várjuk, hogy jönnek még a közbenső hiányzó bizonylatok...) és nem lehetne ilyen blődségeket beküldeni.

**Comment by NTCA-supporter** [comment]
Szia @omachtandras !
A következtetésed helyes, ez a kezdetektől így van.
Mindig csak egyediséget ellenőrzünk a láncon belül, de folytonosságot csak az adott számlán nézünk az invoiceLine értékek között.
Mivel a beküldési sorrend nem garantált, ezért ennyit tudunk validálni.
Üdv

**Comment by omachtandras** [comment]
@NTCA-supporter köszönöm a választ.
Elég szomorú ez így, mert akkor ebben az adatban sem lehet megbízni a kapott értékekben, megint egy út marad, a befogadó ha használni akarja az adatszolgáltatást a saját céljaira, akkor küzdjön a partnerével, hogy helyes adatokat szolgáltasson. :(

Nem lehetne esetleg legalább warninggal jutalmazni az ilyen megoldást?
"A lineNumberReference nem folytonos, ennek oka lehet, hogy hibás az adatszolgáltatás vagy a módosító okiratok nem sorrendben kerülnek átadásra."

**Comment by NTCA-supporter** [comment]
Szia @omachtandras !
Értem a problémád, de ilyen jellegű WARNt nem tervezünk, mivel jellemzően fals riasztást adna.
Eddig senki nem jelzett ilyen problémát, így gyanítom egyedi eset.
Zárom az issuet, ha van még kérdés nyisd újra kérlek.
Üdv

**Comment by omachtandras** [comment]
Ok, köszönöm.
