### ISSUE TITLE
Számlák SAVED státusban ragadtak

### ISSUE THREAD

**Issue by rtoth0407** [nav-gov-hu/Online-Invoice#671]
Sziasztok,
Teszt rendszerben több bizonylatunk SAVED státusban ragadt, már december 29 óta.
A tranzakció azonosítók:
37WXV8628WC91MDM
37WXV9HLQHFG5FDP
37WXVL60WS1CEAGJ
37WXVMID0QDQ8ZEV
37WY177P2VYL8EK8
37WYONJOS8YDZ11A
37WYOOUT2LGGNK1I
37WYOQ6Q0QK01F1N
37WYORIRBA6JQJ1S
37WYOSUUZVSDI5PP
37WZ0OQ413YFSXR1
37WZ0Q04WBY127R9
37WZ0RAF5YLF5R98
37WZ10IV7PFNAVX4
37W1THQPGZ5YPTU6
Kérem nézzétek meg ezeket!

Köszönettel
Réka

**Comment by NTCA-supporter** [comment]
Szia @rtoth0407 !
A 37WXV9HLQHFG5FDP-re néztem rá véletlenszerűen, a <vatDomesticReverseCharge/> önzáró tag okozza a gondot.
Kérlek ne ilyen formátumban küld be. hanem töltsd ki true/false értékkel.
A feldolgozás így nálunk megakad, erre természetesen adunk majd ki javítást, hogy ne akadjanak el a számlák, addig pedig tudod küldeni true értékkel.
Üdv

**Comment by rtoth0407** [comment]
Köszönöm a segítséget, javítjuk a tag töltését.
