### ISSUE TITLE
[DEV support] Csoportos adószám esetén "thirdStateTaxId" hiányolása.

### ISSUE THREAD

**Issue by lakatoskevin** [nav-gov-hu/Online-Invoice#672]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[X] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[X] 3.0

**A requestId értéke / requestId value**
```
DBWH18HOBY20201221152930
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Sziasztok! Ha a vevő csoportos adószámmal rendelkezik, akkor miért kéri tőlem a queryResponse a "thirdStateTaxId"-t? A teszt interfészbe küldtem be egy számlát még dec 21-én és a válaszban legalábbis ez volt megjelölve hibaként (token: 632e6ffd-f494-4c9b-b65f-93c444475b8837KG03ANJQPV). Minden más működik, csak ebben az esetben van gond.

*Egyéb tartalom / Additional content*
A customerVatStatus tag értékét DOMESTIC-re állítottam, szóval azért sem értem, hogy miért ez a hiba.

**Comment by NTCA-supporter** [comment]
Szia @lakatoskevin !

Kérlek futtass egy lekérdezést újra a tesztrendszeren az adott számlára, hogy lássak friss logokat.
Ennek a requestId-ját küld el. 

Köszi

**Comment by lakatoskevin** [comment]
Most olvastam a válaszodat és gyorsan futtattam egy lekérdezést magára a tranzakcióra. Remélem ez nem baj, mert abban csak egy számla volt. Ennek a lekérdezésnek a requestId-je: ZR5L9DZZPB202114142820

**Comment by lakatoskevin** [comment]
Ha esetleg meg kellene ismételni a lekérdezést akkor szóljatok! Szívesen megteszem a számlaadatra való lekérdezést is, csak vegyétek figyelembe, hogy számunkra az sosem volt releváns, így "gyorsan és azonnal" csak tranzakció-lekérdezésre tudok adni request ID-t. Én ez utóbbit preferálnám, mert lehet, hogy a végső határidő még hátra van, de itt a cégnél már szeretnénk mással foglalkozni. Köszi előre is, az esetleges félreértésekért pedig elnézést kérek!

**Comment by NTCA-supporter** [comment]
Szia @lakatoskevin !
A válaszban ez szerepel: One of '{"http://schemas.nav.gov.hu/OSA/3.0/data":customerTaxNumber, "http://schemas.nav.gov.hu/OSA/3.0/data":communityVatNumber, "http://schemas.nav.gov.hu/OSA/3.0/data":thirdStateTaxId}' is expected.

A customerVatData-n belül add meg a customerTaxNumber csomópontot, azon belül a taxpayerId-t, és azután mehet a groupMemberTaxNumber:
![image](https://user-images.githubusercontent.com/58814216/103776820-4c148e80-5030-11eb-9b1f-4f6ba09e3d80.png)

Üdv

**Comment by lakatoskevin** [comment]
Sziasztok! Le lehet zárni ezt az issue-t.
