### ISSUE TITLE
INVALID_INVOICE_REFERENCE

### ISSUE THREAD

**Issue by vivacomp** [nav-gov-hu/Online-Invoice#673]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Kedves Fejlesztők!
Élesben beküldtük az alábbi tr.kód szerinti számlákat:
383U3ULUJLNRFPRS
383U3XMAZV6OWIGJ
383U3ZYHAKQWAXHD
383U42BS1TP0A543

Majd ezeket érvénytelenítettük:
383U1QUZ80LJ50BI
383U2DK4IQPCW7OE
383U2TP547NXNG5W
383U3A1ZW0SV3NAT

Nem értjük, hogy az érvénytelenítések miért futottak hibára?

A teszt rendszerben ehhez hasonló hibákat nem kaptunk, segítsége kérünk.
Köszönjük.

**Comment by NTCA-supporter** [comment]
Szia @vivacomp !

Az éles rendszert nem tudjuk itt supportálni, csak a teszt-et.
Kérlek a hivatalos NAV helpdesknek küldj levelet.

Van 1 tippem, hogy a sztornószámla hamarabb került feldolgozásra, mint a CREATE számla, így azt még nem találtuk és ezért kaptad a hibát. Ez ugye bármikor előfordulhat az aszinkron feldolgozás miatt.
Ha újrapróbálod és már befogadjuk akkor ez volt a gond.

Üdv

**Comment by vivacomp** [comment]
Szia @NTCA-supporter 
Igazad lehet az aszinkronnal, köszönöm.
Üdv.

**Comment by NTCA-supporter** [comment]
Zárom az issuet. Nyisd újra ha van még kérdés.
Üdv
