### ISSUE TITLE
ELECTRONIC_INVOICE_HASH_EXPECTED

### ISSUE THREAD

**Issue by devid2642** [nav-gov-hu/Online-Invoice#674]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[x] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
ManageInvoice:
<requestId>DwSZUY7RTUGzMiZ+sFWdKw</requestId>

QueryTransaction:
<requestId>orSUEAaLY0CaQjkOs2EgXg</requestId>

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Kedves Fejlesztők!

A probléma 2021.01.04 én állt fent, előtte nem volt ilyen gond hasonló kérésre.
Miért kaphatok ELECTRONIC_INVOICE_HASH_EXPECTED hibát egy papír számlára?
<invoiceAppearance>PAPER</invoiceAppearance>

Köszönettel!

*Egyéb tartalom / Additional content*

**Comment by NTCA-supporter** [comment]
Szia @devid2642 !
A completenessIndicator = true értéke esetén várjuk el a hash értéket. Ha ezt false-ra állítod jó lesz.

Üdv

**Comment by devid2642** [comment]
Köszi, valóban megjavult!
