### ISSUE TITLE
[FEATURE] Too large QueryTransactionStatusResponse size for batch invoices due originalRequest node

### ISSUE THREAD

**Issue by danton-edi** [nav-gov-hu/Online-Invoice#675]
Summary of the request

One of our customers received a QueryTransactionStatusResponse which exceed 130 mb size.

The problem: when you send a batch invoice and you want to receive the original request, the originalRequest is populated in each of the processingResult of each individual invoice inside the batch invoice. If you are modifying 621 invoices, you have 621 times the complete original request.

** The solution I propose**
I propose two possible solutions:
1. When the NAV creates a processingResult element for a batch invoice, it will only populate the OriginalRequest node of the processingResult of the BatchIndex=1. The processingResult for the rest of the BatchIndex would be empty.
or
2. Change the structure of the processingResult node moving the batchIndex node inside the BusinessValidationMessages node and the technicalValidationMessages node. In this way, only one processingresult node would be generated for each batch invoice. Obviously, the processingresult would include the individual response for every batch index in a  BusinessValidationMessages/technicalValidationMessages node of this greater processingresult node.

**Acceptable alternatives**
Any which avoid to receive the original request so many times as modification invoices there are inside a batch index and, at the same time, allows us to receive the Orginal request.

**Egyéb tartalom / Additional content**

**Comment by NTCA-supporter** [comment]
Hi @danton-edi !
Thank you for the notice. The 1st suggestion we'll be developed. 
Br

**Comment by danton-edi** [comment]
Thank you!
Fixed: 1. When the NAV creates a processingResult element for a batch invoice, it will only populate the OriginalRequest node of the processingResult of the BatchIndex=1. The **OriginalRequest node** for the rest of the BatchIndex would be empty.

**Comment by NTCA-supporter** [comment]
Hi @danton-edi !
The feature will be available this week on test and prod environment.
Thanks again, I close the issue.
Br
