### ISSUE TITLE
[DEV support] queryInvoiceDigest VS communityVatNumber

### ISSUE THREAD

**Issue by csandazoltan** [nav-gov-hu/Online-Invoice#676]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[x] /queryInvoiceData
[x] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
385ME6C3UWVQ2FS7
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Az szándékos, hogy a queryInvoiceDigest nem mutatja a communityVatNumber-t?

*Egyéb tartalom / Additional content*
Azt megértem, hogy a private-person-nál nem mutat customer data-t (mondjuk azt se jelzi, hogy PRIVATE_PERSON miatt nincs ott)
Feldolgozási hiba nincs, mindent elfogad így.

(azt ne nézzük most, hogy GB-s közösségi adószám az "third state" nem "community", ezek kamu adatok,  de a rendszer befogatta a GB-s számot community-ben )

![image](https://user-images.githubusercontent.com/6756505/103640262-fa94d280-4f4f-11eb-9f2f-8eccc2938855.png)
![image](https://user-images.githubusercontent.com/6756505/103640273-0385a400-4f50-11eb-8ef9-59721e5a71e5.png)

**Comment by NTCA-supporter** [comment]
Szia @csandazoltan !

Én hirttelen a queryInvoiceDigestResponse-ban nem látok communityVanNumber mezőt, így nem értem, hogy miért hiányolod. Pontosan hova kellene töltődnie szerinted?

Köszi

**Comment by csandazoltan** [comment]
@NTCA-developer 
Azt látom én is hogy nincs, se dokumentációban, se response-ban

Akkor szándékos, hogy csak belföldi vevő adószáma látszik a digestben.
Azért hiányolom mert adok meg vevő adószámot, ok közösségi adószám, de akkor is van a vevőnek adószáma. Ez a digestben nincs benne és nincs is jelölve, hogy nincs benne, mindenképp le kell kérnem a data-t is ha ellenőrizni akarom.

Ez átmehetne fejlesztési javaslatnak akkor, hogy a digestbe kerüljön bele a "customerVatStatus", hogy ne kelljen fölöslegesen a data-t kikérni az adőszámért, ha "PRIVATE_PERSON", csak akkor ha "OTHER"
Ezzel terhelést lehetne spórolni,

**Comment by NTCA-supporter** [comment]
Szia @csandazoltan !
Mivel már lezárult a 3.0 véleményezési/tesztelési időszak, így sémamódosítást már nem tervezünk.
Zárom az issuet, ha esetlegesen lesz bármikor új sémaverzió (elvileg nem lesz), akkor elő lehet venni.

Üdv
