### ISSUE TITLE
[DOC] softwareOperation record has no description, ambigious

### ISSUE THREAD

**Issue by andrew-azarov** [nav-gov-hu/Online-Invoice#677]
**A hibás dokumentum neve / Document name containing the error**
Fájlnév vagy hostolt URL / File name or hosted URL.
https://onlineszamla.nav.gov.hu/api/files/container/download/Online%20Szamla_Interfesz%20specifik%C3%A1ci%C3%B3_EN_v3.0.pdf

**Oldalszám / Page number**
A hibát tartalmazó oldal száma / Page number containing the error.
11

**A dokumentációs hiba leírása / Description of the documentation error**
Rövid és tömör összefoglalása a hibának. / A clear and concise description of the summary of the error.
The page includes instructions on implementation of software record.
However description for softwareOperation is omitted.
It's stated as mandatory but has only 2 options:
LOCAL_SOFTWARE
ONLINE_SERVICE

What do they mean?
As I understand: ONLINE_SERVICE means something like a third party service akin to billingo, onlinenav and others. Local software is akin to kulcssoft and others.
But what do you choose when you use it on premises on your server online (web shop for example without any third party service, sending data directly to onlineszamla api)? Technically it's local software but practically an online service...

**Comment by renced42** [comment]
Dear @andrew-azarov 
Choose LOCAL_SOFTWARE if you use standalone client software what is do the rest,
Choose ONLINE_SERVICE if you use som kind of server side sollution or third party service to create and/or send datareport to NTCA.

**Comment by andrew-azarov** [comment]
Thank you, ONLINE_SERVICE it is

**Comment by jozanesz** [comment]
> Choose LOCAL_SOFTWARE if you use standalone client software what is do the rest,
> Choose ONLINE_SERVICE if you use some kind of server side sollution or third party service to create and/or send datareport to NTCA.

Ezeket lehetne magyarul is? (Az első még nyelvtanilag sem áll össze.)
Egyébként az egész szoftverügy zavaros, mert a mi esetünkben más-más cégek fejlesztik a számlázó programokat, (részben) más az xml kimenetet a számlázó programokból, és megint más az xml-eket beküldő rendszert.

**Comment by omachtandras** [comment]
@renced42 : ha nem a kliens küldi be, hanem szerver oldali alkalmazás, de az nem "valami", hanem saját fejlesztés, ugyanúgy, mint a kliensek, akkor is ONLINE_SERVICE?

**Comment by andrew-azarov** [comment]
@omachtandras bocsánat a magyarom, ahogy értettem a szerveren (pl. web shop de a saját modul-vél is) akkor ONLINE_SERVICE.

**Comment by omachtandras** [comment]
@andrew-azarov : Yes, I read this from @renced42 's post, I just don't understand the logic.
In this case, (for me) the client-side and server-side enum would have been more understandable.

**Comment by andrew-azarov** [comment]
@omachtandras I thought it's the difference between 3rd party processor and first party processor thus "local software" and "online service"...
I think this field needs an update (ie change LOCAL SOFTWARE to DESKTOP APPLICATION) or thorough documentation.

**Comment by andrew-azarov** [comment]
As a lot of people are confused I reopen the issue.

**Comment by andrew-azarov** [comment]
@szecsenyizoltan ahogy értettem ez ONLINE_SERVICE lesz. De meg nem világos A fejlesztők segítségét kérem.

**Comment by renced42** [comment]
> @renced42 : ha nem a kliens küldi be, hanem szerver oldali alkalmazás, de az nem "valami", hanem saját fejlesztés, ugyanúgy, mint a kliensek, akkor is ONLINE_SERVICE?

Kedves @omachtandras. 
Például van egy számlázó szoftver ami vastag kliens, telepítve van operációs rendszerre. Ennek az adatbázisa lehet ugyanazon a gépen vagy más szerveren a hálózatban. Ez local SOFTWARE.  LOCAL_SOFTWARE lesz egy SAP is. Helyileg vállalathoz van telepítve. Ha a szoftvered vagy komponense kilép a publikus online világba pl: szerverfarmon, tárhelyszolgáltatónál, felhőben működteted és ajánlod ki másoknak az már ONLINE_SERVICE lesz. Ilyenek a nagy online számlázó cégek vagy nagy könyvelő cégek megoldásai amiket ügyfeleknek biztosítanak. Tehát, ha te magadnak gyártasz egy szoftvert, amit saját magadnak telepítesz vagy önállóan értékesítesz másoknak, akik szintén telepítik az NEM LESZ ONLINE_SERVICE, akkor sem, ha az egyébként az egy tárhelyszolgáltatónál van telepítve. Akkor válik azzá, ha az szolgáltatásként biztosítod és ajánlod ki másnak használatra.

Remélem a fenti magyarázat segíti a megfelelő érték kiválasztását.

**Comment by andrew-azarov** [comment]
@NTCA-developer akkor meg egyszer:
egyetlen szolgáltató webáruház - LOCAL_SOFTWARE
néhány szolgáltató webáruház (például emag.hu) - ONLINE_SERVICE
egyetlen szolgáltató SaaS - LOCAL_SOFTWARE
néhány szolgáltató SaaS (például billingo vagy mas online számlázó) - ONLINE_SERVICE
egy VPS-ben cloud-ban egyetlen szolgáltató (desktop vagy api vagy daemon) számlázó program - LOCAL_SOFTWARE
egy VPS-ben cloud-ban néhány szolgáltató (desktop vagy api vagy daemon) számlázó program - ONLINE_SOFTWARE

akkor miert nem <multiUser>true</multiUser>?

**Comment by szecsenyizoltan** [comment]
@NTCA-developer Köszönöm. Van szankciója a rossz besorolásnak?

**Comment by omachtandras** [comment]
@renced42 : Akkor a miénk mindkettő. Ha lemegy a 3.0 őrület, akkor majd fejlesztünk rá valami paraméterezhetőséget, amit lehet állítgatni a szerint, hogy hol/miként fut van éppen a program.

Köszönöm a választ!

**Comment by renced42** [comment]
> @szecsenyizoltan ahogy értettem ez ONLINE_SERVICE lesz. De meg nem világos A fejlesztők segítségét kérem. @NTCA-developer

Dear @andrew-azarov The answer of the question is: Your solution work as a service and provided to other companies or not. If you are not distributing your software as a service to other companies, than the software type would be LOCAL_SOFTWARE, even if it working on serverside or in a cloud. If you are distributed your program as a service to other companies then your software type would be ONLINE_SERVICE.

**Comment by renced42** [comment]
> @NTCA-developer Köszönöm. Van szankciója a rossz besorolásnak?

Kedves @szecsenyizoltan Nincs :)

**Comment by andrew-azarov** [comment]
Thank you so much, I got it wrong the first time. Now updating to LOCAL_SOFTWARE.

**Comment by szecsenyizoltan** [comment]
@renced42 Amúgy minden online service valahol egy lokális szoftver. :)(

**Comment by jozanesz** [comment]
> Egyébként az egész szoftverügy zavaros, mert a mi esetünkben más-más cégek fejlesztik a számlázó programokat, (részben) más az xml kimenetet a számlázó programokból, és megint más az xml-eket beküldő rendszert.

A válaszokból sem kerültem közelebb a megoldáshoz, mert nemhogy az említett két érték közül nem világos a választás, de az sem, hogy a különböző komponensek közül melyik főverziószáma (ha van egyáltalán), fejlesztőjének a neve, mailcíme és adószáma kellene. Marad, ahogy volt: eddig sem írt senki a NAV-tól a megadott mailcímünkre. Majd írnak, ha kérdésük lesz. :)

(Ezek a vékony-vastag kliensek meg felhő, stb. gumifogalmak, és amúgy is változik, hogy éppen mit hol hostolunk, és ki mit milyen csatornán és technológiával ér el a rendszereken belül.)

**Comment by renced42** [comment]
Kedves @jozanesz látható, hogy ezek az adatok arra szolgálnak, hogy amennyiben szükséges tudjon a NAV valakivel kontaktálni, hogy látszódjon hogy esetleg milyen típusú szoftver érintett. Hogy neked nem írt a NAV annak örüljél :), de elhiheted, hogy van olyan amikor szükség van rá és fel is vesszük a kapcsolatot. 
Ennek tükrében kell az adatokat kitölteni.
