### ISSUE TITLE
OnlineInvoiceTool_installer_2020_12_28.exe használata

### ISSUE THREAD

**Issue by PeterAdam** [nav-gov-hu/Online-Invoice#679]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

A program telepítése során nem hozza létre a C:\Program Files (x86)\Online Invoice Test Tool\apixsd mappát, nem telepít xsd-ket. A megjelenő ablak információjával szemben nem hozza létre a c:\temp\invoice mappát az xml-eknek.

A letöltött xsd-ket megadva neki, src-resolve: Cannot resolve the name 'common:AtomicStringType255' to a(n) 'type definition' component. Tehát nem úgy tűnik, hogy értelmezné a common sémát.

Mit mondjunk a külföldi fejlesztőnek, hogy validáljon?

**Comment by renced42** [comment]
Kedves @PeterAdam 

Az Online Invoice Tool részére megnyitásra került egy új repository itt: https://github.com/nav-gov-hu/Online-Invoice-Test-Tool kérlek itt nyissd meg az issuet.

**Comment by PeterAdam** [comment]
Köszönöm, nézem.
