### ISSUE TITLE
[DOC] Interface dokumentáció changelogból hiányzik a lineNeAmountHuf kötelezősége

### ISSUE THREAD

**Issue by magyarfejlesztovagyok** [nav-gov-hu/Online-Invoice#68]
Az interface dokumentáció 5.3-as pontjában a változások között nincs feltüntetve a forintos párok kötelezővé válása (sor szinten, summaryByVatRate és summary szinten)

**Comment by NTCA-developer** [comment]
Szia!

Köszi, feltettem az új változatot tesztre és élesre.
