### ISSUE TITLE
[Q&A] VatRateType: "Unknown" és "Reason" értelmezési problémák

### ISSUE THREAD

**Issue by HWKF** [nav-gov-hu/Online-Invoice#680]
Több kérdés merült fel:
1. Számunkra nem egyértelmű a dokumentációból, hogy tétel szinten a REASONt a felhasználóknak kötelező-e megadni, vagy lehetőség van a dokumentációban lévő szöveget szerepeltetni és beküldeni? 
Vagy az elején megengedett, de később mindenképp pótolják?
Ez különösen azért fontos, mert a v3 képes program verzió kikerülése után és az első számla kiállítása között nem biztos, hogy könyvelésben jártas szakember rendelkezésükre fog állni.

2. Kínálhatunk-e a felhasználónak fix reason listát, amiből választhat vagy mindenképp a felhasználóknak kell ezt beírnia?
Vagy "beégethetjük"-e leírásban szereplő magyarázatot a CASEhez fix értékként? 
Vagy feltölthetjük-e alapértékként, amit addig használ amíg nem módosít?
A Reason megváltozásának új ÁFA kulcsot kell-e eredményeznie, ha már történt vele adatszolgáltatás? Vagy beküldhető az új normál számlán azonos CASE mellett új reason? Vagy módosítás/érvénytelenítés során?

3. Ha egy V2-es számlát érvénytelenítenek, akkor a régi mentességi beállítás helyett új kódot kell küldeni. Ez esetben számla tartalom módosulásnak minősül a régi és az új kód eltérése vagy sem? Főleg, hogy eddig a mentességre 01-12 közötti kódokat küldtünk be, amire hibajelzést nem kaptunk sohasem.
Vagy csak az UNKNOWN érték a megfelelő, azaz csak az unknown biztosítja a tartalom azonosságát?
Milyen eltéréseket ellenőriz a NAV és milyen azonosságokat fogad el?
Vagy ha beállították pl vatExemption esetén az új kódot, akkor azt elfogadja-e NAV minden esetben? A korábbi issue esetén mintha lett volna ebből másoknál probléma.

4. Lehet-e két különböző ÁFA kulcshoz ugyanazt a CASE - REASON párt megadni?

Mivel számunkra a OSZv3 dokumentáció nem egyértelmű, ezért mindenképp szeretnénk NAV választ is kapni, hogy legyen hivatalos válasz a lehetőségekre és a tiltásokra.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Több issueban volt erről szó, ezzel kapcsolatban van még kérdés? Ha nincs, kérlek zárjátok.

Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet, ha van még kérdés, kérlek nyissátok újra.
Üdv
