### ISSUE TITLE
[Q&A] REQUEST_ID_NOT_UNIQUE - Mi a teendő most?

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#681]
**REQUEST_ID_NOT_UNIQUE**

Szép jó napot!
Kérdezni szeretném, hogy az éles felküldésnél ez jött egyik számlához válasznak. 
```
<requestId>RID20210106111945729</requestId>
...
<result>
<funcCode>ERROR</funcCode>
<errorCode>REQUEST_ID_NOT_UNIQUE</errorCode>
<message>A megadott kérés azonosítója már létezik!</message>
</result>
```
Tranzakció azonosító: **386X9X2JI2IRC3U4**

Az utolsó 3 számjegy a század mp értéke. Most hozzáteszek még egy 5 hosszú random számsort még. bízva abban, hogy ez a hiba többet nem következik be.

**A kérdésem az az, hogy mit tudok most tenni ezzel?**

Köszönöm!

**Comment by NTCA-supporter** [comment]
Szia @zsfoto !
Az adott adatszolgáltatást ismételd meg, ennyi a teendő szerintem.
Erre vonatkozik a kérdésed?
Üdv

**Comment by zsfoto** [comment]
**A számla fent van és zöld pipa van.** 
Legeneráltam picit kevesebb mint 4500 számlát. Átnéztem minden oldalt és mindenhol zöld pipa van.
Van ilyenkor teendő még?

**Comment by NTCA-supporter** [comment]
Az a számla is bekerült, amire ezt a hibaüzenetet kaptad? Vagy arról küldtél be új adatszolgáltatást?
Üdv

**Comment by zsfoto** [comment]
Igen, az a számla bent van.
(Az összes generált számla bent van)
Üdv.

**Comment by NTCA-supporter** [comment]
Akkor nincs további teendő.
Zárom az issuet.
Üdv

**Comment by zsfoto** [comment]
Köszönöm
