### ISSUE TITLE
Technikai azonosító validálás

### ISSUE THREAD

**Issue by boriszelenyi** [nav-gov-hu/Online-Invoice#683]
Sziasztok, 
Jelenleg több mint 300 ügyfelünknek önszámlát állítunk ki és ezt csak úgy tudjuk lejelenteni, ha az ügyfelek technikai azonosítóját bekérjük. Jelenlegi tapasztalatok alapján nagyon gyakran eleve rosszul adják meg az ügyfelek ezeket az azonosítókat. Most új rendszert építünk ki, van rá mód, hogy amikor megadják nekünk ezeket, egy teszt számlával elküldve a NAV teszt vagy live rendszerében validáljuk ezeket (egy ügyfél megadott technikai azonosítóját) regisztrációkor ? 
Köszönöm szépen előre is!  

We operate with 300 + clients who we issue 'self bill' invoices for. In order to report these invoices in RTIR, we need to ask and store their 4 Technical ID credentials (Technical ID,pw and 2 xml keys) in our system (SAP). We have experience that from the newly registered almost 40% fails as they are incorrectly given to us in the first place, but currently we only see that as an error during the first LIVE invoice submission (after receiving the error message). We are currently building a new system, where if pssible we would like to build a test scenario, when upon registration at our system, we would send the 4 credentails asap to a TEST environment to the NAV test system and receive a validation asap whether the credentails are correct or not. Is this possible? Any recommendations?

**Comment by fenyvessy** [comment]
Szerintem ha csak egy token kérést csinálsz, és az sikeresen megtörténik, akkor már jók az adatok.

**Comment by NTCA-supporter** [comment]
Szia @boriszelenyi !
Ahogy előttem említetteték az valóban fontos, hogy a két rendszer felhasználói nem azonosak, így külön kezelendő.
Egy token kéréssel 3 adat helyességét valóban tudod ellenőrizni, viszont a cserekulcs érvényességét csak számla vagy technikai érvénytelenítés beküldésével tudod validálni, huiszen ezeknél kell felhasználnod és dekódolnod a kapott tokent.
Üdv

**Comment by renced42** [comment]
> cserekulcs érvényességét csak számla vagy technikai érvénytelenítés beküldésével tudod validálni

Ha tudja dekódolni akkor helyes, ahhoz szerintem nem kell számlát beküldeni :)

**Comment by NTCA-supporter** [comment]
Sziasztok!
Itt van még kérdés?
Üdv

**Comment by boriszelenyi** [comment]
Nincs, köszönöm a választ!
