### ISSUE TITLE
v3.0 nem jön le a invoiceDataResult tag csak v2.0-ba 

### ISSUE THREAD

**Issue by vbela75** [nav-gov-hu/Online-Invoice#685]
A tegnapi nap folyamán sikerült átállnom teljesen v3.0 a letöltéseimmel le is jött több mint 15 ezer számla ebben volt 2 db v2.0 amire v3/queryInvoiceData lekérésre OK érkezett vissza de hiányzott a válaszból invoiceDataResult tag teljesen. Egyáltalán nem volt számla adat a válasz xml-be csak a header, result és software adatok. Ma szintén megpróbáltam és ugyanannál az adózónál ugyanaz a szállító Tegnapi számlája az sem jött le v3.0, majd ezután v2.0 kipróbáltam és hibátlanul lejött.

A transactId az alábbiak: 384VJQM69W5Y7O7X, 387QFG0HQM4AU9U8, 387QSLG8H35KHYK3

Remélem meg tudjátok találni a hiba forrását.

2. kérdés: - Ha jól érzékelem a lekérdezésekben van valamiféle pufferezés, mert ha régebbi adatokat akarok lekérdezni akkor lassabb a válasz (queryInvoiceData) mekkora az intervallum ahol (visszafelé hány nap) ahol gyorsabb a válasz, ha van ilyen megoldásotok. Azért szeretném tudni mert akkor Én is úgy tudnám ütemezni az adatlekérést hogy a régebbieket külön kérném le.

**Comment by NTCA-supporter** [comment]
Szia @vbela75 !
Az éles rendszert nem supportáljuk itt githubon.
Ilyen választ jellemzően akkor kapsz, ha nincs ilyen beküldött számla sorszám.
Volt már korábban ilyen probléma, hogy whitespace karakterek voltak az invoice_number előtt/után.
Ezeket esetleg érdemes ellenőrizni.
Ha nem ez a gond, akkor a hivatalos helpdesknek írj kérlek.
Üdv

**Comment by vbela75** [comment]
Szia @NTCA-supporter !

Köszi a választ valóban whitespace volt a baj trim-eltem az invoicenumber-t kivettem és megoldódott. 
A jövőben ha élesben bajom van a helpdesket keresem.

A 2. kérdésemre esetleg tudnál válaszolni. :)
Üdv.
És utána zárhatjuk is a issue-t.

**Comment by renced42** [comment]
Kedves @vbela75 

A második kérdésre a válasz az, hogy lehetőség szerint a lekérdezéseket minél hamarabb tedd meg.
Ne várj vele heteket hónapokat :)

**Comment by NTCA-supporter** [comment]
Az issuet zárom, ha van még kérdés nyisd újra kérlek.
Üdv
