### ISSUE TITLE
[Q&A] EU-s ügyfélnek belföldi FAD-os számla WARN/ERROR bug

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#686]
Az éles rendszerben (sajnos nem tudom kipróbálni - csak a logokból látom) a számla kiállítója blokkoló hibát kap MISSING_CUSTOMER_DOMESTIC_TAXNUMBER üzenetettel, ha customerVatStatus OTHER , communityVatNumber EU adószámmal van kitöltve, de a számlatétel sorában belföldi fordított adózású eset van jelölve.

Ugyanezt kipróbálva én a teszt rendszerben Sikeres adatszolgáltatást kapok egy WARN-nal: MISSING_HEAD_DATA_CUSTOMER_TAXNUMBER

Ez egyébként jogos is. Lehet-e ilyen jellegű különbség az éles/teszt rendszerben?

**Comment by nbeeps2** [comment]
Mindkét esetben ez a hibaüzenet, hogy a vevő belföldi adószám hiányzik, de jól láthatóan más a "kód"

**Comment by nbeeps2** [comment]
Na most már 100%, hogy az éles 3.0-val van a baj. Bekértük az ügyfél adatállományát és beküldtük a teszt rendszerbe az adatokat, ott WARN-t kap (MISSING_HEAD_DATA_CUSTOMER_TAXNUMBER), míg ha az éles rendszerbe akarjuk küldeni a számlát, akkor pedig blokkoló error-t (MISSING_CUSTOMER_DOMESTIC_TAXNUMBER).

A blokkoló error hibás, ugyanis a MISSING_CUSTOMER_DOMESTIC_TAXNUMBER csak akkor jöhetne, ha a customerVatStatus  DOMESTIC, azonban a mi esetünkben OTHER esetén is ez jön! Ez HIBA! Kérjük javítani S.O.S!

**Comment by NTCA-supporter** [comment]
@nbeeps2 
https://github.com/nav-gov-hu/Online-Invoice/issues/667 ez nem válasz a te problémádra?
Köszi

**Comment by nbeeps2** [comment]
@NTCA-supporter Igen, erről van szó, viszont nem látom ott sem a választ. Igen, az a gond, hogy a tételek között van olyan, ami belföldi fordított adózású, azaz vatDomesticReverseCharge = true, viszont emiatt csak WARN-t kéne kapni és nem blokkoló ERROR-t. Ahogy írtam is a gond az, hogy a teszt rendszer WARN-t küld (ez működik helyesen), az éles rendszer pedig hibásan blokkoló üzenetet.

Bevágom ide @dupplak adatát:
```
<customerInfo>
<customerVatStatus>OTHER</customerVatStatus>
<customerVatData>
<communityVatNumber>BG202742205</communityVatNumber>
</customerVatData>

```
Szóval nálam is így van kitöltve. A customerVatStatus tehát egyértelműen OTHER és NEM DOMESTIC, ennek ellenére a hibás (és csak éles 3.0-ban létező) üzenet baja, hogy MISSING_CUSTOMER_DOMESTIC_TAXNUMBER. Ami pedig nem igaz, mivel ez csak ekkor jöhetne: "Ha a vevő belföldi áfaalany (CustomerVatStatusType = DOMESTIC), akkor a Magyar adószám (customerVatData)
megadása kötelező." 

Kérem a hiba S.O.S. javítását, mert nem mennek be a számlák! Köszönöm!

**Comment by NTCA-supporter** [comment]
Szerintem az szándékosan ERROR és nem WARN. Fordított adózás esetén minden esetben kötelező a magyar adószám.
@NTCA-tax kérlek erősíts/cáfolj meg.
A tesztrendszerre beküldött számla valamelyik adatát küld el kérlek, hogy megnézzem ott miért nem kapsz errort.
Köszönöm

**Comment by nbeeps2** [comment]
Nem lehet szándékosan ERROR vagy akkor hibás a dokumentáció ("Ha a vevő belföldi áfaalany (CustomerVatStatusType = DOMESTIC), akkor a Magyar adószám (customerVatData) megadása kötelező."

Teszt rendszerbe beküldött azonosító: 388L4LJ9KSVX2DOS 
Bizonylatszám: DD2021/000001

**Comment by dupplak** [comment]
Üdv,
A hiba a belföldi fordított adózás adókulcs miatt van. Ha ezt használjátok, mindenképp kell belfölid adószám, mivel ez - mint a neve is mutatja - belföldi. Ezt cseréljétek le EU fordított adózásra, akkor menni fog. A BFA-t csak DOMESTIC-kel lehet használni, és ezért kell a belföldi adószám is.

Üdv,

**Comment by nbeeps2** [comment]
@dupplak Én vágom, hogy mitől van a hiba, de akkor ezek szerint nem értitek mi a bajom...

Hibásan működik az ÉLES rendszer! Olyan nem lehet, hogy a teszt rendszerbe egy adatra WARN-t kapok, az éles rendszerbe meg ugyanarra ERROR-t. 

És ha megnézzük a MISSING_CUSTOMER_DOMESTIC_TAXNUMBER dokumentációját, akkor abban az látszik, hogy akkor lép életbe, ha a CustomerVatStatusType = DOMESTIC, de az esetemben (és a te esetedben is) nem az, hanem OTHER!

**Comment by dupplak** [comment]
Szia, értem mit írsz, de szerintem a doksi hibás, azt kellene javítaniuk, vagy egyszerűen egy egyértelműbb hibaüzenetet küldeni. INVALID_TAX_CODE_FOR_FOREIGN_CUSTOMER vagy valami ilyesmi, hogy egyértelmű legyen.

**Comment by nbeeps2** [comment]
@dupplak Ha csak a doksi lenne a hibás, akkor a teszt rendszer is blokkoló ERROR-t adna, itt valami nagyobb bibi van.

**Comment by NTCA-supporter** [comment]
Szia @nbeeps2 !

A dokumentáción fogunk pontosítani, valóban nem egyértelmű. 
A tesztrendszeren is kapnod kellene, ennek utánanézek.

Üdv

**Comment by nbeeps2** [comment]
@NTCA-supporter Ok, de onnantól kezdve ha tényleg blokkoló, akkor gyakorlatilag az alábbi WARN megszűnik, illetve átalakul ERROR-ként:

WARN: MISSING_HEAD_DATA_CUSTOMER_TAXNUMBER
Vevő adószáma hiányzik (belföldi fordított adózás).
Figyelmeztet, ha a vevő adószáma nincs kitöltve annak ellenére, hogy a számla
tételsorai között előfordul belföldi fordított adózás jelölése.

**Comment by NTCA-supporter** [comment]
Sziasztok!

A dokumentációt javítottuk, DOMESTIC_TAXNUMBER_EXPECTED_REVERSE_CHARGE lett bevezetve erre az esetre.

Üdv
