### ISSUE TITLE
Vevő adószám (első nyolc karaktere) hiányzik.

### ISSUE THREAD

**Issue by kristofbela** [nav-gov-hu/Online-Invoice#688]
Felküldtem egy privát számlát és ezt kaptam kérem a segitséget!  Egy másik cégnél hibátlanul működik  
Mi a teendő  WAR visszajelzés esetén ?

386VKYPF6582ZD1V 
MISSING_HEAD_DATA_CUSTOMER</ns2:validationErrorCode><ns2:message>Vevő adószám (első nyolc karaktere) hiányzik.

<customerInfo>
   <customerVatStatus>PRIVATE_PERSON</customerVatStatus>
</customerInfo>

**Comment by omachtandras** [comment]
@kristofbela : vélhetően az adótartam 100.000 ft felett van. Ha igen, akkor ez egy ismert hiba. Most gyorsan nem találtam meg, de itt is be van jelentve.
A mi partnereink közül is többen belefutottak, várják / várjuk a javítást.

**Comment by jozanesz** [comment]
#662
Szerintem nem kellene állandóan lezárni a jelenleg nem megoldott problémákat, és akkor többen megtalálnák.

**Comment by hoszke** [comment]
Ezzel a kérdéssel lesz valami változás, vagy fogadjuk el, hogy ez van? Egyáltalán ez hiba? Mert ha ez bent marad, akkor intézkednénk, hogy a felhasználóink előtt ne jelenjen meg, mivel számunkra elég kellemetlen a sok megkeresés részükről.

**Comment by topybear** [comment]
Mert már több példányban van, pl:
https://github.com/nav-gov-hu/Online-Invoice/issues/515
https://github.com/nav-gov-hu/Online-Invoice/issues/520
https://github.com/nav-gov-hu/Online-Invoice/issues/500

**Comment by hoszke** [comment]
Több példányban fent van, mindegyik zárva (kivéve ezt), de a probléma továbbra is fennáll, rendkívül zavaró.

**Comment by topybear** [comment]
Szerintem több helyen is leírták a NAV-os kollégák, hogy a warningok felülvizsgálata még folyamatban van - egyelőre várnunk kell.

**Comment by JimTudeski** [comment]
3+ hónapja nem képesek javítani, de a fenyegetés az jól megy, mi és mikor a kötelező és mennyi a büntetés. Ez a szomorú...

**Comment by NTCA-supporter** [comment]
Sziasztok! A WARN kivezetésre került, egyelőre még csak teszt rendszeren próbálható, a 3.3 verzióban kerül majd élesre.
Nem a képességgel volt a gond, hanem vannak sokkal fontosabb dolgok is, és emiatt az irreleváns WARN miatt senki nem lett fenyegetve.
Üdv

**Comment by JimTudeski** [comment]
Ezt majd megmagyarázom az ügyfeleknek is, hogy irreleváns a WARN, ne aggódjanak... könnyű ez mondani, mert nem bennetek, hanem bennünket hívogatnak az ügyfelek. És akkor magyarázzam meg Mancikának, hogy idáig a lelkére kötöttük a WARN-nal foglalkozzon, de ez olyan WARN hogy nem kell. Az ügyfelekben kialakul, hogy mégsem fontos minden WARN, a NAV is lehet ludas, aztán szép lassan lankad a figyelem. Szerintem egy ordas hiba még ha csak WARN is, és nagyon nagyon kellemetlen, hogy eddig még mindig nem lett javítva az élesen. Fordított esetben, ha meg valamit rosszul küldünk gondolom nem lesznek ilyen elnézők, de majd én is ráfogom a fontosabb dolgaimra...

**Comment by pvmon** [comment]
@NTCA-supporter Elég elszomorító, hogy ismert és javítatlan problémákkal is kiadták az új rendszert élesben. A tesztben néztük, hogy ez már jó és javítva lett. Eszünkbe sem jutott, hogy az élesben meg nem. Most mi is kapjuk a telefonokat e-maileket emiatt...

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ha van még kérdés, nyissátok újra kérlek.
Üdv
