### ISSUE TITLE
[Q&A] SHA3-512

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#69]
A dokumentáció a következőt állítja : 
"A 2.0-ás interfész verzió célja refaktorlálni a meglévő rendszert, bővíteni a nyújtott szolgáltatások körét, valamint lecserélni az SHA-512 hash algoritmust az SHA3-512 algoritmusra"

Két helyen volt eddig használva az SHA-512 : user passwordHash és requestSignature. A dokumentáció alapján mindkét helyen cserélni kellene, nincs feltűntetve hogy csak az egyik hely lenne érintett. A gyakorlatban viszont most csak úgy megy a 2.0 token kérés, ha passwordHash marad SHA-512 és requestSignature átáll SHA3-512-re.

A dokumentáció a hibás/nem pontos vagy a v2 teszt rendszer működés nem az elvárt?

**Comment by Amn3s1a2018** [comment]
Ez volt a [hírekben](https://onlineszamla.nav.gov.hu/home):
> A 2.0-ás számlabejelentő interfész – a metrika lekérdező kényelmi szolgáltatást, valamint a figyelmeztető válaszüzenetek változásait kivéve – 2019.10.15. napjától lesz teljes funkcionalitással elérhető a teszt környezetben.

Hogy a requestSignature SHA3-512 ezzel hogy jön össze, azt nem tudom, de ennek alapján nem érdemes a tesztekből messzemenő következtetéseket levonni még legalább három hétig.

**Comment by NTCA-developer** [comment]
Sziasztok!

Köszi a kérdést. A passwordHash marad az eredeti hash alakjában, az SHA3 csak és kizárólag a requestSignature esetében játszik. Ennek az oka, hogy - kérlek olvass a sorok között - kötelező jelszócsere nélkül nem lehet áttérni a jelszavaknál új algoritmusra.

A doksiban egyértelműsítem a leírást. Valójában úgy volna helyes, hogy "A 2.0-ás interfész verzió célja refaktorlálni a meglévő rendszert, bővíteni a nyújtott szolgáltatások körét, valamint lecserélni az SHA-512 hash algoritmust az SHA3-512 algoritmusra**, ahol ennek relevanciája van**"

Lezárod majd a ticketet?
