### ISSUE TITLE
[Q&A] modifyWithoutMaster használata korábbi 2021 (előtti) külföldi vagy magánszemély számláknál

### ISSUE THREAD

**Issue by millsanthony** [nav-gov-hu/Online-Invoice#690]
Ha jól értem, a dokumentáció az alábbi esetekre szűkíti annak a lehetőségét, hogy egy számla módosításakor a módosítás eredeti számlájára vonatkozó korábbi adatszolgáltatás hiányában a modifyWithoutMaster=true használható:
"- az eredeti számla még 2018. július 1-jét megelőzően került kiállításra, a módosító okirat jelentésköteles
- az eredeti számla bár 2018. július 1-jét követően került kiállításra, de még nem volt jelentésköteles, és nem is történt róla adatszolgáltatás, ugyanakkor a módosító okirat kiállításakor már jelentéskötelessé válik
- az eredeti számlát az adózó jogelődje állította ki, melyről bár megtörtént az adatszolgáltatás, de a jogutód adatszolgáltatásaiban nem található meg
- közműszolgáltatók esetén, ha az adott elszámolószámla tartalmazza az utolsó időszak teljesítéséről szóló adatszolgáltatást is (lásd utilitySettlementIndicator működése)"

Ha egyéb okból nem történt adatszolgáltatás az eredeti számláról, akkor hogy kell eljárni annak módosításakor? Pl. egy külföldiek számára kiállított 2020-as számla volt, amiről 2021.01.04 előtt nem kellett adatot szolgáltatni a V2-es interfészen, és ha jól tudom utólag sem kell ezt pótolni. Vagy egy magánszemély 2020-as számlájáról nem történt adatszolgáltatás. Ezeket hogy kell 2021-ben módosítani, a módosítást hogy kell beküldeni?

**Comment by SimplifiedSzamla** [comment]
És akkor mit kell tenni, ha az alapszámla pl. 2021-es magánszemélynek vagy külföldi vevőnek kiállított számla, de nem került beküldésre, és azt érvénytelenítik később? Akkor mehet a stornó modifyWithoutMaster=true-val?

**Comment by nbeeps2** [comment]
Akkor használjátok a modifyWithoutMaster=True, ha a stornózandó/módosítandó "eredeti" számláról nem történt adatszolgáltatás.

@millsanthony : kérlek, legközelebb, amikor új topic-ot nyitsz, adj neki valami beszédes nevet, köszönöm.

**Comment by millsanthony** [comment]
Bocs, pótoltam a topic címét.
@nbeeps2, köszönöm a választ, egyébként eleve úgy írtuk meg a programunkat ahogy írod, mert "logikusan" nem találtunk más lehetőséget, de ez a működés ettől még helytelen, vagy nem egyértelműen helyes a dokumentáció szerint, az én olvasatomban. 

A dokumentációban lévő megfogalmazásnak két része van, egy általános, és utána egy azt szűkítő.
A teljesen általános állítás:
_"Speciális esetekben előfordulhat, hogy olyan módosító okiratról történik adatszolgáltatás, amelynek
az eredeti számlájáról még nem történt, és nem is fog történni. Ezt a tényt a modifyWithoutMaster
elem „true” értékével kell jelezni."_ 
Ennek még megfelelünk.

Viszont utána van egy ezt az általános megfogalmazást szűkítő definíció, ami nem csak példákat hoz, hanem tételesen felsorolja, azaz behatárolja, hogy milyen esetben állhat elő: 
_"Ilyen helyzet az alábbi esetekben állhat elő: ...."_
És itt van a fent már idézett tételes felsorolás, amiben mivel nincsenek benne azok az esetek, amikre a kérdés vonatkozik, így ezekre a dokumentáció szerint nem alkalmazható a modifyWithoutMaster=True (vagy legalábbis csak az általános mondat szerint  alkalmazható, de a tételes esetlista szerint már nem).

Ezt jó lenne egyértelműsíteni a dokumentációban, és addig is szeretnék itt egy "hivatalos" választ is kapni itt, hogy minden olyan esetben alkalmazható ez a módszer, ahogy @nbeeps2 írja és én is gondolom.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ez teljesen valid megfogalmazás, de szerintem ti is erre jutottatok:
Akkor használjátok a modifyWithoutMaster=True, ha a stornózandó/módosítandó "eredeti" számláról nem történt adatszolgáltatás.

Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
