### ISSUE TITLE
[Q&A] Webesen hol tudok annuálni?

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#692]
**Weboldalon hogy tudok egy xml validáción elbukott felküldést érvényteleníteni?**
A nyilatkozatok menüpontnál nem hozza fel a számlákat. A számlák listájánál nem látok erre vonatkozó gombot, hogy annuálhassam.

TrID: 389UY8UNCJ8UU8VO

Köszönöm

**Comment by topybear** [comment]
Ha elbukott a validáción akkor az nincs fenn a NAV-nál, nem kell érvényteleníteni.

**Comment by renced42** [comment]
Kedves @zsfoto 
Ha XML validáción elbukik valami az nem megy be vagyis nem kell érvényteleníteni sem.

**Comment by NTCA-supporter** [comment]
A kimenő számla lista oldalon a műveleteknél van Technikai érvénytelenítés funkció, amit aztán jóvá kell hagynod a Nyilatkozatoknál.
API-n is tudsz beküldeni tech annulmentet, a manageAnnulment operációval.
Üdv

**Comment by zsfoto** [comment]
Ez van a hibáknál írva:
--
- XML contains on line: [1] and column: [4,127] error:  [cvc-minLength-valid: Value '' with length = '0' is not facet-valid with  respect to minLength '1' for type 'LineNatureIndicatorType'.]
- XML contains on line: [1] and column: [4,127] error: [cvc-type.3.1.3:  The value '' of element 'lineNatureIndicator' is not valid.]
- XML contains on line: [1] and column: [5,174] error:  [cvc-minLength-valid: Value '' with length = '0' is not facet-valid with  respect to minLength '1' for type 'LineNatureIndicatorType'.]
- XML contains on line: [1] and column: [5,174] error: [cvc-type.3.1.3:  The value '' of element 'lineNatureIndicator' is not valid.]
- Xml validation failed

**Comment by NTCA-supporter** [comment]
Ha sémasértés van akkor az a számla nem lett feldolgozva, ahogy írták előttem azt nem kell annulálni.

**Comment by zsfoto** [comment]
A kimenő számláknál nem is listázódik. Ezek szerint be se ment?
Mi legyen a helyi programunk adatbázisában lévő számlával?

**Comment by renced42** [comment]
Kedves @zsfoto 
A számlával ne csinálj semmit.
Javítsd a programodat és küld be helyesen az adatszolgáltatást.

**Comment by zsfoto** [comment]
Köszönöm!

Szép hétvégét mindenkinek!

**Comment by renced42** [comment]
Kedves @zsfoto 
Kérlek zárd az Issuet.
