### ISSUE TITLE
[Q&A] A teszt rendszer nem érhető el

### ISSUE THREAD

**Issue by alaplap** [nav-gov-hu/Online-Invoice#695]
**A kérdés, amire választ szeretnék kapni **
A teszt rendszer nem érhető el. Ti mit tapasztaltok?

**Comment by rtoth0407** [comment]
Igen, én is dolgoznék....

**Comment by renced42** [comment]
Kedves @alaplap 
A teszt rendszerben karbantartás van.

**Comment by renced42** [comment]
Kedves @alaplap 
Kérlek zárd az Issue-t

**Comment by NTCA-supporter** [comment]
Zárom.
"UPDATE : A karbantartás 2021. január 11-én 17 óra 45 perckor befejeződött."
