### ISSUE TITLE
MetricsService 404 minden metrikára

### ISSUE THREAD

**Issue by vectorkovacspeter** [nav-gov-hu/Online-Invoice#696]
https://api.onlineszamla.nav.gov.hu/metricService/v3/queryServiceMetrics/list listából bármelyik metrikára kérdezek 404 -es eredményt kapok, ugyanez a teszten is.
pl.: 
https://api.onlineszamla.nav.gov.hu/metricService/v3/queryServiceMetrics/metric/responseTimeAverageMsManageInvoice

v2 -őn szintén.

Én csinálok valamit rosszul, vagy még mindeig nem mennek a metrikák?

**Comment by NTCA-supporter** [comment]
Szia!

A #554 -ben már jelezve lett a hiba.
Ezt az issuet zárom, ott fogok jelezni ha kint van a javítás.
Üdv
