### ISSUE TITLE
OSA 3.0 <> OSA 2.0 QueryInvoiceDigestResponse Invoice konverzió

### ISSUE THREAD

**Issue by vectorkovacspeter** [nav-gov-hu/Online-Invoice#697]
Érdeklődnék, hogy van-e valami frappáns megoldásaz ha egy 3.0 -ás verziót használó kliensen QueryInvoiceDigestRequest -ben olyan számla jön, amit még 2.0 -val küldtek fel.

Első gondom vele, hogy nem is látom, csak a dekódolt számla byte-okból, hogy van benne OSA/2.0, szerintem ezt kéne már jelezni a Response fejben, vagy valahol struktúráltan.
Második gondom, hogy mivel a klensem már a 3.0 -ás sémán van, nem tudja deserializálni a 2.0 -ás xml-t. (C# xsd-ből generált classok, minden erősen típusos).

Ki tudom esetleg kérni 3.0 -ás formában a 2.0 -ával felküldött számlát (non-plus-ultra lenne, ha eleve így adná a 3.0-ás API)?
Van valami ajánlott konverziós megoldás 2.0 Invoice -> 3.0 Invoice konverzióra?

Bármi egyéb?

**Comment by renced42** [comment]
Kedves @vectorkovacspeter 
Ez a téma itt lett megbeszélve : #607 ezt olvasd át. Neked valami hasonló problémád van talán.

**Comment by NTCA-supporter** [comment]
@vectorkovacspeter van még kérdés?
Üdv

**Comment by vectorkovacspeter** [comment]
Köszönöm, nincs, sajnos több sémával kell dolgoznom, úgy látom másnak se jutott eszébe jobb, zárható.
