### ISSUE TITLE
[Q&A] compressedContentIndicator gzip-es invoiceData

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#698]
Nem sikerül visszakódolnom az olyan számlákat, amiket a számlakiálló compressedContentIndicator True-val jelölt, vagyis gzippel tömörítette az invoiceData.

A QueryInvoiceData-ban látom, hogy a compressedContentIndicator True, az invoiceData tartalma nem visszakódolható. A dokumentációba ajánlott http://www.txtwizard.net/compression  oldalra is hiába vágom be csak egy üres popup ablak ugrik fel, hogy "a www.txtwizard.net közlendője" és egy OK gomb, de nincs konkrét üzenet.

Hogy kell kikódolni a tartalmat?

**Comment by NTCA-supporter** [comment]
Szia @nbeeps2 !
A base64 decode után próbálod mindezt?
Üdv

**Comment by nbeeps2** [comment]
Ok, valóban nem volt base64 decode, de sajnos most sem megy. Egyelőre nem programból próbálom, hanem a dokuemtációban található webes tool-okkal. a Base64 decode után egy csomó hieroglifa, kínaijel, kocka képződik, és ezt hiába másolom át a http://www.txtwizard.net/compression oldalra, hogy csomagolja ki, nem tud vele mit kezdeni. Milyen tool-okkal tudnám ezt tesztelni? 

Erre lenne szükségem:
Van egy Base64 kódolt szövegem (invoicedata)
Ezt decode-olja (ehhez ezt használtam: https://www.base64decode.org/)
Majd az így kapott érzéket gzippel csomagolja ki (ehhez ezt használtam: http://www.txtwizard.net/compression )

**Comment by nbeeps2** [comment]
Kezdem nagyon nem érteni a dolgot. Az invoiceData-ból kivágtam a tartalmát, ami még BASE64 kódolva van, mert így adja vissza a NAV rendszere. Bevágtam a  http://www.txtwizard.net/compression oldalra és rányomtam a Decompress-re is sikeresen kizippelt úgy, hogy még BASE64-ben volt az adat. Nem értem.

**Comment by nbeeps2** [comment]
Nekem nagyon úgy tűnik, hogy a queryinvoiceData válaszában az invoicedata nincs BASE64 kódolva, hanem csak gzippelve van.

**Comment by kabelnet2** [comment]
Az általad használt oldal ezt írja "...and decompressing compressed base64 string..." vagyis az xml-ben visszakapott, base64-ben kódolt adatot kell neki átadni, nem kell előtti kikódolni (mondom mindezt úgy, hogy még sohasem HASZNÁLTAM ezt az oldalt).

**Comment by nbeeps2** [comment]
@kabelnet2 : köszönöm, valóban nem vettem észre az oldal tetején lévő erre vonatkozó feliratot. Egyébként nem mindig működik nekem ez az oldal, sokszor hiába vágom be a BASE64 szöveget (eleve ezzel kísérleteztem, mielőtt nyitottam ezt a topicot) és nem csinál semmit.

**Comment by nbeeps2** [comment]
A problémám megoldódott, annyi, hogy a dokumentációban javasolt http://www.txtwizard.net/compression oldal nem megbízhatóan működik, így én helyette ezt javaslom: https://www.multiutil.com/gzip-to-text-decompress/
