### ISSUE TITLE
[Q&A] belföldi adóalany külföldinek állítanak ki számlát pl. 16%, 19%-os ÁFA-val INVALID_VAT_DATA

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#699]
A rendszer validációval kényszeríti az elévülési időn belül lévő áfakulcsok vagy tartalmak helyes megadását. Normál és
gyűjtőszámla esetén csak:
- 0.05
- 0.07
- 0.12
- 0.18
- 0.2
- 0.25
- 0.27
Ellenkező esetben INVALID_VAT_DATA  üzenettel az adatszolgáltatás Sikertelen lesz.

Hogy tud belföldi adóalany külföldinek állítanak ki számlát a fentiektől eltérő ÁFA kulccsal (pl. 16, 19%)? 
Vagy ilyenkor ÁFA hatályon kívüli vagy 27%-os kulccsal kell számlázni?

**Comment by nbeeps2** [comment]
Azt a részét értem és tudom, hogy bizonyos esetekben (pl. a Magyarországról teljesített távértékesítésről, amennyiben az ügylet után (akár az adózó döntése nyomán, akár az értékhatár túllépése miatt) nem Magyarországon keletkezik adófizetési kötelezettség) nem kellene küldeni a számlát, de ezeket nem igazán lehet detekáltni a programból, azt meg nem szeretném, hogy beleteszek egy kapcsolót a programba, hogy "NE KÜLDJE EZT A SZÁMLÁT A NAV-hoz", mert akkor meg olyankor is bekapcsolják majd, amikor kéne küldeni. Legjobb lenne tehát minden számlát beküldeni a NAV-hoz, így a NAV feldolgozás jó lenne, ha nem dobna error-t, az ilyen ÁFA esetekre, ha azt érzékeli, hogy a vevő külföldi.

**Comment by NTCA-tax** [comment]
Az Online Számla rendszer kizárólag az adatszolgáltatásra kötelezett számlák alapján működik. Egy belföldi adóalany nem nagyon állíthat ki számlát a magyar áfakulcsoktól eltérő mértékben. Amennyiben más tagországban keletkezik adófizetési kötelezettség, akkor oda a magyar vállalkozásnak be kell jelentkeznie, adóregisztrációval kell rendelkeznie. Belföldi adóalanyiságában nem állíthat ki más tagországi adókulcs szerinti számlát. 

A fentiektől eltér az elektronikus szolgáltatásnyújtás és 2021. július 1-től azon távértékesítők adózása, amelyek a különös adózási módszert alkalmazzák. Ők regisztrálnak vagy már regisztráltak a MOSS/OSS rendszerbe. Ezen ügyletekre azonban nem terjed ki a számlaadat-szolgáltatási kötelezettség.

**Comment by nbeeps2** [comment]
"Ezen ügyletekre azonban nem terjed ki a számlaadat-szolgáltatási kötelezettség."
Igen, ezzel tisztában vagyok, ugyanakkor a program minden kiállított számlát beküld(ene) a NAV-hoz.
Nézzük, a fenti példát:
A felhasználó véletlen(!) elüti az ÁFA kulcsot és 16%-al számláz, ezt a program megakadályozza, mert tudja, hogy nem lehet ilyen ÁFA kulccsal számlázni. A program helyesen járt el.
Viszont, ha a felhasználó szándékosan választja ki a 16%-os ÁFA-t, mert olyan számláról van, amire nem terjed ki az adatszolgáltatási kötelezettség, úgy meg engedni kéne a számla kiállítását, csak nem kéne beküldeni a NAV-hoz.
Az óriási gond ezzel az, hogy a program nem tudja detektálni, hogy a 16%-os ÁFA kulcsot valaki tévedésből vagy szándékosan választotta ki.
De menjünk tovább: 
Tavaly még arról volt szó, hogy idén MINDEN számlát be kell majd küldeni a NAV-hoz és aztán idén kiderült, hogy azért jó pár kivétel van ez alól. Ezeket a szituációkat azonban nem igazán lehet automatikusan detekálni, így a program jobb, ha mindent beküld a NAV-hoz alapon működik. 

Azt meg nem szeretném, hogy beleteszek egy kapcsolót a programba, hogy "NE KÜLDJE EZT A SZÁMLÁT A NAV-hoz", mert akkor meg olyankor is bekapcsolják majd, amikor kéne küldeni, illetve a NAV-nak se lenne gondolom ez érdeke, hogy a számlázó programban SZÁNDÉKOSAN ki lehessen kerülni egy számla beküldését azzal, hogy bepipálja ezt a lehetőséget.

MI A MEGOLDÁS?

**Comment by nbeeps2** [comment]
Ugyanez a helyzet az ingatlanbérbeadással, amikor az adott esetben elég lenne számviteli bizonylat kiállítása is, de az ügyfél mindenképp a számlázó programból akarnak számlát kiállítani, mert nem akar Word dokumentumokat gyártani, hiszen ezért van számlázó programja. Ezeket a számlákat sem kéne beküldeni a NAV-hoz, viszont a program beküldi, mivel nem tudja detektálni, hogy olyan ügyletről van szó, amikor számviteli bizonylat is elég lenne. Nem gondolom, hogy az a jó megoldás, hogy az ügyfél jelzi, hogy ez a számla ne menjen be a NAV-hoz, mert ezzel óriási visszaéléseknek lehetne a táptalaja....

**Comment by topybear** [comment]
Vezesd be a bizonylattípus fogalmát (számla, számviteli bizonylat, bekérő stb.) és a bizonylattípuson jelöld, hogy beküldendő-e. Ha ezt a beküldendő jelölést az ÁFA törzsben is bevezeted, akkor egész kellemes keresztellenőrzéseket lehet végezni a "mi szerepelhet min" tárgykörében :)

**Comment by nbeeps2** [comment]
topybear: Ahogy fentebb indokoltam nem tartom szerencsésnek, ha a felhasználó szándékosan ki tudja kerülni egy számla beküldését a NAV-hoz, így nem támogatom azt az ötletet, hogy a felhasználó tudja szabályozni, hogy mi menjen be és mi nem. A programmal csak számlát lehet kiállítani, nincs benne számviteli bizonylat funkció.

**Comment by topybear** [comment]
Valószínűleg a más ügyfélkör más filozófiát alakított ki: mi mindent paraméterezhetővé tettünk, a megfelelő jogosultsággal rendelkező felhasználó állíhatja be, hogy mit kell küldeni, mit nem. Mi semmilyen szinten nem szeretnénk olyan felelősséget magunkra húzni ami egyébként a felhasználóé.

**Comment by nbeeps2** [comment]
Teljesen más az ügyfélkörünk. Nincsenek jogosultságok, a programokat jellemzően egy fő használja pl. egyéni vállalkozók. Nekik fogalmuk sincs a számlázási szabályokról. Ok, hogy az ő felelősségük lenne tudni, hogy mit kéne beküldeni és mit nem, ugyanakkor nincsenek annak a tudásnak a birtokában (és sokszor a könyvelők sem), hogy ezt fejből vágják. Ennek ismeretében, meg orosz rulett lenne egy olyan funkció bevezetése, mely pipát, ha bejelöli, akkor nem küldi be a számlát a NAV-hoz a program. Illetve egy ilyen funkciót lehetne szándékosan rosszhiszeműen is használni. Összességében tehát a javaslatom, hogy ERROR helyett WARNING legyen a témaindító kapcsán.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezzel kapcsolatban van még kérdés? Ha nincs, kérlek zárjátok.

Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet, ha van még kérdés, kérlek nyissátok újra.
Üdv
