### ISSUE TITLE
[Q&A] dokumentáció hibák, ötletek

### ISSUE THREAD

**Issue by connorhu** [nav-gov-hu/Online-Invoice#7]
Sziasztok!

Nem feltétlen ehhez a repohoz tartozik, de a dokumentációban található hibák jelzésére is lehetne valami módot találni és ha már elkezdtetek itt felületet kialakítani, akkor lehetne ennek is helyet teremteni.

Pl: lineExpressionIndicator kötelző, de a táblázatban 67. oldalon nem kötelező.

Lehetne a Word doc-ból generált PDF vonatkozó részeit közvetlenül az XSD-ből összeállítani (mert ott jól van).

**Comment by NTCA-developer** [comment]
Szia!

Ez nagyon jó ötlet, dehogynem lehetne. Mondjuk amit hibának írsz, az pont nem bug hanem feature. :) Azért is jelöltük meg kék színnel, a táblázat alatt pedig csillagos megjegyzésben, hogy ezek a tagek ugyan a séma szerint nem kötelezők, de a hiányukra a rendszer validációs hibát fog dobni. Ez azért van, mert minor verzióban 1.0-1.1 között nem tudsz új kötelező taget felvenni úgy, hogy megtartsd a visszafelé kompatibilitást.

De egy ilyen valóban kellene, mert csomó typo-t és egyéb hibát egyébként egyéni hibabejelentés alapján javítunk folyamatosan, de csak ezért nem adunk ki az új doksit. (lélektani okokból) Ezek mindig az új változatba kerülnek be, de a többiek nyilván nem látják a javított állapotot addig. Ha itt lenne rá felület, akkor legalább ez feloldódna.

Futok egy kört vele, kérem a türelmedet.

**Comment by connorhu** [comment]
Ebből számomra az lett világos, hogy egy API dokumentáció elsődleges platformja nem egy pdf kéne legyen, hanem egy HTML alapú (részben generált) felület. Ott több lehetőség van a különféle finomságok érzékeltetésére és egy jól kitalált UI sokat javít az API értelmezhetőségen és a tanulási görbén.
Érdemes szétnézni, hogy mások hogyan valósítanak meg ilyen tartalmak online dokumentációját. Egy jó felület sokat dob a DX-szen (developer experience)
pl:
https://rebilly.github.io/ReDoc/

**Comment by NTCA-developer** [comment]
Nincs köztünk vita a kérdésben, abszolút így van. Mi is használunk belül openAPI-t (Swaggert), van asciiDoc doksink is. Ami probléma, hogy itt vannak megugrandó hálózati kérdések, amiket még ki kell egyenesíteni mielőtt beengedünk egy végponton a net felől is forgalmat. De lassú víz, ahogy szokták mondani.

**Comment by NTCA-developer** [comment]
Szia!

Nincs elfelejtve a kérés a doksi hibabejelentő sablonnal kapcsolatosan, csak még nem tudtam hozzájutni a megfelelő emberekhez. :) A türelmedet kérem.

**Comment by NTCA-developer** [comment]
Na, sikerült, tetszik mindenkinek úgyhogy felveszek majd ilyen issue sablont meg frissítek CONTRIBUTING.md-t.

Köszönjük szépen a felvetést, ez tényleg nagyon jó ötlet! Az issue lezárható?
