### ISSUE TITLE
[Q&A] invoiceDirection

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#70]
A dokumentációba SUPPLIER és CUSTOMER van, a github-os példákban viszont INBOUND és OUTBOUND. Melyik a helyes?

**Comment by NTCA-moderator** [comment]
Az INBOUND és OUTBOUND érték a megfelelő, a dokumentációt ennek megfelelően javítjuk. Köszönjük az észrevételt!

**Comment by NTCA-developer** [comment]
Szia @EPluribusUnum 

Az elírás az én bűnöm, hamarosan adunk ki frissített dokumentációt. A changelogot én is 7 külön forrásból szedtem össze magamnak sorvezetőnek, és az egyik még egy régi változat volt, így került be a dokumentációba a SUPPLIER és a CUSTOMER. Az XSD a helyes, ahogy írtuk is.

Lezárod majd?
