### ISSUE TITLE
queryTaxpayer infoDate

### ISSUE THREAD

**Issue by Mocsa1974** [nav-gov-hu/Online-Invoice#701]
Üdvözlöm.

Azt vettem észre, hogy a 3.0-ás éles rendszerben a queryTaxpayer operáció a legtöbb lekérdezett adózónál az infoDate mezőben 2021-01-09 ad vissza. A teszt rendszerben nem tapasztaltam ilyen hibát.

Üdvözlettel,
Mocsári Péter

**Comment by NTCA-supporter** [comment]
Szia @Mocsa1974 !
Segíts kérlek, ezt miért gondolod hibának?
Üdv

**Comment by Mocsa1974** [comment]
Azt gondoltam, hogy az infoDate azt mondja meg hogy az adott  adószámnál mikor történt vátozás. Például tőkeemelés, tulajdonosi változás, tevékenység módosítás. Mivel a saját adószámunkat kérdeztem le és tudtommal nem történ 2021-01-09én semmilyen változás a cégben igy tűnt fel a dátum. Egy ismerősöm cégének az adószámát is lekérdezve 2021-01-09 volt az infoDate.
Ezért gondoltam, hogy valami probléma lehet az infoDate töltésével a response-ban. Annyira nem nagy gond mert erre az adatra nem épül semmilyen üzleti folyamatunk, csak furcsa volt a dátum. Ha azt mondod ez így jó, akkor elfogadom és zárhatod az issue-t

Köszönöm

**Comment by NTCA-supporter** [comment]
Szia @Mocsa1974 !
Ez egy technikai adat, a külső adózói nyilvántartartó rendszerből így kaptuk ezeket a dátum mezőket.
Teendő vele nincs, így zárom az issuet.
Üdv

**Comment by csaszko** [comment]
> Szia @Mocsa1974 !
> Segíts kérlek, ezt miért gondolod hibának?
> Üdv

Szia @NTCA-supporter!

Te miért gondolod, hogy ez nem egy hiba?  Az igény megfogalmazásakor az volt a cél, hogy lehessen tudni, hogy az adott cégnek mikor változott utoljára bármi adata. 
@NTCA-developer válasza: 
https://github.com/nav-gov-hu/Online-Invoice/issues/73#issuecomment-574616514

https://github.com/nav-gov-hu/Online-Invoice/issues/146#issuecomment-589614292

A fentiekkel szemben most valami adatbázis update dátuma lehet és nem pedig az adózó adataiban bekövetkezett változás. 

> Ez egy technikai adat, a külső adózói nyilvántartartó rendszerből így kaptuk ezeket a dátum mezőket.
> Teendő vele nincs, így zárom az issuet.

A fent leírtak alapján igenis van vele teendő, kérem, hogy nyissátok vissza ezt az issuet és javítsátok az ígéreteknek megfelelően a működését.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Külső forrásból kapjuk az adózói törzsadatokat, így kicsit körülményesebb utánajárni, hogy miért így kaptuk az infoDate-et.
Természetesen utánajárok, így már értem a problémát.

Üdv

**Comment by csaszko** [comment]
Érdeklődni szeretnék, hogy ezzel mi a helyzet? Fogjátok tudni biztosítani a valós dátumot vagy nem? Szedjük ki ezt a fejlesztést a programokból?

**Comment by renced42** [comment]
Kedves @csaszko 

Dolgozunk rajta, remélhetően hamarosan kijavul a forrás rendszer felöl az adat és ismét jók leszünk.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Kérlek ellenőrizzétek, és jelezzetek vissza, hogy a valós infoDate-et adjuk-e vissza. Ahogy említettem, külső rendszerből kapjuk, így emiatt fontos a visszajelzés.

Köszönöm

**Comment by csaszko** [comment]
Szia!

Élesben nem jó, de teszten jó lehet annak a 2-3 cég esetében aminél most megnéztem. 

Köszi

**Comment by NTCA-supporter** [comment]
Szia @csaszko !
Csak az éles rendszer számít, ott lettek felülcsapva ezek az értékek.
Kérlek írj 1-2 példa adószámot, és az elvárt (biztosan helyes) infoDate értéket hozzájuk, hogy tudjunk nyomozni tovább.
Köszi

**Comment by csaszko** [comment]
Az élesben eddig nálam ami adózónál 2021-01-08 02:03:06 és 2021-01-10 02:59:08 közötti dátum szerepel az infó dátumnál az biztosan rossz volt. 

10586138 pl teszten ez a dátum van: <infoDate>1991-06-30T22:00:00.000Z</infoDate>
11540469 ennél a teszten ez van:   <infoDate>1996-12-31T23:00:00.000Z</infoDate>
13999773 teszt:  <infoDate>2007-09-28T22:00:00.000Z</infoDate>

Azért írtam a tesztes dátumokat, mert azok lehetnek a valósak, ezek mind 1000 éve működő. De ennél jóval több cégnél találkoztam rossz dátummal.

**Comment by Mocsa1974** [comment]
Sziasztok!

Én is megnéztem két céget az élesben. Mindkettőnél rossz dátum van megadva.
12111183
14893694

**Comment by NTCA-supporter** [comment]
Sziasztok!

Csak info, hogy ez hamarosan javulni fog, foglalkoztunk vele. Jelzek majd.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

Kérlek ellenőrizzétek az értékeket és jelezzetek vissza. Már nem kellene, hogy legyen probléma.

Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet, ha van még kérdés, kérlek nyissátok újra.
Üdv
