### ISSUE TITLE
[Q&A] Csoportos adóalanyiság számla sorszám ütközés

### ISSUE THREAD

**Issue by izll** [nav-gov-hu/Online-Invoice#702]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Kedves @NTCA-supporter!

Cégünk több csoporttaggal is számlázik és teszt számla beküldésénél kiderült, hogy az adatszolgáltatásnál a sorszámellenőrzésnél hiába van megadva a csoport tag adószáma is, ha azonos sorszámú számlák kerülnek beküldésre, akkor a "A megadott számla sorszámmal már történt adatszolgáltatás." hibát kapjuk. Ezt azon kívül, hogy előtagot rakunk a sorszám elé, ki lehet máshogy kerülni?

**Comment by NTCA-supporter** [comment]
Szia @izll !
Ugye az invoiceNumber egyediségvizsgálat az eladó adószámára vonatkozik, ami ilyenkor minden esetben a csoport adószáma, ezért kapod a hibát.
A számla sorszám megképzésének módja a kliens dolga, ehhez nem tudok hozzászólni, nyilván az előtag képzés is egy megoldás lehet.
Üdv

**Comment by izll** [comment]
Szia @NTCA-supporter !
És van értelme fejlesztési kérésnek felvenni, hogy csoportos adóalany esetén a csoport tagra történjen az egyediségvizsgálat?
Már csak azért is, mert közműszolgáltató vagyunk és több városban is szolgáltatunk, ugyanazt a programot haszáljuk és előbb-utóbb össze fognak futni a sorszámok. Viszont az előtag használata miatt egyrészt újra kell kezdeni a sorszámozást, másrészt mindenhol átírni a programot is horror.

**Comment by NTCA-supporter** [comment]
Szia @izll !

Szerintem ez olyan erős alapelv, hogy eladóra nézzük a számlasorszám egyediséget.
@NTCA-tax -ra átteszem ezt az issuet, ő szakmai oldalról többet tud hozzátenni.
Üdv

**Comment by izll** [comment]
Szia @NTCA-supporter !

Köszönöm!

Üdv

**Comment by laladisc** [comment]
Ebbe mi is belefutottunk az egyik ügyfelünknél még 2018-ban, és az egyetlen megoldás az egyedi sorszámozás lett. Onnantól kezdve, hogy csoportos adóalany egy vállalkozás minden számla a csoportos adószámára fut össze az Online számla rendszerben és az áfa bevallásban is.

**Comment by NTCA-tax** [comment]
Áfa törvény oldaláról az adóalany a csoport és nem a csoporttag. Az áfa törvény pedig az adóalanyon belül várja el azt, hogy a számlasorszám egyértelműen azonosítson egy számlát. Így jogszabályi oldalról nem tudom megerősíteni, hogy ha ez csoporttag vonatkozásában igaz csak, akkor az megfelelő megoldás lenne.

**Comment by izll** [comment]
Szoa @NTCA-tax !

Köszönöm az információt!

Üdv
