### ISSUE TITLE
ELőleg folyamat

### ISSUE THREAD

**Issue by kurucza** [nav-gov-hu/Online-Invoice#703]
Sziasztok, 

Valaki ismeri közületek a  SAP standard online számla megoldását (Edocument Framework)?
Clearingelt előleg számla beküldés megoldás lenne érdekes, mivel SAP oldali megoldás nincs, ezért saját fejlesztésre van szükség.
(az is nehezíti a dolgot, hogy a fejlesztők nem Magyarországon vannak – multi cég lévén). Most, hogy minden számlát be kell küldeni NAV felé, elég égető lett a probléma, hogy megoldást találjunk erre a problémára. 

Köszi, ha tudtok segíteni

Andi

**Comment by NTCA-tax** [comment]
@kurucza Ezt a kérdést lehet, hogy nem jó fórumra tetted fel. Adóhivatali oldalról biztosan nem fogunk tudni Neked SAP fejlesztési javaslatokat adni...
