### ISSUE TITLE
[Q&A] Közösségen belüli termékértékesítés-előleg 

### ISSUE THREAD

**Issue by Amn3s1a2018** [nav-gov-hu/Online-Invoice#704]
A példák között csak belföldi előleget találtam.
A [https://onlineszamla.nav.gov.hu/api/files/container/download/Online_Szamla_interfesz%20specifikacio_HU_v3.0.pdf](dokumentáció) 119. oldalán felsorolt típusok között nem találtam egyet sem ami erre illene.
Eredetileg a normál termékértékesítéssel azonos módon akartuk jelenteni az előleget és az előleg kivezetést is, azonban közösségen belüli esetben az előleg értékét nem kell jelenteni az áfabevallásban sem, így mégsem kezelhetjük azonos módon.
A könyvelőnek a vatExemption/case NAM használatát javasolták, amit szintén valami „egyéb”-nek tűnik.

**Comment by Macskafarka** [comment]
Közösségen belüli termékértékesítéshez kapott előleg NEM tartalmazhatja a "a fizetendő adó arányos összegét" Áfa tv. 59.§ (2) bek, ezért nem kell róla számlát kiállítani. Így nem értelmezhető a végszámlába betudott előleg fogalma sem közösségi értékesítéskor.  Mivel a közösségi előlegről nem lehet számlát kiállítani (hanem más szigorú számadású bizonylatot kell), ezért nem szerepelhet az ilyen előleg a számaadat-szolgáltatásban sem, és az áfa bevallásban sem.
A termékértékesítésről szóló közösségi számlán nem szerepelhet az előleg, a számla tételsorainak csak magának a termékértékesítő sorai lehetnek, előleg "kivezetés" fogalmilag kizárt.
Ezen okok miatt nem szerepel sem az Áfa bevallásban, sem az xxA60-as bevallásban előlegre utaló sor, mező hivatkozás.
Sajnálom, hogy ezeken a nehéz kérdéseken először a fejlesztőknek kell átrágniuk magukat. 
Szóval jó a sejtésed, eltérően kell bizonylatolni, mint a belföldi előlegnél amúgy már közismert gyakorlat lenne.
Közösségi előlegről nem állíthatsz ki számlát, a közösségi termékértékesítésről szóló számlába nem tudhatsz be előleget.
Ebből is látszik, hogy nálunk mennyire ki van fordítva a belföldi előleg bizonylatolása, hogy sokan már ezt tekintik normálisnak, pedig a magyar előleg bizonylatolás a kakukktojás.

**Comment by Macskafarka** [comment]
3 féle előleg bizonylatolás létezik:
Első, amikor belföldi egyenes áfához adnak előleget (ekkor van az áfás előlegszámla + áfás végszámlába betudó előlegsor)
Második: Belföldi áfa alanyok között bizonyos termékek esetén értelmezett fordított áfás értékesítéshez kapott előleg (ez nem tartalmaz áfás, és a vevőnek sem kell áfát felszámolnia, azonban ezt be lehet tudni a végszámlába
Harmadik: Közösségi értékesítéshez kapott előleg. Itt az előleg nem számlával bizonylatolandó, és a "végszámla" sem igazi végszámla, hanem egyszerű termékértékesítésről szóló számla, mintha nem is lenne előleg.
Állítom, hogy mi a világ legbonyolultabb áfa rendszertét működtetjük.

**Comment by laladisc** [comment]
Na ez a téma engem is nagyon érdekel. Az én ügyfélkörömben is előfordul közösségen belüli előleg. Nagyon kíváncsi vagyok, @NTCA-tax válaszára a témával kapcsolatban.

**Comment by nbeeps2** [comment]
@Macskafarka : Nagyon sokszor hallom/olvasom ezt, hogy nem kell számlát kiállítani csak más szigorú sorszámadású bizonylatot, így az alábbi kérdésem lenne:

Tegyük fel egy sima felhasználó vagyok. Van egy számlázó programon, ami mondjuk semmi mást nem tud készíteni csak számlát. Minden kiállított számla a program felküld a NAV-nak. Akkor mit tegyek? Hogyan állítsak ki szigorú sorszámadású számlát? Milyen programmal és mi a bizonylat neve?

**Comment by Macskafarka** [comment]
@nbeeps2 Egy "sima" számlázó programnak nem kell tudnia mást, mint számlát kiállítani és feladni a NAV-nak. Ha így adtad el, akkor ezt lehet a fejlesztőn számon kérni. Ebben az esetben az ügyfélnek más módon kell megoldania a "számviteli bizonylat" kiállítását.
Ha meg tudod oldani, hogy a programoddal készíts olyan szigorúan sorszámozott bizonylatokat, amelyek nem számlák, és ezeket eleve nem adod föl a NAV Online-ba, akkor ezt megteheted. Ugye ekkor más sorszámtartományt kell használni ezekhez a bizonylatokhoz, mint amit a számlánál használsz.
Ha ugyanazzal a programmal készít a felhasználó számlákat is, meg "nemszámlákat"  is, akkor bizony a felhasználóra kell bízni a választást. Persze ezt lehet szofisztikáltan is végezni, pl. bizonyos személyek, vagy értékesítési helyek esetén lehet választani, mások esetén nem, ha van jogosultsági rendszer, akkor azt is be lehet vonni ebbe stb.
A bizonylat neve a felhasználó jogértelmezésén is múlik, de lehet pl. "Számviteli Bizonylat", más célra "Díjbekérő", vagy "Előleg bekérő"  stb. Persze ezek mindegyike más-más sorszámtartományba kell essen.

**Comment by Macskafarka** [comment]
De akár hívhatod "Közösségi előleg átvételi bizonylat"-nak is, erre nincs konkrét megkötés.

**Comment by nbeeps2** [comment]
@Macskafarka : Értem. A díjbekérő valószínűleg azért nem lenne jó, mert az egész bizonylatnak úgy kell viselkednie, mint egy szigorú számadású bizonylatnak, vagyis gondolom a már kiállított bizonylat (díjbekérő) tartalma sem változhatna meg. Tehát a számviteli bizonylat minden tekintetben olyan, mint egy számla, csak nem számla és nem megy be a NAV-hoz. Én még nem láttam ilyen programot ;) feltételeztem, hogy jellemzően csak az integrált rendszerek területe, de mit tud tenni a hétköznapi felhasználó? Készít egy word dokumtumot? Nem lenne sokkal egyszerűbb, ha mindent számlát be lehetne küldeni a NAV-hoz, azt is, amire amúgy nem kíváncsiak, mert nem is kellett volna számlát kiállítani? Ha már így adódott, hogy mégis számla lett, akkor jó lenne, ha be lehet küldeni és ez sokak problémáját megoldaná....

**Comment by Macskafarka** [comment]
A mi számlázó programunk ilyen. Kb 10-12 éve ilyen. 
Igen, a számviteli bizonylat minden tekintetben **lehet** olyan, mint egy számla, csak nem számla és nem megy be a NAV-hoz.
A Word dokumentum akár jó lehet, csak valahogy meg kell oldani a "szigorú számadásba vétel"-t. D elehet nyomdai bizonylat is, olyan, mint pl. a pénztár bevét bizonylat (persze más mezőkkel). Ilyen készen nem árulnak, de készíttethető.
Amit írsz, és sokan írnak, hogy "nem lenne sokkal egyszerűbb, ha minden számlát be lehetne küldeni": Válaszom, de, egyszerűbb lenne, ha a fejlesztő szemmel pusztán technikai oldalt nézem.  
Azonban: Emlékezni kell arra, hogy a számlakiállítók és mi nem a NAV oldalán focizunk! Az a másik oldal. Szép dolog krokodilt simogatni, de azért az nem játék.  
Az én álláspontom: Egyetlen bittel sem szabad többet adni egy hatóságnak, mint amire joga van tudni. Klasszikus idézettel: "Bármit ad, minden felhasználható Ön ellen"

**Comment by Macskafarka** [comment]
Sok céget ismerek, amelyek nyomdával készítettnek sorszámozott bizonylat tömböket: Pl. Kapujegy, Szállítójegy, Betárazási bizonylat stb. Ezeknek a gyűjtőneve Számviteli bizonylat.

**Comment by NTCA-tax** [comment]
Közösségi értékesítéshez tartozó előlegről ténylegesen nem számlát, hanem számviteli bizonylatot kellene kiállítani. Az áfa törvény ennél az előleg típusnál nem írja elő a számla kiállítását, így erre vonatkozóan nincs adatszolgáltatási kötelezettséged sem. Ez akkor is igaz, ha a program ráírja azt a számlára, hogy "Előleg számla", ugyanis egy számviteli bizonylat megnevezése is lehet az, hogy "számla". 

Amennyiben mégis beküldi a programod a közösségi értékesítés előlegét adatszolgáltatásként, akkor befogadjuk, warningot sem adunk rá.
