### ISSUE TITLE
Szállítási cím megadásának lehetősége - elektronikus számla xml miatt[FEATURE]

### ISSUE THREAD

**Issue by bmatyi94** [nav-gov-hu/Online-Invoice#706]
**Az igény összefoglalása / Summary of the request**
Jelenleg több dedikált mező is van a sémában, amely nem kötelező, viszont adatexport és xml mint számla esetében szükséges és hasznos lehet. A szállítási cím még egy nagyon gyakori eset, mely a számlákon szerepel, így javasolt lenne az xml-ben ennek a helyét is kialakítani.

**Az általam javasolt megoldás / The solution I propose**
invoiceHead csomopontón belül a customerInfo után, shippingInfo csomopónt ahol a shippingAddress megadható egyszerű és részletezett módon, hasonlóképpen a többi címadat esetében. Nem kötelező elemként, így aki nem szerepelteti, annak nem okoz módosítási igényt a programjában.

**Elfogadható alternatívák / Acceptable alternatives**
ConventionalInvoiceInfo részeként lenne megadható a shippingAddress

**Egyéb tartalom / Additional content**
Jelenleg az additionalInvoiceData részben alkalmas a feltüntetésre, viszont kereskedő cégeknél nagyon gyakori a szállítási cím feltüntetése a számlákon, és elektronikus számla xml esetében indokolt lenne egy dedikált mező.

**Comment by DrotosTot** [comment]
Erre analóg lehet a számla postázási címe is, csak félek, hogy a járulékos adatok miatt az adatszolgáltatás már akkorára fog hízni, hogy elveszti eredeti célját. :-)

**Comment by NTCA-tax** [comment]
Amennyiben az általad javasolt irányba mennénk el, hogy legyen dedikált mező, akkor az sémaváltoztatással járna, ami nem feltétlenül jelentene osztatlan sikert mindenki számára. Így megoldásként jelenleg csak az additionalData-t tudom én is javasolni, ahol bármilyen adattal kiegészíthető az adatszolgáltatás/eszámla adattartalma.
