### ISSUE TITLE
INVALID_SUMMARY_VAT_EXEMPTION_CODE : UNKNOWN probléma

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#708]
ERROR/INVALID_SUMMARY_VAT_EXEMPTION_CODE : Érvénytelen adómentességi kód! (Számla fej : InvoiceData/invoiceMain/invoice/invoiceSummary/summaryNormal/summaryByVatRate/vatRate/vatExemption/case = UNKNOWN)"

requestId :  LBR_20210113_10374121

Mi a probléma? Doksi szerint UNKNOWN az használható érték.

Köszönöm.

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !
Most épp nem tudom nézni, de annyit tudok hogy olyan esetben használhatod ha a CREATE számla 3.0 előtti, vagy nem történt róla adatszolgáltatás.
Üdv

**Comment by EPluribusUnum** [comment]
@NTCA-supporter , valóban ez volt a probléma. Zárom
