### ISSUE TITLE
Adóbevallás automatizálása

### ISSUE THREAD

**Issue by mnkpmg** [nav-gov-hu/Online-Invoice#709]
Érdeklődni szeretnék, hogy adóbevallás (2165, 21A50) automatizálása lehetséges-e az XML API-on keresztül? Ha igen, akkor ez tud működni más cég nevében is?

**Comment by EPluribusUnum** [comment]
@mnkpmg , képtlenség ÁFA bevaállást készíteni csak a mostani NAV-OSZ xml adatai alapján. Alapvető fontosságú adatok hiányoznak hozzá. Ez csak egy üres marketing szöveg amivel próbálják eladhatóbbá tenni a NAV-OSZ-t.

**Comment by renced42** [comment]
Kedves @mnkpmg Nem lehet. Ha lesz is ilyen lehetőség, később azt nem az Online Számla rendszeren keresztül lehet majd megoldani.

**Comment by NTCA-supporter** [comment]
Zárom az issuet. Ha van még kérdés nyissátok újra.
Üdv
