### ISSUE TITLE
[Q&A] saját külföldi adószámra irányuló ügylét jelentési kötelezettsége

### ISSUE THREAD

**Issue by janisoft** [nav-gov-hu/Online-Invoice#710]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

A vállalkozásomnak a magyar adószáma mellett van külföldi adószáma is. Az áru mozgását cégen belül egyik adószámról a másikra az ÁFA és az összesítő bevallásban is jelenteni kell, de elvileg tudtommal erre a tranzakcióra nincs számlakiállítási kötelezettség. Kell-e jelenteni az onlineszámla adatszolgáltatásban az ilyen jellegű ügyleteket.

**Comment by Macskafarka** [comment]
@janisoft  Komolyan az a kérdésed, hogy amit nem kell számlával bizonylatolni, azt  kell-e a szerepeltetni a számlaadat-szolgáltatásban? Az Áfa tv. 10. számú mellékletének 1. pontjában van a válasz....

**Comment by NTCA-tax** [comment]
Itt pontosan arra kell megtalálnod a választ, hogy szükséges-e az adott ügyletnél a számla kiállítása. Amennyiben igen, akkor van adatszolgáltatási kötelezettséged, amennyiben nem, akkor nincs. Az utóbbi esetben viszont számviteli bizonylatot ki kell állítanod.
