### ISSUE TITLE
[Q&A] querytaxpaxer infodate újra

### ISSUE THREAD

**Issue by csaszko** [nav-gov-hu/Online-Invoice#711]
Sziasztok!
Mivel a probléma nem oldódott meg, de lezártátok a korábbit és nem tudom, hogy nézitek-e ezeket, ezért létrehoztam egy új issue-t. 

https://github.com/nav-gov-hu/Online-Invoice/issues/701

**Comment by NTCA-supporter** [comment]
Visszanyitottam azt, folytassuk ott.
