### ISSUE TITLE
Getting error while parsing the invoiceData.xsd

### ISSUE THREAD

**Issue by AmrutaK1** [nav-gov-hu/Online-Invoice#712]
src-resolve: Cannot resolve the name 'common:AtomicStringType15' to a(n) 'type definition' component.
  line 16 of file:/D:/Schema_v3/invoiceData.xsd
src-resolve: Cannot resolve the name 'base:TaxNumberType' to a(n) 'type definition' component.
  line 817 of file:/D:/Schema_v3/invoiceData.xsd

**Comment by AmrutaK1** [comment]
Above errors are received while parsing the invoiceData.xsd. Can you please help?

**Comment by elHomomomo69** [comment]
Have the exact same problem with eclipse using jaxb

https://www.javawebtutor.com/articles/jaxb/jaxb_java_class_from_xsd.php

The only way to parse it properly is to "merge" the common file with the file you want parse, like this


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.nav.gov.hu/OSA/3.0/data" xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:base="http://schemas.nav.gov.hu/OSA/3.0/base" targetNamespace="http://schemas.nav.gov.hu/OSA/3.0/data" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://schemas.nav.gov.hu/NTCA/1.0/common"/>
	<xs:import namespace="http://schemas.nav.gov.hu/OSA/3.0/base"/>
	<xs:simpleType name="AtomicStringType100">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Atomi string típus 100 hosszra</xs:documentation>
			<xs:documentation xml:lang="en">Atomic string type for 100 length</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AtomicStringType1024">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Atomi string típus 1024 hosszra</xs:documentation>
			<xs:documentation xml:lang="en">Atomic string type for 1024 length</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="1024"/>
		</xs:restriction>
	</xs:simpleType>

but afterwards, the generated XML does not look like the example tokenExchange.xml, it looks like this
<TokenExchangeRequest xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common">
    <header>
        <requestId>9045</requestId>
        <timestamp>2021-01-15T12:28:36.008Z</timestamp>
        <requestVersion>3.0</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
...

example file
<TokenExchangeRequest _xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common"_ xmlns="http://schemas.nav.gov.hu/OSA/3.0/api">
	<_common_:header>
		<common:requestId>RID896801578348</common:requestId>
		<common:timestamp>2019-09-11T10:55:31.440Z</common:timestamp>
		<common:requestVersion>3.0</common:requestVersion>
		<common:headerVersion>1.0</common:headerVersion>
	</common:header>

**Comment by renced42** [comment]
Dear @AmrutaK1 @elHomomomo69 

You can find the proper solution in issue #539

**Comment by elHomomomo69** [comment]
OK thanks a lot, the parsing was succesfully, but my problem is still prominent.
The tokenrequest looks like this:

> <TokenExchangeRequest xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common">
>     <header>
>         <requestId>9046</requestId>
>         <timestamp>2021-01-15T12:58:35.901Z</timestamp>
>         <requestVersion>3.0</requestVersion>
>         <headerVersion>1.0</headerVersion>
>     </header>

and get the error

`<?xml version="1.0" encoding="utf-8" standalone="yes"?><ns2:generalerrorresponse xmlns="http://schemas.nav.gov.hu/ntca/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/osa/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/osa/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/osa/3.0/data"><result><funccode>error</funccode><errorcode>invalid_request</errorcode><message>helytelen kérés!</message></result><ns2:technicalvalidationmessages><validationresultcode>error</validationresultcode><validationerrorcode>schema_violation</validationerrorcode><message>request body contains on line: [2] and column: [73] error: [cvc-elt.1.a: cannot find the declaration of element 'tokenexchangerequest'.]</message></ns2:technicalvalidationmessages><ns2:technicalvalidationmessages><validationresultcode>error</validationresultcode><validationerrorcode>schema_violation</validationerrorcode><message>request body contains on line: [2] and column: [73] error: [unexpected element (uri:"http://schemas.nav.gov.hu/ntca/1.0/common", local:"tokenexchangerequest"). expected elements are &lt;{http://schemas.nav.gov.hu/osa/3.0/api}manageannulmentrequest&gt;,&lt;{http://schemas.nav.gov.hu/osa/3.0/api}manageinvoicerequest&gt;,&lt;{http://schemas.nav.gov.hu/osa/3.0/api}queryinvoicechaindigestrequest&gt;,&lt;{http://schemas.nav.gov.hu/osa/3.0/api}queryinvoicecheckrequest&gt;,&lt;{http://schemas.nav.gov.hu/osa/3.0/api}queryinvoicedatarequest&gt;,&lt;{http://schemas.nav.gov.hu/osa/3.0/api}queryinvoicedigestrequest&gt;,&lt;{http://schemas.nav.gov.hu/osa/3.0/api}querytaxpayerrequest&gt;,&lt;{http://schemas.nav.gov.hu/osa/3.0/api}querytransactionlistrequest&gt;,&lt;{http://schemas.nav.gov.hu/osa/3.0/api}querytransactionstatusrequest&gt;,&lt;{http://schemas.nav.gov.hu/osa/3.0/api}tokenexchangerequest&gt;]</message></ns2:technicalvalidationmessages></ns2:generalerrorresponse>`

is this because the "common" is missing as in the example showed?

`
> <TokenExchangeRequest xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns="http://schemas.nav.gov.hu/OSA/3.0/api">
> 	<common:header>
> 		<common:requestId>RID896801578348</common:requestId>
> 		<common:timestamp>2019-09-11T10:55:31.440Z</common:timestamp>
> 		<common:requestVersion>3.0</common:requestVersion>
> 		<common:headerVersion>1.0</common:headerVersion>
> 	</common:header>
`

**Comment by renced42** [comment]
Dear @elHomomomo69 
Your request is not correct

Your request should be like this:

`<?xml version="1.0" encoding="UTF-8"?>
<TokenExchangeRequest xmlns="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common">
  <common:header>
    <common:requestId>RIDSe1Bp4Hh4Bb7Cc8S9Zd6Fh0Ri0</common:requestId>
    <common:timestamp>2021-01-18T08:31:40.797Z</common:timestamp>
    <common:requestVersion>3.0</common:requestVersion>
    <common:headerVersion>1.0</common:headerVersion>
  </common:header>
  <common:user>
    <common:login>whatever</common:login>
    <common:passwordHash cryptoType="SHA-512">47C4A1D2A88A55D7F68A4F390117C7571880195C22B1C3392CC7AB6F213E56F345FD4416FAB8995EECB5729ACDA5212F5C4A8F179197BB11FC6B2A411286BF1D</common:passwordHash>
    <common:taxNumber>39999993</common:taxNumber>
    <common:requestSignature cryptoType="SHA3-512">A50A1668DB2850FB4EER24610D57906B30DC1A73EEB822D2881D9F0D3604FE14359335E15B88D844FA776D403406CC27E9E70A9B7D1D09D49AB84CB096266B9D</common:requestSignature>
  </common:user>
  <software>
    <softwareId>123456789123456789</softwareId>
    <softwareName>NAV Online Invoice Test tool</softwareName>
    <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
    <softwareMainVersion>1.0</softwareMainVersion>
    <softwareDevName>Your name</softwareDevName>
    <softwareDevContact>rencenji.denes@nav.gov.hu</softwareDevContact>
    <softwareDevCountryCode>HU</softwareDevCountryCode>
    <softwareDevTaxNumber>12345678</softwareDevTaxNumber>
  </software>
</TokenExchangeRequest>`

**Comment by elHomomomo69** [comment]
Well, yes I know, but this is the problem, I generated the classes automatically via JAXB with the xsd files as sources, and this is what i get when the java classes are generated...

Do someone has created the packages with working classes/package_infos?

So something is wrong with the xsd files or I am doing something wrong. How to change the classes for correct output?
I tried a lot with help from 

http://blog.bdoughan.com/2010/08/jaxb-namespaces.html
http://blog.bdoughan.com/2012/07/jaxb-and-root-elements.html
http://blog.bdoughan.com/2010/08/jaxb-namespaces.html

but did not get a proper result.
Any help is appreciated, did not have any problems like this in version 2.0, the generated requests were fine.

**Comment by renced42** [comment]
Dear @elHomomomo69 

Maybe you can try this in package-info files in generated packages

Example:

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.nav.gov.hu/NTCA/1.0/common", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = { @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://schemas.nav.gov.hu/NTCA/1.0/common", prefix = "common") })

**Comment by elHomomomo69** [comment]
Well yes, looks quite better. I have tried this

```
@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.nav.gov.hu/NTCA/1.0/common", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, 
									xmlns = { @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://schemas.nav.gov.hu/NTCA/1.0/common", prefix = "common"),
											  @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://schemas.nav.gov.hu/OSA/3.0/api", prefix = "")})
```

the result is this

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<common:TokenExchangeRequest xmlns="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common">
    <common:header>
        <common:requestId>9065</common:requestId>
        <common:timestamp>2021-01-18T09:19:54.708Z</common:timestamp>
        <common:requestVersion>3.0</common:requestVersion>
        <common:headerVersion>1.0</common:headerVersion>
    </common:header>
    <common:user>
        <common:login>pziq0uluo0msfnz</common:login>
        <common:passwordHash cryptoType="SHA-512">hash</common:passwordHash>
        <common:taxNumber>10949315</common:taxNumber>
        <common:requestSignature cryptoType="SHA3-512">hash</common:requestSignature>
    </common:user>
    <common:software>
        <common:softwareId>id</common:softwareId>
        <common:softwareName>name</common:softwareName>
        <common:softwareOperation>LOCAL_SOFTWARE</common:softwareOperation>
        <common:softwareMainVersion>2.0</common:softwareMainVersion>
        <common:softwareDevName>devname</common:softwareDevName>
        <common:softwareDevContact>contact</common:softwareDevContact>
    </common:software>
</common:TokenExchangeRequest>

```

so the token TokenExchangeRequest  is now wit "common" too and the software too, which should not be. So does anyone has generated this classes with the xsd files in a correct way? Thanks

**Comment by renced42** [comment]
Dear @elHomomomo69 

I create a saple project:
0.) Create a project (for example: c:\mywork\OSA_XSD_TEST\Project1\src\)
1.)Copy every xsd file into one folder (for example here C:\temp\xsdsource\)
2.) run this command:
c:\Program Files\Java\jdk1.8.0_231\bin>xjc.exe -d c:\mywork\OSA_XSD_TEST\Project1\src\ C:\temp\xsdsource\invoiceApi.xsd
3.) Project
![image](https://user-images.githubusercontent.com/44041065/104908457-c923fa00-5986-11eb-8bf6-22a34482316d.png)
4.) Under common package modify the package-info.java file

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.nav.gov.hu/NTCA/1.0/common", elementFormDefault = javax.xml
                                                                                                                        .bind
                                                                                                                        .annotation
                                                                                                                        .XmlNsForm
                                                                                                                        .QUALIFIED,
                                     xmlns = { @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://schemas.nav.gov.hu/NTCA/1.0/common", prefix = "common")
    })
package hu.gov.nav.schemas.ntca._1_0.common;
 
See the attached project.

[src.zip](https://github.com/nav-gov-hu/Online-Invoice/files/5829848/src.zip)

**Comment by elHomomomo69** [comment]
> Dear @elHomomomo69
> 
> You generated the classes into one folder?

Hi, yes this was the old structure from 1.0, and 2.0. With 3.0 I tried the same and well yes, seems it will not work.

> I create a saple project:
> 0.) Create a project (for example: c:\mywork\OSA_XSD_TEST\Project1\src)
> 1.)Copy every xsd file into one folder (for example here C:\temp\xsdsource)
> 2.) run this command:
> c:\Program Files\Java\jdk1.8.0_231\bin>xjc.exe -d c:\mywork\OSA_XSD_TEST\Project1\src\ C:\temp\xsdsource\invoiceApi.xsd
> 3.) Project
> image
> 4.) Under common package modify the package-info.java file
> 
> @javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.nav.gov.hu/NTCA/1.0/common", elementFormDefault = javax.xml
> .bind
> .annotation
> .XmlNsForm
> .QUALIFIED,
> xmlns = { @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://schemas.nav.gov.hu/NTCA/1.0/common", prefix = "common")
> })
> package hu.gov.nav.schemas.ntca._1_0.common;

I will give it a try, looks promising. Thanks

**Comment by elHomomomo69** [comment]
Holy moly it worked!

Okay, the generated xml is not 100% the same

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:TokenExchangeRequest xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api">
    <common:header>
        <common:requestId>9068</common:requestId>
        <common:timestamp>2021-01-18T12:34:59.992Z</common:timestamp>
        <common:requestVersion>3.0</common:requestVersion>
        <common:headerVersion>1.0</common:headerVersion>
    </common:header>
    <common:user>
        <common:login>login</common:login>
        <common:passwordHash cryptoType="SHA-512">hash</common:passwordHash>
        <common:taxNumber>12345678</common:taxNumber>
        <common:requestSignature cryptoType="SHA3-512">hash</common:requestSignature>
    </common:user>
    <ns2:software>
        <ns2:softwareId>id</ns2:softwareId>
        <ns2:softwareName>name</ns2:softwareName>
        <ns2:softwareOperation>LOCAL_SOFTWARE</ns2:softwareOperation>
        <ns2:softwareMainVersion>3.0</ns2:softwareMainVersion>
        <ns2:softwareDevName>devname</ns2:softwareDevName>
        <ns2:softwareDevContact>contact</ns2:softwareDevContact>
    </ns2:software>
</ns2:TokenExchangeRequest>
```

but it seems that the server is accepting it, next error is by manageInvoice but this is clear, I have used an XML2.0 xml file for testing purposes, error as expected.

Thanks a lot!

So solution is: 

do not parse it in your own project hierarchy, let it parse "for itself" so structure is like in your example.
Next was modify package-info.java file in the common package like described in 4.!

Thanks a lot!

**Comment by renced42** [comment]
dear @AmrutaK1 
If you don't have any further question please close the issue.
Thanks!
