### ISSUE TITLE
[DEV support] INVALID_USER_RELATION

### ISSUE THREAD

**Issue by hosszuful** [nav-gov-hu/Online-Invoice#713]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[x] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
1012831

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Üdv! Tokenkérésre a következő üzenetet kapom: INVALID_USER_RELATION 
A doksi nem tartalmaz erre vonatkozóan releváns információt, így szeretném megkérdezni, hogy hogyan tudom javítani a hibát?
köszi
*Egyéb tartalom / Additional content*

**Comment by bcdel** [comment]
onlineszamla doksi 175-176 page (164-165 oldal) 8-as pontjai:
8 HTTP 500 INTERNAL_SERVER_ERROR GeneralErrorResponse XML tag ERROR INVALID_USER_RELATION 1.0
8 a kérésben szereplő entitások között nincs kapcsolat | A megadott adószámhoz nem tartozik a megadott login névvel technikai felhasználó, vagy a felhasználó státusza már nem engedélyezi a művelet elvégzését. Meg kell győződni az adatok helyességéről, szükség esetén fel kell venni a kapcsolatot az érintett adózóval.
HTH

**Comment by hosszuful** [comment]
A OnlineInvoiceTool-ba beírva felhasználót, jelszót, cserekulcsot, aláírókulcsot nem mond hibát, tehát elvileg az adatoknak jónak kell lennie.

**Comment by hosszuful** [comment]
A kollégák átírták alattam az adatokat.... nincs hiba, bocsi, köszi
