### ISSUE TITLE
Helyesbítő számla sztornózása után hibaüzenet a sztornó számla beküldésekor

### ISSUE THREAD

**Issue by GidroTamas** [nav-gov-hu/Online-Invoice#715]
Sziasztok!

Az alábbi problémával kapcsolatban szeretnénk segítséget kérni.

3 számla kerül kiállításra a rendszerben, az alábbi módon:
1. Egy normál vevői számla kerül kiállításra, HUF devizával, M.o. cég számára. 
2. Utána erre a számlára kiállításra kerül egy helyesbítő számla.
3. Végül a helyesbítő számla sztornózásra kerül.

A probléma: A helyesbítő számla beküldése után, az alábbi hibaüzenetet kapjuk:
"INVALID_INVOICE_REFERENCE	A módosítás vagy érvénytelenítés olyan okiratra hivatkozik, amire vonatkozóan nem történt adatszolgáltatás."
Ellenőriztük a teszt rendszerben, és a normál vevői számla, és a hozzá kapcsolódó sztornó számla esetén is a "Státusz" az "rendben" a NAV teszt rendszerében. A helyesbítő számla esetén pedig a "státusz" a "megszakítva".
Nem tudjuk, hogy mi okozza ezt a problémát, mert ha simán sztornózunk egy normál vevői számlát, akkor gond nélkül be tudjuk küldeni, és ott "rendben" lesz a státusza a sztornó számlának.

**Comment by topybear** [comment]
A "sztornó" - ami egyébként ugyanúgy módosító - melyik számlára hivatkozik? Ugye nem az első helyesbítőre? Mert minden esetben az alapszámla kerül módosításra.

**Comment by NTCA-supporter** [comment]
@GidroTamas az lesz a gond, amit előttem írtak. A "normál vevői" számlára hivatkozz.
Üdv

**Comment by GidroTamas** [comment]
Köszönjük a segítséget. Megnézzük, h. ez volt-e a probléma, utána jelzem, h. ez megoldotta-e a problémát.

**Comment by NTCA-supporter** [comment]
Zárom az issuet. Ha fennáll még a probléma, nyisd újra kérlek.
Üdv
