### ISSUE TITLE
[Q&A] Forintos, készpénzes számla ÁFA tartalom számítás és beküldés

### ISSUE THREAD

**Issue by zonehun** [nav-gov-hu/Online-Invoice#716]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Eddig vagy nem jött ilyen WARN, vagy csak mi nem futottunk bele, de az alábbi a szimptóma.

Van egy 100 Forint nettó + 27 % áfás számla. Ennek a végösszege 127 Ft. Ugyanakkor, ha ezt a magyar ember készpénzben fizeti, akkor a rendszer 125 Ft-ra kerekíti a magyar bankjegyeink, érméink miatt.

Mi most úgy működünk, hogy a tételsorban megjelenítjük a 100 Ft-os, a 27%-os áfa kulcsot a 27 Ft áfa értéket és a 127 Ft bruttó értéket.
A számla összesítőjében megjelenítjük, hogy a számlaérték 100 Ft, az áfa érték 27 Ft, a fizetendő pedig 125 Ft!

Az ÁFA összesítőben pedig áfa kulcsra bontottan a nettó 100 Ft, 27 Ft áfa és 127 Ft bruttó szerepel.

Az OnlineSzámlába történő beküldés WARN dobott a 125 Ft-os számla végértékre - ami egyrészt talán érthető, de másrészt nem.
1. Érthető, mert a végösszeg valóban nem egyezik a kiszámított értékkel (100 + 27 = 127 és nem 125)
2. Nem érthető, mert a NAV is tudja, hogy 5 forintos kerekítés van. Tehát a boltos nem 127 forintot vesz el, hanem 125-öt

Kérlek segítsetek, hogy mi a jogilag helyes eljárási  mód a fenti példa kapcsán, forintos, készpénzes számlák esetében, hogy a WARN-t javítani tudjuk.

Előre is köszönöm!

**Comment by sinick2** [comment]
Ld. 2008. évi III. törvény. Az egész öt forintról szóló téma nem az öt forintra való átszámításról szól, hanem arról, hogy mit tegyünk akkor, ha a számla, nyugta, számviteli bizonylat, sorsjegy, stb értéke nem öt forinttal oszthatóra végződik. Ilyenkor fizetéskor kerekítést kell alkalmazni, aminek feltüntetése bizonylaton nem kötelező. A számla végösszege 100 adóalap érték 27 adóérték, azaz 127 adóval növelt érték. A 125 forint viszont a pénzügyileg rendezett összeg adat. Röviden: a számla értéke 127 forint, ami 125 forinttal. (Nálam pl. négy adat van a készpénzes számlán. Nettó 100, áfa 27, bruttó 127, és fizetendő 125)

**Comment by zonehun** [comment]
@sinick2 köszi a választ! Ha jól értem, akkor amikor a számlát beküldöd, végül is a normál számított összeget küldöd be. A fizetendő KP pedig nem megy be a NAV-nak?

**Comment by Macskafarka** [comment]
@sinick2 -vel egyetértek. A kerekítés nem a számlára szól, hanem a készpénzzel való kiegyenlítésre, vagyis a pénztári mozgásra.  Olyannyira nem a számlára, hogyha készpénz helyettesítővel történik, arra sem vonatkozik. A számlát küldöd be a NAV-nak, a fizetendő összeget nem.
Nem is értem, miért foglalkoznak a kiegyenlítés módjával sokan annyit.
A számlának nem kötelező eleme az,, hogy mi módon fizetik (MAJD esetleg) ki. A számlára ráírt fizetési mód a számlakiállító reményét fejezi ki, ettől még a vevő akkor és úgy fizet, ahogy akar.  Átutalja, beszámítja, kompenzálja, utalvánnyal, készpénz helyettesítővel fizeti ki stb.

**Comment by zonehun** [comment]
@Macskafarka, köszönöm.

A kérdéssel sztem azért foglalkozunk, mert bugyuták a szabályok. Adót fizetek 100 Ft után 27 Ft-ot (meg egyebeket). Ezt vallom be. De valójában 125 Ft-ot kaptam... mindegy, nem vagyok könyvelő, csak fejlesztő :)

Köszönöm az információkra, ez alapján picit módosítunk a rendszeren. Témát zárom.
