### ISSUE TITLE
Közösségi adószámmal nem rendelkező EU-s ügyfél

### ISSUE THREAD

**Issue by pbalazs1** [nav-gov-hu/Online-Invoice#717]
Hogyan kell bejelenteni olyan közösségi ügyfélnek kiállított számlát, 
amelynek nincs közösségi adószáma, csak saját országbéli adószáma.
A specifikációban nem találtam erre vonatkozó előírást.
Határállomáson tevékenykedő ügyfelem jelezte hogy lehet ilyen esete is.

**Comment by nbeeps2** [comment]
Szerintem: customerVatStatus OTHER, és ha akarod (de nem kötelező), akkor kitöltöd a thirdStateTaxId-t.
Ha valakinek nincs közösségi adószáma, akkor nem közösségi ügyfél! Attól lesz közösségi ügyfél, hogy van közösségi adószáma.

**Comment by betasofthu** [comment]
Véletlenül nem külföldi magánszemély az ügyfeled?

**Comment by pbalazs1** [comment]
Nem magánszemély az ügyfél, hanem cég.

**Comment by Macskafarka** [comment]
Ahogy @nbeeps2 és @pbalazs1 mondta: Közösségi a számla vagy akkor, ha a teljesítés helye a közösség másik tagállama és a vevő magánszemély (ennek vannak még egyéb feltételei is) , vagy akkor, ha a teljesítés helye a közösség másik tagállama és a nem természetes személy vevőnek VAN közösségi adószáma.
Ha a nem természetes személy vevőnek nincs közösségi adószáma, akkor az nem közösségi értékesítés, a customerVatStatus OTHER

**Comment by NTCA-tax** [comment]
Ezt a kérdést a következő issue-ban rendesen átbeszéltük: https://github.com/nav-gov-hu/Online-Invoice/issues/740

Amennyiben lenne még kérdés, akkor abban az issue-ban tedd fel.
