### ISSUE TITLE
[Q&A] Módosítás módosítása

### ISSUE THREAD

**Issue by idarph** [nav-gov-hu/Online-Invoice#718]
https://onlineszamla.nav.gov.hu/api/files/container/download/Online_Szamla_interfesz%20specifikacio_HU_v3.0.pdf

147. oldal (2.5 fejezet)

"Jogszabály nem tiltja, hogy egy számlára vonatkozóan több módosító okirat is kiállításra kerüljön."
és
"Nincs lehetőség módosító okirat módosítására. Az Áfa törvény alapján, ha a módosító okirat téves adatokkal került kiadásra, akkor ennek esetleges módosítása az eredeti számla újabb módosításának tekintendő és ennek megfelelően is kell róla adatot szolgáltatni."

Tehát az Áfa tv. alapján minden módosítást az eredeti számlára kell vonatkoztatni.

153. oldal (2.5.7 fejezet)
"Ugyanazon számla többszöri módosítása alkalmával az egyes módosító okiratokról adott adatszolgáltatást mindig azon adatkörre vonatkozóan kell megtenni, ami az előző állapothoz képest módosul az adott okirattal"

Tehát bejelnteni nem azt kell, ami az eredeti számlához képest változott, hanem ami az előző módosító okirathoz képest változott.

Q: Hogyan néz ki egy ilyen bejelentés (xml példa), pl.: 2-3 ugyanazt a tételsort mennyiségben és értékben módosító módosító okirat, milyen adatok szerepelnek a invoiceSummary tagekben?

Egy példa egy 1 tételsoros számla segítségével:
Eredeti számlán az összérték nettó 100 Ft, bejelentve 100 Ft
1. módosítóval az összeérték nettó 120 Ft, bejelentve 20 Ft (120-100)
2. módosítóval az összeérték nettó 130 Ft, bejelentve (10 Ftvagy 30 Ft) ?

Q: a fenti példa szerint a 2. módosítás alkalmával, papír alapú számlánál mit kell a számlára nyomtatni és mit kell bejelenteni?

**Comment by NTCA-tax** [comment]
A módosító számla és az adatszolgáltatás összegei megegyeznek. A példában szereplő esetet többféle módon is tudod kezelni, ez alapvetően számla adattartalmi kérdés, de a végeredmény ugyanaz.

1. módosító számla:
Nettó érték +20 Ft, adatszolgáltatásnál +20 Ft
(másik megoldás, hogy két tételsort készítesz, egy -100 Ft, a következő +120 Ft)

2. módosító számla:
Nettó érték +10 Ft, adatszolgáltatásnál +10 Ft
(másik megoldás, hogy két tételsorban -120 Ft, +130 Ft)

A módosító számlán az összegszerű módosítás hatásának mindenképpen ki kell derülnie.

**Comment by NTCA-tax** [comment]
@idarph lezárhatom ezt az issue-t?
