### ISSUE TITLE
Online Szamla_Interfesz specifikáció - RequestVersionType

### ISSUE THREAD

**Issue by hamvasgy** [nav-gov-hu/Online-Invoice#72]
Online Szamla_Interfesz specifikáció_HU_v2.0.pdf
Online Szamla_Interfesz specifikáció_EN_v2.0.pdf

**Oldalszám / Page number = 6

RequestVersionType, HeaderVersionType értékei 1.0 és 1.1 - ez változik a 2.0 verzió bevezetésével?

**Comment by NTCA-developer** [comment]
Szia @hamvasgy 

Dehogynem, kizárólag 2.0-ás értéket vehet fel a 2.0-ás interfész verzióban ez a tag. Javítjuk a doksit, köszönjük szépen hogy észrevetted!

**Comment by hamvasgy** [comment]
Szia, Úgy érted, hogy mind a két tag?

**Comment by NTCA-developer** [comment]
Szia, bocsánat, most látom hogy a kérdésed mindkét tagra vonatkozott. Én csak a requestVersion tagról beszéltem, a headerVersion marad csak 1.0.

Úgy a jó, ahogy az XSD-ben szerepel.

**Comment by hamvasgy** [comment]
Köszönöm
