### ISSUE TITLE
Egyenes adózás fogalom [DOC]

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#720]
A v3.0 specinek a 83. oldalán (2.1.41 Vevői adószám fejezetben) a következő mondat korrigálásra szorul:"A belföldi adószám helye a customerTaxNumber elem (típusa: CustomerTaxNumberType). Amennyiben a vevő státusza belföldi adóalany (customerVatStatus = DOMESTIC), akkor az áfa regisztrált számlakibocsátónak az egyenes adózású ügylete kivételével kötelező a belföldi adóalany adószámának feltüntetése."
1."ügylete" szóból hiányzik a "k" betű
2. Olyan fogalmat használ, amely ismeretlen az áfa törvényben: "egyenes adózás" . Sajnos ameddig a törvény nem nevesíti ezt a kategóriát kifejezetten addig sokan nem érthetik. Ezt a NAV annyira túltolta, hogy a 2165M lapnak a nevébe is bele került, miközben nincs megmagyarázva maga a fogalom. Ráadásul ott is hibás értelmezéssel használják, mert a 2165 leírás 105. oldalán  "egyenes adózás alá tartozó számláról" beszélnek, holott nem a számla tartozik egyenes adózás alá, hanem legfeljebb annak valamely tételsora.
3. A v3.0 speciben félrevezető az "egyenes adózás" ügyletekről beszélni, mert ott valószínűleg csak a "belföldi" egyenes adózású ügyletekre gondolt a szerző.
A fenti pontatlanságok sok zavart okoznak mert ezeket az írásokat nemcsak adószakérők olvassák, hanem olyanok is, akik egzaktul gondolkodnak, mert az kell a szakmájukhoz.

**Comment by NTCA-tax** [comment]
Az "egyenes adózás" kifejezés egy nagyon elterjedt megnevezés, melyet nem csupán az adóhivatal használ. Amennyiben jogi szempontból teljesen korrektek akarunk lenni, akkor ezt nagyjából három sorban §-okra történő hivatkozással is megtehetnénk, de ettől a lényeg nem változik meg, viszont a szöveg érthetőségén nagyot rontanánk. Persze, ha a három soros megoldást választanánk, akkor meg azt olvasnám egy következő issue-ban, hogy miért nem tudunk egyszerűen fogalmazni, túl bonyolult a dokumentáció...

**Comment by Macskafarka** [comment]
Kedves @NTCA-tax! Kétlem, hogy ezt a "nagyon elterjedt" egyenes áfa fogalmat mindenki ugyanúgy értené közülünk.
Talán mégiscsak érdemes lenne tisztázni, mit is kell érteni alatta. Lehet-e mindent egyenes áfának tekinteni, ami nem fordított? Minden egyenes áfának számít-e, ahol a kulcs számmal van kifejezve, azaz a külföldi áfa kulcsok is egyenes áfának számítanak-e?  Az alanyi, vagy tárgyi, vagy bármiféle mentesség az vajon egyenes áfának számít-e?
Egykor a PM azt mondta, ezért nem lehet számlát "stornózni", mert ilyen nincs az akkori ÁFA törvényben. Pedig nagyon elterjedt fogalom volt, de akkor az nem számított. 
Érdekes módon a v3.0 specinek a 9. oldalán megmagyaráznak olyan "nagyon elterjed" fogalmakat is, mint "számla", "adózó" , ÁFA tv., NAV. Tehát az elterjedtség nem akadálya a fogalom tisztázásnak. 
Én azt látom, hogy az ilyen fogalmakat azért nem határozzák meg egzaktan, hogy később lehessen  másképp értelmezni.
Olyan ez, mint az Áfa tv.-ben és az Art-ben "állami adóhatóság". Az ember meg kapkodja a fejét, hogy a "Nemzeti" az megfeleltethető-e az "állami" -nak, a "hatóság" az a "Hivatal"-nak az "adó" az az "Adó és Vám"-nak, a NAV az állami adóhatóság-e, amikor nemzeti.
Ennyi erővel akkor az adószám mezőbe mi is írhatnánk valamiylen számot, esetleg rendszámot., vagy telefonszámot., vagy alvázszámot.
A "Gazdálkodó szervezet" is egy nagyon elterjedt fogalom, de legalább 3 db törvény mást-mást ért alatta, lásd TB törvény.

**Comment by csaszko** [comment]
Biztosan az lehet ennek a hátterében, hogy senki sem tudja mi az a számla vagy adózó, de az "egyenes adózású ügyletet" mindenki érti...
Nem lett volna annyira nehéz feloldani ez a helyzetet (is), csak annyit kellett volna tenni, hogy ezt is beleírni a kifejezések rövidítések közé.. Ekkor meg sem születik ez az issue és még válaszolni sem "kellett" volna. 

Az, hogy egy program fejlesztőknek szánt fejlesztői dokumentációban az API megmagyarázásra kerül, de az "egyenes adózású ügylet" nem... felbecsülhetetlen.

**Comment by NTCA-tax** [comment]
Sikerült találni olyan fogalmat az egyenes és fordított adózásra, amiben nincs legalább három § jel :) Ezt a dokumentációba is meg fogjuk jeleníteni.

**Comment by Macskafarka** [comment]
Szuper! :)

**Comment by NTCA-tax** [comment]
A kérésnek megfelelően a dokumentációba bekerült a fogalom magyarázata, ezért lezárom ezt az issue-t.
