### ISSUE TITLE
[Q&A] queryInvoiceData V2 vs V3

### ISSUE THREAD

**Issue by kovadam69** [nav-gov-hu/Online-Invoice#721]
Sziasztok!

Ma belefutottunk olyanba, hogy a queryInvoiceData V2-es verziója operáció nem hoz le minden bejövő számlát. Van egy funkciónk is, ami nem ütemezetten kérdezi le a bejövő számlákat, hanem a felhasználó tud partner - számlaszám kombinációval keresni, és több számlát sem találtunk meg így sem (és nem hozta be a reggeli ütemezett feladat sem a számlákat). Ez legalább 1-2 napja így megy. A furcsa, hogy néhány számlát le tudott kérdezni, még a mai lejelentésekből is.
Most átkódoltam a lekérdezéseket a V3-as API-ra, és láss csodát, ezekkel behozta ezeket a számlákat (a manuális keresés legalábbis biztosan működik).
Kérdéseim:
a.) ez most valami rendszerhiba lehet vagy direkt működik így?
b.) a V3-al lejelentett számlákat csak a V3 API lekérdezés látja?
c.) a V3 API-val lekérdezett számla lista behozza a V2-vel jelentett számlákat is, vagy most párhuzamosan 2 API-val kell kérdeznünk a számlákat?

Köszönöm a segítséget előre is!

Üdv: kovadam

**Comment by laladisc** [comment]
Szia!

A 2.0-ás lekérdezés nem ad vissza 3.0-val felküldött számlát. Sem a queryInvoiceData, sem pedig a queryInvoiceDigest. A 3.0 viszont mindkét verzióban felküldött számla adatát visszaadja.

**Comment by NTCA-supporter** [comment]
Szia @kovadam69!

Egy lekérdezés api verziója mindig maximum a saján verzióig ad vissza adatot, fölötte sosem.
Így a v2-es az 1.0,1.1,2.0 számlákat, míg a v3-as az 1.0,1.1,2.0,3.0 számlákat adja vissza.

Üdv

**Comment by kovadam69** [comment]
Köszönöm mindkettőtöknek a választ, így már egyértelmű. Akkor ez marad V3-on, a számlabeküldést is úgyis V3-ra kell tenni.

Üdv: kovadam
