### ISSUE TITLE
Bejövő számla technikai érvénytelenítése

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#722]
Az éles rendszer Web-es felületén néztem meg egy bejövő számlát mint vevő.
A megjelenített adatok alatt megjelent a 'Technikai érvénytelenítés' gomb is, aminek megitélésem szerint ott semmi keresnivalója sincs. Számlákat csak a kibocsátó érvényteleníthet.
Megnyomva kéri az érvénytelenítés okát és utána aktív lett a végrehajtó gomb is. Azt már nem nyomtam meg.

Szerintem ez hiba, javítani kellene, el kellene távolítani a Technikai érvénytelenítést a vevői oldalról.

**Comment by NTCA-supporter** [comment]
Szia @kabelnet2 !

Megnézzük, és javítjuk ha valóban hiba van.
Annyit megnyugtatásul, hogy ha felületről be is küldheted, az a validációkon meg fog bukni, hiszen technikai érvénytelenítésnél a kiállított számlák között keresünk, ami ugye nem lesz meg.
Előre vesszük a feladatot.

Üdv

**Comment by csaszko** [comment]
> Szia @kabelnet2 !
> 
> Megnézzük, és javítjuk ha valóban hiba van.
Én is láttam, ott a gomb. 

> Annyit megnyugtatásul, hogy ha felületről be is küldheted, az a validációkon meg fog bukni, hiszen technikai érvénytelenítésnél a kiállított számlák között keresünk, ami ugye nem lesz meg.

Kérdés, hogy milyen azonosítóra kerestek, mert ha számlaszámra akkor nem biztos, hogy nem lesz találat :) 
Mint ahogy nem régen még biztosan a webes export elszállt, ha több szállítónak egyforma volt a számlaszáma a listában.

**Comment by csaszko** [comment]
Teszt rendszeren kipróbáltam. 
Ha van egyforma kimenő és bejövő számlaszám és a bejövő számlánál rányomsz a technikai érvénytelenítés gombra akkor az ugyan olyan kimenő számlaszámú adatszolgáltatást érvényteleníti!

Továbbá a fenti művelet visszaigazolásánál nem sok minden lehet ellenőrizve, hiszen akkor is kiírja, hogy "művelet sikeresen végrehajtódott" ha nem is talál ilyen számlaszámot.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Teszt rendszeren elérhető a javítás. Kérlek ellenőrizzétek.
Üdv

**Comment by csaszko** [comment]
Szia, 

Nálam a bejövőnél teszten már csak a számla export gomb van. 
Köszi

**Comment by NTCA-supporter** [comment]
Zárom, köszönjük a jelzést.
Üdv
