### ISSUE TITLE
Milyen számlaadatokat lehet letölteni - az eredetit vagy a módosítottat

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#723]
Egy bejövő számlát akartam megnézni. A számla különben valamiért hibás volt, az eladó sztornózta azt .
Ha az online felületen nézem az eredeti számlát, vannak értékek (nettó, vat, bruttó).
Ha letöltöm queryinvoicedata-val, akkor minden érték nulla.
Rendben van ez így? Nem azt kellene letöltenem, amit az eladó feltöltött? Közben a NAV a sztornó miatt kinullázta a számla értékét, de attól még volt egy eredeti számla!
(Jelenleg mindkettőben, az eredetiben és a sztornóban is nulla van (digest, számla letöltés)).
Viszont a WEB-es felület tudja az eredeti értékeket!

**Comment by NTCA-supporter** [comment]
Szia @kabelnet2 !

Ezeknek egységesnek kellene lenniük, tehát ugyanazokat az értékeket kell tartalmazni api-s és felületen történő lekérdezéseknél is.
Teszt környezetről van szó? Számal sorszámokat tudsz mondani?

Üdv

**Comment by kabelnet2** [comment]
Hát igen, most megfogtál. A hiba jellegéből következően az éles rendszerben tapasztaltam. A teszt rendszerben ugyebár nincsenek bejövő számlák, ezért ott fel sem merült ilyesmi.
Viszont most akartam csinálni képet a web-ről, de most már ott is nulla minden - ami egy lehetséges eset hibás számlánál. 
Zárjuk le, majd figyelek rá. Nem sok sztornózottat kapunk...

**Comment by beegedi** [comment]
Sziasztok 

Engedjétek meg, hogy  kérdezzek. Letöltéskor technikai sztornó esetén eltűnik a listából az adat, maga a számla nem megjeleníthető miután sztornózva lett. Későbbiekben várható-e arra vonatkozóan megoldás, hogy össze tudjuk fűzni a bizonylatokat?  Például nem tudjuk eldönteni ha technikai sztornó van, hogy mely mező változott meg, ezért nem lehet semmi alapján azonosítani és eldönteni, hogy fel kell e venni a transzfertérbe vagy sem.  Köszönöm a segítséget
