### ISSUE TITLE
[Q&A] Szankciómentes időszak - kérdés

### ISSUE THREAD

**Issue by RvPSc** [nav-gov-hu/Online-Invoice#724]
Üdv,

A szankciómentes időszakról szeretnék érdeklődni.

A gyermeket nevelő családok otthonfelújítási támogatásáról szóló 518/2020. (XI. 25.) Korm. rendelet alapján:

A 7. § (1) c) pont alapján a támogatás igénylése során, az építési tevékenységek teljesítését igazoló számlaként csak olyan számla fogadható el, amelyről a vállalkozó az általános forgalmi adóról szóló 2007. évi CXXVII. törvény 10. számú melléklet 1. pontja szerinti adatszolgáltatási kötelezettségét teljesítette.

Tehát szankció éri a vevőt, méghozzá az, hogy nem tudja lekérni a támogatást. 
Hogy oldjuk ezt meg? Utólag felküldjük 2021.01.04-ig a magánszemélyes számlákat? Ebben az esetben a warn eltávolítására lenne szükség (15 napos határidő). Illetve a nav.gov.hu-n elérhető leírást is módosítani kellene, mert akkor nem igaz, hogy visszamenőleg nem kell feltölteni ezeket a bizonylatokat.

**Comment by csaszko** [comment]
Ide kapcsolódóan kérdésem az lenne, hogy magánszemély milyen módon tudja ellenőrizni egyszerűen és hitelesen, hogy a számláról amit a kezében tart megtörtént az adatszolgáltatás?
Javasolnék egy adószám és számlaszám alapján egy publikus lekérdezési lehetőséget az Online számla és/vagy NAV oldalon hasonlóan az  Áfa alanyok lekérdezéséhez. 
https://nav.gov.hu/nav/adatbazisok/adatbleker/afaalanyok/afaalanyok_egyszeru

**Comment by RvPSc** [comment]
Ennek kapcsán lenne még egy olyan kérdésem, hogy ha például a számlázó fél saját felelőtlenségének okán nem teljesítette az adatszolgáltatást (amiért a büntetést megfizette), akkor a vevő automatikusan elesik a támogatástól?

**Comment by omachtandras** [comment]
@csaszko, NTCA : ha lesz ilyen, akkor én javaslom a bruttó összeg, mint kötelező szűrési feltétel megadását is, mert egy adószám + számlaszám alapján nagyon könnyű "találgatni" és idegen számlákat "nézegetni".
(Konkurencia mit számláz, mekkora összegben....)

Veszélyes dolog ez, jól át kell gondolni.

**Comment by renced42** [comment]
> Javasolnék egy adószám és számlaszám alapján egy publikus lekérdezési lehetőséget az Online számla és/vagy NAV oldalon hasonlóan az Áfa alanyok lekérdezéséhez.

Ilyen publikus funkció azonosítás nélkül biztos nem lesz. Ez nem publikus adat.

**Comment by csaszko** [comment]
Nem voltam egyértelmű ezek szerint, én nem a teljes xml-t mondtam, hogy adjátok ki, hanem, hogy történt-e adatszolgáltatás vagy sem és az befogadtátok vagy sem. Kb. DONE vagy ABORT vagy "Nem történt adatszolgáltatás" amivel hivatalosan tudja bizonyítani és meg tud győződni, hogy ezt a számláz kifizetheti, mert minden rendben van vele. (adott pillanatban)  
Az áfa alanyok lekérdezésénél sem az adózó áfa bevallását adja vissza a publikus rendszer.

**Comment by csaszko** [comment]
Gondolom azok az állami szervek akik ellenőrzik majd ezeket, is hozzátok fognak fordulni információért, - lehet már meg is tették-, szóval gondolom, hogy nem egyesével fognak emailben több 100.000 számlát kikérni a NAV-tól, valami fejlesztés szükséges lesz szerintem. 
Az előző hozzászólásomhoz, még az hozzájönne, hogy ha volt is adatszolgáltatás, de annulálta a szállító akkor arról is szükséges kellene, hogy legyen ennek tényéről időpontjáról infó, hogy ne a vevőt büntessék aki mindent megtett és erre nincs ráhatása.

**Comment by renced42** [comment]
Kedves @csaszko 

Értem az igényt, de csak az előző válaszomat tudom ismételni. Ez nem publikus adat, azonosítás, jogcím, felhatalmazás stb... nélkül sem magánszemély sem kormányzati szerv sem más nem érheti el ezeket az adatokat, még akkor sem ha az konkrét adatszolgáltatást nem ad vissza. Tehát kell hozzá szabályozás. Ha lesz ilyenre egyszer lehetőség, publikálni fogjuk mindenképpen.

**Comment by bakter80** [comment]
szerintem akkor már egy lépésben ki is lehetne írni az electronicInvoiceHash-t, ha van.
ez meg az, hogy be van-e küldve nem szenzitív adat, bárki lekérdezhetné kibocsájtó adószám+számlaszám alapján.

**Comment by Macskafarka** [comment]
**A kérdés egy abszurd helyzetre vonatkozik,** A számlaadat-szolgáltatás a számlakibocsátó feladata. A vevőnek ehhez semmi, de semmi köze, mert nincs ráhatása.
Jogállamban lehetetlen valakit felelőssé tenni másvalakinek a kötelességének elmulasztásáért. Tehát a hivatkozott kormányrendelet nem állja ki a jogállamisági kritériumokat, ellene egy jogállamban siker reményében lehet pert indítani. Mármint jogállamban, független bíróság előtt.
Másrészt előjött, amit előre jeleztem, hogy **elégtelen a NAV által biztosított "szankciómentesség", ide az áfa törvény 10.sz, mellékletének  2021.01.4-i határdátumának kitolása lenne a kívánatos jogi eszköz**. Amit a Parlament bármikor megtehetne, de a járványhelyzet miatt szerinte jelenleg a Kormány is.
Ha nem teszik meg ezt, azt nehéz másképpen értelmezni, minthogy szándékosan hozták létre ezt a helyzetet, hogy miközben a számlakibocsátó ráér 2021.03.31-e utáni keltezésű természetes személy számláiról adatot szolgáltatni, addig ezért a vevőt hátrány érheti.
Ez a valós probléma véleményem szerint kívül esik a NAV hatáskörén, mert a NAV nem tud jogszabályt érvényteleníteni. Amit meg tudott tenni, azt a szankciómentesség, ezt pedig meg is tette. Más jogi eszköz kellene a tisztességes megoldáshoz.
A NAV nem teheti meg azt sem, hogy magánszemélyeknek hozzáférést biztosít a részükre kiállított számlákról, mert ezt adóügyi adat. A jelenlegi jogszabályi keretek között ezt a NAV nem döntheti el.
A vevő annak igazolását sem kérheti a számla kibocsátótól, hogy megtörtént-e a számla adatszolgáltatás.
**Ide átgondoltabb jogi szabályozás kell.**

**Comment by csaszko** [comment]
> Kedves @csaszko
> 
> Értem az igényt, de csak az előző válaszomat tudom ismételni. Ez nem publikus adat, azonosítás, jogcím, felhatalmazás stb... nélkül sem magánszemély sem kormányzati szerv sem más nem érheti el ezeket az adatokat, még akkor sem ha az konkrét adatszolgáltatást nem ad vissza. Tehát kell hozzá szabályozás. Ha lesz ilyenre egyszer lehetőség, publikálni fogjuk mindenképpen.

Kedves @renced42!

Rendben, akkor ügyfelkapus azonosítással megvalósítható, hogy a magánszemély vevő lekérdezhesse a számláját amiről igazolnia kell, vagy meggyőződnie , hogy a konkrét ügynél maradva el tudja számolni és visszakapja (a tegyük fel 3.000.000, ft-ját jelen esetben) adószám és számlaszám alapján? 
Ha a fenti sem működik akkor milyen működő megoldás lehetséges?
 
Szeretnék érdeklődni, hogy tesztek-e ennek a problémának a megoldása érdekében további lépéseket vagy "a lesz ilyenre egyszer lehetőség, publikálni fogjuk mindenképpen." ennyivel lezártátok?

**Comment by renced42** [comment]
Kedves @csaszko 
Ez nem fejlesztési kérdés és nem is Online számla adatszolgáltatási probléma kör. Itt mi erről dönteni nem tudunk, de annyit ígérek továbbítjuk az észrevételt és a kérdést a megfelelő fórumra. Erre írtam, hogy értjük a kérdést és az igényt. Így a kérdéshez érdemben többet hozzátenni nem tudunk fejlesztőként.

**Comment by Macskafarka** [comment]
@RvPSc A 518/2020. (XI. 25.) Korm. rendel 7.§ (1) c) pontja alapján teljességgel elfogadhatatlanok a pénztárgéppel kiállíltott számlák is, ugyanis nem teljesítik az ÁFA tv. 10.sz. mellékletének 1. pontja szerinti adatszolgáltatást, és ezt a NAV eltűri, sőt tevékenyen támogatja is.

**Comment by RvPSc** [comment]
"I_lyen publikus funkció azonosítás nélkül biztos nem lesz. Ez nem publikus adat._"

Tehát akkor az sem tudja lekérni az adatszolgáltatás sikerességét, akinek ellenőriznie kell majd, hogy jogosult-e a vevő a visszaigénylésre? Kérdem én, hogy akkor hogy lesznek elbírálva ezek az igények? Hasra ütés szerűen? Mit publikáljunk a felhasználók felé? Egyértelmű, hogy lyuk tátong a rendszeren, amit szerintem nem a számlázó program fejlesztőinek kellene betömnie.

**Comment by renced42** [comment]
> Kérdem én, hogy akkor hogy lesznek elbírálva ezek az igények? Hasra ütés szerűen?

Kedves @RvPSc 

Ne keverjük össze a dolgokat, ha nem muszáj. 
Akinek (Kincstár) el kell majd bírálni a kérelmet és ellenőrizni kell a számlát annak van vagy lesz erre eszköze és felhatalmazása és joga.
Az egy másik kérdés, hogy a magánszemély ezt hogyan tudja ellenőrizni vagy garantáltatni a vállalkozóval hogy az adatszolgáltatás megtörtént. Pl.: kérjen Nyilatkozatot vagy 

Az meg egy harmadik kérdés, hogy a számlázó programod tudja a 3.0-t vagy sem.

Mit akarsz publikálni a felhasználó felé? És kit értesz felhasználó alatt? A te ügyfeledet vagy azt akinek a számlát kiadja az ügyfeled?
Neked azt kell kommunikálni, hogy a programod a 3.0-t tudja vagy nem tudja. Ha nem tudja akkor mit lehetne tenni ebben az esetben (Pl.: kéziszámlát kiállítani és felületre feltölteni stb...)

Ezzel együtt nem értem milyen lyukat kellene a számlázó program fejlesztőinak betömni
De még egyszer hangsúlyozom ez NEM az Online Számla rendszer adatszolgáltatásával összefüggő probléma.

**Comment by RvPSc** [comment]
Rendben, köszönöm! Az eredeti kérdésre ettől függetlenül választ szeretnék kapni. Utólag felküldjük 2021.01.04-ig a magánszemélyes számlákat? Ebben az esetben a warn eltávolítására lenne szükség (15 napos határidő). Erre számíthatunk, vagy nem? Illetve a nav.gov.hu-n elérhető leírást is módosítva lesz? Mert akkor nem igaz, hogy visszamenőleg nem kell feltölteni ezeket a bizonylatokat.

**Comment by csaszko** [comment]
Kedves @RvPSc Ne haragudj, hogy ismét bekavarok, de nem szeretnék ezért új issue-t nyitni és ide (is) tartozik. 

Kedves @renced42!

Abban teljesen igazad van, hogy ez főként jogszabályi probléma, de attól még sokakat érintő gond és az nem megoldás, hogy "nem publikus adat ilyen nem lesz" válasszal elintézitek. Az, hogy itt tartunk szerintem a hibás kommunikációtokra is visszavezethető, miszerint a rendszeretek teljesen készen van és a számlázó program fejlesztők miatt van a szankciómentes időszak, mert ők nem készültek el. Hogyan kell számolni a fél éves felkészülési/megvalósítási lehetőséget, amit az elején ígértetek nekünk? Csak azért kérdezem, mert nekem nem jön ki a matek azzal, hogy december végén még bőven módosítotok és kiadtok úgy egy rendszert élesbe, hogy tele van általaltok is ismert hibával. Teljesség igénye nélkül pl.  tévesen küldött WARN-ok esetében amivel a számlát kiállítónak is foglalkoznia kell. Hogy lehet erre a rendszerre azt mondani, hogy kész és a másik oldal az aki nem? Nem tartana szinte sehol ez a projekt még, ha a sok számlázó fejlesztő nem tesztelné a rendszereteket évek óta, ami véleményem szerint, egyáltalán nem egy közösség dolga lenne egy állami adófizetői pénzen fejlesztett rendszer esetében.  Az, hogy bizonyos dolgokat ad-hoc másnapra bevezettek, módosítotok és emellett az utóbbi időben rendszeresen "fentről" (tisztelet a kivételnek) érkező választ adtok felvetésekre ahelyett, hogy érdemben is foglalkoznátok a kérdésekkel, nagyon dühítő és elkeserítő. Szeretném (gondolom nem csak én, de a saját nevemben tudok nyilatkozni) kérni, hogy a továbbiakban a rendszer valós állapotát tükröző kommunikációt hirdessetek minden fórumon és ne rajtunk kísérletezzetek, velünk teszteltessetek. Egy megfelelően átgondolt, kialakított rendszert adnátok ki a kezeitek közül. Nagyon jó lenne az is, amennyiben valamire nem alkalmas a rendszer, akkor azt az illetékes szerveknek magatoktól jelezzétek főleg, ha már felhívták a figyelmeteket az anomáliára. 

Ti vagytok abban a helyzetben, hogy sokszor bármit is tudjatok tenni az ügy megfelelő megoldása érdekében. Amennyiben gondot okoznak a fent leírtak és a gyakorlati oldalon megjelenő valós ésszerű igények és érdekekért való lobbizás, akkor véleményem szerint, át kell adni másnak a helyet. 

Ha nálatok előjött már a fenti probléma korábban és azért reagáltatok ilyen gyorsan, akkor azért baj, hogy tudtatok róla, de nem érdekelt a téma, ha meg most került elő, akkor jobban is sikerülhetett volna az ezzel kapcsolatos válasz és probléma átgondolása, ha valóban értitek azt. 

Konkrét témában megoldási javaslat 2.0 

Továbbra is az a véleményem, hogy igenis rátok is tartozik, és adatszolgáltatási probléma is, mert ha most ennél a pályázatnál előjött, akkor máshol is fogják kérni. A jelenlegi helyzetben teljesen kiszolgáltatott bárki és mindenki, aki magánszemélyként vesz igénybe szolgáltatást vagy vásárol (jelen esetben tudtommal csak ebben) pályázat keretében, aminél kötelezővé teszik az adatszolgáltatást meglétét. Az újságok szerint már adtak le pályázatokat, ott ki és hogyan kapja meg tőletek az adatokat? 

Hangsúlyozom, hogy NEM csak az átmeneti időszakot érinti a probléma, mert bármikor lehet olyan nem törvénykövető adózó, akár szándékosan, akár nem, aki nem tesz eleget az adatszolgáltatási kötelezettségének. Még ha mindenféle papíron is lenyilatkozta... nem biztos, hogy jogi útra szeretné mindenki vinni, vagy az a cél.  
Ezért azon kívül, hogy érthető a célja, de ebben a formában aggályos ehhez kötni egy pályázatot. Ennek a részbeni feloldását technikai oldalon abban látom, hogy biztosítotok egy olyan felületet, ahol le lehet kérdezni és hivatalos formába adtok egy visszaigazolást a magánszemély vevőknek is. 
Ezt az igazolást pedig a számla kiállítója tudná lekérni a NAV-tól, weben és API-n, esetleg hivatalosan NAV-tól közvetlenül elküldetni, vevő email címére (egy email címet ad át a számlázó, természetesen utólag is legyen lehetőség, ne csak akkor, amikor kiállítják a számlát) 
Ezzel igazolva azt, hogy a vevő jogszerűen járt el és mindent megtett amit tudott. Esetleg addig nem fizeti ki a számlát, ameddig ezt nem kapja meg. Figyelve arra, hogy történt-e esetleg annulálás (ami az utolsó), tehát ha vevő megkapja a nyilatkozatott adott időpontban és x idő múlva eladó annulálja azt, akkor ne a vevő legyen ezért büntetve. 
Azt, hogy ezt a nyilatkozatot a számlázó fejlesztők egyesével oldják meg, nem látom értelmét, mert nem lenne egységes és nem lesz hiteles információ a vevő részére sem. Ne kelljen a NAV ügyfélszolgálatra bemenni és azt terhelni ezekkel a kérésekkel is. 
Ezáltal megoldott, hogy nem publikusak az adatok, de mégsem kell mindenféle regisztrációval rendelkeznie a magánszemélynek. 
Ha pedig az lenne a válasz erre is, hogy adótitok, akkor jogi útra kell terelni a témát sürgősen, de a fejlesztésre sem ér rá, mert jelenleg igen problémás a helyzet. 

Köszönöm

**Comment by renced42** [comment]
Kedves @csaszko

Köszönjük az észrevételeket

Kedves @RvPSc 
A feltett "Utólag felküldjük 2021.01.04-ig a magánszemélyes számlákat" kérdést is meg fogjuk kérdezni ahogyan ígértem korábban és a számla ellenőrzés lehetőségét is szintúgy.

**Comment by NTCA-tax** [comment]
Az Online Számla rendszert az adóhivatal tartja fenn, alapvetően adóztatási célokból. Amennyiben más kormányzati szerv szeretne az adatokhoz hozzáférni, akkor ahhoz jogszabályi felhatalmazásra van szükség egyrészt, másrészt az informatikai háttér kialakítására. Ez a kormányzati oldalon lévő kérdéseket jelent. 

A más szerv általi adatigénylések esetén ugyanakkor fontos figyelembe venni a rendszernek a sajátosságait, illetve a rendszer kialakítására vonatkozó jogszabályi előírásokat. Amennyiben egy számlán nem szerepel magánszemély adattartalom, akkor ez egy rendszerben lévő adottság. Nem tervezünk módosításokat ebben, így a magánszemély nem fog tudni a saját nevére, mint vevőre kiállított számla adatokat lekérdezni. Nem tervezünk olyan lehetőséget sem, hogy számlasorszám alapján lehessen adatot egyedileg lekérdezni. A nem adóalanyoknak kiállított számlák esetén adóhivatal oldalán nem kötelezettség az adatszolgáltatás teljesítése 2021.03.31-ig (legalább is nem szankcionálunk, ha nem teljesül).

**Comment by csaszko** [comment]
Kedves @NTCA-tax!

Köszönjük a tájékoztatást! 
A válaszodban szépen megfogalmazott általánosságok vannak, de az ügy szempontjából semmit nem segít, a többit meg már leírtam korábban.

**Comment by lvitya586** [comment]
> Az Online Számla rendszert az adóhivatal tartja fenn, alapvetően adóztatási célokból. Amennyiben más kormányzati szerv szeretne az adatokhoz hozzáférni, akkor ahhoz jogszabályi felhatalmazásra van szükség egyrészt, másrészt az informatikai háttér kialakítására. Ez a kormányzati oldalon lévő kérdéseket jelent.
> 
> A más szerv általi adatigénylések esetén ugyanakkor fontos figyelembe venni a rendszernek a sajátosságait, illetve a rendszer kialakítására vonatkozó jogszabályi előírásokat. Amennyiben egy számlán nem szerepel magánszemély adattartalom, akkor ez egy rendszerben lévő adottság. Nem tervezünk módosításokat ebben, így a magánszemély nem fog tudni a saját nevére, mint vevőre kiállított számla adatokat lekérdezni. Nem tervezünk olyan lehetőséget sem, hogy számlasorszám alapján lehessen adatot egyedileg lekérdezni.

Az adóhivatalt pedig az adófizetők tartják fenn közvetve. Többször is felmerült már a szolgáltató állam kifejezés, amit ha valóban komolyan gondolnának, akkor nem ilyen lenne a hozzáállás. Az Online Számla rendszer ha már létrejött nem kevés adóforintból, akkor ne csak az adóztatás legyen a szempont.

A magánszemélyektől is keletkezik igény arra vonatkozóan, hogy lekérdezhetőek legyenek a nekik kiállított számlák. Pl. sokkal egyszerűbb lenne, ha a díjnet, a számlaközpont (vagy a megboldogult távszámla), ésatöbbi rendszerekhez hasonló módon, de azok helyett egyetlen felületen elérhetőek lennének a számlák és nem kellene sokféle távközlési, közmű, stb. szolgáltatói rendszert kezelni, továbbá a megőrzés is biztosított lenne a megőrzés és vitás kérdés esetén elő lehetne venni ezeket. Az ügyfélkapuval pedig megoldható lenne az azonosítás, ill. adott esetben nyilatkozattétel az adatok kezeléséről is GDPR konform módon.

Ehelyett most megint sikerült kitalálni egy öszvérmegoldást azzal, hogy a fizikai számlán rajta vannak a személyes adatok, de beküldésre már nem kerülnek.

**Comment by NTCA-tax** [comment]
Amit itt feszegettek, az nem jogszabály értelmezési, hanem jogalkotási kérdés és messze nem adójogszabályokról beszélgettek. Ezért ezt az issue-t lezárom.
