### ISSUE TITLE
[DOC] 2.1.6  Egyezményes, nevesített adatok szerepeltetése 

### ISSUE THREAD

**Issue by ocsike** [nav-gov-hu/Online-Invoice#725]
A Online_Szamla_interfesz specifikacio_HU_v3.0.pdf -ben a címben jelölt fejezetben a ConventionalInvoiceInfoType ábráján létható elnevezések és az ábra alatti táblázatban szereplő elnevezések nincsenek szinkronban pl. ábrán orderNumbers van míg a táblázatban orderNumber/orderNumber  van itt az orderNumbers/orderNumber lenne a helyes.

Másik kérdés, hogy ha használom ezt az elemet akkor, miért kötelező minden elemét kitölteni?  Pl. nincs mindig EKÁER szám, rendelésszám, projektszám stb?

**Comment by NTCA-supporter** [comment]
Szia @ocsike !
Jogos az észrevétel, köszi, javítani fogjuk.
Ezt úgy kell értelmezni, hogy ha adsz meg pl. ekaerIds csomópontot, akkor kötelező megadnod legalább 1 ekaerId taget.
Ha nem kézed meg egyáltalán az ekaerIds-t, akkor nem adsz meg ilyet és kész.

Üdv

**Comment by ocsike** [comment]
Üdv,
Köszi szépen.
