### ISSUE TITLE
[Q&A] Számlával egy tekintet alá eső okirat beküldése

### ISSUE THREAD

**Issue by ocsike** [nav-gov-hu/Online-Invoice#726]
Üdv!

Számlával egy tekintet alá eső okiratot, hogy tudom beküldeni? Azaz az eredeti számla bemegy elfogadják, utána kiderül, hogy rossz a vevő adószáma,vagy címe. Ilyenkor elkészül egy helyesbítő számla a javított adatokkal ami ugye az eredetihez kapcsolódik, viszont nincs tétel rajta, mert számla végösszege nem változik. Ha nincs tétel a számlán akkor azt most visszadobja a rendszer.

**Comment by NTCA-supporter** [comment]
Szia @ocsike !
https://onlineszamla.nav.gov.hu/api/files/container/download/Online_Szamla_interfesz%20specifikacio_HU_v3.0.pdf
A 2.5 fejezetet olvasd át kérlek, sok info megvan benne, ami neked kell.
Röviden:
A manageInvoice beküldésnél invoiceOperation: MODIFY
Így befogadjuk tétel nélkül. Kell megadni egy 0 ft-os összesítőt, és akkor az összeg értékek sem módosulnak.
Üdv

**Comment by ocsike** [comment]
Üdv!
Köszi szépen, működik a dolog. Zárom.
