### ISSUE TITLE
Adatexport online számla séma szerint [Q&A]

### ISSUE THREAD

**Issue by bmatyi94** [nav-gov-hu/Online-Invoice#727]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Kedves Olvasó,

A 23/2014-es NGM rendelet szerint az adatexport teljesíthető az online számla séma strúktura szerint is. **Megengedett-e a fájlokat egy darab xml-ben átadni az adóhatóságnak, mely több számla adattartalmát tartalmazza?** Amennyiben igen, hogyan?

** Az online számlázó adatexport generálása után a NAV programja egy darab xml-ben adja vissza a számlák adattartalmát. Viszont a root element a következő: <**Invoices** xmlns="http://schemas.nav.gov.hu/OSA/3.0/data" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns3="http://schemas.nav.gov.hu/dto/invoices">. Az Invoices root elementen belül pedig több "invoice" element található. 

**Ilyen root element és séma hivatkozás "http://schemas.nav.gov.hu/dto/invoices" nem szerepel a közzétett dokumentációban sémákban, vagy hol található meg?** **Helyes-e az adatexport követelményei szerint?**

Előre is köszönöm a segítséget.
Üdv.

Budai Mátyás

**Comment by NTCA-tax** [comment]
Kedves Mátyás!

Az adatexport és az adatszolgáltatás között jelentős különbségek vannak, amit érdemes figyelembe venni.
- Az adatexport a számla összes adatát tartalmaznia kell, míg az adatszolgáltatásnak (amennyiben nem maga a számla 3.0-ban), akkor "csak" az áfa törvény szerinti adattartalmat.
- Az adatszolgáltatást automatikus gépi feldolgozásra terveztük, az adatexportot egyedileg a revizorok elemzik. Ebből következően amennyiben az adatszolgáltatásban bármilyen hiba van, az a feldolgozás során nem javítható, az adatexport esetén ugyanakkor a revizor tudja korrigálni az apróbb problémákat (nem az adattartalmat, hanem a struktúrát...)

A gyakorlati tapasztalat az, hogy az adatexportnál a legtöbb számlázó program esetében már az is lassan eredmény, ha értelmezhető az adatállomány. Ez persze nem követendő út, de ezért használunk olyan megoldásokat, amelyek jobban hibatűrők tudnak lenni. A legnagyobb problémát - sajnos - nem az okozza, hogy a

**Comment by jozanesz** [comment]
>     * Az adatexport[nak?] a számla összes adatát tartalmaznia kell

Ezt pontosan hogy lehet kiolvasni az NGM rendeletből?

Pl. 
```
            <xs:element name="rezsicsokkentes" type="decimal_tipus" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>A rezsicsökkentés eredményeként jelentkező megtakarítás összegét fel kell tűntetni jól láthatóan, színes mezőben.</xs:documentation>
                </xs:annotation>
            </xs:element>```
A számlaképtörvény alapján legalább 3 db forint érték kapcsolódik a rezsicsökkentéshez. Akkor mind a hármat ugyanilyen elembe be kellene tenni? És a kapcsolódó szövegeket hova? És amúgy is mi köze a NAV-nak ezekhez? De van több más adózás szempontjából irreleváns adat is különböző jogszabályok alapján.

**Comment by NTCA-tax** [comment]
@jozanesz igazad van, nem volt pontos amit leírtam. Az adójogszabályok szerinti összes kötelező adattartalmára vonatkozik amit leírtam. Nem a karácsonyi jókívánságokat akarjuk nézegetni azért és nem is a rezsicsökkentés hatását... De teljesen értem a hozzászólásodat és a pont ott van Nálad :)

**Comment by bmatyi94** [comment]
@NTCA-tax Köszönöm a válaszod. A kérdésem arra vonatkozott volna, hogy szerepeltethető-e az száma adatszolgáltatási séma szerint megalkotott például 3.0-ás xml-ek, amelyek tartalmazzák az adójogszabályok szerint összes kötelező adattartalmat egy darab xml fájlban? Amennyiben igen, az hogyan oldható meg technikailag, mivel jelenleg a sémában nem látok erre lehetőséget?

**Comment by NTCA-tax** [comment]
Lehet több számlát adatexportban egy XML-ben szerepeltetni. A kérdésedben leírt megoldás (a root alatt több invoice csomópont szerepel) is járható út. Ezt az adóellenőrök fel tudják dolgozni, függetlenül attól, hogy a séma szerint nem lenne valid. De az is járható megoldás, hogy számlánként adod az adatexportot. Adózóktól már láttam mindegyikre példát egyébként, tehát nem csupán az Online Számlázó adja egy XML-ben az adatexportot.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
