### ISSUE TITLE
[Q&A]

### ISSUE THREAD

**Issue by tacshu** [nav-gov-hu/Online-Invoice#728]
Sziasztok,

van esetleg olyan listátok, amiben megvannak azon Java verziók, ahol még működik a publikált séma szerinti validálás?
Nekem az egyik verzióban ilyen hibát ad:
- NonParserException invalid facet "maxLength" for type "simpleType"
Egy másikban pedig:
- Invalid value '2' specified for facet 'length'

Köszönöm

**Comment by renced42** [comment]
Kedves @tacshu 

Kérlek fejtsd ki konkrétan mit szeretnél mert nem értem a kérdést.

**Comment by NTCA-supporter** [comment]
@tacshu van még kérdés?
Üdv

**Comment by tacshu** [comment]
Bocsánat, nem tudtam foglalkozni az üggyel.
Szóval, azt tapasztaltuk, hogy bizonyos Oracle verziókból indított Java alapú(tehát itt az Oarcle-be épített Java-ra gondolok)XML validációnál xsd értelmezési hibákat dob.

**Comment by renced42** [comment]
Kedves @tacshu 

Kérdéseim:
Mi dob hibát? A beküldás során kaptok vissza hibaüzenetet vagy csak simán XSD validáltok és ott a hiba?
Nem nagyon tapasztaltuk hogy még bárkinek problémája lett volna a java verziónkkal.

Példa requestet tudsz küldeni a teszt rendszeren?

**Comment by tacshu** [comment]
Mi validálunk beküldés előtt. Ott jelentkezik a hiba. Sikerült kerülő megoldást kitalálni, mert szerencsére az Oracle XML validációjában nem jelentkezik a hiba.
Azért tettem fel ezt, hogy hátha van listátok, ahol ilyen előfordulhat.
Mi Oracle 10g és 12c-ben is a 12.1.0.2.0-nál tapasztaltunk ilyet.

**Comment by renced42** [comment]
Kedves @tacshu 
Ha ez a helyzet, hogy akkor vagy a külső parser a hibás, vagy az Oracle parsere :)
De egyébként nincs ilyen listánk és nem ütköztünk ilyen hibába illetve nem tudok róla.

De az XML az valid, mondjuk egy notepad++ ban? Ha ott sem akkor az XML nem jó és a java oldalon nem állítja elő jól a program.

**Comment by tacshu** [comment]
Máshol valid. Nem az XML-lel van baj, hanem a parserrel. Annyira bonyolult lett az xsd, hogy ezt már nem veszi be a gyomra. :)
Ok, akkor ennyi. Köszönöm az infot.
