### ISSUE TITLE
[Q&A] queryInvoiceDigest operáció relationalQueryParams használata

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#729]
A számlát le tudom kérni kelte tól-ig dátumra, ezt értem, viszont a teljesítés dátumra történő szűrés nekem nem egyértelmű.
Hogy kell értelmezni a relationalQueryParams használatát?

invoiceDelivery/queryOperator: Relációs kereső operátor
invoiceDelivery/queryValue: A keresett érték

Hogy tudok megadni olyan tól-ig szűrést teljesítés dátumra, mint a mandatoryQueryParams esetében a keltnél?

**Comment by NTCA-supporter** [comment]
Szia @nbeeps2 !
Pl. így:
`<invoiceDelivery>
	<queryOperator>GTE</queryOperator>
	<queryValue>2021-01-20</queryValue>
</invoiceDelivery>
<invoiceDelivery>
	<queryOperator>LTE</queryOperator>
	<queryValue>2021-01-27</queryValue>
</invoiceDelivery>`

Ennyi info elég, vagy küldjek egy teljes requestet?
Üdv

**Comment by nbeeps2** [comment]
Oké, köszönöm, így már értem. Köszönöm.
Jól látom, hogy olyat nem lehet, hogy csak teljesítés dátumára kérdezek a kelte helyett?
A teljesítés dátumának intervalluma lehet több, mint 35 nap?

**Comment by NTCA-supporter** [comment]
A mandatoryQueryParams csomópont megadása kötelező, ahogy a neve is jelzi.
A teljesítés dátuma úgy tudom lehet több, a mandatory-n belül lévő intervallumok lehetnek csak max. 35 naposok.
Üdv
