### ISSUE TITLE
[FEATURE] Adószám ellenőzés opcióként konkrét dátummal

### ISSUE THREAD

**Issue by csaszko** [nav-gov-hu/Online-Invoice#73]
**Az igény összefoglalása / Summary of the request**
 Jó lenne egyszerűen automatikusan a NAV rendszerével megtudni, hogy érvényes vagy nem adott napon az adószáma a partnernek akitől a számlát befogadjuk. Ez nem a kiállításhoz, hanem a befogadáshoz lenne fontos és hasznos funkció.   

**Az általam javasolt megoldás / The solution I propose**
/queryTaxpayer kiegészítése egy plusz opciós dátum megadhatóságának lehetőségével (adott napon érvényes-e a lekérdezett adószám, pl számla kiállítás napján még élő volt a cég, de mire feldolgozásra kerül a szállítói számla - bevételezésre- már nem érvényes az adószáma.) 

**Elfogadható alternatívák / Acceptable alternatives**
Nem hiszem, hogy érdemes máshogy megoldani.

**Egyéb tartalom / Additional content**
"Az adóhatóság pénteki közleményében kiemelte: érdemes minden eshetőségre felkészülve megfelelően dokumentálni, hogy a vállalkozás a lehető legkörültekintőbben jár el üzletkötései során. A NAV honlapján található adatbázisokban ellenőrizhető, hogy ki mennyire tartja be a szabályokat, valamint az online számla rendszer is megkönnyíti a számlakibocsátó partnerek megbízhatóságának felmérését."

**Comment by NTCA-developer** [comment]
Szia @csaszko 

Köszi a felvetést.

Olyat tudunk, hogy a lekérdezés válaszában visszaadjuk azt az időpontot, amikor az adatok utoljára változtak, ez kvázi a visszaadott adatok időbeli érvényességét jelöli. Ezt az adatot viszont mi csak pillanatkép-szerűen tudjuk szolgáltatni, tehát historikus adatot nem fogunk tudni adni belőle.

Ez fedi azt amit javasolsz?

**Comment by bsibsi** [comment]
Szia @NTCA-developer 

Az, hogy mikor változtak utoljára az adatok valóban hasznos kiegészítő információ, azonban ez sajnos önmagában nem jelent megoldást a csaszko altal megfogalmazott igényre, hiszen ezzel a módszerrel nem biztosítható egy olyan ellenőrzés, mely segítségével megállapítható lenne, hogy egy adott tárgynapon a megadott adószámhoz milyen információk tartoztak (adózó adatai, adózási forma, érvényesség, stb.).

Ezek az adatok fontosak ahhoz, hogy egy tetszőleges múltbeli (tipikusan néhány napos, esetleg pár hetes) ügylet hitelességét megfelelően ellenőrizni lehessen. Ilyen ellenőrzésre egyébként több környező országban is van lehetőség hasonló célú, minden adott országban regisztrált adózó által szabadon elérhető API-n keresztül, ami jelentős könnyebbséget biztosít az adózók számára a szükgéges ellenőzések elvégzésében mind számlakiállítás, mind pedig számla befogadás során.

Bízom benne, hogy itthon is megoldható egy ilyen adatlekérdezési módszer, mind aktuális, mind pedig historikus adatokkal, hiszen mindkettőnek van relevanciája.

**Comment by NTCA-developer** [comment]
Szerintem még fedheti, korai temetni az ötletet. A NAV jellemzően nem csiki-csukizik az adószámokkal, azaz relatíve ritkán van olyan, hogy egy adószám ami tegnap még érvényes volt ma már nem az, de holnap meg megint igen. Ha egy adószám érvénytelenné válik, az többnyire a végállomás. Ha mondjuk 3 nap múlva megkapod a számlát azt látod, hogy az adószám utolsó módosítása tegnap volt és az adószám most érvénytelen, akkor jóhiszeműen feltételezheted, hogy 3 nappal ezelőtt még érvényes volt. 

Az én személyes véleményem szerint az elvárható gondosságot ennek az ellenőrzése eléggé kimeríti. Persze értem hogy history jobb volna, de ami miatt ilyet nem tudunk adni az már a master data management szépsége.

**Comment by bsibsi** [comment]
Értem az álláspontod, valóban ritkább, hogy az egyik nap még érvényes adószám másnapra már nem lesz az, azonban ez is többször előfordult már a múltban csupán csak a saját partnerköben (csődeljárás, felfüggesztés, stb), ezért az ennek lekérdezhetőségére vonatkozó igényt valósnak érzem.

Ami pedig hasonlóan érdekes kérdés az az adózási forma lekérdezése (kisadózó, KATA, EVA, stb.), historikusan. Számla befogadásánál fontos tisztában lenni a partner adózási formájával, hiszen az egyes adózási formákhoz egyedi számla tartalmi és formai követelményeknek kell megfelelni, amit úgy lehet helyesen megállapítani és betartatni, ha a befogadó tisztában van a számla kiállítójának a kiállítás pillanatában érvényes adózási formájával. Ez év végével különösen aktuálissá fog válni, hiszen az EVÁ-t mint adózási formát kivezetik, ezért minden olyan kisvállalkozás, ami jelenleg ezt használja át fog térni valamely más adónemre, ami miatt könnyen lehet hogy a számlázási szokásaikon is változtatniuk kell majd.

Megértem, hogy pillanatnyilag kihívást jelent számotokra ezen információk rendelkezésre bocsátása az API-n keresztül, hiszen sokszor egy viszonylag egyszerű adatelérési kérdést is meglehetősen komplexé tudja tenni a belső adatkezelési szabályoknak való megfelelési követelmény, de attól hogy ez kihívást jelent, az igény véleményem szerint továbbra is releváns, így bízok benne, hogy sikerülni fog ezen a nehézségen felül kerekedni.

**Comment by csaszko** [comment]
Szia @NTCA-developer, 

Amennyiben a NAV elfogadja ezt a megoldást arra, hogy az adózót "ellenőríztük" amikor lekérdezzük, (külön opciós dátummal és csak akkor adná vissza az utolsó módosítást, hogy lehessen ezt is loggolni (ha akarjátok) ), akkor részemről elfogadható lenne egy verziója, ameddig esetleg nem megoldható a részletes lekérdezés. 
Illetve még annyi, hogy nem vagyok tisztában azzal, mikortól beszélünk arról, hogy egy adószám nem érvényes és esetleg van-e bármilyen jogi lehetősége arra, hogy visszakapja vagy ilyenkor esetleg a régi helyett újat kap és a másikat meg már soha nem adják vissza. Van-e olyan hogy felfüggesztett, amit bármikor vissza lehet állítani, ha van ilyekor milyen választ ad a rendszer vagy mert ok hogy most érvényes nem érvényes, de ha visszaállítható akkor érdekes lehet mást infó is. 

A kivitelezés része igazából részemről tényleg mindegy: a lényeg a befogadó oldalon biztosra lehessen menni a lekérdezésnél, hogy az adott pillanatban a számlát kiállító cég NAV szempontból is rendben van és ezt el is fogadják egy esetleges ellenőrzésnél.

**Comment by NTCA-developer** [comment]
Igen, szerintem is valid az igény a historikus adatokra. Megint csak IT stratégiai vizekre tévedtünk, mert ugye van egy másik adózó lekérdező alkalmazás is rajtunk kívül a NAV-ban, aminek semmi más dolga nincs mint adószámok lekérdezését kiszolgálni, ellentétben velünk. Valakinek csak el kell dönteni, melyik kap primátusságot.

A kérdést inkább úgy tenném fel, hogy amit a jelenlegi keretek között is tudunk, azt visszaadjuk-e a lekérdezés válaszában. Értem, hogy nem 100% a hatásfok, de a semminél úgy 90%-kal jobbnak érzem.

**Comment by csaszko** [comment]
> Az én személyes véleményem szerint az elvárható gondosságot ennek az ellenőrzése eléggé kimeríti.

Szerintem is, de sajnos a tapasztalatok azok, hogy bizonyos kérdésekre -szinte mindig- megyénként eltérő választ kap az adózó a feltett kérdésekre.  :(

**Comment by csaszko** [comment]
**Megint csak IT stratégiai vizekre tévedtünk, mert ugye van egy másik adózó lekérdező alkalmazás is rajtunk kívül a NAV-ban**, 
Erről beszéltél? https://www.nav.gov.hu/nav/adatbazisok/adatbleker/afaalanyok/afaalanyok_egyszeru

Amúgy ennek van API része? Aminél értelmesen le lehet kérdezni és fel is lehet dolgozni a választ? Vagy csak a webes felület van a manuális lekérdezéshez?

**Comment by NTCA-developer** [comment]
@csaszko 

Én sajnos nem ismerem konkrétan a másikat, sosem használtam csak tudom hogy van. Amit viszont tudok, hogy publikus API része nincs, és ha lenne is valószínűleg nem bírná el az Online számla rendszer forgalmának tizedrészét sem, nem erre lett tervezve. Ezért mondtam, hogy ez stratégiai kérdés is.

**Comment by csaszko** [comment]
> @csaszko
> 
> Én sajnos nem ismerem konkrétan a másikat, sosem használtam csak tudom hogy van. Amit viszont tudok, hogy publikus API része nincs, és ha lenne is valószínűleg nem bírná el az Online számla rendszer forgalmának tizedrészét sem, nem erre lett tervezve. Ezért mondtam, hogy ez stratégiai kérdés is.

Oks, köszi. Akkor én maradnék az első verziónál, akárhogy ahogy meg tudjátok oldani. Programból lehessen lekérdezni, ne kelljen embernek ezzel külön foglalkoznia, hogy beírogatja és lekérdezi.

**Comment by NTCA-developer** [comment]
Oké, a historikus adatokra való igényt pedig továbbítom. Hátha.

**Comment by csaszko** [comment]
Köszönöm!

**Comment by NTCA-developer** [comment]
Szia @csaszko 

Befogadjuk az igényt. A 2.0-ás adózó lekérdező válaszában szolgáltatjuk az adatok utolsó módosításának időpontját is.

**Comment by csaszko** [comment]
Köszönöm
