### ISSUE TITLE
[Q&A] Lánckezdő bizonylat tételsorok ÁFA bontása nem egyezik a summary-ben lévővel

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#730]
Sziasztok!

Sajnos 2.0 és éles rendszer, de egy olyan hiba, ami elég komolynak tűnik és érdemes lenne utána járni, hogy 3.0-ban is előfordulhat-e, illetve az is érdekelne, hogy ilyenkor kap-e legalább egy warningot az adatszolgáltató.

A partnerünk a NAVtól jövő adatok alapján dolgozza fel a bejövő számláit.
Vásárolt egy nagy áruházláncnál, és az adatszolgáltatás úgy néz ki, hogy 
- van két számlasor 27%os kulccsal, pozitív összegekkel, minden jó velük.
- van egy számlasor, ami adómentes, 0 alap, 0 adó, ezzel sem lenne még gond.
Az összesítő azonban így néz ki:
`            <invoiceSummary>
                <summaryNormal>
                    <summaryByVatRate>
                        <vatRate>
                            <vatExemption>Free freight</vatExemption>
                        </vatRate>
                        <vatRateNetData>
                            <vatRateNetAmount>61259</vatRateNetAmount>
                            <vatRateNetAmountHUF>61259</vatRateNetAmountHUF>
                        </vatRateNetData>
                        <vatRateVatData>
                            <vatRateVatAmount>16540</vatRateVatAmount>
                            <vatRateVatAmountHUF>16540</vatRateVatAmountHUF>
                        </vatRateVatData>
                        <vatRateGrossData>
                            <vatRateGrossAmount>77799</vatRateGrossAmount>
                            <vatRateGrossAmountHUF>77799</vatRateGrossAmountHUF>
                        </vatRateGrossData>
                    </summaryByVatRate>
                    <invoiceNetAmount>61259</invoiceNetAmount>
                    <invoiceNetAmountHUF>61259</invoiceNetAmountHUF>
                    <invoiceVatAmount>16540</invoiceVatAmount>
                    <invoiceVatAmountHUF>16540</invoiceVatAmountHUF>
                </summaryNormal>
                <summaryGrossData>
                    <invoiceGrossAmount>77799</invoiceGrossAmount>
                    <invoiceGrossAmountHUF>77799</invoiceGrossAmountHUF>
                </summaryGrossData>
            </invoiceSummary>
`
A nettó, adó, bruttó egyezik a 27%os sorok értékeivel, csak éppen adómentesként jelölve...
A kérdésem az, hogy miként lehet az, hogy egyetlen, csak mentes kulcsot tud átadni az összesítőben, ahol ráadásul lehet adótartalom és a nettó és a bruttó eltér egymástól úgy, hogy az az ÁFA kulcsok és adó összegek szempontjából teljesen ellentmond a tételsorokban található adatoknak?

A gazdasági társaságok eltérő méretei miatt a partnerünk nem lát esélyt arra, hogy az ő megkeresése okán változtasson az adatszolgáltatáson az eladó.

Előre is köszönöm a választ.

**Comment by NTCA-supporter** [comment]
Szia @omachtandras !

Erre biztosan kap, több WARN-t is.
Az összegszerű eltérésnek "csak" WARN-t kapnak.

Üdv

**Comment by omachtandras** [comment]
Köszönöm a választ.

Közben előjött más partnernél más számla, a következő érdekességekkel:
"
- a számla fejben a GROSS_AMOUNT_SUM 291 681,00, a GROSS_AMOUNT_HUF_SUM 298 976,40, pedig forintos számla, nem szabadna eltérnie a 2 értéknek..
- a tételeknél a kapott bruttó összegeket összeadva 257 365,50 lesz.
- a 7. soron 0 értékeket adtak minden összegben. Mivel adtak át darabot és egységárat, azokból látszik hogy itt 27 020-nak kellene lenni a bruttó összegnek. De még ezt hozzáadva a teljes tételsor összeghez, sem jön ki az a bruttó, amit a fejen adtak (egyik se), és a summary se (a summaryban a 291 681,00 szerepel mindkét bruttó összegnél).

A számlakép alapján a 7. sornak a nettó összege 27 020 Ft, a bruttója 34 315 Ft, így a GROSS_AMOUNT_SUM és GROSS_AMOUNT_HUF_SUM közötti eltérés a 7. sor áfája volt.
"

Remélem erre is kaptak wargningot, bár én nem lennék ennyire megengedő... :)

Izgalmas lesz ilyen adatokból júliusi ÁFA bevallás-tervezetet készíteni.

Zárom a jegyet.

**Comment by NTCA-supporter** [comment]
Ez a számla biztosan kapott több WARN-t is. Elég csúnya, hogy ilyen tiszta adatok vannak :(
Üdv
