### ISSUE TITLE
[Q&A]Egyszerűsített számlán speciális áfák

### ISSUE THREAD

**Issue by gajzi** [nav-gov-hu/Online-Invoice#731]
Korábban már be lett jelentve, de a javítás ígéretén kívül még nem történt semmi, pedig közben a 3.0 bevezetésre is került.
Ha egyszerűsített számlában speciális (nem százalékos) áfát küldünk fel, minden esetben INCORRECT_SUMMARY_CALCULATION_VAT_CONTENT_GROSS_AMOUNT_SUMMARY_SIMPLIFIED (Az egyszerűsített számla egy vagy több adótartalomhoz tartozó tételsoraiban szereplő bruttó értékek összege eltér az összesítésében a hozzá tartozó adótartalomnál szereplő bruttó összegtől)
warning jön.
Ha most átállnánk 3.0-ás verzióra az ügyfeleinknél, elöntenének a warningok (amellett, hogy az ügyfelek is jogosan telefonálnának ilyen esetekben, minden ügyfeleknél jelentkező NAV ERROR/WARNING-ról a saját ügyfélszolgálatunk is kap értesítést, de az ilyen felesleges üzenetek mellett félő, hogy elsiklanának a valós problémák),  mikorra várható ennek a javítása.

köszönettel,
Gajzer Arnold

**Comment by NTCA-supporter** [comment]
Szia @gajzi !

Az #550 még nyitva van, abban fogjuk jelezni, ha tesztelhető a javítás. 

Ezt zárom.
Üdv
