### ISSUE TITLE
INVALID_REQUEST_SIGNATURE

### ISSUE THREAD

**Issue by Antonikas58** [nav-gov-hu/Online-Invoice#732]
Hi dev team,
We faced an issue when trying to get token for manage invoice. request id is 20210127083403307. Could you please support us here, it seems that hash F7C6C4C8E10C71928C0F5F441E28EDAC586E5050A8941BA87B2F5BF83C8FAA8023C1ADC3A32A9E060F987AEF14A5106C262F167E7C01C39797109B3F82F35254
is not the expected one for this message.

Best regards
Anton Liolia

**Comment by Antonikas58** [comment]
sorry request id is 2021012708340330

**Comment by Antonikas58** [comment]
20210127083403307

**Comment by Antonikas58** [comment]
sorry request id is 20210127083403307

**Comment by Antonikas58** [comment]
Also one more question. Can the password for user be the same as for signature key?

**Comment by NTCA-supporter** [comment]
Hi @Antonikas58 !
I can see the following:
Invalid request signature, actual:[F7C6C4C8E10C71928C0F5F441E28EDAC586E5050A8941BA87B2F5BF83C8FAA8023C1ADC3A32A9E060F987AEF14A5106C262F167E7C01C39797109B3F82F35254], expected:[595480F904258BCB5EE2BD9B67B82C420CF21CB7A41A6C9281485DDD3E9D2E222B869FBF67845893B2A51DF0F291DA2B7F163A68779E6BC5B9826AA44FD72483]

You can check your fix if you get the same result.
I don't really understand your second question :) 

Br

**Comment by Antonikas58** [comment]
We faced one strange problem that when we had the same password for User and Signature key our request was rejected, but when we updated the password for signature key and made it different then it was working, that is why the question is if there is any special check that passwords should not be the same?

**Comment by NTCA-supporter** [comment]
Hi @Antonikas58 !
Is there any more question?
Br

**Comment by NTCA-supporter** [comment]
I close the issue due to inactivity.
Feel free to reopen it.
