### ISSUE TITLE
Díjbekérő létrehozása - NEM MŰKÖDIK

### ISSUE THREAD

**Issue by kollaristvan** [nav-gov-hu/Online-Invoice#733]
SOS probléma!

Tegnap óta nem tudok díjbekérőt létrehozni. Ezidáig nem volt rá szükségem, tehát nem tudom, hogy valaha működött-e, de most egy 3 millió forintos szponzori szerződésem értelmében 8 napom van kiállítani egy díjbekérőt.

KATA-s egyéni vállalkozó vagyok.

Létrehoztam tömböt (már többet is próbaként), mindent kitöltök (egy tétel, egy megjegyzés, 0% áfa AAM). Ha mindent kitöltök, a "kitöltés ellenőrzése" gombra kattintva minden rendben, és aktív is lesz az előnézeti és véglegesítési gomb. Már az előnézet is hibát jelez és a véglegesítés is. 

Ez a probléma 24 órája fennáll. Sajnos előtte nem készítettem díjbekérőt, így azt nem tudom megmondani, hogy az elmúlt fél évben - mióta a rendszert használom - ez a funkció működött-e.

Most viszont SOS meg kellene valahogy oldanom a díjbekérő kiállítását, mivel a szponzorációs szerződésem feltétele, és ha nem oldom meg napokon beül, akkor szerződést szegek és elbukom a 3 millió forintot. Azt meg nem szeretném.

Köszönöm gyors segítségük!

**Comment by fenyvessy** [comment]
@kollaristvan , ez nem az a hely, ahol a NAV számlázó támogatása történik, itt a számlázó programok adatszolgáltatásával kapcsolatban folyik a diskurzus, szóval érdemi támogatást a problémád vonatkozásában szerintem nem fogsz kapni. De hogy segítsek is: a díjbekérő nem szigorú számadású bizonylat, azaz fogsz egy tetszőleges szövegszerkesztőt, megnyitod benne azt a dokumentumot, amit a google "díjbekérő minta" keresésre feldobott, kitöltöd és már küldheted is. Amikor megérkezett a pénz a számládra, akkor **kell** majd kiállítani róla a számlát, amit gondolom már meg fogsz tudni tenni a NAV számlázójában, ahogy eddig is tetted.

**Comment by kollaristvan** [comment]
> @kollaristvan , ez nem az a hely, ahol a NAV számlázó támogatása történik, itt a számlázó programok adatszolgáltatásával kapcsolatban folyik a diskurzus, szóval érdemi támogatást a problémád vonatkozásában szerintem nem fogsz kapni. De hogy segítsek is: a díjbekérő nem szigorú számadású bizonylat, azaz fogsz egy tetszőleges szövegszerkesztőt, megnyitod benne azt a dokumentumot, amit a google "díjbekérő minta" keresésre feldobott, kitöltöd és már küldheted is. Amikor megérkezett a pénz a számládra, akkor **kell** majd kiállítani róla a számlát, amit gondolom már meg fogsz tudni tenni a NAV számlázójában, ahogy eddig is tetted.

Köszönöm! Sejtettem, hogy ez lesz a megoldás.

**Comment by NTCA-supporter** [comment]
Sziasztok!

A problémát javítottuk. Kérlek ellenőrizzétek és zárjátok az issuet, ha rendben van.

Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet, ha van még probléma, nyissátok újra. Köszönjük a jelzést.
Üdv
