### ISSUE TITLE
[Q&A] taxpayerShortName "kr. a." értelmezése

### ISSUE THREAD

**Issue by salesdb** [nav-gov-hu/Online-Invoice#734]
Nemrég elérhetővé vált a taxpayerShortName, ez nagyszerű!
Nagyon megkönnyíti a számlát kiállító életét, sokkal szebbek a számlák a ShortName-el mint az értelmetlenül hosszú cégnevekkel.

Azt vettem észre, hogy a rövidítés nem csak a vevő nevét hanem a hozzátartozó fontos információt is rövidíti. pl így:
v. a. = Végelszámolás alatt
kr. a. = Kényszertörlés alatt

A taxpayerName mezőben ezek szépen benne vannak, de nem értik az ügyfeleink a "kr. a." rövidítést.

Megoldható-e hogy ez a fontos infó a rövid névben is ki legyen írva. Tehát a rövidítés csak a vásárló nevére vonatkozzon?
Amennyiben nem, kaphatok-e egy listát az összes előforduló rövidítésről?

**Comment by salesdb** [comment]
ide is rosszul írtam, nem kr. a. hanem kt. a., mindegy a kérdésemen ez nem változtat.

**Comment by clapygeza** [comment]
@salesdb 
2006. évi V. törvény
5. § *  A cég nevét (rövidített nevét)

a) a cégbejegyzési eljárás alatt „bejegyzés alatt” („b. a.”),

b) csődeljárás esetén „csődeljárás alatt” („cs. a.”),

c) felszámolási eljárás esetén „felszámolás alatt” („f. a.”),

d) végelszámolási eljárás esetén „végelszámolás alatt” („v. a.”),

e) kényszertörlési eljárás esetén „kényszertörlés alatt” („kt. a.”),

f) *  határokon átnyúló egyesülés céljára létrejövő cég esetén „egyesülés céljára alapított” („e.a.”)

toldattal kell használni.

**Comment by salesdb** [comment]
Köszönöm, ez jó lesz
