### ISSUE TITLE
[Q&A] Kell-e számítani a belátható közeljövőben új verzióra? (3.1, 4.0, stb.)

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#737]
Nincs semmi hiányérzetem, örülök, hogy megy a 3.0 és sikerült átállni, pusztán az előre tervezés miatt kérdezem, hogy van-e kilátásban a közeljövőben valami változás (3.1, 4.0) , lesz-e valami újabb határidő (pl. 2022), miben lesz új a következő verzió (ha lesz), mire számítsunk?

**Comment by renced42** [comment]
Kedves @nbeeps2 

Jelen pillanatban nem tervezzük sem a 3.1-et sem a 4.0-t, Ennél fogva határidő sincs. Várjuk, hogy mindenki sikeresen áttérjen a 3.0-ra, illetve a mi oldalunkon is van munka, amivel el tudjuk magunkat foglalni a 3.0-val kapcsolatban.

**Comment by csaszko** [comment]
:) 

> Jelen pillanatban nem tervezzük sem a 3.1-et sem a 4.0-t, Ennél fogva határidő sincs. 

https://onlineszamla.nav.gov.hu/home

> Online Számla 3.2.2-es verzió
> 2021-01-15 00:00
> Az Online Számla rendszer 3.2.2-es verziójának javításával megszűnt az a hiba, ami miatt az önzáró taget tartalmazó XML-fájl feldolgozása „SAVED” állapotban maradt. Az ilyen jellegű számlák sémasértés miatt most már „ABORTED” státuszt kapnak.

**Comment by renced42** [comment]
Kedves @csaszko 

Tudom, hogy odaraktad a szmájlit, de egyértelmű, hogy a kérdés nyilvánvalóan az XSD specire vonatkozott és nem a NAV Online Számla alkalmazás verzióra.

Kedves @nbeeps2 
Ha nincs több kérdés ezzel kapcsolatosan kérlek zárd az issuet.
