### ISSUE TITLE
[Q&A] áfakerekítés

### ISSUE THREAD

**Issue by jozanesz** [nav-gov-hu/Online-Invoice#738]
Amennyiben több számlatétel esetén számlatételenként számítunk áfát és bruttó Ft-ot,  ez esetben a számlatételek áfájának összege és bruttó forintjának összege többnyire nem egyezik meg - kerekítési eltérések miatt - az áfaszázalékonkénti számlaösszesítő áfájával és bruttó Ft-jával. Az eltérések korrigálására áfaszázalékonként számított áfakerekítési különbözetet használunk, ami a számlaképen _kerekítési különbözet_ sorként jelenik meg. Hogyan kell ezt a különbözetet beadni az XML-ben? Számlatételként? Milyen értéket kell tenni az _áfakerekítési különbözet_ sor számlatétel nettó Ft, áfa Ft, áfa %  és bruttó Ft adataiba? (A számlaképen a különbözet sorokban a nettó Ft rovat üres, és esetleg az áfa % is.)

**Comment by NTCA-tax** [comment]
Ilyen sornak a beszúrását a jogszabály nem írja elő és nem is tudnám levezetni. Ugyanakkor ettől még több vállalkozásnál bevett megoldás a kerekítési különbözet, mely nem csupán adót, hanem akár adóalapot is érinthet, attól függ ki hogyan közelíti meg a kerekítést. Tehát nincs olyan szabály, mit kell tenni, bármely megoldás jó lehet, ha ténylegesen csak kerekítési különbözetet jelent.

**Comment by jozanesz** [comment]
Ennél konkrétabb segítségre számítottam. :(

Pl. a számlaképtörvényben szerepel a _Kerekítés_, de mint sok minden mást, ezt sem magyarázza.
Ugyanakkor a jelenleg érvényes áfatörvény tudtommal nem ír elő kötelezettséget a számlán belüli áfaösszesítésre normál számlák esetén. Ennek ellenére az adatszolgáltatás igen: summaryByVatRate. Az áfatörvény alapján kötelező „áthárított adó” a számlaképtörvény alapján csak az összesítőben szerepelhet. Tételenként viszont _valószínűleg_ a „Bruttó érték (Ft)” feltüntetendő.

Ha szépen összeadogatjuk a tételek áfatartalmát és bruttó értékét, és ezt írjuk az összesítőbe, akkor kisebb összegeknél gyakran kapunk INCORRECT_SUMMARY_CALCULATION_VAT_RATE_VAT_AMOUNT_HUF_SUMMARY* és INCORRECT_SUMMARY_CALCULATION_VAT_RATE_VAT_AMOUNT_SUMMARY figyelmeztetést. Ezt csak úgy lehet elkerülni, ha nem a tételek adóforintjait (lineVatAmount[HUF]) összesítjük, hanem az összesített nettóra (vatRateNetAmount[HUF]) számoljuk az adót.

Ha viszont a számlán szerepelnek tételenként az adóforintok és/vagy bruttó értékek, akkor ezek összege így nem feltétlenül egyezik az összesítésben lévő adóval és bruttóval. Ahol tömegesen gyártják a számlákat, ott nem szeretnék kockáztatni, hogy a vevők megreklamálják az eltérést.

**Akkor most kérnék kb. három jó példát a „bármely megoldásra”. :)**

Jelenleg be lehet adni számlatételként 0 nettó forintos kerekítést nem 0 (akár negatív) áfával, de nehéz lenne megmagyarázni, hogy ez miféle szolgáltatás/termékértékesítés.

Még trükkösebben tűnik az egyik számlakibocsátó azon megoldása, hogy a kerekítést „AHK” megjelöléssel szerepeltetik a számlán, ebben a sorban csak a „bruttó díj” van kitöltve a számlaképen (+-x Ft),  de alatta az „ÁFA összesítõ” rovatban nincs AHK-ra összesítés: jól össze is zavarna mindenkit, ha lenne. Az adatszolgáltatás ezt tartalmazza:
```xml
<line>
<lineNumber>...</lineNumber>
<advanceIndicator>false</advanceIndicator>
<lineExpressionIndicator>true</lineExpressionIndicator>
<lineDescription>Kerekítés</lineDescription>
<quantity>1.0</quantity>
<unitOfMeasure>OWN</unitOfMeasure>
<unitOfMeasureOwn>Ft</unitOfMeasureOwn>
<unitPrice>0.0</unitPrice>
<unitPriceHUF>0.0</unitPriceHUF>
<lineAmountsNormal>
<lineNetAmountData>
<lineNetAmount>0.0</lineNetAmount>
<lineNetAmountHUF>0.0</lineNetAmountHUF>
</lineNetAmountData>
<lineVatRate>
<vatOutOfScope>true</vatOutOfScope>
</lineVatRate>
</lineAmountsNormal>
</line>
```
Ebben a tételben a számlaképen szereplő bruttó +-x Ft nem szerepel, az ott nem szereplő egyéb adatok ellenben igen. Majd az összesítés:
```xml
<summaryByVatRate>
<vatRate>
<vatOutOfScope>true</vatOutOfScope>
</vatRate>
<vatRateNetData>
<vatRateNetAmount>0.0</vatRateNetAmount>
<vatRateNetAmountHUF>0.0</vatRateNetAmountHUF>
</vatRateNetData>
<vatRateVatData>
<vatRateVatAmount>0.0</vatRateVatAmount>
<vatRateVatAmountHUF>0.0</vatRateVatAmountHUF>
</vatRateVatData>
</summaryByVatRate>
```
Ennek meg nincs nyoma a számlaképen.

---

*Az INCORRECT_SUMMARY_CALCULATION_VAT_RATE_VAT_AMOUNT_HUF_SUMMARY-ból több jön, mint INCORRECT_SUMMARY_CALCULATION_VAT_RATE_VAT_AMOUNT_SUMMARY-ból. Az a gyanúm, hogy **a #444 csak lezárva lett, de megoldva nem**.

Igazából üdvös lenne, ha **ezek a figyelmeztetések egyáltalán nem jelentkeznének, amikor az összesítő sor adótartalma megegyezik a tételsorok helyesen számított adóértékeinek összegével.**

**Comment by JimTudeski** [comment]
A legnagyobb baj, hogy a mai napig nincs a számításra és kerekítésre egy szabályzás/előírás. Heti példa egyik ügyfelemnél:
![image](https://user-images.githubusercontent.com/11393403/107113476-6de77800-685f-11eb-8f21-20313d5f6847.png)

A nettó összesen 0,07 miatt felfele kerekedik. A bruttó 460,4639 lefele. Így "összenyomja" a kettő közt keletkező ÁFA értéket, ami 97 lesz. Ha csak a tételek ÁFÁ-it nézzük viszon, akkor 97,74, amit az összesítőben egyébként meg felfele kellene kerekíteni. Így most a példában kijön az 1ft ÁFA különbség és jön a INCORRECT_SUMMARY_CALCULATION_VAT_RATE_VAT_AMOUNT_HUF_SUMMARY...

**Comment by lvitya586** [comment]
> Mit kéne cisnálni? A 363-at nettó összesennek megtartani, ehhez venni előbb a kerekített ÁFÁ-t a 98-at, és a végösszeg fog 1Ft-tal emelkedni 461-re?

Pontosan ez lesz a helyes megoldás, ugyanis a bruttó=nettó+adó és nem a bruttóból számítjuk vissza a nettót vagy az adót

**Comment by pitfla** [comment]
Nem jó a példa táblázat és a magyarázat sem. A táblázatnak nem jó az összesítése, mert az áfákat összeadva 98 ft lenne és akkor már a nettó+áfa sem 460 ft.
A válasz azért nem jó, mert ha valakinek a polcon az áru 460 ft-al van kitéve, akkor bizony a bruttóból kell visszaszámolni a nettót és az áfát.
Én azt az elvet követem ilyenkor, hogy -az adóhatóságnak kedvezve- az áfát kerekítem inkább fel, abból még gond nem volt.
Ez viszont olyankor probléma, amikor direktben készlet rendszerből megy a számlázás szerződés szerinti egységárakon, ahol az egységárat, így a nettót sem lehet akárhová kerekíteni.
Szóval nincs tökéletes megoldás, ami minden esetet lefed.

**Comment by DrotosTot** [comment]
Mivel nincs szabály, nálunk csak a számla végösszegénél alkalmazunk kerekítést, egészre: az egyes tételsorok összege és a kerekített érték közötti különbözet lesz a kerekítés nettó és bruttó végösszegnél. Ezt követően a kerekített bruttónál számoljuk az 1-2 forintosok miatti további kerekítést, kp-val történő kiegyenlítés esetén.
Ennek a megoldásnak az a hátránya, hogy, ha egy több számlából álló számlaláncolatot érvénytelenítenek, akkor nem a tételsorok összegét kell a végösszeg kerekítésének számításakor figyelembe venni, hanem a számlaláncolat egyes számláinak kerekített végösszegeit, mert csak így fog egyezni az érvénytelenítő számla végösszege a számlaláncolatban levő számlák végösszegének összegével (huh, ez a mondat gyönyörű lett...).

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezzel kapcsolatban van még kérdés? Ha nincs, kérlek zárjátok.

Üdv

**Comment by pitfla** [comment]
Igazából a probléma és a kérdés abból adódik, hogy amikor a fillérek megszűntek, akkor mi "úgy lettünk iskolázva", hogy a tételekben sem lehet tizedes érték. Ezért volt problémás és kérdéses, hogy mi legyen a kerekítési szabály.
Sokan úgy építettük fel a rendszerünket, hogy forintos számlánál minden áfa és bruttó kerekített, mert egész forint létezik csak.
Ezért az "új iskola" nem érti, hogy mi ezzel a problémánk. 
A megoldás annyi, hogy nekünk kell alkalmazkodni az új világhoz, ahol már a forintot is 2 tizedessel szokás feltüntetni. Lásd, a NAV online-számlázó is szórja a tizedeseket. Régen ilyenért harapott a APEH revizor!
Részemről a topikot lezárhatjuk.

**Comment by NTCA-supporter** [comment]
Köszi a visszajelzést, zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv

**Comment by jozanesz** [comment]
> Ezzel kapcsolatban van még kérdés? Ha nincs, kérlek zárjátok.

Amire nem kaptam választ, továbbra is várom. Csak ez egyetlen már megoldott mellékes problémát töröltem a korábbi írásomból.

Pl. a számlaképtörvényben szerepel a _Kerekítés_, de mint sok minden mást, ezt sem magyarázza.
Ugyanakkor a jelenleg érvényes áfatörvény tudtommal nem ír elő kötelezettséget a számlán belüli áfaösszesítésre normál számlák esetén. Ennek ellenére az adatszolgáltatás igen: summaryByVatRate. Az áfatörvény alapján kötelező „áthárított adó” a számlaképtörvény alapján csak az összesítőben szerepelhet. Tételenként viszont _valószínűleg_ a „Bruttó érték (Ft)” feltüntetendő.

Ha szépen összeadogatjuk a tételek áfatartalmát és bruttó értékét, és ezt írjuk az összesítőbe, akkor kisebb összegeknél gyakran kapunk INCORRECT_SUMMARY_CALCULATION_VAT_RATE_VAT_AMOUNT_HUF_SUMMARY és INCORRECT_SUMMARY_CALCULATION_VAT_RATE_VAT_AMOUNT_SUMMARY figyelmeztetést. (Igazából üdvös lenne, ha ezek a figyelmeztetések egyáltalán nem jelentkeznének, amikor az összesítő sor adótartalma megegyezik a tételsorok helyesen számított adóértékeinek összegével.) Ezt csak úgy lehet elkerülni, ha nem a tételek adóforintjait (lineVatAmount[HUF]) összesítjük, hanem az összesített nettóra (vatRateNetAmount[HUF]) számoljuk az adót.

Ha viszont a számlán szerepelnek tételenként az adóforintok és/vagy bruttó értékek, akkor ezek összege így nem feltétlenül egyezik az összesítésben lévő adóval és bruttóval. Ahol tömegesen gyártják a számlákat, ott nem szeretnék kockáztatni, hogy a vevők megreklamálják az eltérést.

**Akkor most kérnék kb. három jó példát a „bármely megoldásra”.**

Jelenleg be lehet adni számlatételként 0 nettó forintos kerekítést nem 0 (akár negatív) áfával, de nehéz lenne megmagyarázni, hogy ez miféle szolgáltatás/termékértékesítés.

Még trükkösebbnek tűnik az egyik számlakibocsátó azon megoldása, hogy a kerekítést „AHK” megjelöléssel szerepeltetik a számlán, ebben a sorban csak a „bruttó díj” van kitöltve a számlaképen (+-x Ft),  de alatta az „ÁFA összesítõ” rovatban nincs AHK-ra összesítés: jól össze is zavarna mindenkit, ha lenne. Az adatszolgáltatás ezt tartalmazza:
```xml
<line>
<lineNumber>...</lineNumber>
<advanceIndicator>false</advanceIndicator>
<lineExpressionIndicator>true</lineExpressionIndicator>
<lineDescription>Kerekítés</lineDescription>
<quantity>1.0</quantity>
<unitOfMeasure>OWN</unitOfMeasure>
<unitOfMeasureOwn>Ft</unitOfMeasureOwn>
<unitPrice>0.0</unitPrice>
<unitPriceHUF>0.0</unitPriceHUF>
<lineAmountsNormal>
<lineNetAmountData>
<lineNetAmount>0.0</lineNetAmount>
<lineNetAmountHUF>0.0</lineNetAmountHUF>
</lineNetAmountData>
<lineVatRate>
<vatOutOfScope>true</vatOutOfScope>
</lineVatRate>
</lineAmountsNormal>
</line>
```
Ebben a tételben a számlaképen szereplő bruttó +-x Ft nem szerepel, az ott nem szereplő egyéb adatok ellenben igen. Majd az összesítés:
```xml
<summaryByVatRate>
<vatRate>
<vatOutOfScope>true</vatOutOfScope>
</vatRate>
<vatRateNetData>
<vatRateNetAmount>0.0</vatRateNetAmount>
<vatRateNetAmountHUF>0.0</vatRateNetAmountHUF>
</vatRateNetData>
<vatRateVatData>
<vatRateVatAmount>0.0</vatRateVatAmount>
<vatRateVatAmountHUF>0.0</vatRateVatAmountHUF>
</vatRateVatData>
</summaryByVatRate>
```
Ennek meg nincs nyoma a számlaképen.

Szóval mi a jó megoldás?
