### ISSUE TITLE
[Q&A]Számla minta kérés

### ISSUE THREAD

**Issue by pelach** [nav-gov-hu/Online-Invoice#74]
Üdv!
Legutóbb voltak számla minták.
Lehetne ide is kérni?
Köszönöm!

**Comment by NTCA-developer** [comment]
Szia!

Természetesen, még csak kérni sem kell. Az egyetlen nehezítő tényező, hogy a data sample-t nem mi, hanem a szakmai terület csinálja, így nem látok rá mikorra készülnek el. De rákérdezek és visszajelzek.

**Comment by NTCA-developer** [comment]
Szia @pelach 

Úgy saccoljuk, hogy október közepére elérhető lesz a data sample is. Ahogy az API sample XML esetében, kitesszük majd ide és az Online számla felületre is a dokumentációk közé.
