### ISSUE TITLE
[Q&A] Külföldi cégek adószámai

### ISSUE THREAD

**Issue by kassayAkos** [nav-gov-hu/Online-Invoice#740]
A dokumentációban ez szerepel: `Vevő a Közösség másik tagállamában nyilvántartásba vett adóalany, és az ügyletet belföldi 27, 18 vagy 5%-os áfa terheli. Ilyenkor a customerVatStatus = OTHER és a customerInfo/customerVatData/communityVatNumber töltése nem kötelező, de lehetséges megadni.` 

Hogyan kell eljárni abban az eseten, ha a vevőnek nincs közösségi adószáma és a fenti kategóriába tartozik, tehát áfá-s számlát állítunk ki neki? Az adatszolgáltatásban nem lehet felküldeni a customerTaxNumber/taxpayerId, csak számjegyeket. Hogyan kell adatot szolgáltatni az olyan külföldi adószámokról, amelyek pl 1 vagy 2 betűvel kezdődnek vagy több mint 8 számjegyből állnak?

pl. Az eladó magyarországi adóalany, a vevő romániai adóalany és nincs közösségi adószáma.
SC ISS EDU SRL, akinek az adószáma: RO33627988 (tartalmazza a RO-t)

pl.2 az eladó magyarországi adóalany, a vevő hollandiai adóalany és nincs közösségi adószáma.
SpaTrend B.V., adószáma: 858654659 (9 számjegyű)

Segítségüket és válaszukat előre is köszönjük.

**Comment by lvitya586** [comment]
Szerintem itt tárgyi tévedések vannak a közösségi adószámmal kapcsolatban.
Az említett példák pontosan a közösségi adószámokra jellemzők, így nem tudom miből jött ki az a vélemény, hogy nem azok.

Ezeket ugyanúgy le lehet kérdezni a VIES segítségével, mintha magyar adószámok lennék, sőt! Még ingyenes SOAP szervíz is van, amivel le lehet kérdezni és ezt be lehet építeni akár programba is. (Én beépítettem az enyémbe)

A két példa válasza a lekérdezés által:

1.

`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
	<soap:Body>
		<checkVatResponse xmlns="urn:ec.europa.eu:taxud:vies:services:checkVat:types">
			<countryCode>RO</countryCode>
			<vatNumber>33627988</vatNumber>
			<requestDate>2021-01-29+01:00</requestDate>
			<valid>true</valid>
			<name>ISS EDU SRL</name>
			<address>MUN. IAŞI BLD. ALEXANDRU CEL BUN Nr. 37 Bl.  E2 Sc. D Et. 2 Ap. 3</address>
		</checkVatResponse>
	</soap:Body>
</soap:Envelope>`

2.
Ebben a példában hiányosan lett megadva az adószám, mert a holland formátum NL#########B##, de egy kis kiegészítéssel már meg is lett az eredmény.

`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
	<soap:Body>
		<checkVatResponse xmlns="urn:ec.europa.eu:taxud:vies:services:checkVat:types">
			<countryCode>NL</countryCode>
			<vatNumber>858654659B01</vatNumber>
			<requestDate>2021-01-29+01:00</requestDate>
			<valid>true</valid>
			<name>SPATREND B.V.</name>
			<address>WILLIBRORDUSLAAN 00087 5552HC VALKENSWAARD</address>
		</checkVatResponse>
	</soap:Body>
</soap:Envelope>`

**Comment by JamborTimea** [comment]
Köszi szépen a választ! Van egy másik eset is, szintén romániai a cég: SC Mali Place SRL , adószáma: 749725, EU adószáma nincs és ezt nem tudjuk felküldeni, mert nem 8 számjegyű.

**Comment by JamborTimea** [comment]
És még van két eset: Podoleanu Irina  P.F.A., romániai adóalany, adószáma: RO41415692, Vies-el ellenőrízve:  Nem, az uniós adószám érvénytelen, ezért nem használható fel tagállamközi ügyletekhez.

STAFF BROKER DE ASIGURARE SRL - romániai adóalany, adószáma: 7820938, https://termene.ro/firma/7820938-STAFF-BROKER-DE-ASIGURARE-SRL, EU adószáma neki sincs.

Az ő esetükben, hogyan járjunk el?

Válaszát előre is nagyon szépen köszönöm!

**Comment by lvitya586** [comment]
Mivel a customerTaxNumber/taxpayerId csak magyar adószám megadására szolgál, ezért oda semmiképpen nem kerülhet. A communityVatNumber jöhetne szóba, de ha nincs közösségi adószáma, akkor gondolom a dokumentáció 86. oldalán található 5. sorszámú eset alapján kell eljárni ezekben az esetekben.

> Vevő a Közösség másik tagállamában nyilvántartásba vett adóalany, és az ügyletet belföldi 27, 18 vagy 5%-os áfa terheli.
customerVatStatus = OTHER
customerInfo/customerVatData/communityVatNumber töltése nem kötelező, de lehetséges megadni.

De majd feltételezem valaki hivatalosan is fog nyilatkozni ezügyben.

**Comment by JamborTimea** [comment]
Köszönöm a választ! Igen én is afelé hajlok, hogy eszerint kell eljárni, de akkor a fenti esetek során, a külföldi vevő esetén nem küldenénk adószámot. Kíváncsian várom az illetékesek válaszát, hogy ez egy helyes út-e?

**Comment by NTCA-tax** [comment]
Amennyiben a vevő rendelkezik közösségi adószámmal és közösségi fordított adózás történt, akkor a vevő közösségi adószámát mindenképp szerepeltetni kell a számlán és az adatszolgáltatásban is. Ekkor az adatszolgáltatásban a communityVatNumber mezőben kell szerepeltetni az adószámát. 

Amennyiben nem rendelkezik közösségi adószámmal, akkor belföldi áfa kulcsot kell szerepeltetni, és megerősítem @lvitya586 bejegyzését, hogy a dokumentáció ebben az esetben ténylegesen azt tartalmazza, hogy lehetséges, de nem kötelező a vevő adószámát a communityVatNumber mezőben szerepeltetni.

**Comment by JamborTimea** [comment]
Köszönöm szépen a választ!
