### ISSUE TITLE
2.0 verzióval kiállított számlák utólagos beküldése

### ISSUE THREAD

**Issue by timjoe** [nav-gov-hu/Online-Invoice#741]
Tisztelt Kollégák!

Ügyfelemnél egyelőre még nem vezettük be az OSZ 3.0-t, a 2.0-s verzió működik.
Ügyfelem könyvelője felhívta a NAV ügyfélszolgálatát (1819 / 7 /2), hogy a 2.0 verzióval idén készített fel nem adott számlákkal van-e valami teendő, mivel a PTGSZLAH nevű nyomtatvány megszűnt, azon nem tud adatot szolgáltatni róluk.
Az ügyfélszolgálattól azt a tájékoztatást kapta, hogy az adatszolgáltatási kötelezettség (függetlenül attól hogy a NAV 03.31-ig nem szankciónál ezen számlák azonnali fel nem adása miatt) változatlanul fennáll, így vagy kézzel fel kell rögzíteni a számlák adatait, vagy a 3.0 indulása után kell a számlázó programnak beküldenie a számlaadatokat. 
A könyvelő hiába hivatkozott arra, hogy a NAV alábbi linken megjelent tájékoztatójában ilyenről nem esik szó:

https://nav.gov.hu/nav/ado/afa/Online_Szamla__Marciu20201216.html

Létezik ezzel kapcsolatban a telefonos ügyfélszolgálatnál "hivatalosabbnak" tekinthető rendelet/állásfoglalás?

Tj

**Comment by NTCA-tax** [comment]
Az áfa törvény alapján 2021. január 4-től teljesen kiszélesedett az adatszolgáltatási kötelezettség. Ugyanakkor az általad is idézett adóhivatali közlemény alapján 2021. március 31-ig szankcionálási moratóriumot vezetett be az adóhivatal az olyan számlatípusok adatszolgáltatására, amelyekre vonatkozóan csak 2021-től van adatszolgáltatási kötelezettség. A közlemény ennél árnyaltabban fogalmaz, de nagyjából ez a lényege. Ezen (és csak ezen!) számlák vonatkozásában nem szankcionál az adóhivatal, amennyiben nem történt meg adatszolgáltatás, hibás az adatszolgáltatás. Ekkor nem kell az adatszolgáltatást pótolni, kijavítani (a közlemény utolsó mondata ezt tartalmazza).

Amennyiben a számla a 2020. július 1-jei szabályozás alapján adatszolgáltatásra kötelezett (belföldi adóalanynak kiállított bármely számla), akkor ezen számlák adatszolgáltatási mulasztására nem vonatkozik a szankcionálási moratórium. 

Amennyiben a kérdésed a nem adóalany magánszemélyeknek kiállított számlára vonatkozik, akkor ezen számlák vonatkozásában nincs PTGSZLAH nyomtatványon adatszolgáltatási kötelezettséged, és az adóhivatal nem szankcionál, amennyiben 2021. március 31-ig ilyen számlákról nem teljesítesz adatszolgáltatást.

**Comment by timjoe** [comment]
Értem, hogy ha a nem adóalany magánszemélyek számláiról 03.31-ig nem történik adatszolgáltatás, akkor nincs szankció, de a kérdés arra (is) irányult, hogy a NAV ügyfélszolgálata által említett - 03.31 előtt magánszemélyeknek kiállított számlákról - UTÓLAGOS adatszolgáltatás kötelező-e a 3.0 elindítása után.  (Ha nem, akkor az ügyfélszolgálat miért állítja ezt, ha igen, akkor hol találok erről valamilyen hivatalos állásfoglalást.)

**Comment by NTCA-tax** [comment]
Az adóhivatali közlemény utolsó mondatát tudnám csak beidézni: "A fentieknek megfelelő esetekben a szankciómentességnek nem feltétele a jelzett időszakban nem teljesített adatszolgáltatás utólagos pótlása vagy a nem megfelelő adatszolgáltatás utólagos korrekciója."

**Comment by timjoe** [comment]
Tisztelt NTCA-tax!

Ezek szerint a NAV ügyfélszolgálatának információja, miszerint "a magánszemélyek 2.0-val kiállított számláit UTÓLAG BE KELL KÜLDENI" téves?

**Comment by RvPSc** [comment]
Ez lesz az, amire nem fogsz egyértelmű választ kapni, csak valami terelést, de mindenkit érdekelne. (lásd előző válasz, meg vagy 4 másik isssue, állásfoglalás kérések stb)

**Comment by NTCA-tax** [comment]
Köszönöm a jelzést, az ügyfélszolgálat felé jelzem. 

Ettől függetlenül az adóhivatali közlemény egyértelműen megválaszolja a kérdésedet, mely mindenki számára elérhető és egyértelműen hivatkozható.

**Comment by NTCA-tax** [comment]
Mivel az összes felmerült kérdés megválaszolásra került, ezért zárom ezt az issue-t.
