### ISSUE TITLE
Response code 401 [DEV support]

### ISSUE THREAD

**Issue by lazaralexandra** [nav-gov-hu/Online-Invoice#742]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[X] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[X] 3.0

**A requestId értéke / requestId value**
```

```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Az alábbi hibaüzenetet kapjuk:
message: Response code 401 mapped as failure.
A dokumentumban csak azt található, hogy a hibaüzenet oka Invalid_Security_user.
Mit takarhat ez pontosan? Milyen esetekben kaphatunk ilyen hibaüzenet?

*Egyéb tartalom / Additional content*

**Comment by renced42** [comment]
Kedves  @lazaralexandra 

Kicsit bővebben fejtsd ki kérkel, mit és milyen URL-re küldesz :)

Köszi!

**Comment by lazaralexandra** [comment]
A használt URL: https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3/manageInvoice
Ami még szintén nem működik a manageAnnulment.
A fejlesztő azt írja, hogy a queryTransaction működik v3-ra és nem volt változás a crypto algoritmusban.
A manageinvoce xml:

<?xml version="1.0" encoding="UTF-8"?>
<ManageInvoiceRequest xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns="http://schemas.nav.gov.hu/OSA/3.0/api">
	<common:header>
		<common:requestId>20210201122344892</common:requestId>
		<common:timestamp>2021-02-01T12:23:44.892Z</common:timestamp>
		<common:requestVersion>3.0</common:requestVersion>
		<common:headerVersion>1.0</common:headerVersion>
	</common:header>
	<common:user>
		<common:login>7nvptfaqsb7lzoj</common:login>
		<common:passwordHash cryptoType="SHA-512">26C9981FCAC43EAE16125C99FCC30D621EA3DC982B0F912CB4939DE7D0C1F7F640893BCE1181C14E68893DB7F03B3A995D4D75D235C5265085D641736A9172F50</common:passwordHash>
		<common:taxNumber>11222149</common:taxNumber>
		<common:requestSignature cryptoType="SHA3-512">711E8186A65FA8CD22186A9F3F908D0EF32F55F95117436451AE44804C9F693125AAAD02922F575C06C8439E50802E2956F749929F54B84A3A96F28BF51013B3</common:requestSignature>
	</common:user>
	<software>
		<softwareId>MULESOFT0000000000</softwareId>
		<softwareName>BaanERP 5.0</softwareName>
		<softwareOperation>LOCAL_SOFTWARE</softwareOperation>
		<softwareMainVersion>5.0</softwareMainVersion>
		<softwareDevName>Infor(US) Inc</softwareDevName>
		<softwareDevContact>string</softwareDevContact>
		<softwareDevCountryCode>US</softwareDevCountryCode>
		<softwareDevTaxNumber>11222149</softwareDevTaxNumber>
	</software>
    <exchangeToken>ed03dfde-a4cb-42a9-a1ab-923f1034ca983989UX0AS2WT</exchangeToken>
    <invoiceOperations>
        <compressedContent>false</compressedContent>
        <invoiceOperation>
            <index>1</index> 
            <invoiceOperation>CREATE</invoiceOperation>
            <invoiceData>PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRGLTgnPz4gPEludm9pY2VEYXRhIHhtbG5zPSJodHRwOi8vc2NoZW1hcy5uYXYuZ292Lmh1L09TQS8zLjAvZGF0YSIgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeHNpOnNjaGVtYUxvY2F0aW9uPSJodHRwOi8vc2NoZW1hcy5uYXYuZ292Lmh1L09TQS8zLjAvZGF0YSBpbnZvaWNlRGF0YS54c2QiIHhtbG5zOmNvbW1vbj0iaHR0cDovL3NjaGVtYXMubmF2Lmdvdi5odS9OVENBLzEuMC9jb21tb24iIHhtbG5zOmJhc2U9Imh0dHA6Ly9zY2hlbWFzLm5hdi5nb3YuaHUvT1NBLzMuMC9iYXNlIiA+ICA8aW52b2ljZU51bWJlcj5USVMvOTk0MTE1LzQ5OTwvaW52b2ljZU51bWJlcj4gICA8aW52b2ljZUlzc3VlRGF0ZT4yMDIxLTAxLTI3PC9pbnZvaWNlSXNzdWVEYXRlPiAgIDxjb21wbGV0ZW5lc3NJbmRpY2F0b3I+ZmFsc2U8L2NvbXBsZXRlbmVzc0luZGljYXRvcj4gICA8aW52b2ljZU1haW4+ICAgICA8aW52b2ljZT4gICAgICAgPGludm9pY2VIZWFkPiAgICAgICAgIDxzdXBwbGllckluZm8+ICAgICAgICAgICA8c3VwcGxpZXJUYXhOdW1iZXI+ICAgICAgICAgICAgIDxiYXNlOnRheHBheWVySWQgeG1sbnM6YmFzZT0iaHR0cDovL3NjaGVtYXMubmF2Lmdvdi5odS9PU0EvMy4wL2Jhc2UiPjExMjIyMTQ5PC9iYXNlOnRheHBheWVySWQ+ICAgICAgICAgICA8L3N1cHBsaWVyVGF4TnVtYmVyPiAgICAgICAgICAgPHN1cHBsaWVyTmFtZT5GTEVYVFJPTklDUyBJTlRFUk5BVElPTkFMIEtGVDwvc3VwcGxpZXJOYW1lPiAgICAgICAgICAgPHN1cHBsaWVyQWRkcmVzcz4gICAgICAgICAgICAgPGRldGFpbGVkQWRkcmVzcz4gICAgICAgICAgICAgICA8YmFzZTpjb3VudHJ5Q29kZSB4bWxuczpiYXNlPSJodHRwOi8vc2NoZW1hcy5uYXYuZ292Lmh1L09TQS8zLjAvYmFzZSI+SFU8L2Jhc2U6Y291bnRyeUNvZGU+ICAgICAgICAgICAgICAgPGJhc2U6cG9zdGFsQ29kZSB4bWxuczpiYXNlPSJodHRwOi8vc2NoZW1hcy5uYXYuZ292Lmh1L09TQS8zLjAvYmFzZSI+ODkwMDwvYmFzZTpwb3N0YWxDb2RlPiAgICAgICAgICAgICAgIDxiYXNlOmNpdHkgeG1sbnM6YmFzZT0iaHR0cDovL3NjaGVtYXMubmF2Lmdvdi5odS9PU0EvMy4wL2Jhc2UiPlphbGFlZ2Vyc3plZzwvYmFzZTpjaXR5PiAgICAgICAgICAgICAgIDxiYXNlOnN0cmVldE5hbWUgeG1sbnM6YmFzZT0iaHR0cDovL3NjaGVtYXMubmF2Lmdvdi5odS9PU0EvMy4wL2Jhc2UiPlBvc3RhPC9iYXNlOnN0cmVldE5hbWU+ICAgICAgICAgICAgICAgPGJhc2U6cHVibGljUGxhY2VDYXRlZ29yeSB4bWxuczpiYXNlPSJodHRwOi8vc2NoZW1hcy5uYXYuZ292Lmh1L09TQS8zLjAvYmFzZSI+dXQ8L2Jhc2U6cHVibGljUGxhY2VDYXRlZ29yeT4gICAgICAgICAgICAgICA8YmFzZTpudW1iZXIgeG1sbnM6YmFzZT0iaHR0cDovL3NjaGVtYXMubmF2Lmdvdi5odS9PU0EvMy4wL2Jhc2UiPjYzPC9iYXNlOm51bWJlcj4gICAgICAgICAgICAgPC9kZXRhaWxlZEFkZHJlc3M+ICAgICAgICAgICA8L3N1cHBsaWVyQWRkcmVzcz4gICAgICAgICA8L3N1cHBsaWVySW5mbz4gICAgICAgICA8Y3VzdG9tZXJJbmZvPiAgICAgICAgICAgPGN1c3RvbWVyVmF0U3RhdHVzPkRPTUVTVElDPC9jdXN0b21lclZhdFN0YXR1cz4gICAgICAgICAgIDxjdXN0b21lclZhdERhdGE+ICAgICAgICAgICAgIDxjdXN0b21lclRheE51bWJlcj4gICAgICAgICAgICAgICA8dGF4cGF5ZXJJZD4yNjkxMjg3NzwvdGF4cGF5ZXJJZD4gICAgICAgICAgICAgPC9jdXN0b21lclRheE51bWJlcj4gICAgICAgICAgIDwvY3VzdG9tZXJWYXREYXRhPiAgICAgICAgICAgPGN1c3RvbWVyTmFtZT5DaXRyaXggU3lzdGVtcyBJbnRlcm5hdGlvbmFsIEdtYkg8L2N1c3RvbWVyTmFtZT4gICAgICAgICAgIDxjdXN0b21lckFkZHJlc3M+ICAgICAgICAgICAgIDxzaW1wbGVBZGRyZXNzPiAgICAgICAgICAgICAgIDxiYXNlOmNvdW50cnlDb2RlIHhtbG5zOmJhc2U9Imh0dHA6Ly9zY2hlbWFzLm5hdi5nb3YuaHUvT1NBLzMuMC9iYXNlIj5IVTwvYmFzZTpjb3VudHJ5Q29kZT4gICAgICAgICAgICAgICA8YmFzZTpyZWdpb24geG1sbnM6YmFzZT0iaHR0cDovL3NjaGVtYXMubmF2Lmdvdi5odS9PU0EvMy4wL2Jhc2UiPlNjaGFmZmhhdXNlbjwvYmFzZTpyZWdpb24+ICAgICAgICAgICAgICAgPGJhc2U6cG9zdGFsQ29kZSB4bWxuczpiYXNlPSJodHRwOi8vc2NoZW1hcy5uYXYuZ292Lmh1L09TQS8zLjAvYmFzZSI+ODIwMDwvYmFzZTpwb3N0YWxDb2RlPiAgICAgICAgICAgICAgIDxiYXNlOmNpdHkgeG1sbnM6YmFzZT0iaHR0cDovL3NjaGVtYXMubmF2Lmdvdi5odS9PU0EvMy4wL2Jhc2UiPkNIPC9iYXNlOmNpdHk+ICAgICAgICAgICAgICAgPGJhc2U6YWRkaXRpb25hbEFkZHJlc3NEZXRhaWwgeG1sbnM6YmFzZT0iaHR0cDovL3NjaGVtYXMubmF2Lmdvdi5odS9PU0EvMy4wL2Jhc2UiPlJoZWlud2VnIDkuPC9iYXNlOmFkZGl0aW9uYWxBZGRyZXNzRGV0YWlsPiAgICAgICAgICAgICA8L3NpbXBsZUFkZHJlc3M+ICAgICAgICAgICA8L2N1c3RvbWVyQWRkcmVzcz4gICAgICAgICA8L2N1c3RvbWVySW5mbz4gICAgICAgICA8aW52b2ljZURldGFpbD4gICAgICAgICAgIDxpbnZvaWNlQ2F0ZWdvcnk+Tk9STUFMPC9pbnZvaWNlQ2F0ZWdvcnk+ICAgICAgICAgICA8aW52b2ljZURlbGl2ZXJ5RGF0ZT4yMDIxLTAxLTI3PC9pbnZvaWNlRGVsaXZlcnlEYXRlPiAgICAgICAgICAgPHBlcmlvZGljYWxTZXR0bGVtZW50PmZhbHNlPC9wZXJpb2RpY2FsU2V0dGxlbWVudD4gICAgICAgICAgIDxjdXJyZW5jeUNvZGU+VVNEPC9jdXJyZW5jeUNvZGU+ICAgICAgICAgICA8ZXhjaGFuZ2VSYXRlPjE5NC45NDk5NTwvZXhjaGFuZ2VSYXRlPiAgICAgICAgICAgPGludm9pY2VBcHBlYXJhbmNlPlBBUEVSPC9pbnZvaWNlQXBwZWFyYW5jZT4gICAgICAgICA8L2ludm9pY2VEZXRhaWw+ICAgICAgIDwvaW52b2ljZUhlYWQ+ICAgICAgIDxpbnZvaWNlTGluZXM+ICAgICAgICAgPG1lcmdlZEl0ZW1JbmRpY2F0b3I+ZmFsc2U8L21lcmdlZEl0ZW1JbmRpY2F0b3I+ICAgICAgICAgPGxpbmU+ICAgICAgICAgICA8bGluZU51bWJlcj4xPC9saW5lTnVtYmVyPiAgICAgICAgICAgPGFkdmFuY2VEYXRhPiAgICAgICAgICAgICA8YWR2YW5jZUluZGljYXRvcj5mYWxzZTwvYWR2YW5jZUluZGljYXRvcj4gICAgICAgICAgICAgPGFkdmFuY2VQYXltZW50RGF0YS8+ICAgICAgICAgICA8L2FkdmFuY2VEYXRhPiAgICAgICAgICAgPGxpbmVFeHByZXNzaW9uSW5kaWNhdG9yPnRydWU8L2xpbmVFeHByZXNzaW9uSW5kaWNhdG9yPiAgICAgICAgICAgPGxpbmVEZXNjcmlwdGlvbj5OUy1TRFctMzAwMC1Db3BwZXItV088L2xpbmVEZXNjcmlwdGlvbj4gICAgICAgICAgIDxxdWFudGl0eT4xPC9xdWFudGl0eT4gICAgICAgICAgIDx1bml0T2ZNZWFzdXJlPlBJRUNFPC91bml0T2ZNZWFzdXJlPiAgICAgICAgICAgPHVuaXRQcmljZT44MDA8L3VuaXRQcmljZT4gICAgICAgICAgIDxsaW5lQW1vdW50c05vcm1hbD4gICAgICAgICAgICAgPGxpbmVOZXRBbW91bnREYXRhPiAgICAgICAgICAgICAgIDxsaW5lTmV0QW1vdW50PjgwMDwvbGluZU5ldEFtb3VudD4gICAgICAgICAgICAgICA8bGluZU5ldEFtb3VudEhVRj4xNTU5NTkuOTY8L2xpbmVOZXRBbW91bnRIVUY+ICAgICAgICAgICAgIDwvbGluZU5ldEFtb3VudERhdGE+ICAgICAgICAgICAgIDxsaW5lVmF0UmF0ZT4gICAgICAgICAgICAgICA8dmF0RXhlbXB0aW9uLz4gICAgICAgICAgICAgICA8dmF0T3V0T2ZTY29wZT4gICAgICAgICAgICAgICAgIDxjYXNlPkFUSzwvY2FzZT4gICAgICAgICAgICAgICAgIDxyZWFzb24+T3V0IG9mIFZBVDwvcmVhc29uPiAgICAgICAgICAgICAgIDwvdmF0T3V0T2ZTY29wZT4gICAgICAgICAgICAgPC9saW5lVmF0UmF0ZT4gICAgICAgICAgICAgPGxpbmVWYXREYXRhPiAgICAgICAgICAgICAgIDxsaW5lVmF0QW1vdW50PjA8L2xpbmVWYXRBbW91bnQ+ICAgICAgICAgICAgICAgPGxpbmVWYXRBbW91bnRIVUY+MDwvbGluZVZhdEFtb3VudEhVRj4gICAgICAgICAgICAgPC9saW5lVmF0RGF0YT4gICAgICAgICAgICAgPGxpbmVHcm9zc0Ftb3VudERhdGE+ICAgICAgICAgICAgICAgPGxpbmVHcm9zc0Ftb3VudE5vcm1hbD44MDA8L2xpbmVHcm9zc0Ftb3VudE5vcm1hbD4gICAgICAgICAgICAgICA8bGluZUdyb3NzQW1vdW50Tm9ybWFsSFVGPjE1NTk1OS45NjwvbGluZUdyb3NzQW1vdW50Tm9ybWFsSFVGPiAgICAgICAgICAgICA8L2xpbmVHcm9zc0Ftb3VudERhdGE+ICAgICAgICAgICA8L2xpbmVBbW91bnRzTm9ybWFsPiAgICAgICAgIDwvbGluZT4gICAgICAgPC9pbnZvaWNlTGluZXM+ICAgICAgIDxpbnZvaWNlU3VtbWFyeT4gICAgICAgICA8c3VtbWFyeU5vcm1hbD4gICAgICAgICAgIDxzdW1tYXJ5QnlWYXRSYXRlPiAgICAgICAgICAgICA8dmF0UmF0ZT4gICAgICAgICAgICAgICA8dmF0RXhlbXB0aW9uLz4gICAgICAgICAgICAgICA8dmF0T3V0T2ZTY29wZT4gICAgICAgICAgICAgICAgIDxjYXNlPkFUSzwvY2FzZT4gICAgICAgICAgICAgICAgIDxyZWFzb24+T3V0IG9mIFZBVDwvcmVhc29uPiAgICAgICAgICAgICAgIDwvdmF0T3V0T2ZTY29wZT4gICAgICAgICAgICAgPC92YXRSYXRlPiAgICAgICAgICAgICA8dmF0UmF0ZU5ldERhdGE+ICAgICAgICAgICAgICAgPHZhdFJhdGVOZXRBbW91bnQ+ODAwPC92YXRSYXRlTmV0QW1vdW50PiAgICAgICAgICAgICAgIDx2YXRSYXRlTmV0QW1vdW50SFVGPjE1NTk1OS45NjwvdmF0UmF0ZU5ldEFtb3VudEhVRj4gICAgICAgICAgICAgPC92YXRSYXRlTmV0RGF0YT4gICAgICAgICAgICAgPHZhdFJhdGVWYXREYXRhPiAgICAgICAgICAgICAgIDx2YXRSYXRlVmF0QW1vdW50PjA8L3ZhdFJhdGVWYXRBbW91bnQ+ICAgICAgICAgICAgICAgPHZhdFJhdGVWYXRBbW91bnRIVUY+MDwvdmF0UmF0ZVZhdEFtb3VudEhVRj4gICAgICAgICAgICAgPC92YXRSYXRlVmF0RGF0YT4gICAgICAgICAgICAgPHZhdFJhdGVHcm9zc0RhdGE+ICAgICAgICAgICAgICAgPHZhdFJhdGVHcm9zc0Ftb3VudD44MDA8L3ZhdFJhdGVHcm9zc0Ftb3VudD4gICAgICAgICAgICAgICA8dmF0UmF0ZUdyb3NzQW1vdW50SFVGPjE1NTk1OS45NjwvdmF0UmF0ZUdyb3NzQW1vdW50SFVGPiAgICAgICAgICAgICA8L3ZhdFJhdGVHcm9zc0RhdGE+ICAgICAgICAgICA8L3N1bW1hcnlCeVZhdFJhdGU+ICAgICAgICAgICA8aW52b2ljZU5ldEFtb3VudD44MDA8L2ludm9pY2VOZXRBbW91bnQ+ICAgICAgICAgICA8aW52b2ljZU5ldEFtb3VudEhVRj4xNTU5NTkuOTY8L2ludm9pY2VOZXRBbW91bnRIVUY+ICAgICAgICAgICA8aW52b2ljZVZhdEFtb3VudD4wPC9pbnZvaWNlVmF0QW1vdW50PiAgICAgICAgICAgPGludm9pY2VWYXRBbW91bnRIVUY+MDwvaW52b2ljZVZhdEFtb3VudEhVRj4gICAgICAgICA8L3N1bW1hcnlOb3JtYWw+ICAgICAgICAgPHN1bW1hcnlHcm9zc0RhdGE+ICAgICAgICAgICA8aW52b2ljZUdyb3NzQW1vdW50PjgwMDwvaW52b2ljZUdyb3NzQW1vdW50PiAgICAgICAgICAgPGludm9pY2VHcm9zc0Ftb3VudEhVRj4xNTU5NTkuOTY8L2ludm9pY2VHcm9zc0Ftb3VudEhVRj4gICAgICAgICA8L3N1bW1hcnlHcm9zc0RhdGE+ICAgICAgIDwvaW52b2ljZVN1bW1hcnk+ICAgICA8L2ludm9pY2U+ICAgPC9pbnZvaWNlTWFpbj4gPC9JbnZvaWNlRGF0YT4=</invoiceData>
        </invoiceOperation>
    </invoiceOperations>
</ManageInvoiceRequest>

**Comment by lazaralexandra** [comment]
Hova tudom csatolni a manageinvoice és az invoicedata xml-t, hogy meg tudjátok nézni?

**Comment by NTCA-supporter** [comment]
Szia @lazaralexandra !

Az interfész dokumentáció ide vonatkozó tartalma:
'Számos esetben jelentkezhet a hibaüzenet. Lehetséges okok: a megadott login névvel nem létezik felhasználó, vagy nem
helyes a jelszava, vagy a login + passwordHash pár szemantikailag helyes, de a jelszóhash rosszul kerül kiszámításra a kliens
oldalán. Meg kell győződni az adatok és a hashelés helyességéről, szükség esetén fel kell venni a kapcsolatot a technikai
felhasználót birtokló adózóval.'

Elég requestId-t küldeni, és akkor nézzük a logokat, nem kell a teljes xml.

Üdv

**Comment by lazaralexandra** [comment]
Request ID: 20210201122344892

**Comment by NTCA-supporter** [comment]
Szia @lazaralexandra !
Szerintem a content-type: text/plain a problémás. Kérlek próbáld meg a content-type=application/xml-t, ha az nem oldja meg, akkor nézem tovább.
Üdv

**Comment by lazaralexandra** [comment]
Átállította fejlesztő a content-typet. Utána invalid sec. error hibaüzenet mindegyik cégünkben.
Pl. Request ID: 20210203054104968
Ezt kellene akkor tovább nézni.
Köszönöm.

**Comment by NTCA-supporter** [comment]
Szia @lazaralexandra !
A leírás alapján olyan túl sok hibalehetőség nincs :) 
A tokenkérésnél (ami sikeres volt) és a számlabeküldésnél (ami sikertelen) a technikai felhasználóhoz más-más passwordHash van beküldve.
Üdv

**Comment by lazaralexandra** [comment]
Azt írja fejlesztő: the password hash generation is same for tokenexchange and invoice.
Tehát akkor ez nem lehet hiba. NTCA-supporterrel van lehetőség angolul telefonos segítséget kérni?
Köszönöm.

**Comment by lazaralexandra** [comment]
Pls note we are using the same login details for Query and it also works fine. Please let us know if anything has changed with respect to login/password for manageInvoice.  
Ezt írta még fejlesztő, hogy egyedül a manageInvoice-nál és ugye manageAnnulmentnél van ilyen probléma, Query-nél ugyanígy kezelik a logint, pswd-ot és ott jól működik, nem kapnak hibaüzenetet.
Köszönöm.

**Comment by NTCA-supporter** [comment]
Szia @lazaralexandra !
A NAV-nak van telefonos helpdeskje, ott lehet próbálkozni, de:

A logokból egyértelműen látszik (tesztrendszer ellenére a jelszóhasht nem írom ki teljesen):

**tokenExchange**:
requestId: 20210128064842868
reponse: 200 OK
<common:login>eg7wrtik5gyhszx</common:login>
<common:passwordHash cryptoType="SHA-512">125784B3FB7A2BEE24E514EF5BE5EBD8C92D3E24CB4E57A5DA7C...</common:passwordHash>
<common:taxNumber>30359730</common:taxNumber>

**manageInvoice**:
requestId: 20210203054104968 
reponse: 401 INVALID_SECURITY_USER
<common:login>eg7wrtik5gyhszx</common:login>
<common:passwordHash cryptoType="SHA-512">2125784B3FB7A2BEE24E514EF5BE5EBD8C92D3E24CB4E57A5DA7CD9EFC73C1D094FF7970FAB5C9EE884A6A...</common:passwordHash>
<common:taxNumber>30359730</common:taxNumber>

Ezek alapján nekem úgy tűnik a jelszóhash minden, csak nem ugyanaz a két kérésben.

Üdv

**Comment by NTCA-supporter** [comment]
Szia @lazaralexandra !
Van még kérdés?
Üdv

**Comment by lazaralexandra** [comment]
Nem, köszi. Sikerült így megoldani.
