### ISSUE TITLE
[DEV support] queryTransactionStatus - nics értékelhető válasz

### ISSUE THREAD

**Issue by Leslie7** [nav-gov-hu/Online-Invoice#743]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[x] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[x] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
manageInvoice : 164 Transaction _ID: 398O1WSODFY01UMQ
queryTransactionStatus: 166 

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Látszólag minden a helyén, de csak GeneralExceptionResponseType  válasz jön 200-as kóddal bármikor próbálom. 
Nem jön vissza semmi olyan információ ami informatív lenne, pedig  nagyon kellene ide valamilyen státusz információ válaszul.
Addig is, amíg lesz ilyen,  megköszönném, ha valaki meg tudná nézni a szerver oldalt, hogy hol akadt el.

*Egyéb tartalom / Additional content*

**Comment by Leslie7** [comment]
Megtaláltam a problémát. Nem a megfelelő technikai felhasználó adataival lett beküldve  a queryTransactionStatus. 
Ha server küldene a hibának megfelelő választ, sokkal könnyebb lenne megérteni a problémát.

**Comment by NTCA-supporter** [comment]
Szia!
Melyik requestId-s beküldés volt az aminél nem kaptál megfelelő választ és mikor történt? 
Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet. Ha van még kérdsé, nyisd újra kérlek.
