### ISSUE TITLE
ERROR OSA v3 Schemas implementation (Token Exchange)

### ISSUE THREAD

**Issue by sapshashikant** [nav-gov-hu/Online-Invoice#744]
Hello Team,

We have imported the "**new OSA v3**" Schemas in our system but we are not able to find the HEADER/USER node in schema for token exchange, Also we have verified the "**API example XML**" for token exchange and both the nodes available there. 

Is there any other way to export the correct schema to system. 

Best Regards, 
Shashikant P.

**Comment by NTCA-supporter** [comment]
Hi @sapshashikant !

You should also import the common schema.
https://github.com/nav-gov-hu/Common/blob/master/src/schemas/nav/gov/hu/NTCA/common.xsd

Header and user types can be found in the common xsd.

Br

**Comment by sapshashikant** [comment]
1-	The XSD mentioned in the tax authority site is incomplete (header and user mandatory nodes are missing in all the Request fields)

![image](https://user-images.githubusercontent.com/78403802/107326170-02a4dc80-6ad1-11eb-8f60-7d647ae8a1ce.png)

2-	In Response structure also the header and result mandatory nodes are missing, due to which it is giving error while mapping the structures

![image](https://user-images.githubusercontent.com/78403802/107326515-8eb70400-6ad1-11eb-9e5d-d427f1e41a4f.png)

By Manually editing the version 3.0 structure we are not able to get  the tag as expected in common tags, though we are using common XSD as reference in main payload.

Regards,
Shashikant P

**Comment by NTCA-supporter** [comment]
Hi @sapshashikant !
Could you solve the problem?
Is there any more question?
Br

**Comment by sapshashikant** [comment]
Issue has been resolved
