### ISSUE TITLE
QueryInvoiceDigest csoportos áfa alanyiság esetén

### ISSUE THREAD

**Issue by ballonyi** [nav-gov-hu/Online-Invoice#745]
Csoportos áfa alanyként lekérdeztem QueryInvoiceDigest operációval egy megadott időszak számláit. Ha nem adok meg groupMemberTaxNumber szűrőfeltételt, akkor nem csak a saját számlákat, hanem a csoport valamennyi tagjának a számláját hozza a digest.  Ha megadok szűrőfeltételt, akkor is csak azt tudja szűrni ahol az adatszolgáltatás tartalmaz ilyet.
Az a  problémám, hogy a manageInvoice beengedi a számlát 177-el kezdődő taxNumber megadásával és groupMemberTaxNumber megadása nélkül is. Ez nehézséget okoz az automatikus feldolgozásban, mert általában mindegyik groupmembernek önálló informatikai rendszere van, és nem szeretné a másik csoporttag számláit feldolgozni. Jó lenne, ha csoportos ÁFA alany esetén a manageInvoice megkövetelné a groupmember megadását is. A tesztrendszerben találkoztam ilyen 2021-es számlával (pl. 385L4K9U62O1L10H transactionId).

**Comment by NTCA-supporter** [comment]
Szia @ballonyi !

Erre figyelmeztető üzenetet adunk, de befogadjuk a számlát.
Az interfész dokumentációban ez szerepel:
A szállító (eladó) adatai között a számlán kötelező feltüntetni azt az adószámot, ami alatt a gazdasági
esemény történt (supplierTaxNumber elem, típusa: TaxNumberType). Ha az eladó csoportos áfaalany
tagja, akkor – az Áfa tv. előírásainak megfelelően – az eladó adóalany a csoport. A csoporttag
adószámát pedig a groupMemberTaxNumber elemben (típusa: TaxNumberType) kell feltüntetni, ha ez
szerepel a számlán. A szállító közösségi (uniós) adószáma pedig a communityVatNumber elemben
(típusa: CommunityVatNumberType) szerepeltethető, ha az szerepel a számlán. 

Ha van további kérdés, akkor @NTCA-tax tud precízebben válaszolni.
Üdv

**Comment by Macskafarka** [comment]
@ballonyi  "Jó lenne, ha csoportos ÁFA alany esetén a manageInvoice megkövetelné a groupmember megadását is. "
Szerintem ezt a NAV nem követelheti meg, mert az ÁFA tv. szerint csak a csoport adószámának kell kötelezően a számlán szerepelnie, a csoporttag saját adószáma csak lehetőség, de nem kötelező. Ha szerepel a számlán, akkor be is kell küldeni, de ha nem szerepel, akkor nem követelhető meg.

**Comment by Macskafarka** [comment]
"általában mindegyik groupmembernek önálló informatikai rendszere van, és nem szeretné a másik csoporttag számláit feldolgozni" Ezt szerintem az áfacsoportnak erősen át kell gondolnia, mert jogilag a szállító felé is egynek számít a csoport, vagyis bármelyik tagtól követelni lehet a számla kifizetését. Pl. ha az 'A' csoporttag tartozik nekem, a tartozását simán beszámíthatom a 'B' csoporttag felém való követelésébe. Továbbá a csoport egyetlen ÁFA bevallást készít, a Közösségi számláin a csoport közösségi adószáma jelenik meg. Ezekre a helyzetekre  külön informatikai rendszert működtetni......

**Comment by NTCA-tax** [comment]
A csoporttag adószámának számlán történő feltüntetési kötelezettsége nem áfa törvényből eredő előírás, hanem az Art. 30. § alapján kell ezt megtenni. Mivel számlaadat-szolgáltatás kizárólag az áfa törvényben megjelölt kötelező adattartalomra, valamint az áfa törvényben megjelölt adatokra terjed ki, ezért az adatszolgáltatásnál nem követelhetjük meg az áfa csoporttag adószámát.

**Comment by ballonyi** [comment]
_"Mivel számlaadat-szolgáltatás kizárólag az áfa törvényben megjelölt kötelező adattartalomra, valamint az áfa törvényben megjelölt adatokra terjed ki"_ 

Jól értem hogy bár az Art 30. § kötelezően előírja, de nem kötelező mert az Áfa tv-ben nem szerepel? Miért, az Art nem vonatozik az adatszolgáltatásokat teljesítőkre? Az ember azt gondolná, hogy ha létezik akár egyetlen hatályos jogszabály ami ezt megköveteli, akkor megkövetelhető. Vagy nem vehető ez fel az Áfa tv-be is?

Nagy segítség lenne, ha azon esetekben amikor XML alapú e-számla érkezik, akkor az automatikusan (kézi jóváhagyás nélkül) bekerülhetne a rendszerbe. A nem csoportos alanyoknál ez megvalósítható, de csoportos alanyoknál a fentiek miatt tehát nem. :(

**Comment by NTCA-tax** [comment]
A számlaadat-szolgáltatást az Áfa törvény írja elő az Áfa törvényben szereplő kötelező tartalmi elemekre. A számlával kapcsolatban számos más jogszabály ír elő további kötelező tartalmi elemet, de mivel az adatszolgáltatási kötelezettséget az Áfa törvény írja elő, így csak az abban szabályozott elemekre terjedhet ki. Amennyiben a NAV az Áfa törvényen kívüli adatelemekre is kiterjesztené az adatszolgáltatási kötelezettséget (pl. ebben az esetben egy Art-ban foglalt kötelezettségre), akkor túlterjeszkedne a jogszabály által adott kereteken. Tehát itt jogszabályi felhatalmazási probléma van a felvetéseddel kapcsolatban.

**Comment by jozanesz** [comment]
> Amennyiben a NAV az Áfa törvényen kívüli adatelemekre is kiterjesztené az adatszolgáltatási kötelezettséget (pl. ebben az esetben egy Art-ban foglalt kötelezettségre), akkor túlterjeszkedne a jogszabály által adott kereteken.

Láttam én már olyan kötelező elemeket pl., hogy _modifyWithoutMaster_, _lineNumberReference_, _customerVatStatus_, _UnitOfMeasureType_ stb., ahol van már némi túlterjeszkedés.

**Comment by Macskafarka** [comment]
@jozanesz Mert kiderült, hogy a törvényt lehetetlen betartani, muszáj kiegészíteni a réseket, mint a Jurassic Park 1. részében a béka génjeivel.  Fogjuk fel ezt is egyfajta Jurassic Parknak.

**Comment by ballonyi** [comment]
Még egy érdekesség: 

Beküldtem egy olyan adatszolgáltatást, amelyik csoportos adóalany számára készült, de taxnumber-ként a groupmember lett megadva. Csont nélkül DONE lett, nem volt mellette WARN! 
Viszont ez a számla befogadó oldalon nem kérdezhető le, sem a webes felületen (bejövő számlák), sem queryInvoiceDigest segítségével (insDate tól-ig próbáltam lekérdezni).
