### ISSUE TITLE
[Q&A] Nem létező szervezet, de van adószáma?

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#746]
A NAV-tól lekérdezve a **18000098-1-41** adószámot a Magyar Közjegyzői Kamara  név jön elő.
A bírósági nyilvántartásban  (birosag.hu/adatbázisok) nem szerepel sem ilyen adószám, sem ilyen nevű szervezet. pedig az számít a 
a 2011. évi CLXXXI. törvény 86.§ (1) bekezdése szerinti közhiteles nyilvántartásnak.
Tudtommal ha a magyar adószám 9. karaktere 1, az az adószámos magánszemélyeket jelent.
Ha egy adószámhoz nem létezik közhitelesen nyilvántartott szervezet jogi személy, az akkor természetes személynek számít?
Hogyan kell helyesen erről a vevőről adatot szolgáltatni a **customerVatStatus** mezőben: DOMESTIC, vagy OTHER, vagy PRIVATE_PERSON?

**Comment by NTCA-tax** [comment]
Konkrét adózóval kapcsolatban GitHub-on keresztül nem adhatok meg információt. A lekérdezés az adóhivatali törzsadatokat mutatja vissza egyébként.

Az adószám 9. karaktere az áfa kód. Amennyiben az áfa kód értéke "1", akkor az azt jelenti, hogy az adott adóalany adómentes tevékenységet végez, vagy alanyi mentességet választott.

**Comment by Macskafarka** [comment]
A kérdés konkrét adószám nélkül is megválaszolható: 
Ha egy adószámhoz nem létezik közhitelesen nyilvántartott szervezet jogi személy, az akkor természetes személynek számít?
Hogyan kell helyesen erről a vevőről adatot szolgáltatni a customerVatStatus mezőben: DOMESTIC, vagy OTHER, vagy PRIVATE_PERSON?
Jogilag nem létező jogi személyt hogyan kell kezelni? DOMESTIC, mert van adószáma? OTHER, mert nem létező? PRIVATE_PERSON, mert ha jogi személyként nem létezik, akkor csak magánszemély kehet?

**Comment by NTCA-tax** [comment]
@Macskafarka már nem nagyon tudom értelmezni, mit akarsz pontosan. Van egy adóhivatali rendszer lekérdezésed, melynél pontosan tudod, hogy egy szervezetet kapsz a lekérdezés eredményeként. Miért akarod magad átminősíteni azt magánszemélynek? Az adóhivatali nyilvántartásban lekérdezettek alapján egyértelmű, hogy az adott adószámhoz milyen szervezetet tartunk nyilván és az is, hogy adóalany. Mivel belföldi adóalany, ezért DOMESTIC-ként kell az adatszolgáltatásba szerepeltetni.

**Comment by Macskafarka** [comment]
Megértettem a választ, hogy a NAV adószám nyilvántartsa számít, és irreleváns az, hogy jogilag nem létezik a szervezet, ha "valahogy" kapott adószámot.

**Comment by Macskafarka** [comment]
A probléma abból fakad nálam, hogy mi a NAV nyilvántartásán kívül megkeressük a "valódi" nyilvántartást vezető szervezetet. Lehet, nem kellene....

**Comment by Macskafarka** [comment]
Ezt kitárgyaltuk lezárom.

**Comment by topybear** [comment]
A MOKK egy speciális "állatfajta", a közjegyzői önkormányzat része.
https://net.jogtar.hu/jogszabaly?docid=99100041.tv

Így látatlanban azt tippelném, hogy az önkormányzatokat, kormányzati szerveket sem találod meg ott.
