### ISSUE TITLE
[DEV support]

### ISSUE THREAD

**Issue by ballonyi** [nav-gov-hu/Online-Invoice#747]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[x] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
QIDT_000000030848 és QIDT_000000030849

```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**

Ugyanazt a számlát lekérdeztem többször egymásután. A válaszul kapott QueryInvoiceDataResponse a QIDT_000000030849 hívásban nem tartalmazza a ns2 névteret, a QIDT_000000030848 pedig igen:

```
<?xml version="1.0" standalone="yes"?>
<QueryInvoiceDataResponse xmlns="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns2="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">
  <ns2:header>
    <ns2:requestId>QIDT_000000030849</ns2:requestId>
    <ns2:timestamp>2021-02-02T15:18:36.676Z</ns2:timestamp>
    <ns2:requestVersion>3.0</ns2:requestVersion>
    <ns2:headerVersion>1.0</ns2:headerVersion>
  </ns2:header>
  <ns2:result>
    <ns2:funcCode>OK</ns2:funcCode>
```

illetve

```
<?xml version="1.0" standalone="yes"?>
<ns2:QueryInvoiceDataResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">
  <header>
    <requestId>QIDT_000000030848</requestId>
    <timestamp>2021-02-02T15:18:31.829Z</timestamp>
    <requestVersion>3.0</requestVersion>
    <headerVersion>1.0</headerVersion>
  </header>
  <result>
    <funcCode>OK</funcCode>
  </result>
```

Teljesen véletlenszerűnen egyik vagy másik fajta response-t kapom.

*Egyéb tartalom / Additional content*

**Comment by nagyzo** [comment]
A névtér definiálva van mindkét hívásnál, csak máshogy, de tkp. mindkét esetben valid:

`<QueryInvoiceDataResponse xmlns="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns2="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">
`
`<ns2:QueryInvoiceDataResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">`

Ez ilyen. Arra én is kíváncsi vagyok, hogy mi lehet a mögöttes szándék (tippem van).

**Comment by kabelnet2** [comment]
Az én tippem az, hogy nem szándék van mögötte, hanem több processzor, párhuzamosan működve és az egyik így generálja a másik meg úgy (nyilván valamilyen beállítás függvényében).
De nem érdemes ezzel sokat foglalkozni, kezelni kell tudni ezt is, azt is, mert mindegyik XML valid.

**Comment by ballonyi** [comment]
Így lesz a bugból fícsör.
