### ISSUE TITLE
[DEV support] INVALID_REQUEST időnként

### ISSUE THREAD

**Issue by mlnrdns** [nav-gov-hu/Online-Invoice#748]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[x] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[x] 2.0
[] 3.0

**A requestId értéke / requestId value**
```
tMFsZ1hOl0m_tXXh43iB0A28672_04
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Sziasztok,

időnként INVALID_REQUEST-et kapunk bizonyos kérésekre (GeneralExceptionResponse), míg ugyanazok a számlák egy következő körben bemennek (más transactioncsoportban). Egy transactionben több számla van ilyenkor mindig.

**Comment by NTCA-supporter** [comment]
Szia @mlnrdns !
Nem látok ilyen kérést a logokban. A méretkorlátra figyeltek? Esetleg még olyan esetben lehet ilyen válasz, ez magyarázná azt hogy a következő összeállításban, ahol már nincs méretrobléma, minden rendben.

Üdv

**Comment by NTCA-supporter** [comment]
Itt sikerült elhárítani a problémát? Van még kérdés?
Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet, ha van még probléma nyissátok újra kérlek.
Üdv
