### ISSUE TITLE
[DEV support]

### ISSUE THREAD

**Issue by vajayattila** [nav-gov-hu/Online-Invoice#749]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[x] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**RID707855305577**
```
A szerver felől érkező válasz:
OpenSSL SSL_read: Connection was reset, errno 10054
```

Segítséget kérek a hiba okának felderítésében. Előre is köszönöm.

**Comment by NTCA-supporter** [comment]
Szia!
15-17-ig tervezett karbantartás van.
Üdv

**Comment by vajayattila** [comment]
Köszönöm a választ. Ki van valahová írva, ahol tájékozódni lehet erről?

**Comment by NTCA-supporter** [comment]
https://onlineszamla-test.nav.gov.hu/home
Mivel jelenleg minden le van állítva, így a friss híreket nem tudja letölteni a weboldal, így lehet nem fogod már látni, de itt szoktuk jelezni a tervezett üzemszüneteket.
Üdv

**Comment by vajayattila** [comment]
Áhááá. Én meg mindig a https://onlineszamla.nav.gov.hu/home oldalt figyeltem, de akkor az az élesre vonatkozó infókat tartalmazza gondolom. Ma is okosabb lettem. 
Köszönöm az információt, zárhatod az hibajegyet.

**Comment by NTCA-supporter** [comment]
Így van, ott az élesre vonatkozó hírek vannak.
Üdv
