### ISSUE TITLE
NAV által hitelesített eszámla adattartalmi vizsgálata a befogadói oldalon

### ISSUE THREAD

**Issue by topybear** [nav-gov-hu/Online-Invoice#750]
Az egész azzal kezdődött, hogy kaptunk egy - az egyik népszerű, nagy rendszer által kiállított - végszámlát, eszámlaként, hitelesített pdf -ben. A kolléganő kíváncsiságból megnézte a NAV Online felületén is és ott feltűnt neki, hogy mint helyesbítő számla jelenik meg - mint kiderült, az előlegszámla helyesbítéseként adták fel a végszámlát. A pdf-ben egyébként minden kerek, fejlécben végszámla szerepel, semmi nem utal arra, hogy ez az előlegszámla helyesbítése lenne.
Jelen esetben tiszta a helyzet, hisz a pdf számít, az alapján ez végszámla, az adatszolgáltatás adattartalma pedig nem a mi problémánk.

De mi lesz a helyzet akkor, ha NAV által hitelesített eszámlát állít ki valaki? Ez esetben ugyanis az adatszolgáltatásban szereplő összes(!) adat a számla részévé válik. A jogászunk csuklóból rávágta, hogy mivel egy csomagban kapjuk, minden adat a hiteles számla részét képezi, így a befogadáskori ellenőrzéskor az összes adat helyességét ellenőrzini kellene. Ugye alapvetően egy csomó olyan NAV által kért technikai és adminisztratív információ van az állományban, amelyek helyességének ellenőrízése egy ügyintézőnek egyrészt nem kompetenciája, másrészt a szükséges ismeretei sincsenek meg hozzá. 

A fenti egy tökéletes példa arra, hogy 
  - ha a számla "klasszikusan" kötelező elemeit nézem akkor minden rendben van, kezemben van egy végszámla, 
  - ha viszont a kapott technikai információkat is nézem, akkor valójában van egy előlegszámla helyesbítőm, amire valaki azt írta rá, hogy végszámla és el kellene utasítanom.

Van erre esetleg valami jogi iránymutatás csak nem találtam meg, vagy sikerült véletlenül beletenyerelni egy problémás részbe, ami a későbbiekben további szabályozás, de legalábbis valamilyen hivatalos állásfoglalás után kiált?

**Comment by EPluribusUnum** [comment]
@topybear , pont emiatt a NAV ígért egy xslt-t, ami xml-ből pdf-et (számlakép) generál és így nem lesz ellentmondás a számlakép és xml között. Jelenleg pdf és xml között a feltöltőnek kell garantálni az egyezőséget és a feltöltő is felel érte.

**Comment by sinick2** [comment]
Ugyanez a probléma megvan akkor is, ha számlát állítunk ki, majd észrevesszük, hogy hibás a számla, a számlát érvénytelenítjük, majd új számlát állítunk ki. Ilyenkor az új számlát is azt eredeti számla módosításaként kell beküldeni. Itt is egy normál számlát kap a vevő, online számla oldalon viszont módosító számlát fog látni.

Lásd. 2020. december 3-i 3.0-ás specifikáció, 2.5.8 fejezet, példa-1., második lehetőség (154. oldal). 

"Második lehetőség: Az eredeti számláról az adózó érvénytelenítő számlát készít, majd immáron a valóságnak megfelelő adattartalommal új okiratot bocsát ki. Az érvénytelenítő számlaadat-szolgáltatás az „Adatszolgáltatás számla érvénytelenítéséről” fejezetben leírtak szerint készül. A helyes adattartalommal kibocsátott új számla szintén az eredeti számla módosításaként kerül kiadásra. Az erről nyújtott adatszolgáltatás – szintén módosításról történő adatszolgáltatásként – a helyes tételadatokat tartalmazza."

**Comment by NTCA-tax** [comment]
A PDF e-számlánál tiszta a dolog, hiszen adattartalmilag rendben van, az adatszolgáltatás viszont nem megfelelő.

Amennyiben a számlakibocsátó az e-számláját adatszolgáltatásként állítja ki, akkor nincs ilyen eltérés. Amennyiben hibás az adatszolgáltatás adattartalma, akkor logikusan hibás lesz a számla adattartalma is. Ennek a problémának a könnyebb láthatóvá tételéhez egyértelműen az XSLT jelenthet egy megoldást, vagy pedig a számlabefogadó rendszerében is lehet valamilyen megoldás rá.

Fontos azonban kiemelni, hogy nem a bizonylat megnevezése a döntő, hanem annak adattartalma. A bizonylat megnevezésének kötelezettségét egyébként az áfa törvény nem tartalmazza, adattartalmon keresztül szabályozza a számlázást.

**Comment by omachtandras** [comment]
@NTCA-tax : az XSLT hogy áll? Mikorra várható valami ezzel kapcsolatban?

Köszönöm

**Comment by NTCA-tax** [comment]
@omachtandras : kérdésed teljesen jogos, időpontot még nem tudok mondani.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet. Az XSLT-vel kapcsolatban van külön issue #648 . Ha van még kérdés nyissatok újat kérlek.
Üdv
