### ISSUE TITLE
QueryInvoiceDataResponse sok esetben csak OK válasz [DEV support]

### ISSUE THREAD

**Issue by bmatyi94** [nav-gov-hu/Online-Invoice#751]
Kedves NTCA developer

**Környezet / Environment**
[x] https://api.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**

[] /queryInvoiceData

**A kérés verziója / version of the request**

[] 2.0
[] 3.0

**A requestId értéke / requestId value**
```
pl: TSTKF68886875746
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**

Mi az oka annak hogy az QueryInvoiceDataResponse sok esetben csak OK -al jön vissza a result elemben, viszont   "invoiceDataResult" nélkül függetlenül a kérés verziójától?

*Egyéb tartalom / Additional content*

**Comment by NTCA-supporter** [comment]
Szia @bmatyi94 !

A tesztrendszeren nem látok ilyen requestet.
Ilyen választ akkor adunk, ha nem létezik ilyen számla az adott adózónál.

A kérésben ellenőrizd a whitespace-eket, csak tipp.

Üdv

**Comment by bmatyi94** [comment]
Kedves @NTCA-supporter 

Éles rendszerbe történt a request a NAV online invoice test tool-al. A digest lekérésben visszajön a számla.

Egyébként nem csak a NAV tool-ban tapasztaltuk, hanem a saját lekérésünkben is, hogy a digest visszaadja a számlaszámot és azt a számlát lekérjük a InvoiceData-ban akkor van hogy visszaadja az invoiceDataResult részt, de van hogy több esetben nem.

Üdv

**Comment by NTCA-supporter** [comment]
Szia @bmatyi94 !
Itt a githubon nem supportáljuk az éles rendszert.
Kérlek próbáld meg reprodukálni teszt rendszeren.
Ez csak akkor fordulhat elő, ha a digest és a data lekérdezésnél változik az invoiceNumber, pl. szóközt raksz elé, vagy vág le belőle, ezért mondtam, hogy ez a tippem.

Üdv

**Comment by NTCA-supporter** [comment]
Van még kérdés?
Üdv

**Comment by pitfla** [comment]
Ugyanezt tapasztaljuk mi is, havonta van 2-4 beérkező számla ügyfelenként, ahogy csak egy OK jön vissza, hiányzik a számlaadat.
Mivel beérkező számlákról van szó, tesztrendszerben nem demonstrálható.
Jó lenne erre megoldást találni, mert mi sem találunk semmilyen összefüggést az esetek között. A számlaszámokat, adószámokat biztosan jól küldjük át, többször ellenőriztük.
<result>
    <funcCode>OK</funcCode>
 </result>
A teljes <ns2:invoiceDataResult> blokk hiányzik a válaszüzenetből.

**Comment by tkelemen73** [comment]
Sziasztok,
valami bíztatót tudtok ezügyben? Most is jelentkezik a probléma, a válaszban OK jön vissza, de invoiceDataResult nincs benne.
RequestID, amivel meg tudjátok nézni a tesztben a kérést: ABIFNGVRW4POXIVSJF652QVYFM
Üdv
T.

**Comment by pitfla** [comment]
Hátha így most már foglalkoznak majd vele, hogy a tesztben is jelentkezett ez a probléma. Én még csak az élesben találkoztam vele, de elég gyakran, úgyhogy nagyon kellene már magyarázat rá.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Nagy csodák nincsenek.
Amit @tkelemen73 említ, az is egy olyan invoice_number, aminek a végén van két szóköz: '94008518  '
Azért nem adjuk vissza a számla tartalmát, mert '94008518' sorszámú számla nincs.
Egy másik issueban már jelezve lett, hogy blokkoló validáció lesz bvezetve az invoice_number elején/végén lévő whitespace karakterek tiltására, ami a 3.5 verzióban kerül ki a héten teszt és éles környezetre.
Üdv

**Comment by NTCA-supporter** [comment]
Kieégszítésként még annyit, hogy ugye akkor sem adunk vissza számla adatot, ha az adott számla menet közben technikai érvénytelenítve lett. Ez a két lehetőség van, vagy nem létezik az adott számla (pl. whitespace karakter miatt hiányos a lekérdezett sorszám), vagy technikai érvénytelenítve lett. Más nincs.

**Comment by tkelemen73** [comment]
Szia,
kicsit furcsának találom, a választ, ugyanis a /queryInvoiceDigest operáció által visszaadott számla sorszámokkal van visszakérdezve, tehát ha van benne, akkor az eredetiben is lett volna? De ha az eredetiben volt, akkor miért nem lehet lekérdezni? Ha az egyik szolgáltatásban lekérdezhető, akkor a másikban nem kellene letiltani, ez nem feature, ez bug... Szerintem... ;)
üdv
T.

**Comment by NTCA-supporter** [comment]
Szia @tkelemen73 !
Kérlek küld el a digest-es lekérdezés valamelyik azonosítóját a teszt környezetről.
Megnézzük annak válaszát, és kiderül hogy bug vagy feature.
Üdv

**Comment by tkelemen73** [comment]
Szia,
queryInvoiceDigest:
ABIFNGVRW4POXIX4KBJHYQOYFQ

5 db számlát adott vissza, amire visszakérdeztem egyesével queryInvoiceData:
ABIFNGVRW4POXIX4LNXPUYBYFQ
ABIFNGVRW4POXIX4LT6JFWHYFQ
ABIFNGVRW4POXIX4L6O5H4AYFQ
ABIFNGVRW4POXIX4MIYMYFFYFQ
ABIFNGVRW4POXIX4MSE7E5YYFQ

Köszönöm!
üdv
T.

**Comment by NTCA-supporter** [comment]
Köszi @tkelemen73 !
A digest responseban látszódik, hogy mind az öt számla sorszáma végén vannak szóközök:
`<ns2:invoiceNumber>94008471  </ns2:invoiceNumber>`
Emiatt nem kapod vissza a Data lekérdezést.
A digest válasz feldolgozásánál szerintem nem veszed figyelembe ezeket.
Szóval én a feature-re szavazok :)
Üdv

**Comment by pitfla** [comment]
Bocsánat, de én ezt azért nem tudom elfogadni, mert ez a "feautre" sok-sok felesleges lekérdezést generál. (Arról nem is beszélve, hogy egy valamirevaló adatbáziskezelő nem tárol jobbról szóközöket, pláne nem kulcs mezőben!)
Ügyfeleim könyvelés közben futnak bele ebbe a hibába. Beérkező számla rögzítésénél honnan tudná egy papír alapú számlánál (vagy akár elektronikusnál), hogy lejelentve hány szóközzel volt az adott számla?!? Én automatikusan amúgy is vágom jobbról, de ha engednék is szóközöket, kezdjen el kísérletezni a könyvelő, hogy 1-el lejön-e? 2-vel lejön-e? Ez szerintem abszurd.
Erőteljesen javaslom, hogy történjen egységesítés ezen a téren és végezze el a feldolgozó rendszer a jobbról történő vágást a számlaszám mezőben. Úgy gondolom, hogy ezzel mindenki egyetért.
Ha ez nem oldódik meg, akkor tovább fog lassulni a folyamat azzal, hogy én is rá fogok küldeni minden egyes esetben egy queryInvoiceDigest-et is a rendszerre.

**Comment by renced42** [comment]
Kedves @pitfla 

Egyébként megértve a problémádat, had világítsam meg más szemszögből:

Ennek semmi köze azadatbáziskezelőhöz. Ez üzleti döntés. Az adatbázis kezelő rendszer azt tárol le, amit beadnak neki és amire képes. Amit az adatszolgáltatásban beküldenek azt úgy tároljuk le, így ha szóközökkel küldi be akkor úgy.

De meg is fordíthatjuk a dolgokat és akkor azt mondanám, hogy egy valamire való számlázó szoftver pedig nem rak szóközöket,tabot, sortörést és más marhaságokat a számla sorszámba. Szerintem meg ez abszurd :)

A probléma megoldására, napokon belül be fogunk vezetni egy blokkoló validációt, ha whitespacek lesznek a számlasorszám elején meg végén (nem csak jobbról hanem balról is.)

**Comment by omachtandras** [comment]
@renced42, @pitfla  : valószínűleg ott van a kutya elásva, hogy az SQL standard szerint a szóközök automatikus elhagyásra kerülnek egy összehasonlításnál, ezért aki olyan adatbázis-kezelőt használ, ami a standard szerint működik fel sem tűnik neki, hogy hogy került tárolásra az adat, mert a query le fogja hozni egyezőként akkor is, ha szóköz nélkül keres, de mondjuk char-os mezőként a db-ben szóközökkel kiegészítve található meg az adat.
Akinek pedig olyan db-je van, ahol nem a standard szerinti működés van megvalósítva ott ez feltűnik, trim-el, vagy varchar-t használ char helyett, stb., stb.

**Comment by pitfla** [comment]
Mint ahogy írtam korábban, az én esetemben az ártatlanon csattan az ostor, mert nincs ráhatásom arra, hogy az én ügyfeleim részére kiállított számlák hogyan vannak lejelentve. A könyvelő beírja a papír számláról a számlaszámot, a programom meg hiába próbálja lekérdezni, nem kap választ, mert X db szóköz van a sorszám mögött (vagy akár előtt).
Úgyhogy én üdvözlöm @renced42 által vázolt megoldást, de biztos lesznek, akik meg most akadnak majd ki, hogy az adatszolgáltatásuk sikertelen lesz. Talán jobb lenne egy automatikus trimmelés.

**Comment by topybear** [comment]
Akkor megváltozik a számla adattartalma - ami eleve vitatható -, de ha azt az esetet nézed, ahol az adatszolgáltatás maga a számla, akkor már agyon is van ütve az egész.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet, mert ezzel kapcsolatban nem lesz változás. A blokkoló validáció régen be lett vezetve, azóta nem fordulhat elő ilyen probléma. Ha van még kérdés nyissatok újat kérlek.
Üdv
