### ISSUE TITLE
Online számla - megjelenítési probléma

### ISSUE THREAD

**Issue by topybear** [nav-gov-hu/Online-Invoice#752]
Online számla bejelentkezést követően, ha először egy régebbi, 2.0-as verzióban küldött forintos számlát tekintünk meg, és utána egy 3.0-val beküldött eurós számlát is megnéznénk, akkor ez utóbbit is forintosnak jeleníti meg:
![image](https://user-images.githubusercontent.com/3189331/107052047-7becb880-67cd-11eb-96de-a2a8cfe159ce.png)

A szűrő felületen egyébként még eurósnak mutatja.:

![image](https://user-images.githubusercontent.com/3189331/107052089-87d87a80-67cd-11eb-87f5-77e78a3cddc4.png)

Ha bejelentkezést követően azonnal ezt a számlát nézzük (és nem nézegetünk előtte 2.0-val beküldött forintos számlát), akkor jól mutatja:

![image](https://user-images.githubusercontent.com/3189331/107052347-d554e780-67cd-11eb-8eb9-a7fbdffdcc19.png)

**Comment by NTCA-supporter** [comment]
Szia @topybear !
Utánanézek és visszajelzek.
Üdv

**Comment by topybear** [comment]
Van róla videó is, de mivel skype megbeszélés során lett rögzítve, azt csak privátban oszthatom meg.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ez valóban bug, javítani fogjuk. Egyébként nem függ a verziótól, ha csak 3.0-s számlákkal játszod el ugyanezt akkor is ez tapasztalható.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
A javítás a 3.11-es verzióval kikerült tesztrendszerre.
Zárom az issuet, ha van még kérdés/probléma, kérlek nyissátok újra.
Üdv
