### ISSUE TITLE
[Q&A] Versenysemleges ellenőrzéseket kérünk

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#753]
Azonos ellenőrzési szigort kérünk a NAV számlázó programjánál, mint amit a számlázó programokat fejlesztőktől elvárnak.
**Kérem, hogy kapjanak ugyanolyan WARN-t azok, akik a NAV által ingyenesen biztosított Online Számla programot használják, mint amit mi kapunk**. Hadd derüljenek ki a NAV hatóság által elvártak turpisságai számukra is!
Fejezze be a NAV  a folyamatos piactorzító magatartását, és tartózkodjon a tisztességtelen eszközöktől!
Miért csak a Online Számla esetében tette ezt: "WARN-üzenet kikapcsolása 3.0-ás számlaadat-szolgáltatásoknál".
Már az is jogellenes, hogy a pénztárgéppel számlázóknál nem szerez érvényt az ÁFA tv. 10.sz. mellékletének 1. pontja szerinti adatszolgáltatási kötelezettségnek, és eltűri, sőt támogatja a jogellenes magatartást.
Már a legelső pillanatban szóltam, hogy tisztességtelen dolog az, ha valaki, vagy valami piaci szereplőként és
szabályozó hatóságként is jelen van.
Olyan ez, mintha az élelmiszer-felügyeleti hatóság kezdene el élelmiszert árulni. Ráadásul miközben másokat ellenőriz  azoknál szigorúbb szabályokat alkalmazna, mint saját magáénál.

**Comment by NTCA-supporter** [comment]
Szia @Macskafarka !

A kezdetektől ugyanaz a WARN készlet fut le 100%-ba az Online Számlázóból (gondolom erre gondoltál) kiállított számlákra is.

Miből gondolod, hogy ott más ellenőrzések futnak? Ez az idézett WARN üzenet kikapcsolása szöveget honnan másoltad?

Üdv

**Comment by Macskafarka** [comment]
Lehet, hogy én értek félre valamit? Én talán nem is igaz, hogy van változás, csak közzé van téve valami itt: 
[https://onlineszamla-test.nav.gov.hu/informatikai_valtozasok](url)
**Online Számla 3.3 verzió**
    **Exportfunkciók kiegészítése a 3.0-ás XSD-ben bevezetett új mezőkkel
    Új aszinkron-hibaüzenet bevezetése
    "Áthárított adót tartalmazó különbözet szerinti adózás jelölése" megnevezés módosítása
    Jogszabályok menüpont átnevezése
    WARN-üzenet kikapcsolása 3.0-ás számlaadat-szolgáltatásoknál
    Hibajavítás**

**Comment by topybear** [comment]
5. WARN-üzenet kikapcsolása 3.0-ás számlaadat-szolgáltatásoknál
Megtörtént a MISSING_HEAD_DATA_CUSTOMER WARN kikapcsolása a 3.0-ás számlaadat-szolgáltatásoknál.

Szerintem az Online Számla és az Online Számlázó elnevezések most megkavartak...

**Comment by NTCA-supporter** [comment]
Szia @Macskafarka !

Ahogy előttem is írták, összekeverted a kettőt.
Az Online Számla a központi rendszer, ahova az adatszolgáltatások beküldése történik, többek között az Online Számlázó alkalmazásból is.
Ahogy írtam, ez mindig is így volt, és így is lesz, hogy a Számlázóból kiállított számlákra ugyanaz az ERROR és WARN készlet fut le.
Az idézett WARN-nak már nem volt relevanicája a 3.0-ás sémára, ezért lett kivezetve (többszörös github kérésre), ami az API-s beküldésre is vonatkozik.

Kérlek a jövőben mellőzd az ilyen jellegű követelőző témaindítást és vádaskodást, és előbb tisztázzuk a témát, mielőtt a kérésekhez (és nem a követelésekhez) eljutunk. Nem az első ilyen volt részedről, ezt te is tudod. Ha van még kérdés, állunk rendelkezésre.

Üdv

**Comment by Macskafarka** [comment]
Ok. Csak megzavart, hogy az Online számlázó jobb felső sarkában ott van az 'ONLINE SZÁMLA' felirat.
Talán ez másoknak is okozhat ilyen tévedést.  Bocs a félreértésért.
