### ISSUE TITLE
ÉLES rendszerben autentikációs hiba!

### ISSUE THREAD

**Issue by EnokhSys** [nav-gov-hu/Online-Invoice#754]
Sziasztok!

Pénteken még minden rendben volt, de ma reggeltől két cégnél sem mennek be a számlák az ÉLES rendszerbe. Már a tokenrequest is elutasításra kerül autentikációs hibával. Sem a programon, sem a technikai felhasználón nem változtattak semmit. A NAV-nál viszont volt szombat hajnalban karbantartás, lehet, hogy ez okozza?

**Comment by NTCA-supporter** [comment]
Szia @EnokhSys !
Az éles rendszert itt nem supportáljuk, arra van hivatalos NAV helpdesk.
Teszt rendszeren nem tapasztalsz ilyet?

Ha az éles rendszeren nem menne valami globálisan, szombat óta, arról tudnánk szerintem, és biztosan jelezte volna más is.
Így első körben mégis a technikai felhasználó változására tippelnék, de sajnos pontos infot nem tudok.
Üdv

**Comment by EnokhSys** [comment]
Szia @NTCA-supporter,
ez a v2.0 élesben van, elfelejtettem mondani. Kipróbálhatom a v2.0-ás tesztrendszerében is. Két másik ügyfélnél a v3.0-ban nem tapasztalok ilyet.
Már létrehoztunk egy új technikai felhasználót is, azzal sem megy, pedig semmi nem változott péntek óta a beküldőprogramban.
Maradjunk "hotline", még visszajövök...

**Comment by EnokhSys** [comment]
Kedves @NTCA-supporter, köszi a segítséget, sikerült kideríteni a hiba okát, a cégnél egy korábbi elkefélésből létrejött egy rejtett technikai hiba. Zárom az issuet.
