### ISSUE TITLE
invoiceApi.xsd kérdés [Q&A]

### ISSUE THREAD

**Issue by szaby96** [nav-gov-hu/Online-Invoice#755]
Sziasztok!

Érdeklődni szeretnék, hogy az InvoiceApi.xsd tartalmazza a xs:schema-k között az xmlns:data="http://schemas.nav.gov.hu/OSA/3.0/data"-t, mégsincs importálva. Ennek van valami oka?
Okozhat-e hibát ennek importálása?

**Comment by NTCA-supporter** [comment]
Szia!

Szerintem azért nincs importálva, mert nincs belőle használva semmi, így fölösleges a xs:schema-ban is. Gondot nem okoz ha magadnál beimportálod szerintem.
Üdv

**Comment by NTCA-supporter** [comment]
Zárom, ha van még kérdés nyisd újra kérlek.
Üdv
