### ISSUE TITLE
Érvénytelenítő számla fordított áfakulcs hiányzó adószám

### ISSUE THREAD

**Issue by sinick2** [nav-gov-hu/Online-Invoice#757]
**Az igény összefoglalása / Summary of the request**
2021. januárban a vevőnek készült egy belföldi értékesítésről szóló számla fordított adózású áfakulccsal. A vevő adószáma a számlán nem volt megadva, ezért adatszolgáltatásba "Vevő adószáma hiányzik (belföldi fordított adózás) (1. sor)." figyelmeztetéssel fogadta be. 2021. februárban a számla érvénytelenítésre megtörtént, viszont az adatszolgáltatás elutasításra került "Vevő belföldi adószáma hiányzik (belföldi fordított adózás)." hibával, mivel február 3. óta fordított adózású tétel esetén nem lehet üres az adószám. (Ld. DOMESTIC_TAXNUMBER_EXPECTED_REVERSE_CHARGE hiba.)

**Az általam javasolt megoldás / The solution I propose**
Fordított adózású tételt tartalmazó alapszámla érvényteleníthető legyen az eredeti adattartalommal, azaz adószám nélkül.

**Comment by bakter80** [comment]
vagy általánosan: miért nem lehet bármit sztornózni?

**Comment by sinick2** [comment]
Tisztelt NTCA-tax! Mikor várható tájékoztatás a nyitó hozzászólásban leírt problémával és javaslattal kapcsolatban? Köszönöm.

**Comment by sinick2** [comment]
Tisztelt NTCA-tax! Szeretném újra megkérdezni, hogy mikor várható tájékoztatás a nyitó hozzászólásban leírt problémával és javaslattal kapcsolatban? Köszönöm.

**Comment by ch-e-mistry** [comment]
Tisztelt fejlesztők, @NTCA-tax,

Valószínűleg sokak által fájdalmas pont ez, köztük nekem is.

A mai nap kértem telefonos segítséget 1819-es telefonszámon, és érthető okokból több utánajárással jár a részükről, tekintettel arra, hogy a hiba maga technikai jellegű.

Kérem tudnának legalább ideiglenes megoldással szolgálni? Leírni a pontos menetét, hogy ilyen esetben (mivel a rendszer maga nem ajánl fel módosítást, csak adatbeküldést, ami sikertelen minden esetben) mi a teendője annak, aki belefutott ebbe a hibába?

Illetve tudnák javítani, hogy ne lehessen számlát kiállítani, hibás adatokkal?

Köszönöm, további szép napot.

**Comment by renced42** [comment]
> Illetve tudnák javítani, hogy ne lehessen számlát kiállítani, hibás adatokkal?

Kedves @ch-e-mistry, @sinick2 A számlát nem a NAV állítja ki, A NAV maximum befogadja az adatszolgáltatást. 
A problémára megnézzük mi a megoldás, ha meg van jelezzük.

**Comment by dupplak** [comment]
Ugyanez a probléma merült fel nálunk is. A számlakiállító február elején félrekattintott és a belföldi fordított adózás kulcsot választotta Magánszemély vevőnél. Most szeretné stornózni, azonban mi már blokkoljuk ezeket a számlákat a NAV módosítása óta (WARNING -> ERROR), hogy ne az adatszolgáltatásnál történjen hiba.

Legegyszerűbb és leggyorsabb megoldás lenne, ha a stornózást engedélyeznék, még ha hibás is a tartalom, ez az eredeti számla tartalmát úgyis "kiüti".

Kérjük jelezzenek vissza amint lehetséges!

Köszönöm, további szép napot!

**Comment by NTCA-supporter** [comment]
Sziasztok!

Kis türelmet kérünk még. A szakmai egyeztetés már folyamatban, engedékenyebb lesz ez a blokkoló validáció, de pontosítani kell minden esetet, amikor befogadjuk a modify/storno számlát ilyen esetekben, és ezeket jóvá kell hagyatni.
Jelzek, ha megvan a végső döntés, és azt is megírom, hogy melyik verzióba fog kerülni a módosítás.

Üdv

**Comment by dupplak** [comment]
Üdv,
lehetne, hogy erre végre választ kapjunk? Ez hátráltatja a mindennapi munkát és nekünk kell mindig egy magyarázatot kitalálni, hogy miért nem működik még. Várunk egy visszajelzést és megoldást 1 héten belül! Köszönjük.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Teszt rendszeren már ott a javítás, élesen a csütörtöki telepítéssel kerül ki. STORNO operation-re ki lett kapcsolva.
MODIFY esetén, ha az eredeti CREATE számlát 3.0 előtti (1.x vagy 2.x) verzióban küldték be, akkor nem fut az ellenőrzés.

Zárom az issuet, ha van még kérdés nyissátok újra kérlek.

Üdv
