### ISSUE TITLE
[Q&A]

### ISSUE THREAD

**Issue by Datatexlab** [nav-gov-hu/Online-Invoice#758]
**A kérdés, amire választ szeretnék kapni /Merged item indicator rule**
Rövid és tömör leírása a kérdésnek. / Question is, whenever an xml file is larger than 10 mb than <mergedItemIndicator>true</mergedItemIndicator> 
if less
<mergedItemIndicator>false</mergedItemIndicator>
Thank you

**Comment by NTCA-supporter** [comment]
Hi @Datatexlab !
I don't really know what is the question.
Please add some more detail.
