### ISSUE TITLE
Invoice appearance rule

### ISSUE THREAD

**Issue by Datatexlab** [nav-gov-hu/Online-Invoice#759]
**A kérdés, amire választ szeretnék kapni / Invoice appearance rule**
Rövid és tömör leírása a kérdésnek. / How can i determine whether the value in InvoiceAppearance string should be Electronic or EDI or Paper. We provide xml/xsd file based on the latest update to the intermediary service provider that will submit it to NAV. However, we also see in examples PAPER. Is this determined by which invoice type actually will go to client? thanks

**Comment by WittmannWien** [comment]
Is this determined by which invoice type actually will go to client?
Yes, this is the correct determenation.

**Comment by NTCA-tax** [comment]
At the time of closing the invoice, if the software knows the issue format of the invoice (e.g. paper, electronic, EDI), then this value can be indicate in the XML file. If this data is not available at the time of closing the invoice, the software could use the unknown value.

**Comment by NTCA-supporter** [comment]
I close the issue due to inactivity.
Feel free to reopen it.
