### ISSUE TITLE
[DOC] annulmentVerificationStatus dokumentáció hiánya

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#76]
**A hibás dokumentum neve / Document name containing the error**
https://onlineszamla-test.nav.gov.hu/api/files/container/download/Online%20Szamla_Interfesz%20specifik%C3%A1ci%C3%B3_HU_v2.0.pdf

**Oldalszám / Page number**
48.oldal

**A dokumentációs hiba leírása / Description of the documentation error**
A  annulmentVerificationStatus mező response értékei nincsenek dokumentálva, pl. mikor vesz fel NOT_VERIFIABLE értéket?

VERIFICATION_PENDING
VERIFICATION_DONE
VERIFICATION_REJECTED

**Comment by nbeeps2** [comment]
A VERIFICATION_DONE azt jelenti, hogy megtörtént a technikai érvénytelenítés felhasználó által történt elfogadása az online felületen vagy csak azt jelenti, hogy maga az ANNUL operáció lett DONE?

**Comment by NTCA-developer** [comment]
Szia!

Abból indultunk ki, hogy ezek az értékek ugyan azok mint a jóváhagyó felületen, és a technikai érvénytelenítés szabályaiból ezeket ki lehet következtetni, de igazad van, mert a doksiban valóban nem szerepel ez a leírás, holott oda tartozna. A következő transzportba beletesszük ezt is. Addig is:

- NOT_VERIFYABLE státuszt akkor vesz fel, ha az annulment kérés aszinkron feldolgozása során bármely index ERROR értéket kapott (ekkor bukott az egész technikai érvénytelenítés a többi indexre is, kvázi nem történt semmi)
- VERIFICATION_PENDING státuszt akkor vesz fel, ha az annulment kérés aszinkron feldolgozása minden indexen DONE eredményt adott, ekkortól lehet a technikai érvénytelenítést a felületen jóváhagyni
- VERIFICATION_DONE státuszt akkor vesz fel, ha már sikeresen jóváhagyták a kérést a felületen (neked ez a trigger, hogy küldheted újra a technikailag érvénytelenített számlákat)
- VERIFICATION_REJECTED státuszt akkor vesz fel, ha elsődleges felhasználó nem jóváhagyta, hanem elutasította a technikai érvénytelenítést (kvázi ismét nem történt semmi, minden visszaállt az eredeti állapotba)

**Comment by nbeeps2** [comment]
Köszönöm, 2 kérdés még ezzel kapcsolatban:
1. NOT_VERIFIABLE vagy NOT_VERIFYABLE a pontos visszatérési érték? (előbbi van a doksiban, Te pedig most az Y-nos változatát írtad a szónak)
2. A QUERYTRANSACTIONSTATUS meghívásakor, ha technikai érvénytelenítésről van szó akkor a response-ban megjelenik a annulmentVerificationStatus, ez eddig ok. A kérdés, hogy ilyenkor ezzel párhuzamban van <invoiceStatus> is a response-ban?

Pl.  <invoiceStatus>ABORTED</invoiceStatus><annulmentVerificationStatus>NOT_VERIFYABLE</annulmentVerificationStatus>

**Comment by nbeeps2** [comment]
bocsánat, átírta a github a kérdésem, szóval:
A QUERYTRANSACTIONSTATUS meghívásakor, ha technikai érvénytelenítésről van szó akkor a response-ban megjelenik a annulmentVerificationStatus, ez eddig ok. A kérdés, hogy ilyenkor ezzel párhuzamban van invoiceStatus is a response-ban?

pl egy responsban:
invoicestatus: aborted
annulmentVerificationStatus: not_verifyable

**Comment by NTCA-developer** [comment]
Szia!

> NOT_VERIFIABLE vagy NOT_VERIFYABLE a pontos visszatérési érték? (előbbi van a doksiban, Te pedig most az Y-nos változatát írtad a szónak)

Ezt a szót annyiszor rontom el, ahányszor megpróbálom helyesen leírni. :) Egyszerűen nem áll rá a kezem, de ne foglalkozz velem, az XSD az irányadó mindig, most is. Ahogy ott van, úgy a jó.

> A kérdés, hogy ilyenkor ezzel párhuzamban van invoiceStatus is a response-ban?

Igen van, ez is egy feldolgozandó tranzakció, mint a számlabeküldés.

**Comment by NTCA-developer** [comment]
Szia!

Kikerült a teszt és éles környezetre a frissített interfész dokumentáció, ami tartalmazza amit a ticket hiányol.
