### ISSUE TITLE
[DOC]Hibás a passwordHash cryptoType értéke

### ISSUE THREAD

**Issue by Csomb** [nav-gov-hu/Online-Invoice#760]
Sziasztok!

A "/sample/API sample" összes példájában ez szerepel:

common:passwordHash cryptoType="SHA2-512"

Valószínűleg a 2020.12.10-i változtatás nem lett végig vezetve, mert a doksiban az van, hogy:

"A passwordHash tag a típusából adódóan kiegészül egy új, kötelező attribútummal: cryptoType néven. Egyetlen elfogadott értéke: SHA-512"

Kerestem fél órát, hogy mit rontottam :-)

Szép napot!

**Comment by NTCA-supporter** [comment]
Köszi a jelzést, igyekszünk javítani hamarosan.

**Comment by NTCA-supporter** [comment]
Ezt közben javítottam, köszi mégegyszer a jelzést.
Üdv
