### ISSUE TITLE
[Q&A] Nálam van a hiba? , vagy bug?

### ISSUE THREAD

**Issue by PlutoMars007** [nav-gov-hu/Online-Invoice#762]
Sziasztok!
AAM-es egyszerűsített számlát rögzítettem webes felületen, warningot kapok, de nem találom a hibát.

"- Az egyszerűsített számla egy vagy több adótartalomhoz tartozó tételsoraiban szereplő bruttó értékek összege eltér az összesítésében a hozzá tartozó adótartalomnál szereplő bruttó összegtől. 
–  Tag: InvoiceData/invoiceMain/invoice/invoiceSummary/summarySimplified/vatContentGrossAmount
–  Érték: 148000"

Egy számlatétel szerepel a számlán és az összeg mindenhol stimmel, tranzakció azonosító: 39CSOE7YSNSJZYZG
Most, hogy nem rég bekerült az elküldés előtti  "tartalmi ellenőrzés"  lehetőség kipróbáltam normál számlával, ott nem mutat hibát, csak az egyszerűsített számlánál.

**Comment by NTCA-supporter** [comment]
Szia @PlutoMars007 !

Lásd #550 :)  Ha nincs több kérdés, kérlek zárd ezt, és majd abban megy a tájékoztatás.,
Üdv

**Comment by PlutoMars007** [comment]
Rendben köszi :)
