### ISSUE TITLE
[Q&A] Külföldi önszámláről kell adatszolgáltatás

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#763]
Ha a külföldi vevő (nincs magyar adószáma) ragaszkodik ahhoz, hogy önszámlával számlázza ki a felé teljesített eladásainkat, akkor  annak hogyan kell bekerülnie a számlaadat-szolgáltatásba?  Melyik a helyes gondolatmenet:
1. Sehogy, mert nem a magyar áfa tv. alapján készül a számla
2. A külföldi partner számlázó programjának kell adatot szolgáltatnia, mivel a bennünket a magyar áfa tv. alapján terhelő számlakiállításra hatalmaztuk fel. A mulasztásért egyetemlegesen felelünk mi is és a számla kiállító is.
3. Nekünk kell kézzel berögzíteni a NAV felületén és bennünket terhel a 4 napos határidő. A mulasztás jogkövetkezménye csak ránk vonatkozik, (Akkor is, ha nem kaptuk meg a számlát?).
4. Ki sem állíthat helyettünk ilyen önszámlát, mert az ÁFA tv-ben csak belföldi adószámmal rendelkező partnerrel köthető önszámla megállapodás.

**Comment by NTCA-tax** [comment]
Önszámlázásban bárkivel meg lehet egyezni, nincs erre jogszabályi kötöttség. Az adott ügyletnek megfelelő adattartalommal kell a számlát kiállítani és itt a magyar jogszabályokat kell figyelembe venni. Az adatszolgáltatást meg kell oldani ebben az esetben is. Ez technikai kérdés, hogyan lehet megtenni. Például a következő megoldások lehetségesek:

- A külföldi partner fejleszt egy adatszolgáltatási funkciót a programjához
- A külföldi partner a számlaadatokat megküldi a magyar társaság adatszolgáltatási rendszerébe
- Szolgáltatót vesznek igénybe az adatszolgáltatás teljesítéséhez

A fentieken kívül előfordulhat más technikai megoldás is persze, de a gyakorlatban ezekkel a megoldásokkal találkoztam. Persze szóba jöhet az is, hogy a magyar társaság rögzíti a számlaadatokat, de ez jogszabályilag nem túl helyes megoldás, de legalább a számlaadat beérkezik. Találkoztam olyan elképzeléssel is, hogy a magyar társaság kiállít az önszámlákról a saját rendszerében számlát, amelyre megtörténik az adatszolgáltatás, de ez sem jó, hiszen az adott ügyletnél nem ez a számla... Persze ez utóbbit el lehet vinni olyan irányba is, hogy az önszámlázási megállapodást felbontják, de a magyar társaság a külföldi partner által megadott adatok alapján állítja ki a számlát, bár ez nem feltétlenül mindig működőképes, hiszen jellemzően más a célja az önszámlázásnak.

**Comment by Macskafarka** [comment]
Nagyon köszönöm a választ, sokat segített. lezárom az issue-t
