### ISSUE TITLE
[DEV support] ns2 - namespace kérdés

### ISSUE THREAD

**Issue by kharonx** [nav-gov-hu/Online-Invoice#764]
Üdvözlöm,

egy ideje fut már a nav3.0 -s adatszolgáltatás teszt és arra lettem figyelmes, hogy a státusz ellenőrzésnél nem mindig ugyanazt a response -t kapom.Néha van ns2 namespace néha nincs.
Van erre valami magyarázat, én csinálok valamit rosszul?

Példa:
 vagy ezt kapom: processingResults vagy ezt ns2:processingResults

Ugyanazon számla más - más időben lekérdezve.

Előre is köszönöm!

> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[] 3.0

**A requestId értéke / requestId value**
```

```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**

*Egyéb tartalom / Additional content*

**Comment by DrotosTot** [comment]
Szia!
#453 -ban már ki lett vesézve, a lényeg, hogy a NAV nem garantálja a névterek állandó, kiszámítható sorrendjét.

**Comment by kharonx** [comment]
Köszönöm, akkor feldolgozás előtt egy replace megold mindent. :)
