### ISSUE TITLE
Feldolgozás sikertelen - mégsem lehet újraküldeni a számlát [Q&A]

### ISSUE THREAD

**Issue by littlecutieorion** [nav-gov-hu/Online-Invoice#765]
Február 9-én délután 4-5 óra között a NAV éles szerveren problémák voltak és az automatikusan küldött majdnem tízezer számlák között volt olyan, ami a következővel érkezett vissza:

"ERROR
SERVICE
Feldolgozás sikertelen!(OPERATION_FAILED)"

Ezeket a számlákat megpróbáltam újraküldeni és legnagyobb meglepetésemre a következő hibaüzi jött:

"ERROR
TransactionId: xyz......
BUSINESS ERROR
Számla validációs hiba.
A megadott számla sorszámmal már történt adatszolgáltatás.;BUSINESS;ERROR;INVOICE_NUMBER_NOT_UNIQUE"

A NAV online számla felületére belépve megvannak ezek a számlák, de a státusza mindnek: megszakítva. 
Technikailag nem tudjuk érvényteleníteni, nincs rá lehetőség, újraküldeni nem tudjuk. 
Ebben az esetben mi a teendő? 
Üdv.

**Comment by littlecutieorion** [comment]
Szia! 
Be se ment a számla elsőre. ID-t sem adott vissza akkor, csak error-t!
Az adatszolgáltatásoknál látni egyébként. 
Köszi, hogy próbálsz segíteni :)

**Comment by SimplifiedSzamla** [comment]
Még olyanok voltak anno, amikor a frissítések utáni nagyobb megakadások idején, hogy a NAV nem adott vissza tranzakciós id-t, de akkor ki tudtuk nézni a beküldött számlát a kimenő számlák közt, onnan meg lehetett nézni az adatszolgáltatást, abból ki lehetett szedni a tranzakciós id-t és az alapján tudtam lekérni a státuszt.
Azért írom le így, mert az előfordul, hogy a NAV szégyenlős, és nem ad vissza tranzakciós id-t, de attól függetlenül megcsinálja amit meg kell.

Bár ott van még a lehetőség, hogy kézzel felviszi az illetékes a számlákat a NAV felületén.
De majd esetleg valami NAV-os fejlesztő is hozzászól ehhez, az Ő meglátásaik jobbak lehetnek.

**Comment by nagyzo** [comment]
Online Szamla_interfesz specifikáció_HU_v3.0. A "1.6.6 Válaszidő, timeout" fejezet alapján a 3.0-ban ez nem bug, hanem feature.
Erre sajnos készülni kell.

**Comment by littlecutieorion** [comment]
Érdekes, a Feldolgozási státusz mindegyiknél "Feldolgozva" vagy "lekérdezve". Viszont a számla státusz: "megszakítva".
Lehet, hogy ezzel nem is kéne foglalkozni? Az lehet, amit írtatok, hogy nem adta vissza akkor a tranzakciós id-t?

**Comment by SimplifiedSzamla** [comment]
Az adatszolgáltatásoknál akkor teljesült a számla beküldési kötelezettség, ha a státusz le van kérdezve. Úgyhogy ami ott feldolgozva állapotban van, az le kell kérdezned.

Ha a NAV-tól vissza nem kapott tranzakciós azonosítót keresed:
- Bemész a kimenő számlákhoz
- Átállítód a szűrést, hogy számlaszámra szűrjön, rászűrsz a keresett számlaszámra
- Ha ott megjelenik a számla, akkor megnézed a számla részleteit, megjelennek a számla adatai
- Letekersz a számla aljára, ott van, hogy adatszolgáltatás megtekintése, arra rányomsz
- Ez átdob egy másik oldalra, ahol láthatod az adatszolgáltatás adatait
- Ezen az oldalon van egy olyan, hogy "Tranzakciós azonosító" - ezt kimásolod
- Rámész a számlák->adatszolgátatások menüpontra, és rászűrsz erre a tranzakciós azonosítóra 
- ha megjelenik a beküldés, akkor megnézed, hogy milyen a státusza: 
- Feldolgozva: kérdezd le
- Lekérdezve: nincs vele dolgod szerintem
- Megszakítva: lövésem sincs sajnos

Más ötletem nincs, ha ez nem segít, akkor bocsi.

**Comment by littlecutieorion** [comment]
Kedves @SimplifiedSzamla!
Nagyon rendes, hogy ennyi időt töltesz a problémámmal.
Az ID-k megvannak, lepecáztuk.
Megpróbáltam a status-t lekérdezni, és bármelyiket kértem (akár "Lekérdezve", akár "Feldolgozva"), ugyanazt adja:

"ERROR
TransactionId: jfdkfjdljfldjfld
BUSINESS ERROR
Számla validációs hiba.
A megadott számla sorszámmal már történt adatszolgáltatás.;BUSINESS;ERROR;INVOICE_NUMBER_NOT_UNIQUE"

Úgy gondolom, a válasz "féllábas" maradt odafenn az üzemzavar idején, de ettől rendben van az adatszolgáltatás. Még egyszer köszi a segítségedet. 
Üdv.
