### ISSUE TITLE
[DEV support] TokenExchange egy végpontról több azonosító adattal

### ISSUE THREAD

**Issue by hosszuful** [nav-gov-hu/Online-Invoice#766]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[x] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
Ezek a kérések kel nem jók:
"A" intézményi adatokkal:
ReqId: 1015288, vagy 1000321
Üzenet: HTTP 401 Unauthorized ( INVALID_SECURITY_USER Helytelen authentikációs adatok!)
"B" intézményi adatokkal:
ReqId: 1015306, vagy 1000320 
Üzenet: HTTP 401 Unauthorized ( INVALID_SECURITY_USER Helytelen authentikációs adatok!)
Saját céges adatainkkal:
ReqId: 1015309, vagy 1000319
Üzenet: HTTP 200 OK Sikeres tokenkérés
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
A rendszerünk több NAV-os felhasználó által kiállított számla beküldésért felel. Saját céges adatainkkal beállított tokenkérés hiba nélkül lefut és response-ba visszajön a token. A probléma az, hogy ez csak a saját adatainkkal működik. Korábban a 2.0-ás verziónál ez működött és nem tapasztaltuk, hogy bármi hiba lenne. Az érintett felhasználókkal (nevezzük őket "A"-nak és "B"-nek) történtek egyeztetések, hogy nem változtatatták-e meg a kapcsolati adataikat (felhasználó/jelszó/cserekulcs/aláíró-kulcs), de mindkét esetben megfelelőnek találták ezeket az adatokat. Ezen 4 adaton kívül tudtommal csak az adószám és a https tanúsítvány játszik. 
Így elakadtam egy kicsit, mert már nem tudok mit mondani az ügyfeleknek. Lehet, hogy nálam van a hiba, de akkor miért működik a saját adatainkkal? A hash és signature képzéseket ezen oknál fogva jónak gondolom,  ezért a kérésem az volna, hogy tudtok-e mondani valami pontosabbat a fenti "A" és "B" kérésekről?

Előre is köszönöm.

update: Ellenőriztük a jelenleg futó 2.0-ás verzióval, ami ugyanezeket az adatok használja, ott nem ad hibát a token kérés. A pwdHash előállításában doksi szerint nem történt változás, csak átkerült cryptoType tagbe. Ennek a jó kérésnek a requestId-ja 50006481, ennek a 3.0-ás hibás párja a 1000321 requestId. Ez a kettő ugyanazokkal az intézményi adatokkal rendelkezik.

update2: az éles api-ra küldve a tokenkérések rendben lemennek. Előfordulhat, hogy külön kell hozzáférést kérni a teszt és éles apihoz?
*Egyéb tartalom / Additional content*

**Comment by NTCA-supporter** [comment]
Szia @hosszuful !

Igen, teszt és éles rendszerhez külön technikia felhasználók tartoznak, a két rendszer független egymástól.

Üdv

**Comment by hosszuful** [comment]
Köszi

**Comment by BartBM** [comment]
@NTCA-supporter How do you get credentials for a technical user that works against api-test? 
(we have a technical user working against the production url but need one for test).

**Comment by NTCA-supporter** [comment]
Hi @BartBM !
Primary users (those who have representation right to the taxpayer) can create new technical users. They can do it here in the Users menu:
https://onlineszamla-test.nav.gov.hu/home

Br
