### ISSUE TITLE
Számla végén, ÁFA kulcsonként részletezés - melyik törvény alapján?

### ISSUE THREAD

**Issue by EnokhSys** [nav-gov-hu/Online-Invoice#767]
Kedves @NTCA-tax,

tudnátok segíteni nekem légyszi abban, hogy a számla végén, az ÁFA kulcsonkénti részletezést melyik paragrafus írja elő kötelező jelleggel?

Nem a NAV OnLine Számla miatt kérdezem, hanem az EDI-n történő elektronikus számlák miatt kell tisztáznunk a kérdést az egyik EDI szolgáltatóval, és csak annyiban érinti a NAV OnLine Számlát, hogy az a számla amit beküldünk a NAV-nak, és az a számla, amit EDI-n küldünk a vevőnek, adattartalmilag is meg kell egyezzen egymással. 

Nagyon köszönöm!

**Comment by jozanesz** [comment]
(Csak zárójelben írom - NTCA-ék a tapasztalatok alapján nem ismerik -, a 2013. évi CLXXXVIII. törvény az egységes közszolgáltatói számlaképről a következő alapossággal specifikálja e követelményt: „**ÁFA összesítő (Ft)**”.)

**Comment by EnokhSys** [comment]
> (Csak zárójelben írom - NTCA-ék a tapasztalatok alapján nem ismerik -, a 2013. évi CLXXXVIII. törvény az egységes közszolgáltatói számlaképről a következő alapossággal specifikálja e követelményt: „**ÁFA összesítő (Ft)**”.)

Köszi az infót. Ezt értem, de ez nem válasz a kérdésemre, arról nem is beszélve, hogy ez a közszolgáltatói számlákra vonatkozik. Azt a törvényt keresem, amely előírja a számla végén az ÁFA összesítő szerepeltetésének módját és kötelezőségét,

**Comment by Macskafarka** [comment]
@EnokhSys **A számlára általánosan nincs előírva az áfa kulcsonkénti részletezés.** Csupán ágazati jogszabály tartalmaz ilyent pl. a közüzemi számlákra vonatkozóan. Ha lenne ilyen, az csak törvényben lehetne, rendeletben nem. A számla általánosan kötelező tartalmát az ÁFA tv. 169.§ szabályozza. Néhány kisebb dolgot más törvények, Pl a "Kisadózó" fogalmat a Katv. tv., a magyar adószámot az Art. tv. Az egyéni vállalkozói nyilvántartási számot az Evectv.  Az áfa kulcsonkénti összesítést jórészt megszokásból írják rá a számlákra.

**Comment by Macskafarka** [comment]
Sok olyan dolog szokott lenni a számlákon, ami megszokáson, régi gyakorlaton, szájhagyományon, távhiten stb. alapul. Ilyen pl. a fizetendő összeg betűvel való kiírása, az aláíró neve, a 10 éve eltörölt példányszámozás, a valaha volt "másolat" kifejezés stb.
Egy másik issue-ban említett fizetési mód is ilyen. De ilyen a bankszámlaszám is, azt sem írja elő semmi.

**Comment by EnokhSys** [comment]
@Macskafarka köszi szépen! Nagyszerűek a válaszaid, van hat macskám, hálából meghúzogatom a farkukat! :-))

Igen, ezekről a megszokásokról már volt szó korábban, ha jól emlékszem a kerekítések kapcsán. Érdekes az, hogy vannak értelemszerű dolgok (mint pl ÁFA részletezés, kerekítés), amelyekre nincs semmi előírás, mégis szinte mindenki pontosan és jól alkalmazza.

**Comment by EnokhSys** [comment]
Mivel választ kaptam a kérdésemre, zárom az issue-t,
