### ISSUE TITLE
[Q&A] közösségi adómentes termékértékesítés

### ISSUE THREAD

**Issue by Roose88** [nav-gov-hu/Online-Invoice#768]
Sziasztok!

Dokumentáció 86. oldal:
Vevő a Közösség másik tagállamában nyilvántartásba vett adóalany és közösségi adómentes termékértékesítés az ügylet
communityVatNumber töltése kötelező.

Melyik adókulcsok tartoznak ebbe a körbe?
KBAET (Adómentes Közösségen belüli termékértékesítés, új közlekedési eszköz nélkül) és KBAUK (Adómentes Közösségen belüli új közlekedési eszköz értékesítés) ?

**Comment by NTCA-tax** [comment]
Attól függ miről szól az ügylet. Amennyiben új közlekedési eszköz, akkor mint ahogy a leírás is tartalmazza KBAUK, amennyiben nem új közlekedési eszköz, akkor KBAET.

**Comment by NTCA-tax** [comment]
Ezzel kapcsolatban van maradt még valami kérdés?

**Comment by Roose88** [comment]
Itt igazából nem az áfakulcs használatának szabálya érdekelt, hanem, hogy melyik adókulcsoknál kötelező megadni a közösségi adószámot. És egy felsorolást vártam.
Mindezt azért, mert én úgy láttam, hogy az interface erre nem validál, de felhasználói oldalra be akarom építeni.

**Comment by NTCA-tax** [comment]
A kérdésedet akkor félreértettem... Egyedül a KBAET esetén kell mindig a vevő oldalán a közösségi adószámot feltüntetni, a KBAUK esetén van olyan eset, amikor a vevőnek nincs adószáma.

**Comment by Roose88** [comment]
Nagyon szépen köszönöm. Így zárható.
