### ISSUE TITLE
Üres közösségi adószám esetén ÁFA-s számla

### ISSUE THREAD

**Issue by lazaralexandra** [nav-gov-hu/Online-Invoice#769]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Ha BP-nek nincs közösségi adószáma és a számla ÁFA-s, akkor tudjuk a communityVAT number üresként küldeni? Mert hibát kapunk. A dokumentációban ezt látom
Vevő a
Közösség másik
tagállamában
nyilvántartásba
vett adóalany,
és az ügyletet
belföldi 27, 18
vagy 5%-os áfa
terheli.
customerVatStatus = OTHER
customerInfo/customerVatData/communityVatNumber töltése nem kötelező,
de lehetséges megadni.

Mi ezt adtuk meg:
"customerInfo": {
	"customerVatStatus": "OTHER",
        "communityVatNumber": "",
Aborted lett a tesztszámla, hibaüzenet:
2	ERROR	15022021	13:42	SCHEMA_VIOLATION	XML contains on line: [27] and column: [34] error: [cvc-type.3.1.3: The value '' of element 'communityVatNumber' is not valid.]	
1	ERROR	15022021	13:42	SCHEMA_VIOLATION	XML contains on line: [27] and column: [34] error: [cvc-pattern-valid: Value '' is not facet-valid with respect to pattern '[A-Z]{2}[0-9A-Z]{2,13}' for type 'CommunityVatNumberType'.]	
1	ERROR	08022021	15:35	SERVER ERROR	Error validating JSON. Error: - Missing required field \"customerTaxNumber\"  - Invalid type Object, expected Array for invoiceLines(400)	
Mit az eljárás ilyenkor?

**Comment by NTCA-supporter** [comment]
Szia @lazaralexandra !
Ha megadod a taget az xml-ben, akkor annak pattern validnak kell lennie, ahogy a schema_violation-ös szöveg is írja.
Üdv

**Comment by lazaralexandra** [comment]
Köszi, tehát üres nem lehet. Ebben az esetben, ha alapvetően üres az adószám, akkor payloadban egyik VATnumber taget sem kell alapvetően küldeni, vagyis ilyen esetben sem a közösségi, sem pedig a harmadik országbeli ÁFAkódhoz tartozó taget nem kell küldeni?

**Comment by NTCA-supporter** [comment]
Pontosan.
