### ISSUE TITLE
[Q&A] negatív számlaösszeg

### ISSUE THREAD

**Issue by zsfoto** [nav-gov-hu/Online-Invoice#770]
Szeretném megkérdezni, hogy a **39AVRGI4IY3R76JX** tranzakció id-jű beküldésünk végösszege negatív lett egy véletlen miatt.
Most vettem észre. (sok ezer számla megy fel egymenetben)
Ez jól van így?

Köszönöm

**Comment by DrotosTot** [comment]
WARN-t fogsz rá kapni, ha CREATE a számla: "Eredeti (CREATE) számla nettó összege nem lehet negatív."
Csak módosító vagy törlő esetén lehet negatív a végösszeg.

**Comment by zsfoto** [comment]
Nem kaptam rá WARN-t! Zöld pipával van nyugtázva.

**Comment by NTCA-supporter** [comment]
Szia @zsfoto !
Itt van még kérdés?
Üdv

**Comment by zsfoto** [comment]
Köszönöm nincs.
(Covidos voltam, soká tartott a körülménye. Hamarosan leszek)
