### ISSUE TITLE
[Q&A] list of available implementations

### ISSUE THREAD

**Issue by andrew-azarov** [nav-gov-hu/Online-Invoice#771]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
It would be great to have a list of current implementations. For now I found only php, scala and js implementations but they are listed sporadically. As a dev of a python implementation it would be great to have a list so other devs could benefit from the code and contribute if they can.
Maybe there are paid implementations which will also would like to be listed.

P.S.: Github now supports discussions which you can utilize for Q&A and Feature requests.

**Comment by NTCA-supporter** [comment]
I close the issue due to inactivity.
Feel free to reopen it.
