### ISSUE TITLE
[Q&A] marginSchemeVat, marginSchemeNoVat ill. a marginSchemeIndicator

### ISSUE THREAD

**Issue by Roose88** [nav-gov-hu/Online-Invoice#772]
Sziasztok!

3.0 Kérdés a marginSchemeVat, marginSchemeNoVat ill. a marginSchemeIndicator mezők helyes használatáról. #494-ban láttam a besorolást:
TRAVEL_AGENCY -> marginSchemeVat
SECOND_HAND > marginSchemeNoVat
ARTWORK -> marginSchemeNoVat
ANTIQUES -> marginSchemeNoVat

Egy 2.0-val szolgáltatatott számlán szereplő marginSchemeVat és marginSchemeNoVat helyesbítő vagy sztornó számláján 3.0 adatolszolgáltatásban minek kell szerepelnie a marginSchemeIndicator mezőben?
Megpróbáltam az 'UNKNOWN'-t, de nem fogadta el.

**Comment by NTCA-supporter** [comment]
Szia @Roose88 !
A case/reason szerkezetű adómértékeknél megengedett az UNKNOWN case.
A MarginSchemeType-nak fix értékkészlete van, így csak a TRAVEL_AGENCY, SECOND_HAND, ARTWORK, ANTIQUES értékek elfogadottak.
Üdv

**Comment by Roose88** [comment]
De mi alapján válasszak 2.0 -s adatszolgáltatás helyesbítésekor a 3.0 esetre értéket a MarginSchemeType-hoz?

**Comment by Csomb** [comment]
Van egy ilyen a doksiban (hátha segít)

"Ha a programod nem tudja meghatározni előzmény nélküli vagy 3.0 előtti számlákra hivatkozott módosító/sztornó számláknál a case értékeket, akkor használd az UNKNOWN-t."

**Comment by Roose88** [comment]
A MarginSchemeType esetében nincs case érték, az UNKNOWN nem elfogadott. Ezért tettem fel a kérdést.

**Comment by NTCA-supporter** [comment]
@NTCA-tax tudsz segíteni a megfeleltetésben?
Köszi

**Comment by NTCA-tax** [comment]
A 2.0-ban van egy marginSchemeIndicator, melynek az értékei TRAVEL_AGENCY, SECOND_HAND, ARTWORK, ANTIQUES. Ezt elvileg ki kellett tölteni a 2.0-ás számlaadat szolgáltatásnál, amennyiben különbözet szerinti volt az ügylet. Lényegében ezt a mezőt emeltük át 3.0-ban a maginschemeVat és marginschemeNoVat mezők helyére, ezzel a duplikációt is megszüntettük.

**Comment by NTCA-tax** [comment]
Ezzel kapcsolatban maradt még valami kérdés?

**Comment by Roose88** [comment]
Köszönöm, nincs több kérdés. Zárható.
