### ISSUE TITLE
[Q&A] Hibaüzenetek listája 3.0

### ISSUE THREAD

**Issue by vectorgogolaktibor** [nav-gov-hu/Online-Invoice#775]
Tisztelt Cím

A [linken ](https://github.com/nav-gov-hu/Online-Invoice/issues/170) lévő Issue-ba kaptunk választ miszerint elkészült egy hiba üzenet fordítás.
Ez ahogy láttom, még 1 évvel ezelőtti fordításokat tartalmaz.
Lesz vagy van már jelenleg is valahol ilyen fordítás a a 3-as verzióra.
Előre is köszönöm válaszukat!

**Comment by kabelnet2** [comment]
Lásd: Régiek a hibaüzenet-file-ok #663
Jan. 3.-án azt írták, hamarosan frissíteni fogják. Hogy mi a hamaros, azt nem írták.

**Comment by NTCA-supporter** [comment]
Frissítettem, köszi a türelmet.
Üdv
