### ISSUE TITLE
[Q&A] Több számla érvénytelenítése egy okirattal

### ISSUE THREAD

**Issue by lazaralexandra** [nav-gov-hu/Online-Invoice#778]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Nem látok arra példát, ha több számlát szeretnék egy okirattal érvényteleníteni. Csak módosításra látok példát, ahol 0-k az értékek.
Van erre valami példátok, hogy kéne ennek kinézni? Gondolom itt is a batchinvoice csomópontot kellene használni. Ennél a több számla módosításos példánál invoicelines-k sincsenek.
Köszönöm.

**Comment by NTCA-supporter** [comment]
Szia @lazaralexandra !
A különsbég, hogy az invoiceOperation = STORNO és hogy vannak tételek.
A batchInvoice-on belül ugyanolyan invoice csomópontok vannak, amik már ismertek, azok adatszerkezete ugyanolyan.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet, mivel nincs nyitott kérdés. Ha tudunk még segíteni, nyissatok újat kérlek.
Üdv
