### ISSUE TITLE
[Q&A] Bejövő számla adatainak lekérdezése

### ISSUE THREAD

**Issue by aabel-1** [nav-gov-hu/Online-Invoice#779]
Szeretnénk a bejövő számlák adatainak lekérdezését tesztelni. Ehhez szükség volna arra, hogy a teszt rendszeren legyen bejövő számlánk. Lehetséges két account tesztrendszerének összekapcsolása, hogy az egyik tudjon számlát küldeni a másiknak mint az éles rendszeren? Esetleg milyen más lehetőség van ennek a tesztnek az elvégzésére?

**Comment by makailaci** [comment]
Szia, számlaletöltést tesztelheted az éles rendszerből is, csak lekérdezel, más nem történik. Nagy adatmennyiség lekérdezéséhez úgyis az kell, nem elég 1-2 számla a teszből. Csak úgy kapsz rendes információkat, ha látod, hogyan küldik be mások a számlákat. (Látsz majd csodákat.) üdv, laci

**Comment by aabel-1** [comment]
Kedves Laci!

Köszönöm a választ.

/Attila/
