### ISSUE TITLE
[FEATURE] INVOICE_NUMBER_NOT_UNIQUE probléma üzemszünetek után

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#78]
**Az igény összefoglalása / Summary of the request**
Nagyon bosszantó hibája a jelenlegi 1.1-es rendszernek, hogy amikor üzemszünet/lassulás van (pl. legutóbb 2019.10.28-án), akkor a következő eset nagyon sűrűn előfordul:
- a program be akarja küldeni a számlát, de már nem kap választ (így tranzakció azonosítót sem) a NAV-tól, mert ekkor történik a lassulás a NAV-nál 
- később a program a queryInvoiceData-val megpróbálja lekérni a számlát a rendszerből, hogy megnézze, hogy bent van-e és kinyerje a tranzakció azonosítót, de erre olyan válasz érkezik, hogy nincs bent még a számla
- a program ilyenkor megismétli a számla feladását a NAV-hoz viszont ez ABORTED-re fut INVOICE_NUMBER_NOT_UNIQUE üzenettel, mert valójában bekerült a számla (az online felületen is látszik!)

**Az általam javasolt megoldás / The solution I propose**
Kérem a hiba javítását, mert ha a queryInvoiceData azt adja vissza, hogy nincs bent a számla, akkor nem fordulhat elő, hogy a számla beküldés azért nem sikerült, mert már van ilyen sorszámú számla.

**Elfogadható alternatívák / Acceptable alternatives**
Jó lenne ezt most már az 1.1-ben javítani, de legkésőbb a 2.0-ban, hogy ez ne fordulhasson elő.

**Egyéb tartalom / Additional content**
A prog.hu fórumon más fejlesztők is jelezték, hogy ők is ezt tapasztalják.

**Comment by NTCA-developer** [comment]
Szia @nbeeps2! 

Köszi az igény összefoglalását. A működés szempontjából nem értek veled egyet hogy ez a rendszer hibája volna, inkább úgy fogalmaznék hogy egy együttállása több dolognak, amit persze értek hogy miért probléma a túloldalon. Rögtön elmagyarázom miért mondom ezt, egyáltalán nem azért mert púderezni akarom a dolgot.

Ugye a számla befogadása szinkron, míg a feldolgozása aszinkron módon történik meg. A szinkron hívásban - operációtól függően - nagyjából 8-10 üzleti validáció van, ezeket taglalja az interfész dokumentáció 3.2-es fejezete. Ezen ellenőrzések teljesüléséig a hívó várakozik, nyitott TCP session-ben.
Az általad jelzett probléma akkor jelentkezik, ha az ellenőrzéseket kiszolgáló komponensek közül valamelyik(ek)nek a válaszideje indokolatlanul megnő. Sokan kérdezitek prog.hu-n is, hogyan lehetséges az, hogy HTTP 503 / 504 válasz esetén a számla mégis bekerül a rendszerbe. A válasz nagyon egyszerű: úgy, hogy a HTTP 503 / 504-et nem az alkalmazás válaszolja, hanem az előtte lévő egyik hálózati eszköz. Ha megnézitek, akkor a 

`<html>HTTP 503 Bad Gateway</html>`

válasz teljesen invalid a REST API sémaleírójára, még csak nem is XML. Az alkalmazás sosem így válaszol. llyenkor valójában az történik, hogy a TCP session-t az eszköz elterminálja mint halott session, de az általa indított szál a memóriában még teljesen életképes és aktív. Csak sajnos később fejeződik be, mint amit a hálózati eszköz timeout értéke megenged. Nyilván lehetne a timeout értékeket bizonyos mértékben nyújtani, de ez nem megoldja, hanem csak elodázza a problémát. (incidens esetén pedig ténylegesen rontana is a helyzeten) 

A másik probléma az együttállásban, ha az aszinkron rész is döcög. Ekkor hiába jött be sikeresen az adatszolgáltatásról szóló kérés (ideértve azt az esetet is, ha erről a kliens nem kapta vissza a tranzakció azonosítót) a feldolgozás még nem jutott túl azokon a lépéseken ami alapján megállapítható lenne, hogy a request alatt lévő base64 tartalom vajon egy befogadható számlát tartalmaz-e. Később persze feldolgozásra kerülne, de ha ez előtt te számlaszámmal akarod lekérdezni, hogy adott számla bent van-e már a rendszerben, akkor az alkalmazás ezen a pontos felelősen nem mondhatja azt hogy igen, beküldted. A számlaszám alapú lekérdezés nem alkalmas az incidensek alatti ellenőrzésre, csak az incidens utániakra.

Amit tenni lehetne, hogy időalapú szűréssel lekérdezhetővé tesszük a beküldő adott időszakra eső tranzakcióinak listáját. Ha a beküldő olyan transactionId-t talál a listában ami számára ismeretlen, akkor ennek ismeretében a returnOriginalRequest opcióval lekérhető a teljes kérés tartalma a /queryTransactionStatus operációban. A belső base64 tartalmat ugyan kliens oldalon kell majd felparsolni, de ezt követően az egyes indexek alatti számlaszámok már megismerhetőek és a tranzakció azonosító - számlaszám párosítás utólag is elvégezhető, így elkerülhető a duplikáció. Azt tudjuk garantálni, hogy ez bármilyen üzemzavar esetén helyes eredményt ad vissza, feltéve hogy válaszol. A tranzakció listázó operáció viszont biztosan csak 2.0 lehet.

Mit gondolsz?

**Comment by nbeeps2** [comment]
Az általad javasolt megoldásnak mennyire kavar be ennek egy olyan elméleti eset, amikor egy offline számlázó program több telephelyen van telepítve és a felhasználó nem állít be számlatömb előtagot és ugyanazzal a számlaszámmal kerül kiállításra két számla A és B telephelyen?

**Comment by NTCA-developer** [comment]
Szerintem semennyire, ha jól értem a kérdésedet.

Ha ugyan az a cég akarja ugyan azt a számlaszámot 2x beküldeni, akkor versenyhelyzet alapján az első számla be fog menni, az összes későbbi pedig bukni fog. Még annak sincs jelentősége, hogy a példádban szereplő két számla 1 tranzakcióban kerül-e be a rendszerbe, mert az egyes indexek mindenképpen külön szálon fognak feldolgozódni.

Amikor látsz egy számodra ismeretlen transactionId-t, akkor a javasolt megoldás szerint mindenképpen bele kell nézz a base64 tartalomba hogy meg tudd állapítani mely számla vagy számlák voltak benne. A két számla akár külön, akár egy tranzakcióban jött be, így is, úgy is valahogy meg kell állapítani, hogy melyik számla van az ismeretlen tranzakcióban. Az a tény, hogy ebben a konkrét esetben a számlaszám önmagában nem egyedi és a számla más adatai alapján kell tudnod különbséget tenni (feltehetően nem azonos a vevő, a végösszeg, a tételek stb) szerintem irreleváns.

**Comment by nbeeps2** [comment]
Igen, igazából most is nagyon hasonlót végzek, mert a QUERYINVOICEDATA-val lekérem a számla adatát, majd ha van benne tranzakció azonosító, akkor dekodolom a base64 invoice tagot és lecsekkolom pár alapadat alapján, hogy biztosan az-e a számla, amiről a program szerint is szó van.
Csak ez jelenleg a már általad leírtak szerint nem megy, mert a QUERYINVOICEDATA nem adja vissza a számlát ilyen esetben és ezért küldi fel a program ismételten. Erre egyik megoldás jelenleg, hogy amikor a számla INVOICE_NUMBER_NOT_UNIQUE üzenetre (ABORTED) fut, akkor ezt követően történik csak meg a QUERYINVOICEDATA lekérdezés és adategyeztetések és ha a szerint minden stimmel, akkor a program elrejti az ABORTED üzenetet a felhasználó elől és kvázi DONE-re állítja a számlát. Ez a megoldás viszont szerintem azért veszélyes, mert így nem veszem észre az adatszolgáltatásokhoz kapcsolódó WARN üzeneteket és nem tudom a felhasználónak jelezni, ilyen szempontból jobb lenne egy megelőzés erre (" időalapú szűréssel lekérdezhetővé tesszük a beküldő adott időszakra eső tranzakcióinak listáját").

**Comment by NTCA-developer** [comment]
Szerintem nem problémás akkor, ha a /queryTransactionStatus műveletet addig folytatod, amíg meg nincs a feldolgozás eredmény. Scenárió alapján ez a sorrend:

1) Beküldesz x darab számlát adott tranzakcióban. Lassulás van, nem kapod vissza a transactionId-t.
2) Mivel azt tudod, hogy adott időablakban milyen tranzakciókat küldtél be, azokban mely számlák voltak és hányra nem kaptál vissza tranzactionId-t a szervertől, listázod a tranzakcióidat az új operációban.
3) Ha olyan transactionId-ket is kapsz vissza a válaszban, amit te nem ismersz, akkor egyesével lekérdezed ezeket a transactionId-ket a /queryTransactionStatus operációval, ügyelve, hogy a returnOriginalRequest tag értéke true legyen.
4) Ha még mindig tart a lassulás, akkor a /queryTransactionStatus azt fogja mondani a tranzakció alatti indexekre, hogy a feldolgozási státuszuk még IN_PROGRESS vagy esetleg RECEIVED, mert még el se kezdtük. De ez éppen most nem baj, mert a returnOriginalRequest = true miatt vissza fogod kapni az egyes indexek alatti számlaadatokat is base64-ben. Ezt te csak arra használod most, hogy belenézés után bejegyezd annak a tényét magadhoz, hogy melyik számlaszám melyik transactionId alatt ment be a rendszerbe. Ezzel csak helyreállítjuk a normális állapotot, mintha már a válaszban megkaptad volna a transactionId-t.
5) Ha bejegyezted magadhoz az ismeretlen transactionId-ket, akkor már nincs más dolgod vele, mint kérdezgetni addig a feldolgozási eredményt, amíg minden tétel nem DONE vagy ABORTED alatta, ahogy ezt teszed az összes többi tranzakcióval is. Ez viszont már vissza fogja adni neked az összes ERROR és WARN üzenetet is, tehát nem fogsz kevesebbet tudni így. 
+1) Esetlegesen, ha már a 4-es lépésnél olyan szerencséd volt, hogy a tranzakció fel is volt dolgozva, akkor az 5)-ös lépésre nincs is szükség, egy lépésben meglesz a transactionId - számlaszám párosítás és a hozzájuk tartozó feldolgozási eredmény is.

**Comment by nbeeps2** [comment]
Rendben, elfogadom ezt a megoldást. Várom az új operációt, akkor a 2.0-ban! Köszönöm.

**Comment by szako** [comment]
Lehet valamit tudni erről? Köszönöm!

**Comment by NTCA-developer** [comment]
Szia @szako 

Én nagyon támogatom, szerintem menni fog. Csak még nem tudtunk leülni megbeszélni. Írok majd ha lesz hírem.

**Comment by NTCA-developer** [comment]
Sziasztok!

Befogadjuk az igényt. A 2.0-ás API-ban létrehozunk egy tranzakció listázó operációt. A listázást timestampes intervallum megadásával lehet majd kérni, maximum 35 napos időtartamra. A válasz lapozható lista lesz az adószámhoz tartozó beküldéses transactionId értékekkel és még pár üzleti adattal.
