### ISSUE TITLE
Figyelmeztetés jön az Online Számla felületen az adatszolgáltatásnál.

### ISSUE THREAD

**Issue by celeburdi** [nav-gov-hu/Online-Invoice#780]
A következő a figyelmeztetés:
 - Az egyszerűsített számla egy vagy több adótartalomhoz tartozó tételsoraiban szereplő bruttó értékek összege eltér az összesítésében a hozzá tartozó adótartalomnál szereplő bruttó összegtől.

    –  Tag: InvoiceData/invoiceMain/invoice/invoiceSummary/summarySimplified/vatContentGrossAmount
    –  Érték: 30000
A számla egyetlen tárgyi adómentes tételsorból áll.
A tételsor bruttó értéke és az összesítések nem térnek el.
Miért jön ez a figyelmeztetés?

**Comment by NTCA-supporter** [comment]
Szia!

Már jelezték korábban, az #550 issueban lesz jelezve, ha elkészült a javítás.
Ezt zárom.
Üdv
