### ISSUE TITLE
Technical error file in NTCA

### ISSUE THREAD

**Issue by vkozakevich** [nav-gov-hu/Online-Invoice#782]
Hello.
We sent an invoice to the NTCA, but it is wrong(technical). Can we delete the wrong invoice from the system and refill it?

**Comment by NTCA-supporter** [comment]
Hi!

You can use the technical annulment function in this case.

Br

**Comment by WittmannWien** [comment]
Yes, you can, you need to log on into the site https://onlineszamla-test.nav.gov.hu/home (you can log in with your technical user ID and password) then go to Invoice - Outbound invoices - search for the invoice and open it, then select function Technical annulment - fill out Annulment code + Reason and save it. After got to Declaration - data disclosure annulment (you will see your annulment request there pending.) Open it and select Accept annulment. After that you can reload the same invoice.

**Comment by vkozakevich** [comment]
I uploaded file in NTCA and see aborted status  Invoice - Data Exchanges
![image](https://user-images.githubusercontent.com/77329708/109165154-4a438d80-778c-11eb-802e-ea400f1c9c4c.png)
File has technical error. After I founnd error and correct them. And I would like to reload correct file in NTCA. If i upload file , I get error :
 - The specified invoice number has already been used previously.

    –  Tag: InvoiceData/invoiceNumber
For the file to be successfully uploaded to the system, I need to change its number, but the number remains the same.
Can I delete invoice from  Invoice - Data Exchanges?
Technical annulment i can use in Invoice - Outbound invoices, but this page does not display the wrong invoice.

**Comment by WittmannWien** [comment]
If you go the Invoice - Outbund Invoice change the search pattern to invoicenumber.
![2021-02-25 15_20_46-Outgoing invoices _ Online invoice](https://user-images.githubusercontent.com/50328266/109166723-4ceab680-777d-11eb-8618-747054cf279e.png)

Than you will be able to search for the invoicenumber.
After you find it you can use the technical annulment.

**Comment by vkozakevich** [comment]
Thank You
