### ISSUE TITLE
[DEV support] v2.0 manageInvoice status 200, but invoiceData XML not validate on NAV System

### ISSUE THREAD

**Issue by Apatullii** [nav-gov-hu/Online-Invoice#783]
When we send a manageInvoice request, we get the 200 status, but the InvoiceData xml file does not pass validation in the NAV system.

**Technical faults**
- XML contains on line: [66] and column: [27] error: [cvc-complex-type.2.4.b: The content of element 'lineVatRate' is not complete. One of '{"http://schemas.nav.gov.hu/OSA/2.0/data":vatPercentage, "http://schemas.nav.gov.hu/OSA/2.0/data":vatExemption, "http://schemas.nav.gov.hu/OSA/2.0/data":vatOutOfScope, "http://schemas.nav.gov.hu/OSA/2.0/data":vatDomesticReverseCharge, "http://schemas.nav.gov.hu/OSA/2.0/data":marginSchemeVat, "http://schemas.nav.gov.hu/OSA/2.0/data":marginSchemeNoVat}' is expected.]
- XML contains on line: [82] and column: [23] error: [cvc-complex-type.2.4.b: The content of element 'vatRate' is not complete. One of '{"http://schemas.nav.gov.hu/OSA/2.0/data":vatPercentage, "http://schemas.nav.gov.hu/OSA/2.0/data":vatExemption, "http://schemas.nav.gov.hu/OSA/2.0/data":vatOutOfScope, "http://schemas.nav.gov.hu/OSA/2.0/data":vatDomesticReverseCharge, "http://schemas.nav.gov.hu/OSA/2.0/data":marginSchemeVat, "http://schemas.nav.gov.hu/OSA/2.0/data":marginSchemeNoVat}' is expected.]
- Xml validation failed 

Is it possible to get an error of invoice status in the response, without going to the website https://onlineszamla.nav.gov.hu/?

![изображение](https://user-images.githubusercontent.com/79591950/109116900-4b57c900-7752-11eb-84cb-9110c9524708.png)

**Comment by WittmannWien** [comment]
Hi, yes, you can, you have to use the Api - QueryTransactionStatus, to get this information.

**Comment by Apatullii** [comment]
How I can do it? I can't find this information in the documentation.

**Comment by WittmannWien** [comment]
Please check the Online_Szamla_Interfasz_specifikacio_EN_v3.0 documentation. 
If you do not have it you can download here.
https://onlineszamla.nav.gov.hu/dokumentaciok

Documentation- Section 1.8.8.1 QueryTransactionStatusRequest. 
From Page 62

**Comment by Apatullii** [comment]
I found this information. Thank you
