### ISSUE TITLE
NAV 3.0 XML (xmlns_base....) tartalom

### ISSUE THREAD

**Issue by KKARACSONY** [nav-gov-hu/Online-Invoice#785]
Sziasztok, 

Felmerült a kérdés, hogy problémát okoz-e, hogyha az XML tartalmazza ezeket az "xmlns:base=:http://schemas.nav.gov.hu/OSA/3.0/base" részeket mint pl. itt: 
![image](https://user-images.githubusercontent.com/60341815/109166141-a7374780-777c-11eb-8226-a8cea230616f.png)

A példa xml-ekben nincsenek ezek benne, de hagyhatjuk ezt így? Szintaktikailag helyesek a számlák, és befogadja őket probléma nélkül a NAV. 

Köszönjük!

**Comment by NTCA-supporter** [comment]
Szia @KKARACSONY !
Problémát nem okoz, így hagyható.
Üdv
