### ISSUE TITLE
[DEV support] Csoportos adószámmal rendelkezik a vevő.....

### ISSUE THREAD

**Issue by lakatoskevin** [nav-gov-hu/Online-Invoice#786]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[x] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
3A7ZQDMGS0ZIZ9A2
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Sziasztok! ISMÉT nem működik részünkről az az eset amikor csoportos adószáma van a kliensnek. Egyszer ez már működött, de most megint nem fogadja el a rendszeretek. A válaszban legyetek kedvesek megadni azt, hogy hogyan is kellene kinéznie a csoportos adószám megadásának, mert a példaszámlákat néztem, és azokat követve kódoltam le mindent, de nem megy a dolog.........

*Egyéb tartalom / Additional content*

**Comment by sinick2** [comment]
Nekem működik! 

3.0-ban így kell, ha a számlán mindkét adószám szerepel:

<customerVatData>
	<customerTaxNumber>
		<ns2:taxpayerId>12345678</ns2:taxpayerId>
		<ns2:vatCode>5</ns2:vatCode>
		<ns2:countyCode>44</ns2:countyCode>
		<groupMemberTaxNumber>
			<ns2:taxpayerId>87654321</ns2:taxpayerId>
			<ns2:vatCode>4</ns2:vatCode>
			<ns2:countyCode>42</ns2:countyCode>
		</groupMemberTaxNumber>
	</customerTaxNumber>
</customerVatData>

ha nincs csoporttag adószám megadva, akkor így:

<customerVatData>
	<customerTaxNumber>
		<ns2:taxpayerId>12345678</ns2:taxpayerId>
		<ns2:vatCode>5</ns2:vatCode>
		<ns2:countyCode>44</ns2:countyCode>
	</customerTaxNumber>
</customerVatData>

**Comment by lakatoskevin** [comment]
Szia sinick2!

Sajnos ERROR 400-at dob vissza de azért köszi, hogy te legalább megpróbálsz segíteni... :D

**Comment by NTCA-supporter** [comment]
Szia @lakatoskevin !
Küldj kérlek egy transactionId-t vagy requestId-t ami alapján meg tudom nézni a konkrét kérésedet.
Egyébként a fent említett megoldás jó.
Üdv

**Comment by lakatoskevin** [comment]
Szia! Köszi szépen a gyors választ!

<common:requestId>DZGGK42RFD2021226141618</common:requestId>

<exchangeToken>8f94a6ba-15e6-4bd6-89e4-5d025d6089373A81QVJNDNKM</exchangeToken>

**Comment by lakatoskevin** [comment]
Bocsi, azóta találtam egy tranzakció ID-t is, lemaradt: 3A81QVRXR7TWPG7U

**Comment by NTCA-supporter** [comment]
Megvan, köszi.
Ha belföldi a vevő, akkor a taxpayerId mező kötelező, csak azzal együtt adhatod meg a csoporttag adószámát, ahogy fentebb is írták.
![image](https://user-images.githubusercontent.com/58814216/109307069-5c7f0380-7840-11eb-87e4-8d87a1a19df5.png)

**Comment by lakatoskevin** [comment]
Igen, a speckóban ezt én is megtaláltam, viszont nekünk csak és kizárólag a 8 jegyű csoportazonosító áll a rendelkezésünkre.

Kvázi így néz ki a dolog:

<customerVatData>
<customerTaxNumber>
<groupMemberTaxNumber>
<base:taxpayerId>12345678</base:taxpayerId>
</groupMemberTaxNumber>
</customerTaxNumber>
</customerVatData>

Itt és most ország-világ előtt elismerem, hogy valószínűleg én nem veszek észre valami abszolúte nyilvánvaló dolgot, viszont valaki kegyelmezzen meg nekem, és mesélje el nekem, hogy ez hogyan oldható meg, ha csak a 8 jegyű azonosító áll a rendelkezésünkre.

**Comment by nbeeps2** [comment]
Feladod adószámként: taxpayerid, lásd fent a grafika: Az adóalany adó törzsszáma, csoportos adóalany esetén csoportazonosító szám (vagyis az első 8 karakter). A groupMemberTaxNumber elemet nem töltöd.

**Comment by NTCA-supporter** [comment]
Pontosan, köszi.

**Comment by lakatoskevin** [comment]
`<customerVatData>
<customerTaxNumber>
<base:taxpayerId>17781774</base:taxpayerId>
</customerTaxNumber>
</customerVatData>`

A válasz pedig ERROR 400. Feladom. Megpróbáltatok nekem segíteni, amit köszönök szépen, de feladom. Tudni ekll realisztikusan látni a dolgokat, ha ez a múltkor még működött, most meg nem, akkor ezt el KELL tudni engednem. Köszi mégegyzser mindenkinek a segítséget. Lehet zárni az ISSZJÚT. Peace.

**Comment by nbeeps2** [comment]
@lakatoskevin : Valami teljesen más dolgot elnézel ezen kívül. Kipróbáltam és teljesen jól működik , DONE lesz.

**Comment by lakatoskevin** [comment]
Lehet. Mindenesetre én azon gondolkozom, hogy az utolsó 4-5 kommentet innen kinyomtatom, bekereteztetem, és kirakom a szobám falára. ANNYIRA, de annyira jól reflektál ez a kis rövid sztori az egész életemre, hogy azt elképzelni sem lehet. Szóval lehet máshol lesz itt a probléma, de pont hogy azért kell lezárni ezt az esetet. Ja, és köszi mégegyszer a segítséget!

**Comment by lakatoskevin** [comment]
HAPPY END, ott volt a hiba hogy megváltozott a tag neve, csak a 400-as hiba nem nagyon árulkodott erről. Klappol minden.
