### ISSUE TITLE
Miért nem látszik a multi cégek számlái az adatszolgáltatásban ?

### ISSUE THREAD

**Issue by kristofbela** [nav-gov-hu/Online-Invoice#787]
**A kérdés, amire választ szeretnék kapni 
Miért nem látszik a multi cégek számlái az adatszolgáltatásban ?

**Comment by NTCA-supporter** [comment]
Szia @kristofbela !
Ennyi infoval nem sokat tudok kezdeni. Segíts kérlek, milyen számlát nem látsz? Teszt rendszeren tudsz konkrét példát mondani?
Az adatszolgáltatások lekérdezései kizárólag a kiállítói oldalra vonatkozna. A bejövő számlák oldalon lehet vevő oldali lekérdezést végezni.
Üdv

**Comment by betasofthu** [comment]
Szerintem pénztárgéppel kiállított számláról lehet szó, azok ugyanis nem jelennek meg itt. (pl.: MOL üzemanyag számla)

**Comment by kristofbela** [comment]
![szamla_20210225_111029](https://user-images.githubusercontent.com/75739080/109327126-4715d380-7858-11eb-9653-255390099c15.jpg)

**Comment by nbeeps2** [comment]
Így van, ez egy pénztárgépes számla...

**Comment by Macskafarka** [comment]
Az ÁFA törvény alapján MINDEN számlázó programmal kiállított számlának be kell kerülnie a NAV Online számlaadat-szolgáltatásba.
A pénztárgép is számlázó program, a törvényben nincs felmentés. A NAV-nak kötelessége lenne a törvény betartatása, de valami miatt ezt elmulasztja. Az a látszat, mintha valamilyen háttéralku miatt tűrné meg ezt a jogsértést, ami több kérdést is felvet..

**Comment by nbeeps2** [comment]
@Macskafarka Igen, a kérdés igazából az, hogy mit tekintünk számlázó programnak. A pénztárgép egy hardver és nem egy szoftver, így én nem tekintem számlázó programnak. Viszont, ha úgy defináljuk, hogy minden számlázó program, amivel számlát állítunk elő, akkor meg az... Minden bizonnyal az lehet a háttérben, hogy egy pénztárgép technikailag teljesen másképp működik, mint egy számlázó program. Nem képes az adatszolgáltatás sikerességéken lekérdezésére és/vagy kijelzésére, stb. Ugyanakkor így meg az egész "számlanyilvántartás" fals, mert nem kérdezhetők le az ilyen bejövő számlák a NAV rendszeréből. Faramuci egy helyzet...

**Comment by omachtandras** [comment]
@nbeeps2 : azért csak fut valami szoftver is azon a hardveren... A probléma szerintem inkább az, hogy volt egy pénztárgépes adatszolgáltatás, és most van egy másik, ahol a NAV sokkal-de sokkal több adatot kér (többet egyébként, mint ami egy ÁFA bevalláshoz kellene), és ahogy az 1.0->2.0->3.0 konverziót sem vállalja be (senki), úgy azt sem tudja megoldani - legalább is jó ideje.

**Comment by Macskafarka** [comment]
@nbeeps2 Nem számít az, hogy Te vagy én minek tekintjük a pénztárgépet, mert ezt az Áfa tv. szabályozza a 10.sz,. mellékletében. 
Ezek szerint számlát kétféle módon lehet kiállítani: 1. nyomdai úton előállított nyomtatvány használatával, 2.  számlázási funkcióval rendelkező programmal. Mindkettőnek szerepelnie kell a NAV Online adatszolgáltatásban. Nincs olyan opció, hogy valami más csinál számlát, és azt nem kell betenni az adatszolgáltatásba. Ha az autóm készítene számlát, akkor az számlázó programmal készített számla, ahogy a pénztárgép is. Maga a gép fizikai teste nem készít számlát, a pénztárgépben is processzor van, és számlázó program fut. A pénztárgépe használatát a NAV engedélyéjez van kötve, viszont a NAV-nak a kötelessége az Áfa tv.  és benne a számla adatszolgáltatás betartatása. Nekem úgy tűnik, hogy a NAV tudtával, és engedélyével történik a törvényszegés, az adatszolgáltatás elszabotálása. Zavar, hogy nem lehet ezeket a számlákat letölteni a NAV-tól, pedig azért fejlesztettünk erre  funkciót, mert a törvény betartásában reménykedtünk. Így a letöltés értelme vált kérdésessé, sőt a NAV által 2021.07.01-től készítendő Áfa bevallás tervezet is. Ha abban benne lesznek ezek a pénztárgépes számlák, de letölteni nem lehet, az érdekes jogi helyzetet okoz.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Már folyamatban van a pénztárgépes számlák Online Számla rendszerbe történő áttöltés folyamatának kialakítása, meg lesz oldva, hogy ezen számlák is látszódjanak.
Ha nincs több kérdés, kérlek zárjátok az issuet.
Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet. A pénztárgépes számlákkal kapcsolatos issue a #411 
Üdv
