### ISSUE TITLE
[FEATURE] WADL mellett WSDL

### ISSUE THREAD

**Issue by connorhu** [nav-gov-hu/Online-Invoice#788]
**Az igény összefoglalása / Summary of the request**
Egyik partner jelezte, hogy ők szívesebben dolgoznának WSDL-ből, idézem: "This made it easier for us to generate the service code from the definition."
Lehetséges-e a jövőben a WADL mellett a WSDL is?

**Comment by EPluribusUnum** [comment]
@connorhu , nem lehet adni wsdl-t, mert ez nem SOAP/WS API interface. Ez mezei https + xml.
