### ISSUE TITLE
API Error responses / technical or business messages comes back in the wrong language

### ISSUE THREAD

**Issue by swinkler13fja** [nav-gov-hu/Online-Invoice#789]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[x] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
Transaction status of a previous submitted ManageInvoiceRequest
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**

The following issue is effected on the Test-API and maybe on the Production-API. Noting to the documentation on page 68:

_Documentation:_
"The message tag returns the technical error message (for technical validations) or the business definition of the blocking error (ERROR) or warning (WARN) (for business validations). The validation result localisation observes the contact language of the technical user making the query."

_Current Behavior:_
The chosen language (Contact Language) for the Technical User at the Web-Portal (Test-Environment) is Englisch, but the API responses comes back in Hungarian language .

_Expected Behavior:_
The API Response for Error / Technical / Business messages should be transmitted in the selected "contact language" of the technical user at the web portal. Regardless if it's the test or produktion environment.

```<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<QueryTransactionStatusResponse xmlns="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns2="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">
    <ns2:header>
        <ns2:requestId>RID010321073635647STDE</ns2:requestId>
        <ns2:timestamp>2021-03-01T07:36:35.647Z</ns2:timestamp>
        <ns2:requestVersion>3.0</ns2:requestVersion>
        <ns2:headerVersion>1.0</ns2:headerVersion>
    </ns2:header>
    <ns2:result>
        <ns2:funcCode>OK</ns2:funcCode>
    </ns2:result>
    <software>
        <softwareId>276090100027771000</softwareId>
        <softwareName>Fuljoy*********</softwareName>
        <softwareOperation>LOCAL_SOFTWARE</softwareOperation>
        <softwareMainVersion>1.0</softwareMainVersion>
        <softwareDevName>Stephan ********</softwareDevName>
        <softwareDevContact>it@*********.de</softwareDevContact>
        <softwareDevCountryCode>DE</softwareDevCountryCode>
        <softwareDevTaxNumber>**************</softwareDevTaxNumber>
    </software>
    <processingResults>
        <processingResult>
            <index>1</index>
            <invoiceStatus>DONE</invoiceStatus>
            <businessValidationMessages>
                <validationResultCode>WARN</validationResultCode>
                <validationErrorCode>INCORRECT_LINE_CALCULATION_NET_AMOUNT</validationErrorCode>
                <message>A tétel mennyiség és egységár szorzata (figyelembe véve az adott kedvezményt) eltér a nettó értékétől.</message>
                <pointer>
                    <tag>InvoiceData/invoiceMain/invoice/invoiceLines/line/lineAmountsNormal/lineNetAmountData/lineNetAmount</tag>
                    <value>8653.54</value>
                    <line>1</line>
                </pointer>
            </businessValidationMessages>
            <compressedContentIndicator>false</compressedContentIndicator>
        </processingResult>
        <originalRequestVersion>3.0</originalRequestVersion>
    </processingResults>
</QueryTransactionStatusResponse>```

*Egyéb tartalom / Additional content*

**Comment by NTCA-supporter** [comment]
Hi @swinkler13fja !
I checked your 94wbv0bbwpnfdle user in database and it has HU value as language.
Are you sure that you changed the language to EN?
Br

**Comment by swinkler13fja** [comment]
Thanks for the quick response, I checked both accounts now, the test environment and the production. 
For reproduction, I used the following steps:

1. got to https://onlineszamla-test.nav.gov.hu (TEST) or https://onlineszamla.nav.gov.hu (Production)
2. click on the button "LOGIN" at the top
3. login with the given user credentials
4. click on the "User-Card" on top of the page
5. click on the button "USER PROFILE"
6. show in the field "Contact Language"

In both cases are the Language "English" is selected. So I think that the API messages will be getting back in English. I know the language was chosen during the registration process. It was never changed by myself after that.

So in the case that your database entry ha the value HU, there is no wonder that I receive all messages only on Hungary.  I'm not sure where the issue is located. The only think what I can do, changing the language via web-portal again to look if the API language will be changed.

**Comment by NTCA-supporter** [comment]
Hi!

As the documentation says, the lang of the queryTransactionStatus response depends on the technical user's setup.
So you should modify the used technical user's language. The customer's language setup you mentioned is a global setup, but it's for other purposes.
It's a bit complicated I know :) 
Br

**Comment by swinkler13fja** [comment]
Ah Ok, thanks for this information.
