### ISSUE TITLE
[DOC]Header verzió

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#79]
A docu szerint nem lehet megadni 2.0-t a requestVersion-ban. 5.oldal.

**Comment by NTCA-developer** [comment]
Szia!

A ticket most a requestVersion vagy a headerVersion tagra vonatkozik? A doksiban egyébként mindkettő jól szerepel, de az indokolás miatt kérdezem. :)

**Comment by kabelnet2** [comment]
Re: [nav-gov-hu/Online-Invoice] [DOC]Header verzió (#79)



Szia, requestVersion-nál az én pdf-emben (utolsó módosítás 09.18) az enum oszlopban 1.0 és 1.1 van (csak), a 2.0 hiányzik. Üdv, Tamás






Szia!
A ticket most a requestVersion vagy a headerVersion tagra vonatkozik? A doksiban egyébként mindkettő jól szerepel, de az indokolás miatt kérdezem. :)
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/nav-gov-hu/Online-Invoice/issues/79?email_source=notifications\u0026email_token=AL6YQHO4SGI5FNYK2OSQYUTQRHJTPA5CNFSM4JG6UDCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECVMB7I#issuecomment-548061437", "url": "https://github.com/nav-gov-hu/Online-Invoice/issues/79?email_source=notifications\u0026email_token=AL6YQHO4SGI5FNYK2OSQYUTQRHJTPA5CNFSM4JG6UDCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECVMB7I#issuecomment-548061437", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by NTCA-developer** [comment]
Hoppá. És tényleg. Van 10.14-i változat, ahol pont csomó Githubos észrevételt vezettünk át meg sok más szöveget is javítottunk, illetve a batchInvoice implementálása után beemeltük az új ERROR és WARN üzeneteket is. De ez a változat tényleg nincs kint a honlapon. Utánanézek. A doksi egyszer még biztosan lesz változtatva, mert hamarosan összeülünk átbeszélni a nyitott Githubos fejlesztési igényeket és biztosan lesz olyan amit beépítünk, ez miatt a doksi is változik.

Azért köszönöm hogy jelezted.

ui: megtennéd nekem, hogy prog.hu-ra kipostolod a data sample XML-ek elérését? Mert githubon már egy hete kint vannak, a központi honlapon még egyéb okok miatt nincsenek és sokan keresik őket.

https://github.com/nav-gov-hu/Online-Invoice/tree/master/sample/Data%20sample

Köszi!

**Comment by skovacs70** [comment]
Szia @NTCA-developer,

Az előző hozzászólásodban említetted, hogy van 10.14-ei változat a doksiból, de a honlapon még mindig a 09.18-as van kint.
Ez ki fog még kerülni, vagy már csak a következő változat? (Írtad, hogy még egyszer biztosan fog változni.)

Köszönöm.

**Comment by NTCA-developer** [comment]
Szia @skovacs70 

Kikerült a 10.14-es állapot végre. Élesen és teszten is kint van. Ez egyben válasz is a kérdésedre. Az új változat majd csak akkor, ha sikerült a megbeszélést összehozni a nyitott fejlesztési témákról.

De ezek csak kényelmi fejlesztések és módosítások lesznek, nagy koncepcionális változás nem várható.
