### ISSUE TITLE
[Q&A] softwareId

### ISSUE THREAD

**Issue by kovacspeter1** [nav-gov-hu/Online-Invoice#791]
Az API leírásban a kérések fejlécében kötelező mezőként szerepel a softwareId, vagyis a "A számlázó program azonosítója". Ez pontosan milyen azonosító és hogyan lehet hozzájutni egy ilyenhez?

**Comment by makailaci** [comment]
> Az API leírásban a kérések fejlécében kötelező mezőként szerepel a softwareId, vagyis a "A számlázó program azonosítója". Ez pontosan milyen azonosító és hogyan lehet hozzájutni egy ilyenhez?

Ezt neked kell összerakni magadnak. Egyértelmű legyen, hogy melyik program melyik verziójával ment a beküldés.

Doksiból:
A softwareId az adott számlázó program azonosítására szolgáló 18 elemű karaktersorozat.
A softwareId képzésére vonatkozó ajánlás: az azonosító első két karaktere a szoftvert fejlesztő cég országkódja ISO 3166 alpha-2 szabvány szerint. Az azonosító további karakterei a fejlesztő cég adószám törzsszáma, megfelelő számú számjegyen (egyes országokban az adószám hosszúsága lényegesen eltérhet a Magyarországon megszokott 8 számjegytől).

**Comment by kovacspeter1** [comment]
De nekem webáruházam van, nem számlázó programom. A számlázó program a NAV Online-Invoice. Vagy ilyenkor a számlázó program úgy értendő, hogy az a program, ami számlázást kér a NAV-os programtól az API-n keresztül?

**Comment by renced42** [comment]
> De nekem webáruházam van, nem számlázó programom. A számlázó program a NAV Online-Invoice. Vagy ilyenkor a számlázó program úgy értendő, hogy az a program, ami számlázást kér a NAV-os programtól az API-n keresztül?
> És ezt az azonosítót be is kell valahogy regisztráltatni a NAV-nál, vagy elég, ha mindig ugyanazt használom?

Akkor neked ezzel nem kell foglalkoznod, mert azt a NAV Online Számlázó rendszere kitölti.

**Comment by kovacspeter1** [comment]
Nincs saját számlázórendszerünk. A webáruházunk tulajdonosa a szállítói számlákat szeretné importálni a NAV-tól API-n keresztül. Van erre bármilyen egyszerű megoldás?

**Comment by BeczeT** [comment]
Nekem van. Írj privátban, ha érdekel.

**Comment by renced42** [comment]
Kedves @kovacspeter1 

A vevő oldali számlákat a vevő az API-n keresztül le tudja kérdezni.

**Comment by connorhu** [comment]
Ha csak importálni szeretnéd akkor azt egy tetszőleges libbel meg lehet csinálni. Ebben akár én is tudok segíteni.

**Comment by kovacspeter1** [comment]
connorhu, köszönöm a felajánlást. Hogyan tudnék privátban írni neked, hogy megbeszéljük? (Az itteni email címed nem publikus.)

**Comment by connorhu** [comment]
connor @ connor hu

**Comment by NTCA-supporter** [comment]
Zárom az issuet, ha van még kérdés nyissátok újra kérlek.
Üdv
