### ISSUE TITLE
Több számla módosítása egy okirattal xml példa

### ISSUE THREAD

**Issue by KrisztaBal** [nav-gov-hu/Online-Invoice#792]
Hello, az lenne a kérdésem, hogy a **Több számla módosítása egy okirattal** példához terveztek-e olyan példa xml-t megosztani, amelyben a termékek darabszámát javítjátok nem csak a fizetési határidőt, egyebeket. Sokat segítene. Köszönettel, Kriszta

**Comment by NTCA-supporter** [comment]
Szia @KrisztaBal !
Nem tudok róla, a meglévő példák alapján összeollózható egy ilyen eset.
Üdv
