### ISSUE TITLE
[DEV support]

### ISSUE THREAD

**Issue by vkozakevich** [nav-gov-hu/Online-Invoice#793]
Hello.
We have an invoice with customer from Switzerland. Customer has vat code CHE-115.138.470 MWST. But NTCA accept only digital value.  Therefore, when uploading a file to the system, we have an error

- XML contains on line: [24] and column: [38] error:  [cvc-pattern-valid: Value '' is not facet-valid with respect to pattern  '[0-9]{8}' for type 'TaxpayerIdType'.]
--
- XML contains on line: [24] and column: [38] error: [cvc-type.3.1.3: The value '' of element 'taxpayerId' is not valid.]
- XML contains on line: [25] and column: [48] error:  [cvc-pattern-valid: Value '115.138.470 MWST' is not facet-valid with  respect to pattern '[1-5]{1}' for type 'VatCodeType'.]
- XML contains on line: [25] and column: [48] error: [cvc-type.3.1.3:  The value '115.138.470 MWST' of element 'vatCode' is not valid.]
- Xml validation failed

What value should the tag taxpayerId  contain in this case?

**Comment by NTCA-supporter** [comment]
Hi @vkozakevich !
I guess you should fill the thirdStateTaxId in this case.
![image](https://user-images.githubusercontent.com/58814216/109678997-7770b100-7b7b-11eb-948f-e351c54595cc.png)

Br

**Comment by vkozakevich** [comment]
> Hi @vkozakevich !
> I guess you should fill the thirdStateTaxId in this case.
> ![image](https://user-images.githubusercontent.com/58814216/109678997-7770b100-7b7b-11eb-948f-e351c54595cc.png)
> 
> Br

If i will fill thirdStateTaxId, then what value should the tag taxpayerId contain? The same value?

**Comment by vkozakevich** [comment]
Thank You.
