### ISSUE TITLE
[Q&A] V3 query_invoice_data V2-es számla éles lassúság

### ISSUE THREAD

**Issue by csandazoltan** [nav-gov-hu/Online-Invoice#795]
Kedves Support!

Éles rendszer lassú

Kérdésem az lenne, hogy abban az esetben, ha V2-vel jelentett számla adatot kérdezek le V3 invoice_data kéréssel, miért ennyire lassú a válasz?
Ez a verzió eltérések miatt van, vagy a V3as lekérdezés az élesen általánosan lassú?

Vadul ugrál 2mp és 20mp között.
Minden nap letöltjük a teljes számlaállományt önellenőrzés céljából. Ez több ezer számlánál, súlyos órákat vett most igénybe, a V2-höz képest

Most álltunk át a V3-as rendszerre, ami a V2-höz képest nagyságrendekkel lassabb.
Hajnal 3kor kezdtünk letölteni egyesével 2040 számlát letölteni, 5 órával később 1610-nél tart. Ez átlagban 11mp-es válaszidőt jelent számlánként.
V2 eseteén, körülbelül ugyanekkora számlamennyiségnél másfél óra volt, ez átlagban 2mpes válaszidőt jelent.

**Comment by nbeeps2** [comment]
Én azt vettem észre, hogy V2/V3-ről független azok a számlák lekérdezése jóval lassabb, amik tömörítve lettek beküldve (pl. Telekom által kiállított számlák). Ezek lehívására olykor 30-45 mp-et is kell várni.

**Comment by csandazoltan** [comment]
> Én azt vettem észre, hogy V2/V3-ről független azok a számlák lekérdezése jóval lassabb, amik tömörítve lettek beküldve (pl. Telekom által kiállított számlák). Ezek lehívására olykor 30-45 mp-et is kell várni.

compressedContentIndicator true?

Érdekes, szerencsére a mi számláink nem ilyenek.

**Comment by nbeeps2** [comment]
@csandazoltan compressedContentIndicator true: igen

**Comment by NTCA-supporter** [comment]
Szia @csandazoltan !

Köszi a jelzést.
Akkor összefoglalva, az összes beküldött számla v2-es.
v2-es interfészen végigiterálva ezeken queryInvoiceData lekérdezéssel sokkal gyorsabb, mint v3 interfészen ugyanazon a számla halmazon?
Utánanézek mi lehet. Az biztos, hogy nem erőforrás eloszlási probléma, a v3-nak nincs kevesebb kiosztott erőforrása mint v2-nek.

Üdv

**Comment by csandazoltan** [comment]
> Szia @csandazoltan !
> 
> Köszi a jelzést.
> Akkor összefoglalva, az összes beküldött számla v2-es.
> v2-es interfészen végigiterálva ezeken queryInvoiceData lekérdezéssel sokkal gyorsabb, mint v3 interfészen ugyanazon a számla halmazon?
> Utánanézek mi lehet. Az biztos, hogy nem erőforrás eloszlási probléma, a v3-nak nincs kevesebb kiosztott erőforrása mint v2-nek.
> 
> Üdv

Nem pont ugyanaz. március 1 előtt V2-vel ment a lekérdezés, március 1 után v3-al

2-3 ezer számlát állítunk nagyságrendileg naponta
V2-ben áltagban 1,5 óra alatt végzett 1 nappal.
V3 még mindig megy 8 órája 1864-nél tart a 2040-ben

Csinátam egy kis tesztet, ugyanazt a számlát kértem le 20-szor v2-ben, 20-szor v3-ban
Úgy tűnik nem csak V3-ban van gond

A metrics sem teljesen pontos
https://api.onlineszamla.nav.gov.hu/metricService/v3/queryServiceMetrics/metric/responseTimeAverageMsQueryInvoiceData

Eszerint 2554 most az átlag válaszidő, ez nem igazon "pontos", legalábbis nekem.

Van valami limit, hogy milyen gyorsan lehet lekérni? Nem láttam leírásban, csak a régebbi verziók limitálását.

Itt a "teszt" (válaszidő millisec-ben):
Tudom, nem számottevő a teszt, de ezt látom most, nagyon ugrál a rendszer 1mp alatt-tól 15 másodperc felettig.

![image](https://user-images.githubusercontent.com/6756505/109789249-7342a300-7c10-11eb-860e-8c846e431036.png)

**Comment by csandazoltan** [comment]
Ok, kicsit javult a helyzet, de még mindig ugrál
![image](https://user-images.githubusercontent.com/6756505/109912724-eef22d80-7cac-11eb-9e9c-c0cdfbdf2c4e.png)

**Comment by csandazoltan** [comment]
Megnéztem megint, visszatért a 17-18 mp maximum, 7-8 mp átlag

Ha sokat kérek szorosan egymás után, akkor valami várólistára kerül a kérés, érdekes ez az 1mp alatt és 15mp fölötti ingadozás

**Comment by csandazoltan** [comment]
@NTCA-supporter 
Ma reggel már jobb a helyzet, max 1 mp, min 300ms. V2 és V3 is. Ez így tökéletes!

Kíváncsi vagyok. Mi történt?

**Comment by nbeeps2** [comment]
@csandazoltan Zár az ország :) Jövő héttől hasítani fog ;)

**Comment by csandazoltan** [comment]
@nbeeps2 Sajnos ez nem a "jó" megoldás :(

**Comment by csandazoltan** [comment]
@NTCA-supporter Próbálok rájönni mi a baj, mert valami még mindig nem kerek....
Vannak olyan számlák amiknek nagyon sokáig tart a válasza, van amelyik azonnal lejön 1mp alatt.

Van amikor lejön másodpercenként 4-5 számla, van amikor percenként 2-3

Az alább lekértem egy batch módosító számlát ami 13 módosításból áll, ennek a lekérése nagyon nagyon sokáig tart
Ez így jól van?
![image](https://user-images.githubusercontent.com/6756505/110112292-d6b80680-7db1-11eb-8c30-955c71ccbd7f.png)

**Comment by csandazoltan** [comment]
Újabb göngyszem ma reggel

![image](https://user-images.githubusercontent.com/6756505/114138160-86324c80-990d-11eb-8433-e1591c787d1f.png)

**Comment by csandazoltan** [comment]
Ezek a válaszidők elég hosszúak
![image](https://user-images.githubusercontent.com/6756505/114355682-0ce66400-9b70-11eb-9691-0ec64dd7f373.png)

**Comment by NTCA-supporter** [comment]
@csandazoltan köszi az infokat.
Holnap kérlek próbálj rá újra, 2.0 és 3.0 számlákra is. Találtunk egy optimalizálást, ami egyelőre bizakodásra ad okot, de majd csúcsidőben kiderül.
Köszi

**Comment by csandazoltan** [comment]
@NTCA-supporter 
Szóval akkor tudott, hogy lassulás van. Ez hova lett kiírva? A metrics miért nem tükrözi ezt a helyzetet?

Egy létrehozó számla lekérdezése klasszisokkal gyorsabb
![image](https://user-images.githubusercontent.com/6756505/114650705-03313d80-9ce3-11eb-8fb7-ff1b85df645d.png)

Viszont egy csoportos módosító számla 32 elemmel, lassú maradt. Jobb, de lassú
![image](https://user-images.githubusercontent.com/6756505/114651412-33c5a700-9ce4-11eb-9e2e-e006363eebae.png)
![image](https://user-images.githubusercontent.com/6756505/114652677-a9cb0d80-9ce6-11eb-933b-3e2f26b53f1a.png)

V2 VS V3
V2-t nem tudtam összehasonlítani, mert a /invoiceService/v2/queryInvoiceData 503-as hibát ad.
`no healthy upstream`

Create gyors
![image](https://user-images.githubusercontent.com/6756505/114652498-450fb300-9ce6-11eb-946e-76b54ef17539.png)

V2-es módosító számlát lekérdezni, V3-al eléggé lassú
11 eleme van
![image](https://user-images.githubusercontent.com/6756505/114653627-bd777380-9ce8-11eb-934f-e471c20c1e04.png)

---

Valami gond a módosító számlák lekérdezésével van
Próbáltam találni egyre nagyobb tételszámú számlákat
5-ig nem sok baj van, 5-10-között már növekszik a váladszidő lineárisan.

10-nél kb 10szeres a válaszidő
![image](https://user-images.githubusercontent.com/6756505/114653893-4b535e80-9ce9-11eb-8506-34fede3ef211.png)

11-nél elszalad a szekér és már nem lineáris a növekedés
![image](https://user-images.githubusercontent.com/6756505/114654443-77231400-9cea-11eb-9592-d257f6659bdf.png)

12-nél is
![image](https://user-images.githubusercontent.com/6756505/114654824-40013280-9ceb-11eb-8b63-2cd13b46adfc.png)

20 tétel
![image](https://user-images.githubusercontent.com/6756505/114656108-c74fa580-9ced-11eb-9bb5-3b5f83274879.png)


Van egy 94 tételesünk is, azt nem akartam elindítani :)

**Comment by renced42** [comment]
Kedves @csandazoltan 

Ha itt nincs több észrevétel kérlek zárd az issue-t.

Köszönöm szépen!

**Comment by csandazoltan** [comment]
@renced42 Ha kapok választ a problémámra, akkor zárom az issue-t.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ha ezek a nyitott kérdések: "Szóval akkor tudott, hogy lassulás van. Ez hova lett kiírva? A metrics miért nem tükrözi ezt a helyzetet?"
Akkor: ha tudott, akkor hírként publikálva van. Ha nem, akkor sehova nem lett kiírva. A metrics átlagot mutat. Többet jelenleg nem tudok, főleg így visszamenőleg.

Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Köszönöm!
