### ISSUE TITLE
[Q&A] onlineszamla-test.nav.gov.hu megjelenítés eltér felhasználónként

### ISSUE THREAD

**Issue by burnyo** [nav-gov-hu/Online-Invoice#798]
Tisztelt NAV!

Az átállási tesztek során egy általam nem megmagyarázható eltéréseket vettem észre az én gépemen és a felhasználó gépén megjelenő, ugyanahhoz a számlához tartozó NAV-oldal adataiban. Egy EUR pénznemben beküldött számla az én böngészőmben a NAV oldalán helyesen EUR-nak látszik és az összegadatok is helyesen EUR és HUF formában is megjelennek. A felhasználó gépén a NAV oldalon (persze az ő azonosítójával belépve) ugyanabban a számla pénznemmezőben már forint szerepel és az adatok is valószínűleg emiatt eltérően jelennek meg. Tranzakcióazonosító teljesen ugyanaz, ahogy a mellékelt linkekre feltöltött képeken is látszik. 

Mi lehet ennek az oka? Találkoztak már ilyen problémával? Ez nagyon megnehezíti a tesztelést számunkra. Segítségüket előre si köszönjük!

Ezek a két egymás melletti ablakról készÍtett képernyőképek linkjei:
https://ibb.co/Tcx5NwF
https://ibb.co/mbqnJX0
https://ibb.co/GCLk27w

**Comment by topybear** [comment]
Esetleg nem hasonló a probléma oka?
https://github.com/nav-gov-hu/Online-Invoice/issues/752

**Comment by burnyo** [comment]
Talált, süllyedt! :-) Nem találtam rá erre a posztra, de teljesen ugyanez a helyzet, a felhasználó belépés után rögtön a 3.0-s számlát megjelenítve a jó adatokat látja. Köszönöm szépen a gyors segítséget, megpróbálunk ezzel együtt élni, amíg ki nem javítják a hibát.

**Comment by NTCA-supporter** [comment]
Szia @burnyo !
Köszi a jelzést, az említett issueban lesz jelezve ha kész a javítás.
Ezt zárom.
Üdv
