### ISSUE TITLE
[Q&A] Különböző operációk közös requestben

### ISSUE THREAD

**Issue by Amn3s1a2018** [nav-gov-hu/Online-Invoice#8]
A manageAnnulment leválasztásának leírását rövidebbre lehetne venne. A külön URL miatt technikailag nem lehetséges az ANNUL operációt keveredése a többivel, ezt ennél bővebben kifejteni felesleges.

A leírásból (számomra) nem világos, hogy a többi operáció (pl. CREATE és STORNO egyszerre) szerepelhet-e közös manageInvoice kérésben. A számlaláncok kezelésének új verziója elméletileg megengedné, hogy egy számlalánc több elemét egyszerre adjuk fel. Életszerűbb eset, ha egymástól független, de eltérő operációk egyszerre keletkeznek. Ezeket a jövőben lehetne küldeni egy tokennel?

**Comment by NTCA-developer** [comment]
Szia!

Köszönöm hogy kiemelted a kérdést a pull requestből. A ManageAnnulmentOperationType simple type által leírt minden operáció szerepelhet bármilyen kombinációban a /manageInvoice hívásban. 

Viszont vedd figyelembe, hogy ha egy számlával több módosítást szeretnél végezni (a belső base64 tartalomban batchInvoice elemet szeretnél képezni) akkor a /manageInvoice hívásban csak 1 indexed lehet, különben nem fogadjuk be a kérést. Ebből következően, (mivel az index alatt van az operáció értéke is) ilyen esetben csak 1 MODIFY vagy 1 STORNO operációd lehet. (ez viszont megszámlálhatatlan mennyiségű számlát tartalmazhat belül)

Megválaszoltam, vagy van még kérdésed?

**Comment by Amn3s1a2018** [comment]
A konkrét kérdést szerintem tisztáztuk, köszönöm. Lenne kérdésem, ami nem tartozik szorosan a fentiekhez, ezeket feladom külön issue-ban.
