### ISSUE TITLE
[Q&A]A régi problémám utózöngései

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#80]
Tudom, hogy most már nem fogtok semmin változtatni (ezért is Q&A), de azért megint visszautalnék, arra a korábbi issue-ra, hogy egy módosító gyűjtőszámlának vannak-e (megjegyzendő, elmentendő) saját adatai. A Jedi tanács szerint nincsenek.

Most éppen az electronicInvoiceHash megadásánál (mi megadjuk) vagyok gondban.
- ha egy batch index alatt adom meg, akkor szerintem az a jelentése, hogy az eredeti számlánál megadott hibás volt, s most módosítom a jó értékre
- ez rendben is van, de akkor hol adjam meg a módosító számlának magának a hash-ét, amivel a vevő ellenőrizni tudja, hogy jó-e a számla?

(ez az adat  a módosító számla saját adata, amit vállaltatok, hogy tároltok és nem csak alapszámlára. Ezt a módosító számla számlaszámára hivatkozva kellene visszakapnom.)
Ötlet?

**Comment by NTCA-developer** [comment]
Szia @kabelnet2 

Hmm, igen, nagyon is értem a kérdést. 

> ha egy batch index alatt adom meg, akkor szerintem az a jelentése, hogy az eredeti számlánál megadott hibás volt, s most módosítom a jó értékre

Igen, ezt teljesen jól gondolod, mi is így fogjuk kezelni. És a batchInvoice még csak nem is kell hogy képben legyen, a sima módosítás hashére sincs meg a dedikált tag. 

Ha azzal kell főzni amink van, akkor a barkács megoldás az hogy csinálj additionalData taget a számlafejhez és oda egy általad megalkotott egyezményes kóddal írd bele a módosítás saját hashét, de hadd kérdezzek rá erre jövő héten. Ha van rá szép megoldás, akkor én inkább azt szeretném.

**Comment by kabelnet2** [comment]
Kösz, várok, hátha lesz valami jó megoldás. A barkács azért nem tetszik, mert ez feature, ha valaki használni akarja, akkor ott keresi, ahol annak lenni kellene (pl. a web-es felületen a megfelelő mezőben). Ha mindenkinek külön levélben kell jelezni, hogy az nem az igazi, hanem ott valahol elbújtatva van az igazi, hát az már nem olyan jó, már a bizalom is megrendül az egész iránt.
Vagyis várok.

**Comment by kabelnet2** [comment]
Azért azt kérlek lásd be, hogy az általad javasolt megoldás nem igazán használható. Az AdditionalInvoiceData az invoiceDetail-ben van, vagyis ha megadom, az a módosított (eredeti) számla adatát fogja felülírni - vagyis ugyan ott vagyunk, mint a hash tag-el magával.

**Comment by NTCA-developer** [comment]
:)

Nem javasolnék olyan megoldást, ami nem működik. Maga az AdditionalInvoiceData egy listaelem, ezeken nem felülírjuk hanem uniózzuk. Felülírás csak akkor történik, ha az általad használt dataName már szerpelt a láncban korábban.

Szóval ha kinevezel egy értéket a módosító számla hashének, akkor nemcsak hogy megadhatod, hanem később még azt is helyesbítheted. (noha csak ezért számla módosítás nem indokolt, ez inkább technikai érvénytelenítésnek tűnik)

**Comment by kabelnet2** [comment]
Igen, de a módosított számla eleme, amit (azonos név esetén) felül is ír egy újabb módosítás. Gondolj a felhasználóra, akinek meg kellene találni a jó hash-t.
Biztos lehet valahogy ezt is használni, csak túl nehézkes, túl bonyolult, úgyhogy inkább marad a külső szolgáltató.

**Comment by NTCA-developer** [comment]
Oké, én csak a nem használható megoldás részre reagáltam. De próbálom ütni a szép megoldást is ettől függetlenül.

**Comment by NTCA-developer** [comment]
Szia @kabelnet2 

Sajnálom, de ennek a kiigazítására csak a 3.0-ban lesz lehetőség. A NAV az API bővítését és a kényelmi szolgáltatások - nagyobb jó értekében történő - módosítását még bevállalja a április előtt, de a Data már sérthetetlen. Valahol igazad kell adnom nekik, ez is egy valid szempont.

Addig nyitva hagyom, hogy ne felejtődjön el. Addig is marad a barkács amit beszéltünk.

**Comment by kabelnet2** [comment]
Bár valóban beszéltünk barkács módszerről, az én inkább kihagynám.
Akkor, ha már nem 2.0-ról beszélünk, lenne két megjegyzésem a dologhoz:
1. A (NAV) rendszernek támogatni kellene a számlák hitelességének ellenőrzését. Egy olyan funkcióra gondolok, ahol az én vevőim fel tudnak tölteni egy számlát (pdf) egy interface-en és a rendszer megmondja, hogy az hiteles vagy sem (kiszámolja az SHA-t és összehasonlítja). Ettől lenne a számla e-számla, hogy a hitelessége ellenőrizhető. 
Ebben az esetben bárhol lehetne az SHA, azt csak a feltöltőre és a NAV-ra tartozna. Az ötlet nem új, korábban (github előtt) leveleztem erről a supporttal.
2. Ha a módosító számláknak van egy eleme, amely esetében elismeritek, hogy az tárolásra érdemes a módosító számla sajátjaként, akkor vissza lehetne térni az eredeti problémámhoz, és megvizsgálni, hogy a módosító számla, mint önálló onjektum néhány elemét is tárolni lehetne a rendszerben (pl. fizetési határidő,...)

**Comment by szabogab** [comment]
Szia @kabelnet2!

Kérem segíts a electronicInvoiceHash megadásánál.
Leírás szerint: "Elektronikus számla vagy módosító okirat állomány SHA256 lenyomata."
 Vagyis a hash kód a számla adattartalmát tartalmazza digitális formában, kódolva.
Kérdésem:
Hash kódot miért a számla tartalmaként (InvoiceDetailType) kell szerepeltetni, hiszen a megképzett hash maga a számlát jelképezi.

Ha hash-t kiszámolom eredeti számlából és ezzel a hash sorral bővítem az eredeti számlát, akkor épp a tartalma fog újból megváltozni, így a hash és a tartalma sose lesz következetes.
Ez nekem ördögi kör...

**Comment by kabelnet2** [comment]
Szia, Először is ez az SHA256 nem tartozik az online-számlához, egy egy külön szolgáltatás, arra szolgál, hogy elektronikus számlát tudjál csinálni a valamilyen elektronikus formában továbbított számláidból (mondjuk pdf-ből).
Ez akkor van meg, ha a vevőd tudja ellenőrizni, hogy a kapott számla pontosan ugyan az, mint amit te kiállítottál. Ebben segít a NAV online rendszere.
Miután előállítottad a számlát elektronikus formában (pl. pdf file) előállíthatod annak a file-nak az SHA256 lenyomatát, a pdf-től teljesen külön. Ezt az SHA256 lenyomatot tudod elküldeni azonline számlávan együtt a NAV-hoz, aki tárolja azt (mást nem csinál vele.
Ha most a vevőd ellenőrizni akarja a tőled kapott pdf file-t (hogy nem sérült-e pl.), akkor előállítha ő is annak SHA256 lenyomatát és összehasonlítja a NAV online számla rendszeréből kinyerhető, általad feltöltött adattal. Ha a kettő azonos, akkor a számla hiteles.
Én most az elvet mondtam el. Ha olvasod a fentebb leírtakat, láthatod, hogy azért nem minden OK ezen a részen, úgyhogy mi pl. maradtunk a külső hitelesítő használatánál az elektronikus számlázásban, mégha fizetni is kell érte.

**Comment by szabogab** [comment]
Köszönöm, megvilágosodtam!

**Comment by Amn3s1a2018** [comment]
Szia, @kabelnet2 
Mi is gondolkodtunk ilyenen, és bár végül elvetettük volt két ötlet ami talán használható.

Nem tudom van-e az  electronicInvoiceHash definícióba belefér-e (nem találtam ilyent)...
Szóval adott a probléma, hogy van a számlának ez a kifacsart értelmezése, hogy a számlalánc eleje az számla, a módosító meg nem és nincs is neki adata. Mivel a NAV-nál ehez ragaszkodnak és ezt nem tudjuk se átugrani se megkerülni mi lenne, ha csak simán elfogadjuk, úgy ahogy van.
Ha innen nézzük újra a hash kérdését, akkor a számla 
  - amikor elkezdjük a számlaláncot, még csak ez az egy dokumentum. Ennek a hash-ét feladom. 
  - Kiderül, hogy módosítani kell a számlát. A módosító maga nem a számla, tehát ebből nem csinálok hash-t
  - Már az eredeti sem számla, hiszen módosítottam. Volt rajta hibás adat amit javítani kellett, ha azt az adatot egyből jól adom meg, nyilván a hash is más lett volna, tehát a hash is hibás, vagyis azt is javítani kell, de mire?
  - Van két dokumentumom, mostmár a kettő együtt a számla, tehát a két dokumentum egyben megfogom és abból készítem el a hash-t, és ez lesz a módosítás aláírása.

És mi van akkor, ha tényleg az electronicInvoiceHash volt a téves, mert pl sha helyett véletlenül crc-vel számoltad? Ugyanez. Csinálsz egy módosítást ami nem módosít semmit (semmi mást), az eredeti meg az üres módosítás uniója lesz a hash alapja, és ez lesz az electronicInvoiceHash.

A második 5let, hogy ragaszkodunk ahoz, hogy a hash a konkrét dokumentum tulajdonsága, és az additionalInvoiceData/dataName=electronicInvoiceHash<ID> mezőben adjuk fel, ahol az ID a dokumentum azonosítója, pl. egy számlaszám vagy bármi amivel meg tudod különböztetni a számlalánc elemeit. Így lehet módosítani, ha azt kell és minden módosítónak is van saját hash-e.

**Comment by kabelnet2** [comment]
Szia, az invoiceHash nem kötődik az online számlához. Azt a NAV csak tárolja. Az értelme, feladata az, hogy a vevő ellenőrizni tudja, hogy az elektronikus formában neki elküldött számla (pl. pdf) ugyan az-e, amit mi kiáűllítottunk.
Vagyis minden kiállított számlához kell hash érték és a hash-t a számla nyomtatott formája (pl., pdf) alapján kell képezni.
Továbbá nem lehet valami nagyon bonyolult dolog, mert a partnerek (vevők) használják azt.
A partnernek az eredeti számlát és a módosító számlát küldöm, vagyis ezeknek a hash-ét kell megadnom valahol ahhoz, hogy a vevő ellenőrizni tudjon.

**Comment by NTCA-developer** [comment]
Szia @kabelnet2 !

Itt az idő, a 3.0-ban remélhetőleg kezeljük ezt az esetet. Azt nem tudom hogy számodra tetsző megoldást választottunk-e, de attól nem félek hogy magadban tartod hogyha nem. :) Ezt hadd zárjam le most, ha van észrevételed akkor nyiss újat kérlek!

**Comment by kabelnet2** [comment]
Ami a hash-t illeti, az szerintem így jó helyen van.
De közben emeltétek a tétet - legyen elektronikus számla a feladás.
Itt most megint elő kellene vezetnem az összes korábbi érvemet, hogy módosító gyűjtőszámla esetén ez így nem lesz jó. A módosító gyűjtőszámla egy darab papír, számlaszámmal, fizetési határidővel, végösszeggel. A könyveléshez ilyesmi kell. Ez így nem jelenik meg még a 3.0-ban sem. Persze össze lehet vadászni, bár a kerekítési dolgok bejöhetnek (forintra annyit kellene utalni, amennyi az eredeti, mondjuk úgy papír számla végösszege). Van olyan számlánk, ami 75 korábbi számlát módosít. Nem hiszem, hogy van könyvelő, aki szeretné 75 rész-számlából összevadászni az eredeti számlát.
De mindezt már megtárgyaltuk, tisztáztuk, hogy mások a ti és a mi szempontjaink.
