### ISSUE TITLE
[Q&A] számlakép letöltése

### ISSUE THREAD

**Issue by kovacspeter1** [nav-gov-hu/Online-Invoice#800]
Tud valaki módot arra, hogy az API-n keresztül letölthessem a számlaképet pl. pdf formátumban? Vagy azt csak a web-es felületen lehet? Esetleg curl-el?

**Comment by renced42** [comment]
Kedves @kovacspeter1 az Apin nem küldesz be számlát így számlaképet sem tudsz letölteni.
Számlát az Online Számlázó készít így csak onnan tudod a szánlát letölteni.

Egyéblént tervezzük, hogy készítünk XSLT alapján egy egységes számlakép megjelenítésére alkalmas megoldást, ami a letöltött XML-ből értelmezhető képet varázsol a síma user számára is. Ez nem lesz azonban számla még ettől.

**Comment by kovacspeter1** [comment]
Én bejövő számlákat töltök le, amik nem feltétlenül a NAV Online Számlázóval készültek, de gondolom, ugyanabból az adatbázisból és adatkészletből dolgozik. Ebből kiindulva esetleg az Online Számla Web-ről, az ő számlakép engine-jét használva, de PHP-ből, teljesen automatikusan, mondjuk curl-el meg tudnám csinálni? El lehet készíttetni vele egy olvasható, pl. pdf számlaképet egy bejövő számlától?

**Comment by renced42** [comment]
Kedves @kovacspeter1 
Jelenleg nincs ilyen lehetőség a letöltött XML olvasható formá ba örténő öntését (számlaképet) ebben az esetben magadnak kell elkészíteni.

**Comment by NTCA-supporter** [comment]
Van még kérdés @kovacspeter1 ?

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
