### ISSUE TITLE
Invalid security user / Helytelen authentikációs adatok

### ISSUE THREAD

**Issue by leczkat** [nav-gov-hu/Online-Invoice#801]
Jo napot kivanok, 
szamlacsomag kuldese soran kb. az elkuldott szamlak felenel Invalid security user hibajelentest kaptunk. Meg a 2-es valtozatot hasznaljuk, es a beallitason semmin sem valtoztattunk. 
Marcius 2-an 6:49:19 es 6:49:43 kozott kellett tortennie valaminek, mert azota nem tudunk egyetlen szamlat sem bekuldeni.

**Comment by NTCA-supporter** [comment]
Üdv @leczkat !
Ennyi info sajnos nem elég, kérlek küldj egy transactionId-t vagy valami azonosítót amire rá tudok nézni.
Semmi ilyen jellegű változás nem volt sem a teszt sem az éles környezeten, ami változtatni az authentikációt.

**Comment by leczkat** [comment]
3AD35TUPQKXA4M5J ez a szamla elment. Nem tudom jo lesz-e. 
Mar irtam a kollegaknak, nekem csak a webhez van hozzaferesem, de csak en tudok magyarul.

**Comment by leczkat** [comment]
Kedves NTCA-supporter, csak erdeklodni szeretnek, hogy elegendo e az elkuldott tranzakcios ID, vagy kuldjek mas adatot is?
Koszonom.

**Comment by NTCA-supporter** [comment]
Szia @leczkat !
Tudsz még esetleg küldeni friss adatot, ahol nem sikerült a beküldés?
Sajnos nem tudtam ezzel foglalkozni. Azóta esetleg megoldódott a probléma?
Üdv

**Comment by leczkat** [comment]
Hello, azóta megoldódott a probléma. Szerintünk a 3-as verzió miatt megváltozott a jelszó kódolása. Az átkódolás után újra kezdett működni a számlák exportja. Csak nem értjük, hogy történhetett minden export közben.
