### ISSUE TITLE
QueryInvoiceDigestRequest INBOUND Jogosultság szükséges!

### ISSUE THREAD

**Issue by rostasc3** [nav-gov-hu/Online-Invoice#802]
Szép napot kívánok!
 
Számlázó programunkban bejövő számla lekérdezést szeretnék készíteni a QueryInvoiceDigestRequest-tel. 
A kérés ez:
`<?xml version="1.0" encoding="UTF-8"?>
<QueryInvoiceDigestRequest xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns="http://schemas.nav.gov.hu/OSA/3.0/api">
	<common:header>
		<common:requestId>LP001615203980928</common:requestId>
		<common:timestamp>2021-03-08T11:46:20.938Z</common:timestamp>
		<common:requestVersion>3.0</common:requestVersion>
		<common:headerVersion>1.0</common:headerVersion>
	</common:header>
	<common:user>
		<common:login>rl585dxgqawcuyc</common:login>
		<common:passwordHash cryptoType="SHA-512">776565480545A623D10F392FA79ABF405F0F5B849F553373D9D17738BCB0D910E75B10992A67964993910638F1A85A4DE9DB31A4A380961A64A25D621DCE0F45</common:passwordHash>
		<common:taxNumber>56580763</common:taxNumber>
		<common:requestSignature cryptoType="SHA3-512">AACBA03EB5E70C650C5BF6981DE5513976903D51A6FF1FCB03139F2E6C34B25F9B90F62F6A3043388333E073C491EDBDA5E614A2F0D683E47475D98E09082479</common:requestSignature>
	</common:user>		
	<software>
		<softwareId>123456789123456789</softwareId>
		<softwareName>LSZAMLA</softwareName>
		<softwareOperation>LOCAL_SOFTWARE</softwareOperation>
		<softwareMainVersion>2</softwareMainVersion>
		<softwareDevName>Leichter Irodatechnika Kft</softwareDevName>
		<softwareDevContact>leichter@leichter.hu</softwareDevContact>
		<softwareDevCountryCode>HU</softwareDevCountryCode>
		<softwareDevTaxNumber>12491980</softwareDevTaxNumber>
	</software>	
	<page>1</page>
	<invoiceDirection>INBOUND</invoiceDirection>
	<invoiceQueryParams>
		<mandatoryQueryParams>		
			<invoiceIssueDate>
				<dateFrom>2021-02-02</dateFrom>
				<dateTo>2021-03-08</dateTo>
			</invoiceIssueDate>
		</mandatoryQueryParams>
	</invoiceQueryParams>
</QueryInvoiceDigestRequest>`

A kérés elmegy (éles és teszt környezetben is), de válaszként mindig a következőt kapom:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GeneralErrorResponse
	xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common"
	xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api"
	xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base"
	xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">
	<header>
		<requestId>LP001615203980928</requestId>
		<timestamp>2021-03-08T11:46:20.938Z</timestamp>
		<requestVersion>3.0</requestVersion>
		<headerVersion>1.0</headerVersion>
	</header>
	<result>
		<funcCode>ERROR</funcCode>
		<errorCode>FORBIDDEN</errorCode>
		<message>Jogosultság szükséges!</message>
	</result>
	<software>
		<softwareId>123456789123456789</softwareId>
		<softwareName>LSZAMLA</softwareName>
		<softwareOperation>LOCAL_SOFTWARE</softwareOperation>
		<softwareMainVersion>2</softwareMainVersion>
		<softwareDevName>Leichter Irodatechnika Kft</softwareDevName>
		<softwareDevContact>leichter@leichter.hu</softwareDevContact>
		<softwareDevCountryCode>HU</softwareDevCountryCode>
		<softwareDevTaxNumber>12491980</softwareDevTaxNumber>
	</software>
</GeneralErrorResponse>`
Az "Online_Szamla_interfesz specifikacio_HU_v3.0.pdf" legutolsó verziójában sem találtam arra utaló nyomot, hogy milyen jogosultság szüksége ehhez a lekérdezéshez, esetleg nem adok meg egy szükséges paramétert? 
tudnának segíteni ebben?
Köszönettel
Rostás István

**Comment by rostasc3** [comment]
Sose írtam még ide kérdést, ezért lett ilyen kusza... Amikor beszúrtam az xml-emet még egészen jól nézett ki :-) Mindenesetre a lényeg a "Jogosultság szükséges!" válasz és annak az oka.

**Comment by fenyvessy** [comment]
@rostasc3 szerintem első körben annak a technikai felhasználónak a jogosultságait ellenőrizd (a NAV webes felületén a felhasználók menüpontban), amivel a lekérdezést csinálod, mert valószínűleg ott nincs engedélyezve a lekérdezés.

**Comment by NTCA-supporter** [comment]
Szia @rostasc3 !
A technikai felhasználónak, akivel a lekérdezést végzed kétféle lekérdező jogosultsága lehet, amit a webes felületen lehet beállítani.
Ha a Saját számlák lekérdezése joga van, mint a te esetedbe, akkor csak a kiállítói oldalt láthatja és csak azokat a számlákat, amik általa lettek kiállítva.
Ha a Számlák lekérdezése joga van, ami a bővebb, akkor az eladó összes ki- és bejövő számláját láthatja.

Így látatlanban ezt mondom, ha mégsem ez az akkor nézem tovább, de előbb próbálkozzatok ezzel.

Üdv

**Comment by rostasc3** [comment]
Köszönöm a gyors választ, keresgélem amit írtatok (ezen a felületen ritkán járok)!

**Comment by rostasc3** [comment]
Köszönöm szépen, ez volt a probléma!
üdv Mindenkinek!

**Comment by rostasc3** [comment]
.
