### ISSUE TITLE
Online Invoice Test Tool Build: 3.0 Proxy problema

### ISSUE THREAD

**Issue by robozb** [nav-gov-hu/Online-Invoice#803]
Sziasztok!

Az Online Invoice Test Tool Build: 3.0. ...-ben nem tudom megoldani ezt a problémát:

2021.03.08 20:43:13:9414 IP address:192.168.0.10
2021.03.08 20:43:13:9424 Target URL: https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3/tokenExchange
2021.03.08 20:43:13:9434 Setup POST method
2021.03.08 20:43:13:9444 Setup Accept param: application/xml
2021.03.08 20:43:13:9444 Setup content type: application/xml
2021.03.08 20:43:13:9454 Setup user agent
2021.03.08 20:43:13:9464 Reading XML file
2021.03.08 20:43:13:9484 UTF-8 encoding
2021.03.08 20:43:13:9484 Sending bytes:1214
2021.03.08 20:43:13:9494 Request length: 1214 byte
2021.03.08 20:43:15:8973 Proxy/URL support error occured! Check your Proxy or Server URL settings on the Misc. Settings tab or  ->A kérelmet megszakították: Nem sikerült létrehozni az SSL/TLS biztonságos csatornát.A kérelmet megszakították: Nem sikerült létrehozni az SSL/TLS biztonságos csatornát.

Az ég világon semmi sincs beállítva a Proxy-nál

Előre is köszi!

**Comment by robozb** [comment]
Szerintem átemelt egy raklap beállítást a 2-es verzióból. Valahogy be lehet tölteni a default értékeket?

**Comment by renced42** [comment]
Kedves @robozb 
A TLS version beállítás-t 1.2-re kell állítani.

**Comment by robozb** [comment]
> Kedves @robozb
> A TLS version beállítás-t 1.2-re kell állítani.

Köszönöm szépen, ez megoldotta!
