### ISSUE TITLE
CryptoType setCryptoType

### ISSUE THREAD

**Issue by robozb** [nav-gov-hu/Online-Invoice#804]
Sziasztok! 

A CryptoType setCryptoType értékeit hol lehet megtalálni?

Millió köszönet!

**Comment by NTCA-supporter** [comment]
Szia @robozb !
https://github.com/nav-gov-hu/Online-Invoice/blob/master/src/schemas/nav/gov/hu/OSA/CHANGELOG_3.0.md#311-k%C3%B6telez%C5%91-api-m%C3%B3dos%C3%ADt%C3%A1sok

Üdv

**Comment by NTCA-supporter** [comment]
Van még kérdés @robozb ?

**Comment by robozb** [comment]
@NTCA-supporter  köszönöm, nem!
