### ISSUE TITLE
Technikai érvénytelenítés annulmentReference schema_violation error [DEV support]

### ISSUE THREAD

**Issue by lkiss-nf** [nav-gov-hu/Online-Invoice#805]
Sziasztok!

Szeretnék segítséget kérni a következő hiba megértésében:

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[x] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[x] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
ManageAnnulment requestId: NFTC202103090837541402
QueryTransactionStatus requestId: NFTC202103090838211403
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
A technikai érvénytelenítés tesztelésekor az elküldött invoiceAnnulment tag értéke dekódolva:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<InvoiceAnnulment xmlns="http://schemas.nav.gov.hu/OSA/3.0/annul">
    <annulmentReference>2020/147657/7</annulmentReference>
    <annulmentTimestamp>2021-03-09T08:37:54.017Z</annulmentTimestamp>
    <annulmentCode>ERRATIC_DATA</annulmentCode>
    <annulmentReason>Test annulment reason</annulmentReason>
</InvoiceAnnulment>
```
Látszólag megegyezik a példa manageAnnulment.xml-ben található invoiceAnnulment formátumával, státusz lekérdezéskor mégis a következő hibát kapom:
```
<technicalValidationMessages>
	<ns2:validationResultCode>ERROR</ns2:validationResultCode>
	<ns2:validationErrorCode>SCHEMA_VIOLATION</ns2:validationErrorCode>
	<ns2:message>XML contains on line: [3] and column: [25] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element 'annulmentReference'. One of '{"http://schemas.nav.gov.hu/OSA/3.0/annul":annulmentReference}' is expected.]</ns2:message>
</technicalValidationMessages>
<technicalValidationMessages>
	<ns2:validationResultCode>ERROR</ns2:validationResultCode>
	<ns2:validationErrorCode>SCHEMA_VIOLATION</ns2:validationErrorCode>
	<ns2:message>Xml validation failed</ns2:message>
</technicalValidationMessages>
```

Az annulmentReference tag értékével lenne gond vagy esetleg formailag hibás a kérés?

Köszönettel,
lkiss-nf

**Comment by NTCA-supporter** [comment]
Szia @lkiss-nf !
Szerintem összekeveredtek a dolgok.
Én úgy látom, hogy amit említesz beküldést, az rendben lement, viszont az említett lekérdezés nem arra vonakozik, mint ami a beküldés.

Az említett annul beküldés transactionId 3ANHN8C16BDFVRY4 de te a 3AMGDXE8BCXFXN13 transaction-t kérdezed le, tehát ezek nincsenek párban.
Üdv

**Comment by lkiss-nf** [comment]
Valóban egy korábbi hibás teszt kavarta össze a státusz lekérdezést, köszönöm a segítséget!
