### ISSUE TITLE
Online Invoice Test Tool Build: 3.0 ... dirindex hiba

### ISSUE THREAD

**Issue by robozb** [nav-gov-hu/Online-Invoice#806]
Kedves Közösség!

Ezzel mit lehet kezdeni?

2021.03.09 13:21:02:4758 .dirindex file doesn't exist!

Köszönöm szépen!

**Comment by renced42** [comment]
Kedves @robozb 
A Onliner Invoice Test Toolnak van saját repoja
https://github.com/nav-gov-hu/Online-Invoice-Test-Tool. Kérlek ide írd ezzel akpcsolatos kérdéseid :) Köszi!

**Comment by robozb** [comment]
OK, köszönöm!

**Comment by robozb** [comment]
https://github.com/nav-gov-hu/Online-Invoice-Test-Tool/issues/6

**Comment by renced42** [comment]
Kedves @robozb 
Zárd az Issuet, kérlek.
