### ISSUE TITLE
[FEATURE] CryptoType ellenőrzés

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#808]
CryptoType-ba nem valid adatokat küldenek be, ellenőrzés kellene rá.
Minimálisan "cryptoType" alapján legalább a "value" hosszra kellene ellenőrizni. (Másra lehetséges egyáltalán?)

Számla letöltésnél (éles rendszeren) most olyan cryptoType="SHA3-512" mellé olyan valuet kaptunk, ami valójában xml bináris base 64 kódolás első 512 karaktere. Egyértelműen probléma és megfogható lenne még feltöltésnél.

Köszönöm.

**Comment by renced42** [comment]
Kedves @EPluribusUnum 
A cryptoTypera van ellenörzés, ha nem jó értéket adsz meg visszajön rá a hibaüzenet.

pl:
 <ns2:result>
    <ns2:funcCode>ERROR</ns2:funcCode>
    <ns2:errorCode>INVALID_PASSWORD_HASH_CRYPTO</ns2:errorCode>
    <ns2:message>Érvénytelen jelszó hash algoritmus!</ns2:message>
  </ns2:result>


Tudnál példát küldeni, pontosan miről van szó?

**Comment by EPluribusUnum** [comment]
@renced42 , nem a "cryptoType" a hibás, hanem a "value".

Éles rendszer transactionId : 3ANG5PVBYYU6JWSG

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !
Értem a problémádat, és valahol jogos is.
A 3.0-ban bevezetett completenessIndicator jelölővel beküldött számláknál ellenőrizzük nem csak a hash hosszát, de az értékét is. 
Ez lenne hivatott validálni, hogy az ilyen számláknál csak jó hash-t fogadjunk be.
Viszont a completenessIndicator = false esetekben a electronicInvoiceHash csak egy opcionális mező, így arra nem lenne célszerű validálni.
Üdv

**Comment by omachtandras** [comment]
@NTCA-supporter : egy warningot sem érne meg esetleg?

**Comment by NTCA-supporter** [comment]
Sziasztok!

Utánakérdezek, hogy érdemes-e erre WARN-t dobni, de nem sok esélyt látok rá egy teljesen opcionális adatra.

Üdv
