### ISSUE TITLE
[Q&A] Test environment communication

### ISSUE THREAD

**Issue by lazaralexandra** [nav-gov-hu/Online-Invoice#809]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
is it possible to check if they have any new restrictions in place for requests coming in from external urls?
Tegnap kb. délután 3 óta teszt rendszerbe nem tudunk számlát küldeni. Van esetleg valami korlátozás azóta, ha external url-ről küldenénk be számlákat?

Köszönjük.

**Comment by lazaralexandra** [comment]
Fontos lenne SOS tudni a kérdésre a választ, mert szeretnénk befejezni a tesztelést, hogy át tudjunk állni 3.0-ra éles rendszerben is!
Adószámot is megadom, ahonnan akarjuk küldeni adatokat: 11222149-2-14.
Köszönöm.

**Comment by renced42** [comment]
Kedves @lazaralexandra 
Nincs ilyen korlátozás.
Mit jelent a "nem tudunk beküldeni"?

**Comment by lazaralexandra** [comment]
Olyan mintha valami blokkolná a post callt NAV felé. Csütörtök 3 után jelentkezett a probléma minden előzmény nélkül.
Ezt kaptam a fejlesztőktől:
we are facing issues while trying to hit 
https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3/tokenExchange from mule. We just wanted to get a confirmation from HTA that nothing has changed at their end related to certificates

**Comment by renced42** [comment]
Kedves @lazaralexandra 
Nem történt változás jó lenne látni a hibaüzenetet illetve a hibát.
Érdemes lenne egy trace route-ot csinálni, hogy hol akad el a kommunikáció.
Mindenesetre a NAV nem blokkol IP címeket a fenti szolgáltatásokon.

**Comment by lazaralexandra** [comment]
Közben kiderült, hogy futott egy olyan hálózati biztonsági patch ami Mulesoft oldalon blokkolta azokat a hívásokat, ami külső címre hivatkozott. Úgyhogy megoldódik a probléma. Köszönöm.
