### ISSUE TITLE
[Q&A]batchInvoice xsd

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#81]
Korábban szó volt arról (itt egy issue tárgyalása során), hogy a batchInvoice-ot módosítjátok, hogy az tényleg batch invoice legyen, vagyis legalább két tag kötelező.
Az aktuális (bár ki tudja...) xsd-ben nincs ez a módosítás, ott 1..* a számosság.
Ezt köszönöm, ha lehet most már maradjon is így, mert így nem kell ellenőrizgetni, hány számla módosul és elágazni 1 vagy több alapján.

**Comment by NTCA-developer** [comment]
Igazság szerint ez a módosítás már belekerült a véleményezési időszak elején a sémába, de visszacsináltuk amikor elkezdtük implementálni a batchInvoice-os beküldést. Készülnünk kell arra az esetre is, ha a batchInvoice alatt más-más vevő van, noha gazdaságilag ilyennek nem szabadna lennie. Amikor ez megtörténik, akkor vevői oldalról lekérdezve a batchInvoice-os számlaszámot csak azokat a batchIndexeket adhatjuk vissza, ami ténylegesen a vevőé, ekkor viszont már nem garantálható a 2...* számosság, a lekérdezés eredménye nem volna valid a saját sémánkra.

Számodra kicsit rosszabb hír talán, hogy ez az ellenőrzés nem megszűnt, hanem felköltözött a szolgáltatás rétegbe, ld BATCH_INVOICE_CARDINALITY_ERROR hibakód az IF doksi 3.3.1 fejezetében.
