### ISSUE TITLE
Getting Error while trying to submit XML invoice

### ISSUE THREAD

**Issue by khimth** [nav-gov-hu/Online-Invoice#810]
Hi,

I am getting below error when trying to submit invoice using v3 of API.

Example XML:

`<customerInfo>
<customerVatStatus>DOMESTIC</customerVatStatus>
<customerVatData>
<customerTaxNumber>
<base:taxpayerId>XXXXXX</base:taxpayerId>
<base:vatCode>2</base:vatCode>
<base:countyCode>02</base:countyCode>
</customerTaxNumber>
</customerVatData>
<customerName>XXXXXXXX</customerName>
<customerAddress>
<detailedAddress>
<base:countryCode>HU</base:countryCode>
<base:postalCode>1239</base:postalCode>
<base:city>Budapest</base:city>
<base:streetName>XXXXX.</base:streetName>
<base:publicPlaceCategory>.</base:publicPlaceCategory>
</detailedAddress>
</customerAddress>
</customerInfo>`

**Error**:

`Error: simple type 'CustomerVatStatusType', attribute 'base': The QName value '{http://schemas.nav.gov.hu/NTCA/1.0/common}AtomicStringType15' does not resolve to a(n) simple type definition. `

**Comment by renced42** [comment]
Dear @khimth 

Please read #539 and https://github.com/nav-gov-hu/Online-Invoice/blob/master/src/schemas/nav/gov/hu/OSA/CHANGELOG_3.0.md english section.

I think your XML header not correct. You must define the namespace of common.xsd in the header of your XML.

**Comment by khimth** [comment]
Dear @renced42,

Thank you for your response. I have manage to fix the issue now.

However I have 1 concern, sometimes API end-points don't return responses and it looks like it doesn't work.

Is this only in test version of API ?

Your help will be appreciated.


Thank You

**Comment by renced42** [comment]
Dear @khimth 

Yeah, sometime we have maintenance break, generally after working hour (in Hungarian time).
It can be on PROD and TEST environment too.

**Comment by khimth** [comment]
Thanks @renced42 for your feedback, But in test environment it's happens regularly.

**Comment by renced42** [comment]
Dear @khimth 

If you send some test requestid we can check it.

**Comment by khimth** [comment]
Dear @renced42, 
Thank you for your help. I think its working fine now.
