### ISSUE TITLE
API 3: Token Exchange: Bad Request?! 

### ISSUE THREAD

**Issue by robozb** [nav-gov-hu/Online-Invoice#812]
Sziasztok!

Ez vajon mit jelent?

2021.03.12 10:57:05:3934 XmlPrefix/common:header
2021.03.12 10:57:05:3934 Add XML node to request:header
2021.03.12 10:57:05:3934 Add XML element to request:requestId - RIDNp3Vv8Li6Ch1
2021.03.12 10:57:05:3934 Add XML element to request:timestamp - 2021-03-12T09:57:05.377Z
2021.03.12 10:57:05:3934 Add XML element to request:requestVersion - 3.0
2021.03.12 10:57:05:3934 Add XML element to request:headerVersion - 1.0
2021.03.12 10:57:05:3934 Add XML node to request:user
2021.03.12 10:57:05:3934 Add XML element to request:login - e4aupkuyvqrk5yv
2021.03.12 10:57:05:3934 Add XML element to request:passwordHash - 94FC66501EC8F1B6B6CE99364B5382280A69843D56DAD0E98902F149DAD3359BE602490D01831E1F7F5FCCEF5887E46B19098255F76B4249030466A374C93EAB
2021.03.12 10:57:05:3934 Add XML element to request:taxNumber - 62635927
2021.03.12 10:57:05:3934 Signature RID:RIDNp3Vv8Li6Ch1
2021.03.12 10:57:05:3934 Signature DATE string:20210312095705
2021.03.12 10:57:05:3934 Signature XML sign key string:e4aupkuyvqrk5yv
2021.03.12 10:57:05:3934 CRC32:
2021.03.12 10:57:05:3934 Requestsignature literal:RIDNp3Vv8Li6Ch120210312095705e4aupkuyvqrk5yv
2021.03.12 10:57:05:3934 SHA3-512 input:RIDNp3Vv8Li6Ch120210312095705e4aupkuyvqrk5yv
2021.03.12 10:57:05:3934 Add XML element to request:requestSignature - 87D1048FC31ECFE8E1EF78D05F30D8BAD991F4885FA11F4F7728BBA93AC1F2D8B9FA4C252C87327CEC3017457774C22F68B1ADF09892B47EBF5795E968417A77
2021.03.12 10:57:05:3934 Add XML node to request:software
2021.03.12 10:57:05:3934 Add XML element to request:softwareId - 123456789012345678
2021.03.12 10:57:05:3934 Add XML element to request:softwareName - NAV Online Invoice Tester
2021.03.12 10:57:05:3934 Add XML element to request:softwareOperation - LOCAL_SOFTWARE
2021.03.12 10:57:05:3934 Add XML element to request:softwareMainVersion - 3.0
2021.03.12 10:57:05:4094 Add XML element to request:softwareDevName - Roboz Béla
2021.03.12 10:57:05:4094 Add XML element to request:softwareDevContact - info@webfocus.hu
2021.03.12 10:57:05:4094 Add XML element to request:softwareDevCountryCode - HU
2021.03.12 10:57:05:4094 Add XML element to request:softwareDevTaxNumber - 62635927
2021.03.12 10:57:32:7524 IP address:192.168.100.159
2021.03.12 10:57:32:7524 Target URL: https://api-test.onlineszamla.nav.gov.hu/invoiceService/v3/tokenExchange
2021.03.12 10:57:32:7524 Setup POST method
2021.03.12 10:57:32:7524 Setup Accept param: application/xml
2021.03.12 10:57:32:7524 Setup content type: application/xml
2021.03.12 10:57:32:7524 Setup user agent
2021.03.12 10:57:32:7524 Reading XML file
2021.03.12 10:57:32:7524 UTF-8 encoding
2021.03.12 10:57:32:7524 Sending bytes:1461
2021.03.12 10:57:32:7524 Request length: 1461 byte
2021.03.12 10:57:33:5493 Status code:Bad Request
2021.03.12 10:57:33:5493 Response length: 1121 byte
2021.03.12 10:57:33:5650 Not found element in the returned XML! Az objektumhivatkozás nincs beállítva semmilyen objektumpéldányra.

Köszönöm szépen!

**Comment by robozb** [comment]
Kérés:

<?xml version="1.0" encoding="UTF-8"?>
<TokenExchangeRequest xmlns="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common">
<common:header>
<common:requestId>RIDFs5Zd1Dx8Ms1</common:requestId>
<common:timestamp>2021-03-12T09:31:26.975Z</common:timestamp>
<common:requestVersion>3.0</common:requestVersion>
<common:headerVersion>1.0</common:headerVersion>
</common:header>
<common:user>
<common:login>e4aupkuyvqrk5yv</common:login>
<common:passwordHash cryptoType="SHA-512">94FC66501EC8F1B6B6CE99364B5382280A69843D56DAD0E98902F149DAD3359BE602490D01831E1F7F5FCCEF5887E46B19098255F76B4249030466A374C93EAB</common:passwordHash>
<common:taxNumber>62635927</common:taxNumber>
<common:requestSignature cryptoType="SHA3-512">C6A7637978EF51671B82D95A6F4F3C201095BC8FFD6B5CC8B4FE075587D4FB60449170B062A94B2632410D103C08C4560B42CA0C8DE5130260EC4F85DC5F3B98</common:requestSignature>
</common:user>
<software>
<softwareId>123456789012345678</softwareId>
<softwareName>NAV Online Invoice Tester</softwareName>
<softwareOperation>LOCAL_SOFTWARE</softwareOperation>
<softwareMainVersion>3.0</softwareMainVersion>
<softwareDevName>Roboz BĂ©la</softwareDevName>
<softwareDevContact>info@webfocus.hu</softwareDevContact>
<softwareDevCountryCode>HU</softwareDevCountryCode>
<softwareDevTaxNumber>62635927</softwareDevTaxNumber>
</software>
</TokenExchangeRequest>

**Comment by robozb** [comment]
Válasz:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
`<ns2:GeneralErrorResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">`
`  <header>`
`    <requestId>RIDFs5Zd1Dx8Ms1</requestId>`
`    <timestamp>2021-03-12T09:31:26.975Z</timestamp>`
`    <requestVersion>3.0</requestVersion>`
`    <headerVersion>1.0</headerVersion>`
`  </header>`
`  <result>`
`    <funcCode>ERROR</funcCode>`
`    <errorCode>INVALID_REQUEST_SIGNATURE</errorCode>`
`    <message>Érvénytelen kérés aláírás!</message>`
`  </result>`
`  <ns2:software>`
`    <ns2:softwareId>123456789012345678</ns2:softwareId>`
`    <ns2:softwareName>NAV Online Invoice Tester</ns2:softwareName>`
`    <ns2:softwareOperation>LOCAL_SOFTWARE</ns2:softwareOperation>`
`    <ns2:softwareMainVersion>3.0</ns2:softwareMainVersion>`
`    <ns2:softwareDevName>Roboz Béla</ns2:softwareDevName>`
`    <ns2:softwareDevContact>info@webfocus.hu</ns2:softwareDevContact>`
`    <ns2:softwareDevCountryCode>HU</ns2:softwareDevCountryCode>`
`    <ns2:softwareDevTaxNumber>62635927</ns2:softwareDevTaxNumber>`
`  </ns2:software>`
`</ns2:GeneralErrorResponse>`

**Comment by robozb** [comment]
A kérést az "Online Invoice Test Tool Build: 3.0 ..." állítja elő

**Comment by renced42** [comment]
Kedves @robozb 
Ha az utolsó sor jelentésére vagy kíváncsi az azt jelenti, hogy a program nem tudta a válaszból kiolvasni a tokent.
Ha a válasz hibaüzenetre gondolsz akkor pedig azt, hogy az aláírókulcs nem jól van megadva.

**Comment by robozb** [comment]
Kedves @renced42!

Megakadtam az "Online Invoice Test Tool" használatában. Úgy látom mindent jól paraméterezk fel, mégis ez a hibaüzenet :( 

Nincs bármi tipped, hogy hogyan tovább? Melyek a legilletékesebb idevonatkozó dokumentumok? 

Nagyon köszönöm!

**Comment by renced42** [comment]
Kedves @robozb 
Mint írtam, biztosan az aláíró kulcs a rossz.

Az általad bemásolt logban látszik is hogy az aláírókulcs megegyezik a login névvel ami biztosan nem jó, így azt ki kell javtani.

2021.03.12 10:57:05:3934 Add XML element to request:login - e4aupkuyvqrk5yv
2021.03.12 10:57:05:3934 Signature XML sign key string:e4aupkuyvqrk5yv

**Comment by robozb** [comment]
Kedves @renced42!

Nagyon köszönöm, máris nézem!

**Comment by robozb** [comment]
Kedves @renced42!

Szuper, így már működik!

Üdv: Béla
