### ISSUE TITLE
[DEV support] REQUEST_ID_NOT_UNIQUE probléma

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#813]
"REQUEST_ID_NOT_UNIQUE : A megadott kérés azonosítója már létezik!"
requestId: 2021031211354368KB11476LBR

A saját logjainkban csak egy kérés látszódik erre a requestId-re, egy QueryInvoiceDataRequest hívás (timestamp : 2021-03-12T12:47:39.995Z)

Szeretném tudni hogy NAV oldalon (Teszt környezet) milyen kérések látszódnak ezzel a requestId-vel.

Köszönöm.

**Comment by NTCA-supporter** [comment]
Kedves @EPluribusUnum !

A teszt környezeten nem találtam ilyen requestId-jú kérést.

**Comment by EPluribusUnum** [comment]
@NTCA-supporter , köszi, akkor zárom. Élesre van már ilyen korábbi bejelentésem a nav.gov.hu oldalon, arra várom a visszajelzést.
(Az egyik teszelő nem a teszt környezetben dolgozott)
