### ISSUE TITLE
Case?

### ISSUE THREAD

**Issue by robozb** [nav-gov-hu/Online-Invoice#814]
Sziasztok!

Honnan lehet tudni, hogy a PDF leírás szerint melyik "case"-t hiányolja a rendszer?

<message>XML contains on line: [83] and column: [41] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/data":reason}'. One of '{"http://schemas.nav.gov.hu/OSA/3.0/data":case}' is expected.]</message>

Köszönöm!

Üdv: Béci

**Comment by connorhu** [comment]
Abban a sorban és oszlopban milyen tartalom van?

**Comment by robozb** [comment]
Kedves @connorhu!

Azóta rájöttem, hogy az üzenet a számla XML-jére vonatkozik, abban az XML-ben kell elemezni a sort és oszlopot!

Köszönöm szépen!
