### ISSUE TITLE
[Q&A] queryInvoiceDigest karakterkészlet

### ISSUE THREAD

**Issue by ballonyi** [nav-gov-hu/Online-Invoice#815]
A teszt környezetben queryInvoiceDigest kérésre az alábbi response-t kaptam. A két számla kiállítója ugyanaz, mindkettőt a NAV E-Invoice alkalmazásával rögzítették fél óra sem telt el a két számla kiállítása között. Mégis az egyik invoiceDigest-nél jó a karakterkészlet a másiknál nem. (a kiszolgáló node-ok nem egységesen vannak paraméterezve?) 

![queryInvoiceDigest_charset](https://user-images.githubusercontent.com/50325477/111468592-05c16700-8726-11eb-91c4-e874879b1fa5.jpg)

**Comment by NTCA-supporter** [comment]
Szia @ballonyi !
Küldj kérlek egy requestId-t.
Nincs ilyen különbözőség, így nem kellene, hogy probléma legyen.
Adatbázisban ugyanaz a két karakter van letárolva, azt megnéztem.
Üdv

**Comment by ballonyi** [comment]
QIDG_000000056057

Köszönöm

**Comment by NTCA-supporter** [comment]
A többi számlánál ahol ugyanez az eladó, mit látsz?
A log és DB alapján is ugyanazokat a karaktereket adjuk vissza.
Üdv

**Comment by ballonyi** [comment]
Nálam volt a hiba, bocs.
