### ISSUE TITLE
[FEATURE] Lehetséges állandó default xmlns és prefixek használata a response xml fájlokban?

### ISSUE THREAD

**Issue by Szilikatipari** [nav-gov-hu/Online-Invoice#816]
v3.0 által visszaküldött válasz XML fájlokban (egyelőre csak QueryTaxpayerResponse és GeneralErrorResponse ellenőrzésénél tartok) véletlenszerűen változik a default xmlns (vagy a common vagy az api) és ez szerint kerül ns2 kiosztásra. 

Ha megoldható , kérésem az lenne, hogy a default xmlns mindig a gyökér, fenti esetekben az "api" legyen és a prefixek neve legyen állandó, utalva a forrás XSD-re pl "common", "base". 

Lehet, hogy én leszek az egyetlen akinek a fenti helyzet problémát jelent? Ennek oka, hogy egy az apám által, 30 éve clipperben, kizárólag saját használatra és ezért maximálisan családi kisvállalkozásunk igényeihez igazított programhoz fejlesztek számla adat bejelentő kiegészítőt Delphi7 segítségével. Delphi7-ben nem találtam megoldást az xmlns prefixek kezelésére, ezért kénytelen vagyok statikusan megoldani a v3.0 igényeit.  Apám is hobbi programozó volt, én is az voltam/vagyok, nincs forrás és szellemi kapacitás fejlesztőrendszert váltani. Kerestünk alternatívát kereskedelmi forgalomban, nem is találtunk megfelelőt és nem is vállaják/ megfizethetetlen olyan mértében az igényekhez szabni mint a jelenlegi régi clipper program. Bízom benne, hogy tudják orvosolni a problémát, köszönettel: Antal Gábor

**Comment by topybear** [comment]
Azt már az elején jelezték, hogy ezek nem lesznek fixek.
Csak így a partszélről - ez nem segít rajtad?
http://codeverge.com/embarcadero.delphi.xml/parse-xml-with-namespace/2031331

**Comment by Szilikatipari** [comment]
Köszönöm Topybear! Teljesen használható.
