### ISSUE TITLE
[FEATURE] metrics API (új) státusz függvény

### ISSUE THREAD

**Issue by EPluribusUnum** [nav-gov-hu/Online-Invoice#817]
A jelenlegi metrics API nem ad egyértelmű választ arra hogy épp melyik szolgáltatás nem fut. A NAV vállaljon a rendszeréért felelősséget és legyen képes egyértelmű igen/nem választ adni arra hogy valami megy-e, vagy le van kapcsolva.
Jelenleg minden kliensnek magának kell(ene) értelmeznie a visszaadott statisztikai adatokat. Ennek így nem sok értelme van. 
Olyan függvény kellene, ami egyetlen hívásra egy válaszban visszaadja hogy melyik függvényhívások vannak lekapcsolva.

Köszönöm.

**Comment by NTCA-supporter** [comment]
Szia @EPluribusUnum !
Ezt zárom, mert a #408 erről szól.
Üdv
