### ISSUE TITLE
[Q&A] ManageInvoiceRequest SCHEMA_VIOLATION header hiba

### ISSUE THREAD

**Issue by kovacssz84** [nav-gov-hu/Online-Invoice#818]
Tisztelt Support!

ManageInvoiceRequest beküldése után a státusz lekérdezésre az alábbi hibát kapjuk vissza. Nem értem, hogy pontosan hol lehet a hiba. A hibaüzenet alapján olyan mintha egy sima <header> taget látna és <common:header>-t vár. A beküldött üzenetet jónak látom.

`<funcCode>ERROR</funcCode>
<errorCode>INVALID_REQUEST</errorCode>
<message>Helytelen kérés!</message></result><ns2:technicalValidationMessages><validationResultCode>ERROR</validationResultCode>
<validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
<message>Request body contains on line: [2] and column: [143] error: [cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/3.0/api":header}'. One of '{"http://schemas.nav.gov.hu/NTCA/1.0/common":header}' is expected.]`

A az alábbi üzenetet küldtük be:

transactionId:3B0KRO12KAUPROA6
requestId:10256

`'<ManageInvoiceRequest xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns="http://schemas.nav.gov.hu/OSA/3.0/api">
<common:header>
<common:requestId>10256</common:requestId>
<common:timestamp>2021-03-18T12:26:20.484Z</common:timestamp><common:requestVersion>3.0</common:requestVersion>
<common:headerVersion>1.0</common:headerVersion>
</common:header>
<common:user>
<common:login>z3cvnqqo1dwwnky</common:login>
<common:passwordHash cryptoType="SHA-512"></common:passwordHash><common:taxNumber>12951659</common:taxNumber>
<common:requestSignature cryptoType="SHA3-512"></common:requestSignature>
</common:user>
<software>
<softwareId>HU3456789123456789</softwareId>
<softwareName>NAV pt</softwareName>
<softwareOperation>LOCAL_SOFTWARE</softwareOperation>
<softwareMainVersion>1.0</softwareMainVersion>
<softwareDevName>ssai</softwareDevName>
<softwareDevContact>+3645</softwareDevContact>
</software>
<exchangeToken>7b901279-13ba-4c2b-a6d6-cf9a2c1caacb3B0KRNX8CKXL</exchangeToken>`

Köszönöm

**Comment by NTCA-supporter** [comment]
Úgy látom közben sikerült megoldani :)

**Comment by NTCA-supporter** [comment]
`<common:header>
		<common:requestId></common:requestId>
		<common:timestamp>2021-03-18T13:31:24.523Z</common:timestamp>
		<common:requestVersion>3.0</common:requestVersion>
		<common:headerVersion>1.0</common:headerVersion>
	</common:header>
	<common:user>
		<common:login></common:login>
		<common:passwordHash cryptoType="SHA-512"></common:passwordHash>
		<common:taxNumber></common:taxNumber>
		<common:requestSignature cryptoType="SHA3-512"></common:requestSignature>
	</common:user>`

Így próbáld.
Üdv

**Comment by kovacssz84** [comment]
Én leszek a béna, de nem látom a különbséget :( Pontosan mit kellene nézni, vagy máshogy írni?

**Comment by NTCA-supporter** [comment]
2 külön hiba is van:
- a queryTransactionStatus-nál a requestben a user és header tagek elől hiányzik a common: namespace jelölő (lásd fenti példám)
- a számla xml-ben a communityVatNumber nem lesz jó, nem pattern valid.

**Comment by kovacssz84** [comment]
Köszönöm a segítséget. Én minden áron a ManageInvoiceRequest-ben kerestem a hibát nem a queryTransactionStatus-nál. 
Zárható a jegy.
