### ISSUE TITLE
InvoiceData névtér

### ISSUE THREAD

**Issue by ballonyi** [nav-gov-hu/Online-Invoice#819]
Meglepve tapasztalom hogy míg a beküldött számla adatszolgáltatások névtere:
`<InvoiceData xmlns="http://schemas.nav.gov.hu/OSA/3.0/data" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/base">`

addig a getInvoiceData által visszaadott xml-é pedig:

`<InvoiceData xmlns="http://schemas.nav.gov.hu/OSA/3.0/data" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns3="http://invoice.dto.icon.icellmobilsoft.hu/invoice">`

Pluszban van egy `ns3` névtér. Ezek szerint a getInvoiceData által visszakapott base64 karaktersorozat nem az a base64 karaktersorozat, amelyet a szla. kibocsátó által beküldött adatszolgálatás tartalmaz. Az electronicInvoiceHash értéke viszont a beküldött adatszolgáltatásból származik, ami így nem egyezik meg a getInvoiceData által visszaadottból képzett értékkel. 

Számíthatok arra hogy ha egyszerűen kiveszem az XML-ből a `xmlns:ns3="http://invoice.dto.icon.icellmobilsoft.hu/invoice"` karaktersorozatot, akkor utána reprodukálható lesz a hash vagy esetleg más (szóköz, sortörés, stb) különbség is lehet? Miért van benne pluszban ez a névtér?

**Comment by ballonyi** [comment]
Ezek szerint csak én problémázom azon, hogy a letöltött xml és az electronicInvoiceHash nem passzol...

**Comment by NTCA-supporter** [comment]
Szia @ballonyi !
Azoknál a számláknál, ahol a 3.0-ban bevezetett completenessIndicator = true, ott mindig az eredeti, kliens által beküldött xml-t adjuk vissza, változtatás nélkül.
Ahol ez false, ott a letárolt adatokból állítjuk össze az adatokat, így igen, ott eltérhet a ns elnevezés, sortötés stb.
Üdv

**Comment by ballonyi** [comment]
Értem, köszönöm!
