### ISSUE TITLE
[Q&A]Interface napló

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#82]
Azt olvasom: "Minden 2.0-ás kérés és válasz letölthető a frontend Szolgáltatások/Interfész napló menüpontjában requestId és softwareId megadásával."
Nekem nem jelenik meg ilyen menüpont. Kell hozzá valamilyen beállítás?

**Comment by NTCA-developer** [comment]
Szia @kabelnet2 

Igen, külön jogosultság kell ha másodlagos felhasználóval nézed.

![kép](https://user-images.githubusercontent.com/49475983/68755239-77584500-0608-11ea-850a-39bcd15021e4.png)

Mindazonáltal sajnos el kell mondjam azt is, hogy 2.0-ás kérések esetén csak a 3 számla lekérdezés request-response adatait fogod látni jelenleg. (data, digest, check) Már kijavítottuk, de nincs kint a release még a környezetben.

**Comment by NTCA-developer** [comment]
Szia @kabelnet2 

A 2.4-es release tartalmazza ennek a javítását, kint van már a teszt környezetben január eleje óta. Ezt lezárom.
