### ISSUE TITLE
invoice Digest query módosítása/frissítése[Q&A]

### ISSUE THREAD

**Issue by bmatyi94** [nav-gov-hu/Online-Invoice#820]
Kedves Fejlesztők!

Szeretnék érdeklődni, hogy tervben van-e az invoiceDigest lekérdezés bővítése? Mivel már nem csak belföldi partnernek kiállított számlák jelentendőek, egy EU-s partner esetén a Digest válasz, nem tartalmazza az EU-s adószámot, mivel a customerTaxNumber a dokumentáció szerint csak 8 számjegyű lehet, így gondolom továbbra is ott a taxpayerId értéke kerül visszaadásra. Tervezik-e a Digest operációt kibővíteni a customerVatStatus elemmel, communityVatNumber, thirdStateTaxId-val? 

Valamint egyszerűsített számla esetén a digest visszaadná a summarySimplified értékeit is,( most csak a normál számla áfa és nettó értékeit adja vissza. De egy simplified eseténben a Digest a számla végösszegét nem)? 

Köszönöm előre is a válaszotokat.

**Comment by samoly** [comment]
Sziasztok!

A fenti kérdés fogalmazódott meg szinte szó szerint bennünk is.

Jelenleg a számla adatok letöltésekor számunkra a legtöbb esetben elegendő egy olyan listázás, ami a digest-ek adatait tartalmazza, és nem kell a details-t meghívnunk számlánként egyéb adat miatt.
Viszont ahogy fent bmatyi94 is írta, ez a külföldi cégek esetében most nem elég, mert a digest-en nincs semmilyen customer azonosító, amivel tudnánk hozzá hiteles partner adatokat lekérni bármilyen egyéb külső interface segítségével. Jelenleg az esetek  nagy részében csak emiatt kell meghívnunk a details-t, mert azon már van partner információ/azonosításra alkalmas id.

Várható ezzel kapcsolatban a jövőben QueryInvoiceDigest válasz (XSD) módosítás-kiegészítés?

Köszönöm!

**Comment by NTCA-supporter** [comment]
Sziasztok!

Nincs tervben api módosítás sajnos.
Az igényt felírtuk, ha esetleg a távoli jövőben hozzá kell nyúlni, akkor figyelembe vesszük.
Zárom az issuet.
Üdv
