### ISSUE TITLE
[Q&A] ITEM_AGGREGATION_MISMATCH figyelmeztetés

### ISSUE THREAD

**Issue by szako** [nav-gov-hu/Online-Invoice#821]
A 3.0-ban bevezetett új lehetőséggel élve, a dokumentáció **Nagyméretű számlákról történő adatszolgáltatás fejezetének** megfelelően alkalmazzuk a tételösszevonást. Akkor alkalmazzuk ezt, ha a számla XML tömörítetlen mérete 15MB fölé nőne és COMPRESSION_TOLERANCE_EXCEEDED validációs hibakódot kapnánk.

Tételösszevonással beküldött nagyméretű alapszámlára, nem tételösszevonással beküldött helyesbítő számla készítésekor az alábbi figyelmeztetést adja a NAV rendszere:

> **ITEM_AGGREGATION_MISMATCH**
> - A mergedItemIndicator értéke nem lehet „false”, ha a számlaláncban korábban „true” értéket vett fel.
> - Figyelmeztet, ha a beküldött számlához tartozó számlaláncban van olyan korábbi számla, ahol a mergedItemIndicator = true, de a számla mergedItemIndicator értéke false.

A hibaüzenetet értem, csak a logikáját nem. Az adatszolgáltatás során nem arra kéne törekedni, hogy minél jobban közelítsenek a beküldött adatok és a számla képe? A tételösszevonás egy technikailag kényszerű lépés, de a helyesbítőnél miért kellene összevontan küldeni, amikor mondjuk az eredeti 40e sorból csak pár sort helyesbítek? Elképzelhető, hogy a mostani figyelmeztetés később ez hibaüzenet lesz?

Köszönöm!

**Comment by NTCA-tax** [comment]
A logika a következő: amennyiben tételes adatszolgáltatás történik egy számláról, akkor annak módosítására több lehetőség is van. Az összevont adatszolgáltatásnál szintén vannak tételsorok, azonban azok valamilyen elv szerinti csoportosítást jelentenek. Amennyiben a kettőt összekevernénk, akkor könnyen kialakulhatna olyan adatfeldolgozási és adatelemzési probléma, amely az összevont adatszolgáltatás tételes módosítására lehet visszavezetni. Ezt lehetne egy mindkét oldalon bonyolult algoritmussal megoldani és az esetleges problémákra különböző warningokat és errorokat alkotni, ugyanakkor nem lenne túlságosan sok értelme. Egyrészt ezen nagyméretű adatszolgáltatások száma és aránya elenyésző, másrészt az összevont adatszolgáltatású számla tételes módosítása nem hordozna jelentős hozzáadott értéket a rendszer összessége számára.
