### ISSUE TITLE
[Q&A] MODIFICATION_INDEX_NOT_UNIQUE error message

### ISSUE THREAD

**Issue by ErvinRuben** [nav-gov-hu/Online-Invoice#822]
Dear Developer team,

We have an issue where we are getting the following error: MODIFICATION_INDEX_NOT_UNIQUE

Our case is the below:

We have submitted an invoice (document number 1)
We have submitted a correction (Document number 2, OriginalInvoiceNumber 1 & ModificationIndex 1)
We are submitting a second correction (Document Number 3, OriginalInvoiceNumber 1 & ModificationIndex 2) and this last document is getting the non unique error.

Please find below the tracing ID's pertaining to the test environment for your reference:
3B1VVQEEAR7NCTE7 (first correction, went through with 'Ok,warning')
3B1W6Z4SUJEN4LX8 (get aborted 'CONTENT')

Could you please investigate what could went wrong. Let me know if you woudl need any further details.

thank you in advance!

**Comment by NTCA-supporter** [comment]
Hi @ErvinRuben !
As I can see, the data report with 3B1VVQEEAR7NCTE7  transactionId contains a MODIFY invoice KGE3Stage and it's modificationIndex is 2.
That's why you get the error.
Br

**Comment by ErvinRuben** [comment]
Thank you for your swift response, apparently the issue indeed is with us.
