### ISSUE TITLE
[Q&A] countryCode regex

### ISSUE THREAD

**Issue by ballonyi** [nav-gov-hu/Online-Invoice#823]
A beküldött adatszolgáltatás ezt a vevő címet tartalmazza (additionalAddressDetail értékét elmostam):

```
<customerAddress>
	<ns2:simpleAddress>
		<ns2:countryCode>DE</ns2:countryCode>
		<ns2:postalCode>83043</ns2:postalCode>
		<ns2:city>Bad Aibling</ns2:city>
		<ns2:additionalAddressDetail>xxxxxxxxxxxxxxxx</ns2:additionalAddressDetail>
	</ns2:simpleAddress>
</customerAddress>
```

XSD validációs hibát kaptam:
```
XML   contains on line: [41] and column: [33] error: [cvc-type.3.1.3: The value   &apos;&apos; of element &apos;ns2:countryCode&apos; is not   valid.]
0XML contains on line: [41]   and column: [33] error: [cvc-pattern-valid: Value &apos;&apos; is not   facet-valid with respect to pattern &apos;[A-Z]{2}&apos; for type   &apos;CountryCodeType&apos;.]
```

Nem értem mit hiányol, megfelel a [A-Z]{2} regex-nek, és ISO 3166 alpha-2 szerinti érték.  
requestid=MNGI_000000712082 (éles)

(magyar címmel rendelkező számlák rendesen bemennek)

Köszönöm

```

**Comment by csandazoltan** [comment]
A hibaüzeneted szerint nincs a mezőben érték, mivel kötelező érték, ezért problémázik

Ha feloldod a html entitásokat akkor láthatod
Nem azzal van a baja, hogy 'DE', hanem hogy üres

> XML   contains on line: [41] and column: [33] error: [cvc-type.3.1.3: The value   '' of element 'ns2:countryCode' is not   valid.]
> 0XML contains on line: [41]   and column: [33] error: [cvc-pattern-valid: Value '' is not   facet-valid with respect to pattern '[A-Z]{2}' for type   'CountryCodeType'.]

**Comment by NTCA-supporter** [comment]
Így van, a probléma az, hogy üres értékkel küldted be. Szerintem amit bemásoltál az nem ez a tranzakció, de az élesre mi nem tudunk ránézni.
Kérlek nézz utána, hogy pontosan mi volt az invoceData xml-ben.
Üdv

**Comment by ballonyi** [comment]
_"Szerintem amit bemásoltál az nem ez a tranzakció,"_
Pedig a logom alapján ez az a tranzakció... Van helpdesk az éleshez, ahol meg tudják nézni hogy mi ment be?

**Comment by csandazoltan** [comment]
@ballonyi Jó sort nézünk? A supplierAddress-ben is van egy contryCode :)

**Comment by ballonyi** [comment]
_"Szerintem amit bemásoltál az nem ez a tranzakció,"_
Bocs, tényleg nem az a tranzakció volt. Benéztem. :(
