### ISSUE TITLE
[DEV support] INVALID_REQUEST_SIGNATURE 

### ISSUE THREAD

**Issue by lszoke66** [nav-gov-hu/Online-Invoice#824]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[x] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
MAGHU20210322104047
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Kedves Support!

A manageInvoice operációra INVALID_REQUEST_SIGNATURE választ kapok 3.0 teszt   környezetben.

A számla.xml valid, tokenExchange lefut hiba nélkül. 

Az XML előállításához ugyanazt a kódot használom, ami 2.0 éles környezetben hiba nélkül működik. 

Mi lehet a hiba ?

*Egyéb tartalom / Additional content*

**Comment by csandazoltan** [comment]
> A számla.xml valid

Csak az invoiceData ágat felelteted meg invoiceData.xsd-vel?

Mi a helyzet az egész kéréssel és a invoiceApi.xsd-vel?

Mert a V3-ban változott a requestSignature struktúrája és típusa is és ráadásul külön névtérbe is került!
Meg kell adni a titkosítás típusát is attribútumban
![image](https://user-images.githubusercontent.com/6756505/112098792-aa1e3000-8ba2-11eb-892f-caba3e09e762.png)

Ha beküldöd xsd megfeleltetés nélkül, akkor lehet így reagál rá a szerver

Ha megfelelsz mindegyik xsd-nek akkor nem mondtam semmit

**Comment by renced42** [comment]
Kedves @lszoke66 

Itt valami gyanús. A 3.0-s végpontra hiába küldesz 2.0 kód szerinti requestsignature-t, az nem lesz jó. Több okból sem. Egyrészt mert megváltozott az XSD szerkezet, másrészt kicsit változott a számítás is. Tehát vagy a végpontok vannak összekeverve és a tokenkérésed a 2.0-s végpontra megy még mindig, vagy a 3.0-s requestsignature számításod nem jó ami a 2.0-hoz képest változott.

**Comment by NTCA-supporter** [comment]
Szia @lszoke66 !

Önellenőrzés céljából:
Invalid request signature, actual:[18920B812AFE3FD3D15EAFE47AB4C37B244721EB4560CE2A398C4474A85C2038C82A2192D5E18BA5EDCBE410BBDF1164DEBA404C0F15DE7FC87072D760F391BB], expected:[CB7B18488A366D92703402B8F22C3C7CCFC2E5EE22D01A13DE1F6AA2EC54C98A105492CB53540B904FD3F9B99806C15AB5C35E473C1620AFC011AF8625534376]

Az xml ránézésre jónak tűnik, így a számítás során megy félre valami.
Üdv

**Comment by lszoke66** [comment]
Sziasztok, 
rosszul fogalmaztam ! A request signature **érték** kiszámításáshoz használjuk ugyanazt a  kódot, amit 2.0 -ban. Nem fedeztünk fel változást a dokumentációk összahasonlítása alapján! Mi változott ?

**Comment by renced42** [comment]
Kedves @lszoke66 

A fő változás, hogy SHA3-512-vel kell kalkulálni az értéket

**Comment by NTCA-supporter** [comment]
A számítás módszerében nem történt változás.
Egyedül a  cryptoType="SHA3-512" jött a képbe de azt jól küldöd.

**Comment by lszoke66** [comment]
Sziasztok, meg lett a hiba, köszönöm az együttműködést !
