### ISSUE TITLE
[DEV support]ManageInvoiceRequest operációt néha nem dolgozza fel a NAV rendszere?

### ISSUE THREAD

**Issue by EnokhSys** [nav-gov-hu/Online-Invoice#825]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[x] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
Három példa:
- 7ab2e0ba-f5f7-456d-a6e7-4449f128d98a3B3L03Q9AQ1E
- 7962938a-0cbc-46b0-bc7f-4e0bafd039583B3POUELLMHD
- 34632163-b401-4351-997f-9ea659d4fbc93B3LTFG3D1Q7

**A probléma rövid és tömör leírása / Clear and concise description of the problem**

Üdv Nektek!

Az egyik partneremnél a V3.0-ás motor tesztelése közben felfigyeltem arra, hogy néhány számlánál a ManageInvoiceRequest-re nem érkezik válasz, és a számlát lekérdezve úgy tűnik, hogy az be sem érkezett a NAV-hoz. Gondot nem okoz ez a hiba, mert ilyenkor automatikusan beküldésre kerül másodszorra is, csak gondoltam szólok, hogy érdemes lenne utánanéznetek a hibának. 
(A tesztelés során kb. 1800 db. számlát küldtem be; - 12 mp-ként 1 számlát, hogy ne torlódjanak egymásba, ezen belül pedig az operációk között legalább 1 mp-es időközt biztosítva, hogy ne legyen floodolás,)

**Comment by NTCA-supporter** [comment]
Szia @EnokhSys !
Ezek milyen azonosítók? RequestId?
Köszi

**Comment by EnokhSys** [comment]
Szia @NTCA-supporter,
ezer bocs, csak szimultánt játszom több feladatban és véletlenül a tokeneket másoltam be.
Szóval a problémás requestId-k:
- PHPH2176510720155613
- PHPH2176575520180725
- PHPH2176521720161901
Ezeken kívül van még kb. két-három, ha szükséged van rá, azokat is előbányászom. 
Köszi.

**Comment by NTCA-supporter** [comment]
Szia @EnokhSys !

Ez a probléma még jelen van? Ha nincs, kérlek zárd az issuet.

Üdv

**Comment by EnokhSys** [comment]
Szia @NTCA-supporter,

hasonlót nem találtam, csupán az egyik statusrequestre egy ilyen válaszüzenet érkezett 2021.08.02-án, 17:02-kor: 

"_upstream connect error or disconnect/reset before headers. reset reason: connection termination_"

Gondot nem okoznak, mert a rendszer automatikusan lekérdezte 1 óra múlva ismét a számlát, és akkor már minden rendben volt.

Zárom az issuet.
