### ISSUE TITLE
[Q&A] Előlegszámla és végszámla

### ISSUE THREAD

**Issue by ErvinRuben** [nav-gov-hu/Online-Invoice#826]
Sziasztok!

Negatív végszámla esetében tudnátok útmutatást adni, hogyan lehetséges az adatszolgáltatás. 

Példa tranzakció azonosító (teszt rendszerben): 

Előlegszámla: 3B9GPG9RFPG9B7XL

Végszámla: 3B9GRSO8L7GLGN1Q

Értelmezésünk szerint, nem kötelező az eredeti számlára vontakoztatni, tehát a végszámla nem tartalmazza az eredeti számlaszámot, dátumot még az árfolyamot sem, ettól függetlenül az adatszolgáltatás erre vontakozóan elutasításra került.

Lehetséges, hogy ezt csak az előlegszámla javításával rendezhető? Ez esetben kaphatunk némi útmutatást?

Köszönjük a segítségetek! Üdv!

**Comment by ErvinRuben** [comment]
Sziasztok! 

Van már esetleg valami tipp a fönti problémra?

Köszi előre is, nagyon leköteleztnétek!

Szép napot!

**Comment by fenyvessy** [comment]
@ErvinRuben, a NAV részéről korábban az volt ilyen esetben a hozzáállás, hogy nem lehet negatív végszámlád. Helyesbíteni kell az előlegszámlát, majd az előlegszámlára hivatkozva egy nullás végszámlát kell létrehozni.
Ha az adatszolgáltatás elutasításra került, akkor annak ott van benne az oka, az alapján tudsz elindulni. A konkrét ok ismerete nélkül csak ötletelni és tippelgetni lehetne...

**Comment by NTCA-tax** [comment]
@ErvinRuben sikerült megfejteni az error okát az error üzenet alapján?

**Comment by ErvinRuben** [comment]
> @ErvinRuben sikerült megfejteni az error okát az error üzenet alapján?

Nem igazán, valójában az nem teljesen világos, hogyan lehetséges a teljesítés negatív végszámla esetében és milyen kötelező adatok szükségesek.

A mi értelmezésünk alapján, ugyanazok az adatok szükségesek mintha egy jóváíró (credit note) esetében, vagyis szükségeltetik a vonatkoztatás az eredeti számlára, értsd előlegszámla.

Meg tudnátok ebben erősiteni, vagy netán cáfolni :)

Köszönöm előre is!

**Comment by NTCA-tax** [comment]
Negatív végösszegű számlát egyrészt nem szabadna kiállítani. Amennyiben több előleg fizetés történt, mint a teljesítés összege, akkor az előlegszámlát kell módosítani és ott visszaadni a vevőnek a túlfizetését. A végszámla végösszege így nullánál nem lehet kevesebb. Ugyanakkor önmagában a negatív végösszeg még nem kap errort, hanem warning üzenettel jár.

A végszámla viszont nem úgy működik, mint a módosító számla, tehát nem szükségszerű hivatkozni az előlegszámlára számlasorszámmal. Amennyiben mégis van számlasorszám hivatkozás, akkor azt az advanceOriginalInvoice mezőben lehet megtenni. Amennyiben ez a mező kitöltött, akkor a csomópont mindegyik mezőjét ki kell tölteni! Ennek elmulasztása esetén viszont biztosan error lesz a feldolgozás vége.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezzel kapcsolatban van még kérdés? Ha nincs, kérlek zárjátok.

Üdv

**Comment by ErvinRuben** [comment]
Helló! Lezártuk, köszönjük!

Üdv!
