### ISSUE TITLE
[Q&A] Hibás INCORRECT_HEAD_DATA_CUSTOMER_TAXPAYERID validáció?

### ISSUE THREAD

**Issue by DrotosTot** [nav-gov-hu/Online-Invoice#829]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[X] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[X] 3.0

**A requestId értéke / requestId value**
ManageInvoice: DEMID7YNTJJPoQbVggbzv
QueryTaxpayer: DEMID4QKmS45tCks5OZUm

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Beküldött számlára INCORRECT_HEAD_DATA_CUSTOMER_TAXPAYERID WARN érkezik. Vevő adószámát lekérdezve a taxpayerValidity=true.

*Egyéb tartalom / Additional content*

**Comment by zambodaniel** [comment]
Nálunk rengeteg ilyen WARN jön élesen is.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Teszt rendszeren meg tudnád ismételni a beküldést, hogy lássak friss logokat?
A teszt rendszeren egyébként nincs adózói törzs frissítés, így ott nincsenek naprakész adatok.
Élessel kapcsolatban itt nem tudunk segíteni, kérlek itt jelezzétek a problémát: https://www.nav.gov.hu/nav/e-ugyfsz/levelkuldes

Köszönöm

**Comment by DrotosTot** [comment]
> Teszt rendszeren meg tudnád ismételni a beküldést, hogy lássak friss logokat?
manageInvoice
requestId: DEMIDuWXu8Y3tgCoQLRSA
timestamp: 2021-04-07T07:08:20.000Z

queryTaxpayer
requestId: DEMIDc0gEhyWdkiZ8yeeZ
timestamp: 2021-04-07T07:08:50.000Z

Mi is köszönjük!

**Comment by NTCA-supporter** [comment]
Sziasztok!

Köszi az infot.
Egyrészt ahogy mondtam, a teszt környezet nincs sztinkronizálva az élő adatokkal, így az fentartásokkal kezelendő.

Másrészt: az adózó lekérdezőnél lévő taxpayerValidity és a WARN-nál lévő élőség ellenőrzés már feltételekkel fut a törzsadatokon, innen ered az anomália. A feltételeket egységesítjük, így nem lesz majd ilyen eltérés.

Addig maradjon nyitva az issue nyugodtan.

Üdv

**Comment by DrotosTot** [comment]
OK, köszönöm!
Minket a visszakapott, egymásnak ellentmondó válaszok jobban zavartak, mint maga a konkrét adószám érvényessége.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezzel kapcsolatban van még kérdés? Ha nincs, kérlek zárjátok.

Üdv

**Comment by zambodaniel** [comment]
Szia!

Kérdés szerintem nincs, de még mindíg eltérő eredmények jönnek a felületen és az adatszolgáltatás beküldésekor.
Hiába jelezzük a megfelelő csatornákon, nincs foganatja.

**Comment by NTCA-supporter** [comment]
Szia @zambodaniel !
Rendben. Holnap lesz egy éles telepítés, utána kérlek nézz rá és jelezz vissza, hogy fennáll-e még a probléma.
Köszi

**Comment by zambodaniel** [comment]
@NTCA-supporter , jó lett. Köszönjük!

**Comment by NTCA-supporter** [comment]
Rendben, köszi a visszajelzést, zárom az issuet. 
Üdv
