### ISSUE TITLE
[Q&A]Áfamentes számla minta 

### ISSUE THREAD

**Issue by Amn3s1a2018** [nav-gov-hu/Online-Invoice#83]
**Áfamentes számla minta**
Nem szerepel a példák között áfamentes tételt tartalmazó számla, ami majdnem érthető is, hiszen a jogszabály alapján (jelenleg) nem kell beküldeni azokat a számlákat ami csak ilyen tételt tartalmaz. Előfordulhat azonban, hogy az adómentes értékesítés együtt szerepel más 100 Ft áfát meghaladó eladással vagy az adózó úgy dönt, hogy minden számlát beküld.
A speciális esetek, amik külön mezőt kaptak (pl. vatOutOfScope) talán egyértelműek. Ahol kellett  biztosan megoldották a vatExemption kitöltését is, de mivel a struktúra akár azt is megengedi, hogy azonos eseteket különbözőképpen adjunk fel jó lenne ehez egy sorvezető.

**Comment by NTCA-developer** [comment]
Szia @Amn3s1a2018 

Köszi a felvetést, rákérdezek csinál-e a szakterület ilyen példa számlát.

**Comment by NTCA-developer** [comment]
Bevállalták, de csomó egyeztetésen át vezet az útja, szóval hamar ne várd. De lesz ilyen sample.

**Comment by Amn3s1a2018** [comment]
Nálunk jelenleg kézzel írnak szöveget az ilyen számlára, ezt kezdtük átalakítani, hogy az tétel áfájához kapcsolódóan adják meg és az ottani szöveget fogjuk ide is betölteni. Ha indulás előtt  megérkeznek a példák annak nagyon örülünk majd.
