### ISSUE TITLE
[Q&A] INVALID_INVOICE_REFERENCE STORNÓ számla beküldésekor

### ISSUE THREAD

**Issue by aszuts** [nav-gov-hu/Online-Invoice#830]
sziasztok!

Adott egy eleve hibás számla, aminek a beküldésére ezt kapom:
`ERROR: INVALID_VAT_DATA, A számlában megadott áfakulcs vagy áfaérték nem engedélyezett. TAG: InvoiceData/invoiceMain/invoice/invoiceLines/line/lineAmountsNormal/lineVatRate/vatPercentage`

A számla azért hibás, mert szerepel rajta 10%-os ÁFA kulcs. Nyilvánvalóan hibás a számla, de mivel már kiállítottam nem tudom másként javítani csak stornózással.

Stornó számla elkészült, amikor beküldöm adatszogáltatásra, akkor ezt kapom:
`ERROR: INVALID_INVOICE_REFERENCE, A módosítás vagy érvénytelenítés olyan okiratra hivatkozik, amire vonatkozóan nem történt adatszolgáltatás. TAG: InvoiceData/invoiceMain/invoice/invoiceReference/originalInvoiceNumber`

Az eredeti számlára is kaptam tranzakciós ID-t, ezért az is fel van dolgozva valamilyen szinten a NAV-nál.

Fejben sok esetet végigjátszottam, de mindig oda jutottam, hogy adatszolgáltatnom kell a stornó számlát is, különben a számla sorszám folytonosság megszakad.
Ha meg nem állítok ki stornó számlát, akkor a könyvelésen fog fennakadni a számla. Mint nyilvánvalóan rontott számla, amit javítani kell egy stornóval és újra kiállítani helyesen.

**Mi a helyes eljárás? Hogy kellene ezt kezelni?**

köszönöm

**Comment by NTCA-supporter** [comment]
Szia @aszuts !
Ilyen esetben, ha ERROR-t kapsz az alapszámlára, akkor azt nem mentjük le, nem kezeljük számlaként, ezért nem is tudsz rá beküldeni sztornó számlát.
Ilyenkor javítani kell az alapszámlát és azt újra beküldeni.
Üdv

**Comment by aszuts** [comment]
Köszönöm a gyors választ. Beszéltem a pénzüggyel is, azt mondták azért vezetnek róla jegyzőkönyvet is. Mert egy ellenőrzés során aggályos lehet, ha egy már kiállított számlát utólag módosítunk.
