### ISSUE TITLE
[Q&A] INVALID_REQUEST

### ISSUE THREAD

**Issue by sandorpaszti** [nav-gov-hu/Online-Invoice#831]
Levelet már írtam ezzel a referenciával: NAV e-553824
Sajnos nem tudjuk, hogy miért kapunk invalid request hibát.
Van lehetőség online módon figyelni, hogy mit küldünk be? Egyáltalán megérkezik-e rendesen a kérés a NAV oldalára?
A mi adószámunk: 22567671. SoftwareID: EGLBNL009761159B01. Fejlesztő adószáma: NL009761159B01.
Segítségüket előre is köszönöm!
Pászti Sándor
+36-20-9402077

**Comment by NTCA-supporter** [comment]
Kedves @sandorpaszti !
Egy requestId-t küldj kérlek, hogy a konkrét kérést be tudjam azonosítani.
Üdv

**Comment by sandorpaszti** [comment]
Kedves @NTCA-supporter !
Sajnos nincs requestID, az alkalmazás (Exact) transactionID mezője is üres...
Úgy látom, hogy az exchangetoken művelet az sikeres.
Illetve elvileg a hálózat is engedi a kapcsolatot, mert a NAV Online Test Tool-jával sikeresen tudok kéréseket beküldeni.
Hogyan tudnék meggyőződni arról, hogy tényleg eljut az alkalmazásból is a csomag a NAV-hoz?
Köszönöm!
Sanyi

**Comment by renced42** [comment]
Kedves @sandorpaszti 

Ha az Online Invoice Tool-t használod akkor kapcsold be a logolást, hogy mentse le.
A logban minden infó benne van.
Ha nincs TR ID az azt jelenti, hogy a beküldés sem sikeres.
A request ID-t a Request fülről kell kimásolni.

![image](https://user-images.githubusercontent.com/44041065/112498499-df837300-8d86-11eb-869f-abbcc7608308.png)

**Comment by NTCA-supporter** [comment]
@sandorpaszti sikerült haladni ezzel kapcsolatban?
Üdv

**Comment by sandorpaszti** [comment]
Kedves @NTCA-supporter!
Köszönöm a segítséget illetve az érdeklődést.
Időközben a szoftver (Exact) fejlesztője rámutatott arra a beállításra, ami megoldotta a problémát (a számlakészítést HTML formátumról PDF formátumra kellett állítani).
Köszönettel:
Sanyi
