### ISSUE TITLE
[Q&A] "Adóhatósági ellenőrzési adatszolgáltatás" XML és számla PDF-hez csatolt XML

### ISSUE THREAD

**Issue by JamborTimea** [nav-gov-hu/Online-Invoice#833]
Jó napot kívánok!

Két kérdéssel fordulok most Önökhöz:
1. Az„adóhatósági ellenőrzési adatszolgáltatás” során kapott XML-ben, hogyan kell lekezelni avatOutOfScope eseteket (ATK, EUD37,EUFADE,EUE,HO)? Azt itt megtalálható sémában nem találtam erre vonatkozó információt:
https://net.jogtar.hu/jogszabaly?docid=a1400023.ngm
A Záradékok résznél látok hivatkozást fordított adózásra, adómentességre és különbözet szerinti szabályozás, de azt nem tudom, hogy a fentebb felsorolt (1. pont) eseteket hová kell besorolni?

2. A számla PDF képéhez csatolt XML, lehet pont ugyanaz, mint amit az adatszolgáltatás során küldünk fel?

Ezt találtam és ez alapján gondolom, hogy lehetnek megegyezőek. Jól értelmeztem?

"Az elektronikus aláírás független az elektronikus számla formátumától, így akár PDF dokumentumon, vagy bármely más fájlformátumban előállított dokumentumon (például. XML) is elhelyezhető. A PDF fájlformátum alkalmas arra is, hogy ne csupán a számlaképet jelenítse meg, hanem számítógéppel könnyebben feldolgozható számlaadatot is hordozhat. Ekkor a PDF dokumentumhoz csatolásra kerül egy XML, CSV vagy bármely más fájlformátumú, gépileg értelmezhető adatállomány is. Ha az elektronikusan aláírt XML, vagy az elektronikusan aláírt PDF állomány mellett tájékoztatásként megküldött XML dokumentum az online számlaadat-szolgáltatáshoz használt séma alapján készült, az megkönnyítheti a számlaadatok vevői oldalon történő feldolgozását." (https://nav.gov.hu/nav/ado/afa/Az_elektronikus_szaml20200416.html)

Esetleg kaphatnék 1-2 példa XML-t, hogy hogyan kell kinézzen helyesen ebben a két esetben?

Válaszukat előre is nagyon szépen köszönöm, Tímea

**Comment by NTCA-tax** [comment]
Az adatexportnak jelenleg két alapvetően eltérő struktúra alapján készülhet: NGM rendelet melléklete, számlaadat-szolgáltatás XSD-je. Az NGM rendelet mellékelet szerinti adatstruktúrának sajnos vannak olyan hiányosságai, melynek csak kreatív módon lehet adatexport állományt készíteni. Éppen ezért fogadjuk ott el a 0%-os adókulcsot, amit az adatszolgáltatásban nem. 

A PDF-hez csatolt XML lehet az adatszolgáltatás XML-je, de nem kötelező, hogy az legyen és nem is kötelező, hogy egyáltalán legyen. Tehát ez egy jó megoldás lehet, de nem kötelezettség.

**Comment by JamborTimea** [comment]
Köszönöm szépen a választ!

**Comment by EnokhSys** [comment]
Nagyon jó a topiknyitó által felvetett ötlet, hogy az elektronikus számlaként küldött pdf-ben, az emberileg olvasható számlakép mellett az XML kód is benne legyen, de izé... bocs a láma kérdésért, ezt hogyan tudnám megcsinálni? Van valamilyen pdf készítő program? Vagy van olyan program, amelynek segítségével egy már elkészített pdf-be, utólag bele tudok venni XML kódokat? Előre is köszi.

**Comment by connorhu** [comment]
"In PDF 1.4, support was added for Metadata Streams, using the Extensible Metadata Platform (XMP) to add XML standards-based extensible metadata as used in other file formats. This allows metadata to be attached to any stream in the document, such as information about embedded illustrations, as well as the whole document (attaching to the document catalog), using an extensible schema."

https://en.wikipedia.org/wiki/PDF
https://en.wikipedia.org/wiki/Extensible_Metadata_Platform

Innen már csak egy lépés, hogy az adatszolgáltatásban szereplő teljes számla bekerüljön önálló névtér alatt.

**Comment by EnokhSys** [comment]
@connorhu köszi a választ! Ezt eddig is tudtam, de a kérdésem a "hogyan"-ra vonatkozott. Arra a "már csak egy lépésre" vagyok kíváncsi, mert amikor elindítok egy nyomtatást az integrált rendszerből, hogy a számlakép ne a fizikai nyomtatóra, hanem a pdf nyomtató driverre menjen ki, akkor milyen utasítással/segédprogrammal/kalapáccsal tudom a metaadatokat belepasszírozni.

**Comment by connorhu** [comment]
@EnokhSys szerintem ezt speciális libraryvel/eszközzel lehet generálni, vagy utólag beágyazni. Keresni kell megfelelő szerszámokat amikkel ez elvégezhető. Az ötlet nem rossz, felírtam, szerintem én is meg fogom csinálni.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
