### ISSUE TITLE
Eladó adószáma

### ISSUE THREAD

**Issue by kolocsan** [nav-gov-hu/Online-Invoice#834]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Tisztelt Ügyfélszolgálat!
Az lenne a kérdésem, hogy problémát okoz e az, hogy az eladó magyar adószáma és közösségi adószáma is szerepel az XML file-ban belföldi értékesítés esetén.

Köszönöm

**Comment by tkelemen73** [comment]
Nem, megengedi

**Comment by NTCA-tax** [comment]
Jelenleg warning nélkül befogadjuk. Csak megjegyzésként, ekkor a számlán nem kellene feltüntetni a közösségi adószámot, csak a belföldit, mivel azon végezte a termékértékesítést/szolgáltatásnyújtást (áfa tv. 169. § c) ).
