### ISSUE TITLE
[DEV support] INCORRECT_HEAD_DATA_SUPPLIER _GROUPMEMBER_TAXPAYERID but not part of a GroupMember

### ISSUE THREAD

**Issue by lcoll-edicomgroup** [nav-gov-hu/Online-Invoice#835]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[x] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
2103261006396281849
2103260933253538712
2103260817522764321
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
We are getting the validation warning in all of the invoices reported (there is more requestIDs availiable)
INCORRECT_HEAD_DATA_SUPPLIER _GROUPMEMBER_TAXPAYERID
Hibás adószám. Eladóként áfa csoporttag adószáma lett megadva!

But the tax id informed is not registered as a VAT Group, it is the actual taxpayer ID

*Egyéb tartalom / Additional content*

**Comment by NTCA-supporter** [comment]
Hi @lcoll-edicomgroup !
As far as I can see, the 25353745 taxNumber is a member of the 17781949 VAT group.
However the vat class is 2, which is not the code of VAT group members.
I'll check that how could this happen and get back to you.
Br

**Comment by lcoll-edicomgroup** [comment]
Hi, thanks for the answer, in PRODUCTION this warning is not happening, so maybe due to not updated master data in TEST, as it is true 25353745 **was** part of 17781949, but not anymore

**Comment by NTCA-supporter** [comment]
Hi!
It's a new warning message, and it'll be on PRODUCTION tomorrow.
I've asked if it's the same situation on PROD. We'll see, but if the data not up to date then you can ignore the WARN message.
I'll send you their answer.
Br

**Comment by lcoll-edicomgroup** [comment]
Hi,

Thank you, our official GO-LIVE date is tomorrow so we can confirm it based on your reply, thanks for the clarity. 
Just to double-check and confirm, "25353745" should be set up as standalone company (VAT class 2) not part of a VAT Group

Thanks again for all the help!

**Comment by NTCA-supporter** [comment]
I close the issue because it's been resolved.
Feel free to reopen it.
