### ISSUE TITLE
[Q&A] Óraátállítás - INVALID_REQUEST_SIGNATURE

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#837]
Sziasztok!

Ma hajnalban - vélhetően az óraátállítással kapcsolatban - érdekes esemény történt az éles NAV Online Számla felé.
A tesztben biztos nem fogjuk tudni reprodukálni, ezért csak gondolatébresztőnek írom fel a NAVos kollégának, hátha beugrik valami, illetve az érdekelne, hogy más is tapasztalt-e ilyet.

Az érdekes az, hogy nem hajnali 2kor vagy (az ugrás miatt) 3kor kezdődött, hanem pontosan 4 órakor és pontosan 5 óráig tartott.

INVALID_REQUEST_SIGNATURE : Érvénytelen kérés aláírás!

Mind a saját üzemeltetésű felhős környezetünkből, mind az ügyfelek által üzemeltetett rendszerekből bejött a figyelmeztetés, függetlenül attól, hogy *nix vagy Windowsos környezetről van/volt-e szó.

Az UTC időkezelés miatt nem gondoltuk, hogy ilyen probléma lehet, illetve eddig egyetlen óra átállításkor sem tapasztaltuk ilyet.

Igaz, hogy tavaly ősszel még nem volt tömeges bejövő számla letöltés sem az ügyfeleknél, illetve azóta aktiváltuk azt a programrészt is, amely visszakérdez, hogy a NAV oldalán is be van-e jegyezve minden számlára, hogy lekértük a státuszát és hiába kértük le, ha a NAV ezt nem jegyezte be, akkor újra lekérjük (elkerülendő azt, hogy az ügyfelek levelet kapjanak a NAVtól, de ez a szál nagyot ment anno, nem magyarázom :)).

**Comment by omachtandras** [comment]
Ha senki másnak nem volt ezzel problémája, akkor zárom a jegyet.

**Comment by omachtandras** [comment]
Upsz, bocsánat, most látom, hogy @NTCA-supporter  magához vette. Visszanyitom, ha nem találtok semmit, zárd le nyugodtan.

Köszönöm!

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet. Ha van még hasonló tapasztalat nyissatok újat kérlek.
Üdv
