### ISSUE TITLE
[DEV support] QueryInvoiceData

### ISSUE THREAD

**Issue by ballonyi** [nav-gov-hu/Online-Invoice#838]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[x] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
QIDG_000000063175
QIDT_000000063180
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Egy QueryInvoiceDigest kérés (requestId: QIDG_000000063175) által visszaadott számlákat kezdtem el QueryInvoiceData-val lekérdezni. Az első 31-et sikeresen letöltötte,de a 32-nél (requestId: QIDT_000000063180) leakadt "bad request" hibával. Az egyedüli különbség itt az invoiceNumber ékezetes "4Á/88379" (erről meggyőződtem a webes felületen is). 
Kérhetnék segítséget, hogy miért hibás a kérés?

Köszönöm

**Comment by KMGY100** [comment]
A probléma nálam is fennáll. 
Ha számla számában ékezetes karakter van akkor  a    QueryInvoiceData  nem ad vissza semmit

**Comment by renced42** [comment]
Sziasztok

Nem lehet, hogy a #490 esete áll fenn?

**Comment by NTCA-supporter** [comment]
Szia @ballonyi!

Megnéztem a logban a  QIDT_000000063180 kérésedet. Én azt látom, hogy nem az ékezetes karaktert látom hibának, hanem azt, hogy a kérés végén hiányzik egy ">" karakter. Erre rá tudnál nézni? 
Én ezt látom a logban:
</invoiceNumberQuery>
</QueryInvoiceDataRequest

**Comment by KMGY100** [comment]
Az alábbi 2 darab  Trid -s számla számában ékezetes karakter szerepel
3BG8GVMKABRBMV1N                   
3BHLNBOO7TQL48AC      

A  QueryInvoiceData nem ad vissza semmit

**Comment by NTCA-supporter** [comment]
@KMGY100 Légyszi küld el a fenti két QueryInvoiceData kérés requestId-ját és megnézem. Köszi

**Comment by KMGY100** [comment]
QueryInvoiceDataResponse      requestId:      362323455513000520210330120938

egy harmadik requestId  de ugyanaz a helyzet.

**Comment by KMGY100** [comment]
Igen, ez volt a hiba , 
illetve az hogy  dupláztam az utf-8 - at.
köszönöm

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
