### ISSUE TITLE
[DEV support] tokenExchangeRequest hiba

### ISSUE THREAD

**Issue by kukko** [nav-gov-hu/Online-Invoice#839]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[X] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[X] 3.0

**A requestId értéke / requestId value**
```
1617035639835
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
A dokumentációnak megfelelően előállítottam a tokenExchange által elvárt XML-t, azonban a válaszban az alábbi hibaüzenetet kapom vissza:
`Request body contains on line: [1] and column: [336] error: [cvc-elt.1.a: Cannot find the declaration of element 'TokenExchangeRequest'.]`

Tudnak valamilyen segítséget nyújtani, hogy mi okozhatja a problémát? Válaszukat előre is köszönöm.

*Egyéb tartalom / Additional content*

**Comment by renced42** [comment]
Kedves @kukko 

Ha az XML úgy néz ki ahogy kell akkor nézd meg, hogy a "TokenExchangeRequest" valóban az-e, kisbetű, nagybetű elírás?

**Comment by NTCA-supporter** [comment]
Szia @kukko !
<ns3:requestVersion>2.0</ns3:requestVersion>
Ez a probléma.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
