### ISSUE TITLE
[Q&A]Lekérdezés transacion id alapján

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#84]
Szerintem erről már volt szó itt valahol, de meg kell ismételjem: nem igazán jó a transaction id alapján történő lekérdezés. Erre csak a digest használható, de ott külön node-on van így mindenképpen meg kell adni mellette a mandatory node valamelyik elemét. Ilyen esetben éppen az érdekelne, hogy mi is volt az adott transakcióban, ha ezt tudom (pl, számlaszámok) akkor nem is kellene használnom a lekérdezést. Szerintem a transaction adatoknak a mandatory-ban lenne a helye.

**Comment by kabelnet2** [comment]
Nem nyitok új issue-t:
Ugyancsak problémának érzem, hogy a supplierTaxNumber csak a számlaszámmal együtt adható meg digest-es lekérdezésben. Vagyis nem tudom lekérdezni egy adott beszállítótól érkezett számlákat, csak úgy, hogy lekérdezem az összeset és utána válogatok - ami nektek többszörösére növelheti az adatforgalmat és a szükséges erőforrásokat. (igazából az INBOUND mellé kellett volna tenni a tax numbert (opcionálisan), az mindenhol jó lenne. Persze most már.......

**Comment by NTCA-developer** [comment]
Szia @kabelnet2 

Kezdem a másodikkal. Teljesen igazad van, ez a mi hibánk és ki fogjuk javítani. Ezt már tudjuk mióta elkövettük, de még senki nem kérdezte. :)

A digest-be vissza kell tenni az adószám szűkítő paraméterét, ahogy az a frontenden is megvan. Sajnos a nagy favágás és átalakítás közben elmaradt a taxNumber, mint additionalQueryParam. De még a 2.0 élesítése előtt visszatesszük. Valószínűleg egy kalap alatt megy majd a többi Githubos átalakítással.

Az elsőt még nem értem. 

> Szerintem erről már volt szó itt valahol, de meg kell ismételjem: nem igazán jó a transaction id alapján történő lekérdezés.

TransactionId-re csak a feldolgozás eredményét kérdezed le. Mi köze ennek a számla adatokhoz? Kérlek segíts megvilágosodnom.

**Comment by kabelnet2** [comment]
Ha van egy transaction id-m és szeretném lekérdezni a hozzá tartozó számlákat, hogy mi is volt annak a bevallásbak a tartalma. Erre a transaction id egyértelműen elegendő (+ index, de ezt most hagyjuk). De a query nem engedi meg, hogy mandatory parameter nélkül lekérdezzek transaction id-re, vagyis még valamit tudnom kell: a számlaszámot, az időpontot, hogy ki tudjam tölteni a mandatory parameter-t. Ezt érzem feleslegesnek.
Azt, hogy transaction id alapján számlát lehet lekérdezni ti tettétek be az invoiceQueryParams-ba, a transactionQueryParams elemmel.

**Comment by NTCA-developer** [comment]
Így már értem, köszi.

Ha ezt arra használod hogy megtudd, a tranzakcióban milyen számlák voltak, akkor nem volna egyszerűbb a /queryTransactionStatus operációban lekérni és a base64 tartalmat kibontani?

Egyébként igazad van.

**Comment by NTCA-developer** [comment]
Szia @kabelnet2 

Az adószámos szűrés javítás folyamatban. Ezt lezárom.
