### ISSUE TITLE
online szamla teszt rendszer hiba

### ISSUE THREAD

**Issue by KeterCurver** [nav-gov-hu/Online-Invoice#840]
a teszt üzemmódban nincsenek aktualizalva az adoszamok, a mienk sajnos meg csoporttagkent szerepel, nem tudok tesztelni

**Comment by NTCA-supporter** [comment]
Szia @KeterCurver !
Valóban nincsenek szinkronizálva, de ez csak figyelmeztető üzenet. Tesztelés szempontjából ezt figyelmen kívül hagyhatod szerintem, ha a valóságban a beküldött adószám nem csoporttag.
Üdv

**Comment by KeterCurver** [comment]
Szia NTCA-supporter,
Tegnapi napon próbáltuk a rendszerben tesztelni, és nincs kommunikáció az onlineszámla nav oldaláról. 
szerinted akkor mi más lehet a probléma?

**Comment by KeterCurver** [comment]
![Capture](https://user-images.githubusercontent.com/81613812/113000154-d8d27280-916f-11eb-8d04-84ff3f76a0a7.JPG)

**Comment by KeterCurver** [comment]
Szia,

Igen, ott működik.

**Comment by NTCA-supporter** [comment]
Szia @KeterCurver !
Kérlek a https://nav.gov.hu/nav/e-ugyfsz/levelkuldes fórumon jelezd a problémát, és egyedileg meg fogják oldani, hogy aktuális adatok legyenek teszt környezen is.
Az issue szerintem zárható, a problémát detektáltuk.
Üdv

**Comment by KeterCurver** [comment]
Szia,

köszi. ok lezárom. ott is jeleztem egyidőben mint itt. csak nem segítenek sajnos 2021.04.01-ig.

köszi a segítséget

**Comment by NTCA-supporter** [comment]
Szia @KeterCurver !
Elvileg már jó a teszt környezet, kérlek próbáld meg.
Üdv

**Comment by KeterCurver** [comment]
Szia NTCA-supporter!
Nagyon hálás vagyok! Sikerült!
üdv,
