### ISSUE TITLE
[Q&A] Vevő belföldi adószáma hiányzik (belföldi fordított adózás) hiba

### ISSUE THREAD

**Issue by beniraj** [nav-gov-hu/Online-Invoice#842]
A vevőnek ki lett állítva egy fordított adózású storno számla, amin szerepel a vevő adószáma is, visszaellenőrizéskor mégis a [validationErrorCode] => DOMESTIC_TAXNUMBER_EXPECTED_REVERSE_CHARGE [message] => Vevő belföldi adószáma hiányzik (belföldi fordított adózás). hibaüzenet kapjuk. Mit tehetünk ez ügyben? Köszönöm

**Comment by NTCA-supporter** [comment]
Szia @beniraj !
Teszt rendszerről küldj kérlek valamilyen azonosítót (transactionId) amivel meg tudjuk nézni a konkrét esetet.
Köszönöm

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
