### ISSUE TITLE
[Q&A]Hibás INCORRECT_HEAD_DATA_CUSTOMER_GROUPMEMBER_TAXPAYERID üzenet

### ISSUE THREAD

**Issue by burnyo** [nav-gov-hu/Online-Invoice#843]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Tisztelt NAV!

Ma több számlához is megkaptuk a címben levő új üzenetet. A vevők korábban valóban csoporttagok voltak, de már rég nem azok, és az egyedi adószámuk szerepel a számlán.  Kérem ellenőrizzék a program működését.
Tranzakcióazonosítók:
3BISITQW2N18QBRY
3BISIWOWHUNIT0IZ
3BISJ8WIPEN9W3IA

**Comment by NTCA-supporter** [comment]
Szia @burnyo !
Ez éles vagy teszt könyezet?
Ha éles, akkor azt nem supportáljuk, de ha küldesz 1-2 adószámot, akkor arra ará tudnak nézni az illetékesek.
Köszönöm

**Comment by burnyo** [comment]
Szia!

Igen, éles környezet (tegnap még gond nélkül ment be ilyen vevőhöz számla). Az érintett adószámok:

11451448-2-07
11451479-2-07

**Comment by NTCA-supporter** [comment]
Köszi, utána járunk.
Ha valóban már nem csoporttagok, akkor ignorálható a WARN. Természetesen ez így nem szép megoldás, helyretesszük az adatokat. Valószínűleg egyedi eset, és adathiba lehet nálnuk, mert maga a WARN ellenőrzés jól működik.
Üdv

**Comment by burnyo** [comment]
Köszönöm, várjuk a javulást! :-)

**Comment by WittmannWien** [comment]
Sziasztok,

szintén hasonló probélmával szembesültem. (Èles rendszer)
Adószám: 11140241209

Köszi szépen.

**Comment by connorhu** [comment]
Teszt rendszer azért nem releváns mert az ottani adózói adatok nem frissek.

**Comment by burnyo** [comment]
Köszönöm. Sajnos korábban én is olvastam ezt az információt, de ez egy olyan adószám, amire ugyanúgy érkezik figyelmeztetés mind a teszt, mind az éles rendszerből, és hátha így gyorsabban elhárul a probléma.

**Comment by izll** [comment]
Üdv,
Itt is ilyen probléma van:
11451448-2-07
Továbbá "Hibás adószám. A vevő nem élő adózó!", pedig igen:
22039080-1-07

**Comment by fzoli15** [comment]
Mi is tapasztaljuk ezt a hibát az éles rendszerben. Példákat nem írok, úgy tűnik, hogy általános jellegű hibáról van szó, nem egy-egy egyedi esetről.

**Comment by DrotosTot** [comment]
Ez összefüggésben lehet a #829 problémámmal?
Sima adószámnál nem tapasztaljátok, hogy "téved" a rendszer?

**Comment by burnyo** [comment]
Tisztelt NAV! 
Várható ezzel kapcsolatban valami javítás, vagy külön jelezni kell az éles rendszer ügyfélszolgálatának is a jelenséget?
Továbbra is kapjuk a szerintünk fals üzeneteket, megnézve a querytaxpayer adatai között ott van valóban a csoportjelző, aminek már nem lenne szabad ott lennie. Egyik cégünk az összes beküldött számlájához INCORRECT_HEAD_DATA_SUPPLIER_GROUPMEMBER_TAXPAYERID üzenetet kap, ugyanezen ok miatt.

**Comment by NTCA-supporter** [comment]
Szia @burnyo !
Kérlek jelezd a https://www.nav.gov.hu/nav/e-ugyfsz/levelkuldes felületen is az éles adatokat, az a biztos.
A problémát jeleztük az illetékeseknek, visszajelzésre várunk.
Üdv

**Comment by kristofbela** [comment]
25953534-2-43 

3BJCG730FSI1Y7RC
3C5NL1IGTZP9PD1H 
3C4ZLO0YU130MUUQ

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezzel kapcsolatban van még probléma vagy megoldódott? Ha nincs, kérlek zárjátok.

Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet, ha van még kérdés/probléma, kérlek nyissátok újra.
Üdv
