### ISSUE TITLE
Pénznem rossz a NAV weboldalán

### ISSUE THREAD

**Issue by rtoth0407** [nav-gov-hu/Online-Invoice#844]
Éles rendszerbe beküldtünk egy EUR számlát, de a NAV weboldalon HUF látszódik
![image](https://user-images.githubusercontent.com/55562563/113330988-ac5d5880-931f-11eb-9890-c9881a86b9a7.png)
![image](https://user-images.githubusercontent.com/55562563/113331071-c860fa00-931f-11eb-9f88-fb89e09b93d1.png)

**Comment by topybear** [comment]
Esetleg ugyanez?
https://github.com/nav-gov-hu/Online-Invoice/issues/752

**Comment by NTCA-supporter** [comment]
Szia @rtoth0407 !
Így van, ez a bug már jelentve lett.
Csak frontendes bugról van szó, maga a számla feldolgozása/mentése megfelelően működik.
Ezt az issuet zárom, a 752-ben lesz jelezve ha elkészült a javítás.
Üdv és köszi a jelzést!
