### ISSUE TITLE
[DOC] airCargo pattern hibás

### ISSUE THREAD

**Issue by bcdel** [nav-gov-hu/Online-Invoice#845]
**A hibás dokumentum neve / Document name containing the error**
Fájlnév vagy hostolt URL / File name or hosted URL.

API dokumentáció: Online Számla 3.0 rendszer interfész specifikáció (utoljára frissítve: 2021.03.25.)

**Oldalszám / Page number**
A hibát tartalmazó oldal száma / Page number containing the error.

128/139
2.2.3.5.3

**A dokumentációs hiba leírása / Description of the documentation error**
Rövid és tömör összefoglalása a hibának. / A clear and concise description of the summary of the error.

airCargo
SimpleType: boolean
Pattern: totalDigits value="22" fractionDigits value="6"

fennakadast nem okoz, mert most kicsit vicc a eset a forgalmunk

**Comment by NTCA-supporter** [comment]
Köszi a jelzést, javítani fogjuk.
Üdv

**Comment by NTCA-supporter** [comment]
Javítottuk, köszi a jelzést.
