### ISSUE TITLE
[FEATURE] Vevő EU adószám hiánya esetén jöjjön hibaüzenet, ha a tételek EU-ÁFA-sok

### ISSUE THREAD

**Issue by janisoft** [nav-gov-hu/Online-Invoice#846]
**Az igény összefoglalása / Summary of the request**
A rendszer befogadja, és hibajelzés nélkül feldolgozza azokat a számlákat, ahol a számla tételek EU ÁFA-sak (vatExemption KBAET),
viszont a vevő EU adószáma nincs kitöltve.

**Az általam javasolt megoldás / The solution I propose**
Legalább WARN, de akár ERROR is visszajöhetne ebben az esetben, hiszen ez így biztosan nem helyes

**Comment by NTCA-supporter** [comment]
Szia @janisoft !
Továbbítjuk a felvetést az illetékeseknek.
Üdv

**Comment by NTCA-supporter** [comment]
Szia @janisoft !
Tesztrendszerre kikerültek az új WARN ellenőrzések, amiben ez is szerepel.
Köszönjük a felvetést, zárom az issuet.
Üdv
