### ISSUE TITLE
[DEV support] "Feldolgozás sikertelen!" hibaüzenet

### ISSUE THREAD

**Issue by pitfla** [nav-gov-hu/Online-Invoice#849]
**Környezet / Environment**
[x] https://api.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
/QueryInvoiceCheckRequest
[] 3.0

**A requestId értéke / requestId value**
    <funcCode>ERROR</funcCode>
    <errorCode>OPERATION_FAILED</errorCode>
    <message>Feldolgozás sikertelen!</message>

Kedves Fejlesztők!
Egy módosító számla beküldésekor ilyen választ kapok. 
QueryTransactionStatusRequest esetén is ennyi a válasz.
Mi lehet ilyenkor a probléma?

**Comment by kabelnet2** [comment]
"A hibakód továbbá akkor is jelentkezhet, ha egy request nem a megfelelő operáció végpontjára van beküldve, például egy sémavalid számla beküldése a /manageInvoice helyett a /queryTaxpayer végpontra történik."
Csak egy lehetőség a dokuból.

**Comment by tkelemen73** [comment]
Az egyik ügyfelünknél az az érdekesség állt elő, hogy kapott egy OPERATION_FAILED üzenetet a számla beküldésre, ami után az ismétlő job megpróbálta újra küldeni a számlát pár perc múlva, arra már kapott tranzakció azonosítót, viszont a státusz lekérdezés már ABORTED státuszt kapott, számla sorszám nem egyedi hibaüzenettel. Amikor visszakérdeztünk a számlára, abban azzal időponttal szerepelt egy általunk nem ismert tranzakcióazonosítóval a sikeres adatszolgáltatás, amikor arra OPERATION_FAILED üzenet érkezett.
Lehetséges, hogy itt van valami hiba, a specifikációhoz képest, nem megismételni kellene a küldést, hanem először egy /queryInvoiceCheck vagy /queryInvoiceData és ha nincs értelmes válasz, csak akkor újraküldés?

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezzel kapcsolatban van még kérdés, fennáll még a probléma? Ha nincs, kérlek zárjátok.
Ha volt ilyen eset mostanában, hogy OP_FAILEd és közben befogadtuk a számlát akkor annak utánanézek szívesen (teszt rendszer esetén).

Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet, ha van még kérdés, kérlek nyissátok újra.
Üdv
