### ISSUE TITLE
[Q&A] 2021 január 1. magánszemélyes vásárlások adatszolgáltatása

### ISSUE THREAD

**Issue by csaszko** [nav-gov-hu/Online-Invoice#85]
> Jövőre még nagyobb fokozatba kapcsol a gazdaságfehérítés. Gyakorlatilag minden számláról online adatot kell majd szolgáltatni, amely a gazdaságfehérítésén túl biztosítja azt is, hogy a Nemzeti Adó- és Vámhivatal (NAV) akár már 2021 tavaszától elkészítse a vállalkozások áfa bevallási tervezetét. Az adóhivatal jelenleg csak a 100  ezer forintos áfa összeget elérő számlák adatait látja online, 2020. július 1-től már az ún. belföldi áfaalanyok részére kiállított számlát, vagyis lényegében minden vállalkozói számlát, 2021. január 1-től pedig még a magánszemélyek részére kiállítottakat is. 

Szia, 
Szeretnék érdeklődni, hogy milyen terv van erre, hogyan fogjuk beküldeni ezeket a magánszemélyes vásárlásokat? Mert, hogy ezek szerint mire élesedik a 2.0 már lehet újra kezdeni az egész egyeztetést, fejlesztést stb.

**Comment by NTCA-developer** [comment]
Szia @csaszko 

Amit én tudok: a jelenlegi adatvédelmi szabályok nem teszik a NAV számára lehetővé magánszemély azonosítható módon történő összekötését a számlával. Ezért ezek az adatszolgáltatások - jelen környezetben - csakis anonimizált módon történhetnek.

A belső szerkezetben a customerInfo alatti adatok valószínűleg choice struktúrává fognak átalakulni. Ez az egyik oka annak, hogy kelleni fog a 3.0, mivel ez breaking change, a korábbi szerkezettel nem lesz kompatibilis. De dacára, hogy ez nagy verziónak számít, a jelenlegi ismereteim szerint ez az átalakítás kliens oldalon sokkal kisebb lesz a 2.0-hoz képest. 

De konkrét szabályozási kérdések rendezése szükséges ahhoz, hogy lássuk mi a 3.0 scopeja, addig ezek csak tervek.

**Comment by csaszko** [comment]
Köszönöm a válaszod. 
Tudom, hogy ez az infó csak most látott napvilágot, és még csúszhat, de 2021. jan.1. ebben az esetben eléggé problémásnak tűnik, mert akkor addigra 3.0val is kész kell lenni, és még csak éppen elindul élesben a 2.0 április 1-el. 
Nem biztos, hogy minden változót szem előtt tartok most, de nem lenne elegendő egy pl vevotipus mező bevezetése még a 2.x-be, ami miatt nem lenne szükséges atalakitani a customerinfot ? Szerintem ez sokkal emészthetőbb lenne kliens oldalról.

**Comment by NTCA-developer** [comment]
Mi is szerettük volna egybevonni vagy legalább előkészíteni, de sajnos felelősen ezt nem tudjuk megtenni. Ha egy dolog is kimarad, akkor megint ott vagyunk hogy kell 3.0, sőt, még rosszabbul néz ki 1 kihagyott breaking change miatt főverziót emelni.

Ezt így nem szabad bevállalni, én se tenném.

**Comment by csaszko** [comment]
Az átgondolást értem, meg mindent ami mondasz, csak az nem világos, hogy ha már úgyis rengeteget csúszott az egész online számla és most műkodik még ha nem is végleges módon és úgy ahogy szeretnétek, de mennek az adatok, akkor mi múlna +1-2 hónap csúszáson? Hogy egyszerre lehessen mindent megoldani? Szerintem mindenki szeretné ezt az egészet már a háta mögött hagyni és max 1-2 évente valami apróságot módosítani. Sokkal jobb lenne egyszerre egy kicsit többet foglalkozni vele, mint állandóan ezen pörögni mikor valaki bedob valamit...

**Comment by NTCA-developer** [comment]
Megállapítom a hatásköröm hiányát. :)

**Comment by csaszko** [comment]
Sejtettem sajnos, csak hátha valaki lesz olyan aki olvass, hatásköre is megvan hozzá hallgat a józan észre és még érdemben hajlandó is kezelni a problémát. Mert nem gondolom, hogy akkor a 2021 jan1 tartható, ha a beígért 6 hónap tesztelést/kivitelezést tartjátok.

**Comment by NTCA-developer** [comment]
Szia @csaszko 

A publikált roadmap tükrében mit szeretnél, mi legyen ezzel a tickettel? Lezárható?

**Comment by csaszko** [comment]
Szia, 
Igen, köszönöm.
