### ISSUE TITLE
[DEV support] CustomerInfo kötelező-e módosító számlánál?

### ISSUE THREAD

**Issue by soosreb** [nav-gov-hu/Online-Invoice#850]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageInvoice

**A kérés verziója / version of the request**
[] 3.0

**A requestId értéke / requestId value**
```
zNEjuatvgUStwPK31UFgFg0_634145
Zd_9nicTKEKjKZ98YuD8qQ14680064
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Módosító számla esetében a 3.0 specifikáció szerint nem kötelező a customerInfo tag kitöltése, kivéve, ha történt változás a customer adataiban. Ez a korábbi verzióknál így is működött, azonban a 3.0-ás verziónál úgy tűnik, hogy ez megváltozott.
Példa: 
A request id: zNEjuatvgUStwPK31UFgFg0_634145 TransactionId: 3C1GAIO88IMPNRSL xml a customerInfo tag nélkül ABORTED státuszt kapott a következő megjegyzéssel: Vevői adatok megadása kötelező, ha a vevő nem magánszemély.
Érdekes módon a request id:  Zd_9nicTKEKjKZ98YuD8qQ14680064 TransactionId: 3C1GE6HHY91J5HUZ xml, melyben csak a customerName és a customerAddress tag lett kitöltve, de a pl. a customerVatData nem, DONE státuszt kapott.

Mi a helyes eljárás ebben az esetben?

Előre is köszönöm a választ,
Soós Rebeka

*Egyéb tartalom / Additional content*

**Comment by soosreb** [comment]
@NTCA-supporter, van esetleg valami fejlemény ezzel az issueval kapcsolatban? Köszi!

**Comment by soosreb** [comment]
@NTCA-tax, kindly reminder.

**Comment by soosreb** [comment]
Kedves @NTCA-tax és @NTCA-supporter! Tudnátok az alábbival kapcsolatban visszajelzést adni? Már több mint két hete áll nálatok a dolog, fontos lenne az ügyfeleknek visszajelezni, Köszi

**Comment by soosreb** [comment]
@NTCA-tax, @NTCA-supporter, kindly reminder.

**Comment by NTCA-supporter** [comment]
Szia @soosreb !
Vegyük külön a két dolgot.
Maga a customerInfo csomópont nem kötelező módosításnál.
Viszont ha megképzed akkor már életbe lépnek az üzleti validációk, pl. ha nem PRIVATE_PERSON a vevő típusa, akkor meg kell adnod a nevet.

A 3C1GAIO88IMPNRSL transactionId esetén te megképezted a customerInfo csomópontot, így a többi adatnak is szerepelnie kell.

Ha nincs több kérdés kérlek zárd az issuet.
Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet, ha van még kérdés, kérlek nyissátok újra.
Üdv
