### ISSUE TITLE
[Q&A] [taxpayerValidity] => true azonban a számla WARN lett

### ISSUE THREAD

**Issue by salesdb** [nav-gov-hu/Online-Invoice#851]
Adószám lekérdezés során  a válaszban "[taxpayerValidity] => true" jött vissza. Az elkészült számla mégis WARN lett. Megnéztem az adószámot a NAV oldalán a szankciós jelleggel törölt adószámok között szerepel. Az API leírásban ez van "A taxpayerValidity tag értéke akkor true, ha a lekérdezett adószám létezik. Nem érvényes vagy nem létező adószámra false érték kerül visszaadásra." 
Nem találkoztam még ilyennel.
Hogyan szűrjem ki az ilyen adószámot, ha az API azt adja vissza hogy megfelelő?
Ezek szerint eltérő adatbázisból dolgozik az API ha lekérdezek és más adatbázist használ a NAV ha feldolgoz egy számlát?
Mit mondjak a számla kibocsátónak miért lett WARN a számlája?
Nem járok el helyesen amikor a QueryTaxpayer adataira hagyatkozom?
Adószám: 26670737213
[requestId] => RID081728800161831779741529
[timestamp] => 2021-04-13T12:43:17.817Z
[requestVersion] => 3.0

**Comment by DrotosTot** [comment]
Ha tesztrendszerben kaptad ezt, akkor nekem a #829 issue-ra azt válaszolták, hogy a tesztrendszerben levő adatok nem valósak.
Éleshez itt kérhetsz supportot: https://www.nav.gov.hu/nav/e-ugyfsz/levelkuldes

**Comment by NTCA-supporter** [comment]
Sziasztok!

Köszi a jelzést, a #829 erről szól, így ezt zárom, ott folytassuk.
Üdv
