### ISSUE TITLE
[Q&A] külföldi irányítószám

### ISSUE THREAD

**Issue by attilaszoke** [nav-gov-hu/Online-Invoice#852]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Üdvözlet,
Az irányítószámok kezelése elég szigorú, sok esetben feltöltési problémát tud okozni, főleg 3. országok esetén
ahol a helyes irányítószám esetleg nem elfogadott a séma szerint.
Ez így marad mindörökre?
Köszönettel

**Comment by renced42** [comment]
Kedves @attilaszoke 

Küldenél néhány példát?
Köszi!

**Comment by NTCA-supporter** [comment]
Szia @attilaszoke !
A pattern marad, viszont ajánlom figyelmedbe az interfész doksi ide vonatkozó részét:
Egyes speciális esetekben az irányítószám sem értelmezhető az adott országban (például Írország),
ilyenkor az irányítószám (PostalCode) elemet „0000” karaktersorozattal kell feltölteni. Az irányítószám
formátuma támogatja példálul a csak 3 karakter hosszú, illetve a szóközt és kötőjelet tartalmazó
irányítószám formátumokat. Más speciális esetekben, ha az adott ország irányítószáma pontosan
feltüntetve a séma szerint érvénytelen, az irányítószámot a séma szerint érvényesre célszerű
konvertálni.

Kérlek zárd ha nincs több kérdés.
Üdv
