### ISSUE TITLE
[Q&A]Adójegyes értékesítés (AJT) feladása

### ISSUE THREAD

**Issue by rostasc3** [nav-gov-hu/Online-Invoice#854]
Üdv Mindenkinek!
Hogyan kell feladni AJT-s terméket (dohány) tartalmazó számlát? (case/reason)
köszönettel
Rostás István

**Comment by NTCA-tax** [comment]
Case: ATK, reason: dohánytermék (vagy ami a számlán szerepel a tárgyi hatályon kívüliség okaként).

**Comment by rostasc3** [comment]
Köszönöm!
