### ISSUE TITLE
[Q&A] Tanúsítvány

### ISSUE THREAD

**Issue by kuni1123** [nav-gov-hu/Online-Invoice#855]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Akárhol kerestem, nem találtam meg a certifikációt amivel hitelesíteni tudnám a kéréseimet. 
Az első link amit találtam az ez volt: [NAV kérdések és válaszok
](https://nav.gov.hu/nav/online_penztargepek/kerdesek_es_valaszok_gyik/gyartok_forgalmazok/kriptografia#faq_4825041)
Java kódból próbálom futtatni a kérést. A hibaüzenet amit kapok: **PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target**
Érdekesség(számomra legalább is), hogy Postmanből próbálva elmegy a kérés és valid üzenetet kapok vissza. 
Valószínűsítem, hogy [erre](https://nav.gov.hu/nav/online_penztargepek/kerdesek_es_valaszok_gyik/gyartok_forgalmazok/kriptografia) lenne szükségem, vagyis ez lenne a leírása, de nem találtam többet róla.
A kérdésem az lenne, hogy hol tudnám letölteni a kérések elküldéséhez szükséges tanúsítványt, vagy honnan tudnám megigényelni?

Előre is köszönöm a válaszukat,
Kun Dávid

**Comment by renced42** [comment]
Kedves  @kuni1123 
Ez tipikus java probléma az SSL kapcsolatok kiépítésével összefüggésben.
A megoldás annyi, hogy a szervertől le kell húzni a tanúsítványt és a java keystoreba be kell importálni. Ha ez meg van, akkor a Java már meg fogja találni a szerver tanúsítványát. 

Ezzel a parancsal linux alól is le tudod menteni, de böngészőből is akár

openssl s_client -host onlineszamla-api-uat.nav.gov.hu -port 443 -showcerts | awk '/BEGIN CERT/ {p=1} ; p==1; /END CERT/ {p=0}' > onlineszamla.pem 

Google keresés:
[https://www.google.com/search?q=download+ssl+cert+from+server&rlz=1C1GCEU_huHU819HU819&oq=download+ssl+cert+from+server&aqs=chrome..69i57.11720j0j7&sourceid=chrome&ie=UTF-8&safe=active](url)

**Comment by kuni1123** [comment]
Köszönöm a választ! Azt hittem, hogy van valamilyen különleges megoldása, vagy eljárása ennek a dolognak ebben az esetben. 

Üdv,
Dávid
