### ISSUE TITLE
[Q&A] Szállítói számla adatok

### ISSUE THREAD

**Issue by MisiSzabolcs** [nav-gov-hu/Online-Invoice#857]
Szállítói számla adatok exportálása az online rendszerből

Sziasztok!
Nekem egy olyan kérdésem van, hogy hol érhető el / elérhető-e a specifikáció, ami alapján kiépíthető a számlázóprogramban az a funkció, amivel az online adatszolgáltatásba beküldött szállítói számláimat tömegesen lekérdezhetem és importálhatom a saját programomba (.xml formátumban talán?)

Előre is köszönöm a választ!

**Comment by kabelnet2** [comment]
Természetesen a dokumentációban. A queryinvoicedigest-el lekérheted, hogy milyen (célszerűen új, az előző lekérdezés óta érkezett) számlák vannak, majd ezek tételes adatait a queryinvoicedata-val tudod lekérdezni, a beszállító által feltöltött xml lesz a végeredmény.

**Comment by Macskafarka** [comment]
**Arra kell vigyázni, hogy a lekérés NEM tartalmazza a pénztárgéppel kiállított számlákat,** mert azokat a NAV eldugja.
A pénztárgépes számlákat ugyanúgy szerepeltetni kellene a számlaadat-szolgáltatásban az ÁFA tv. alapján, de ezt senki nem követeli meg. A pénztárgépes számlázók arra hivatkoznak, hogy a pénztárgép adatszolgáltatása tartalmatta a pénztárgépes szmlákat és a NAV azt mondta-mondja nekik, hogy ezeket nem kell beletenniük a számlaadat-szolgáltatásba (hiába van erre törvényi előírás). A NAV nekünk azt ígérgeti, hogy egyszer majd a pénztárgépes számlákat is le lehet kérni, mert megoldja ezt. Ettől még persze nem lesz megoldva a törvényen kívüli állapot, hogy a számlaadat-szolgáltatás mindenkire vonatkozik (pénztárgépesekre is).

**Comment by kabelnet2** [comment]
Hát mivel az issue címe 'szállítói adatok', ez szerintem őt nem fogja zavarni :)

**Comment by MisiSzabolcs** [comment]
Sziasztok!

Köszönöm a válaszokat mindenkinek. Ezek fényében el tudok indulni házon belül a fejlesztéssel :)
Igen azt tudom, hogy az online pénztárgépből kiállított szla-k nem szerepelnek az adatszolgáltatásban, de valójában az a helyes, mert nem lehet kétszer adatot szolgáltatni ugyan arról az ügyletről. 
 - Vagyis vagy a számlázóprogramból megy az adatszolgáltatás (KP-s fizetési módú számla által) és a pénztárgépből nem
 -  vagy a pénztárgépből megy az adatszolgáltatás, de akkor nem szabad szla-t kiállítani a számlázó programban.

**Comment by Macskafarka** [comment]
@MisiSzabolcs Szeintem nem nekünk, és nem a NAV-nak kellene ezt eldöntenie, hogy mi a helyes. A számlaadat-szolgáltatást az ÁFA tv. 10.sz. melléklete írja elő kötelezően. Ezt be kell tartani. Ha valaki ezt megszegi, pláne, ha arra bíztat, hogy hagyják figyelmen kívül, az már büntetőjogi tényállási elem. 
Jól is néznénk ki, ha mindenki maga mérlegelné azt, hogy betartja-e a törvényeket, vagy sem. Ha a NAV-nak mondjuk odaadom papir alapon a számlát, akkor hivatkozhatok arra, hogy azért nem adom számlaadat-szolgáltatásban, mert akkor duplán lenne nála meg?

**Comment by Macskafarka** [comment]
Lett volna már elég idő arra, hogy ezt a kérdést törvény módosítással oldják meg. Nem tették. Helyette sunyiság, és a tisztázatlan helyzet fenntartása van. Akiknek ez a dolguk, azok pontosan tudják, hogyan lehetne a jelenlegi káoszt megoldani. de nem teszik.

**Comment by MisiSzabolcs** [comment]
@Macskafarka 
Igazad van, hogy ahol ezt meg lehetne oldani, ott van a legtöbb infó a megoldáshoz, de mégis kezeletlen ág maradt.
Bízzunk benne, hogy rövidesen tisztázásra kerül ^^

**Comment by renced42** [comment]
Kedves @Macskafarka 

"mert azokat a NAV eldugja."

Nem dugja el! 
Szerintem kb 10x már le lett írva itt a GitHubon, hogy dolgoznak azon a NAV-ban, hogy az OPG-s adatok - többek között az Online Számla rendszerben is megjelenjenek.

**Comment by Macskafarka** [comment]
Kedves @renced42 Lehet, hogy nem jó szót használtam, az én szókincsemben nem tudok jobbat kitalálni (amely szalonképes is)  arra az esetre, amikor a törvény konkrétan előírja az Online számlaadat-szolgáltatást, és a NAV feladata lennr a törvény betartatása, e helyett azt kommunikálja, hogy nem kell a pénztárgépeseknek teljesítenie a számlaadat-szolgáltatást, mert a pénztárgépes adatokból majd összeállítanak valamit. 
Én messze nem becsülöm le azt a munkát, amivel az OPG adatok megjelenítésén dolgoztok, csak ez nem felel meg a hatályos törvényeknek. Ez nem fejlesztési kérdés, ez jogi kérdés. Nem a fejlesztőknek kell erre megoldást találniuk, hanem a jogalkotónak.
Itt elvekről van szó. Arról, hogy a NAV jogsértést követ el, amikor nem követeli meg a számlaadat szolgáltatást előíró törvény betartását. 
De ezen a fórumon ezt a témát befejeztem, nem nekünk kell ezt megoldani, ebben a kérdésben én elsősorban nem technikai problémát látok.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet, mert az eredeti kérdés meg lett válaszolva. Ha van még kérdés nyissatok újat kérlek.
A pénztárgépes topicra pedig van nyitott issue #411 
Üdv
