### ISSUE TITLE
[DOC]Nem hiba, csak kérés

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#86]
A doku előző (09.18) verziójában a pdf tartalomjegyzékben a bejegyzések linkek voltak, rákattintva az adott fejezetre lehetett ugrani. Az újban ez már nem így van.  Nem lehetne visszaállítani, mert szerintem sokkal könnyebb kezelni a dokut ha azonnal a fejezetre lehet ugrani.

**Comment by NTCA-developer** [comment]
Köszi, javítottam.
