### ISSUE TITLE
[DEV support] Az online számla RSS nem egyezik a weblapon megjelenő hírekkel

### ISSUE THREAD

**Issue by zonehun** [nav-gov-hu/Online-Invoice#860]
**Környezet / Environment**
[x] https://onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[x] RSS feed

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
A NAV ajánlások között szerepelt, hogy az RSS feedet építsük be a szoftvereinkbe. A probléma csak az, hogy ha pl. most lekérdezem az RSS feedet (https://onlineszamla.nav.gov.hu/feed/atom.xml?localisation=hu), akkor az utolsó bejegyzés 
dátuma: 2021-04-08T11:05:40.073Z. 
A címe: Online Számla rendszer lassulása. 
Tartalma: Az Online Számla rendszerben incidens van folyamatban!

Ehhez képest a weblapon az utolsó hír
dátuma: 2021-04-13 09:20
címe: Online Számla rendszer lassulása
tartalma: 2021.04.13-án 08 óra 30 perctől az Online Számla rendszer gépi interfészén elérhető szolgáltatások válaszidejében lassulás és esetenként kapcsolódási problémák tapasztalhatók. A probléma javítása folyamatban van.

UPDATE 1: 2021.04.13-án 11 óra 25 perckor elhárult a hiba az adatszolgáltatással érintett operációkon, a /queryInvoiceData operáció kivételével. A /queryInvoiceData operáció működésének helyreállítása folyamatban van.

UPDATE 2: A /queryInvoiceData operáció működésével kapcsolatos probléma 2021.04.13-án 15 óra 30 perckor elhárult.

Szeretnénk az RSS-re támaszkodni, de így nem lehet. Tudtok abban segíteni, hogy mi a helyes RSS link (akkor majd a weblapon is javítanotok kellene), vagy mikor lesz ez javítva?

Köszönöm

**Comment by renced42** [comment]
Kedves @zonehun 

Köszönjük a jelzést. Elvileg most már jó. Kérlek nézd meg.

**Comment by zonehun** [comment]
@renced42 köszönöm. Még nem az igazi. Ha most megnézed az RSS-t, akkor a feed-ben rossz sorrendben vannak a hírek. Nem egyeznek a weblapon találhatóval. Szerintem azért, mert a hír utolsó módosítása szerinti sorrendben lehetnek. Az <updated>tag-ből gondolom. 

Ha tudjátok, akkor jó lenne a publikációs dátumot is beletenni az RSS-be és alapértelmezetten aszerint rendezni. 

Ezen kívül az RRS-ben nincsen benne a hír szövege. Csak a címet látom és egy összegzést. Pl:
Cím: Online Számla rendszer interfészszolgáltatás-kiesés és API végpontok lekapcsolása
Tartalom: <![CDATA[ <a href="https://onlineszamla.nav.gov.hu"><img src="https://onlineszamla.nav.gov.hu/files/container/download/online-szamla-logo.png" width="141" height="141" style="width:141px; height:141px; vertical-align: text-top;" /></a>Új tartalom érthető el az Online Számla rendszerben! ]]>

A teljes tartalmat is ki tudjátok tenni esetleg az XML-be? Az nagyon hasznos lenne és ahogy nézem nagyon rövidek szoktak lenni.

Köszönöm szépen!

**Comment by zonehun** [comment]
:) a Github motor értelmeztve a CDATA-ban lévő img linket :)

**Comment by renced42** [comment]
Kedves @zonehun 

Igen ez sajnos azért van mert a feedre a híreket nem sorrendben tették ki :(
A tartalom hiánya már nekem is régi akadásom, rajta vagyunk, de ez most még egyenlőre így marad egy darabig sajnos.

**Comment by zonehun** [comment]
Rendben, akkor addig is a saját belső adminisztrátori felületünkre behúzzuk. 
Ha majd a hírek szövege is benne lesz, akkor a felhasználók felé is publikáljuk.
köszönöm!

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ebben sajnos nem várható változás a közeljövőben, így zárom az issuet.
Köszönjük a megértést.
Üdv
