### ISSUE TITLE
[DEV support] Response status code 503

### ISSUE THREAD

**Issue by Apatullii** [nav-gov-hu/Online-Invoice#861]
Service Response status code 503 from https://api-test.onlineszamla.nav.gov.hu and https://api.onlineszamla.nav.gov.hu
For operations /tokenExchange and /manageInvoice
version of the request 2.0
Everything is worked yesterday.

**Comment by DrotosTot** [comment]
The possibility of the account data service according to XSD version 2.0 in the Online Invoice system was discontinued at midnight on March 31, 2021.

**Comment by Apatullii** [comment]
What can I do to fix it quickly? We need to send the invoice!

**Comment by DrotosTot** [comment]
It is not too easy, there were a lot of changes between 2.0 and 3.0.
V3.0 documentation available at:
https://onlineszamla-test.nav.gov.hu/api/files/container/download/Online%20Szamla_Interfesz%20specifikacio_EN_v3.0.pdf
