### ISSUE TITLE
[FEATURE] Pénzforgalmi ÁFA információ szolgáltatása a QueryTaxpayer tranzakcióban

### ISSUE THREAD

**Issue by janisoft** [nav-gov-hu/Online-Invoice#862]
**Az igény összefoglalása / Summary of the request**
Javaslatom, hogy a QueryTaxpayer tranzakció válaszüzenete tartalmazza pénzforgalmi ÁFA-val kapcsolatos információkat.

**Comment by NTCA-supporter** [comment]
Szia @janisoft !
Az API-n nem tervezünk változást, így zárom az issuet.
A felvetést köszönjük.
Üdv
