### ISSUE TITLE
E-számla teljes adattartalom

### ISSUE THREAD

**Issue by cukabacsi** [nav-gov-hu/Online-Invoice#864]
Sziasztok!
Az xml-es elektronikus számlához a teljes adattartalmat kell megadni a leírás szerint. 
Ez konkrétan mit jelent? Tartalmaznia kell olyan elemeket is, mint például a megjegyzés, bankszámlaszám, stb? Amik nem alapelemei a számlának?
Köszönettel: Nagy József

**Comment by csandazoltan** [comment]
3.0 leírás, 2.6.2-es pont

> Az XSD 3.0 verziója lehetőséget biztosít arra, hogy az adatszolgáltatást az eladó a teljes adattartalmú
> elektronikus számla beküldésével valósítsa meg, ha ez az elektronikus számla éppen az ezen
> dokumentáció szerinti invoiceData.xsd -séma szerinti XML állomány. 

Amit küldesz a NAV felé és xsd helyes, az lesz az elektronikus számla az invoiceData tagban lévő BASE64-es xml

Lényegében, mivel ugyanazt a sablont használja a vevő és az eladó így könnyű xml eszámlát küldeni a NAV felé, mert azt a vevő onnan lekérdezheti és tetszése szerint feldolgozhatja

Érdemes elolvasni a leírást, vannak limitációk

**Comment by cukabacsi** [comment]
Köszönöm a választ, de a leírás ezt a részt, amit kérdeztem, nem fejti ki.
Mi eddig is xsd helyesen küldtük a számlát, beküldtük a megfelelő formában (SHA3-512) a electronicInvoiceHash értéket is.
Tesztben küldtem eszámlaként is, el is fogadta a rendszer (completenessIndicator=true).
De a "Teljes adattartalmú" jelentése érdekelne, hogy ez pontosan mit jelent. 
Küldjük az eladó minden adatát, a vevő minden adatát, a termékek nevét, mennyiségét, mennyiségi egységét, egységárát (nettó), áfakulcsot, a számla nettó, áfa, bruttó értékét, áfa összesítéseket, dátumokat, fizetési módot, árfolyamot, pénznemet.
De például nem küldjük a termékkódot, árengedményt. stb., vagy a bankszámlaszámot,  megjegyzést, mivel ezek nem kötelezőek. 
A lényeg, hogy ha a vevő elfogadja az általunk küldött adatokat, és xsd helyes a beküldés, akkor már minősülhet e-számlának?

**Comment by topybear** [comment]
Úgy gondolkozz, hogy az van a számlán ami az xml-ben elküldésre kerül. Ha abban nincs termékkód, akkor azt nem "írtad rá"  a számlára. Mert az ügyfél csak azokat az adatokat látja, amit beleraktál az xml-be.

**Comment by cukabacsi** [comment]
Így már értem, köszönöm!

**Comment by csandazoltan** [comment]
Azt azért érdemes megjegyezni, hogy NAV-os számlabeküldésnek a formája kötött, ez biztosítja, hogy az eladó és a vevő biztos megértik egymást az xml-es eszámlán keresztül
Vannak opcionális adatok amiket megadhatsz, de nem mindent
A leírásban illetve a invoiceData.xsd-ben van, hogy mit szabad

**Comment by EnokhSys** [comment]
Nem szeretnék egy külön issue-t nyitni, ezért itt tenném fel a kérdést.

Ha egy vevővel megállapodok abban, hogy elektronikus számlázásra térünk át, akkor:
1. Használhatom a NAV OnLine Számlának beküldésre kerülő XML-ben a BASE64-ben elkódolt adatot, amelyre képezek egy SHA3-512-es biztonsági kódot és azt az "electronicInvoiceHash" szegmensben mellékelem a beküldéshez, akkor ez már jogszabályilag hiteles számlának tekinthető, amennyiben a NAV befogadja a számlát.
2. Készíthetek egy olyan pdf-et, amelyen nincs sem digitális aláírás, sem időbélyeg, de amennyiben képzek az elkészített pdf-ről egy SHA3-512-es biztonsági kódot és azt az "electronicInvoiceHash" szegmensben mellékelem a beküldéshez, akkor ez már jogszabályilag hiteles számlának tekinthető, amennyiben a NAV befogadja a számlát.
További feltétel az, hogy a számlát az archiválási jogszabályoknak megfelelően biztosítom a sérthetetlenségét, törlésvédelmét, véletlen megsemmisülését stb., ezt tovább nem részletezem. 

Jól írtam le azt a két lehetőséget, hogy a NAV OnLine Számla rendszere hogyan használható elektronikus számlázás megvalósítására szállító és vevő között?

**Comment by csandazoltan** [comment]
@EnokhSys 
Inkább nyiss egy újat, mert ez "zárva" van már nem biztos, hogy figyelik a NAV-os kollégák és én is kíváncsi vagyok egy hivatalos és pontos válaszra

**Comment by EnokhSys** [comment]
@csandazoltan oké, köszi, megnyitottam.
