### ISSUE TITLE
[Q&A] kozossegi ugylet EU adoszam nelkul

### ISSUE THREAD

**Issue by janisoft** [nav-gov-hu/Online-Invoice#865]
Egy vallalkozas kozossegi ugyletet ugy szamlaz, hogy a partner EU adoszamat egy szabad szoveg mezoben tunteti fel a szamlan, igy a szamlan megjelenik, de az adatszolgaltatasba nem kerul bele. Az AFA tipus KBAET minden tetelnel. A NAV rendszere minden jelzes nelkul DONE statusszal be is fogadja a szamlat.
Ez igy rendben van?

Koszonettel:
Janos

**Comment by omachtandras** [comment]
Vélhetően nincs. Elég sok problémás eset van, amire egyelőre nincs warning, de ígéret szerint lesz rá.

https://github.com/nav-gov-hu/Online-Invoice/issues/847

**Comment by NTCA-tax** [comment]
Ebben az esetben a számla adattartalmilag helyes, az adatszolgáltatás viszont nem. Amennyiben egyébként lenne a közösségi adószámra dedikált mező, de a felhasználó nem azt használja, akkor az adatszolgáltatás hiányosságának az oka a felhasználó nem megfelelő szoftverkezelése...

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezt zárom, mert valóban a #847 issue már ezzel foglalkozik.Ha van még kérdés nyissatok újat kérlek.
Üdv
