### ISSUE TITLE
XML adatkinyerés az onlineszámla.nav.gov.hu felületéről

### ISSUE THREAD

**Issue by richardszabowolt** [nav-gov-hu/Online-Invoice#866]
Sziasztok!

Több partnerünk megkeresése és kérdése alapján érdeklődöm, hogy van lehetőség XML formátumban kinyerni a kiállított számlákat? Néhány könyvelő program kizárólag arra képes, hogy XML formátumban lévő adatot olvasson és azt jelezték, amikor kiválasztják a kívánt időszakra vonatkozó számlákat, az XLSX formátumban kerül letöltésre, más opciót nem tudnak kiválasztani.

Köszönettel,
Richárd

**Comment by renced42** [comment]
Kedves @richardszabowolt 

Az API-n van erre operáció le lehet kérdezni a beküldött adatszolgáltatást.

Számlaadat-szolgáltatás REST API
interfészleírás és fejlesztői dokumentáció

1.8.5 A /queryInvoiceData operáció
A /queryInvoiceData egy számlaszám alapján működő lekérdező operáció, amely a számlán szereplő
kiállító és a vevő oldaláról is használható. Az operáció a megadott számlaszám teljes adattartalmát adja
vissza a válaszban.

**Comment by richardszabowolt** [comment]
Kedves @renced42 köszönöm a gyors választ!

**Comment by NTCA-supporter** [comment]
Sziasztok!

Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
