### ISSUE TITLE
[Q&A] Teszt felület offline?

### ISSUE THREAD

**Issue by annaszilvasi** [nav-gov-hu/Online-Invoice#867]
https://onlineszamla-test.nav.gov.hu/ nem elérhető, valamint a beküldött számlák is visszapattannak.

**Comment by NTCA-supporter** [comment]
Szia @annaszilvasi !
Igen, tervezett karbantartás van. A hírek között ki van publikálva, várhatóan 11:30-tól lesz újra elérhető az alkalmazás.
Üdv

**Comment by annaszilvasi** [comment]
Köszi @NTCA-supporter !
Így, hogy az oldal sem jött be, a híreket sem lehetett látni :-D
