### ISSUE TITLE
[Q&A] Hitelesített elektronikus számla kibocsátása a NAV OnLine Számla segítségével.

### ISSUE THREAD

**Issue by EnokhSys** [nav-gov-hu/Online-Invoice#868]
Sziasztok!

Úgy látom, hogy másokat is érdekel a téma, ezért megerősítést kérnék szépen arra vonatkozóan, hogy jól gondolom-e az alábbiakat.

A v3.0-ás dokumentációjában szó van arról, hogy a NAV OnLine Számla hogyan segíti az elektronikus számlázást, ami tényleg nagy előnyt jelent. A kérdésem tulajdonképpen arra vonatkozik, hogy a jelenlegi jogszabályok szerint, az elektronikus számla mikortól tekinthető hitelesítettnek. Hiszen papíralapú számla esetén a kibocsátó aláírása, elektronikus számla esetén a korábbi jogszabályok szerint a digitális aláírás és az időbélyegző biztosította a hitelesítést, de ez később már nem lett kötelező. 

Ha jól értelmezem a jelenlegi jogszabályokat, tulajdonképpen akkor hiteles egy számla, ha a számla eredetisége, adattartalmának sértetlensége és emberi olvashatósága biztosítva van. Pont.    
Ha egy vevővel megállapodok abban, hogy elektronikus számlázásra térünk át, akkor:

1. Használhatom a NAV OnLine Számlának beküldésre kerülő XML-ben a BASE64-ben elkódolt adatot, amelyre képzek egy SHA3-512-es biztonsági kódot, és azt az "electronicInvoiceHash" szegmensben mellékelem a beküldéshez. Amennyiben a NAV befogadja a számlát, akkor ez már jogszabályilag hiteles elektronikus számlának tekinthető.

2. Készíthetek egy olyan dokumentumot (pdf, doc, jpg... stb), amelyen nincs sem digitális aláírás, sem időbélyeg, de amennyiben képzek az elkészített dokumentumról egy SHA3-512-es biztonsági kódot, és azt az "electronicInvoiceHash" szegmensben mellékelem a beküldéshez, akkor ez már jogszabályilag hiteles számlának tekinthető, amennyiben a NAV befogadja a számlát.

(További feltétel az, hogy az archiválási jogszabályoknak megfelelően biztosítom a számla sérthetetlenségét, törlésvédelmét, véletlen megsemmisülését stb., de ennek már nincs köze a számla hitelességének kérdéséhez, hanem annak megőrzési kötelezettségéhez.)

Jól írtam le azt a két lehetőséget, hogy a NAV OnLine Számla rendszere hogyan segíti a hiteles elektronikus számla kibocsátását?

**Comment by EnokhSys** [comment]
Azt hittem izgalmas téma... :-( 
Senki nem használja még a NAV OnLine Számla által biztosított lehetőséget az elektronikus számlázásra? Esetleg NTCA-tax vagy NTCA-supporter?

**Comment by BeczeT** [comment]
> Azt hittem izgalmas téma... :-(
> Senki nem használja még a NAV OnLine Számla által biztosított lehetőséget az elektronikus számlázásra? Esetleg NTCA-tax vagy NTCA-supporter?
A második esetet amit leírtál használom, az ügyfelek örülnek neki, hogy egyszerűen tudnak e-számlát készíteni. A PDF-et létrehozom, készítek belőle egy hash-t, beleírom az XML-be. Elküldöm email-ben a vevőnek (PDF, hash- ez egyenlőre user szálon megy) és az adósoknak az XML-t (ez meg a háttérben megy).

**Comment by EnokhSys** [comment]
@topybear Köszi szépen a megerősítést. Nálam sajnos a partnereimnél van EDI-számla, PKI-számla, és most lesz OLSZ-számla. Ugyanis annál a partnernél, aki ez utóbbit szeretné bevezetni elektronikus számlázásként, nem jöhet szóba sem az EDI, sem a PKI a speciális ügyviteli folyamatai miatt.

**Comment by EnokhSys** [comment]
@BeczeT Neked is köszönöm a megerősítést, valószínűleg a partnerem legtöbb vevője ezt fogja kérni, de mivel semmiből sem áll megcsinálnom az 1-es módszert, azt is elkészítem, aztán majd a vevő eldönti, hogy melyiket szeretné választani.

**Comment by Rokasan** [comment]
Mi SAP ERP és S4/HANA hoz fejlesztettünk modult, elkészítettük az E-számla verziót is a 2. pont szerint, működik rendesen.

**Comment by EnokhSys** [comment]
@Rokasan Neked is köszönöm!

**Comment by EnokhSys** [comment]
Azt hiszem lezárom a témát, mert ellenvélemény nem jött, csak megerősítés, így rendben vagyunk.
