### ISSUE TITLE
[Q&A] Helyesbítő számla sztornózása után hibaüzenet

### ISSUE THREAD

**Issue by annaszilvasi** [nav-gov-hu/Online-Invoice#869]
Sziasztok!

Az alábbi problémával fordulnék hozzátok.
Az alábbi számlaláncolatot szeretnénk beküldeni:
számla -> helyesbítő számla -> helyesbítő számla stornója -> eredeti számla sztornója.

![image](https://user-images.githubusercontent.com/29543666/116546682-333b2c00-a8f2-11eb-8ceb-d3ea6b75ad3a.png)

A harmadik, azaz a helyesbítő számla sztornózása már nem megy be, INVALID_INVOICE_REFERENCE az error.
1. A számlaláncolat logikája hibás lenne? először az eredeti számlát kéne sztornózni, majd utána a helyesbítőt?
2. Esetleg a referencia számlaszámokkal lenne a gond?

Köszönöm a segítséget előre is.

**Comment by NTCA-supporter** [comment]
Szia!
MODIFY/STORNO esetén mindig az alapszámlára kell hivatkozni. Azért kapod az error-t, mert a módosítószámlára hivatkozol.
Üdv
