### ISSUE TITLE
batchInvoice-on belül invoiceLines [Q&A]

### ISSUE THREAD

**Issue by era910413** [nav-gov-hu/Online-Invoice#87]
A batchinvoice miatt feltöltött példában (Több számla módosítása batchInvoice használatával.xml) az Invoice elemen belül nem szerepel invoiceLines. Ez direkt van így, és így is lesz? Tehát az ilyen típusú módosításoknál nem szükséges/nem kötelező tételadatokat küldeni?

**Comment by Amn3s1a2018** [comment]
A gyakorlatban sokszor (az nem is biztos h legtöbbször) fordul elő ilyen amit a batchInvoice példájában látunk. Valószínűleg ezért választottak ilyen esetet (és nem azért, mert sokkal egyszerűbb volt és gyorsan zárni kellett a ticketet).
Abban az esetben ha módosítással tételek is változnak, akkor nyilván azokat az adatokat is ugyanúgy fel kell adni. A batchInvoice invoice eleme ugyanaz a típusa a normál számla, tehát ugyanazok a kötelezőségek vonatkoznak rá.

**Comment by NTCA-developer** [comment]
Szia @era910413 

Igazából @Amn3s1a2018  már tökéletes választ adott a kérdésre, csak ugyan ezt tudom elismételni máshogy. A példaszámla egy dolog, a séma pedig egy másik. A sémában a batchInvoice mindenféle tartalmi módosítást tud kezelni, a számlasor módosítás is ide tartozik.

Lezárod majd ha nincs több kérdésed?
