### ISSUE TITLE
[Q&A] REQUEST_ID_NOT_UNIQUE

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#870]
Sziasztok!

Ismét egy olyan probléma, ami az élesben néha előjön, de a tesztben nem tudjuk reprodukálni. Azért írom fel, hátha a NAVos fejlesztő kollégáknak gondolatébresztő lehet.

Amikor az éles rendszer terhelt elég ritkán ugyan, de teljesen különböző ügyfeleinknél előfordul, hogy a REQUEST_ID_NOT_UNIQUE választ kapja a programunk.
Egy alkalommal előjött a saját üzemeltetésű felhős környezetünkben is, ezen elindulva tudtuk megkeresni az éles supportot és az ő válaszukat felhasználva tudom írni ezt az issue-t.

Azon az ominózus napon a mi request-ünk 15:41:07.179 ment ki. Nálunk a timeout 60 mp-re van állítva.
Az éles support szerint 15:41:43-kor ugyanezzel az azonosítóval ment egy újabb request.
Mi 100%ig biztosak vagyunk benne, hogy nem küldünk ki dupla requestet semmilyen módon, az azonosító előállítása pedig 100%ig biztosítja az egyediséget.

A logjaink alapján az EREDETI kérésre 15:41:43.948-kor kaptuk meg válaszba a REQUEST_ID_NOT_UNIQUE-t.

Értetlenül állunk a dolog előtt.

(Az éles bejelentésünk száma: e-548695(77) volt.)

Köszönöm.

**Comment by csandazoltan** [comment]
Nem vagyok nav-os csak kíváncsi vagyok. :)

Hogy van biztosítva az egyediség? Tárolt request ID-k és léptetve van, vagy valami random string van időbélyeg alapján?
> Mi 100%ig biztosak vagyunk benne, hogy nem küldünk ki dupla requestet semmilyen módon

Ha egy futó processz mellett elindul egy másik, annak is garantált a saját ID-je?
Olvasatom szerint a requestId a teljes folyamat végén kerül az adószámhoz letárolásra
![image](https://user-images.githubusercontent.com/6756505/116648805-35e36300-a97e-11eb-9820-dc80bbd4483a.png)

Gondolok arra, hogy 
elindul PROCESS1, megkapja ID1 és vár a válaszra
elindul PROCESS2, megkapja ugyanazt az ID1-et 'valamiért' (nem tudom hogy generáljátok a requestID-t)
PROCESS2, hamarabb végez sikeresen, nav bejegyzi ID1-et sikeresnek
PROCESS1 hibára fut később, mert már nem egyedi az ID amivel elindult (nem tudom a nav mikor ellenőrzi az ID-t)

Azért nem tudjátok a teszten ezt reprodukálni, mert egyszerre 1 ember tesztel egy szálon
DE csak tapogatózok a sötétben, mert nem tudom ti hogy generáljátok az ID-t és a nav mikor ellenőrzi az egyediségét annak
Ha mindkét oldal a sikeresség végén jegyzi az egyedi azonosítókat, akkor az nagyon könnyen bekavarodik a párhuzamos lekérésekbe

**Comment by omachtandras** [comment]
@csandazoltan : biztosítva van, hogy egy adótörzsszámú adatbázisra csak egyetlen NAVval kommunikáló szolgáltatás kapcsolódhasson (erről egyébként a saját felhős szolgáltatásunk esetén szintén 100%ig biztosak vagyunk, hogy így van). Egy szolgáltatáson belül pedig biztosítva  van, hogy a requestID-ben szereplő tagok legalább egyike állandóan változzon (sync-es futó sorszám).

Eredetileg kértük a supporttól a két request-et is, hogy lássuk, de azt nem küldték el. Most kértük, hogy legalább azt mondják meg, hogy azonos volt-e a két request.

**Comment by EPluribusUnum** [comment]
Az hogy a 60sec-es timeout idő előtt volt a NAVtól válasz (~36 sec) és hogy dupla request volt arra utal, hogy NAV házon belül valamelyik két layer-e között csinálja a request ismétlést (gyanúsan ~30 sec után) és így saját maga okozza a REQUEST_ID_NOT_UNIQUE-ot.

**Comment by csandazoltan** [comment]
@EPluribusUnum Ha ilyen lenne, akkor ez egy nagyobb rendszerszíntű probléma lenne és mindenki tele lenne REQUEST_ID_NOT_UNIQUE hibákkal.
Nekem rendszeresen percek felett vannak a válaszaim, pláne nagy adatlekérésnél

Nem vagyok meggyőzve arról, hogy a szerver oldalon lenne ilyen gond

Kíváncsi vagyok a hivatalos válaszra és a requestek nyers xml-elére, hogy lássuk a request ID-ket

**Comment by renced42** [comment]
Kedves @EPluribusUnum 

"NAV házon belül valamelyik két layer-e között csinálja a request ismétlést"

Ez a hiba szinkron. Vagy van ilyen - adott adószámra, adott időn belül - requestID vagy nincs. Ez tuti egyedi hiba. Nyilván meg kell vizsgálni.

**Comment by kabelnet2** [comment]
Mit kapsz vissza, ha ilyen esetben (REQUEST_ID_NOT_UNIQUE) kiadsz egy status kérést az állítólag már létező azonosítóval? Vagy utólag rákeresel az azonosítóra a Web-es felületen? Ha van találat, akkor tényleg létezik és talán kiderül, mi hozta létre.

**Comment by EPluribusUnum** [comment]
@kabelnet2 , requestId-re nem lehet lekéderni. Nem a transactionId-ről van szó, hanem a header-ben lévő requestId-ről.
Amúgy hiba esetén x idő múlva újra próbálkozás van (send hívás 1 percenként, query/list hívás 15 percenként).

**Comment by kabelnet2** [comment]
Igaz, bocs.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezzel kapcsolatban van még kérdés? Ha nincs, kérlek zárjátok. A mi oldalunkon ez elég egyértelmű validáció, így ezt én is kliens oldali problémának gondolom.

Üdv

**Comment by omachtandras** [comment]
Lezárom.
Az éles supporttal nem jutottunk semmire. 30 naponta válaszoltak, de nem teljeskörűen, az idő meg csak ment, túl sok volt a beletett energia kecsegtető eredmény nélkül.
Elengedtük a kérdést.
