### ISSUE TITLE
[Q&A] Mi az a KAÜ azonosítás?

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#871]
"Az Online Számla rendszerben hamarosan bevezetjük a KAÜ-azonosítást, amit a bevezetés előtt az Online Számla rendszer tesztportálján tesztelünk."

Mi az a KAÜ azonosítás és ez miképp érinti majd később a gépi interfészt?

**Comment by NTCA-supporter** [comment]
Szia @nbeeps2 !
https://kau.gov.hu/informacio/kau
A gépi interfészt nem érinti. Egyedül a webes bejelentkezésnél lesz változás, de KAÜ-n belül is lehet ügyfélkapuval bejelentkezni, így a felhasználók számára ez gyakorlatilag semmit teendőt nem jelent.
Üdv

**Comment by csandazoltan** [comment]
Sajnos a dokumentáció sem érhető el így :)

**Comment by tkelemen73** [comment]
Sziasztok,
érdeklődnék, hogy mikor várható, hogy a tesztrendszer felülete ismét elérhetővé váljon? Az "Online Számla tesztportál elérésének átmeneti felfüggesztése" ma kezdődött 4 hete, kérdésem, hogy meddig fog még tartani? Technikai érvénytelenítést tesztelné, próbálná ki az egyik ügyfelünk, de mivel nincs hol jóváhagyni a beküldött technikai érvénytelenítéseket...
Üdv
T.

**Comment by Macskafarka** [comment]
Van, ahol azért nem vesznek át egy fejlesztést, mert nem nem tudják tesztelni.
A NAV teszt rendszer működtetésének nincs jogszabályi kötelezettsége, a válaszadásra sincs semmi előírás.
Kizárólag akkor és addig áll érdekükben működtetni, ameddig az itteni közösségből profitálnak. Probléma feltárást, véleményt, megoldási ötleteket, tesztelést stb.
Ez nagyon szomorú, de előre lehetett látni. Világos jogszabályi keretek és előírások kellenek ahhoz, hogy a NAV-ot rászorítsák a kommunikációra.  Mostanra már számos olyan probléma került elő, amely a jelenlegi keretek között megoldhatatlannak látszik. A NAV-nak nem érdeke, vagy maga sem tudja rá a választ.
Mondtam már, hogy kár a krokodilt simogatni.
Leült ez az egész dolog, és itt maradtunk árván, rútul, nyomorultul magunkra hagyva......

**Comment by Macskafarka** [comment]
A kérdésre a válasz: A KAÜ azonosítás egy ürügy arra, hogy lekapcsoljanak egy rendszert.
Először még azt írták, hogy csak pár órára. Ezt a szöveget azóta eltüntették, ahogy szokták, ha egy tájékoztatásuk már kínossá vált.
Ha a belépés azonosítást lecserélik, az olyan, mintha egy lakáson zárat cserélnek.
Azonban egy zárcsere miatt nem lehet egy hónapig megakadályozni a lakás használatát. 
Ürügy, ürügy, ürügy. Valótlan információ közlése, a valós ok elhallgatása.

**Comment by janisoft** [comment]
Szaisztok!
Hol lehet a teszt rendszerhez technikai felhasználót regisztrálni? A teszt weboldal jó ideje nem elérhető.
Köszi!

**Comment by renced42** [comment]
Kedves @tkelemen73, @janisoft

Az Online Számla rendszerbe olyan új funkcionalitások kerülnek be felhasználókezelés és authentikáció oldalon, amelyet jogszabályi kötelezettség miatt vizsgálni szükséges az erre hivatott szervezetnek.
A vizsgálat ideje alatt a rendszer frontend felületét zárva kell tartani. A vizsgálatok olyan szakaszba léptek, hogy a környezet rövid időn belül megnyitható, azonban a hatósági tesztelés átmenetileg tovább folytatódik a megnyitást követően. Emiatt előfordulhatnak lassulások, esetleg szolgáltatás kiesés is.
A vizsgálatok lezárásáig kérjük a türelmeteket.

**Comment by Rokasan** [comment]
tesztportál nélkül az új ügyfeleink most induló SAP rendszerükhöz nem tudnak teszt techhnikai usert generálni, nem tudnak tesztelni. Tesztelés és ellenőrzés nélkül semmilyen módosítás / fejlesztés / beállítás nem élesíthető.

A teszt rendszer lekapcsolása miatt tehát nem tudanak eleget tenni jogszabályi kötelezettségüknek, miközben a korábbi türelmi időszaknak már vége. A tesztrendszer újraindításának dátuma nem ismert, a projekteket tervezni lehetetlen.

Nem gondolnám, hogy ez korrekt eljárás a NAV részéről.

Megértem, hogy a NAV oldalon is folyik fejlesztés, tesztelés, ellenőrzés, de véleményem szerint ez nem érintheti az a NAV teszt rendszert, amely arra hivatott, hogy az adóalanyok biztonsággal üzembe tudják helyezni a saját rendszereiket, el tudják indítani számlázó moduljaikat.

**Comment by attilaszoke** [comment]
Üdvözlet,  
Van esetleg valami várható időpont, hogy mikortól lehet az Online Test frontendet használni?
Köszönettel,

**Comment by NTCA-supporter** [comment]
Sziasztok!

A teszt rendszer már elérhető régóta.
Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
