### ISSUE TITLE
[Q&A] Hibás adókulcsot adtam meg, hogyan tudom javítani?

### ISSUE THREAD

**Issue by JamborTimea** [nav-gov-hu/Online-Invoice#872]
Jó napot kívánok!

Szeretném a segítségüket kérni az alábbi témában:

Ha egy számlán egy tételnek hibás adókulcsot adtam meg, akkor hogyan tudom javítani?
Sztornó számlát kell készíteni vagy helyesbítő számlát kell használni?

Ha helyesbítőszámlát kell használni akkor, mi kell szerepjen a számlán?

Tehát pl. az eredeti számlán van: Termék 1 db  2000 HUF nettó, áfakulcs: EUFAD37.

A helyesbítő számlán lesz: Termék 1 db 2000 HUF nettó, áfakulcs: KBAET és az adatszolgáltatásban beküldjük az eredeti tételre való hivatkozást és az új adókulcsot és a többit (pl. mennyiség, nettó egység ár) nullás értékkel? 

(Az itt megtalálható: https://onlineszamla.nav.gov.hu/api/files/container/download/Peldaszamlak_v3.0.zip: teteladatok modositasa.xml alapján próbáltam értelmezni, hogy mit kell a mi esetünkben csinálni.)

Ilyen esetben a lineOperation=”MODIFY" kell használni vagy a lineOperation=”CREATE”. Ugyancsak a fenti dokumentációban olvastam, hogy: 

"A módosító okiratokról nyújtott adatszolgáltatásban a lineOperation=”MODIFY” típusú műveleteket csak abban az esetben javasolt alkalmazni, ha a módosítás a számla szöveg, vagy dátum típusú adatait érinti (pl. terméknév, cikkszám, mennyiségi egység). Számszerű vagy mennyiségi adatok módosításakor a lineOperation=”MODIFY” típusú műveletek használata kerülendő, helyette a lineOperation=”CREATE” típusú megoldások használata ajánlott". Az adókulcs, melyik kategóriába tartozik?

Segítségüket előre is nagyon szépen köszönöm!

**Comment by NTCA-tax** [comment]
A CREATE lenne az egyértelműbb megoldás mint számlaképen, mint pedig adatszolgáltatásban is. Ekkor a módosító számla két tételsort fog tartalmazni:
1. tételsor: -2000 Ft, áfakulcs EUFAD37
2. tételsor: +2000 Ft, áfakulcs KBAET

**Comment by JamborTimea** [comment]
Köszönöm szépen a választ!
