### ISSUE TITLE
VATEXEMPTION  in xml file.

### ISSUE THREAD

**Issue by vkozakevich** [nav-gov-hu/Online-Invoice#873]
The company provides transportation services. In case of import of the goods from third country to Hungary or EU there is a VAT exemption under paragraph 93 of VAT Act. Which VATEXEMPTION case have to be indicated in xml file?

**Comment by NTCA-supporter** [comment]
Hi @vkozakevich !
Please check the documentation here: https://onlineszamla.nav.gov.hu/api/files/container/download/Online%20Szamla_Interfesz%20specifikacio_EN_v3.0.pdf

The table on page 126-127 contains the desctiptions of the cases.
Br

**Comment by NTCA-supporter** [comment]
I close the issue due to inactivity. Feel free to reopen it.
Br
