### ISSUE TITLE
BAD_REQUEST TokenExchange random

### ISSUE THREAD

**Issue by warchef** [nav-gov-hu/Online-Invoice#874]
Sziasztok!

Erre a requestId-ra rá tudtok nézni (ÉLES)? R2021050516275410687

Néhány esetben, legutoljára pl a fentire (Tokenkérés) HTTP 400 jön vissza és nem tudom, hogy miért.
Nem történt módosítás a szoftverben.

Köszi,
Marci

**Comment by NTCA-supporter** [comment]
Szia @warchef !
Éles környezetet nem suportáljuk githubon.
https://www.nav.gov.hu/nav/e-ugyfsz Itt tudsz hivatalos úton érdeklődni.
A pontos hibaüzenetnek érdemes utánanézni, gondolom nem csak http 400-at kapsz.
Zárom az issuet.
Üdv
