### ISSUE TITLE
[Q&A] Ingyenes átadás áfás számlájára példa kellene

### ISSUE THREAD

**Issue by Macskafarka** [nav-gov-hu/Online-Invoice#875]
Tisztelt NAV!
Többször elhangzott kérésként az, hogy tegyenek közzé DATA példát +XML-t azokra az esetekre, amikor ingyenes értékesítés történik.
Különleges esetnek számít az ingyenes ügyletek kezelése. Ezen eseteket az áfatörvény 11. (termékértékesítés) és 14. (szolgáltatásnyújtás) paragrafusa tartalmazza. Lényegében akkor tekintik az ingyenes termékátadásokat, szolgáltatásnyújtásokat adóköteles ügyletnek, ha az adóalany az ügylettel kapcsolatban korábban adólevonási jogot érvényesített, és az ingyenes ügylet általában vállalkozásidegen célból történik.
A jogszabályból azt a megoldást lehet levezetni, hogy az ingyenes ügyletek vonatkozásában is számla kerüljön kibocsátásra.
A NAV 3.0 specije a vatAmountMismatch között említi ezeket az eseteket: „REFUNDABLE_VAT: az áfa felszámítása a 11. vagy 14. § alapján történt és az áfát a számla címzettjének meg kell térítenie és NONREFUNDABLE_VAT: az áfa felszámítása a 11. vagy 14. § alapján történt és az áfát a számla címzettjének nem kell megtérítenie”.
Kérem, hogy mielőbb tegyenek közzé DATA példát és hozzá kapcsolódó XML-t mindkét esetre vonatkozóan.
Kérésem azon alapul, hogy a NAV-nak törvényi kötelezettsége az adózókat támogatni abban, hogy a jogszabályi kötelezettségeiket teljesíteni tudják. 
Nagyban segítené a munkánkat, ha lenne minta előttünk.

**Comment by konyisoft** [comment]
Sziasztok!
Nem is beszélve a 11. § b) "ha az adóalany - vállalkozásának céljára tekintettel - más tulajdonába ingyenesen enged át árumintát és kis értékű terméket" - esetén az adatszolgáltatás milyen áfa kóddal történjen?

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezt az issuet zárom, mert van már ezzel kapcsolatban: #655 
Üdv
