### ISSUE TITLE
Miért nem ad választ az éles szerver a szállítói számlák listázására QueryInvoiceDigestRequest-tel?  [Q&A]

### ISSUE THREAD

**Issue by SiposElek** [nav-gov-hu/Online-Invoice#877]
Sziasztok!

Tegnap óta tapasztaljuk, és sok ügyfelünk jelezte, hogy a QueryInvoiceDigestRequest szolgáltatás invoiceDirection = IINBOUND, és insDate->dateTimeFrom/dateTimeTo paraméterekkel lekérdezve nem ad választ az éles szerveren! Elég nagy problémát okoz ez, mert a bejövő számlákat nem lehet listázni semmilyen időintervallumra az adatszolgáltatás lejelentésének időpontjára vonatkozóan. A keltére lekérdezés működik, de nagyon nem szerencsés ez a lekérdezési paraméter a lejelentés időpontja helyett, mivel így kimaradhatnak számlák a lekérdezésből, ha korábbi keltezésű a számla, mint az adatszolgáltatás dátuma. Amikor a könyvelők lekérdeznek egy intervallumot a keltére, azt az intervallumot nem szokták ismét lekérdezni, mert egyszer már lekérdezték, de mégis lehet, sajnos, hogy a lejelentés dátumához képest korábbi keltezésű számlákat jelentenek le. Eddig ebből nem volt probléma, most lesz, sajnos, ráadásul emiatt módosítani kellett a programunkon, hogy lehessen kelte szerint is lekérdezni.

A kérdésünk az lenne, hogy miért nem működik az eddig jól működő szállító számlák listájának lekérdezése? Továbbá számíthatunk-e rá, hogy hamarosan jól, megbízhatóan fog-e működni újra? Még egy kérdés, a lekérdezés timeout-ja azért van, mert a kérés teljesítése, az adatok keresése sokkal tovább tart insDate szerinti lekérdezésnél, mint invoiceIssueDate szerinti lekérdezésnél, és ha igen, akkor ennek mi az oka?

Előre is köszönöm a választ.

**Comment by renced42** [comment]
Kedves @SiposElek 
Mijen lekérdezési intervallumot adsz meg?

**Comment by SiposElek** [comment]
> Kedves @SiposElek
> Milyen lekérdezési intervallumot adsz meg?

Semmilyen intervallumra nem működik a fenti paraméterekkel a lekérdezés insDate intervallum megadása esetén éles szerveren.  A kimenő számlák lekérdezése megy éles szerveren, a teszt szerveren pedig mindkettő jól működik. A programunkon nem változtattunk, korábban ez jól működött, vagyis kaptunk választ elfogadható időn belül, most semmilyen válasz nem jön.

**Comment by renced42** [comment]
Kedves @SiposElek, @veerede 

Köszönjük a jelzést a kollégák már vizsgálják a problémát. Úgy látszik, hogy azt API-n ez a lekérdezés érintett a problémával.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Kikerült élesre egy optimalizálás, kérlek majd jelezzetek vissza, főleg a vevő oldali lekérdezések kapcsán.
Nézzük mi is, de több szem többet lát.
Köszi a türelmet!

**Comment by trappoti** [comment]
Sziasztok!

Igen, rövid tesztem alapján újra kapok választ a szállítói számlák lekérésére (QueryInvoiceDigestRequest, insDate szűréssel). Köszönjük a javítást!

**Comment by SiposElek** [comment]
Sziasztok!

Úgy néz ki, hogy sikerült a javítás, mert alaposan leteszteltük a programunkból, és most már gyorsan megkapjuk a szállítói számlák listáját. Egyébként tegnap a javítás előtt az Online Invoice Test Tool-lal sem ment ez a lekérés éles szerveren 6000 ms POST sleep time-mal sem. Lefagyott tőle a teszt program. Most gyorsan választ kap a teszt program is 1000 ms sleep time-ra is.
Köszönjük a javítást!
Lezárom az issue-t.
