### ISSUE TITLE
[FEATURE] advanceIndicator mező kötelezősége

### ISSUE THREAD

**Issue by Amn3s1a2018** [nav-gov-hu/Online-Invoice#88]
Az előleg és végszámlák esetén jelölhető, hogy mely tételek azok amik előlegként ill. korábban kapott előleg elszámolása miatt szerepelnek a számlán. A mező jelölése minOccurs="0" ami a gyakorlatban azt jelenti, hogy az adat közlése opcionális. Ez azt eredményezi, hogy az adatszolgáltató
- előleg tételben küldi az advanceIndicator=true-t egyéb esetben semmit
- advanceIndicator=true/false minden tételben következetesen
- nem küld semmit  (akár figyelmetlenségből vagy mert úgy értelmezi – helytelenül –, hogy nem kötelező a mező)

A gyakorlatban a fentiek mindegyike, sőt tetszőleges kombinációja is előfordul, akár többféle programok használata, akár a verziók közti eltérések miatt. A harmadik ponthoz, a fölösleges köröket elkerülendő még hivatkoznék a [kérdések/válaszok](https://onlineszamla.nav.gov.hu/kerdesek_es_valaszok) „32. kérdés: Hogyan kell teljesíteni az előleg- és végszámla esetén az online adatszolgáltatást” kezdetű részre.

Ez már talán az 1.1-es verzióban is probléma, ha valaki a NAV-nál össze akar vetni egy-egy visszaigénylést a betöltött számlákkal. A probléma 2.0-től kezdve az egymás számláit feldolgozó vállalkozásoknál is megjelenik majd és ahogy az első hibák kiderülnek valószínűleg önmagától tisztul is a környezet.

Jó lenne valahogy tisztázni a kérdést, akár a mező kötelezővé tételével, az előlegszámla/végszámla azonosításával a számlafejben és az összefüggések vizsgálatával, vagy legalább az xsd dokumentációs részében jelezve, hogy miről van szó... (igen, tudom, az api dokumentáció már most is tartalmaz erre vonatkozóan minimális információt)

**Comment by NTCA-developer** [comment]
Szia @Amn3s1a2018 

A probléma valid és sokkal általánosabb is, mint ahogy a kérdéseben szerepel. Sajnos a boolean tagek elsöprő többsége három értékű. Ebben a konstellációban a null és a false ekvivalens, az igazi különbség csak a true esetében van, ahogy te is írod.

Ezt annó mi is jeleztük még az 1.0 előtt, de akkor nem tudtunk túljutni ezen a problémán. Ennek az igazi feloldása az lehetne, hogy az összes boolean tag kötelező, de ezt a szakmai terület nem fogja engedni. Ennek hiányában csak a default értékkel tudunk némi értelmet adni ennek (minden boolean default false), de érdemi különbséget ez sem okoz.

Az a problémám, hogy ha a minOcc 0-át nem lehet kivenni a sémából, akkor nincs ötletem a megoldásra.

**Comment by Amn3s1a2018** [comment]
Amit mindenféle konfliktus nélkül meg lehet csinálni

1. Az xsd leíró mezőbe szövegesen jelezni, hogy a minOcc 0 csak technikai okból van, kell a mező ha releváns. Ezt akár minden ilyen bool megkaphatja.
1. Ha üres a mező az ellenőrzés során egy warn, ha valószínűsíthető a hiba. Ilyen pl az előzmény nélküli számla, negatív tételekkel, ami persze lehet sima kedvezmény is, de ha a számla pont a „kedvezmény” miatt leesne 100e Ft áfa korlát alá, és mégis küldik, az gyanús.

A korrekt egy valódi felsorolás lenne talán, vagy betenni az áru / szolgáltatás felsorolásba, hogy mindent megegyszer egy előleg jelöléssel.

**Comment by NTCA-developer** [comment]
Szia @Amn3s1a2018 

Reagálok.

> kell a mező ha releváns.

Szerintem ezt a II. számú melléklete a dokumentációnak már megugrotta.

A WARN nem fog menni. A szakma alapelve, hogy fals pozitív warning ne legyen, tehát csak akkor dobjuk ha megalapozottan az mondható, hogy valami gond van. A negatív tételes számla (főleg ha előzmény nélküli, aminek vannak olyan alakzatai amit a törvény megenged de te informatikailag semmire sem mész vele) túl általános, nem fér bele ebbe a körbe.

Tényleg ott vagyok amit az elején írtam: a jelenlegi szabályok szerint ennek nem látom a feloldását. Az mindegy, hogy hova írom ezt le, a sémába, a doksiba vagy akár mindkettőbe, a minOcc 0-ás boolean tagek akkor is háromértékűek maradnak.

**Comment by Amn3s1a2018** [comment]
Akkor ezt itt lezárom :(

[//]: # (de nem örülünk)
