### ISSUE TITLE
[Q&A] Elektronikus számla - módosító számla elutasításra kerül

### ISSUE THREAD

**Issue by WittmannWien** [nav-gov-hu/Online-Invoice#880]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Kedves Nav Support,

a mai napon próbálkoztam elektronikus XML számlával és módosító számlával.
Az eredeti számla rendben befogadásra is került. (Domestic customer; completenessIndicatur= true; invoiceAppearance=Electronic)
Transakció: 3DH734HLP0T3I93G

Amint készítek ehhez a számlához egy jóváírást, a jóváírás azonnal alutasításra kerül a következö hibaüzenettel:
<ns2:validationErrorCode>INVOICE_REFERENCE_NOT_EXPECTED</ns2:validationErrorCode>
        <ns2:message>Eredeti számlára történő hivatkozás alapszámla esetén nem adható meg.</ns2:message>

Nem igazán értem, miért jön ez a hibaüzenet.
Az XML rendben tartalmazza az invoiceReference-nél az eredeti elektronikus számlaként lejelentett és visszaigazolt számlát.
Transakció: 3DH73WXB5UZE2O03
A jóváírás szintén completenessIndicator=true; invoiceAppearance=Electronic értékekkel készült, mint írtam reference információk az eredeti számlára rendben vannak, eredeti számla lejelentve és visszaigazolva.
Kicsit el vagyok veszve, hol lehet a gond.

Meg tudnátok nézni, mi a baj?
Elöre is köszönöm.
Üdv
Péter

**Comment by topybear** [comment]
A módosítón az invoiceOperation értéke MODIFY?

**Comment by WittmannWien** [comment]
Szuper, köszi a tippet. Most látom hogy az ideiglenes kommunikációs program, ami adatbeküldésre és lehívásra használok hibás invoiceOperation-t küld.
Create-tel fut neki, emiatt van a hiba.
Háhá.
Erre nem is gondoltam, abból indultam ki hogy helyes az InvoiceOperation. Èn naiv.
Köszi szépen.
