### ISSUE TITLE
2019 óta rossz adószámra számlázás megoldása (?)

### ISSUE THREAD

**Issue by szecsenyizoltan** [nav-gov-hu/Online-Invoice#881]
A partner a vevőjénél 2019 óta úgy számláz, hogy a vevőjénél az adószám megegyezik az eladóéval (vagyis saját magával). 
Mi a teendő ennek a megoldására?

**Comment by Macskafarka** [comment]
Az eladónál annyi a teendő, hogy az ezt követően készülő számláinál helyesen fogja megadni a vevőjének az adószámát.
A számla befogadó nem helyezheti levonásba azon számláinak áfa tartalmát, amelyen nincs rajta az ő adószáma .
Ha ezt nem vette észre, az az ő baja.
Ha olyan számlák áfáját helyezte levonásba, amelyen nem szerepelt az adószáma, akkor áfa önrevíziókat kell végeznie + büntit fizetnie. 
Ja és a vevő szabaduljon meg azon szakembereitől, akiknek dolga lett volna ezt észrevenni. Ez egyébként javasolt a számlakiállítónál is.
Szakmailag ez akkora tévedés, mintha egy autószerelő éveken keresztül a kormánykereket szerelte volna fel a autókarék helyett, és ezt sem ő, sem a vevője nem vette észre.

**Comment by betasofthu** [comment]
Szerintem lehet módosítani a téves adószámot tartalmazó  számlákat egy módosító számlával, természetesen vevőnként. A módosító számlának tartalmazni kell az eredeti számlára való hivatkozást. Az adóhivatal szerint ez csak a számlaszám lehet. Korábban egy adószakértő azt mondtam, hogy mivel az áfa törvény csak "hivatkozást ír elő", lehet úgy is hivatkozni. hogy a pl.: "a 2019 évi összes számla". Ha nem tudjátok felsorolni a számlaszámokat, akkor ez utóbbi megoldást ellenőrzéskor meg kell védeni. Ezt számlázó programmal is meg lehet csinálni, de lehetőség van más szigorú számadás alá vont számlázási módon is elvégezni, például kézi számával. Talán még az adóhivatal online számlázója is megcsinálja.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Ezzel kapcsolatban van még kérdés? Ha nincs, kérlek zárjátok.

Üdv
