### ISSUE TITLE
OPG számlák migrálása 3.0-ba [Q&A]

### ISSUE THREAD

**Issue by vbela75** [nav-gov-hu/Online-Invoice#883]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Azt szeretném kérdezni? Mikorra várható az online pénztárgép rendszerben keletkező számlák áttöltése a 3.0-ba. Erről már több nyilvános rendezvényen is nyilatkoztak a NAV képviselői. A 3.0 dokumentációban is szerepel az OPG jelölés. Nagyon sok ügyfél kérdezi mert nagyon várnák és nem tudunk semmilyen időpontot kommunikálni. A 2021 Q3-tól tervezett ÁFA tervezet bevezetésére jó lenne ha Mi is látnánk ezeket az adatokat ez volt az ígéret.

**Comment by vbela75** [comment]
Kedves @NTCA-supporter !

Erre kaphatnék választ?

**Comment by NTCA-supporter** [comment]
Szia @vbela75 !
A #411 erről szól, így ezt zárom. 
Üdv
