### ISSUE TITLE
[DEV support] INVALID_REQUEST_SIGNATURE

### ISSUE THREAD

**Issue by tib99** [nav-gov-hu/Online-Invoice#884]
**Környezet / Environment**
[x] https://onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[X] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
ID3566120210603145339670Q

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Sziasztok

Meg tudnátok nézni, hogy mi lehet a probléma, az ÉLES rendszerben nem tudjuk egy cégnek már a második technikai felhasználóját használni mert INVALID_REQUEST_SIGNATURE választ kapunk. 
Az alkalmazást sok helyen használják sehol nem volt eddig ilyen probléma de ennél a cégnél nem tudjuk használni a szolgáltatást. Nem a jelszóval vagy a kulccsal van a baj mert ha az rossz akkor más hibát kapunk.
Mondok egy request id, ha rá tudnák nézni jó lenne: 
   <requestId>ID3566120210603145339670Q</requestId>
    <timestamp>2021-06-03T14:53:39.670Z</timestamp>
Köszönöm

**Comment by NTCA-supporter** [comment]
Szia @tib99 !
Itt éles rendszert nem supportálunk.
Ide tudsz küldeni levelet: https://www.nav.gov.hu/nav/e-ugyfsz/e-ugyfsz.html
Egyébként ha már userrel jó, tehát a signature számolás rendben van, akkor csak az lehet, hogy vagy a kulcs vagy jelszó változott.
Üdv

**Comment by tib99** [comment]
Köszönöm
