### ISSUE TITLE
[Q&A] Lekérdező funkció NAV online felületről 

### ISSUE THREAD

**Issue by lazaralexandra** [nav-gov-hu/Online-Invoice#886]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Több kérdésem, illetve felvetésem lenne
1. A letöltésben nem szerepel a self-billing indicator, ami fontos lenne, hogy tudjuk, hogy a vevő küldi be az SBI számlát.
2. Vevőnév alapján történő keresés nem túl hatékony, illetve bizonyos esetekben nem jött le az összes számla ha a névből a min. 5 karakter alapján próbáltuk letölteni, számlaszámra hivatkozva viszont lejön az adott számla. Van itt valami megkötés?
3. A letöltésben az adószám alapján történő keresés csak magyar adószám 1. 8 száma alapján lehetséges. Mi pedig zömében EU-s adószámhoz kapcsolódó ügyleteket szeretnénk lekérdezni. Mikor fog működni, hogy az adószám, ne csak magyar adószámot jelentsen?
Hosszú távon 
API queryInvoiceData lesz a megoldás, de ahhoz fejlesztés kell...

Köszönöm: Lázár Alexandra

**Comment by lazaralexandra** [comment]
Kérdés továbbra is él, mivel a fejlesztés a letöltésre több időt vesz igénybe. 

Köszönöm: Lázár Alexandra

**Comment by lazaralexandra** [comment]
Még egy kérdés, invoicedigestnél hogy tudok szűrni csak a self-billing számlákra, amit a vevő számláz felénk?

Köszönöm: Lázár Alexandra

**Comment by dkekesi** [comment]
> Még egy kérdés, invoicedigestnél hogy tudok szűrni csak a self-billing számlákra, amit a vevő számláz felénk?
Sajnos sehogy, mert az nem a digest-ben van, hanem az invoiceData-ban, azaz a teljes adattartalmat le kell tölteni és abból kiolvasni.

**Comment by NTCA-supporter** [comment]
Szia @lazaralexandra !

1: mit értesz letöltés alatt? Kérlek pontosítsd.
2: erre pedig példát írj kérlek, hogy milyen vevőnevet milyen szűrési értékkel nem találtunk. Esetleg egy tesztrendszerbeli számlát is küldhetsz.
3: itt sem tudom mit értesz letöltés alatt. Az a mező amit említesz, mindig a magyar adószámra fog keresni. Az, hogy esetleg egy új keresőmezőt felveszünk külön az EU-s adószámra megoldhatónak látom a jövőben.
+1: a queryInvoiceDigest operációban nem tudsz erre a jelölőre és ezen az API-n nem is fogunk változtatni.

Üdv

**Comment by lazaralexandra** [comment]
1., 2., 3.  kérdés mind a NAV online felület lekérdezés funkciójára vonatkozott - kimenő számlák - Szűrési feltételek. 
Amit írtam vevőnév min. 5 karakterével lekérdezni nem egyértelműen azonosítja a vevőt, ha ráadásul másképp vannak a vevőnevek a különböző cégeinkben rögzítve: AG vagy AKTIENGESELLSCHAFT. Ezért lenne fontos, hogy ne csak magyar adószámra lehessen szűrni, hanem szűrési feltételek akkor bővüljenek az EU-s adószámra is és ha kell külföldire is. Ez egyelőre még nem működik, de fontos lenne.
Mindkét esetben, bejövő és kimenő számlák esetében is pl. ha 1 hónap adatait akarnánk lekérdezni, akkor lejöna lista, viszont kiexportálni már nem tudjuk az adatokat! 9000 rekordot nem lehet kiexportálni! Hiba: Túl sok találat! Szűkítsen a keresési listán.
Ez szintén fontos lenne, mivel itt nem akarnánk szállítónként (adószámmal vagy névvel), hanem egyben letöltenénk a ránk számlázott adatokat.

Köszönöm: Lázár Alexandra

**Comment by dkekesi** [comment]
Kedves Alexandra!
A profilomban találja elérhetőségeimet. Lehet, hogy tudunk segíteni Önnek.
Üdv,Dani

**Comment by lazaralexandra** [comment]
A kérdés, illetve kérés még mindig él. A kimenő számlák - szűrési feltételei továbbra sem változtak. Arra jó lenne valami ígéret.

Köszi: Lázár Alexandra

**Comment by NTCA-supporter** [comment]
Kedves @lazaralexandra !
Megértettem a kérdéseket, azonban nincs tervben ilyen jellegű módosítás a közeljövőben, így kérlek a jelenlegi funkciókkal próbáld használni a felületet. Ha nincs további kérdés, kérlek zárd az issuet.
Üdv
