### ISSUE TITLE
[Q&A] Előlegszámla módosító számlája

### ISSUE THREAD

**Issue by JamborTimea** [nav-gov-hu/Online-Invoice#889]
Készítettem egy előlegszámlát - amelyen van egy elrontott előlegtétel - ekkor készítek egy módosító számlát, ahol javítom az előlegtételt, ilyen esetbe a módosító számlán is meg kell jelenjen az <advanceIndicator>true</advanceIndicator> tag, mivel előlegtételt javítok?

pl. Előlegszámla tétele: Előleg 1000 HUF
     Módosító számla tétele: Előleg -1000 HUF
                                               Előleg 2000 HUF
                                               
Válaszukat előre is nagyon szépen köszönöm!

**Comment by betasofthu** [comment]
Nekem válaszolt NTCA-tax hasonló kérdésre itt #367
A  stornó illetve módosító tétel is előleg jellegű.

**Comment by JamborTimea** [comment]
@betasofthu köszi szépen a választ!
