### ISSUE TITLE
[DOC] Apró elírás az API dokumentációban

### ISSUE THREAD

**Issue by bcdel** [nav-gov-hu/Online-Invoice#89]
**A hibás dokumentum neve / Document name containing the error**
Onlineszamla API dokumentació Mindkét nyelven (EN/HU)

**Oldalszám / Page number**
EN: 157 HU: 147

**A dokumentációs hiba leírása / Description of the documentation error**
/manageO  -> /manageInvoice O

**Comment by NTCA-developer** [comment]
Köszönjük, javítottuk. A következő publikált verzióban benne lesz.

**Comment by NTCA-developer** [comment]
Szia!

Kikerült a teszt és éles környezetre a frissített interfész dokumentáció.
