### ISSUE TITLE
[Q&A] ÁFA mentes értékesítés az ÁFA Tv. 87/b. alapján

### ISSUE THREAD

**Issue by DrotosTot** [nav-gov-hu/Online-Invoice#890]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Melyik adómentes case alkalmazandó az ÁFA TV. 87/b. §-ban foglaltak alapján történő ÁFA mentes értékesítés esetén?

**Comment by fzoli15** [comment]
#799 issue alatt volt már ez a kérdés, lassan 4 hónapja türelmesen várjuk a választ...
Mi jobb híján TAM jelöléssel küldjük be az ilyen tételeket.

**Comment by DrotosTot** [comment]
@fzoli15 
Köszönöm a választ!
Ezt az issue elkerülte a figyelmemet (vagy rosszul kerestem)...
Akkor várok én is veletek tovább...

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ezt zárom, maradjon a #799
