### ISSUE TITLE
[Q&A] Külföldi magánszemélynek távértékesítés, letelepedési ország ÁFA kulcsát nem fogadja az API

### ISSUE THREAD

**Issue by zonehun** [nav-gov-hu/Online-Invoice#892]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Sziasztok,

2021.07.01-től az EU-n belüli távértékesítésre vonatkozó szabályok úgy változtak, hogy a vevő letelepedési országa szerinti ÁFA kulccsal kell számlát kiállítani.

Példa: Magyar cég cipőt értékesít romániai magánszemély vásárlónak. A számlát magyar cég kiállítja és az állításuk szerint (könyvelő szerint), a román, 19%-os ÁFA kulcsot kell alkalmazniuk a számlán.

Ez önmagában nem gond, a rendszerünkben ezt tudjuk engedélyezni. Azonban a NAV OnlineSzámla visszadobja NAV séma hibával.

Az a gyanúnk, hogy a cég könyvelője benézett valamit. Mi a helyes eljárás? Milyen ÁFA kulccsal kell egy ilyen ügyletet beküldeni?

Köszönöm

**Comment by NTCA-tax** [comment]
Július 1-től amennyiben a távértékesítés összege az összes EU-s tagállam vonatkozásában a 10 ezer eurót meghaladja, akkor a vevő tagállamában kell az adót megfizetni. Ennek két módszere lehetséges:

1. A magyar vállalkozás áfa regisztrációt hajt végre az érintett tagországban/tagországokban. Ekkor a számláját is az áfa regisztrációján keresztül állítja ki, amely az áfa szempontjából nem magyar adóalany, tehát nincs adatszolgáltatási kérdés.
2. A magyar vállalkozás regisztrál az OSS rendszerbe, és a saját magyar adószámáról állít ki számlát más tagállami adókulcsokkal. Ez az eset ugyanakkor szintén nem tartozik az adatszolgáltatás alá, mivel a 10. számú melléklet mentesíti ezen ügyleteket az adatszolgáltatás alól.

A fentiek alapján tehát nem lehet olyan számla, amely ne a magyar áfakulcsot tartalmazná és mégis adatszolgáltatás vonatkozna rá.

**Comment by zonehun** [comment]
Kedves @NTCA-tax , Köszönöm a válaszokat!

Jól értem, hogy ez akkor két irányt jelent:
1. esetben vizsgálnunk kell, hogy az adószám magyar. Ezt meg tudjuk tenni a publikusan elérhető CDV számító képlettel? Tehát ha a képlet szerint CDV helyes az adószám, akkor az magyar?
2. esetben arra gondoltunk, hogy a "Belföldi adóalany", "Magányszemély", "Egyéb" adózói státuszokhoz felveszünk egy továbbit "EU magánszemély" (vagy valami hasonlót). Ez a megoldás helyes lehet?

A nem magyar adószám esetén (bár magyar letelepedésű cég) és "EU magánszemély" esetén nem küldjük a számlákat az API végpontra. Ez így a július 1-től működő jogszabályokkal harmóniában van? Nem vétünk hibát a megoldással?

Köszönöm

**Comment by NTCA-tax** [comment]
Az első irány egy megfelelő irány is lehet, de persze más megoldási út is lehetséges a számlakiállító oldalán a magyar adóalanyiság vizsgálatára.

A 2. esetben arra felhívnám a figyelmedet, hogy az "EU magánszemély" nem tökéletes elhatárolás. Más tagállami magánszemély személyesen is vásárolhat Magyarországon és akár kérhet a vásárlásáról számlát. Ebben az esetben belföldi értékesítés történik, nem pedig távértékesítés. Amennyiben a vevői adatoknál akarod elkülöníteni, akkor a felhasználó számára szerencsésebb lenne utalni arra, hogy távértékesítés történik úgy, hogy a másik tagállamban kell az adót megfizetnie. Az "EU magánszemély" jelölés félreviheti a felhasználót, és előfordulhat olyan eset, hogy a félreértése miatt nem történik meg adatszolgáltatás olyan számláról, amelyről viszont kellene.

Továbbá ami fontos, hogy a két feltétel között nem "ÉS" kapcsolat van, hanem "VAGY". Amennyiben más tagállamban rendelkezik a magyar vállalkozás áfa regisztrációval, akkor nincs olyan eset, amikor a más tagállami adószámával lenne adatszolgáltatási kötelezettsége. Amennyiben a magyar adószámáról történik meg a távértékesítés, akkor pedig vizsgálni kell, hogy a másik tagállamban keletkezik-e adófizetési kötelezettsége, és amennyiben igen, akkor szintén nincs adatszolgáltatás.

**Comment by zonehun** [comment]
Köszönöm a válaszokat. A két feltétel között természetesen "vagy" kapcsolat van. Ezt rosszul írtam. Az "EU magánszemély" helyett meg találunk egy jobbat, köszönöm a pontosítást.
