### ISSUE TITLE
2021.julius 1-i üzemzavar

### ISSUE THREAD

**Issue by leczkat** [nav-gov-hu/Online-Invoice#893]
Jó napot kívánok! 
Lehetséges, hogy júl 1-ről júl 2-ra éjszaka üzemzavar volt? A számláink küldése leállt, és csak pár perce tudtuk újra indítani. 
A fejlesztőink szeretnék tudni, hogy nálunk keressék e a hibát, vagy pedig a rendeszerben volt. 
Előre is köszönjük a választ. 
Leczó Katalin

**Comment by renced42** [comment]
Kedves @leczkat 

Nem volt üzemzavar. Kérlek zárd az issue-t.

Köszönöm szépen!
