### ISSUE TITLE
[DEV support]

### ISSUE THREAD

**Issue by ballonyi** [nav-gov-hu/Online-Invoice#894]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[x] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
QIDG_D1_000000011610
2021.07.07 19:00:02

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
A hívás során a HttpsURLConnection hiba nélkül kiépült, de a request body küldése során
 _javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake_
hibát kapok. Nagy segítség lenne, ha esetleg túloldali log alapján kaphatnék támpontot hogy mi miatt történik.

Előre is köszönöm!

**Comment by renced42** [comment]
Kedves @ballonyi 

Általában ez a hiba kettő dologhoz kapcsolódik, java verzió váltáshoz + Online Számla szerver SSL tanúsítvány hiány illetőleg a TLS 1.2 helyett alacsonyabb TLS használata.
Ezeket érdemes megnézni.

**Comment by ballonyi** [comment]
Köszönöm! 

Az imént próbáltam tesztben beküldeni egy TokenExchangeRequest-t:
requestId=TEXCH_999999670394, 
timestamp=2021-07-15T14:24:46.105Z

400, Bad Request hibával jön vissza. 
Úgy gondolom hogy az xml megfelel az XSD-nek.
Karakterkészlet probléma nem lehet mert nincs benne ékezetes.
Nincs response body, így nem tudom hogy pontosabban mivel van probléma.
Kaphatnék némi támpontot hogy mi lehet a gond?

Köszönöm

**Comment by ballonyi** [comment]
Köszönöm!
