### ISSUE TITLE
Adószám megszűnése számlakibocsátó esetén

### ISSUE THREAD

**Issue by GabiSzamla77** [nav-gov-hu/Online-Invoice#895]
Sziasztok!
Több ügyfelünk járt már úgy, hogy hamarabb "kitiltásra" került a NAV Online Számla rendszerből, mint a tényleges megszűnés napjának vége. A legutóbbi esetek példája:
Rendszeresen hó végén számláznak, de most a megszűnés napja is 06.30. volt.
A számlákat 06.30-án állították ki, és aznap meg is történt a továbbítása, viszont már 06.30-án délelőtt érvénytelen adózó jelzéssel érkezik a hibaüzenet, továbbá a felhasználó sem tud belépni a NAV Online rendszerbe.
A NAV-os ügyfélszolgálattal is egyeztettünk, és egyetértettünk abban, hogy ha a megszűnés napja 06.30., akkor jogszerűen 06.30-án éjféltől kellene letiltani a belépést és az interfészt.

Pontosabban ez is kérdéses, mivel, ha jól tudom, pl. az adószám törlését követően 30 nap van a szükséges záró bevallások beadására, akkor ugyanennyi ideig hozzá is férhetne a NAV Online Számla rendszerben lévő adataihoz. Természetesen 07.01-jétől számlát már nem állít ki, de a régi adatszolgáltatásaihoz való hozzáférés jogszerű volna. 
Kérdés lehet még a nyomdai úton előállított számlák esete is, ahol van egy berögzítési határidő - ez szintén átcsúszhat a megszűnési dátum utánra.
Esetleg tudtok valami megoldást a fenti esetekre, vagy valamit nem jól értelmezünk?
Köszönöm.

**Comment by NTCA-supporter** [comment]
Szia @GabiSzamla77 !
Jelenleg az Online Számla rendszerben ez nem megoldott funkció, ez persze hiányosság.
Meg lesz oldva a 30 napos "türelmi idő" is. Maradjon nyitva az issue, jelzek majd ha tesztelhető.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ez már megoldódott, élesen is van a fejlesztés.
Zárom az issuet.
Üdv
