### ISSUE TITLE
NAV_ERROR.INCORRECT_HEAD_DATA_PERIODICAL_SETTLEMENT

### ISSUE THREAD

**Issue by koverg70** [nav-gov-hu/Online-Invoice#897]
A tárgyban jelzett figyelmeztetés jön az elmúlt négy hónapban (május óta) az online számlázóban. A hibaüzenetet ugyan megtaláltam itt https://onlineszamla.nav.gov.hu/api/files/container/download/Online_Szamla_interfesz%20specifikacio_HU_v3.0.pdf és ott van, hogy 3.0-ás verzió óta létezik, de hogy mit jelent, és mit kell javítani azt nem találom sehol.

Esetleg van itt valaki, aki az API angol terminológiáját jobban érti. Mi az a periodical settlement? (Én is fejlesző vagyok ugyan, de más területen, szóval nézzétek el, ha nem tudom értelmezni az üzenetet.)

Előre is köszi a válaszokat.

Gábor

![image](https://user-images.githubusercontent.com/4959128/127381206-e9ef0b1a-1c91-4d04-9b2a-d544413b3a70.png)

**Comment by omachtandras** [comment]
Szia Gábor!

Részletek a dokumentációból:
Figyelmeztet, ha időszakos elszámolás kezdő és/vagy záró dátumának kitöltöttsége esetén a periodicalSettlement elem „false” értéket vesz fel.
Csak akkor fut le, ha legalább az egyik dátum és a periodicalSettlement elemek kitöltöttek.
invoiceMain/invoice/invoiceHead/invoiceDetail/periodicalSettlement
invoiceMain/invoice/invoiceHead/invoiceDetail/invoiceDeliveryPeriodStart
invoiceMain/invoice/invoiceHead/invoiceDetail/invoiceDeliveryPeriodEnd

periodicalSettlement    xs:boolean  Időszakos elszámolás jelzés
invoiceDeliveryPeriodStart     xs:date      Ha a számla egy időszakra vonatkozik, akkor az időszak első napja
invoiceDeliveryPeriodEnd    xs:date    Ha a számla egy időszakra vonatkozik, akkor az időszak utolsó napja
(Valószínűleg itt kicsit pongyola a dokumentáció, talán jó lenne, ha a start és end esetén is az időszakos elszámolás kifejezés szereplne.)

Azt kell eldöntenetek, hogy határozott időszaki számlát (időszaki elszámolás) állítotok-e ki.
Ha igen, akkor az invoiceMain/invoice/invoiceHead/invoiceDetail/periodicalSettlement értékének true-nak kell lennie és ilyenkor kell tölteni a másik két dátumot is (jellemzően az End dátumot szokták ilyenkor ismerni a szoftverek, mert jelenleg (99%ban) az kell az ÁFA bevallás korrekt elkészítéséhez), de nem kizárt, hogy a Start dátumot is ismeritek.

Nekem az a tapasztalatom, hogy NEM időszaki elszámolású számla esetén is szokták tölteni a Start / End dátumokat, pl. ha gyűjtőszámláról van szó. Ugye ilyenkor van egy első és egy utolsó teljesítés dátuma, ezekkel szokták tölteni ezeket a mezőket, pedig nem szabadna, mert ezek nevesítetten a határozott időszaki számlára vonatkoznak a dokumentáció szerint nem pedig a gyűjtőszámlához.

Remélem azért @NTCA-tax megerősíti, hogy helyes, amit írtam. :)

András

**Comment by NTCA-supporter** [comment]
Szia @koverg70 !
Kérlek teszt rendszeren ellenőrizd, hogy fennáll-e még a probléma.
Úgy rémlik volt ezzel kapcsolatban javítás, ami ezt orvosolta. A fenti leírás egyébként helytálló szerintem.
Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet, ha van még kérdés/probléma, kérlek nyissátok újra.
Üdv
