### ISSUE TITLE
[Q&A] Előlegszámla többszörös felhasználás

### ISSUE THREAD

**Issue by csandazoltan** [nav-gov-hu/Online-Invoice#898]
**Lehet e egy előlegszámlát több végszámlán felhasználni?**

Olyan élethelyzetet próbálunk megoldani, hogy egy nagyobb előleget szeretnénk több számlán felhasználni. 
A leírás csak azt mondja, hogy ha nagyobb az előlegszámla mint a végszámla, akkor az előlegszámlát módosítani kell a végszámla maximum értékéig így a végszámla 0 Ft.

Több számlán használjuk fel az előleget:

Előlegszámla1 net 100000 HUF brut 127000 HUF
Végszámla1 net 50000 HUF brut 63500 HUF - Előlegszámla1 net -50000 HUF -brut 63500 HUF - Végösszeg 0 HUF
Végszámla2 net 50000 HUF brut 63500 HUF - Előlegszámla1 net -50000 HUF -brut 63500 HUF - Végösszeg 0 HUF

Illetve 

Ilyet lehet vagy minden előlegszámlát egyben kell felhasználni egy végszámlára?
Több előlegszámla szerepelhet egy végszámlán amíg azok összege a végösszeg alatt van, de 1 előlegszámla nem szerepelhet több végszámlán

Technikaliag az API be tudja fogadni, szakmai és adóügyi oldalról lennék kíváncsi

**Comment by omachtandras** [comment]
Szia Zoltán!

Biztos, hogy lehet. Számtalan ügyfelünk csinálja, nagy mennyiségben mind kiállítói, mind befogadói oldalon.

András

**Comment by Macskafarka** [comment]
Adóügyileg be lehet tudni Lehet egy előlegszámlát akár több végszámlába is.
Arra kell vigyázni, hogy a termékértékesítő sorok áfa kulcsával megegyező előleg tudható be, az is csak az adott áfa kulcsú termékértékesítő sorok összegéig.
Ennél még cifrábbak is lehetnek:  Egy számlába (nevezzük végszámlának) több előlegszámlából érkező összeget, akár részösszeget is be lehet betudni.
Pl. 
Előlegszámla1: ennek az 1. tételsora 27%-os, bruttó 100.000 Ft , a 2. sora 18%-os bruttó 200.000 Ft
Előlegszámla2: 1. tételsora 27%-os bruttó 40.000 Ft, 2. sora: 5%-os kulcsú, bruttó: 15.000 Ft.
majd az Előlegszámla2-nek az 1. sorát módosítják úgy, hogy bruttó 55.000 Ft legyen, és a 2. sorát 0-ra módosítják.
Ezt követően a Végszámla1: betudnak az előlegszámla1-ből 27%-ből bruttó 80.000 Ft-ot és a 18%-ból bruttó 110.000 Ft-ot,
az Előlegszámla2-ből 27%-kal bruttó 30.000 Ft-ot. (csak akkor lehet ezeket megcsinálni, ha  vannak mellette termékértékesítő sorok is, a 27%-os kulccsal minimum bruttó 110.000 Ft (80.000+30.000) és 18%-os kulccsal minimum bruttó 110.000 Ft)
A Végszámla2-be betudnak az Előlegszámla1-ből 18%-kal 90.000 Ft-ot, az Előlegszámla2-ből bruttó 25.000 Ft-ot.
Ez egész után az Előlegszámla1-nek a 27%-os kulcsú, eredetileg bruttó 100.000 Ft-os sorát  módosítják egy okirattal bruttó 80.000 Ft-ra.
Az Előlegszámla1-ből így  "felszabaduló" 27%-os bruttó 20.000 Ft-ot vagy bankból visszautalják, vagy készítenek róla egy Előlegszámla3-at.
Végtelenül lehet folytatni a példát, de ennyivel szerintem sikerült érzékeltetni a lehetőségeket.

**Comment by csandazoltan** [comment]
Köszönöm a válaszokat! Ezt akkor alaposan át kell gondolni!
