### ISSUE TITLE
[FEATURE] Queries V2

### ISSUE THREAD

**Issue by kabelnet2** [nav-gov-hu/Online-Invoice#9]
A lekérdezésekkel kapcsolatban megint a saját szempontjaimat fogom kifejteni, mások szempontjait majd ti figyelembe veszitek.

A lekérdezési lehetőségek közül az használja a rendszerünk, amely egy adott számlaszámra kérdez rá. Minden módosító számla feladása előtt ellenőrzi, hogy megvannak-e a hivazkozott számlák. Ehhez viszont nincs szükség arra, hogy visszakapjuk magát a számlát (base64-ben), azt mi is ismerjük, csak a státusza (van/nincs) érdekel. Az adatátvitel nagyobb része viszont éppen a számla.
Tehát lehetne egy olyan kapcsoló a lekérdezésben, hogy kérem a számla részletes adatait vagy sem. (Ugyan ez vonatkozik a módosítókra is ilyenkor). Kis változtatás lenne a programban de nagy az adatátvitel mennyiségében. Én úgy gondolom, hogy sokan használják erre a célra ezt a lekérdezést.

A rendszer bevezetése óta várunk a vevői számlák lekérdezhetőségére. Igazából feltehetőleg minden számla érdekel majd bennünket, főleg amelyeknél sikerül megoldani az elektronikus bevételezést (a többinél elég lesz, ami a digest-ben jön).
Viszont a lekérdezéshez lenne egy ötletem. A jelenlegi lekérdezési lehetőségek (számla kiállítási dátum, teljesítés dátum) mellett kellene egy olyan, hogy a 'DONE-ba menetel dátuma (és ideje)'. Az előző lekérdezéseknél ugyanis lehet olyan számla, ami utólag érkezik (mert pl. hibás és csak a következő napon javítják), így viszont mindig egy jó nagy adagot kell lekérdezni visszamenőleg is, hogy ne maradjon ki számla, azután jöhet az ellenőrzés, hogy ez már megvan ez meg feldolgozandó.
Egy ilyen DONE-os dátum lehetőség esetén (főleg ha még időpont is megadható lenne) minimalizálni lehetne a lekérezett adatok mennyiségét és a feldolgozást: az előző lekérdezés adatait megadva éppen a jó adatok jönnének.

**Comment by NTCA-developer** [comment]
> Tehát lehetne egy olyan kapcsoló a lekérdezésben, hogy kérem a számla részletes adatait vagy sem.

Ezt azonnal megvesszük, nagyon jó hogy mondod, hogy erre használjátok. A negatív ágon ugye nem lesz különbség, mert ha nincs meg a számla, akkor ugyan úgy üres üzleti tartalmú QueryInvoiceDataResponse fog visszamenni, de a pozitív ágon nekünk sem mindegy, hogy az egész tartalmat fel kell-e fetchelni vagy nem. Mit szólsz egy ilyenhez?

```xml
<xs:complexType name="InvoiceNumberQueryType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">Számla lekérdezés számlaszám paramétere</xs:documentation>
			<xs:documentation xml:lang="en">Invoice number param of the Invoice query</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="invoiceNumber" type="data:SimpleText50NotBlankType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Számla vagy módosító okirat sorszáma </xs:documentation>
					<xs:documentation xml:lang="en">Sequential number of the original or modifiation invoice</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="invoiceEntity" type="InvoiceEntityType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">Számlán szereplő fél keresési paramétere</xs:documentation>
					<xs:documentation xml:lang="en">Query parameter of the entity present on the invoice</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="resultOption">
				<xs:annotation>
					<xs:documentation>Ide jön enumként, kell-e a teljes tartalom vagy csak egy EXISTS lényegében</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
```

> Viszont a lekérdezéshez lenne egy ötletem. A jelenlegi lekérdezési lehetőségek (számla kiállítási dátum, teljesítés dátum) mellett kellene egy olyan, hogy a 'DONE-ba menetel dátuma (és ideje)'.

Itt pontosítsunk. Közvetetten most is van ilyen infód, az auditData node-ban visszakapod az insdate nevű tagban a beszúrás időpontját, szemantikailag a "DONE-ba menetel" és a mentés ugyan az a szerver felől nézve, hiszen csak az lesz elmentve, ami DONE, és pont akkor (so-so) lesz elmentve, amikor DONE-ba megy.

A javaslatod arra irányul, hogy legyen bemenő kereső paraméter az insert date-re? Ha igen, akkor gondolom a digestes lekérdezésbe szeretnéd. Ez stimm? Ha igen, akkor ez akár mehet kötelező számla kiállítás helyébe is, annyira jó a végrehajtási terve, nem tart semeddig.

Kérlek jelezz vissza, és ha jól értettem a javaslataid, akkor felveszem mindkettőt a boardra.

**Comment by kabelnet2** [comment]
Az elsőnél: tökéletesen értjük egymást. A megoldás is elfogadható, hiszen az ettől független invoiceEntity is új és kötelező elem. Vagyis ugyis hozzá kell nyúlni a jelenlegi programokhoz, akkor meg mindegy, hogy a resultOption is kötelező. Így talán többen adják meg azt, hogy nem kell a számla maga, ha tényleg nem kell.

A másiknál tisztázzuk, hogy mit szeretnék: valami olyan módszert, amivel MINDEN bejövő számlát le tudok kérdezni (természetesen az lehet, hogy csak megadott adószámról), ne maradjon ki egy sem. Mindezt úgy, hogy ne kelljen nagy átlapolással dolgozni (vagyis sok számlát lekérdezni és abból kiválogatni, ami még nem volt feldolgozva) mert ez szerintem nektek is nekem is plusz munka illetve terhelés a gépnek.
Egy ilyen LEKÉRDEZÉSHEZ szerintem nem jó a számla kiállítás dátuma vagy a teljesítés dátuma, mert pl. egy hiba és annak javítása megváltoztathatja a felviteli sorrendet.
Az adatszolgáltatás akkor van készen és a vevői számla akkor dolgozható fel a mi oldalunkon, ha DONE státuszba kerül nálatok (a beszállítói annulálást most hagyjuk, de utána másodszor is lesz DONE, vagyis kezelhető. De azért reméljük nem lesznek.) Ezért gondolom, hogy ez az időpont alkalmas lenne egy ilyen lekérdezésre.
Vagyis megadok egy tól-ig dateTime-ot, ti visszaadjátok (igen a digest-re gondoltam) az ebbe az időintervallumba beérkezett (és DONE) számlákat, amiket én feldolgozok és feljegyzem az ig dateTime-ot. Legközelebb (=másnap) ettől az időponttól fogom kérni a számlákat. Így remélhetőleg minden számlát megkapok anélkül, hogy többször kérdeznék rá ugyanarra.

Tehát igen: a digest-ben szeretnék insert dateTime alapján lekérdezni.

**Comment by NTCA-developer** [comment]
Szia!

Köszönöm a választ, így már értem a második igényt is. Én kiállítói oldalon kerestem a lekérdezés okát, valószínű ezért nem volt elsőre tiszta.

Felveszem mindkettőt a boardra. Ha elfogadod, akkor kérlek zárd majd le az issue-t.

**Comment by csaszko** [comment]
#14 
Arra szerettem volna kilyukadni én is, de @kabelnet2 jobban leírta, hogy szerintem sem lesz 100%os ha az vizsgáljuk, pl x nap intervallumban lekérjük a done számlákat és az általunk utolsó lekérdezés dátumát elmentjük és a következő lekérdezésnél már innen fogjuk csak nézni, hiszen lehetnek olyan számlák amikor akkor még nem kerültek feldolgozásra szerver által. Viszont 2 hetet vagy akármennyi időt felesleges lenne mindig lekérdezni. Természetesen kliens oldalon biztosan nem okoz gondot.

**Comment by NTCA-developer** [comment]
Mi biztosítjuk szerver oldalon a funkciót, mert a felvetés jó. A beszúrás dátumánál mi garantáljuk, hogy a feldolgozás tényleges végén kerül rá az insertDate a számlára, ezért nyugodtan támaszkodhattok erre.
