### ISSUE TITLE
QueryInvoiceDataResponse séma probléma

### ISSUE THREAD

**Issue by rtoth0407** [nav-gov-hu/Online-Invoice#90]
A számlaküldésben a tételek ÁFA értéke és bruttó értéke opcionális adatok, a QueryInvoiceData  operáció ezen adatok hiánya esetén mégis SCHEMA_VIOLATION hibakóddal hibára fut.

Javasoljuk a QueryInvoiceDataResponse séma javítását.

A tételek ÁFA értékét és bruttó értékét nem kötelező megjeleníteni a számlákon, és igazából nem is szabad megjeleníteni a kerekítési problémák miatt.

**Comment by NTCA-developer** [comment]
Szia @rtoth0407 

Ez valid hiba, köszönjük szépen hogy jelezted. Magunknál már javítottuk, meg fogom írni hogy melyik release-ben és mikor ment ki. Addig nyitva hagyom.

**Comment by NTCA-developer** [comment]
Szia @rtoth0407 

A 2.6-os release tartalmazza ennek a javítását, kint van már a teszt környezetben január eleje óta. Ezt lezárom, köszönjük még egyszer hogy jelezted!
