### ISSUE TITLE
[DEV support] Helytelen currencyCode megjelenítés a teszt portálon

### ISSUE THREAD

**Issue by szkomaromi-contactplus** [nav-gov-hu/Online-Invoice#900]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[x] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[x] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
3H06NI3386KFUJ4Z
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
A teszt rendszerbe currencyCode EUR pénznemmel feladott számla a felhasználó számára a teszt NAV portálon ellenőrizve forintos számlaként látszik. (A queryInvoiceDigest hívás is EUR pénznemet ad vissza.)

![Picture1](https://user-images.githubusercontent.com/62558596/129557352-d53010a6-b116-4bfd-ba59-375cac1cb5e9.jpg)

*Egyéb tartalom / Additional content*

**Comment by topybear** [comment]
https://github.com/nav-gov-hu/Online-Invoice/issues/752 ?

**Comment by szkomaromi-contactplus** [comment]
> 
> 
> #752 ?

Elég valószínű. 
Köszönöm a visszajelzést!

Sajnos azt nem tudja a felhasználó, hogy "merre felé kattintgatott", amíg ide jutott.

**Comment by NTCA-supporter** [comment]
Folyamatban van a hiba javítása. Amint kikerül a teszt rendszerre jelezzük a #752 issueban. Ha nincs több kérdés akkor kérlek zárd le az issue-t. Köszi
