### ISSUE TITLE
QueryInvoiceDigest

### ISSUE THREAD

**Issue by ballonyi** [nav-gov-hu/Online-Invoice#902]
Az ÉLES rendszerben beküldtem a requestid=QIDG_000000769647 QueryInvoiceDigest kérést, amivel a saját 08.31-én beküldött _kimenő_ számláinkat szeretném visszaolvasni:

    <page>1</page>
    <invoiceDirection>OUTBOUND</invoiceDirection>
    <invoiceQueryParams>
        <mandatoryQueryParams>
            <insDate>
                <dateTimeFrom>2021-08-31T02:00:00.000Z</dateTimeFrom>
                <dateTimeTo>2021-08-31T21:00:00.000Z</dateTimeTo>
            </insDate>
        </mandatoryQueryParams>
    </invoiceQueryParams>

A válaszüzenetben: 
```
<ns2:invoiceDigestResult>
 <ns2:currentPage>1</ns2:currentPage>
 <ns2:availablePage>1</ns2:availablePage>
<ns2:invoiceDigest>
...
```

Összesen csak 21 invoiceDigest elemet kapok vissza, viszont ha belépek a webes felületre akkor azt látom hogy 935 számla van 08.31 dátumra:
![web](https://user-images.githubusercontent.com/50325477/131865332-d8e940fb-22c5-44ed-aa63-043b8a6d9d20.png)

Csoportos ÁFA alanyok vagyunk. Az látszik hogy a lista elején látható K-val kezdődő számlaszámok ugyanazon áfa csoport, de egy másik csoport tag számlái. Csak ezeket adja vissza a QueryInvoiceDigest, a miénket nem.  

Szeretném kérdezni hogy paraméterezzem a QueryInvoiceDigest-et hogy lejöjjön az összes számla?

Köszönöm!

**Comment by nbeeps2** [comment]
Lehet, hogy csak jogosultsági kérdés lesz. A technikai felhasználóval, amivel a QueryInvoiceDigest-et végzed lehet más jogosultságok vannak beállítva, mint azzal a fiókkal, amivel belépsz a webes felületre. Jogosultság függő ugyanis, hogy a felhasználó csak az általa kiállított számlákat kérheti le vagy a többi felhasználó által létrehozott számlákat is.

**Comment by ballonyi** [comment]
A saját magunk által kibocsátott, beküldött számlákat próbáltam visszaolvasni.

**Comment by NTCA-supporter** [comment]
Szia @ballonyi !
Éles rendszert itt nem támogatunk, így ebben nem tudok segíteni.
A screenshoton látok 2021.08.30-i kiállítási dátummal számlákat, míg a digest lekérdezésben csak 31-ére szűrsz. Nem itt csúszott el, hogy weben 2 napnyi intervallumra kerestél?
Üdv

**Comment by ballonyi** [comment]
Bocs, valóban rossz request-et másoltam be... 

A K-s sorszámú számlák kelte, és a 2021-el kezdődő számlaszámok egyaránt 08.30-i keltezésűek, tehát ha az egyiket hozza, akkor a másikat is kéne. Ilyen akkor lehetne ha az insDate eltérne a számla kelt dátumától, de abban bizonyos vagyok hogy teljesült azonnali beküldés. Gyanús hogy a response csak az egyik ÁFA csoporttag számláit hozza.

Éles supportot hogy tudok kérni?

**Comment by NTCA-supporter** [comment]
Szia!
https://www.nav.gov.hu/nav/e-ugyfsz/e-ugyfsz.html
Teszt környezeten nem tudjátok reprodukálni?
Üdv

**Comment by ballonyi** [comment]
Megismételtem élesben a hívást és jó eredményt hozott. Nem tudom mi lehetett, lényeg hogy most jó. 

Köszönöm
