### ISSUE TITLE
[Q&A] Technikai érvénytelenítés

### ISSUE THREAD

**Issue by DHM7** [nav-gov-hu/Online-Invoice#904]
Amennyiben a teszt számlázó rendszerünkbe fejlesztői hiba miatt az éles rendszer technikai felhasználóját rögzítettük és ezzel sikerült beküldenünk közel 20.000 db számlát, amelyek nem valós csak tesztelési célból lettek kiállítva, akkor erre használható-e a technikai érvénytelenítés lehetőség. Ha igen akkor tömegesen jóvá lehet-e hagyni a technikai érvénytelenítést vagy ezt egyesével kell megtennünk?

**Comment by NTCA-supporter** [comment]
Szia @DHM7 !
Egy annulmentRequestben 100 számlára tudsz hivatkozni amikor beküldöd.
Utána viszont egyesével kell jóváhagynod ezeket a requesteket igen.
Üdv

**Comment by omachtandras** [comment]
https://github.com/nav-gov-hu/Online-Invoice/issues/649#issuecomment-751784937

**Comment by DHM7** [comment]
Köszönöm, a kérdés első fele érdekelne még, hogy a technikai érvénytelenítés használható-e ebben az esetben?

**Comment by NTCA-supporter** [comment]
Igen, mivel itt nem jöttek létre ezek a számlák, teljesen invalidak.
Üdv
