### ISSUE TITLE
[Q&A] Ügylet típus és NAV ÁFA kódok kapcsolata

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#906]
Sziasztok!

Most ismét előjött egy ügyfélnél, hogy a partner a belföldi számlát úgy jelentette, hogy a tételsoron EUFAD37-es NAV ÁFA kódot adott meg.
Tudomásom szerint van a NAVnak egy elképzelése arról, hogy milyen ügyletek esetén milyen ÁFA kódot szabad használni / minek van értelme.
Lehetséges esetleg az, hogy egy ezzel a témakörrel kapcsolatos ajánlás jelenjen meg a dokumentációban vagy bárhol a NAV oldalán?
És ezzel párhuzamosan lehet-e, hogy a nem megfelelő együttállások esetén warning érkezzen?

Tudom, hogy ez inkább adószakmai kérdés, de az EÁFA közeledtével fontos lenne, hogy megfelelő minőségű adatok érkezzenek a kulcsok esetében is.

Köszönöm!

**Comment by DrotosTot** [comment]
@omachtandras:
Szerintem erre a legjobb ajánlás a Számviteli törvény 165.§. (2). bek., mivel egyértelműen megállapítható, hogy a kiállított bizonylat hibásan írja le a gazdasági eseményt, így befogadni sem (lenne) szabad.
Ugyanakkor a warning szükségességével egyetértek.

Az EÁFA abból a szempontból is érdekes lesz, hogy mi történik azokkal az adatszolgáltatásokkal, amelyek számláit a vállalkozás nem kívánja a könyvelésében szerepeltetni (nem kíván élni az adólevonási jogával). De ez már másik téma.

**Comment by omachtandras** [comment]
@DrotosTot: mi már egy ideje beépítettük a számlázó modulunkba, hogy ügylet típustól függően engedünk csak NAV kódokat használni. Egy ideig megengedő jelleggel, most már kötelező tiltással. Szállítunk egy beállítást, de az ügyfél a saját jogértelmezése szerint ezt átállíthatja.
Mindenképpen jó lenne egy NAVos értelmezés, akkor arra támaszkodva szállíthatnánk az alapértelmezett beállításokat.

DE, visszatérve a befogadói oldalra. A számlaképen sok szoftvernél még mindig nem szerepel az a szöveg és kód, amit beküld a NAVhoz. Egyszerűen ott van, hogy adómentes és kész. Nem részletezi tovább. Ezért a számlát visszautasítani nem szokták, nem is fog ezzel szórakozni egyetlen könyvelő sem, nem fog ezért harcolni a partnerrel.

Viszont, amikor majd jön az EÁFA és a NAV által elkészített ÁFA tervezetben a sorok összegei köszönő viszonyban sem lesznek ilyenek miatt az ügyviteli programok által készített bevallással, akkor jön majd a fejvakarás, hogy miért nem.

Vagy egyszerűen csak legyintenek majd a NAVos megoldásra, hogy semmire nem jó, semmi nem egyezik a valósággal.

Pedig "csak" az alapadatok hibásak.

A legutóbbi egyeztetésen is kérték a NAVosok, hogy javítsanak a programok az adatok minőségén, én ennyit tudok tenni, hogy jelzem, hogy szerintem milyen ponton kellene a NAVnak lépnie.
Mert az nem fog menni sajnos, hogy a könyvelők majd kikényszerítik a nagyobb cégektől / szoftverektől a változtatást.

Ez látszik az elmúlt egy év tapasztalatából. Legalább is nálunk a kisebb cégek könyvelői ha próbálkoznak is lelkesen a partnerek adatszolgáltatásának javításával, amikor elkezdik használni a NAVtól történő adatokon alapuló feldolgozást, előbb-utóbb feladják a harcot és inkább betanítják a programot, hogy ha ettől ez jön, akkor az igazából azt jelenti.

Csak, ugye, az EÁFA erről semmit nem fog tudni. És 99%ig biztos vagyok benne, hogy nem fogják azon a felületen ezeket a betanításokat / módosításokat még egyszer megtenni. Mert senki nem fizeti azt meg nekik, márpedig ez idő-idő-idő.

**Comment by NTCA-supporter** [comment]
Sziasztok!
A tesztrendszerre kikerült új WARN-ok szerintem megoldják ezt a problémát.
Kérlek ellenőrizzétek.
Üdv

**Comment by omachtandras** [comment]
@NTCA-supporter : egyelőre azt gondolom, hogy igen, köszönjük őket! Ha lesz még olyan eset, amibe belefutunk ezek után, akkor jelezni fogom.
