### ISSUE TITLE
[Q&A] EU-s ügylet meghatározása - warningot megér?

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#908]
Tisztelt Kollégák!

Egyik partnerünk más számlázó programmal is készít számlákat. Ezeket az ÁFA bevallás elkészítéshez és a könyveléshez a NAV OSZ-n keresztül tölti le és juttatja be az ERP-nkbe.

EU-s értékesítés esetén ez a számlázó program a következő adatokat adja át a NAVnak:

```xml
                <supplierInfo>
                    <supplierTaxNumber>
                        <ns2:taxpayerId>Eladó magyar adótörzsszáma</ns2:taxpayerId>
                        <ns2:vatCode>X</ns2:vatCode>
                        <ns2:countyCode>YY</ns2:countyCode>
                    </supplierTaxNumber>
                    <supplierName>Eladó neve</supplierName>
                    <supplierAddress>
                        <ns2:simpleAddress>
                            <ns2:countryCode>HU</ns2:countryCode>
                            <ns2:postalCode>IRSZ</ns2:postalCode>
                            <ns2:city>Város</ns2:city>
                            <ns2:additionalAddressDetail>További címadatok</ns2:additionalAddressDetail>
                        </ns2:simpleAddress>
                    </supplierAddress>
                    <supplierBankAccountNumber>BANKSZLA</supplierBankAccountNumber>
                </supplierInfo>
                <customerInfo>
                    <customerVatStatus>OTHER</customerVatStatus>
                    <customerVatData>
                        <communityVatNumber>Vevő közösségi adószáma</communityVatNumber>
                    </customerVatData>
                    <customerName>Vevő neve</customerName>
                    <customerAddress>
                        <ns2:simpleAddress>
                            <ns2:countryCode>OK</ns2:countryCode>
                            <ns2:postalCode>IRSZ</ns2:postalCode>
                            <ns2:city>Város</ns2:city>
                            <ns2:additionalAddressDetail>További címadatok</ns2:additionalAddressDetail>
                        </ns2:simpleAddress>
                    </customerAddress>
                </customerInfo>
```

Mivel a customerVatStatus-ban nagy szívfájdalmunkra nincs nevesítve külön az EU-s ügylet, ezért az Otherből és az ügylet adószámaiból következtetnénk arra, hogy milyen ügylet lehetett a számla alapja.

A dokumentáció szerint közösségi ügylet esetén CommunityVatNumberType-ban kellene szerepeltetni a saját EU adószámunkat:

2.1.4 Adószámok a sémában
...A szállító közösségi (uniós) adószáma pedig a communityVatNumber elemben
(típusa: CommunityVatNumberType) szerepeltethető, ha az szerepel a számlán. 
...

A kérdésem az, hogy létezik-e olyan ügylet, amikor a számlán a magyar belföldi adószám szerepel, a partner oldalán pedig EU-s adószám?
Ha nem létezik ilyen, akkor lehetne ebben az esetben is warninggal jutalmazni az ilyen tartalmú adatátadást?
Ha létezik, de a tételsorok alapján egyértelmű, hogy EU-s ügyletről van szó, akkor lehetne warningot adni?

(A tételsorok egyébként jelen esetben annyiban segítenek, hogy EUFAD37 kód van rajtuk (de nem mindig van szerencsés együttállás: https://github.com/nav-gov-hu/Online-Invoice/issues/906#issue-994852365), tehát utalnak az EU-s értékesítésre, de véleményem szerint a korrekt az lenne, ha a fejadatokból már eldönthető lenne az ügylet típusa.
(Tudom, a 3.0 az utolsó változat, de ha egyszer lesz séma bővítés az ügylet egyértelmű jelölése bele kellene, hogy kerüljön. Kiállító oldalon is sokat segítene, ha egy kényszer hatására átgondolná és támogatást kapna minden szoftverfejlesztő, hogy milyen ügyletek vannak és pontosan milyen elemeket érintenek az xml-ben.))

Előre is köszönöm a választ!

**Comment by NTCA-supporter** [comment]
Sziasztok!
A tesztrendszerre kikerült új WARN-ok szerintem megoldják ezt a problémát.
Kérlek ellenőrizzétek.
Üdv

**Comment by omachtandras** [comment]
@NTCA-supporter : egyelőre azt gondolom, hogy igen, köszönjük őket! Ha lesz még olyan eset, amibe belefutunk ezek után, akkor jelezni fogom.

(Ellenőrizni megpróbáljuk valahogy, csak még nem tudom hogy állítunk elő ilyen együttállást a szoftverünkkel. :))
