### ISSUE TITLE
[Q&A] hibás számlaszám javítása

### ISSUE THREAD

**Issue by janisoft** [nav-gov-hu/Online-Invoice#911]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Sziasztok!

Hogyan javítanátok az alábbi hibát?
ERP rendszer elkészíti a számlát, aminek a számlaszáma 2021/1, a belső azonosítója 1234
Nyomtatáskor a számlaszám mezőbe hiba miatt az 1234 kerül (így kapja meg az ügyfél is)
Adatszolgáltatásban és minden más nyilvántartásban a helyes 2021/1 szerepel.
Ja és mindezt fél évre visszamenőleg :)

Köszönettel:
János

**Comment by EPluribusUnum** [comment]
A papír az igazság, tehát az 1234 a helyes törvényileg. Így annul kell minden ilyen számlára és felküldés a papíron szereplő számlaszámmal.
Majd az összesre sztornó (papíron lévő számlaszám meghivatkozása) és új számla kíálltás a szerinted helyes számlaszámmal.
És az adatbázisba is le kell módosítani, hogy a papírzal egyezzenek az adatok.

(PS nem vagyok törvényi szaki, de szerintem így lenne helyes)
