### ISSUE TITLE
[Q&A] hibás számlaadat-szolgáltatásról októbertől levelet küld a NAV

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#912]
A mai napon jelent meg ez a hír: "A Nemzeti Adó- és Vámhivatal (NAV) a jövőben rendszeresen tájékoztatja az online számlaadat-szolgáltatást küldő adózókat sikertelen vagy figyelmeztetést kiváltó adatszolgáltatásaikról."
"Az adózók megkeresése előtt a NAV külön, elektronikus tárhelyre küldött levélben tájékoztatja azokat a szoftverfejlesztőket..."

Ezt a kezdeményezést minden fejlesztő nevében kérem visszavonni vagy újragondolni! A Sikertelen adatszolgálatás rendben van, arról küldjön levelet, akár az adózónak, akár a fejlesztőnek, de a WARN-t ne vegyük már ebbe bele!!! A WARN-os adatszolgálatás sikeres és nem hibás adatszolgáltatást. Leggyakoribb ilyen WARN-os üzenet az adószám kapcsán van, ilyen a felhasználói körünk nagyságát tekintve a havonta több száz is előfordulhat. Nem kívánom, hogy a NAV teleszemetelje a NAV tárhelyünket az ezekről szóló üzenetekkel! Pl. ha valaki egy mai napon alakuló cégnek/egyéni vállalkozásnak számláz, akkor gyakran kap WARN üzenetet az adószámra vonatkozóan, miközben éles/működő adószámról van szó, csak még nincs szinkronizálva a NAV Online számla által vizsgált adatbázissal. 

A kérésem, hogy a WARN-okra ne küldjön a NAV üzenetet, csak az ERROR-orokról. Ha van olyan WARN, amit szeretne teljesen elkerülni a NAV, akkor minősítsék át ERROR-nak. Pl. mínuszos végösszegű számlák kiállításának esete, ami nem tiltott, nem kap ERROR-t csak WARN-t, a programban figyelmeztetés mellett ilyen kiállítható, de én ezekről, mint fejlesztő nem kívánok tájékoztatást kapni, engem ne SPAM-eljen a NAV, nem járultam/járulok hozzá!

**Comment by omachtandras** [comment]
Sziasztok!

Jó lenne mintát látni. Ez egy aggregált levél lesz, vagy minden ügyfelünk esetében külön kapunk, ha az éppen kiszemelt hibát / warningot ő előidézi.
Azt is jó lenne tudni, hogy milyen hibák vannak a fókuszban. Az pl. pozitív kommunikáció lehetne az ügyfeleink felé, hogy ha tudnánk, hogy most ezek a fókuszok, és lám, ha Te nem kaptál levelet, akkor biztos lehetsz benne, hogy jól csinálod a dolgokat, jó a szoftvered.
Nálunk az ügyfél maga kap visszajelzést a szoftverünktől (ha a normál lekérdezési lehetőség mellett ezt kéri) e-mail-ben, ha error vagy warning egy adatszolgáltatás.
Ez alapján nyilván megkeres és egyeztetünk, hogy szoftver hiba vagy ő csinál valami olyat, amit nem feltétlenül kellene. De, ha ez warning, akkor nincs semmilyen jog korünk arra, hogy azt mondjuk neki, hogy ne csináld, ha ő az törvényesnek gondolja...

Biztos sokan nem így járnak el, és vannak tömeges típushibák, ezt nem kétlem, de pl. a közüzemi cégeink még mindig negatív elszámoló számlát állítanak ki, mert megakadt az általunk jelzett probléma NAV oldalon és még mindig nincs rá megoldás, így élesíteni sem tudjuk náluk a fejlesztést.
Igazán nem szeretnénk ez miatt (sem) a szőnyeg szélére kerülni. :)

**Comment by sinick2** [comment]
Ha végigolvassátok, akkor 

Az adózók megkeresése előtt a NAV külön, elektronikus tárhelyre küldött levélben tájékoztatja azokat a szoftverfejlesztőket, akiknek adószáma a 2021. augusztusi sikertelen adatszolgáltatási kísérletekben a fejlesztő adószámaként (softwareDevTaxNumber[1] elem) megjelenik.

**Comment by nbeeps2** [comment]
" De, ha ez warning, akkor nincs semmilyen jog korünk arra, hogy azt mondjuk neki, hogy ne csináld, ha ő az törvényesnek gondolja..."
Pontosan!!!

"Igazán nem szeretnénk ez miatt (sem) a szőnyeg szélére kerülni. :)"
Dettó! Én sem akarom, hogy a NAV lejárasson minket a felhasználók előtt!!!

**Comment by nbeeps2** [comment]
> Ha végigolvassátok, akkor
> 
> Az adózók megkeresése előtt a NAV külön, elektronikus tárhelyre küldött levélben tájékoztatja azokat a szoftverfejlesztőket, akiknek adószáma a 2021. augusztusi sikertelen adatszolgáltatási kísérletekben a fejlesztő adószámaként (softwareDevTaxNumber[1] elem) megjelenik.

sinick2, ha végigolvasod, amit írtam, akkor pont ez a bajom. Engem ne SPAM-eljen a NAV a WARN-ok miatt!!!

**Comment by sinick2** [comment]
@nbeeps2: Na, akkor még egyszer ...

"sikertelen adatszolgáltatási kísérletekben"

Azaz WARN-okért nem kapsz!

**Comment by nbeeps2** [comment]
sinick2: Akkor fussunk neki még egyszer ;)

"A Nemzeti Adó- és Vámhivatal (NAV) a jövőben rendszeresen tájékoztatja az online számlaadat-szolgáltatást küldő adózókat sikertelen **vagy a figyelmeztetést kiváltó adatszolgáltatásaikról**."

Ez alapján megy a levél az ERROR-ról és a WARN-ról, és a "adózók megkeresése előtt a NAV külön, elektronikus tárhelyre küldött levélben tájékoztatja azokat a szoftverfejlesztőket", tehát kapok belőle én is.

**Comment by topybear** [comment]
Akkor fussunk neki ismét :)

"A Nemzeti Adó- és Vámhivatal (NAV) a jövőben rendszeresen tájékoztatja az online számlaadat-szolgáltatást küldő adózókat sikertelen vagy a figyelmeztetést kiváltó adatszolgáltatásaikról."

Azaz a hibáról és a figyelmeztetésről az adózókat. Ebből a fejlesztő nem kap.

"Az adózók megkeresése előtt a NAV külön, elektronikus tárhelyre küldött levélben tájékoztatja azokat a szoftverfejlesztőket, akiknek adószáma a 2021. augusztusi sikertelen adatszolgáltatási kísérletekben a fejlesztő adószámaként (softwareDevTaxNumber[1] elem) megjelenik."

Azaz csak egy levél és csak akkor, ha a sikertelen adatszolgáltatások közt megjelenik az általa fejlesztett szoftver.

Szerintem :)

**Comment by nbeeps2** [comment]
topybear: Legyen így, de az is lehet, hogy az egyszerűbb megfogalmazás végett már nem tették be a közlemény másik részébe a figyelmeztetéseket, mert az első részében már szerepelt. Ugyanakkor az sem mindegy, hogy a WARN kapcsán a felhasználónak milyen megfogalmazású levelet küld majd a NAV és mennyire sugallja vele, hogy hibásan működik a program...

**Comment by omachtandras** [comment]
> A NAV közleményekről korábban már bebizonyosodott, hogy hajlamosak "megváltozni". Amúgy érdekes lenne, ha egy szoftverfejlesztő cég erről példát véve rendszeren tájékoztatná az ügyfelei arról, hogy a NAV üzeneteit ő hogyan értékelte. Pl. valós, vagy csak a NAV által generált műprobléma.

Szerintem ilyenekbe ne menjünk itt bele, mert nem viszi előre a dolgokat.

**Comment by nbeeps2** [comment]
A fenti üzenet kapcsán kérném, hogy a NAV vágja be ide azt a levélsablont, amit a felhasználóknak ki fog küldeni. Ugyanis semmiképpen nem szeretném, ha a NAV lejárassa a céget, pl. azzal, hogy programhibának állítja be a sikertelen adatszolgáltatást, pl. egy ehhez hasonló szöveggel, ami egyelőre nekünk szántak: "Az eddigi tapasztalatok azt mutatják, hogy az adatszolgáltatás sikertelensége döntő többségében a 
számlázószoftver programozási hibájára vagy hiányosságára vezethető vissza"

Ahogy már feljebb kifejtettem egyáltalán nem csak olyan vezet ERROR-hoz és WARN-hoz, ami programozási hiba lenne, szóval nem kellene ezzel dobálózni, mert ezt ha így ebben a formában az ügyfélnek küldik el, az ki fogja meríteni a hírnév rontást, ami jogi következményekkel jár!

**Comment by nbeeps2** [comment]
Nem - minden esetben - programozási hibából blokkoló validáció hibakódok:
SUPPLIER_TAX_NUMBER_MISMATCH 
INVOICE_NUMBER_NOT_UNIQUE
INVALID_INVOICE_REFERENCE 
INVOICE_TYPE_MISMATCH 
INVOICE_LINE_ALREADY_EXISTS
ANNULMENT_IN_PROGRESS 
CUSTOMER_NOT_ASSIGNED
LINE_NUMBER_REFERENCE_NOT_UNIQUE 
MODIFY_WITHOUT_MASTER_MISMATCH 

A fenti hibakódok esetén NE küldjön a NAV levelet az adózónak vagy legalábbis semmiképp ne utaljanak arra, hogy ez programozási hibára vezethető vissza!

A fenti kódok nagy része előhozható az alábbi szituációban egy TÖKÉLETESEN működő programban.
Felhasználó számláz: 1-100-ig sorszámtartományban, ezek közül vannak normál számlák, helyesbítők, stornók, minden.
Majd az ügyfélnek ellopják a laptopját vagy vírusos lesz, mindegy. Újratelepíti a programot, visszatölt egy korábbi mentést, amiben 72-nél járt a sorszámozás. Elfelejt beállítani új számlatömböt. Vagy teljesen üresen kezdi meg a program használatát egy másik telephelyen és szintén nem állít be számlatömböt, Vagy teljesen üresen kezdi meg a program használatát az új laptopján és nem állít be nyitó sorszámot. Elkezd számlázgatni , stornózni, helyesbíteni és szépen kapja majd a fenti üzenetek közül nagy részét (de természetesen nem mindegyiket ez eset alapján írtam, de mindegyiknek oka van és bármelyik - főleg offline/dekstop - programban előhozhatók).

A kérésem tehát az lenne, hogy csak olyan esetben küldjenek levelet a felhasználónak, ahol egyértelműen programhiba van (pl. nem sémavalid XML). 

A WARN-okat is jól át kell gondolni. A mi saját rendszerünkben a legtöbb ilyen WARN-t a vevő adószáma alapján kapjuk. A vevő adószáma érvényes, ezt ellenőrzik a kollégák minden számla kiállításakor külsős/hivatalos nyilvántartásokban, de NAV még nem frissített, nem naprakész adatbázis WARN-t ad az adószámra, hogy pl. nem érvényes, holott az. Ez legtöbbször az aznap alakul vállalkozásoknál figyelhető meg. A másik pedig a negatív előjelű normál Create számla, amire eleve figyelmeztetést küld a program, hogy nem kéne, de a felhasználó a saját felelősségére kiállíthat ilyen számlát. Továbbra is az a véleményen, hogy ha NAV valamit el akar kerül, akkor a WARN-t minősítse át ERROR-ként és akkor be lehet építeni ellene védelmet, de ameddig WARN egy WARN, addig azzal SENKI nem fog foglalkozni, mert az adatszolgáltatás sikeres lesz.

Szóval erősen szelektálni kellene, hogy milyen ERROR-ok és milyen WARN-okról szóljon a tájékoztatás és ne így nagy általánosságban beszéljünk erről a két csoportról, hanem szűkítsük le őket.

**Comment by omachtandras** [comment]
Nem tudom, hogy ki hogy van vele, mi kaptunk levelet az ügyfélkapun, hogy volt hibás adatszolgáltatás a szoftverünkkel.
A levélben SEMMI KONKRÉTUM nem volt.
Sem az, hogy mely adószámon történtek hibás adatszolgáltatások, sem az, hogy milyen hibák voltak, ha mondjuk az adószámokat valamilyen oknál fogva nem akarta megadni a NAV.

Tudomásunk szerint az érintett időszakban egyetlen hiba volt a NAV felé, ami kezelői hiba volt, de ez most mellékes is, mert NEM TUDTUNK MEG SEMMIT A LEVÉLBŐL, amivel tudtunk volna kezdeni valamit.
Javítani a programot, ha tényleg hibás (vagy legalább elgondolkodni rajta, hogy vajon hogy idézhette elő bárki azt a hibát, ha mi azt gondoljuk róla, hogy elvileg van ellene védelem a programban...), vagy egyeztetni az ügyfelekkel, hogy mit is csinálnak, mint módosítsanak a számlázási folyamatukon, stb. stb.

Ez így semmit nem ért, ettől a fejlesztőknek küldött levéltől semmit nem tudott javulni az adatszolgáltatás minősége, még akkor sem, ha erre mondjuk az adott fejlesztőnél a szándék meglenne.

**Comment by omachtandras** [comment]
@NTCA-tax : én / a mi cégünk maximálisan az mellett van, hogy legyenek a hibák javítva. Ha nálunk vannak, akkor nálunk is (azért régebben nálunk is volt olyan, hogy ügyfél fél év után vette észre, hogy van nem teljesített adatszolgáltatása, hiába kapott róla naponta levelet a rendszertől....), ha máshol, akkor meg máshol, mert az ügyfeleink szeretnének jó minőségű adatokból automatikusan számlákat feldolgozni.

A levélből: "Ezt a levelet azért kapta, mert az Ön adószáma szerepelt a számlázóprogram fejlesztőjének adószámaként (softwareDevTaxNumber elem) a 2021. augusztus 1. és 31. közötti sikertelen online számlaadat-szolgáltatási kísérletek legalább egyikében. "

Tehát, augusztusban volt valami, nem szeptemberben. Lehet, hogy az ügyfelek szeptemberről kapnak. De ez nem is annyira fontos.

Az előzetes tájékoztatás jó lehet, csak legyen benne a levélben, hogy mivel volt baj ÉS, ha lehet KINÉL (adószám). Hogy tudjunk vele valamit kezdeni.
Esetleg, mire kiküldenétek ki is derülne, hogy azt a hibát mégsem kellene bevenni a halmazba, ahogy @nbeeps2 írta.

Mert ezzel a levéllel, most semmit nem tudtunk sajnos.

Köszi!

**Comment by Macskafarka** [comment]
@NTCA-tax viszont így nincs sok értelme. Kb. annyit lehet megtudni, hogy a szoftverünk használói közül valakinek valami problémája van. Kinek és mi?

**Comment by peacefuldev** [comment]
@NTCA-tax itt is jelezni szeretném, hogy hiába valósítottuk meg a dokumentációban leírtakat, továbbra is időről időre belefutunk az INVOICE_NUMBER_NOT_UNIQUE duplikált bejelentésből eredő hibába, amit nagyon nehéz debug-olni!
A 735-ös Issue-ban jelzett kérdésre (https://github.com/nav-gov-hu/Online-Invoice/issues/735), ami szerintünk lehet a probléma oka, majd egy éve nem válaszoltak. Ennek fényében nagyon inkorrektnek tartom hasonló levelek kiküldését az ügyfeleknek, miközben szupportot nem adnak egy hibás tervezésből eredő problémára!

**Comment by nbeeps2** [comment]
Na ma volt egy érdekes eset, ami kapcsán javasolnám kiegészíteni a NAV tájékoztató levelét, amit a felhasználónak(!) küld, hogy szerepeljen benne a szoftver fejlesztő és a program neve!

Minden NAV adatszolgáltatásnak ugyanis kötelező tartalmi eleme a következő:
- A számlázó program azonosítója
- A számlázó program neve
- A számlázó program működési típusa
- A számlázó program fő verziója
- A számlázó program fejlesztőjének neve
- A számlázó program fejlesztőjének működő email címe

Az eset pedig a következő volt. Felhasználó megkeresett minket és átküldte, hogy milyen levelet kapott a NAV-tól. Ebben az szerepelt, hogy több mint 1000(!) alkalommal ERROR-ra futott az adatszolgáltatás szeptemberben, ami viszont azért tart érdekesnek, mert ő a programban mindent rendben lát, annyira, hogy még idén nem is hívta fel az ügyfélszolgálatunkat, tehát soha semmi gondja nem is volt a beküldéssel SOHA. Megvizsgáltuk az állományát és azt láttuk a logokban, hogy egyetlen egy alkalommal sem(!) volt számla adatszolgáltatás hibája az ügyfélnek, nem hogy 1000...

Ezzel bebizonyosodott, hogy nem a mi programunk generálta ezeket az ERROR-okat, viszont az ügyfél azért minket keresett meg, mert a mi programunkat használja. Két magyarázat létezik:
- Lehet ellopták tőle a programot (és a mentését, amiben a NAV bekötéshez szükséges adatok van) és illetéktelenek az ő tudta nélkül egy másik gépen állítanának ki számlákat, amik aztán a nem megfelelő kezdősorszám miatt generálnak errorokat (pl. INVALID_INVOICE_REFERENCE). Az ügyfél csak 1 gépen használja a programot!
- Vagy a tudta nélkül valakik egy teljesen másik programot használnak a nevében, de ebben az esetben is felmerül, hogy akkor kéne, hogy tudja az illető a NAV bekötéshez szükséges adatokat (pl. könyvelő?)

Összegezve sokat segítene, ha a NAV az ilyen levelében tájékoztatná a felhasználót, hogy MILYEN programról van szó, mi annak és a fejlesztőnek a neve, mivel ez minden számla adatszolgáltatásban benne van. Szerencsére sikerült meggyőzni a felhasználót, hogy nem a mi programunk a hibás, de nem szeretnénk, ha mindig bizonygatni kéne az igazunkat, szóval jó lenne konkrét programnevet és fejlesztőnevet beleírni, hogy melyik programmal lehet a gond, mert az sem ritka, hogy egy cég akár többféle rendszerrel is dolgozik.

**Comment by EPluribusUnum** [comment]
További hasznos dolgok amik mehetnének a levélbe : 
- technikai felhasználó nevet is, aki a hibákat generálta
- dátumok (napok), amikor a hibák keletkeztek
- számlaszámok
(- transaction_id, request_id)

**Comment by omachtandras** [comment]
@nbeeps2 : azt meg tudod mondani, hogy mi volt a konkrét error?

(https://github.com/nav-gov-hu/Online-Invoice/issues/922)

**Comment by nbeeps2** [comment]
> @nbeeps2 : azt meg tudod mondani, hogy mi volt a konkrét error?
> 
> (#922)

INVALID_INVOICE_REFERENCE 

A cégnek amúgy 4 stornó/módosító számlája volt, mind a 4-nek sikeres lett az adatszolgáltatása...
Viszont a NAV levélében 1000-nél is több INVALID_INVOICE_REFERENCE hibát írnak... Aminek semmi nyoma nincs a programban, szóval ezt valami mást generálta, csak az ügyfél azért nekünk továbbította a NAV levelet, mert a mi programunkat használja. Ezért kár, hogy nincs benne a NAV-os levelében a program neve, mert akkor látta volna az ügyfél már elsőre is, hogy nekünk ehhez semmi közünk.

**Comment by nbeeps2** [comment]
Közben kiderült - amit mi is sejtettünk -, hogy egy teljesen másik program generálta ezeket a hibákat, még pedig a felhasználó cég könyvelő programja, amiben szintén volt számlázási funkció. Szóval ezért is lenne jó, ha a NAV-os levél kiegészülne azzal, hogy melyik program generálta a hibákat és akkor elkerülhetők ezek a félreértések és gyanúsítgatások.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ezt zárom, kérdés esetén nyissatok újat kérlek.
Üdv
