### ISSUE TITLE
[Q&A] Private_person logika változása?

### ISSUE THREAD

**Issue by lazaralexandra** [nav-gov-hu/Online-Invoice#915]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Private_person esetében eddig sikeresen beküldtük a számlákat, viszont most ABORTED-ra fut, hibaüzenet a következő:
1	ERROR	15102021	08:35	SCHEMA_VIOLATION	XML contains on line: [32] and column: [34] error: [cvc-complex-type.2.4.b: The content of element 'base:simpleAddress' is not complete. One of '{\"http://schemas.nav.gov.hu/OSA/3.0/base\":countryCode}' is expected.]	
A dokumentációban:
Ha a vevő magánszemély (customerVatStatus =
PRIVATE_PERSON), akkor az adóhivatali rendszer nem fogad be olyan adatszolgáltatást, mely tartalmaz
vevői név és/vagy címadatot, bármi is szerepel ezekben a mezőkben.

Pl. Éles rendszerben SCF/2887/476, SIF/17950/476
"customerInfo": {
				"customerVatStatus": "PRIVATE_PERSON"
			},
			"invoiceDetail": {
...
Köszönöm: Lázár Alexandra

**Comment by NTCA-supporter** [comment]
Szia @lazaralexandra !
Éles rendszert itt nem támogatunk.
Kérlek küld be a számlát teszt rendszerbe, és küldj egy requestId/transactionId adatot.

Köszönöm

**Comment by lazaralexandra** [comment]
Köszönöm. Nincs megképezve a simpleAddress csomópont, de csinálok teszt példát mindjárt.

**Comment by lazaralexandra** [comment]
Teszt példa:
Transaction ID: 3JDS1TNWN0MLE187
Error message: 
XML contains on line:   [32] and column: [34] error: [cvc-complex-type.2.4.b: The content of element   'base:simpleAddress' is not complete. One of   '{\"http://schemas.nav.gov.hu/OSA/3.0/base\":countryCode}' is   expected.]
Invoice no: SCN/8425/476

Köszönöm, ha megnézed.

**Comment by NTCA-supporter** [comment]
Zárom az issuet, ha van még kérdés, kérlek nyissátok újra.
Üdv
