### ISSUE TITLE
[Q&A] QueryInvoiceDigestRequest -  OPG esetében n.a. az invoiceAmount mezők értéke

### ISSUE THREAD

**Issue by erikapapp** [nav-gov-hu/Online-Invoice#916]
Az "QueryInvoiceDigestRequest" kérés esetében a visszakapott válasz abban az esetben ha a source online pénztárgép "source=OPG" az alábbi oszlopokban "n.a." jelenik meg: 
- invoiceNetAmount, 
- invoiceNetAmountHUF, 
- invoiceVatAmount, 
- invoiceVatAmountHUF

Várható, hogy az MGM source-hoz hasonlóan az összeg fog megjelenni ezekben a mezőkben?

Köszönöm.

Üdvözlettel: Papp Erika

**Comment by NTCA-supporter** [comment]
Szia @erikapapp !
Az OPG számlák minden esetben egyszerűsített (simplified) számlák, így mindig csak a bruttó összegek lesznek töltve.
Hamarosan publikálva lesz a töltési logika, hogy a pénztárgépes adatokból mit mire forgatunk át az Online Számlás sémában.
Üdv

**Comment by erikapapp** [comment]
Köszönöm a választ. Akkor ez azt jelenti, hogy az OPG-s számlák összegéből semmilyen információ nem lesz benne az "QueryInvoiceDigestRequest" kérés válaszában? Vagy az Online Számlás sémában lesznek majd plusz mezők kifejezetten az OPG-s számlák miatt.

**Comment by NTCA-supporter** [comment]
Ez nem az OPG-s forrástól függ, hanem attól, hogy egyszerűsített-e a számla. Az összes egyszerűsített számlánál üresek ezek az értékek.
Üdv

**Comment by NTCA-supporter** [comment]
Szia @konyisoft !
Igen sajnos, ez most így működik. Sémaváltozást egyelőre nem tervezünk.
Zárom az issuet, ha van még kérdés, kérlek nyissátok újra.
Üdv

**Comment by szako** [comment]
> Szia @erikapapp ! Az OPG számlák minden esetben egyszerűsített (simplified) számlák, így mindig csak a bruttó összegek lesznek töltve. **Hamarosan publikálva lesz a töltési logika, hogy a pénztárgépes adatokból mit mire forgatunk át az Online Számlás sémában.** Üdv

Az említett anyag már publikálásra került? Köszönöm!
