### ISSUE TITLE
[Q&A] ÁFA csoporttag adószám megadása adószám esetén

### ISSUE THREAD

**Issue by BenceBakos** [nav-gov-hu/Online-Invoice#917]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**

Van egy ügyfél, akinek számláin feltüntetünk Adószámot, és Csoportos tag adószámot is.
A következő warning jön erre:

```
 - Hibás adószám. Vevőként ÁFA csoporttag adószáma lett megadva!

    –  Tag: InvoiceData/invoiceMain/invoice/invoiceHead/customerInfo/customerVatData/customerTaxNumber/taxpayerId
    –  Érték: 12345678
```
_A megoldás az, hogy egyáltalán nem küldünk be CSoport tag adószámot, ha van Adószám feltüntetve?_

**Comment by NTCA-supporter** [comment]
Köszi @omachtandras , ettől többet egyelőre én sem tudok hozzáfűzni :)

**Comment by BenceBakos** [comment]
Köszönöm a segítséget!
