### ISSUE TITLE
Helytelen termékdíj számítás WARN üzenet [INCORRECT_PRODUCT_FEE_CALCULATION_AGGREGATE_PRODUCT_CHARGE_SUM]

### ISSUE THREAD

**Issue by NyBela** [nav-gov-hu/Online-Invoice#919]
Fejlesztői támogatást kértem a #913-on egy hónapja.
Mivel nem érkezett választ, ezért szeretném hibaként jelezni.
Ez a probléma napi szinten keletkezik.

A probléma:
2020 november 25-én az alábbi levelet írtam, amit nem írnék le végig újból.
Az alábbi problémára keresek választ.
Érvénytelenítő , vagy helyesbítő számla esetén, a számla beküldése után ezt az üzenetet kapjuk vissza.
WARN / INCORRECT_PRODUCT_FEE_CALCULAT
A "Helytelen termékdíj-számítás. A termékdíjak termékkódonkénti összege eltér a termékdíj összesen értéktől. "
Az eredeti számla probléma nélkül elfogadásra került. Ez a jelenség kizárólag az érvénytelenítő, vagy a helyesbítő (vagyis negatív) előjelű esetben fordul elő. Ez már a 2.0-ban is probléma volt, de még a 3.0-ban is ezt tapasztaljuk.
A küldött XLS tartalma pontosan megegyezik az eredeti adattartalommal, a termékdíj számításban sincs semmilyen változás.
Bármilyen más érvénytelenítő számla (amin nincs termékdíj) megfelelően működik.
A számla tétele és az összesítő a számlavégén is megegyezik.
Kérek, választ arra, hogy hol van a probléma.
Köszönöm szépen

2020 november 26-án az Az NTCA válasza: "Megnéztem és valóban nem működik jól a warn. A 3.0 kapcsán amúgy is lesz egy nagyobb warning módosítás. Abba belevesszük ezt is. Köszi a jelzést!"
... majd pár üzenetváltás után.
2021.aug. 24-én NTCA "A bug javításra került már, zárom az issuet. Ha van még kérdés/hiba nyissatok újat kérlek. Üdv"

Sajnos ugyanaz a helyzet. A WARN-os visszajelzések éppúgy jönnek.
Kérem, a probléma újbóli ellenőrzését.
Köszönöm

**Comment by NTCA-supporter** [comment]
Szia @NyBela !
Kérlek teszt rendszerbe küld be az eredeti és a módosító számlát is ugyanazokkal a termékdíj adatokkal, és akkor meg tudjuk pontosan nézni, hogy hol a hiba.
A másik új issuet lezártam.

Köszönöm

**Comment by NyBela** [comment]
Szia!
Beküldtem és itt az eredmény.
Az alap és az érvénytelenítő számla is.
WARN üzenet van újból.
A tag jeleket [ ] -re cseréltem hogy be tudjam illeszteni.

2020 nov 26-án az 549-es hozzászólásban ezt az üzenetet kaptam rá az NTCA supportertől:
"Megnéztem és valóban nem működik jól a warn. A 3.0 kapcsán amúgy is lesz egy nagyobb warning módosítás. Abba belevesszük ezt is. Köszi a jelzést!"

Itt a mai példa:
Egy soros az egész demozás: 3x60=180 és a stornó -3x60=-180
Kérem, hogy nézzetek rá. Köszönöm.

[?xml version="1.0" encoding="UTF-8"?]
-[InvoiceData xsi:schemaLocation="http://schemas.nav.gov.hu/OSA/3.0/data invoiceData.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:base="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns="http://schemas.nav.gov.hu/OSA/3.0/data"]
[invoiceNumber]X2021/255[/invoiceNumber]
[invoiceIssueDate]2021-11-04[/invoiceIssueDate]
[completenessIndicator]false[/completenessIndicator]
-[invoiceMain]
-[invoice]
-[invoiceHead]
-[supplierInfo]
-[supplierTaxNumber]
[base:taxpayerId]xxxxxxxx[/base:taxpayerId]
[base:vatCode]2[/base:vatCode]
[base:countyCode]18[/base:countyCode]
[/supplierTaxNumber]
[supplierName]DEMO Kft[/supplierName]
-[supplierAddress]
-[base:simpleAddress]
[base:countryCode]HU[/base:countryCode]
[base:postalCode]9700[/base:postalCode]
[base:city]Szombathely[/base:city]
[base:additionalAddressDetail]Hosszú utca 28[/base:additionalAddressDetail]
[/base:simpleAddress]
[/supplierAddress]
[supplierBankAccountNumber]11111111-11111111-11111111[/supplierBankAccountNumber]
[/supplierInfo]
-[customerInfo]
[customerVatStatus]DOMESTIC[/customerVatStatus]
-[customerVatData]
-[customerTaxNumber]
[base:taxpayerId]xxxxxxxx[/base:taxpayerId]
[base:vatCode]2[/base:vatCode]
[base:countyCode]05[/base:countyCode]
[/customerTaxNumber]
[/customerVatData]
[customerName]DEMO KERESKEDELMI ES SZOLGALTATO KFT[/customerName]
-[customerAddress]
-[base:simpleAddress]
[base:countryCode]HU[/base:countryCode]
[base:postalCode]xxxx[/base:postalCode]
[base:city]MISKOLC[/base:city]
[base:additionalAddressDetail]xxxxxxxxxxxxxxxxxx[/base:additionalAddressDetail]
[/base:simpleAddress]
[/customerAddress]
[/customerInfo]
-[invoiceDetail]
[invoiceCategory]NORMAL[/invoiceCategory]
[invoiceDeliveryDate]2021-11-04[/invoiceDeliveryDate]
[currencyCode]HUF[/currencyCode]
[exchangeRate]1.000000[/exchangeRate]
[paymentMethod]TRANSFER[/paymentMethod]
[paymentDate]2021-11-12[/paymentDate]
[cashAccountingIndicator]false[/cashAccountingIndicator]
[invoiceAppearance]PAPER[/invoiceAppearance]
[/invoiceDetail]
[/invoiceHead]
-[invoiceLines]
[mergedItemIndicator]false[/mergedItemIndicator]
-[line]
[lineNumber]1[/lineNumber]
[lineExpressionIndicator]true[/lineExpressionIndicator]
[lineDescription]Fedél 600[/lineDescription]
[quantity]1.0000[/quantity]
[unitOfMeasure]PIECE[/unitOfMeasure]
[unitPrice]1000.0000[/unitPrice]
-[lineAmountsNormal]
-[lineNetAmountData]
[lineNetAmount]1000.00[/lineNetAmount]
[lineNetAmountHUF]1000.00[/lineNetAmountHUF]
[/lineNetAmountData]
-[lineVatRate]
[vatPercentage]0.27[/vatPercentage]
[/lineVatRate]
-[lineVatData]
[lineVatAmount]270.00[/lineVatAmount]
[lineVatAmountHUF]270.00[/lineVatAmountHUF]
[/lineVatData]
-[lineGrossAmountData]
[lineGrossAmountNormal]1270.00[/lineGrossAmountNormal]
[lineGrossAmountNormalHUF]1270.00[/lineGrossAmountNormalHUF]
[/lineGrossAmountData]
[/lineAmountsNormal]
[intermediatedService]false[/intermediatedService]
[obligatedForProductFee]true[/obligatedForProductFee]
-[lineProductFeeContent]
-[productFeeCode]
[productCodeCategory]CSK[/productCodeCategory]
[productCodeValue]E201701[/productCodeValue]
[/productFeeCode]
[productFeeQuantity]3.0000[/productFeeQuantity]
[productFeeMeasuringUnit]KG[/productFeeMeasuringUnit]
[productFeeRate]60.00[/productFeeRate]
[productFeeAmount]180.00[/productFeeAmount]
[/lineProductFeeContent]
[/line]
[/invoiceLines]
-[productFeeSummary]
[productFeeOperation]DEPOSIT[/productFeeOperation]
-[productFeeData]
-[productFeeCode]
[productCodeCategory]CSK[/productCodeCategory]
[productCodeValue]E201701[/productCodeValue]
[/productFeeCode]
[productFeeQuantity]3.0000[/productFeeQuantity]
[productFeeMeasuringUnit]KG[/productFeeMeasuringUnit]
[productFeeRate]60.00[/productFeeRate]
[productFeeAmount]180.00[/productFeeAmount]
[/productFeeData]
[productChargeSum]180.00[/productChargeSum]
[/productFeeSummary]
-[invoiceSummary]
-[summaryNormal]
-[summaryByVatRate]
-[vatRate]
[vatPercentage]0.27[/vatPercentage]
[/vatRate]
-[vatRateNetData]
[vatRateNetAmount]1000.00[/vatRateNetAmount]
[vatRateNetAmountHUF]1000.00[/vatRateNetAmountHUF]
[/vatRateNetData]
-[vatRateVatData]
[vatRateVatAmount]270.00[/vatRateVatAmount]
[vatRateVatAmountHUF]270.00[/vatRateVatAmountHUF]
[/vatRateVatData]
[/summaryByVatRate]
[invoiceNetAmount]1000.00[/invoiceNetAmount]
[invoiceNetAmountHUF]1000.00[/invoiceNetAmountHUF]
[invoiceVatAmount]270.00[/invoiceVatAmount]
[invoiceVatAmountHUF]270.00[/invoiceVatAmountHUF]
[/summaryNormal]
-[summaryGrossData]
[invoiceGrossAmount]1270.00[/invoiceGrossAmount]
[invoiceGrossAmountHUF]1270.00[/invoiceGrossAmountHUF]
[/summaryGrossData]
[/invoiceSummary]
[/invoice]
[/invoiceMain]
[/InvoiceData]


*** ÉRVÉNYTELENYÍTŐ SZÁMLA
[?xml version="1.0" encoding="UTF-8"?]
-[InvoiceData xsi:schemaLocation="http://schemas.nav.gov.hu/OSA/3.0/data invoiceData.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:base="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns="http://schemas.nav.gov.hu/OSA/3.0/data"]
[invoiceNumber]X2021/256[/invoiceNumber]
[invoiceIssueDate]2021-11-08[/invoiceIssueDate]
[completenessIndicator]false[/completenessIndicator]
-[invoiceMain]
-[invoice]
-[invoiceReference]
[originalInvoiceNumber]X2021/255[/originalInvoiceNumber]
[modifyWithoutMaster]false[/modifyWithoutMaster]
[modificationIndex]1[/modificationIndex]
[/invoiceReference]
-[invoiceHead]
-[supplierInfo]
-[supplierTaxNumber]
[base:taxpayerId]xxxxxxxx[/base:taxpayerId]
[base:vatCode]2[/base:vatCode]
[base:countyCode]18[/base:countyCode]
[/supplierTaxNumber]
[supplierName]DEMO Kft[/supplierName]
-[supplierAddress]
-[base:simpleAddress]
[base:countryCode]HU[/base:countryCode]
[base:postalCode]9700[/base:postalCode]
[base:city]Szombathely[/base:city]
[base:additionalAddressDetail]Hosszú utca 28[/base:additionalAddressDetail]
[/base:simpleAddress]
[/supplierAddress]
[supplierBankAccountNumber]11111111-11111111-11111111[/supplierBankAccountNumber]
[/supplierInfo]
-[customerInfo]
[customerVatStatus]DOMESTIC[/customerVatStatus]
-[customerVatData]
-[customerTaxNumber]
[base:taxpayerId]xxxxxxxx[/base:taxpayerId]
[base:vatCode]2[/base:vatCode]
[base:countyCode]05[/base:countyCode]
[/customerTaxNumber]
[/customerVatData]
[customerName]DEMO KERESKEDELMI ES SZOLGALTATO KFT[/customerName]
-[customerAddress]
-[base:simpleAddress]
[base:countryCode]HU[/base:countryCode]
[base:postalCode]3527[/base:postalCode]
[base:city]MISKOLC[/base:city]
[base:additionalAddressDetail]xxxxxxxxxxxxxxxxxxxxxxxxxxxxx[/base:additionalAddressDetail]
[/base:simpleAddress]
[/customerAddress]
[/customerInfo]
-[invoiceDetail]
[invoiceCategory]NORMAL[/invoiceCategory]
[invoiceDeliveryDate]2021-11-04[/invoiceDeliveryDate]
[currencyCode]HUF[/currencyCode]
[exchangeRate]1.000000[/exchangeRate]
[paymentMethod]TRANSFER[/paymentMethod]
[paymentDate]2021-11-08[/paymentDate]
[cashAccountingIndicator]false[/cashAccountingIndicator]
[invoiceAppearance]PAPER[/invoiceAppearance]
[/invoiceDetail]
[/invoiceHead]
-[invoiceLines]
[mergedItemIndicator]false[/mergedItemIndicator]
-[line]
[lineNumber]1[/lineNumber]
-[lineModificationReference]
[lineNumberReference]1[/lineNumberReference]
[lineOperation]MODIFY[/lineOperation]
[/lineModificationReference]
[lineExpressionIndicator]true[/lineExpressionIndicator]
[lineDescription]Fedél 600[/lineDescription]
[quantity]-1.0000[/quantity]
[unitOfMeasure]PIECE[/unitOfMeasure]
[unitPrice]1000.0000[/unitPrice]
-[lineAmountsNormal]
-[lineNetAmountData]
[lineNetAmount]-1000.00[/lineNetAmount]
[lineNetAmountHUF]-1000.00[/lineNetAmountHUF]
[/lineNetAmountData]
-[lineVatRate]
[vatPercentage]0.27[/vatPercentage]
[/lineVatRate]
-[lineVatData]
[lineVatAmount]-270.00[/lineVatAmount]
[lineVatAmountHUF]-270.00[/lineVatAmountHUF]
[/lineVatData]
-[lineGrossAmountData]
[lineGrossAmountNormal]-1270.00[/lineGrossAmountNormal]
[lineGrossAmountNormalHUF]-1270.00[/lineGrossAmountNormalHUF]
[/lineGrossAmountData]
[/lineAmountsNormal]
[intermediatedService]false[/intermediatedService]
[obligatedForProductFee]true[/obligatedForProductFee]
-[lineProductFeeContent]
-[productFeeCode]
[productCodeCategory]CSK[/productCodeCategory]
[productCodeValue]E201701[/productCodeValue]
[/productFeeCode]
[productFeeQuantity]-3.0000[/productFeeQuantity]
[productFeeMeasuringUnit]KG[/productFeeMeasuringUnit]
[productFeeRate]60.00[/productFeeRate]
[productFeeAmount]-180.00[/productFeeAmount]
[/lineProductFeeContent]
[/line]
[/invoiceLines]
-[productFeeSummary]
[productFeeOperation]DEPOSIT[/productFeeOperation]
-[productFeeData]
-[productFeeCode]
[productCodeCategory]CSK[/productCodeCategory]
[productCodeValue]E201701[/productCodeValue]
[/productFeeCode]
[productFeeQuantity]-3.0000[/productFeeQuantity]
[productFeeMeasuringUnit]KG[/productFeeMeasuringUnit]
[productFeeRate]60.00[/productFeeRate]
[productFeeAmount]-180.00[/productFeeAmount]
[/productFeeData]
[productChargeSum]-180.00[/productChargeSum]
[/productFeeSummary]
-[invoiceSummary]
-[summaryNormal]
-[summaryByVatRate]
-[vatRate]
[vatPercentage]0.27[/vatPercentage]
[/vatRate]
-[vatRateNetData]
[vatRateNetAmount]-1000.00[/vatRateNetAmount]
[vatRateNetAmountHUF]-1000.00[/vatRateNetAmountHUF]
[/vatRateNetData]
-[vatRateVatData]
[vatRateVatAmount]-270.00[/vatRateVatAmount]
[vatRateVatAmountHUF]-270.00[/vatRateVatAmountHUF]
[/vatRateVatData]
[/summaryByVatRate]
[invoiceNetAmount]-1000.00[/invoiceNetAmount]
[invoiceNetAmountHUF]-1000.00[/invoiceNetAmountHUF]
[invoiceVatAmount]-270.00[/invoiceVatAmount]
[invoiceVatAmountHUF]-270.00[/invoiceVatAmountHUF]
[/summaryNormal]
-[summaryGrossData]
[invoiceGrossAmount]-1270.00[/invoiceGrossAmount]
[invoiceGrossAmountHUF]-1270.00[/invoiceGrossAmountHUF]
[/summaryGrossData]
[/invoiceSummary]
[/invoice]
[/invoiceMain]
[/InvoiceData]



* ÜZENET
WARN
INCORRECT_PRODUCT_FEE_CALCULAT
Helytelen termékdíj-számítás. A termékdíjak termékkódonkénti összege eltér a termékdíj összesen értéktől.

**Comment by NTCA-supporter** [comment]
Valóban hibás a működés, javítani fogjuk.
Üdv

**Comment by NyBela** [comment]
Köszönöm a választ.
És mint már az elmúlt évben is kérdeztem, mire várható a javítás? Sajnos ez napi probléma.
Üdv.

**Comment by NTCA-supporter** [comment]
Sziasztok!
A javítás teszt rendszeren elérhető. Élesbe ma este megy.
Köszönjük a jelzést és a türelmet!
Üdv

**Comment by NyBela** [comment]
Szia!
Sajnos továbbra is ugyanaz a WARN-os hibaüzenet jön vissza termékdíjas érvénytelenítő, vagy módosító számla esetén.
Kivettem a termékdíjas részeket. A tag jeleket [ ] -re cseréltem hogy be tudjam illeszteni.
Itt a 4 számla sor és az összesítése. 
Köszönöm.

[line]
[lineNumber]1[/lineNumber]
.
.
.
[lineProductFeeContent]
[productFeeCode]
[productCodeCategory]KT[/productCodeCategory]
[productCodeValue]90001B1[/productCodeValue]
[/productFeeCode]
[productFeeQuantity]39.0900[/productFeeQuantity]
[productFeeMeasuringUnit]KG[/productFeeMeasuringUnit]
[productFeeRate]85.00[/productFeeRate]
[productFeeAmount]3322.65[/productFeeAmount]
[/lineProductFeeContent]
[/line]
[line]

[lineNumber]2[/lineNumber]
.
.
.
[lineProductFeeContent]
[productFeeCode]
[productCodeCategory]CSK[/productCodeCategory]
[productCodeValue]90001B1[/productCodeValue]
[/productFeeCode]
[productFeeQuantity]42.0000[/productFeeQuantity]
[productFeeMeasuringUnit]KG[/productFeeMeasuringUnit]
[productFeeRate]85.00[/productFeeRate]
[productFeeAmount]3570.00[/productFeeAmount]
[/lineProductFeeContent]
[/line]
[line]

[lineNumber]3[/lineNumber]
.
.
.
[lineProductFeeContent]
[productFeeCode]
[productCodeCategory]CSK[/productCodeCategory]
[productCodeValue]90001B1[/productCodeValue]
[/productFeeCode]
[productFeeQuantity]42.0000[/productFeeQuantity]
[productFeeMeasuringUnit]KG[/productFeeMeasuringUnit]
[productFeeRate]85.00[/productFeeRate]
[productFeeAmount]3570.00[/productFeeAmount]
[/lineProductFeeContent]
[/line]
[line]

[lineNumber]4[/lineNumber]
.
.
.
[lineProductFeeContent]
[productFeeCode]
[productCodeCategory]CSK[/productCodeCategory]
[productCodeValue]90001B1[/productCodeValue]
[/productFeeCode]
[productFeeQuantity]42.0000[/productFeeQuantity]
[productFeeMeasuringUnit]KG[/productFeeMeasuringUnit]
[productFeeRate]85.00[/productFeeRate]
[productFeeAmount]3570.00[/productFeeAmount]
[/lineProductFeeContent]
[/line]
[/invoiceLines]
.
.
.
[productFeeSummary]
[productFeeOperation]DEPOSIT[/productFeeOperation]
[productFeeData]
[productFeeCode]

[productCodeCategory]KT[/productCodeCategory]
[productCodeValue]90001B1[/productCodeValue]
[/productFeeCode]
[productFeeQuantity]39.0900[/productFeeQuantity]
[productFeeMeasuringUnit]KG[/productFeeMeasuringUnit]
[productFeeRate]85.00[/productFeeRate]
[productFeeAmount]3322.65[/productFeeAmount]
[/productFeeData]
[productFeeData]
[productFeeCode]

[productCodeCategory]CSK[/productCodeCategory]
[productCodeValue]90001B1[/productCodeValue]
[/productFeeCode]
[productFeeQuantity]126.0000[/productFeeQuantity]
[productFeeMeasuringUnit]KG[/productFeeMeasuringUnit]
[productFeeRate]85.00[/productFeeRate]
[productFeeAmount]10710.00[/productFeeAmount]
[/productFeeData]
[productChargeSum]14032.65[/productChargeSum]
[/productFeeSummary]

**Comment by NyBela** [comment]
Még annyit tennék hozzá, hogy most ez nem érvénytelenítő számla volt.

**Comment by NyBela** [comment]
Szia NTCA-supporter!

 

Utána néztem.

 

Annál a cégnél, ahol elő szokott rendszeresen fordulni, most nincs ilyen WARN üzenet.

Köszönöm ez érdeklődést.

 

Üdv.

Béla
