### ISSUE TITLE
[DOC] Új mezők nemkötelezősége technikailag vagy jogilag

### ISSUE THREAD

**Issue by bcdel** [nav-gov-hu/Online-Invoice#92]
**A hibás dokumentum neve / Document name containing the error**
Fájlnév vagy hostolt URL / File name or hosted URL.

API dokumentáció

**Oldalszám / Page number**
A hibát tartalmazó oldal száma / Page number containing the error.

76, 77, 148, 248-249

**A dokumentációs hiba leírása / Description of the documentation error**
Rövid és tömör összefoglalása a hibának. / A clear and concise description of the summary of the error.

A 2.0 átállással kapcsolatban új mezők kerültek bevezetésre.

például: periodicalSettlement, smallBusinessIndicator

Ezen mezők a sémadokumentáció szerint technikailag nem kötelezőek, de ez nem határozza meg, hogy ha relevánsak, akkor kell-e adatszolgáltatáskor szerepelniük az XML-ben, vagy elhagyhatóak-e.

a Mellékletek II. fejezetében lévő kötelezőségi összefoglalóban szükséges lenne az ilyen mezőkről is egyértelműen nyilatkozni.

**Comment by bcdel** [comment]
bővítem a listát: lineNatureIndicator

**Comment by NTCA-developer** [comment]
Köszi @bcdel, megnézzük és frissítjük a doksit ha indokolt.

**Comment by NTCA-developer** [comment]
Frissítettük a doksit, ezt nyitva hagyom addig amíg a publikáció meg nem történt.

**Comment by NTCA-developer** [comment]
Szia!

Kikerült a teszt és éles környezetre a frissített interfész dokumentáció,

**Comment by bakter80** [comment]
leírom mert meg*tt: a "periodicalSettlement"-re akartam keresni, és gyanúsan keveset találtam.
el van írva a doksiban: 
"periodicalSettelment" (263, 267. oldal)
