### ISSUE TITLE
[Q&A] Online pénztárgéppel kiállított blokk adatai meg fognak-e jelenni a NAV rendszerében?

### ISSUE THREAD

**Issue by erikapapp** [nav-gov-hu/Online-Invoice#920]
Érdeklődni szeretnék, hogy az online pénztárgéppel kiálított blokk esetében meg fognak-e jelenni adatok a NAV rendszerében a kimenő számlák között. 
Válaszukat előre is köszönöm.

**Comment by omachtandras** [comment]
@erikapapp : kiállítói oldalon lehet majd elérni az adatokat, de az egy másik projekt és sajnos eléggé csúszik. :(

https://github.com/nav-gov-hu/Online-Cash-Register-Logfile

**Comment by erikapapp** [comment]
@omachtandras Köszönöm a gyors választ.
