### ISSUE TITLE
[Q&A] Adózóknak küldött levél - INVALID_EXCHANGE_TOKEN hiba

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#922]
Sziasztok!

Hozzánk is megérkezett az első ügyfél megkeresés.
A NAV levele szerint neki "csak" INVALID_EXCHANGE_TOKEN hibája volt, ~150 db.

Átnéztük a logokat, minden számlája beküldve, mindegyikre lekérve NAVtól az állapot, minden rendben.
A logokban nincs ilyen hiba, de van egy elméletünk, hogy mi történhet(ett).

Első kérdésem, hogy a NAV, amikor legyűjtötte a hibákat, akkor ellenőrizte-e azt, hogy egy ilyen hibára futott számla később be lett-e küldve és valójában sikeres az adatszolgáltatás, csak volt olyan beküldés, amikor még nem volt az?

Második kérdés, hogy előfordulhat-e a következő:
1. Mi a küldés előtti időpillanatban generáljuk a tokent, tehát biztos nem telik el 5 perc a generálás és a beküldés közt.
2. Viszont a http timeout-unk 1 perc, így az előfordulhat, hogy 
- beküldjük a számlát
- a NAV terheltség miatt viszont nem válaszol 1 percig
- ekkor mi ezt logoljuk (az ügyfélnél több ilyen számla is van, ahol a logban látszik, hogy ez az 1 perces timeout elérkezett, idővel újra próbálkoztunk a beküldéssel és egy vagy több kísérlet után már siker koronázta kitartásunkat, a számla NAV által feldolgozásra került)
3. A NAVnál várakozik a terheltség miatt queue-ban az adat és mire feldolgozásra kerül, addigra eltelik az 5 perc és erre a hibára fut..., amit mi természetesen már nem kapunk meg, mert a http timeout miatt a csatorna lezárásra került...

A levélben az van, hogy az ügyfél ne válaszoljon rá.
Ha a fenti eset mondjuk nem fordulhat elő, hogyan tud meggyőződni az ügyfél arról, hogy a NAV szerint mely számláiról nem történt adatszolgáltatás?
Ez a cég havonta ~22.000 db számlát állít ki.
Mivel a program mindegyikre megkapta a NAVtól a feldolgozva választ, ami ellentmondásban van a NAV levelével, így látszólag csak az út marad számára, hogy egyesével lekérdezi mindegyiket a NAV felületén, hogy valóban ott van-e...
Ez eléggé lehetetlen küldetésnek tűnik.
Mit lehet tenni, hogy az ügyfél is megnyugodjon és a számlázó programra se égjen rá az, ami a levélben van: "Programhiba".

Köszönöm a válaszokat.

**Comment by renced42** [comment]
Kedves @omachtandras!

Ha a szoftveretek szerint sikeres az adatszolgáltatás az ügyfélnek nem kell semmit csinálnia.
A másik dolog, amit ellenőrzés képpen csinálnak az ügyfelek, hogy a gépi interfészen le tudja kérdezni mi van bent így a helyi és a remote adatból diffet lehet vonni. Ezt a funkciót attól függően, hogy hány rétegű a szoftver valahova implementálják és riportot készíthet vele.
De mivel a szoftvered biztos jó erre nincs szükség :)

**Comment by omachtandras** [comment]
@renced42 : azért ez ennyire nem egyszerű, az ügyfél az Adóhatóságtól kapott egy levelet, hogy "Kérjük, vegye fel a kapcsolatot az  online  számlaadat-szolgáltatásra  használt számlázóprogramjának fejlesztőjével a hibák okának feltárásához és elhárításához.  "

Ezzel az Ő és a mi felelősségi körünkbe utaltátok, hogy derítsük ki, hogy mi van a szerintetek feltárt hibák mögött.
Erre nem mondhatod azt, hogy "Ha a szoftveretek szerint sikeres az adatszolgáltatás az ügyfélnek nem kell semmit csinálnia.".
Mi bízunk a szoftverünkben, ennek ellenére próbálunk megfelelni annak az elvárásnak, hogy kiderüljön, ha tényleg probléma van. De ehhez támogatás kell, több, mint ami a levélből kiolvasható.

Első körben sokat segítene, ha a kérdéseimre kapnék válaszokat.

Köszönöm.

**Comment by renced42** [comment]
Kedves @omachtandras 

A vizsgálat nem arra vonatkozott, hogy be lett-e egy számla küldve vagy sem, hanem arra, hogy a beküldéskor milyen hibák keletkeztek. Ezeket próbáljuk felszámolni, minimalizálni. Javaslatok mástól is érkeztek, ezeket vizsgálni fogjuk, hogy a következő alkalommal, még milyen infót tegyünk bele a tájékoztatásba, hogyan lehetne ezt még hatékonyabbá tenni. A timeout probléma biztosan valós és ezzel kapcsolatban adtál is egy ötletet.

**Comment by omachtandras** [comment]
@renced42 : nem tudom, hogy pontosan mi jutott eszedbe a timeout kapcsán, de nekem a következő: az INVOICE_NUMBER_NOT_UNIQUE "hibát" is megoldaná nálunk, ha a lassú feldolgozásos időszakokban, amikor 1 percen belül nem kapunk választ és timeout-olunk Ti nem dolgoznátok már fel a beküldött adatot, hiszen azt mi újra meg fogjuk kísérelni majd később beküldeni. Most ugye valamikor feldolgozásra kerül, de addigra mi már lehet újra beküldjük, mert hiába implementáltuk az itt korábban leírt és elvárt megoldást, ahogy másoknál is, nálunk is előfordul néha terhelt időszakokban, hogy olyan választ kapunk az első tranzakcióval kapcsolatban, hogy újra beküldjük a számlát és akkor derül ki, hogy mégis fel van dolgozva és válthatunk arra a tranzakcióra.

**Comment by Mocsa1974** [comment]
> @renced42 : nem tudom, hogy pontosan mi jutott eszedbe a timeout kapcsán, de nekem a következő: az INVOICE_NUMBER_NOT_UNIQUE "hibát" is megoldaná nálunk, ha a lassú feldolgozásos időszakokban, amikor 1 percen belül nem kapunk választ és timeout-olunk Ti nem dolgoznátok már fel a beküldött adatot, hiszen azt mi újra meg fogjuk kísérelni majd később beküldeni. Most ugye valamikor feldolgozásra kerül, de addigra mi már lehet újra beküldjük, mert hiába implementáltuk az itt korábban leírt és elvárt megoldást, ahogy másoknál is, nálunk is előfordul néha terhelt időszakokban, hogy olyan választ kapunk az első tranzakcióval kapcsolatban, hogy újra beküldjük a számlát és akkor derül ki, hogy mégis fel van dolgozva és válthatunk arra a tranzakcióra.

Az INVOICE_NUMBER_NOT_UNIQUE problámára mi a következőt csináljuk:

1. Számla beküldés előtt a tokenkérésnél ha timeout van, akkor a számla tuti újra beküldhető mivel a manageInvoice el se tud indulni.

2. Ha a manageInvoice operációnál jön timeout (a mi klines oldali timeoutunk 1 perc, a NAV-é 5 perc) akkor a számla következő beküldési időpontját +6percre állítjuk. (hogy a NAV-os timeout tuti bekövetkezzen ha egyáltalán lesz timeout).

3. Küldés előtt megnézzük, hogy a saját adatbázisunkban van-e a számlához a NAV által generált transactionID. (mangeInvoice timeout esetén nem lesz, viszont ez nem jelenti azt hogy a NAV-nál sem lesz).

4. A queryInvoiceData operációval megnézzük hogy szerepel-e a NAV-nál a számla. (Ha szerepel, mert a manageInvoice nálunk timeout-tal elszállt viszont a NAV mondjuk 3 perc múlva mégis feldolgozta a számlát) akkor a queryInvoiceData által visszaadott válaszban ott a transactionID. Azzal lekérdezzük a számla státuszát.

5. Ha a queryInvoiceData nem ad vissza számlaadatot, akkor ismét simán beküldhető a számla (mert nincs ott a NAV-nál és az 5 perces timeout miatt már nem is lesz ott soha az előző manageInvoice hívásra).

**Comment by omachtandras** [comment]
@Mocsa1974 : köszi a leírást. A 2. pontban mi nem várjuk ki a +6 percet, ezen most módosítani fogunk, hátha az segít valamit.
