### ISSUE TITLE
[Q&A] Új blokkoló validációk pontosítás

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#927]
A 3.11-es verzióban két új blokkoló validáció került be:

- INVOICE_DELIVERY_DATE_LATE, ha a teljesítés időpontja későbbi, mint a kiállítás időpontja plusz 5 év;
- INVOICE_ISSUE_DATE_LATE, ha a kiállítás időpontja későbbi, mint a beküldés időpontja plusz 1 év

A "későbbi" szót nem szeretem, mert mindig két értelme van:
1. Ha a teljesítés dátuma 2015 és a kiállítás időpontja 2021, akkor a teljesítési dátuma későbbi, mivel régebben (tehát később) történt, mint a kiállítás.
2. Ha a teljesítés dátuma 2027 és a kiállítás időpontja 2021, akkor a teljesítési dátuma későbbi, mivel a kiállítás/mai nap után (tehát később) történik.

A kérdés, hogy melyik esetre gondolt a "költő"?

Ugyanez a kérdés INVOICE_ISSUE_DATE_LATE esetén is. Sőt, ott ez különösen zavarba ejtő, mivel alapvetően a kelte, mindig a mai nap, amikor pedig azonnal megtörténik a beküldés is. Ha viszont valaki állítgatja a rendszerdátumot, akkor zavarossá válik, hogy mi számít "későbbnek". Sajnos a dokumentációban sem lett ez részletezve, jó lett volna egy konkrét példát hozni, hogy tényleg teljesen egyértelmű legyen, mert értelmezhető így is és úgy is.

**Comment by Macskafarka** [comment]
Számomra az egész szigorítás érthetetlen. **Mi az, hogy blokkolja a NAV az adatszolgáltatást egy ténylegesen kiállított számláról? Hol van a jogszabályi alapja, hogy ez megtehető lenne?** Ha egy 2015-ös teljesítési dátumú számlát 2019-ben módosítottak, akkor az adóügyi elévülése az utolsó módosítástól kezdve újraindul. Ha a 2021-es ismételt módosító okiratot blokkolják, akkor a NAV adatbázisa hiányos lesz. Ettől még a számlabefogadónak joga van levonásba helyezni  az ilyen számlát.
A másik: a 2010-es dátum korlát bevezetése is problémákat okozott egyik ügyfelünknél, ahol bírósági ítélet miatt kellett új számlát kiállítani 2010 előtti Teljesítési dátummal. 
Jó lenne. ha az OSZ blokkoló üzeneteit alaposabb szakmai megfontolások alapján állítanák össze, és eldobásra kerülnének azok, amelyek nem jogszabályon alapulnak.
Azt kell belátni, hogy nem az a cél, hogy a NAV elképzelésének megfelelő adatbázist állítsanak össze, hanem az, hogy az adólanyok teljesíteni tudják a számlaadat-szolgáltatási kötelezettségüket.

**Comment by Macskafarka** [comment]
Akkor lenne elfogadható a blokkolás, ha a jogszabályba bekerülne az a rész, hogy a számlakiállítók MENTESÜLNEK a számlaadat-szolgáltatási kötelezettségük teljesítése alól, ha bizonyítani tudják, hogy a NAV akárcsak egyszer is blokkolta az adott számlaláncolat bármelyik elemének a befogadását. Ekkor mentesülnek az adóügyi, polgári jogi és büntetőjogi következményei alól.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ezt a választ kaptam:
"Itt egy félreértés látszik a kérdésben: ami régebben történt, az korábban történt (nem később), a blokkoló validációk helyesek.
Az INVOICE_DELIVERY_DATE_LATE az extrém módon (5 év) a jövőbe dátumozott teljesítési időpontot szűrik, ami teljesen indokolt.
Az INVOICE_ISSUE_DATE_LATE azokat az eseteket szűri, amikor a beküldés időpontjához képest extrém módon (1 év) előre dátumozza a számla keltét.
Mindkét esetben indokolt az ERROR."
Üdv

**Comment by nbeeps2** [comment]
@NTCA-supporter: oké, én egy szóval nem mondtam, hogy nem helyesek, csak számomra nem volt egyértelmű, ezért szerettem volna a pontosítást. Köszönöm.

**Comment by Macskafarka** [comment]
@NTCA-supporter részemről így rendben van.  
Csak az én fantáziám szegényes, hogy nem tudok elképzelni olyan életszerű esetet, hogy valaki a számla keltét a beküldés dátumához képest előre dátumozza akárcsak 1 nappal is. Ez azt jelenti, hogy a ma még ki sem állított számlát beküldik.

**Comment by sinick2** [comment]
@Macskafarka: Életszerű. Van ilyen már kicsiben is. A cég 100 ügyfelének számláz valami havidíjat szerződés szerint pl. december 1 keltével. A számlát postán küldi, borítékoz, a borítékba rak még más anyagot, talán még valami egyedi csomagot is kell összeállítani hozzá, ami ügyfelenként más és más, stb. Tehát nem a számlázás veszi el ebből a legtöbb időt. Egyedül van, ezért már november 30-án és 31-én megcsinál 50-50 darabot, mert egy napi teendőbe nem ér bele, 1-én már csak postázza. Így csinálja, mert így csinálja 10 éve.

**Comment by nbeeps2** [comment]
@sinick2 : hát ez így nem szabályos és felesleges is. A számla kelte az a nap, amikor a számlát kiállítják. Tehát, ha november 30-án csinál 50 db számlát, akkor november 30. a kelte és nem lehet december 1. Másrészt semmi értelme nincs is a keltét manipulációval (pl. rendszeridő átállítás) állítani, mivel számvitelileg csakis a teljesítési dátum számít és senkit nem érdekel, hogy novemberi vagy decemberi a kelte, mert a teljesítési dátum lesz a meghatározó. Az, hogy így csinálja 10 éve az nem azt jelenti, hogy jól csinálta, számos hasonló számlázási rossz gyakorlatot lehetne példaként felhozni.

**Comment by omachtandras** [comment]
@nbeeps2 : egyetértek, ne csináljon ilyet. De a teljesítési dátum mindenhatóságában azért ne bízzunk, vannak esetek pl. ÁFA szempontjából is, amikor nem az a mérvadó. A mi ügyfeleink közül néhányat pl. már a NAV megkeresett, hogy miért úgy vallja be az ÁFÁját, ahogy, miért nem teljesítési dátum szerint. Elég mérgesek is, megy az idejük az ilyen ellenőrzésekkel, de már elég felkészültek, elég a megfelelő NAVos füzetecskét elővenni, hogy meggyőzzék az ellenőrt, hogy a NAV sem gondolja mindig komolyan, hogy csak a teljesítési dátum számít. :)

Egyébként én olyan esetekben láttam ilyen "trükközést", amikor pl. a fizetési határidőt szerződésileg a számla kiállítási dátumához kötik, azt meg mondjuk a hó első napjához... És, ha sok ilyen szerződés van, és kevés számlázó, akkor jön a @sinick2  által leírt trükközés. (Vannak olyan programok, ahol a számla csak kiállítható, nincs mondjuk olyan tudása, hogy összeállítom, de érvényesíteni majd egy kötegben szeretném valamikor az összeset...)

**Comment by sinick2** [comment]
@nbeeps2: Persze, nyilván, de ez most nem számviteli kérdés. Egyébként - ha jól emlékszem - van ennek "szabályos" változata is, amikor a számla adatait "lezárják" és a számlát nyomdai úton állítják elő, aminek átfutása 1-2 nap. Eleve az OSA is 5 napon túli keltére küld WARN-t. Valahol ez a speciális eset le van írva, vagy itt, vagy a prog.hu, vagy valamelyik OSA doksiban olvastam.
