### ISSUE TITLE
Bejövő számlák excel export hiba Tesztrendszeren

### ISSUE THREAD

**Issue by GabiSzamla77** [nav-gov-hu/Online-Invoice#933]
Sziasztok!
A tesztrendszeren ha egy bejövő számlát szeretnék excelbe exportálni, akkor a fájl nem jön létre. Egyesével sem, és több számlával sem.
(Az élesen jól működik.)

**Comment by NTCA-supporter** [comment]
Szia!

Első körben segíts kérlek, hogy a Lista Export-ról van szó vagy az Export-ról. Ha az Export-ról akkor a Szolgáltatások/Dokumentumok oldalon nézted és ott nem jött létre a fájl? Ha küldesz adószámot akkor utána tudok nézni.

**Comment by GabiSzamla77** [comment]
Nem a Lista Export, hanem a másik kettő: 
- egy számla esetén jobb egérgombbal a Műveleteknél a Számla export magyar nyelven: ilyenkor ERROR kezdet van a fájl nevében, de megnyitni nem lehet, a Dokumentumoknál pedig az van, hogy a fájl nem létezik.
- ha két vagy több számlát kijelölök, és katt. az Export-ra, akkor is a Dokumentumoknál a "fájl nem létezik" a jelölés a letöltés ikonnál.
Adószám: 65305911
Köszönöm.

**Comment by NTCA-supporter** [comment]
Köszi az infokat, nézzük. Jelzünk, ha megoldódott.
Üdv

**Comment by NTCA-supporter** [comment]
Javítva, köszi mégegyszer a jelzést.
Üdv
