### ISSUE TITLE
Technical annulment -  Content Issues - Single invoice annulment

### ISSUE THREAD

**Issue by abin2hats** [nav-gov-hu/Online-Invoice#934]
Hi

I am trying to create a Technical annulment.

Technical annulment was created with status = "Saved" and Wzarn count 0

But there is a message Content Issues

Information
- Single invoice annulment
–  Tag: InvoiceData/invoiceNumber
–  Value: INV1920746077

What is wrong with this?

**Comment by csandazoltan** [comment]
English documentation 2.4 Technical annulment of previous data report

I don't see any InvoiceData/invoiceNumber tag, those are for creation and modification

Annulment uses a different xml structure
InvoiceAnnulementType
- annulementReference
- annulmentTimestamp
- annulmentCode
- annulmentReason

Also Technical annulements use a whole different API entry /manageAnnulment

**Comment by abin2hats** [comment]
Yes there is no invoiceNumber in the manageAnnulment API, but the annulementReference is the invoiceNumber

"The processing system applies technical annulment on the basis of the number for the invoice or
the invoice-equivalent document (invoiceNumber element), which shall be stored in the
annulmentReference element in the data report on the technical annulment."

**Comment by csandazoltan** [comment]
Then I don't understand what is the issue

**Comment by NTCA-supporter** [comment]
Hi @abin2hats !
It's just an informational message, that the annulment references to the INV1920746077 invoice. (This message makes more sense when the annulment refers to an invoice chain, then you get the items of the chain.)
Your request is OK, so no worries.
It's important that you have to approve/decline the annulment on the web UI (Declarations/Data disclosure annulment menu).

Br

**Comment by abin2hats** [comment]
Thank you
