### ISSUE TITLE
[DOC] A vatRateVatAmountHUF kötelezősége

### ISSUE THREAD

**Issue by ervinvarga** [nav-gov-hu/Online-Invoice#94]
**A hibás dokumentum neve / Document name containing the error**
Fájlnév vagy hostolt URL / File name or hosted URL.

Online Szamla_Interfesz specifikáció_HU_v2.0.pdf 
invoiceData.xsd 

**Oldalszám / Page number**

A hibát tartalmazó oldal száma / Page number containing the error.
91. oldal/vatRateVatAmountHUF 

**A dokumentációs hiba leírása / Description of the documentation error**
Rövid és tömör összefoglalása a hibának. / A clear and concise description of the summary of the error.

A vatRateVatAmountHUF kötelezősége: 

A tesztjeink során felmerült egy kérdésünk a vatRateVatAmountHUF (Az adott adómértékhez tartozó értékesítés vagy szolgáltatásnyújtás ÁFA összege forintban) mező kapcsán. A számlaadat a korábbi, 1.1-es sémában nem kötelező mezőként volt meghatározva, azonban a jelenlegi struktúrában nem szerepel mellette az ezt jelölő minOccurs=0 érték.

A Számla adatszolgáltatás REST API interfészleírás és fejlesztői dokumentáció 2.0-ás verzióját vizsgálva azonban ezzel ellentétben azt láttuk, hogy a kérdéses mező továbbra is nem kötelezőként van jelölve. 

A fenti kérdés kapcsán szeretnénk megerősítésüket kérni arról, hogy ebben az esetben melyik leírás irányadó a gyakorlatban.

**Comment by NTCA-developer** [comment]
Szia @ervinvarga !

Ez egy dokumentációs hiba, a táblázatban a kötelezőség valóban nem jó. (Nem kötelezőként szerepel, de a sémában az). 

Javítjuk, ezt addig nyitva hagyom amíg ki nem ment.

**Comment by ervinvarga** [comment]
Szia @NTCA-developer, 

Én köszönöm a gyors visszajelzést! Akkor ha jól értem haladhatunk aszerint, hogy a vatRateVatAmountHUF a 2.0-ás séma verziótól kötelező mező (ahogy az XSD-ben van).

**Comment by NTCA-developer** [comment]
Szia!

Igen, a séma az irányadó.

**Comment by NTCA-developer** [comment]
Szia!

Kikerült a teszt és éles környezetre a frissített interfész dokumentáció.
