### ISSUE TITLE
[Q&A]

### ISSUE THREAD

**Issue by tothjozsefferenc** [nav-gov-hu/Online-Invoice#940]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Számla feltöltésekor INVALID_SECURITY_USER - ERROR - Helytelen authentikációs adatok! (2) hibát kapok vissza.
Felhasználó technikai adatait ellenőriztem, és helyesek.
Felhasználónév: mscew4agkd3dzsl

Példa:
<?xml version="1.0" encoding="UTF-8"?>
<InvoiceData xmlns="http://schemas.nav.gov.hu/OSA/3.0/data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.nav.gov.hu/OSA/3.0/data invoiceData.xsd" xmlns:base="http://schemas.nav.gov.hu/OSA/3.0/base">
    <invoiceNumber>9758</invoiceNumber>
    <invoiceIssueDate>2021-12-19</invoiceIssueDate>
    <completenessIndicator>false</completenessIndicator>
    <invoiceMain>
        <invoice>
            <invoiceHead>
                <supplierInfo>
                      <supplierTaxNumber>
                          <base:taxpayerId>13623388</base:taxpayerId>
                          <base:vatCode>2</base:vatCode>
                          <base:countyCode>42</base:countyCode>
                      </supplierTaxNumber>
                    <supplierName>Medscan Kft</supplierName>
                    <supplierAddress>
                        <base:detailedAddress>
                            <base:countryCode>HU</base:countryCode>
                            <base:postalCode>1067</base:postalCode>
                            <base:city>Budapest</base:city>
                            <base:streetName>Eötvös</base:streetName>
                            <base:publicPlaceCategory>utca</base:publicPlaceCategory>
                            <base:number>25/a</base:number>
                        </base:detailedAddress>
                    </supplierAddress>
                </supplierInfo>
                <customerInfo>
                    <customerVatStatus>PRIVATE_PERSON</customerVatStatus>
                </customerInfo>
                <invoiceDetail>
                    <invoiceCategory>NORMAL</invoiceCategory>
                    <invoiceDeliveryDate>2021-12-19</invoiceDeliveryDate>
                    <currencyCode>HUF</currencyCode>
                    <exchangeRate>1</exchangeRate>
                    <paymentMethod>CASH</paymentMethod>
                    <paymentDate>2021-12-19</paymentDate>
                    <invoiceAppearance>PAPER</invoiceAppearance>
                </invoiceDetail>
            </invoiceHead>
            <invoiceLines>
            <mergedItemIndicator>false</mergedItemIndicator>
                <line>
                    <lineNumber>1</lineNumber>
                    <productCodes>
                        <productCode>
                            <productCodeCategory>OWN</productCodeCategory>
                            <productCodeOwnValue>4060</productCodeOwnValue>
                        </productCode>
                    </productCodes>
                    <lineExpressionIndicator>false</lineExpressionIndicator>
                    <lineDescription>Vending / Élelmiszer árú értékesítés</lineDescription>
                    <quantity>2</quantity>
                    <unitOfMeasure>OWN</unitOfMeasure>
                    <unitOfMeasureOwn>db</unitOfMeasureOwn>
                    <unitPrice>260</unitPrice>
                    <unitPriceHUF>260</unitPriceHUF>
                    <lineAmountsNormal>
                        <lineNetAmountData>
                            <lineNetAmount>520</lineNetAmount>
                            <lineNetAmountHUF>520</lineNetAmountHUF>
                        </lineNetAmountData>
                        <lineVatRate>
                            <vatPercentage>0.27</vatPercentage>
                        </lineVatRate>
                        <lineVatData>
                            <lineVatAmount>140</lineVatAmount>
                            <lineVatAmountHUF>140</lineVatAmountHUF>
                        </lineVatData>
                        <lineGrossAmountData>
                            <lineGrossAmountNormal>660</lineGrossAmountNormal>
                            <lineGrossAmountNormalHUF>660</lineGrossAmountNormalHUF>
                        </lineGrossAmountData>
                    </lineAmountsNormal>
                </line>
            </invoiceLines>
            <invoiceSummary>
                <summaryNormal>
                    <summaryByVatRate>
                        <vatRate>
                            <vatPercentage>0.27</vatPercentage>
                        </vatRate>
                        <vatRateNetData>
                            <vatRateNetAmount>520</vatRateNetAmount>
                            <vatRateNetAmountHUF>520</vatRateNetAmountHUF>
                        </vatRateNetData>
                        <vatRateVatData>
                            <vatRateVatAmount>140</vatRateVatAmount>
                            <vatRateVatAmountHUF>140</vatRateVatAmountHUF>
                        </vatRateVatData>
                        <vatRateGrossData>
                            <vatRateGrossAmount>660</vatRateGrossAmount>
                            <vatRateGrossAmountHUF>660</vatRateGrossAmountHUF>
                        </vatRateGrossData>
                    </summaryByVatRate>
                    <invoiceNetAmount>520</invoiceNetAmount>
                    <invoiceNetAmountHUF>520</invoiceNetAmountHUF>
                    <invoiceVatAmount>140</invoiceVatAmount>
                    <invoiceVatAmountHUF>140</invoiceVatAmountHUF>
                </summaryNormal>
                <summaryGrossData>
                    <invoiceGrossAmount>660</invoiceGrossAmount>
                    <invoiceGrossAmountHUF>660</invoiceGrossAmountHUF>
                </summaryGrossData>
            </invoiceSummary>
        </invoice>
    </invoiceMain>
</InvoiceData>

**Comment by NTCA-supporter** [comment]
Kedves @tothjozsefferenc!

Kérlek segíts, hogy ez melyik környzeten kapod. Teszt vagy éles?

**Comment by tothjozsefferenc** [comment]
Kedves Support,

A hibaüzenetet az éles környezetbe kaptam.

Köszönöm
József

**Comment by NTCA-supporter** [comment]
Akkor sajnos mi nem tudunk segíteni. Mi csak a teszt környezeten nézhetünk ilyen jellegű hibákat. Az élesen a következő elérhetőségek egyikén tudsz segítséget kérni: 
Segítség telefonon
A NAV Infóvonalán, a 1819-es telefonszámon a 7. menüpontban választható témák:
almenüpont: Segítségnyújtás Online Számla bejelentkezés
almenüpont: A jogszabály értelmezése
almenüpont: Informatikai segítség
almenüpont: A NAV Online Számlázó programja használatával kapcsolatos segítség
Segítség e-mailben
A https://www.nav.gov.hu/nav/e-ugyfsz/e-ugyfsz.html linken a levélküldésre kattintva kiválaszthatja üzenete tárgyát. Például:
  „Számlaadat-szolgáltatás, jogértelmezési kérdések”,
  „Számlaadat-szolgáltatás, informatikai problémák ÉLES környezetben”, illetve
  „Online Számlázó informatikai problémák ÉLES környezetben”.
