### ISSUE TITLE
[Q&A] Számlázó programot fejlesztőknek szánt ajánlás bővítéséhez javaslatok

### ISSUE THREAD

**Issue by omachtandras** [nav-gov-hu/Online-Invoice#941]
Sziasztok!

Létezik egy ajánlása a NAVnak a számlázó programot fejlesztőknek:
https://nav.gov.hu/nav/ado/afa/NAV_ajanlas_a_szamlaz20210303.html

Nem tudom, hogy tervben van-e ennek bővítése, módosítása, de ha igen, akkor lennének javaslataim a számlakép és adatszolgáltatás eltérésére vonatkozóan. **_Bele kellene írni, hogy az adatszolgáltatás arról szól, ami a számlán szerepel._**
1. Találkoztunk olyan számlázó rendszerrel, amely megteszi azt, hogy más kulcsot ad át az adatszolgáltatásban, mint ami a számlaképen szerepel. Konkrétan arról van szó, hogy a 0%ot engedi a számlára nyomtatni, de az adatszolgáltatásban helyette már betűs kódot ad át. Azt nem tudom, hogy mi a cserélési algoritmus, de leveleztem velük, és elismerték, hogy azért, hogy ne legyen NAV adatszolgáltatás hiba ők ezt a "user error"-t így javítják. Jó lenne, ha lehetne hivatkozni egy NAV ajánlásra, hogy ez így nem ok.  (Gondolom azért nem érdekli őket, mert úgysincs adófizetési kötelezettség...)
2. Az adatszolgáltatásban tizedeses összegek szerepelnek, míg a számlaképen kerekítettek. Erre is jó lenne felhívni a figyelmet, hogy ha kerekítve nyomtatja a számlaképre, akkor tárolja is úgy az adatbázisában, és adja át azt a NAVnak, vagy pedig tegye meg, hogy kerekítés nélkül jeleníti meg a számlaképen. (Itt meg gondolom azért nem érdekli őket, mert 1000 ft-ban van a bevallás, és úgysem derül ki az ilyen kis eltérés...)
3. A számlaképen szerepel a határozott időszakiság ténye, és a dátumok is. Az adatszolgáltatásban azonban minderről semmi. Itt olyan válasz volt, hogy ezt később a rendszerükben átállíthatja az ügyfél, mert ez könyvelési adat, és ezért nem adják át. Próbáltam rávilágítani, hogy ez az adat ÁFÁ-t vezérel a befogadó oldalon, és ezért, ha módosul, akkor azt tudtára kellene adni a partnernek valamilyen egy tekintet alá eső okirat formájában, de itt elhalt a levelezés...

Ezek mind olyan hibák, amikre nem lehet warningot, vagy errort tenni, hiszen a számlaképet a NAV nem látja, viszont vannak olyan kollégák, akikkel hiába levelez az ember, mivel nincsenek ezek az esetek nevesítve sehol azt a választ kapjuk (ha egyáltalán kapunk :)) hogy bocs, de semmi nem írja elő ezt vagy azt. Nehéz küzdeni velük, mert ezek a dolgok valóban triviálisnak tűnnek és - véleményem szerint - kiolvashatók a törvényekből / rendeletekből, mint elvárások, de nem tudok konkrét szövegrészre hivatkozni, ezért elhajtanak... És, most, hogy az EÁFA is lekerült a napirendről még magabiztosabban gondolhatják, hogy úgysem derül ki soha, a NAV még annyi visszajelzést sem fog kapni a befogadó oldaltól, mint az EÁFA esetén kapott volna...

+1. Ezt az esetet csak elgondolkodtató példaként írom, nem vagyok benne biztos, hogy lehet bármit tenni ellene warning vagy error szinten, úgy, hogy ne okozzunk valós eseményeknél problémát.
Sikerült egy olyan számla + x db módosító láncolatot összehozni a számlázó programnak, hogy a végén, ha összevontuk az egészet, akkor egyetlen olyan sor maradt, aminek a mennyisége negatív előjelű volt, az egységára szintén negatív előjelű, de a szorzatuk már pozitív, így tulajdonképpen kijött, hogy mekkora összeget vár el a szállító az egyébként teljesített szolgáltatásért....
Ha a NAV elkészít mindig egy pillanatnyi állapotot a láncolatból, akkor elvileg tudhatja, hogy csak olyan sor van rajta, ami negatív mennyiséget és negatív egységárat tartalmaz, tehát adhatna erre is warningot, és talán több értelme is lenne, mint a lánckezdő számla VÉGÖSSZEGE nem lehet negatív esetnek, mert ez valóban programhiba, nem lehet olyan gazdasági esemény, amely esetén negatív mennyiséget negatív egységárral teljesítek és még pénzt is kapok érte...

**Comment by omachtandras** [comment]
A 0%os kulcsnál erre a részre való hivatkozás sem hatotta meg őket:
"A számlázó programokban előforduló technikai megoldás az adatbázisban 0%-os adókulcs tárolása az egyes számításokhoz. Ilyen adókulcs a hatályos áfatörvényben nem létezik, ezen esetekben valójában a mentességek, hatályon kívüliségek valamely esetéről van szó. A számlázó programban el kell kerülni – akár a számlakiállítási folyamat blokkolásával is – a 0%-os adókulcs használatát a számlaképen és az adatszolgáltatásban akkor is, ha a program működésében használt táblákban esetleg szerepel ilyen.
Ajánlás-30: Az adómentességek eseteit (adómentességi hivatkozások) javasolt a számlázó programban törzsadatként kezelni (adótábla). Így a számla adattartalmi minősége is megfelelőbb lesz, és ezzel a számlaadat-szolgáltatásnál is számos problémát el lehet kerülni."

**Comment by omachtandras** [comment]
Azt elmúlt hetek "sztárja" a következő: előleg számla betudó végszámla az előleg számla helyesbítéseként kerül átadásra.
Van, hogy annyit még sikerül megugrani, hogy az előleg tényét jelzik, de van, hogy már azt sem.

Sajnos most nem tudom elérni a NAV oldalán a számlázó programok fejlesztőinek szóló ajánlást, így nem tudom ellenőrizni, hogy erre vonatkozóan van-e benne bármilyen figyelmeztetés, de ha nincs, akkor jó lenne kiemelni, hogy a dokumentációban nagyon jól le van írva, hogy mit is kellene tenni ilyen számlák esetében.

**Comment by NTCA-tax** [comment]
Köszönjük a felvetéseket, továbbítottam a megfelelő személyhez. 

Az ajánlást itt tudod elérni: https://nav.gov.hu/pfile/file?path=/ado/afa/Szamlazo_Fejlesztoi_Ajanlas_v1.0 Azt nem tudom, hogy 25 nappal ezelőtt hogyan lehetett, de ahogy megérkezik a már többször megigényelt időgépem, akkor megnézem :)
