### ISSUE TITLE
Hibás adószám. A vevő nem élő adózó!

### ISSUE THREAD

**Issue by kristofbela** [nav-gov-hu/Online-Invoice#943]
Hibás adószám. A vevő nem élő adózó! miért kaptam az adószám lekérdezésekor ez az üzenetet??

**Comment by NTCA-supporter** [comment]
Szia @kristofbela!
Segíts egy kicsit, ennyiből sajnos még nekünk sem megy a megfejtés :)
Melyik környezet? Melyik adószám? Az interfészes/webes lekérdezésről van szó?
Üdv

**Comment by kristofbela** [comment]
éles 3MLT9HUX6PLM27ST
adószam 26562874
lekerdeztem most jónak tünik

?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns2:QueryTransactionStatusResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data"><header><requestId>QAmfxOeH0E6Jc+VUZPzTCQ</requestId><timestamp>2022-01-04T12:24:07.784Z</timestamp><requestVersion>3.0
/
/
/
/
</ns2:invoiceStatus><ns2:businessValidationMessages><ns2:validationResultCode>WARN</ns2:validationResultCode><ns2:validationErrorCode>INCORRECT_HEAD_DATA_CUSTOMER_TAXPAYERID</ns2:validationErrorCode><ns2:message>Hibás adószám. A vevő nem élő adózó!</ns2:message><ns2:pointer><ns2:tag>InvoiceData/invoiceMain/invoice/invoiceHead/customerInfo/customerVatData/customerTaxNumber/taxpayerId</ns2:tag><ns2:value>26562874</ns2:value></ns2:pointer></ns2:businessValidationMessages><ns2:compressedContentIndicator>false</ns2:compressedContentIndicator></ns2:processingResult><ns2:originalRequestVersion>3.0</ns2:originalRequestVersion></ns2:processingResults></ns2:QueryTransactionStatusResponse>

**Comment by NTCA-supporter** [comment]
Zárom ezt az issuet, az éles rendszert itt nem tudjuk támogatni.
Üdv
