### ISSUE TITLE
invoiceOperation STORNO vs. MODIFY [Q&A]

### ISSUE THREAD

**Issue by szkomaromi-contactplus** [nav-gov-hu/Online-Invoice#944]
Helytelenül járunk-e el akkor, ha egy számla minden "módosítását" MODIFY invoiceOperation-ként jelentjük le az adatszolgáltatásban, akkor is ha az adott esetben a felhasználó szemszögéből sztornó számlát takar?

**Comment by NTCA-tax** [comment]
Az adott ügyletet kellene mindig magunk előtt látni. Amennyiben az ügylet meghiúsult, akkor nem módosítani kellene a számlát, hanem érvényteleníteni. Az ügylet nulla végösszegre való módosítása és a sztronózás között lehet fontos különbség is. Például egy ügyletből csinálhatunk ingyenes ügyletet, vagy termékmintára változtatjuk az összes tételsorát egy számlának, akkor ezek módosítást jelentenek. Amennyiben érvénytelenítünk, akkor azzal azt jelezzük, hogy az adott ügylet nem történt meg.
