### ISSUE TITLE
[Q&A] Tanúsítványcsere az Online Számla rendszerben

### ISSUE THREAD

**Issue by nbeeps2** [nav-gov-hu/Online-Invoice#945]
Tanúsítványcsere az Online Számla rendszerben
"2022. január 12-én 17 órakor megújul az Online Számla éles és tesztrendszerében használt gép-gép interfészkapcsolat titkosító SSL-tanúsítványa.  Az új tanúsítvány a Technikai információk/Dokumentációk menüpontban érhető el és tölthető le tömörített formában."

Kell valamit fejleszteni? A megújulból azt gondolom, hogy már eddig is volt, viszont én nem emlékszem, hogy bármikor is dolgom lett volna a .cer fájllal. Jan. 12 után minden fog működni, ami eddig működött vagy kell valamit fejleszteni a számlázó programokba?

**Comment by renced42** [comment]
Kedves @nbeeps2 

Nem kell fejleszteni, de számos megoldás érzékeny lehet az SSL tanúsítványok érvényességére.
Ilyen esetben az ügyfél oldali szerver vagy kliens megoldásnál a használatban lévő tanúsítvány tárban el kell helyezni az új tanúsítvány publikus kulcsát, hogy ne legyen SSL handshake probléma.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom ezt az issuet, mivel úgy látom nincs több kérdés/teendő.
Üdv
