### ISSUE TITLE
[Q&A] A bejövő számla lekérdezéskor nem kapok hozzátartozó cég címeket. 

### ISSUE THREAD

**Issue by cityba** [nav-gov-hu/Online-Invoice#947]
A pzs féle php-modult használom, és egyik számla lekérdezésnél se kapok cégcímeket.
`...KFT." ["supplierAddress"]=> object(SimpleXMLElement)#19 (0) { } } ["customerInfo"]=>... `
Mi ennek az oka? Hogy tudom meg a számlázó cég cím adatait?

**Comment by szecsenyizoltan** [comment]
Probléma nálam is fenn áll. A válaszból hiányzik:
- szállító adószáma
- szállító címe
- vevő adószáma
- vevő címe

**Comment by renced42** [comment]
@szecsenyizoltan , @cityba 
Segítségnyújtáshoz ennél kicsit többre lenne szükség....

**Comment by szecsenyizoltan** [comment]
Operáció: queryInvoiceData, INBOUND 
Mire gondolsz? Tranzakció ID? 
Éles rendszeren nem mennek ezek és tudom nem ez a  fóruma, de ezt nehéz tesztelni a teszt szerveren.

**Comment by szecsenyizoltan** [comment]
Élesen
transactionId: 3M0BN4FMZN0NQVWB
transactionId: 3KY16DRRYSCD9PQY
transactionId: 3LTGJRTHYDAAUY2S

**Comment by NTCA-supporter** [comment]
Sziasztok!

A queryInvoiceData válaszában a kicsomagolt invoiceData xml-ben nincsenek benne ezek az adatok?
Valóban itt nem supportáljuk az élest, de mivel ugyanaz az alkalmazásverzió van kint teszt és éles rendszeren is, ezért kellene tudni reprodukálni teszten is. Kérlek próbáljátok meg.

Köszönöm

**Comment by cityba** [comment]
@NTCA-supporter szia, éles rendszeren se ad vissza címeket,adószámot, 1et sem,semelyik számlához, tavaly április 1 óta.Volt valamilyen formai változás akkor? Milyen adatra lenne szükség még?

**Comment by NTCA-supporter** [comment]
@szecsenyizoltan vevőnek megadod a saját adószámodat. Ilyenkor a számlát le tudod kérdezni outbound és inbound irányból is.

**Comment by szecsenyizoltan** [comment]
Köszönöm.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Teszt rendszeren próbálgattam, szerintem az lesz a gond nálatok, hogy az említett adatok (vevő-eladó adószám/cím) más namespace-ben vannak a response-ban, mint a default namespace.
A 3.0 óta több xsd van használatban, pl. egy queryInvoiceData response ezeket tartalmazza:
`<InvoiceData xmlns="http://schemas.nav.gov.hu/OSA/3.0/data" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns3="http://invoice.dto.icon.icellmobilsoft.hu/invoice">`
Ez szerintem jó kiindulási alap lehet.
Üdv

**Comment by szecsenyizoltan** [comment]
Köszi. 

// Nálam ez volt a hiba, hogy csak 1x szedtem le a namespace-ket. Vagyis a számla base64_encode után már nem.

**Comment by cityba** [comment]
@NTCA-supporter  itt egy kérés: `Request body: <?xml version="1.0" encoding="UTF-8"?> <QueryInvoiceDataRequest xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns="http://schemas.nav.gov.hu/OSA/3.0/api"><common:header><common:requestId>RID048695300164198757837348</common:requestId><common:timestamp>2022-01-12T11:39:38.487Z</common:timestamp><common:requestVersion>3.0</common:requestVersion><common:headerVersion>1.0</common:headerVersion>`

Itt a válasz: `Response body: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns2:QueryInvoiceDataResponse xmlns="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/api" xmlns:ns3="http://schemas.nav.gov.hu/OSA/3.0/base" xmlns:ns4="http://schemas.nav.gov.hu/OSA/3.0/data">`

Akkor a kéréssel lesz a gond? vagy a response feldolgozással?

**Comment by NTCA-supporter** [comment]
A response feldolgozással szerintem.
Arra figyelj, hogy a namespace-ek sorrendje a válaszban nem garantált, erről már volt sok téma korábban.

**Comment by szecsenyizoltan** [comment]
@cityba response
Abban ugye két xml van egymásban. A külsőről leszedtem a namespacet, a belsőről csak base64_decode után tudom leszedni (Ezt a lépést hagytam ki.)

**Comment by cityba** [comment]
@NTCA-supporter @szecsenyizoltan  Szóval melyik fájlban, mit is kell módosítanom? :)

**Comment by szecsenyizoltan** [comment]
Ez zárjuk. pzs alá beírom.

**Comment by cityba** [comment]
Rendben, köszönöm
