### ISSUE TITLE
[Q&A] lineGrossAmountData kötelezősége

### ISSUE THREAD

**Issue by magardy** [nav-gov-hu/Online-Invoice#95]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

A tesztjeink során felmerült egy kérdésünk a queryInvoiceData NAV-os operációjával kapcsolatban, ami a következő:

Abban az esetben, ha egy olyan számlát riportálunk, aminek a sor szintű bruttó értéke nem kerül beküldésre, hiszen ez nem egy kötelező mező (lineGrossAmountData elem nélkül), és a számla bemegy Done státusszal, majd a queryInvoiceData NAV-os operációval megpróbáljuk elkérni a tranzakció azonosítóját, akkor a következő hibaüzenetet kapjuk:

                    <validationResultCode>ERROR</validationResultCode>
                    <validationErrorCode>SCHEMA_VIOLATION</validationErrorCode>
                    <message>Field [lineGrossAmountData] contains error: [The content of element 'lineGrossAmountData' is not complete. One of '{"http://schemas.nav.gov.hu/OSA/2.0/data":lineGrossAmountNormal}' is expected.]</message>

Amennyiben a sor szintű bruttó érték is (lineGrossAmountData elemmel) beküldésre kerül a számlában, és Done státuszt kap, akkor a queryInvoiceData NAV-os operációval sikeresen megkapjuk a tranzakció azonosítóját.

A fentiek kapcsán a következő kérdésünk merült fel:

Mivel a lineGrossAmountData elem a dokumentációban, illetve a sémában is nem kötelező elemként van feltüntetve, megerősítést szeretnénk kérni, hogy a fenti hibaüzenet vagy a dokumentációt és a sémaleírást vegyük alapul.

**Comment by NTCA-developer** [comment]
Szia!

Ezt már már is megtalálta, nálunk volt a hiba: https://github.com/nav-gov-hu/Online-Invoice/issues/90

Ezt kérlek hadd zárjam le, az eredetit nyitva hagyom addig amíg a javítás nem települt ki. Jó lesz így?

**Comment by magardy** [comment]
Szia,
Igen, jó lesz, köszi.
