### ISSUE TITLE
QueryInvoiceDigestRequest customerGroupMemberTaxNumber szürés

### ISSUE THREAD

**Issue by ocsike** [nav-gov-hu/Online-Invoice#950]
A QueryInvoiceDigestRequest operációban van-e lehetőség csoportos adószámmal rendelkező ügyfélnek  a saját adószáma alá tartozó számláinak lekérése.?  Konkrétan a pl a 1111111 csoportazonosítóval rendelkezik 3 cég ezen cégek saját adószáma pl  ezekkel:  3333333,4444444,66666666   szeretném lekérni pl csak a 3333333 adószámú cég bejövő számláit,  mert  a  többi nem érdekel..

**Comment by Macskafarka** [comment]
@ocsike  kérésének szerintem jogi akadálya van.  
A csoportos adólanyiságnak éppen az a lényege, hogy a csoport EGYETLEN entitásként viselkedik a számlázánál mind a NAV felé, mind a vevői és a szállítói felé. A csoport részére kiállított számlákon elég csak a csoportazonosítót szerepeltetni. Tehát a bejövő számlákon nem kötelező elem a saját adószám szerepeltetése.  Amúgy ha szerepelne, akkor sincs igazán értelme, mert a csoport számla tartozásaiért a csoport tagjai egyetemlegesen felelnek, A példában a 33333333 cég által vásárolt termékért az eladó simán követelheti akár a 44444444, akár a 66666666 adószámú cégektől,  akár egyoldalúan is, pl.kompenzálás, vagy akár beszámítás esetén is. Ez akár előlegszámla utáni végszámlára is igaz.  Ehhez még az sem kell, hogy bizonyítsa, hogy a 33333333 nem fizet.
Amikor döntés születik arról, hogy csoportos áfa alanyiságot választ egy cégcsoport, annak szerintem az a minimuma, hogy a kimenő és a bejövő számláikat közösen kezelik. Márcsak azért is, mert az ÁFA bevallásnál is egyetlen bevallást kell készítsen az áfacsoport.

**Comment by ocsike** [comment]
@Macskafarka  Nem tudom,hogy van-e jogi akadálya, viszont a könyvelőnek az a jó ha a 33333333-as cég bejövő telefonszámlája ne legyen ott a 44444444-es cég bejövő számlái közt. és viszont A QueryInvoiceDigestRequest-ben ugye szerepel minden számla...... végülis az xml végigolvasásával ki lehet szűrni,hogy melyik számla melyik csoporttagé.

**Comment by Macskafarka** [comment]
Akkor másképpen fogalmazok: 1. A szállító számlán csak a csoportazonosító szerepeltetése kötelező, tehát a saját adószán vagy rajta van, vagy nincs. 2. ha rajta van a saját adószám, akkor sem jelenti azt 100%-ban, hogy ez az adott csoporttagé. Ettől még lekérdezni le lehet, csak félrevezető.

**Comment by topybear** [comment]
Mi úgy csináljuk, hogy lekérdezzük a csoport számláit. Ahol meg van adva a csoporttag adószáma, ott el tudjuk automatikusan dönteni, hogy az adott cégnek szól-e a számla, ez alapján vagy feldolgozzuk, vagy logolva elvetjük. Ahol nincs megadva, ott meg a felhsználónak kell ledönteni, hogy az neki szól-e és befogadja vagy elveti.

**Comment by ocsike** [comment]
@topybear 
Így oldom meg én is ezt a problémát.

**Comment by NTCA-supporter** [comment]
Szia @ocsike !
A QueryInvoiceDigestRequest/invoiceQueryParams/additionalQueryParams/groupMemberTaxNumber mezőben megadhatod a csoporttag adószámát és akkor csak az említett számlák lesznek listázva.
Üdv

**Comment by ocsike** [comment]
@NTCA-supporter 
Próbáltam, de nem ad vissza semmit. Jelzem, csak éles rendszerben tudom ezt lekérdezni.

**Comment by NTCA-supporter** [comment]
@ocsike próbáld meg esetleg tesztrendszerben, hogy eladónak és vevőnek ugyanúgy a saját csoport és tag adószámot adod meg, és akkor mindkét irányból le tudod kérdezni, és akkor meg tudom nézni mi a gond.
Üdv

**Comment by NTCA-supporter** [comment]
@ocsike 
Kipróbáltam belső teszt környezeten és tudtam reprodukálni. Javítani fogjuk, majd jelzem ha tesztelhető.
Köszi a jelzést!

**Comment by NTCA-supporter** [comment]
@ocsike bocsánat, félreértettem a leírást. INBOUND esetben mindig az eladóra szűrünk az additionalQueryParams-ban megadott taxNumber vagy groupMemberTaxNumber esetén, OUTBOUND esetén pedig fordítva, hiszen az egyik fél az mindig a technikai felhasználóhoz tartozó adózó. Így válaszolva az eredeti kérdésre, nincs lehetőség a saját számlák között tovább szűrni a saját csoporttag adószámra.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet, nincs tervben ilyen jellegű átalakítás.
Üdv
