### ISSUE TITLE
A bejelentkezés nem folytatható, mivel egy adózónál sem rendelkezik élő képviseleti joggal.

### ISSUE THREAD

**Issue by Jaszuro** [nav-gov-hu/Online-Invoice#951]
Üdv!
Nagy nehezen azt az információt találtam, hogy a teszt szerverhez is valódi cégadatokkal kell bejelentkezni (mind a webes felületen, mind az API-val), ami nem is lenne gond, mivel van is ügyfélkapus regisztrációm, és cégem is, ami az éles rendszerbe bejelentkezve látszik is, viszont a teszt szerver szerint a sikeres KAÜ bejelentkezés után a bejelentkezés nem folytatható, mert nincs hozzám rendelve semmilyen képviseleti jog. Szeretném megkérdezni, hogy ilyenkor mit lehet tenni, ha nem az éles szerveren vágyom próbálgatni a programomat. Esetleg rosszul tudom, és van valami eldugott oldal, ahol külön regisztrálnom kellene? A webes felületen lévő form segítségével már próbáltam üzenetet küldeni, de arra válasz nem jött.
Köszönettel,
Szuromi János
Badbox Kft.

**Comment by NTCA-supporter** [comment]
Szia @Jaszuro !
Sajnos a teszt rendszeren nem naprakészek ezek a törzsadatok (adózói adatok, képviseleti jogok, címadatok, áfacsoportok stb.).
Rákérdezek, hogy mikor lesz frissítve legközelebb.

Üdv

**Comment by Jaszuro** [comment]
Szia @NTCA-supporter !
Köszönöm a közbenjárást, már be tudok jelentkezni, és minden szépen működik. Annyi nyűgöm lenne még, hogy a bejövő számlákat lekérdezve a teszt szerveren üres eredményeket kapok, míg az élesen szépen jönnek a valós adatok. Amennyiben csak a számlák lekérdezése funkciót használom, szabad az éles szervert használva fejleszteni?

**Comment by gcsehi** [comment]
Sziasztok!
Szintén ugyanez lenne a problémám!
A szamlazz.hu oldalon próbálom összekötni a vállalkozásom a NAV-val, viszont ahányszor próbálkozom az ügyfélazonosítással, ezt az üzenetet kapom:
"A bejelentkezés nem folytatható, mivel egy adózónál sem rendelkezik élő képviseleti joggal."
Mindeközben az egyéni vállalkozásom élő (az ügyfélkapu szerint is)
Próbáltam már okostelefonon, laptopon, inkognitó lapon, több böngészőben stb.
Mi lehet a gond? 
Kérem segítsenek a probléma megoldásában!

**Comment by vankcuf** [comment]
Jaszuro: a teszt rendszerben csak azokat a bejövő számlákat látod, amiket a cégednek a teszt(!) rendszerben állították ki! A teszt rendszerben semmilyen körülmények között nem láthatók éles adatok, mert ez két teljesen különálló adatbázis!

**Comment by szaszakk** [comment]
@gcsehi Szia! 
Nekem is felmerült ez a hiba, neked hogy sikerült megoldanod?

**Comment by gcsehi** [comment]
Szia!
Vártam 2 napot és egyszerűen jó lett. Nem csináltam semmit, nem nyúlt bele
senki.

szaszakk ***@***.***> ezt írta (időpont: 2022. máj. 24., K
20:46):

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom ezt az issuet ha nincs már senkinek gondja a bejelentkezéssel.
Ha még van, kérlek nyissatok újat.
Üdv

**Comment by Kebab11noel** [comment]
Helló!
Nekünk szintén ez a problémánk, januárban jegyzett Kft nem látszódik a teszt rendszerben.
