### ISSUE TITLE
[Q&A] Feldolgozási státusz

### ISSUE THREAD

**Issue by leczkat** [nav-gov-hu/Online-Invoice#952]
Kedves Fejlesztők!
A kollégáim új elküldési platformot tesztelnek, ezért a január 10-én elküldött számlákat, elküldték újra az új rendszerből az onlineszamlarendeszert teszt felületére is. 
Az éles rendszerből a számlák 99%-ra a DONE válasz jött vissza. A teszt rendszerből viszont 99%-ban a PROCESSED vagy SAVE válasz jött vissza, és a weboldalra való bejelnetkezés után a számlák státusza QUERIED. 
A kérdés az, van-e ennek jelentősége, kell e ezzel foglalkoznunk, miért kaptuk ezeket a válaszokat? Miért vannak ezek a számlák a lekérdezett státuszban? 
Segítségüket előre is köszönjük. 

Üdvözlettel: 

Leczó Katalin
Fleetcor Hungary Kft

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ezzel kapcsolatban van még kérdés? A feldolgozási státuszok szerepelnek az interfész dokumentációban részletesen.
Üdv

**Comment by leczkat** [comment]
Rendben
