### ISSUE TITLE
[Q&A] Számlák lekérdezése meghatalmazáson/jogosultságon keresztül más adóalanytól

### ISSUE THREAD

**Issue by zzvara** [nav-gov-hu/Online-Invoice#953]
A `QueryInvoiceDigestRequest` esetén ad támogatást arra a rendszer, hogy például egy könyvelő a saját technikai felhasználójával más adóalany inbound vagy outbound számláit lekérdezze úgy, meghatalmazáson (vagy egyéb jogosultság beállításán) keresztül, mintha a szóban forgó adóalany technikai felhasználója lenne?

Másképp fogalmazva, más adóalany (minden bejövő és kimenő) számláit teljeskörűen letöltheti egy adóalany a megfelelő jogosultsággal? Például az EGYKE adatlaphoz hasonló mechanizmussal? (_Egységes Képviseleti Adatlap - Bejelentés az állami adó- és vámhatósági ügyek képviselő útján történő intézéséhez_)

A választ nagyon szépen köszönöm!

**Comment by NTCA-supporter** [comment]
Szia @zzvara !
Erre nincs lehetőség, a technikai felhasználó minden esetben adózóhoz van rendelve, és csak annak az adózónak a számláit tudja lekérdezni. (Ez nem csak a digest lekérdezésre vonatkozik, hanem általánosan értendő.)
Üdv

**Comment by renced42** [comment]
@NTCA-supporter-t kiegészítve, az adózó a könyvelőjének tud hozzáférést adni új technikai felhasználó generálásával csak lekérdezői joggal. Ez most is sok helyen így működik, így a könyvelő program le tudja kérdezni a számlákat.

**Comment by zzvara** [comment]
@NTCA-supporter köszönöm a választ!

@renced42 valóban, másképpen foglalmazva arra voltam kíváncsi, hogy technikai felhasználó generálása és a kulcsok átadása nélkül is megoldható-e, hogy egy harmadik személy elérje a számlákat.

Köszönöm!

**Comment by zzvara** [comment]
@NTCA-supporter könyvelő kapcsolatunk megerősítette és demózta, hogy az EGYKE meghatalmazással a könyvelő belépve a `onlineszamla.nav.gov.hu` weboldalra saját felületén le tudja kérdezni az ügyfelei számláit, akikkel van EGYKE meghatalmazása. Szeretnék kérni egy megerősítést, hogy ez kizárólag a `onlineszamla.nav.gov.hu` weboldalon működik és a NAV API-val nem kivitelezhető.

Köszönöm szépen mégegyszer!

**Comment by renced42** [comment]
Kedves @zzvara Az API technikai userrel működik, nincs köze az EGYKE adatlapokhoz. Azt a belépett felhasználó adja ki. 
Az API-n természetesen ugyan úgy le lehet kérdezni a technikai felhasználóhoz rendelt adózó számláit.
