### ISSUE TITLE
How to handle the return of all items and return a specific item in NAV?

### ISSUE THREAD

**Issue by abin2hats** [nav-gov-hu/Online-Invoice#955]
Hi

What we can do with the following cases in NAV after Order is created and invoice details sent to the NAV system using /manageInvoice API?

1) Case  1(Return all items): All items returned by the customer 

a) How we can cancel the invoice in API call? which endpoint can be used?

2) Case 2(Return just specific items): customer return a specific item of the order

a) How we can inform this to the NAV system? which API endpoint can be used?

**Comment by NTCA-supporter** [comment]
Hi @abin2hats !
I recommend you to read the interfase scepification: https://onlineszamla.nav.gov.hu/api/files/container/download/Online%20Invoice%20System%203.0%20Interface%20Specification.pdf
Your questions are detailed in chapter 2.5 Data report on invoice-equivalent documents

You have to use the manageInvoice endpoint in both cases, but the invoiceOperation will be STORNO in the 1st case and MODIFY in the 2nd.
Br
