### ISSUE TITLE
What is the use of `STORNO` in manageInvoice endpoint in NAV?

### ISSUE THREAD

**Issue by abin2hats** [nav-gov-hu/Online-Invoice#956]
Hi

What is the use of `STORNO` in manageInvoice endpoint in NAV?

Can you give a sample XML request for STORNO invoice operation?

**Comment by NTCA-supporter** [comment]
Hi!
As I mentioned in another issue, the interface specification ansewrs it.
You can find examples here: https://onlineszamla.nav.gov.hu/dokumentaciok
Data Example XML: Data example XML (last updated on 21.12.2020)

Br

**Comment by abin2hats** [comment]
The invoice operation for STORNO is not available in the sample files.

Can you please give me a sample file for invoice operation storno?

**Comment by NTCA-supporter** [comment]
If you download the Data example XML zip file, you can find a html file and it conatins an example for cancellation (4.4.2 Example: Cancellation of transaction). The xml file is mentioned too: File name: Modositas es ervenytelenites 2.xml

**Comment by abin2hats** [comment]
It's a PDF file, not an HTML file (2020-12-07-Invoicesamples_v3.0_EN.pdf). 
Thank you.
