### ISSUE TITLE
Indokolatlan INCONSISTENT_MODIFICATION_DATA_VATAMOUNT_NOT_ZERO_HUF figyelmeztetés!

### ISSUE THREAD

**Issue by SiposElek** [nav-gov-hu/Online-Invoice#958]
Sziasztok!

Már néhány esetben jelezték nekünk az ügyfeleink, hogy sztornó számla lejelentésekor a címben említett INCONSISTENT_MODIFICATION_DATA_VATAMOUNT_NOT_ZERO_HUF figyelmeztetést kapják. Mindkét alkalommal ellenőriztem, hogy milyen adatszolgáltatást küldtünk fel a szerverre, és a szerverről még le is kérdeztem a számlákat, és az Online számla rendszer fejlesztői dokumentációjában a hivatkozott InvoiceData/invoiceMain/invoice/invoiceSummary/SummaryNormal/invoiceVatAmountHUF tagek összege 0 az alapszámlát és az egy darab módosító számlát tekintve. Szerintem valamilyen hiba lehet a szerveren, ezért kérem az eset kivizsgálását.

A legutóbbi sztornó számla azonosításához adatok:
tranzakciós azonosító: 3M09WT71WRL0Z7LI
requestId: R_11951209206_6965235507445
számlaszám: 2277/2021

A hozzá tartozó alapszámla adatai:
tranzakciós azonosító: 3LW4MXPIZPWFVFSU
requestId: R_11951209206_6965243498138
számlaszám: 2276/2021

Ha valamilyen adatra még szükség van, akkor kérem jelezzétek és elküldöm.

Köszönöm előre is!

**Comment by NTCA-supporter** [comment]
Szia @SiposElek !
Itt nem supportáljuk az éles rendszert, ahhoz használd kérlek ezt: https://nav.gov.hu/ugyfeliranytu/keressen_minket/levelkuldes/e-ugyfsz 
A tesztrendszerre ha beküldöd hasonló adatokkal, akkor meg tudom nézni.
Üdv

**Comment by SiposElek** [comment]
Köszönöm @NTCA-supporter !

Megpróbáljuk előidézni teszt szerveren is.

**Comment by SiposElek** [comment]
Kivizsgáltuk jobban a problémát, és nálunk a hiba.
