### ISSUE TITLE
FAD os számlák pontos tagelése

### ISSUE THREAD

**Issue by programozas** [nav-gov-hu/Online-Invoice#959]
Csak egyeztetni szeretném hogy FAD os számla esetében a  számla tételénél így kell tagelni ?

				<lineVatRate>
					        <vatExemption>
								<case>FAD</case>
								<reason>Mentes ÁFA tv. 142.§</reason>
                                                                <vatDomesticReverseCharge>True</vatDomesticReverseCharge>
							</vatExemption>
				</lineVatRate>

**Comment by NTCA-supporter** [comment]
Szia!
Javaslom az interfész specifikáció (https://onlineszamla.nav.gov.hu/api/files/container/download/Online_Szamla_interfesz%20specifikacio_HU_v3.0.pdf) 2.2.3.2.1 vatRate fejezetét.
Ennyi elengendő:
`<lineVatRate>
    <vatDomesticReverseCharge>true</vatDomesticReverseCharge>
</lineVatRate>`
Üdv

**Comment by NTCA-supporter** [comment]
Zárom az issuet, ha van még kérdés nyisd újra kérlek.
Üdv
