### ISSUE TITLE
[FEATURE] QueryInvoiceCheckRequest élesben

### ISSUE THREAD

**Issue by era910413** [nav-gov-hu/Online-Invoice#96]
A QueryInvoiceCheckRequest az éles és a teszt rendszerben nem ugyanúgy működik.
A cégünkhöz beérkező számlákat úgy kérdezzük le, hogy a batchindex tag-et kihagyjuk - nem is kötelező elem - viszont a kiállító adószámát belerakjuk a kérésbe:
<invoiceNumberQuery>
 <invoiceNumber>valami</invoiceNumber>
 <invoiceDirection>INBOUND</invoiceDirection>
 <supplierTaxNumber>12345678</supplierTaxNumber>
</invoiceNumberQuery>

(nyilván direkt nem létező adószámot írtam a példába)

A fenti kérésre kapott respond a teszt rendszerben megfelelő, tehát visszaadja az invoiceCheckResult elemet, az éles rendszerben viszont invalid_request errorcode-al elutasításra kerül, az alábbi hibaüzenet kíséretében:
<message>Field [{"http://schemas.nav.gov.hu/OSA/2.0/api":supplierTaxNumber}] contains error: [Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/2.0/api":supplierTaxNumber}'. One of '{"http://schemas.nav.gov.hu/OSA/2.0/api":batchIndex}' is expected.]</message> 

Tehát hiányolja a batchIndex elemet, ami nem is kötelező.
Mi nem csinálunk jól valamit, vagy valóban nem egyezik a két rendszer ilyen téren?

**Comment by NTCA-developer** [comment]
Szia!

Kellene a kérésben lévő requestId, ezt meg tudod adni?

**Comment by era910413** [comment]
Szia!
Most pl. ezzel próbáltam:
<requestId>GAE90A201912124443905</requestId>

Köszi!

**Comment by NTCA-developer** [comment]
Szia!

A kérésed jó. Ami miatt a problémát tapasztalod az, hogy a teszt környezetben a 2.4.0 alkalmazásverzió van kint, de az élesen még csak a 2.2.0.  Ez az infó egyébként nektek is hozzáférhető a Technikai információk/Informatikai változások menüpont alatt. (Ezzel persze nem azt mondom hogy elvárt hogy folyton nézzétek, csak a jövőre nézve említem meg.)

A 2.2.0-ban még nem volt a séma része a supplierTaxNumber, ami a te kérésedben is kitöltött. Az éles tehát nem azt mondja, hogy kell neki a batchInvoice, hanem azt, hogy a sequence által leírt sorozatban van a számára egy ismeretlen elem, ahol maximum a batchIndex állhatna, ezért mondja a hibaüzenet, hogy 
`One of '{"http://schemas.nav.gov.hu/OSA/2.0/api":batchIndex}' is expected.`

Hamarosan utoléri magát a két környezet, de ez nem tőlünk függ. Lezárod majd?

**Comment by era910413** [comment]
Így már minden világos, köszönöm!
