### ISSUE TITLE
[Q&A] ÁFA tv 102. par esetén melyik adókód használatos?

### ISSUE THREAD

**Issue by janisoft** [nav-gov-hu/Online-Invoice#960]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

A NAV-os tájékoztató szerint az EAM adókód a 98-109. § szerinti esetekben alkalmazható. A szövegezés szerint termékexport illetve egyedi spaciális esetek tartoznak ide. Az EAM adókódot magyar adóalanynak nem engedi kiállítani a rendszer, INCORRECT_LINE_DATA_VAT_DATA_MISMATCH_EAM hibaüzenet generálódik, pedig az ÁFA törvény 102. par alapján magyar adóalanynak számlázható pl. a termékexporthoz kapcsolódó fuvarozás.

Kérdésem, hogy mi a helyes adókód választás az ÁFA tv. 102. par alapján érvényes adómentesség esetében?

Javaslom továbbá a dokumentációt ezzel az esettel kiegészíteni.

Köszönettel:
János

**Comment by janisoft** [comment]
@NTCA-tax számithatok válaszra?
Köszönettel:
János

**Comment by NTCA-tax** [comment]
A felvetés teljesen valid, mivel léteznek olyan ügyletek, amely bár EAM kód alá kellene tartozniuk de belföldi adóalany a vevő.  Még hasonló problémát látunk az EUFADE esetében is. Ugyanakkor ezek warningot jelentenek, tehát az adatszolgáltatást lehet teljesíteni, azonban hibásan jelez egyes esetekben ez a warning. Megfelelő helyre felraktam az asztalra hibás warningként, így mindenképpen foglalkozunk vele.
