### ISSUE TITLE
[Q&A] ÁFA tv 93. § (2) esetében a termékimporthoz nyújtott szolgáltatáskor milyen adókódot kell használni?

### ISSUE THREAD

**Issue by janisoft** [nav-gov-hu/Online-Invoice#961]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

Érdeklődök, hogy az ÁFA tv  93. § (2) termékimporthoz nyújtott szolgáltatás belföldi adóalany részére tranzakció esetén milyen adókódot kell használni?

Köszönettel:
János

**Comment by janisoft** [comment]
@NTCA-tax számithatok válaszra?
Köszönettel:
János

**Comment by NTCA-tax** [comment]
Jelenleg nincs ennek megfelelő adókód. Az EAM lehet jelenleg a legközelebbi, de mindenesetre köszönjük a felvetést, felvettük a javításra váró problémák közé :)

Az EAM-nél warningot fog kapni az adatszolgáltatást, ahogy egy másik issue-ban kifejtettem... de ettől az adatszolgáltatás megfelelő lesz.
