### ISSUE TITLE
[Q&A] Bankszámlaadatok tömbösített lekérdezése

### ISSUE THREAD

**Issue by OliverGergelySzabo1995** [nav-gov-hu/Online-Invoice#962]
Az lenne a kérdésem, hogy van-e mód az egyes kiállított számlákhoz tartozó bankszámlaadatok ("supplierBankAccountNumber" és "customerBankAccountNumber") lekérdezésére valamelyik endpoint-on keresztül? Mivel ezek a mezők a "QueryInvoiceDigestResponse"-on belül nem érhetők el. 

Köszönettel, Olivér

**Comment by surisomi** [comment]
Ez engem is érdekelne, mert az egyik ügyfelünknek ez lenne a kérése.

Köszönettel, Soma

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
