### ISSUE TITLE
[Q&A] Bejövő számlák online lekérdezésénél lassulás tapasztalható az ÉLES rendszerben

### ISSUE THREAD

**Issue by vankcuf** [nav-gov-hu/Online-Invoice#963]
Tudom, hogy nem a teszt rendszerre vonatkozik (ott nincs bejövő számlám, így nem tudom kipróbálni), de a lényeg, hogy a bejövő számlák online lekérdezése ismét nagyon lassú, ha teljesítés dátumra kérjük le. Ha csak kelt alapján kérem le, akkor azonnal jön válasz, ha pedig teljesítés dátumra, akkor meg 60 másodperc is kevés a lekérdezéshez, akár 1 számla esetén is. Tavaly is volt már ilyen gond, akkor sikerült elhárítani, biztos valami adatbázis indexelési probléma. Kérem, hogy nézzenek utána, mert most ez sok ügyfelünknél probléma.
Köszönöm.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet, nem látunk mostanában ilyen lassulást.
Ha van még hiba, kérlek nyissátok újra.
Üdv
