### ISSUE TITLE
[Q&A]

### ISSUE THREAD

**Issue by gcsehi** [nav-gov-hu/Online-Invoice#964]
Sziasztok! 
A NAV-val való összekötést próbálnám megcsinálni a szamlazz.hu. oldalon, de akárhányszor bejelentkezek ez az üzenet fogad:
"A bejelentkezés nem folytatható, mivel egy adózónál sem rendelkezik élő képviseleti joggal." 
Mindeközben az egyéni vállalkozásom élő (az ügyfélkapu szerint is). 
Mi lehet a probléma? 
Köszönöm előre is a válaszokat!

**Comment by NTCA-supporter** [comment]
Szia @gcsehi !
Az éles rendszert itt sajnos nem tudjuk támogatni, erre használd ezt kérlek:
https://nav.gov.hu/ugyfeliranytu/keressen_minket/levelkuldes/e-ugyfsz

Üdv
