### ISSUE TITLE
[Q&A] 2022. február 5. szombat reggel óta minden gépi, feltöltött számla PROCESSING állapotban van a FLEXYS és a saját rendszeremben is.

### ISSUE THREAD

**Issue by tsteve111** [nav-gov-hu/Online-Invoice#965]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.

2022. február 5. szombat reggel óta minden gépi, feltöltött számla 
[invoiceStatus] => PROCESSING állapotban
van a FLEXYS és a saját rendszeremben is. 
Egyszerre 2 rendszer nem hibásodhatott meg...

Mit lehet tudni erről a hibáról?

Perpill szombat délután fél 3 van, a NAV oldalak semmilyen hibát ill. karbantartást nem jeleznek, sőt a vanenav.hu oldal szerint is minden OK.
Tegnap még mindkét említett  (általam felügyelt) rendszer rendben üzemelt.

Köszönöm a választ!

Török István

**Comment by tsteve111** [comment]
Este 6 körül javult meg a rendszer, természetesen a NAV oldalon semmilyen jelzés nem volt a hibáról :(
Elég kellemetlen hogy szombat lévén süket és vak a rendszer....

**Comment by NTCA-supporter** [comment]
Szia @tsteve111 !
Egy aszionkron feldolgozó rendszernél az, hogy nem lesz végállapotban egy számla, nem hiba.
Zárom az issuet, a jelzést köszönjük.
Üdv
