### ISSUE TITLE
[Q&A] modify XML különböző számlázó rendszerekből

### ISSUE THREAD

**Issue by GBY2022** [nav-gov-hu/Online-Invoice#967]
Számlázó programot váltunk. Sajnos korábbi számlákat kell helyesbíteni, de már csak az új programból tudjuk megtenni. Viszont a nav online felületen minden helyesbítő számla hibára megy, mivel nem tudja folytatni a Linenumberreference-t. Milyen adatokkal lehet ilyen esetben az xml-t beküldeni? 
köszönöm!

**Comment by makailaci** [comment]
Szia, ilyenbe én is belefutottam (mint kiderült, a cég számlázója nem tud jóváíró számlát kibocsájtani), úgy oldottam meg, hogy le vannak töltve a kimenő számlák és onnan szedem a sorok számát. üdv, laci

**Comment by NTCA-supporter** [comment]
Sziasztok!
Itt van még kérdés? A számlaláncban szereplő sorok számára a queryInvoiceChainDigest operáció használható egyébként.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet. Ha van még kérdés nyissatok újat kérlek.
Üdv
