### ISSUE TITLE
[Q&A] Érvénytelenítő számla adatszolgáltatása tétel(ek) nélkül

### ISSUE THREAD

**Issue by DrotosTot** [nav-gov-hu/Online-Invoice#969]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Sziasztok!
Akaratunk ellenére sikerült egy olyan stornó adatszolgáltatást beküldeni, amiről hiányoztak a tételek (invoiceLines). Meglepetésünkre "csak" WARN-ok jöttek rá, szerintünk ez az adatszolgáltatás ABORTED-et érne.
Létezhet ez?
TRID: 3ODZKZMV4MATBCD8

**Comment by NTCA-supporter** [comment]
Szia @DrotosTot!
A teszt környezeten lévő interfész doksiban már láthatod az eredményét, az INVOICE_LINE_MISSING blokkoló hiba futni fog STRONO-ra is. Hamarosan tesztelhető lesz.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
Ez megvalósításra került, így zárom az issuet.
Üdv
