### ISSUE TITLE
Módosító számla beküldése utána státusz hiba

### ISSUE THREAD

**Issue by balintdozsa** [nav-gov-hu/Online-Invoice#97]
Módosító számla beküldése után a queryTransactionStatus hibát jelez:
XML:
`
...
<invoiceReference>
        <originalInvoiceNumber>HU00100000000</originalInvoiceNumber>
        <modifyWithoutMaster>false</modifyWithoutMaster>
        <modificationIndex>1</modificationIndex>
</invoiceReference>
...
`
queryTransactionStatus:
`
...
validationErrorCode>SCHEMA_VIOLATION</validationErrorCode><message>Field [{"http://schemas.nav.gov.hu/OSA/2.0/data":modificationIndex}] contains error: [Invalid content was found starting with element '{"http://schemas.nav.gov.hu/OSA/2.0/data":modificationIndex}'. One of '{"http://schemas.nav.gov.hu/OSA/2.0/data":modifyWithoutMaster}' is expected.]
...
`

Javasoljuk a séma javítását.

Hiába van benne a módosító xml-ben a fenti invoiceReference, minden esetben hibát kapunk.

**Comment by NTCA-supporter** [comment]
Szia @balintdozsa !
Tudsz küldeni egy transactionID-t? Ránézünk, ha elküdlted.
Köszi!

**Comment by balintdozsa** [comment]
Szia! Tovább nyomozva kiderült, hogy mégis mi küldjük rossz sorrendben az xml-ben az információt. Köszi azért.
