### ISSUE TITLE
[DOC] VTSZ törzs hivatkozás hibás

### ISSUE THREAD

**Issue by janisoft** [nav-gov-hu/Online-Invoice#971]
**A hibás dokumentum neve / Document name containing the error**
Fájlnév vagy hostolt URL / File name or hosted URL.

Specifikáció 4.4 pont VTSZ hivatkozás

**Oldalszám / Page number**
A hibát tartalmazó oldal száma / Page number containing the error.

184. oldal

**A dokumentációs hiba leírása / Description of the documentation error**
Rövid és tömör összefoglalása a hibának. / A clear and concise description of the summary of the error.

http://nav.gov.hu/data/cms285468/4002_2013.1.sz.mell..pdf 
hivatkozás hibás

**Comment by NTCA-supporter** [comment]
Köszönjük a jelzést, a következő verzióban javítani fogjuk.

**Comment by NTCA-supporter** [comment]
Szia!
A teszt oldalon lévő dokumentációban már javítva lett: https://onlineszamla-test.nav.gov.hu/dokumentaciok
Hamarosan élesen is ez a verzió lesz kint. Köszi a jelzés mégegyszer.
Zárom az issuet, ha van még kérdés nyisd újra kérlek.
Üdv
