### ISSUE TITLE
[Q&A] Adószám lekérdezésekor a válaszul kapott adószám nem helyes

### ISSUE THREAD

**Issue by Charcsi** [nav-gov-hu/Online-Invoice#972]
Tisztelt Ügyfélszolgálat,

Nem tudom kihez is forduljak a problémámmal ezért írok ide.
A Számlázó programunk az adószám alapján ellenőrizi a vevő adatait. Ezt az adatot a NAV Online /queryTaxpayer operációjával kérdezzük le a NAV onliner-ból.

Ez tökéletesen működik, de van egy törzsszám a 27504875, melyre ha lekérdezzük a partner adatokat, akkor az adószámhoz a  27504875-2-13 adószámot adja vissza, és nem a helyes 27504875-4-13 adószámot. 

A vevő áfa csoport tag kér, hogy legyen feltüntetve a csoportos adószáma is a számlán. 
Ha megadjuk a csoportos adószámot, akkor a rendszerünk vizsgálja azt hogy a vevő adószámához a helyes -4- adócsoportos adószám legyen megadva, és ha nem akkor nem enged számlázni. Illetve nálunk kötelező csoportos adószám esetében mind a két adószámot megadni. 
Azért nem tud a számla elkészülni, mert a /queryTaxpayer operáció hibásan adja vissza az adószámot. Nem a -4- es adókód hanem a -2- es adókód kerül a válaszba.

A nav.gov.hu adatbázisá menüpontban ellenőriztem az adatokat, és azt láttam hogy a csoport összes tagjának az adószáma át van állítva -4- áfakódra, illetve van olyan adószám ami a helyes 27504875-4-13, de a csoportképviselő adószáma még most is a -2- adókódra van állítva.

Nyilván a rendszerünk szabályrendszerén változtathatnánk, és engedhetnénk azt hogy a -2- adó kódot is engedje a rendszer használni, csoportos adószám esetében, de a számla felküldésekor struktúra hibát kapnánk erre. 

Kinek kell jeleznem ezt aznomáliát? 

Köszönöm segítségüket, és várom válaszukat.

üdv Jene Károly

**Comment by EPluribusUnum** [comment]
@Charcsi , a számla kiállítását nem lehet blokkolni azért mert a NAV szervere nem elérhető, vagy esetlegesen hibás adatot ad vissza. Nyomtatni kell és be kell küldeni, mégha tudni is lehet előre hogy hibás jelölést fog kapni.
Egy figyelmeztetést meg lehet tenni a felhasználó felé, de blokkolni nem lehet, ha formailag megfelelő számla nyomtatható.

**Comment by Charcsi** [comment]
@EPluribusUnum, ezzel mind egyet is értek a Felhasználó a lehető legkevesebbet érezzen abból hogy számla kiállítási nehézségek vannak a háttérben.

Mi mint szoftver készítő nem blokkoljuk, és nem akadályozuk a számla kiállítást, egy bizonyos pontig. 
De az adószám az olyan adat ami fontos az adatszolgáltatásban.
A Felhasználó, és a Hivatal elvárása az hogy ne legyen hibás számla! 
Miért ne ellenőrizném az adószámot, ha a technikai feltételem meg van hozzá, van net, elérhető a rendszer, a csillagok is együtt állnak. A felhasználó ne adhasson meg hibás adószámot, vagy ne adhasson meg olyan adószámot ami nem élő!
Ha figyelmeztetjük hogy valami nem ok, 2 x kérünk tőle engedélyt hogy a bevitt adat lehet hogy nem megfelelő biztosan akarod a számlát? Ennek ellenére ok-ét nyom kinyomtatja a számlát, és elküldi a rendszer az adatszolgáltatás majd visszapattan a számla, akkor a Felhasználó szemszögéből a rendszer  a sz@r. (Mert a Felhasználók  használni akarják a rendszert nem érteni. :( )
A rendszer legyen okos, és csak helyes számlát lehessen kiállítani!
(Ez jogos kérdés nem?)
Amennyiben az adószám operáció 0,5 - 1 % közötti hibával dolgozik csak, és a hiba csak adathiba, emiatt vegyük ki az ellenőrzést?
 
Csak egy forum kell ahol jelezzük ezen hibás adatokat. A NAV rendszerében a megfelelő kolléga ellenőrzi javítja az adatbázist, és másnap a felhasználó vígan tud számlázni. 
Nem ez lenne a megoldás?

**Comment by Amn3s1a2018** [comment]
A számlán nem kötelező feltüntetni a teljes adószámot, elég a törzsszám (a legtöbb esetben így van, fordított áfás számla a kivétel, de hirtelen nem találom hol olvastam ezt. @NTCA-tax talán megcáfolja ha hülyesget írtam). Sok problémát megold ha ezt ki is használjuk. Ilyenkor ugyebár az xml-ből is ki lehet hagyni. Pl. a költözés miatti adószám (régiókód) változás problémáját ezzel szépen ki lehet kerülni.
Az áfacsoport ki-be lépés más tészta, mert itt nem csak az adószám egy karakteres része változik, a csoportazonosító is képbe kerül. Én is tapasztaltam már, hogy a queryTaxpayer adata nincs mindig szinkronban a valósággal (néha a nav más adatforrásával), viszont a számla kiállítására szabott (8 nap?) határidőn belül ezek bőven meg szoktak oldódni. Személy szerint azt gondolom, hogy jó gyakorlat ilyenkor a felhasználóra bízni, hogy kiállítja-e a számlát (figyelmeztetés, nem blokkolás ahogy már többen írták). Az adószám hibák is csak WARN üzenetet adnak, az adatszolgáltatást ilyen esetben teljesítettnek vehetjük.

**Comment by Charcsi** [comment]
Szia @Amn3s1a2018 

És azt tudod hogy hol kell ezt intézni. (Mivel írtad hogy egy 8 napon belül megoldódik.) 
Mi a módja annak hogy az adószám helyes legyen a NAV rendszerében?

**Comment by Macskafarka** [comment]
A számlát arra a vevői adószámra kell kiállítani, amit a vevő kér. Lehet ellenőrizni, hogy van-e ilyen adószám, és az érvényes-e, de jogilag a helyesség teljesen irreleváns. A számlát ki kell állítani a vevő  által megadott adatokkal, és kész.  A számla befogadó csak akkor tudja levonni a számlán áthárított adót, ha az ő érvényes és helyes adószáma szerepel rajta., de ez már az ő felelőssége.
