### ISSUE TITLE
cvc-pattern-valid: Value is not facet-valid with respect to pattern

### ISSUE THREAD

**Issue by abin2hats** [nav-gov-hu/Online-Invoice#973]
Hi 

I am testing an invoice in https://onlineszamla-test.nav.gov.hu/

I am getting the following error

```
- XML contains on line: [152] and column: [29] error: [cvc-pattern-valid: Value '' is not facet-valid with respect to pattern '.{1,512}' for type 'SimpleText512NotBlankType'.]
--
- XML contains on line: [152] and column: [29] error: [cvc-type.3.1.3: The value '' of element 'lineDescription' is not valid.]
- Xml validation failed
```

Transaction id is 3P57P1P3X01QU49X

Can you please tell me what was the issue?

**Comment by NTCA-supporter** [comment]
Hi!

I think the error response is pretty straightforward, the lineDescription cannot be empty, use a valid string value.

Br

**Comment by abin2hats** [comment]
Ok thank you
