### ISSUE TITLE
What we can add in the vatPercentage for tax-free products?

### ISSUE THREAD

**Issue by abin2hats** [nav-gov-hu/Online-Invoice#975]
Hi

I am getting the following error while creating an invoice

Blocker fault
- The provided VAT percentage or VAT rate is not allowed.
–  Tag: InvoiceData/invoiceMain/invoice/invoiceLines/line/lineAmountsNormal/lineVatRate/vatPercentage
–  Value: 0
–  Invoice line: 1
- The provided VAT percentage or VAT rate is not allowed.
–  Tag: InvoiceData/invoiceMain/invoice/invoiceLines/line/lineAmountsNormal/lineVatRate/vatPercentage
–  Value: 0
–  Invoice line: 2
- The provided VAT percentage or VAT rate is not allowed.
–  Tag: InvoiceData/invoiceMain/invoice/invoiceSummary/summaryNormal/summaryByVatRate/vatRate/vatPercentage
–  Value: 0

My Product is a tax free product

What we can add in InvoiceData/invoiceMain/invoice/invoiceLines/line/lineAmountsNormal/lineVatRate/vatPercentage, if the product is tax free product?

**Comment by NTCA-supporter** [comment]
Hi!

I recommend you to check the interface spec: https://onlineszamla.nav.gov.hu/api/files/container/download/Online%20Invoice%20System%203.0%20Interface%20Specification.pdf

2.2.3.2.1 vatRate chapter contains the possible values.

Br
