### ISSUE TITLE
[DEV support] queryInvoiceData - Szolgáltató és vevő adószám/cím üresek?

### ISSUE THREAD

**Issue by csandazoltan** [nav-gov-hu/Online-Invoice#976]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[x] /queryInvoiceData
[x] /queryInvoiceDigest
[x] /query_tax_payer

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
Adatok nem valódiak, Vodafone adószámát használtam akkor példa cégnek...
Digest: DERP16487179338529393735894686
Invoice: DERP16487179339831578622662264
```

Kérdésem az lenne, hogy a queryInvoiceData-ban szándékosan üresek a:

- supplierTaxNumber
- supplierAddress
- customerTaxNumber
- customerAddress

mezők?
![image](https://user-images.githubusercontent.com/6756505/161025718-156d9b60-59c9-4c12-b1b1-e5b17c39af7c.png)

A queryInvoiceDigest-ben még megvan az adőszám
![image](https://user-images.githubusercontent.com/6756505/161025788-fd057de6-2870-44f8-89a0-36ce1f64ffb6.png)

A query_tax_payer-ben is vannak "címek" és adószám
![image](https://user-images.githubusercontent.com/6756505/161026360-c042a670-a9cf-4cf4-b9de-119fbe9a2187.png)

**Comment by NTCA-supporter** [comment]
Szia @csandazoltan !

Ott van az:
`	<invoice>
			<invoiceHead>
				<supplierInfo>
					<supplierTaxNumber>
						<ns2:taxpayerId>***</ns2:taxpayerId>
						<ns2:vatCode>2</ns2:vatCode>
						<ns2:countyCode>06</ns2:countyCode>
					</supplierTaxNumber>
					<supplierName>Digicube Kft.</supplierName>
					<supplierAddress>
						<ns2:simpleAddress>
							<ns2:countryCode>HU</ns2:countryCode>
							<ns2:postalCode>6729</ns2:postalCode>
							<ns2:city>Szeged</ns2:city>
							<ns2:additionalAddressDetail>***</ns2:additionalAddressDetail>
						</ns2:simpleAddress>
					</supplierAddress>
					<supplierBankAccountNumber>***</supplierBankAccountNumber>
				</supplierInfo>
				<customerInfo>
					<customerVatStatus>DOMESTIC</customerVatStatus>
					<customerVatData>
						<customerTaxNumber>
							<ns2:taxpayerId>***</ns2:taxpayerId>
							<ns2:vatCode>2</ns2:vatCode>
							<ns2:countyCode>44</ns2:countyCode>
						</customerTaxNumber>
					</customerVatData>
					<customerName>Csanda Kft</customerName>
					<customerAddress>
						<ns2:simpleAddress>
							<ns2:countryCode>HU</ns2:countryCode>
							<ns2:postalCode>6721</ns2:postalCode>
							<ns2:city>valami</ns2:city>
							<ns2:additionalAddressDetail>***</ns2:additionalAddressDetail>
						</ns2:simpleAddress>
					</customerAddress>
				</customerInfo>`

A response-ban több séma is szerepel:
<InvoiceData xmlns="http://schemas.nav.gov.hu/OSA/3.0/data" xmlns:ns2="http://schemas.nav.gov.hu/OSA/3.0/base">

Ez már volt sokszor téma, kérlek nézz utána.
Üdv

**Comment by csandazoltan** [comment]
Igen ez az én saram, nem midnenütt műtöttem ki az nsX: tagokat

Oh már emlékszem... Már az elején megjelentek a kérdőjelek a fejem felett... namespace lett használva amikor nem is kellett volna... lehet schema típus definíciót külön fájlban tárolni szabadon és más más xsd-kbe be lehet include-olni, nem kell namesapce...

Namespace akkor kellene ha lenne két ugyanolyan mező aminek customerAddress a neve és ns1 vagy ns2 más más definíció lenne.
De itt "egyenlőre" csak a külön tárolás miatt van használva

Köszönöm az infót és zárom az issue-t
