### ISSUE TITLE
[DEV support]

### ISSUE THREAD

**Issue by shadowd-dev** [nav-gov-hu/Online-Invoice#985]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[] /manageInvoice
[x] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
RID067114600165406988799857
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Kérés elküldése után a válasz nem tartalmazza a számlaláncot nem kapok se WARN-t se ERROR-t
<ns2:invoiceChainDigestResult>
<ns2:currentPage>1</ns2:currentPage>
<ns2:availablePage>0</ns2:availablePage>
</ns2:invoiceChainDigestResult>
</ns2:QueryInvoiceChainDigestResponse>

*Egyéb tartalom / Additional content*

**Comment by NTCA-supporter** [comment]
Szia @shadowd-dev !
Azért nem kapod vissza, mert megadtad a QueryInvoiceChainDigestRequest/invoiceChainQuery/taxNumber taget is, ami OUTBOUND esetben a vevő adószámára szűr. Mivel ezeknél a számláknál nem volt megadva vevői adószám így nincs találat.
Ha kiszeded a requestből ezt, akkor jó lesz.

Üdv

**Comment by shadowd-dev** [comment]
Szia @NTCA-supporter!
Köszönöm, így már működik.
Üdv,
László
