### ISSUE TITLE
[Q&A] QueryTaxpayerRequest - Eltérés a teszt és éles környezet között

### ISSUE THREAD

**Issue by BenjaminHorn** [nav-gov-hu/Online-Invoice#986]
Úgy vettem észre, hogy teszt és éles környezet között előfordulnak eltérések a QueryTaxpayerRequest eredményében.

Pl.:
https://api-test.onlineszamla.nav.gov.hu/
![image](https://user-images.githubusercontent.com/5570232/171826952-e8445720-a87e-49cf-b74c-5219b35e5ec1.png)

https://api.onlineszamla.nav.gov.hu/
![image](https://user-images.githubusercontent.com/5570232/171827039-83194b15-030b-4e75-8d71-44b5fc40b15b.png)

Az éles a helyes, mintha a teszt le lenne marad, mert más - frissen bejegyzett - cég az élesen már lekérdezhető, teszten még nem ad vissza eredményt. Lehetséges lenne, hogy a két környezet ugyan azt az (legfrissebb) adatot adja vissza?

Ha nem, akkor szeretném kérni, hogy a szinkronizáció minél gyakrabban történjen meg. A fent említett példában a címváltoztatás több hónapja megtörtént.

Köszönöm

**Comment by NTCA-supporter** [comment]
Kedves @BenjaminHorn!

A teszt rendszerben nem történnek rendszeres frissítések, mert a teszt rendszernek a fő célja meglévő és új funkciók, folyamatok kipróbálása az éles használat előtt. Egyelőre nincs is tervben az adatok rednszeres frissítése.

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet. Ha van még kérdés, kérlek nyissatok újat.
Üdv
