### ISSUE TITLE
[Q&A]

### ISSUE THREAD

**Issue by attilaszoke** [nav-gov-hu/Online-Invoice#99]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
A 2.0 specifikációban szereplő SHA3-512 titkosítási algoritmus a külföldi fejlesztők információja alapján a Microsoft még nem implementálta 
a rendszereiben. Mivel a fejleszett ERP szoftver teljes egészében Microsoft platformon nyugszik, külső szolgáltató termékét kell bevonni. Mely partnert javasolt bevonni amely megbízható és hosszú távon fogja támogatni a titkosítást?

**Comment by NTCA-developer** [comment]
Szia @attilaszoke 

Ha modularizálni kell a hashelést akkor felteszem mindegy hogy a megvalósítás milyen platformon működik. Amennyiben ez a feltételezés helyes akkor a Bouncycastle nevű crypto libet javasolom személy szerint. Van C# és java megoldásuk is. Régóta működik, aktívan fejlesztik és konkrétan tudom hogy az ő SHA3 hash algoritmusuk helyes eredményt ad vissza.

Ha nem akarsz binárist akkor publikus a forráskóduk Githubon, le is lehet húzni.

https://www.bouncycastle.org/latest_releases.html

Ez segít?

**Comment by attilaszoke** [comment]
Köszi. Továbbítom a fejlesztőknek a választ. Aztán meglátjuk :-)

**Comment by NTCA-developer** [comment]
Oké. Most lezárom, ha kell a jövőben akkor nyisd újra nyugodtan.
