### ISSUE TITLE
[Q&A] queryInvoiceChainDigest TESZT környezetben

### ISSUE THREAD

**Issue by UnClaimAll** [nav-gov-hu/Online-Invoice#990]
TESZT környezetben a 3SZO41L4C6MPLKNY tranzakcióra a queryInvoiceChainDigest nem ad vissza invoiceChainElement-et. Az availablePage pedig 0. Ez a számla a 3SZPA7RBCUVY4SNL tranzakcióval stornózva lett. Az online számla manuális (teszt) felületén látom is hogy így van, legalábbis módosítás-érvénytelenítés, és látszik az eredeti számla is. Nem tudom hova tenni, ez bug, vagy én csinálok valamit rosszul?

**Comment by NTCA-supporter** [comment]
Szia @UnClaimAll !
Lásd #985 issue.
Üdv
