### ISSUE TITLE
UNINTENDED_MODIFICATION_DELIVERY_DATE figyelmeztetés azonos napon készült alapbizonylat és módosítása esetén [DEV support]

### ISSUE THREAD

**Issue by szkomaromi-contactplus** [nav-gov-hu/Online-Invoice#991]
**Környezet / Environment**
[x] https://api-test.onlineszamla.nav.gov.hu

**Hívott API operáció / called API operation**
[] /manageAnnulment
[x] /manageInvoice
[] /queryInvoiceChainDigest
[] /queryInvoiceCheck
[] /queryInvoiceData
[] /queryInvoiceDigest
[] /queryTransactionList
[] /queryTransactionStatus
[] /tokenExchange

**A kérés verziója / version of the request**
[] 1.1
[] 2.0
[x] 3.0

**A requestId értéke / requestId value**
```
3TBEQYZFZCAYCG80
```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**
Úgy tűnik mintha a UNINTENDED_MODIFICATION_DELIVERY_DATE figyelmeztetés akkor is lefutna egy módosító bizonylatra, ha az alapbizonylat teljesítési dátuma valóban megegyezik a módosító bizonylat keltével. Mintha az ellenőrzés csak a módosító bizonylat  invoiceDeliveryDate, invoiceIssueDate elemeit vizsgálná és nem ellenőrizné hozzá az alapbizonylat invoiceDeliveryDate elemét.

*Egyéb tartalom / Additional content*

**Comment by NTCA-supporter** [comment]
Szia @szkomaromi-contactplus !
Köszi a jelzést. Utánakérdezek.
Üdv

**Comment by szkomaromi-contactplus** [comment]
@NTCA-supporter  Sikerült esetleg ránézni erre a problémára?

**Comment by tkelemen73** [comment]
Sziasztok, akkor is jelentkezik a figyelmeztető üzenet, ha ma készítek egy számlát, mai teljesítéssel, majd lestornózom. Tesztrendszerben a számla tranzakció azonosítója: 3UF7NRRSUFXVZMUN illetve a stornó számla, amire jön a figyelmeztetés 3UF7OG7VSSQEXOEU.
Üdv
T.

**Comment by marcipunk** [comment]
Mi is tapasztaljuk ezt az anomáliát, hogy ugynaz napi a sztornó kiállítása és teljesítése, mint az alapbizonylaté. Nagyon sok felhasználó nagyon sokszor fog megijedni ettől a felesleges infótól.

**Comment by szkomaromi-contactplus** [comment]
@NTCA-supporter Ugye erre fogunk választ kapni az Online Számla rendszer 3.17 verziójának élesítése előtt?

**Comment by RvPSc** [comment]
És erre is szeretnénk: https://github.com/nav-gov-hu/Online-Invoice/issues/988

**Comment by renced42** [comment]
Sziasztok!

A problémát megvizsgáltuk, jogos a felvetés, de sajnos van egy rossz hírem. Sajnos a releaseből ez már  már nem tudjuk kivenni, és egy későbbibe tudjuk csak beletenni a javítást. Várhatóan a 3.18.2-be kerül bele. Igyekszünk mihamarabb kiadni a patchet élesre.
Elnézéseteket kérjük. Igyekszünk az ügyfelek felé is kommunikálni.

**Comment by NTCA-supporter** [comment]
Sziasztok!
A mai napon élesedig a 3.17-es verzió, ami tartalmazza ezt az info üzenetet, jelenlegi formájában. Mindenképpen fogunk rá adni javítást, amit jelezni is fogunk, ha tesztelhető.
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!

Átmenetileg inaktiváltuk ezt az INFO üzenetet, teszt rendszeren már tesztelhető. Amíg nem tisztázódik a végleges működés addig kikapcsolva marad, várhatóan jövő héten élesítjük a teszt rendszeren lévő verziót.
Üdv

**Comment by Macskafarka** [comment]
@NTCA-supporter  Helyes. nagyon jó lenne, ha a kreatívság helyett az lebegne mindenki szeme előtt, hogy ez egy kötelező adatszolgáltatás, amelyet jogszabálynak kell szabályoznia. Ezért súlytalanok azok a próbálkozások, hogy mi lenne az adatbázis építőnek az érdeke és az ötletei. MINDENT szó nélkül kell elfogadnia, ami nem ütközik jogszabályba. A rendőr sem tehet igazoltatáskor megjegyzéseket arra, hogy milyen a kocsi színe, vagy tetszik-e neki az autógumi típusa.

**Comment by NTCA-supporter** [comment]
Sziasztok!

Élesen is kint van az inaktiválás.

Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
Zárom az issuet, mivel ki lett kapcsolva az INFO.
Üdv
