### ISSUE TITLE
[Q&A] szállítói számlák lekérdezése

### ISSUE THREAD

**Issue by lazaralexandra** [nav-gov-hu/Online-Invoice#992]
**A kérdés, amire választ szeretnék kapni / The question I would like to be answered**
Rövid és tömör leírása a kérdésnek. / A clear and concise description of the question.
Szállítói számlák lekérdezésénél (INBOUND invoice direction) InvoiceDigestRequest-ben, illetve a QueryInvoiceDataRequest-ben meg kell adni logint/passwordot. Ha több telephely van, és telephelyenként külön technikai azonosítónk, gondolom nem lehet konkrétan megmondani, hogy melyik telephely/technikai azonosítóhoz tartozik a beszállítói számla, ha azonos a vevői adószám, akkor az összes vevői adószámra számlázott számla le fog töltődni a invoicedigestresponse és az invoicedatarequest lekérdezésekkel bármelyik technikai azonosítóval, ahol a vevői számlaszám azonos.

Köszi: Alexandra

**Comment by EPluribusUnum** [comment]
@lazaralexandra , direkt nincs telephely jelölés az xml-ben. Ha a feltöltő nem jelöli meg valamelyik additional mezőben a telephelyet, akkor az eladó adószma, a vevő címe, vagy a feltöltő technikai felhasználó alapján találgathatsz hogy melyik telephelyhez tartozik a számla. A NAV szepontjából egy adózó van, neki a telephely nem számít.
