### ISSUE TITLE
The provided VAT percentage or VAT rate is not allowed

### ISSUE THREAD

**Issue by abin2hats** [nav-gov-hu/Online-Invoice#993]
Hi 

I am getting the following error for the transaction with Transaction Id: 3T9OV3ZOOX497B7N

```
- The provided VAT percentage or VAT rate is not allowed.
–  Tag: InvoiceData/invoiceMain/invoice/invoiceLines/line/lineAmountsNormal/lineVatRate/vatPercentage
–  Value: 0.2
–  Invoice line: 1
- The provided VAT percentage or VAT rate is not allowed.
–  Tag: InvoiceData/invoiceMain/invoice/invoiceLines/line/lineAmountsNormal/lineVatRate/vatPercentage
–  Value: 0.2
–  Invoice line: 2
- The provided VAT percentage or VAT rate is not allowed.
–  Tag: InvoiceData/invoiceMain/invoice/invoiceLines/line/lineAmountsNormal/lineVatRate/vatPercentage
–  Value: 0.2
–  Invoice line: 3
- The provided VAT percentage or VAT rate is not allowed.
–  Tag: InvoiceData/invoiceMain/invoice/invoiceSummary/summaryNormal/summaryByVatRate/vatRate/vatPercentage
–  Value: 0.2
```

Does the 0.2 VAT rate is not allowed? 

https://onlineszamla-test.nav.gov.hu/api/files/container/download/Online%20Invoice%20System%203.0%20Interface%20Specification.pdf

In page: 186 point 14

It says 0.2 VAT rate is allowed

What is the issue here? What are the allowed VAT rates?

**Comment by NTCA-developer** [comment]
Hi @abin2hats,

0.2 VAT rate is allowed only before a specific date. (I don't remember which exactly, but it has historical reasons) If you issue the invoice in the present only 0.05, 0.18, 0.27 VAT rates are valid.

**Comment by abin2hats** [comment]
Thank you @NTCA-developer
