### ISSUE TITLE
The exchange rate for the currency (HUF) is incorrect.

### ISSUE THREAD

**Issue by abin2hats** [nav-gov-hu/Online-Invoice#994]
Hi

I am getting the following error for the transaction with Transaction Id: 3T9S4I15TGC889XG

```
The exchange rate for the currency (HUF) is incorrect.
–  Tag: InvoiceData/invoiceMain/invoice/invoiceHead/invoiceDetail/exchangeRate
–  Value: 357.02
```

What is the issue here?

If the Currency is HUF what will be the value of exchangeRate is it 1?

**Comment by NTCA-developer** [comment]
Hy @abin2hats 

Indeed, if you are reporting an invoice with HUF currency, set the exchangeRate to 1. (as the interface documentation stipulates)

**Comment by abin2hats** [comment]
Thank you @NTCA-developer
