### ISSUE TITLE
INCORRECT_SUMMARY_CALCULATION_VAT_CONTENT_GROSS_AMOUNT_SUMMARY_SIMPLIFIED warn

### ISSUE THREAD

**Issue by sinick2** [nav-gov-hu/Online-Invoice#995]
Többféle áfás, nem áfás, áfamentes áfakulcsokat tartalmazó egyszerűsített számla esetén INCORRECT_SUMMARY_CALCULATION_VAT_CONTENT_GROSS_AMOUNT_SUMMARY_SIMPLIFIED warn-t kapok egy számlára négy esetben is a tesztrendszerben és nem értem, hogy miért. Nem értem, hogy a négy hibához tartozó "érték" számítás hogy jön ki!

Kérhetnék segítséget, hogy mi a hiba?

Tranzakcióazonosító: 3TIFIXPRNJXPKZEC

Köszönöm: sinick2

**Comment by NTCA-supporter** [comment]
Szia @sinick2 !
Megnéztem, és a marginSchemeIndicator esetekben nem jól számolunk.
Javítani fogjuk, jelzem majd ha tesztelhető.
Köszi a jelzést!
Üdv

**Comment by NTCA-supporter** [comment]
Sziasztok!
A 3.20-as verzióban javítva lett ez a bug, élesen van már egy ideje.
Zárom az issuet, ha van még probléma nyissatok újat kérlek.
Üdv
