### ISSUE TITLE
[Q&A] Tévesen sztornózott számlára megoldási javaslat kérése

### ISSUE THREAD

**Issue by Szildiko** [nav-gov-hu/Online-Invoice#999]
Az egyik ügyfél saját fejlesztésű számlázó programban tévesen sztornózott egy egyszerűsített készpénzfizetési számlát (egy dátumost), aminek a dátuma januári volt. A sztornó számla kiállítása és beküldése a NAV rendszerébe 07.27-én történt (szintén egy dátumos 07.27). Pénzmozgás ténylegesen csak januárban volt. Tényleg csak hibázott, nem vette észre, hogy a kurzor a táblázat tetején és nem az alján áll.

Ha a sztornót sztornózzuk, akkor jön a figyelmeztetés, hogy "A hivatkozott alapszámlára korábban már érkezett sztornó okirat (INCONSISTENT_MODIFICATION_DATA_STORNO_ALREADY_EXISTS)", ami igaz is az eseményre, de ez lenne a legegyszerűbb és a felhasználó által is érthető folyamat. 

Mi lenne a tényleges helyes megoldás arra, hogy a januári számla "újra éles" legyen. Kell-e a téves sztornó számlát elküldeni az ő ügyfelének?

Előre is köszönöm a segítséget!

**Comment by topybear** [comment]
A sztornó számla technikai érvénytelenítése? 
Nem mondom, hogy betű szerint erre való - baromira nem -, de ezzel a sztornó visszavonásra kerül és megmarad az eredeti számla. 
Persze egyesekben felmerülhet az a gonosz kérdés, hogy egy számlázó rendszerben egy sztornózott számla hogyan lesz egyszercsak nem sztornózott... :)

**Comment by Szildiko** [comment]
Így van, akkor bennem felmerül, hogy a kinyomtatott stornó számlával is mi lesz, mert attól ott van papíron. Nem téphetem össze, nem húzhatom át, attól hogy a NAV rendszerében technikai érvénytelenítést adok rá. Ha technikai érvénytelenítés, akkor megint hajlok arra, hogy a stornót stornózni és mindkettőt technikai érvényteleníteni. 

Utóbbit elmagyarázni egy szaki idős személynek nem lenne egyszerű és nem gondolnám, hogy a számlázó ügyfélszolgálatának kéne. Sokan már a jelszavukat se tudják a felülethez. A számlázó program jelenleg nem tudja a "gép-gép" közti technikai érvénytelenítést. 

Felhívtam a NAV általános ügyfélszolgálatát, ott azt mondták, hogy újra ki kell állítani a januári számlát és el kell küldeni mind a stornót és az újat az ügyfélnek. Én ezt összezavaró és felesleges adminisztrációnak és költségnek érzem, ha pl még postán küldi a számlákat. Egy három dátumos számlánál még talán kivitelezhető volna, de egy egy dátumosnál, ahol minden számlának eltérő lesz a napja, mert nem fért bele egy napba és pénzmozgás sincs mögötte.... Nem értek egyet vele. Tényleg ezt kéne?

**Comment by betasofthu** [comment]
A "stornót stornózni" nem lehet. 
Szerintem ne csinálj technika érvénytelenítést, mert az "_a technikai érvénytelenítésekre
vonatkozó adatok a kockázatelemző rendszer bemenő adataként használhatók._" Simán ki kell állítani egy új számlát, ami az eredetit pótolja, akkori teljesítési dátummal. A pénzmozgás érdektelen.

**Comment by renced42** [comment]
Kedves @Szildiko Hogy a klasszikust idézzem, ha elutaztál akkor el vagy utazva. Vagyis ha egy számlát lesztornóztál, akkor az le van sztornózva. Nincs olyan hogy sztornót sztornózol. Ebben az esetben új számlát kell kiállítani az ügyfélnek. 

A technikai érvénytelenítésnek sincs helye, hiszen azt egyébként hibás nem pedig téves adatszolgáltatásokra kell alkalmazni.

**Comment by Szildiko** [comment]
Köszönöm a válaszokat, akkor a stornó marad ahogy van 07.27-el. Aztán kiállít egy NEM egyszerűsített készpénzes számlát, tehát 3 dátumosat, ott beírja az eredeti teljesítést.

Hogy néz ki a könyvelés?

A januári pénztár jelentésben ott lesz a számla, hogy bejött a pénz.
07.27-ei pénztár jelentésen mi fog szerepelni (a stornónál)? Vagy azt ne pénztárba könyvelje a könyvelő, hanem azt is analitikusan és majd kompenzálja össze az új számlával?
Ha így van, akkor a számlázó átadása a könyvelő programoknak ilyen esetben felejtős és jobb ha ezeket kézzel könyveli a könyvelő.

**Comment by Macskafarka** [comment]
@Szildiko  Itt csak a számlaadat-szolgáltatással kapcsolatos dolgokra lehet válaszokat kapni.

**Comment by Macskafarka** [comment]
A könyvelés ilyen esetben egy jó ERP rendszerben ki van találva. Ezt a tudást veszi meg az ügyfél.  Számos lehetőség van: Vagy olyan ügyviteli rendszert kel használni, ami ezt képes kezelni, vagy lejjebb kell adni az igényből, esetleg nem kell annyi hibát elkövetni, vagy a pénztár jelentés zárása előtt észrevenni a hibát, vagy pénztártól való távozás után NINCS korrekció.
